### ISSUE TITLE
Log storage for long periods of time.

### ISSUE THREAD

**Issue by ixiaoyi93** [grafana/loki#10003]
**Is your feature request related to a problem? Please describe.**
From what I know about loki, it's not suitable for storing logs for long periods of time. Again, this is a very common requirement in real production environments.

**Describe the solution you'd like**
Support long term storage or provide a solution to this requirement.

**Describe alternatives you've considered**
Considering adjusting the `period: 168h` parameter directly, does this have any effect?
```
schema_config:
  configs:
  - from: 2020-05-15
    object_store: alibabacloud
    schema: v11
    index:
      prefix: loki_index_
      period: 168h
```

**Additional context**
