### ISSUE TITLE
Simple scalable deployment mode random restarts

### ISSUE THREAD

**Issue by chg-dio** [grafana/loki#10001]
**Describe the bug**
I run Loki in simple scalable deployment mode as statefulset with NFS storage to store the chunks and dedicated (per pod) storage to store the TSDB index and WAL directory - since I had problems with WAL and TSDB index in shared storage and multiple write/read instances running.

The deployment is running but I face random restarts I am not able to track down even in debugging mode. After some time the ready state gives an 503 status and the pod will be restarted by kubernetes. Maybe I miss something in the logs someone else can find. Below is a log during a write instance crash:

I removed some personal Logs with level=info, since I don't think they are part of the problem.

The debug log can be found here (it is too long for this issue):
https://www.logpasta.com/paste/5a8b90c3-7d6b-4a29-b633-081fee91a068

![grafik](https://github.com/grafana/loki/assets/123104999/e227b505-3e00-4838-967a-40e9f9cfa64d)

**To Reproduce**
1. Deploy Loki in Kubernetes with the files provided below

<details>
  <summary>Write statefulset</summary>

```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-write
  namespace: logging
  labels:
    app: loki-write
spec:
  revisionHistoryLimit: 1
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: loki-write
  serviceName: loki-write-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loki-write
      annotations:
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        fsGroup: 10001
        runAsGroup: 10001
        runAsUser: 10001
      containers:
        - name: loki
          image: docker.io/grafana/loki:2.8.2
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/loki/loki.yaml"
            - "-target=write"
          volumeMounts:
            - name: config
              mountPath: "/etc/loki"
            - name: loki-data
              mountPath: "/data"
              subPath: data
              readOnly: false
            - name: loki-wal
              mountPath: "/wal"
              subPath: wal
              readOnly: false
            - name: loki-index
              mountPath: "/index"
              subPath: index
              readOnly: false
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: memberlist
              containerPort: 7946
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: loki
            defaultMode: 0755
            items:
              - key: loki.yaml
                path: loki.yaml
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-data
            readOnly: false
  volumeClaimTemplates:
    - spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: rook-cephfs
        resources:
          requests:
            storage: 2Gi
      metadata:
        name: loki-wal
    - spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: rook-cephfs
        resources:
          requests:
            storage: 2Gi
      metadata:
        name: loki-index

```
</details>

<details>
  <summary>Read statefulset</summary>

```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-read
  namespace: logging
  labels:
    app: loki-read
spec:
  revisionHistoryLimit: 1
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: loki-read
  serviceName: loki-read-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loki-read
      annotations:
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        fsGroup: 10001
        runAsGroup: 10001
        runAsUser: 10001
      containers:
        - name: loki
          image: docker.io/grafana/loki:2.8.2
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/loki/loki.yaml"
            - "-target=read"
          volumeMounts:
            - name: config
              mountPath: "/etc/loki"
            - name: loki-data
              mountPath: "/data"
              subPath: data
              readOnly: false
            - name: loki-index
              mountPath: "/index"
              subPath: index
              readOnly: false
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: memberlist
              containerPort: 7946
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: loki
            defaultMode: 0755
            items:
              - key: loki.yaml
                path: loki.yaml
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-data
            readOnly: false
        - name: loki-index
          persistentVolumeClaim:
            claimName: loki-index
            readOnly: false

```
</details>

<details>
  <summary>Write service</summary>

```
---
apiVersion: v1
kind: Service
metadata:
  name: loki-write-headless
  namespace: logging
  labels:
    name: loki-write-headless
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"
spec:
  selector:
    app: loki-write
  ports:
  - protocol: TCP
    port: 3100
    name: http-metrics
    targetPort: 3100
  - protocol: TCP
    port: 7946
    targetPort: 7946
    name: memberlist
  type: ClusterIP

```
</details>

<details>
  <summary>Read service</summary>

```
---
apiVersion: v1
kind: Service
metadata:
  name: loki-read-headless
  namespace: logging
  labels:
    name: loki-read-headless
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"
spec:
  selector:
    app: loki-read
  ports:
  - protocol: TCP
    port: 3100
    name: http-metrics
    targetPort: 3100
  - protocol: TCP
    port: 7946
    targetPort: 7946
    name: memberlist
  type: ClusterIP

```
</details>

<details>
  <summary>Loadbalancer (you need to change the image if you want to use this file, since I use my own Image)</summary>

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-loadbalancer
spec:
  selector:
    matchLabels:
      app: loki-loadbalancer
  replicas: 1
  template:
    metadata:
      labels:
        app: loki-loadbalancer
    spec:
      containers:
      - image: docker.company.com/docker/nginx:spa-secure
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
                - sleep
                - "10"
        name: loki-loadbalancer
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 3100
          name: loki
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 256Mi
          requests:
            cpu: 5m
            memory: 8Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx
          readOnly: true
          name: nginx-conf
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: gitlab-registry-docker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 101
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-conf
        configMap:
          name: loki
          items:
            - key: nginx.conf
              path: nginx.conf

```
</details>

<details>
  <summary>Loadbalancer service</summary>

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: loki-loadbalancer
  name: loki-loadbalancer
  namespace: logging
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  - port: 3100
    protocol: TCP
    targetPort: 3100
    name: loki
  selector:
    app: loki-loadbalancer
  type: ClusterIP
status:
  loadBalancer: {}
```
</details>

<details>
  <summary>PVC</summary>

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: logging
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-index
  namespace: logging
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs

```
</details>

<details>
  <summary>Configmap</summary>

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  namespace: logging
  labels:
    name: loki
data:
  loki.yaml: |
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 120h
    common:
      path_prefix: /data
      storage:
        filesystem:
          chunks_directory: /data/chunks
          rules_directory: /data/rules
      compactor_address: http://loki-loadbalancer:3100
    compactor:
      working_directory: /data/compactor
      shared_store: filesystem
    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      max_outstanding_per_tenant: 2048
    ingester:
      lifecycler:
        join_after: 10s
        observe_period: 5s
        ring:
          replication_factor: 3
          kvstore:
            store: memberlist
        final_sleep: 0s
      chunk_idle_period: 1m
      wal:
        enabled: true
        dir: /wal
        checkpoint_duration: 15m
      max_chunk_age: 1m
      chunk_retain_period: 30s
      chunk_encoding: snappy
      chunk_target_size: 1.572864e+06
      chunk_block_size: 262144
      flush_op_timeout: 10s
    limits_config:
      max_cache_freshness_per_query: '10m'
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 30m
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      # parallelize queries in 15min intervals
      split_queries_by_interval: 15m
    query_range:
      # make queries more cache-able by aligning them with their step intervals
      align_queries_with_step: true
      max_retries: 5
      parallelise_shardable_queries: true
      cache_results: true
    ruler:
      enable_api: true
      wal:
        dir: /wal/ruler-wal
      storage:
        type: local
        local:
          directory: /data/rules
      rule_path: /tmp/prom-rules
      remote_write:
        enabled: true
        clients:
          local:
            url: http://prometheus:9090/api/v1/write
            queue_config:
              # send immediately as soon as a sample is generated
              capacity: 1
              batch_send_deadline: 0s
    schema_config:
      configs:
        - from: "2023-07-01"
          index:
            period: 24h
            prefix: index_
          object_store: filesystem
          schema: v12
          store: tsdb
    server:
      http_listen_address: 0.0.0.0
      grpc_listen_address: 0.0.0.0
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: debug
    storage_config:
      tsdb_shipper:
        active_index_directory: /index/tsdb-index
        cache_location: /index/tsdb-cache
        shared_store: filesystem
      filesystem:
        directory: /data/chunks
    table_manager:
      retention_deletes_enabled: true
      retention_period: 120h
    memberlist:
      join_members: ["loki-read-headless", "loki-write-headless"]
      dead_node_reclaim_time: 30s
      gossip_to_dead_nodes_time: 15s
      left_ingesters_timeout: 30s
      bind_addr: ['0.0.0.0']
      bind_port: 7946
      gossip_interval: 2s
    querier:
      query_ingesters_within: 2h
    query_scheduler:
      max_outstanding_requests_per_tenant: 1024
  nginx.conf: |
    error_log  /var/log/nginx/error.log notice;
    pid        /tmp/nginx.pid;
    worker_rlimit_nofile 8192;

    events {
        worker_connections  4096;  ## Default: 1024
    }

    http {
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp_path;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;      
      access_log   /var/log/nginx/access.log  main;
      sendfile     on;
      tcp_nopush   on;

      upstream read {
        server loki-read-headless:3100;
      }

      upstream write {
        server loki-write-headless:3100;
      }

      upstream cluster {
        server loki-read-headless:3100;
        server loki-write-headless:3100;
      }

      server {
        listen 8080;
        listen 3100;

        location = /ring {
            proxy_pass       http://cluster$request_uri;
        }

        location = /memberlist {
            proxy_pass       http://cluster$request_uri;
        }

        location = /config {
            proxy_pass       http://cluster$request_uri;
        }

        location = /metrics {
            proxy_pass       http://cluster$request_uri;
        }

        location = /metrics-read {
            proxy_pass       http://read/metrics;
        }

        location = /metrics-write {
            proxy_pass       http://write/metrics;
        }

        location = /ready {
            proxy_pass       http://cluster$request_uri;
        }

        location = /loki/api/v1/push {
            proxy_pass       http://write$request_uri;
        }

        location = /loki/api/v1/tail {
            proxy_pass       http://read$request_uri;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location ~ /loki/api/.* {
            proxy_pass       http://read$request_uri;
        }
      }

      include /etc/nginx/conf.d/*.conf;

    }

```
</details>

**Expected behavior**
Loki runs without random restarts

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: statefulset (self written)
