### ISSUE TITLE
IPv6 lifecycler option doesn't recognized

### ISSUE THREAD

**Issue by gillg** [grafana/loki#10088]
**Describe the bug**
Using Loki 2.8.3 the option `ingester.lifecycler.enable_inet6` is not recognized.

I'm curently using a custom loki build `quay.io/shwetaap/loki:dev` (cc @shwetaap ) which was based on the important changes made in April inside dskit.
I would finaly use an official loki release, but everytime I tried I face the error above:
```
field enable_inet6 not found in type ring.LifecyclerConfig. Use `-config.expand-env=true` flag if you want to expand environment variables in your config file
```

According to the changelog and the doc https://github.com/grafana/loki/blob/60e33e37056d2ffe30e9098763b130c5f979800a/docs/sources/configure/_index.md?plain=1#L1395 it should work since the version 2.8.2...

**To Reproduce**
* Use loki 2.8.3 
* use a config like that:
```
distributor:
  ring:
    instance_addr: loki-loki-distributed-distributor # Trick to make work the IPv6, because loki can't detect correctly it's pod IP
    kvstore:
      store: memberlist

memberlist:
  bind_addr: # IPV6
    - '::' # Trick to force using IPV6

ingester:
  lifecycler:
    enable_inet6: true # IPV6

    ring:
      kvstore:
        store: memberlist
      replication_factor: 2
```
