### ISSUE TITLE
Windows Version of Promtail -  unable to overwrite the logline extracted timestamp with the log created timestamp

### ISSUE THREAD

**Issue by mbsarathchandra** [grafana/loki#10161]
**Describe the bug**
Windows Version of Promtail is unable to overwrite the logline extracted timestamp with the log created timestamp when using the timestamp stage in the promtail config. This causes the historical data show up in grafana with the timestamp when it was read by Promtail and not when the log line was created.

**To Reproduce**
1. Started Loki (2.8.2) installed on Linux Server, Time zone for OS CST
2. Started Promtail (2.8.2) installed on Windows Server, Time zone for OS CST
3. View the log data using Grafana, version 9.3.6.

Sample Log Lines:
[2023-07-03 11:11:00.6618057] [ 30] [DEBUG] [Common.Utility.LogScope] - [Started [Service.TestMethod1]]
[2023-07-03 11:12:00.7128080] [ 30] [DEBUG] [Common.Utility.LogScope] - [Finished [Service.TestMethod1] in 36 ms]
[2023-07-03 12:14:16.4805761] [ 61] [INFO ] [BusinessLogic.MessageHandler.OutageEvent] - [Message received:
BusinessEntities.QueueMessageType.OutageEventMessage]
[2023-07-03 11:11:00.6618057] [ 30] [DEBUG] [Common.Utility.LogScope] - [Started [Service.TestMethod2]]
[2023-07-03 11:12:00.7128080] [ 30] [DEBUG] [Common.Utility.LogScope] - [Finished [Service.TestMethod2] in 36 ms]

Promtail Scrape Config: (To harvest the logs)
scrape_configs:
- job_name: Test.Project.6
  static_configs:
    - targets:
        - localhost
    - labels:
        Environment: UAT
        HostIP: 10.10.10.10
        HostName: ServerName
        ServerType: WebServices
        ProjectName: Test.Project.6
        __path__: D:\Program Files\AppSourceCode\Logs\Test.Project.6\TimeStampLogTest.log    
  pipeline_stages:
    - multiline:
        firstline: '^\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'
        max_wait_time: 5s 
        max_lines: 10000  
    - regex:
        expression: '^\[(?P<LogTimestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{7})\] (?P<LogThreadId>\[.*\]) (?P<LogLevel>\[.*\]) (?P<ClassName>\[.*\]) - (?P<LogMessage>\[(?s:.*)\])'	  
    - labels:
        LogTimestamp:
        LogThreadId:
        LogLevel:
        ClassName:
    - timestamp:
        source: LogTimestamp      
        format: 2023-07-03 15:15:00.6618057
        location: "America/Chicago"    
    - output:
        source: LogMessage

**Expected behavior**
In Grafana, when I query on the historical timestamp I should be able to see the logs. But when I query on the latest timestamp I see the logs. Unable to build valid Time Series Graph for the log occurrences, because the time series graph by default uses the Time Field of Loki data. The time filed shows the time when the log was extracted. This cause invalid graph for the log occurrences data.

**Environment:**
 - Infrastructure: 
      - Loki (2.8.2) installed on Linux Server, Time zone for OS CST
      -  Promtail (2.8.2) installed on Windows Server, Time zone for OS CST
 - Deployment tool: Manual

**Screenshots, Promtail config, or terminal output**
Grafana Screen shot of the timestamp for the logs.
![image](https://github.com/grafana/loki/assets/48734995/d3b7f386-bcbc-4ae0-9f9e-a75e4b20e990)

I have tried all different formats and combinations for the timestamp stage and no change in the timestamp data in Loki. I have seen lot of posts on the timestamp update, but all the users were using the linux version of the promtail and not the windows version. This is main reason for me to report this issue as a bug for Promtail Windows version. Any help is greatly appreciated on this issue.

Thanks
Sarath

**Comment by mbsarathchandra** [comment]
Hi ,
Checking if you guys have any update on this issue / bug posted. 

Thanks

**Comment by tonyswu** [comment]
There are several errors in your configuration:
1. Your regex is incorrect and does not match your log line.
2. You need to use capture group in order to extract information.
3. Your timestamp format is in the wrong format.
4. You are trying to reference labels that don't exist.

I'd recommend something like this (not actually tested):

```
- regex:
    expression: '^\[(?P<LogTimestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}.\d{7})\] \[(?P<LogThreadId>.*)\] \[(?P<LogLevel>.*)\] \[(?P<ClassName>.*)\] - \[(?:(.*))\]'

- labels:
    # You don't actually want timestamp as a label.
    # LogTimestamp:
    LogThreadId:
    LogLevel:
    ClassName:

- timestamp:
    source: LogTimestamp
    format: '2006-01-02 15:04:05.0000000'
    location: "America/Chicago"

# Since you aren't capturing LogMessage you don't need this.
# - output:
#    source: LogMessage
```
