### ISSUE TITLE
Loki/Promtail : after running normally for 1 or 2 hours, some logs are not being ingested

### ISSUE THREAD

**Issue by SmartGuyy** [grafana/loki#10197]
**Describe the bug**
It's been few weeks now that we noticed some logs are not being ingested in real-time by Loki for some applications (random). On startup it works normally and after some time some logs are not ingested anymore. After few hours we suddenly see a peak of volume for application log and basically all logs that were not ingested in real-time for a specific time frame are suddenly being ingested all at once.

**To Reproduce**
1. Start Loki-stack (chart) with Promtail & Loki enabled only
2. Observe logs being retrieved normally every minutes for all applications
3. After about 90 to 120 minutes : observe logs not being available in Loki for some applications, while some remain available in real time
4. (Optional) Restart DaemonSet of Promtail : logs are now correctly being flushed and ingested in Loki
5. (Optional) Does not restart anything and notice some logs are suddenly ingested from 1 to 8 hours after with a huge amount of entries (all logs from the time frame it wasn't proceeded).

**Expected behavior**
Loki should constantly ingest every minute the logs (in real time) for all applications, like it is supposed to do out of the box.

**Environment:**
 - Infrastructure: RKE Kubernetes 1.24.13
 - Deployment tool: Loki-stack helm chart (Loki & Promtail enabled)
 - Versions : Loki 2.8.3 & Promtail 2.8.3
 - Active cluster with 9 workers, more than 200 pods sending millions of entries every hour

**Screenshots, Promtail config, or terminal output**
- No errors or warning are being sent either in Loki or Promtail at the time we stop receiving the logs for some applications (debug mode doesn't give much information too)
- On a 24 hours timeframe, the only errors i get is from queries that are being ran to the frontend (unrelated)
- Config (values) : 
```
config:
  analytics:
    reporting_enabled: false # Toggle for analytics reporting
  compactor:
    retention_enabled: true # Toggle for retention in the compactor
  frontend:
    compress_responses: true # Toggle for response compression
    log_queries_longer_than: 5s # Threshold for logging slow queries
    max_outstanding_per_tenant: 4096 # Limit for outstanding requests per tenant
  ingester:
    chunk_block_size: 262144 # Uncompressed size of a chunk block
    chunk_idle_period: 3m # Time before idle chunks are flushed
    chunk_target_size: 2097152 # Target compressed size for chunks
    concurrent_flushes: 64 # Number of concurrent flushes
    flush_check_period: 10s # Frequency of flush checks
    flush_op_timeout: 15m # Timeout for flush operations
    lifecycler:
      heartbeat_period: 10s # Frequency of heartbeats
      heartbeat_timeout: 2m # Timeout for heartbeats
      num_tokens: 256 # Number of tokens for distribution
    max_chunk_age: 1h # Maximum age of a chunk in memory
    max_transfer_retries: 0 # Number of retries for chunk transfers
    wal:
      checkpoint_duration: 2m # Frequency of checkpoints
      enabled: true # Toggle for WAL
      flush_on_shutdown: true # Toggle for flushing chunks on shutdown
      replay_memory_ceiling: 8GB # Memory ceiling for WAL replay
  limits_config:
    cardinality_limit: 200000 # Limit for unique series per user
    max_label_value_length: 20480 # Maximum length of label value
    max_label_name_length: 10240 # Maximum length of label name
    max_label_names_per_series: 300 # Maximum number of label names per series
    ingestion_burst_size_mb: 40 # Burst size for ingestion rate
    ingestion_rate_mb: 80 # Maximum ingestion rate per user
    max_concurrent_tail_requests: 100000 # Limit for concurrent tail requests
    max_entries_limit_per_query: 15000 # Limit for entries per query
    max_query_length: 0h # Maximum query length
    max_query_parallelism: 32 # Maximum query parallelism
    max_streams_per_user: 100000 # Maximum streams per user
    per_stream_rate_limit: 20MB # Rate limit per stream
    per_stream_rate_limit_burst: 40MB # Burst size for per stream rate limit
    retention_period: ${LOKI_RETENTION_PERIOD} # Retention period for logs
    split_queries_by_interval: 24h # Interval for splitting queries
  query_scheduler:
    max_outstanding_requests_per_tenant: 4096 # Limit for outstanding requests per tenant
  querier:
    max_concurrent: 100000 # Maximum concurrent queries
    query_ingesters_within: 0 # Time range for querying ingesters
    tail_max_duration: 24h # Maximum duration for tailing logs
  server:
    grpc_server_max_recv_msg_size: 104857600 # Maximum gRPC receive message size
    grpc_server_max_send_msg_size: 104857600 # Maximum gRPC send message size
    grpc_server_max_concurrent_streams: 100000 # Set max concurrent streams (0 being no limit)
    log_level: info # Log level
  table_manager:
    retention_deletes_enabled: false # Toggle for retention deletes
    retention_period: 0s # Retention period for table manager
```
