### ISSUE TITLE
Helm Chart - support topologySpreadConstraints

### ISSUE THREAD

**Issue by rubenvw-ngdata** [grafana/loki#10205]
**Is your feature request related to a problem? Please describe.**
I try to configure a multi zone setup and want to use topology spread constraints to do so, but there is no support for any of the statefullsets/deployments

**Describe the solution you'd like**
This could either be a service specific configuration to allow to configure topologySpreadConstraints in the values.yaml configuration

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by aschaber1** [comment]
I believe they currently achieve this via `podAntiAffinity`:
https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L780-L786

I agree though that a `topologySpreadConstraints` would be nicer :)

**Comment by rubenvw-ngdata** [comment]
This is currently supported for a lot of the services, but not for the singleBinary setup.

**Comment by mvink-guida** [comment]
Still missing this option on the singleBinary with objectStorage, if you want to run three replica's on two zones/nodes, you need `topologySpreadConstraints` to make sure autoscaler is able to scale back to the desired of two zones/nodes.
Our setup has fallbacks for a 3rd zone, but needs to scale back to two zones/nodes, which you can accomplish with `topologySpreadConstraints` 

```
                          - maxSkew: 2
                            minDomains: 2
                            topologyKey: topology.kubernetes.io/zone
                            whenUnsatisfiable: DoNotSchedule
                            labelSelector:
                              matchLabels:
                                app.kubernetes.io/component: single-binary
                                app.kubernetes.io/instance: loki
                            matchLabelKeys:
                              - controller-revision-hash
```
