### ISSUE TITLE
Promtail not working with docker.sock

### ISSUE THREAD

**Issue by pavelforever** [grafana/loki#10224]
**Describe the bug**
Promtail can't get logs from docker.sock. I get message in grafana 'Data source connected, but no labels were received. Verify that Loki and Promtail are correctly configured.' Struggling with promtail for a several days, but with no success

**To Reproduce**
To reproduce you can use my prepared repository - https://github.com/pavelforever/grafana-promtail-loki-socks

But here are main settings:
docker-compose.yml
```
version: "3.7"
networks:
  loki:
services:
  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki
  promtail:
    user: root
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    user: "0"
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki
```

promtail-config.yml
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
#docker logs
scrape_configs:
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: [flog]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
```

loki-config.yml
```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
ruler:
  alertmanager_url: http://localhost:9093
```

**Expected behavior**
I expect to successfully retrieve the logs in grafana

**Environment:**
 - Infrastructure: ubuntu
 - Deployment tool: docker compose

**Screenshots, Promtail config, or terminal output**
![chrome_fPGPFlwVrb](https://github.com/grafana/loki/assets/9401132/674de98c-9dc6-4450-a51c-7b632fd46150)
![chrome_1dok3KstXj](https://github.com/grafana/loki/assets/9401132/ded8ca04-700a-472a-9656-a6206038c329)
