### ISSUE TITLE
can't not apply config in storage_config['index_queries_cache_config']

### ISSUE THREAD

**Issue by lovesharepc** [grafana/loki#10237]
can't not apply config in storage_config['index_queries_cache_config']

**Describe the bug**
my config

```
storage_config:
  index_queries_cache_config:
    memcached_client:
      addresses: memcached:11211
      timeout: 100ms
      max_item_size: 104857600
      update_interval: 1m
    fifocache:
      max_size_bytes: 100MB
      ttl: 1h0m0s
```

when loki up, use api check config
fount config not apply
![image](https://github.com/grafana/loki/assets/1570732/53b49a2b-8b01-422f-9fa6-2d07e773cf82)

**Environment:**
docker with grafana/loki:2.8.4 image

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
