### ISSUE TITLE
[helm-loki-5.X.X (helm-loki-5.10.0)] IRSA (ServiceAccount+IAM) does not work - Error: SignatureDoesNotMatch

### ISSUE THREAD

**Issue by rafaelpissolatto** [grafana/loki#10239]
**Describe the bug**
We are trying to use helm-loki (we tried with many versions like helm-loki-5.10.0) with distributed components (read, write, backend, etc) and with IRSA on AWS EKS (service account + IAM role annotation linked) but we are receiving and found an error `SignatureDoesNotMatch` in all components and the Loki does not write anything in the bucket. If we pass the `AWS Keys` the Loki works as expected (same AWS policy). 

Other tests (without positive effect):
- Changed the signature version to `v2` where `the default is `v4` (but this version was deprecated by AWS: https://docs.aws.amazon.com/AmazonS3/latest/API/bucket-policy-s3-sigv4-conditions.html)
- Created a pod (test) and use the same ServiceAccount (the pod with awscli worked fine - put, get, delete, everything worked), Loki did not.
- Diff versions
- Debug mode shows the same error (nothing more)

**To Reproduce**
1. Install Helm-Loki (helm-loki-5.8.x/helm-loki-5.9.x/helm-loki-5.10.x)
2. Configure values to create ServiceAccount and add necessary EKS labels (required for IRSA/IAM)
3. Configure values to use AWS S3 without AWS secretKey (to use IAM role linked on the ServiceAccount) - loki.storage.s3.secretAccessKey and loki.storage.s3.accessKeyId as null (or use default settings) 

**Expected behavior**
Use Loki with IRSA to use AWS S3 bucket to store (ServiceAccount + AWS IAM Role)

**Environment:**
 - Deployment tool: Terraform/Helm
 - Infrastructure: Kubernetes (AWS EKS) 

**Screenshots, Promtail config, or terminal output**

- Log:
```verilog
level=info ts=2023-08-13T21:10:36.341468164Z caller=module_service.go:82 msg=initialising module=ingester-querier
level=info ts=2023-08-13T21:10:36.341748307Z caller=compactor.go:332 msg="waiting until compactor is JOINING in the ring"
level=info ts=2023-08-13T21:10:36.341751687Z caller=ringmanager.go:186 msg="waiting until index gateway is JOINING in the ring"
level=info ts=2023-08-13T21:10:36.341766167Z caller=compactor.go:336 msg="compactor is JOINING in the ring"
level=info ts=2023-08-13T21:10:36.356644496Z caller=memberlist_client.go:595 msg="joining memberlist cluster succeeded" reached_nodes=6 elapsed_time=15.542506ms
level=info ts=2023-08-13T21:10:37.342245319Z caller=compactor.go:346 msg="waiting until compactor is ACTIVE in the ring"
level=info ts=2023-08-13T21:10:37.476541042Z caller=compactor.go:350 msg="compactor is ACTIVE in the ring"
level=info ts=2023-08-13T21:10:39.901872952Z caller=ringmanager.go:190 msg="index gateway is JOINING in the ring"
level=info ts=2023-08-13T21:10:39.902072634Z caller=ringmanager.go:199 msg="waiting until index gateway is ACTIVE in the ring"
level=info ts=2023-08-13T21:10:40.011476841Z caller=ringmanager.go:203 msg="index gateway is ACTIVE in the ring"
level=info ts=2023-08-13T21:10:40.011561382Z caller=module_service.go:82 msg=initialising module=store
level=info ts=2023-08-13T21:10:40.011609942Z caller=module_service.go:82 msg=initialising module=index-gateway
level=info ts=2023-08-13T21:10:40.011611772Z caller=module_service.go:82 msg=initialising module=ruler
level=info ts=2023-08-13T21:10:40.011637042Z caller=ruler.go:499 msg="ruler up and running"
level=info ts=2023-08-13T21:10:40.011717793Z caller=loki.go:500 msg="Loki started"
level=error ts=2023-08-13T21:10:40.163862096Z caller=ruler.go:542 msg="unable to list rules" err="SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: B7000000000000000, host id: K+ZLyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
level=info ts=2023-08-13T21:10:44.387234815Z caller=table_manager.go:190 msg="downloading all files for table loki_index_19582"
ts=2023-08-13T21:10:44.548703647Z caller=spanlogger.go:85 table-name=loki_index_19582 user-id=fake org_id=fake level=info msg="downloaded index set at query time" duration=161.186619ms
ts=2023-08-13T21:10:44.564693097Z caller=spanlogger.go:85 table-name=loki_index_19582 org_id=fake level=info msg="downloaded index set at query time" duration=15.914759ms
level=error ts=2023-08-13T21:11:40.035178939Z caller=ruler.go:542 msg="unable to list rules" err="SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: ATB0000000000000, host id: 8Wl9xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
level=error ts=2023-08-13T21:12:40.038372125Z caller=ruler.go:542 msg="unable to list rules" err="SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: SWG0000000000000, host id: vTToxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
level=error ts=2023-08-13T21:13:40.039006749Z caller=ruler.go:542 msg="unable to list rules" err="SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: YFQ0000000000000, host id: guE11xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
level=error ts=2023-08-13T21:14:40.037110445Z caller=ruler.go:542 msg="unable to list rules" err="SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: TBD0000000000000, host id: b4G1Ixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
level=info ts=2023-08-13T21:15:36.323230249Z caller=table_manager.go:223 msg="syncing tables"
ts=2023-08-13T21:15:36.32330742Z caller=spanlogger.go:85 level=info msg="building index list cache"
ts=2023-08-13T21:15:36.376923378Z caller=spanlogger.go:85 level=info msg="index list cache built" duration=53.604728ms
level=info ts=2023-08-13T21:15:36.376985709Z caller=table_manager.go:262 msg="query readiness setup completed" duration=2.5µs distinct_users_len=0
```

- ConfigMap generated by Helm:
```yaml
apiVersion: v1
kind: ConfigMap
data:
  config.yaml: |
    analytics:
      reporting_enabled: false
    auth_enabled: false
    common:
      compactor_address: "loki-backend"
      path_prefix: /var/loki
      replication_factor: 3
      storage:
        s3:
          bucketnames: bucket-name
          insecure: false
          region: <aws-region>
          s3: s3://<aws-region>
          signature_version: v4
    frontend:
      scheduler_address: query-scheduler-discovery.namespace.svc.cluster.local.:9095
    frontend_worker:
      scheduler_address: query-scheduler-discovery.namespace.svc.cluster.local.:9095
    index_gateway:
      mode: ring
    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
    memberlist:
      join_members:
        - loki-memberlist
    query_range:
      align_queries_with_step: true
    ruler:
      storage:
        s3:
          bucketnames: bucket-name/ruler
          insecure: false
          region: <aws-region>
          s3: s3://<aws-region>
          s3forcepathstyle: false
        type: s3
    runtime_config:
      file: /etc/loki/runtime-config/runtime-config.yaml
    schema_config:
      configs:
        - from: "2022-01-11"
          index:
            period: 24h
            prefix: loki_index_
          object_store: s3
          schema: v12
          store: boltdb-shipper
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
    storage_config:
      aws:
        s3: s3://<aws-region>/bucket-name
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/boltdb-cache
        shared_store: s3
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0
```

- ServiceAccount generated by Helm:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: <namespace>
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/<aws-role-name>
    meta.helm.sh/release-name: loki
    meta.helm.sh/release-namespace: <namespace>
  labels:
    app.kubernetes.io/instance: loki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: loki
    app.kubernetes.io/version: v5.10.0
    helm.sh/chart: loki-5.10.0
automountServiceAccountToken: true
```

**Comment by rafaelpissolatto** [comment]
As feedback on this, it was caused by a misconfiguration in the IAM policy (S3) attached to the IAM role used by the Loki service account that did not match the "bucket name/path", specially for:

```yaml
    ruler:
      storage:
        s3:
          bucketnames: bucket-name/ruler
```

And caused by these inputs in the Helm values:

```yaml
loki:
  storage:
    type: "s3"
    s3:
      region: eu-central-1
    bucketNames:
      chunks: <bucket name>/chunks
      ruler: <bucket name>/ruler
      admin: <bucket name>/admin
```
To avoid making adjust on the S3 policy, I did:

```yaml
    bucketNames:
      chunks: <bucket name>
      ruler: <bucket name>
      admin: <bucket name>
```

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ListObjectsInBucket",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::bucket-name",
                "arn:aws:s3:::bucket-name/*"
            ]
        }
    ]
}
```

**Comment by rafaelpissolatto** [comment]
As feedback on this, it was caused by a misconfiguration in the IAM policy (S3) attached to the IAM role used by the Loki service account that did not match the "bucket name/path", specially for:

Config generated (after deployment of Helm)

```yaml
    ruler:
      storage:
        s3:
          bucketnames: bucket-name/ruler
```

And caused by these inputs in the Helm values:

```yaml
loki:
  storage:
    type: "s3"
    s3:
      region: us-east-1
    bucketNames:
      chunks: <bucket name>/chunks
      ruler: <bucket name>/ruler
      admin: <bucket name>/admin
```
To avoid making adjust on the S3 policy, I did:

```yaml
loki:
  storage:
    type: "s3"
    s3:
      region: us-east-1
    bucketNames:
      chunks: <bucket name>
      ruler: <bucket name>
      admin: <bucket name>
```

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ListObjectsInBucket",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::bucket-name",
                "arn:aws:s3:::bucket-name/*"
            ]
        }
    ]
}
```
