### ISSUE TITLE
Fluent Bit to Fluentd forwarding issue with Loki plugin

### ISSUE THREAD

**Issue by OriMeyuhas** [grafana/loki#10254]
**Describe the bug**
I have a setup where Fluent Bit is installed on an IoT device. This device is configured to forward its logs to a Fluentd pod that running within an EKS cluster, which is exposed via an AWS Network Load Balancer (NLB). The primary role of this Fluentd pod is to act as an aggregator and subsequently forward these logs to a Loki instance.
However, I’ve encountered an issue where Fluentd reports an “incoming chunk is broken” error when attempting to send logs from Fluent Bit. The exact cause of this error remains unclear, It could be related to a configuration mismatch or other underlying issues.
Additionally, I followed the official Loki documentation for Fluentd, which recommends using the image grafana/fluent-plugin-loki:master. However, I noticed that this image hasn’t been updated in over 2 years, which could be a potential factor in the issues I’m facing. I am using this image to deploy the Fluentd pod.

**To Reproduce**
1. Started Loki (loki-stack 2.9.10)
2. Configured Fluentd with the recommended grafana/fluent-plugin-loki:master image to receive logs from Fluent Bit and forward them to Loki.
3. Fluent Bit on the IoT device is set to forward logs to Fluentd.

**Configuration:**

**Fluentd Configuration:**

```
fluentd.conf: |
    <source>
      @type forward
      port 24224
      resolve_hostname true
    </source>

    <match **>
      @type loki
      url http://my-loki-url:3100
      extra_labels {“job”:“fluentd”}
      <buffer>
        flush_interval 10s
        flush_at_shutdown true
      </buffer>
    </match>
```

**Fluent Bit Configuration:**

```
[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    debug

[INPUT]
    Name         cpu
    Tag          cpu_usage

[OUTPUT]
    Name         forward
    Match        *
    Host         dns of the fluentd
    Port         24224

[OUTPUT]
    Name          stdout
    Match         *
```

**Expected behavior**
Fluent Bit should seamlessly forward logs to the Fluentd pod in the EKS cluster. Fluentd should then process these logs and forward them to Loki, ensuring all logs from the IoT device are captured and stored in Loki for analysis.

**Actual Behavior**
Fluentd is encountering an “incoming chunk is broken” error during the log forwarding process from Fluent-Bit.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshot**
<img width="519" alt="Screen Shot 2023-08-15 at 16 55 37" src="https://github.com/grafana/loki/assets/107118002/cfa30ef6-0f0a-4551-9493-5f3dcfe1061f">

**Comment by OriMeyuhas** [comment]
**Update:**

After diving deeper into the issue, I've come to believe that the "incoming chunk is broken" error is tied to the health check of the AWS Network Load Balancer (NLB). This error surfaces even without sending any logs, pointing to the possibility that it's triggered automatically when the NLB performs health checks.

Furthermore, when I switched to the `grafana/fluent-plugin-loki:main` image, I encountered another issue: `config error file="/fluentd/etc/fluentd.conf" error_class=Fluent::ConfigError error="Unknown output plugin ' loki'"`.

Would appreciate any insights or suggestions on these matters. Thanks!

**Comment by OriMeyuhas** [comment]
Thank you for your assistance @tonyswu . 

I've made the following changes to my Fluentd and Fluent Bit configurations based on the recommendations:

**Fluentd Configuration:**
```xml
<source>
  @type http
  @log_level debug
  port 9880
</source>  

<source>
  @type http_healthcheck
  port 80
  bind 0.0.0.0
</source>

<label @FLUENT_LOG>
  <match **>
    @type null
    @id ignore_fluent_logs
  </match>
</label>

<match **>
  @type loki
  url http://my-loki-url:3100
  extra_labels {"job":"fluentd"}
  <label>
    fluentd_worker
  </label>
  <buffer>
    flush_interval 10s
    flush_at_shutdown true
  </buffer>
</match>
```

**Fluent Bit Configuration:**
```
[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    debug

[INPUT]
    Name         cpu
    Tag          cpu.usage

[OUTPUT]
    Name         http
    Match        *
    Host         my-host
    Port         80

[OUTPUT]
    Name          stdout
    Match         *
```

Additionally, I made infrastructural changes:

1. Switched from NLB to ALB.
2. Updated the Fluentd service to include two ports: one for health checks and one for HTTP.
3. Updated the ingress to handle both the health check and HTTP paths.
4. Added an annotation to the ingress for ALB health checks.

**Fluentd Service Spec:**
```yaml
spec:
  type: ClusterIP
  selector:
    app: fluentd-aggregator
  ports:
    - name: healthcheck
      port: 80
      targetPort: 80
    - name: http
      port: 9880
      targetPort: 9880
```

**Ingress Spec:**
```yaml
spec:
  ingressClassName: alb
  rules:
  - host: my-host
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fluentd-service
            port:
              name: http
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: fluentd-service
            port:
              name: healthcheck
```

**Ingress Annotation:**
```
alb.ingress.kubernetes.io/healthcheck-path: /health
```

With these changes, I've been able to resolve the issue I was facing. Thanks again for the support!
