### ISSUE TITLE
404 Page Not Found HTTP API

### ISSUE THREAD

**Issue by brngates98** [grafana/loki#10268]
**Describe the bug**
Keep running into these 404 errors when attempting to use the http api.
Loki is ingesting logs from windows and linux without issue however i want to remove a few job names from testing phase to do some clean up.
**To Reproduce**
 curl -v -G -X POST 'http://loki.thetmg.com:3100/loki/api/v1/delete'  --data-urlencode 'query={job="dmesg"}'

**Expected behavior**
Delete job=dmesg entries 

**Environment:**
 - Infrastructure: Bare Metal
 - Deployment tool: deb installer
**CONFIG**
```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /etc/loki
  storage:
    filesystem:
      chunks_directory: /etc/loki/data/chunks
      rules_directory: /etc/loki/data/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

frontend:
  max_outstanding_per_tenant: 8096
  compress_responses: true

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 4048

querier:
  engine:
    timeout: 10m
  query_timeout: 10m
  max_concurrent: 4048

limits_config:
  enforce_metric_name: false
  max_cache_freshness_per_query: '10m'
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  split_queries_by_interval: 15m

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://loki.thetmg.com:9009/alertmanager


```

**Screenshots, Promtail config, or terminal output**
curl http://loki.thetmg.com:3100/loki/api/v1/status/buildinfo
{"version":"HEAD-d819332","revision":"d8193321a","branch":"HEAD","buildUser":"root@84eeedb42522","buildDate":"2023-07-24T14:04:59Z","goVersion":""}

 curl -v -G -X POST 'http://loki.thetmg.com:3100/loki/api/v1/delete'  --data-urlencode 'query={job="dmesg"}'
*   Trying 192.168.70.33:3100...
* Connected to loki.thetmg.com (192.168.70.33) port 3100 (#0)
> POST /loki/api/v1/delete?query=%7Bjob%3D%22dmesg%22%7D HTTP/1.1
> Host: loki.thetmg.com:3100
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Wed, 16 Aug 2023 15:39:30 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host loki.thetmg.com left intact

**Comment by Cedric-lefebvre-mgx** [comment]
Ok i just managed to get the delete to work by adding:

```
loki:  
  runtimeConfig:
    overrides:
      fake:
        deletion_mode: "filter-and-delete"
structuredConfig:
  compactor:
    shared_store: s3
    retention_enabled: true
```

Inside the loki-distributed helm chart. I've been able to query and request deletion as expected now.
