### ISSUE TITLE
Loki's embedded_cache setting is ignored & Loki continues to reference deprecated fifocache

### ISSUE THREAD

**Issue by suntereo** [grafana/loki#10278]
**Describe the bug**  
There seems to be an issue with recognizing the `embedded_cache` settings in the configuration for Loki version 2.8.4 (Windows version). Despite configuring Loki to use `embedded_cache` and explicitly disabling `fifocache`, warnings related to the deprecated `fifocache` are still appearing.

**To Reproduce**  
1. Configure query_range with embedded_cache settings and set `enable_fifocache` to false
2. Start Loki 2.8.4
3. Warnings related to deprecated `fifocache` appear in the logs, such as:
   ```
   level=warn ts=2023-08-09T21:48:17.629216Z caller=cache.go:114 msg="fifocache config is deprecated. use embedded-cache instead"
   ```

**Expected behavior**  
I expect that the configuration for `embedded_cache` is recognized and no warnings related to `fifocache` are thrown, as `fifocache` is not being used and is explicitly disabled. Continuing to use the deprecated `fifocache` feature could lead to potential issues or conflicts in the future, and it might not be as optimized as the new `embedded_cache` feature. Ensuring that the system accurately recognizes and adheres to the specified configuration for `embedded_cache` is crucial for optimal performance and future stability.

**Environment:**  
- Loki for Windows
- OS Name: Microsoft Windows Server 2022 Standard

**Screenshots, Promtail config, or terminal output**  
Here is the relevant part of the configuration where `embedded_cache` is enabled, and `enable_fifocache` is explicitly set to false to try to force `fifocache` off:
```yaml
query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: false
      embedded_cache:
        enabled: true
        max_size_mb: 100
        ttl: 24h
```
Despite this configuration, warnings related to deprecated `fifocache` continue to appear in the logs:
```
level=warn ts=2023-08-09T21:48:17.6276412Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache - frontend.embedded-cache"
level=warn ts=2023-08-09T21:48:17.629216Z caller=cache.go:114 msg="fifocache config is deprecated. use embedded-cache instead"
level=warn ts=2023-08-09T21:48:17.629216Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache - chunksembedded-cache"
```
Here is where the warning is being thrown: [cache.go#L127](https://github.com/grafana/loki/blob/67002f34653bf56e4516340ee9bdbeb669eb4ae3/pkg/storage/chunk/cache/cache.go#L127)

**Comment by suntereo** [comment]
I was able to resolve this issue and I'm closing this ticket. Here's what I discovered, which may be helpful to others experiencing the same issue:

I used Visual Studio Code to step through the code and understand what was happening.

I noticed that the code that checked `EnableFifoCache` was being called twice. Here is the specific snippet from `cache.go`:

```go
if cfg.EnableFifoCache {
    level.Warn(logger).Log("msg", "fifocache config is deprecated. use embedded-cache instead")
    fifocfg = cfg.Fifocache
}
```

This code can be found at [this URL](https://github.com/grafana/loki/blob/67002f34653bf56e4516340ee9bdbeb669eb4ae3/pkg/storage/chunk/cache/cache.go#L127).

The chunk store seemed to be responsible for this second call to this code. I noticed I wasn't telling the chunk store to use `embedded_cache`. It appears that the default is the FIFO cache, which led to the deprecation warning.

To fix this, I needed to turn `embedded_cache` on for the chunk store module as well. Here's the configuration that resolved the issue:

```yaml
query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 500
        ttl: 24h

chunk_store_config:
  max_look_back_period: 0s
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 500
      ttl: 24h
```

### Conclusion

It seems that the FIFO cache is the default for the `chunk_store` module unless `embedded_cache` is used. By setting `embedded_cache` for the `chunk_store` module, the warning disappeared, and the configuration is now working as expected.
