### ISSUE TITLE
Error when upgrading to Helm chart 6.14.1

### ISSUE THREAD

**Issue by karl-dpg** [grafana/loki#10293]
**Describe the bug**
After upgrading to Helm chart 6.14.1, an error starting showing during the Helm upgrade. Error is:

```
template: promtail/templates/secret.yaml:18:8: executing "promtail/templates/secret.yaml" at <tpl .Values.config.file .>: error calling tpl: error during tpl function execution for "server:\n  log_level: 
...
: parse error at (promtail/templates/secret.yaml:22): function "ToUpper" not defined
```

**To Reproduce**
Setting the `config.snippets.pipelineStages` to the below:

```
    config:
      snippets:
        pipelineStages:
          - cri: {}
          - match:
              selector: '{namespace=~"test"}'
              stages:
                - json:
                    expressions:
                      app: app
                      level: level
                      msg: msg
                - template:
                    source: output
                    template: '{{ printf "[%-5s] " .level | ToUpper }}{{ printf "[%-22s] " .app }}'
```

**Expected behavior**
Template remains functioning after upgrade.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
