### ISSUE TITLE
how can I get the log(chunks) size per job?

### ISSUE THREAD

**Issue by mua-haha** [grafana/loki#10316]
I am using Loki 2.8.0 locally ,and recently i found loki data is a bit large. 

my data dir size is 70+G,but I count my log,it's only 20G MAX a week.

I config the loki as :
```
chunk_store_config:
  max_look_back_period: 168h
table_manager:
  retention_deletes_enabled: true
  retention_period: 168h
```

so  how can i get the log size per job, or analyze the data in 70+G
