### ISSUE TITLE
camelCase vs snake_case in values keys

### ISSUE THREAD

**Issue by alextes** [grafana/loki#10370]
It looks like the schema_ and rules_ configs keys are somehow set to camelCase instead of snake_case. Is this by accident? It makes a issue I'm debugging confusing. I'm no pro at Helm so not 100% right now the reason is that this changed in the last repo update but it's certainly harder to debug with inconsistent casing + templating going on.

https://github.com/grafana/loki/blob/586b9042c637f01a977765cc72de0e2c66e60ca9/production/helm/loki/values.yaml#L308

Thanks for this chart!

**Comment by chaudum** [comment]
@trevorwhitney Correct me if I'm wrong, but the intention was to distinguish between Helm configuration options in camelCase and Loki configuration in snake_case.

**Comment by alextes** [comment]
Is the user supposed to understand that distinction or purely for maintainers? The latter makes things a bit messy but could be okay.

I still think one problematic aspect of this is it's hard to tell where one can copy from Loki docs or where one should stick to Helm `values.yaml`. Take my loki block below, it's mixed. Worse, is `querier` camelCase and you can't copy from Loki docs or is it snake_case and you can?

Long term it'd be great if the Helm chart simply provided whatever options you needed with maybe the option to override entire blocks that go into Loki configs 1-to-1.

```yaml
loki:
  query_scheduler:
    max_outstanding_requests_per_tenant: 32768

  querier:
    max_concurrent: 16

  schemaConfig:
    configs:
      - from: 2023-08-29
        index:
          period: 24h
          prefix: index_
        object_store: s3
        schema: v12
        store: tsdb

  limits_config:
    enforce_metric_name: false
    max_cache_freshness_per_query: 10m
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    retention_period: 744h
    split_queries_by_interval: 15m

  auth_enabled: false

  storage:
    bucketNames:
      chunks: relay-loki-stag-chunks
      ruler: relay-loki-stag-ruler
    type: s3
    s3:
      endpoint: https://s3.gra.perf.cloud.ovh.net/
      region: gra
      accessKeyId: ****
      secretAccessKey: ****
      s3ForcePathStyle: true
```
