### ISSUE TITLE
Multi-store support for index and compactor doesn't work as expect.

### ISSUE THREAD

**Issue by Erichorng** [grafana/loki#10397]
Hi everyone. I have recently started using Loki and encountered some issues. I used the helm chart (loki-5.15) to install Loki on a 3 node k8s cluster. I wanted to save logs in the filesystem at the beginning and later switch to aws. Below is my configuration:（btw, It’s now 2023-08-30）

```
schemaConfig:
    configs:
    - from: 2022-01-11
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: loki_index_fs_
        period: 24h
    - from: 2023-08-31
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_ceph_
        period: 24h

storage_config:
    filesystem:
      directory: /var/loki/prelog
    aws:
      s3: https://<my-object-store>
      s3forcepathstyle: true
      #endpoint:
      region: default
      secret_access_key: <my-secret-key>
      access_key_id: <my-access-key>
      bucketnames: chunks
	  boltdb_shipper:
	      active_index_directory: /var/loki/index
	      #shared_store:
	      cache_location: /var/loki/boltdb-cache
```

I wanted to save both data and index in the filesystem at the beginning and then automatically switch to my defined AWS storage on 8/31. However, when I started Loki, I found that my data was saved in /var/loki/prelog, but my index was in [AWS.](<img width="303" alt="截圖 2023-08-30 下午5 53 11" src="https://github.com/grafana/loki/assets/46678749/cca61169-af70-40f9-ba09-710d69a3e98a">)

After some research, my understanding is that when I did not set boltdb_shipper.shared_store, it was automatically set to the last period config (if its store=boltdb-shipper). I am not sure if my understanding is correct. Also, the same logic, my shared_store for compactor seems to be set to aws by default, but I want it to compact the index in the filesystem.

Can anyone tell me how to configure it correctly? Thanks in advance!
