### ISSUE TITLE
Possible memory leak in writer

### ISSUE THREAD

**Issue by bobykus31** [grafana/loki#10408]
**Describe the bug**
When a writer has object storage configured but can not access it, it start consuming more and more memory until  system crashes 

**To Reproduce**
1. Started Loki 2.8.4
2. Started  fluent bit

**Expected behavior**
Loki does not increase memory usage even it can not write data to object storage

**Environment:**
Ubuntu Jammy Kernel  5.4.0-152-generic

**Screenshots, Promtail config, or terminal output**
Here is Aug 25 we installed and configured Loki writer. Unfortunately without opening firewall access to S3 object storage. The system crashed today.
![Screenshot from 2023-08-31 13-25-56](https://github.com/grafana/loki/assets/38345247/a633d0f8-9b25-4b6a-aedf-109d289452f9)

The config is
```
auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  grpc_server_max_recv_msg_size: 1048576000
  grpc_server_max_send_msg_size: 1048576000
  graceful_shutdown_timeout: 30s
  http_server_read_timeout: 300s
  http_server_write_timeout: 300s
  http_server_idle_timeout: 5m0s
common:
  path_prefix: "/var/lib/loki"
  storage:
    s3:
      s3: One
      s3forcepathstyle: true
      bucketnames: bb
      endpoint: s3.my.host
      region: SOM
      access_key_id: AKay
      secret_access_key: ASecrat
      insecure: false
      sse_encryption: false
      http_config:
        idle_conn_timeout: 10m
        response_header_timeout: 0s
        insecure_skip_verify: true
        ca_file: ''
      signature_version: v4
      sse:
        type: ''
        kms_key_id: ''
        kms_encryption_context: ''
      backoff_config:
        min_period: 100ms
        max_period: 3s
        max_retries: 5
  replication_factor: 1
  ring:
    kvstore:
      store: memberlist
schema_config:
  configs:
  - from: '2022-01-19'
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: index_
      period: 24h
  - from: '2023-08-20'
    store: tsdb
    object_store: s3
    schema: v12
    index:
      prefix: index_
      period: 24h
storage_config:
  index_queries_cache_config:
    background:
      writeback_goroutines: 10
      writeback_buffer: 100000
memberlist:
  join_members:
  - m1:7946
  - m2:7946
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  chunk_idle_period: 15m
  max_chunk_age: 1h
chunk_store_config:
  max_look_back_period: 720h
  chunk_cache_config:
    background:
      writeback_goroutines: 10
      writeback_buffer: 100000
  write_dedupe_cache_config:
    background:
      writeback_goroutines: 50
      writeback_buffer: 100000
table_manager:
  retention_deletes_enabled: true
  retention_period: 720h
limits_config:
  ingestion_rate_strategy: global
  ingestion_rate_mb: 256
  ingestion_burst_size_mb: 512
  max_label_name_length: 2048
  max_label_value_length: 8192
  max_label_names_per_series: 120
  reject_old_samples: true
  reject_old_samples_max_age: 1w
  creation_grace_period: 10m
  enforce_metric_name: true
  max_line_size: 0
  max_line_size_truncate: false
  max_streams_per_user: 0
  max_global_streams_per_user: 50000
  unordered_writes: true
  per_stream_rate_limit: 314572800
  per_stream_rate_limit_burst: 1572864000
  max_chunks_per_query: 20000000
  max_query_series: 5000
  max_query_lookback: 30d
  max_query_length: 30d1h
  max_query_parallelism: 32
  cardinality_limit: 10000000
  max_streams_matchers_per_query: 10000
  max_entries_limit_per_query: 50000
  max_cache_freshness_per_query: 1m
  max_queriers_per_tenant: 0
  split_queries_by_interval: 15m
  min_sharding_lookback: 0s
ingester_client:
  pool_config:
    client_cleanup_period: 45s
    remote_timeout: 30s
  remote_timeout: 30s
  grpc_client_config:
    max_recv_msg_size: 1048576000
    max_send_msg_size: 1048576000
    grpc_compression: gzip
analytics:
  reporting_enabled: false
tracing:
  enabled: false

```
