### ISSUE TITLE
Data source connected, but no labels were received

### ISSUE THREAD

**Issue by matheusriios** [grafana/loki#10525]
**Hi everyone!**

Recently I installed Loki + Grafana but when I added Loki as a data source I got the error: Data source connected, but no labels were received. Verify that Loki and Promtail are correctly configured.

Does anyone know how I can fix it?

Loki configuration:

```
### config-map
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: grafana
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 15s
      chunk_retain_period: 15s
      max_transfer_retries: 0
      chunk_block_size: 262144
    schema_config:
      configs:
        - from: 2020-01-01
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb:
        directory: /data/loki/index
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h

### loki
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-loki
  namespace: "grafana"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-loki
  template:
    metadata:
      labels:
        app: grafana-loki
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana-loki
          image: grafana/loki:latest
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/loki/loki.yaml
            - -target=all
          ports:
            - name: grafana-loki
              containerPort: 3100 
          volumeMounts:
            - name: grafana-loki-vol
              mountPath: /loki
            - name: loki-config
              mountPath: /etc/loki/
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: grafana-loki-vol
          nfs:
            server: ${MY_SERVER_IP}
            path: "/home/shared/devops/grafana/loki/data"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-loki-svc
  namespace: "grafana"
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 3100
      targetPort: 3100
  selector:
    app: grafana-loki
```

Promtail configuration
```
### promtail-config
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: grafana
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    clients:
      - url: http://grafana-loki-svc:3100/loki/api/v1/push

    positions:
      filename: /tmp/positions.yaml
      
    target_config:
      sync_period: 10s

    scrape_configs:
      - job_name: pod-logs
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - docker: {}
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: __host__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            replacement: $1
            separator: /
            source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_pod_name
            target_label: job
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__

### promtail
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana-promtail
  namespace: grafana
spec:
  selector:
    matchLabels:
      app: grafana-promtail
  template:
    metadata:
      labels:
        app: grafana-promtail
    spec:
      serviceAccountName: promtail-serviceaccount
      containers:
        - name: grafana-promtail
          image: grafana/promtail:latest
          args:
            - -config.file=/etc/promtail/promtail-config.yaml
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail
            - name: promtail-log
              mountPath: /var/log
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-config
        - name: promtail-log
          nfs:
            server: ${MY_SERVER_IP}
            path: "/home/shared/devops/grafana/promtail/logs/"
```

```
Loki last log:
level=info ts=2023-09-10T14:26:50.677430902Z caller=checkpoint.go:498 msg="atomic checkpoint finished" old=wal/checkpoint.000266.tmp new=wal/checkpoint.000266

Promtail logs:
[ 2023-09-10T14:25:20.09 ]: level=info ts=2023-09-10T14:25:19.992726219Z caller=promtail.go:133 msg="Reloading configuration file" md5sum=34cb7dca4919e6ca6e3b74c97f291cef
[ 2023-09-10T14:25:20.09 ]: level=info ts=2023-09-10T14:25:19.993216497Z caller=kubernetes.go:327 component=discovery discovery=kubernetes config=pod-logs msg="Using pod service account via in-cluster config"
[ 2023-09-10T14:25:20.09 ]: level=info ts=2023-09-10T14:25:19.994155789Z caller=server.go:322 http=[::]:9080 grpc=[::]:32787 msg="server listening on addresses"
[ 2023-09-10T14:25:20.09 ]: level=info ts=2023-09-10T14:25:19.994343539Z caller=main.go:174 msg="Starting Promtail" version="(version=2.9.0, branch=HEAD, revision=2feb64f69)"
[ 2023-09-10T14:25:20.09 ]: level=warn ts=2023-09-10T14:25:19.994374766Z caller=promtail.go:263 msg="enable watchConfig"
```
