### ISSUE TITLE
scheduler IPv6 error: too many colons in address

### ISSUE THREAD

**Issue by rissson** [grafana/loki#10532]
**Describe the bug**

Getting some errors contacting scheduler:

```
level=warn ts=2023-09-11T10:03:08.836374884Z caller=scheduler_processor.go:98 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp: address 2a05:d014:
409:db00:ca9d::5:9095: too many colons in address\"" addr=2a05:d014:409:db00:ca9d::5:9095
```

This makes Loki un-queriable.

**To Reproduce**
1. Deploy Loki on an IPv6-only environment with Helm and the following values:

<details>
<summary>Details</summary>

```yaml
          loki:
            analytics:
              reporting_enabled: false
            auth_enabled: false
            storage:
              type: s3
              s3:
                region: eu-central-1
                access_key_id: ${AWS_ACCESS_KEY_ID}
                secret_access_key: ${AWS_SECRET_ACCESS_KEY}
              bucketNames:
                chunks: loki-chunks
                ruler: loki-ruler
                admin: loki-admin
            extraMemberlistConfig:
              advertise_addr: "${POD_IP}"
            compactor:
              compactor_ring:
                instance_enable_ipv6: true
            distributor:
              ring:
                instance_enable_ipv6: true
            ingester:
              lifecycler:
                enable_inet6: true
            query_scheduler:
              scheduler_ring:
                instance_enable_ipv6: true

          memberlist:
            service:
              publishNotReadyAddresses: true

          singleBinary:
            replicas: 3
            extraArgs:
              - -config.expand-env=true
            extraEnvFrom:
              - secretRef:
                  name: loki-aws-credentials
            extraEnv:
              - name: POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP

          backend:
            enabled: false
          write:
            enabled: false
          read:
            enabled: false
          gateway:
            enabled: false

          monitoring:
            serviceMonitor:
              metricsInstance:
                enabled: false
            selfMonitoring:
              enabled: false
              grafanaAgent:
                installOperator: false
            lokiCanary:
              enabled: false

          test:
            enabled: false
```
</details>

Helm chart used is the one from #10531, with version 2.9.0

2. Get the errors.

I should mention that this only happens since upgrading to 2.9.0, and I had to add a bunch on configuration to get loki to even start:
```yaml
            compactor:
              compactor_ring:
                instance_enable_ipv6: true
            distributor:
              ring:
                instance_enable_ipv6: true
            ingester:
              lifecycler:
                enable_inet6: true
            query_scheduler:
              scheduler_ring:
                instance_enable_ipv6: true
```

**Expected behavior**

No errors. Can query Loki.

**Environment:**
 - Infrastructure: AWS EKS v1.27 IPv6-only with VPC CNI + Cillium
 - Deployment tool: Helm + ArgoCD

**Screenshots, Promtail config, or terminal output**
Already pasted above.
