### ISSUE TITLE
Loki v2.9.0 - failed to run compaction index store client not found for aws

### ISSUE THREAD

**Issue by jdgeisler** [grafana/loki#10554]
**Describe the bug**
We upgraded from Loki v2.8.4 to v2.9.0 and noticed the following error in our compactor that was not there before the upgrade.

```
level=error ts=2023-09-12T15:58:13.665292402Z caller=compactor.go:523 msg="failed to run compaction" err="index store client not found for aws"
```

After some troubleshooting, we found that this was because the `object_store` in our `schema_config` was set to `aws`. Once we changed `object_store` to `s3`, compaction started working again.

**To Reproduce**
1. Set Loki config as the following, with the `object_store` set to `aws` according to the [documentation](https://grafana.com/docs/loki/latest/configure/#period_config)
```
schema_config:
      configs:
      - from: "2020-09-07"
        index:
          period: 24h
          prefix: loki_index_
        object_store: aws
        schema: v11
        store: boltdb-shipper
      - from: "2023-06-01"
        index:
          period: 24h
          prefix: tsdb_index_
        object_store: aws
        schema: v12
        store: tsdb
storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h
        index_gateway_client:
          server_address: dns:///loki-distributed-index-gateway:9095
        shared_store: s3
      tsdb_shipper:
        active_index_directory: /var/loki/data/tsdb-index
        cache_location: /var/loki/data/tsdb-cache
        index_gateway_client:
          server_address: dns:///loki-distributed-index-gateway.loki.svc.cluster.local:9095
        shared_store: s3
```
2. Compaction works as expected on Loki v2.8.4
3. Upgrade Loki to v2.9.0
4. Compaction stops working and gives the above error in the description
5. Update the `schema_config` to `object_store: s3`
6. Compaction starts working again

**Expected behavior**
We did not see a breaking change or an update in the documentation related to `aws` no longer working in the `object_store` field of the `period_config`, so we expected this to work the same as in the previous version of Loki.

```
# Which store to use for the chunks. Either aws (alias s3), azure, gcs,
# alibabacloud, bos, cos, swift, filesystem, or a named_store (refer to
# named_stores_config). Following stores are deprecated: aws-dynamo, gcp,
# gcp-columnkey, bigtable, bigtable-hashed, cassandra, grpc.
[object_store: <string> | default = ""]
```

We did see changes related to the compactor shared store and the index shipper configs listed [here](https://grafana.com/docs/loki/latest/setup/upgrade/#compactor-multi-store-support), but nothing specific towards this issue we ran into.

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: loki-distributed helm chart
