### ISSUE TITLE
Loki can write but cannot read data from s3 storage

### ISSUE THREAD

**Issue by Alexsandr-Random** [grafana/loki#10570]
Stack - Grafana + Loki + promtail + s3 storage (seaweedfs) - all latest versions 
Loki could write logs into s3 storage (could download logs via aws cli and general size of bucket increasing)
But when using grafana dashboard (or just loki cli) - loki can not extract historical data from s3 (only  logs from cache)
It is NOT s3 permissions issue (user got admin privileges, e.g. read, list, write, tag...)
It is NOT connectivity issue (because we could write logs)
it is NOT grafana issue (loki cli also can not query historical data from s3)
Seems like bug...

Here is my loki configuration: 

````
auth_enabled: false
chunk_store_config:
#  max_look_back_period: 336h
  max_look_back_period: 0s

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  # Read timeout for HTTP server
  http_server_read_timeout: 5m
  # Write timeout for HTTP server
  http_server_write_timeout: 5m
  # Write timeout for HTTP server
  http_server_idle_timeout: 5m

limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 360h
#    retention_period: 336h

#
schema_config:
  configs:
  - from: 2020-05-15
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: loki_
      period: 24h
#
storage_config:
 boltdb_shipper:
   active_index_directory: /loki/index
   cache_location: /loki/index_cache
   shared_store: s3
 #  resync_interval: 45s
 aws:
   bucketnames: <secret>
   endpoint: seaweedfs-filer.service.consul:8333
   region: eu
   access_key_id: <secret>
   secret_access_key: <secret>
   insecure: true
 #  sse_encryption: false 
   s3forcepathstyle: true
#
compactor:
  working_directory: /loki/compactor
  shared_store: s3
  compaction_interval: 1m
  retention_enabled: true
  retention_delete_delay: 2h 
  retention_delete_worker_count: 150
#
ingester:
  chunk_idle_period: 3m
  chunk_block_size: 262144
  chunk_retain_period: 1m
  max_transfer_retries: 0
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  wal:
    dir: /loki/wal
#
table_manager:
    retention_deletes_enabled: true
    retention_period: 336h
````
