### ISSUE TITLE
Logs and Labels disappear after about an hour using Azure Blob Storage

### ISSUE THREAD

**Issue by Steve887** [grafana/loki#10574]
I am trying to use Loki with Grafana from an Azure Container App. I have been able to get this working using the default local config, I would like to use Azure Blob Storage to persist the logs beyond a container restart.

I have tried following the documentation to set it up, and I see indexes and files created in the storage, and logs show up in Grafana. However after about an hour the logs and labels all disappear, even when I expand the time range in the query.

The documentation around how to setup blob storage is a little confusing so there's a chance my configuration is wrong. Can anyone confirm? There's no obvious errors in the console logs for Loki.

Loki.yaml

```
auth_enabled: false

server:
  http_listen_port: 3100

common:
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-12-11
      index:
        period: 24h
        prefix: index_
      object_store: azure
      schema: v11
      store: boltdb-shipper

storage_config:
  azure:
    use_managed_identity: true
    account_name: ${STORAGE_ACCOUNT_NAME}
    container_name: ${LOGS_CONTAINER_NAME}
    request_timeout: 0
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: azure
  filesystem:
    directory: /loki/chunks
    
ruler:
  alertmanager_url: http://localhost:9093
  
compactor:
  working_directory: /loki/compactor
  
ingester:
  wal:
    dir: /loki/wal
```

Grafana datasource config
```
  - name: Logs
    type: loki
    access: proxy
    orgId: 1
    url: http://${LOKI-CONTAINER-NAME}:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    jsonData:
      derivedFields:
        - datasourceUid: otlp
          matcherRegex: (?:"traceid"):"(\w+)"
          name: TraceID
          url: $${__value.raw}
```

Folder structure created in my blob storage:
![image](https://github.com/grafana/loki/assets/129719/35114580-0570-463a-8578-861eeb0bac0e)
