### ISSUE TITLE
jsonnet doesn't output both boltdb and tsdb shipper configuration

### ISSUE THREAD

**Issue by umezawatakeshi** [grafana/loki#10602]
**Describe the bug**
When both `using_boltdb_shipper` and `using_tsdb_shipper` are set to `true`, only boltdb-shipper configuration is output.

**To Reproduce**
1. Write main.jsonnet like:
   ```
   local loki = import 'loki/loki.libsonnet';

   loki {
     _config+:: {
       ...
       using_boltdb_shipper: true,
       boltdb_shipper_shared_store: 's3',
       using_tsdb_shipper: true,
       tsdb_shipper_shared_store: 's3',
     }
   }
   ```
2. The output `storage_config` in ConfigMap is like:
   ```
     storage_config:
        ...
        boltdb_shipper:
            active_index_directory: /data/index
            cache_location: /data/boltdb-cache
            shared_store: s3
        ...
   ```
   (`tsdb_shipper` does not exist)

**Expected behavior**
The output `storage_config` in ConfigMap is like:
```
    storage_config:
        ...
        boltdb_shipper:
            active_index_directory: /data/index
            cache_location: /data/boltdb-cache
            shared_store: s3
        tsdb_shipper:
            active_index_directory: /data/tsdb-index
            cache_location: /data/tsdb-cache
            shared_store: s3
        ...
```

**Environment:**
 - Deployment tool: jsonnet

---

Probably it is because https://github.com/grafana/loki/blob/v2.9.1/production/ksonnet/loki/shipper.libsonnet#L27-L39 is interpreted like
```
      storage_config+: if ... then ({
        ...
      }) else ({} + if ... then {
        ...
      } else {}),
```
, not
```
      storage_config+: (if ... then {
        ...
      } else {}) + (if ... then {
        ...
      } else {}),
```
