### ISSUE TITLE
[helm/loki] Option to use emptyDir for backend component

### ISSUE THREAD

**Issue by ehlomarcus** [grafana/loki#10621]
**Is your feature request related to a problem? Please describe.**
Backend component requires a PersistentVolumeClaim, but do support persistentVolumeClaimRetentionPolicy on `(semverCompare ">= 1.23-0" .Capabilities.KubeVersion.Version)`.
Running Loki on AWS EKS with Fargate requires use of AWS EFS for persistence, but cleanup is not needed then. Setting `enableStatefulSetAutoDeletePVC` solves this.

It would be beneficial to be able to run without a PVC and instead use an emptyDir.

**Describe the solution you'd like**
Running Loki on AWS EKS with Fargate allow you to use local storage that comes with Fargate. I would like to be able to use an `emptyDir` and use `spec.containers[].resources.limits.ephemeral-storage` and `spec.containers[].resources.requests.ephemeral-storage`, to set how much should be available.

**Describe alternatives you've considered**
Alternative is to continue using EFS, which is working just fine.

**Additional context**
[statefulset-backend](https://github.com/grafana/loki/blob/main/production/helm/loki/templates/backend/statefulset-backend.yaml)

Example

```yaml
    spec:
      volumes:
      {{- if .Values.backend.persistence.enableUseOfEmptyDir }}
        - name: data
          emptyDir: {}
      {{- end }}
  {{- if ne .Values.backend.persistence.enableUseOfEmptyDir }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- with .Values.backend.persistence.storageClass }}
        storageClassName: {{ if (eq "-" .) }}""{{ else }}{{ . }}{{ end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.backend.persistence.size | quote }}
        {{- with .Values.backend.persistence.selector }}
        selector:
          {{- toYaml . | nindent 10 }}
        {{- end }}
  {{- end }}
```
