### ISSUE TITLE
Can only query the logs in last 1 hour when using filesystem as backend storage

### ISSUE THREAD

**Issue by Erichorng** [grafana/loki#10642]
Hi everyone. I have recently started using Loki and encountered some issues. I used helm chart(5.22.0, appVersion 2.9.1) to install Loki on a 3 node k3s cluster. When I use filesystem as backend storage, I couldn't query the logs correctly, It seams like I can only query the logs in the last 1~2 hour. However, when I use aws as backend storage, everything is OK. I'm not sure if this can be considered a bug, since the official user manual mentions that the filesystem is not recommended for use in a clustered Loki environment. 
After conducting some experiments, I found that the data is being correctly preserved. The issue appears to be occurring in the Loki read pod, there are lots of error shows:

![截圖 2023-09-18 下午12 08 11](https://github.com/grafana/loki/assets/46678749/87c6fb59-85dd-4f70-8030-7f13dc0ca0d5)

![截圖 2023-09-18 上午11 52 54](https://github.com/grafana/loki/assets/46678749/d675fd0d-7c1f-4df8-8b7a-08b6aa6afe04)

![loki-read error log](https://github.com/grafana/loki/assets/46678749/cdb73080-6915-484e-acda-a0b677695413)

The bug also appears in loki 2.8.4.

**To Reproduce**
1. Started Loki using helm (appVerson 2.9.1), with configurations below: 
```
gateway:
  replicas: 3
  service:
    type: NodePort    #   <- temp

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 3
  compactor:
    working_directory: /var/loki/compactor
    retention_enabled: true
    retention_delete_delay: 1h
    retention_delete_worker_count: 150
    compaction_interval: 6m
    shared_store: filesystem
  limits_config:
    retention_period: 48h
  schemaConfig:
    configs:
    - from: 2022-01-11
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: loki_index_fs_
        period: 24h
    #- from: 2022-01-11
    #  store: boltdb-shipper
    #  object_store: aws
    #  schema: v11
    #  index:
    #    prefix: loki_index_ceph_
    #    period: 24h

  storage_config:
    filesystem:
      directory: /var/loki/prelog
    aws:
      endpoint: <my-endpoint>
      region: default
      secret_access_key: <my-secret>
      access_key_id: <my-access-key>
      bucketnames: chunks
    boltdb_shipper: 
      active_index_directory: /var/loki/index 
      #shared_store: 
      cache_location: /var/loki/boltdb-cache
```

3. Started Promtail
4. Started Grafana
5. Wait for 3 hours, Query the log. Can only query the logs in last 1~2 hour 

**Expected behavior**
Can query all the logs
**Environment:**
 - Infrastructure: vm, 3 node , Ubuntu, k3s cluster
 - Deployment tool: helm
