### ISSUE TITLE
Loki rules don't send alert to alert manager when a lot of line return

### ISSUE THREAD

**Issue by insider89** [grafana/loki#10645]
**Describe the bug**
I am using [loki](https://github.com/grafana/loki/tree/main/production/helm/loki) 5.15.0 helm chart. I've configured recording rules to send alerts: record rules as metrics to prometheus, alerts rules to alertmanager. Everything working fine, until I got a lot of logs which match my alert rule.
The following rule should send alert when string contain `ERROR` word in the `middleware` namespace:
```
                - name: loki_ruler
                  interval: 1m
                  rules:
                    - alert: ErrorLogsNewAnd
                      expr: 'sum by(log_message, pod) (count_over_time({namespace="middleware"} |= `ERROR` | pattern `<_> <_> <log_message>` [1m]))'
                      for: 1m
                      labels:
                        severity: warning
                      annotations:
                        summary: ERROR in middleware namespace
                        description: "Message is '{{ "{{" }} $labels.log_message {{ "}}" }}'\nPod is '{{ "{{" }} $labels.pod {{ "}}" }}'"
```
Backend pod evaluate this rule fine:
```
level=info ts=2023-09-19T10:01:37.142221835Z caller=engine.go:218 component=ruler org_id=fake msg="executing query" type=instant query="sum by (log_message,pod)(count_over_time({namespace=\"middleware\"} |= \"ERROR\" | pattern \"<_> <_> <log_message>\"[1m]))" query_hash=2795709808
level=info ts=2023-09-19T10:01:37.519127994Z caller=metrics.go:152 component=ruler org_id=fake latency=fast query="sum by (log_message,pod)(count_over_time({namespace=\"middleware\"} |= \"ERROR\" | pattern \"<_> <_> <log_message>\"[1m]))" query_hash=2795709808 query_type=metric range_type=instant length=0s start_delta=377.782954ms end_delta=377.783157ms step=0s duration=376.797351ms status=200 limit=0 returned_lines=0 throughput=20MB total_bytes=7.7MB lines_per_second=180585 total_lines=68044 total_entries=1750 store_chunks_download_time=0s queue_time=0s splits=0 shards=0 cache_chunk_req=0 cache_chunk_hit=0 cache_chunk_bytes_stored=0 cache_chunk_bytes_fetched=0 cache_chunk_download_time=0s cache_index_req=0 cache_index_hit=0 cache_index_download_time=0s cache_result_req=0 cache_result_hit=0 cache_result_download_time=0s
level=info ts=2023-09-19T10:01:37.656941527Z caller=manager.go:202 storage=registry manager=tenant-wal msg="dynamically updated instance" instance=fake
```
When I do such query in the Grafana UI, it returns result to me:
![Screenshot 2023-09-19 at 13 06 09](https://github.com/grafana/loki/assets/17744154/daa1b374-8493-4f6b-9dd7-0d821b227e36)

When I change alert to different namespace, it sends alerts to alertmanager. The only difference between namespace, that there is a lot of messages in the middleware namespace that contains `ERROR` word. 
![Screenshot 2023-09-19 at 13 09 31](https://github.com/grafana/loki/assets/17744154/86fa5d95-f89a-4b2f-89fc-1289efeadae5)

When I change the alert rule to record rule, I see metrics in the prometheus, so the issue somewhere between loki and alertmanager. I didn't find any errors in the loki and alertmanager logs. 

**To Reproduce**
1. Started Loki (2.8.4)
2. Started Promtail (2.8.3)
3. Query: `sum by(log_message, pod) (count_over_time({namespace="middleware"} |= `ERROR` | pattern `<_> <_> <log_message>` [1m]))`

**Expected behavior**
Loki send alerts to alertmanager.

**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: [helm]

**Screenshots, Promtail config, or terminal output**
Loki helm chart config:
```
loki:
          storage:
            type: s3
            bucketNames:
              chunks: prod-loki
              ruler: prod-loki
              admin: prod-loki
            s3:
              s3: s3://eu-west-1
              region: eu-west-1
          auth_enabled: false
          compactor:
            retention_enabled: true
            compaction_interval: 60m
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
          limits_config:
            retention_period: 744h
            reject_old_samples: true
            reject_old_samples_max_age: 168h
            max_query_series: 10000
            max_query_parallelism: 2
          server:
            grpc_server_max_recv_msg_size: 10982429
            grpc_server_max_send_msg_size: 10982429
          rulerConfig:
            enable_api: true
            wal:
              dir: /var/loki/wal
            storage:
              type: local
              local:
                directory: /tmp/loki/rules
            ring:
              kvstore:
                store: inmemory
            alertmanager_url: http://alertmanager-operated.monitoring.svc.cluster.local:9093
            enable_alertmanager_v2: true
            remote_write:
              enabled: true
              client:
                url: http://prometheus-operator-kube-p-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
---
extraObjects:
        - apiVersion: v1
          kind: ConfigMap
          metadata:
            name: loki-rules
          data:
            recording-rules.yaml: |-
              groups:
                - name: loki_ruler_JavaOOM
                  limit: 10
                  interval: 1m
                  rules:
                    - record: OutOfMemoryError
                      expr: 'sum by(job,pod)(count_over_time({namespace=~"demo-.*"} |= "java.lang.OutOfMemoryError"[1m]))'
                      labels:
                        severity: warning
                - name: loki_ruler_KafkaTopicDeleted
                  limit: 10
                  interval: 1m
                  rules:
                    - record: KafkaTopicDeleted
                      expr: 'sum by(job,pod)(count_over_time({namespace=~"demo-stream"} |= "Deleting topic"[1m]))'
                      labels:
                        severity: warning
                - name: loki_ruler_Interceptop
                  interval: 1m
                  rules:
                    - alert: ErrorLogsNewAnd
                      expr: 'sum by(log_message, pod) (count_over_time({namespace="middleware"} |= `ERROR` | pattern `<_> <_> <log_message>` [1m]))'
                      for: 1m
                      labels:
                        severity: warning
                      annotations:
                        summary: ERROR in middleware namespace
                        description: "Message is '{{ "{{" }} $labels.log_message {{ "}}" }}'\nPod is '{{ "{{" }} $labels.pod {{ "}}" }}'"
                    - alert: WarnLogs
                      expr: 'sum by(log_message,pod) (count_over_time({namespace="middleware"} |= `WARN` | pattern `<_> <_> <log_message>` [1m]))'
                      for: 1m
                      labels:
                        severity: warning
                      annotations:
                        summary: WARN in middleware namespace
                        description: "Message is '{{ "{{" }} $labels.log_message {{ "}}" }}'\nPod is '{{ "{{" }} $labels.pod {{ "}}" }}'"
```
Promtail helm configuration:
```
 resources:
          limits:
            memory: 150Mi
          requests:
            cpu: 10m
            memory: 150Mi

        config:
          logLevel: info
          serverPort: 3101
          clients:
            - url: http://loki-write.logging.svc.cluster.local:3100/loki/api/v1/push

        tolerations:
          - effect: NoSchedule
            operator: Exists

        serviceMonitor:
          enabled: true
          labels:
            release: prometheus-operator
```
