### ISSUE TITLE
loki queries with wide time ranges tend to miss logs

### ISSUE THREAD

**Issue by freehck** [grafana/loki#10658]
**Describe the bug**
If a query has a wide time range some log lines can be missed.
Manual split of queries to smaller time ranges eliminates the problem.
I think it's a problem of Loki Querier.

**To Reproduce**
I managed to reproduce the problem only on a heavy loaded production infrastructure.
Here will be a lot of shell code, so take a deep breath.

First of all let's define an additional function to simplify a bit the following code reading:
```
mylogcli(){
  logcli query --quiet --forward --limit=0 --org-id="ORG_ID"--addr=http://LOKI_ADDR "$@"
}
```

Now here's a bunch of queries taking the log for one specific day (24h):
1) direct way to query a full day log in one pass:
```
mylogcli '{pod="POD_NAME"}' --from="2023-09-01T00:00:00+03:00" --to="2023-09-02T00:00:00+03:00" -o raw > full-day.log
```
2) manual split to query the same range by hours: i.e. 24 queries for the same specific day (24h):
```
:>full-day-hours.log;
for i in $(seq 0 23); do
  ii=$(printf '%02d' "$i");
  if [ "$i" -ne 23 ]; then
    ie=$((i+1)); d=1;
  else
    ie=0; d=2;
  fi
  iie=$(printf '%02d' "$ie");
  mylogcli '{pod="POD_NAME"}' --from="2023-09-01T${ii}:00:00+03:00" --to="2023-09-0${d}T${iie}:00:00+03:00" -o raw >>full-day-hours.log
  echo "HOUR $ii rc $?"
done
```
3) manual split to query the same range by smaller ranges of 10 minutes only: i.e. 24*6 queries for the same specific day (24h):
```
:>full-day-10mins.log;
d=1
for i in $(seq 0 23); do
  ii=$(printf '%02d' "$i");
  for j in $(seq 0 10 50); do
    ie=$i; je=$((j+10)); de=$d;
    if [ "$j" -eq "50" ]; then
      ie=$((i+1)); je=0;
      if [ "$i" -eq 23 ]; then
        de=$((d+1)); ie=0;
      fi
    fi
    jj=$(printf '%02d' "$j");
    iie=$(printf '%02d' "$ie");
    jje=$(printf '%02d' "$je");
    mylogcli '{pod="POD_NAME"}' --from="2023-09-0${d}T${ii}:${jj}:00+03:00" --to="2023-09-0${de}T${iie}:${jje}:00+03:00" -o raw >>full-day-10mins.log;
    echo "$ii:$jj rc $?";
  done
done
```

Here're the results for these three commands:
```
# md5sum *
d39a5829271d38a2c819459e40bf5897  full-day-10mins.log
d39a5829271d38a2c819459e40bf5897  full-day-hours.log
50f63231216ca127c7798a8e82bedae7  full-day.log
# ls -l
total 1199412
-rw-r--r--    1 root     root     409469805 Sep 19 20:02 full-day-10mins.log
-rw-r--r--    1 root     root     409469805 Sep 19 20:04 full-day-hours.log
-rw-r--r--    1 root     root     409246066 Sep 19 18:39 full-day.log
# echo "$(echo 'scale=2; (409469805-409246066)/1024' | bc)kb of missed logs";
218.49kb of missed logs
# wc -l *| grep -v total
  1238558 full-day-10mins.log
  1238558 full-day-hours.log
  1237879 full-day.log
# echo "$(echo '1238558-1237879' | bc) lines of missed logs"
679 lines of missed logs
```

As you can see, the log `full-day.log` returned by the first query has 679 lines (or 218.49kb) less than `full-day-hours.log` or `full-day-10mins.log` returned by split (second and third) queries . It's about 0.055% of the full amount of log, but for B2B purposes even such a small percent of missed logs is a problem.

A visual analysis of the differences of the collected logs shows that the missed lines are not in the beginning or in the end, but everywhere. F.e. the lines I was looking for were actually in the middle of the day.

**Expected behavior**
I expect a direct query of a full time range to return all the log lines, but in fact I see the difference between `full-day.log` and `full-day-hours.log`.

**Environment:**
We use ha-loki installation in Kubernetes with Minio backend.

80-loki.tf
```
resource "helm_release" "loki" {
  name         = "loki"
  namespace    = "loki"
  repository   = "https://grafana.github.io/helm-charts"
  chart        = "loki"
  version      = "5.8.9"
  values = [
    "${templatefile("../../../files/helm-loki-values.yaml", local.cfg)}"
  ]
}
```
helm-loki-values.yaml
```
loki:
  auth_enabled: false

global:
  dnsService: "coredns"

loki:
  storage:
    type: s3
    s3:
      endpoint: MINIO_ADDR:9000
      accessKeyId: AKEY
      secretAccessKey: SKY
      insecure: true
      s3ForcePathStyle: true
    bucketNames:
      admin: ha-loki-admin-bucket
      chunks: ha-loki-chunks-bucket
      ruler: ha-loki-ruler-bucket

backend:
  nodeSelector:
    node-pool: master
    
read:
  replicas: 4
  autoscaling:
    enabled: true
    minReplicas: 4
    maxReplicas: 6
    targetCPUUtilizationPercentage: 60

write:
  replicas: 6
  autoscaling:
    enabled: true
    minReplicas: 6
    maxReplicas: 8

gateway:
  replicas: 3
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
  nodeSelector:
    LOKI_NODE_POOL_LABEL: LOKI_NODE_POOL_VALUE
  service:
    port: 80
    type: NodePort
    nodePort: SOME_PORT
```
