### ISSUE TITLE
Can't search for structured metadata

### ISSUE THREAD

**Issue by mathias-ioki** [grafana/loki#10683]
**Describe the bug**
We want to use the new `structured metadata` feature. For that, we have configured Loki to accept this new kind of metadata and we configured Promtail to ship the structured metadata. Everything looks fine so far. But if we now add these non-indexed fields to our search query, we don't get any response. We tried logcli and Grafana Explore to search for the logs.

We are pretty sure, that these structured metadata are correctly shipped to Loki, because:
* It's possible to ship the field as label, by replacing structured_metadata with labels in promtail
* structured_metadata is the right keyword in promtail, as promtail complains when we use an unknown one
* structured metadata are send to loki by promtail, as promtail is logging an error, when we disable it again in loki by setting allow_structured_metadata to false.

But we don't know how to confirm that they are correctly stored in S3.

**To Reproduce**
1. Enable structured metadata in Loki and restart:
```
limits_config:
  allow_structured_metadata: true
```
2. Configure Promtail to add structured metadata to your logs:
```
scrape_configs:
  - job_name: docker
    pipeline_stages:
      - static_labels:
          job: docker
      - match:
          selector: '{application="appname"} |= "log message"'
          stages:
            - json:
                expressions:
                  payload:
            - json:
                expressions:
                  request_id:
                source: payload
            - structured_metadata:
                request_id:
```
3. Query: `'{application="appname"} | request_id = "123abc"'`

**Expected behavior**
The expected behavior is to get log lines, which contain the mentioned request_id. But instead of that, you get an empty response.

**Environment:**
- Loki version: 2.9.1
- Promtail version: 2.9.1
- LogCli version: 2.9.1
- Infrastructure: Cloud VMs with Read-Write mode
- Deployment tool: apt packages

**Comment by luxaritas** [comment]
Also ran into this. Can be reproduced with a single post via cURL:
```
DATA_PRE='{"streams": [{ "stream": { "label": "labelvalue" }, "values": [ [ "'
TIME=$(date +%s%N)
DATA_POST='", "log line content", {"structured": "structuredvalue"} ] ] }]}'

curl -v -H "Content-Type: application/json" -XPOST -s "http://localhost:3100/loki/api/v1/push" --data-raw "$DATA_PRE$TIME$DATA_POST"
```
and then doing a logcli or grafana lookup (I also tried a grafana nightly snapshot from ~ a week ago)

**Comment by vlad-diachenko** [comment]
I will check today/tomorrow

**Comment by periklis** [comment]
Do you use V13 in your Schema config?

**Comment by mathias-ioki** [comment]
> Do you use V13 in your Schema config?

No, at the moment, we are using boltdb with schema v11, but prepared already for tsdb with schema v12.

* What is recommended here? Is v13 latest?
* How can we migrate to a newer version? Just adding a new section with a date in future?

**Comment by luxaritas** [comment]
I was on schema v12, and updating to v13 led to everything working as expected. I don't _think_ this is in the docs anywhere, perhaps it should be?

**Comment by periklis** [comment]
V13 is the chunk format allowing to store structured metadata in the first place.

**Comment by vlad-diachenko** [comment]
Thanks @periklis  ;)

**Comment by mathias-ioki** [comment]
v13 chunk format works for us, too! Thank you @periklis for your fast help!

**Comment by vlad-diachenko** [comment]
updated the docs

**Comment by hendrikebbers** [comment]
Same issue here. I created a LOKI Docker container that has the following `config.yaml`:

```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

limits_config:
  allow_structured_metadata: true
```

Request:
```
POST /loki/api/v1/push HTTP/1.1
Content-Type: application/json
Host: localhost:3100
Connection: close
User-Agent: RapidAPI/4.2.0 (Macintosh; OS X/13.3.1) GCDHTTPRequest
Content-Length: 101

{"streams":[{"stream":{"app":"demo1"},"values":[["1695659008945000000","Hello World!", {"a":"b"}]]}]}
```

Response:
```
HTTP/1.1 400 Bad Request
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Mon, 25 Sep 2023 16:40:00 GMT
Content-Length: 245
Connection: close

loghttp.PushRequest.Streams: []*loghttp.Stream: unmarshalerDecoder: Value is string, but can't find closing '"' symbol, error found in #10 byte of ...|a":"b"}]]}]}|..., bigger context ...|"1695659008945000000","Hello World!", {"a":"b"}]]}]}|...

```
