### ISSUE TITLE
minio make-user-job error mc: <ERROR> Deprecated command. Please use 'mc admin policy attach' instead.

### ISSUE THREAD

**Issue by christopher-wong** [grafana/loki#10707]
**Describe the bug**

Deploying the `Loki` chart with Minio enabled leads to the following error:

```
│ Connecting to MinIO server: http://loki-49ec98b9-minio:9000                                                                                                                     │
│ Added `myminio` successfully.                                                                                                                                                   │
│ User 'console' already exists.                                                                                                                                                  │
│ Adding policy 'consoleAdmin' for 'console'                                                                                                                                      │
│ mc: <ERROR> Deprecated command. Please use 'mc admin policy attach' instead.                                                                                                    │
│ Stream closed EOF for monitoring/loki-49ec98b9-minio-make-user-job-5cnn4 (minio-mc)
```

**To Reproduce**
Helm values 
```
minio:
  enabled: true
  persistence:
    size: "8Gi"
  imagePullSecrets:
    - name: "registry-credential-fs-platform"
  image:
    tag: "RELEASE.2022-08-13T21-54-44Z"
  mcImage:
    tag: "RELEASE.2023-06-28T21-54-17Z"
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

```

**Expected behavior**
Job should complete without error

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm via Pulumi

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
