### ISSUE TITLE
Error "unable to fetch index files and extract tenants: : short write" on Compactor

### ISSUE THREAD

**Issue by LERUfic** [grafana/loki#10721]
**Describe the bug**

I encountered an issue with my compactor where it fails to perform compaction correctly, displaying the error message `unable to fetch index files and extract tenants: : short write.` This error is preventing the compactor from functioning as expected.
```
{"caller":"compactor.go:531","err":"unable to fetch index files and extract tenants: : short write","level":"error","msg":"failed to compact files","table":"loki_index_19626","ts":"2023-09-26T15:03:07.750992041Z"}
{"caller":"compactor.go:460","err":"unable to fetch index files and extract tenants: : short write","level":"error","msg":"failed to run compaction","ts":"2023-09-26T15:03:07.751082518Z"}
```
<img width="1438" alt="Screenshot 2023-09-26 at 22 11 33" src="https://github.com/grafana/loki/assets/108259869/7a346a95-e477-4dc6-ad6e-5e457cb6fc1f">

**To Reproduce**
1. Start Loki using Helm Chart "Loki Distributed" (Chart: 0.69.16, Image: docker.io/grafana/loki:2.8.2) on GKE.
2. Add high cardinality labels to Loki for indexing, potentially causing issues with the index gateway.
3. Replace the loki-index-gateway disk with pd-ssd from standard.
4. Tomorrow notice that queries become significantly slower.
5. Revert all changes (except the disk storage class change) and attempt to optimize the configuration, but queries remain slow.
6. Discover the compactor error occurring since yesterday.
7. Attempt a fresh installation of the compactor, but compaction continues to fail.

**Expected behavior**
We suspect that the compaction failure might be the root cause of our slow query performance. Our expectation was that after reverting all the changes and resolving any compactor issues, our query speeds would return to normal.

**Environment:**
 - Infrastructure: Kubernetes (GKE)
 - Deployment tool: Helm Chart Loki Distributed 0.69.16
 - Loki Config
```
auth_enabled: true
server:
    http_listen_port: 3100
    log_level: info
    log_format: json
    grpc_server_max_recv_msg_size: 17179869184
    grpc_server_max_send_msg_size: 17179869184
    http_server_read_timeout: 5m
    http_server_write_timeout: 5m
    graceful_shutdown_timeout: 5m
memberlist:
    join_members:
        - loki-memberlist
distributor:
    ring:
        kvstore:
            store: memberlist
ingester:
    chunk_block_size: 15728640
    chunk_encoding: snappy
    chunk_idle_period: 30m
    chunk_retain_period: 1m
    chunk_target_size: 4000000
    flush_check_period: 30s
    flush_op_timeout: 3m
    concurrent_flushes: 64
    autoforget_unhealthy: true
    lifecycler:
        ring:
            kvstore:
                store: memberlist
            replication_factor: 3
    wal:
        dir: /var/loki/wal
ingester_client:
    remote_timeout: 1m
    grpc_client_config:
        max_recv_msg_size: 17179869184
        max_send_msg_size: 17179869184
querier:
    query_ingesters_within: 2h
    tail_max_duration: 1h
    max_concurrent: 100
    multi_tenant_queries_enabled: true
query_range:
    align_queries_with_step: true
    cache_results: true
    parallelise_shardable_queries: true
    max_retries: 5
    results_cache:
        cache:
            enable_fifocache: true
            fifocache:
                max_size_bytes: 2GB
                validity: 24h
            redis:
                endpoint: <redacted>
                timeout: 5m
                expiration: 24h
storage_config:
    boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 24h
        shared_store: gcs
        query_ready_num_days: 7
        index_gateway_client:
            server_address: loki-index-gateway.loki.svc.cluster.local:9095
            grpc_client_config:
                max_recv_msg_size: 17179869184
                max_send_msg_size: 17179869184
    index_queries_cache_config:
        redis:
            endpoint: <redacted>
            timeout: 5m
            expiration: 24h
    gcs:
        bucket_name: <redacted>
schema_config:
    configs:
        - from: "2022-01-01"
          store: boltdb-shipper
          object_store: gcs
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
common:
    compactor_address: http://loki-compactor.loki.svc.cluster.local:3100
compactor:
    working_directory: /var/loki/compactor
    shared_store: gcs
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
chunk_store_config:
    chunk_cache_config:
        redis:
            endpoint: <redacted>
            timeout: 5m
            expiration: 24h
    write_dedupe_cache_config:
        redis:
            endpoint: <redacted>
            timeout: 5m
            expiration: 24h
limits_config:
    query_timeout: 5m
    reject_old_samples: true
    reject_old_samples_max_age: 24h
    ingestion_rate_mb: 512
    ingestion_burst_size_mb: 1024
    per_stream_rate_limit: 512M
    per_stream_rate_limit_burst: 1024M
    cardinality_limit: 200000
    max_query_lookback: 336h
    enforce_metric_name: false
    max_cache_freshness_per_query: 10m
    split_queries_by_interval: 15m
    max_entries_limit_per_query: 1000
    max_query_series: 100000
    max_concurrent_tail_requests: 50
    retention_period: 336h
    max_global_streams_per_user: 5000000
    max_query_parallelism: 64

frontend:
    max_outstanding_per_tenant: 5000
    compress_responses: true
    log_queries_longer_than: 20s
    tail_proxy_url: http://loki-querier.loki.svc.cluster.local:3100
    scheduler_address: loki-query-scheduler:9095
    grpc_client_config:
        max_recv_msg_size: 17179869184
        max_send_msg_size: 17179869184
frontend_worker:
    scheduler_address: loki-query-scheduler:9095
    grpc_client_config:
        max_recv_msg_size: 17179869184
        max_send_msg_size: 17179869184
        grpc_compression: snappy
query_scheduler:
    max_outstanding_requests_per_tenant: 5000
    grpc_client_config:
        max_recv_msg_size: 17179869184
        max_send_msg_size: 17179869184
table_manager:
    retention_deletes_enabled: true
    retention_period: 336h
ruler:
    alertmanager_url: <redacted>
    evaluation_interval: 5s
    enable_sharding: true
    enable_api: true
    remote_write:
        enabled: false
        client:
            url: <redacted>
    ring:
        kvstore:
            store: memberlist
    rule_path: /tmp/loki
    storage:
        local:
            directory: /etc/loki/rules
        type: local
    wal:
        dir: /var/loki/wal
```

**Screenshots, Promtail config, or terminal output**
<img width="1374" alt="Screenshot 2023-09-26 at 22 24 58" src="https://github.com/grafana/loki/assets/108259869/126a18b2-d9d9-4cf9-90d1-1a539a580f64">
<img width="324" alt="Screenshot 2023-09-27 at 00 00 29" src="https://github.com/grafana/loki/assets/30289344/cc51380a-6a13-4723-8496-7c72e3b44836">
