### ISSUE TITLE
Loki 2.9.1 - LokiTooManyCompactorsRunning alert occurs every 10 min

### ISSUE THREAD

**Issue by barwod** [grafana/loki#10737]
**Describe the bug**
I upgraded the days ago my loki helm chart from the 2.5.0 version to 2.9.1 ( chart 5.23.1 version ). After the upgrade, I get an every 10 min alert:

[FIRING:1] LokiTooManyCompactorsRunning (monitoring warning)
monitoring has had 3 compactors running for more than 5m. Only one compactor should run at a time.

I tried to search documentation and can't find any information about the problem. I use AWS S3 as storage.

**Expected behavior**
The alert doesn't appear.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Values file:**
```
USER-SUPPLIED VALUES:
backend:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
gateway:
  basicAuth:
    enabled: true
    existingSecret: secret
  ingress:
    annotations:
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/target-type: ip
      kubernetes.io/ingress.class: alb
    enabled: true
    hosts:
    - host: host
      paths:
      - path: /
        pathType: Prefix
    - host: host
      paths:
      - path: /
        pathType: Prefix
    tls: null
  nginxConfig:
    serverSnippet: |
      location = /cloudwatch-ingest {
        proxy_pass /loki/api/v1/push;
      }
  replicas: 3
  resources:
    requests:
      cpu: 70m
      memory: 15Mi
loki:
  auth_enabled: false
  storage:
    bucketNames:
      admin: admin
      chunks: chunks
      ruler: ruler
    querier:
      max_concurrent: 4
    s3:
      accessKeyId: null
      endpoint: null
      region: region
      s3ForcePathStyle: true
      secretAccessKey: null
    type: s3
monitoring:
  dashboards:
    enabled: false
  lokiCanary:
    enabled: false
  rules:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  serviceMonitor:
    enabled: false
read:
  persistence:
    enableStatefulSetAutoDeletePVC: false
  replicas: 2
  resources:
    limits:
      memory: 3Gi
    requests:
      cpu: 50m
      memory: 3Gi
serviceAccount:
  create: false
  name: service-account
test:
  enabled: false
write:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 2.9Gi
```
