### ISSUE TITLE
[promtail] Docker service discovery is picking up anot working when a container uses a `network_mode` directive

### ISSUE THREAD

**Issue by usommerl** [grafana/loki#10739]
**Describe the bug**
We use `promtail` and `docker_sd` to scrape the logs of OCI containers that are deployed via `docker-compose`.  We have noticed that *promtail* does not add a newly started container as a scrape target if the *docker-compose* service was configured with the `network_mode: "service:[service name]"` directive [\[1\]](https://docs.docker.com/compose/compose-file/compose-file-v3/#network_mode).

**To Reproduce**
1. Configure `promtail` to use `docker_sd`
2. Start a `docker-compose` project that has at least one service with the `network_mode: "service:[service name]"` directive
3. Output the container IDs of all containers
4. Check in the `promtail` logs whether it discovered the container with the `network_mode: service:[service name]` setting

**Expected behavior**
I would expect that the logs of all containers that were started by the *docker-compose* project are scraped by *promtail*.

**Environment:**
 - Infrastructure: VPS
 - Deployment tool: docker-compose

**Screenshots, promtail config, or terminal output**
```yaml
# Excerpt from promtail config.yml:

scrape_configs:
- job_name: docker
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
```
