### ISSUE TITLE
operator: configure Loki to use S3 without credentials (AWS STS OIDC)

### ISSUE THREAD

**Issue by felixkrohn** [grafana/loki#10747]
**Is your feature request related to a problem? Please describe.**
According to the documentation, using helm Loki can be installed without using fixed credentials for the s3 storage.
The operator does not expose this capability.

**Describe the solution you'd like**
Ideally, this should also be possible when deploying Loki through the operator. However, from the little I understand, the secret and especially the `access_key_id` and `access_key_secret` keys in it, [are mandatory](https://github.com/grafana/loki/blob/main/operator/internal/handlers/internal/storage/secrets.go#L85). Giving dummy values here won't work either, the credentials given seem to override any credential-less capability Loki might have.

**Describe alternatives you've considered**
This could either be that the credentials become optional for the s3 storage, or by adding another storage option (like "s3-sts"?) for which the credentials are not used or required.

**Additional context**
* Ideal for EKS clusters or also OpenShift on AWS (ROSA).
* In enterprise environments, it's usually not possible/allowed (for good reasons) to use static credentials.
* Ideally, the name of the Serviceaccount to be used could be configured as well.

**Comment by xperimental** [comment]
I have not looked into it any deeper already, so I don't know if there are any workarounds that I can provide for you.

Tthere's an existing feature request for supporting STS (and similar procedures in other public clouds): [LOG-4540](https://issues.redhat.com/browse/LOG-4540)

**Comment by blaivs** [comment]
I've just found the same issue, I was trying to migrate to the operator from the helm chart to simplify the setup. In the helm chart I can define the serviceAccount to use, where I attach the permissions for writing into a bucket. Other option could be being able to add an annotation to the serviceAccount, but didn't find a way to do it.

**Comment by periklis** [comment]
@blaivs Can you provide a Loki config yaml with STS enabled? I just can't figure out the right setting from the top of my head right now as per my lookups on the manual do not show me that we clearly support STS in Loki itself. Maybe just me holding this wrond

**Comment by blaivs** [comment]
Actually we are using https://github.com/redradrat/aws-iam-operator to create a service account:


```yaml
---
# creates a role, and a service account with the eks role annotation
apiVersion: aws-iam.redradrat.xyz/v1beta1
kind: Role
metadata:
  name: loki
spec:
  assumeRolePolicy: []
  createServiceAccount: true
  addIRSAPolicy: true
  maxSessionDuration: 3600
---
apiVersion: aws-iam.redradrat.xyz/v1beta1
kind: PolicyAttachment
metadata:
  name: loki-attachement
spec:
  target:
    type: Role
    name: loki
    namespace: monitoring
  policy:
    name: loki
    namespace: monitoring
---
apiVersion: aws-iam.redradrat.xyz/v1beta1
kind: Policy
metadata:
  name: loki
spec:
  statement:
    - effect: "Allow"
      actions:
        - "s3:ListBucket"
        - "s3:ListBucketVersions"
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:DeleteObject"
        - "s3:AbortMultipartUpload"
      resources:
        - "arn:aws:s3:::loki-bucket"
        - "arn:aws:s3:::loki-bucket/*"
```
then we configure helm values.yaml of [loki's chart](https://github.com/grafana/loki/tree/main/production/helm/loki)

```yaml
serviceAccount:
  create: false
  name: loki
 ...
```
on the pod itself we see the following vars injected +token which the underlying aws sdk gets (tested and working):
```
AWS_ROLE_ARN=arn:aws:iam::605604302963:role/loki
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```
