### ISSUE TITLE
`pipeline_stages` not doing anything

### ISSUE THREAD

**Issue by hydazz** [grafana/loki#10753]
Im trying to filter my pve firewall logs, which get send to /var/log/pve-firewall.log in the format:
```
304 5 tap304i0-OUT 01/Oct/2023:15:22:55 +1100 DROP: IN=fwbr304i0 OUT=fwbr304i0 PHYSIN=tap304i0 PHYSOUT=fwln304i0 MAC=e0:63:da:80:2b:5a:e2:62:79:53:bc:88:08:00 SRC=192.168.100.8 DST=192.168.1.10 LEN=84 TOS=0x00 PREC=0x00 TTL=64 ID=10637 DF PROTO=ICMP TYPE=8 CODE=0 ID=28751 SEQ=3
```
using the regex:
```
^(?P<vmid>\d+)\s(?P<rule>\d+)\s(?P<interface>[\w\d-]+)\s(?P<timestamp>[\d\/\w: +]+)\s(?P<action>[\w]+): IN=(?P<in_iface>[\w\d]+) OUT=(?P<out_iface>[\w\d]+) PHYSIN=(?P<physin_iface>[\w\d]+) PHYSOUT=(?P<physout_iface>[\w\d]+) MAC=(?P<mac_address>[\w\d:]+) SRC=(?P<src_ip>[\d.]+) DST=(?P<dst_ip>[\d.]+) LEN=(?P<length>\d+) TOS=(?P<tos>[\w\d]+) PREC=(?P<prec>[\w\d]+) TTL=(?P<ttl>\d+) ID=(?P<id>\d+) DF PROTO=(?P<protocol>[\w]+) TYPE=(?P<type>\d+) CODE=(?P<code>\d+) ID=(?P<proto_id>\d+) SEQ=(?P<seq>\d+)$
```
yields all options getting properly grouped:
![image](https://github.com/grafana/loki/assets/53986978/f137214f-96e6-4825-8a83-89a75c399ffe)

however promtail is not applying the regex into the timestamp or labels, im only getting the labels from `static_configs`.
```bash
^Croot@voyager:/etc/promtail # promtail --inspect -config.file /etc/promtail/config.yml
level=info ts=2023-10-01T04:54:47.912292491Z caller=promtail.go:133 msg="Reloading configuration file" md5sum=6f28a342bdeab19fc57354fdb3a27699
level=info ts=2023-10-01T04:54:47.913049972Z caller=server.go:322 http=[::]:9080 grpc=[::]:43057 msg="server listening on addresses"
level=info ts=2023-10-01T04:54:47.913135897Z caller=main.go:174 msg="Starting Promtail" version="(version=2.9.1, branch=HEAD, revision=d9d5ed4a1)"
level=warn ts=2023-10-01T04:54:47.913149199Z caller=promtail.go:263 msg="enable watchConfig"
[inspect: regex stage]: none
[inspect: regex stage]: none
[inspect: labels stage]: none
[inspect: labels stage]: none
[inspect: regex stage]: none
[inspect: regex stage]: none
[inspect: labels stage]: none
[inspect: labels stage]: none
[inspect: regex stage]: none
[inspect: regex stage]: none
[inspect: labels stage]: none
[inspect: labels stage]: none
```
`promtail --stdin --dry-run --inspect -config.file /etc/promtail/config.yml` causes promtail to not even output any logs

```yaml
server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.1.7:3100/loki/api/v1/push

scrape_configs:
  - job_name: pve-firewall
    static_configs:
      - targets:
          - localhost
        labels:
          job: pve-firewall
          host: voyager
          agent: promtail
          __path__: /var/log/pve-firewall.log

    pipeline_stages:
      - match:
          selector: '{job="pve-firewall"}'
          stages:
            - regex:
                expression: '^(?P<vmid>\d+)\s(?P<rule>\d+)\s(?P<interface>[\w\d-]+)\s(?P<timestamp>[\d\/\w: +]+)\s(?P<action>[\w]+): IN=(?P<in_iface>[\w\d]+) OUT=(?P<out_iface>[\w\d]+) PHYSIN=(?P<physin_iface>[\w\d]+) PHYSOUT=(?P<physout_iface>[\w\d]+) MAC=(?P<mac_address>[\w\d:]+) SRC=(?P<src_ip>[\d.]+) DST=(?P<dst_ip>[\d.]+) LEN=(?P<length>\d+) TOS=(?P<tos>[\w\d]+) PREC=(?P<prec>[\w\d]+) TTL=(?P<ttl>\d+) ID=(?P<id>\d+) DF PROTO=(?P<protocol>[\w]+) TYPE=(?P<type>\d+) CODE=(?P<code>\d+) ID=(?P<proto_id>\d+) SEQ=(?P<seq>\d+)$'     
            - timestamp:
                source: timestamp
                format: 02/Jan/2006:15:04:05 -0700
            - labels:
                vmid:
                rule:
                interface:
                action:
                in_iface:
                out_iface:
                physin_iface:
                physout_iface:
                mac_address:
                src_ip:
                dst_ip:
                length:
                tos:
                prec:
                ttl:
                id:
                protocol:
                type:
                code:
                seq:
```
any help would be appreciated, this config is based on a similar one I use for `mail.log`, which works. but this one does not 🤷
