### ISSUE TITLE
Grafana can not get more logs from loki 2.9

### ISSUE THREAD

**Issue by Fyne5** [grafana/loki#10776]
Dear friends,

Now, I have weird issue on my Grafana, when I fetch log, Grafana just show logs in time 1-2 minutes and not more. Here is my config file.

Could you please let me know what am I wrong? Thank you so much.

```
auth_enabled: false

server:
  http_listen_port: 3099
  http_server_read_timeout: 500s
  http_server_write_timeout: 500s
  #grpc_server_max_recv_msg_size: 4194304 (4MB)
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_recv_msg_size: 16777216
  grpc_server_max_send_msg_size: 16777216

querier:
  #query_timeout: 300s
  engine:
    timeout: 500s

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 30m
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0
  wal:
    enabled: false

schema_config:
  configs:
   - from: 2022-11-30
     store: tsdb
     object_store: filesystem
     schema: v12
     index:
       prefix: tsdb_index_
       period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/tsdb-shipper-active
    cache_location: /tmp/loki/tsdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/compactor
  shared_store: filesystem
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  query_timeout: 500s
  ingestion_rate_mb: 30
  ingestion_burst_size_mb: 50
  reject_old_samples: true
  reject_old_samples_max_age: 2160h
  retention_period: 2160h
  split_queries_by_interval: 10m
  per_stream_rate_limit: 16M
  per_stream_rate_limit_burst: 32M

chunk_store_config:
  max_look_back_period: 2160h

table_manager:
  retention_deletes_enabled: true
  retention_period: 2160h
```

For logs from loki output:
```
loki_gke-loki-1  | level=warn ts=2023-10-05T01:50:11.526504422Z caller=store.go:56 msg="running with DEPRECATED flag -store.max-look-back-period, use -querier.max-query-lookback instead."
loki_gke-loki-1  | level=warn ts=2023-10-05T01:50:11.526699442Z caller=loki.go:299 msg="using configured global timeout (\"8m20s\") as the default (can be overridden per-tenant in the limits_config). Configured engine timeout (\"8m20s\") is deprecated and will be ignored."
loki_gke-loki-1  | level=error ts=2023-10-03T10:44:34.834611801Z caller=scheduler_processor.go:106 msg="error processing requests from scheduler" err="rpc error: code = Canceled desc = context canceled" addr=127.0.0.1:9095
loki_gke-loki-1  | level=error ts=2023-10-03T10:44:34.834712282Z caller=scheduler_processor.go:106 msg="error processing requests from scheduler" err="rpc error: code = Canceled desc = context canceled" addr=127.0.0.1:9095
```
