### ISSUE TITLE
Loki ignoring config settings for dynamodb provisioned throughput

### ISSUE THREAD

**Issue by markussiebert** [grafana/loki#10789]
**Describe the bug**
We found out, that loki is burning money, if we use dynamodb for index/chunks. We manually set the provisioned read/wirte throughput to 1, but loki increased it to 300 / 1. We can see it in the loki logs:

```bash
│ level=info ts=2023-10-04T15:25:37.514518641Z caller=table_manager.go:534 msg="provisioned throughput on table, skipping" table=csa-iat-26_loki_19628 read=300 write=1  ││ level=info ts=2023-10-04T15:25:38.516856418Z caller=table_manager.go:534 msg="provisioned throughput on table, skipping" table=csa-iat-26_loki_19608 read=300 write=1  │
│ level=info ts=2023-10-04T15:25:39.514816155Z caller=table_manager.go:534 msg="provisioned throughput on table, skipping" table=csa-iat-26_loki_19615 read=300 write=1  ││ level=info ts=2023-10-04T15:25:40.513395115Z caller=table_manager.go:534 msg="provisioned throughput on table, skipping" table=csa-iat-26_loki_19616 read=300 write=1  │
│ level=info ts=2023-10-04T15:25:41.516084825Z caller=table_manager.go:534 msg="provisioned throughput on table, skipping" table=csa-iat-26_loki_19617 read=300 write=1  ││ level=info ts=2023-10-04T15:25:42.51378672Z caller=table_manager.go:534 msg="provisioned throughput on table, skipping" table=csa-iat-26_loki_19626 read=300 write=1   │
│ level=info ts=2023-10-04T15:25:43.515776276Z caller=table_manager.go:534 msg="provisioned throughput on table, skipping" table=csa-iat-26_loki_19627 read=300 write=1  ││ level=info ts=2023-10-04T15:25:44.514990569Z caller=table_manager.go:534 msg="provisioned throughput on table, skipping" table=csa-iat-26_loki_19605 read=300 write=1  │
```

our config looks like:

```yaml
/ $ cat /etc/loki/loki.yaml
analytics:
  reporting_enabled: false
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
compactor:
  shared_store: aws
  working_directory: /data/loki/boltdb-shipper-compactor
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
  wal:
    dir: /data/loki/wal
limits_config:
  enforce_metric_name: false
  max_entries_limit_per_query: 5000
  reject_old_samples: true
  reject_old_samples_max_age: 168h
memberlist:
  join_members:
  - 'loki-memberlist'
schema_config:
  configs:
  - from: "2020-05-15"
    index:
      period: 24h
      prefix: csa-iat-26_loki_
    object_store: s3
    schema: v11
    store: aws
server:
  grpc_listen_port: 9095
  http_listen_port: 3100
storage_config:
  aws:
    bucketnames: redacted
    dynamodb:
      dynamodb_url: dynamodb://eu-central-1
      kms_key_id: redacted
    region: eu-central-1
    s3forcepathstyle: true
    sse:
      kms_key_id: redacted
      type: SSE-KMS
    sse_encryption: true
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/boltdb-cache
    cache_ttl: 24h
    shared_store: s3
  filesystem:
    directory: /data/loki/chunks
table_manager:
  chunk_tables_provisioning:
    provisioned_read_throughput: 10
    provisioned_write_throughput: 10
  index_tables_provisioning:
    provisioned_read_throughput: 10
    provisioned_write_throughput: 10
  retention_deletes_enabled: true
```

**To Reproduce**
Use above config with grafana/loki:2.8.2

**Expected behavior**
Loki should respect our values configured under table_manager:

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
See logs above
