### ISSUE TITLE
WAL and tsdb_shipper WAL

### ISSUE THREAD

**Issue by yongzhang** [grafana/loki#10809]
Hi team

We're using AWS EC2 in ASG for loki nodes, so these nodes have short lifecycle, We mounted dedicated EBS for [WAL](https://grafana.com/docs/loki/latest/operations/storage/wal/) and have config like this:

```
      ingester:
        wal:
          enabled: true
          dir: /opt/loki/wal
          flush_on_shutdown: true
```

Recently we're planning to migrate loki to v2.9.x, and switch storage to tsdb, by checking the directory, we found there's also a `wal` folder in `tsdb-index` with config like this:

```
      storage_config:
        aws:
          s3: s3://${region}/${bucket_name}
          s3forcepathstyle: true
        tsdb_shipper:
          active_index_directory: /opt/loki/tsdb-index
          cache_location: /opt/loki/tsdb-cache
          shared_store: aws
```
tree:

```
# tree /opt/loki/tsdb-index/
/opt/loki/tsdb-index/
├── multitenant
│   └── index_19638
│       └── 1696744965-log-1696744164297722393.tsdb
├── per_tenant
├── scratch
│   └── aws_2023-10-08
├── uploader
│   └── name
└── wal
    ├── aws_2023-10-08
    │   └── 1696745745
    │       └── 00000000
    └── aws_2023-10-09
        └── 1696744164
            └── 00000000

11 directories, 4 files
```

So the question is, should `wal` in  `/opt/loki/tsdb-index` should also be persistent? Any other folders in this directory should be persistent? Thanks.
