### ISSUE TITLE
Data lost when migrating from v2.7.x to v2.9.x

### ISSUE THREAD

**Issue by yongzhang** [grafana/loki#10810]
Hi, team

We're migrating from v2.7.x to v2.9.x, in v2.7.x we're using aws dynamodb for index and chunks,

config for v2.7.x:

```
      target: all,table-manager

      ....

      schema_config:
        configs:
        - from: 2022-06-07
          store: aws-dynamo
          object_store: aws
          schema: v12
          index:
            prefix: loki_index_
            period: 168h
          chunks:
            prefix: loki_chunks_
            period: 168h

      storage_config:
        aws:
          s3: s3://${region}/${bucket_name}
          s3forcepathstyle: true
          dynamodb:
            dynamodb_url: dynamodb://${region}

      table_manager:
        retention_deletes_enabled: true
        retention_period: ${log_retention_period}
        chunk_tables_provisioning:
          enable_ondemand_throughput_mode: true
          provisioned_write_throughput: 0
          provisioned_read_throughput: 0
          enable_inactive_throughput_on_demand_mode: true
          inactive_write_throughput: 0
          inactive_read_throughput: 0
        index_tables_provisioning:
          enable_ondemand_throughput_mode: true
          provisioned_write_throughput: 0
          provisioned_read_throughput: 0
          enable_inactive_throughput_on_demand_mode: true
          inactive_write_throughput: 0
          inactive_read_throughput: 0
```

in v2.9.x, we switched to tsdb:

```
      target: all                   < table-manager was removed here, otherwise loki won't start

      ....

      schema_config:
        configs:
        - from: 2022-06-07
          store: aws-dynamo
          object_store: aws
          schema: v12
          index:
            prefix: loki_index_
            period: 168h
          chunks:
            prefix: loki_chunks_
            period: 168h
        - from: 2023-10-08
          store: tsdb
          object_store: aws
          schema: v12
          index:
            prefix: index_
            period: 24h

      storage_config:
        aws:
          s3: s3://${region}/${bucket_name}
          s3forcepathstyle: true
          dynamodb:
            dynamodb_url: dynamodb://${region}
        tsdb_shipper:
          active_index_directory: /opt/loki/tsdb-index
          cache_location: /opt/loki/tsdb-cache
          shared_store: aws

      compactor:
        working_directory: /opt/loki/retention
        shared_store: aws
        compaction_interval: 10m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150

      limits_config:
        retention_period: ${log_retention_period}

      table_manager:
        retention_deletes_enabled: true
        retention_period: ${log_retention_period}
        chunk_tables_provisioning:
          enable_ondemand_throughput_mode: true
          provisioned_write_throughput: 0
          provisioned_read_throughput: 0
          enable_inactive_throughput_on_demand_mode: true
          inactive_write_throughput: 0
          inactive_read_throughput: 0
        index_tables_provisioning:
          enable_ondemand_throughput_mode: true
          provisioned_write_throughput: 0
          provisioned_read_throughput: 0
          enable_inactive_throughput_on_demand_mode: true
          inactive_write_throughput: 0
          inactive_read_throughput: 0
```

We expect data before 2023-10-08 will still be handled by table-manager and new data handler by tsdb, but seems it doesn't work as expected, I lost all of my data before 2023-10-08, and I can't find any documation about this kind of migration. I did this in my dev environment so this is fine, but I need to know what's the correct way for the migration to prepare my production environment, thanks.
