### ISSUE TITLE
[type/question] How to get rid of "failed to snapshot table for reads"?

### ISSUE THREAD

**Issue by PatrykKlimowicz** [grafana/loki#10852]
**Describe the bug**
I run Loki with loki-distributed chart. After some time (usually 30 minutes) after clean start of Loki (clean start means container on Azure is empty, there are no Loki pods or PVCs) I see errors like this in ingester log stream:

```bash
level=debug ts=2023-10-11T07:28:58.287915272Z caller=checkpoint.go:377 msg="writing series" size="4.8 kB"
level=info ts=2023-10-11T07:28:58.327687739Z caller=table_manager.go:136 index-store=boltdb-shipper-2020-09-07 msg="uploading tables"
level=info ts=2023-10-11T07:28:58.41624166Z caller=table_manager.go:171 index-store=boltdb-shipper-2020-09-07 msg="handing over indexes to shipper"
level=info ts=2023-10-11T07:28:58.416338363Z caller=table.go:318 msg="handing over indexes to shipper loki_index_19641"
level=info ts=2023-10-11T07:28:58.416349764Z caller=table.go:334 msg="finished handing over table loki_index_19641"
level=debug ts=2023-10-11T07:28:58.416358164Z caller=table.go:107 msg="snapshotting table loki_index_19641"
level=debug ts=2023-10-11T07:28:58.416365164Z caller=table.go:110 msg="checking db 1697008759 for snapshot"
level=error ts=2023-10-11T07:28:58.484433233Z caller=table_manager.go:184 index-store=boltdb-shipper-2020-09-07 msg="failed to snapshot table for reads" table=loki_index_19641 err="invalid database"
```

In the code I can see that:

```go
err = table.Snapshot()
if err != nil {
  // we do not want to stop handing over of index due to failures in snapshotting them so logging just the error here.
  level.Error(util_log.Logger).Log("msg", "failed to snapshot table for reads", "table", table.name, "err", err)
}
```

So I assume that this error is NOT critical, and the code was added to spare some CPU cycles according to the author. However, it is pretty annoying to see the error message over and over again for every index after the first flush to Azure Storage happened. 

Is it possible to know the possible root cause of this issue?

**To Reproduce**
1. Loki distributed chart version `0.74.6`
2. Promtail helm chart version `6.15.2`
3. Used this values and some combination of it (see comments about options tries):

<details>
<summary>values.yaml</summary>
<be>

```yaml
loki:
  # this is just for testing purposes like adding curl and setting log_level
  podSecurityContext:
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  containerSecurityContext:
    readOnlyRootFilesystem: false
  structuredConfig:
    schema_config:
      configs:
      - from: 2020-09-07
        store: boltdb-shipper
        object_store: azure
        schema: v11
        index:
          prefix: loki_index_
          period: 24h

    storage_config:
      boltdb_shipper:
        shared_store: azure
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h

      azure:
        environment: AzureGlobal
        account_name: logs
        account_key: "my-secret-key"
        container_name: logs

    limits_config:
      enforce_metric_name: false
      # tried with false as well
      reject_old_samples: true
      reject_old_samples_max_age: 336h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      retention_period: 336h

    # tried with and w/o compactor
    compactor:
      # tried w/o retention as well
      retention_enabled: true
      shared_store: azure
      working_directory: /var/loki/retention
      compaction_interval: 10m
      retention_delete_delay: 2h
      retention_delete_worker_count: 150

# I ran ingester with chunk_encoding: gzip and chunk_encoding: snappy
ingester:
  persistence:
    enabled: true
    claims:
      - name: data
        size: 100Gi  # smallest available on premium Azure SA
        storageClass: azurefile-csi-loki

querier:
  persistence:
    enabled: true
    size: 100Gi  # smallest available on premium Azure SA
    storageClass: azurefile-csi-loki

compactor:
  enabled: true
  persistence:
    enabled: true
    size: 100Gi # smallest available on premium Azure SA
    storageClass: azurefile-csi-loki
```

In the default values file there is this setting:

```yaml
  storageConfig:
    boltdb_shipper:
      shared_store: filesystem
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 168h
    filesystem:
      directory: /var/loki/chunks
```

the above causes the `filesystem` to be set in final loki config file, but since I use Azure I tried to remove that and ran the loki with this setting - no luck in both scenarios. Is this needed? 

</details>

**Expected behavior**

I would like to see no errors like:

```bash
level=info ts=2023-10-11T07:39:58.32682277Z caller=table_manager.go:136 index-store=boltdb-shipper-2020-09-07 msg="uploading tables"
level=info ts=2023-10-11T07:39:58.326872471Z caller=index_set.go:86 msg="uploading table loki_index_19641"
level=info ts=2023-10-11T07:39:58.326881272Z caller=index_set.go:107 msg="finished uploading table loki_index_19641"
level=info ts=2023-10-11T07:39:58.326890472Z caller=index_set.go:185 msg="cleaning up unwanted indexes from table loki_index_19641"
level=info ts=2023-10-11T07:39:58.416660365Z caller=table_manager.go:171 index-store=boltdb-shipper-2020-09-07 msg="handing over indexes to shipper"
level=info ts=2023-10-11T07:39:58.416746667Z caller=table.go:318 msg="handing over indexes to shipper loki_index_19641"
level=info ts=2023-10-11T07:39:58.416756868Z caller=table.go:334 msg="finished handing over table loki_index_19641"
level=debug ts=2023-10-11T07:39:58.416764868Z caller=table.go:107 msg="snapshotting table loki_index_19641"
level=debug ts=2023-10-11T07:39:58.416771568Z caller=table.go:110 msg="checking db 1697009400 for snapshot"
level=debug ts=2023-10-11T07:39:58.440459852Z caller=checkpoint.go:377 msg="writing series" size="7.0 kB"
**level=error ts=2023-10-11T07:39:58.485972367Z caller=table_manager.go:184 index-store=boltdb-shipper-2020-09-07 msg="failed to snapshot table for reads" table=loki_index_19641 err="invalid database"**
```

I'd rather see clean output maybe even a success message when in debug mode 😄 

**Environment:**
 - Azure AKS v1.25.6
 - Loki and promtail versions are above
 - Azure Storage Account: Premium LRS for File Storage + Premium LRS for Blob Storage (as suggested in different issues)

**Screenshots, Promtail config, or terminal output**

Promtail config is as simple as adding the URL:

```yaml
config:
  clients:
    - url: http://loki-loki-distributed-gateway/loki/api/v1/push
```

I do not really care if the org_id is fake or whatever. 

**Any inputs?** 

Just to clarify: I can see logs on Grafana, I can filter them, change time range etc. I just do not really understand what is the reason of this snapshotting error and it is pretty hard to find some information that will match more or less my case.
