### ISSUE TITLE
Retention period for each container in promtail with loki 

### ISSUE THREAD

**Issue by vadlakiran** [grafana/loki#10979]
i am not able to segrate the logs some of the microservice container having many log i want retention period as 10 days and some of the container i need to give 30 day, using loki with promtail /fluentbit

**Describe the bug**

**To Reproduce**
1. Started Loki (SHA or version) lates
2. Started Promtail (SHA or version) to tail '...' lates
3. Query: `{} term`

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop] promtail installed on k8s and loki and grafana installed on bare-metal
 - Deployment tool: [e.g., helm, jsonnet] helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by vlad-diachenko** [comment]
hey @vadlakiran. do you mean you want to have different retention periods for the different sets of logs?

**Comment by vlad-diachenko** [comment]
if so, you can use retention streams to specify custom retention period for the streams that matches different stream selectors:  https://grafana.com/docs/loki/latest/operations/storage/retention/#configuring-the-retention-period

here is an example that you also can find in our docs, that configures different retention period for different containers(but you can use any labels to select different streams that you need)
```yaml
        retention_period: 168h
        retention_stream:
        - selector: '{container="nginx"}'
          priority: 2
          period: 336h
        - selector: '{container="loki"}'
          priority: 1
          period: 72h
```
