### ISSUE TITLE
Unable to Query Historical Data After Restarting Loki Ingester Component

### ISSUE THREAD

**Issue by EverHopeful** [grafana/loki#10975]
I'm using a microservices architecture deployment of Loki with multi-tenancy and caching enabled. I've noticed that each time I restart the Ingester component of Loki, which generally takes about 10 minutes to complete, there is a loss of data continuity when querying from Grafana or historical data becomes unqueryable. The query phenomenon is as shown in the attached screenshot.

Here's a screenshot of my query results：
![48210b68-94e8-403f-a8a8-42aedff5c135](https://github.com/grafana/loki/assets/108403536/ba91a8b6-98b6-4092-b6bb-673e28f6fe60)
![image](https://github.com/grafana/loki/assets/108403536/d1379eb4-a5f3-4539-92e4-61b19a2f7541)

My configuration is as follows:
```
    auth_enabled: true
    chunk_store_config:
      chunk_cache_config:
        redis:
          endpoint: redis:6379
          expiration: 1440m
          pool_size: 0
          timeout: 500ms
      max_look_back_period: 0s
      write_dedupe_cache_config:
        redis:
          endpoint: redis:6379
          expiration: 1440m
          pool_size: 0
          timeout: 500ms
    common:
      compactor_address: http://loki-distributed-compactor:3100
    compactor:
      shared_store: filesystem
    distributor:
      ring:
        kvstore:
          store: memberlist
    frontend:
      compress_responses: true
      log_queries_longer_than: 5s
      tail_proxy_url: http://loki-distributed-querier:3100
    frontend_worker:
      frontend_address: loki-distributed-query-frontend-headless:9095
    ingester:
      chunk_block_size: 26214400
      chunk_encoding: snappy
      chunk_idle_period: 30m
      chunk_retain_period: 5m
      chunk_target_size: 15728640
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal
    ingester_client:
      grpc_client_config:
        grpc_compression: gzip
    limits_config:
      enforce_metric_name: false
      ingestion_burst_size_mb: 128
      ingestion_rate_mb: 64
      max_cache_freshness_per_query: 10m
      max_entries_limit_per_query: 50000
      max_query_series: 100000
      max_streams_matchers_per_query: 100000
      per_stream_rate_limit: 50M
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    memberlist:
      join_members:
      - loki-distributed-memberlist
    querier:
      multi_tenant_queries_enabled: true
    query_range:
      align_queries_with_step: true
      cache_results: true
      max_retries: 5
      parallelise_shardable_queries: true
      results_cache:
        cache:
          redis:
            endpoint: redis:6379
            expiration: 1440m
    ruler:
      alertmanager_url: https://alertmanager.xx
      external_url: https://alertmanager.xx
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      storage:
        local:
          directory: /etc/loki/rules
        type: local
    runtime_config:
      file: /var/loki-distributed-runtime/runtime.yaml
    schema_config:
      configs:
      - from: "2020-10-24"
        index:
          period: 24h
          prefix: index_
        object_store: s3
        schema: v12
        store: boltdb-shipper
    server:
      grpc_listen_port: 9095
      grpc_server_max_recv_msg_size: 27106425
      http_listen_port: 3100
    storage_config:
      aws:
        access_key_id: My_ak
        bucketnames: local-loki-test
        endpoint: http://local-loki-test.oss***.aliyuncs.com
        insecure: true
        region: ***
        s3forcepathstyle: true
        secret_access_key: My_sk
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 24h
        shared_store: s3
      index_queries_cache_config:
        redis:
          endpoint: redis:6379
          expiration: 1440m
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
---
    overrides:
      <tanent_a>:
        ingestion_rate_mb: 100
        max_chunks_per_query: 100000
        max_streams_per_user: 100000
        split_queries_by_interval: 15m
      <tanent_b>:
        ingestion_rate_mb: 100
        max_chunks_per_query: 100000
        max_streams_per_user: 100000
        split_queries_by_interval: 15m
```

I stumbled upon an error log in my queries component as follows:
```
{"log":"level=info ts=2023-10-20T07:17:38.045630662Z caller=table_manager.go:195 index-store=boltdb-shipper-2020-10-24 msg=\"downloading all files for table index_19650\"\n","stream":"stderr","time":"2023-10-20T07:17:38.053451724Z"}
{"log":"level=error ts=2023-10-20T07:17:38.071052094Z caller=index_set.go:285 table-name=index_19650 user-id=hdmap-ack-nonprod msg=\"sync failed, retrying it\" err=\"NoSuchKey: The specified key does not exist.\\n\\tstatus code: 404, request id: 653229924929FD33344331C8, host id: \"\n","stream":"stderr","time":"2023-10-20T07:17:38.153145658Z"}
```

Any help would be greatly appreciated.
