### ISSUE TITLE
Promtail - Ability to filter for labels in clients config

### ISSUE THREAD

**Issue by butschi84** [grafana/loki#10981]
**problem**
We run promtail to collect logs from our openshift kubernetes Plattform
- The openshift plattform itself is managed by our team `openshift-mgmt`.
- The business applications / workloads / pods that run on the plattform are managed by our team `businessapp-mgmt`.

This means I should be able to send the logs with label, say "team=openshift-mgmt" to loki-tenant `openshift-mgmt` and logs with "team=businessapp-mgmt" to loki tenant `businessapp-mgmt`.

I see no configuration option at the moment to achieve this.

**possible solution**
I suggest a modification in the promtail config "clients" section to be able to filter the logs like:

```
clients:
   - url: http://loki
     headers:
        X-Scope-OrgID: openshift-mgmt
     label_filters: 
       - labels: [team]
         regex: openshift-mgmt
	 action: keep
   - url: http://loki
     headers:
        X-Scope-OrgID: businessapp-mgmt
     label_filters: 
       - labels: [team]
         regex: businessapp-mgmt
	 action: keep
````

**Alternatives**
I found no way to achieve the desired split-sending with the available config options. Other tools like fluentD support this split-sending
