### ISSUE TITLE
ingester pod stuck in infinite loop, and pod never becomes ready, after pod is evicted

### ISSUE THREAD

**Issue by pdfruth** [grafana/loki#10988]
**Describe the bug**
I have installed the Red Hat OpenShift Loki operator V5.7.7 and the Red Hat OpenShift Logging V5.7.7 operator on an OpenShift V4.12.32 cluster.
According to the configuration of the Loki ingester pod, the following image is being used;
```
registry.redhat.io/openshift-logging/logging-loki-rhel8@sha256:81b5aa1aa2bc04a8a0227e5578bc6fbd0096e3e9791c869546669f33148e4955
```

Based on skopeo inspect of the image, this is Loki V2.9.2
```    "Created": "2023-10-18T01:03:43.890837169Z",
    "DockerVersion": "",
    "Labels": {
        "architecture": "x86_64",
        "build-date": "2023-10-18T00:51:43",
        "com.redhat.component": "logging-loki-container",
        "com.redhat.license_terms": "https://www.redhat.com/agreements",
        "description": "Horizontally-scalable, highly-available, multi-tenant log aggregation system inspired by Prometheus.",
        "distribution-scope": "public",
        "io.buildah.version": "1.29.0",
        "io.k8s.description": "Horizontally-scalable, highly-available, multi-tenant log aggregation system inspired by Prometheus.",
        "io.k8s.display-name": "OpenShift Loki",
        "io.openshift.build.commit.id": "43ccda28b09a9ec2ddc281ed44e552ed95357893",
        "io.openshift.build.commit.url": "https://github.com/openshift/loki/commit/43ccda28b09a9ec2ddc281ed44e552ed95357893",
        "io.openshift.build.source-location": "https://github.com/openshift/loki",
        "io.openshift.expose-services": "",
        "io.openshift.maintainer.component": "Logging",
        "io.openshift.maintainer.product": "OpenShift Container Platform",
        "io.openshift.tags": "openshift,logging,loki",
        "maintainer": "AOS Logging \u003cteam-logging@redhat.com\u003e",
        "name": "openshift-logging/logging-loki-rhel8",
        "release": "1",
        "summary": "Provides the latest release of Red Hat Universal Base Image 8.",
        "url": "https://access.redhat.com/containers/#/registry.access.redhat.com/openshift-logging/logging-loki-rhel8/images/v2.9.2-1",
        "vcs-ref": "1ca98adefc21aedd6dc8696d4563d0ff023ae1d7",
        "vcs-type": "git",
        "vendor": "Red Hat, Inc.",
        "version": "v2.9.2"
    },
```
After initial installation and configuration of the Loki operator, all of the logs are successfully ingested and I'm able to query logs.
However, after the node upon which the Loki ingester pod runs is drained (and thus the Loki ingester pod is evicted), when the Loki ingester pod restarts on one of the other available nodes in the OpenShift cluster, the Loki ingester pod never becomes "ready".  I also notice that the pod appears to be stuck in an infinate CPU-bound loop, continuously using approximately 1300 millicore of CPU.

At this point it is no longer possible to query current/recent logs, since the ingester appears to have ceased ingesting logs.

**To Reproduce**
1. Install/configure the Loki operator on an OpenShift cluster.
2. Drain the node upon which the ingester pod runs, thus causing the pod to be restarted on some other node.
3. Notice the ingester pod is now stuck in an infinate CPU-bound loop.  And the following messages can be seen endlessly repeating every 60 seconds in the ingester pod logs;
```
...
level=info ts=2023-10-21T18:37:07.861376414Z caller=table_manager.go:136 index-store=boltdb-shipper-2020-10-11 msg="uploading tables"
level=info ts=2023-10-21T18:37:07.86142031Z caller=index_set.go:86 msg="uploading table index_19651"
level=info ts=2023-10-21T18:37:07.861427157Z caller=index_set.go:107 msg="finished uploading table index_19651"
level=info ts=2023-10-21T18:37:07.861433148Z caller=index_set.go:185 msg="cleaning up unwanted indexes from table index_19651"
level=info ts=2023-10-21T18:37:08.140668518Z caller=table_manager.go:171 index-store=boltdb-shipper-2020-10-11 msg="handing over indexes to shipper"
level=info ts=2023-10-21T18:37:08.140746883Z caller=table.go:318 msg="handing over indexes to shipper index_19651"
level=info ts=2023-10-21T18:37:08.140753365Z caller=table.go:334 msg="finished handing over table index_19651"

level=info ts=2023-10-21T18:38:07.861517434Z caller=table_manager.go:136 index-store=boltdb-shipper-2020-10-11 msg="uploading tables"
level=info ts=2023-10-21T18:38:07.86154688Z caller=index_set.go:86 msg="uploading table index_19651"
level=info ts=2023-10-21T18:38:07.86155374Z caller=index_set.go:107 msg="finished uploading table index_19651"
level=info ts=2023-10-21T18:38:07.861558936Z caller=index_set.go:185 msg="cleaning up unwanted indexes from table index_19651"
level=info ts=2023-10-21T18:38:08.140677379Z caller=table_manager.go:171 index-store=boltdb-shipper-2020-10-11 msg="handing over indexes to shipper"
level=info ts=2023-10-21T18:38:08.140749573Z caller=table.go:318 msg="handing over indexes to shipper index_19651"
level=info ts=2023-10-21T18:38:08.140755897Z caller=table.go:334 msg="finished handing over table index_19651"

level=info ts=2023-10-21T18:39:07.861997734Z caller=table_manager.go:136 index-store=boltdb-shipper-2020-10-11 msg="uploading tables"
level=info ts=2023-10-21T18:39:07.86203594Z caller=index_set.go:86 msg="uploading table index_19651"
level=info ts=2023-10-21T18:39:07.862042633Z caller=index_set.go:107 msg="finished uploading table index_19651"
level=info ts=2023-10-21T18:39:07.862048579Z caller=index_set.go:185 msg="cleaning up unwanted indexes from table index_19651"
level=info ts=2023-10-21T18:39:08.140557821Z caller=table_manager.go:171 index-store=boltdb-shipper-2020-10-11 msg="handing over indexes to shipper"
level=info ts=2023-10-21T18:39:08.140655895Z caller=table.go:318 msg="handing over indexes to shipper index_19651"
level=info ts=2023-10-21T18:39:08.140664363Z caller=table.go:334 msg="finished handing over table index_19651"

... above is endlessly repeated every 60 seconds
```

4. After the node is drained, and pods are restarted elsewhere in the cluster, the following are the pod status
```
$ oc -n openshift-logging get pods 

NAME                                               READY   STATUS    RESTARTS   AGE
cluster-logging-operator-6dd4cccc47-tmfbj          1/1     Running   0          7h7m
collector-22dcl                                    2/2     Running   0          5h45m
collector-dwcct                                    2/2     Running   0          5h45m
collector-dxdf9                                    2/2     Running   0          5h45m
collector-gbrhh                                    2/2     Running   0          5h45m
collector-gknsr                                    2/2     Running   0          5h45m
collector-sdvkz                                    2/2     Running   0          5h45m
logging-view-plugin-7547cd9d5f-25p2r               1/1     Running   0          5h45m
lokistack-sample-compactor-0                       1/1     Running   0          5h48m
lokistack-sample-distributor-664c7cb7c6-kt6tg      1/1     Running   0          5h48m
lokistack-sample-gateway-85cfc7d7c7-grrmr          2/2     Running   0          5h48m
lokistack-sample-gateway-85cfc7d7c7-swfgh          2/2     Running   0          5h48m
lokistack-sample-index-gateway-0                   1/1     Running   0          5h48m
lokistack-sample-ingester-0                        0/1     Running   0          107m
lokistack-sample-querier-6964f67479-f4mt8          1/1     Running   0          5h48m
lokistack-sample-query-frontend-74996597d7-4qbcd   1/1     Running   0          5h48m
```

**Expected behavior**
ingester pod should restart, and continue normally ingesting logs.

**Environment:**
 - Infrastructure: OpenShift V4.12.32 + Logging Operator V5.7.7 + Loki Operator V5.7.7
 - Deployment tool: OpenShift Loki operator

EDIT: Adding CRs for LokiStack and ClusterLogging 
```
apiVersion: loki.grafana.com/v1
kind: LokiStack
  name: lokistack-sample
  namespace: openshift-logging
spec:
  hashRing:
    memberlist:
      instanceAddrType: podIP
    type: memberlist
  limits:
    global:
      ingestion:
        ingestionBurstSize: 16
        ingestionRate: 8
      queries:
        queryTimeout: 3m
      retention:
        days: 7
  managementState: Managed
  size: 1x.extra-small
  storage:
    schemas:
      - effectiveDate: '2020-10-11'
        version: v11
    secret:
      name: loki-s3-secret
      type: s3
    tls:
      caKey: service-ca.crt
      caName: ingress-ca
  storageClassName: ocs-storagecluster-ceph-rbd
  tenants:
    mode: openshift-logging
```

```
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
  name: instance
  namespace: openshift-logging
spec:
  collection:
    type: vector
  logStore:
    lokistack:
      name: lokistack-sample
    type: lokistack
  managementState: Managed
```
