### ISSUE TITLE
possible memory leak in structured metadata

### ISSUE THREAD

**Issue by shimasima2323** [grafana/loki#10994]
**Describe the bug**
I'm trying to push log records into loki via push JSON API, if log records contains structured metadata, loki memory usage increases over time with no limit, i played with some configs like using s3 backend, or changing cache settings with no success.

**To Reproduce**

1. Started Loki with this config:
```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    resync_interval: 5s
    shared_store: s3
  aws:
   s3: s3://admin:supersecret@minio.:9000/loki
   s3forcepathstyle: true

query_scheduler:
  max_outstanding_requests_per_tenant: 32768

querier:
  max_concurrent: 16

limits_config:
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 100
  reject_old_samples: false
  allow_structured_metadata: true

ruler:
  alertmanager_url: http://localhost:9093

analytics:
 reporting_enabled: true

```
2. Started to send log batches to push api '...'

**Expected behavior**
the ingestions continues with proper memory consumption. 

**Environment:**
 - Infrastructure: docker container on debian host
 - Deployment tool: docker compose
