### ISSUE TITLE
`-querier.cache-index-stats-results` does not work as I expacted

### ISSUE THREAD

**Issue by pyo-counting** [grafana/loki#10992]
**Describe the bug**
Loki [documentation](https://grafana.com/docs/loki/latest/configure/#query_range) describe below.

> When `-querier.cache-index-stats-results` is true and `index_stats_results_cache` block is not configured, `results_cache` block configuration will be used.

But it doesn't work as docs describe. it works weird.

**To Reproduce**
Loki config file
``` yaml
analytics:
  reporting_enabled: false
auth_enabled: true
common:
  compactor_address: 'loki-backend'
  compactor_grpc_address: 'loki-backend.loki-ns.svc.cluster.local:9095'
  path_prefix: /var/loki
  replication_factor: 3
  ring:
    kvstore:
      store: memberlist
  storage:
    hedging:
      at: 250ms
      max_per_second: 20
      up_to: 3
    s3:
      bucketnames: psy-test-s3
      insecure: false
      region: ap-northeast-2
      s3forcepathstyle: false
compactor:
  compactor_ring:
    kvstore:
      store: memberlist
  retention_enabled: true
  shared_store: s3
  shared_store_key_prefix: compoactor_index/
  working_directory: /var/loki/compactor
distributor:
  rate_store:
    debug: true
  ring:
    kvstore:
      store: memberlist
  write_failures_logging:
    add_insights_label: true
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  query_stats_enabled: true
  scheduler_address: ""
  scheduler_dns_lookup_period: 3s
frontend_worker:
  match_max_concurrent: true
  scheduler_address: ""
index_gateway:
  mode: ring
  ring:
    kvstore:
      store: memberlist
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
limits_config:
  enforce_metric_name: false
  max_cache_freshness_per_query: 10m
  max_line_size: 256KB
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 20MB
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 260w
  shard_streams:
    enabled: false
  split_queries_by_interval: 15m
memberlist:
  join_members:
  - loki-memberlist
querier:
  max_concurrent: 16
  tail_max_duration: 30m
query_range:
  align_queries_with_step: true
  cache_index_stats_results: true
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 150
        ttl: 30m
      enable_fifocache: false
    compression: snappy
query_scheduler:
  max_outstanding_requests_per_tenant: 32768
  querier_forget_delay: 60s
  scheduler_ring:
    kvstore:
      store: memberlist
  use_scheduler_ring: true
ruler:
  storage:
    s3:
      bucketnames: psy-test-s3
      insecure: false
      region: ap-northeast-2
      s3forcepathstyle: false
    type: s3
runtime_config:
  file: /etc/loki/runtime-config/runtime-config.yaml
schema_config:
  configs:
  - from: "1993-07-29"
    index:
      period: 24h
      prefix: tsdb_index_
    object_store: s3
    schema: v12
    store: tsdb
server:
  grpc_listen_port: 9095
  http_listen_port: 3100
  log_format: logfmt
  log_level: debug
  log_request_at_info_level_enabled: true
  log_request_headers: true
  log_source_ips_enabled: true
storage_config:
  hedging:
    at: 250ms
    max_per_second: 20
    up_to: 3
  tsdb_shipper:
    active_index_directory: /var/loki/ingester/index-write
    cache_location: /var/loki/index/tsdb/cache
    index_gateway_client:
      log_gateway_requests: true
      server_address: loki-backend:9095
    shared_store: s3
    shared_store_key_prefix: tsdb_index/
tracing:
  enabled: true
```
- `-querier.cache-results` is true
- `results_cache` block is configured to using `embedded_cache`(not fifocache)

**Expected behavior**
I configure `-querier.cache-index-stats-results` values to true and doesn't not configure `index_stats_results_cache`, so `embedded_cache` configuration will be used for `index_stats_results_cache ` block.

**Environment:**
 - Infrastructure: EKS 1.24 (container runtime: containerd)
 - Deployment tool: [loki helm](https://artifacthub.io/packages/helm/grafana/loki/5.34.0) (version: 5.34.0)

**Screenshots, Promtail config, or terminal output**
Loki simple scalable deployment mode is deployed and k8s read target Pod print below error
``` log
panic: duplicate metrics collector registration attempted

goroutine 1 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0x2787820?, {0xc000233bd0?, 0x1, 0x5?})
	/src/loki/vendor/github.com/prometheus/client_golang/prometheus/registry.go:405 +0x78
github.com/prometheus/client_golang/prometheus/promauto.Factory.NewCounter({{0x2e9b110?, 0x43908c0?}}, {{0x2787820, 0x7}, {0x277e3c6, 0x5}, {0x278fbd2, 0xb}, {0x27f95a3, 0x2a}, ...})
	/src/loki/vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go:265 +0xfe
github.com/grafana/loki/pkg/storage/chunk/cache.NewFifoCache({0xc000c13248, 0x17}, {{0xc0007eff40, 0x9}, 0x0, 0x1a3185c5000, 0x0, 0x0, 0xdf8475800}, {0x2e9b110, ...}, ...)
	/src/loki/pkg/storage/chunk/cache/fifo_cache.go:148 +0x685
github.com/grafana/loki/pkg/storage/chunk/cache.New({0x0, 0x34630b8a000, {0xa, 0x2710, 0x40000000}, {0x0, 0x400, 0x64}, {{0x0, 0x0}, ...}, ...}, ...)
	/src/loki/pkg/storage/chunk/cache/cache.go:143 +0x3d0
github.com/grafana/loki/pkg/querier/queryrange.newResultsCacheFromConfig({{0x0, 0x34630b8a000, {0xa, 0x2710, 0x40000000}, {0x0, 0x400, 0x64}, {{0x0, 0x0}, ...}, ...}, ...}, ...)
	/src/loki/pkg/querier/queryrange/roundtrip.go:80 +0x25e
github.com/grafana/loki/pkg/querier/queryrange.NewTripperware({{0x0, 0x1, {{0x0, 0x34630b8a000, {...}, {...}, {...}, {...}, {...}, {...}, ...}, ...}, ...}, ...}, ...)
	/src/loki/pkg/querier/queryrange/roundtrip.go:126 +0x4b1
github.com/grafana/loki/pkg/loki.(*Loki).initQueryFrontendTripperware(0xc000b24000)
	/src/loki/pkg/loki/modules.go:717 +0x289
github.com/grafana/dskit/modules.(*Manager).initModule(0xc0007c71a0, {0x7ffdd60a36f3, 0x4}, 0xc0000cec90?, 0x1?)
	/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:136 +0x1f7
github.com/grafana/dskit/modules.(*Manager).InitModuleServices(0x1?, {0xc000712710, 0x1, 0xc000c93080?})
	/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108 +0xd8
github.com/grafana/loki/pkg/loki.(*Loki).Run(0xc000b24000, {0xc00098e3c0?})
	/src/loki/pkg/loki/loki.go:461 +0x4a
main.main()
```
