### ISSUE TITLE
Tablemanager creates provisioned table when provisioned_throughput_on_demand_mode is set to true

### ISSUE THREAD

**Issue by simonrondelez** [grafana/loki#1101]
**Describe the bug**
There is no way to prevent Tablemanager to create the Dynamodb tables first in provisioned mode before switching it to on-demand.

**To Reproduce**

configure tablemanager like
```yaml
    table_manager: 
      retention_deletes_enabled: true
      retention_period: 168h
      index_tables_provisioning:
        provisioned_throughput_on_demand_mode: true
        inactive_throughput_on_demand_mode: true
``` 
see behaviour on the created Dynamodb tables

**Expected behavior**
The Dynamodb tables should be created in on-demand mode at initial creation.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Backend: s3 for chunks and Dynamodb for chards

**Screenshots, promtail config, or terminal output**
<img width="1241" alt="screenshot creating" src="https://user-images.githubusercontent.com/2873948/66033155-fedd6f00-e506-11e9-9bdc-87f6a664848b.png">
<img width="1349" alt="screenshot updating" src="https://user-images.githubusercontent.com/2873948/66033159-01d85f80-e507-11e9-9b92-49d0206f69b0.png">
