### ISSUE TITLE
Promtail Dokcer memory leak since v2.5.0 

### ISSUE THREAD

**Issue by Alexsandr-Random** [grafana/loki#11021]
**Describe the bug**
When we using the same config in promtail v2.4.1 and v.2.5.0 in the same environment we got memory leak when using promtail v.2.5.0+ in docker environment. memory slowly growth and then cause OOM or just floating under 100%
Docker containers we running via Nomad.  
We also separated promtail task in own container and we are 100% sure that it is promtail itself cause memory growth. 
Its not pipline issue or misconfiguration or large amount of log files. Even if logs not writing for a long time or we not using piplines at all  - memory still growth. 
In future versions we seen same behavior like in v.2.5.0+
p.s. promtail stderr empty. 

**Expected behavior**
Same memory usage behavior as in  v2.4.1 

**Screenshots, Promtail config, or terminal output**
Here is our typical promtail config: 
```
server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://our-loki-server.com/api/prom/push
  batchsize: 1048576 # default
  batchwait: 1s  # default
  backoff_config:
    min_period: 2s  # default 500
    max_period: 1m  # default 5m
    max_retries: 100 # default 10
  
scrape_configs:
  - job_name: default
    static_configs:
    - targets:
        - localhost
      labels:
        node: <% env "attr.unique.hostname" %>
        app: sandbox-dev
        __path__: "/alloc/logs/node.std???.{?,??,???}"
    pipeline_stages:
      - regex:
          source: filename
          expression: "/alloc/logs/(?P<filename>.*)"
      - template:
          source: filename
          template: '{{ .Value }}'
      - labels:
          filename:
```
