### ISSUE TITLE
loki's log rotention does not work when loki pod restarts

### ISSUE THREAD

**Issue by eeliu** [grafana/loki#11035]
**Describe the bug**
Normally, the log rotention feature works well. 
But if loki pod restart happens during retention_period, the previous logs which generated before loki pod restarts will be not deleted. My loki version: 2.8.5

**To Reproduce**
* Deploy loki pod with 2.8.5 version(configuration will be shown later)
* Send some logs to loki with `retention_period: 24.hours, loki's statefulset's replicas: 1`
* Confirm the chunk data and index data are already sent to s3 storage successfully.
  - Normally, will wait some time
* Recreate the loki pod by `kubectl delete pod loki-0 -n $namespace`
* The chunk data and the index data still exist after wait 24.hours + 2.hours(retention_delete_delay)

**Expected behavior**
* Normally, the log rotention feature works well.

(If don't do above step4(e.g. recreate the loki pod), the logs(index data and chunk data) will be deleted from s3 storage too)

**Environment:**
* Deploy loki as pod
* loki version: 2.8.5

**Loki configuration**
```
apiVersion: v1
data:
  loki.yaml: |-
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 0s
    compactor:
      shared_store: s3
      working_directory: /data/loki/boltdb-shipper-compactor
      retention_enabled: true
      compaction_interval: 10m
      retention_delete_delay: 2h
    distributor:
      ring:
        kvstore:
          store: memberlist
    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
      query_store_max_look_back_period: 0
      wal:
        enabled: true
        dir: /data/wal
    querier:
      max_concurrent: 20
    limits_config:
      ingestion_rate_mb: 8
      ingestion_burst_size_mb: 16
      per_stream_rate_limit: 5MB
      per_stream_rate_limit_burst: 15MB
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 24h
      retention_period: 24h
    memberlist:
      join_members:
        - loki-headless
    schema_config:
      configs:
      - from: "2022-11-20"
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          period: 24h
          prefix: index_
        chunks:
          period: 24h
          prefix: chunks_
    server:
      http_listen_port: 3100
      log_level: warn
    storage_config:
      object_prefix: sub-folder
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: s3
    common:
      storage:
        s3:
          s3: s3://s3Address/$myBucket
          s3forcepathstyle: true
```
