### ISSUE TITLE
Logs become more heavier since 2.9.2

### ISSUE THREAD

**Issue by timansky** [grafana/loki#11063]
**Describe the bug**
After update to 2.9.2 from 2.8.3 space utilization  in s3 become x3 bigger.

**To Reproduce**
<details>
<summary>Ingester config</summary>

```
auth_enabled: true

common:
  storage:
    s3:
      bucketnames: loki-00,loki-01,loki-02,loki-03,loki-04,loki-05,loki-06,loki-07,loki-08,loki-09
      endpoint: s3-storage:7480
      region: US
      access_key_id: SOME_KEY
      secret_access_key: SOME_KEY
      insecure: true
      sse_encryption: false
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 0s
        insecure_skip_verify: true
      s3forcepathstyle: true

  ring:
    kvstore:
      store: etcd
      etcd:
        endpoints:
          - monitoring-loki-d1:2379
          - monitoring-loki-d2:2379
          - monitoring-loki-d3:2379
    heartbeat_timeout: 1m
    heartbeat_period: 15s
  replication_factor: 1

schema_config:
  configs:
    - from: 2023-04-18
      store: tsdb
      object_store: s3
      schema: v12
      index:
        period: 24h
        prefix: index_

storage_config:
  tsdb_shipper:
    shared_store: s3
    active_index_directory: /var/lib/loki/tsdb/index
    cache_location: /var/lib/loki/tsdb/cache
    query_ready_num_days: 0
    index_gateway_client:
      server_address: loki-index-gateway:9095
    enable_postings_cache: true
    use_boltdb_shipper_as_backup: false

  index_queries_cache_config:
    enable_fifocache: false
    embedded_cache:
      enabled: false

chunk_store_config:
  chunk_cache_config:
    enable_fifocache: false
    embedded_cache:
      enabled: false
  write_dedupe_cache_config:
    enable_fifocache: false
    embedded_cache:
      enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester_client:
  pool_config:
    client_cleanup_period: 5s
    health_check_ingesters: true
  grpc_client_config:
    grpc_compression: snappy

ingester:
  autoforget_unhealthy: true
  chunk_idle_period: 6h
  chunk_encoding: snappy 
  lifecycler:
    heartbeat_period: 5s
    final_sleep: 15s
    min_ready_duration: 15s
    num_tokens: 512
    readiness_check_ring_health: false
  max_chunk_age: 6h
  max_transfer_retries: 0 
  query_store_max_look_back_period: 0 # For S3 this value must always be left as 0
  sync_period: 5m
  sync_min_utilization: 0.8
  wal:
    enabled: true
    dir: /var/lib/loki/wal
    flush_on_shutdown: false
    replay_memory_ceiling: 21GB  

limits_config:
  ingestion_rate_strategy: global
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 200
  enforce_metric_name: false
  max_streams_per_user: 0
  max_global_streams_per_user: 1000000
  max_cache_freshness_per_query: 1m
  max_query_length: 720h
  max_query_lookback: 720h
  query_timeout: 2m
  reject_old_samples: true
  reject_old_samples_max_age: 96h
  unordered_writes: true

tracing:
  enabled: true

analytics:
  reporting_enabled: false
```
</details>

**Environment:**
 - Infrastructure: mixed Kubernetes + vm
 - Deployment tool: Manual

**Screenshots, Promtail config, or terminal output**
![lokiupdate](https://github.com/grafana/loki/assets/1217278/bd90106d-21e9-483c-b757-025c917e76c1)

![lokirecieve](https://github.com/grafana/loki/assets/1217278/cb5483c0-b45c-45e9-89fa-14805f877178)
