### ISSUE TITLE
How to set up Loki and Promtail to communicate over TLS

### ISSUE THREAD

**Issue by waardd** [grafana/loki#11092]
I'm struggling how to get Loki and Promtail to run over TLS.
I added some lines to my config but see no difference.

```
server:
  http_listen_port: 9080
  http_tls_config: &tls_server_config
    cert_file: /opt/loki/mycertificate.crt
    key_file: /opt/loki/mycertificate.key

  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      host: 'lste005654'
      env: 'mon'
      __path__: /var/log/*log
```
What changes do i make to let both Loki and Promtail run under TLS

**Comment by JStickler** [comment]
@waardd You might have better luck getting questions answered on the [community forums](https://community.grafana.com/c/grafana-loki/41).

**Comment by brophyja** [comment]
We have deployed Loki in a Kubernetes cluster using the Helm chart, and run Promtail on various VMs.
From the Loki helm chart's `values.yaml` file, the Loki ingress is configured to use a designated host name with a corresponding certificate & key stored in the `loki-ingress-tls` secret, as shown below:
```
ingress:
  enabled: true
  hosts:
    - loki.<domain_name>
  tls:
    - hosts:
      - loki.<domain_name>
      secretName: loki-ingress-tls
```

For Promtail, the configuration references a certificate authority file that trusts the Loki ingress:
```
clients:
  - url: https://loki.<domain_name>/loki/api/v1/push
    tls_config:
      ca_file: /etc/pki/tls/certs/ca-bundle.crt
```

If Promtail cannot communicate with Loki, the Promtail logs should provide some details.
