### ISSUE TITLE
Loki 2.9.2 Azure Bob Storage Permission Denied

### ISSUE THREAD

**Issue by IMAMBAKS** [grafana/loki#11138]
**Describe the bug**
I'm trying to connect with a azure container blob storage. However I am getting permission denied (see below). I am running the docker-compose to run Loki 2.9.2.

```
level=warn ts=2023-11-05T08:05:34.209120666Z caller=loki.go:288 msg="global timeout not configured, using default engine timeout (\"5m0s\"). This behavior will change in the next major to always use the default global timeout (\"5m\")."
level=info ts=2023-11-05T08:05:34.210660288Z caller=main.go:108 msg="Starting Loki" version="(version=2.9.2, branch=HEAD, revision=a17308db6)"
level=info ts=2023-11-05T08:05:34.212060592Z caller=server.go:322 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=warn ts=2023-11-05T08:05:34.213418405Z caller=cache.go:127 msg="fifocache config is deprecated. use embedded-cache instead"
level=warn ts=2023-11-05T08:05:34.213450945Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache - chunksembedded-cache"
level=warn ts=2023-11-05T08:05:34.213581911Z caller=experimental.go:20 msg="experimental feature in use" feature="Azure Blob Storage"
level=warn ts=2023-11-05T08:05:34.213677909Z caller=experimental.go:20 msg="experimental feature in use" feature="Azure Blob Storage"
level=info ts=2023-11-05T08:05:34.213849795Z caller=table_manager.go:136 index-store=boltdb-shipper-2022-12-01 msg="uploading tables"
level=error ts=2023-11-05T08:05:34.213894229Z caller=log.go:230 msg="error running loki" err="mkdir /data/loki/cache: permission denied\nerror creating index client\ngithub.com/grafana/loki/pkg/storage.(*store).storeForPeriod\n\t/src/loki/pkg/storage/store.go:295\ngithub.com/grafana/loki/pkg/storage.(*store).init\n\t/src/loki/pkg/storage/store.go:177\ngithub.com/grafana/loki/pkg/storage.NewStore\n\t/src/loki/pkg/storage/store.go:155\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:689\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:136\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:461\nmain.main\n\t/src/loki/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:461\nmain.main\n\t/src/loki/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"
```

I have tested the `account_key` &  `account_name` with other means (python blob). And hardcoded in the following config:

```yaml
# (default configuration)
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h 
  max_chunk_age: 1h 
  chunk_target_size: 1048576
  max_transfer_retries: 0
  wal:
    dir: "/tmp/wal"

schema_config:
  configs:
    - from: 2022-12-01
      store: boltdb-shipper
      object_store: azure
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/cache
    cache_ttl: 24h
    shared_store: azure
  azure:
    container_name: loki
    account_key: ***
    account_name: REDACTED
    request_timeout: 0

compactor:
  working_directory: /data/loki/boltdb-shipper-compactor
  shared_store: azure


limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 720h
  ingestion_burst_size_mb: 16
  ingestion_rate_mb: 16
  retention_period: 720h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: localhost
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  
```
