### ISSUE TITLE
[docs] Malformed YAML in "Query your exported logs"

### ISSUE THREAD

**Issue by kaloyan-raev** [grafana/loki#11163]
**Describe the bug**
I follow the instructions described at https://grafana.com/docs/grafana-cloud/send-data/logs/export/query-exported-logs/#query-the-archive-using-loki-in-read-only-mode

The example for the `docker-compose.query-archive.yaml` file is malformed due to the invalid indentation of some lines.

**To Reproduce**
1. Follow the instructions described at https://grafana.com/docs/grafana-cloud/send-data/logs/export/query-exported-logs/#query-the-archive-using-loki-in-read-only-mode
2. Execute `docker-compose -f docker-compose.query-archive.yaml up -d`
3. The Loki container won't start.

**Expected behavior**
I expect the instructions in the documentation to work.

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: docker-compose

**Screenshots, Promtail config, or terminal output**
Error from the Loki container logs:
```
loki_1     | failed parsing config: /etc/loki/config.yaml: yaml: unmarshal errors:
loki_1     |   line 42: field querier already set in type loki.ConfigWrapper. Use `-config.expand-env=true` flag if you want to expand environment variables in your config file
loki_loki_1 exited with code 1
```

**Comment by kaloyan-raev** [comment]
Here is the example with fixed line indentations:

```yaml
version: "3.8"

services:
  loki:
    image: grafana/loki:2.8.2
    command: "-config.file=/etc/loki/config.yaml -target=querier"
    ports:
      - "3100:3100"
      - 7946
      - 9095
    volumes:
      - ./fixtures/loki-query-archive.yaml:/etc/loki/config.yaml:ro
    networks:
      - grafana-loki

  grafana:
    image: grafana/grafana:9.2.0-beta1
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki:3100
            jsonData:
              timeout: 600
              httpHeaderName1: "X-Scope-OrgID"
            secureJsonData:
              httpHeaderValue1: "{{TENANT_ID}}"
        EOF
        /run.sh
    ports:
      - "3000:3000"
    networks:
      - grafana-loki
networks:
  grafana-loki: {}
```
