### ISSUE TITLE
Labels guery empty after 30 minutes

### ISSUE THREAD

**Issue by tomasz-pcf** [grafana/loki#11174]
**Describe the bug** 
Labels query giving empty results after 30 minutes.

**To Reproduce**
1. Started Loki sha256:fc2b3ae55f634df7bf7edb11f11242b87fd329558635216852d328254f8318d8
2. Generate loki logs with labels with python script
```
import requests
import json
import time

host = 'somehost'
msg = 'On server {host} detected error1'.format(host=host)
url = 'https://XXX.com/loki/api/v1/push'
headers = {
    'Content-type': 'application/json'
}
ns = 1e9
ts = str(int(time.time() * ns))
payload = {
  "streams": [{
      "stream": {
        "label": "value",
        "guid": "1",
        "instance": "Testing"
      },
      "values": [[ ts, "test" ]]
    }]
}
payload = json.dumps(payload)
answer = requests.post(url, data=payload, headers=headers)
```
4. Query after creating logs:
```
curl -g 'https://XXX.com/loki/api/v1/series' --data-urlencode 'match[]={guid="1"}'
```
This should produce:
`{"status":"success","data":[{"guid":"1","label":"value","instance":"Testing"}]}`
5. Query again after 30 minutes:
```
curl -g 'https://XXX.com/loki/api/v1/series' --data-urlencode 'match[]={guid="1"}'
```
This will produce:
`{"status":"success","data":[]}`

**Expected behavior**
I would expect to have same results from step 4 and 5.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: docker-compose

docker-compose.yaml
```
---
version: '3'
services:
  nginx:
    container_name: nginx
    restart: always
    image: nginxinc/nginx-unprivileged:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro

  loki:
    container_name: loki
    restart: always
    image: grafana/loki:main
    ports:
      - 3100:3100
    command: -config.file=/config.yaml
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data:/loki:rw
      - ./config.yaml:/config.yaml:ro
```

config.yaml
```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
```
nginx.cof
```
upstream service_http {
  server loki:3100;
}

server {
    listen 80;
    server_name 0.0.0.0;
     
    location / {
        proxy_set_header        Host $host:$server_port;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
    
        # Fix the "It appears that your reverse proxy set up is broken" error.
        proxy_pass          http://service_http;
        proxy_read_timeout  90;

    
        # Required for new HTTP-based CLI
        proxy_http_version 1.1;
        proxy_request_buffering off;
    }
}
```
