### ISSUE TITLE
Loki Canary seems broken when gateway is disabled

### ISSUE THREAD

**Issue by CVanF5** [grafana/loki#11208]
**Describe the bug**
Canary has only errors in the logs when gateway is disabled.  It's clearly looking for the gateway service, when it shouldn't be, since gateway is disabled. Normally I would disable Canary, but the helm chart fails to install without Canary enabled.
```
error querying loki: query_range request failed: Get "http://loki-gateway.prometheus.svc.cluster.local.:80/loki/api/v1/query_range?start=1699540799577059108&end=1699540998577033673&query=%7Bstream%3D%22stdout%22%2Cpod%3D%22loki-canary-ssnt2%22%7D+&limit=1000": dial tcp: lookup loki-gateway.prometheus.svc.cluster.local. on 10.0.0.10:53: no such host
```

**To Reproduce**
values:
```
loki:
  auth_enabled: false
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: azure
    azure:
      accountName: ${AZURE_ACCOUNT_NAME}
      accountKey: ${AZURE_ACCOUNT_KEY}

backend:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-azure-credentials

read:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-azure-credentials

write:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-azure-credentials

ingress:
  enabled: true
  ingressClassName: "nginx"
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
  paths:
    write:
      - /api/prom/push
      - /loki/api/v1/push
    read:
      - /api/prom/tail
      - /loki/api/v1/tail
      - /loki/api
      - /api/prom/rules
      - /loki/api/v1/rules
      - /prometheus/api/v1/rules
      - /prometheus/api/v1/alerts
    singleBinary:
      - /api/prom/push
      - /loki/api/v1/push
      - /api/prom/tail
      - /loki/api/v1/tail
      - /loki/api
      - /api/prom/rules
      - /loki/api/v1/rules
      - /prometheus/api/v1/rules
      - /prometheus/api/v1/alerts
  hosts:
    - redacted
  tls:
  - hosts:
    - redacted
    secretName: loki-tls

monitoring:
  lokiCanary:
    enabled: true # Cannot disable

gateway:
  enabled: false
```

**Expected behavior**
Canary looks for the correct service endpoint when gateway no selected

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Comment by cuppett** [comment]
$loki.host is used by the canary daemonset. The issue starts here:

https://github.com/grafana/loki/blob/helm-loki-5.41.4/production/helm/loki/templates/_helpers.tpl#L608-L616

The conditional doesn't have a path for when using ingress and not using the single binary.

**Comment by cuppett** [comment]
It's likely allowing configuration for ingress will require more configuration for authentication as well.

**Comment by ddeath** [comment]
Hi, just to share my workaround for now... If you are deploying Loki with ArgoCD you can use `ignoreDifferences`:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.28.0
      helm:
        valueFiles:
          - $values/dev/grafana-loki/values.yaml
    - repoURL: {{ .Values.argocdRootApplicationRepoURL }}
      targetRevision: main
      ref: values
  destination:
    namespace: grafana-loki
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /spec/template/spec/containers/0/args/0
```

And then you just modify DaemonSet manually and change `-addr` to whatever you need.
