### ISSUE TITLE
grafana/loki 2.9.2 shows "no data" in grafana GUI for 30d time range.

### ISSUE THREAD

**Issue by dmitry-mightydevops** [grafana/loki#11216]
**Describe the bug**

- aws nlb
- grafana/loki 5.36.3  2.9.2 
- grafana 10.1.5
- storage is AWS S3

When I query the loki datasource in grafana explore over 30d I always get no data in the UI:

```
count_over_time({namespace="loki"} |= "traceID12"[1d])
```

at the same time if I query loki via API I'm getting the response in around 45-55s and getting OK logs in loki-gateway

```sh
➜ k port-forward service/loki-gateway 8080:80
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080

➜ time curl  --header "X-Scope-OrgID: 1"  -G -s  "http://localhost:8080/loki/api/v1/query_range?direction=backward&end=1699835276995000000&limit=1000&query=count_over_time%28%7Bnamespace%3D%22loki%22%7D+%7C%3D+%22traceID6%22%5B1d%5D%29&start=1697239676995000000&step=1200000ms" | jq

```json
...
   "stats": {
      "summary": {
        "bytesProcessedPerSecond": 361679547,
        "linesProcessedPerSecond": 1929325,
        "totalBytesProcessed": 16784220576,
        "totalLinesProcessed": 89532903,
        "execTime": 46.406330423,
        "queueTime": 93.35206493,
        "subqueries": 0,
        "totalEntriesReturned": 2,
        "splits": 32,
        "shards": 512,
        "totalPostFilterLines": 28,
        "totalStructuredMetadataBytesProcessed": 0
      },
      "querier": {
        "store": {
          "totalChunksRef": 8360,
          "totalChunksDownloaded": 8360,
          "chunksDownloadTime": 762419414445,
          "chunk": {
            "headChunkBytes": 0,
            "headChunkLines": 0,
            "decompressedBytes": 16775284300,
            "decompressedLines": 89466364,
            "compressedBytes": 1542589248,
            "totalDuplicates": 18,
            "postFilterLines": 28,
            "headChunkStructuredMetadataBytes": 0,
            "decompressedStructuredMetadataBytes": 0
          }
        }
      },
      "ingester": {
        "totalReached": 64,
        "totalChunksMatched": 45,
        "totalBatches": 64,
        "totalLinesSent": 0,
        "store": {
          "totalChunksRef": 0,
          "totalChunksDownloaded": 0,
          "chunksDownloadTime": 0,
          "chunk": {
            "headChunkBytes": 2078813,
            "headChunkLines": 12047,
            "decompressedBytes": 6857463,
            "decompressedLines": 54492,
            "compressedBytes": 787603,
            "totalDuplicates": 0,
            "postFilterLines": 0,
            "headChunkStructuredMetadataBytes": 0,
            "decompressedStructuredMetadataBytes": 0
          }
        }
      },
      "cache": {
        "chunk": {
          "entriesFound": 8071,
          "entriesRequested": 8360,
          "entriesStored": 289,
          "bytesReceived": 1329626449,
          "bytesSent": 246409937,
          "requests": 475,
          "downloadTime": 738407089164
        },
        "index": {
          "entriesFound": 3422,
          "entriesRequested": 3424,
          "entriesStored": 1957,
          "bytesReceived": 893106,
          "bytesSent": 0,
          "requests": 1056,
          "downloadTime": 16663924731
        },
        "result": {
          "entriesFound": 0,
          "entriesRequested": 32,
          "entriesStored": 32,
          "bytesReceived": 0,
          "bytesSent": 0,
          "requests": 64,
          "downloadTime": 733145420
        },
        "statsResult": {
          "entriesFound": 0,
          "entriesRequested": 0,
          "entriesStored": 0,
          "bytesReceived": 0,
          "bytesSent": 0,
          "requests": 0,
          "downloadTime": 0
        }
      }
    }
  }
}

curl --header "X-Scope-OrgID: 1" -G -s   0.00s user 0.01s system 0% cpu 46.521 total
jq  0.02s user 0.00s system 0% cpu 46.532 total


```

**gateway pod display 200 OK for this query around 1.5-2s right after the grafana displays NO DATA screen**

```sh
✗  klo -l app.kubernetes.io/component=gateway | grep query_range | grep Grafana
10.120.146.200 - - [13/Nov/2023:01:09:56 +0000]  200 "GET /loki/api/v1/query_range?direction=backward&end=1699837752794000000&limit=1000&query=count_over_time%28%7Bnamespace%3D%22loki%22%7D+%7C%3D+%22traceID12%22%5B1d%5D%29&start=1697242152794000000&step=1200000ms HTTP/1.1" 3407 "-" "Grafana/10.1.5" "-"

```

I always get this screen in Grafana:

![image](https://github.com/grafana/loki/assets/70822710/b57ae5e8-4c52-40c8-b9e7-f26e0b8835b5)

If I enable memcached query for chunks/results, then:

- first query: always no data
- 2nd query: immediately data (taken from cache I guess of the previous run)

## SO it feels like grafana closes the connection right few seconds before getting data from the loki datasource

**Expected behavior**

Data to be returned.

**Environment:**
 - Infrastructure: eks 1.27
 - Deployment tool: argocd + helm
 - pods in namespace:

```sh
➜ kgpo                                       
NAME                                          READY   STATUS    RESTARTS   AGE
loki-backend-0                                2/2     Running   0          14m
loki-backend-1                                2/2     Running   0          19m
loki-canary-b8jxm                             1/1     Running   0          8d
loki-canary-rm7gv                             1/1     Running   0          8d
loki-canary-wpptc                             1/1     Running   0          8d
loki-canary-zvjvh                             1/1     Running   0          8d
loki-gateway-cb8b5fdd5-wx426                  1/1     Running   0          26m
loki-grafana-agent-operator-d7c684bf9-hmnnl   1/1     Running   0          8d
loki-memcached-766464575c-5kbs2               2/2     Running   0          26m
loki-read-56d5d74978-5n2hm                    1/1     Running   0          19m
loki-read-56d5d74978-ms2wd                    1/1     Running   0          19m
loki-write-0                                  1/1     Running   0          18m
loki-write-1                                  1/1     Running   0          19m
promtail-4cxfl                                1/1     Running   0          9d
promtail-hcml9                                1/1     Running   0          9d
promtail-ms7mk                                1/1     Running   0          9d
promtail-mvfn5                                1/1     Running   0          24m

```

#### Loki datasource

has timeout for 5m

```
  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      orgId: 1
      url: http://loki-gateway.loki
      access: proxy
      editable: true
      jsonData:
        httpHeaderName1: 'X-Scope-OrgID'
        timeout: 300
        derivedFields:
          - datasourceName: Tempo
            matcherRegex: 'traceID=(\w+)'
            name: TraceID
            url: '$${__value.raw}'
            urlDisplayLabel: 'View Trace'
            datasourceUid: tempo
      secureJsonData:
        httpHeaderValue1: '1'
```

#### Grafana dataproxy

has timeout for 5m

```yaml
grafana.ini:
    dataproxy:
      logging: true
      timeout: 300
      keep_alive_seconds: 60
```

#### Loki gateway nginx conf has this server wide:

has timeouts for 10m

```
server {
...
  client_max_body_size  100M;
  proxy_read_timeout    600; 
  proxy_send_timeout    600;
  proxy_connect_timeout 600;
  send_timeout 600;
}
```

#### loki limits_config

has query_timeout = 5m

```yaml
limits_config:
      query_timeout: 5m
      retention_period: 30d
      retention_stream:
        - selector: '{namespace="ingress-nginx"}'
          priority: 1
          period: 90d
        - selector: '{namespace=~"prod|staging|dev"}'
          priority: 1
          period: 90d
      enforce_metric_name: false
      ingestion_burst_size_mb: 100
      ingestion_rate_mb: 20
      max_cache_freshness_per_query: 10m
      max_entries_limit_per_query: 50000
      max_query_length: 90d
      max_query_lookback: 90d
      max_query_parallelism: 32
      reject_old_samples_max_age: 240h
      reject_old_samples: true
      split_queries_by_interval: 30m
```
