### ISSUE TITLE
Monolithic Loki multiple replicas bootstrap issues

### ISSUE THREAD

**Issue by dombisza** [grafana/loki#11252]
**Describe the bug**
I was trying to deploy Loki in monolithic mode with 2 replicas from helm, because I did not have enough resources in the cluster at that time one of the pods were stuck in `Pending` state. At this point I could not connect Loki as a data source to Grafana even if I configured the running pod's IP address as URL. After scaling up the cluster the second pod was able to start and from this point the data source started to work in Grafana. From this point even if only one of the replicas were running I could query Loki from Grafana. 
I am guessing when you run Loki with:
```yaml
singleBinary:
  replicas: 2
```
It tries to bootstrap the instance in cluster mode and the initialization fails until all the members are available.
I am not sure if this is some kind of bug or this is an expected behaviour.

My full `values.yaml`

```yaml
global:
  dnsService: "coredns"
imagePullSecrets:
  - name: regcred
loki:
  commonConfig:
    replication_factor: 2
  storage:
    type: s3
    # null values will be populated at deploytime from env
    bucketNames:
      chunks: null
    s3:
      region: null
      secretAccessKey: null
      accessKeyId: null
      endpoint: null
      s3ForcePathStyle: false
      http_config:
        idle_conn_timeout: 1m
        response_header_timeout: 0s
        insecure_skip_verify: false
  rulerConfig:
    storage:
      type: local
      local:
        directory: /var/loki/rules
  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/index_cache
      shared_store: s3
  auth_enabled: false
  compactor:
    retention_enabled: true
    delete_request_cancel_period: 120m # don't wait 24h before processing the delete_request
    retention_delete_delay: 120m # wait 120m before actually deleting stuff
  chunk_store_config:
    max_look_back_period: 60d # after this period indexes get removed
  limits_config:
    retention_period: 60d # after this period chunks will be removed from OBS. This can only remove indexed chunks. https://github.com/grafana/loki/issues/6300#issuecomment-1431887039
singleBinary:
  replicas: 2
  persistence:
    storageClass: csi-disk-topology
    size: 10Gi
```
The only error in logs were:
```
level=warn ts=2023-11-17T12:46:22.630511964Z caller=memberlist_client.go:595 msg="joining memberlist cluster: failed to reach any nodes" retries=0 err="1 error occurred:\n\t* Failed to resolve loki-memberlist: lookup loki-memberlist on 10.247.3.10:53: no such host\n\n"
level=info ts=2023-11-17T12:46:22.742399101Z caller=ingester.go:447 msg="recovered WAL checkpoint recovery finished" elapsed=57.26µs errors=false
level=info ts=2023-11-17T12:46:22.742524939Z caller=ingester.go:469 msg="WAL segment recovery finished" elapsed=182.873µs errors=false
level=warn ts=2023-11-17T12:46:24.310294772Z caller=memberlist_client.go:595 msg="joining memberlist cluster: failed to reach any nodes" retries=1 err="1 error occurred:\n\t* Failed to resolve loki-memberlist: lookup loki-memberlist on 10.247.3.10:53: no such host\n\n"
level=warn ts=2023-11-17T12:46:26.411599087Z caller=memberlist_client.go:595 msg="joining memberlist cluster: failed to reach any nodes" retries=2 err="1 error occurred:\n\t* Failed to resolve loki-memberlist: lookup loki-memberlist on 10.247.3.10:53: no such host\n\n"
level=error ts=2023-11-17T12:47:34.34571165Z caller=http.go:315 org_id=fake traceID=687cb5057f7cffa0 msg="Error from client" err="websocket: close 1006 (abnormal closure): unexpected EOF"
level=error ts=2023-11-17T12:47:37.6256073Z caller=http.go:315 org_id=fake traceID=5a2126df94a1030c msg="Error from client" err="websocket: close 1006 (abnormal closure): unexpected EOF"
level=error ts=2023-11-17T12:47:39.613993411Z caller=http.go:315 org_id=fake traceID=39d887e2de04e923 msg="Error from client" err="websocket: close 1006 (abnormal closure): unexpected EOF"
level=error ts=2023-11-17T12:47:41.187307883Z caller=http.go:315 org_id=fake traceID=04dfcbe94a2fbca6 msg="Error from client" err="websocket: close 1006 (abnormal closure): unexpected EOF"
level=error ts=2023-11-17T12:47:54.349485154Z caller=http.go:315 org_id=fake traceID=797d7a7b7fa12790 msg="Error from client" err="websocket: close 1006 (abnormal closure): unexpected EOF"
level=error ts=2023-11-17T12:47:57.627744701Z caller=http.go:315 org_id=fake traceID=52a994711ff6d6e3 msg="Error from client" err="websocket: close 1006 (abnormal closure): unexpected EOF"
level=error ts=2023-11-17T12:47:59.61849866Z caller=http.go:320 org_id=fake traceID=2b64548d7075557f msg="Unexpected error from client" err="read tcp 172.16.2.8:3100->10.110.10.199:34300: read: connection reset by peer"
[...]
```

**To Reproduce**
- deploy loki in monolithic mode with 2 replicas on a cluster which only has enough resources for 1 instance

**Expected behavior**
I would still expect either one of these:
- Loki does not start up and goes to crashLoopBackoff until the other member is scheduled/running
- Loki starts up, but has some kind of error message about the pending members
- Loki starts up normally in non-clusterized mode

**Environment:**
 - Infrastructure: OpenTelekomCloud CCE kubernetes 1.25
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
none
