### ISSUE TITLE
Unable to lookback logs older than 2-3h max(random number)

### ISSUE THREAD

**Issue by PratikC91** [grafana/loki#11301]
I have setup loki to collect logs from my docker swarm cluster and push it to s3, this works great for day to day use but if i want to see logs older than a particular time which seems to be random, i am unable to get the logs. 
I can see all the logs being availabe in s3 but cant query them in loki.

Loki Config

```
auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_interface_names:
    - "lo"
  instance_addr: 127.0.0.1
  ring:
    instance_addr: 127.0.0.1
    instance_interface_names:
    - "lo"
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki # Update this accordingly, data will be stored here.

schema_config:
  configs:
  - from: 2020-05-15
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: s3
  aws:
    s3: s3://ap-north-xyz/c---------logs
    s3forcepathstyle: true
    bucketnames: c--------logs
    region: aap-north-xyz
    access_key_id: ------------------
    secret_access_key: -------------------


compactor:
  working_directory: /loki/compactor
  shared_store: s3
  compaction_interval: 5m
```
  
  promtail-config
  
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_service_name']
        target_label: 'service'
      - source_labels: ['__meta_docker_container_label_com_docker_stack_namespace']
        target_label: 'namespace'
```

<img width="1486" alt="Screenshot 2023-11-23 at 11 22 55 AM" src="https://github.com/grafana/loki/assets/138769896/52780256-5060-4728-bca9-37d9b029e247">
<img width="1896" alt="Screenshot 2023-11-23 at 11 23 35 AM" src="https://github.com/grafana/loki/assets/138769896/63bfdf15-0574-41d1-87ef-e612c12e7f46">
<img width="1894" alt="Screenshot 2023-11-23 at 11 24 09 AM" src="https://github.com/grafana/loki/assets/138769896/5de18c09-e21c-4fb3-8cd4-f23c86befe85">

how do i fix this?

**Comment by JStickler** [comment]
Questions have a better chance of being answered if you ask them on the [community forums](https://community.grafana.com/c/grafana-loki/41).

**Comment by tonyswu** [comment]
Try changing your S3 configuration to:

```
storage_config:
  s3:
    bucketnames: c--------logs
    s3forcepathstyle: true
    region: aap-north-xyz
    access_key_id: ------------------
    secret_access_key: -------------------
```

You can also double check your configuration with the `/config` API endpoint. And as JStickler mentioned, please feel free to bring this to the forum and I'll be happy to engage with you there.

**Comment by summed** [comment]
Am experiencing somewhat similar issue, except I am using tsdb. The S3 is onprem minio...

Write to S3 doesn't seem to be an issue, just when reading.


My config:

``` yaml
storage:
  type: s3
  s3:
    region: null
    endpoint: http://10.10.10.10:80/loki-logging
    accessKeyId: xyz
    secretAccessKey: zyx
    s3ForcePathStyle: true
    insecure: true
storage_config:
  tsdb_shipper:
    shared_store: s3
schemaConfig:
  configs:
  - index:
      period: 24h
      prefix: index_
    object_store: s3
    schema: v12
    store: tsdb
```
