### ISSUE TITLE
Docker dosen't start when using `--server.enable-runtime-reload` flag

### ISSUE THREAD

**Issue by Quiwy** [grafana/loki#11341]
**Describe the bug**
When trying to use the `--server.enable-runtime-reload` flas as described [in the doc](https://grafana.com/docs/loki/latest/configure/#reload-at-runtime), loki doens't start with an error.

**To Reproduce**
1. Started Loki 2.9.2
2. Loki doesn't start

**Expected behavior**
Reload endpoint working and loki starting.

**Environment:**
 - Infrastructure: Docker
 - Deployment tool: Docker compose

**Screenshots, Promtail config, or terminal output**
Docker-compose part :
```
version: '3'
  loki:
    container_name: loki
    image: grafana/loki:2.9.2
    restart: unless-stopped
    command:
      - '--server.enable-runtime-reload'
      - '--config.file=/loki/loki.yml'
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/loki
    networks:
      - monitoring

networks:
  monitoring:
```

I also tried with `- '--server.enable-runtime-reload=true'` .

Do you have any clue if this is a bug, or just me not understanding how to use the flag ?
Error on output : 
```
loki          | flag provided but not defined: -server.enable-runtime-reload                                                                               loki          | Run with -help to get list of available parameters
```
