### ISSUE TITLE
Logs written to Loki with TSDB are not always persisted.

### ISSUE THREAD

**Issue by href** [grafana/loki#11355]
**Describe the bug**

After switching from BoltDB to TSDB we noticed that some logs could no longer be queried after a while and seem to have been permanently lost, or at least there is no index pointing at them anymore. After switching back to BoltDB the problem vanished.

**Details**

In October we upgraded to Loki 2.9.1, and later 2.9.2, seemingly without problems. Then this week we had a likely unrelated index corruption issue. Our queries would not start again, showing that 2-3 gzip files became corrupt:

```
Nov 28 11:10:56 prod-log1-rma1 loki[158282]: level=error ts=2023-11-28T10:10:56.052764667Z caller=index_set.go:132 table-name=tsdb_index_19675 user-id=fake msg="failed to open existing index file /srv/loki/tsdb-cache/tsdb_index_19675/fake/1700560453-compactor-1699910221886-1700015957612-c4bb37c1.tsdb, removing the file and continuing without it to let the sync operation catch up" err="mmap, size 0: invalid argument"
Nov 28 11:10:56 prod-log1-rma1 loki[158282]: level=error ts=2023-11-28T10:10:56.066221625Z caller=index_set.go:285 table-name=tsdb_index_19682 msg="sync failed, retrying it" err="flate: corrupt input before offset 2149"
Nov 28 11:10:56 prod-log1-rma1 loki[158282]: level=error ts=2023-11-28T10:10:56.077733227Z caller=index_set.go:285 table-name=tsdb_index_19682 msg="sync failed, retrying it" err="gzip: invalid header"
```

We were able to remove these files and start the queriers again. During additional investigation, we discovered that the log volumes we expect to see were no longer there. This affected all hosts, **not** just the ones with the corrupt index files. It also affected time-ranges **before** the corrupt indices.

So while the corrupt indices are likely worth an issue of their own, they are not the issue here.

We have a logging end-to-end check that sends a log via journal/promtail, and queries the logserver until that log is found. This has worked since we have switched to the new log format.

Since this check runs once a minute, we however expect to see the following pattern (we have 58-59 checks an hour, as each check takes slightly more than a minute):

![Arc-2023-12-01-0PRTCILL](https://github.com/grafana/loki/assets/273163/270edb24-fb6f-4383-b31f-ba4d9a7bc6fa)

However, the volumes we found were these:

![Arc-2023-12-01-HyVWs8VG](https://github.com/grafana/loki/assets/273163/422f8f3f-4e7c-4ee6-a634-93ec37ffc421)

This is not just a display issue, querying the relevant time-ranges with `logcli` does not return the logs missing in the graph either.

After discovering the issue we tried switching back to the old format, which seems to have solved the issue, though we will have to monitor the situation, as the logs were not dropped consistently and not all the time. We have multiple Loki servers and some seem worse than others and the volume returned differs between time.

What could played a role were network issues, as at least in the second graph above, the first time the log volume decreases, is exactly when we had a network outage. It does look like it did not recover, long after the network was fixed that day. A reboot did not help either.

We also noticed that the space-usage does not seem to have changed, making us believe that maybe just the index or so is damaged, and the data is actually still there (without understanding Loki in detail).

Maybe there's a way to rebuild the index to get back at our data?

**To Reproduce**

We have no reproduction steps yet, but we can switch back to the old format in a lab environment to try and reproduce if requested.

**Expected behavior**

Data written to long-term storage should be 100% available.

**Environment:**

- Infrastructure: VM, Ubuntu 20.04, Datacenter, Loki 2.9.2, Promtail 2.9.2
- Deployment tool: Ansible (Apt Package).

**Screenshots, Promtail config, or terminal output**

This is the Loki config we use:
```
# Ansible managed
auth_enabled: false

server:
  log_level: info
  grpc_server_max_recv_msg_size: 16777216
  grpc_server_max_send_msg_size: 16777216
  http_server_write_timeout: 120s

distributor:
  ring:
    kvstore:
      store: consul
      consul:
        host: localhost:8500

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: consul
        consul:
          host: localhost:8500
      replication_factor: 1
    final_sleep: 0s
  max_transfer_retries: 0
  flush_op_timeout: 60s
  flush_check_period: 30s
  concurrent_flushes: 8
  chunk_target_size: 4194304
  max_chunk_age: "2h"
  chunk_idle_period: 2h
  wal:
    enabled: true
#   dir: configured in the service file

schema_config:
  configs:
    - from: 2021-09-03
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: "24h"
    - from: 2023-10-10
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        prefix: tsdb_index_
        period: "24h"
    - from: 2023-12-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: "24h"

storage_config:
  boltdb_shipper:
    active_index_directory: /srv/loki/index
    cache_location: /srv/loki/index_cache
    shared_store: filesystem
  tsdb_shipper:
    active_index_directory: /srv/loki/tsdb-index
    cache_location: /srv/loki/tsdb-cache
    shared_store: filesystem
  filesystem:
    directory: /srv/loki/chunks

compactor:
  working_directory: /srv/loki/compactor
  shared_store: filesystem
  compaction_interval: 5m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  unordered_writes: true
  max_query_length: "1488h"
  retention_period: "1488h"
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 40
  split_queries_by_interval: "1h"
  max_cache_freshness_per_query: 120s
  query_timeout: 120s
  retention_stream:
  - selector: '{unit=~"ceph-radosgw.*"}'
    priority: 1
    period: 168h

chunk_store_config:
  max_look_back_period: 0s

frontend_worker:
  frontend_address: '127.0.0.1:9091'
  parallelism: 6

frontend:
  tail_proxy_url: http://127.0.0.1:3112

querier:
  # Ingesters have cunks not older than max_chunk_age
  query_ingesters_within: "2h"

query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 5
  # Split queries by index period, this ensures that every index file
  # is downloaded only once
  cache_results: true
  parallelise_shardable_queries: true

  results_cache:
    cache:
      # We're going to use the in-process "FIFO" cache
      enable_fifocache: true
      fifocache:
        size: 1024
        validity: 24h

common:
  compactor_grpc_address: '127.0.0.1:9094'
```

Some parameters are passed to the processes, which are as follows (all on one host):
```
/usr/bin/consul agent -data-dir=/var/lib/consul -config-dir=/etc/consul.d
/usr/bin/loki -server.http-listen-address 127.0.0.1 -server.http-listen-port 3112 -server.grpc-listen-port 9092 -target querier -config.file=/etc/loki/loki-local-config.yaml -boltdb.shipper.active-index-directory /srv/loki/index-2 -boltdb.shipper.cache-location /srv/loki/index_cache-2 --
/usr/bin/loki -server.http-listen-address 127.0.0.1 -server.http-listen-port 0 -server.grpc-listen-port 9093 -target querier -config.file=/etc/loki/loki-local-config.yaml -boltdb.shipper.active-index-directory /srv/loki/index-3 -boltdb.shipper.cache-location /srv/loki/index_cache-3 --
/usr/bin/loki -server.http-listen-address 127.0.0.1 -server.http-listen-port 0 -server.grpc-listen-port 9095 -target ingester -config.file=/etc/loki/loki-local-config.yaml -boltdb.shipper.active-index-directory /srv/loki/index-5 -boltdb.shipper.cache-location /srv/loki/index_cache-5 -ingester.wal-dir /srv/loki/wal-5 --
/usr/bin/loki -server.http-listen-address 127.0.0.1 -server.http-listen-port 0 -server.grpc-listen-port 9096 -target ingester -config.file=/etc/loki/loki-local-config.yaml -boltdb.shipper.active-index-directory /srv/loki/index-6 -boltdb.shipper.cache-location /srv/loki/index_cache-6 -ingester.wal-dir /srv/loki/wal-6 --
```
