### ISSUE TITLE
Error "failed to open existing index file" for TSDB cache index named "compactor-<number>.r" 

### ISSUE THREAD

**Issue by MrWong99** [grafana/loki#11387]
**Describe the bug**
We updated our Loki test instance (all in one Docker container) from Loki 2.8.2 to 2.9.1 and in the process also migrated from BoltDB to TSDB. Shortly after the migration the instance started to fail and restart over and over with error messages like this one:

```
level=info ts=2023-12-05T10:54:04.764533163Z caller=util.go:94 table-name=index_19634 file-name=1696464930-c113e6a79322-1696429470848356120.tsdb.gz size="735 B" msg="downloaded file" total_time=229.736µs
level=info ts=2023-12-05T10:54:04.764603925Z caller=util.go:94 table-name=index_19634 file-name=1696441530-c113e6a79322-1696429470848356120.tsdb.gz size="735 B" msg="downloaded file" total_time=15.815953ms
level=info ts=2023-12-05T10:54:04.764908875Z caller=util.go:94 table-name=index_19634 file-name=compactor-1696427407.gz size="66 kB" msg="downloaded file" total_time=353.361µs
level=info ts=2023-12-05T10:54:04.765005556Z caller=util.go:94 table-name=index_19634 file-name=1696459530-c113e6a79322-1696429470848356120.tsdb.gz size="735 B" msg="downloaded file" total_time=326.996µs
level=info ts=2023-12-05T10:54:04.765035635Z caller=util.go:94 table-name=index_19634 file-name=9cd42f14b82f-1666087218896467368-1696428900.gz size="25 kB" msg="downloaded file" total_time=164.285µs
level=error ts=2023-12-05T10:54:04.76532315Z caller=compactor.go:601 msg="failed to compact files" table=index_19634 err="invalid tsdb path: /loki/boltdb-shipper-compactor/index_19634/compactor-1696427407"
level=error ts=2023-12-05T10:54:04.765359677Z caller=compactor.go:523 msg="failed to run compaction" err="invalid tsdb path: /loki/boltdb-shipper-compactor/index_19634/compactor-1696427407"
level=info ts=2023-12-05T10:54:59.404666407Z caller=table_manager.go:136 index-store=boltdb-shipper-2020-10-24 msg="uploading tables"
level=info ts=2023-12-05T10:54:59.404709006Z caller=table_manager.go:171 index-store=boltdb-shipper-2020-10-24 msg="handing over indexes to shipper"
level=info ts=2023-12-05T10:54:59.408884062Z caller=table_manager.go:136 index-store=tsdb-2023-09-20 msg="uploading tables"
level=info ts=2023-12-05T10:54:59.408917421Z caller=index_set.go:86 msg="uploading table index_19696"

...

level=info ts=2023-11-29T15:04:22.503922171Z caller=table_manager.go:136 index-store=tsdb-2023-09-20 msg="uploading tables"
level=error ts=2023-11-29T15:04:22.503987714Z caller=index_set.go:132 table-name=index_19635 msg="failed to open existing index file /loki/tsdb-cache/index_19635/compactor-1696599161.r, removing the file and continuing without it to let the sync operation catch up" err="invalid tsdb path: /loki/tsdb-cache/index_19635/compactor-1696599161.r"
ts=2023-11-29T15:04:22.504130074Z caller=spanlogger.go:86 level=info msg="building table names cache"
ts=2023-11-29T15:04:22.510411732Z caller=spanlogger.go:86 level=info msg="table names cache built" duration=6.274038ms
ts=2023-11-29T15:04:22.510428393Z caller=spanlogger.go:86 level=info msg="building table cache"
ts=2023-11-29T15:04:22.510448522Z caller=spanlogger.go:86 level=info msg="table cache built" duration=16.643µs
level=info ts=2023-11-29T15:04:22.510845248Z caller=util.go:94 table-name=index_19635 file-name=compactor-1696599161.r.gz size="66 kB" msg="downloaded file" total_time=351.901µs
level=error ts=2023-11-29T15:04:22.515500329Z caller=index_set.go:285 table-name=index_19635 msg="sync failed, retrying it" err="invalid tsdb path: /loki/tsdb-cache/index_19635/compactor-1696599161.r"
level=info ts=2023-11-29T15:04:22.516591911Z caller=util.go:94 table-name=index_19635 file-name=compactor-1696599161.r.gz size="66 kB" msg="downloaded file" total_time=1.047537ms
level=error ts=2023-11-29T15:04:22.520041375Z caller=index_set.go:285 table-name=index_19635 msg="sync failed, retrying it" err="invalid tsdb path: /loki/tsdb-cache/index_19635/compactor-1696599161.r"
level=error ts=2023-11-29T15:04:22.520053909Z caller=index_set.go:103 table-name=index_19635 msg="failed to initialize table index_19635, cleaning it up" err="invalid tsdb path: /loki/tsdb-cache/index_19635/compactor-1696599161.r"
level=error ts=2023-11-29T15:04:22.520124983Z caller=log.go:230 msg="error running loki" err="invalid tsdb path: /loki/tsdb-cache/index_19635/compactor-1696599161.r\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:461\nmain.main\n\t/src/loki/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"
```

I've manually split the lines of the 'err' in the last log line:

```
invalid tsdb path: /loki/tsdb-cache/index_19635/compactor-1696599161.r
error initialising module: store
github.com/grafana/dskit/modules.(*Manager).initModule
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/loki/pkg/loki.(*Loki).Run
    /src/loki/pkg/loki/loki.go:461
main.main
    /src/loki/cmd/loki/main.go:110
runtime.main
    /usr/local/go/src/runtime/proc.go:250
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1598
```

**To Reproduce**

1. Start Loki 2.8.2 with these configs:

__loki.yaml:__
```yaml
analytics:
  reporting_enabled: false

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 10000000
  grpc_server_max_send_msg_size: 10000000
  http_server_read_timeout: 300s
  http_server_write_timeout: 300s

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 24h
  retention_delete_worker_count: 150

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  unordered_writes: false
  enforce_metric_name: false
  reject_old_samples: false
  max_entries_limit_per_query: 0
  max_query_length: 0
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  max_query_parallelism: 16
  retention_period: 5d
  retention_stream:
    - selector: '{systemlogs="yes"}'
      priority: 1
      period: 2d

ingester:
  wal:
    enabled: false
    dir: /loki/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0

frontend_worker:
  match_max_concurrent: false

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    shared_store: filesystem
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
  filesystem:
    directory: /loki/chunks

querier:
  max_concurrent: 5

query_range:
  max_retries: 2
  parallelise_shardable_queries: true
```

__docker-compose.yml:__
```yaml
version: '3.8'

services:
  loki:
    image: grafana/loki:2.8.2
    restart: always
    read_only: true
    volumes:
      - ./loki.yaml:/etc/config/loki.yaml
      - log-storage-data:/loki
    entrypoint:
      - /usr/bin/loki
    command:
      - -config.file=/etc/config/loki.yaml

volumes:
  log-storage-data:
```

2. Produce some logs to fill up the index and chunks a bit (since these are test instances we have a generator running that produces a steady stream of 1 log per second from a pseudo-random selection of logs).

3. Stop the instance, switch the configs and start the new Loki 2.9.1 version:

__loki.yaml:__
```yaml
analytics:
  reporting_enabled: false

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 10000000
  grpc_server_max_send_msg_size: 10000000
  http_server_read_timeout: 300s
  http_server_write_timeout: 300s

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 24h
  retention_delete_worker_count: 150


schema_config:
  configs:
    - from: "2020-10-24"
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
    - from: "2023-09-20"
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

limits_config:
  unordered_writes: false
  enforce_metric_name: false
  reject_old_samples: false
  max_entries_limit_per_query: 0
  max_query_length: 0
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  max_query_parallelism: 16
  retention_period: 5d
  retention_stream:
    - selector: '{systemlogs="yes"}'
      priority: 1
      period: 5d
ingester:
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0

frontend_worker:
  match_max_concurrent: false

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    shared_store: filesystem
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

query_scheduler:
  max_outstanding_requests_per_tenant: 32768

querier:
  max_concurrent: 13

query_range:
  max_retries: 2
  parallelise_shardable_queries: true
```

__docker-compose.yml:__
```yaml
version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.1
    restart: always
    read_only: true
    tmpfs: 
      - /tmp
    volumes:
      - ./loki.yaml:/etc/config/loki.yaml:Z
      - log-storage-data:/loki
    entrypoint:
      - /usr/bin/loki
    command:
      - -config.file=/etc/config/loki.yaml

volumes:
  log-storage-data:
```

4. Keep producing logs as mentioned before.
5. The mentioned errors described above appear after some time and result in shutdown of the instances.

**Expected behavior**

I would expect a log message that describes what is going wrong exactly with a suggestion on how to fix it. I also wouldn't expect the instance to fail entirely

**Environment:**
 - Infrastructure: Docker Version 24.0.7, Docker Compose Version: 2.23.3
 - Deployment tool: Docker Compose
