### ISSUE TITLE
query_range not returing logs older than a day

### ISSUE THREAD

**Issue by VenkateswaranJ** [grafana/loki#11415]
I'm running [Loki 2.8.6](https://github.com/grafana/loki/releases/tag/v2.8.6) locally in Ubuntu. I [pushed](https://grafana.com/docs/loki/latest/reference/api/#push-log-entries-to-loki) some log streams which are 2 days older to Loki and tried to query them back via [query_range](https://grafana.com/docs/loki/latest/reference/api/#query-loki-over-a-range-of-time) api, but I don't see any logs as response.

The log push was successful with 204 responses.

Here is my Loki config file
```
auth_enabled: false

server:
  http_listen_port: 3100
  log_level: "warn"


common:
  instance_addr: 127.0.0.1
  path_prefix: /home/venkat/Documents/LokiPlayGround/storage/loki
  storage:
    filesystem:
      chunks_directory: /home/venkat/Documents/LokiPlayGround/storage/loki/chunks
      rules_directory: /home/venkat/Documents/LokiPlayGround/storage/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 500
      ttl: 24h

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 500
        
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
    boltdb_shipper:
        active_index_directory: /home/venkat/Documents/LokiPlayGround/storage/loki/boltdb-shipper-active
        cache_location: /home/venkat/Documents/LokiPlayGround/storage/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem

limits_config:
  reject_old_samples: false
```

Here are the log streams I tried to push (2 days older than today):

```jsonnet
{
  "streams": [
    {
      "stream": {
        "filename": "/home/venkat/Documents/LokiTest/log_file_one.log",
        "job": "varlogs"
      },
      "values": [
        [
          "1701866912497426336",
          "Test log line old"
        ]
      ]
    },
    {
      "stream": {
        "filename": "/home/venkat/Documents/LokiTest/log_file_two.log",
        "job": "varlogs"
      },
      "values": [
        [
          "1701866913497426336",
          "Test log line old"
        ]
      ]
    }
  ]
}
```

**My findings:**

The first thing is, I don't see chunks under `/home/venkat/Documents/LokiPlayGround/storage/loki/chunks` , maybe it's still in the `wal`?

I tried to write some logs to the same streams with new timestamp
```jsonnet
{
  "streams": [
    {
      "stream": {
        "filename": "/home/venkat/Documents/LokiTest/log_file_one.log",
        "job": "varlogs"
      },
      "values": [
        [
          "1702048047793233833",
          "Test log line new"
        ]
      ]
    },
    {
      "stream": {
        "filename": "/home/venkat/Documents/LokiTest/log_file_two.log",
        "job": "varlogs"
      },
      "values": [
        [
          "1702048047793233933",
          "Test log line new"
        ]
      ]
    }
  ]
}
``` 
After writing the logs with new timestamps, I can see some chunks under `/home/venkat/Documents/LokiPlayGround/storage/loki/chunks`
Surprisingly the chucks also contain the old logs. So now If I query again, I get both `old` & `new` logs for both streams.

Here is the output

```jsonnet
{
    "status": "success",
    "data": {
        "resultType": "streams",
        "result": [
            {
                "stream": {
                    "filename": "/home/venkat/Documents/LokiTest/log_file_two.log",
                    "job": "varlogs"
                },
                "values": [
                    [
                        "1702048047793233933",
                        "Test log line new"
                    ],
                    [
                        "1701866913497426336",
                        "Test log line old"
                    ]
                ]
            },
            {
                "stream": {
                    "filename": "/home/venkat/Documents/LokiTest/log_file_one.log",
                    "job": "varlogs"
                },
                "values": [
                    [
                        "1702048047793233833",
                        "Test log line new"
                    ],
                    [
                        "1701866912497426336",
                        "Test log line old"
                    ]
                ]
            }
        ],
        "stats": {
            "summary": {
                "bytesProcessedPerSecond": 21776,
                "linesProcessedPerSecond": 588,
                "totalBytesProcessed": 14652,
                "totalLinesProcessed": 396,
                "execTime": 0.67282,
                "queueTime": 0.916845,
                "subqueries": 0,
                "totalEntriesReturned": 4,
                "splits": 337,
                "shards": 5392
            },
            "querier": {
                "store": {
                    "totalChunksRef": 196,
                    "totalChunksDownloaded": 196,
                    "chunksDownloadTime": 12364776,
                    "chunk": {
                        "headChunkBytes": 0,
                        "headChunkLines": 0,
                        "decompressedBytes": 14504,
                        "decompressedLines": 392,
                        "compressedBytes": 15484,
                        "totalDuplicates": 0
                    }
                }
            },
            "ingester": {
                "totalReached": 96,
                "totalChunksMatched": 0,
                "totalBatches": 2,
                "totalLinesSent": 2,
                "store": {
                    "totalChunksRef": 2,
                    "totalChunksDownloaded": 2,
                    "chunksDownloadTime": 277597,
                    "chunk": {
                        "headChunkBytes": 0,
                        "headChunkLines": 0,
                        "decompressedBytes": 148,
                        "decompressedLines": 4,
                        "compressedBytes": 158,
                        "totalDuplicates": 0
                    }
                }
            },
            "cache": {
                "chunk": {
                    "entriesFound": 196,
                    "entriesRequested": 196,
                    "entriesStored": 0,
                    "bytesReceived": 72814,
                    "bytesSent": 0,
                    "requests": 196,
                    "downloadTime": 1141288
                },
                "index": {
                    "entriesFound": 0,
                    "entriesRequested": 0,
                    "entriesStored": 0,
                    "bytesReceived": 0,
                    "bytesSent": 0,
                    "requests": 0,
                    "downloadTime": 0
                },
                "result": {
                    "entriesFound": 0,
                    "entriesRequested": 0,
                    "entriesStored": 0,
                    "bytesReceived": 0,
                    "bytesSent": 0,
                    "requests": 0,
                    "downloadTime": 0
                }
            }
        }
    }
}
``` 

**I feel like I'm missing something in the configuration, could anyone please help with this?**
