### ISSUE TITLE
Query is terminated after 60 second

### ISSUE THREAD

**Issue by kfkawalec** [grafana/loki#11411]
Every loki (v2.9.2) query aborts after 60sec.
I know this is the querier.query-timeout flag, if I set this to 42 sec - query is terminated after 42 sec.
But when I set value to 65 or any higher number that 60 timeout is still after 60 seconds.

I check other timeout at https://grafana.com/docs/loki/latest/configure/ but there is no other important timeout configured to 60sec (1m).

Is there some bug or is there another timeout that should be set?

My helm config:
```
fullnameOverride: "loki"

loki:
  auth_enabled: true
  tenants:
    - name: username
      password: ${LOKI_PASSWORD}

  limits_config:
    retention_period: 90d
    retention_stream:
    - selector: '{namespace="default"}'
      priority: 1
      period: 24h
    max_query_length: 2161h # default: 721h
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_cache_freshness_per_query: 10m
    split_queries_by_interval: 15m
    ingestion_rate_mb: 8
    ingestion_burst_size_mb: 12

  commonConfig:
    replication_factor: 1

  storage:
    s3:
      s3: "http://minio:${MINIO_PASSWORD}@loki-minio.{{ .Release.Namespace }}.svc:9000"
      s3ForcePathStyle: true

  compactor:
    retention_enabled: true
    shared_store: s3

  memcached:
    chunk_cache:
      enabled: true
      host: loki-memcached-chunk.{{ .Release.Namespace }}.svc
      service: memcache
      batch_size: 256
      parallelism: 10
    results_cache:
      enabled: true
      host: loki-memcached-queries.{{ .Release.Namespace }}.svc
      service: memcache
      timeout: 500ms
      default_validity: 12h

test:
  enabled: false

write:
  replicas: 0
  persistence:
    storageClass: local-path

read:
  replicas: 0
  persistence:
    storageClass: local-path
  extraVolumes:
    - configMap:
        name: loki-ruler-rules-tenant
      name: rules-tenant
  extraVolumeMounts:
    - mountPath: /etc/loki/rules/tenant
      name: rules-tenant

backend:
  replicas: 0
  persistence:
    storageClass: local-path

singleBinary:
  replicas: 1
  extraArgs:
    - -querier.engine.timeout=5m
    - -querier.query-timeout=65s
  persistence:
    storageClass: local-path
  extraVolumes:
    - configMap:
        name: loki-ruler-rules-tenant
      name: rules-tenant
  extraVolumeMounts:
    - mountPath: /etc/loki/rules/tenant
      name: rules-tenant

gateway:
  enabled: true
  basicAuth:
    enabled: true
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/client-body-buffer-size: "1M"
      cert-manager.io/cluster-issuer: tenant
    hosts:
      - host: loki.${CLUSTER_DOMAIN}
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: loki-tls
        hosts:
          - loki.${CLUSTER_DOMAIN}
```
