### ISSUE TITLE
[Bug] invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by AtlanCI** [grafana/loki#11410]
**Describe the bug**
I'm starting the loki all-in-one program and I'm getting panic.

**To Reproduce**
1. use this config
```yaml
auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9060

ruler:
  storage:
    type: local
    local:
      directory: /home/server/loki/ruler
  rule_path: /tmp/scratch
  enable_api: true

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2023-04-27
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb:
    directory: /home/server/loki/index   

  filesystem:
    directory: /home/server/loki/chunks  

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  query_timeout: 5m 

  max_query_lookback: 672h



table_manager:
  retention_deletes_enabled: true
  retention_period: 672h
```
2. Started Loki (2.9.2)

**Expected behavior**
normal startup

**Environment:**
 - Infrastructure:  bare-metal
 - OS: CentOS Linux release 7.6.1810 (Core)

**Screenshots, Promtail config, or terminal output**
**stack log**
```shell
panic: runtime error: invalid memory address or nil pointer dereference
goroutine 475 [running]:
github.com/grafana/loki/pkg/storage/stores/shipper/util.logPanic({0x2548240, 0xc000b3bbd8})
        /drone/src/pkg/storage/stores/shipper/util/util.go:95 +0x47
github.com/grafana/loki/pkg/storage/stores/shipper/util.safeOpenBoltDbFile.func1()
        /drone/src/pkg/storage/stores/shipper/util/util.go:54 +0x45
panic({0x2548240?, 0xc000b3bbd8?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
go.etcd.io/bbolt.(*freelist).read(0x0?, 0x0?)
        /drone/src/vendor/go.etcd.io/bbolt/freelist.go:265 +0x1a
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
        /drone/src/vendor/go.etcd.io/bbolt/db.go:323 +0xaf
sync.(*Once).doSlow(0xc000b3ed08?, 0x10?)
        /usr/local/go/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
go.etcd.io/bbolt.(*DB).loadFreelist(0xc000b3eb40?)
        /drone/src/vendor/go.etcd.io/bbolt/db.go:316 +0x45
go.etcd.io/bbolt.Open({0xc000af2dc0, 0x36}, 0x1b6?, 0xc0010fbf48)
        /drone/src/vendor/go.etcd.io/bbolt/db.go:293 +0x458
github.com/grafana/loki/pkg/storage/chunk/client/local.OpenBoltdbFile(...)
        /drone/src/pkg/storage/chunk/client/local/boltdb_index_client.go:404
github.com/grafana/loki/pkg/storage/stores/shipper/util.safeOpenBoltDbFile({0xc000af2dc0, 0x36}, 0xc000b525a0)
        /drone/src/pkg/storage/stores/shipper/util/util.go:62 +0x105
created by github.com/grafana/loki/pkg/storage/stores/shipper/util.SafeOpenBoltdbFile in goroutine 1
        /drone/src/pkg/storage/stores/shipper/util/util.go:42 +0x86
```
