### ISSUE TITLE
Loki being locked for unknown reason

### ISSUE THREAD

**Issue by bobykus31** [grafana/loki#11452]
**Describe the bug**
We run a cluster of 3 writers and 3 readers interconnected. Writers are receiving logs from fluentd. Readers are connected to garafana. Data is stored in s3 like obj storage (NetApp StorageGrid). Periodically writers are being locked with no visible reason. The process just stops replying to any network connections

**To Reproduce**
1. Started Loki (SHA or version)
/usr/bin/loki --version
loki, version 2.9.2 (branch: HEAD, revision: a17308db6)
  build user:       root@eee92863de73
  build date:       2023-10-16T14:20:36Z
  go version:       go1.21.3
  platform:         linux/amd64
  tags:             netgo

3. Logs are streamed from Fluentd
4. No queries, just a clear injection

**Expected behavior**
Logs are constantly being written to log storage.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: a binary from this site

**Screenshots, Promtail config, or terminal output**

```
Dec 12 11:04:09 lokiwrite-webmail3 loki[26903]: level=info ts=2023-12-12T11:04:08.187462067Z caller=table_manager.go:136 index-store=tsdb-2023-08-20 msg="uploading tables"
Dec 12 11:04:09 lokiwrite-webmail3 loki[26903]: level=info ts=2023-12-12T11:04:08.187525738Z caller=index_set.go:86 msg="uploading table index_19702"
Dec 12 11:04:09 lokiwrite-webmail3 loki[26903]: level=info ts=2023-12-12T11:04:08.187539734Z caller=index_set.go:107 msg="finished uploading table index_19702"
Dec 12 11:04:09 lokiwrite-webmail3 loki[26903]: level=info ts=2023-12-12T11:04:08.18755324Z caller=index_set.go:185 msg="cleaning up unwanted indexes from table index_19702"
Dec 12 11:04:09 lokiwrite-webmail3 loki[26903]: level=info ts=2023-12-12T11:04:08.187565102Z caller=index_set.go:86 msg="uploading table index_19703"
Dec 12 11:04:09 lokiwrite-webmail3 loki[26903]: level=info ts=2023-12-12T11:04:08.187573899Z caller=index_set.go:107 msg="finished uploading table index_19703"
Dec 12 11:04:09 lokiwrite-webmail3 loki[26903]: level=info ts=2023-12-12T11:04:08.187582115Z caller=index_set.go:185 msg="cleaning up unwanted indexes from table index_19703"
Dec 12 11:04:16 lokiwrite-webmail3 loki[26903]: level=warn ts=2023-12-12T11:04:09.628674812Z caller=tcp_transport.go:437 component="memberlist TCPTransport" msg="WriteTo failed" addr=1.4.6.7:7946 err="dial tcp 1.4.6.7:7946: i/o timeout"
Dec 12 11:04:16 lokiwrite-webmail3 loki[26903]: ts=2023-12-12T11:04:10.106902518Z caller=memberlist_logger.go:74 level=info msg="Suspect lokiread-webmail3 has failed, no acks received"
Dec 12 11:04:16 lokiwrite-webmail3 loki[26903]: level=warn ts=2023-12-12T11:04:10.106982009Z caller=pool.go:196 msg="removing ingester failing healthcheck" addr=1.4.5.5:9095 reason="rpc error: code = DeadlineExceeded desc = context deadline exceeded"

```

I want to know the reason what is the inside components from a single binary that are not happy. Unfortunately, it is not visible either from logs or metrics. The only anomaly I see is a jump of schedulers goroutines (how this is manageable by config.yml when Loki is running with -target=**write**) 

![Screenshot from 2023-12-12 13-05-25](https://github.com/grafana/loki/assets/38345247/4b553a51-6477-4a52-8f5a-fe5adc1fecd5)
![Screenshot from 2023-12-12 13-05-03](https://github.com/grafana/loki/assets/38345247/81089423-ca58-4629-b6c0-1bcf4c34ec97)
![Screenshot from 2023-12-12 13-04-25](https://github.com/grafana/loki/assets/38345247/908c6d89-d8bc-41f8-887a-6eb06dcdb6ba)

Here is my config.yml
```
auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  grpc_server_max_recv_msg_size: 1048576000
  grpc_server_max_send_msg_size: 1048576000
  graceful_shutdown_timeout: 30s
  http_server_read_timeout: 300s
  http_server_write_timeout: 300s
  http_server_idle_timeout: 5m0s
  log_level: info
common:
  path_prefix: "/var/lib/loki"
  storage:
    s3:
      s3: One
      s3forcepathstyle: true
      bucketnames: loki-webmail
      endpoint: s3
      region: DK
      access_key_id: 
      secret_access_key: 
      insecure: false
      sse_encryption: false
      http_config:
        idle_conn_timeout: 10m
        response_header_timeout: 0s
        insecure_skip_verify: true
        ca_file: ''
      signature_version: v4
      sse:
        type: ''
        kms_key_id: ''
        kms_encryption_context: ''
      backoff_config:
        min_period: 100ms
        max_period: 3s
        max_retries: 5
  replication_factor: 1
  ring:
    kvstore:
      store: memberlist
schema_config:
  configs:
  - from: '2022-01-19'
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: index_
      period: 24h
  - from: '2023-08-20'
    store: tsdb
    object_store: s3
    schema: v12
    index:
      prefix: index_
      period: 24h
storage_config:
  index_queries_cache_config:
    background:
      writeback_goroutines: 10
      writeback_buffer: 100000
memberlist:
  dead_node_reclaim_time: 300s
  gossip_to_dead_nodes_time: 150s
  join_members:
  - lokiread-webmail1:7946
  - lokiread-webmail2:7946
  - lokiread-webmail3:7946
  - lokiwrite-webmail1:7946
  - lokiwrite-webmail2:7946
  - lokiwrite-webmail3:7946
  max_join_retries: 100
  rejoin_interval: 300s
  randomize_node_name: false
  stream_timeout: 60s
  pull_push_interval: 120s
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  chunk_idle_period: 2h
  max_chunk_age: 2h
  concurrent_flushes: 64
  chunk_target_size: 6291456
  chunk_encoding: zstd
  chunk_block_size: 1048576
  autoforget_unhealthy: true
chunk_store_config:
  max_look_back_period: 720h
  chunk_cache_config:
    background:
      writeback_goroutines: 10
      writeback_buffer: 100000
    enable_fifocache: false
  write_dedupe_cache_config:
    background:
      writeback_goroutines: 50
      writeback_buffer: 100000
    enable_fifocache: false
table_manager:
  retention_deletes_enabled: true
  retention_period: 720h
limits_config:
  ingestion_rate_strategy: global
  ingestion_rate_mb: 10240
  ingestion_burst_size_mb: 1000
  max_label_name_length: 2048
  max_label_value_length: 8192
  max_label_names_per_series: 120
  reject_old_samples: true
  reject_old_samples_max_age: 1w
  creation_grace_period: 10m
  enforce_metric_name: true
  max_line_size: 0
  max_line_size_truncate: false
  max_streams_per_user: 1000000
  max_global_streams_per_user: 1000000
  unordered_writes: true
  per_stream_rate_limit: 500MB
  per_stream_rate_limit_burst: 400MB
  max_chunks_per_query: 20000000
  max_query_series: 5000
  max_query_lookback: 30d
  max_query_length: 30d1h
  max_query_parallelism: 32
  cardinality_limit: 10000000
  max_streams_matchers_per_query: 10000
  max_entries_limit_per_query: 50000
  max_cache_freshness_per_query: 1m
  max_queriers_per_tenant: 0
  split_queries_by_interval: 15m
  min_sharding_lookback: 0s
ingester_client:
  pool_config:
    client_cleanup_period: 45s
    remote_timeout: 30s
  remote_timeout: 30s
  grpc_client_config:
    max_recv_msg_size: 1048576000
    max_send_msg_size: 1048576000
    grpc_compression: gzip
analytics:
  reporting_enabled: false
tracing:
  enabled: false
query_range:
  results_cache:
    cache:
      enable_fifocache: false
  index_stats_results_cache:
    cache:
      enable_fifocache: false


```

lokiread run with -target=read command line option,  lokiwrite with  -target=write. The only way to "unlock" a locked instance it the restart.
