### ISSUE TITLE
AWS region is set to `dummy`

### ISSUE THREAD

**Issue by exb-atix** [grafana/loki#11453]
**Describe the bug**
AWS region is not taken into account at least for `loki-backend` pods when trying to access AWS STS. This is throwing continuously error messages (see log in output section). Apart from these error messages, everything is working as expected though.
After looking into the code (as non-native Go speaker) the culprit seems to lie around the lines 224-232 and 245-247 of `s3_storage_client.go` where the region should be set into the s3Config object.

**To Reproduce**
1. Deploy Loki (2.9.3) via Helm chart (5.41.0)
2. look into log of a `loki-backend` pod

**Expected behavior**
The used endpoint is not filled with `dummy` region and thus doesn't throw an error.

**Environment:**
 - Infrastructure: Kubernetes on AWS
 - Deployment tool: helm via helmfile

**Screenshots, Promtail config, or terminal output**

Loki log:
```
level=info ts=2023-12-12T10:44:11.495384847Z caller=loki.go:505 msg="Loki started"
level=error ts=2023-12-12T10:44:11.505356978Z caller=ruler.go:571 msg="unable to list rules" err="WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.dummy.amazonaws.com/\": dial tcp: lookup sts.dummy.amazonaws.com on 172.20.0.10:53: no such host"
```

Loki helm values:
```
loki:
  auth_enabled: false
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 3
  compactor:
    apply_retention_interval: 1h
    compaction_interval: 5m
    retention_delete_worker_count: 500
    retention_enabled: true
    shared_store: s3
  schemaConfig:
    configs:
      - from: 2018-04-15
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: loki_index_
          period: 24h
  server:
    http_listen_port: 3100
  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/index_cache
      shared_store: s3
    aws:
      bucketnames: {{ .Values.loki.bucket_name }}
      region: {{ .Values.aws.region }}
      s3forcepathstyle: false
serviceAccount:
  create: true
  name: loki
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.loki.s3_access_role }}
```

Screenshot of the applied env vars:

![envvars](https://github.com/grafana/loki/assets/152986542/7dd35782-37d0-4f45-b908-44c87a6e1e8b)

**Comment by tehlers320** [comment]
im seeing this as well but on 2.9.1

**Comment by tehlers320** [comment]
Sorry im not using loki helm but i figured it out.

The config must have the region set here when using IRSA

```
    common:
      compactor_address: 'loki'
      path_prefix: /var/loki
      replication_factor: 2
      storage:
        s3:
          bucketnames: {{ .Values.s3_bucket }}
          region: {{ .Values.region }}
```

Mines working now. Env vars did not matter for whatever reason.
