### ISSUE TITLE
Inconsistent behavior in Loki v2.9.2 after scale up

### ISSUE THREAD

**Issue by Erichorng** [grafana/loki#11470]
**Describe the bug**
I have deployed loki v2.9.2 with single binary mode, aws storage, boltdb-shipper, replica =1. Everything was fine until I updated Loki to replica=3. After the upgrade, the query worked inconsistently. The results of each query are different each time, and this behavior continued for about 15 minutes (subsequent experiments revealed that this may be related to chunk max age).
To conduct the experiment, I deployed a log generator that generate 1 log line per second, and after the upgrade, we can see the results bellow:
<img width="1402" alt="截圖 2023-12-13 上午10 02 01" src="https://github.com/grafana/loki/assets/46678749/ac4d033f-b5bc-4ac6-94e4-20a2be640a8a">
<img width="1405" alt="截圖 2023-12-13 上午10 02 17" src="https://github.com/grafana/loki/assets/46678749/ccf92ba4-04e0-4b7f-b0cc-286071fc4699">
<img width="1405" alt="截圖 2023-12-13 上午10 02 34" src="https://github.com/grafana/loki/assets/46678749/310fd8f9-b1d1-447b-899f-319df3b06da8">
<img width="883" alt="截圖 2023-12-13 上午11 07 39" src="https://github.com/grafana/loki/assets/46678749/0a40bfa3-932e-4c51-92fc-467952806367">

It can be observed that there are inconsistent issues with logs approximately 30 minutes before the upgrade. This time coincides with the max_chunk_age I set. I believe that these inconsistent logs are logs that haven't been flushed before the upgrade.

Further more, approximately 15 minutes later (it may take longer if max_chunk_age is set to a larger value), these logs will return to normal. However, some logs will take more time to recover. After comparison, it was found that this time point corresponds to the restart time of loki-0 (When we perform a scale-up, the loki statefulset will first start two new pods and then restart the old pods).
<img width="431" alt="截圖 2023-12-13 上午10 29 32" src="https://github.com/grafana/loki/assets/46678749/df0f78b2-f1c0-40bb-981d-a92c046e1d5a">

**To Reproduce**
1. Started Loki v2.9.2 with configuration bellow

```
singleBinary:
  replicas: 1
gateway:
  replicas: 3
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  querier:
    query_ingesters_within: 1h
  ingester:
    max_chunk_age: 30m
    chunk_idle_period: 10m
  compactor:
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    compaction_interval: 10m
  limits_config:
    retention_period: 48h
  schemaConfig:
    configs:
      - from: 2022-01-11
        store: boltdb-shipper
        object_store: aws
        schema: v11
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      s3forcepathstyle: true
      endpoint: <endpoint>
      region: default
      secret_access_key: <sk>
      access_key_id: <ak>
      bucketnames: <bucket>
      http_config:
        ca_file: <ca_file>
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/boltdb-cache
```
2. Started Promtail, Grafana
3. After a few hours, upgrade loki with the bellow modification:
```
singleBinary:
  replicas: 3
loki:
  commonConfig:
    replication_factor: 3
```

4. Query logs, and the logs shows inconsistently.

**Expected behavior**
The log lines should look the same after scale up.

**Environment:**
 - Infrastructure: 3 node k3s cluster
 - Deployment tool: helm
