### ISSUE TITLE
loki ingester not load blancing and oom 

### ISSUE THREAD

**Issue by waney316** [grafana/loki#11474]
You may submit questions in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**NOTE: All questions submitted as issues will be closed.**

Loki: 2.9.3

 My  Loki deployment is on Kubernetes with an average daily log ingestion of 700GB. I deployed it using Helm and Loki in a distributed setup. However, I'm noticed significant imbalance in the load of the ingester components, with ingester2 frequently experiencing Out of Memory (OOM) situations. Below is my configuration, could anyone  please help me investigate this issue?
![image](https://github.com/grafana/loki/assets/23314093/bcfc8bdc-e3f2-48ec-82d5-2a6eb2fdb16f)

```yaml
   auth_enabled: true
    ingester:
      chunk_idle_period: 30m
      chunk_block_size: 262144
      flush_check_period: 2m
      chunk_retain_period: 1m
      max_transfer_retries: 0
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
    server:
      http_listen_port: 3100
      grpc_server_max_concurrent_streams: 2000
      grpc_server_max_recv_msg_size: 33555000
      grpc_server_max_send_msg_size: 33555000
    schema_config:
      configs:
        - from: 2023-10-01
          store: tsdb
          object_store: s3
          schema: v12
          index:
            prefix: tsdb_index_
            period: 24h
    storage_config:
      aws:
        access_key_id: 
        secret_access_key:   
        bucketnames: 
        endpoint: 
        http_config:
          insecure_skip_verify: true
        insecure: false
        s3forcepathstyle: false
        sse_encryption: false
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index
        shared_store: s3     
        cache_ttl: 168h
        index_gateway_client:
          server_address: dns:///loki-index-gateway:9095
    limits_config:
      enforce_metric_name: false
      max_global_streams_per_user: 10000
      ingestion_rate_mb: 100
      ingestion_burst_size_mb: 200
      per_stream_rate_limit : 80MB
      per_stream_rate_limit_burst: 150MB
      max_entries_limit_per_query: 10000
      max_query_parallelism: 256
      max_query_length: 72h
      max_concurrent_tail_requests: 20
      max_cache_freshness_per_query: 10m
      retention_period: 168h
      max_query_series: 1000000
      max_label_names_per_series: 1000000
      reject_old_samples: false
      reject_old_samples_max_age: 1w
      split_queries_by_interval: 15m
    compactor:
      working_directory: /data/retention
      shared_store: s3
      compaction_interval: 30m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    frontend:
      max_outstanding_per_tenant: 4096      
    query_scheduler:
      max_outstanding_requests_per_tenant: 32768
    querier:
      max_concurrent: 16
```
