### ISSUE TITLE
Loki: load rules/alerte from configmap using k8s-sidecar

### ISSUE THREAD

**Issue by nlamirault** [grafana/loki#11508]
**Describe the bug**

Hi, I try to use the k8s-sidecar to load Loki alerting rules from configmap. I've got 3 replicas of the Backend component ... sometimes the rules folder contains yaml files, sometimes it is empty...

```shell
$ /var/loki/rules/fake $ ls
loki
namespace_loki.configmap_loki-rule-commons-apps-error.loki-alerting-rules-all-apps.yaml
namespace_loki.configmap_loki-rule-lambda-dgfip-error.loki-alerting-rules-lambda.yaml

/var/loki/rules/fake $ ls
loki

/var/loki/rules/fake $ ls
loki

/var/loki/rules/fake $ ls
loki
namespace_loki.configmap_loki-rule-commons-apps-error.loki-alerting-rules-all-apps.yaml
namespace_loki.configmap_loki-rule-lambda-error.loki-alerting-rules-lambda.yaml
```

**To Reproduce**

Configuration:

Helm values:

```yaml
rulerConfig:
      external_url: "http://grafana.monitoring:80"
      datasource_uid: "loki"
      alertmanager_url: http://alertmanager-operated.monitoring:9093
      enable_alertmanager_v2: true
      enable_api: true
      enable_sharding: true
      wal:
        dir: /var/loki/ruler-wal
      rule_path: /var/loki/rules/
      remote_write:
        enabled: true
        client:
          url: http://prometheus-operated.monitoring:9090/api/v1/write
      ring:
        kvstore:
          store: inmemory

[...]

sidecar:
    enableUniqueFilenames: true
    rules:
      enabled: true
      label: loki-rule
      labelValue: ""
      folder: "/var/loki/rules/fake"
      logLevel: info
      searchNamespace: "ALL"
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi

```

Generated:

```yaml
ruler:
  alertmanager_url: http://alertmanager-operated.monitoring:9093
  datasource_uid: loki
  enable_alertmanager_v2: true
  enable_api: true
  enable_sharding: true
  external_url: http://grafana.monitoring:80
  remote_write:
    client:
      url: http://prometheus-operated.monitoring:9090/api/v1/write
    enabled: true
  ring:
    kvstore:
      store: inmemory
  rule_path: /var/loki/rules/
  storage:
    local:
      directory: /var/loki/rules
    type: local
  wal:
    dir: /var/loki/ruler-wal
```

**Expected behavior**

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: Helm
 - Storage: S3

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by marinflorin** [comment]
I am also interested in this one. I checked in the code (correct me if I am wrong), but the `ruler` will sync the rules only on start in `newRuler`. The problem is that the sidecar will download the rules from Kubernetes ConfigMaps after the ruler has been initialized; therefore, it will not load them. 

I believe the sidecar is a work in progress, although adding it to the `helm` chart creates a lot of confusion.

**Comment by nlamirault** [comment]
Any news on this bug ? Thanks

**Comment by sjentzsch** [comment]
Interesting, for me updating my rule config just worked, without requiring a restart of the backend.

I am using latest Helm chart, with Loki set up as SSD and 3 replicas each, with the following generated config:

```
...
ruler:
  alertmanager_url: http://_http-web._tcp.alertmanager-operated.observability.svc.cluster.local
  enable_alertmanager_discovery: true
  enable_alertmanager_v2: true
  evaluation_interval: 1m
  external_labels:
    origin: loki
  remote_write:
    clients:
      ...
    enabled: true
  rule_path: /rules
  storage:
    local:
      directory: /rules
    type: local
  wal:
    dir: /var/loki/ruler-wal
 ...
```

A look into `/rules`:
```
/ $ tree /rules/
/rules/
└── fake
    └── namespace_observability.configmap_loki-rules.general.txt

1 directories, 1 files
```

**Comment by NicoJDE** [comment]
This is my working config:
```
loki:
    rulerConfig:
      alertmanager_url: http://prometheus-kube-prometheus-alertmanager.prometheus.svc:9093
      enable_alertmanager_v2: true
      external_labels:
        origin: loki
      storage:
        type: local
        local:
          directory: /rules
      rule_path: rules/fake #for single tenant mode is fake
  sidecar:
    rules:
      searchNamespace: ALL
      folder: /rules/fake
```

have fun 😸
