### ISSUE TITLE
TSDB migration failing

### ISSUE THREAD

**Issue by kadhamecha-conga** [grafana/loki#11507]
hi team,

i'm facing below error when migrate from boltdb to tsdb ,

below is the error for ingester as well as in index-gateway:

`level=error ts=2023-11-22T16:11:43.608498801Z caller=log.go:171 msg="error running loki" err="mkdir uploader: read-only file system\nerror creating index client\ngithub.com/grafana/loki/pkg/storage.(*store).storeForPeriod\n\t/src/loki/pkg/storage/store.go:270\ngithub.com/grafana/loki/pkg/storage.(*store).init\n\t/src/loki/pkg/storage/store.go:164\ngithub.com/grafana/loki/pkg/storage.NewStore\n\t/src/loki/pkg/storage/store.go:147\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:655\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:120\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:92\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:457\nmain.main\n\t/src/loki/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1172\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:122\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:92\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:457\nmain.main\n\t/src/loki/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1172"`

before migration:

```
storage_config:
  aws:
    bucketnames: test-1
    endpoint: s3-endpoint
    region: us-east-2
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    cache_ttl: 168h
    index_gateway_client:
      server_address: dns:///loki-index-gateway:9095
    shared_store: filesystem
  filesystem:
    directory: /var/loki/chunks
  index_queries_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      addresses: dnssrv+_memcached-client._tcp.loki-memcached-index-queries.test.svc.cluster.local
      consistent_hash: true
      service: http
  tsdb_shipper:
    active_index_directory: /var/loki/tsdb-index
    cache_location: /var/loki/tsdb-cache
    cache_ttl: 168h
    index_gateway_client:
      server_address: dns:///loki-index-gateway:9095
    shared_store: s3

```
after migrating to TSDB:

```
storage_config:
  aws:
    bucketnames: test-1
    endpoint:  s3-endpoint
    region: us-east-2
  index_queries_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      addresses: dnssrv+_memcached-client._tcp.loki-memcached-index-queries.test.svc.cluster.local
      consistent_hash: true
      service: http
  tsdb_shipper:
    active_index_directory: /var/loki/tsdb-index
    cache_location: /var/loki/tsdb-cache
    cache_ttl: 168h
    index_gateway_client:
      server_address: dns:///loki-index-gateway:9095
    shared_store: s3
```
schema_config: 
```
schema_config:
  configs:
  - from: "2022-07-20"
    index:
      period: 24h
      prefix: loki_index_
    object_store: aws
    schema: v12
    store: boltdb-shipper
  - from: "2023-12-14"
    index:
      period: 24h
      prefix: loki_tsdb_index_
    object_store: s3
    schema: v12
    store: tsdb

```

the difference is in boltdb_shipper  shared_store is filesystem but in tsdb i have changed to s3 

can you please help , if there is any config issue ?

let me know, if you need more information.

thanks.
