### ISSUE TITLE
No log found from loki

### ISSUE THREAD

**Issue by duj4** [grafana/loki#11523]
**Describe the bug**
I am setting up a loki with simple-scalable mode, all services are showing as up and running. However, when I tried to ingest dummy logs from Fluentbit, nothing got found from Grafana.

**To Reproduce**
1. Deploy loki in simple-scalable mode
2. Generate dummy logs from Fluentbit

**Expected behavior**
I hope the dummy log could be retrieved.

**Environment:**
 - Infrastructure: K8S 1.28.2
 - Deployment tool: yml file

**Screenshots, Promtail config, or terminal output**
memberlist:
![image](https://github.com/grafana/loki/assets/19278537/0b21cf31-fa93-4281-9adc-857cdc128c1c)

loki-gateway.log:
```
172.16.32.128 - - [19/Dec/2023:04:12:18 +0000]  200 "GET /memberlist HTTP/1.1" 5014 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "192.168.126.1"
172.16.32.128 - - [19/Dec/2023:04:13:49 +0000]  200 "GET /loki/api/v1/query?direction=backward&query=vector%281%29%2Bvector%281%29&time=4000000000 HTTP/1.1" 1249 "-" "Grafana/10.2.2" "192.168.126.128"
172.16.32.128 - - [19/Dec/2023:04:14:00 +0000]  204 "POST /loki/api/v1/push HTTP/1.1" 0 "-" "Fluent-Bit" "192.168.126.128"
172.16.32.128 - - [19/Dec/2023:04:14:01 +0000]  204 "POST /loki/api/v1/push HTTP/1.1" 0 "-" "Fluent-Bit" "192.168.126.128"
172.16.32.128 - - [19/Dec/2023:04:14:02 +0000]  204 "POST /loki/api/v1/push HTTP/1.1" 0 "-" "Fluent-Bit" "192.168.126.128"
```

loki-write.log:
```
level=debug ts=2023-12-19T04:14:01.879527348Z caller=push.go:150 org_id=fake msg="push request parsed" path=/loki/api/v1/push contentType=application/json contentEncoding= bodySize="14 B" streams=0 entries=0 streamLabelsSize="0 B" entriesSize="0 B" totalSize="0 B" mostRecentLagMs=1702959241879
level=debug ts=2023-12-19T04:14:01.879572394Z caller=logging.go:101 traceID=7fef6715ec312974 orgID=fake msg="POST /loki/api/v1/push (204) 290.248µs"
level=debug ts=2023-12-19T04:14:04.87927091Z caller=push.go:150 org_id=fake msg="push request parsed" path=/loki/api/v1/push contentType=application/json contentEncoding= bodySize="14 B" streams=0 entries=0 streamLabelsSize="0 B" entriesSize="0 B" totalSize="0 B" mostRecentLagMs=1702959244879
level=debug ts=2023-12-19T04:14:04.879305515Z caller=logging.go:101 traceID=0eff2952eee41a88 orgID=fake msg="POST /loki/api/v1/push (204) 115.64µs"
level=debug ts=2023-12-19T04:14:07.878118616Z caller=push.go:150 org_id=fake msg="push request parsed" path=/loki/api/v1/push contentType=application/json contentEncoding= bodySize="14 B" streams=0 entries=0 streamLabelsSize="0 B" entriesSize="0 B" totalSize="0 B" mostRecentLagMs=1702959247878
level=debug ts=2023-12-19T04:14:07.878150239Z caller=logging.go:101 traceID=519af5c56a0e7a33 orgID=fake msg="POST /loki/api/v1/push (204) 101.003µs"
level=debug ts=2023-12-19T04:14:10.87700194Z caller=push.go:150 org_id=fake msg="push request parsed" path=/loki/api/v1/push contentType=application/json contentEncoding= bodySize="14 B" streams=0 entries=0 streamLabelsSize="0 B" entriesSize="0 B" totalSize="0 B" mostRecentLagMs=1702959250876
```

When queried from Grafana explorer:

loki-read.log:
```
level=info ts=2023-12-19T04:16:37.937212933Z caller=engine.go:220 component=querier org_id=fake msg="executing query" type=range query="{job=\"fluentbit\"}" length=15m0s step=20s query_hash=1553317564
ts=2023-12-19T04:16:37.93725177Z caller=spanlogger.go:85 user=fake level=debug msg="querying store" params="selector={job=\"fluentbit\"}, direction=BACKWARD, start=2023-12-18 22:45:00 +0000 UTC, end=2023-12-18 23:00:00 +0000 UTC, limit=1000, shards="
level=debug ts=2023-12-19T04:16:37.937311272Z caller=async_store.go:77 msg="skipping querying ingesters for chunk ids" query-from=1702939500 query-through=1702940400
ts=2023-12-19T04:16:37.93733927Z caller=spanlogger.go:85 user=fake method=GetChunkRefs level=debug shortcut=false from=2023-12-18T22:45:00Z through=2023-12-18T23:00:00Z err=null
ts=2023-12-19T04:16:37.938054078Z caller=spanlogger.go:85 user=fake method=query.Exec level=debug Ingester.TotalReached=0 Ingester.TotalChunksMatched=0 Ingester.TotalBatches=0 Ingester.TotalLinesSent=0 Ingester.TotalChunksRef=0 Ingester.TotalChunksDownloaded=0 Ingester.ChunksDownloadTime=0s Ingester.HeadChunkBytes="0 B" Ingester.HeadChunkLines=0 Ingester.DecompressedBytes="0 B" Ingester.DecompressedLines=0 Ingester.CompressedBytes="0 B" Ingester.TotalDuplicates=0 Querier.TotalChunksRef=0 Querier.TotalChunksDownloaded=0 Querier.ChunksDownloadTime=0s Querier.HeadChunkBytes="0 B" Querier.HeadChunkLines=0 Querier.DecompressedBytes="0 B" Querier.DecompressedLines=0 Querier.CompressedBytes="0 B" Querier.TotalDuplicates=0
ts=2023-12-19T04:16:37.938082211Z caller=spanlogger.go:85 user=fake method=query.Exec level=debug Cache.Chunk.Requests=0 Cache.Chunk.EntriesRequested=0 Cache.Chunk.EntriesFound=0 Cache.Chunk.EntriesStored=0 Cache.Chunk.BytesSent="0 B" Cache.Chunk.BytesReceived="0 B" Cache.Chunk.DownloadTime=0s Cache.Index.Requests=0 Cache.Index.EntriesRequested=0 Cache.Index.EntriesFound=0 Cache.Index.EntriesStored=0 Cache.Index.BytesSent="0 B" Cache.Index.BytesReceived="0 B" Cache.Index.DownloadTime=0s Cache.Result.Requests=0 Cache.Result.EntriesRequested=0 Cache.Result.EntriesFound=0 Cache.Result.EntriesStored=0 Cache.Result.BytesSent="0 B" Cache.Result.BytesReceived="0 B" Cache.Result.DownloadTime=0s
ts=2023-12-19T04:16:37.938088597Z caller=spanlogger.go:85 user=fake method=query.Exec level=debug Summary.BytesProcessedPerSecond="0 B" Summary.LinesProcessedPerSecond=0 Summary.TotalBytesProcessed="0 B" Summary.TotalLinesProcessed=0 Summary.ExecTime=813.795µs Summary.QueueTime=24.478µs
level=info ts=2023-12-19T04:16:37.938135924Z caller=metrics.go:152 component=querier org_id=fake latency=fast query="{job=\"fluentbit\"}" query_hash=1553317564 query_type=limited range_type=range length=15m0s start_delta=5h31m37.938132564s end_delta=5h16m37.938132788s step=20s duration=813.795µs status=200 limit=1000 returned_lines=0 throughput=0B total_bytes=0B lines_per_second=0 total_lines=0 total_entries=0 store_chunks_download_time=0s queue_time=24.478µs splits=0 shards=0 cache_chunk_req=0 cache_chunk_hit=0 cache_chunk_bytes_stored=0 cache_chunk_bytes_fetched=0 cache_chunk_download_time=0s cache_index_req=0 cache_index_hit=0 cache_index_download_time=0s cache_result_req=0 cache_result_hit=0 cache_result_download_time=0s
level=debug ts=2023-12-19T04:16:37.939463264Z caller=async_store.go:129 org_id=fake bytes=0B chunks=0 streams=0 entries=0 msg="queried statistics" matchers="{job=\"fluentbit\"}" source=store
level=debug ts=2023-12-19T04:16:37.944715807Z caller=async_store.go:129 org_id=fake bytes=0B chunks=0 streams=0 entries=0 msg="queried statistics" matchers="{job=\"fluentbit\"}" source=store
level=info ts=2023-12-19T04:16:37.946375718Z caller=engine.go:220 component=querier org_id=fake msg="executing query" type=range query="{job=\"fluentbit\"}" length=13m23.637s step=20s query_hash=1553317564
ts=2023-12-19T04:16:37.946423509Z caller=spanlogger.go:85 user=fake level=debug msg="querying store" params="selector={job=\"fluentbit\"}, direction=BACKWARD, start=2023-12-18 22:16:36.363 +0000 UTC, end=2023-12-18 22:30:00 +0000 UTC, limit=1000, shards="
level=debug ts=2023-12-19T04:16:37.946452558Z caller=async_store.go:77 msg="skipping querying ingesters for chunk ids" query-from=1702937796.363 query-through=1702938600
ts=2023-12-19T04:16:37.946508153Z caller=spanlogger.go:85 user=fake method=GetChunkRefs level=debug shortcut=false from=2023-12-18T22:16:36.363Z through=2023-12-18T22:30:00Z err=null
ts=2023-12-19T04:16:37.94727775Z caller=spanlogger.go:85 user=fake method=query.Exec level=debug Ingester.TotalReached=0 Ingester.TotalChunksMatched=0 Ingester.TotalBatches=0 Ingester.TotalLinesSent=0 Ingester.TotalChunksRef=0 Ingester.TotalChunksDownloaded=0 Ingester.ChunksDownloadTime=0s Ingester.HeadChunkBytes="0 B" Ingester.HeadChunkLines=0 Ingester.DecompressedBytes="0 B" Ingester.DecompressedLines=0 Ingester.CompressedBytes="0 B" Ingester.TotalDuplicates=0 Querier.TotalChunksRef=0 Querier.TotalChunksDownloaded=0 Querier.ChunksDownloadTime=0s Querier.HeadChunkBytes="0 B" Querier.HeadChunkLines=0 Querier.DecompressedBytes="0 B" Querier.DecompressedLines=0 Querier.CompressedBytes="0 B" Querier.TotalDuplicates=0
ts=2023-12-19T04:16:37.947299234Z caller=spanlogger.go:85 user=fake method=query.Exec level=debug Cache.Chunk.Requests=0 Cache.Chunk.EntriesRequested=0 Cache.Chunk.EntriesFound=0 Cache.Chunk.EntriesStored=0 Cache.Chunk.BytesSent="0 B" Cache.Chunk.BytesReceived="0 B" Cache.Chunk.DownloadTime=0s Cache.Index.Requests=0 Cache.Index.EntriesRequested=0 Cache.Index.EntriesFound=0 Cache.Index.EntriesStored=0 Cache.Index.BytesSent="0 B" Cache.Index.BytesReceived="0 B" Cache.Index.DownloadTime=0s Cache.Result.Requests=0 Cache.Result.EntriesRequested=0 Cache.Result.EntriesFound=0 Cache.Result.EntriesStored=0 Cache.Result.BytesSent="0 B" Cache.Result.BytesReceived="0 B" Cache.Result.DownloadTime=0s
ts=2023-12-19T04:16:37.947305418Z caller=spanlogger.go:85 user=fake method=query.Exec level=debug Summary.BytesProcessedPerSecond="0 B" Summary.LinesProcessedPerSecond=0 Summary.TotalBytesProcessed="0 B" Summary.TotalLinesProcessed=0 Summary.ExecTime=870.821µs Summary.QueueTime=35.719µs
level=info ts=2023-12-19T04:16:37.947353112Z caller=metrics.go:152 component=querier org_id=fake latency=fast query="{job=\"fluentbit\"}" query_hash=1553317564 query_type=limited range_type=range length=13m23.637s start_delta=6h0m1.584349381s end_delta=5h46m37.947349525s step=20s duration=870.821µs status=200 limit=1000 returned_lines=0 throughput=0B total_bytes=0B lines_per_second=0 total_lines=0 total_entries=0 store_chunks_download_time=0s queue_time=35.719µs splits=0 shards=0 cache_chunk_req=0 cache_chunk_hit=0 cache_chunk_bytes_stored=0 cache_chunk_bytes_fetched=0 cache_chunk_download_time=0s cache_index_req=0 cache_index_hit=0 cache_index_download_time=0s cache_result_req=0 cache_result_hit=0 cache_result_download_time=0s
```
From Grafana:
![image](https://github.com/grafana/loki/assets/19278537/61544b0a-de26-4470-9ab5-f16b1dca7c24)

The object store is Minio running locally, which is working fine in Cortex env. However in Loki, the fake folder was not created at all:
![image](https://github.com/grafana/loki/assets/19278537/229b8919-de63-4641-ba73-893ecbc436c1)

fluentbit.conf:
```
[INPUT]
    name  dummy
    dummy {"key": 1, "sub": {"stream": "stdout", "id": "some id"}, "kubernetes": {"labels": {"team": "Santiago Wanderers"}}}
    rate 1

[OUTPUT]
    name                   loki
    match                  *
    host                   loki-gateway.com
    port                   80
    labels                 job=fluentbit
    label_keys             $sub['stream']
    auto_kubernetes_labels on
```

Loki config file:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  namespace: logging
  labels:
    app.kubernetes.io/name: loki
data:
  config.yml: |-
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: debug

    common:
      path_prefix: /var/loki
      replication_factor: 3
      ring:
        kvstore:
          store: memberlist
      compactor_address: "loki-backend"

      storage:
        s3:
          endpoint: 192.168.126.128:9000
          bucketnames: chunks
          access_key_id: <access_key>
          secret_access_key: <secret_key>
          s3forcepathstyle: true
          insecure: true

    memberlist:
      join_members:
        - loki-memberlist

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m

    ruler:
      storage:
        s3:
          bucketnames: ruler

    index_gateway:
      mode: ring

    frontend:
      scheduler_address: query-scheduler-discovery.logging.svc.cluster.local:9095

    frontend_worker:
      scheduler_address: query-scheduler-discovery.logging.svc.cluster.local:9095

    schema_config:
      configs:
        - from: "2023-12-13"
          store: tsdb
          object_store: s3
          schema: v12
          index:
            period: 24h
            prefix: loki_index_

    storage_config:
      tsdb_shipper:
        active_index_directory: /var/loki/tsdb-index
        cache_location: /var/loki/tsdb-cache
        shared_store: s3
```
And I tried monolithic mode with local storage, the same:
```
---
target: "all"
auth_enabled: false

server:
  http_listen_address: "centos8-1"
  http_listen_port: 3100
  grpc_listen_address: "centos8-1"
  grpc_listen_port: 9095
  log_level: debug

memberlist:
  node_name: "centos8-1"
  bind_port: 7946

schema_config:
  configs:
    - from: "2023-12-13"
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        period: 24h
        prefix: loki_index_

storage_config:
  tsdb_shipper:
    active_index_directory: /home/dujas/loki/index
    cache_location: /home/dujas/loki/tsdb-cache
    shared_store: filesystem

common:
  path_prefix: /home/dujas
  replication_factor: 1
  ring:
    kvstore:
      store: memberlist

  storage:
    filesystem:
      chunks_directory: /home/dujas/loki/chunks
      rules_directory: /home/dujas/loki/chunks

analytics:
  reporting_enabled: false

compactor:
  working_directory: /home/dujas/loki/compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m
```

I am struggling in this for quite a while, please help me out, thanks.
