### ISSUE TITLE
Promtail - Logs are tailed again

### ISSUE THREAD

**Issue by pwurbs** [grafana/loki#11556]
**Describe the bug**
In Loki log, there are spikes of log occurrences with "reason: 'entry too far behind'". Sometimes the shipped logs have timestamps some days too old. 
Taking the spikes and the time gap into account, it seems that Promtail tails and ships logs again. 
The positions file looks good. 
It only occurs for container logs covered by kubernetes_sd_configs (not for static_configs).
I spent much time to find the cause, but I had no success.
This issue occurs since Promtail update from 2.8.2 to 2.9.2. I reverted the version to 2.8.7 and the issue mostly vanished 
But I faced the issue with 2.8.x that log shipping is stopped at all for some log files.

**To Reproduce**
1. Deployed Loki (2.8.3)
2. Deployed Promtail (2.9.2) to tail Docker based log files
3. Wait for 'entry too far behind' log events in Loki

**Expected behavior**
Log files should be tailed only once

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Promtail config**
```
server:
  log_level: info
  log_format: logfmt
  http_listen_port: 3101

clients:
  - tenant_id: 1
    url: http://loki:3100/loki/api/v1/push

positions:
  filename: /run/promtail/positions.yaml

scrape_configs:
  # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
  - job_name: kubernetes-pods
    pipeline_stages:
      - docker: {}
      - labeldrop:
        - pod
        - filename
        - job
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels:
          - __meta_kubernetes_pod_controller_name
        regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
        action: replace
        target_label: __tmp_controller_name
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_name
          - __meta_kubernetes_pod_label_app
          - __tmp_controller_name
          - __meta_kubernetes_pod_name
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: app
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_instance
          - __meta_kubernetes_pod_label_instance
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: instance
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_component
          - __meta_kubernetes_pod_label_component
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: component
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - namespace
        - app
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        regex: true/(.*)
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - replacement: prd
        target_label: environment
  - job_name: rke-container
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets:
        - localhost
        labels:
          job: rke-container-logs
          host: ${HOSTNAME}
          __path__: /var/lib/rancher/rke/log/*.log
          environment: prd
  - job_name: os-audit
    static_configs:
      - targets:
        - localhost
        labels:
          job: os-audit-logs
          host: ${HOSTNAME}
          __path__: /var/log/audit/audit.log
          environment: prd
  - job_name: kube-audit
    static_configs:
      - targets:
        - localhost
        labels:
          job: kube-audit-logs
          host: ${HOSTNAME}
          __path__: /var/log/kube-audit/audit-log.json
          environment: prd
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      labels:
        job: os-syslog-logs
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
      - target_label: environment
        replacement: prd  
limits_config:
tracing:
  enabled: false

```

I also see such log lines every 10s in Promtail:
```
caller=filetargetmanager.go:181 msg="received file watcher event" name=/var/log/pods/xxx/0.log op=CREATE
caller=filetargetmanager.go:181 msg="received file watcher event" name=/var/log/pods/xxx/0.log.20231228-090858 op=CREATE
```
