### ISSUE TITLE
Add missing default values to support ServerSideApply

### ISSUE THREAD

**Issue by albundy83** [grafana/loki#11560]
**Describe the bug**
To be able to synchronize successfully loki with ArgoCD when we enable `ServerSideApply=true`, it will be nice to have the missing default values for relabeling here https://github.com/grafana/loki/blob/76bf5053f2795aefa40578deb7e493efbebb073c/production/helm/loki/templates/monitoring/pod-logs.yaml#L21-L24

```yaml
  relabelings:
    - action: replace # <-- Missing
      sourceLabels:
        - __meta_kubernetes_pod_node_name
      targetLabel: __host__
```
and here https://github.com/grafana/loki/blob/76bf5053f2795aefa40578deb7e493efbebb073c/production/helm/loki/templates/monitoring/pod-logs.yaml#L45-L46
```yaml
    - action: replace # <-- Missing
      replacement: "{{ include "loki.clusterLabel" $ }}"
      targetLabel: cluster
```

**To Reproduce**
Create Application in ArgoCD and enable `ServerSideApply=true`

**Expected behavior**
I'd like to be able to successfully synchronize loki using ArgoCD

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm / ArgoCD

**Screenshots, Promtail config, or terminal output**
