### ISSUE TITLE
Installation failure if pod ip range is in 240.0.0.0/12

### ISSUE THREAD

**Issue by Aslan-Liu** [grafana/loki#11570]
**Describe the bug**
Use loki helm chart 5.41.4 to install Loki on k8s. If pod ip rage is in 240.0.0.0/12, loki-backend, loki-read and loki-write will keep crashing.

**To Reproduce**
1. Prepare K8S and set pod ip range as 240.0.0.0/12
2. Install Loki with helm chart 5.41.4

**Expected behavior**
loki-backend, loki-read and loki-write shall run correctly.

**Environment:**
I google this issue for a while, I also change values.yaml to see if it works. Here is the portion of my values.yaml. (But it doesn't work)
```
loki:
  memberlistConfig:
    bind_addr:
      - ${MY_POD_IP}

write:
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  persistence:
    volumeClaimsEnabled: false

read:
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  persistence:
    enableStatefulSetAutoDeletePVC: false

backend:
  extraArgs:
    - -config.expand-env=true
  extraEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  persistence:
    volumeClaimsEnabled: false

memberlist:
  service:
    publishNotReadyAddresses: true
```

**Screenshots, Promtail config, or terminal output**
```
# kubectl get po -n loki-loki
NAME                                  READY   STATUS             RESTARTS        AGE
loki-backend-0                        1/2     CrashLoopBackOff   7 (3m30s ago)   14m
loki-backend-1                        1/2     CrashLoopBackOff   7 (3m36s ago)   14m
loki-backend-2                        1/2     CrashLoopBackOff   7 (3m31s ago)   14m
loki-gateway-5b4dd5dbc8-2npw5         1/1     Running            0               14m
loki-read-54d565d7f7-8mlcn            0/1     CrashLoopBackOff   7 (3m28s ago)   14m
loki-read-54d565d7f7-crz2b            0/1     CrashLoopBackOff   7 (3m47s ago)   14m
loki-read-54d565d7f7-dj4ts            0/1     CrashLoopBackOff   7 (3m22s ago)   14m
loki-table-manager-688bbfdfb9-bgg55   1/1     Running            0               14m
loki-write-0                          0/1     CrashLoopBackOff   7 (3m37s ago)   14m
loki-write-1                          0/1     CrashLoopBackOff   7 (3m45s ago)   14m
loki-write-2                          0/1     CrashLoopBackOff   7 (3m37s ago)   14m

```
