### ISSUE TITLE
loki on grafana: No Labels Found

### ISSUE THREAD

**Issue by dingziyang** [grafana/loki#11610]
**ENV:**
- grafana: 10.2.2
- loki: 2.9.0
- promtail: 2.9.0

---

**Q:** I used Docker to run Grafana on 172.16.1.6, Docker to run Loki on 172.16.1.6, Docker to run Promtail on 172.16.1.8 I added a datasource loki on the Grafana page, but in Explore it shows **no labels found.** 

---

**configs：**

- **1.1 grafana-docker-compose.yml**
```
version: '3'

services:
  grafana:
    image: grafana/grafana:10.2.2
    restart: always
    container_name: grafana
    network_mode: "host"
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=viewer
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana_1qaz
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_ANALYTICS_CHECK_FOR_PLUGIN_UPDATES=false
    volumes:
      - ./data:/var/lib/grafana
      - ./log:/var/log/grafana
      - ./provisioning:/etc/grafana/provisioning
```
- **1.2 grafana-docker-log**
```
logger=cleanup t=2024-01-09T13:27:41.213779645+08:00 level=info msg="Completed cleanup jobs" duration=42.190346ms
logger=infra.usagestats t=2024-01-09T13:28:52.169116844+08:00 level=info msg="Usage stats are ready to report"
logger=cleanup t=2024-01-09T13:37:41.212608498+08:00 level=info msg="Completed cleanup jobs" duration=40.920472ms
logger=context userId=1 orgId=1 uname=admin t=2024-01-09T13:44:50.425519337+08:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=192.168.1.78 time_ms=38 duration=38.500043ms size=0 referer= handler=/api/live/ws
logger=cleanup t=2024-01-09T13:47:41.208152944+08:00 level=info msg="Completed cleanup jobs" duration=36.168066ms
logger=cleanup t=2024-01-09T13:57:41.40404885+08:00 level=info msg="Completed cleanup jobs" duration=232.3374ms
logger=infra.usagestats t=2024-01-09T13:58:52.167866816+08:00 level=info msg="Usage stats are ready to report"
logger=cleanup t=2024-01-09T14:07:41.208122522+08:00 level=info msg="Completed cleanup jobs" duration=35.942714ms
logger=cleanup t=2024-01-09T14:17:41.228399521+08:00 level=info msg="Completed cleanup jobs" duration=55.889805ms
logger=cleanup t=2024-01-09T14:27:41.212725225+08:00 level=info msg="Completed cleanup jobs" duration=41.080523ms
logger=infra.usagestats t=2024-01-09T14:28:52.166912492+08:00 level=info msg="Usage stats are ready to report"
logger=cleanup t=2024-01-09T14:37:41.208833506+08:00 level=info msg="Completed cleanup jobs" duration=36.665378ms
logger=cleanup t=2024-01-09T14:47:41.353685937+08:00 level=info msg="Completed cleanup jobs" duration=181.887083ms
logger=cleanup t=2024-01-09T14:57:41.208434818+08:00 level=info msg="Completed cleanup jobs" duration=36.311678ms
logger=infra.usagestats t=2024-01-09T14:58:52.169392686+08:00 level=info msg="Usage stats are ready to report"
logger=cleanup t=2024-01-09T15:07:41.207781974+08:00 level=info msg="Completed cleanup jobs" duration=35.784499ms
logger=cleanup t=2024-01-09T15:17:41.208545582+08:00 level=info msg="Completed cleanup jobs" duration=36.703124ms
logger=cleanup t=2024-01-09T15:27:41.212253904+08:00 level=info msg="Completed cleanup jobs" duration=40.662935ms
logger=infra.usagestats t=2024-01-09T15:28:52.167360545+08:00 level=info msg="Usage stats are ready to report"
logger=context userId=1 orgId=1 uname=admin t=2024-01-09T15:30:50.885548022+08:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=192.168.1.78 time_ms=63 duration=63.15956ms size=0 referer= handler=/api/live/ws
logger=tsdb.loki endpoint=callResource pluginId=loki dsName=Loki-local dsUID=e3f4cf6b-c708-42e3-a4bf-76a8ca34779e uname=admin t=2024-01-09T15:30:55.369691052+08:00 level=info msg="Response received from loki" status=ok statusCode=200 contentLength=21 duration=3.541601ms contentEncoding= stage=databaseRequest
logger=cleanup t=2024-01-09T15:37:41.305128928+08:00 level=info msg="Completed cleanup jobs" duration=132.654828ms
logger=context userId=1 orgId=1 uname=admin t=2024-01-09T15:39:02.779792517+08:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=192.168.1.78 time_ms=1 duration=1.660811ms size=0 referer= handler=/api/live/ws
logger=context userId=1 orgId=1 uname=admin t=2024-01-09T15:39:08.896152755+08:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=192.168.1.78 time_ms=1 duration=1.574874ms size=0 referer= handler=/api/live/ws
logger=context userId=1 orgId=1 uname=admin t=2024-01-09T15:39:14.038096527+08:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=192.168.1.78 time_ms=1 duration=1.617594ms size=0 referer= handler=/api/live/ws
logger=context userId=1 orgId=1 uname=admin t=2024-01-09T15:39:20.596031114+08:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=192.168.1.78 time_ms=1 duration=1.568736ms size=0 referer= handler=/api/live/ws
```
- **2.1 loki-docker-compose.yml**
```
version: '3'

services:
  loki:
    image: grafana/loki:2.9.0
    restart: always
    container_name: loki
    network_mode: "host"
    ports:
      - "3100:3100"
    volumes:
      - ./config:/etc/loki
      - ./data:/loki
    environment:
      - TZ=Asia/Shanghai
    command: -config.file=/etc/loki/local-config.yaml
```
- **2.2 loki-config.yaml**
```
auth_enabled: false
server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info
  log_source_ips_enabled: true

common:
  path_prefix: ./tmp/loki
  storage:
    s3:
      endpoint: http://172.16.1.6:9000
      insecure: false
      bucketnames: loki-data
      access_key_id: K0LFAV4KOSIEOLRQSDIA
      secret_access_key: lQS8ehLq+NY8tGji63pSyYKVGXplzzSe6kHn2e66
      s3forcepathstyle: true
  replication_factor: 1

ingester:
  lifecycler:
    address: 172.16.1.6
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2024-01-01
    store: boltdb-shipper
    object_store: s3
    schema: v12
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: ./tmp/loki/index
    cache_location: ./tmp/loki/index_cache
    resync_interval: 5s
    shared_store: s3
  aws:
    s3: http://loki:loki_1qaz@172.16.1.6:9000/loki-data
    s3forcepathstyle: true

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 672h

table_manager:
  retention_deletes_enabled: true
  retention_period: 672h
```
- **2.3 loki-docker-log**
```
level=info ts=2024-01-09T07:45:27.781028723Z caller=table_manager.go:228 index-store=boltdb-shipper-2024-01-01 msg="syncing tables"
level=info ts=2024-01-09T07:45:27.781071251Z caller=table_manager.go:136 index-store=boltdb-shipper-2024-01-01 msg="uploading tables"
level=info ts=2024-01-09T07:45:27.781570391Z caller=table_manager.go:271 index-store=boltdb-shipper-2024-01-01 msg="query readiness setup completed" duration=2.027µs distinct_users_len=0 distinct_users=
level=info ts=2024-01-09T07:45:32.78097459Z caller=table_manager.go:228 index-store=boltdb-shipper-2024-01-01 msg="syncing tables"
level=info ts=2024-01-09T07:45:32.781203482Z caller=table_manager.go:271 index-store=boltdb-shipper-2024-01-01 msg="query readiness setup completed" duration=1.54µs distinct_users_len=0 distinct_users=
level=info ts=2024-01-09T07:45:37.780631887Z caller=table_manager.go:228 index-store=boltdb-shipper-2024-01-01 msg="syncing tables"
level=info ts=2024-01-09T07:45:37.780856798Z caller=table_manager.go:271 index-store=boltdb-shipper-2024-01-01 msg="query readiness setup completed" duration=2.088µs distinct_users_len=0 distinct_users=
level=info ts=2024-01-09T07:45:42.780695256Z caller=table_manager.go:228 index-store=boltdb-shipper-2024-01-01 msg="syncing tables"
level=info ts=2024-01-09T07:45:42.780899676Z caller=table_manager.go:271 index-store=boltdb-shipper-2024-01-01 msg="query readiness setup completed" duration=2.031µs distinct_users_len=0 distinct_users=
level=info ts=2024-01-09T07:45:47.780500917Z caller=table_manager.go:228 index-store=boltdb-shipper-2024-01-01 msg="syncing tables"
level=info ts=2024-01-09T07:45:47.780728789Z caller=table_manager.go:271 index-store=boltdb-shipper-2024-01-01 msg="query readiness setup completed" duration=1.962µs distinct_users_len=0 distinct_users=
level=info ts=2024-01-09T07:45:52.780631546Z caller=table_manager.go:228 index-store=boltdb-shipper-2024-01-01 msg="syncing tables"
level=info ts=2024-01-09T07:45:52.78114858Z caller=table_manager.go:271 index-store=boltdb-shipper-2024-01-01 msg="query readiness setup completed" duration=2.003µs distinct_users_len=0 distinct_users=
level=info ts=2024-01-09T07:45:57.781087291Z caller=table_manager.go:228 index-store=boltdb-shipper-2024-01-01 msg="syncing tables"
level=info ts=2024-01-09T07:45:57.781583366Z caller=table_manager.go:271 index-store=boltdb-shipper-2024-01-01 msg="query readiness setup completed" duration=1.679µs distinct_users_len=0 distinct_users=
level=info ts=2024-01-09T07:46:02.780394199Z caller=table_manager.go:228 index-store=boltdb-shipper-2024-01-01 msg="syncing tables"
level=info ts=2024-01-09T07:46:02.780614662Z caller=table_manager.go:271 index-store=boltdb-shipper-2024-01-01 msg="query readiness setup completed" duration=2.034µs distinct_users_len=0 distinct_users=
level=info ts=2024-01-09T07:46:07.780395648Z caller=table_manager.go:228 index-store=boltdb-shipper-2024-01-01 msg="syncing tables"
level=info ts=2024-01-09T07:46:07.780865434Z caller=table_manager.go:271 index-store=boltdb-shipper-2024-01-01 msg="query readiness setup completed" duration=1.476µs distinct_users_len=0 distinct_users=
level=info ts=2024-01-09T07:46:12.780775334Z caller=table_manager.go:228 index-store=boltdb-shipper-2024-01-01 msg="syncing tables"
level=info ts=2024-01-09T07:46:12.78134245Z caller=table_manager.go:271 index-store=boltdb-shipper-2024-01-01 msg="query readiness setup completed" duration=3.043µs distinct_users_len=0 distinct_users=
```
- 3.1 **promtail-docker-compose.yml**
```
version: '3'

services:
  promtail:
    image: harbor.my.com:11443/library/promtail:2.9.0
    restart: always
    container_name: promtail
    volumes:
      - ./log:/var/log
      - ./config:/etc/promtail/
    environment:
      - TZ=Asia/Shanghai
    command: -config.file=/etc/promtail/local-config.yaml
```
- **3.2 promtail-config.yaml**
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"

clients:
  - url: http://172.16.1.6:3100/loki/api/v1/push

positions:
  filename: ./positions.yaml
  sync_period: 10s

scrape_configs:
- job_name: hb_backend_equip-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: hb_backend_equip-logs
      __path__: /root/my-docker-compose/hb-backend-equip/log/equip-server.log

- job_name: hb_backend_stat-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: hb_backend_stat-logs
      __path__: /root/my-docker-compose/hb-backend-stat/log/stat-server.log

- job_name: hb_backend_survey-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: hb_backend_survey-logs
      __path__: /root/my-docker-compose/hb-backend-survey/log/survey-server.log

- job_name: hb_backend_train-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: hb_backend_train-logs
      __path__: /root/my-docker-compose/hb-backend-train/log/train-server.log

- job_name: hb_backend_video-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: hb_backend_video-logs
      __path__: /root/my-docker-compose/hb-backend-video/log/video-server.log
```
- 3.3 **promtail-docker-log**
```
level=info ts=2024-01-09T01:45:25.010430906Z caller=promtail.go:133 msg="Reloading configuration file" md5sum=de5b8ea502c2b76bf2a90993598b463b
level=info ts=2024-01-09T01:45:25.012224098Z caller=server.go:322 http=[::]:9080 grpc=[::]:37973 msg="server listening on addresses"
level=info ts=2024-01-09T01:45:25.012701245Z caller=main.go:174 msg="Starting Promtail" version="(version=2.9.0, branch=HEAD, revision=2feb64f69)"
level=warn ts=2024-01-09T01:45:25.012817628Z caller=promtail.go:263 msg="enable watchConfig"
level=info ts=2024-01-09T01:45:30.011571208Z caller=filetargetmanager.go:361 msg="Adding target" key="/root/my-docker-compose/hb-backend-stat/log/stat-server.log:{job=\"hb_backend_stat-logs\"}"
level=info ts=2024-01-09T01:45:30.011653684Z caller=filetargetmanager.go:361 msg="Adding target" key="/root/my-docker-compose/hb-backend-video/log/video-server.log:{job=\"hb_backend_video-logs\"}"
level=info ts=2024-01-09T01:45:30.011675667Z caller=filetargetmanager.go:361 msg="Adding target" key="/root/my-docker-compose/hb-backend-equip/log/equip-server.log:{job=\"hb_backend_equip-logs\"}"
level=info ts=2024-01-09T01:45:30.011700244Z caller=filetargetmanager.go:361 msg="Adding target" key="/root/my-docker-compose/hb-backend-train/log/train-server.log:{job=\"hb_backend_train-logs\"}"
level=info ts=2024-01-09T01:45:30.011720801Z caller=filetargetmanager.go:361 msg="Adding target" key="/root/my-docker-compose/hb-backend-survey/log/survey-server.log:{job=\"hb_backend_survey-logs\"}"
```
- **4.1 logcli lables:** 
```
[root@localhost loki]# ./logcli-linux-amd64 labels
2024/01/09 15:48:50 http://localhost:3100/loki/api/v1/labels?end=1704786530995434306&start=1704782930995434306
[root@localhost loki]#
[root@localhost loki]#
``` 
- **4.2 get http://172.16.1.6:3100/loki/api/v1/labels:** 
```
{"status":"success"}
``` 
- **5. minio bucket loki-data**: only one file (**loki_cluster_seed.json**)
```
{
    "UID":"52b66309-3b8a-4858-822a-e82adc2ae3b4",
    "created_at":"2024-01-09T02:21:27.788536334Z",
    "version":{
        "version":"2.9.0",
        "revision":"2feb64f69",
        "branch":"HEAD",
        "buildUser":"root@bbf5319ac191",
        "buildDate":"2023-09-07T18:04:36Z",
        "goVersion":"go1.20.7"
    }
}
```
---

I suspect that the log data may not have been captured, but I am not sure where the problem occurred.
