### ISSUE TITLE
promtail kubernetes discovery target added without path

### ISSUE THREAD

**Issue by cameronbraid** [grafana/loki#1166]
installing on openshift 3.9

![image](https://user-images.githubusercontent.com/672405/66974328-77872280-f0e6-11e9-90d3-d321e4034438.png)

Using helm deployed with the following values :

```

loki:
  serviceName: "loki"
  servicePort: 3100
  serviceScheme: http

rbac:
  create: true
  pspEnabled: false

nodeSelector: 
 node: node01

volumes:
- name: docker
  hostPath:
    path: /var/lib/docker/containers
- name: pods
  hostPath:
    path: /var/log/pods

volumeMounts:
- name: docker
  mountPath: /var/lib/docker/containers
  readOnly: true
- name: pods
  mountPath: /var/log/pods
  readOnly: true

config:
  server:
    http_listen_port: 3101
    log_level: debug
```

Debug logs 

[debug-log.txt](https://github.com/grafana/loki/files/3737238/debug-log.txt)

**Comment by cyriltovena** [comment]
Are you using the default scrape config from helm ?

**Comment by cyriltovena** [comment]
When mousing over you can also see labels before relabeling. That would be useful to see what you have there for one of them.

**Comment by cyriltovena** [comment]
By default the relabeling rule that should add the glob path to watch for is:

```
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
```

I'm wondering if you have those two labels `__meta_kubernetes_pod_uid` and `__meta_kubernetes_pod_container_name` before relabeling, but also I'm wondering if ` /var/log/pods/*$1/*.log` is the correct path for logs on your host ?

**Comment by cameronbraid** [comment]
here is an example, yep - those labels exist

```
__address__="10.128.0.204:15672"
__meta_kubernetes_namespace="drivenow-staging-x"
__meta_kubernetes_pod_annotation_openshift_io_scc="restricted"
__meta_kubernetes_pod_annotationpresent_openshift_io_scc="true"
__meta_kubernetes_pod_container_init="false"
__meta_kubernetes_pod_container_name="rabbitmq"
__meta_kubernetes_pod_container_port_name="http"
__meta_kubernetes_pod_container_port_number="15672"
__meta_kubernetes_pod_container_port_protocol="TCP"
__meta_kubernetes_pod_controller_kind="StatefulSet"
__meta_kubernetes_pod_controller_name="rabbitmq-cluster"
__meta_kubernetes_pod_host_ip="10.118.56.32"
__meta_kubernetes_pod_ip="10.128.0.204"
__meta_kubernetes_pod_label_app="rabbitmq-cluster"
__meta_kubernetes_pod_label_controller_revision_hash="rabbitmq-cluster-68c467d689"
__meta_kubernetes_pod_label_statefulset_kubernetes_io_pod_name="rabbitmq-cluster-1"
__meta_kubernetes_pod_labelpresent_app="true"
__meta_kubernetes_pod_labelpresent_controller_revision_hash="true"
__meta_kubernetes_pod_labelpresent_statefulset_kubernetes_io_pod_name="true"
__meta_kubernetes_pod_name="rabbitmq-cluster-1"
__meta_kubernetes_pod_node_name="node01-2018"
__meta_kubernetes_pod_phase="Running"
__meta_kubernetes_pod_ready="true"
__meta_kubernetes_pod_uid="00406294-f087-11e9-8262-0cc47a39144c"
```

in the promtail container :

```
# ls -l /var/log/pods/*00406294-f087-11e9-8262-0cc47a39144c/*.log
lrwxrwxrwx. 1 root root 165 Oct 17 13:37 /var/log/pods/00406294-f087-11e9-8262-0cc47a39144c/rabbitmq_0.log -> /var/lib/docker/containers/5937640fd79c52537f297009dacec403bccd303d710ede703e4d352c2d50083a/5937640fd79c52537f297009dacec403bccd303d710ede703e4d352c2d50083a-json.log


# head -n 1 /var/lib/docker/containers/5937640fd79c52537f297009dacec403bccd303d710ede703e4d352c2d50083a/5937640fd79c52537f297009dacec403bccd303d710ede703e4d352c2d50083a-json.log
{"log":"'/etc/rabbitmq/rabbitmq.conf' -\u003e '/var/lib/rabbitmq/rabbitmq.conf'\n","stream":"stdout","time":"2019-10-17T02:37:06.225536725Z"}
```

```

**Comment by cameronbraid** [comment]
And yep I'l using the default heml config.. you can see my values above

**Comment by cameronbraid** [comment]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
  namespace: loki
  labels:
    app: promtail
    chart: promtail-0.12.3
    release: promtail
    heritage: Helm
data:
  promtail.yaml: |
    client:
      backoff_config:
        maxbackoff: 5s
        maxretries: 20
        minbackoff: 100ms
      batchsize: 102400
      batchwait: 1s
      external_labels: {}
      timeout: 10s
    positions:
      filename: /run/promtail/positions.yaml
    server:
      http_listen_port: 3101
      log_level: debug
    target_config:
      sync_period: 10s
    scrape_configs:
    - job_name: kubernetes-pods-name
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ^$
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container_name
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
    - job_name: kubernetes-pods-app
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: .+
        source_labels:
        - __meta_kubernetes_pod_label_name
      - source_labels:
        - __meta_kubernetes_pod_label_app
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ^$
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container_name
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
    - job_name: kubernetes-pods-direct-controllers
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: .+
        separator: ''
        source_labels:
        - __meta_kubernetes_pod_label_name
        - __meta_kubernetes_pod_label_app
      - action: drop
        regex: ^([0-9a-z-.]+)(-[0-9a-f]{8,10})$
        source_labels:
        - __meta_kubernetes_pod_controller_name
      - source_labels:
        - __meta_kubernetes_pod_controller_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ^$
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container_name
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
    - job_name: kubernetes-pods-indirect-controller
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: .+
        separator: ''
        source_labels:
        - __meta_kubernetes_pod_label_name
        - __meta_kubernetes_pod_label_app
      - action: keep
        regex: ^([0-9a-z-.]+)(-[0-9a-f]{8,10})$
        source_labels:
        - __meta_kubernetes_pod_controller_name
      - action: replace
        regex: ^([0-9a-z-.]+)(-[0-9a-f]{8,10})$
        source_labels:
        - __meta_kubernetes_pod_controller_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ^$
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container_name
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
    - job_name: kubernetes-pods-static
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: ^$
        source_labels:
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_label_component
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ^$
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container_name
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
        - __meta_kubernetes_pod_container_name
        target_label: __path__
```

**Comment by cyriltovena** [comment]
Everything looks correct.

you could try to add:

```
extraScrapeConfigs:
- job_name: test-sym-link
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/pods/00406294-f087-11e9-8262-0cc47a39144c/*log
```

just to verify if promtail can access that symlink.
