### ISSUE TITLE
operator: RulerConfig remote_write timeout issue

### ISSUE THREAD

**Issue by shev06** [grafana/loki#11731]
By creating a rulerconfig CR with remotewrite parameters the operator creates client configuration with the field timeout which results in an error.

**To Reproduce**
*Steps to reproduce the behavior:*
Create the following configuration:
```
kind: RulerConfig
apiVersion: loki.grafana.com/v1
metadata:
  name: rulerconfig-sample
  namespace: openshift-logging
spec:
  evaluationInterval: 1m
  pollInterval: 1m
  remoteWrite:
    client:
      authorization: basic
      authorizationSecretName: my-secret-resource
      name: remote-write-log-metrics
      proxyUrl: 'http://proxy-host.mycompany.org'
      relabelConfigs:
        - action: replace
          regex: ALERTS.*
          replacement: $1
          separator: ''
          sourceLabels:
            - labelc
            - labeld
          targetLabel: labelnew
      timeout: 30s
      url: 'http://remote-write-host.mycompany.org'
    enabled: true
    refreshPeriod: 10s
```

**Expected behavior**
Create valid config.yaml file

**Environment:**
 - Infrastructure: Openshift
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**
Containers have the following error, whilst crashlooping.
``` 
field timeout not found in type config.plain
```
