### ISSUE TITLE
After running one night, Loki lost connection.

### ISSUE THREAD

**Issue by hellodudu** [grafana/loki#1173]
**Describe the bug**
- I start two docker containers in remote server, Grafana and Loki. It's works well yesterday, After running 20 hours, I found Loki lost connection. Now I cann't set datasource in grafana and get `404 page not found` response from `loki/api/v1/label`

- I use Loki collecting logs without Promtail, only by pushing api `api/prom/push`.

- `loki-local-config.yaml` and `grafana.ini` are all default settings.

**To Reproduce**
1. Started from docker-compose.yaml

```
version: "3"
services:
  loki:
    images: Grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki/:/etc/loki
      - ./data/loki/:/tmp/loki
    command: -config.file=/etc/loki/loki-local-config.yaml
    restart: unless-stopped
    depends_on:
      - grafana

  grafana:
    images: grafana/grafana
    container_name: grafana
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./data/grafana/:/var/lib/grafana/
    ports:
      - "3000:3000"
    user: "472"
    environment:
      GF_EXPLORE_ENABLED: "true"
    logging:
      driver: loki
      options:
        loki-url: "http://212.64.58.168:3100/api/prom/push"
        loki-retries: "5"
        loki-batch-size: "400"
```

2. Set datasource with url `http://loki:3100`
3. Run one night(I don't know how much time exactly)
4. Loki lost connect, set datasource from Grafana failed with `Bad Gateway. 502`, query with curl `http://212.64.58.168:3100/loki/api/v1/label` got error `404 page not found`. But push api `api/prom/push` successed.

**Expected behavior**
loki query logs success.

**Environment:**
 - centos7
 - docker-compose 1.24.1

**Screenshots, Promtail config, or terminal output**
