### ISSUE TITLE
include in extra-manifests.yaml

### ISSUE THREAD

**Issue by marselsultanov** [grafana/loki#11796]
**Describe the bug**
### Describe the bug a clear and concise description of what the bug is.

When i put:
```
extraManifests:
  - apiVersion: v1
     kind: MyCRD
     metadata:
       labels:
         {{- include "loki.labels" . | nindent 4 }}
```
to:
https://github.com/grafana/loki/blob/6d66ea382cfdc90ca12b38e2ff6cb29a301a118e/production/helm/loki/values.yaml

I get error "did not find expected node content"

Partially case here: 
https://stackoverflow.com/questions/71169122/how-to-add-custom-templates-to-bitnami-helm-chart
but quotas doesn't help me, because i have multiline labels, if i do:
```
extraManifests:
  - apiVersion: v1
     kind: MyCRD
     metadata:
      labels:
        '{{- include "loki.labels" . | nindent 4 }}'
```
i get:
```
metadata:
  labels: '
    here: default
    labels: but_in
    single: quote'
```
but kubectl give error on this :/

How i can use **include** with map in **extraManifests**?

**To Reproduce**
helm template loki grafana/loki --values my-values.yaml

my-values.yaml:
```
extraManifests:
  - apiVersion: v1
    kind: MyCRD
    metadata:
      labels:
        {{- include "loki.labels" . | nindent 4 }}

**Expected behavior**
Include resolves without quotas

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by marselsultanov** [comment]
If i change:
1. values.yaml to
```
extraManifests:
  - |
    apiVersion: v1
    kind: MyCRD
    metadata:
      labels:
        '{{- include "loki.labels" . | nindent 4 }}'
```
2. extra-manifests.yaml to
```
{{ range .Values.extraManifests }}
---
{{ tpl . $ }}
{{ end }}
```

It's work, but i'm not sure that it's a good way...
