### ISSUE TITLE
[Loki] I have some question about Loki Single Binary HA

### ISSUE THREAD

**Issue by kingbj940429** [grafana/loki#11860]
I use Loki Helm, S3

Loki Chart version : 5.42.0

1. what is different S3 and Persistent Volume
when I deleted PV, all logs are deleted also.

why all logs are deleted when I deleted PV in spite of using S3 ?

2. I set Loki's replica 2 for HA

when I queried logs, a grafana take turns showing the results.
I think maybe requests Loki-0, Loki-1 in round robin.

it is possible to set HA in Single Binary mode?

3. I want to use alerting by setting rulers
I set s3 as rulers storge

how can I add rulers.yaml?

This is logs when initialized Loki as Single Binary
![image](https://github.com/grafana/loki/assets/63000843/6f9eba87-ac57-4e44-aaa0-84d188495943)

This is config
```yaml
auth_enabled: false
common:
  compactor_address: 'loki'
  path_prefix: /var/loki
  replication_factor: 1
  storage:
    s3:
      bucketnames: eks-loki-chunks
      insecure: false
      region: ap-northeast-2
      s3forcepathstyle: false
compactor:
  compaction_interval: 10m
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  retention_enabled: true
  shared_store: s3
  working_directory: /var/loki/compactor
frontend:
  scheduler_address: ""
frontend_worker:
  scheduler_address: ""
index_gateway:
  mode: ring
limits_config:
  max_cache_freshness_per_query: 10m
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  split_queries_by_interval: 15m
memberlist:
  join_members:
  - loki-memberlist
query_range:
  align_queries_with_step: true
ruler:
  alertmanager_url: http://prometheus-alertmanager.monitoring.svc:9093
  enable_alertmanager_v2: true
  enable_api: true
  storage:
    s3:
      bucketnames: eks-loki-chunks
      insecure: false
      region: ap-northeast-2
      s3forcepathstyle: false
    type: s3
runtime_config:
  file: /etc/loki/runtime-config/runtime-config.yaml
schema_config:
  configs:
  - from: "2023-01-05"
    index:
      period: 24h
      prefix: index_
    object_store: s3
    schema: v12
    store: tsdb
server:
  grpc_listen_port: 9095
  http_listen_port: 3100
storage_config:
  aws:
    s3: s3://ap-northeast-2/eks-loki-chunks
  boltdb_shipper:
    active_index_directory: /var/loki/active
    cache_location: /var/loki/cache
    cache_ttl: 24h
    shared_store: s3
  hedging:
    at: 250ms
    max_per_second: 20
    up_to: 3
  tsdb_shipper:
    active_index_directory: /var/loki/tsdb-index
    cache_location: /var/loki/tsdb-cache
    shared_store: s3
tracing:
  enabled: false
```
