### ISSUE TITLE
Unable to filter for structured metadata labels

### ISSUE THREAD

**Issue by nhippe-ds** [grafana/loki#11912]
**Describe the bug**
We're testing the `structured_metadata` feature and encountered an issue with filtering on the fields. 

**To Reproduce**
1. Ensure that Loki is setup to use structured metadata as [required](https://grafana.com/docs/loki/latest/get-started/labels/structured-metadata/).
```
limits_config:
  allow_structured_metadata: true

## must use V13 schema
  schemaConfig:
    configs:
      - from: "2024-02-01"
        index:
          prefix: loki_index_
          period: 24h
        object_store: azure
        schema: v13
        store: tsdb
```
2. Assume app logs
```
2024-02-08T23:33:30.453435958Z stdout F 2024-02-08T23:33:30.453Z stdout F 2024-02-08T23:33:30.453Z hitId=00002-feba3521-528d-440d-8c01-f753a246d85a projectId=000017abcdef message=testingIds something=this foo=bar
```

3. Setup promtail to extract high cardinality label
```
      - match:
          selector: '{source="k8s", app="python-logger"}'
          stages:
            - regex:
                expression: '.*projectId=(?P<projectId>[a-zA-Z0-9-]*[0-9]+[a-zA-Z0-9-]*)'
            - regex:
                expression: '.*hitId=(?P<hitId>[a-zA-Z0-9_-]*[0-9]+[a-zA-Z0-9_-]*)'
            - structured_metadata:
                projectId:
                hitId:
```

4. Query logs: `{source="k8s", app="python-logger"}`
5. Note labels will be listed as Fields and have the ability to filter. When filter is applied it's added to base query as extracted label. 

![loki](https://github.com/grafana/loki/assets/77296759/eb254a71-d577-4cd0-9a92-069af94918c2)

**Expected behavior**
If the intention of structured metadata is to improve query performance on high cardinality labels without the need to use a filter like `logfmt`, it would be nice to be able to quick filter on those values. We're comparing Loki to Splunk and one of the use cases would be to run a very broad search, and then filter for a specific hitId to see all correlating logs. We can certainly do this via `logfmt` but the query performance will be drastically impacted by the base search. If we're extracting labels via structured_metadata, and if they're included in the Fields list, they should be added as a label filter automatically when filtering. Not part of the base query as an extracted label.

**Environment:**
 - Loki 2.9.2
 - Promtail 2.9.2
 - Infrastructure: Kubernetes
 - Grafana version: (tested on both 9.4.3 & 10.3.1)
