### ISSUE TITLE
Log deletion does not work

### ISSUE THREAD

**Issue by mac133k** [grafana/loki#11926]
**Describe the bug**
2 deletion requests were submitted to Loki delete API. The requests were received and GET requests return their states as 'received', but that has not changed for 5 days now and the logs in question remain searchable. There have been no mentions of the deletion requests in Loki compactor logs since the submission confirmation.

**To Reproduce**
Submit the deletion request to Loki API using curl.
Check Loki logs and API for the status.
Wait...
Search for logs.

**Expected behavior**
The logs were expected to at least be removed from search results, but ideally from S3 storage too.

**Environment:**
 - Linux VMs, micro-services mode
 - Deployment tool: Ansible
- Loki version: 2.9.1
- Loki compactor and limits config blocs:
```
compactor:
  compaction_interval: 10m
  retention_delete_delay: 24h
  retention_enabled: true
  working_directory: /data1/loki/compactor
limits_config:
  cardinality_limit: 1000
  deletion_mode: filter-and-delete
  retention_period: 5y
```
- Storage backend: on-prem S3 (Ceph)
- Storage schema: v12 TSDB
- IndexGWs are active in the cluster.

Please let me know if you need more information.
