### ISSUE TITLE
[Helm] alibabacloud storage type is not supported

### ISSUE THREAD

**Issue by lindeskar** [grafana/loki#11945]
**Describe the bug**
The Loki Helm chart does not allow using `alibabacloud` in `.Values.loki.storage.type`.

**To Reproduce**
1. Configure Helm value `.Values.loki.storage.type` to be `alibabacloud`
2. Run `helm template` or `helm install`

**Expected behavior**
The Helm chart allows using the value and injects it in Helm templates where referenced.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Output from `helm template`:
```txt
Error: execution error at (context/charts/loki/templates/validate.yaml:26:4): Cannot run Scalable targets (backend, read, write) without an object storage backend.
```

**Comment by lindeskar** [comment]
Looks like this:

https://github.com/grafana/loki/blob/57619b76a4700d001d621212d6117120b18f060c/production/helm/loki/templates/validate.yaml#L25-L27

depends on this:

https://github.com/grafana/loki/blob/9e7725b31b19792dad692afd9ad7e9804c04bfc1/production/helm/loki/templates/_helpers.tpl#L600

which is missing `alibabacloud`.

**Comment by wang287611200** [comment]
hello @lindeskar I see you commit the alibabacloud storage type,but I don't kown how to config ,can you hekp me ? give me some samples?

**Comment by lindeskar** [comment]
> hello [@lindeskar](https://github.com/lindeskar) I see you commit the alibabacloud storage type,but I don't kown how to config ,can you hekp me ? give me some samples?

@wang287611200 I no longer have access to Alibaba Cloud, but back then I used something like:

```yaml
storage:
  type: "alibabacloud"

storage_config:
  alibabacloud:
    bucket: "my-bucket-name"
    endpoint: "oss-cn-hangzhou.aliyuncs.com"
    access_key_id: "${ALIBABA_ACCESS_KEY}"
    secret_access_key: "${ALIBABA_ACCESS_SECRET}"
```
