### ISSUE TITLE
K8s/Loki Distributed/Minio - Index/Fake not being saved to storage

### ISSUE THREAD

**Issue by FlanniganColum** [grafana/loki#12006]
**Describe the bug**
After setting doing a very basic setup of loki to work with minio storage i have found that none of the files are being stored in minio. I am not seeing any errors and i have tried multiple attempts to get this to work to no avail. Below is the config i am using and in this example i have a separate sidekick pod for the connection to minIO but once confirmed it is working ill be adding it as a sidecar to ensure best performance

`global:
  dnsService: "coredns"
loki:
  structuredConfig:
    storage_config:
      aws:
        s3: http://sidekick:9000
        endpoint: http://sidekick:9000
        bucketnames: loki
        access_key_id: XXXXXXXXXXXXXX
        secret_access_key: XXXXXXXXXXXXX
        insecure: true
        s3forcepathstyle: true

      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
        shared_store: s3
        resync_interval: 5m

    schema_config:
      configs:
        - from: 2022-01-11
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            prefix: loki_index_
            period: 24h`

Does anyone have any ideas on why this is not storing or any ideas about getting this to work. it seems Loki documentation has a long way to go before it is useful.

**To Reproduce**
1. Create test.yaml file
2. helm upgrade --install --values test.yaml loki grafana/loki-distributed -n loki-dev
3. Mnitoring minio bucked for files & monitoring for put requests
4. Only put request observed is loki_cluster_seed.json file being created and after that nothing

**Expected behavior**
Expected that the ingester would be saving the fake/index files to minio, When monitoring the /loki/index diectory i see no files being populated which is where the files shoudl be going

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: heml

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by htdangkhoa** [comment]
same issue

**Comment by edwardrf** [comment]
Same issue here with tsdb:
```
auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: aws
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
  aws:
    s3: s3://<region>/<bucket>
    access_key_id: <access_key>
    secret_access_key: <secret_key>

ruler:
  alertmanager_url: http://localhost:9093

```
