### ISSUE TITLE
RPC Error: Code(500) desc = Empty Ring When Querying Loki in Read-Only Mode with S3 Storage

### ISSUE THREAD

**Issue by Edition-X** [grafana/loki#12010]
**Describe the bug**
When attempting to run Loki in read-only mode locally on my MacBook Pro, querying Loki results in an "empty ring" error. This setup is intended for accessing logs stored in an S3 bucket with read-only permissions. Despite following the configuration guidelines, Loki fails to execute queries successfully, as indicated by repeated "rpc error: code = Code(500) desc = empty ring" errors.

**To Reproduce**
1. Run `docker-compose up` with the provided `docker-compose.yaml` and `local-config.yaml`

**Expected behavior**
Expected Loki to successfully query and return logs stored in the S3 bucket without encountering an "empty ring" error, allowing for read-only access to the logs through Grafana.

**Environment:**
 - Infrastructure: Docker on MacBook Pro
 - Deployment tool: Docker Compose

**Screenshots, Promtail config, or terminal output**

Relevant terminal output showcasing the error:
```
level=error ts=2024-02-20T18:46:43.380865587Z caller=retry.go:73 org_id=fake traceID=4b0cb9662f264025 msg="error processing request" try=0 query= err="rpc error: code = Code(500) desc = empty ring\n"
```

Full log output:
```
level=info ts=2024-02-20T18:45:13.490717045Z caller=main.go:108 msg="Starting Loki" version="(version=2.9.4, branch=HEAD, revision=f599ebc535)"
level=info ts=2024-02-20T18:45:13.491196629Z caller=server.go:322 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2024-02-20T18:45:13.49228967Z caller=memberlist_client.go:434 msg="Using memberlist cluster label and node name" cluster_label= node=0e1c4e21d2dd-ede7a373
level=info ts=2024-02-20T18:45:13.492721087Z caller=modules.go:1140 msg="-boltdb.shipper.compactor.shared-store not specified, initializing compactor to operator on the following object stores" stores=s3
level=info ts=2024-02-20T18:45:13.493044379Z caller=memberlist_client.go:540 msg="memberlist fast-join starting" nodes_found=1 to_join=4
level=info ts=2024-02-20T18:45:13.49335542Z caller=memberlist_client.go:560 msg="memberlist fast-join finished" joined_nodes=1 elapsed_time=312.875µs
level=info ts=2024-02-20T18:45:13.493364379Z caller=memberlist_client.go:573 msg="joining memberlist cluster" join_members=127.0.0.1:7946
level=info ts=2024-02-20T18:45:13.493515545Z caller=memberlist_client.go:592 msg="joining memberlist cluster succeeded" reached_nodes=1 elapsed_time=150.375µs
level=warn ts=2024-02-20T18:45:13.493577087Z caller=cache.go:127 msg="fifocache config is deprecated. use embedded-cache instead"
level=warn ts=2024-02-20T18:45:13.493587712Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache - chunksembedded-cache"
level=info ts=2024-02-20T18:45:13.493810045Z caller=table_manager.go:271 index-store=boltdb-shipper-2020-07-31 msg="query readiness setup completed" duration=750ns distinct_users_len=0 distinct_users=
level=info ts=2024-02-20T18:45:13.493821795Z caller=shipper.go:165 index-store=boltdb-shipper-2020-07-31 msg="starting index shipper in RO mode"
level=info ts=2024-02-20T18:45:13.493826795Z caller=shipper_index_client.go:76 index-store=boltdb-shipper-2020-07-31 msg="starting boltdb shipper in RO mode"
level=info ts=2024-02-20T18:45:13.493919295Z caller=table_manager.go:271 index-store=tsdb-2022-12-12 msg="query readiness setup completed" duration=334ns distinct_users_len=0 distinct_users=
level=info ts=2024-02-20T18:45:13.493923587Z caller=shipper.go:165 index-store=tsdb-2022-12-12 msg="starting index shipper in RO mode"
level=info ts=2024-02-20T18:45:13.494018587Z caller=table_manager.go:271 index-store=tsdb-2023-08-21 msg="query readiness setup completed" duration=292ns distinct_users_len=0 distinct_users=
level=info ts=2024-02-20T18:45:13.494022795Z caller=shipper.go:165 index-store=tsdb-2023-08-21 msg="starting index shipper in RO mode"
level=info ts=2024-02-20T18:45:13.494322337Z caller=worker.go:112 msg="Starting querier worker using query-scheduler and scheduler ring for addresses"
level=info ts=2024-02-20T18:45:13.494891837Z caller=mapper.go:47 msg="cleaning up mapped rules directory" path=/loki/rules-temp
level=info ts=2024-02-20T18:45:13.496812045Z caller=module_service.go:82 msg=initialising module=analytics
level=info ts=2024-02-20T18:45:13.49702342Z caller=module_service.go:82 msg=initialising module=server
level=info ts=2024-02-20T18:45:13.497068504Z caller=module_service.go:82 msg=initialising module=cache-generation-loader
level=info ts=2024-02-20T18:45:13.497127879Z caller=module_service.go:82 msg=initialising module=memberlist-kv
level=info ts=2024-02-20T18:45:13.49713667Z caller=module_service.go:82 msg=initialising module=query-frontend-tripperware
level=info ts=2024-02-20T18:45:13.497158129Z caller=module_service.go:82 msg=initialising module=compactor
level=info ts=2024-02-20T18:45:13.49722192Z caller=ring.go:273 msg="ring doesn't exist in KV store yet"
level=info ts=2024-02-20T18:45:13.497227712Z caller=module_service.go:82 msg=initialising module=query-scheduler-ring
level=info ts=2024-02-20T18:45:13.497238962Z caller=module_service.go:82 msg=initialising module=ring
level=info ts=2024-02-20T18:45:13.497243379Z caller=basic_lifecycler.go:297 msg="instance not found in the ring" instance=0e1c4e21d2dd ring=compactor
level=info ts=2024-02-20T18:45:13.497254129Z caller=basic_lifecycler_delegates.go:63 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2024-02-20T18:45:13.497262254Z caller=ring.go:273 msg="ring doesn't exist in KV store yet"
level=info ts=2024-02-20T18:45:13.497278504Z caller=ring.go:273 msg="ring doesn't exist in KV store yet"
level=info ts=2024-02-20T18:45:13.497283754Z caller=module_service.go:82 msg=initialising module=index-gateway-ring
level=info ts=2024-02-20T18:45:13.497295504Z caller=module_service.go:82 msg=initialising module=ingester-querier
level=info ts=2024-02-20T18:45:13.49730842Z caller=basic_lifecycler.go:297 msg="instance not found in the ring" instance=0e1c4e21d2dd ring=scheduler
level=info ts=2024-02-20T18:45:13.497319629Z caller=basic_lifecycler_delegates.go:63 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2024-02-20T18:45:13.497336545Z caller=compactor.go:395 msg="waiting until compactor is JOINING in the ring"
level=info ts=2024-02-20T18:45:13.497341879Z caller=compactor.go:399 msg="compactor is JOINING in the ring"
level=info ts=2024-02-20T18:45:13.49736842Z caller=ring.go:273 msg="ring doesn't exist in KV store yet"
level=info ts=2024-02-20T18:45:13.497400879Z caller=ringmanager.go:201 msg="waiting until scheduler is JOINING in the ring"
level=info ts=2024-02-20T18:45:13.497405337Z caller=ringmanager.go:205 msg="scheduler is JOINING in the ring"
level=info ts=2024-02-20T18:45:13.49741667Z caller=basic_lifecycler.go:297 msg="instance not found in the ring" instance=0e1c4e21d2dd ring=index-gateway
level=info ts=2024-02-20T18:45:13.497423629Z caller=basic_lifecycler_delegates.go:63 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2024-02-20T18:45:13.497504504Z caller=ringmanager.go:184 msg="waiting until index gateway is JOINING in the ring"
level=info ts=2024-02-20T18:45:13.49750817Z caller=ringmanager.go:188 msg="index gateway is JOINING in the ring"
level=info ts=2024-02-20T18:45:14.498139629Z caller=ringmanager.go:197 msg="waiting until index gateway is ACTIVE in the ring"
level=info ts=2024-02-20T18:45:14.498168963Z caller=ringmanager.go:214 msg="waiting until scheduler is ACTIVE in the ring"
level=info ts=2024-02-20T18:45:14.498192171Z caller=compactor.go:409 msg="waiting until compactor is ACTIVE in the ring"
level=info ts=2024-02-20T18:45:14.659376879Z caller=ringmanager.go:201 msg="index gateway is ACTIVE in the ring"
level=info ts=2024-02-20T18:45:14.659446088Z caller=module_service.go:82 msg=initialising module=store
level=info ts=2024-02-20T18:45:14.659457338Z caller=module_service.go:82 msg=initialising module=index-gateway
level=info ts=2024-02-20T18:45:14.659474213Z caller=module_service.go:82 msg=initialising module=ruler
level=info ts=2024-02-20T18:45:14.659484879Z caller=ruler.go:528 msg="ruler up and running"
level=info ts=2024-02-20T18:45:14.674210171Z caller=ringmanager.go:218 msg="scheduler is ACTIVE in the ring"
level=info ts=2024-02-20T18:45:14.674301838Z caller=module_service.go:82 msg=initialising module=querier
level=info ts=2024-02-20T18:45:14.674324671Z caller=module_service.go:82 msg=initialising module=query-frontend
level=info ts=2024-02-20T18:45:14.674325879Z caller=module_service.go:82 msg=initialising module=query-scheduler
level=info ts=2024-02-20T18:45:14.681312921Z caller=compactor.go:413 msg="compactor is ACTIVE in the ring"
level=info ts=2024-02-20T18:45:14.681339213Z caller=loki.go:505 msg="Loki started"
level=info ts=2024-02-20T18:45:17.676125339Z caller=worker.go:209 msg="adding connection" addr=172.25.0.2:9095
level=info ts=2024-02-20T18:45:17.685462131Z caller=scheduler.go:615 msg="this scheduler is in the ReplicationSet, will now accept requests."
level=info ts=2024-02-20T18:45:19.682796048Z caller=compactor.go:474 msg="this instance has been chosen to run the compactor, starting compactor"
level=info ts=2024-02-20T18:45:19.68308259Z caller=compactor.go:503 msg="waiting 10m0s for ring to stay stable and previous compactions to finish before starting compactor"
level=info ts=2024-02-20T18:45:24.678867217Z caller=frontend_scheduler_worker.go:107 msg="adding connection to scheduler" addr=172.25.0.2:9095
level=info ts=2024-02-20T18:45:56.290690301Z caller=roundtrip.go:295 org_id=fake traceID=2e435182fd6d95c2 msg="executing query" type=labels label= length=1h0m0s query=
level=info ts=2024-02-20T18:45:56.291481093Z caller=table_manager.go:195 index-store=tsdb-2023-08-21 msg="downloading all files for table loki_prod_012_tsdb_index_19773"
ts=2024-02-20T18:45:56.546416593Z caller=spanlogger.go:86 table-name=loki_prod_012_tsdb_index_19773 org_id=fake traceID=2e435182fd6d95c2 level=info msg="downloaded index set at query time" duration=254.744042ms
ts=2024-02-20T18:45:56.594128468Z caller=spanlogger.go:86 table-name=loki_prod_012_tsdb_index_19773 user-id=fake org_id=fake traceID=2e435182fd6d95c2 level=info msg="downloaded index set at query time" duration=301.887209ms
ts=2024-02-20T18:45:56.594570302Z caller=spanlogger.go:86 user=fake level=info org_id=fake traceID=2e435182fd6d95c2 latency=fast query_type=labels length=1h0m0s duration=302.927208ms status=200 label= query= splits=0 throughput=0B total_bytes=0B total_entries=0
level=info ts=2024-02-20T18:45:56.598184885Z caller=metrics.go:207 component=frontend org_id=fake traceID=2e435182fd6d95c2 latency=fast query_type=labels length=1h0m0s duration=307.194708ms status=200 label= query= splits=0 throughput=0B total_bytes=0B total_entries=0
level=info ts=2024-02-20T18:46:43.378590087Z caller=roundtrip.go:295 org_id=fake traceID=4b0cb9662f264025 msg="executing query" type=labels label= length=1h0m0s query=
ts=2024-02-20T18:46:43.379676962Z caller=spanlogger.go:86 user=fake level=info org_id=fake traceID=4b0cb9662f264025 latency=fast query_type=labels length=1h0m0s duration=206.708µs status=500 label= query= splits=0 throughput=0B total_bytes=0B total_entries=0
level=error ts=2024-02-20T18:46:43.380865587Z caller=retry.go:73 org_id=fake traceID=4b0cb9662f264025 msg="error processing request" try=0 query= err="rpc error: code = Code(500) desc = empty ring\n"
ts=2024-02-20T18:46:43.382119629Z caller=spanlogger.go:86 user=fake level=info org_id=fake traceID=4b0cb9662f264025 latency=fast query_type=labels length=1h0m0s duration=366.209µs status=500 label= query= splits=0 throughput=0B total_bytes=0B total_entries=0
level=error ts=2024-02-20T18:46:43.38288517Z caller=retry.go:73 org_id=fake traceID=4b0cb9662f264025 msg="error processing request" try=1 query= err="rpc error: code = Code(500) desc = empty ring\n"
ts=2024-02-20T18:46:43.38394742Z caller=spanlogger.go:86 user=fake level=info org_id=fake traceID=4b0cb9662f264025 latency=fast query_type=labels length=1h0m0s duration=133.625µs status=500 label= query= splits=0 throughput=0B total_bytes=0B total_entries=0
level=error ts=2024-02-20T18:46:43.384493045Z caller=retry.go:73 org_id=fake traceID=4b0cb9662f264025 msg="error processing request" try=2 query= err="rpc error: code = Code(500) desc = empty ring\n"
ts=2024-02-20T18:46:43.385007837Z caller=spanlogger.go:86 user=fake level=info org_id=fake traceID=4b0cb9662f264025 latency=fast query_type=labels length=1h0m0s duration=130.25µs status=500 label= query= splits=0 throughput=0B total_bytes=0B total_entries=0
level=error ts=2024-02-20T18:46:43.385287129Z caller=retry.go:73 org_id=fake traceID=4b0cb9662f264025 msg="error processing request" try=3 query= err="rpc error: code = Code(500) desc = empty ring\n"
ts=2024-02-20T18:46:43.385682712Z caller=spanlogger.go:86 user=fake level=info org_id=fake traceID=4b0cb9662f264025 latency=fast query_type=labels length=1h0m0s duration=73.708µs status=500 label= query= splits=0 throughput=0B total_bytes=0B total_entries=0
level=error ts=2024-02-20T18:46:43.385930254Z caller=retry.go:73 org_id=fake traceID=4b0cb9662f264025 msg="error processing request" try=4 query= err="rpc error: code = Code(500) desc = empty ring\n"
level=warn ts=2024-02-20T18:46:43.386030629Z caller=logging.go:123 traceID=4b0cb9662f264025 orgID=fake msg="GET /loki/api/v1/labels?start=1708451201357000000&end=1708454801357000000 (500) 7.533291ms Response: \"empty ring\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-GB,en;q=0.9,en-US;q=0.8; Dnt: 1; Sec-Ch-Ua: \"Not A(Brand\";v=\"99\", \"Microsoft Edge\";v=\"121\", \"Chromium\";v=\"121\"; Sec-Ch-Ua-Mobile: ?0; Sec-Ch-Ua-Platform: \"macOS\"; Sec-Fetch-Dest: empty; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Agent: Grafana/10.3.3; X-Datasource-Uid: P8E80F9AEF21F6940; X-Forwarded-For: 192.168.65.1; X-Grafana-Device-Id: 310296f19f96551646747ae53e294aee; X-Grafana-Org-Id: 1; X-Grafana-Referer: http://localhost:3000/explore?schemaVersion=1&panes=%7B%22s39%22%3A%7B%22datasource%22%3A%22P8E80F9AEF21F6940%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22expr%22%3A%22%22%2C%22queryType%22%3A%22range%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22P8E80F9AEF21F6940%22%7D%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D%7D&orgId=1; X-Plugin-Id: loki; "
level=info ts=2024-02-20T18:46:56.046135051Z caller=roundtrip.go:295 org_id=fake traceID=69a6d61bee63eb26 msg="executing query" type=labels label= length=1h0m0s query=
ts=2024-02-20T18:46:56.04741701Z caller=spanlogger.go:86 user=fake level=info org_id=fake traceID=69a6d61bee63eb26 latency=fast query_type=labels length=1h0m0s duration=338.583µs status=500 label= query= splits=0 throughput=0B total_bytes=0B total_entries=0
level=error ts=2024-02-20T18:46:56.047828176Z caller=retry.go:73 org_id=fake traceID=69a6d61bee63eb26 msg="error processing request" try=0 query= err="rpc error: code = Code(500) desc = empty ring\n"
ts=2024-02-20T18:46:56.048420843Z caller=spanlogger.go:86 user=fake level=info org_id=fake traceID=69a6d61bee63eb26 latency=fast query_type=labels length=1h0m0s duration=102.916µs status=500 label= query= splits=0 throughput=0B total_bytes=0B total_entries=0
level=error ts=2024-02-20T18:46:56.048618718Z caller=retry.go:73 org_id=fake traceID=69a6d61bee63eb26 msg="error processing request" try=1 query= err="rpc error: code = Code(500) desc = empty ring\n"
ts=2024-02-20T18:46:56.048921135Z caller=spanlogger.go:86 user=fake level=info org_id=fake traceID=69a6d61bee63eb26 latency=fast query_type=labels length=1h0m0s duration=64.999µs status=500 label= query= splits=0 throughput=0B total_bytes=0B total_entries=0
level=error ts=2024-02-20T18:46:56.04906251Z caller=retry.go:73 org_id=fake traceID=69a6d61bee63eb26 msg="error processing request" try=2 query= err="rpc error: code = Code(500) desc = empty ring\n"
ts=2024-02-20T18:46:56.049391843Z caller=spanlogger.go:86 user=fake level=info org_id=fake traceID=69a6d61bee63eb26 latency=fast query_type=labels length=1h0m0s duration=48.541µs status=500 label= query= splits=0 throughput=0B total_bytes=0B total_entries=0
level=error ts=2024-02-20T18:46:56.04953476Z caller=retry.go:73 org_id=fake traceID=69a6d61bee63eb26 msg="error processing request" try=3 query= err="rpc error: code = Code(500) desc = empty ring\n"
ts=2024-02-20T18:46:56.049809301Z caller=spanlogger.go:86 user=fake level=info org_id=fake traceID=69a6d61bee63eb26 latency=fast query_type=labels length=1h0m0s duration=53.042µs status=500 label= query= splits=0 throughput=0B total_bytes=0B total_entries=0
level=error ts=2024-02-20T18:46:56.049959218Z caller=retry.go:73 org_id=fake traceID=69a6d61bee63eb26 msg="error processing request" try=4 query= err="rpc error: code = Code(500) desc = empty ring\n"
level=warn ts=2024-02-20T18:46:56.049998218Z caller=logging.go:123 traceID=69a6d61bee63eb26 orgID=fake msg="GET /loki/api/v1/labels?start=1708451201357000000&end=1708454801357000000 (500) 3.974334ms Response: \"empty ring\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-GB,en;q=0.9,en-US;q=0.8; Dnt: 1; Sec-Ch-Ua: \"Not A(Brand\";v=\"99\", \"Microsoft Edge\";v=\"121\", \"Chromium\";v=\"121\"; Sec-Ch-Ua-Mobile: ?0; Sec-Ch-Ua-Platform: \"macOS\"; Sec-Fetch-Dest: empty; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Agent: Grafana/10.3.3; X-Datasource-Uid: P8E80F9AEF21F6940; X-Forwarded-For: 192.168.65.1; X-Grafana-Device-Id: 310296f19f96551646747ae53e294aee; X-Grafana-Org-Id: 1; X-Grafana-Referer: http://localhost:3000/explore?schemaVersion=1&panes=%7B%22s39%22%3A%7B%22datasource%22%3A%22P8E80F9AEF21F6940%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22expr%22%3A%22%22%2C%22queryType%22%3A%22range%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22P8E80F9AEF21F6940%22%7D%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D%7D&orgId=1; X-Plugin-Id: loki;
```

docker-compose.yaml:
```
version: "3.8"

networks:
  loki: {}

services:
  loki:
    # image: grafana/loki:2.8.2
    image: grafana/loki:latest
    ports:
      - "3100:3100"
      - 7946
      - 9095
      - 8500
    volumes:
      - ./local-config.yaml:/etc/loki/local-config.yaml:ro
    command: '-config.file=/etc/loki/local-config.yaml -log.level=info -target=read'
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          jsondata:
            timeout: 600
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
```

local-config.yaml:
```
auth_enabled: false

server:
  http_listen_port: 3100
  http_server_read_timeout: 10m
  http_server_write_timeout: 10m
  grpc_server_keepalive_timeout: 10m

memberlist:
  join_members:
    # - loki:7946
    - 127.0.0.1:7946

limits_config:
  query_timeout: 10m


common:
  path_prefix: /loki
  replication_factor: 1
  # compactor_address: loki:3100
  compactor_address: 127.0.0.1:3100
  ring:
    kvstore:
      store: memberlist
  storage:
    s3:
      bucketnames: bucket-name
      region: eu-west-1
      access_key_id: 
      secret_access_key:
      session_token:
      s3forcepathstyle: true
      insecure: true
      sse_encryption: false

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    shared_store: s3
    cache_location: /loki/boltdb-cache
  tsdb_shipper:
    shared_store: s3
    cache_location: /loki/tsdb-cache

schema_config:
  configs:
  - from: "2020-07-31"
    store: boltdb-shipper
    object_store: s3
    schema: v12
    index:
      prefix: loki_prod_012_index_
      period: 1d
      tags: {}
    chunks:
      prefix: ""
      period: 0s
      tags: {}
    row_shards: 16
  - from: "2022-12-12"
    store: tsdb
    object_store: s3
    schema: v12
    index:
      prefix: loki_prod_012_tsdb_index_
      period: 1d
      tags: {}
    chunks:
      prefix: ""
      period: 0s
      tags: {}
    row_shards: 16
  - from: "2023-08-21"
    store: tsdb
    object_store: s3
    schema: v13
    index:
      prefix: loki_prod_012_tsdb_index_
      period: 1d
      tags: {}
    chunks:
      prefix: ""
      period: 0s
      tags: {}
    row_shards: 16
```

Additional context

- The docker-compose.yml and Loki configuration files are set up to facilitate a read-only connection to an S3 bucket for log storage.

- The issue seems to be related to the memberlist configuration, potentially due to misconfiguration or a misunderstanding of the required setup for read-only mode operations.
