### ISSUE TITLE
helm chart ignores http_config for ruler storage configuration

### ISSUE THREAD

**Issue by sebhoss** [grafana/loki#12112]
**Describe the bug**

I have the following in my helm values.yaml:

```yaml
loki:
  storage:
    s3:
      http_config:
        ...
```

The rendered ConfigMap does include everything in `http_config` in its `common` field:

```yaml
data:
  config.yaml: |
    common:
      storage:
        s3:
          http_config:
            ...
```

However the `ruler` configuration does not include the `http_config` which causes connection errors in my setup. Adding the `http_config` section manually fixes this.

**To Reproduce**
1. Render helm chart with the above values.yaml
2. Look at generated ConfigMap

**Expected behavior**

The `ruler` configuration should include the `http_config` as well. 

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**

none applicable
