### ISSUE TITLE
querier component: error getting addresses from ring

### ISSUE THREAD

**Issue by wolf666666** [grafana/loki#12138]
**Describe the bug**
When upgrade the loki version(2.9.3 or 2.9.5), the loki-querier componient, the log always have error logs:
Mar 05 10:57:16 seliius29524 loki-2.9.3[3950949]: level=error ts=2024-03-05T09:57:16.116271811Z caller=ring_watcher.go:56 component=querier-scheduler-worker msg="error getting addresses from ring" err="empty ring"
Mar 05 10:57:19 seliius29524 loki-2.9.3[3950949]: level=error ts=2024-03-05T09:57:19.115903431Z caller=ring_watcher.go:56 component=querier-scheduler-worker msg="error getting addresses from ring" err="empty ring"

I did not config querier-scheduler, the query-frontend has configed frontend.downstream-url

**To Reproduce**
1. Started Loki  querier component(2.9.3)

**Expected behavior**
correct the error log.

**Environment:**
 - Infrastructure: [REH9]

**Comment by wolf666666** [comment]
resolved by set -query-scheduler.use-scheduler-ring=false
I print the config with parameter -print-config-stderr, I find the default value of query-scheduler.use-scheduler-ring is true, i don't know why

**Comment by bobykus31** [comment]
is it really a resolution to disable -query-scheduler.use-scheduler-ring?

**Comment by bobykus31** [comment]
It looks like all rings are empty. while 

```

memberlist:
  node_name: ""
  randomize_node_name: false
  stream_timeout: 1m0s
  retransmit_factor: 4
  pull_push_interval: 2m0s
  gossip_interval: 200ms
  gossip_nodes: 3
  gossip_to_dead_nodes_time: 2m30s
  dead_node_reclaim_time: 5m0s
  compression_enabled: true
  advertise_addr: ""
  advertise_port: 7946
  cluster_label: ""
  cluster_label_verification_disabled: false
  join_members:
  - lokiread-k8s1:7946
  - lokiread-k8s2:7946
  - lokiread-k8s3:7946
```
  
and 

```
index_gateway:
  mode: ring
  ring:
    kvstore:
      store: memberlist
```
The 

http://lokiread-k8s1:3100/indexgateway/ring 

is empty. Config like this  was just fine in 2.x.x

So the same seems to be with a  scheduler-ring. Why is the solution to disable it?

**Comment by bobykus31** [comment]
ah, it does not work with `target=read`!

**Comment by csh0101** [comment]
I build a loki v3.0.0 on my k3s cluster and this problem is occur, but some time ago (15 30sencods) maybe , it will be health? why?

**Comment by Vinaum8** [comment]
> I build a loki v3.0.0 on my k3s cluster and this problem is occur, but some time ago (15 30sencods) maybe , it will be health? why?

me too, i need help with config grafana loki and ipv6 eks cluster.

**Comment by cgustav** [comment]
How i solved it with simple scalable install.

```yaml
loki:
  auth_enabled: false
  commonConfig:
    ring:
      kvstore:
        # Backend storage to use for the ring. Supported values are: consul, etcd,
        # inmemory, memberlist, multi.
        # CLI flag: -common.storage.ring.store
        store: memberlist

```

**Comment by salacr** [comment]
Are you running it on kubernetes / docker / swarm ?
For some reason I have a problem to run a SSD with memberlist in swarm enviroment :/

**Comment by mac133k** [comment]
> How i solved it with simple scalable install.
> 
> loki:
>   auth_enabled: false
>   commonConfig:
>     ring:
>       kvstore:
>         # Backend storage to use for the ring. Supported values are: consul, etcd,
>         # inmemory, memberlist, multi.
>         # CLI flag: -common.storage.ring.store
>         store: memberlist

Worked for me, however in my values overrides I had to explicitly set scheduler address to an empty string in loki.structuredConfig to make sure it is not overridden by Helm templates in other places, ie.:
```
loki
  structuredConfig:
    frontend:
      scheduler_address: ''
    frontend_worker:
      scheduler_address: ''
    query_scheduler:
      use_scheduler_ring: true
      scheduler_ring:
        kvstore:
          store: memberlist
```
