### ISSUE TITLE
compactor.shared_store and compactor.delete_request_store not support named_stores.

### ISSUE THREAD

**Issue by xpader** [grafana/loki#12145]
**Describe the bug**
When set `compactor.shared_store` or `compactor.delete_request_store` to named stores name, loki fails to start with error:
```
failed to init delete store. Object client not found for minio
error initialising module: compactor
github.com/grafana/dskit/modules.(*Manager).initModule
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/loki/pkg/loki.(*Loki).Run
        /src/loki/pkg/loki/loki.go:461
main.main
        /src/loki/cmd/loki/main.go:110
runtime.main
        /usr/local/go/src/runtime/proc.go:267
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1650
```

**To Reproduce**
1. Change compactor shared_store or delete_request_store to a named_store like:
```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 20000000

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  named_stores:
    aws:
      minio:
        s3: http://xxxxxxx:xxxxxxxxxxx@192.168.1.154:9000/loki
        s3forcepathstyle: true
      obs:
        s3forcepathstyle: true
        bucketnames: loki-log-chunks
        endpoint: https://obs.north-4.xxx.com
        access_key_id: xxxxxxxxx
        secret_access_key: xxxxxxxx

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h
    - from: 2024-02-28
      store: tsdb
      object_store: minio
      schema: v12
      index:
        prefix: index_
        period: 24h

chunk_store_config:
  chunk_cache_config:
    redis:
      endpoint: "127.0.0.1:6379"
      db: 2
      idle_timeout: 30
      expiration: 1h

ruler:
  alertmanager_url: http://localhost:9093

limits_config:
  allow_structured_metadata: true
  ingestion_rate_mb: 32
  ingestion_burst_size_mb: 64
  max_global_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 24h
  #max_query_lookback: 336h
  retention_period: 336h
  max_query_series: 2000

query_scheduler:
  max_outstanding_requests_per_tenant: 10000

compactor:
  working_directory: /loki/retention
  shared_store: minio
  retention_enabled: true

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h
```
1. Started Loki (2.9.4)
3. Loki started failed with errors.

**Expected behavior**
Loki running good and shared_store, delete_request_store works with named stores.
