### ISSUE TITLE
Leave config compactor.shared_store empty changed index directory structure

### ISSUE THREAD

**Issue by xpader** [grafana/loki#12144]
**Describe the bug**
After change compactor.shared_store from "filesystem" to empty, the chunks/index/ directory structure changed.

Index directory structure before:
index/index_19788/1709714725-4190a62bcac5-1699356495812046098.tsdb.gz
index/index_19788/1709717425-4190a62bcac5-1699356495812046098.tsdb.gz

Index directory structure after:
index/index_19760/fake/1709397279-compactor-1707262144888-1707356939531-199e0224.tsdb.gz
index/index_19788/fake/1709708079-compactor-1709678517450-1709707516058-f77fe4d4.tsdb.gz

There's a 'fake/' directory in every index path.

When change compactor.shared_store from empty to "filesystem", directory structure came back.

My config before:
```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 20000000

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  named_stores:
    aws:
      minio:
        s3: http://xxxxxxxxxx:xxxxxxxxxxxxxx@192.168.1.154:9000/loki
        s3forcepathstyle: true
      obs:
        s3forcepathstyle: true
        bucketnames: loki-log-chunks
        endpoint: https://obs.north-4.xxx.com
        access_key_id: xxxxxxx
        secret_access_key: xxxxxxxxxxxxxxxxxxxx

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h
    - from: 2024-02-28
      store: tsdb
      object_store: minio
      schema: v12
      index:
        prefix: index_
        period: 24h

chunk_store_config:
  chunk_cache_config:
    redis:
      endpoint: "127.0.0.1:6379"
      db: 2
      idle_timeout: 30
      expiration: 1h

ruler:
  alertmanager_url: http://localhost:9093

limits_config:
  allow_structured_metadata: true
  ingestion_rate_mb: 32
  ingestion_burst_size_mb: 64
  max_global_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 24h
  #max_query_lookback: 336h
  retention_period: 336h
  max_query_series: 2000

query_scheduler:
  max_outstanding_requests_per_tenant: 10000

compactor:
  working_directory: /loki/retention
  shared_store: filesystem
  retention_enabled: true

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h
```

My config after, compactor.shared_store is removed:
```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 20000000

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  named_stores:
    aws:
      minio:
        s3: http://xxxxxxxxxx:xxxxxxxxxxxxxx@192.168.1.154:9000/loki
        s3forcepathstyle: true
      obs:
        s3forcepathstyle: true
        bucketnames: loki-log-chunks
        endpoint: https://obs.north-4.xxx.com
        access_key_id: xxxxxxx
        secret_access_key: xxxxxxxxxxxxxxxxxxxx

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h
    - from: 2024-02-28
      store: tsdb
      object_store: minio
      schema: v12
      index:
        prefix: index_
        period: 24h

chunk_store_config:
  chunk_cache_config:
    redis:
      endpoint: "127.0.0.1:6379"
      db: 2
      idle_timeout: 30
      expiration: 1h

ruler:
  alertmanager_url: http://localhost:9093

limits_config:
  allow_structured_metadata: true
  ingestion_rate_mb: 32
  ingestion_burst_size_mb: 64
  max_global_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 24h
  #max_query_lookback: 336h
  retention_period: 336h
  max_query_series: 2000

query_scheduler:
  max_outstanding_requests_per_tenant: 10000

compactor:
  working_directory: /loki/retention
  shared_store: filesystem
  retention_enabled: true

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h
```

**To Reproduce**
1. Stay config compactor.shared_store to filesystem.
2. Started Loki (2.9.4)
3. Write some logs and wait for flush to storage.
4. Watch the index structure is like `index/index_19788/1709714725-4190a62bcac5-1699356495812046098.tsdb.gz`
5. Remove compactor.shared_store in config, and restart loki.
6. Write some logs and wait for flush to storage.
7. Watch the index structure is like `index/index_19788/fake/1709708079-compactor-1709678517450-1709707516058-f77fe4d4.tsdb.gz`

**Expected behavior**
Index structure is always like `index structure is like `index/index_19788/1709714725-4190a62bcac5-1699356495812046098.tsdb.gz``.

**Environment:**
 - Loki 2.9.4
