### ISSUE TITLE
The logs volume query has timed out

### ISSUE THREAD

**Issue by Tiduster** [grafana/loki#12153]
**Describe the bug**
The following error message appear "The logs volume query has timed out" instead of displaying the Logs volume chart. The message appear 3-5 seconds after the execution of the query. The result of the query is return without issue.

I read a lot of issues, and was not able to find an explication.
I know that there is a Grafana timeout and a Loki timeout, but the value are much longer than a few seconds.
I know that there was a specific log volume timeout (10sec) but it's not present in current version and my timeout is triggered really quickly (3 to 5 sec).

**To Reproduce**
1. Loki 2.9.1 SingleBinary
2. Chart Loki from https://grafana.github.io/helm-charts, revision 5.43.3
3. Configuration:
```
        helm:
            values: |
                loki:
                  commonConfig:
                    replication_factor: 2
                  auth_enabled: false
                  revisionHistoryLimit: 3
                  podLabels:
                    azure.workload.identity/use: "true"

                  storage:
                    type: azure
                    bucketNames:
                      chunks: loki
                    azure:
                      accountName: ***********
                      useFederatedToken: true

                  compactor:
                    shared_store: azure
                    compaction_interval: 10m
                    retention_enabled: true
                    retention_delete_delay: 2h
                    retention_delete_worker_count: 150

                  limits_config:
                    max_cache_freshness_per_query: 10m
                    split_queries_by_interval: 60m
                    retention_period: 720h #equals to 30 days

                  query_scheduler:
                    max_outstanding_requests_per_tenant: 2048

                serviceAccount:
                  annotations:
                    azure.workload.identity/tenant-id: ***********
                    azure.workload.identity/client-id: ***********
                  labels:
                    azure.workload.identity/use: "true"

                singleBinary:
                  replicas: 2
                  persistence:
                    enabled: true
                    enableStatefulSetAutoDeletePVC: true
                    size: 10Gi

                monitoring:
                  selfMonitoring:
                    enabled: true
                  lokiCanary:
                    enabled: true
                  serviceMonitor:
                    enabled: true
                    labels:
                      release: prometheus

                gateway:
                  enabled: false
```

5. Query: Get some logs for a pod, even for a small interval like 24h

**Expected behavior**
Query return correctly and Logs volume chart is displayed

**Environment:**
 - Infrastructure: Kubernetes, Azure AKS
 - Deployment tool: ArgoCD / Helm

**Screenshots, Promtail config, or terminal output**
![Screenshot from 2024-03-06 23-34-17](https://github.com/grafana/loki/assets/1652493/5c429307-b101-4916-8697-7474a6f20fa9)
