### ISSUE TITLE
promtail not ready

### ISSUE THREAD

**Issue by chesha1** [grafana/loki#12177]
**Describe the bug**
When installing promtail with Helm, all pods are running but not ready.

The log directroy is not default, below is the `values.yaml` I use for installation.
```yaml
image:
  registry: docker.mirrors.sjtug.sjtu.edu.cn
config:
  clients:
    - url: http://192.168.48.67:3100/loki/api/v1/push
  snippets:
    pipelineStages:
      - cri: {}
    common:
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - namespace
          - app
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /home/cce/docker/containers/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        replacement: /home/cce/docker/containers/*$1/*.log
        regex: true/(.*)
        separator: /
        source_labels:
          - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
          - __meta_kubernetes_pod_container_name
        target_label: __path__

defaultVolumes:
  - name: run
    hostPath:
      path: /run/promtail
  # - name: containers
  #   hostPath:
  #     path: /var/lib/docker/containers
  - name: pods
    hostPath:
      path: /home/cce/docker/containers

defaultVolumeMounts:
  - name: run
    mountPath: /run/promtail
  # - name: containers
  #   mountPath: /var/lib/docker/containers
  #   readOnly: true
  - name: pods
    mountPath: /home/cce/docker/containers
    readOnly: true
```

The output of `kubectl logs promtail-xxx` looks like:
```
level=info ts=2024-03-12T07:13:50.070674761Z caller=promtail.go:133 msg="Reloading configuration file" md5sum=0cd7edc0fc5b0a7255e8bd57f24f7a97
level=info ts=2024-03-12T07:13:50.071149836Z caller=kubernetes.go:327 component=discovery discovery=kubernetes config=kubernetes-pods msg="Using pod service account via in-cluster config"
level=info ts=2024-03-12T07:13:50.072038958Z caller=server.go:322 http=[::]:3101 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2024-03-12T07:13:50.072185507Z caller=main.go:174 msg="Starting Promtail" version="(version=2.9.3, branch=HEAD, revision=2535f9bede)"
level=warn ts=2024-03-12T07:13:50.072205218Z caller=promtail.go:263 msg="enable watchConfig"
level=info ts=2024-03-12T07:13:55.071349307Z caller=filetargetmanager.go:361 msg="Adding target" key="/home/cce/docker/containers/*4f5329b7-8d6e-4b39-8b1d-47b21f8b45fa/cce-cgpu-monitor/*.log:{app=\"cce-cgpu-monitor\", container=\"cce-cgpu-monitor\", job=\"kube-system/cce-cgpu-monitor\", namespace=\"kube-system\", node_name=\"192.168.48.6\", pod=\"cce-cgpu-monitor-7n2bp\"}"
level=info ts=2024-03-12T07:13:55.071438871Z caller=filetargetmanager.go:361 msg="Adding target" key="/home/cce/docker/containers/*4f5329b7-8d6e-4b39-8b1d-47b21f8b45fa/cgpu-init/*.log:{app=\"cce-cgpu-monitor\", container=\"cgpu-init\", job=\"kube-system/cce-cgpu-monitor\", namespace=\"kube-system\", node_name=\"192.168.48.6\", pod=\"cce-cgpu-monitor-7n2bp\"}"
level=info ts=2024-03-12T07:13:55.07319296Z caller=filetargetmanager.go:361 msg="Adding target" key="/home/cce/docker/containers/*71b8ec0c-aa96-4e6c-9525-154e4ee39a6a/nvidia-device-plugin-ctr/*.log:{app=\"nvidia-device-plugin-daemonset\", container=\"nvidia-device-plugin-ctr\", job=\"kube-system/nvidia-device-plugin-daemonset\", namespace=\"kube-system\", node_name=\"192.168.48.6\", pod=\"nvidia-device-plugin-daemonset-nq42f\"}"
level=warn ts=2024-03-12T07:14:06.142310244Z caller=logging.go:123 msg="GET /ready (500) 102.091µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept: */*; Connection: close; User-Agent: kube-probe/1.20; "
level=warn ts=2024-03-12T07:14:16.142112461Z caller=logging.go:123 msg="GET /ready (500) 39.407µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept: */*; Connection: close; User-Agent: kube-probe/1.20; "
level=warn ts=2024-03-12T07:14:26.142440383Z caller=logging.go:123 msg="GET /ready (500) 40.958µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept: */*; Connection: close; User-Agent: kube-probe/1.20; "
level=warn ts=2024-03-12T07:14:36.142356017Z caller=logging.go:123 msg="GET /ready (500) 41.68µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept: */*; Connection: close; User-Agent: kube-probe/1.20; "
```

When I use `kubectl exec -it promtail-xxx -n promtail -- /bin/sh` to enter the pod, the directory targetted do have logs:
```bash
# ls /home/cce/docker/containers
001f6de4f56e4fdb6943ec9d6b9fe9fe7d4abe01c5a761dc41a724cf00b1cce2
00af6082dd37ed10110daba56dde66c8575e4f4e1fa9b971619131500a86c8f3
033d6c89efe5d6df7af9db9e24b1c4e3e4aa56b485a79e13e7da2a4cc7e2557e
```
```bash
# ls /home/cce/docker/containers/001f6de4f56e4fdb6943ec9d6b9fe9fe7d4abe01c5a761dc41a724cf00b1cce2
001f6de4f56e4fdb6943ec9d6b9fe9fe7d4abe01c5a761dc41a724cf00b1cce2-json.log  config.v2.json   hostname  mounts
checkpoints                                                                hostconfig.json  hosts     resolv.conf
```
```bash
# cat xxx.log
{"log":"Warning: pause should be the first process\n","stream":"stderr","time":"2023-11-08T08:46:40.312695133Z"}
```
```bash
# cat /run/promtail/positions.yaml
positions: {}
```
