### ISSUE TITLE
api/v1/index/volume not working

### ISSUE THREAD

**Issue by DanielCastronovo** [grafana/loki#12185]
**Describe the bug**
Volume endpoint not working

**To Reproduce**
```
curl -G "http://loki-read:3100/loki/api/v1/labels"
{"status":"success","data":["account","app","cluster","component","container","filename","instance","job","namespace","node_name","pod","region","source","stream"]}

curl -G "http://loki-read.3100/loki/api/v1/status/buildinfo"
{"version":"2.9.3","revision":"2535f9bede","branch":"HEAD","buildUser":"root@7ff3d2769ef3","buildDate":"2023-12-11T19:11:37Z","goVersion":""}

# curl -G http://loki-read:3100/loki/api/v1/index/volume?query={cluster="test-cluster"}&start=1710098439&end=1710262808
not found
```

**Expected behavior**
log volume for the label cluster

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Comment by MarcBrendel** [comment]
Ran into the same problem today, it needs to be enabled first:

```YAML
limits_config:
  # Enable log-volume endpoints.
  volume_enabled: true

  # The maximum number of aggregated series in a log-volume response
  # CLI flag: -limits.volume-max-series
  volume_max_series: 1000
```

[https://grafana.com/docs/loki/latest/configure/#limits_config](https://grafana.com/docs/loki/latest/configure/#limits_config)
