### ISSUE TITLE
Data source connected, but no labels received

### ISSUE THREAD

**Issue by taimoor-mirza29** [grafana/loki#12192]
**Describe the bug**
 I am trying to do basic level PoC of Loki stack on one of our servers (based on RHEL) using the Docker compose file provided [here](https://github.com/grafana/loki/tree/main/production/docker). However, every time I run the containers, and test the Grafana's connection with Loki data source, I get the following exception:

`Data source connected, but no labels received. Verify that Loki and Promtail is configured properly.`

**To Reproduce**
1. Run the following `docker-compose.yml` with provided config files

**Docker Compose**
```yaml
# docker-compose.yml
services:
  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - ./loki/:/var/log/
      - ./config:/etc/promtail/
    ports:
      - "9080:9080"
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - loki

  loki-1:
    image: grafana/loki:2.9.2
    container_name: loki-testing-1
    volumes:
      - ./config:/etc/loki/
    ports:
      - "3100:3100"
      - "7946:7946"
    command: "-reporting.enabled=false -config.file=/etc/loki/loki.yaml -target=all -legacy-read-mode=false"
    networks:
      - loki
    user: "0:0"
    restart: always
```

**Loki Settings**
```yaml
# config/loki.yml
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

common:
  path_prefix: /loki
  compactor_address: http://loki-testing-1:3100/
  replication_factor: 1

storage_config:
  aws:
    endpoint: minio:9000
    insecure: true
    bucketnames: loki-data
    access_key_id: loki
    secret_access_key: supersecret
    s3forcepathstyle: true

memberlist:
  join_members:
    - loki-testing-1
   # - loki-testing-2
   # - loki-testing-3
   # - "loki-read"
    #  - "loki-write"
    # - "loki-backend"
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr: ['0.0.0.0']
  bind_port: 7946
  gossip_interval: 2s


ingester:
  lifecycler:
    join_after: 10s
    observe_period: 5s
    ring:
      replication_factor: 1
      kvstore:
        store: memberlist
    final_sleep: 0s
  chunk_idle_period: 1m
  wal:
    enabled: true
    dir: /loki/wal
  max_chunk_age: 1m
  chunk_retain_period: 30s
  chunk_encoding: snappy
  chunk_target_size: 1.572864e+06
  chunk_block_size: 262144
  flush_op_timeout: 10s

ruler:
  enable_api: true
  enable_sharding: true
  wal:
    dir: /loki/ruler-wal
  evaluation:
    mode: remote
    query_frontend:
      address: dns:///loki-testing-1:9095
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/prom-rules
  remote_write:
    # enabled: true
    # clients:
    #   local:
    #      url: http://prometheus:9090/api/v1/write
    #      queue_config:
    #        # send immediately as soon as a sample is generated
    #        capacity: 1
    #        batch_send_deadline: 0s

schema_config:
  configs:
  - from: 2020-08-01
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: index_
      period: 24h
  - from: 2023-07-11
    store: tsdb
    object_store: s3
    schema: v12
    index:
      prefix: index_
      period: 24h
  - from: 2024-01-10
    store: tsdb
    object_store: s3
    schema: v12
    index:
      prefix: index_
      period: 24h


limits_config:
  max_cache_freshness_per_query: '10m'
  reject_old_samples: true
  reject_old_samples_max_age: 30m
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  # parallelize queries in 15min intervals
  split_queries_by_interval: 15m
  volume_enabled: true

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h

query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 5
  parallelise_shardable_queries: true
  cache_results: true

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  max_outstanding_per_tenant: 2048

query_scheduler:
  max_outstanding_requests_per_tenant: 1024

querier:
  query_ingesters_within: 2h

compactor:
  working_directory: /tmp/compactor
```

**Promtail Settings**
```yaml
# config/promtail.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.150.87:3100/loki/api/v1/push
    tenant_id: docker

scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
```
**Expected behavior**
Grafana should be receiving labels from Loki.

**Environment:**
 - Infrastructure: bare-metal (RHEL 7.9 Maipo)
 - Deployment tool: Docker

**Screenshots, Promtail config, or terminal output**
![grafana-errro-ss](https://github.com/grafana/loki/assets/156061320/a31a1e38-ffb6-4289-8e0a-50e414e9757d)

**Comment by taimoor-mirza29** [comment]
Update: I figured what's wrong with my settings. I went thought the following section of [documentation](https://grafana.com/docs/loki/latest/send-data/promtail/scraping/#journal-scraping-linux-only). There were 2 issues exactly:

- Journalctl (if persistence is enabled) by default dumps logs in /var/log/journal/$(cat /etc/machine-id) path. I wasn't mounting this path in Promtail's service in Docker Compose. Final shape of docker-compose.yml looks like this:
  ```yaml
    promtail:
      image: grafana/promtail:2.9.2
      container_name: promtail
      volumes:
        - ./loki/:/var/log/
        - ./config:/etc/promtail/
        - /var/log/journal/:/var/log/journal/
        - /etc/machine-id:/etc/machine-id # required for journalctl logs
      ports:
        - "9080:9080"
      command: -config.file=/etc/promtail/promtail.yaml
      networks:
        - loki
    ```
 - The same path needs to be present in promtail.yml config file
   ```yaml
    scrape_configs:
      - job_name: journal
        journal:
          json: false
          max_age: 12h
          path: /var/log/journal # must match the path where host's log path is mounted.
          labels:
            job: systemd-journal
    ````
