### ISSUE TITLE
Error "Empty results, no matching label"

### ISSUE THREAD

**Issue by duj4** [grafana/loki#12200]
**Describe the bug**
I ingested a log snippet with elder timestamp:
> 2024-03-09 11:27:22,725+0800 index-writer-stats-CHANGE_HISTORY-3-0 INFO      [c.a.jira.index.WriterWithStats] [JIRA-STATS] [index-writer-stats] CHANGE_HISTORY : snapshot stats: {"addDocumentsMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{}},"deleteDocumentsMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{}},"updateDocumentsMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{}},"updateDocumentConditionallyMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{}},"updateDocumentsWithVersionMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{"10":0,"100":0,"500":0,"1000":0,"5000":0,"10000":0,"30000":0,"60000":0}},"updateDocumentsWithVersionSize":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{"1":0,"10":0,"100":0,"1000":0,"10000":0}},"replaceDocumentsWithVersionMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{"10":0,"100":0,"500":0,"1000":0,"5000":0,"10000":0,"30000":0,"60000":0}},"replaceDocumentsWithVersionSize":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{"1":0,"10":0,"100":0,"1000":0,"10000":0}},"optimizeMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{}},"closeMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{}},"commitMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{}}}, index writer version cache stats: {"put":0,"get":0,"getFound":0,"clear":0,"clearSizeExceeded":0}, index writer searcher stats: {"createNew":0,"reuse":0}
> 2024-03-09 11:27:22,745+0800 index-writer-stats-WORKLOG-4-0 INFO      [c.a.jira.index.WriterWithStats] [JIRA-STATS] [index-writer-stats] WORKLOG : total stats: {"addDocumentsMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{}},"deleteDocumentsMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{}},"updateDocumentsMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{}},"updateDocumentConditionallyMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{}},"updateDocumentsWithVersionMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{"10":0,"100":0,"500":0,"1000":0,"5000":0,"10000":0,"30000":0,"60000":0}},"updateDocumentsWithVersionSize":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{"1":0,"10":0,"100":0,"1000":0,"10000":0}},"replaceDocumentsWithVersionMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{"10":0,"100":0,"500":0,"1000":0,"5000":0,"10000":0,"30000":0,"60000":0}},"replaceDocumentsWithVersionSize":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{"1":0,"10":0,"100":0,"1000":0,"10000":0}},"optimizeMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{}},"closeMillis":{"count":0,"min":0,"max":0,"sum":0,"avg":0,"distributionCounter":{}},"commitMillis":{"count":5,"min":1,"max":21,"sum":56,"avg":11,"distributionCounter":{}}}, index writer version cache stats: {"put":0,"get":0,"getFound":0,"clear":0,"clearSizeExceeded":0}, index writer searcher stats: {"createNew":0,"reuse":0}
> 
But when I tried to query it from Grafana, error below posted:
![image](https://github.com/grafana/loki/assets/19278537/93d1cd56-ddd1-4537-95e4-0bde17bf4c92)

If I ingested fresh log snippet:
> 2024-03-13 23:53:51,980+0800 JIRA-Bootstrap INFO      [c.a.plugin.util.WaitUntil] Plugins that have yet to be enabled: (18): [com.codebarrel.addons.automation, com.atlassian.servicedesk.servicedesk-knowledge-base-plugin, com.atlassian.jira.migration.jira-migration-plugin, com.atlassian.servicedesk.incident-management-plugin, com.atlassian.servicedesk.project-ui, com.atlassian.servicedesk.plugins.automation.servicedesk-automation-modules-plugin, com.atlassian.servicedesk.frontend-webpack-plugin, com.atlassian.servicedesk.public-rest-api, com.atlassian.servicedesk.servicedesk-variable-substitution-plugin, com.atlassian.servicedesk.plugins.servicedesk-search-plugin, com.atlassian.servicedesk.servicedesk-reports-plugin, com.atlassian.servicedesk.servicedesk-lingo-integration-plugin, com.atlassian.servicedesk.servicedesk-notifications-plugin, com.atlassian.jira.mobile.jira-mobile-rest, com.atlassian.servicedesk, com.atlassian.servicedesk.plugins.automation.servicedesk-automation-then-webhook-plugin, com.atlassian.servicedesk.servicedesk-canned-responses-plugin, com.atlassian.servicedesk.approvals-plugin], 282 seconds remaining
> 2024-03-13 23:53:51,985+0800 ThreadPoolAsyncTaskExecutor::Thread 8 INFO      [c.a.j.migration.guardrails.AccessLogProcessingJobRunner] Successfully registered access log processing job {}. jira-migration-access-log-processing-job-key
> 2024-03-13 23:53:52,029+0800 ThreadPoolAsyncTaskExecutor::Thread 8 INFO      [c.a.j.migration.mediaclient.MediaClient] media base url: https://api.media.atlassian.com
> 
The query looks good from Grafana:
![image](https://github.com/grafana/loki/assets/19278537/98c0e3c1-a831-4501-a61a-3a9b5fb3cc99)

**To Reproduce**
1. Deployed Loki ({"version":"2.9.4","revision":"f599ebc535","branch":"HEAD","buildUser":"root@5d9969758d88","buildDate":"2024-01-24T16:02:36Z","goVersion":""}) in K8S in SSD mode
2. Ingested an old log snippet
3. Query it right away from Grafana

**Expected behavior**
I hope to query the log ingested right away, even though it is elder.

**Environment:**
 - Infrastructure: K8S
 - Deployment tool: yaml file

**Screenshots, Promtail config, or terminal output**
Loki config as below:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  namespace: logging
  labels:
    app.kubernetes.io/name: loki
data:
  config.yml: |-
    auth_enabled: true

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: debug

      http_tls_config:
        cert_file: /etc/loki/certs/tls.crt
        key_file: /etc/loki/certs/tls.key
        client_auth_type: RequireAndVerifyClientCert
        client_ca_file: /etc/loki/certs/ca.crt

      grpc_tls_config:
        cert_file: /etc/loki/certs/tls.crt
        key_file: /etc/loki/certs/tls.key
        client_auth_type: RequireAndVerifyClientCert
        client_ca_file: /etc/loki/certs/ca.crt

    common:
      path_prefix: /var/loki
      replication_factor: 3
      ring:
        kvstore:
          store: memberlist
      compactor_address: "loki-backend.logging.svc.cluster.local"

      storage:
        s3:
          endpoint: 192.168.126.128:9000
          bucketnames: chunks
          access_key_id: <key_id>
          secret_access_key: <access_key>
          s3forcepathstyle: true
          insecure: true

    ingester_client:
      grpc_client_config:
        tls_enabled: true
        tls_cert_path: /etc/loki/certs/tls.crt
        tls_key_path: /etc/loki/certs/tls.key
        tls_ca_path: /etc/loki/certs/ca.crt
        tls_server_name: loki-server.com
        tls_insecure_skip_verify: false

    memberlist:
      join_members:
        - "loki-memberlist.logging.svc.cluster.local"
      tls_enabled: true
      tls_cert_path: /etc/loki/certs/tls.crt
      tls_key_path: /etc/loki/certs/tls.key
      tls_ca_path: /etc/loki/certs/ca.crt
      tls_server_name: loki-server.com
      tls_insecure_skip_verify: false

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 24h
      max_query_parallelism: 100

    query_scheduler:
      max_outstanding_requests_per_tenant: 4096
      grpc_client_config:
        tls_enabled: true
        tls_cert_path: /etc/loki/certs/tls.crt
        tls_key_path: /etc/loki/certs/tls.key
        tls_ca_path: /etc/loki/certs/ca.crt
        tls_server_name: loki-server.com

    index_gateway:
      mode: ring

    frontend:
      scheduler_address: query-scheduler-discovery.logging.svc.cluster.local:9095
      max_outstanding_per_tenant: 4096
      grpc_client_config:
        tls_enabled: true
        tls_cert_path: /etc/loki/certs/tls.crt
        tls_key_path: /etc/loki/certs/tls.key
        tls_ca_path: /etc/loki/certs/ca.crt
        tls_server_name: loki-server.com

    frontend_worker:
      scheduler_address: query-scheduler-discovery.logging.svc.cluster.local:9095
      grpc_client_config:
        tls_enabled: true
        tls_cert_path: /etc/loki/certs/tls.crt
        tls_key_path: /etc/loki/certs/tls.key
        tls_ca_path: /etc/loki/certs/ca.crt
        tls_server_name: loki-server.com

    schema_config:
      configs:
        - from: "2023-12-13"
          store: tsdb
          object_store: s3
          schema: v12
          index:
            period: 24h
            prefix: loki_index_

    storage_config:
      tsdb_shipper:
        active_index_directory: /var/loki/tsdb-index
        cache_location: /var/loki/tsdb-cache
        shared_store: s3
        index_gateway_client:
          grpc_client_config:
            tls_enabled: true
            tls_cert_path: /etc/loki/certs/tls.crt
            tls_key_path: /etc/loki/certs/tls.key
            tls_ca_path: /etc/loki/certs/ca.crt
            tls_server_name: loki-server.com
```
