### ISSUE TITLE
[Loki] Helm Chart cannot parse environment variables with "- config.extra-env=true"

### ISSUE THREAD

**Issue by Angel0r** [grafana/loki#12218]
**Describe the bug**
Loki Helm Chart cannot parse environment variables. I am using FluxV2 and when I pass `- config.extra-env=true` in `extraArgs` in the HelmRelease, the following error is produced:
```yaml
loki failed parsing config: /etc/loki/config/config.yaml: yaml: control characters are not allowed
```

**To Reproduce**
Loki Chart version: 5.43.5
1. Use environment variables for s3 storage. So in `backend` I am enabling `- config.extra-env=true` in `extraArgs` and then env in `extraEnv`. Save the changes in values file:
`values.yaml`
```yaml
global:
  image:
    # -- Overrides the Docker registry globally for all images
    registry: null
loki:
  # Configures the readiness probe for all of the Loki pods
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 30
    timeoutSeconds: 1
  image:
    # -- The Docker registry
    registry: docker.io
    # -- Docker image repository
    repository: grafana/loki
  # -- Provides a reloadable runtime configuration file for some specific configuration
  # -- Storage config. Providing this will automatically populate all necessary storage configs in the templated config.
  storage:
    bucketNames:
      chunks:  test-loki
      ruler:  test-loki
      admin: test-loki
    type: s3
    s3:
      s3: "s3://test-loki"
      endpoint: "test.se-grid.com/"
      region: eu-north-1
      secretAccessKey: "${SECRET_KEY}"
      accessKeyId: ${ACCESS_KEY}
      signatureVersion: null
      s3ForcePathStyle: true
      insecure: false
      http_config: {}

# Configuration for the backend pod(s)
backend:
  # -- Number of replicas for the backend
  replicas: 3
  autoscaling:
    # -- Enable autoscaling for the backend.
    enabled: false
  # -- Comma-separated list of Loki modules to load for the read
  targetModule: "backend"
  # -- Additional CLI args for the backend
  #! Enable expand-env so we can add environment variable for storagegrid secrets
  extraArgs:
    - "-config.expand-env=true"
  extraEnv:
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: loki-test-credentials
          key: secretAccessKey
    - name: ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-test-credentials
          key: accessKeyId
  # -- Volume mounts to add to the backend pods
  extraVolumeMounts: []
  # -- Volumes to add to the backend pods
  extraVolumes: []
  # -- Resource requests and limits for the backend
  resources: {}
``` 

**Expected behavior**
It should pass the environment variables correctly so in the `accessKeyId` and the `secretAccessKey` in the S3 storage.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Fluxv2

**Logs from Kubernetes**
<img width="1189" alt="Screenshot 2024-03-14 at 17 06 35" src="https://github.com/grafana/loki/assets/23244740/669d98d4-9579-41ba-baa9-c96a19572298">

**Comment by atillaqb** [comment]
I also have the same problem!

**Comment by Angel0r** [comment]
I managed to solve the problem and it seems that the list format of the `extraEnvFrom` doesn't work in this case since I had to refer the secret as well. So the correct way to use it, is the following:
```yaml
      # -- Additional CLI args for the backend
      extraArgs:
        - -config.expand-env=true
      # -- Environment variables to add to the backend pods
      extraEnv: []
      # -- Environment variables from secrets or configmaps to add to the backend pods
      extraEnvFrom: 
        - secretRef:
            name: loki-test-credentials
```
For the grafana/loki(Simple Scalable) Helm Chart you also need to add these `extraArgs` and `extraEnvFrom` in all Loki's instances( read, write, backend, lokiCanary, and gateway) since all of them have access to the corresponding storage.
