### ISSUE TITLE
Promtail prevents deletion of volumes

### ISSUE THREAD

**Issue by jonathanschwrz** [grafana/loki#1224]
**Describe the bug**
We have extended our Promtail configuration to scrape trace files (*.trc) and enabled bidirectional mountPropergation to support scraping of host mounted EBS volumes. Promtail is tailing them successfully. However, if we delete the pod and volume with the trace files, the pod will remain in endless termination and the volumes remain in place. With `lsof` in the promtail container we see that it keeps the trace files open so the volume (pv and pvc) can't be deleted.

**To Reproduce**
1. Deploy Loki and Promtail helm chart (0.4.0)
2. Create pod, pvc and pc with trace files
4. Add scrape config
5. Delete volume

**Scrape config**
``` 
  - job_name: traces
      pipeline_stages:
      - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - source_labels:
        - __meta_kubernetes_pod_label_XInstallation
        target_label: __X_system_id__
      - action: keep
        regex: .+
        source_labels:
        - __X_system_id__
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __X_system_id__
        target_label: service
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container_name
      - action: replace
        replacement: $1/volumes/*/*/trace
        separator: _
        source_labels:
        - __meta_kubernetes_pod_uid
        target_label: __tmp_log_folder
      - action: replace
        replacement: /pods/$1*/service/*.trc
        separator: /
        source_labels:
        - __tmp_log_folder
        - __meta_kubernetes_pod_label_X
        target_label: __path__
```

**Expected behavior**
We would expect that Promtail stopps tailing the files if it discovers that the volume is in termination. 

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

How can we ensure that promtail does not prevent volumes from being deleted in Kubernetes?
