### ISSUE TITLE
Provide the option to extract all keys from a json input

### ISSUE THREAD

**Issue by rrajkomar** [grafana/loki#1225]
**Is your feature request related to a problem? Please describe.**
When parts of a log line are generated by application code that is from a library or a framework, internal json keys may not be known in advance.
However being able to search with those keys as labels them might prove useful

**Describe the solution you'd like**
It would be great if the json pipeline_stages has an option to auto-extract all keys from the json input (i.e. if no expressions keys are provided)

It would then require the labels stage to also accept using all keys extracted from a given source to be then used as labels

Something like this :
```
      - regex:
          expression: '^\[(?P<time>[^\]]+)\] (?P<channel>[a-z]+)\.(?P<level>[A-Z]+): (?P<message>.+) (?P<context>.+) (?P<extra>.+)$'
      - json:
          expressions:
          source: context
          output: context_keys
      - json:
          expressions:
          source: extra
          output: extra_keys
      - labels:
          channel:
          level:
          message:
          context:
          extra_sources:
                  - context_keys
                  - extra_keys
```
