### ISSUE TITLE
Imposible to enable s3forcepathstyle

### ISSUE THREAD

**Issue by i5Js** [grafana/loki#12371]
**Describe the bug**
Impossible to enable s3forcepathstyle, I see it's hardcode in the values file. 

**To Reproduce**
1. Create the values file with s3forcepathstyle true:
```
  # S3 backend storage configuration
  storage:
    bucketNames:
      chunks: <bucket-name>
      ruler: <bucket-name>
    type: s3
    s3:
      s3: "s3://<bucket-name>"
      endpoint: <endpoint>
      region: eu-west-1
      secretAccessKey: ${MINIO_SECRET_ACCESS_KEY}
      accessKeyId: ${MINIO_ACCESS_KEY_ID}
      S3ForcePathStyle: true
      insecure: false
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 0s
        insecure_skip_verify: false
```

**Expected behavior**
s3forcepathstyle should be enabled in the configmap

**Environment:**
 - Infrastructure: kubernetes environment v1.27.4
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
cm output
```
ruler:
  storage:
    s3:
      access_key_id: ${MINIO_ACCESS_KEY_ID}
      bucketnames: k8s-loki
      endpoint: <endpint>
      http_config:
        idle_conn_timeout: 90s
        insecure_skip_verify: false
        response_header_timeout: 0s
      insecure: false
      region: eu-west-1
      s3: s3://k8s-loki
      **s3forcepathstyle: false**
      secret_access_key: ${MINIO_SECRET_ACCESS_KEY}
    type: s3
```
