### ISSUE TITLE
Promtail: Simple way to construct json from simple log line 

### ISSUE THREAD

**Issue by KVInventoR** [grafana/loki#12408]
Hi all,

Is there any simple way to construct and send  json which can be created from regexp without using templates?

I tried to use this example, but no luck

```
- regex:
    expression: '^(?P<timestamp>\w+ \d+ \d+:\d+:\d+) (?P<loglevel>\w+) (?P<message>.*)'
- json:
    expressions:
      timestamp: timestamp
      loglevel: loglevel
      message: message
- labels:
    loglevel: ""
```

I would like to have log as json object in loki  with some labels
