### ISSUE TITLE
logstream docker is missing on annotation

### ISSUE THREAD

**Issue by troke12** [grafana/loki#12445]
Hi, i want to ask that `__meta_docker_container_log_stream` is really not valuable 

The output is :
![image](https://github.com/grafana/loki/assets/10250068/1e788051-5f54-426f-97a5-572afa9d9e63)

Promtail config : 
```yml
scrape_configs:
  - job_name: flog_scrape

    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'

      - source_labels: ['__meta_docker_container_id']
        regex: '(.*)'
        target_label: 'container_id'

      - source_labels: ['__meta_docker_container_log_stream']
        regex: '(.*)'
        target_label: 'logstream'
```

so i use that logstream in

![image](https://github.com/grafana/loki/assets/10250068/b1e82f52-b1ab-44bf-8db5-301c8e863d5a)

how i can fix that?
