### ISSUE TITLE
error="server returned HTTP status 400 Bad Request (400): snappy: corrupt input"

### ISSUE THREAD

**Issue by shootkin** [grafana/loki#1245]
**Describe the bug**
I have a simple aiohttp application with a simple access log. When I try to scrap this log with promtail, I see this error in promtail logs: 
```
level=error ts=2019-11-12T09:15:51.153976316Z caller=client.go:206 component=client host=loki:3100 msg="final error sending batch" status=400 error="server returned HTTP status 400 Bad Request (400): snappy: corrupt input"
```

And corresponding logs in loki server:
```
... caller=logging.go:44 traceID=72677bd02c0f41c6 msg="POST //api/prom/push (301) 22.967µs"
... caller=logging.go:44 traceID=34ad07e894249fd9 msg="GET /api/prom/push (400) 56.83µs
```

**To Reproduce**
1. Started Loki v0.4.0
2. Started Promtail v0.4.0 to tail access log from aiohttp application
3. Query: `No query`

**Expected behavior**
Logs from my application are transported to loki server with 200 HTTP status.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: simple binary file

**Screenshots, Promtail config, or terminal output**
Sample of aiohttp access log:
```
2019-11-12 09:15:47,241	aiohttp.access	INFO	10.255.0.2 [12/Nov/2019:09:15:47 +0000] 0.000378 "GET /api/cache/tasks?page=1 HTTP/1.1" 404 173 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
```
Promtail config:
```
scrape_configs:
- job_name: sample-server
  static_configs:
  - targets:
      - localhost
    labels:
      log_kind: access-log
      instance: my_instance
      __path__: /var/logs/app/access.log
```
