### ISSUE TITLE
Loki Helm Chart SecurityContext is not being defined properly.

### ISSUE THREAD

**Issue by fsvalim** [grafana/loki#12539]
The containerSecurityContext from Helm Chart Loki is not being defined according to the default values.yaml into the StatefulSet resource.

 1. Execute the helm install dry-run and check the output.

Expected behavior: allowPrivilegeEscalation: false in the containerSecurityContext, should be defined because is set as default. value

 - Infrastructure: Kubernetes
 - Deployment tool: helm

Part of the dry-run output:

```
  spec:
      serviceAccountName: cawe-monitoring-loki
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      initContainers:
        []
      containers:
        - name: loki
          image: "grafana/loki:2.4.2"
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/loki/loki.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: "/data"
              subPath: 
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          resources:
            {}
          securityContext:
            readOnlyRootFilesystem: true
          env:
      nodeSelector:
      ```
