### ISSUE TITLE
Error while upgrade to loki 3.0.0

### ISSUE THREAD

**Issue by xpader** [grafana/loki#12588]
**Describe the bug**
After upgrade Loki to 3.0.0, Loki can not start, and get error below:
`level=error ts=2024-04-12T02:53:31.018745494Z caller=main.go:66 msg="validating config" err="CONFIG ERROR: invalid compactor config: compactor.delete-request-store should be configured when retention is enabled"`

**To Reproduce**
This is the config part:
```
limits_config:
  allow_structured_metadata: true
  ingestion_rate_mb: 32
  ingestion_burst_size_mb: 64
  max_global_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 24h
#  max_query_lookback: 720h
  retention_period: 720h
  max_query_series: 2000

query_scheduler:
  max_outstanding_requests_per_tenant: 10000

compactor:
  working_directory: /loki/retention
#  shared_store: filesystem
  retention_enabled: true
```

Just upgrade loki to 3.0.0, after restart loki instance.

**Expected behavior**
Loki started normally.

**Environment:**
 - Infrastructure: Docker
 - Deployment tool: docker-compose-plugin
