### ISSUE TITLE
insane quantity of files in chunks directory ?

### ISSUE THREAD

**Issue by zerthimon** [grafana/loki#1258]
I've noticed loki creates a lot of files in it's `chunks` directory:
```
/storage/loki/chunks# ls -alF | wc -l
49240
```
Is this normal ?

config:
```
---
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

storage_config:
  boltdb:
    directory: /storage/loki/index
  filesystem:
    directory: /storage/loki/chunks

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb
    object_store: filesystem
    schema: v9
    index:
      prefix: index_
      period: 168h

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 336h

table_manager:
  retention_deletes_enabled: true
  retention_period: 4368h
```
