### ISSUE TITLE
S3 storage configuration of LokiStack through the secret does not work properly

### ISSUE THREAD

**Issue by kai-uwe-rommel** [grafana/loki#12608]
**Describe the bug**
I am trying to deploy a LokiStack using the Operator on Openshift and a local Minio instance in the same namespace. The deployment itself is working correctly (as far as I can see). But afterwards, the compactor pod crashloops complaining it does not find the endpoint in the secret. But it is there.

**To Reproduce**
1. Install the Red Hat Loki operator on Openshift
2. Create a Minio deployment in the target namespace where the LokiStack instance will be created
3. Provide the secret with the configuration data for the Minio S3 store according to this: https://loki-operator.dev/docs/object_storage.md/
4. Create the LokiStack instance with the operator
5. When the compactor-0 pod starts, it fails with this error message:
`failed to init delete store: failed to get s3 object: MissingEndpoint: 'Endpoint' configuration is required for this service
`
**Expected behavior**
The configured secret DOES contain the endpoint. So the compactor should not fail.

**Environment:**
 - Openshift 4.15 cluster
 - Red Hat LokiStack 5.9 operator
 - simple Minio deployment

**Screenshots, Promtail config, or terminal output**
This is what the secret looks like in a test environment:
```
apiVersion: v1
kind: Secret
metadata:
  name: minio-s3
  namespace: openshift-logging
type: Opaque
data:
  # minio
  access_key_id: bWluaW8=
  # PassW0rd
  access_key_secret: UGFzc1cwcmQ=
  # logging
  bucketnames: bG9nZ2luZw==
  # http://minio:9000
  endpoint: aHR0cDovL21pbmlvOjkwMDA=
```

And this is the lokistack instance object:
```
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: lokistack-logging
  namespace: openshift-logging
spec:
  managementState: Managed
  size: 1x.extra-small
  hashRing:
    type: memberlist
  limits:
    global:
      queries:
        queryTimeout: 3m
      retention:
        days: 7
  rules:
    enabled: true
  storage:
    schemas:
    - effectiveDate: "2020-10-11"
      version: v12
    secret:
      name: minio-s3
      type: s3
  storageClassName: thin
  tenants:
    mode: openshift-logging
```
