### ISSUE TITLE
Docs feedback: https://grafana.com/docs/loki/latest/setup/size/ is COMPLETELY broken

### ISSUE THREAD

**Issue by simonfelding** [grafana/loki#12618]
Hi Grafana
The values output here are completely broken and cause the deployment to fail with very bad error messages. Please take the link down or fix the output.

It produces the following output (as an example):
```
loki:
  authenabled: false
read:
  replicas: 9
  resources:
    requests:
      cpu: 3
      memory: 6
    limits:
      cpu: 3
      memory: 8
write:
  replicas: 4
  resources:
    requests:
      cpu: 1
      memory: 6
    limits:
      cpu: 2
      memory: 12

```

Problems:
1. It returns a file that does not end with yaml.
2. The output is not complete: You need to add more to get it working.
3. EXTREMELY BAD: The resources do not have units. This causes Kubernetes to break, as it assumes the units are very small.

It results in errors like
```Warning  FailedMount  18m                 kubelet            MountVolume.SetUp failed for volume "kube-api-access-fl7vf" : write /var/lib/kubelet/pods/ed8cd4f9-ad9f-448a-a2e9-7891dfff649a/volumes/kubernetes.io~projected/kube-api-access-fl7vf/..2024_04_15_13_43_31.1659629596/ca.crt: no space left on device```

Because Kubernetes uses the memory limits for the projected volume too.
