### ISSUE TITLE
Not able to see all namespaces in Grafna Loki after a while

### ISSUE THREAD

**Issue by mukul2039** [grafana/loki#12611]
**Describe the bug**

Installed Loki Helm chart version 5.44.1 using values file mentioned as below. Also, installing Promtail to send logs to loki from all the nodes. For few minutes Grafana displays all the logs and is able to query logs for all namespaces. After a while only few namespaces remain. Tried different combinations to install but nothing seems to work so far. 

Loki Helm chart version **5.44.1**
Promtail Helm Chart version **6.15.5**
Kubernetes Version 1.28 on OCI(Oracle Cloud Infrastructure)
```
loki:
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  limits_config:
    ingestion_rate_mb: 2048
    ingestion_burst_size_mb: 2048
  auth_enabled: false
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    type: s3
    s3:
      bucketnames: loki-bucket
      endpoint: endpoint
      region: eu-frankfurt-1
      secretAccessKey: secretaccesskey
      accessKeyId: accesskey
      s3ForcePathStyle: true
      insecure: true
      http_config:
        insecure_skip_verify: true
  storage_config:
      boltdb_shipper:
        shared_store: s3
        cache_ttl: 24h
lokiCanary:
  enabled: false
write:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  persistence:
    volumeClaimsEnabled: true
    size: 20Gi
read:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  persistence:
    enableStatefulSetAutoDeletePVC: true
    size: 20Gi
backend:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  persistence:
    size: 30Gi
ingress:
  enabled: false
monitoring:
  selfMonitoring:
     grafanaAgent:
       tolerations:
         - operator: Exists
```

**To Reproduce**
1. Started Loki with the helm chart version mentioned above
2. Started Promtail with version as mentioned above
3. Query: `{namespace="api-services"} |= `` | logfmt | __error__=`` | line_format `{{.message}}``

**Expected behavior**
Expected to see all the namespaces and logs while querying loki from Grafana.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**
