### ISSUE TITLE
A Problem on the Saving Time of Loki Chunks with S3 Minio as the Storage Backend

### ISSUE THREAD

**Issue by fanchibaoLiu** [grafana/loki#12629]
My question is, if I want to set the log to only be saved for 180 days, what should I do?
This is my current configuration for Loki：
```
    schema_config:
      configs:
      - chunks:
          period: 24h
          prefix: loki_chunks_
        from: "2020-09-07"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        row_shards: 16
        schema: v13
        store: tsdb

    storage_config:
      aws:
        bucketnames: chunks,chunks2
        s3: http://Sxxxx7:3lQxxxxxtb@10.0.0.57:9000
        s3forcepathstyle: true
      index_queries_cache_config:
        memcached_client:
          addresses: dnssrv+_memcached-client._tcp.loki-distributed-memcached-index-queries.loki.svc.cluster.local
          consistent_hash: true
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index_cache
        cache_ttl: 24h

    table_manager:
      retention_deletes_enabled: true
      retention_period: 4032h
```

> table_manager.retention_deletes_enabled=true and table_manager.retention_period=4032h
Can these two parameters ensure that they are only saved for 4032 hours,Data exceeding 4032 hours will be deleted, including chunks and indexes in the minio bucket?

Do we still need to configure the lifecycle strategy of the minio bucket?

Do you have any senior who can help answer this question? Thank you very much!
