### ISSUE TITLE
docker image does not recognise timezone appropriately

### ISSUE THREAD

**Issue by instantdreams** [grafana/loki#12634]
**Describe the bug**
Date on host reports according to timezone. Date on container reports in UTC.

**To Reproduce**
1. Run loki in container, passing "TZ" environment variable and "localtime" and "timezone" volumes
2. Executed the following commands:

```
$ docker exec loki date
Tue Apr 16 14:25:52 UTC 2024
$ docker exec loki cat /etc/timezone
America/Edmonton
```

**Expected behavior**
Result should be MDT rather than UTC

**Environment:**
 - uname Linux 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
 - Docker version 25.0.4, build 1a576c5
 - Docker Compose version v2.24.7
 - loki, version 2.9.7 (branch: HEAD, revision: efc4d2f009)

**Screenshots, Promtail config, or terminal output**
compose.yaml

``` yaml
services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    hostname: loki
    user: 1000:1000
    command: --config.file=/etc/loki/config.yaml --config.expand-env=true
    ports:
      - 3100:3100 # web ui
    environment:
      - TZ=America/Edmonton
    volumes:
      - /srv/loki/etc-loki:/etc/loki
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
```

Whilst this is a small issue, my concern is that my five promtail instances are sending data using MDT timestamps.
