### ISSUE TITLE
Loki forcibly adding `loki.` to s3.endpoint

### ISSUE THREAD

**Issue by larivierec** [grafana/loki#12633]
**Describe the bug**
Using the 6.2.0 helm chart, after it is deployed and loki-write starts emitting data it is sending the data to `loki.<s3.endpoint>`

**To Reproduce**
1. Start Loki -> docker.io/grafana/loki:3.0.0
2. See [Values](https://github.com/larivierec/home-cluster/blob/main/kubernetes/apps/monitoring/loki/app/helm-release.yaml)

my s3.endpoint resolves to `s3.garb.dev` in case you don't want to search the entire file.

**Expected behavior**
It should be sending it to <s3.endpoint> not `loki.<s3.endpoint>`

**Environment:**
 - Kubernetes
 - Helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

```
level=error ts=2024-04-16T13:53:23.797962343Z caller=flush.go:152 component=ingester org_id=fake msg="failed to flush" err="failed to flush chunks: store put chunk: RequestError: send request failed\ncaused by: Put \"http://loki.s3.garb.dev/fake/3e235da5417e60b9/18ed2141a9d%3A18ed21506ba%3A17a4e06e\": dial tcp: lookup loki.s3.garb.dev on 10.43.0.10:53: no such host, num_chunks: 47, labels: {app=\"vector-agent\", namespace=\"monitoring\", node=\"k3s-wg-1\", service_name=\"vector-agent\"}"
```

Note: I have explicitly set minio.enabled: false even thought that's the default value to be sure.
I have glanced at [this](https://github.com/grafana/loki/blob/main/production/helm/loki/templates/_helpers.tpl#L207-L223) and don't see any issues, so i'm a little confused at why this is happening.

This is either a bug or a code 18, in both cases, i'd like for it to work :)

**Comment by xpader** [comment]
This is my storage config, there is not `loki` in endpoint url, you can take a refer to this:

```
storage_config:
  named_stores:
    aws:
      minio:
        s3: http://accessKey:accessSecret@172.19.210.8:9000/loki
        s3forcepathstyle: true
      seaweedfs:
        s3: http://accessKey:accessSecret@172.19.210.8:8333/loki
        s3forcepathstyle: true
```
