### ISSUE TITLE
Memcached seems not working in Loki 2.9.7

### ISSUE THREAD

**Issue by duj4** [grafana/loki#12714]
**Describe the bug**
I tried to add memcached for chunks and results in my loki cluster, but from memcached_exporter it seems they were not working at all.
I think there should be something mis-configured, but I cannot tell where, no obvious log found.

**To Reproduce**
Config as below:
```
    chunk_store_config:
      chunk_cache_config:
        memcached:
          batch_size: 256
          parallelism: 10
        memcached_client:
          host: 'loki-memcached-chunks.<namespace>.svc.cluster.local'
          service: 'loki-memcached-chunks'
          addresses: 'loki-memcached-chunks.<namespace>.svc.cluster.local:11211'

    query_range:
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          default_validity: 12h
          memcached_client:
            host: 'loki-memcached-results.<namespace>.svc.cluster.local'
            service: 'loki-memcached-results'
            addresses: 'loki-memcached-results.<namespace>.svc.cluster.local:11211'
            timeout: 500ms
```

**Expected behavior**
Memcached should be working.

**Environment:**
 - Infrastructure: K8S
 - Deployment tool: helm
 - Version: 2.9.7

**Screenshots, Promtail config, or terminal output**
![image](https://github.com/grafana/loki/assets/19278537/f1356b09-a704-454f-bdc5-efa644e6db6d)

When I ran the query, here is from loki-read.log:

> 2024-04-21T18:33:58.183333503+08:00 stderr F level=warn ts=2024-04-21T10:33:58.091176695Z caller=experimental.go:20 msg="experimental feature in use" feature="DNS-based memcached service discovery"
> 2024-04-21T18:33:58.183340434+08:00 stderr F level=debug ts=2024-04-21T10:33:58.103712548Z caller=memcached_client_selector.go:105 msg="updating memcached servers" servers=10.96.219.81:11211 count=1
> 2024-04-21T18:33:58.183344901+08:00 stderr F level=warn ts=2024-04-21T10:33:58.104945074Z caller=experimental.go:20 msg="experimental feature in use" feature="DNS-based memcached service discovery"
> 2024-04-21T18:33:58.18335424+08:00 stderr F level=debug ts=2024-04-21T10:33:58.1114272Z caller=memcached_client_selector.go:105 msg="updating memcached servers" servers=10.96.22.143:11211 count=1
> 2024-04-21T18:34:58.182136789+08:00 stderr F level=debug ts=2024-04-21T10:34:58.107151558Z caller=memcached_client_selector.go:105 msg="updating memcached servers" servers=10.96.219.81:11211 count=1
> 2024-04-21T18:34:58.182174134+08:00 stderr F level=debug ts=2024-04-21T10:34:58.120451469Z caller=memcached_client_selector.go:105 msg="updating memcached servers" servers=10.96.22.143:11211 count=1
> 2024-04-21T18:35:58.181804079+08:00 stderr F level=debug ts=2024-04-21T10:35:58.106780861Z caller=memcached_client_selector.go:105 msg="updating memcached servers" servers=10.96.219.81:11211 count=1
> 2024-04-21T18:35:58.181826795+08:00 stderr F level=debug ts=2024-04-21T10:35:58.119872665Z caller=memcached_client_selector.go:105 msg="updating memcached servers" servers=10.96.22.143:11211 count=1
> 2024-04-21T18:36:58.182384859+08:00 stderr F level=debug ts=2024-04-21T10:36:58.111790906Z caller=memcached_client_selector.go:105 msg="updating memcached servers" servers=10.96.219.81:11211 count=1
> 2024-04-21T18:36:58.182417735+08:00 stderr F level=debug ts=2024-04-21T10:36:58.119808487Z caller=memcached_client_selector.go:105 msg="updating memcached servers" servers=10.96.22.143:11211 count=1

**Comment by duj4** [comment]
@JStickler Thanks for the reply. Yes, I ran memcached in the same chart as Loki and use the "address" config, but I am not sure whether the config is correct:
    ```
chunk_store_config:
      chunk_cache_config:
        memcached:
          batch_size: 256
          parallelism: 10
        memcached_client:
          host: 'loki-memcached-chunks.<namespace>.svc.cluster.local'
          service: 'loki-memcached-chunks'
          addresses: 'loki-memcached-chunks.<namespace>.svc.cluster.local:11211'

    query_range:
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          default_validity: 12h
          memcached_client:
            host: 'loki-memcached-results.<namespace>.svc.cluster.local'
            service: 'loki-memcached-results'
            addresses: 'loki-memcached-results.<namespace>.svc.cluster.local:11211'
            timeout: 500ms

```

**Comment by AndreZiviani** [comment]
There were a few bugs around cache writeback, check these PR:
https://github.com/grafana/loki/pull/12456
https://github.com/grafana/loki/pull/11776

The last one is the most relevant but TLDR there was a bug on how the queue size was calculated so after some time loki simply stops using memcached, affecting both performance and deduplication of chunks
You can check the metric `loki_cache_background_queue_bytes`, it will probably be constant on 500MB (default value)

**Comment by duj4** [comment]
@AndreZiviani , thank for the reply.
It seems the issue had been fixed in 2.9.5 https://github.com/grafana/loki/issues/11821?

**Comment by AndreZiviani** [comment]
It was only mentioned on the 3.0 changelog but looks like you are right

**Comment by duj4** [comment]
@AndreZiviani I did not find the parameter in either the config or [doc](https://grafana.com/docs/loki/v2.9.x/configure/), if you meant the parameters under `cache_config` -> `background`, then all of them are set as default values.

I am not sure whether my config of `memcached_client` is correct or not, could you please help confirm that?

**Comment by AndreZiviani** [comment]
@duj4 I believe your issue may be on the `addresses` filed, it should use the [dns-service-discovery](https://grafana.com/docs/mimir/latest/configure/about-dns-service-discovery/#supported-discovery-modes) format

this is my config:
```
    chunk_store_config:
      cache_lookups_older_than: 3h
      chunk_cache_config:
        default_validity: 0s
        embedded_cache:
          enabled: false
        memcached:
          batch_size: 6
          parallelism: 5
        memcached_client:
          addresses: dnssrv+_memcached-client._tcp.loki-memcached-chunks.loki.svc.cluster.local
          consistent_hash: true
          timeout: 10s

    query_range:
      align_queries_with_step: true
      cache_index_stats_results: false
      cache_results: true
      max_retries: 5
      results_cache:
        cache:
          default_validity: 0s
          memcached:
            batch_size: 6
            parallelism: 5
          memcached_client:
            addresses: dnssrv+_memcached-client._tcp.loki-memcached-frontend.loki.svc.cluster.local
            consistent_hash: true
            timeout: 10s
```
