### ISSUE TITLE
Helm: loki-canary test pod gets rendered even when tests are disabled

### ISSUE THREAD

**Issue by elchenberg** [grafana/loki#12765]
**Describe the bug**

I could not find out how to *not* deploy the loki-canary test pod using the Helm chart v6.4.3 when the loki-canary is enabled but the tests are disabled (`test.enabled=false`).

I think the issue was introduced with this change: <https://github.com/grafana/loki/commit/79b876b65d55c54f4d532e98dc24743dea8bedec#diff-4f7364c8431077f51149aa596196fa56a856485769d10f6aa581c5728653015d>

```diff
{{- with .Values.test }}
-{{- if and .enabled $.Values.monitoring.selfMonitoring.enabled $.Values.monitoring.lokiCanary.enabled }}
+{{- if $.Values.lokiCanary.enabled }}
```

I guess the change should have looked like this instead:

```diff
{{- with .Values.test }}
-{{- if and .enabled $.Values.monitoring.selfMonitoring.enabled $.Values.monitoring.lokiCanary.enabled }}
+{{- if and .enabled $.Values.lokiCanary.enabled }}
```

**To Reproduce**

**Expected behavior**

Test pods should not be created when tests are disabled.

**Environment:**

 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**

**Comment by elchenberg** [comment]
Correction: It is not getting deployed unless I run `helm test`. But it is getting rendered with `helm template` which is different to v5.47.2 of the Helm chart.

My values.yaml:

```yaml
deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  useTestSchema: true
singleBinary:
  replicas: 1
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0
test:
  enabled: false
```

**Comment by pablofrommars** [comment]
It looks like they get deployed in my case despite disabling them:

```yaml
mode: SingleBinary

backend:
  replicas: 0
  extraEnvFrom:
  - secretRef:
      name: loki-secrets

singleBinary:
  replicas: 1
read:
  replicas: 0
write:
  replicas: 0

monitoring:
  selfMonitoring:
    enabled: false
  lokiCanary:
    enabled: false

test:
  enabled: false

loki:
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: azure
    azure:
      account_name: stellafutura
      account_key: ${AZURE_STORAGE_ACCESS_KEY}
      endpoint_suffix: blob.core.windows.net
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: azure
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
```
