### ISSUE TITLE
Adding custom resource in loki helm value for memcached 

### ISSUE THREAD

**Issue by cloudcafetech** [grafana/loki#12809]
Please add custom resource in loki helm value for memcached ... taking default value for memory 9830Mi

``` 
 memcached:
    resources:
      limits:
        #memory: 9830Mi
        memory: 1000Mi
      requests:
        cpu: 500m
        #memory: 9830Mi
        memory: 1000Mi
```
