### ISSUE TITLE
Helm Chart Enterprise Gateway Fails to Start in SSD 

### ISSUE THREAD

**Issue by bentonam** [grafana/loki#12882]
**Describe the bug**
The enterprise gateway fails to start when using the chart default values in SSD mode.  

The default value in the chart is: 

```yaml
enterpriseGateway:
  useDefaultProxyURLs: true
```
https://github.com/grafana/loki/blob/main/production/helm/loki/templates/gateway/deployment-gateway-enterprise.yaml#L72 

```yaml
            {{- if .Values.enterpriseGateway.useDefaultProxyURLs }}
            - -gateway.proxy.default.url=http://{{ template "loki.fullname" . }}-admin-api.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.admin-api.url=http://{{ template "loki.fullname" . }}-admin-api.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.distributor.url=dns:///{{ template "loki.fullname" . }}-distributor-headless.{{ .Release.Namespace }}.svc:9095
            - -gateway.proxy.ingester.url=http://{{ template "loki.fullname" . }}-ingester.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.query-frontend.url=http://{{ template "loki.fullname" . }}-query-frontend.{{ .Release.Namespace }}.svc:3100
            - -gateway.proxy.ruler.url=http://{{ template "loki.fullname" . }}-ruler.{{ .Release.Namespace }}.svc:3100
            {{- end }}
```

The proxy urls are hard-coded, and they assume that the chart is being deployed in distributed mode. as the distributor service is only created if distributed mode is being deployed. https://github.com/grafana/loki/blob/main/production/helm/loki/templates/distributor/service-distributor-headless.yaml#L2 

This should be conditionalized around SSD / Distributed.  The only workaround for this is to disable the default proxy urls and set the extra to hard-coded values.

```yaml
enterpriseGateway:
  useDefaultProxyURLs: false
  extraArgs:
    gateway.proxy.default.url: http://enterprise-logs-backend.logs.svc:3100
    gateway.proxy.admin-api.url: http://enterprise-logs-backend.logs.svc:3100
    gateway.proxy.distributor.url: dns:///enterprise-logs-write-headless.logs.svc:9095
    gateway.proxy.ingester.url: http://enterprise-logs-write.logs.svc:3100
    gateway.proxy.query-frontend.url: http://enterprise-logs-read.logs.svc:3100
    gateway.proxy.ruler.url: http://enterprise-logs-backend.logs.svc:3100
```

**Expected behavior**
The enterprise gateway should populate the correct urls depending on the mode SSD/Distributed.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
