### ISSUE TITLE
Support JSON for systemd output fields

### ISSUE THREAD

**Issue by roidelapluie** [grafana/loki#1288]
**Is your feature request related to a problem? Please describe.**

I would like to get more fields out of systemd but not indexing them:

```
{"_AUDIT_SESSION":"39444","_GID":"0","_COMM":"sudo","_EXE":"/usr/bin/sudo","_CAP_EFFECTIVE":"1fffffffff","_PID":"1546","PRIORITY":"6","_UID":"0","MESSAGE":"pam_unix(sudo:session): session closed for user root","_AUDIT_LOGINUID":"550","_BOOT_ID":"729a106eb5ec435f9e2ef354b8bdda8a","SYSLOG_FACILITY":"10","SYSLOG_IDENTIFIER":"sudo","_TRANSPORT":"syslog","_SYSTEMD_CGROUP":"/system.slice/sshd.service",_SYSTEMD_UNIT":"sshd.service","_SOURCE_REALTIME_TIMESTAMP":"1574205809328532","_MACHINE_ID":"a3956a4f6aa34db59bc7f433d18dbb12","_HOSTNAME":"XXX,"_SYSTEMD_SLICE":"system.slice","_CMDLINE":"XXX"}
```

In this exemple, __exe is interresting but maybe we do not want to index it.

**Describe the solution you'd like**

I have no idea :)

**Describe alternatives you've considered**

I use fluentbit for systemd and promtail for log files for now

**Comment by rfratto** [comment]
This is an interesting use case we're not covering at the moment. There's two solutions here: the easiest thing to do would be a flag to pass through the journal message as JSON. This would be a bit slow, since we'd have to marshal each line we read as JSON. 

The other option would be to use labels in the pipeline to get this data sent to Loki without indexing it. From my understanding, there are a few problems preventing this from working today: 

1. Internal labels are dropped before pipelines execute. We'd either need this, or thee ability to drop labels in a pipeline, which we don't support right now either. Maybe we should have both?
2. I don't think there's a way to operate on a label in a pipeline.
3. The only stage that would let you change the message to include fields would be the template stage, but that can only operate on one extracted field at a time.

Off the top of my head, I imagine configuring a pipeline like this:

```yaml
scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
    pipeline_stages:
      - template: 
          source: output 
          template: 'pid={{ .Labels["pid"] }} msg={{ .Output }}'
      - output:
          source: output
      - drop_labels:
          # remove pid label so it's not sent to Loki
          labels: ['pid']
    relabel_configs:
      - source_labels: ['__journal__pid']
        target_label: 'pid'
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
```

/cc @cyriltovena
