### ISSUE TITLE
`replace: '{{ .Value | urldecode }}'` doesn't  decode a value (it doesn't work)

### ISSUE THREAD

**Issue by fadeevab** [grafana/loki#12890]
## Describe the bug
`replace` stage with the `replace: '{{ .Value | urldecode }}'` doesn't decode an matched value (it doesn't work).

`[inspect: replace stage]: none`.

_For the reference, `{{ .Value | upper }}` works as **expected**._

Documentation: [urldecode](https://grafana.com/docs/loki/v2.9.x/query/template_functions/#urldecode)

## To Reproduce
`promtail, version 2.9.8 (branch: release-2.9.x, revision: 94e0029)`

```bash
cat my2.log | promtail --stdin --dry-run --config.file=./promtail2.yml  --inspect
```

![image](https://github.com/grafana/loki/assets/5967447/4b3a2444-9012-4bfb-b198-bf185df292ac)

`my2.log` test log:

```
asdf%40gmail.com
lflfl%40gmail.com
```

`promtail2.yml` config:

```yaml
server:
  http_listen_port: 9088
  grpc_listen_port: 0

clients:
  - url: http://127.0.0.2:3100/loki/api/v1/push

scrape_configs:
  - job_name: some job
    pipeline_stages:
      - replace:
          expression: '(.+)'
          replace: '{{ .Value | urldecode }}'
```

**Expected behavior**
Emails `asdf%40gmail.com` and `lflfl%40gmail.com` should be converted into `asdf@gmail.com` and `lflfl@gmail.com`.

**Environment:**
 - Infrastructure: bare-metal
