### ISSUE TITLE
Loki chart fails to render proper YAML when add more than one extra manifest

### ISSUE THREAD

**Issue by ngclinflows** [grafana/loki#12910]
**Describe the bug**
Loki chart fails to render proper YAML when add more than one extra manifest, since `---` YAML files separator is stuck to last character of preceding YAML files due to template whitespace chomping.

**To Reproduce**
Add at least 2 extra objects in values:
```yaml
extraObjects:
  # Grafana datasource provisioning
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: loki-datasource
      labels:
        grafana_datasource: "1"
    data:
      loki-datasource.yaml: "..."
  # Custom Alerting Rules
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: loki-alerting-rules
    data:
      loki-alerting-rules.yaml: "..."
```
Leads to render something like:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: "..."---      # <--- missing new line before `---` separator
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alerting-rules
data:
  loki-alerting-rules.yaml: "..."
```

**Expected behavior**
Renders valid YAML

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
N/A
