### ISSUE TITLE
Loki crashing on docker

### ISSUE THREAD

**Issue by imclint21** [grafana/loki#12948]
**Describe the bug**
The instance crash after few hours

Configuration:
---

```yaml
auth_enabled: false

server:
  http_listen_port: 3100

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  filesystem:
    directory: /loki/

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  max_query_lookback: 2100h
  retention_period: 2100h

compactor:
  working_directory: /loki/retention
  delete_request_store: filesystem
  retention_enabled: true

ruler:
  alertmanager_url: http://localhost:9093

analytics:
 reporting_enabled: false
```

Logs I get:
---

<img width="1158" alt="image" src="https://github.com/grafana/loki/assets/5221349/6b2fc209-8329-4da1-99d5-5ab3993052fd">
