### ISSUE TITLE
global.image.registry not respected in helm chart for memcache pods

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#12962]
I recently update to the new Helm Chart v6.0 and had a few issues with the memcache portion. These are less major issues and more so quality of life for the chart. For both of these issues the existing chart components already support them, just memcache is the odd one out

1. `global.image.registry` is not respected by the memcache statefulset. 

2. there are no default values for the `podSecurityContext` for memcache. I ended up going with this for my deployment
```
podSecurityContext:
    runAsNonRoot: true
    runAsGroup: 1001
    runAsUser: 1001
```

_Originally posted by @Dalktor in https://github.com/grafana/loki/issues/12506#issuecomment-2101713098_
