### ISSUE TITLE
Change to use latest Nginx in distribute gateway

### ISSUE THREAD

**Issue by wenlinhe** [grafana/loki#12960]
**Is your feature request related to a problem? Please describe.**
No, just because security consideration

**Describe the solution you'd like**
The Loki helm chat still using old Nginx version:  

```
 image:
    # -- The Docker registry for the gateway image
    registry: docker.io
    # -- The gateway image repository
    repository: nginxinc/nginx-unprivileged
    # -- The gateway image tag
    tag: 1.20.2-alpine
```

There are some security issues that in the old version Nginx, the latest Nginx version is v1.25.5, but we're afraid if we directly change this version there may be some conflict. Would Loki team please change and verify compatibility that so we can use latest Nginx version?
