### ISSUE TITLE
Support for inlined pipeline config for docker logger

### ISSUE THREAD

**Issue by wapmorgan** [grafana/loki#1296]
**Is your feature request related to a problem? Please describe.**
When there's need to rebuild plugin or to copy file with pipeline to pluigin directory, it's big problem.
```yaml
options:
    loki-url: ...
    loki-external-labels: container_name={{.Name}}
    loki-pipeline-stage-file: /ag/app.yaml
```

The problem is **/ag/app.yaml is should be inside plugin container**, not in root fs!

**Describe the solution you'd like**
Allow to inline pipeline stage config in config parameter. Like this:
```yaml
options:
    loki-url: ...
    loki-external-labels: container_name={{.Name}}
    loki-pipeline-stages: 
      - json:
        // ...
      - output:
       // ..
```

**Describe alternatives you've considered**
Only injecting (copying) pipeline file to plugin directory.
