### ISSUE TITLE
no rule groups found when using S3 and configMap to load rules

### ISSUE THREAD

**Issue by yelhouti** [grafana/loki#12967]
**Describe the bug**
I'm trying to load rules using configMap while using s3 and ssd . I can see that the sidecar copying rule files into `/rules` (I even tried changing config to have them copied to `/loki/rules`).
Querying the rules always returns: `no rule groups found`

**To Reproduce**
1. Started Loki 3.0.0
2. Started Promtail 2.9.3

values:
```yaml
loki:
  auth_enabled: false 
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      endpoint: minio.minio.svc.cluster.local:9000
      accessKeyId: loki
      s3ForcePathStyle: true
      insecure: true
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h
```
```bash
curl http://loki-backend:3100/api/prom/rules
# or
curl http://loki-gateway/api/prom/rules
```

**Expected behavior**
To see the rules.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by JStickler** [comment]
Questions have a better chance of being answered if you ask them on the [community forums](https://community.grafana.com/c/grafana-loki/41).

**Comment by edwlarkey** [comment]
I'm having a similar problem to this using the helm chart. I am not able to provision recording rules in the `ruler` section.

```
loki:
  storage:
    bucketNames:
      chunks: REPLACEME
      ruler: REPLACEME
      admin: REPLACEME
    type: s3
    s3:
      region: REPLACEME
      s3ForcePathStyle: true
  rulerConfig:
    wal:
      dir: /var/loki/ruler-wal
    rule_path: /etc/loki/rules
    remote_write:
      enabled: true
      clients:
        mimir:
          url: http://mimir-nginx.monitoring.svc.cluster.local/api/v1/push
ruler:
  replicas: 1
  nodeSelector:
    monitoring-worker: "true"
  persistence:
    enabled: true
  directories:
    fake:
      rules.yaml: |
        groups:
        - name: api
          rules:
            - record: api:loglevel:sum_rate
              expr: sum by(level) (rate({container="api"} [10m]))

```

The ruler logs:


```
level=info ts=2024-05-22T16:22:21.599510548Z caller=api.go:509 org_id=fake msg="no rule groups found" userID=fake
level=info ts=2024-05-22T16:22:23.445419254Z caller=api.go:509 org_id=fake msg="no rule groups found" userID=fake
level=info ts=2024-05-22T16:22:33.81113425Z caller=api.go:509 org_id=fake msg="no rule groups found" userID=fake
level=info ts=2024-05-22T16:22:41.711968209Z caller=api.go:509 org_id=fake msg="no rule groups found" userID=fake
level=info ts=2024-05-22T16:22:43.424880297Z caller=api.go:509 org_id=fake msg="no rule groups found" userID=fake
level=info ts=2024-05-22T16:22:53.69105127Z caller=api.go:509 org_id=fake msg="no rule groups found" userID=fake
level=info ts=2024-05-22T16:23:02.140777628Z caller=api.go:509 org_id=fake msg="no rule groups found" userID=fake
level=info ts=2024-05-22T16:23:03.763753726Z caller=api.go:509 org_id=fake msg="no rule groups found" userID=fake
level=info ts=2024-05-22T16:23:13.713900816Z caller=api.go:509 org_id=fake msg="no rule groups found" userID=fake
level=info ts=2024-05-22T16:23:22.022359636Z caller=api.go:509 org_id=fake msg="no rule groups found" userID=fake
```

**Comment by yelhouti** [comment]
You can not use both configMaps and s3. I recommand configMaps for gitops...
to use configMaps instead of s3:

```
  rulerConfig:
    storage:
      type: local
      local:
        directory: /var/loki/rules
    rule_path: /var/loki/rules-temp
    alertmanager_url: http://kube-prometheus-stack-alertmanager.prometheus.svc:9093
    enable_alertmanager_v2: true
    wal:
      dir: /var/loki/ruler-wal
```
If you are deploying on default mode (SSD).

IMO this should be better documented. Thanks for the person who helped me figure it out.

**Comment by edwlarkey** [comment]
I suspected that, but I couldn't figure out how to turn off S3 just for the ruler. Using your config to override the storage config for ruler worked. Thank you!

**Comment by yelhouti** [comment]
Yes I m using configmaps now, which I think is better

**Comment by jimmy-ungerman** [comment]
Do you mind posting your values.yaml as much as you can? I'm imagining you're creating the configmap using `.Values.loki.extraObjects` to create rules configmaps, then the `.Values.sidecar.rules.enabled.true` to copy those configmaps into your rules directory?

Just want to make sure I understand correctly

**Comment by nlamirault** [comment]
I think it is same as https://github.com/grafana/loki/issues/11508

**Comment by MartinEmrich** [comment]
I have the same issue, but I am confused now.

Isn't the ruler storage also where all the time series for Recording Rules and various state is stored? That would most certainly not work with "local" and a mounted config map. I would want that on a fast block device (`local`).

Also I did not expect the Loki helm chart to use S3 for the ruler. I run in Simple-Scalable mode, the ruler runs within the "backend" StatefulSet which has a set of PersistentVolumeClaims (i.e. block storage based filesystem volumes).

As I use S3 for the actual logs, I had to configure `loki.storage` with a ruler bucket name:

````
        s3:
          region: my-region-1
        bucketNames:
          chunks: my-loki-logs
          ruler: my-loki-logs
          admin: my-loki-logs
````

If I would remove the "ruler" entry there, the helmchart would just render `bucketNames: null`, making the backend crash.

How can I have it use S3 for the actual logs, but not for the ruler?
I fear that just overriding the rulerConfig.storage object is not enough?

**Comment by jerem0808** [comment]
Hi all,
This is my current values.yaml which works. If it can help anyone
```
---
global:
deploymentMode: "Distributed"
sidecar:
  rules:
    enableUniqueFilenames: true
    enabled: true
    # -- Folder into which the rules will be placed.
    # This folder points to the persistentVolume mounted on the pod
    folder: /var/loki/rules/


loki:
  analytics:
    reporting_enabled: false
  structuredConfig:
    memberlist:
      bind_addr: []
  limits_config:
    max_entries_limit_per_query: 50000000000
    max_global_streams_per_user: 30000
    per_stream_rate_limit: 5MB
    max_concurrent_tail_requests: 40
    ingestion_rate_mb: 25
    ingestion_burst_size_mb: 20

  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin

    s3:
      endpoint: <ENDPOINT>
      secretAccessKey: <KEY>
      accessKeyId: <KEY>
      s3ForcePathStyle: true
  # More infor https://grafana.com/docs/loki/latest/operations/storage/schema/
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: s3
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
  rulerConfig:
    storage:
      type: local
      local:
        # Directory to scan for rules.
        # This folder correspond to where the rules are first mounted with the ConfigMap
        directory: /etc/loki/rules
    # File path to store temporary rule files.
    rule_path: /var/loki/rules/fake
    alertmanager_url: "<URL>"
    alertmanager_client:
      basic_auth_username: "<USER>"
      basic_auth_password: "<PASSWORD>"
      tls_insecure_skip_verify: true
  # https://grafana.com/docs/loki/latest/operations/multi-tenancy/
  # We want to keep it single-tenant
  auth_enabled: false


ruler:
  enabled: true
  replicas: 1
  directories:
    fake:
      snmp_alarm.yaml: |
        groups:
          - name: ALARM NAME
            rules: [ ... ]
  persistence:
    # -- Enable creating PVCs which is required when using recording rules
    enabled: true
    storageClass: caas-persistent-storage
  extraArgs:
    - --memberlist.bind-addr=$(MY_POD_IP)
    - -log.level=debug
  extraEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
```

**Comment by mwtzzz** [comment]
There's two ways to load and store rules files in SimpleScaleable mode:
a) in S3 bucket via API call
b) in local pod storage via yaml files

## S3: ##
Loki ruler with s3 storage works like this:

1. loki-backend pods periodically scan the S3 bucket. It is looking for binary files that contain the rules data. The names of the files are based on a hash of Loki namespace and other things.
2. The only way to add rules files to S3 is to use the Loki API. A rule created by an API POST call is added to the bucket under `/rules/{tenant_id}/{hash part2}/{hash part 2}`.
3. Rules files (yaml, text files, etc) *manually* added to the bucket are *ignored*
4. The loki-backend pods periodically scan the S3 bucket, find the rules and create a yaml copy of it in in each pod `/var/loki/rules-temp/<org_id>/<namespace>`. This temp folder is the "working area" where the ruler reads the rules.
5. Any files *manually* added to `/var/loki/rules-temp` are ignored and deleted
6. Any files manually added to the `/rules/`, `/var/loki/rules` are ignored.
7. `/loki/rules` is read-only and does not appear to be used.

To successfully add rules to S3, use the API.

## Local pod filesystem ##

1. loki-backend pods mount an `emptyDir` at `/rules`. At first there are no files in it. But, the backend statefulset also has a k8s-sidecar whose job is to search configMaps and secrets for a label (of your choosing). These configMaps and secrets contain the rules. The sidecar will copy these rules to files in the `/rules/{tenant_id}` folder, thus making them available to the ruler. 
2. the backend ruler periodically scans `/rules/{tenant_id}` and loads any rules it finds.

The `sidecar:` helm values get applied to the init container in the loki-backend stateful set.

There is no need to configure `extraVolume` or `extraVolumeMounts`. These get ignored anyway when the helm chart creates the sidecar, so it would be pointless to use them. There is no way to tell the helm chart to replace or rename the default volumeMount `sc-rules-volume`, so it's best to use the default.

All you have to do is create a configMap with contents this like:

    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: loki-rules
      namespace: your k8s namespace
      labels:
        loki_rule: "DevTeam"
    data:
      dev-team-rules.yaml: |
        groups:
        - name: linuxrulegroup
          rules:
            - alert: rc-local-errors
              expr: |
                <logql expression>
    ...

The metadata label from the ConfigMap must match the label you pass to the sidecar in helm.

To successfully add rules to local storage, use a configMap.

**Comment by mwtzzz** [comment]
> [@mwtzzz](https://github.com/mwtzzz) I'm able to see files are getting copied to `/rules` but on ssh'ing the backend pod I don't see `/rules/fake/<my-file.yaml>` getting created

check folder permissions
make sure your side car folder is `/rules/fake`
make sure you can use `curl` to post new rules using the default "fake" tenant

**Comment by mwtzzz** [comment]
> Hey folks! Was anyone able to make the sidecar somehow work with rules for different tenants?

I have only tried with one tenant, but it ought to work for different ones if you tell the sidecar to put them into `/rules/tenant1`, `/rules/tenant2`, etc

**Comment by zorek187** [comment]
> Hey folks! Was anyone able to make the sidecar somehow work with rules for different tenants?

Managed to make it work by adding the "FOLDER_ANNOTATION" env var to the sidecar container
[This PR](https://github.com/grafana/loki/pull/13289) adds the required value to use the env var

**Comment by akii90** [comment]
I have successfully set up AlertRules in Loki Ruler. 

Loki version: 3.5.1

Key point: Using ruler_storage, ruler.storage is deprecated

```
ruler:
  alertmanager_url: http://kube-prometheus-alertmanager:9093
  external_url: http://kube-prometheus-alertmanager:9093
  ring:
    kvstore:
      store: memberlist
  # tmp dir
  rule_path: /tmp/loki/scratch
  # Deprecated, but can't be set to null, the code still loads and validates the conf.
  # Set to a minimum
  storage:
    local:
      directory: /conf/rules
    type: local
ruler_storage:
  backend: local
  local:
    directory: /rules
```

Then set your rules in ConfigMap or whatever, mount to dir `/rules/<tenant>`, the default tenant is **fake**.
```
/rules/<tenant>/rules.yaml

```
