### ISSUE TITLE
Incorrect config rendering in `query_range` section

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#12964]
We encountered a bug in the rendering of the Loki config with the helm chart v6.0.0 that may be similar to what @MartinEmrich encountered above. These simple values will cause the rendering to fail:

```yaml
loki:
  query_range:
    parallelise_shardable_queries: false
  useTestSchema: true
```

This causes `.Values.loki.config` to look like (note the extra indent):
```yaml
query_range:
  align_queries_with_step: true
    parallelise_shardable_queries: false
  cache_results: true
```

I believe anything under `loki.query_range` is being misindented [here](https://github.com/grafana/loki/blob/0084262269f4e2cb94d04e0cc0d40e9666177f06/production/helm/loki/values.yaml#L216-L218).

EDIT: I've added a PR to solve the above but in general we've had trouble upgrading to Helm chart v6 as there are now two fields which are seemingly necessary where before they were not, and they're not listed in the upgrade guide:

- As of 6.0: we must provide a `schemaConfig` whereas in v5 we could use a suggested default without needing a `useTestSchema` flag.
- As of 6.1: we must provide storage defaults otherwise templating fails (see [this comment](https://github.com/grafana/loki/pull/12548#issuecomment-2046492619)).

In general I would personally prefer that I can always install a Helm chart with no values and get some kind of sensible default, even if only for testing out the chart. Later, when I want to go production-ready, I can tweak those parameters to something more appropriate.

_Originally posted by @coro in https://github.com/grafana/loki/issues/12506#issuecomment-2049831044_
