### ISSUE TITLE
promtail: client tls_config for helm chart

### ISSUE THREAD

**Issue by mwennrich** [grafana/loki#1297]
Currently the helm chart for promtail is missing an option for tls_config.

I would like to have an option to specifiy the promtail tls_config options also with the helm chart: 

```
tls_config:
  [ca_file: <string>]
  [cert_file: <filename>]
  [key_file: <filename>]
  [server_name: <string>]
  [insecure_skip_verify: <boolean> | default = false]
```

**Comment by R-Studio** [comment]
Any news?

**Comment by Jeroen0494** [comment]
You can use the following notation in your helm chart:
```
config:
  clients:
  - url: https://loki.cluster.local/loki/api/v1/push
    tls_config:
      insecure_skip_verify: true
```

**Comment by cstyan** [comment]
@mwennrich is this still an issue? does the suggested config from Jeroen work for you?

**Comment by janosmiko** [comment]
I'm using it with these settings and it works:
```
config:
  clients:
    - url: https://loki.example.com:443/loki/api/v1/push
      tls_config:
        ca_file: /run/secrets/loki-client-tls/ca.crt
        cert_file: /run/secrets/loki-client-tls/tls.crt
        key_file: /run/secrets/loki-client-tls/tls.key
        server_name: loki.example.com
        insecure_skip_verify: false

extraVolumes:
  - name: loki-client-tls
    secret:
      secretName: loki-client-tls

extraVolumeMounts:
  - name: loki-client-tls
    mountPath: /run/secrets/loki-client-tls
    readOnly: true

extraArgs:
  - -client.external-labels=cluster=test-cluster

podSecurityContext:
  runAsUser: null
  runAsGroup: null
  seccompProfile:
    type: RuntimeDefault
  seLinuxOptions:
    type: spc_t

```
