### ISSUE TITLE
Cannot provision recording rules via the helm chart in distributed mode

### ISSUE THREAD

**Issue by edwlarkey** [grafana/loki#13027]
**Describe the bug**
We cannot provision recording rules with the helm chart. The default values file contains these lines https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L2762-L2826 which suggest that rules can be provisioned if included here.

When adding custom rules, I can see they are added in `/etc/loki/rules` in the ruler container, but they are not picked up by Loki. When the `rule_path` config is set to `/etc/loki/rules`, Loki tries to delete the directory and fails because it is a read only filesystem. The template for the statefulset mounts the configmap here https://github.com/grafana/loki/blob/main/production/helm/loki/templates/ruler/statefulset-ruler.yaml#L105

**To Reproduce**
1. Started Loki 3.0.0
2. Install with helm

values.yaml:
```yaml
deploymentMode: Distributed
loki:
  storage:
    bucketNames:
      chunks: REPLACEME
      ruler: REPLACEME
      admin: REPLACEME
    type: s3
    s3:
      region: REPLACEME
      s3ForcePathStyle: true
  rulerConfig:
    storage:
      type: local
      local:
        directory: /var/loki/rules
    wal:
      dir: /var/loki/ruler-wal
    rule_path: /etc/loki/rules
    remote_write:
      enabled: true
      clients:
        mimir:
          url: http://mimir-nginx.monitoring.svc.cluster.local/api/v1/push
ruler:
  replicas: 1
  persistence:
    enabled: true
  directories:
    fake:
      rules.yaml: |
        groups:
        - name: api
          rules:
            - record: api:loglevel:sum_rate
              expr: sum by(level) (rate({container="api"} [10m]))
```

**Expected behavior**
I would expect that the rules be picked up by Loki and eventually show up in the Grafana UI. 

**Environment:**
 - Infrastructure: Kubernetes (EKS)
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**

```
level=info ts=2024-05-23T15:33:10.474158364Z caller=mapper.go:47 msg="cleaning up mapped rules directory" path=/etc/loki/rules
level=warn ts=2024-05-23T15:33:10.474274885Z caller=mapper.go:41 msg="unable to remove user directory" path=/etc/loki/rules/fake err="unlinkat /etc/loki/rules/fake: read-only file system"
```

**Comment by PatTheSilent** [comment]
```yaml
rule_path: /tmp/loki/scratch
storage:
  local:
    directory: /etc/loki/rules/
  type: local
```

mind the different paths in `storage.local.directory` and `rule_path`

**Comment by Rohlik** [comment]
The discrepancy between them is fine; there is no need to have these values the same. Even the official documentation has a similar [example](https://grafana.com/docs/loki/latest/alert/#alerting-and-recording-rules).

**Comment by rbelnap** [comment]
I also ran into this issue and was confused.  I resolved it by setting:
```
  rulerConfig:
    remote_write:
      enabled: true
      client:
        url: http://infra-thanos-receive.thanos.svc.cluster.local:19291/api/v1/receive
        write_relabel_configs:
        - action: replace
          target_label: job
          replacement: loki-recording-rules
    storage:
      type: local
      local:
        directory: /etc/loki/rules
    rule_path: /var/loki/rules-temp/
```
It was not clear to me that the ruler storage configured where the ruler files *come from* and the `rule_path` was where the rule files are *read from*.  I'm not sure where the chart could be adjusted to address this, maybe if `ruler.directories` isn't empty, the `rulerConfig.storage` is set to local, the `rulerConfig.rule_path` is set appropriately? It was confusing because I didn't understand the whole source -> target design for rule files initially, and the chart didn't help.

**Comment by edwlarkey** [comment]
Thank you all, I was able to get rules working with the following config.

```yaml
  rulerConfig:
    storage:
      type: local
      local:
        directory: /etc/loki/rules
    rule_path: /var/loki/rules-temp/
    wal:
      dir: /var/loki/ruler-wal
    remote_write:
      enabled: true
      clients:
        mimir:
          url: http://mimir-nginx.monitoring.svc.cluster.local/api/v1/push
```

But, I hit this issue https://github.com/grafana/mimir/discussions/4843 and it looked like metrics were not being sent to Mimir. I disabled multitenancy, and metrics are appearing in Mimir now.
