### ISSUE TITLE
service/loki missing following "monolithic Helm chart" install.

### ISSUE THREAD

**Issue by javydekoning** [grafana/loki#13045]
**Describe the bug**
Following the docs for Monolithic helm install, no loki service is created (3100)

**To Reproduce**

Values: 

```yaml
loki:
  mode: SingleBinary
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: 'filesystem'
    schemaConfig:
      configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem # we're storing on filesystem so there's no real persistence here.
        schema: v13
  singleBinary:
    replicas: 1
  read:
    replicas: 0
  backend:
    replicas: 0
  write:
    replicas: 0
```

Run `helm template . --values ./values.yaml | k apply -f -`

And no service exists:

```
loki-canary                       ClusterIP   172.20.231.211   <none>        3500/TCP             6m55s
loki-memberlist                   ClusterIP   None             <none>        7946/TCP             6m55s
release-name-loki-chunks-cache    ClusterIP   None             <none>        11211/TCP,9150/TCP   6m55s
release-name-loki-gateway         ClusterIP   172.20.174.145   <none>        80/TCP               6m55s
release-name-loki-results-cache   ClusterIP   None             <none>        11211/TCP,9150/TCP   6m55s
```

**Expected behavior**
Loki service created TCP 3100

**Environment:**
k3s single node
