### ISSUE TITLE
Windows logs scraped by promtail agent not  in readable format

### ISSUE THREAD

**Issue by lingesh00** [grafana/loki#13041]
**Scenerio:**
    The windows VM was created using kubevirt in k8s cluster .And I was trying to scrap the windows logs using promtail agent and pushed it to loki instance which was running in k8s cluster(host cluster).

**Promtail service:**
  Service for promtail  was created using NSSM tool.

Issue:
   The scraped logs are not in the readable format, also  new logs are not getting appended only those logs which were present before restarting the promtail agent was available from the loki.

**Logs from  Grafana UI:**

![image](https://github.com/grafana/loki/assets/147600847/0d463ecd-02a8-4274-b602-7b7709e916b1)

**Promtail config file:**
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  
positions:
  filename: C:\promtail\positions.yaml

clients:
  - url: http://<loki-gateway_ip>:<port>/loki/api/v1/push
    tenant_id: win-log
scrape_configs:
  - job_name: application-logs
    encoding: utf-16
    static_configs:
      - targets:
          - localhost
        labels:
          logfile: application-logs
          __path__: C:\Windows\System32\winevt\Logs\Application.evtx
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          logfile: system-logs
          __path__: C:\Windows\System32\winevt\Logs\System.evtx
```
  

k8s Version: V1.24.0
Loki version: loki:2.9.4
Promtail exe : https://github.com/grafana/loki/releases/download/v3.0.0/promtail-windows-amd64.exe.zip

How to scrap the windows logs , is there any steps to be followed .I have refered the official documentatio there is no proper explanation to deploy promtail in windows machine.
