### ISSUE TITLE
Logs Retained for Only 20 Days Despite 30-Day Retention Policy in Loki

### ISSUE THREAD

**Issue by lingesh00** [grafana/loki#13058]
**Issue :**
    Deployed loki with aws s3 bucket  in the cluster with retention for 30days , but i was able to see only the logs for last 20days .

**To Reproduce**

-  Install loki using helm with versin 2.9.4

# Source: loki/templates/config.yaml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  namespace: cloudlyte-logging
  labels:
    helm.sh/chart: loki-5.44.1
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "2.9.4"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |

    auth_enabled: true
    common:
      compactor_address: 'http://loki-backend:3100'
      path_prefix: /var/loki
      replication_factor: 3
      storage:
        s3:
          access_key_id: <-->
          bucketnames: chunks
          region: us-east-1
          endpoint: <-->
          insecure: true
          s3forcepathstyle: true
          secret_access_key: <-->
    frontend:
      scheduler_address: query-scheduler-discovery.logging.svc.cluster.local.:9095
    frontend_worker:
      scheduler_address: query-scheduler-discovery.logging.svc.cluster.local.:9095
    index_gateway:
      mode: ring
    compactor:
      retention_enabled: true
    limits_config:
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      retention_period: 30d
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
    memberlist:
      join_members:
      - loki-memberlist
    query_range:
      align_queries_with_step: true
    ruler:
      storage:
        s3:
          access_key_id: < -->
          bucketnames: ruler
          endpoint: <-->
          insecure: true
          s3forcepathstyle: true
          region: us-east-1
          secret_access_key: <-->
        type: s3
    runtime_config:
      file: /etc/loki/runtime-config/runtime-config.yaml
    schema_config:
      configs:
      - from: "2022-01-11"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v12
        store: boltdb-shipper
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
    storage_config:
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
    tracing:
      enabled: false
```

**Expected behavior**
 As per the loki config file , the logs should be retaind for 30days , but i was able to see only last 20days logs.

**Environment:**
 - Infrastructure:  Kubernetes(v1.24.0)
 - Deployment tool: Helm

**Log from Grafana UI:**

![Screenshot 2024-05-29 121011](https://github.com/grafana/loki/assets/147600847/d71856f8-69a1-44d4-96f5-bd56e1249dbc)
