### ISSUE TITLE
[Question] Log is not deleted exceed retention perion

### ISSUE THREAD

**Issue by g3david405** [grafana/loki#13072]
**Describe the bug**
I set the config file that retention logs for 1d, however the old log file still exists when exceed the time period.
Here is my partial config:
```
compactor:
  compaction_interval: 10m
  delete_request_store: s3
  retention_delete_delay: 2h
  retention_enabled: true
  shared_store: s3
  working_directory: /var/loki/compactor
ingester:
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_idle_period: 30m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  max_transfer_retries: 0
  wal:
    dir: /var/loki/wal
limits_config:
  enforce_metric_name: false
  max_cache_freshness_per_query: 10m
  reject_old_samples: true
  reject_old_samples_max_age: 24h
  retention_period: 24h
  split_queries_by_interval: 15m
schema_config:
  configs:
  - from: "2020-09-07"
    index:
      period: 24h
      prefix: loki_index_
    object_store: s3
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
storage_config:
  aws:
    bucketnames: loki-bucket
    s3: http://minio.tenant.svc.cluster.local
    s3forcepathstyle: true
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    cache_ttl: 168h
    shared_store: s3
table_manager:
  retention_deletes_enabled: true
  retention_period: 0s
```
I use minio as my storage, but the data still exists for more than 1 day (I write this article in 5/30)
![image](https://github.com/grafana/loki/assets/75260884/9609ffe1-3e68-4ba3-8e5a-4746c0ef2166)

**Expected behavior**
Logs older than 1d(24h) in minio should be deleted.

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm
![image](https://github.com/grafana/loki/assets/75260884/59538d64-b8ff-4977-8b0b-9d6719f8a8bd)

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
