### ISSUE TITLE
Azure blob storage config; storage account name not being set in request URL

### ISSUE THREAD

**Issue by murillio4** [grafana/loki#13086]
I have my storage configured like this: (name and key ommited)
```
...
storage_config:
  azure:
    use_managed_identity: false
    connection_string: "DefaultEndpointsProtocol=https;AccountName=<<NAME>>;AccountKey=<<KEY>>;EndpointSuffix=core.windows.net"
    container_name: "loki"
    request_timeout: 0
      
storage:
  bucketNames:
    chunks: loki
    ruler: loki
    admin: loki
  type: azure
...
```

I gen an error in loki backend `level=error ts=2024-05-30T16:47:49.610718972Z caller=ruler.go:576 msg="unable to list rules" err="Get \"https://.blob.core.windows.net/loki?comp=list&delimiter=&prefix=rules%2F&restype=container&timeout=31\": dial tcp: lookup .blob.core.windows.net: no such host"`. Seems like its not picking up the AccountName. I have also tried to set `account_name` and `account_key` without using the `connection_string`, but still not picking it up.

**To Reproduce**
1. Loki Version: 3.0.0
2. Loki Helm Chart Version: 6.6.2

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

```
level=error ts=2024-05-30T16:47:49.610718972Z caller=ruler.go:576 msg="unable to list rules" err="Get \"https://.blob.core.windows.net/loki?comp=list&delimiter=&prefix=rules%2F&restype=container&timeout=31\": dial tcp: lookup .blob.core.windows.net: no such host"
level=info ts=2024-05-30T16:48:08.410016817Z caller=gateway.go:241 component=index-gateway msg="chunk filtering is not enabled"
level=info ts=2024-05-30T16:48:08.424700696Z caller=gateway.go:241 component=index-gateway msg="chunk filtering is not enabled"
level=info ts=2024-05-30T16:48:08.463652667Z caller=gateway.go:241 component=index-gateway msg="chunk filtering is not enabled"
level=info ts=2024-05-30T16:48:28.435858464Z caller=gateway.go:241 component=index-gateway msg="chunk filtering is not enabled"
level=info ts=2024-05-30T16:48:30.723587581Z caller=gateway.go:241 component=index-gateway msg="chunk filtering is not enabled"
level=info ts=2024-05-30T16:48:30.742946098Z caller=gateway.go:241 component=index-gateway msg="chunk filtering is not enabled"
level=info ts=2024-05-30T16:48:30.756356926Z caller=gateway.go:241 component=index-gateway msg="chunk filtering is not enabled"
level=info ts=2024-05-30T16:48:30.76306544Z caller=gateway.go:241 component=index-gateway msg="chunk filtering is not enabled"
level=info ts=2024-05-30T16:48:30.7806389Z caller=gateway.go:241 component=index-gateway msg="chunk filtering is not enabled"
level=info ts=2024-05-30T16:48:30.787119606Z caller=gateway.go:241 component=index-gateway msg="chunk filtering is not enabled"
level=info ts=2024-05-30T16:48:30.958810079Z caller=gateway.go:241 component=index-gateway msg="chunk filtering is not enabled"
level=info ts=2024-05-30T16:48:30.966099111Z caller=gateway.go:241 component=index-gateway msg="chunk filtering is not enabled"
```

**Comment by murillio4** [comment]
Seems like the loki chart is not generating the ruler config correctly. Its only getting `container_name`.
```
ruler:
  storage:
    azure:
      container_name: <Container name>
```

**Comment by murillio4** [comment]
After digging through the loki helm chart i discovered that the values of `storage_config.azure` uses snake_case and `storage.azure` uses camelCase. Changing the config solved the problem.

**Comment by acar-ctpe** [comment]
Can you please paste an example?

**Comment by murillio4** [comment]
@acar-ctpe sorry for late answer. Here is part of my config:

```yaml
loki:  
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1

  storage_config:
    tsdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/index_cache
      cache_ttl: 24h
    
    filesystem:
      directory: /var/loki/chunks
    
    ## snake_case
    azure:
      account_name: <name>
      account_key: <key>
      container_name: <container-name>
  
  ## camelCase
  storage:
    bucketNames:
      chunks: <container-name>
      ruler: <container-name>
      admin: <container-name>
    
    type: azure
    azure:
      accountName: <name>
      accountKey: <key>

  schemaConfig:
    configs:
      - from: "2020-12-11"
        index:
          period: 24h
          prefix: index_
        object_store: azure
        schema: v13
        store: tsdb

  compactor:
    retention_enabled: true
    working_directory: /var/loki/compactor
    compaction_interval: 10m
    delete_request_store: azure
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
```
