### ISSUE TITLE
Docs feedback: /docs/sources/setup/install/helm/install-scalable/_index.md

### ISSUE THREAD

**Issue by edsoncelio** [grafana/loki#13088]
Hello,

If you try to follow these docs to set up a minimal installation you will receive this error: 

```bash
Error: INSTALLATION FAILED: execution error at (loki/templates/validate.yaml:40:4): You must provide a schema_config for Loki, one is not provided as this will be individual for every Loki cluster. See [Storage schema | Grafana Loki documentation](https://grafana.com/docs/loki/latest/operations/storage/schema/) for schema information. For quick testing (with no persistence) add --set loki.useTestSchema=true
```
To fix it you need to add the schemaConfig block, like this:

```yaml
loki:
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h
```
And then it will work fine.

Besides that, the examples that are referencing the `schemaConfig` are outdated, referencing to to `schema_config`: https://grafana.com/docs/loki/latest/configure/examples/configuration-examples/

It will be good to add this block above (or a similar one) to achieve the docs goal or add the flag to use the test schema with a few words explaining the reason.

Another suggestion is to specify a version of the helm chart used in this guide, this will help to not break the docs in breaking changes.

I can open a PR to update these docs (If this is an expected behavior).
