### ISSUE TITLE
Get "http://loki-canary:3500/metrics": dial tcp 10.96.55.232:3500: connect: connection refused

### ISSUE THREAD

**Issue by andytael** [grafana/loki#13087]
**Describe the bug**
Looking at the log-file for the pod `loki-helm-test` I can see the following error:

```
=== RUN   TestCanary
=== RUN   TestCanary/Canary_should_have_entries
    canary_test.go:127:
        	Error Trace:	/src/loki/production/helm/loki/src/helm-test/canary_test.go:127
        	            				/src/loki/production/helm/loki/src/helm-test/canary_test.go:58
        	            				/src/loki/production/helm/loki/src/helm-test/canary_test.go:172
        	            				/usr/local/go/src/runtime/asm_amd64.s:1650
        	Error:      	Received unexpected error:
        	            	Get "http://loki-canary:3500/metrics": dial tcp 10.96.55.232:3500: connect: connection refused
        	Test:       	TestCanary/Canary_should_have_entries
        	Messages:   	Failed to scrape metrics
    canary_test.go:171:
        	Error Trace:	/src/loki/production/helm/loki/src/helm-test/canary_test.go:171
        	            				/src/loki/production/helm/loki/src/helm-test/canary_test.go:57
        	Error:      	Condition never satisfied
        	Test:       	TestCanary/Canary_should_have_entries
        	Messages:   	Expected Loki Canary to have entries
=== RUN   TestCanary/Canary_should_not_have_missed_any_entries
    canary_test.go:127:
        	Error Trace:	/src/loki/production/helm/loki/src/helm-test/canary_test.go:127
        	            				/src/loki/production/helm/loki/src/helm-test/canary_test.go:66
        	            				/src/loki/production/helm/loki/src/helm-test/canary_test.go:172
        	            				/usr/local/go/src/runtime/asm_amd64.s:1650
        	Error:      	Received unexpected error:
        	            	Get "http://loki-canary:3500/metrics": context deadline exceeded
        	Test:       	TestCanary/Canary_should_not_have_missed_any_entries
        	Messages:   	Failed to scrape metrics
    canary_test.go:171:
        	Error Trace:	/src/loki/production/helm/loki/src/helm-test/canary_test.go:171
        	            				/src/loki/production/helm/loki/src/helm-test/canary_test.go:65
        	Error:      	Condition never satisfied
        	Test:       	TestCanary/Canary_should_not_have_missed_any_entries
        	Messages:   	Expected Loki Canary to not have any missing entries
--- FAIL: TestCanary (120.00s)
    --- FAIL: TestCanary/Canary_should_have_entries (60.00s)
    --- FAIL: TestCanary/Canary_should_not_have_missed_any_entries (60.00s)
FAIL
```

**To Reproduce**
1. Deploy to k8s cluster using the following configuration:

```yaml
# https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml
# Default values for jaeger.
# This is a YAML-formatted file.
# Jaeger values are grouped by component. Cassandra values override subchart values

provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false

allInOne:
  enabled: true
  replicas: 1
  image:
    repository: jaegertracing/all-in-one
    pullPolicy: Always
  extraEnv: []
  # command line arguments / CLI flags
  # See https://www.jaegertracing.io/docs/cli/
  args: []
  # samplingConfig: |-
  #   {
  #     "default_strategy": {
  #       "type": "probabilistic",
  #       "param": 1
  #     }
  #   }
  ingress:
    enabled: false
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx
    annotations: {}
    labels: {}
    # Used to create an Ingress record.
    # hosts:
    #   - chart-example.local
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: "true"
    # labels:
    #   app: jaeger
    # tls:
    #   # Secrets must be manually created in the namespace.
    #   - secretName: chart-example-tls
    #     hosts:
    #       - chart-example.local
  # resources:
  #   limits:
  #     cpu: 500m
  #     memory: 512Mi
  #   requests:
  #     cpu: 256m
  #     memory: 128Mi
  nodeSelector: {}

## Disabled as using All-in-One
ingester:
  enabled: false
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
spark:
  enabled: false
esIndexCleaner:
  enabled: false
esRollover:
  enabled: false  
esLookback:
  enabled: false
hotrod:
  enabled: false

# This needs to be looked at, allowed values (cassandra, elasticsearch, grpc-plugin, badger, memory)
storage:
  type: memory
```

**Expected behavior**
Expect to get metrics from the `http://loki-canary:3500/metrics` service.

If I do a port-forward to the `loki-canary` service on the k8s cluster and curl `http://localhost:3500/metrics` I get values

```log
 curl http://localhost:3500/metrics
# HELP deprecated_flags_inuse_total The number of deprecated flags currently set.
# TYPE deprecated_flags_inuse_total counter
deprecated_flags_inuse_total 0
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 9.083e-06
go_gc_duration_seconds{quantile="0.25"} 2.8934e-05
go_gc_duration_seconds{quantile="0.5"} 4.7112e-05
go_gc_duration_seconds{quantile="0.75"} 6.0182e-05
go_gc_duration_seconds{quantile="1"} 0.000296451
go_gc_duration_seconds_sum 0.001569694
go_gc_duration_seconds_count 26
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 17
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.21.9"} 1
```

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Log file above
