### ISSUE TITLE
Global `grpc_client_config`

### ISSUE THREAD

**Issue by z0rc** [grafana/loki#13096]
**Is your feature request related to a problem? Please describe.**
I'm setting `grpc_client_config.grpc_compression: snappy` for multiple components in loki.yaml. I need this to reduce traffic between Loki microservices to save on cloud costs.

The problem is, this configuration has to be set individually for every Loki component. Which:
- isn't pretty, my helm chart values is sprinkled with `grpc_client_config` in multiple places. Like this:
  ```yaml
  loki:
    storage_config:
      boltdb_shipper:
        index_gateway_client:
          grpc_client_config:
            grpc_compression: snappy
      tsdb_shipper:
        index_gateway_client:
          grpc_client_config:
            grpc_compression: snappy
    structuredConfig:
      ingester_client:
        grpc_client_config:
          grpc_compression: snappy
      pattern_ingester:
        client_config:
          grpc_client_config:
            grpc_compression: snappy
    ingester:
      chunk_encoding: snappy
    query_scheduler:
      grpc_client_config:
        grpc_compression: snappy
    frontend:
      grpc_client_config:
        grpc_compression: snappy
    frontend_worker:
      grpc_client_config:
        grpc_compression: snappy
  ```
- easy to miss this options for some component, or have to remember to set it when Loki introduces new microservices (bloom-*, pattern-ingester)

**Describe the solution you'd like**
Ability to set `grpc_client_config` in config once and it will be applied universally.

**Describe alternatives you've considered**
None.

**Additional context**
N/A
