### ISSUE TITLE
Can't upgrade filesystem setup from helm 5.48.0 up to 6+

### ISSUE THREAD

**Issue by jonathon2nd** [grafana/loki#13092]
**Describe the bug**
Unable to perform helm upgrade past 5.48.0

I am seeking the new basic filesystem setup for preprod. 

**To Reproduce**
1. Start with https://grafana.github.io/helm-charts loki:5.48.0 installed with the following values
```
global:
  # -- configures DNS service name
  dnsService: "rke2-coredns-rke2-coredns"
  # -- configures DNS service namespace
  dnsNamespace: "kube-system"
loki:
  # Should authentication be enabled
  auth_enabled: false
  # -- Check https://grafana.com/docs/loki/latest/configuration/#common_config for more info on how to provide a common configuration
  commonConfig:
    replication_factor: 1
  # -- Storage config. Providing this will automatically populate all necessary storage configs in the templated config.
  storage:
    type: 'filesystem'
  # --  Optional compactor configuration
  compactor:
    shared_store: filesystem
    working_directory: /var/loki/boltdb-shipper-compactor
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 1h
    retention_delete_worker_count: 100
# Configuration for the single binary node(s)
singleBinary:
  # -- Number of replicas for the single binary
  replicas: 1
  persistence:
    # -- Enable StatefulSetAutoDeletePVC feature
    enableStatefulSetAutoDeletePVC: false
    # -- Enable persistent disk
    enabled: true
    # -- Size of persistent disk
    size: 100Gi
    # -- Storage class to be used.
    # If defined, storageClassName: <storageClass>.
    # If set to "-", storageClassName: "", which disables dynamic provisioning.
    # If empty or set to null, no storageClassName spec is
    # set, choosing the default provisioner (gp2 on AWS, standard on GKE, AWS, and OpenStack).
    storageClass: linstor-replica-three
# -- Section for configuring optional Helm test
test:
  enabled: false
# Monitoring section determines which monitoring features to enable
monitoring:
  # Self monitoring determines whether Loki should scrape its own logs.
  # This feature currently relies on the Grafana Agent Operator being installed,
  # which is installed by default using the grafana-agent-operator sub-chart.
  # It will create custom resources for GrafanaAgent, LogsInstance, and PodLogs to configure
  # scrape configs to scrape its own logs with the labels expected by the included dashboards.
  selfMonitoring:
    enabled: false
  # The Loki canary pushes logs to and queries from this loki installation to test
  # that it's working correctly
  lokiCanary:
    enabled: false
```

**Expected behavior**
I consulted: https://grafana.com/docs/loki/latest/setup/upgrade/upgrade-to-6x/
And after making needed adjustments expected the upgrade to work, it did not.

Things were not made more clear by https://github.com/grafana/loki/blob/main/production/helm/loki/CHANGELOG.md

I first had this error 
```
Unable to save changes: application spec for preprod-loki is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = `helm template . --name-template preprod-loki --namespace loki --kube-version 1.26 --values /tmp/f525c479-3de6-4876-9d74-73219c935e13 <api versions removed> --include-crds` failed exit status 1: Error: execution error at (loki/templates/validate.yaml:31:4): You have more than zero replicas configured for both the single binary and simple scalable targets. If this was intentional change the deploymentMode to the transitional 'SingleBinary<->SimpleScalable' mode Use --debug flag to render out invalid YAML
```

Which I seemed to resolve by adding
```
deploymentMode: SingleBinary
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
```

But then I had 
```
Unable to save changes: application spec for preprod-loki is invalid: InvalidSpecError: Unable to generate manifests in : rpc error: code = Unknown desc = `helm template . --name-template preprod-loki --namespace loki --kube-version 1.26 --values /tmp/8580f49b-a7c8-43d3-a065-cd6bdf0972c2 <api versions removed> --include-crds` failed exit status 1: Error: execution error at (loki/templates/validate.yaml:40:4): You must provide a schema_config for Loki, one is not provided as this will be individual for every Loki cluster. See https://grafana.com/docs/loki/latest/operations/storage/schema/ for schema information. For quick testing (with no persistence) add `--set loki.useTestSchema=true` Use --debug flag to render out invalid YAML
```

I looked at https://github.com/grafana/loki/issues/12773#issuecomment-2075897405 which seemed to help some

But then the compactor config seemed to be completely wrong, and nothing seemed to fix it.

**Environment:**
 - Infrastructure: v1.26.13 +rke2r1
 - Deployment tool: Helm

**Comment by jonathon2nd** [comment]
Ok it might be because I have not migrated to TSDB yet: https://grafana.com/docs/loki/latest/setup/migrate/migrate-to-tsdb/
Attempting that with chart version: 6.6.2
```
deploymentMode: SingleBinary
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
global:
  dnsService: "rke2-coredns-rke2-coredns"
  dnsNamespace: "kube-system"
loki:
  auth_enabled: false
  # -- Check https://grafana.com/docs/loki/latest/configuration/#common_config for more info on how to provide a common configuration
  commonConfig:
    replication_factor: 1
  # -- Storage config. Providing this will automatically populate all necessary storage configs in the templated config.
  storage:
    type: 'filesystem'
    tsdb_shipper:
      active_index_directory: /var/loki/tsdb-index
      cache_location: /var/loki/tsdb-cache
  compactor:
    working_directory: /var/loki/boltdb-shipper-compactor
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 1h
    retention_delete_worker_count: 100
    delete_request_store: filesystem
# Configuration for the single binary node(s)
  schemaConfig:
    configs:
      - from: "2023-01-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
      - from: "2024-05-31"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
singleBinary:
  # -- Number of replicas for the single binary
  replicas: 1
  persistence:
    # -- Enable StatefulSetAutoDeletePVC feature
    enableStatefulSetAutoDeletePVC: false
    # -- Enable persistent disk
    enabled: true
    # -- Size of persistent disk
    size: 100Gi
    # -- Storage class to be used.
    # If defined, storageClassName: <storageClass>.
    # If set to "-", storageClassName: "", which disables dynamic provisioning.
    # If empty or set to null, no storageClassName spec is
    # set, choosing the default provisioner (gp2 on AWS, standard on GKE, AWS, and OpenStack).
    storageClass: linstor-replica-three
```

That seems to do it!

Bonus: Rancher-logging needs a label added to the output
```
2024-05-31 20:43:24 +0000 [warn]: #0 [clusterflow:cattle-logging-system:all:clusteroutput:cattle-logging-system:loki] failed to write post to http://preprod-loki.loki:3100/loki/api/v1/push (400 Bad Request error at least one label pair is required per stream
```
![image](https://github.com/grafana/loki/assets/52681917/86174b22-4af5-4fde-9be0-c864351d2a74)
