### ISSUE TITLE
Severe memory leak when ingesting logs with structured metadata

### ISSUE THREAD

**Issue by JohanLindvall** [grafana/loki#13123]
**Describe the bug**
The memory usage of the ingester / write pods increase rapidly and the pods get killed by the Kubernetes scheduler.

**To Reproduce**

1. Deploy Loki 3 Distributed or simple scalable using official Helm charts
2. Ingest quite a bit of data (5k lines/s) with structure metadata of high cardinality
3. Wait until the pods get killed due to OOM

**Expected behavior**
Pods should not get killed and mem usage should not grow as fast as it does

**Environment:**
AKS, Kubernetes 1.28.9
Deployed the official Loki helm charts
I tried Loki 3.0.0 and also the latest main binaries as of 2023-06-03

**Screenshots, Promtail config, or terminal output**
This shows memory usage of the ingester pods:
![Screenshot from 2024-06-04 08-24-16](https://github.com/grafana/loki/assets/13338719/dae2d0c6-6591-401a-9f66-1586ac93da07)

This shows pprof heap output after running for a few minutes
![leak](https://github.com/grafana/loki/assets/13338719/54e8c0cc-a7b1-406a-9a1e-6e093cd86b12)

It looks like gRPC data somehow is kept alive (possibly by the structured metadata symbolizer, although this is speculation from me)

This may have been reported before, under https://github.com/grafana/loki/issues/10994

What we typically put in the structured metadata:
country (1-200 different values), data_center (2-300 different values), traceid, spanid (no upper bound)

Config:
```
auth_enabled: false
chunk_store_config:
  chunk_cache_config:
    background:
      writeback_buffer: 500000
      writeback_goroutines: 1
      writeback_size_limit: 500MB
    default_validity: 0s
    memcached:
      batch_size: 4
      parallelism: 5
    memcached_client:
      addresses: dnssrvnoa+_memcached-client._tcp.loki-chunks-cache.monitoring-loki3.svc
      consistent_hash: true
      max_idle_conns: 72
      timeout: 2000ms
common:
  compactor_address: 'http://loki-compactor:3100'
  path_prefix: /var/loki
  replication_factor: 3
  storage:
    azure:
      account_key: ${AZURE_STORAGE_ACCOUNT_KEY}
      account_name: ${AZURE_STORAGE_ACCOUNT_NAME}
      container_name: ${AZURE_STORAGE_CONTAINER_NAME}
      use_federated_token: false
      use_managed_identity: false
compactor:
  delete_request_store: azure
  retention_enabled: true
frontend:
  scheduler_address: loki-query-scheduler.monitoring-loki3.svc.cluster.local:9095
  tail_proxy_url: http://loki-querier.monitoring-loki3.svc.cluster.local:3100
frontend_worker:
  scheduler_address: loki-query-scheduler.monitoring-loki3.svc.cluster.local:9095
index_gateway:
  mode: simple
ingester:
  chunk_encoding: snappy
limits_config:
  bloom_compactor_enable_compaction: false
  bloom_gateway_enable_filtering: false
  discover_log_levels: false
  discover_service_name: []
  ingestion_burst_size_mb: 250
  ingestion_rate_mb: 250
  max_cache_freshness_per_query: 10m
  max_global_streams_per_user: 100000
  max_label_names_per_series: 30
  max_line_size: 1048576
  max_line_size_truncate: true
  max_query_series: 10000
  per_stream_rate_limit: 50MB
  per_stream_rate_limit_burst: 250MB
  query_timeout: 300s
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 744h
  shard_streams:
    enabled: false
  split_queries_by_interval: 15m
  volume_enabled: true
memberlist:
  join_members:
  - loki-memberlist
pattern_ingester:
  enabled: false
querier:
  max_concurrent: 16
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      background:
        writeback_buffer: 500000
        writeback_goroutines: 1
        writeback_size_limit: 500MB
      default_validity: 12h
      memcached_client:
        addresses: dnssrvnoa+_memcached-client._tcp.loki-results-cache.monitoring-loki3.svc
        consistent_hash: true
        timeout: 500ms
        update_interval: 1m
ruler:
  storage:
    azure:
      account_key: ${AZURE_STORAGE_ACCOUNT_KEY}
      account_name: ${AZURE_STORAGE_ACCOUNT_NAME}
      container_name: ruler
      use_federated_token: false
      use_managed_identity: false
    type: azure
runtime_config:
  file: /etc/loki/runtime-config/runtime-config.yaml
schema_config:
  configs:
  - from: "2020-01-01"
    index:
      period: 24h
      prefix: index_
    object_store: azure
    schema: v13
    store: tsdb
server:
  grpc_listen_port: 9095
  grpc_server_max_recv_msg_size: 25165824
  grpc_server_max_send_msg_size: 25165824
  http_listen_port: 3100
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s
storage_config:
  boltdb_shipper:
    index_gateway_client:
      server_address: dns+loki-index-gateway-headless.monitoring-loki3.svc.cluster.local:9095
  hedging:
    at: 250ms
    max_per_second: 20
    up_to: 3
  tsdb_shipper:
    index_gateway_client:
      server_address: dns+loki-index-gateway-headless.monitoring-loki3.svc.cluster.local:9095
tracing:
  enabled: true
```
