### ISSUE TITLE
Unrecognized storage client after schema upgrade 

### ISSUE THREAD

**Issue by csomm** [grafana/loki#13141]
**Describe the bug**
We are currently running Loki 2.9.6. We tried to add a new schema config to migrate to TSDB. After adding the new schema config we got the error message `Unrecognized storage client , choose one of: aws, s3, gcs, azure, alibabacloud, swift, bos, cos, filesystem.`

We tried to modify the config according to hints we found in other tickets, where people had the same issue, especially we added `shared_store` attributes in different places. But we still get the same error message. When we remove the new schema config, Loki starts again, as expected.

**To Reproduce**

Try to start Loki 2.9.6 with this config (this is the last iteration of the config we tried to get running):
```
auth_enabled: false

common:
  path_prefix: /var/loki
  ring:
    kvstore:
      store: memberlist

memberlist:
  join_members:
  - loki-memberlist

limits_config:
  ingestion_rate_strategy: local
  ingestion_rate_mb: 5
  retention_period: 20w

server:
  http_listen_port: 8080
  grpc_listen_port: 9095
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

ingester_client:
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    grpc_compression: gzip

ingester:
  max_transfer_retries: 10
  wal:
    enabled: false
  flush_check_period: 2m
  chunk_block_size: 1048576 # 1MB
  lifecycler:
    num_tokens: 512

schema_config:
  configs:
  - from: 2020-05-05
    store: cassandra
    object_store: azure
    schema: v10
    index:
      prefix: index_
      period: 5w
  - from: 2024-06-05
    store: tsdb
    object_store: azure
    schema: v13
    index:
      prefix: index_
      period: 24h

frontend_worker:
  match_max_concurrent: true

storage_config:
  azure:
    container_name: loki
    account_name: ${BLOB_ACCOUNT_NAME}
    account_key: ${BLOB_ACCOUNT_KEY}
  cassandra:
    addresses: ${CASSANDRA_ENDPOINTS}
    port: 10350
    keyspace: loki
    disable_initial_host_lookup: true
    SSL: true
    host_verification: true
    auth: true
    username: ${CASSANDRA_USERNAME}
    password: ${CASSANDRA_PASSWORD}
  tsdb_shipper:
    shared_store: azure

analytics:
  reporting_enabled: false

chunk_store_config:
  max_look_back_period: 20w

table_manager:
  retention_deletes_enabled: true
  retention_period: 20w

compactor:
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: azure
  shared_store: azure

ruler:
  enable_sharding: true
  storage:
    type: local
    local:
      directory: "/tmp/rules"
  rule_path: "/rules"
  wal:
    dir: "/rules/wal"
  remote_write:
    enabled: true
    config_refresh_period: 10s
    client:
      url: http://prometheus.sys-prometheus.svc.cluster.local.:80/api/v1/write
      remote_timeout: 30s
      headers: {}
      write_relabel_configs: []
      name: loki
```
The log message
`level=error ts=2024-06-04T13:01:34.5735901Z caller=log.go:230 msg="error running loki" err="Unrecognized storage client , choose one of: aws, s3, gcs, azure, alibabacloud, swift, bos, cos, filesystem\nerror initialising module: table-manager\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:461\nmain.main\n\t/src/loki/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650"`
gets printed on startup and Loki then exits.

When we remove the section
```
  - from: 2024-06-05
    store: tsdb
    object_store: azure
    schema: v13
    index:
      prefix: index_
      period: 24h
```
Loki is running as expected again.

**Expected behavior**
Loki should start after adding the new schema config, or in case some config is missing, it should print a more helpful error message.

**Environment:**
 - Kubernetes 1.27.9
 - Deployment is currently done with our own StatefulSet manifest, running Loki in single binary mode. We want to migrate to a config which is supported by the Helm chart and then migrate to the Helm chart
