### ISSUE TITLE
Docs feedback: /docs/sources/send-data/promtail/stages/pack.md

### ISSUE THREAD

**Issue by Feuermurmel** [grafana/loki#13142]
I think the following sentence is incorrect:

> The `pack` stage is a transform stage which lets you embed extracted values and labels into the log line by packing the log line and labels inside a JSON object.

In my tests, I was unable to insert a label into the packed JSON object, while inserting a value from the extraction map works.

I'm using the following pipeline, which inserts the entry `foo_extraction_map = hello-1` into the extraction map and the entry `foo_labels = hello-2` into the labels:

```yaml
clients:
- url: http://localhost

scrape_configs:
- job_name: test
  pipeline_stages:
    - template:
        source: extraction_map_entry
        template: hello-1
    - static_labels:
        labels_entry: hello-2
    - pack:
        labels: [extraction_map_entry, labels_entry]
```

The produced log line (when running with `--dry-run`) looks like this:

```
2024-06-05T17:04:24.885895196+0200	{labels_entry="hello-2"}	{"extraction_map_entry":"hello-1","_entry":"hello"}
```

This means that `pack` was able to "see" `extraction_map_entry` from the extraction map, but not `labels_entry` from the labels.
