### ISSUE TITLE
promtail: __path__ fileglob behavior

### ISSUE THREAD

**Issue by karlism** [grafana/loki#1314]
**Describe the bug**
I'm unable to add logfiles from different directories to `__path__`.
It works when I specify:
```
__path__: /var/log/{daemon,messages}
```
But doesn't work when I specify:
```
__path__: {/var/log/daemon,/var/log/messages}
```
```
# echo $0 
ksh
$ ls -la /var/log/{daemon,messages}          
-rw-r-----  1 root  _promtail  6387 Nov 25 10:24 /var/log/daemon
-rw-r--r--  1 root  wheel       138 Nov 25 10:00 /var/log/messages
$ ls -la {/var/log/daemon,/var/log/messages} 
-rw-r-----  1 root  _promtail  6387 Nov 25 10:24 /var/log/daemon
-rw-r--r--  1 root  wheel       138 Nov 25 10:00 /var/log/messages
$ bash
$ echo $0
bash
$ ls -la /var/log/{daemon,messages}
-rw-r-----  1 root  _promtail  6387 Nov 25 10:24 /var/log/daemon
-rw-r--r--  1 root  wheel       138 Nov 25 10:00 /var/log/messages
$ ls -la {/var/log/daemon,/var/log/messages}
-rw-r-----  1 root  _promtail  6387 Nov 25 10:24 /var/log/daemon
-rw-r--r--  1 root  wheel       138 Nov 25 10:00 /var/log/messages
```

**To Reproduce**
```
# cat /tmp/promtail.yml 
---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: "/tmp/positions.yaml"

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: "syslog"
    static_configs:
    - labels:
        __path__: /var/log/{daemon,messages}
        #__path__: {/var/log/daemon,/var/log/messages}
        hostname: example
        job: syslog
      targets:
      - localhost

# promtail -config.file=/tmp/promtail.yml 
level=warn ts=2019-11-25T10:59:46.094732806Z caller=filetargetmanager.go:98 msg="WARNING!!! entry_parser config is deprecated, please change to pipeline_stages"
level=info ts=2019-11-25T10:59:46.095204968Z caller=server.go:121 http=0.0.0.0:9080 grpc=0.0.0.0:34652 msg="server listening on addresses"
level=info ts=2019-11-25T10:59:46.095818529Z caller=main.go:65 msg="Starting Promtail" version="(version=, branch=, revision=)"
level=info ts=2019-11-25T10:59:51.097059246Z caller=filetargetmanager.go:257 msg="Adding target" key="{hostname=\"example\", job=\"syslog\"}"
ts=2019-11-25T10:59:51.137000974Z caller=log.go:124 component=tailer level=info msg="Seeked /var/log/daemon - &{Offset:6387 Whence:0}"
level=info ts=2019-11-25T10:59:51.137143439Z caller=tailer.go:77 component=tailer msg="start tailing file" path=/var/log/daemon
ts=2019-11-25T10:59:51.137319866Z caller=log.go:124 component=tailer level=info msg="Seeked /var/log/messages - &{Offset:138 Whence:0}"
level=info ts=2019-11-25T10:59:51.137431228Z caller=tailer.go:77 component=tailer msg="start tailing file" path=/var/log/messages
^Clevel=info ts=2019-11-25T10:59:53.606531519Z caller=signals.go:54 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=info ts=2019-11-25T10:59:53.606852159Z caller=filetargetmanager.go:318 msg="Removing target" key="{hostname=\"example\", job=\"syslog\"}"
level=info ts=2019-11-25T10:59:53.607173095Z caller=tailer.go:148 component=tailer msg="stopped tailing file" path=/var/log/daemon
level=info ts=2019-11-25T10:59:53.60727424Z caller=tailer.go:148 component=tailer msg="stopped tailing file" path=/var/log/messages

# cat /tmp/promtail.yml   # (__path__ value is changed)
---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: "/tmp/positions.yaml"

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: "syslog"
    static_configs:
    - labels:
        #__path__: /var/log/{daemon,messages}
        __path__: {/var/log/daemon,/var/log/messages}   # <-- here
        hostname: example
        job: syslog
      targets:
      - localhost

# promtail -config.file=/tmp/promtail.yml 
Unable to parse config: sourcing: yaml: unmarshal errors:
  line 17: cannot unmarshal !!map into model.LabelValue
```
I've tried escaping `/` characters with `\`, but that didn't help.

**Expected behavior**
I expect it to work when full path is specified inside the variable. I need to specify full path in order to read logs from different directories.
Also, wouldn't it make more sense if value of `__path__` would be a list instead of string?

**Environment:**
 - Infrastructure: OpenBSD 6.5 amd 64 VM:
`OpenBSD example 6.5 GENERIC#7 amd64`
`promtail` version 1.0.0
