### ISSUE TITLE
Slow performance/timeout for count_over_time on < 1,000 logs

### ISSUE THREAD

**Issue by fraxken** [grafana/loki#13157]
Hello 👋 

We have encountered an issue with our Loki setup at work. A few months ago, we upgraded from:

```
loki, version 2.2.1 (branch: HEAD, revision: babea82e)
```

to the latest version available at that time:

```
loki, version 2.9.3 (branch: HEAD, revision: 2535f9bede)
````

Since the upgrade, some LogQL requests have stopped working properly. For example, the following query times out when fetching ~700 logs over a range of one hour (it works fine with a range of 15 minutes or less):

```
count_over_time(
  {app="auth",env="production"}
    |= "request an authentication on"
    | regexp `\(.*\) (?P<email>\S+) request`
[$__range])
```

However, without count_over_time, the LogQL runs almost instantaneously.

```
{app="auth",env="production"}
    |= "request an authentication on"
    | regexp `\(.*\) (?P<email>\S+) request`
```

## Additional Information

<details>
<summary>Loki configuration</summary>

```yml
auth_enabled: false

server:
  http_listen_port: 3100
  http_path_prefix: '/'

ingester:
  wal:
    enabled: true
    dir: /var/lib/loki/wal
#    recover: true
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled
  chunk_encoding: snappy

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /var/lib/loki/boltdb-shipper-active
    cache_location: /var/lib/loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /var/lib/loki/chunks

compactor:
  working_directory: /var/lib/loki/boltdb-shipper-compactor
  shared_store: filesystem
  retention_enabled: true

limits_config:
  retention_period: 1440h
  split_queries_by_interval: 0
  max_query_length: 0h
  max_query_series: 2000
  reject_old_samples: true
  reject_old_samples_max_age: 168h

query_scheduler:
  max_outstanding_requests_per_tenant: 1024

query_range:
  split_queries_by_interval: 0
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 1000

querier:
  max_concurrent: 12

chunk_store_config:
  max_look_back_period: 0s
  chunk_cache_config:
    embedded_cache:
      enabled: true
      max_size_mb: 500
      ttl: 24h

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

frontend:
  max_outstanding_per_tenant: 1024
  compress_responses: true

ruler:
  storage:
    type: local
    local:
      directory: /etc/loki/rules
  rule_path: /var/lib/loki/rules-temp
#  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
```
</details>

We're still using the old index/storage system, so I don't know whether the bug is here or not.

Best Regards,
Thomas
