### ISSUE TITLE
Container not found error for azure blob storage

### ISSUE THREAD

**Issue by vsawant1608** [grafana/loki#13151]
Getting below error

```
level=error ts=2024-06-06T09:35:20.615090549Z caller=flush.go:152 component=ingester org_id=self-monitoring msg="failed to flush" err="failed to flush chunks: store put chunk: write error: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /src/loki/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=ContainerNotFound) =====\nDescription=The specified container does not exist.\nRequestId:42610c73-a01e-0077-72f4-b7bf6a000000\nTime:2024-06-06T09:35:20.6148952Z, Details: \n   Code: ContainerNotFound\n   PUT https://azblobsre.blob.core.windows.net/chunks/self-monitoring/4d37258f6e0bf113/18fec310358-18fec9ef7c8-f5b1b911?blockid=t6DN1ZkkRqmW%2Fd654Y33ZwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%3D%3D&comp=block&timeout=31\n   Authorization: REDACTED\n   Content-Length: [59561]\n   User-Agent: [Azure-Storage/0.14 (go1.21.9; linux)]\n   X-Ms-Client-Request-Id: [bf8a6070-7051-4a30-5baf-aee8c18e7079]\n   X-Ms-Date: [Thu, 06 Jun 2024 09:35:20 GMT]\n   X-Ms-Version: [2020-04-08]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 404 The specified container does not exist.\n   Content-Length: [225]\n   Content-Type: [application/xml]\n   Date: [Thu, 06 Jun 2024 09:35:19 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [bf8a6070-7051-4a30-5baf-aee8c18e7079]\n   X-Ms-Error-Code: [ContainerNotFound]\n   X-Ms-Request-Id: [42610c73-a01e-0077-72f4-b7bf6a000000]\n   X-Ms-Version: [2020-04-08]\n\n\n, num_chunks: 1, labels: {pod=\"loki-canary-84vgr\", service_name=\"unknown_service\", stream=\"stdout\"}"
level=info ts=2024-06-06T09:35:28.961804375Z caller=table_manager.go:136 index-store=tsdb-2024-04-01 msg="uploading tables"

```

Steps to reproduce.
1) Installed loki helm chart with below values.yaml

```
    loki:
      schemaConfig:
        configs:
          - from: 2024-04-01
            store: tsdb
            object_store: azure
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      ingester:
        chunk_encoding: snappy
      tracing:
        enabled: true
      querier:
        max_concurrent: 4

      storage:
        type: azure
        azure:
          # Name of the Azure Blob Storage account
          accountName: azblobsre
          container_name: container
          # Key associated with the Azure Blob Storage account
          accountKey: accountkey
          # Comprehensive connection string for Azure Blob Storage account (Can be used to replace endpoint, accountName, and accountKey)
          connectionString: "validvalue;EndpointSuffix=core.windows.net"
          # Flag indicating whether to use Azure Managed Identity for authentication
          useManagedIdentity: false
          # Flag indicating whether to use a federated token for authentication
          useFederatedToken: false
          # Client ID of the user-assigned managed identity (if applicable)
          userAssignedId: "fffff-fff-470e-867d-d54603137ed3"
          # Timeout duration for requests made to the Azure Blob Storage account (in seconds)
          requestTimeout: 0
          # Domain suffix of the Azure Blob Storage service endpoint (e.g., core.windows.net)
          endpointSuffix: "core.windows.net"
        bucketNames:
          chunks: "chunks"
          ruler: "ruler"
          admin: "admin"

    deploymentMode: SimpleScalable

    backend:
      replicas: 2
    read:
      replicas: 2
    write:
      replicas: 2

    # Disable minio storage
    minio:
      enabled: false

    # Zero out replica counts of other deployment modes
    singleBinary:
      replicas: 0

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
    global:
      dnsNamespace: openshift-dns
      dnsService: dns-default
```
2. All pods are up and running.

Expected: It writes data successfully to azure blob storage.
