### ISSUE TITLE
failed parsing config: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by vsawant1608** [grafana/loki#13204]
I tried setting up loki with azure blob storage.

Have this in values.yaml

```
       azure:
          # Azure storage account name.
          account_name: "${azureaccountname}"
          container_name: "chunks"
          # Azure storage account key.
          account_key: "${azureaccountkey}"
          endpoint_suffix: "blob.core.windows.net"
          use_managed_identity: false
          use_federated_token: false

......


      compactor:
    enabled: true
    replicas: 1
    # affinity: {}   # causes a warning that affinity is a table
    nodeSelector: {}
    podAnnotations: {}
    podLabels: {}
    serviceLabels: {}
    extraArgs:
      - "-config.expand-env=true"
    # -- Environment variables to add to the ingester pods
    extraEnv: []
      # -- Environment variables from secrets or configmaps to add to the ingester pods
    extraEnvFrom:
      - secretRef:
          name: loki-azure-credentials
```

Loki azure credentials is a secret created like below

```
apiVersion: v1
kind: Secret
metadata:
  name: loki-azure-credentials
type: Opaque
stringData:
  azureaccountname: "aass"
  azureaccountkey: "dddfff"
```

compactor pods are failing with below error.

```
failed parsing config: /etc/loki/config/config.yaml: yaml: line 30: mapping values are not allowed in this context
```

Is there a way we can find out what exactly is causing the issue?

If I hardcode the values then it works.
