### ISSUE TITLE
structured_metadata is added as normal label

### ISSUE THREAD

**Issue by andres32168** [grafana/loki#13229]
**Describe the bug**
Enabling structured_metadata not working.
Following [documentation ](https://grafana.com/docs/loki/latest/send-data/promtail/stages/structured_metadata/#parse-from-service-discovery-labels)will lead to have high cardinality labels added to every log stream. 

**To Reproduce**
1. Add pipeline_stages to the snippets of the helm chart
```
  snippets:
    pipelineStages:
      - cri: {}
      - structured_metadata:
          pod: 
          pod_uid: 
          pod_host_ip:
```
2. Add labels to common section
```
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_uid
        target_label: pod_uid
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_host_ip
        target_label: pod_host_ip
```

**Expected behavior**
I expected to get structured_metadata for every logline with pod, pod_uid and pod_host_ip added.
But instead of this, those were added as normal labels which will cause high cardinality.

What I already tried:
```
  snippets:
    pipelineStages:
      - cri: {}
      - structured_metadata:
          pod: __meta_kubernetes_pod_name
          pod_uid: __meta_kubernetes_pod_uid
          pod_host_ip: __meta_kubernetes_pod_host_ip
```

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Loki Version: 3.0.0
 - Schema Version v13
 - Promtail Version 3.0.0

**Screenshots, Promtail config, or terminal output**
![loki_structured_metadata_label](https://github.com/grafana/loki/assets/115992806/d51eb96d-7c2f-41f4-bb53-8407e5ae4b27)
