### ISSUE TITLE
`promtail` stales in Windows

### ISSUE THREAD

**Issue by dilshaat** [grafana/loki#1324]
**Describe the bug**
I am testing promtail in `Windows  (10)`. After promtail is run, it does not show any error, but only two lines of information:

```bash
level=info ts=2019-11-27T05:17:05.8905522Z caller=server.go:121 http=[::]:9081 grpc=[::]:59730 msg="server listening on addresses"
level=info ts=2019-11-27T05:17:05.8905522Z caller=main.go:65 msg="Starting Promtail" version="(version=, branch=, revision=)"
``` 

And it doesn't send any log lines into `Loki`.

However, if I run `promtai` with the same `config file` in `Contos 7` and `log files` it works. I have just copied the log files and changed the path in `promtail config`. 
However, it is same Loki server listening on port 3100.

**To Reproduce**
1. Started Loki (1.0) `localhost:3100`
2. Started promtail: localhost: 9081(tried 9080 as well)
3. Started Promtail (1.0) to tail a `Log4j` log file located on my PC's drive (shown in config file)

**Expected behavior**
logs to be shipped to Loki. No action is present in Loki

**Environment:**
 - Infrastructure: [Laptop: Windows 10, VM: Centos 7]

**Screenshots, Promtail config, or terminal output**

The regex part may be wrong, that is another issue (if any advice give, very much appreciated), I have tried to uncomment `pipeline stages` as well, however, same issue is present.
```yaml
server:
  http_listen_port: 9081
  grpc_listen_port: 0

positions:
  filename: C:/Temp/positions.yaml

clients:
 - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
- job_name: aq
  entry_parser: raw
  pipeline_stages:
  - regex:
      expression: ^(?P<timestamp>\d{4}-\w{3}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) (?P<app>\w+) (?P<thread>\[\w+\])\s+(?P<level>\w+)\s+ (?P<msg>.*)$
  - timestamp:
      source: timestamp
      format: 2019-11-15 23:15:55.452
  static_config:
  - targets:
    - localhost
    lable:
      job: aqservice
      host: mypc
      __path__: D:/Vagrant/projects/MaaS\files/aservice.log

- job_name: etl
  entry_parser: raw
  pipeline_stages:
  - regex:
      expression: ^(?P<timestamp>\d{4}-\w{3}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) (?P<app>\w+) (?P<thread>\[\w+\])\s+(?P<level>\w+)\s+ (?P<msg>.*)$
  - timestamp:
      source: timestamp
      format: 2019-11-15 23:15:55.452
  static_config:
  - targets:
    - localhost
    lable:
      job: ETLService
      host: mypc
      __path__: D:/Vagrant/projects/MaaS/files/ETL.log

```
**Loki Config**
```yaml
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb
    object_store: filesystem
    schema: v9
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: c:\Temp\loki\index

  filesystem:
    directory: c:\Temp\loki\chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate: 100000
  ingestion_burst_size: 15000

```
