### ISSUE TITLE
 [loki-canary] Support passing loki user, password and tenant_id as environment variable.

### ISSUE THREAD

**Issue by Vinaum8** [grafana/loki#13290]
**Is your feature request related to a problem? Please describe.**
Issue with loki canary authentication.

**Describe the solution you'd like**
Add support for the following environment variables in the grafana/loki-canary container:

- LOKI_USERNAME: The username for authenticating with the Loki service.
- LOKI_PASSWORD: The password for authenticating with the Loki service.
- LOKI_TENANT_ID: The tenant ID for multi-tenant Loki instances.

**Additional context**
│ level=error msg="failed to send entry, server rejected push with a non-retryable status code" entry=1719190934246426338 status=401 err="server returned HTTP status 401 Unauthorized  │

**Comment by dgeorges** [comment]
I ran into the same thing. Loki can take the basic auth user/password as a command line argument see https://github.com/grafana/loki/blob/main/cmd/loki-canary/main.go#L55-L56. 

I am using the loki helm chart for deployment and was able to pass the credentials from a secret like this. 

```
lokiCanary:
  # Basic Auth Credentials for the Canary to send data to Loki
  extraArgs:
    - -pass=$(LOKI_PASS)
    - -user=grafana_loki_user
  extraEnv:
    - name: LOKI_PASS
      valueFrom:
        secretKeyRef:
          name: loki-canary-extras
          key: loki_pass
```

Not super obvious but it works.
