### ISSUE TITLE
promtail configure

### ISSUE THREAD

**Issue by the5dot45x39** [grafana/loki#1330]
Hello.

Please, help. I can not configure the correct parsing of logs in loki. I can't understand where error in my config file.

Log file exampe:

```
2019-11-28 17:52:17 #1024 (E_USER_NOTICE): #0 Misc message, include (,),.,/,_ and etc #END
2019-11-28 17:52:17 #1024 (E_USER_NOTICE): #0 2 misc message, include misc #END
```

Current configuration promtain.yaml file:

```
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug
clients:
  - url: http://10.0.0.1:4100/api/prom/push
positions:
  filename: /var/tmp/positions.yaml
scrape_configs:
  - job_name: php_errors_test
    entry_parser: raw
    pipeline_stages:
      - regex:
          expression: '(?P<data>\d{4,4}-\d{2,2}-\d{2,2}) (?P<time>\d{2,2}:\d{2,2}:\d{2,2}) (?P<message>[\s\S]*?(\#END))'
      - output:
          source: message
      - labels:
          data:
          time:
    static_configs:
      - targets: 
        - localhost
        labels:
          datatype: logs
          app: test
          __path__: /src/public/_tmp/php_errors.log
```

Now promtail just picks up the lines, assigning them static label from "static_config" (datatype, app), without parsing the log lines and labes (data, time)
