### ISSUE TITLE
Custom timestamp format example

### ISSUE THREAD

**Issue by Dilidonka** [grafana/loki#1334]
Can you please give an example, how to set custom format for the log ? How to make reference to the values ? 
Thank you!
> The syntax used by the custom format defines the reference date and time using specific values for each component of the timestamp (i.e., Mon Jan 2 15:04:05 -0700 MST 2006). The following table shows supported reference values which should be used in the custom format.

**Comment by pstibrany** [comment]
Here is one example, from Grafana issue https://github.com/grafana/grafana/issues/20511:

```
clients:
  - url: http://localhost:3100/loki/api/v1/push

positions:
  filename: /tmp/20511-positions.yml

scrape_configs:
  - job_name: testing

    static_configs:
      - targets:
          - localhost

        labels:
          __path__: /tmp/random.log

    pipeline_stages:
      - json:
          expressions:
            message:
            timestamp:

      - timestamp:
          source: timestamp
          format: 2006-01-02T15:04:05.000000Z

      - output:
          source: message
```

Associated log file:

```
{ "timestamp": "2019-11-21T02:15:00.123456Z", "message": "DEBUG message"}
{ "timestamp": "2019-11-21T03:15:00.123456Z", "message": "WARNING message"}
{ "timestamp": "2019-11-21T04:15:00.123456Z", "message": "ERROR message"}
```
