### ISSUE TITLE
failed to get token ranges for ingester err="zone not set"

### ISSUE THREAD

**Issue by Assaf1928** [grafana/loki#13414]
After last version update (3.1) I get the next error:
level=error ts=2024-07-04T12:19:47.79081202Z caller=recalculate_owned_streams.go:55 msg="failed to get token ranges for ingester" err="zone not set"

this is my config-yml file:

After last version update (3.1) I get the next error:
level=error ts=2024-07-04T12:19:47.79081202Z caller=recalculate_owned_streams.go:55 msg="failed to get token ranges for ingester" err="zone not set"

this is my config-yml file:

```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100



limits_config:
  retention_period: 720h

schema_config:
  configs:
    - from: 2021-08-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
    
# # chunk_store_config:
# #   max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

ruler:
  alertmanager_url: http://localhost:9093

 ingester:
   lifecycler:
     ring:
       kvstore:
         store: inmemory
       replication_factor: 1
     join_after: 30s
     final_sleep: 0s
   wal:
     enabled: true
     dir: /loki/wal

distributor:
  ring:
    kvstore:
      store: inmemory


compactor:
  working_directory: /loki/compactor

```

**Comment by instantdreams** [comment]
Had the same issue after a container update yesterday.

Checked my `loki.yaml` file and tried again today - and the image had been updated. New version does not have the issue. My Loki instance is now back up again.

**Comment by crazyelectron-io** [comment]
New install of 3.1 gives me the same error
```
caller=recalculate_owned_streams.go:55 msg="failed to get token ranges for ingester" err="zone not set"
```

**Comment by ondrejmo** [comment]
I had the same issue with Loki 3.1.0 and the following configuration file:

```yaml
---

auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

common:
  replication_factor: 1
  path_prefix: /loki
    
  storage:
    filesystem:
      chunks_directory: /loki/chunks

  ring:
    # instance_availability_zone: zone
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-05-28
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  retention_enabled: true
  retention_delete_delay: 2h
  delete_request_cancel_period: 24h
  delete_request_store: s3

ruler:
  enable_api: true
  enable_alertmanager_v2: true

  alertmanager_url: http://alertmanager.monitoring.svc:9093

  remote_write:
    enabled: true
    client:
      url: http://prometheus.monitoring.svc:9090/api/v1/write

  storage:
    type: s3
    s3:
      endpoint: minio.cloud.svc:9000
      s3forcepathstyle: true
      bucketnames: loki
      insecure: true
      access_key_id: ${S3_USER}
      secret_access_key: ${S3_PASS}
   
  wal:
    dir: /loki/ruler_wal

limits_config:
  retention_period: 720h
  max_query_length: 721h
  max_entries_limit_per_query: 1000000
  ingestion_rate_mb: 8 # MB, default is 4
  ingestion_burst_size_mb: 12 # MB, default is 6
  split_queries_by_interval: 15m
  unordered_writes: true
  retention_stream: []
  shard_streams:
    enabled: false
  volume_enabled: true
  discover_service_name: [ topic ]
  discover_log_levels: true

query_range:
  align_queries_with_step: true
  cache_results: true

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

frontend:
  max_outstanding_per_tenant: 2048

analytics:
  reporting_enabled: false

ingester:
  max_chunk_age: 8h
  chunk_idle_period: 4h

pattern_ingester:
   enabled: true

storage_config:
 tsdb_shipper:
   active_index_directory: /loki/index
   cache_location: /loki/index_cache
 aws:
   s3: s3://${S3_USER}:${S3_PASS}@minio.cloud.svc:9000/loki
   s3forcepathstyle: true
```

However, when I un-comment the `instance_availability_zone: zone` line the error changes to `"can't use ring configuration for computing token ranges")`, which is defined in https://github.com/joe-elliott/dskit/blob/0e1c99b54ea7ef89ad80fa32cb2751cc0dbf5c32/ring/token_range.go#L77C26-L77C84

**Comment by KAllan357** [comment]
I ran into this yesterday and gave up looking and went back to 3.0.0. I was using a fresh install of the latest Helm chart.

**Comment by cboggs** [comment]
I'm hitting this with all 3.1 configurations I can think to try. Seems [this](https://github.com/grafana/loki/commit/e7689b248dbe549b2ac61a0e335d8b5b999cc47d) commit introduced `recalculate_owned_streams.go`. At a glance, it seems this is invoked no matter what the configuration is (aside from, presumably, singlebinary), and it doesn't properly pick up the RF and/or zone awareness fields.

Rolled back to 3.0.0 to get things online, but would love to be able to upgrade. :-)

**Comment by Hitesh-Agrawal** [comment]
I see the same error for 3.1.0 , but the whole loki stack is working as expected. What is the cause of this error.

**Comment by zeyneprumeysayorulmaz** [comment]
I'm having the same problem. Can anyone solve the problem?
 Chart version: 6.10.0
 Chart Name: loki
 Loki version: 3.1.1

**Comment by Starefossen** [comment]
Same error here with latest version of the official loki chart.

**Comment by kristeey** [comment]
experiencing the same error without zone awareness replication of ingesters for 
Chart version: 6.12.0
Chart Name: loki
`caller=recalculate_owned_streams.go:55 msg="failed to get token ranges for ingester" err="can't use ring configuration for computing token ranges"`
Downgraded for now. Is there any updates on this?

**Comment by pikeas** [comment]
Same here, running single binary with filesystem storage and replication=1, so IIUC there are no zones in this configuration.

**Comment by lesaux** [comment]
I'm running the distributed-loki helm chart with image tag 3.2.1 and it seems setting `zone_awareness_enabled: false`  in the `common.ring` configuration gets rid of the error in ingester logs, but grafana still displays "An error occured within the plugin" when I browse to the logs explorer, and it logs
``` client: failed to call resources: empty ring```

If pattern_ingester is disabled then I have no errors.

**Comment by alexinfoblox** [comment]
https://github.com/grafana/loki/issues/14847

**Comment by Praveenk8051** [comment]
Im getting the same error with 3.0.0 version.. Is it normal ?

**Comment by pbozzoli** [comment]
I'm getting same error trying with latest version:

level=error ts=2025-01-10T07:52:05.242016583Z caller=recalculate_owned_streams.go:55 msg="failed to get token ranges for ingester" err="zone not set"

With version 3.0.0 this error doesn't appear

**Comment by hellomaxgemeinhardt** [comment]
has anyone solved it? getting the same one on :latest

**Comment by Praveenk8051** [comment]
this doesn't occur with 2.9 version

**Comment by darkobas2** [comment]
well if you add:
```
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: calico-kube-controllers
  namespace: kube-system
rules:
  # Calico creates some tiers on startup.
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - tiers
    verbs:
      - create
```
it should go away... but now it just spams that its already present

```
2025-02-14 18:38:54.151 [INFO][1] kube-controllers/client.go 414: Tier default already exists. error=resource already exists: Tier(default)
2025-02-14 18:38:54.158 [INFO][1] kube-controllers/client.go 414: Tier adminnetworkpolicy already exists. error=resource already exists: Tier(adminnetworkpolicy)
```
