### ISSUE TITLE
Setting resource requests/limits for loki-canary in helm chart does not apply for canary-pods

### ISSUE THREAD

**Issue by t0a5tbr0t** [grafana/loki#13425]
**Describe the bug**
I tried to set the values for loki-canarys resource requests and limits. Unfortunately they are not applied to the relevant pods of the canary daemonset.

**To Reproduce**
1. Deploy the loki helm chart
2. Set the values for loki-canary as follows:

```
  lokiCanary:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        cpu: 20m
        memory: 100Mi
  write:
    resources:
      ...
```

**Expected behavior**
The defined resource requests and limits are applied to the pods of the loki-canary daemonset.
As implied above, the identically defined resource values for other pods (like loki-write) were applied as expected.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Screenshot from the values and live manifest in ArgoCD:
loki-canary (not working):
![image](https://github.com/grafana/loki/assets/165992174/1678b8f2-7960-4e74-b463-ad722bb99209)
![image](https://github.com/grafana/loki/assets/165992174/89ae9531-35e9-4533-8e25-98d4509769ca)

loki-write (is working - just for reference):
![image](https://github.com/grafana/loki/assets/165992174/63dc1bf3-793b-4cbb-a953-2f567088772e)
![image](https://github.com/grafana/loki/assets/165992174/1a2adcbf-e042-49f0-81ab-b354dda0f819)

Thank you for your support!
