### ISSUE TITLE
DynamoDB invalid configuration

### ISSUE THREAD

**Issue by mr-karan** [grafana/loki#1345]
**Describe the bug**
Looks like the config provided over [here](https://github.com/grafana/loki/blob/master/docs/configuration/examples.md#aws) `DynamoDB` is wrong. There's no `dynamodb.url` value mentioned, but while starting Loki in clustered mode, all the components related to storage backend complain about:

```sh
level=error ts=redacted caller=main.go:65 msg="error initialising loki" err="error initialising module: store: error creating index client: Must set -dynamodb.url in aws mode"
```

The `dynamodb.url` is no where mentioned in docs and I even checked the code. I am guessing the store module initializing is coming from Cortex, which [does](https://github.com/cortexproject/cortex/blob/78e0607b405eba31c151d34d333de201f76a9c33/docs/aws-specific.md#dynamodb-capacity-provisioning) have the `dynamodb.url` flag. 

Are the docs correct?

**To Reproduce**
1. Relevant config snipped:

```yml
schema_config:
    configs:
    - from: "2019-10-01"
    index:
        period: 168h
        prefix: loki
    object_store: s3
    schema: v9
    store: aws
storage_config:
    aws:
      s3: s3://redacted:redacted@ap-south-1/redacted
      dynamodbconfig:
        dynamodb: dynamodb://redacted:redacted@ap-south-1
```
2. Deployed Loki in K8s cluster, taking inspiration from the setup [here](https://github.com/grafana/loki/tree/master/production/ksonnet) 
3. `kubectl get pods -n loki`  

**Expected behavior**
Ingestor, Querier and Table-Manager shouldn't `CrashLoopBackOff`

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: kubectl apply

**Screenshots, Promtail config, or terminal output**

![gg](https://user-images.githubusercontent.com/5689132/69912681-b84ab900-1452-11ea-90c3-b3c58ff25cfe.png)
