### ISSUE TITLE
goimports and local package

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1348]
As per the discussions on the PR : https://github.com/grafana/loki/pull/1249#discussion_r352297031

It seems that we want to order local package as last together.

golangci-lint seems to support this.

```yaml
 goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/org/project
```

Do we all agree that we want this ? /cc @pstibrany @rfratto @sh0rez @slim-bean @joe-elliott @pracucci @gouthamve @owen-d (AKA are you able to configure your IDE accordingly ?)
