### ISSUE TITLE
cannot start when using Loki as query-fronted

### ISSUE THREAD

**Issue by JC-paavo** [grafana/loki#13526]
loki Version: 3.1.0
config.yaml:
```
auth_enabled: false
target: query-frontend
http_prefix:
server:
  http_listen_port: 3100
query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
    - embedded_cache:
        enabled: true
        max_size_mb: 100
        ttl: 24h
limits_config:
  max_cache_freshness_per_query: '10m'
  split_queries_by_interval: 15m
frontend:
  log_queries_longer_than: 5s
  downstream_url: http://loki-headless.svc.cluster.local:3100
  compress_responses: true
```
Run Command: ./loki -config.file=config.yaml
Error:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/grafana/loki/v3/pkg/loki.validateSchemaRequirements(0xc000bf0008)
        /src/loki/pkg/loki/validation.go:32 +0x712
github.com/grafana/loki/v3/pkg/loki.(*Config).Validate(0xc000bf0008)
        /src/loki/pkg/loki/loki.go:288 +0x12b2
main.main()
        /src/loki/cmd/loki/main.go:69 +0x637
```

**Comment by JStickler** [comment]
Have you seen [this comment](https://github.com/grafana/loki/issues/12971#issuecomment-2189760991)?

**Comment by JC-paavo** [comment]
I operated according to this [document](https://grafana.com/docs/loki/latest/configure/examples/query-frontend/), which seems misleading

Modified to this configuration to run：
```
auth_enabled: false
target: query-frontend
http_prefix: /loki
common:
  compactor_address: http://127.0.0.1:3100
compactor:
  retention_enabled: false
  working_directory: /tmp/retnetion
server:
  http_listen_port: 3100
schema_config:
  configs:
    - from: "2024-07-14"
      index:
        period: 24h
        prefix: index_
      schema: v13
      object_store: s3
      store: tsdb
storage_config:
  tsdb_shipper:
    active_index_directory: /data/loki/tsdb_shipper_index
    cache_location: /data/loki/tsdb_shipper_index_cache
    cache_ttl: 24
  aws:
    s3forcepathstyle: true
    s3: http://ak:sk@minio.paas.svc.cluster.local:9000/loki-log
query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100
        ttl: 24h
limits_config:
  max_cache_freshness_per_query: '10m'
  split_queries_by_interval: 15m
```
