### ISSUE TITLE
Enabling bloom increase CPU by a lot on pod restart

### ISSUE THREAD

**Issue by QuentinBisson** [grafana/loki#13571]
**Describe the bug**

We run Loki using the helm chart in SSD mode and when I enable bloom compactor, the CPU spikes a lot (we are usually using less than 100m) when the backend pods starts. The CPU shot up to 1 full CPU which is the current cpu limit set on the backend pod.

It would be fine if it happend only once but this happens everytime pods with bloom enabled are restarted (rollout of a config change, new loki image and so on).

I think this could be related to the bloom_tokenizer component because the tokens are recreated on every restart while usual compaction runs fine.

Would it make sense to store them somewhere (whether on disk or s3) to not have to recreate thos n-grams all the time?

Original community slack thread https://grafana.slack.com/archives/CEPJRLQNL/p1721251526999089

**To Reproduce**
1. Started Loki 3.0.0 or 3.1.0 using the helm chart in ssd mode with the following values:

```
      loki:
	structuredConfig:
          bloom_compactor:
            enabled: true
            retention:
              enabled: true
              max_lookback_days: 30
          bloom_gateway:
            enabled: true
            client:
              addresses: dns+loki-backend-headless.loki.svc.cluster.local:9095
        limits_config:
          bloom_gateway_enable_filtering: true
          bloom_compactor_enable_compaction: true
```

I tried to play with worker_parallelism but this gets worse :D

**Expected behavior**

CPU should only spike once or ideally not spike at all when creating n-grams

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool:  helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
