### ISSUE TITLE
Loki not retaining logs more than 5 mins

### ISSUE THREAD

**Issue by anandecemptc** [grafana/loki#1362]
I have deployed the loki tool on my kebernetes cluster using helm, i used following commands to create deployments 

```bash
helm install loki/loki-stack -n loki-stack \                   
  --set fluent-bit.enabled=true,promtail.enabled=true,loki.persistence.enabled=true,loki.persistence.size=25Gi,loki.config.table_manager.retention_deletes_enabled=true,loki.config.table_manager.retention_period=120h \
  --namespace=logging
```

I am able to create a deployment without any issues and able to create datasources and pointed to loki service.

Loki explorer displayed the logs for each deployments, after some time i couldn't see the older logs on the Grafana UI.
But I given the data retention for 5 days , I can see only for 5 mins of logs for container.

You can see my configuration: 

```yaml
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
  - from: "2018-04-15"
    index:
      period: 168h
      prefix: index_
    object_store: filesystem
    schema: v9
    store: boltdb
server:
  http_listen_port: 3100
storage_config:
  boltdb:
    directory: /data/loki/index
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: true
  retention_period: 120h
```

![Untitled](https://user-images.githubusercontent.com/15903560/70147698-d0c50880-16ca-11ea-9a5f-c78d0f371a65.png)
