### ISSUE TITLE
Loki mixin: dashboard job selectors don't match loki deployed via helm chart when using provided servicemonitor

### ISSUE THREAD

**Issue by jmichalek132** [grafana/loki#13631]
**Describe the bug**
Job label selectors used in dashboards from loki mixin (https://github.com/grafana/loki/blob/main/production/loki-mixin/dashboards/loki-writes.libsonnet#L21) don't match the job label value on loki, when running it in the distributed mode using the helm chart from loki repo in combination with enabling the service monitor for scraping metrics.

The job label selector snippet from one of the dashboards.
```jsonnet
distributor: if $._config.meta_monitoring.enabled
then [utils.selector.re('job', '($namespace)/(distributor|%s-write|loki-single-binary)' % $._config.ssd.pod_prefix_matcher)]
else [utils.selector.re('job', '($namespace)/%s' % (if $._config.ssd.enabled then '%s-write' % $._config.ssd.pod_prefix_matcher else 'distributor'))],
```
ends up producing `job=~"(loki)/distributor"` label selector. but in our case the actual value of the labels is ` job="loki/loki-distributor"` not matching the label selector.
This is due to the service monitor:
````yaml
    path: /metrics
    port: http-metrics
    relabelings:
    - action: replace
      replacement: loki/$1
      sourceLabels:
      - job
      targetLabel: job
````
The `loki/` part is added using relabeling, and the `loki-distributor` is the name of the service.

**To Reproduce**
1. Started Loki 3.0.0, helm chart version 6.6.0
2. Enable service monitor 
3. Deploy dashboards from the mixin

**Expected behavior**
Dashboards present in loki mixin would work out of box with loki in the distributed mode deployed using the helm chart.

**Environment:**
 - Infrastructure: k8s v1.28.3
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by jmichalek132** [comment]
So for now I went with a workaround which got at least some of the panels working which is adding a relabaling rule to service monitor in the helm chart, to make the job label match what the dashboards expect.

```yaml
monitoring:
  serviceMonitor:
    enabled: true
    interval: 60s
    relabelings:
      - action: replace
        replacement: loki/$1
        regex: loki/loki-(.*)
        sourceLabels:
        - job
        targetLabel: job
```
