### ISSUE TITLE
Helm chart for for Writer pod does not reflect number of replicas

### ISSUE THREAD

**Issue by washeeeq** [grafana/loki#13701]
**Describe the bug**
When loki is deployed on Kubernetes modifying number of replicas setting:
- backend to 1
- writer to 1
- reader to 1
created linked PVC(s) are all in line except writer.
This ends having one pod of writer and 3 PVCS writer0/1/2 plus also custom size is ignored.
Config:
```
# Configuration for the write pod(s) 
  write:
    persistence:
      volumeClaimsEnabled: true
      enabled: true
      size: 5Gi
      storageClass: "standard"
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-nodepool: pool-infra
  # --  Configuration for the read pod(s)
  read:
    persistence:
      volumeClaimsEnabled: true
      enabled: true
      size: 5Gi
      storageClass: "standard"
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-nodepool: pool-infra
  # --  Configuration for the backend pod(s)
  backend:
    persistence:
      volumeClaimsEnabled: true
      enabled: true
      size: 5Gi
      storageClass: "standard"
    replicas: 1
    nodeSelector:
      cloud.google.com/gke-nodepool: pool-infra
```
**To Reproduce**
1. Started Loki  - version: 6.7.3
2. Started Promtail - no promtail at the moment
3. Query: `{} term`

**Expected behavior**
Number of replicas = number of PVC(s) and other configuration is accepted.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
![loki_write](https://github.com/user-attachments/assets/4f753071-7b70-4bd5-acc4-9d0897ec0c15)
