### ISSUE TITLE
Resources for `memcached` cannot be configured

### ISSUE THREAD

**Issue by StefanKock** [grafana/loki#13755]
**Describe the bug**
Resources for `memcached` are ignored.

Probably a coding error in https://github.com/grafana/loki/blob/helm-loki-6.7.4/production/helm/loki/templates/memcached/_memcached-statefulset.tpl#L93

Maybe fixing it with ` {{- if $.ctx.Values.memcached.resources }}`?

**To Reproduce**
1. Add the following paragraph to the Helm values:
```yaml
memcached:
  image:
# Setting pullPolicy works
    pullPolicy: Always
# Setting resources does not work
  resources:
    limits:
      memory: 10Gi
    requests:
      cpu: 500m
      memory: 1Gi
```
2. Template helm values: `helm template grafana/loki -f my-values.loki.yaml --version 6.7.4`
3. Started Promtail (SHA or version) to tail '...'
4. See in the templated result that `resources` are not applied:
```yaml
---
# Source: loki/templates/chunks-cache/statefulset-chunks-cache.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-loki-chunks-cache
  labels:
    helm.sh/chart: loki-6.7.4
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: "memcached-chunks-cache"
    name: "memcached-chunks-cache"
  annotations:
    {}
spec:
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: "memcached-chunks-cache"
      name: "memcached-chunks-cache"
  updateStrategy:
    type: RollingUpdate
  serviceName: release-name-loki-chunks-cache

  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: "memcached-chunks-cache"
        name: "memcached-chunks-cache"
      annotations:
    spec:
# /../
      containers:
        - name: memcached
          image: memcached:1.6.23-alpine
          imagePullPolicy: Always
          resources:
            limits:
              memory: 9830Mi
            requests:
              cpu: 500m
              memory: 9830Mi
# /../
```

**Expected behavior**
memcached resources block can be overridden.
```yaml
# /../
      containers:
        - name: memcached
          resources:
            limits:
              memory: 10Gi
            requests:
              cpu: 500m
              memory: 1Gi
# /../
```

**Environment:**
 - Infrastructure:Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by rknightion** [comment]
In newer versions of the chart I thought you had to configure the resources in chunksCache/resultsCache sections (setting those there is working okay for us in SSD mode). the memcached section is for image related settings I think. 

```

        memcached:
          image:
            repository: library/memcached
        resultsCache:
          # -- Specifies whether memcached based results-cache should be enabled
          enabled: true
          # -- Specify how long cached results should be stored in the results-cache before being expired
          defaultValidity: 12h
          # -- Memcached operation timeout
          timeout: 2000ms
          # -- Total number of results-cache replicas
          replicas: 3
          # -- Port of the results-cache service
          port: 11211
          # -- Amount of memory allocated to results-cache for object storage (in MB).
          allocatedMemory: 1024
          # -- Maximum item results-cache for memcached (in MB).
          maxItemMemory: 5
          # -- Maximum number of connections allowed
          connectionLimit: 16384
          # -- Max memory to use for cache write back
          writebackSizeLimit: 500MB
          # -- Max number of objects to use for cache write back
          writebackBuffer: 500000
          tolerations:
            - operator: Equal
              key: arch
              value: arm64
              effect: NoSchedule
          nodeSelector:
            popzone: 1c
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
          extraExtendedOptions: "modern"

        chunksCache:
          # -- Specifies whether memcached based chunks-cache should be enabled
          enabled: true
          # -- Batchsize for sending and receiving chunks from chunks cache
          batchSize: 4
          # -- Parallel threads for sending and receiving chunks from chunks cache
          parallelism: 5
          # -- Memcached operation timeout
          timeout: 10000ms
          # -- Specify how long cached chunks should be stored in the chunks-cache before being expired
          defaultValidity: 0s
          # -- Total number of chunks-cache replicas
          replicas: 12
          # -- Port of the chunks-cache service
          port: 11211
          # -- Amount of memory allocated to chunks-cache for object storage (in MB).
          allocatedMemory: 12288
          # -- Maximum item memory for chunks-cache (in MB).
          maxItemMemory: 5
          # -- Maximum number of connections allowed
          connectionLimit: 16384
          # -- Max memory to use for cache write back
          writebackSizeLimit: 500MB
          # -- Max number of objects to use for cache write back
          writebackBuffer: 500000
          # -- Number of parallel threads for cache write back
          writebackParallelism: 1
          tolerations:
            - operator: Equal
              key: arch
              value: arm64
              effect: NoSchedule
          nodeSelector:
            popzone: 1c
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
          extraExtendedOptions: "-L"
```

**Comment by hongbo-miao** [comment]
Having same question. This `results-cache` pod has two containers `memcached` and `exporter`

This does not work:

```yaml
resultsCache:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
```

Further check https://github.com/grafana/loki/blob/6532b4b263deea4581699a076f244c2c818f5e8c/production/helm/loki/values.yaml#L3215-L3217

The memory is calculated based on `allocatedMemory` which is why got that weird number `11000000000`.

However, I am still not sure how to set the rest of

- `memcached` CPU resource limit
- `exporter` CPU and memory resource limit

![Image](https://github.com/user-attachments/assets/4c7da7b3-5049-4649-ab13-5dd7eebfc2c8)

**Comment by hongbo-miao** [comment]
Having same question. This `results-cache` pod has two containers `memcached` and `exporter`.

By default, I have

![Image](https://github.com/user-attachments/assets/917af81e-9b8e-40b3-8b9e-c66b6b9ee73c)

This is because https://github.com/grafana/loki/blob/6532b4b263deea4581699a076f244c2c818f5e8c/production/helm/loki/values.yaml#L3215-L3217

The memory is calculated based on `allocatedMemory` which is why got that weird number `11000000000`.

If I set

```yaml
resultsCache:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
```

I can see

![Image](https://github.com/user-attachments/assets/c3ff2c0e-115a-4bb8-a7af-6ee1da0755e5)

`memcached` container in `results-cache` pod, the resource limit has been applied. 

However, I am still not sure how to set the rest of `exporter` container CPU and memory resource limit.

**Comment by hongbo-miao** [comment]
This `results-cache` pod has two containers `memcached` and `exporter`.

I succeed setting resource limit for `memcached` container, but not not `exporter`, I posted more info at https://community.grafana.com/t/how-to-set-resource-limit-for-exporter-container-in-the-results-cache-pod/141271

Hopefully it helps at least for `memcached` container resource limit ☺️

**Comment by hongbo-miao** [comment]
This `results-cache` pod has two containers `memcached` and `exporter`.

I succeed setting resource limit for `memcached` and `exporter` after some help. I posted more info at https://community.grafana.com/t/how-to-set-resource-limit-for-exporter-container-in-the-results-cache-pod/141271

Hopefully it helps! ☺️

**Comment by BertelBB** [comment]
> This `results-cache` pod has two containers `memcached` and `exporter`.
> 
> I succeed setting resource limit for `memcached` and `exporter` after some help. I posted more info at https://community.grafana.com/t/how-to-set-resource-limit-for-exporter-container-in-the-results-cache-pod/141271
> 
> Hopefully it helps! ☺️

It helps, but it is a one-size-fits-all. AFAICT, the `results-cache` requires much less memory than the `chunks-cache` and neither of these tools rely on CPU to operate, yet they have 500m vCPU allocated because it is hardcoded...

**Comment by StefanKock** [comment]
Thx to @hongbo-miao I succeeded to configure the `memcached-chunks-cache` (`image: memcached`) with `chunksCache` in the values.yaml.

```
chunksCache:
  resources:
    limits:
      memory: 6Gi
    requests:
      cpu: 500m
      memory: 5Gi

# sibling can be configured similarly
resultsCache:
```

So, I have a solution for my problem.
