### ISSUE TITLE
helm: incorrect service selector in the case of the SingleBinary mode

### ISSUE THREAD

**Issue by yskopets** [grafana/loki#13752]
**Describe the bug**
`loki-headless` k8s Service generated by the `loki` Helm chart in the case of the SingleBinary mode selects both Loki and Loki Canary pods, which is incorrect.

The Service should select ONLY Loki pods.

**To Reproduce**
1. Install Loki in the SingleBinary mode using `loki` Helm chart + enable Loki Canary
2. Inspect selector of the `loki-headless` k8s Service
   ```shell
   kubectl get svc loki-headless -n loki -oyaml
   ``` 
   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: loki-headless
     namespace: loki
   spec:
     selector:
       app.kubernetes.io/instance: loki
       app.kubernetes.io/name: loki
    ```
3. List Pods matching that selector
   ```shell
   kubectl get pods -n loki -l app.kubernetes.io/instance=loki,app.kubernetes.io/name=loki
   ``` 
   ```
   NAME                READY   STATUS    RESTARTS   AGE
   loki-0              1/1     Running   0          45h
   loki-canary-rq8dr   1/1     Running   0          47h
   loki-canary-t5c28   1/1     Running   0          47h
   ```
   Apparently, `loki-headless` k8s Service selects both Loki pods and Loki Canary pods, which is incorrect.

**Expected behavior**
`loki-headless` k8s Service should select ONLY Loki pods.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Mode: SIngleBinary + Loki Canary enabled

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
