### ISSUE TITLE
migrating from local filesystem to s3 fails with migration tool 

### ISSUE THREAD

**Issue by mehransaeed7810** [grafana/loki#13797]
Whilst running the below cmd for migration, it doesnt recognize the s3 in the dest-config. Not sure if I am using it in right way. 

```bash
`migrate -source.config.file=source-config.yaml -dest.config.file=dest-config.yaml -source.tenant=fake -dest.tenant=default -from=2023-06-16T14:00:00-00:00 -to=2024-07-01T00:00:00-00:00`

line 2: field s3 not found in type storage.Config. Use `-config.expand-env=true` flag if you want to expand environment variables in your config file
```

I used both loki's configs as source and dest config but it didn't like it, then I tried doing this way. 

```bash
#source-config.file

#source-config.yaml
storage_config:
  filesystem:
    directory: /test/chunks/fake


#dest-config.file

storage_config:
  s3:
    bucketnames: default   # The name of the bucket where data will be stored
    endpoint: http://10.1.0.10:12345/   # The endpoint for MinIO
    access_key_id: enterprise-logs   #  MinIO access key
    secret_access_key: secret   #  MinIO secret key
    insecure: true   # Set to false if using HTTPS, true otherwise

```

My questions are
1.  is it the right config to use in the source and dest config. 

2.Also I am using MinIO as S3 so folder structure is different there compared to local filesystem. 
filesystem: chunks/fake 
S3: chunks/default (where default is the bucket name and tenant-id)

So shall I be using default as tenant-id in the migrate cmd.

**Comment by rgroothuijsen** [comment]
Specifying the actual source/destination configurations should work because the migration tool reads and writes data to storage in the same way as a regular Loki instance, although aside from that in this case the validation error specifically notes that `s3` is not a field of `storage_config`. The source and destination configs could be, for example:

```
# Source instance configuration

common:
  path_prefix: "/"

schema_config:
  configs:
    - from: 2020-10-01
      store: tsdb
      schema: v13
      object_store: filesystem
      index:
        period: 24h
        prefix: index_

storage_config:
  filesystem:
    directory: /test/chunks
```

```
# Destination instance configuration

common:
  path_prefix: "/"

schema_config:
  configs:
    - from: 2020-10-01
      store: tsdb
      schema: v13
      object_store: aws
      index:
        period: 24h
        prefix: index_

storage_config:
  aws:
    bucketnames: default
    endpoint: http://10.1.0.10:12345/
    access_key_id: enterprise-logs
    secret_access_key: secret
    insecure: true
```

The tenant IDs to specify are the same as the ones you're actually using at your source/destination, so that would be `default` for your destination instance.
