### ISSUE TITLE
promtail cannot send log to loki server with error 401 Unauthorized message

### ISSUE THREAD

**Issue by alochym01** [grafana/loki#1386]
i just play with loki

when i run promtail with log.level=debug and get 
"caller=client.go:231 component=client host=127.0.0.1:3100 msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
"

please help

thank you

my loki.yaml
```yaml
auth_enable: false

server:
    http_listen_address: 0.0.0.0
    http_listen_port: 3100

ingester:
    lifecycler:
        address: 0.0.0.0
        ring:
            kvstore:
                store: inmemory
            replication_factor: 1
        final_sleep: 0s
    chunk_idle_period: 5m
    chunk_retain_period: 30s

schema_config:
    configs:
        -   from: 2018-04-15
            store: boltdb
            object_store: filesystem
            schema: v9
            index:
                prefix: index_
                period: 168h

storage_config:
    boltdb:
        directory: /home/hadn/loki/config/index
    filesystem:
        directory: /home/hadn/loki/config/chunks

limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h

chunk_store_config:
    max_look_back_period: 0
```
my promtail.yaml
```yaml
server:
    http_listen_address: 192.168.56.104
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
    filename: /home/hadn/loki/config/positions.yaml

client:
    url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
    -   job_name: alochym
        pipeline_stages:
            -   match:
                    selector: '{name="nginx"} |= "GET"'
                    stages:
                        -   regex:
                                expression: \w{1,3}.\w{1,3}.\w{1,3}.\w{1,3}(?P<output>.*)
                        -   output:
                                source: output
        static_configs:
        -   targets:
                -   localhost
            labels:
                job: nginx
                env: dev
                host: 192.168.56.104
                __path__: /var/log/nginx/*.log
```
