### ISSUE TITLE
Helm chart defines Loki config as an object instead of a string

### ISSUE THREAD

**Issue by chancez** [grafana/loki#1392]
**Describe the bug**
- Currently the Loki configuration is defined as an object https://github.com/grafana/loki/blob/master/production/helm/loki/values.yaml#L21
- Being a dictionary, this makes it difficult or impossible to override some default values. For example, nested dictionaries, you can set the individual fields to `null`, but this results in the defaults in the chart values.yaml being used, not unsetting them. This makes it difficult or impossible to use any application defaults rather than chart defaults. Not only this, but with nested dictionaries, you also get multiple unnecessary sections being defined. If I use consul for my ring configuration, the existing `kvstore` defaults in the values.yaml are still there.

**To Reproduce**

- Store the following into a `loki-values.yaml`

```
loki:
  enabled: true

  config:
    ingester:
      chunk_idle_period: null
      chunk_block_size: null
      chunk_retain_period: null
      lifecycler:
        ring:
          store: consul
          replication_factor: 1
          consul:
            host: "consul:8500"
            prefix: ""
            httpclienttimeout: "20s"
```

- use `helm template` to template the file we want to look at (`faq` is just `jq` for more file types):

```
helm2 template production/helm/loki-stack -x charts/loki/templates/secret.yaml -f loki-values.yaml | faq -fyaml '.data["loki.yaml"] | @base64d' -rM
```
Here's the output:

```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      consul:
        consistentreads: true
        host: consul:8500
        httpclienttimeout: 20s
        prefix: ""
      kvstore:
        store: inmemory
      replication_factor: 1
      store: consul
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
  - from: "2018-04-15"
    index:
      period: 168h
      prefix: index_
    object_store: filesystem
    schema: v9
    store: boltdb
server:
  http_listen_port: 3100
storage_config:
  boltdb:
    directory: /data/loki/index
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: false
  retention_period: 0
```

Notice that chunk_block_size and chunk_idle_period are still set, even though I actually want to just leave it unset for Loki's application defaults, and also notice `lifecycler.ring.kvstore` is set even though I just want to use consul. In theory, if Loki did better validation on mutually exclusive options, it may even error with the config created.

**Expected behavior**
I would expect only the content of my configuration file to be used. I don't want the merging behavior. If the config field was used as a string, rather than a dictionary, it would work this way.

For example, if instead of the following https://github.com/grafana/loki/blob/master/production/helm/loki/values.yaml#L21:
```
config:
  auth_enabled: false
...
```

it could be:
```
config: |
  auth_enabled: false
...
```

Currently the only reason I see it's not done this way is so that within `production/helm/loki/templates/statefulset.yaml` it can use `http_listen_port`, but that can be fixed also:

Change 
```
              containerPort: {{ .Values.config.server.http_listen_port }}
```

To
```
              containerPort: {{ (.Values.config | fromYaml ).server.http_listen_port }}
```

And in the config, you need to make sure the option is set (and any other options):

```
  config: |
    server:
      http_listen_port: 3100
```
