### ISSUE TITLE
Promtail regex is breaking previous multiline

### ISSUE THREAD

**Issue by alanwech** [grafana/loki#14016]
Bug description:
I'm trying to parse camunda logs that come out of a supervisor using the following settings:
```
      - cri: {}
      ...
      - match:
          selector: '{app=~"ow-camunda.*", container!="failure-sidecar"}'
          stages:
            - multiline:
                firstline: '^\d{2}-\w{3}-\d{4} \d{2}:\d{2}:\d{2}.\d{3}'
            - regex:
                expression: '(?i).*(?P<level>severe|info|critical|debug|debg|fine|finest|trace|verbose|error|warn|warning)( |:)[\S\s]*$'
            - labels:
                level:
```

The logs look like this:
30-Aug-2024 15:29:25.981 INFO [http-nio-8080-exec-8] net.iquall.camunda.plugin.ProcessInstanceListenerPlugin$preInit$1.parseProcess Registering Listener for process ow_l9j-x2n-scn
30-Aug-2024 15:29:25.982 SEVERE [http-nio-8080-exec-8] org.camunda.commons.logging.BaseLogger.logError ENGINE-16004 Exception while closing command context: ENGINE-09005 Could not parse BPMN process. Errors: 
\* multiple none start events or timer start events not supported on process definition | resource ow_l9j-x2n-scn.bpmn | line 11 | column 57
\* multiple none start events or timer start events not supported on process definition | resource ow_l9j-x2n-scn.bpmn | line 11 | column 57
		at org.camunda.bpm.engine.impl.util.EngineUtilLogger.exceptionDuringParsing(EngineUtilLogger.java:66)

When I only use the multiline stage, it works as expected, but the moment I add that regex it stops working (only the multiline, the regex works fine).
WITHOUT REGEX:
![Image](https://github.com/user-attachments/assets/955e41cb-2dc0-4741-aebb-3443b89e7328)

WITH REGEX:
![Image](https://github.com/user-attachments/assets/d5b58afd-1fa0-4c21-84df-0f740360ccf4)

Camunda logs are coming from a kubernetes pod named ow-camunda-env.
