### ISSUE TITLE
Unable to get Loki to start using S3

### ISSUE THREAD

**Issue by witchbutter** [grafana/loki#1402]
**Describe the bug**
Specifying S3 as an object store Loki fails to start with this error message:
```
level=info ts=2019-12-11T22:52:20.878473926Z caller=aws_autoscaling.go:136 msg="enabling autoscaling on table" table=(MISSING)
level=error ts=2019-12-11T22:52:21.364893479Z caller=table_manager.go:179 msg="error syncing tables" err="InvalidParameter: 1 validation error(s) found.\n- minimum field size of 1, RegisterScalableTargetInput.RoleARN.\n"
```

**To Reproduce**
1. Started Loki v1.0.0, v1.1.0 or v1.2.0 with this config assuming you have done all your IAM work ahead of time in the docs:
```
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 1

schema_config:
  configs:
    - from: 2019-11-01
      store: aws
      object_store: s3
      schema: v10
      # How many shards will be created. Only used if schema is v10.
      row_shards: 16
      index:
        prefix: loki-dev-
        period: 168h

storage_config:
  aws:
    s3: https://s3.us-east-2.amazonaws.com/some-loki-bucket
    #s3forcepathstyle: false
    dynamodbconfig:
      dynamodb: dynamodb://us-east-2
      # No idea if the following performance settings are good
      # DynamoDB table management requests per-second limit.
      apilimit: 2.0
      # DynamoDB rate cap to back off when throttled.
      throttlelimit: 10.0
      # Application Autoscaling endpoint URL with escaped Key and Secret encoded.
      applicationautoscaling: "https://application-autoscaling.us-east-2.amazonaws.com"
      # Number of chunks to group together to parallelise fetches (0 to disable)
      chunkgangsize: 10
      # Max number of chunk get operations to start in parallel.
      chunkgetmaxparallelism: 32

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  # Master 'off-switch' for table capacity updates, e.g. when troubleshooting
  throughput_updates_disabled: false
  retention_deletes_enabled: true
  retention_period: 672h
  index_tables_provisioning:
    # Selects Dynamo usage units on instantiation
    inactive_read_throughput: 30
    inactive_write_throughput: 1
    provisioned_write_throughput: 300
    provisioned_read_throughput: 30
    write_scale:
      enabled: true
      # DynamoDB minimum provision capacity.
      min_capacity: 10
      # DynamoDB maximum provision capacity.
      max_capacity: 1000
      # DynamoDB minimum seconds between each autoscale up.
      out_cooldown: 1800
      # DynamoDB minimum seconds between each autoscale down.
      in_cooldown: 1800
      # DynamoDB target ratio of consumed capacity to provisioned capacity.
      target: 80
    inactive_write_scale:
      enabled: true
      # DynamoDB minimum provision capacity.
      min_capacity: 1
      # DynamoDB maximum provision capacity.
      max_capacity: 10
      # DynamoDB minimum seconds between each autoscale up.
      out_cooldown: 900
      # DynamoDB minimum seconds between each autoscale down.
      in_cooldown: 1800
      # DynamoDB target ratio of consumed capacity to provisioned capacity.
      target: 90
    # Number of last inactive tables to enable write autoscale.
    inactive_write_scale_lastn: 1
    read_scale:
      enabled: true
      min_capacity: 10
      # DynamoDB maximum provision capacity.
      max_capacity: 1000
      # DynamoDB minimum seconds between each autoscale up.
      out_cooldown: 1800
      # DynamoDB minimum seconds between each autoscale down.
      in_cooldown: 1800
      # DynamoDB target ratio of consumed capacity to provisioned capacity.
      target: 80
    inactive_read_scale:
      enabled: true
      # DynamoDB minimum provision capacity.
      min_capacity: 10
      # DynamoDB maximum provision capacity.
      max_capacity: 1000
      # DynamoDB minimum seconds between each autoscale up.
      out_cooldown: 900
      # DynamoDB minimum seconds between each autoscale down.
      in_cooldown: 1800
      # DynamoDB target ratio of consumed capacity to provisioned capacity.
      target: 80
    # Number of last inactive tables to enable read autoscale.
    inactive_read_scale_lastn: 2
```

**Expected behavior**
For Loki to start cleanly.  I have not pointed any promtails to it yet so it has no data to write.  I expect that may be related to the validation error.

**Environment:**
 This all in EKS where I have enabled IAM roles to service accounts following this guide: https://docs.aws.amazon.com/en_pv/eks/latest/userguide/iam-roles-for-service-accounts.html
I should point out though that the issue is definitely not permissions.  Dynamo is working as expected.  I have the node role enabling everything required in the docs via this policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "LokiS3",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:ListBucket",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::some-loki-bucket/*",
                "arn:aws:s3:::some-loki-bucket"
            ]
        },
        {
            "Sid": "LokiDynamo",
            "Effect": "Allow",
            "Action": [
                "dynamodb:UpdateTable",
                "dynamodb:UpdateItem",
                "dynamodb:UntagResource",
                "dynamodb:TagResource",
                "dynamodb:Query",
                "dynamodb:PutItem",
                "dynamodb:ListTagsOfResource",
                "dynamodb:ListTables",
                "dynamodb:GetItem",
                "dynamodb:DescribeTable",
                "dynamodb:DeleteTable",
                "dynamodb:CreateTable",
                "dynamodb:BatchWriteItem",
                "dynamodb:BatchGetItem"
            ],
            "Resource": "arn:aws:dynamodb:us-east-2:XXXXXXXXXXXX:table/loki-dev-*"
        },
        {
            "Sid": "LokiDynamoAutoScale",
            "Effect": "Allow",
            "Action": [
                "dynamodb:ListTables",
                "application-autoscaling:RegisterScalableTarget",
                "application-autoscaling:PutScalingPolicy",
                "application-autoscaling:DescribeScalingPolicies",
                "application-autoscaling:DescribeScalableTargets"
            ],
            "Resource": "*"
        },
        {
            "Sid": "LokiDynamoUseRoleARN",
            "Effect": "Allow",
            "Action": [
                "iam:PassRole",
                "iam:GetRole"
            ],
            "Resource": "arn:aws:iam::XXXXXXXXXXXX:role/loki-service-account"
        }
    ]
}
```
