### ISSUE TITLE
HPA for Loki-indexer in a failed state when zoneAwareReplication is set to enabled

### ISSUE THREAD

**Issue by sepulworld** [grafana/loki#14021]
**Describe the bug**
HPA for Loki-indexer in a failed state when  zoneAwareReplication is set to enabled

**To Reproduce**

* add HPA for indexer

```
ingester:
  zoneAwareReplication:
    enabled: true
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 15
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
```

```
kubectl describe hpa loki-ingester -n monitoring

---snip---
  Warning  FailedGetScale  30s (x6119 over 25h)  horizontal-pod-autoscaler  statefulsets.apps "loki-ingester" not found

```

There is no loki-ingester statefulset. There are instead the 3 zone aware statefulsets.

**Expected behavior**

expect to see HPA working with the zone aware statefulsets.

**Environment:**
 - Infrastructure: Kubernettes 
 - Deployment tool: helm
