### ISSUE TITLE
Invalid Config with log_level on server config

### ISSUE THREAD

**Issue by bozzelliandrea** [grafana/loki#14031]
Hi, I'm trying to set the debug level for loki inside a docker container, but the container failed the startup and the error message is this one:
level=error caller=main.go:56 msg="validating config" err="invalid schema config: must specify at least one schema configuration"

I'm configuring the yaml as written in the documentation: https://grafana.com/docs/loki/latest/configure/#server

**To Reproduce**
1. configure a docker container with the `grafana/loki:main-4e17ad8` image
2. set the log level as config yaml
```yaml
server:
  log_level: "error"
```
3. mount the container with the yaml config (compose example)
```yaml
loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - "./loki/config.yaml:/etc/config.yaml"
    command: ["-config.file=/etc/config.yaml"]
```

**Expected behavior**
container logs with the config level

**Environment:**
laptop - docker
