### ISSUE TITLE
Make affinity block optional

### ISSUE THREAD

**Issue by adrianmiron** [grafana/loki#14066]
**Is your feature request related to a problem? Please describe.**

I would like to be able to disable the affinity block, but i am unable to because of the way the yaml template is written atm

```
{{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

**Describe the solution you'd like**
Add a conditional block

```
{{- if .Values.backend.affinity }}
{{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
```

This way i can set this and it will actually work `affinity: {}`

**Describe alternatives you've considered**
Right now i am forced to do something like this, which is silly:

```
affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: randomvalue123
            topologyKey: kubernetes.io/hostname
```
**Additional context**
