### ISSUE TITLE
Gateway HPA used a deprecated autoscalling API

### ISSUE THREAD

**Issue by dev-ago** [grafana/loki#14077]
**Describe the bug**

When deploying the Helm chart `loki-simple-scalable` version 1.8.11 by Grafana, the deployment fails due to the usage of the `autoscaling/v2beta1` API, which is no longer supported in Kubernetes version 1.30.3. The specific error is related to the `HorizontalPodAutoscaler` resource in the `hpa.yaml` file, which still references `autoscaling/v2beta1`.

**To Reproduce**
1. Started Loki (version 1.8.11)
2. Used Promtail with the same version to tail logs.
3. Executed the Helm chart for deployment on Kubernetes v1.30.3.

**Error Output**
STDERR:
  ```
  Error: Failed to render chart: exit status 1: 
  Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "loki-gateway" namespace: "" from "":
  no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"
  ensure CRDs are installed first
  Error: plugin "diff" exited with error
  ```

**Expected behavior**
The `HorizontalPodAutoscaler` should use a supported API version (`autoscaling/v2` or later) for Kubernetes v1.30.3. The `autoscaling/v2beta1` API was deprecated in Kubernetes v1.26, as mentioned in the [Kubernetes deprecation guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v126).

**Environment:**
 - Infrastructure: [e.g., Kubernetes v1.30.3]
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Relevant portion of `hpa.yaml`:
```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "loki.gatewayFullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "loki.gatewayFullname" . }}
  minReplicas: {{ .Values.gateway.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.gateway.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.gateway.autoscaling.targetCPUUtilizationPercentage }}
```

The issue is that `apiVersion: autoscaling/v2beta1` is still used instead of the `apiVersion: autoscaling/v2`
