### ISSUE TITLE
Loki network policy interfaring with traffic in same namespace

### ISSUE THREAD

**Issue by Starefossen** [grafana/loki#14091]
**Describe the bug**

Enabling network policies for the loki helm chart messes with network policies for other pods in the namespace due to the `loki-namespace-only` network policy:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: loki-namespace-only
  namespace: nais-system
spec:
  egress:
  - to:
    - podSelector: {}
  ingress:
  - from:
    - podSelector: {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

**To Reproduce**

1. Install latest version of the loki helm chart with `--set networkPolicy.enabled=true`
2. If you have other pods in the same namespace these will be affected by the network policy deployed by loki

In our case network traffic to load balancers in the same namespace stopped working completely.

**Expected behavior**

I expect the helm chart not to interfere with traffic from other services unless it explicitly says so.

**Environment:**
 - Infrastructure: GKE
 - Deployment tool: helm
