### ISSUE TITLE
An error occurred while starting Loki via Docker

### ISSUE THREAD

**Issue by rea1shane** [grafana/loki#14116]
Log:

```
mkdir : no such file or directory
error creating index client
github.com/grafana/loki/pkg/storage.(*store).storeForPeriod
	/src/loki/pkg/storage/store.go:295
github.com/grafana/loki/pkg/storage.(*store).init
	/src/loki/pkg/storage/store.go:177
github.com/grafana/loki/pkg/storage.NewStore
	/src/loki/pkg/storage/store.go:155
github.com/grafana/loki/pkg/loki.(*Loki).initStore
	/src/loki/pkg/loki/modules.go:690
github.com/grafana/dskit/modules.(*Manager).initModule
	/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:136
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
	/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/loki/pkg/loki.(*Loki).Run
	/src/loki/pkg/loki/loki.go:461
main.main
	/src/loki/cmd/loki/main.go:110
runtime.main
	/usr/local/go/src/runtime/proc.go:271
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1222
error initialising module: store
github.com/grafana/dskit/modules.(*Manager).initModule
	/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
	/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/loki/pkg/loki.(*Loki).Run
	/src/loki/pkg/loki/loki.go:461
main.main
	/src/loki/cmd/loki/main.go:110
runtime.main
	/usr/local/go/src/runtime/proc.go:271
runtime.goexit
	/usr/local/go/src/runtime/asm_arm64.s:1222
level=warn ts=2024-09-11T10:37:02.478846853Z caller=loki.go:288 msg="global timeout not configured, using default engine timeout (\"5m0s\"). This behavior will change in the next major to always use the default global timeout (\"5m\")."
level=info ts=2024-09-11T10:37:02.480291407Z caller=main.go:108 msg="Starting Loki" version="(version=2.9.10, branch=HEAD, revision=7664eda07b)"
level=info ts=2024-09-11T10:37:02.480714733Z caller=server.go:322 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2024-09-11T10:37:02.48315583Z caller=memberlist_client.go:434 msg="Using memberlist cluster label and node name" cluster_label= node=7e49bdccc1cd-98987ca4
level=info ts=2024-09-11T10:37:02.483990849Z caller=memberlist_client.go:540 msg="memberlist fast-join starting" nodes_found=1 to_join=4
level=warn ts=2024-09-11T10:37:02.484180226Z caller=cache.go:127 msg="fifocache config is deprecated. use embedded-cache instead"
level=warn ts=2024-09-11T10:37:02.484193986Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache - chunksembedded-cache"
level=error ts=2024-09-11T10:37:02.484976928Z caller=log.go:230 msg="error running loki" err="mkdir : no such file or directory\nerror creating index client\ngithub.com/grafana/loki/pkg/storage.(*store).storeForPeriod\n\t/src/loki/pkg/storage/store.go:295\ngithub.com/grafana/loki/pkg/storage.(*store).init\n\t/src/loki/pkg/storage/store.go:177\ngithub.com/grafana/loki/pkg/storage.NewStore\n\t/src/loki/pkg/storage/store.go:155\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:690\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:136\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:461\nmain.main\n\t/src/loki/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1222\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:461\nmain.main\n\t/src/loki/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1222"
```

Part of `docker-compose.yaml`:

```yaml
services:
  loki:
    container_name: loki
    image: grafana/loki
    command:
      - -config.file=/etc/loki/config.yaml
      - -ruler.storage.type=local
      - -ruler.storage.local.directory=/etc/loki/rules
    volumes:
      - ./resources/loki:/etc/loki
      - ./data/loki:/loki
    ports:
      - 3100:3100
```

`./resources/loki/config.yaml`:

```yaml
auth_enabled: false

memberlist:
  join_members:
    - loki:7946

schema_config:
  configs:
    - from: 2024-08-01
      store: boltdb-shipper
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  aws:
    s3: s3://monitoring:monitoring@minio.:9000/loki
    s3forcepathstyle: true

ruler:
  alertmanager_url: http://alertmanager:9093
  enable_alertmanager_v2: true
  enable_api: true
  remote_write:
    enabled: true
    client:
      url: http://prometheus:9090/api/v1/write
```

Loki image is latest, id: `ed8bd92c2f07`.
