### ISSUE TITLE
Helm chart values YAML should quote date

### ISSUE THREAD

**Issue by whatnick** [grafana/loki#14126]
**Describe the bug**
The documented values in for Helm use an unquoted string as date. Some deployment tooling such as flux can roundtrip this into an ISO formatted string which Loki cannot parse from the config.

Mitigation would be quote the string in the sample YAML values or Loki config parser modified to support ISO time.

**To Reproduce**
1. Deploy Loki using stock values on cluster running flux Gitops using a Helm Release resource.

**Expected behavior**
Chart deploys and Loki pods start

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: helm + flux

**Screenshots, Promtail config, or terminal output**
```bash
failed parsing config: /etc/loki/config/config.yaml: parsing time "2024-04-01T00:00:00Z": extra text: "T00:00:00Z". Use -config.expand-env=true flag if you want to expand environment variables in your file
```

**Comment by thatMacAdmin** [comment]
I was also affected by this bug. It took me a couple days to figure out why. The documentation should be corrected.

**Comment by robertlemke** [comment]
As a hint to anyone experiencing this, make sure to put the date in schemaConfig into quotes:

```yaml
  values:
    loki:
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
```
