### ISSUE TITLE
Some log data not showing.

### ISSUE THREAD

**Issue by wangjinxiang0522** [grafana/loki#14122]
**Describe the bug**
The log query results are incomplete, with some log data not showing.

My test scenario involves outputting from 0 to 9999. However, when my query condition is "getLogDemon," the numbers from 8995 to 8999 do not show up. Yet, when I query 8996 separately, it displays correctly.

```
  |   | 2024-09-12 14:39:31.946 | 2024-09-12 06:39:31.935 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      9007 |  
  |   | 2024-09-12 14:39:31.946 | 2024-09-12 06:39:31.930 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      9006 |  
  |   | 2024-09-12 14:39:31.946 | 2024-09-12 06:39:31.924 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      9005 |  
  |   | 2024-09-12 14:39:31.946 | 2024-09-12 06:39:31.919 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      9004 |  
  |   | 2024-09-12 14:39:31.946 | 2024-09-12 06:39:31.914 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      9003 |  
  |   | 2024-09-12 14:39:31.946 | 2024-09-12 06:39:31.908 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      9002 |  
  |   | 2024-09-12 14:39:31.946 | 2024-09-12 06:39:31.902 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      9001 |  
  |   | 2024-09-12 14:39:31.946 | 2024-09-12 06:39:31.897 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      9000 |  
  |   | 2024-09-12 14:39:31.945 | 2024-09-12 06:39:31.865 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      8994 |  
  |   | 2024-09-12 14:39:31.945 | 2024-09-12 06:39:31.859 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      8993 |  
  |   | 2024-09-12 14:39:31.945 | 2024-09-12 06:39:31.854 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      8992 |  
  |   | 2024-09-12 14:39:31.945 | 2024-09-12 06:39:31.848 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      8991 |  
  |   | 2024-09-12 14:39:31.945 | 2024-09-12 06:39:31.842 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      8990


``` 

When I query 8996 separately, it displays correctly.
```

2024-09-12 14:39:31.946 | 2024-09-12 06:39:31.876 [http-nio-18091-exec-2] INFO  com.example.demofronted.controller.TempoController Line:47  getLogDemon      8996


``` 

**To Reproduce**
1. Started Loki (2.9.10)
2. Started opentelemetry collector filelog 

**Expected behavior**
The data from 0 to 9999 can be displayed normally.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm, jsonnet

**Screenshots, Promtail config, or terminal output**
```
global:
  dnsService: "kube-dns"

loki:
  server:
    http_listen_port: 3100
    grpc_server_max_recv_msg_size: 1572864000
    grpc_server_max_send_msg_size: 1572864000

  config: |
    auth_enabled: false
    server:
      {{- toYaml .Values.loki.server | nindent 6 }}
    
    common:
      compactor_address: http://{{ include "loki.compactorFullname" . }}:3100

    distributor:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist

    ingester_client:
      grpc_client_config:
        grpc_compression: gzip

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
   
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0
    
      autoforget_unhealthy: true 
      max_chunk_age: 2h
      chunk_idle_period: 1h
      chunk_target_size: 1572864
      flush_op_timeout: 10m
    
      wal:
        dir: /var/loki/wal

    limits_config:
      max_query_parallelism: 256
      tsdb_max_query_parallelism: 512    
      enforce_metric_name: false
      reject_old_samples: false
      reject_old_samples_max_age: 12h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 10m
      per_stream_rate_limit: 5GB
      per_stream_rate_limit_burst: 3GB
      ingestion_rate_mb: 10240
      ingestion_burst_size_mb: 20480

    schema_config:
    {{- toYaml .Values.loki.schemaConfig | nindent 2}}



    storage_config:
    {{- toYaml .Values.loki.storageConfig | nindent 2}}
    
    
    query_range:
      align_queries_with_step: true
      max_retries: 5
      cache_results: true
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            ttl: 24h


    frontend_worker:
      {{- if .Values.queryScheduler.enabled }}
      scheduler_address: {{ include "loki.querySchedulerFullname" . }}:9095
      {{- else }}
      frontend_address: {{ include "loki.queryFrontendFullname" . }}-headless:9095
      {{- end }}    

    
    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      {{- if .Values.queryScheduler.enabled }}
      scheduler_address: {{ include "loki.querySchedulerFullname" . }}:9095
      {{- end }}
      tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100    


    compactor:
      retention_enabled: true
      shared_store: s3
      working_directory: /var/loki/compactor




  schemaConfig:
    configs:
      - from: "2020-09-07"
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: loki_index_
          period: 24h

  storageConfig:
    aws:
      endpoint: 110.22.13.136:9000
      insecure: true
      bucketnames: k8s-loki11
      access_key_id: minioad23232min
      secret_access_key: min23ioad1mian
      s3forcepathstyle: true
    boltdb_shipper:
      shared_store: s3
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 24h


# Configuration for the ingester
ingester:
  kind: StatefulSet
  nodeSelector:
    node-type: monitoring
  replicas: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  affinity: {}


distributor:
  replicas: 1
  nodeSelector:
    node-type: monitoring
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  affinity: {}


querier:
  replicas: 1
  maxUnavailable: 1
  nodeSelector:
    node-type: monitoring
  affinity: {}
  max_outstanding_per_tenant: 4096

queryFrontend:
  maxUnavailable: 1
  affinity: {}
  replicas: 2
  nodeSelector:
    node-type: monitoring

gateway:
  enabled: true
  replicas: 1
  nodeSelector:
    node-type: monitoring

compactor:
  kind: StatefulSet
  replicas: 1
  enabled: true
  nodeSelector:
    node-type: monitoring


queryScheduler:
  enabled: true
  replicas: 1
  affinity: {}
  nodeSelector:
    node-type: monitoring
  max_outstanding_requests_per_tenant: 4096


serviceMonitor:
  enabled: false
  namespace: monitoring
  labels:
    release: prometheus





```
