### ISSUE TITLE
Loki gateway cannot be scraped by prometheus when basicAuth is enabled

### ISSUE THREAD

**Issue by adippl** [grafana/loki#14141]
**Describe the bug**
Prometheus cannot collect logs from loki-gateway when authentication is enabled.

**To Reproduce**
1. Install loki 6.10.0 from helm
2. Enable monitoring and basicAuth
```
gateway:
  enabled: true
  basicAuth:
    enabled: true
monitoring:
  dashboards:
    enabled: true
  rules:
    enabled: true
    labels:
      prometheus: main    
  serviceMonitor:
    enabled: true
    labels:
      prometheus: main
```

3. Prometheus servicemonitor is created but prometheus cannot scrape gateway because of authorization. Error 401
![Image](https://github.com/user-attachments/assets/bd9c8ed3-8b6d-4b02-8acd-d0738d92aa97)

**Expected behavior**
Servicemonitor should configure prometheus to use some authorization or gateway should be scraped via some non authenticated port.

**Environment:**
 - Infrastructure: Kubernetes, kvm virtual machines
 - Deployment tool: argocd
