### ISSUE TITLE
Promtail helm chart: Unable to configure several clients

### ISSUE THREAD

**Issue by eugene100** [grafana/loki#1428]
**Describe the bug**
I want to push logs to some loki servers by promtail. I used `clients:` parameter. Eg
```yaml
config:
  clients:
    - url: http://loki:3100/loki/api/v1/push
      backoff_config:
        maxbackoff: 5s
        maxretries: 20
        minbackoff: 100ms
      batchsize: 102400
      batchwait: 1s
      timeout: 10s
      # Set label for k8s cluster identification
      external_labels:
        kubernetes_cluster: eugene-poc
        loki_host: loki
    - url: http://loki2:3100/loki/api/v1/push
      backoff_config:
        maxbackoff: 5s
        maxretries: 20
        minbackoff: 100ms
      batchsize: 102400
      batchwait: 1s
      timeout: 10s
      external_labels:
        kubernetes_cluster: eugene-poc
        loki_host: loki2

  server:
    http_listen_port: 3101
  positions:
    filename: /run/promtail/positions.yaml
  target_config:
    sync_period: 10s
```
My configuration doesn't work. My `configs` section is ignored. I got:
```
level=warn ts=2019-12-16T10:50:17.032711992Z caller=client.go:226 component=client host=loki-promtail:3100 msg="error sending batch, will retry" status=-1 error="Post http://loki-promtail:3100/loki/api/v1/push: dial tcp: lookup loki-promtail on 10.23.240.10:53: no such host"
```
Cause `client.url` specified as command line argument in [daemonset template](https://github.com/grafana/loki/blob/master/production/helm/promtail/templates/daemonset.yaml#L47-L51) overlap `configs` section. If I remove lines from template all working as expacted.

**To Reproduce**
1. Install first instamce of loki:
```bash
$ helm upgrade --install --namespace loki loki loki/loki
```
2.  Install second instamce of loki:
```bash
$ helm upgrade --install --namespace loki loki2 loki/loki
```
Create values file `promtail-config.yaml`(specified above)
3. Install promtail
```bash
$ helm upgrade --install promtail loki/promtail -f promtail-config.yaml
```

**Expected behavior**
Logs should be screped and pushed to `loki` and `loki2` hosts.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
