### ISSUE TITLE
Promtail inspect doesn't appear like in the documentation

### ISSUE THREAD

**Issue by embcla** [grafana/loki#14310]
**Describe the bug**
The documentation ([web link](https://grafana.com/docs/loki/latest/send-data/promtail/troubleshooting/#inspecting-pipeline-stages), [github link](https://github.com/grafana/loki/blob/main/docs/sources/send-data/promtail/troubleshooting/_index.md)) shows a nice color coded command line output with very detailed output for each pipeline stage
![Image](https://github.com/user-attachments/assets/70ae8b02-37e3-4b50-9e7d-fd729403cbe9)

With my current binary of v.3.2.0
```
promtail, version 3.2.0 (branch: k218, revision: 659f5421)
  build user:       root@003ce357cdf4
  build date:       2024-09-18T16:21:52Z
  go version:       go1.22.6
  platform:         linux/amd64
  tags:             promtail_journal_enabled
```

This does not happen, see this example
![Image](https://github.com/user-attachments/assets/b73e4187-de41-4541-ae7e-79a3b8d055d2)

**To Reproduce**
- Install promtail v3.2.0
- pipe logfile into it (`head file.txt | promtail --inspect --config.file=./promtail/promtail-config.yaml --stdin --dry-run --tracing.enabled`)
- observe output, having or not having the `--inspect` flag makes no difference to the output

**Expected behavior**
I would expect to see detailed tracing output for each pipeline stage defined in the configuration

**Environment:**
 - Ubuntu 22.04 WSL under Win11

**Promtail config**
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # - job_name: system
  #   static_configs:
  #     - targets:
  #       - localhost
  #       labels:
  #         job: varlogs
  #         __path__: /var/log/*log
  - job_name: DIAG-455
    pipeline_stages:
    # timestamp extraction
    - match:
        selector: '{name="logfile"}'
        stages:
        - regex:
            expression: '^(?P<time>[A-Za-z]{3} [0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2})'
        - labels:
            time:
        - template:
            source: time
            template: '{{ Replace .Value "," "." 1 }}'
        - timestamp:
            source: time
            format: 'Sep 30 13:45:27'
            location: "UTC"
    # stationID extraction
    - match:
        selector: '{name="logfile"}'
        stages:
        - regex:
            expression: '^.*(?P<field>bla123)'
        - labels:
            field:
        # - template:
        #     source: 
        #     template: '{{ Replace .Value "," "." 1 }}'

    - match:
        selector: '{name="logfile"}'
        stages:
        - regex:
            expression: '^.*kern.info'
        - labels:
            kernel_info:
        # - template:
        #     source: 
        #     template: '{{ Replace .Value "," "." 1 }}'  

    static_configs:
      - targets:
        - localhost
        labels:
          job: logfile
          __path__: /mnt/logfile.txt
   

```
