### ISSUE TITLE
Log lines seemingly dropped from Lines channel in promtail

### ISSUE THREAD

**Issue by liam-howe-maersk** [grafana/loki#14366]
**Describe the bug**
We have noticed that an application, which we use promtail to scrape its logs, is missing log lines. This was noticed because the application increments a counter on every HTTP request and also logs a log line and the count of these 2 did not add up. We can consistently reproduce this behaviour, every time we run a load test against this application we will see the same pattern, the number of HTTP requests from the test matches the number that is visualised by the prometheus counter but the number of log lines is always less than expected.

After debugging the code and building a custom promtail image we can see that all the expected log lines are sent to this [channel tail.Lines](https://github.com/grafana/loki/blob/v3.1.1/vendor/github.com/grafana/tail/tail.go#L507), however, it seems that not all of these lines are being received [here](https://github.com/grafana/loki/blob/v3.1.1/clients/pkg/promtail/targets/file/tailer.go#L162). It might be relevant to note that each log line is somewhere between 2KB-2.5KB.

**To Reproduce**
1. Deployed promtail as a DaemonSet to a kubernetes cluster (config below)
2. Deployed an application Deployment to the same kubernetes cluster
3. Execute a load test against the application that makes several thousand HTTP requests to the application over 2 minutes
4. Get the number of HTTP requests made as represented by a prometheus counter and by a count of log lines, the count of log lines is always less than expected.

**Expected behavior**
All lines sent to the `tail.Lines` channel should be received and processed at the other end

**Environment:**
 - Infrastructure: Kubernetes on Azure Kubernetes Service
 - Deployment tool: Promtail deployed as a DaemonSet through k8s yamls

**Screenshots, Promtail config, or terminal output**

<details>
  <summary>Click here for Promtail config</summary>
 
  ```yaml
  server:
    log_level: debug
    log_format: logfmt
    http_listen_port: 3101
  
  clients:
    - url: http://loki-instance/loki/api/v1/push
      oauth2:
        client_id: ${OAUTH2_CLIENT_ID}
        client_secret: ${OAUTH2_CLIENT_SECRET}
        token_url: https://login.microsoftonline.com/.../oauth2/v2.0/token
        scopes:
          - "scope.default"
      external_labels:
        k8s_cluster: my-cluster
        env: prod
        provider: azure
      backoff_config:
        min_period: 1s
        max_period: 2m
        max_retries: 10
  
  positions:
    filename: /run/promtail/positions.yaml
  
  scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - app-namespace
              - platform-monitoring
      pipeline_stages:
        - cri: {}
        - labeldrop:
            - filename
            - stream
            - level
      relabel_configs:
        - source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_name
          regex: (app-namespace.+|platform-monitoring;promtail-liam-test-logs.+)
          action: keep
        - source_labels:
            - __meta_kubernetes_pod_controller_name
          regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
          action: replace
          target_label: __tmp_controller_name
        - source_labels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_name
            - __meta_kubernetes_pod_label_app
            - __tmp_controller_name
            - __meta_kubernetes_namespace
          regex: ^;*([^;]+)(;.*)?$
          action: replace
          target_label: app
        - source_labels:
            - __meta_kubernetes_pod_label_app_kubernetes_io_component
            - __meta_kubernetes_pod_label_component
          regex: ^;*([^;]+)(;.*)?$
          action: replace
          target_label: component
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_node_name
          target_label: node_name
        - action: replace
          source_labels:
            - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: container
        - action: replace
          replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
          target_label: __path__
        - action: replace
          regex: true/(.*)
          replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
            - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
            - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
            - __meta_kubernetes_pod_container_name
          target_label: __path__
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_label_env
            - __meta_kubernetes_pod_label_environment
          regex: ^;*([^;]+)(;.*)?$
          target_label: env
  
  tracing:
    enabled: false

  ```
</details>

Hopefully the below screenshot can help to explain what we are seeing

![Image](https://github.com/user-attachments/assets/56afc55c-0882-4ac1-a110-b06a0db93d66)

In the above image the **blue line** shows the count of HTTP requests according to the counter metric, we expect this to be the true count of HTTP requests.

The **yellow line** represents every log line, for an application HTTP request, that was sent down the [tail.Lines channel](https://github.com/grafana/loki/blob/v3.1.1/vendor/github.com/grafana/tail/tail.go#L507), to determine this a log line was added in promtail before sending a log line down this channel that included the HTTP request log line.

The **orange line** represents every log line that included the HTTP request log line that was received on the other end of the channel [here](https://github.com/grafana/loki/blob/v3.1.1/clients/pkg/promtail/targets/file/tailer.go#L162), this was determined by adding a counter to the code that was incremented whenever a log line was received from the channel that included the HTTP request log line. As you can see this orange line is much lower than the yellow line, if every line that was sent down the channel was being received we would expect these to be equal, but they are not.

Finally the **green line** represents the count of HTTP log lines that we eventually see from the application in Grafana that were sent by promtail, which lines up roughly with the count of such log lines received from the other end of the channel.

It isn't shown above to allow for a clearer image but none of the lines ever increment after this.
