### ISSUE TITLE
Rentention based "loki_compactor_apply_retention_last_successful_run_timestamp_seconds" metrics are giving 0 but Retention is working in loki-compactor

### ISSUE THREAD

**Issue by rajattamoli** [grafana/loki#14370]
Hi, 

My loki-compactor deployment on nonprod is working fine but on the production, it is facing an issue with metrics of compactor. loki_compactor_apply_retention_last_successful_run_timestamp_seconds metric are not generating also some loki_compactor based metrics are not coming.

**QUE: why the compactor `active_retention` metrics are 0, but we confirmed that the deletions actually happen in the S3 bucket.**
 
```
compactor:
      compaction_interval: 10m
      delete_request_cancel_period: 24h
      retention_enabled: true
      retention_delete_delay: 2h
      delete_request_store: s3
```
