### ISSUE TITLE
Rentention based "loki_compactor" metrics are giving 0 or not coming but Retention is working in loki-compactor

### ISSUE THREAD

**Issue by rajattamoli** [grafana/loki#14388]
**Describe the bug**
 The loki-compactor active_retention metrics are 0 are some of them are missing, but we confirmed that the deletions actually happen in the S3 bucket.

**To Reproduce**
1. Started Loki 3.1.1
2. scrape metrics from loki compactor service
3. metrics are missing 
4. example: **loki_compactor_apply_retention_last_successful_run_timestamp_seconds** 0, **loki_compactor_apply_retention_operation_total** no-data

**Expected behavior**
Retention metric should be available because retention is happening

**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: [helm]

**Screenshots, Promtail config, or terminal output**
Configuration that we used for the compactor:
```
rentention_period: 180day #this for Global and some tenants we apply 14 days
compactor:
      compaction_interval: 10m
      delete_request_cancel_period: 24h
      retention_enabled: true
      retention_delete_delay: 2h
      delete_request_store: s3
```
