### ISSUE TITLE
Incorrect docker image pulled for loki-writer-0

### ISSUE THREAD

**Issue by chrisdonlan** [grafana/loki#14439]
**Describe the bug**
Looks like the `url` for loki-writer-0 is incorrect.

**To Reproduce**

```
helm upgrade --install minio minio/minio -n loki --values helm/values/minio.yaml --create-namespace
```

```
# minio.yaml is nothing special. Just:

mode: "standalone"
replicas: 1
users:
  - accessKey: <foo>
    secretKey: <bar>
    policy: consoleAdmin
persistence:
  enabled: true
  existingClaim: "pvc-minio"
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
limits:
  memory: "1Gi"
  cpu: "1000m"
buckets:
  - name: loki
    policy: none
    purge: false
    versioning: false
    objectlocking: false
  - name: loki/chunks
    policy: none
    purge: false
    versioning: false
    objectlocking: false
  - name: loki/admin
    policy: none
    purge: false
    versioning: false
    objectlocking: false
  - name: loki/ruler
    policy: none
    purge: false
    versioning: false
    objectlocking: false
```
**Expected behavior**
Expected the loki chart to deploy without errors.

What I found:

```
Failed to pull image "docker.io/harbor.devlnk.net/docker.io/grafana/loki:3.1.1"
``` 

```
# the correct image
docker.io/grafana/loki:3.1.1
```
