### ISSUE TITLE
loki-stack helm manifests not updated for arm64

### ISSUE THREAD

**Issue by tdorsey** [grafana/loki#1450]
**Describe the bug**

Several containers are using outdated images that do not support arm64.

For the server and alertmanager pods, jimmidyson/configmap-reload is locked to version 2.2 from 2 years ago, newer versions have arm64 support.

prom/pushgateway is using the 0.8.0 tag instead of latest, which also has arm support.

Most of the issues I"ve found are with prometheus related containers, so I'm not sure if it's the loki chart referencing an old version or a problem with prometheus dependencies

**To Reproduce**

`helm template --namespace default --dry-run loki loki/loki-stack -f values.yaml`, where values.yaml is 

```
loki:
  enabled: true
  persistence:
    enabled: true
grafana:
  enabled: true
  persistence:
    enabled: true
prometheus:
  enabled: true
  persistence:
    enabled: true
```

**Expected behavior**
loki-stack running in an arm64 cluster

**Environment:**
 - Infrastructure: arm64 bare metal
 - Deployment tool: helm template piped to kustomize

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
