### ISSUE TITLE
3.2.1 docker image failing to start on aarch64

### ISSUE THREAD

**Issue by lnlyssg** [grafana/loki#14530]
**Describe the bug**
Since the update to 3.2.1 my container restarts constantly and does not appear to work at all

**To Reproduce**
1. Pulled latest 3.2.1 image
2. Started Docker container using same compose file as used with 3.2.0:

```
  loki:
    image: grafana/loki:3.2.1
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
      - "9096:9096"
    command: -config.file=/etc/loki/loki-config.yml
    volumes:
      - /opt/loki:/etc/loki
    network_mode: bridge
```

**Expected behavior**
Docker image to run rather than restarting

**Environment:**
 - Infrastructure: `Linux oracle 6.8.0-1014-oracle #14~22.04.1-Ubuntu SMP Thu Oct  3 21:16:49 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux`
 - Deployment tool: Docker compose

**Screenshots, Promtail config, or terminal output**
Unfortunately I have nothing useful to share - there are no logs captured and I cannot see any other diagnostic info other than constant restarts from docker ps:
`28a70c2ef7c4   grafana/loki:latest                    "/usr/bin/loki -conf…"   13 hours ago    Restarting (1) Less than a second ago                                                                                          loki`
