### ISSUE TITLE
Log Dropping When Tailing Logs with Loki

### ISSUE THREAD

**Issue by derhnyel** [grafana/loki#14550]
**Describe the bug**
I am encountering an issue where logs ingested using Fluent Bit are not being tailed correctly in Loki 3.x versions. Logs seem to be dropped or are missing when tailing logs using the gRPC client or log-cli. This issue does not occur in Loki 2.9.10, where all logs are tailed correctly without any missing entries. (even with the --delay-for arg set)

**To Reproduce**
1.	Started Loki with versions 3.x (where the issue is present).
2.	Fluent Bit (v3.1.1) is reading Docker logs and sending them to Loki.
3.	Tail logs using one of the following methods:
	•	gRPC client (custom implementation).
	•	Loki CLI with the following query:
```bash 
 logcli query --tail '{job="logs", appName="mock-service",compName="mock-component"}' --addr=http://localhost:3200 
```

**Expected behavior**
All logs ingested into Loki should appear in the tail stream in order and without any dropped or missing entries, even during high log throughput.

**Environment:**
•	Loki Version: 3.x (issue present); 2.9.10 (working as expected)
•	Fluent Bit Version: v3.1.1
•	Infrastructure: Docker
•	Deployment tool: Docker containers (both Fluent Bit and Loki deployed as containers)
•	Log Source: Docker logs from a custom mock-service Python application
•       Fluent Bit Configuration (fluent-bit-config.conf):
```ini
[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

[INPUT]
    Name          tail
    Path          /var/lib/docker/containers/*/*.log
    Parser        docker
    Tag           docker_logs

[OUTPUT]
    Name         loki
    Match         *
    Host          loki
    Port          3200
    Labels        job=logs, appName=mock-service

```
•       Fluent Bit Dockerfile:
```
# Fluent Bit Dockerfile (fake.fluentbit.dockerfile)

FROM fluent/fluent-bit:3.1.1

COPY fluent-bit.conf /fluent-bit/etc/fluent-bit.conf

COPY parsers.conf /fluent-bit/etc/parsers.conf

EXPOSE 2020

CMD ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]
```
•       Fluent Bit (parsers.ini):
```ini
[PARSER]
    Name docker
    Format json
    Time_Key time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
```

```bash
docker network create loki-network
docker build -t fluent-bit-custom:latest -f fake.fluentbit.dockerfile .
docker run -d --name fluent-bit-custom  --network loki-network  -v /var/lib/docker/containers:/var/lib/docker/containers fluent-bit-custom:latest
```

•	Loki Configuration in (config/loki-config.yaml):
```yaml
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3200
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9095
  log_format: json
  log_level:error
  grpc_server_max_recv_msg_size: 16777216
  grpc_server_max_send_msg_size: 16777216

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  max_query_length: 365d
  ingestion_rate_mb: 256

ruler:
  alertmanager_url: http://localhost:9093

analytics:
  reporting_enabled: false
```
```bash
docker run --name loki  --network loki-network -d -v $(pwd)/config:/mnt/config -p 3200:3200 grafana/loki:3.0.0 -config.file=/mnt/config/loki-config.yaml
```

Mock Service Dockerfile (fake.dockerfile):
```
FROM python:3.9-slim

WORKDIR /app

COPY main.py /app

RUN pip install fastapi structlog uvicorn

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9012", "--reload", "--log-level", "debug"]
EXPOSE 9012
```

Mock Service Code (main.py):
```python
from typing import Any
import datetime
import uuid

from fastapi import FastAPI
import structlog
import uvicorn

APP_NAME = "mock-service"

logger: Any = structlog.get_logger()
app: FastAPI = FastAPI(title="Mock Service", description="Mock Service", version="0.1.0")

class CustomPrintLogger:
    def msg(self, message: Any) -> None:
        print(message)

logger = structlog.wrap_logger(
    CustomPrintLogger(),
    wrapper_class=structlog.BoundLogger,
    processors=[structlog.processors.JSONRenderer()],
)

@app.get("/levels")
def levels() -> dict[str, Any]:
    logger.msg("mock-event", time=str(datetime.datetime.now(datetime.timezone.utc)),
               level="fatal", appName=APP_NAME, message="mock message", host="mock-host",
               compName="mock-component")
    logger.msg("mock-event", time=str(datetime.datetime.now(datetime.timezone.utc)),
               level="critical", appName=APP_NAME, message="mock message", host="mock-host",
               compName="mock-component")
    logger.msg("mock-event", time=str(datetime.datetime.now(datetime.timezone.utc)),
               level="error", appName=APP_NAME, message="mock message", host="mock-host",
               compName="mock-component")
    logger.msg("mock-event", time=str(datetime.datetime.now(datetime.timezone.utc)),
               level="warn", appName=APP_NAME, message="mock message", host="mock-host",
               compName="mock-component")
    logger.msg("mock-event", time=str(datetime.datetime.now(datetime.timezone.utc)),
               level="warning", appName=APP_NAME, message="mock message", host="mock-host",
               compName="mock-component")
    logger.msg("mock-event", time=str(datetime.datetime.now(datetime.timezone.utc)),
               level="info", appName=APP_NAME, message="mock message", host="mock-host",
               compName="mock-component")
    logger.msg("mock-event", time=str(datetime.datetime.now(datetime.timezone.utc)),
               level="debug", appName=APP_NAME, message="mock message", host="mock-host",
               compName="mock-component")
    logger.msg("mock-event", time=str(datetime.datetime.now(datetime.timezone.utc)),
               level="trace", appName=APP_NAME, message="mock message", host="mock-host",
               compName="mock-component")
    logger.msg("mock-event", time=str(datetime.datetime.now(datetime.timezone.utc)),
               level="unknown", appName=APP_NAME, message="mock message", host="mock-host",
               compName="mock-component")
    logger.msg("mock-event", time=str(datetime.datetime.now(datetime.timezone.utc)),
               level="random", appName=APP_NAME, message=f"mock message {uuid.uuid4()}",
               host="mock-host", compName="mock-component")

    print("FATAL: This is an example of unstructured log line")
    print("CRITICAL: This is an example of unstructured log line")
    print("ERROR: This is an example of unstructured log line")
    print("WARN: This is an example of unstructured log line")
    print("WARNING: This is an example of unstructured log line")
    print("INFO: This is an example of unstructured log line")
    print("DEBUG: This is an example of unstructured log line")
    print("TRACE: This is an example of unstructured log line")
    print("UNKNOWN: This is an example of unstructured log line")
    print(f"RANDOM: This is an example of unstructured log line {uuid.uuid4()}")

    return {}

if __name__ == "__main__":
    structlog.configure(
        processors=[
            structlog.stdlib.filter_by_level,
            structlog.processors.TimeStamper(fmt="iso", key="time"),
            structlog.processors.JSONRenderer(),
        ],
        context_class=dict,
        logger_factory=structlog.stdlib.LoggerFactory(),
    )

    uvicorn.run("main:app", host="0.0.0.0", port=9012, reload=True, log_level="critical")
```
```bash
docker run -p 9012:9012 mock:latest
docker build --tag mock:latest -f mock.dockerfile .
curl 127.0.0.1:9012/levels # to generate logs 
```

**Screenshots, Promtail config, or terminal output**
Current result
![Image](https://github.com/user-attachments/assets/a0039796-3117-4d4a-bf98-69acc2993150)

Expected result 
![Image](https://github.com/user-attachments/assets/d27dcfd5-1efd-446c-869e-dbf46e047e48)
