### ISSUE TITLE
cannot be handled as a DaemonSet: json: cannot unmarshal string into Go struct field

### ISSUE THREAD

**Issue by chanyshev** [grafana/loki#14629]
**Describe the bug**
I'm trying to deploy loki with minio and I get an error. my values:
```

global:
  image:
    registry: "***"
imagePullSecrets: "nexus-registry"

loki:
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4

# gateway:
#  ingress:
#    enabled: true
#    hosts:
#      - host: FIXME
#        paths:
#          - path: /
#            pathType: Prefix

deploymentMode: SimpleScalable

backend:
  image:
    registry: "***"
  replicas: 3
  persistence:
    volumeClaimsEnabled: false
read:
  image:
    registry: "***"
  replicas: 3
  persistence:
    volumeClaimsEnabled: false
write:
  image:
    registry: "***"
  replicas: 3
  persistence:
    volumeClaimsEnabled: false


# Enable minio for storage
minio:
  enabled: true
  persistence:
    size: 50Gi

# Zero out replica counts of other deployment modes
singleBinary:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
```

**To Reproduce**
1. Started Loki (SHA or version) - helm chart 6.18.0

**Expected behavior**

**Environment:**
 - Infrastructure: [Kubernetes 1.30]
 - Deployment tool: [helm]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
```
Error: UPGRADE FAILED: failed to create resource: DaemonSet in version "v1" cannot be handled as a DaemonSet: json: cannot unmarshal string into Go struct field PodSpec.spec.template.spec.imagePullSecrets of type []v1.LocalObjectReference
```
