### ISSUE TITLE
No tag in dynamoDB

### ISSUE THREAD

**Issue by Eraac** [grafana/loki#1462]
**Describe the bug**
DynamoDB table has no tag set

**To Reproduce**
1. Started Loki with config that set tag for dynamoDB table

**Expected behavior**
DynamoDB table should have tags

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: helm
 - Loki version: 1.2

**Loki config**
```
[...]
  # Configures the chunk index schema and where it is stored.
  schema_config:
    # The configuration for chunk index schemas.
    configs:
      # The date of the first day that index buckets should be created. Use
      # a date in the past if this is your only period_config, otherwise
      # use a date when you want the schema to switch over.
      - from: 2019-11-14

        # Which store to use for the index. Either cassandra, bigtable, aws, or boltdb
        store: aws

        # Which store to use for the chunks. Either gcs, s3, inmemory, filesystem, cassandra. If omitted, defaults to same value as store.
        object_store: s3

        # The schema to use. Set to v9 or v10.
        schema: v11

        # How many shards will be created. Only used if schema is v10.
        row_shards: 16

        # Configures how the index is updated and stored.
        index:
          # Table prefix for all period tables.
          prefix: loki_index_

          # Table period.
          period: 168h

          # A map to be added to all managed tables.
          tags:
            project: loki
[...]
```
