### ISSUE TITLE
SSL not working by default / not documented

### ISSUE THREAD

**Issue by bukowa** [grafana/loki#1463]
**To Reproduce**
1. Run docker-compose up
2. Visit https://localhost:3100
````yaml
version: "3"

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
````

**Expected behavior**
SSL is documented.

**Environment:**
 - Infrastructure: docker-desktop on windows
 - Deployment tool: docker-compose

**Screenshots, Promtail config, or terminal output**
````shell script
$ curl https://localhost:3100
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
````
![firefox_6aZdpRdpd8](https://user-images.githubusercontent.com/38087302/71716761-16820780-2e16-11ea-804a-529aa8b40f64.png)

No additonal log in `loki` container.

**Info**
So using https in `loki-url: "http://localhost:3100/loki/api/v1/push"` (as documented) won't work.
