### ISSUE TITLE
Loki Simple Scalable Tutorial Not Working - pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by shreybatra** [grafana/loki#14892]
**Describe the bug**
While trying to deploy Loki with Helm charts [using the given official tutorial](https://grafana.com/docs/loki/latest/setup/install/helm/install-scalable/), and using s3 as the object store in Simple Scalable mode, the `backend` and `chunks-cache` pods are stuck in Pending state with error -
```
pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```

The PVCs when found are using storage class `hostpath` -
```
test-logging   data-loki-write-0   Pending                                      hostpath       <unset>                 19s
test-logging   data-loki-write-1   Pending                                      hostpath       <unset>                 19s
test-logging   data-loki-write-2   Pending                                      hostpath       <unset>                 19s
```

Values config file -
```
loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      region: ap-south-1
      bucketnames: <my bucket name>
      s3forcepathstyle: false
  pattern_ingester:
      enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h # 28 days retention
  querier:
    max_concurrent: 4

  storage:
    type: s3
    bucketNames:
        chunks: <my bucket name>
        ruler: <my bucket name>
        admin: <my bucket name>
    s3:
      # AWS endpoint URL
      endpoint: s3.ap-south-1.amazonaws.com
      # AWS region where the S3 bucket is located
      region: ap-south-1
      # AWS secret access key
      secretAccessKey: <secret, which is url encoded>
      # AWS access key ID
      accessKeyId: <access id>
      s3ForcePathStyle: false
      insecure: false

deploymentMode: SimpleScalable

backend:
  replicas: 1
read:
  replicas: 1
write:
  replicas: 1

# Disable minio storage
minio:
  enabled: false
```

**To Reproduce**
1. Started Loki (SHA or version)

**Environment:**
- Tried on local K8s as well as a testing EKS cluster on AWS.

**Comment by daimalou** [comment]
The official documentation is outdated and full of flaws, and it seems that no one is maintaining it.

**Comment by bezchristo** [comment]
Having the same issue. @shreybatra have you been able to fix this?

**Comment by dtapiacl** [comment]
Such an awesome tool, its a shame that the documentation is a mess.

**Comment by MaroIT** [comment]
I just added PersistentVolume's in a template folder in my Helm chart folder, but now I am struggling with 'permission denied' error as there is policy in place that seems to force 'privileged: false' and 'allowPrivilegeEscalation: false' so I am not sure how to proceed with my on-premese kubernetes and hostPath PV's...

**Comment by garnus** [comment]
Hi, 
I had the same problem today. I added the container storage instead using a storageclass
`write:
  replicas: 5
  persistence:
    volumeClaimsEnabled: false
    dataVolumeParameters:
      emptyDir: {}
read:
  replicas: 5
backend:
  replicas: 5
  persistence:
    volumeClaimsEnabled: false
    dataVolumeParameters:
      emptyDir: {}
gateway:
  replicas: 5
  nginxConfig:
    enableIPv6: false`

**Comment by zizekuros** [comment]
> > Well, got to know that it needed a default storage-class being set, I created one and it started working. These things should be there atleast in hello-world.
> 
> Cna you share the code snippet ? [@shreybatra](https://github.com/shreybatra)

I would kindly appreciate this too!

**Comment by zizekuros** [comment]
> Hi, I had the same problem today. I added the container storage instead using a storageclass
> 
> ```
> write:
>   replicas: 5
>   persistence:
>     volumeClaimsEnabled: false
>     dataVolumeParameters:
>       emptyDir: {}
> read:
>   replicas: 5
> backend:
>   replicas: 5
>   persistence:
>     volumeClaimsEnabled: false
>     dataVolumeParameters:
>       emptyDir: {}
> gateway:
>   replicas: 5
>   nginxConfig:
>     enableIPv6: false
> ```

This might solve the issue for me as well.. but wondering, what is the actual difference? Any downsides? @garnus

**Comment by garnus** [comment]
@zizekuros You data lives as long as the pod lives. If you have replicas for write all need to be down to lose data. 
You can also use rancher.io/local-path to make the pod's storage persistent on the node.

**Comment by zizekuros** [comment]
> [@zizekuros](https://github.com/zizekuros) You data lives as long as the pod lives. If you have replicas for write all need to be down to lose data. You can also use rancher.io/local-path to make the pod's storage persistent on the node.

But data are still shipped to external storage (in example S3) frequently, right? It's possible to only lose data that wasn't shipped forward yet, correct?

**Comment by garnus** [comment]
Yes, only data that was not shipped. During test one I got a 15min hole in metrics and once 1h. I didn't find a way to control the sync time yet.

**Comment by hongbo-miao** [comment]
Got same error, adding `storageClass` helps me.

```yaml
backend:
  persistence:
    storageClass: production-hm-loki-storage-class
read:
  persistence:
    storageClass: production-hm-loki-storage-class
write:
  persistence:
    storageClass: production-hm-loki-storage-class
```

Also, make sure having enough nodes, otherwise you may get `didn't match pod anti-affinity rules` error. ☺️
