### ISSUE TITLE
LOKI/Promtail - timestamp is not detected

### ISSUE THREAD

**Issue by replay111** [grafana/loki#14904]
**Describe the bug**
Promtail is not detecting new labels. I am getting logs from mikrotik, logs are sent directly to promtail from as syslog (format: rfc3164).
Promtail is parsing it but all the time I am getting error related with missing timestamp:

ERROR:
```
caller=timestamp.go:176 component=syslog_pipeline msg="extracted data did not contain a timestamp"
```

**To Reproduce**
1. set mikrotik to sent logs to promtail - or use some excerpt of it:
```
<24>Nov 12 19:31:44 mikt00 [DROP_02] forward: in:INT002 out:outside1, connection-state:new src-mac 00:00:00:00:00:00, proto TCP (SYN), 111.111.111.111:58969->222.222.222.222:443, len 48
<24>Nov 12 19:31:43 mikt00 [DROP_00] input: in:outside1 out:(unknown 0), connection-state:new src-mac 00:00:00:00:00:00, proto TCP (SYN), 111.111.111.111:25908->222.222.222.222:8436, len 52
<24>Nov 12 19:29:02 mikt00 [DROP_00] input: in:outside1 out:(unknown 0), connection-state:new src-mac 00:00:00:00:00:00, proto UDP, 111.111.111.111:51710->222.222.222.222:10001, len 32
<24>Nov 12 19:28:59 mikt00 [DROP_00] input: in:outside1 out:(unknown 0), connection-state:new src-mac 00:00:00:00:00:00, proto TCP (SYN), 111.111.111.111:52770->222.222.222.222:443, len 40
<24>Nov 12 19:28:58 mikt00 [DROP_02] forward: in:INT002 out:outside1, connection-state:new src-mac 00:00:00:00:00:00, proto TCP (SYN), 111.111.111.111:58812->222.222.222.222:443, len 48
<24>Nov 12 19:28:57 mikt00 [DROP_02] forward: in:INT002 out:outside1, connection-state:new src-mac 00:00:00:00:00:00, proto TCP (SYN), 111.111.111.111:58818->222.222.222.222:443, len 64
<24>Nov 12 19:28:32 mikt00 [DROP_00] input: in:outside1 out:(unknown 0), connection-state:new src-mac 00:00:00:00:00:00, proto UDP, 111.111.111.111:443->222.222.222.222:65475, len 61
```

promtail:
```
clients:
  - url: https://loki.my.domain/loki/api/v1/push
    tls_config:
      insecure_skip_verify: true

scrape_configs:

  - job_name: mikrotik
    syslog:
      syslog_format: "rfc3164"
      listen_address: 0.0.0.0:6044
      idle_timeout: 20s
      label_structured_data: true
      listen_protocol: udp
      labels:
        job: "syslog_mikrotik"
    pipeline_stages:
      - regex: 
          expression: '(?P<timestamp>\w{3} \d{1,2} \d{2}:\d{2}:\d{2})'
      - timestamp:
          source: "timestamp"
          format: "Jan 2 15:04:05"
      - regex:
          expression: '\[(?P<log_tag>[^\]]+)\]'
      - labels:
          log_tag: "{{ .log_tag }}"
      - regex:
          expression: '(?P<src_ip>\d{1,3}(?:\.\d{1,3}){3})'
      - labels:
          src_ip: "{{ .src_ip }}"


    relabel_configs:
      - source_labels: ['__syslog_message_severity']
        target_label: 'severity'
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
      - source_labels: ['__syslog_message_app_name']
        target_label: 'app'  
```

**Expected behavior**
Logs in loki parsed and contains extra labels in json format

but instead getting error:

```
caller=timestamp.go:176 component=syslog_pipeline msg="extracted data did not contain a timestamp"
```

**Environment:**
 - promtail and loki - running as docker containers (on nomad)
 - Deployment tool: jenkins/manual

**Comment by replay111** [comment]
Ok Looks like I solved my issue,
promtail - final setup:

```
server:
  http_listen_port: 9080
  http_listen_address: 0.0.0.0
  grpc_listen_port: 9095
  log_level: debug

positions:
  filename: /data/positions.yaml


clients:
  - url: https://loki.my.domain/loki/api/v1/push
    tls_config:
      insecure_skip_verify: true

scrape_configs:

  - job_name: mikrotik
    syslog:
      syslog_format: "rfc3164"
      listen_address: 0.0.0.0:6044
      idle_timeout: 20s
      label_structured_data: true
      listen_protocol: udp
      labels:
        job: "syslog_mikrotik"
    pipeline_stages:
      - regex:
          expression: '\[(?P<log_tag>[^\]]+)\] (?P<firewall_chain>\w+): in:(?P<interface_in>[^ ]+) out:(?P<interface_out>[^(,]+|\([^)]+\)|[^)]), connection-state:(?P<conn_state>\w+) src-mac (?P<src_mac>(?:[0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}), proto (?P<protocol>\S+)(?: \((?P<tcp_flags>\w+)\))?, (?P<src_ip>\d{1,3}(?:\.\d{1,3}){3}):(?P<src_port>\d+)->(?P<dest_ip>\d{1,3}(?:\.\d{1,3}){3}):(?P<dest_port>\d+), len (?P<length>\d+)'
      - labels:
          log_tag:
          firewall_chain:
          interface_in: 
          interface_out:
          conn_state:
          src_mac:
          protocol: 
          tcp_flags:
          src_ip:
          src_port:
          dest_ip:
          dest_port:
          length:
      - regex:
          expression: '(?P<message>.+)'
      - labels:
          message:

    relabel_configs:
      - source_labels: ['__syslog_message_severity']
        target_label: 'severity'
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
      - source_labels: ['__syslog_message_app_name']
        target_label: 'app'  
```

and I had to increase number of labels in ```**loki**```:

```
limits_config:
  max_label_names_per_series: 25
```

And now that grafana is able to show me all labels defined in promtail and I am able to filter my logs from miktorik.
