### ISSUE TITLE
compactor is not honoring all API delete log requests

### ISSUE THREAD

**Issue by LinLo** [grafana/loki#14985]
**Describe the bug**
In helm deployment simple scalable mode (but maybe on distributed mode) when we have multiple pods with compactor, so multiple "endpoints" for DELETE api, the DELETE requests are sent to "loki-backend" service, then the kubernetes service is "randomly" forwarding to any backend pod.
What I found is that all POST DELETE requests sent to backend pods where compactor is not "active" (or maybe is not running at all) will stay in "received" status.
I found also that GET DELETE requests is following the same service path as POST DELETE requests and depending on the backend pod the requests ends (loki-backend service load balancing) the reply will not be the same.

**To Reproduce**
1. Deploy loki 3.2.1.
1. Configuration, no TLS/SSL and no AUTH for this test.
    - Simple Scalable mode with 3 backend, 3 writes, 3 read with only one tenant (fake)
        ```
        compactor:
          compaction_interval: 10m
          delete_request_cancel_period: 5m
          delete_request_store: s3
          retention_delete_delay: 5m
          retention_delete_worker_count: 150
          retention_enabled: true
        limits_config:
          deletion_mode: filter-and-delete
          max_query_lookback: 744h
          query_timeout: 300s
          reject_old_samples: true
          reject_old_samples_max_age: 24h
          retention_period: 744h
        ```
1. Launch several POST DELETE requests with curl (adapt start date and TLS/AUTH depending on your deployment)
    - Example:
        ```
        curl -G -X POST 'http://loki-gateway.loki-ns.svc.cluster.local/loki/api/v1/delete' --data-urlencode 'query={job!="1"}' --data-urlencode "start=$(($(date +'%s')-2682000))"
        curl -G -X POST 'http://loki-gateway.loki-ns.svc.cluster.local/loki/api/v1/delete' --data-urlencode 'query={job!="2"}' --data-urlencode "start=$(($(date +'%s')-2682000))"
        curl -G -X POST 'http://loki-gateway.loki-ns.svc.cluster.local/loki/api/v1/delete' --data-urlencode 'query={job!="3"}' --data-urlencode "start=$(($(date +'%s')-2682000))"
        curl -G -X POST 'http://loki-gateway.loki-ns.svc.cluster.local/loki/api/v1/delete' --data-urlencode 'query={job!="4"}' --data-urlencode "start=$(($(date +'%s')-2682000))"
        curl -G -X POST 'http://loki-gateway.loki-ns.svc.cluster.local/loki/api/v1/delete' --data-urlencode 'query={job!="5"}' --data-urlencode "start=$(($(date +'%s')-2682000))"
        ``` 
1. Launch several times GET DELETE requests with curl (adapt with TLS and AUTH depending on your deployment):
    ```
    curl -s -X GET 'http://loki-gateway.loki-ns.svc.cluster.local/loki/api/v1/delete' | jq
    curl -s -X GET 'http://loki-gateway.loki-ns.svc.cluster.local/loki/api/v1/delete' | jq
    curl -s -X GET 'http://loki-gateway.loki-ns.svc.cluster.local/loki/api/v1/delete' | jq
    curl -s -X GET 'http://loki-gateway.loki-ns.svc.cluster.local/loki/api/v1/delete' | jq
    curl -s -X GET 'http://loki-gateway.loki-ns.svc.cluster.local/loki/api/v1/delete' | jq
    ```
1. You will see that each answer content is not containing the full list of previous DELETE requests. It depends on which loki-backend pod the answer came from.
1. Repeat GET DELETE step (4) after some time (5 to 15 min) and will see that DELETE requests "processed" are from only one compactor (on only one loki-backend). You will see in corresponding loki-backend logs that **only** DELETE requests on the "active/running" compactor will be honored. Others will never be taken into account (unless active/running compactor is moving to another pod if the loki-backend pod is deleted for example).

**Expected behavior**
1. All POST DELETE requests must be honored by active/running compactor.
2. All GET DELETE requests should display all requests status.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

Tell me if you need more information (like helm values and loki-backend pod logs).
The only workaround I found for now is to only deploy one instance of backend.

**Comment by simenflatby** [comment]
We are seeing the same behaviour.

# Versions

- helm chart: loki-5.6.4
- loki: 2.8.2

# Hacky work around

Use the deletion request HTTP API straight towards the Pod currently running the compactor component. The API is exposed on the named port `http-metrics` (port 3100 in our version). To find the relevant Pod, look for the latest occurrence of the log line "this instance has been chosen to run the compactor, starting compactor" from the Pods under the StatatefulSet `loki-scalable-backend`.

## Example

### Loki query to find relevant pod

```
{namespace="example-namespace", app="loki-scalable"} |= "this instance has been chosen to run the compactor, starting compactor" | logfmt | component = "backend" | line_format "{{.pod}}"
```

```
2025-03-03 12:26:48.064	loki-scalable-backend-1
```

### Port forwarding from local computer to relevant pod

```
kubectl \
    --context example-context \
    --namespace example-namespace \
    port-forward pod/loki-scalable-backend-1 8080:3100
```

```
Forwarding from 127.0.0.1:8080 -> 3100
Forwarding from [::1]:8080 -> 3100
```
### Using HTTP API toward forwarded port

```
curl \
	--silent \
	--include \
	--request 'POST' \
	--get \
	--data-urlencode 'start=2025-02-17T01:03:38Z' \
	--data-urlencode 'end=2025-02-17T01:03:40Z' \
	--data-urlencode 'query={namespace="example-namespace", app="example-app"} |= `secret`' \
	'http://localhost:8080/loki/api/v1/delete'
```

```
HTTP/1.1 204 No Content
Date: Mon, 03 Mar 2025 11:40:11 GMT
```

**Comment by kkwekkeboom** [comment]
Hi all,

I'm having a similar issue. Running loki 3.4.2 in simple scalable mode with s3 backend
```
# Compactor configuration
  compactor:
    # Activate custom retention
    retention_enabled: true

    # Directory where files can be downloaded for compaction
    working_directory: /var/loki/compactor

    # Delay after which chunks will be fully deleted during retention
    retention_delete_delay: 15m

    # Store used for managing delete requests
    delete_request_store: s3
```

I created a test script that inserts 10 logs in 100 streams. Then it issues delete requests for each of the 100 streams. Some delete requests issued actually remove logs after 5 minutes (the compactor interval). Some do not delete anything

I did try debugging one of the delete requests that did not remove logs

Debugging learns that backend-0 runs the compactor
```
kubectl logs -n loki loki-backend-0 -c loki |  head -n 20000 | grep "this instance" 
level=info ts=2025-04-02T14:00:14.526170535Z caller=compactor.go:493 msg="this instance has been chosen to run the compactor, starting compactor"
kubectl logs -n loki loki-backend-1 -c loki |  head -n 20000 | grep "this instance" 
level=info ts=2025-04-02T14:00:16.075227869Z caller=compactor.go:493 msg="this instance has been chosen to run the compactor, starting compactor"
level=info ts=2025-04-02T14:00:36.075667721Z caller=compactor.go:502 msg="this instance should no longer run the compactor, stopping compactor"
```
The deletion request has been added to the right compactor
```
kubectl logs -n loki loki-backend-0 -c loki | grep "c97740dd-096d-4376-be4a-5a75c75d401e"
level=info ts=2025-04-03T08:37:20.144925842Z caller=request_handler.go:120 msg="delete request for user added" delete_request_id=852532b8 user=abc query="{key=\"c97740dd-096d-4376-be4a-5a75c75d401e\"}" interval=0s
```

However logs with the same filter as this delete request still exist after hours.

**Comment by osery** [comment]
Running into the same issue. Some delete requests end up on backend instances that do not run compactor. Such requests get never processed (or at least until the compactor is run by that backend, e.g., after pod restart). I wonder what the logic for syncing the delete requests actually is.

In distributed mode, I can run just a single compactor, but not in simple scalable :-(.

**Comment by kwinkel** [comment]
Also running into this issue using simple-scalable-deployment method.

Currently have to redeploy my backend instances until the backend where the request is sent to is elected to be the current compactor instance.

The other backends do not know about the deletion requests (`GET loki/api/v1/delete`).

S3 store is configured for the compactor, similar to the regular storage configuration.
```yaml
# ...
compactor:
  delete_request_store: s3
  retention_enabled: true
  # ...
```
