### ISSUE TITLE
[Helm] when deployed with multiple LGTM components in one namespace Ingester naming causes conflicts

### ISSUE THREAD

**Issue by boldfield** [grafana/loki#15062]
**Describe the bug**
When deploying multiple distributed LTGM stack components to a single namespace the anti-affinity rules of each component's conflict with each other.  E.g. [here](https://github.com/grafana/loki/blob/main/production/helm/loki/templates/ingester/statefulset-ingester-zone-a.yaml#L162-L171):
```
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: rollout-group
                    operator: In
                    values:
                      - ingester
                  - key: name
                    operator: NotIn
                    values:
                      - ingester-zone-a
```

**To Reproduce**
1. Deploy distributed Loki, Tempo, and Mimir to a single Kubernetes namespace
2. watch scheduling failures due to podAntiAffinity rule conflicts

**Expected behavior**
All ingester components schedule successfully schedule and deploy

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
N/A
