### ISSUE TITLE
alert is NOT raised to alertmanager in multi-tenant mode Loki

### ISSUE THREAD

**Issue by spike-isao** [grafana/loki#15064]
**Describe the bug**
Alert can be raised to alertmanager in single tenant mode. After I change it to multi-tenant mode, the alert is raised at all. I searched in the internet. I can get some discussion but there is no solution at all.
[Multi-tenant Loki Ruler is not sending Alerts to Mimir AlertManager](https://community.grafana.com/t/multi-tenant-loki-ruler-is-not-sending-alerts-to-mimir-alertmanager/126536)

**To Reproduce**
1. Started Loki (SHA or version)
- latest version pulled yesterday
2. Started Promtail (SHA or version) to tail '...'
- lastest version pulled yesterday
3. Query: `(count_over_time({source=\"test\"}[1d]) > 0)`**check if there is any log with label source equals test**
After any log added to Loki, it should be raised to alertmanager. In single tenant mode, it's working. For multi-tenant mode, it's not working at all. 

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 It's running with docker on a M3 Macbook pro. If you need, I can provide docker-compose.yml file.
 - Deployment tool: [e.g., helm, jsonnet]
 None

**Screenshots, Promtail config, or terminal output**
Loki checks the log with the rule.

![Image](https://github.com/user-attachments/assets/d4111573-edf9-42cb-8ffb-a734935471eb)
Loki configuration file:
````
auth_enabled: true

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /data/loki

ingester:
  wal:
    enabled: true
    dir: /data/loki/wal
    flush_on_shutdown: true

compactor:
  working_directory: /data/loki/retention
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: filesystem

schema_config:
  configs:
  - from: 2021-01-01
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  filesystem:
    directory: /data/loki/chunks

limits_config:
  max_query_lookback: 14d
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 14d

ruler:
  storage:
    type: local
    local:
      directory: /etc/loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true

```
