### ISSUE TITLE
Can't synchronize ArgoCD App

### ISSUE THREAD

**Issue by pbrissaud** [grafana/loki#15100]
**Describe the bug**
I'm trying to install Loki using ArgoCD, but I encounter the following error during the installation process:

```
Failed to load target state: failed to generate manifest for source 1 of 2: rpc error: code = Unknown desc = failed to initialize repository resources: rpc error: code = Internal desc = Failed to checkout FETCH_HEAD: `git submodule update --init --recursive` failed exit status 128: fatal: No url found for submodule path '_shared-workflows-dockerhub-login' in .gitmodules
```

This error is similar to the issues discussed in #14896 and #14966, which were fixed last week by PR #14883. It appears to be caused by an extra file referencing a git submodule. However, this problem has been reintroduced in commit [5897e08](https://github.com/grafana/loki/commit/5897e084dfe011482aa5dadaedef40fbbf79b08c), which was made after the fix in PR #14883.

**To Reproduce**
1. Set up ArgoCD to deploy Loki.
2. Attempt to sync the Loki deployment.
3. Encounter the error during the sync process.

**Expected behavior**
Loki should be successfully deployed via ArgoCD without any submodule issues.

**Environment:**
- Infrastructure: Kubernetes GKE
- Deployment tool: ArgoCD - Helm + values files
 
**Screenshots, Promtail config, or terminal output**

ArgoCD app spec 
```yaml
project: default
destination:
  namespace: loki
  name: kube-central
syncPolicy:
  syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
ignoreDifferences:
  - kind: Secret
    name: loki-gateway
    jsonPointers:
      - /data/.htpasswd
sources:
  - repoURL: https://grafana.github.io/helm-charts
    targetRevision: x
    helm:
      valueFiles:
        - $values/production/helm/loki/simple-scalable-values.yaml
      releaseName: loki
    chart: loki
  - repoURL: https://github.com/grafana/loki
    targetRevision: main
    ref: values
```
