### ISSUE TITLE
I can't get promtail to listen

### ISSUE THREAD

**Issue by CRad14** [grafana/loki#1512]
I am configuring promtail to be a syslog receiver, but for some reason I cannot get it to listen on the port configured. 

Here is the config.yaml

```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0


positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki_addr:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:10514
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
```

netstat -ntlp returns
![image](https://user-images.githubusercontent.com/4015677/72286910-ba846380-360b-11ea-828d-45da91aa6cce.png)

I am not sure what I am missing, but any help would be greatly appreciated. 

Thanks!
