### ISSUE TITLE
[gateway/configmap-gateway.yaml] error converting YAML to JSON: yaml: line 9: did not find expected comment or line break

### ISSUE THREAD

**Issue by wwyhy** [grafana/loki#15143]
Hello,

I am trying to install grafana/loki helm chart (version 6.21.0), but get error during gateway configmap render.
https://artifacthub.io/packages/helm/grafana/loki

If changed the template from "{{- tpl .Values.gateway.nginxConfig.file . | indent 2 }}" to {{- tpl .Values.gateway.nginxConfig.file . | nindent 4 }},
it works fine, but we cannot change the Chart, so could you please help on how can i adjust the value to make it works? thanks!
or is this a issue about the configmap template?

Reproduce:

```
# cat value.yaml
gateway:
  enabled: true
  replicas: 3
  verboseLogging: true
  nginxConfig:
    file: |
      worker_processes  5;
      error_log  /dev/stderr;
      pid        /tmp/nginx.pid;
      worker_rlimit_nofile 8192;
     
```

```
## Refer: https://github.com/grafana/loki/blob/main/production/helm/loki/templates/gateway/configmap-gateway.yaml
# cat configmap.yaml
{{- if and .Values.gateway.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
  namespace: monitoring
  labels:
    app: gateway
data:
  nginx.conf: |
    {{- tpl .Values.gateway.nginxConfig.file . | indent 2 }}
{{- end }}
```

```
# cat Chart.yaml
apiVersion: v2
appVersion: 3.3.0
description: Helm chart for Grafana Loki and Grafana Enterprise Logs supporting both
  simple, scalable and distributed modes.
home: https://grafana.github.io/helm-charts
icon: https://grafana.com/docs/loki/latest/logo_and_name.png
maintainers:
- name: trevorwhitney
- name: jeschkies
name: loki
sources:
- https://github.com/grafana/loki
- https://grafana.com/oss/loki/
- https://grafana.com/docs/loki/latest/
type: application
version: 6.21.0
```

```
# ls
Chart.yaml templates  value.yaml
# ls templates/
confimap.yaml
# helm template . --values ./value.yaml --debug
install.go:222: [debug] Original chart version: ""
install.go:239: [debug] CHART PATH: /tmp/a

---
# Source: loki/templates/confimap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway
  namespace: monitoring
  labels:
    app: gateway
data:
  nginx.conf: |  worker_processes  5;
  error_log  /dev/stderr;
  pid        /tmp/nginx.pid;
  worker_rlimit_nofile 8192;
Error: YAML parse error on loki/templates/confimap.yaml: error converting YAML to JSON: yaml: line 9: did not find expected comment or line break
helm.go:84: [debug] error converting YAML to JSON: yaml: line 9: did not find expected comment or line break
YAML parse error on loki/templates/confimap.yaml
```

Thanks!
