### ISSUE TITLE
Docs missing vital information

### ISSUE THREAD

**Issue by jenia** [grafana/loki#15182]
**Describe the bug**
Docs examples missing vital information

**To Reproduce**
1. Install Loki in monolith mode using Helm charts following [these docs](https://grafana.com/docs/loki/latest/setup/install/helm/install-monolithic/#single-replica).
2. See these type of errors: `{"time": "2024-11-28T14:57:41.907260+00:00", "taskName": null, "msg": "5xx response content will not be enabled.", "level": "INFO"}
at least one bucket name must be specified
github.com/grafana/loki/v3/pkg/storage/chunk/client/aws.buckets`
3. Realize that you need to also configure both the `storage` and `storage_config` values:

```
loki:
  storage:
    bucketNames:
      chunks: "abc"
      admin: "def"
      ruler: "ghi"

loki:
  storage_config:
    gcs:
      bucket_name: "abc" <----- notice it's same as chunks above... I don't know why but seems to work
      service_account: |
        {
         ...
        }
```
shown [here](https://grafana.com/docs/loki/latest/setup/install/helm/configure-storage/) and [here](https://grafana.com/docs/loki/latest/configure/examples/configuration-examples/#4-gcs-exampleyaml) respectively.

**Expected behavior**
Complete example of how to setup a monolith Loki instance using Helm.

**Environment:**
 - Kubernetes 
 - Helm

**Screenshots, Promtail config, or terminal output**
N/A

Can someone please also explain, what does the 
```
loki:
  storage_config:
    gcs:
      bucket_name: "abc" <----- notice it's same as chunks above... I don't know why but seems to work
```
do? Why do you need to specify that bucket twice?

Thanks kindly for updating the docs with full, working examples.
