### ISSUE TITLE
Grafana loki deploys sometimes with a bad read pod

### ISSUE THREAD

**Issue by someStrangerFromTheAbyss** [grafana/loki#15191]
When deploying grafana loki in Simple Scalable with multiple read pods set in a kubernetes cluster, you sometimes end with a loki read pod that cannot execute any queries. This problem reflect in Grafana by a 504 Gateway timeout similar to this [issue](https://github.com/grafana/loki/issues/7084) and is also linked to the 499 nginx issue found [here](https://github.com/grafana/loki/issues/14384#issuecomment-2502593461)

**Expected behavior**
Grafana loki should deploy no problem and should have a "tainted" read pods for no reason

**Environment:**
- Deployed using the official Helm chart of loki, version 6.10.0
- Deploying Grafana loki using version 3.2.1
- Deployed on Internal Cloud. Using Cilium version 1.16.4
- Storage is Azure Blob Storage

**How to replicate:**

- Deploy using the helm upgrade or helm install. Here is my final loki config file:

```
auth_enabled: false
common:
  compactor_address: 'http://loki-backend:3100'
  path_prefix: /var/loki
  replication_factor: 1
  storage:
    azure:
      account_key: CREDENTIALS
      account_name: CREDENTIALS
      container_name: loki
      request_timeout: 30s
      use_federated_token: false
      use_managed_identity: false
compactor:
  compaction_interval: 10m
  delete_request_cancel_period: 24h
  delete_request_store: azure
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  retention_enabled: true
  working_directory: /tmp
frontend:
  scheduler_address: ""
  tail_proxy_url: ""
frontend_worker:
  scheduler_address: ""
index_gateway:
  mode: simple
ingester:
  chunk_idle_period: 30m
  chunk_target_size: 1572864
  flush_check_period: 15s
  wal:
    replay_memory_ceiling: 1024MB
limits_config:
  allow_structured_metadata: true
  ingestion_burst_size_mb: 30
  ingestion_rate_mb: 30
  ingestion_rate_strategy: local
  max_cache_freshness_per_query: 10m
  max_chunks_per_query: 100
  max_concurrent_tail_requests: 100
  max_entries_limit_per_query: 1000
  max_global_streams_per_user: 50000
  max_label_names_per_series: 17
  max_line_size_truncate: false
  max_query_parallelism: 128
  max_query_series: 50
  max_streams_matchers_per_query: 100
  per_stream_rate_limit: 5Mb
  per_stream_rate_limit_burst: 20Mb
  query_timeout: 300s
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 14d
  shard_streams:
    desired_rate: 3000000
    enabled: true
  split_queries_by_interval: 1h
  tsdb_max_bytes_per_shard: 2GB
  tsdb_max_query_parallelism: 2048
  volume_enabled: true
memberlist:
  join_members:
  - loki-memberlist
pattern_ingester:
  enabled: false
query_range:
  align_queries_with_step: true
ruler:
  alertmanager_url: SECRET
  enable_alertmanager_v2: true
  enable_api: true
  storage:
    azure:
      account_key: CREDENTIAL
      account_name: CREDENTIAL
      container_name: loki
      request_timeout: 30s
      use_federated_token: false
      use_managed_identity: false
    type: azure
runtime_config:
  file: /etc/loki/runtime-config/runtime-config.yaml
schema_config:
  configs:
  - from: "2024-07-29"
    index:
      period: 24h
      prefix: index_
    object_store: azure
    schema: v13
    store: tsdb
server:
  grpc_listen_port: 9095
  grpc_server_max_recv_msg_size: 60000000
  grpc_server_max_send_msg_size: 60000000
  http_listen_port: 3100
  http_server_idle_timeout: 600s
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s
  log_level: debug
storage_config:
  hedging:
    at: 250ms
    max_per_second: 20
    up_to: 3
  tsdb_shipper:
    index_gateway_client:
      log_gateway_requests: true
      server_address: dns+loki-backend-headless.6723a512e7641cd9c37269ed.svc.cluster.local:9095
tracing:
  enabled: true
```

- Deploy with the following 3 read pods, 1 backend pod,1 write pod and 1 gateway pod. Here are my helm values:
```
backend:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: projectId
              operator: In
              values:
              - 27edfc6c-eb78-4790-a6c8-ed82a0478f7c
          topologyKey: kubernetes.io/hostname
        weight: 100
    podAntiAffinity: null
  extraEnv:
  - name: GOMEMLIMIT
    valueFrom:
      resourceFieldRef:
        resource: limits.memory
  - name: GOMAXPROCS
    valueFrom:
      resourceFieldRef:
        resource: limits.cpu
  nodeSelector:
    dedicated: logs-instance
  persistence:
    enableStatefulSetAutoDeletePVC: true
    size: 16Gi
    storageClass: csi-cinder-sc-delete
  podAnnotations:
    port: "3100"
    type: loki-backend
  podLabels:
    app: logs
    team: mops
  replicas: 1
  resources:
    limits:
      memory: 1280Mi
    requests:
      cpu: 1
      memory: 1280Mi
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: logs-instance
chunksCache:
  enabled: false
distributor:
  receivers:
    otlp:
      grpc:
        max_recv_msg_size_mib: 60000000
enterprise:
  enabled: false
frontend:
  max_outstanding_per_tenant: 1000
  scheduler_worker_concurrency: 15
fullnameOverride: loki
gateway:
  enabled: true
  ingress:
    enabled: false
  nodeSelector:
    dedicated: logs-instance
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: logs-instance
index:
  in-memory-sorted-index:
    retention_period: 24h
  period: 168h
  prefix: index_
ingress:
  enabled: false
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  compactor:
    compaction_interval: 10m
    delete_request_cancel_period: 24h
    delete_request_store: azure
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    retention_enabled: true
    working_directory: /tmp
  configStorageType: Secret
  image:
    pullPolicy: IfNotPresent
    tag: 3.2.1
  ingester:
    chunk_idle_period: 30m
    chunk_target_size: 1572864
    flush_check_period: 15s
    wal:
      replay_memory_ceiling: 1024MB
  limits_config:
    allow_structured_metadata: true
    ingestion_burst_size_mb: 30
    ingestion_rate_mb: 30
    ingestion_rate_strategy: local
    max_cache_freshness_per_query: 10m
    max_chunks_per_query: 100
    max_concurrent_tail_requests: 100
    max_entries_limit_per_query: 1000
    max_global_streams_per_user: 50000
    max_label_names_per_series: 17
    max_line_size_truncate: false
    max_query_parallelism: 128
    max_query_series: 50
    max_streams_matchers_per_query: 100
    per_stream_rate_limit: 5Mb
    per_stream_rate_limit_burst: 20Mb
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    retention_period: 14d
    shard_streams:
      desired_rate: 3000000
      enabled: true
    split_queries_by_interval: 1h
    tsdb_max_bytes_per_shard: 2GB
    tsdb_max_query_parallelism: 2048
  rulerConfig:
    alertmanager_url: SECRET
    enable_alertmanager_v2: true
    enable_api: true
  schemaConfig:
    configs:
    - from: "2024-07-29"
      index:
        period: 24h
        prefix: index_
      object_store: azure
      schema: v13
      store: tsdb
  server:
    grpc_listen_port: 9095
    grpc_server_max_recv_msg_size: 60000000
    grpc_server_max_send_msg_size: 60000000
    http_listen_port: 3100
    http_server_idle_timeout: 600s
    log_level: debug
  storage:
    azure:
      accountKey: CREDENTIALS
      accountName: CREDENTIALS
      requestTimeout: 30s
      useManagedIdentity: false
    bucketNames:
      admin: loki
      chunks: loki
      ruler: loki
    type: azure
  storage_config:
    boltdb_shipper: null
    tsdb_shipper:
      index_gateway_client:
        grpc_client_config:
          connect_timeout: 1s
        log_gateway_requests: true
  tracing:
    enabled: true
lokiCanary:
  enabled: false
minio:
  enabled: false
monitoring:
  dashboards:
    enabled: false
  lokiCanary:
    enabled: false
  rules:
    alerting: false
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  serviceMonitor:
    enabled: false
    metricsInstance:
      enabled: false
nameOverride: loki
querier:
  extra_query_delay: 500ms
  frontend_worker:
    grpc_client_config:
      max_send_msg_size: 60000000
  max_concurrent: 6
query_range:
  max_concurrent: 6
  parallelise_shardable_queries: true
  results_cache:
    cache_results: true
    cache_validity: 5m
  split_queries_by_interval: 1h
query_scheduler:
  max_outstanding_requests_per_tenant: 1000
rbac:
  namespaced: true
read:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: projectId
              operator: In
              values:
              - 27edfc6c-eb78-4790-a6c8-ed82a0478f7c
          topologyKey: kubernetes.io/hostname
        weight: 100
    podAntiAffinity: null
  extraEnv:
  - name: GOMEMLIMIT
    valueFrom:
      resourceFieldRef:
        resource: limits.memory
  - name: GOMAXPROCS
    valueFrom:
      resourceFieldRef:
        resource: limits.cpu
  nodeSelector:
    dedicated: logs-instance
  persistence:
    enableStatefulSetAutoDeletePVC: true
    size: 16Gi
    storageClass: csi-cinder-sc-delete
  podAnnotations:
    port: "3100"
    type: loki-read
  podLabels:
    name: dev-test-multiple-change
    scrape: "true"
    projectId: 27edfc6c-eb78-4790-a6c8-ed82a0478f7c
    app: logs
    team: mops
  replicas: 3
  resources:
    limits:
      cpu: 3
      memory: 2560Mi
    requests:
      cpu: 100m
      memory: 1280Mi
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: logs-instance
resultsCache:
  enabled: false
sidecar:
  rules:
    enabled: false
test:
  enabled: false
write:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: projectId
              operator: In
              values:
              - 27edfc6c-eb78-4790-a6c8-ed82a0478f7c
          topologyKey: kubernetes.io/hostname
        weight: 100
    podAntiAffinity: null
  autoscaling:
    behavior:
      scaleDown:
        policies:
        - periodSeconds: 1800
          type: Pods
          value: 1
        stabilizationWindowSeconds: 3600
      scaleUp:
        policies:
        - periodSeconds: 900
          type: Pods
          value: 1
    enabled: true
    maxReplicas: 25
    minReplicas: 1
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 80
  extraEnv:
  - name: GOMEMLIMIT
    valueFrom:
      resourceFieldRef:
        resource: limits.memory
  - name: GOMAXPROCS
    valueFrom:
      resourceFieldRef:
        resource: limits.cpu
  nodeSelector:
    dedicated: logs-instance
  persistence:
    enableStatefulSetAutoDeletePVC: true
    size: 16Gi
    storageClass: csi-cinder-sc-delete
  podAnnotations:
    port: "3100"
    type: loki-write
  podLabels:
    scrape: "true"
    projectId: 27edfc6c-eb78-4790-a6c8-ed82a0478f7c
    app: logs
    team: mops
  replicas: 1
  resources:
    limits:
      memory: 2474Mi
    requests:
      cpu: 625m
      memory: 2474Mi
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: logs-instance

```
- If you have no query problems, redeploy using helm upgrade. Do the process multiple times (can take 1 time or it can 20)
- At some point, you will get a "bad deploymend" and one of the read pods will no longer be able to make queries

**Screenshots, Promtail config, or terminal output**

So at first, i thought my problem was linked to the previously mentionned issue and it might be linked to what some users are facing since this problem does end up with 504 Gateway timeout when it happens. It does also make this error in our nginx pods that is linked to our ingress:

`10.171.106.139 - - [28/Nov/2024:20:59:22 +0000] "GET /loki/api/v1/labels?start=1732826612721000000&end=1732827512721000000 HTTP/1.1" 499 0 "-" "Grafana/11.1.3" 3985 49.972 [6723a512e7641cd9c37269ed-loki-read-3100] [] 172.16.6.5:3100 0 49.971 - 8ee94e8c2e23c4261ecbd3e8c037d4bb`

In this case, the bad pod being 172.16.6.5 among my 3 read pods. So seing this error, i tried:

- upgrading to latest version of cilium, now being 1.16.4. Did not help on the issue
- Looking at some threads around github, i tried to set:
```
    socketLB:
      enabled: true
      terminatePodConnections: true
```
on my cilium setup, it did not help
- I removed the old index config attached to my grafana loki (boltdb-shipper) and keep only the tsdb_shipper. It did not help.

I then tried to execute the query directly in the pod. Using port forwarding, i then executed the following request to the "tainted" read pod:

`http://localhost:50697/loki/api/v1/query_range?direction=backward&end=1732889832897000000&limit=1000&query=%7Bproject_id%3D%2227edfc6c-eb78-4790-a6c8-ed82a0478f7c%22%7D+%7C%3D+%60%60&start=1732886232897000000&step=2000ms`

<img width="960" height="379" alt="Image" src="https://github.com/user-attachments/assets/fb13863c-1196-4ef5-8135-713211eab8de" />

This result in a request that just returned...nothing. I waited 30 minutes and POSTMAN and only got this log line confirming the pod received the query:

`level=info ts=2024-11-29T15:58:49.425174467Z caller=roundtrip.go:364 org_id=fake traceID=761b6d90af6ae5c8 msg="executing query" type=range query="{project_id=\"27edfc6c-eb78-4790-a6c8-ed82a0478f7c\"} |= ``" start=2024-11-29T13:17:12.897Z end=2024-11-29T14:17:12.897Z start_delta=2h41m36.528171657s end_delta=1h41m36.528171836s length=1h0m0s step=2000 query_hash=2028412130`

When trying the same request to a different pod on the same helm release, i get the correct http response:

<img width="774" height="277" alt="Image" src="https://github.com/user-attachments/assets/372aba27-dc21-4a2b-b666-1cb4369e3c72" />

And i can see the grafana loki logs telling me the query was a success.

If you do query through grafana, at some point, you will hit the bad pod and result in either EOF error or a 504 gateway timeout. I already posted the nginx eror log, see above.

**How to fix**

This is a temporary fix, but the only known workaround is to simply restart the read pods. Thats it. If you redo a helm upgrade, there is a chance that the same scenario repeats itself. This should not be a problem and at this point, i almost certain its a Loki problem and not a networking problem. Although, if some Grafana loki dev could help me find a way to check what my read pod is missing or why its in a bad state, ill take any suggestion.

**Comment by JStickler** [comment]
>Deploy with the following 3 read pods, 1 backend pod,1 write pod and 1 gateway pod. 
 Curious why you aren't following the recommendations from the [documentation](https://grafana.com/docs/loki/latest/setup/install/helm/install-scalable/) which is for 3 read, 3 write, 3 backend components?  My suspicion is that only having a single Query Scheduler and a single Index Gateway may be part of the problem here, as those support the Read components during querying.

**Comment by someStrangerFromTheAbyss** [comment]
Yeah i just added that last friday to our DEV/QA ENV and the bad Read pod problems seems to dissapear. I havent updated the issue since i want client confirmation that the fix works.

However, should't work even with one backend pod ? Also, it seems many users also has the 499 bug like mentionned in the other issues.

**Comment by JStickler** [comment]
>If its necessary for loki to have more then 1 backend pod, should't the app stop working if it has 1 instance of a backend ?

Not necessarily.  From my understanding of Kubernetes (I'm a technical writer, not a developer or SysAdmin), you might be scaling up or down, upgrading, pods might be restarting.  The idea of having more than one pod is to allow for fluctuations in the number of running pods so that the system stays up if one pod goes down for some reason.  It also helps balance the load if there's more work than one pod can handle.

**Comment by systobe** [comment]
Same issue here. 2x read, 2x write, 2x backend.

**Comment by yongzhang** [comment]
https://github.com/grafana/loki/issues/7496

**Comment by someStrangerFromTheAbyss** [comment]
A bit late to respond to the thread, but i'm reporting the problem is still present, just happens less often with more then 2 backends.

I confirm that the issue @yongzhang  linked is similar to this one, although its not just the labels request that is the problem....queries seems to be also impacted.

**Comment by Niles-dev** [comment]
Hello,
Can confirm I had the same problem with the following versions:
* Deployed using the official Helm chart of loki, version 6.24.0
* Deploying Grafana loki using version 3.3.2
* Deployed on Microk8s with Calico as a CNI
* with default pod values (3 read, 3 write, 3 backend)

I identified the loki read pod which was not working with kube-forward, killed it, and the new one was working as intended.

**Comment by felipewnp** [comment]
I too have the same problem (I guess).

I thought it was exclusively related to cilium, but since I've changed the cilium config AND deployed a dnsmasq sidecar to loki-gateway, I'm beginning to doubt the problem is on loki-gateway.

An example of what happened on 29/01/2025 but not on 30/01/2025:

(over 2 thousand lines of these logs between 03:22 and 06:15 UTC):

![Image](https://github.com/user-attachments/assets/01a19ae3-8924-4379-9654-226b4e424ee3)

**Comment by rainchik** [comment]
Greetings

The same issue:
Loki 3.3.2
Chart ver: 6.18.0
SSD mode: 2 backend, 2 read (min, HPA to 10 max), 2 write (min, HPA to 5 max).
After some specific backend restarts, some of readers "hangs" and cannot respond to any requests (loki/api/v1/labels, /loki/api/v1/series, etc)

Can't find anything in logs, after call /loki/api/v1/labels for example, I just get
`
level=info ts=2025-02-06T15:00:47.421278402Z caller=roundtrip.go:414 org_id=fake msg="executing query" type=labels label= length=1h0m0s query=
` 

in Reader logs and then cut the request by timeout. No any errors, also nothing in debug level logs. 
I also checked :3100/memberlist and :3100/services links on components, looks like all components are running, seeing each other, the cluster it working and syncing. But frontend component (I guess, not sure) just not response for queries (but reports it's working).

The screenshots are from simpler configuration with 1-1-1 backend-reader-writer - I just tried to reproduce and catch the issue.

<img width="1506" alt="Image" src="https://github.com/user-attachments/assets/6b06a867-e2a5-4c05-92fd-4a480bddd407" />

<img width="371" alt="Image" src="https://github.com/user-attachments/assets/de9a5d55-0d21-48b0-83d2-d30030302f43" />

**Comment by felipewnp** [comment]
This doesn't seem to happen when using singleBinary mode.

I've been using singleBinary for almost a week without issues.

Can anyone else try it out and confirm?

**Comment by someStrangerFromTheAbyss** [comment]
Hello.

Just want to update, i had no time to check the bug more. It still happen in our PROD environment, but very rarely. Very incosistent.

@felipewnp I havent checked with singleBinaryMode. Maybe if i have time ill check,but even so, i don't think we will switch to singleBinaryMode

**Comment by felipewnp** [comment]
> Hello [@felipewnp](https://github.com/felipewnp)
> 
> > This doesn't seem to happen when using singleBinary mode.
> 
> Looks like this issue is about communications between "read" and "backend" components, so if we use singleBinary we don't have network level communications between components

True.

Since this solved this major headache, we are keeping the SingleBinaryMode for now, with 2 big replicas.

I will keep you guys posted though, and I'm available to test new releases or workarounds.

**Comment by someStrangerFromTheAbyss** [comment]
After some digging, we figured out on our side that what might be the best solution would be to add a livenessprobe to the /labels.

We will try it out this quarter and if it works, i will let everyone know in this thread.

**Comment by someStrangerFromTheAbyss** [comment]
@JStickler  Sorry to bother you, but no one seems to be checking the merge. Can you take a look ?

Thanks.

**Comment by JStickler** [comment]
@someStrangerFromTheAbyss "no one seems to be checking the merge."  Do you mean on #17063?

**Comment by someStrangerFromTheAbyss** [comment]
Yes. Is it supose to be automatic or someone needs to review from the loki team ? Its been a week, i passed the checks two times, but sometimes it fails for no reason. So maybe something that is automatic is not picking my merge ? if so, no idea what.

**Comment by JStickler** [comment]
All PRs need to a review from someone on the Loki team before they can be merged. As the technical writer, I only approve docs updates.

**Comment by someStrangerFromTheAbyss** [comment]
Still waiting for someone to check my PR...if someone knows a Loki dev that can go check:
https://github.com/grafana/loki/pull/17063

That would be nice. The PR is still in pending for review and its been almost a month.... Only update i have is that me and my partner were asked to sign the CLA. So still waiting.

**Comment by felipewnp** [comment]
Hi @periklis @ashwanthgoli 

Could anyone help out with this?

**Comment by someStrangerFromTheAbyss** [comment]
@duj4 My MR is still in review....To be honest, quite dissapointed in the Grafana team...Nobody communicated with me for the MR and nobodies came check for it. Its been almost 2 months... I saw there is a big MR being made by someone to add livenessProbe to all components. Maybe thats why my MR is being not looked at.

We forked the repo and we are pushing the livenessProbe soon too all our clients. Ill update the issue if it solved the issue.

**Comment by someStrangerFromTheAbyss** [comment]
Also, the issue is technically not fixed.... Can someone re-open the issue ?

**Comment by JStickler** [comment]
Yes, I can re-open this issue.

**Comment by someStrangerFromTheAbyss** [comment]
Update here.

I pushed the update of the livenessProbe to most of our client. Saw the problem happend, the livenessProbe failed, then the read pod restarted and the client confirmed no problem on his part. So i can confirm, it seems to be a viable workaround for that problem.

Now, its not a...perfect solution. If the write pods has problems, then the read pods will bootloop now, which was not happening before....

I assume also that if the read is under A LOT of stress or you have some CPU throttling in place, this solution cannot be used.

But for everyone else, that should work.

Keeping the issue alive until a loki dev maybe take a look...

**Comment by duj4** [comment]
@someStrangerFromTheAbyss thanks for the update, may I know what version of Loki you and your customers are using?

**Comment by someStrangerFromTheAbyss** [comment]
@duj4  We are currently using loki 3.4.3. I know we are not up to date, but from what i saw of the changelog, no major bugfix for that problem. Will try to upgrade to latest at the end of the year.

**Comment by duj4** [comment]
> [@duj4](https://github.com/duj4) We are currently using loki 3.4.3. I know we are not up to date, but from what i saw of the changelog, no major bugfix for that problem. Will try to upgrade to latest at the end of the year.

Thanks @someStrangerFromTheAbyss for the reply, we are still running on 3.4.2, but the livenessProbe is the same. Besides, we enabled `auth_enabled` and TLS for all components (read, write and backend), the normal livenessProbe may not work as it does not support mTLS. However, we figured out another way for the same purpose and it is testing in the QA env right now, which looks good so far.

**Comment by Pionerd** [comment]
Please reopen (again) until the root cause is addressed.

**Comment by someStrangerFromTheAbyss** [comment]
@JStickler @Jayclifford345   Can you re-open the issue ? The MR does not fix the problem.

Was going to do an update on this issue since we did find problems with the livenessProbe but i was very busy.

So its been 3 months since we implemented to clients. We had to remove the livenessProbe after 2 weeks. The impact on read pods was too much. When under a lot of stress, the pods start to bootloop, which is not something we want.

After some discussion in our team, we did find another solution: 
startupProbe

We did figure some key findings:

- The bad read pods is, most of the time, the first one that spawn. Only in rare cases, the second read pod is affected
- It only happens at deployment 

Knowing that, we implement a startupProbe by forking the helm chart. We do intend to contribute  once more to the official helm chart, but the experience from the previous change was bad, it took so long to get a review. For now, we just decided to fork. Once we confirm the issue is gone, we will try to find some time to contribute to the helm chart to add startupProbe.

As of today, adding a startupProbe seems to fix the issue. We did had to do some tinkering to get it right though (add delay, reduce timeout,etc). So we are waiting a month or two before contributing to the helm chart. We do want the change in the official chart so we dont have to host it.

For people who are, like us, stuck because of this problem, here is our current startUpProbe:

```
startupProbe:
  httpGet:
    path: /loki/api/v1/labels?since=1h
    port: 3100
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 1
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3
```

Again, not confirmed it works 100% of the time. Seems to work most of the time though and you will have to fork the helm chart for now since read pods does not support startUpProbe.

Thank you.
