### ISSUE TITLE
[BUG] Loki compactor in AWS CN EKS crashes with InvalidToken: The provided token is malformed or otherwise invalid

### ISSUE THREAD

**Issue by gn-hiro-v** [grafana/loki#15379]
<!-- Please keep the structure below, or your issue may be closed. -->

**Describe the bug**
- I was deploying loki in both AWS international regions and AWS China. The international AWS region works fine.
- However, in AWS China, only `compactor` pod crashes and here is the error
```
│ level=info ts=2024-12-12T04:21:14.588906833Z caller=main.go:126 msg="Starting Loki" version="(version=release-3.3.x-60f2af3, branch=release-3.3.x, revision=60f2af32)"                                                                                                                                │
│ level=info ts=2024-12-12T04:21:14.588954984Z caller=main.go:127 msg="Loading configuration file" filename=/etc/loki/config/config.yaml                                                                                                                                                                │
│ level=info ts=2024-12-12T04:21:14.59177017Z caller=server.go:351 msg="server listening on addresses" http=:3100 grpc=:9095                                                                                                                                                                            │
│ level=info ts=2024-12-12T04:21:14.595201715Z caller=memberlist_client.go:439 msg="Using memberlist cluster label and node name" cluster_label= node=loki-compactor-0-d7b3df81                                                                                                                         │
│ level=info ts=2024-12-12T04:21:14.597680315Z caller=memberlist_client.go:549 msg="memberlist fast-join starting" nodes_found=1 to_join=4                                                                                                                                                              │
│ level=info ts=2024-12-12T04:21:14.61287991Z caller=memberlist_client.go:569 msg="memberlist fast-join finished" joined_nodes=6 elapsed_time=15.202955ms                                                                                                                                               │
│ level=info ts=2024-12-12T04:21:14.612927801Z caller=memberlist_client.go:581 phase=startup msg="joining memberlist cluster" join_members=loki-memberlist                                                                                                                                              │
│ level=info ts=2024-12-12T04:21:14.628418061Z caller=memberlist_client.go:588 phase=startup msg="joining memberlist cluster succeeded" reached_nodes=6 elapsed_time=15.48115ms                                                                                                                         │
│ init compactor: failed to init delete store: failed to get s3 object: InvalidToken: The provided token is malformed or otherwise invalid.                                                                                                                                                             │
│     status code: 400, request id: <>, host id: <>
│
│ error initialising module: compactor                                                                                                                                                                                                                                                                  │
│ github.com/grafana/dskit/modules.(*Manager).initModule                                                                                                                                                                                                                                                │
│     /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138                                                                                                                                                                                                                                  │
│ github.com/grafana/dskit/modules.(*Manager).InitModuleServices                                                                                                                                                                                                                                        │
│     /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108                                                                                                                                                                                                                                  │
│ github.com/grafana/loki/v3/pkg/loki.(*Loki).Run                                                                                                                                                                                                                                                       │
│     /src/loki/pkg/loki/loki.go:492                                                                                                                                                                                                                                                                    │
│ main.main                                                                                                                                                                                                                                                                                             │
│     /src/loki/cmd/loki/main.go:129                                                                                                                                                                                                                                                                    │
│ runtime.main                                                                                                                                                                                                                                                                                          │
│     /usr/local/go/src/runtime/proc.go:272                                                                                                                                                                                                                                                             │
│ runtime.goexit                                                                                                                                                                                                                                                                                        │
│     /usr/local/go/src/runtime/asm_amd64.s:1700                                                                                                                                                                                                                                                        │
│ level=error ts=2024-12-12T04:21:19.868145407Z caller=log.go:216 msg="error running loki" err="init compactor: failed to init delete store: failed to get s3 object: InvalidToken: The provided token is malformed or otherwise invalid
```
- Other pods look fine
![Image](https://github.com/user-attachments/assets/8416a152-b280-423b-98f0-c2a30d34292a)

**To Reproduce**
1. Loki helm from `https://grafana.github.io/helm-charts` with `loki` chart version `6.23.0`
2. Deploy in EKS in AWS CN
3. The config
```
    auth_enabled: false
    bloom_build:
      builder:
        planner_address: loki-bloom-planner-headless.monitoring.svc.cluster.local:9095
      enabled: false
    bloom_gateway:
      client:
        addresses: dnssrvnoa+_grpc._tcp.loki-bloom-gateway-headless.monitoring.svc.cluster.local
      enabled: false
    chunk_store_config:
      chunk_cache_config:
        background:
          writeback_buffer: 500000
          writeback_goroutines: 1
          writeback_size_limit: 500MB
        default_validity: 0s
        memcached:
          batch_size: 4
          parallelism: 5
        memcached_client:
          addresses: dnssrvnoa+_memcached-client._tcp.loki-chunks-cache.monitoring.svc
          consistent_hash: true
          max_idle_conns: 72
          timeout: 2000ms
    common:
      compactor_address: 'http://loki-compactor:3100'
      path_prefix: /var/loki
      replication_factor: 3
      storage:
        s3:
          bucketnames: loki-aws-dev-chunks-3
          insecure: false
          region: us-east-1
          s3forcepathstyle: false
    compactor:
      delete_request_store: s3
      retention_enabled: true
    frontend:
      scheduler_address: loki-query-scheduler.monitoring.svc.cluster.local:9095
      tail_proxy_url: http://loki-querier.monitoring.svc.cluster.local:3100
    frontend_worker:
      scheduler_address: loki-query-scheduler.monitoring.svc.cluster.local:9095
    index_gateway:
      mode: simple
    ingester:
      chunk_encoding: snappy
    limits_config:
      allow_structured_metadata: true
      max_cache_freshness_per_query: 10m
      query_timeout: 300s
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 672h
      split_queries_by_interval: 15m
      volume_enabled: true
    memberlist:
      join_members:
      - loki-memberlist
    pattern_ingester:
      enabled: true
    querier:
      max_concurrent: 4
    query_range:
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          background:
            writeback_buffer: 500000
            writeback_goroutines: 1
            writeback_size_limit: 500MB
          default_validity: 12h
```
4. Check the log for compactor


**Expected behavior**
- Loki `compactor` pod works fine


**Environment:**
 - Infrastructure: EKS in AWS China (`cn-northwest-1`)
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
