### ISSUE TITLE
loki 2.9.0 to 3.0.0 upgrade issue: flag provided but not defined: -boltdb.shipper.compactor.working-directory

### ISSUE THREAD

**Issue by yasharne** [grafana/loki#15422]
**Describe the bug**
I have made all the changes needed for upgrading from 2.9.0 to 3.0.0 described here: https://grafana.com/docs/loki/latest/setup/upgrade/#300
All components are up as expected, but compactor is in crashloopbackoff with this error:
```
flag provided but not defined: -boltdb.shipper.compactor.working-directory
Run with -help to get list of available parameters
```
here is my compactor config section:
```
compactor:
  working_directory: /var/loki/compactor
  compaction_interval: 10m
  delete_request_cancel_period: 15m
  delete_request_store: s3
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  compactor_ring:
    kvstore:
        store: memberlist
```

**To Reproduce**
1. update loki to version 3.0.0

**Expected behavior**
Compactor start working

**Environment:**
 - Infrastructure: openshift
 - Deployment tool:helm

**Screenshots, Promtail config, or terminal output**
