### ISSUE TITLE
memchached cache (chunks-cache) can not be disabled

### ISSUE THREAD

**Issue by zizekuros** [grafana/loki#15439]
**Describe the bug**
I am trying to deploy Loki in EKS with Helm, but I'm having issues with chunks-cache

```
kubectl logs statefulset.apps/loki-chunks-cache -n monitoring
```
or
```
kubectl logs pod/loki-chunks-cache-0 -n monitoring
```
gives me:
```
Defaulted container "memcached" out of: memcached, exporter
```

So I wanted to disable the memcached as I don't really need caching.

I have configured following values. Put them both into the root values and loki.memcached.chunk_cache and loki.memcached.results_cache:
```
memcached:
  chunk_cache:
    enabled: false
  results_cache:
    enabled: false
````

However, chunks-cache is still launched and stuck in pending due to missing memcached service.

**To Reproduce**
1. Helm values:

```
loki:
  # disable memcached cache
  memcached:
    chunk_cache:
      enabled: false
    results_cache:
      enabled: false

  auth_enabled: false # if this is set to false, then multi-tenant is disabled and no X-Scope-OrgID is required

  commonConfig:
    replication_factor: 1 # must be set to 1 if you want to run write/read as single replica
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      region: eu-central-1
      bucketnames: {my-chunk-bucket}
      s3forcepathstyle: false
  pattern_ingester:
      enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h # 28 days retention
  querier:
    max_concurrent: 4

  storage:
    type: s3
    bucketNames:
        chunks: {my-chunk-bucket}
        ruler: {my-ruler-bucket}
        admin: {my-admin-bucket}
    s3:
      # s3 URL can be used to specify the endpoint, access key, secret key, and bucket name this works well for S3 compatible storages or if you are hosting Loki on-premises and want to use S3 as the storage backend. Either use the s3 URL or the individual fields below (AWS endpoint, region, secret).
      #s3: s3://access_key:secret_access_key@custom_endpoint/bucket_name
      s3: null
      # AWS endpoint URL
      endpoint: s3.eu-central-1.amazonaws.com
      # AWS region where the S3 bucket is located
      region: eu-central-1
      # AWS secret access key
      secretAccessKey: {my-secret-access-key}
      # AWS access key ID
      accessKeyId: {my-access-key-id}
      # AWS signature version (e.g., v2 or v4)
      signatureVersion: null
      # Forces the path style for S3 (true/false)
      s3ForcePathStyle: false
      # Allows insecure (HTTP) connections (true/false)
      insecure: false
      # HTTP configuration settings
      http_config: {}

deploymentMode: SimpleScalable

# disable memcached cache
memcached:
  chunk_cache:
    enabled: false
  results_cache:
    enabled: false

backend:
  replicas: 1
  persistence:
    volumeClaimsEnabled: false
    dataVolumeParameters:
      emptyDir: {}
read:
  replicas: 1
write:
  replicas: 1
  persistence:
    volumeClaimsEnabled: false
    dataVolumeParameters:
      emptyDir: {}

gateway:
  enabled: false

# Disable minio storage
minio:
  enabled: false
````

2. Install Loki with helm
```
helm install --values my-values.yaml loki grafana/loki -n monitoring
```

**Expected behavior**
Cache to be disabled.

**Environment:**
 - Infrastructure: Kubernetes (EKS)
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
```
NAME                             READY   STATUS    RESTARTS   AGE
pod/loki-backend-0               2/2     Running   0          36m
pod/loki-canary-9gxrt            1/1     Running   0          36m
pod/loki-canary-thv87            1/1     Running   0          36m
pod/loki-chunks-cache-0          0/2     Pending   0          36m
pod/loki-read-5f95957c96-jqpvj   1/1     Running   0          36m
pod/loki-results-cache-0         2/2     Running   0          36m
pod/loki-write-0                 1/1     Running   0          36m

NAME                                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)              AGE
service/loki-backend                     ClusterIP   10.100.161.235   <none>        3100/TCP,9095/TCP    36m
service/loki-backend-headless            ClusterIP   None             <none>        3100/TCP,9095/TCP    36m
service/loki-canary                      ClusterIP   10.100.29.183    <none>        3500/TCP             36m
service/loki-chunks-cache                ClusterIP   None             <none>        11211/TCP,9150/TCP   36m
service/loki-memberlist                  ClusterIP   None             <none>        7946/TCP             36m
service/loki-query-scheduler-discovery   ClusterIP   None             <none>        3100/TCP,9095/TCP    36m
service/loki-read                        ClusterIP   10.100.75.1      <none>        3100/TCP,9095/TCP    36m
service/loki-read-headless               ClusterIP   None             <none>        3100/TCP,9095/TCP    36m
service/loki-results-cache               ClusterIP   None             <none>        11211/TCP,9150/TCP   36m
service/loki-write                       ClusterIP   10.100.241.40    <none>        3100/TCP,9095/TCP    36m
service/loki-write-headless              ClusterIP   None             <none>        3100/TCP,9095/TCP    36m

NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/loki-canary   2         2         2       2            2           <none>          36m

NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/loki-read   1/1     1            1           36m

NAME                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/loki-read-5f95957c96   1         1         1       36m

NAME                                  READY   AGE
statefulset.apps/loki-backend         1/1     36m
statefulset.apps/loki-chunks-cache    0/1     36m
statefulset.apps/loki-results-cache   1/1     36m
statefulset.apps/loki-write           1/1     36m
```
