### ISSUE TITLE
Promtail add static_labels for specific log entry

### ISSUE THREAD

**Issue by freedomwarrior** [grafana/loki#15565]
Hello!
Got problem with promtailand loki
I need to add `static_labels `based on specific log entry
This is my last version of config
```
  pipeline_stages:
  - json:
      expressions:
        output: log
        stream: stream
        attrs:
  - json:
      expressions:
        tag:
      source: attrs
  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: tag
  - timestamp:
      format: RFC3339Nano
      source: time
  - match:
      selector: '{source="output"}'
      stages:
        - regex:
            expression: ".*GET \/health.*"
            source: "output"
        - static_labels:
            retention_period: "1d"
  - labels:
      tag:
      stream:
      image_name:
      container_name:
      image_id:
      container_id:
  - output:
      source: output
```
And I did not see `retention_period `label in Loki
Log entry looks like this
`INFO:     127.0.0.1:52252 - "GET /health HTTP/1.1" 200 OK`

**Comment by freedomwarrior** [comment]
Resolved
```
  - match:
      selector: '{job="dockerlogs"} |~ ".*GET \/health.*"'
      stages:
      - static_labels:
          custom_retention_period: "1d"
```
