### ISSUE TITLE
can run loki with tls: unable to find pem data

### ISSUE THREAD

**Issue by Dialgatrainer02** [grafana/loki#15602]
**Describe the bug**
when running loki with tls enabled it fails to start becuase it cant load the certificate due to no data

**To Reproduce**
1. use step ca to provision certificates
2. move certificate to host
3. run loki using this config
```yaml
target: all
auth_enabled: False
ballast_bytes: 0
server:
  http_listen_port: 3100
  http_tls_config:
    cert: /etc/ssl/step.crt
    key: /etc/ssl/step.key

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

ruler:
  storage:
    type: local
    local:
      directory: /var/lib/loki/rules
  rule_path: /var/lib/loki/rules_tmp
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true
  alertmanager_url: http://localhost:9093

storage_config:
  aws:
    insecure: false
    s3: s3://loki:<secret>@minio-1.internal/loki-chunk
    s3forcepathstyle: true
  tsdb_shipper:
    active_index_directory: /var/lib/loki/loki/index
    cache_location: /var/lib/loki/loki/index_cache

schema_config:
  configs:
  - from: '2025-01-05'
    index:
      period: 24h
      prefix: index_
    object_store: s3
    schema: v13
    store: tsdb

analytics:
  reporting_enabled: false

common:
  instance_addr: 127.0.0.1
  path_prefix: / ##was /var/lib/loki change to see if its searching in the wrong place
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
```
4. see error in journal

**Expected behavior**
loki runs with tls enabled

**Environment:**
 - Infrastructure: almalinux proxmox lxc
 - Deployment tool:  terraform and ansible

**Screenshots, Promtail config, or terminal output**

![Image](https://github.com/user-attachments/assets/a34bd4f7-abc3-433e-9323-74eaf2df9ba5)

![Image](https://github.com/user-attachments/assets/0838e94b-3029-4564-9846-0b06b21de654)

![Image](https://github.com/user-attachments/assets/fff2551e-0c8e-449b-829e-e7aff429ed54)
(im going to regen all the certs but its definatly valid)
