### ISSUE TITLE
Excessive Log output of the loki service with "INFO" level.

### ISSUE THREAD

**Issue by The-M1k3y** [grafana/loki#15624]
**Describe the bug**

Excessive Log output of the loki service with "INFO" level.
Without setting the log level in the configuration, loki seems to be using the "INFO" log level. This is fine, but the info level produces an enormous amount of output, most of which I would consider to be more suitable for the "DEBUG" level.

Example:
```
prometheus-loki  | level=info ts=2025-01-07T13:51:07.791400274Z caller=table_manager.go:136 index-store=tsdb-2024-04-01 msg="uploading tables"
prometheus-loki  | level=info ts=2025-01-07T13:51:07.791449365Z caller=index_set.go:86 msg="uploading table index_20069"
prometheus-loki  | level=info ts=2025-01-07T13:51:07.791458535Z caller=index_set.go:107 msg="finished uploading table index_20069"
prometheus-loki  | level=info ts=2025-01-07T13:51:07.791465782Z caller=index_set.go:185 msg="cleaning up unwanted indexes from table index_20069"
prometheus-loki  | level=info ts=2025-01-07T13:51:07.791473502Z caller=index_set.go:86 msg="uploading table index_20095"
prometheus-loki  | level=info ts=2025-01-07T13:51:07.791478954Z caller=index_set.go:107 msg="finished uploading table index_20095"
prometheus-loki  | level=info ts=2025-01-07T13:51:07.791484733Z caller=index_set.go:185 msg="cleaning up unwanted indexes from table index_20095"
```

The last 3 lines are repeated hundreds of times and this block is produced every minute, generating over 1GB of logs every month. Except for the first line, this seems to be more suitable for the "DEBUG" level.

**To Reproduce**

1. Deploy any default configuration loki instance without changing the log level. Observed in docker environment but should be the same for every type of deployment.

**Expected behavior**

A sane amount of logs produced by the "INFO" level.

**Environment:**

 - Infrastructure: docker
 - Deployment tool: docker compose

**Screenshots, Promtail config, or terminal output**

Loki configuration:
```
auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  filesystem:
    directory: /loki/storage

schema_config:
  configs:
    - from: 2024-04-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
```

docker compose configuration (shortened):
```
services:
  loki:
    image: grafana/loki
    container_name: prometheus-loki
    restart: unless-stopped
    command: ["-config.file=/etc/loki/local-config.yaml"]
    user: "0"
    # limit log size due to execessive log output of loki
    logging:
      options:
        max-size: 100m
    volumes:
      - ./loki_config/:/etc/loki
      - /monitoring-data/loki:/loki
```
