### ISSUE TITLE
Promtail 1.3: field relabel_configs not found in type scrape.JournalTargetConfig

### ISSUE THREAD

**Issue by WeiBanjo** [grafana/loki#1568]
**Describe the bug**
Promtail fails to start on 1.3 when we have `relabel_configs` in journal configuation

**To Reproduce**
1. Upgrade Promtail from 1.2 to 1.3

**Expected behavior**
Promtail works on 1.3

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
 ### Promtail configuration
This configuration is based on [example](https://github.com/grafana/loki/blob/874d016bd75a6037b6553998f96b212e515b400c/docs/clients/promtail/scraping.md#journal-scraping-linux-only)
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
  namespace: devops
  labels:
    app: promtail
    chart: promtail-0.16.2
    release: promtail
    heritage: Tiller
data:
  promtail.yaml: |
    client:
      backoff_config:
        maxbackoff: 5s
        maxretries: 20
        minbackoff: 100ms
      batchsize: 102400
      batchwait: 5s
      external_labels: {}
      timeout: 10s
    positions:
      filename: /run/promtail/positions.yaml
    server:
      http_listen_port: 3101
    target_config:
      sync_period: 30s
    scrape_configs:
    - job_name: journal-log
      journal:
        json: false
        labels:
          job: systemd-journal
        max_age: 1h
        path: /var/log/journal
        relabel_configs:
        - source_labels:
          - __journal__systemd_unit
          target_label: unit
```

 ### Promtail crash log
```
Unable to parse config: /etc/promtail/promtail.yaml: yaml: unmarshal errors:
  line 276: field relabel_configs not found in type scrape.JournalTargetConfig
```

**Comment by rfratto** [comment]
Hi! There's a subtle difference between the example and the config you posted: `relabel_configs` needs to be outdented one level: 

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
  namespace: devops
  labels:
    app: promtail
    chart: promtail-0.16.2
    release: promtail
    heritage: Tiller
data:
  promtail.yaml: |
    client:
      backoff_config:
        maxbackoff: 5s
        maxretries: 20
        minbackoff: 100ms
      batchsize: 102400
      batchwait: 5s
      external_labels: {}
      timeout: 10s
    positions:
      filename: /run/promtail/positions.yaml
    server:
      http_listen_port: 3101
    target_config:
      sync_period: 30s
    scrape_configs:
    - job_name: journal-log
      journal:
        json: false
        labels:
          job: systemd-journal
        max_age: 1h
        path: /var/log/journal
      relabel_configs:
      - source_labels:
        - __journal__systemd_unit
        target_label: unit
```
