### ISSUE TITLE
OOM issue (8GB RAM) when querying for 2 days of data

### ISSUE THREAD

**Issue by muzzah** [grafana/loki#15711]
**Describe the bug**
I have a single machine with 8GB of ram I run at home. It has around 10 docker containers behind a nginx container. Its access logs among other access logs (e.g systemd journal) are shipped to loki using promtail. We are talking maybe 10-15 logs every few seconds in total max being ingested by loki.

I have grafana as a graphing and alerting frontend. One dashboard I have setup is very similar to https://grafana.com/grafana/dashboards/12559-loki-nginx-service-mesh-json-version/

It shows me total request, status codes, different paths Im interested in etc. Maybe around 20 different graphs on a single page. 
When I set the time range for 1 day, all graphs load fine. 

If I shift to two days of data loki shits itself and OOMs as below

Ive noticed that Ive had to increase the max_query_bytes_read limit to around 800MB to satisfy some of the graphs data usage when time range is last 2 days.
  
My config is as below 

```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  parallelise_shardable_queries: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

query_scheduler:
  max_outstanding_requests_per_tenant: 4096

frontend:
  max_outstanding_per_tenant: 1024

limits_config:
  split_queries_by_interval: 30m
  max_concurrent_tail_requests: 4
  max_query_parallelism: 4
  max_query_series: 1000
  max_line_size: 0
  per_stream_rate_limit: 100MB
  ingestion_rate_mb: 100
  max_query_bytes_read: 800000000
  tsdb_max_query_parallelism: 4
```

Some of the queries which seem to be loading a bit of data (~700MB, if i reduce the max query bytes read to something like 300MB these graphs fail to load )

```
count by(http_host) (count_over_time({filename="/var/log/dockernginx/access.log"} | json [$__auto]))
```

```
 sum(rate({filename="/var/log/dockernginx/access.log", host="$host"} | json | status >= 500 |__error__=""[$__interval])) 
```

```
{filename="/var/log/dockernginx/access.log", host="$host"} | json | body_bytes_sent > 5500000 | line_format `{{.body_bytes_sent}}`
```

**To Reproduce**
1. Started Loki  3.1.2 docker container
2. Started Promtail 3.1.2 docker container
3. USe dashboard/queries as above

**Expected behavior**
I dont understand why so much memory is needed for a home server that is ingesting 10-15 logs every few seconds. 

**Environment:**
 - docker containers running on 24.04 Ubuntu server.

**Screenshots, Promtail config, or terminal output**
Promtail config 

```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: core-journal
    journal:
      json: false
      max_age: 240h
      path: /var/log/core/journal
      labels:
        job: systemd-journal
    relabel_configs:
    - source_labels:
      - __journal__systemd_unit
      target_label: systemd_unit
    - source_labels:
      - __journal__hostname
      target_label: nodename
    - source_labels:
      - __journal_syslog_identifier
      target_label: syslog_identifier
    - source_labels:
      - __journal_syslog_timestamp
      target_label: syslog_time
    pipeline_stages:
      - timestamp:
          source: syslog_timestamp
          format: RFC1123
  - job_name: core-varlogs
    static_configs:
    - targets:
        - localhost
      labels:
        host: core
        job: core-varlogs
        __path__: /var/log/*log
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx_myapp
          __path__: /var/log/dockernginx/*log #this is in the docker compose config
    pipeline_stages:
      - json:
          expressions:
            timestamp: time_iso8601
      - timestamp:
          source: timestamp
          format: RFC3339
          action_on_failure: 'skip'
````
