### ISSUE TITLE
Loki start failed. memberlist-kv: invalid service state: Stopping, expected: Running

### ISSUE THREAD

**Issue by wh-song** [grafana/loki#15788]
Loki: 3.3.0;  
Install Loki locally; 

Loki config:
```
auth_enabled: true

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: debug

common:
  path_prefix: /loki
  compactor_address: http://manager:3100
  replication_factor: 1
  storage:
    s3:
      endpoint: manager:18989
      insecure: true
      access_key_id: loki
      secret_access_key: 11111111
      bucketnames: loki
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist
#    instance_interface_names:
#    - eth0

storage_config:
  tsdb_shipper:
    active_index_directory: /loki1/tsdb-shipper-active
    cache_location: /loki1/tsdb-shipper-cache
    cache_ttl: 24h


memberlist:
  join_members: ["worker", "master", "manager"]
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_port: 7946
  gossip_interval: 2s

ingester:
  lifecycler:
    join_after: 10s
    observe_period: 5s
    ring:
      replication_factor: 1
      kvstore:
        store: memberlist
    final_sleep: 0s
  chunk_idle_period: 1m
  wal:
    enabled: true
    dir: /loki/wal
  max_chunk_age: 1m
  chunk_retain_period: 30s
  chunk_encoding: snappy
  chunk_target_size: 1.572864e+06
  chunk_block_size: 262144
  flush_op_timeout: 10s

schema_config:
  configs:
  - from: 2024-03-29
    store: tsdb
    object_store: s3
    schema: v13
    index:
      prefix: index_
      period: 24h


limits_config:
  max_cache_freshness_per_query: '10m'
  reject_old_samples: true
  reject_old_samples_max_age: 30m
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  # parallelize queries in 15min intervals
  split_queries_by_interval: 15m
  volume_enabled: true

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 5
  parallelise_shardable_queries: true
  cache_results: true

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  max_outstanding_per_tenant: 2048

query_scheduler:
  max_outstanding_requests_per_tenant: 32768

querier:
  max_concurrent: 16

compactor:
  working_directory: /tmp/compactor
```

error message:
[loki.log](https://github.com/user-attachments/files/18436425/loki.log)
