### ISSUE TITLE
chucks-cache OOM

### ISSUE THREAD

**Issue by maffelbaffel** [grafana/loki#15813]
**Describe the bug**
I have deployed Loki using the  `grafana/loki` helm chart and get OOM alerts of the chucks-cache quite regularly.

My Helm config for the `grafana/loki` chunks-cache looks like the following. Deployed in `SimpleScalable` mode.
```yaml
chunksCache:
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi
```

**Environment:**
 - Infrastructure: Kubernetes, Azure AKS
 - Deployment tool: Helm
 - Loki Chart version: 6.24.0

**Screenshots, Promtail config, or terminal output**

![Image](https://github.com/user-attachments/assets/890a05fb-f85e-4c1b-b93b-49268d448332)
