### ISSUE TITLE
Promtail-generated metrics have promtail_custom prefix

### ISSUE THREAD

**Issue by AndrewCooper** [grafana/loki#1583]
**Describe the bug**
Metrics created by the metrics pipeline stage have a prefix of "promtail_custom_". This is not documented anywhere and not logged so I eventually figured it out by scraping the metrics and browsing through them manually.

**To Reproduce**
Add a unique metric name to a scrape_config pipeline, like foo_my_metric.
Scrape the metrics manually.
See the metric promail_custom_foo_my_metric in the output.

**Expected behavior**
Either this behavior should be removed or should be documented.

**Environment:**
docker image: grafana/promtail:v1.3.0

**Comment by adityacs** [comment]
@cyriltovena Instead of removing the prefix, can we make it user defined like below?

```
pipeline_stages:
- json:
    expressions:
      app: app
      payload: payload
- metrics:
    loki_count:
      type: Counter
      description: uhhhhhhh
      source: app
      **prefix: user_custom**  
      config:
        value: loki
        action: inc
```
