### ISSUE TITLE
Single promtail unable to filter and push logs to multiple loki servers

### ISSUE THREAD

**Issue by be-nirmal** [grafana/loki#15841]
There is a use case where single promtail with two loki instances deployed on EKS cluster. 
Now I want that my promtail should filter logs based on some key:value and push that specific logs to one loki server and rest of logs should be pushed to second loki server.  

One loki server is storing logs in s3-bucket-1, Second loki server is storing logs in s3-bucket-2

I have deployed Promtail and Loki using official helm charts. 

**Loki helm chart used**: https://github.com/grafana/helm-charts/tree/main/charts/lgtm-distributed
**Promtail helm chart used**: https://github.com/grafana/helm-charts/tree/main/charts/promtail

**To Reproduce**
1. Configure Loki helm chart with S3 buckets as : 
### Loki one: 
```
  schemaConfig:
    configs:
    - from: "2020-09-07"
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

  storageConfig:
    boltdb_shipper:
      shared_store: s3
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 1h
    filesystem:
      directory: /var/loki/chunks
# -- Uncomment to configure each storage individually
#   azure: {}
#   gcs: {}
    aws:
      s3: s3://ap-south-1
      bucketnames: <Bucket-store-default-logs>
```

### Loki Two : 
```
  schemaConfig:
    configs:
    - from: "2020-09-07"
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

  # -- Check https://grafana.com/docs/loki/latest/configuration/#storage_config for more info on how to configure storages
  storageConfig:
    boltdb_shipper:
      shared_store: s3
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 1h
    filesystem:
      directory: /var/loki/chunks
# -- Uncomment to configure each storage individually
#   azure: {}
#   gcs: {}
    aws:
      s3: s3://ap-south-1
      bucketnames: <Bucket-store-user-activity>


```
2. Deploy two loki servers using loki distributed helm chart given above with release names: loki, loki-for-user-activity
3. Configure promtail with :  
```
clients:
    - url: http://loki-loki-distributed-gateway.monitoring.svc.cluster.local/loki/api/v1/push
      name: default_logs_client

    - url: http://loki-for-usr-act-loki-distributed-gateway.monitoring.svc.cluster.local/loki/api/v1/push
      name: user_activity_logs_client

scrape_configs:
  - job_name: kubernetes-pods
    pipeline_stages:
      - json:
          expressions:
            log_type: log_type

      - match:
          selector: '{log_type="activity"}'
          stages:
            - tenant:
                value: user_activity_loki  # Assign tenant ID for user activity logs
          action: keep

      - match:
          selector: '{log_type!="activity"}'
          stages:
            - tenant:
                value: default_logs  # Assign tenant ID for default logs
          action: keep
```
Application logs looks like
```
{  "assetDetails": {    "asset_id": "1"  },  "event": "status_updated",  "level": "info",  "log_type": "activity",  "timestamp": "2024-12-31T07:11:17.649Z",  "userdetails": {    "agencyId": "1",    "email": "example@gmail.com",    "frontId": "1",    "teamId": "1",    "userId": "2"  }}
{  "assetDetails": {    "asset_id": "1"  },  "event": "status_updated",  "level": "info",  "log_type": "activity",  "timestamp": "2024-12-31T07:11:17.649Z",  "userdetails": {    "agencyId": "1",    "email": "example@gmail.com",    "frontId": "1",    "teamId": "1",    "userId": "2"  }}
{  "assetDetails": {    "asset_id": "4"  },  "event": "status_updated",  "level": "info",  "log_type": "idle",  "timestamp": "2024-12-31T07:11:17.649Z",  "userdetails": {    "agencyId": "1",    "email": "example@gmail.com",    "frontId": "1",    "teamId": "1",    "userId": "2"  }}
{  "assetDetails": {    "asset_id": "4"  },  "event": "status_updated",  "level": "info",  "log_type": "idle",  "timestamp": "2024-12-31T07:11:17.649Z",  "userdetails": {    "agencyId": "1",    "email": "example@gmail.com",    "frontId": "1",    "teamId": "1",    "userId": "2"  }}
{  "assetDetails": {    "asset_id": "4"  },  "event": "status_updated",  "level": "info",  "log_type": "idle",  "timestamp": "2024-12-31T07:11:17.649Z",  "userdetails": {    "agencyId": "1",    "email": "example@gmail.com",    "frontId": "1",    "teamId": "1",    "userId": "2"  }}
{  "assetDetails": {    "asset_id": "4"  },  "event": "status_updated",  "level": "info",  "log_type": "idle",  "timestamp": "2024-12-31T07:11:17.649Z",  "userdetails": {    "agencyId": "1",    "email": "example@gmail.com",    "frontId": "1",    "teamId": "1",    "userId": "2"  }}
{  "assetDetails": {    "asset_id": "4"  },  "event": "status_updated",  "level": "info",  "log_type": "idle",  "timestamp": "2024-12-31T07:11:17.649Z",  "userdetails": {    "agencyId": "1",    "email": "example@gmail.com",    "frontId": "1",    "teamId": "1",    "userId": "2"  }}
{  "assetDetails": {    "asset_id": "4"  },  "event": "status_updated",  "level": "info",  "log_type": "idle",  "timestamp": "2024-12-31T07:11:17.649Z",  "userdetails": {    "agencyId": "1",    "email": "example@gmail.com",    "frontId": "1",    "teamId": "1",    "userId": "2"  }}
```

4. Query: `{} term`
**Expected behavior**
The logs with **log_type: activity** should be appears on loki-2 instance and logs other than **log_type: activity** should be shown on loki 1

5. Grafana is used to query both the loki instances. 

**Environment:**
 - Infrastructure: Kubernetes, EKS
 - Deployment tool: helm
