### ISSUE TITLE
Renention for different tenants not working in SimpleScalable mode

### ISSUE THREAD

**Issue by PoraBot** [grafana/loki#15999]
**Describe the bug**
Hello everyone,
We’ve installed Loki in SimpleScalable mode connected to a MinIO instance onprem, right now we’re trying to implement data renention having multiple tenants activated. We’ve enabled retention but currently retention is not working at all, and in the logs of the pod for loki-backend the only references to retentions are these logs:

![Image](https://github.com/user-attachments/assets/d954a50a-dba0-42e0-a3d8-2f0b897b36d6)

Using Grafana with the Loki datasource we can still see older data.

Any tips or informations about this issue?
Thanks in advance!

**To Reproduce**
1. Creating the ConfigMap as follows:

```
extraObjects:
 - apiVersion: v1
   kind: ConfigMap
   metadata:
     name: loki-tenant-overrides-rules
     labels:
       app.kubernetes.io/name: loki
   data:
     loki-tenant-overrides-rules.yaml: |
       overrides:
         "tenant1":
           retention_period: 60d
           retention_stream:
             - selector: '{namespace="prod"}'
               priority: 2
               period: 30d
             - selector: '{container="loki"}'
               priority: 1
               period: 15d
   
         "tenant2":
           retention_period: 24h
           retention_stream:
             - selector: '{namespace="prod"}'
               priority: 1
               period: 30d
         
         "tenant3":
           retention_period: 72h
           retention_stream:
             - selector: '{k8s.cluster.name="K8S-PROD"}'
               priority: 1
               period: 24h
         
         "tenant4":
           retention_period: 60d
           retention_stream:
             - selector: '{namespace="prod"}'
               priority: 1
               period: 30d
```

2. Retention is enabled as follows:

```
loki:
  ...
 
  compactor:
    working_directory: /var/loki/compactor
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    delete_request_store: s3

  extraVolumes:
    - name: loki-tenant-overrides-rules
      configMap:
        name: loki-tenant-overrides-rules
        items:
          - key: loki-tenant-overrides-rules.yaml
            path: loki-tenant-overrides-rules.yaml
        defaultMode: 420

  extraVolumeMounts:
    - name: loki-tenant-overrides-rules
      mountPath: /etc/loki/config/override

  limits_config:
    retention_period: 180d
    per_tenant_override_config: /etc/loki/config/override/loki-tenant-overrides-rules.yaml
```

ExtraVolumes and extraVolumeMounts is inserted inside Backend, Read and Write blocks as well like this:

```
backend:
  extraVolumes:
    - name: loki-tenant-overrides-rules
      configMap:
        name: loki-tenant-overrides-rules
        items:
          - key: loki-tenant-overrides-rules.yaml
            path: loki-tenant-overrides-rules.yaml
        defaultMode: 420
  extraVolumeMounts:
    - name: loki-tenant-overrides-rules
      mountPath: /etc/loki/config/override
```

3. Using Grafana with the Loki datasource we can still see older data then the one set.

4. **Expected behavior**
Retention job to clean data older then the set period inside of retention_stream

**Environment:**
 - Infrastructure: Kubernetes, Loki SimpleScalable deployment, MinIO
 - Deployment tool: ArgoCD, Helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
