### ISSUE TITLE
Ruler WAL logs are empty when ruler.evaluation.mode=remote

### ISSUE THREAD

**Issue by michal-relout** [grafana/loki#16009]
**Describe the bug**

Hello everyone,
I use SimpleScalable deployment in k8s and want to configure `ruler.evaluation.mode=remote` to accelerate queries executed by the ruler component (recording rules). I was able to deploy dedicated loki-read pods that are only responsible for executing queries from the ruler (which runs on loki-backend pods). The ruler sends queries to dedicated loki-read deployment, the queries are executed there and that works fine (no errors in logs, `loki_ruler_remote_eval_success_total` metric is raising). However, the results of the queries are not stored in the ruler's WAL logs and therefore are not being sent to remote endpoint (prometheus in my case).

Loki documentation about this setup:
https://grafana.com/docs/loki/latest/operations/scalability/#remote-rule-evaluation
https://grafana.com/docs/loki/latest/community/lids/0002-remoteruleevaluation/

If this is expected behaviour and WAL logs cannot be written when `ruler.evaluation.mode=remote` then this should be clearly described in the Loki's documentation that settings under `ruler.remote_write` will not have any effect when `ruler.evaluation.mode=remote`.

**To Reproduce**
Steps to reproduce the behaviour:

Loki `rulerConfig` in helm chart values.yaml:
```
loki:
  rulerConfig:
    remote_write:
      enabled: true
      clients:
        prometheus:
          url: http://${PROMETHEUS_RELEASE}-prometheus.${PROMETHEUS_NAMESPACE}.svc:9090/api/v1/write
    wal:
      dir: /var/loki/ruler-wal
    evaluation:
      mode: remote
      query_frontend:
        address: dns:///loki-read-ruler.${LOKI_NAMESPACE}.svc.cluster.local:9095
```

Queries from the ruler are being executed properly on `loki-read-ruler` pods:

![Image](https://github.com/user-attachments/assets/02149ad1-b6a9-4c00-af22-ddbe76e9402b)

No errors on loki-backend pods or loki-read-ruler pods. There are logs saying that queries are being executed.

However, WAL logs on loki-backend can be found but are empty all the time (the latest WAL log):

```
/ $ ls -l /var/loki/ruler-wal/fake/wal/00000006
-rw-r--r--    1 loki     loki             0 Jan 30 10:35 /var/loki/ruler-wal/fake/wal/00000006
```

**Expected behaviour**

WAL logs should be written on the ruler when `ruler.evaluation.mode=remote` so that they can be sent to remote endpoint (prometheus/mimir) or there should be another recommended way of sending the results of remotely evaluated rules to remote endpoint (prometheus/mimir).

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]

AWS EKS 1.29

 - Deployment tool: [e.g., helm, jsonnet]

helm chart: loki-6.21.0
Loki version: 3.3.0

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
