### ISSUE TITLE
Documentation feedback: /docs/sources/send-data/docker-driver/configuration.md

### ISSUE THREAD

**Issue by z0z0r4** [grafana/loki#16014]
`keep-file` is not a bool

This my termail output

```
docker compose up
validating docker-compose.yml: services.xxx.logging.options.keep-file must be a string, number or null
```

My `docker-compose.yml`

```
x-logging: &loki-logging
  driver: loki
  options:
    loki-url: "http://localhost:3100/loki/api/v1/push"
    max-size: "50m"
    max-file: "10"
    keep-file: true
```

```
docker plugin ls
ID             NAME          DESCRIPTION           ENABLED
5e66f60f565e   loki:latest   Loki Logging Driver   true
```

But in Loki Document, its default value is `false`. I don't know why

https://grafana.com/docs/loki/latest/send-data/docker-driver/configuration/#supported-log-opt-options
