### ISSUE TITLE
Feature Request: Custom CA for loki-docker-driver

### ISSUE THREAD

**Issue by iUnstable0** [grafana/loki#16071]
Hi!

I have Loki running behind NGINX with a self-signed SSL certificate.
When I’m using the loki-docker-driver to log a Docker container to Loki, I get the following error:

```
Feb 03 20:10:18 th-01 dockerd[13044]: time="2025-02-03T20:10:18Z" level=info msg="level=warn ts=2025-02-03T20:10:18.430244046Z caller=client.go:419 container_id=26f08d0c6a2f312020ad9d81c002b2bc6d1c9068b03ea8d9057b54e2c22ddfbb component=client host=loki.local.net msg=\"error sending batch, will retry\" status=-1 tenant= error=\"Post \\\"https://loki:***@loki.local.net/loki/api/v1/push\\\": tls: failed to verify certificate: x509: certificate signed by unknown authority\"" plugin=b643800cd494a0c84ebaba317a9475a98ee6940b266f9786ae3d78d4ceb2828c
```

It would be really beneficial if theres an option to add custom ca certs to trust for the docker driver

```
    logging:
      driver: loki
      options:
        loki-url: "https://loki:password@loki.local.net/loki/api/v1/push"
        loki-custom-ca: "/path/to/ca"
        loki-batch-size: 400
```

Is this possible at all? I dont really know much about docker plugins

Thanks!
