### ISSUE TITLE
s3_secret_access_key does not allow slashes

### ISSUE THREAD

**Issue by PabloCastellano** [grafana/loki#1607]
**Describe the bug**
Loki fails to start when an s3 bucket is configured as storage and the secret key contains a slash. I have generated a different access key pair whose secret key doesn't contain a slash character and it works fine.

**To Reproduce**
1. Configure s3 storage with a secret key that contains a slash. E.g.

```
storage_config:
  boltdb:
    directory: /tmp/loki/index
  filesystem:
    directory: /tmp/loki/chunks
  aws:
    s3: s3://ASDFGHJIQWETTYUI:Jkasduahdkjh213kj1h31+lkjaflkjzvKASDOasofhjafaKFAF/GoQd@region/bucket_name
```
2. Start Loki (master-765b34d)

**Expected behavior**
Loki should correctly parse the secret key and don't interpret it as a port

**Environment:**
 - Infrastructure: Docker running in a VM
 - Deployment tool: Docker-compose

**Screenshots, Promtail config, or terminal output**

```
failed parsing config: /etc/loki/local-config.yaml: parse s3://ASDFGHJIQWETTYUI:Jkasduahdkjh213kj1h31+lkjaflkjzvKASDOasofhjafaKFAF/GoQd@region/bucket_name invalid port ":Jkasduahdkjh213kj1h31+lkjaflkjzvKASDOasofhjafaKFAF" after 
host
```
