### ISSUE TITLE
alloy loki grafana - not working

### ISSUE THREAD

**Issue by JCzz** [grafana/loki#16151]
I have run this example:
https://grafana.com/docs/alloy/latest/tutorials/logs-and-relabeling-basics/

Alloy setup: alloy run ./config.alloy
```
local.file_match "tmplogs" {
    path_targets = [{"__path__" = "/logs/*.log"}]
}

loki.source.file "local_files" {
    targets    = local.file_match.tmplogs.targets
    forward_to = [loki.write.local_loki.receiver]
}

loki.write "local_loki" {
    endpoint {
        url = "http://localhost:3100/loki/api/v1/push"
    }
}
```

This docker compose:
```
networks:
  monitoring: # Define a custom network
    driver: bridge

services:
  loki:
    image: grafana/loki:3.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring  # Attach Loki to the network

  grafana:
    image: grafana/grafana:11.5.1
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        EOF
        /run.sh
    networks:
      - monitoring
```

``` logcli ???
logcli query '{job="alloy"}' --since=1m
http://localhost:3100/loki/api/v1/query_range?direction=BACKWARD&end=1739061003975029000&limit=30&query=%7Bjob%3D%22alloy%22%7D&start=1739060943975029000
```

```
logcli labels
http://localhost:3100/loki/api/v1/labels?end=1739061076837310000&start=1739057476837310000

```

Nothing in Grafana explore, no logs, no labels - nothing

I have found that the example in production/docker-compose.yml is working using promtrail, but as stated in this:
https://grafana.com/blog/2024/04/09/grafana-agent-to-grafana-alloy-opentelemetry-collector-faq/
We should use Alloy, and it does not work.
