### ISSUE TITLE
Configuring Promtail for Windows

### ISSUE THREAD

**Issue by hack3rcon** [grafana/loki#16150]
Hello,
I want to send Windows Event ID `4066` to Grafana Loki server at IP address `192.168.1.2`. I created the following configuration file:
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: C:\ProgramData\promtail\positions.yaml   
clients:
  - url: http://192.168.1.2:3100/loki/api/v1/push

scrape_configs:
  - job_name: windows_event_log_application
    windows_events:
      eventlog_name: Application
      xpath_query: "*[System/EventID=4066]"
    static_configs:
      - targets: [localhost]
        labels:
          job: windows_event_log_application
          source: windows

  - job_name: windows_event_log_security
    windows_events:
      eventlog_name: Security
      xpath_query: "*[System/EventID=4066]"
    static_configs:
      - targets: [localhost]
        labels:
          job: windows_event_log_security
          source: windows

  - job_name: windows_event_log_system
    windows_events:
      eventlog_name: System
      xpath_query: "*[System/EventID=4066]"
    static_configs:
      - targets: [localhost]
        labels:
          job: windows_event_log_system
          source: windows
```
But I got the following error:

```
level=info ts=2025-02-08T11:06:59.673514Z caller=promtail.go:133 msg="Reloading configuration file" md5sum=3a59796f69c24d6712ec52c5cdce3532
level=info ts=2025-02-08T11:06:59.6827082Z caller=server.go:351 msg="server listening on addresses" http=[::]:9080 grpc=[::]:49731
level=info ts=2025-02-08T11:06:59.6838817Z caller=main.go:173 msg="Starting Promtail" version="(version=3.3.2, branch=release-3.3.x, revision=23b5fc2c)"
level=warn ts=2025-02-08T11:06:59.6848194Z caller=promtail.go:263 msg="enable watchConfig"
level=info ts=2025-02-08T11:07:04.6798857Z caller=filetargetmanager.go:346 msg="no path for target" labels="{__address__=\"localhost\", job=\"windows_event_log_application\", source=\"windows\"}"
level=info ts=2025-02-08T11:07:04.6798857Z caller=filetargetmanager.go:346 msg="no path for target" labels="{__address__=\"localhost\", job=\"windows_event_log_security\", source=\"windows\"}"
level=info ts=2025-02-08T11:07:04.6798857Z caller=filetargetmanager.go:346 msg="no path for target" labels="{__address__=\"localhost\", job=\"windows_event_log_system\", source=\"windows\"}"
```
How to solve it?

Thank you.
