### ISSUE TITLE
In loki helm values `rbac.pspEnabled: true` will generate deprecated `podsecuritypolicy`

### ISSUE THREAD

**Issue by GeoffreyStemys** [grafana/loki#16160]
**Describe the bug**
In the helm chart values setting the `rbac.pspEnabled: true` will exit code 1 because of usage of deprecated `podsecuritypolicy`:
https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/
Making impossible to generate the `role` and `roleBinding` from the chart.

**To Reproduce**
1. up a kubernetes cluster at version >= `1.31`
2. apply the following helm (with helmfile):
`helmfile.yaml` is:
```yaml
repositories:

  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:

  - name: loki
    namespace: grafana
    chart: grafana/loki
    version: 6.25.1
    labels:
      app: loki
    values:
      - loki-values.yaml
```
`loki-values.yaml` is:
```yaml
deploymentMode: SingleBinary
loki:
  enableServiceLinks: false
  configStorageType: ConfigMap
  auth_enabled: false
  schemaConfig:
    configs:
      - from: 2020-10-24
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
    ring:
      kvstore:
        store: inmemory
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
      admin_api_directory: /var/loki/admin
  useTestSchema: false

singleBinary:
  replicas: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      memory: 500Mi
      cpu: 100m
    limits:
      memory: 500Mi
  persistence:
    enabled: true
    enableStatefulSetAutoDeletePVC: true
    size: 10Gi
serviceAccount:
  create: true
rbac:
  pspEnabled: true # <---------- problematic flag, true will fail
  namespaced: true
networkPolicy:
  enabled: false
gateway:
  enabled: false
ingress:
  enabled: false
test:
  enabled: false
lokiCanary:
  enabled: false
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
ruler:
  enabled: false
memcachedExporter:
  enabled: false
resultsCache:
  enabled: false
chunksCache:
  enabled: false
rollout_operator:
  enabled: false
minio:
  enabled: false
```
4. when doing an helmfile `apply`:
```bash
helmfile -l app=loki -i apply --context 1
```
this will output :
```
STDERR:
  Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "loki" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
  ensure CRDs are installed first
  Error: plugin "diff" exited with error
```
because of deprecated `podsecuritypolicy`: https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/

5. The problem is that this `pspEnabled` flag will also trigger the generation of the `Role` and `RoleBinding`, meaning that letting the flag at `false` the `serviceAccount` will not be able to retrieve the `configMap` to pass to the loki `config.yaml` to the pod.
6. I did a quick fix by keeping the `pspEnabled` at `false` then generating manually the `Role` and `RoleBinding`with:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loki
  namespace: grafana
subjects:
  - name: loki
    kind: ServiceAccount
    namespace: grafana
roleRef:
  name: loki
  kind: Role
  apiGroup: rbac.authorization.k8s.io
```
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loki
  namespace: grafana
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "endpoints", "configmaps", "secrets", "namespaces" ]
    verbs: [ "get", "list", "watch" ]
```

```shell
NAMESPACE=grafana
kubectl apply -f loki-role.yaml -n $NAMESPACE
kubectl apply -f loki-roleBinding.yaml -n $NAMESPACE
```

**Expected behavior**
`helmfile apply` should return exit code 0 when `rbac.pspEnabled: true` like:
```
UPDATED RELEASES:
NAME   NAMESPACE   CHART          VERSION   DURATION
loki   grafana     grafana/loki   6.25.1          6s
```
To solve imo either use something else than a `podsecuritypolicy` or the chart should be redesign to not tight the generation of the `role` and `rolebinding` with the `podsecuritypolicy` behind a single flag ?

**Environment:**
 - Infrastructure: Kubernetes >= `1.31`
 - Deployment tool: [`kubectl`, `helm`, `helm diff`, `helmfile`]

**Screenshots, Promtail config, or terminal output**

![Image](https://github.com/user-attachments/assets/d86d0bcb-422d-43d9-a3b2-a3c61e47ca77)
