### ISSUE TITLE
OTLP sending issue from Alloy to Loki.

### ISSUE THREAD

**Issue by cpeliciari** [grafana/loki#16174]
I created a test environment so that I can send logs via OTLP to Alloy, but it appears that some Alloy configuration is incorrect.
Basically, I have a client that sends metrics to Alloy via gRPC, and Alloy sends logs to Loki.

# Logs
```
ts=2025-02-11T02:49:07.664352549Z level=error msg="final error sending batch" component_path=/ component_id=loki.write.local component=client host=loki:3100 status=404 tenant="" error="server returned HTTP status 404 Not Found (404): 404 page not found"
```

# Alloy Config
```
otelcol.receiver.otlp "default" {
  grpc { endpoint = "0.0.0.0:4317" }
  http { endpoint = "0.0.0.0:4318" }
  output {
    metrics = [otelcol.processor.batch.default.input]
    logs    = [otelcol.processor.batch.default.input]
    traces  = [otelcol.processor.batch.default.input]
  }
}

otelcol.processor.batch "default" {
  send_batch_size     = 1000
  send_batch_max_size = 2000
  timeout             = "2s"
  output {
    metrics = [otelcol.exporter.prometheus.default.input]
    logs    = [otelcol.exporter.loki.default.input]
    traces  = [otelcol.exporter.otlp.tempo.input]
  }
}

otelcol.exporter.loki "default" {
  forward_to = [loki.write.local.receiver]
}

loki.write "local" {
  endpoint {
    url = "http://loki:3100/otlp"
  }
}

otelcol.exporter.prometheus "default" {
  forward_to = [prometheus.remote_write.mimir.receiver]
}

prometheus.remote_write "mimir" {
  endpoint {
  url = "http://prometheus:9090/api/v1/write"
  }
}

otelcol.exporter.otlp "tempo" {
  client { 
    endpoint = "tempo:4317"
    tls {
      insecure             = true
      insecure_skip_verify = true
    }
  }
}
```

# Grafana Stack 
```
networks:
  grafana-net:

services:
  redis:
    image: redis:alpine
    networks:
      - grafana-net
    ports:
      - "6379:6379"

  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./docker/tempo-data:/var/tempo

  memcached:
    image: memcached:1.6.29
    container_name: memcached
    networks:
      - grafana-net
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m  # Set the maximum memory usage
      - MEMCACHED_THREADS=4       # Number of threads to use

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - grafana-net
    volumes:
      - ./docker/tempo.yaml:/etc/tempo.yaml
      - ./docker/tempo-data:/var/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    depends_on:
      - init
      - memcached

  prometheus:
    image: prom/prometheus:latest
    networks:
      - grafana-net
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./docker/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:v3.3.2
    networks:
      - grafana-net
    ports:
      - "3100:3100"
    volumes:
      - ./docker/loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  alloy:
    image: grafana/alloy:latest
    networks:
      - grafana-net
    volumes:
      - ./docker/alloy-local-config.yaml:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:  run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - "12345:12345"

  grafana:
    image: grafana/grafana:11.2.0
    networks:
      - grafana-net
    volumes:
      - ./docker/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app
    ports:
      - "3000:3000"
```

# Loki Config
```
limits_config:
  allow_structured_metadata: true # required otlp

auth_enabled: false

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks
```

# Go
```
        logExporter, err := otlploggrpc.New(ctx, otlploggrpc.WithGRPCConn(conn))
	if err != nil {
		return nil, fmt.Errorf("failed to create log exporter: %w", err)
	}

	batch := sdklog.NewBatchProcessor(logExporter, sdklog.WithExportInterval(10*time.Second))
	lp := sdklog.NewLoggerProvider(
		sdklog.WithProcessor(batch),
		sdklog.WithResource(res),
	)


        ctx, span := otel.Tracer(oserror.TraceVod).Start(ctx, "usecase.RegisterLocal")
	defer span.End()

	span.SetAttributes(
		attribute.Int("vod.id", int(req.Id)),
	)

	var record logutil.Record
	record.SetSeverity(9)
	record.SetBody(logutil.StringValue("Test Body"))
	record.SetTimestamp(time.Now())
	lp.Emit(ctx, record)

	span.AddEvent("test")


```
