### ISSUE TITLE
support for reading the systemd journal is not compiled into this build of promtail

### ISSUE THREAD

**Issue by mindrunner** [grafana/loki#16220]
**Describe the bug**
Using `grafana/promtail` latest, I see this error message when I try to use systemd logs.

```
level=warn ts=2025-02-12T16:09:46.125808224Z caller=journaltargetmanager.go:29 msg="WARNING!!! Journal target was configured but support for reading the systemd journal is not compiled into this build of promtail!"
```

**To Reproduce**
1. Started Loki `latest`
2. Started Promtail `latest` to tail 'systemd' logs

**Expected behavior**
journalctl systemd logs are being sent

**Environment:**
 - Infrastructure: docker-compose
 - Deployment tool: docker-compose

**Screenshots, Promtail config, or terminal output**
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3000/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      json: false
      max_age: '12h'
      path: /run/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        regex: 'agave.service'
        action: keep
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal_syslog_identifier']
        target_label: 'syslog_identifier'
```
