### ISSUE TITLE
High Log Volume Loki Performance

### ISSUE THREAD

**Issue by mjamaah** [grafana/loki#16408]
## Issue Description
Hello,

I am Designing a log aggregation system for an Orgnization with **100Million** Logs per month.

I am using the **Simple Scalable** deployment mode, Docker Runtime, Azure Blob for Storage.

My Solution is Working Fine, but when i try to run Long Queries(7days, 15days, 30days) using Grafana i am Facing a timeout error:

```html
<html>
  <head>
    <title>504 Gateway Time-out</title>
  </head>
  <body>
    <center>
      <h1>504 Gateway Time-out</h1>
    </center>
    <hr>
    <center>nginx/1.18.0 (Ubuntu)</center>
  </body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

and i can see **499** http status code in the ngnix logs for the long queries.

**Am I missing anything, or is there any way to improve the Loki performance for long queries (Read instances)?**

### Loki.yaml

```yaml
auth_enabled: true

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  http_server_read_timeout: 1000s
  http_server_write_timeout: 1000s
  http_server_idle_timeout: 1000s
  log_level: info
  grpc_server_max_recv_msg_size: 10485760


common:
  path_prefix: /loki
  compactor_address: http://loki-backend:3100
  replication_factor: 3

storage_config:
  azure:
    account_name: <StorageAccountName>
    account_key: <StorageAccountKey>
    container_name: loki
    use_managed_identity: false
    request_timeout: 0
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    cache_ttl: 24h
  filesystem:
    directory: /loki/chunks


memberlist:
  join_members: ["loki-read", "loki-write", "loki-backend"]
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr: ['0.0.0.0']
  bind_port: 7946
  gossip_interval: 2s

ingester:
  lifecycler:
    join_after: 10s
    observe_period: 5s
    ring:
      replication_factor: 3
      kvstore:
        store: memberlist
    final_sleep: 0s
  chunk_idle_period: 1m
  wal:
    enabled: true
    dir: /loki/wal
  max_chunk_age: 1m
  chunk_retain_period: 30s
  chunk_encoding: snappy
  chunk_target_size: 1.572864e+06
  chunk_block_size: 262144
  flush_op_timeout: 10s

ruler:
  alertmanager_url: http://alertmanager:9093
  enable_api: true
  enable_sharding: true
  wal:
    dir: /loki/ruler-wal
  evaluation:
    mode: remote
    query_frontend:
      address: dns:///loki-read:9095
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/prom-rules
  remote_write:
    enabled: true
    clients:
      local:
         url: http://prometheus:9090/api/v1/write
         queue_config:
           # send immediately as soon as a sample is generated
           capacity: 1
           batch_send_deadline: 0s

schema_config:
  configs:
  - from: 2020-08-01
    store: boltdb-shipper
    object_store: azure
    schema: v11
    index:
      prefix: index_
      period: 24h
  - from: 2023-07-11
    store: tsdb
    object_store: azure
    schema: v12
    index:
      prefix: index_
      period: 24h
  - from: 2024-01-10
    store: tsdb
    object_store: azure
    schema: v12
    index:
      prefix: index_
      period: 24h
  - from: 2024-03-29
    store: tsdb
    object_store: azure
    schema: v13
    index:
      prefix: index_
      period: 24h


limits_config:
  max_cache_freshness_per_query: '10m'
  reject_old_samples: true
  reject_old_samples_max_age: 30m
  ingestion_rate_mb: 30
  ingestion_burst_size_mb: 60
  # parallelize queries in 15min intervals
  volume_enabled: true
  allow_structured_metadata: true
  max_label_names_per_series: 50
  max_streams_per_user: 0
  max_label_name_length: 2048
  max_label_value_length: 4096
  max_global_streams_per_user: 0
  max_line_size: 16384
  deletion_mode: filter-and-delete
  retention_period: 720h
  split_queries_by_interval: 6h
  max_query_parallelism: 64
  max_query_series: 1000


table_manager:
  retention_deletes_enabled: true
  retention_period: 720h

query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 5
  parallelise_shardable_queries: true
  cache_results: true

frontend:
  log_queries_longer_than: 0s
  compress_responses: true
  max_outstanding_per_tenant: 2048

query_scheduler:
  max_outstanding_requests_per_tenant: 32000

querier:
  query_ingesters_within: 2h

compactor:
  working_directory: /tmp/compactor
  compaction_interval: 5m
  retention_enabled: true
  delete_request_store: azure

compactor_grpc_client:
  grpc_compression: gzip
```

### nginx.conf
```
error_log  /dev/stderr;
pid        /tmp/nginx.pid;
worker_rlimit_nofile 100000;

events {
    worker_connections  4096;  ## Default: 1024
    use epoll;
    multi_accept on;
}

http {
  default_type application/octet-stream;
  log_format   main '$remote_addr - $remote_user [$time_local]  $status '
    '"$request" $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';
  access_log   /dev/stderr  main;
  sendfile     on;
  tcp_nopush   on;
  tcp_nodelay on;
  client_max_body_size 100M;
  keepalive_timeout 1000s;

  upstream read {
    server loki-read:3100;
  }

  upstream write {
    server loki-write:3100;
  }

  upstream cluster {
    server loki-read:3100;
    server loki-write:3100;
  }

  server {
    listen 80;
    listen 3100;
    server_name doclink-logs.altec-cloud.com;

    location = /ring {
        proxy_pass       http://cluster$request_uri;
        proxy_connect_timeout 1000s;
        proxy_send_timeout 1000s;
        proxy_read_timeout 1000s;
        send_timeout 1000s;
    }

    location = /memberlist {
        proxy_pass       http://cluster$request_uri;
        proxy_connect_timeout 1000s;
        proxy_send_timeout 1000s;
        proxy_read_timeout 1000s;
        send_timeout 1000s;
    }

    location = /config {
        proxy_pass       http://cluster$request_uri;
        proxy_connect_timeout 1000s;
        proxy_send_timeout 1000s;
        proxy_read_timeout 1000s;
        send_timeout 1000s;
    }

    location = /metrics {
        proxy_pass       http://cluster$request_uri;
        proxy_connect_timeout 1000s;
        proxy_send_timeout 1000s;
        proxy_read_timeout 1000s;
        send_timeout 1000s;
    }

    location = /ready {
        proxy_pass       http://cluster$request_uri;
        proxy_connect_timeout 1000s;
        proxy_send_timeout 1000s;
        proxy_read_timeout 1000s;
        send_timeout 1000s;
    }

    location = /loki/api/v1/push {
        proxy_pass       http://write$request_uri;
        proxy_connect_timeout 1000s;
        proxy_send_timeout 1000s;
        proxy_read_timeout 1000s;
        send_timeout 1000s;
    }

    location = /loki/api/v1/tail {
        proxy_pass       http://read$request_uri;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_connect_timeout 1000s;
        proxy_send_timeout 1000s;
        proxy_read_timeout 1000s;
        send_timeout 1000s;
    }

    location ~ /loki/api/.* {
        proxy_pass       http://read$request_uri;
        proxy_connect_timeout 1000s;
        proxy_send_timeout 1000s;
        proxy_read_timeout 1000s;
        send_timeout 1000s;
    }
  }
}
```

### docker-compose.yaml

```yaml
networks:
  loki:

volumes:
  prometheus:
  alertmanager-data:
  loki:

services:
  # Since the Loki containers are running as user 10001 and the mounted data volume is owned by root,
  # Loki would not have permissions to create the directories.
  # Therefore the init container changes permissions of the mounted directory.
  init:
    image: &lokiImage grafana/loki:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/loki"
    volumes:
      - ./loki:/loki
    networks:
      - loki

  prometheus:
    image: prom/prometheus:v3.1.0
    ports:
      - 9090
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    command:
      [
        '--log.level=debug',
        '--config.file=/etc/prometheus/prometheus.yml',
        '--enable-feature=remote-write-receiver',
        '--query.lookback-delta=30s'
      ]
    networks:
      - loki
    logging:
      driver: "local"
      options:
          max-size: "10m"
          max-file: "5"

  loki-gateway:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "3100"
    restart: always
    networks:
      - loki
    healthcheck:
      test: curl -s http://localhost:80/ready | grep -q '^ready$' || exit 1
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 10s
    logging:
      driver: "local"
      options:
          max-size: "10m"
          max-file: "5"


  loki-read:
    image: *lokiImage
    volumes:
      - ./config:/etc/loki/
    # only needed for interactive debugging with dlv
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - apparmor=unconfined
    ports:
      - "3100"
      - "7946"
      # uncomment to use interactive debugging
      # - "40000-40002:40000" # makes the replicas available on ports 40000, 40001, 40002
    command: "-config.file=/etc/loki/loki.yaml -target=read -legacy-read-mode=false"
    networks:
      - loki
    restart: always
    deploy:
      mode: replicated
      replicas: 6
    extra_hosts:
      - "<StorageAccountURL>:<PrivateEndpointIP>"
    logging:
      driver: "local"
      options:
          max-size: "10m"
          max-file: "5"

  loki-write:
    image: *lokiImage
    volumes:
      - ./config:/etc/loki/
    # only needed for interactive debugging with dlv
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - apparmor=unconfined
    ports:
      - "3100"
      - "7946"
      # uncomment to use interactive debugging
      # - "50000-50002:40000" #  makes the replicas available on ports 50000, 50001, 50002
    command: "-config.file=/etc/loki/loki.yaml -target=write"
    networks:
      - loki
    restart: always
    deploy:
      mode: replicated
      replicas: 3
    extra_hosts:
      - "<StorageAccountURL>:<PrivateEndpointIP>"
    logging:
      driver: "local"
      options:
          max-size: "10m"
          max-file: "5"

  loki-backend:
    image: *lokiImage
    volumes:
      - ./config:/etc/loki/
      - ./rules:/loki/rules:ro
    # only needed for interactive debugging with dlv
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - apparmor=unconfined
    ports:
      - "3100"
      - "7946"
      # uncomment to use interactive debugging
      # - "60000-60002:40000" #  makes the replicas available on ports 60000, 60001, 60002
    command: "-config.file=/etc/loki/loki.yaml -target=backend -legacy-read-mode=false"
    networks:
      - loki
    restart: always
    deploy:
      mode: replicated
      replicas: 3
    extra_hosts:
      - "<StorageAccountURL>:<PrivateEndpointIP>"
    logging:
      driver: "local"
      options:
          max-size: "10m"
          max-file: "5"

  # alertmanager to enable receiving alerts
  alertmanager:
    image: prom/alertmanager:v0.28.0
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./config:/config"
      - ./alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug
    networks:
      - loki
    logging:
      driver: "local"
      options:
          max-size: "10m"
          max-file: "5"

```
