### ISSUE TITLE
Promtail error : entry for stream xxxx has xx label names; limit 15;

### ISSUE THREAD

**Issue by DuvelCorp** [grafana/loki#16486]
Hello

I got stable systems for > 1 year and now I have this issue while the logs being sent to Promtail/Loki havent changed, and the config files neither.

I suspect this happened after a recent upgrade of my loki/promtail containers (I use 'latest" tags)

So the error is pretty clear: I send logs having 27 label names, while the limit is 15.

The problem is that I havent changed anything to the limits, and after extensive researches, I cant find where I can increase that limit in promtail or loki. And I cant find either where a default 15 label name limit is stated somewhere in the docs.
It makes no sense to me.

The logs in question are syslogs from my pfSense firewall.

The Promtail config is this

```

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

relabellclients:
  - url: http://192.168.1.3:3100/loki/api/v1/push

scrape_configs:
- job_name: syslog

  syslog:
    listen_address: 0.0.0.0:1514
    idle_timeout: 60s
    label_structured_data: no
    labels:
      job: "syslog"

  relabel_configs:
    - source_labels: ['__syslog_message_hostname']
      target_label: 'host'
    - source_labels: ['__syslog_connection_ip_address']
      target_label: 'connection_ip'
    - source_labels: ['__syslog_message_severity']
      target_label: 'severity'
    - source_labels: ['__syslog_message_facility']
      target_label: 'facility'
    - source_labels: ['__syslog_message_app_name']
      target_label: 'appname'
    - source_labels: ['__syslog_message_proc_id']
      target_label: 'procid'
    - source_labels: ['__syslog_message_msg_id']
      target_label: 'msgid'

  pipeline_stages:
  - regex:
      expression: '^(?P<rule_number>[\d]+),(?P<sub_rule_number>[\d]*),(?P<anchor>[\d]*),(?P<tracker>[\w\d]*),(?P<interface>[\w\d]*),(?P<reason>[\w]*),(?P<action>[\w]*>
  - labels:
      rule_number:
      sub_rule_number:
      tracker:
      interface:
      reason:
      action:
      direction:
      ip_version:
      packet_ttl:
      packet_id:
      ip_flags:
      protocol_name:
      source_ip:
      source_port:
      dest_ip:
      dest_port:

  - geoip:
      db: "/usr/share/GeoIP/GeoLite2-City.mmdb"
      db_type: "city"
      source: source_ip
  - geoip:
      db: "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
      db_type: "asn"
      source: source_ip

  - labeldrop:
      - geoip_postal_code
      - geoip_subdivision_code
      - geoip_subdivision_name
      - geoip_continent_code
      - geoip_continent_name
      - geoip_timezone
```

And here's the error log (a bit reformated):
```

level=error ts=2025-02-27T07:50:10.351614403Z 
caller=client.go:430 
component=client 
host=192.168.1.3:3100 
msg="final error sending batch" status=400 
tenant= 
error="server returned HTTP status 400 Bad Request (400): 1 errors like: entry for stream 

'{action=\"block\", 
appname=\"filterlog\", 
connection_ip=\"172.19.0.5\", 
dest_ip=\"109.129.18.106\", 
dest_port=\"54059\", 
direction=\"in\", 
facility=\"local0\", 
geoip_autonomous_system_number=\"396982\", 
geoip_autonomous_system_organization=\"GOOGLE-CLOUD-PLATFORM\", 
geoip_country_name=\"United States\", 
geoip_location_latitude=\"37.751\", 
geoip_location_longitude=\"-97.822\", 
host=\"WatchGuard\", 
interface=\"pppoe0\", 
ip_flags=\"none\", 
ip_version=\"4\", 
job=\"syslog\", 
packet_id=\"54321\", 
packet_ttl=\"249\", 
procid=\"97685\", 
protocol_name=\"tcp\", 
reason=\"match\", 
rule_number=\"4\", 
service_name=\"syslog\", 
severity=\"informational\", 
source_ip=\"205.210.31.224\", 
source_port=\"44\", 
tracker=\"1000000103\"}'

 has 27 label names; limit 15; 
```

Indeed I do have 27 labels on here, but they are all useful and I dont want to drop any. And it has always worked like this. My pfsense syslogs havent changed at all, they have always been like this and properly handled by promtail and  properly ingested by Loki.... all the 27 labels.

So I wonder what happened, why suddenly there's a 15 label name limit and how to increase it.
