### ISSUE TITLE
.ruler_storage configuration used by -use-thanos-objstore=true lacks named_storage field

### ISSUE THREAD

**Issue by ringerc** [grafana/loki#16544]
**Describe the bug**

Loki 3.4 added `.storage_config.named_stores` and `.storage_config.object_store.named_stores`, which allow `.schema_config.configs[].object_store` to refer to a named store rather than a provider like `s3`. The former is used unless `-use-thanos-objstore=true` is passed, in which case it's ignored and the latter is used instead.

This support does not appear to have been extended to `.ruler.storage` and the thanos-client equivalent `.ruler_storage` block. These don't recognise `named_stores` keys, and `.ruler_storage.backend` does not recognise named store names like `schema_config.configs[].object_store` does.

So ruler storage configuration is inconsistent with the main object storage configuration.

**To Reproduce**

Start Loki 3.4+ as `loki -t all -config.file=config.yaml  -use-thanos-objstore=true` with a `config.yaml` like:

```yaml
server:
  http_listen_port: 3100

common:
  ring:
    kvstore:
      store: memberlist
  replication_factor: 1
  path_prefix: /var/loki

schema_config:
  configs:
  - from: 2020-05-15
    store: tsdb
    object_store: my-named-store
    schema: v13
    index:
      prefix: index_
      period: 24h

ruler:
  wal:
    dir: /loki/ruler-wal
  # This configuration is only used by Ruler when -use-thanos-objstore=true is NOT passed.
  # It must be present even when using the thanos client because a startup
  # check incorrectly uses this path instead of the override .ruler_storage
  # used by the thanos client for everything else. See bug https://github.com/grafana/loki/issues/16543
  storage:
    type: local
    local:
      directory: /ruler_rules
  # 'fake' is the default tenant name in single tenant mode, rules are defined per tenant
  rule_path: /rules/fake
  enable_api: true
  enable_alertmanager_v2: true
  enable_alertmanager_discovery: true
  alertmanager_url: http://_web._tcp.alertmanager-operated.monitoring.svc.cluster.local

# This configuration is only used when -use-thanos-objstore=true is passed
ruler_storage:
  backend: my-named-store

storage_config:
  tsdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/index_cache
    cache_ttl: 24h
  object_prefix: loki
  # This configuration is used only when -use-thanos-objstore=true is NOT passed
  # (.storage_config.use_thanos_objstore is not set or set to false)
  named_stores:
    aws:
      my-named-store:
        endpoint: https://fake-s3:9000
        region: fake-region
        bucketnames: fake-bucket
  # This configuration is used only when -use-thanos-objstore=true IS passed
  # (.storage_config.use_thanos_objstore is true)
  object_store:
    named_stores:
      s3:
        my-named-store:
          endpoint: fake-s3:9000
          region: fake-region
          bucket_name: fake-bucket

# Enable anonymous usage reporting.
analytics:
  reporting_enabled: false
```

Loki will fail to start with

```
unsupported storage backend
error initialising module: ruler-storage
github.com/grafana/dskit/modules.(*Manager).initModule
	/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
	/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/loki/v3/pkg/loki.(*Loki).Run
	/src/loki/pkg/loki/loki.go:495
main.main
	/src/loki/cmd/loki/main.go:129
runtime.main
	/usr/local/go/src/runtime/proc.go:272
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1700
level=info ts=2025-03-04T22:36:10.441211622Z caller=main.go:126 msg="Starting Loki" version="(version=3.4.2, branch=release-3.4.x, revision=4fa045d3)"
level=info ts=2025-03-04T22:36:10.441243399Z caller=main.go:127 msg="Loading configuration file" filename=/etc/loki/config/config.yaml
level=error ts=2025-03-04T22:36:10.44213785Z caller=log.go:216 msg="error running loki" err="unsupported storage backend\nerror initialising module: ruler-storage\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:495\nmain.main\n\t/src/loki/cmd/loki/main.go:129\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"
```

**Expected behavior**

Expected Ruler to look for rules in the store defined in `.storage_config.object_store.named_stores.s3.my-named-store`.

It looks like `storage_config.object_stores` is field `ObjectStore` of type `bucket.ConfigWithNamedStores`, from type `Config` in `pkg/storage/factory.go`.

Whereas `.ruler_storage` is field `RulerStorage` of type `rulestore.Config` (`pkg/ruler/rulestore/config.go`), from type `Config` in `pkg/loki/loki.go`; it has embedded base type `bucket.Config`. It should probably be embedding `bucket.ConfigWithNamedStores` and use named-store aware loading for its `Backend` field.

**Environment:**
 - Infrastructure: Any
 - Deployment tool: Any
 
**Screenshots, Promtail config, or terminal output**

Inline above
