### ISSUE TITLE
Loki Helm Chart Configuration Issues (use_thanos_objstore)

### ISSUE THREAD

**Issue by TreeKat71** [grafana/loki#16599]
**Describe the bug**
I also post it in grafana community [here](https://community.grafana.com/t/loki-helm-chart-configuration-issues-use-thanos-objstore/145666)

In short, enable `use_thanos_objstore` and config `storage.object_store` should work fine. But it doesn't.
And without `storage.bucketNames.chunks`, I can't even do `helm install`

**To Reproduce**
Helm chart version: 6.27.0
Install values.yaml like:
```
deploymentMode: SimpleScalable

loki:
  storage:
    use_thanos_objstore: true

    bucketNames:
      chunks: dummy-value     <--- I have to use this to prevent an error

    object_store:
      type: s3
      prefix: null            <---- this seems buggy and need to be removed
```

**Expected behavior**
All S3 config should now be placed under `object_store` and should work fine.
But the `object_store.prefix` seems buddy and break Config

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
<img width="1616" alt="Image" src="https://github.com/user-attachments/assets/693501f9-0e6e-448d-b890-35d7ba77f3fa" />

**Comment by Tazmaniac** [comment]
It seems that there is no "use_thanos_objstore" support in the current Helm chart.
Need to to added before the (not planned yet) complete deprecation of the current objstore support.

**Comment by Tazmaniac** [comment]
Your link refer to the loki config.yaml not the allowed parameters in the helm values.yaml
The helm templates generating the k8s resources (and the loki yaml conf) are not aware of the new storage client config.
See the result of helm install --dry-run loki grafana/loki -f your-values.yaml

**Comment by P4sca1** [comment]
> Your link refer to the loki config.yaml not the allowed parameters in the helm values.yaml The helm templates generating the k8s resources (and the loki yaml conf) are not aware of the new storage client config. See the result of helm install --dry-run loki grafana/loki -f your-values.yaml

```sh
$ helm show values grafana/loki --version 6.27.0 | grep thanos
    {{- if and .Values.loki.storage.use_thanos_objstore .Values.ruler.enabled}}
  # -- In case of using thanos storage, enable use_thanos_objstore and the configuration should be done inside the object_store section.
    # Loki now supports using thanos storage clients for connecting to object storage backend.
    use_thanos_objstore: false
```

**Comment by P4sca1** [comment]
This should already be fixed by https://github.com/grafana/loki/pull/16266

**Comment by NathanBaulch** [comment]
FWIW, I worked around this issue by also setting `use_thanos_objstore` in the `loki.storage_config` section.

**Comment by taoyouh** [comment]
I tried with chart version 6.29.0. It seems that we still need to manually set `loki.storage_config.use_thanos_objstore` to let it work. I think we could populate `storage_config.use_thanos_objstore` with the value of `loki.storage.use_thanos_objstore` in the helm template?

My working version of values.yaml, where `use_thanos_objstore` must be set twice:
```
deploymentMode: SingleBinary
...
loki:
...
  storage:
    bucketNames:
      chunks: xxx
      ruler: xxx
      admin: xxx
    use_thanos_objstore: true
    object_store:
      type: s3
      s3:
        endpoint: oss-cn-wulanchabu-internal.aliyuncs.com
        region: oss-cn-wulanchabu
        secret_access_key: ${S3_ACCESS_KEY}
        access_key_id: ${S3_ACCESS_ID}

  storage_config:
    use_thanos_objstore: true
```

**Comment by Tazmaniac** [comment]
As of v6.29 chart
- Still need double use_thanos_objstore declaration
- If you're not using S3, generated ruler storage configuration is buggy. The support is halfway, a buggy "storage:" section is still build.

**Comment by fr34kyn01535** [comment]
Thanks for the hint, works when setting both declarations. Receiving _"error running loki" err="at least one bucket name must be specified"_ otherwise. Would love to see any of this be reflected in any documentation, documentation is an absolute steaming pile of shawarma.. The deprecated loki-distributed docs should be removed from the interwebs, and helm docs need proper examples..

**Comment by VtG242** [comment]
6.30.1 chart

-  double use_thanos_objstore declaration needed still
-  ruler_storage configuration for s3 generated even in case that local storage is used, ruler pod is running  but no rules executed

If ruler_storage is modified to use local storage manually e.g. :
```
ruler_storage:
  backend: local
  local:
    directory: /etc/loki/rules
```
Everything is OK and ruler is executing rules as expected.

**Comment by Tazmaniac** [comment]
As of today (not released):
- Double declaration should no longer needed. Fix : https://github.com/grafana/loki/commit/81866d790cb1f3140d5ddf7f9e50a0083c7accd8
- ruler_storage configuration still has no complete thanos objectstore support.

**Comment by 1tft** [comment]
It seems, that not only ruler_storage has no complete thanos objectstore support, also for GEL admin_client seems not to support it yet.

**Comment by jkroepke** [comment]
Can someone confirm here that the issue from helm point of view is resolved?

**Comment by Tazmaniac** [comment]
I see nothing in the latest merges that correct the fact that helm thanos objectstore support is incomplete.
I don't want to tweak manually generated resources. So migrating to  thanos objectstore is not possible for me.

**Comment by jkroepke** [comment]
But it sounds more like an product issue and not a helm chart issue?

I'm asking, because the Helm Chart has support for thanos_objstore for ruler and chunks

**Comment by Tazmaniac** [comment]
No, the generated config is/was broken for me.
Manual config on bare-os or on manually tweaked k8s resources is OK.
Could no double check the helm stratus now as I am away on holiday. Will re-check/retry when I will be back.

**Comment by jkroepke** [comment]
Not sure if https://github.com/grafana/loki/pull/17024 helps but it would be great to know what needs to be modified.

**Comment by Tazmaniac** [comment]
Ok, better but not complete:
diff between without and with thanos objstore:

```
      ruler:
        storage:
          azure:
            account_key: <my_key>
            account_name: lokistorage
            container_name: loki
-           use_federated_token: false
-           use_managed_identity: false
+         storage_prefix: null
          type: azure
        wal:
          dir: /var/loki/ruler-wal
+     ruler_storage:
+       azure:
+         account_key: <my_key>
+         account_name: lokistorage
+         container_name: loki
+       backend: azure
+       storage_prefix: null
```

As [docs](https://github.com/grafana/loki/docs/sources/setup/migrate/migrate-storage-clients/_index.md) says, with thanos objstore enabled, ruler storage should be declared under ruler_storage which is OK.

But a ruler.storage section is still built.
- which is I think wrong
- and use "storage_prefix" parameter which is unknown with the old azure storage subsystem.

which lead to runtime error: 
```
failed parsing config: /etc/loki/config/config.yaml: yaml: unmarshal errors:
  line 98: field storage_prefix not found in type base.RuleStoreConfig. Use `-config.expand-env=true` flag if you want to expand environment variables in your config file
```
https://github.com/grafana/loki/blob/0ec355c349fbbd5f2a969adf979bb6a6a61f80f8/production/helm/loki/templates/_helpers.tpl#L216 should not mess with Values.loki.storage.use_thanos_objstore
```
{{/*
Storage config for ruler
*/}}
{{- define "loki.rulerStorageConfig" -}}
{{- if .Values.loki.storage.use_thanos_objstore -}}
type: {{ .Values.loki.storage.object_store.type | quote }}
{{- include "loki.thanosStorageConfig" (dict "ctx" . "bucketName" .Values.loki.storage.bucketNames.ruler) | nindent 0 }}
{{- else if .Values.minio.enabled -}}
type: "s3"
s3:
  bucketnames: ruler
{{- else if (eq (include "loki.isUsingObjectStorage" . ) "true") }}
type: {{ .Values.loki.storage.type | quote }}
{{- include "loki.lokiStorageConfig" (dict "ctx" . "bucketName" .Values.loki.storage.bucketNames.ruler) | nindent 0 }}
{{- else }}
type: "local"
{{- end }}
{{- end -}}
```
but Values.loki.storage.use_thanos_objstore should be taken into account at the calling site:
https://github.com/grafana/loki/blob/0ec355c349fbbd5f2a969adf979bb6a6a61f80f8/production/helm/loki/templates/_helpers.tpl#L379

```
{{/* Loki ruler config */}}
{{- define "loki.rulerConfig" }}
ruler:
  storage: <------------- should be conditional on "loki.isUsingObjectStorage" not true
    {{- include "loki.rulerStorageConfig" . | nindent 4}}
{{- if (not (empty .Values.loki.rulerConfig)) }}
{{- toYaml .Values.loki.rulerConfig | nindent 2}}
{{- end }}
{{- end }}

{{/* Ruler Thanos Storage Config */}}
{{- define "loki.rulerThanosStorageConfig" -}}
{{- if and .Values.loki.storage.use_thanos_objstore .Values.ruler.enabled}}
  backend: {{ .Values.loki.storage.object_store.type }}
  {{- include "loki.thanosStorageConfig" (dict "ctx" . "bucketName" .Values.loki.storage.bucketNames.ruler) | nindent 2 }}
{{- end }}
{{- end }}
```
But I am perhaps wrong.

**Comment by Tazmaniac** [comment]
Could possibly be fixed by https://github.com/grafana/loki/commit/62caeedd7c8ccf41bd00d933de052c5df8476c6b

Will test with the next helm chart release.

**Comment by Tazmaniac** [comment]
As of today, after https://github.com/grafana/loki/commit/43dfc9740e8ea357758cbbd6accb6c8f8ea0c358 and helm chart 6.37.0 release:
- a spurious ruler.storage section is still generated along a proper ruler.ruler_storage section:
```
    ruler:
      storage:
        s3:
          bucketnames: loki
          insecure: false
          s3forcepathstyle: false
        type: s3
    ruler_storage:
      azure:
        account_key: <mykey>
        account_name: <myaccount>
        container_name: loki
      backend: azure
      storage_prefix: null

```
- but the configuration is valid and properly load.

I finally migrate my cluster from 3.4.2 to 3.5.3 with thanos_objstore as documented.
