### ISSUE TITLE
Sampling of log lines

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#166]
Promtail could support sampling of log-lines based on regexp patterns. This helps systems logging too much.

A simple config would be:
```yaml
- regex: http 200 .*
  sampling: 0.01
- regex: http 500 .*
  sampling: 1
- regex: .*error.*
  sampling: 1
- regex: .*
  sampling: 0.1
```
