### ISSUE TITLE
Delete request is stuck in "received"

### ISSUE THREAD

**Issue by phyzical** [grafana/loki#16606]
**Describe the bug**
Basically i had a rogue container that start hitting me with 290k logs A SECOND, this resulted in around 30gb of logs every hour, i noticed once my server alerted me of space running out but i assume it going for a few hours.

Anyway i then decided to try and just cull all logs from this specific container, But no matter what i try i cannot seem to get the delete requests to move from "received"?

**To Reproduce**
So i created a request with `curl -X POST -g 'http://192.168.69.111:3100/loki/api/v1/delete?query={container="dockdns"}&start=1677996312' -H 'X-Scope-OrgID:fake'`

Then i can see it was received via 
```
curl -g 'http://192.168.69.111:3100/loki/api/v1/delete?query={container="dockdns"}&start=1677996312' -H 'X-Scope-OrgID:fake'
```

```
[{"request_id":"74e495a1","start_time":1677996312,"end_time":1741257797.699,"query":"{container=\"dockdns\"}","status":"received","created_at":1741257797.699}]
```

i waited a day and still nothing,

**Expected behavior**
delete logs

**Environment:**
i am running via docker https://hub.docker.com/r/grafana/loki/ 

version is 3.4.2

**Screenshots, Promtail config, or terminal output**

config is 

```
auth_enabled: false
analytics:
  reporting_enabled: false
server:
  http_listen_port: 3100

ingester:
  wal:
    dir: /loki/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h
    - from: "2024-11-02"
      index:
        period: 24h
        prefix: index_
      object_store: filesystem
      schema: v13
      store: tsdb
compactor:
  working_directory: /loki/retention
  compaction_interval: 6m
  retention_enabled: true
  retention_delete_delay: 10m
  retention_delete_worker_count: 150
  delete_request_store: filesystem
storage_config:
  boltdb:
    directory: /loki/index
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index
    cache_location: /loki/tsdb-cache  
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 1024
  ingestion_burst_size_mb: 1024
#  retention_period: 8640h
  deletion_mode: filter-and-delete
frontend:
  address: 127.0.0.1  
```

**Comment by phyzical** [comment]
Also out of the 150gb being taken up 145gb of it is in `chunks/fake`

as a follow up incase i fail to get the delete request to ever clear, whats the best way to manually cull whats in fake?

is it safe to just remove or will this cause issues in regards to say indexes?

**Comment by rafamiga** [comment]
Same here, I want to delete test log data and my requests are sitting in "received" state for more than 8 hours now. 
```
loki --version
loki, version 3.5.0 (branch: k248, revision: 4b16bc4f)
```
Running in a k3s cluster with minio as storage backend. Here's a revelant `values.yaml` part:

```
loki:
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  compactor:
    retention_enabled: true
    # working_directory: /loki/retention
    # delete_request_store: filesystem
    delete_request_store: s3
[…]
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 20d
    reject_old_samples: false
    reject_old_samples_max_age: 7d
    ingestion_rate_mb: 40
    max_query_series: 2000
```

Just curious if this report will get anywhere.

BTW: The compactor configuration is not well documented, I had to rely on searching the web for getting it to accept delete queries.
