### ISSUE TITLE
Logs cannot be query after migrate to tsdb

### ISSUE THREAD

**Issue by wwyhy** [grafana/loki#16650]
**Describe the bug**
I have upgraded the Loki from 2.9.10 to 3.3.0, and migrated index from boltdb to tsdb on 27th Feb.
after migrated, I can only can query logs from 27th Feb, but cannot query logs before 27th Feb(like, 25th Feb).

I checked the object storage(azure blob), it seems the data file is in there before 27th Feb, but only have index file on 27th Feb and later.

<img width="730" alt="Image" src="https://github.com/user-attachments/assets/d0a7f4e5-cc77-4409-a5bd-0a9df4ed2a6c" />

<img width="725" alt="Image" src="https://github.com/user-attachments/assets/1b86f762-b925-443e-b792-7a5cf8698d34" />

**To Reproduce**
1. Started Loki (from 2.9.10 to 3.3.0)
2. Started Fluentbit

**Expected behavior**
Logs can be query before last Friday and after last Friday.

**Environment:**
 - Infrastructure: [k8s]
 - Deployment tool: [helm with microservices mode]

**Screenshots, Promtail config, or terminal output**

**Before migrate config:**
```yaml
schema_config:
  configs:
  - from: "2022-10-15"
    index:
      period: 24h
      prefix: monitoring-system_index_
    object_store: azure
    schema: v11
    store: boltdb-shipper

storage_config:
  boltdb_shipper:
    shared_store: azure

limits_config:
  retention_period: 720h
```

**After Migrate config:**
```yaml
schema_config:
  configs:
  - from: "2022-10-15"
    index:
      period: 24h
      prefix: monitoring-system_index_
    object_store: azure
    schema: v13
    store: boltdb-shipper
  - from: "2024-12-15"
    index:
      prefix: monitoring-system_index_
      period: 24h
    store: tsdb
    object_store: azure
    schema: v13

storage_config:
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/boltdb-cache
    cache_ttl: 24h
  tsdb_shipper:
    active_index_directory: /var/loki/tsdb-index
    cache_location: /var/loki/tsdb-cache
    cache_ttl: 24h

limits_config:
  retention_period: 720h
```

is it caused by no index generate? how to re-build the index or fix this issue? 

Thanks!

**Comment by Tazmaniac** [comment]
Try to remove theses two lines:
    active_index_directory: /var/loki/tsdb-index
    cache_location: /var/loki/tsdb-cache
The location/directory parameters where previously needed because the defaults was not working with the provided images.
It seems to be fixed now, and the result is the reverse.
That fixed the problem for me.
On image based install, we should never have had to set these parameters.

**Comment by wwyhy** [comment]
@Tazmaniac 
both lines cannot be removed. otherwise it will raise error

`level=error ts=2025-03-11T02:56:41.422833764Z caller=main.go:70 msg="validating config" err="MULTIPLE CONFIG ERRORS FOUND, PLEASE READ CAREFULLY\nCONFIG ERROR: `tsdb` index type is configured in at least one schema period, however, `storage_config`, `tsdb_shipper`, `active_index_directory` is not set, please set this directly or set `path_prefix:` in the `common:` section\nCONFIG ERROR: `tsdb` index type is configured in at least one schema period, however, `storage_config`, `tsdb_shipper`, `cache_location` is not set, please set this directly or set `path_prefix:` in the `common:` section"`

**Comment by Tazmaniac** [comment]
Did you modify the loki config or the helm values ?
My helm values:
```
  storage_config:
    tsdb_shipper:
      cache_ttl: 24h
  schemaConfig:
    configs:
    - from: "2024-04-22"
      store: tsdb
      object_store: azure
      schema: v13
      index:
        period: 24h
```
Resulting generated configuration with helm chart 6.27 (loki 3.4.2) or 6.21.0 (first loki 3.3.0)
```
    storage_config:
      bloom_shipper:
        working_directory: /var/loki/data/bloomshipper
      boltdb_shipper:
        index_gateway_client:
          server_address: dns+loki-backend-headless.loki.svc.cluster.local:9095
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
      tsdb_shipper:
        cache_ttl: 24h
        index_gateway_client:
          server_address: dns+loki-backend-headless.loki.svc.cluster.local:9095
```
I use simple-scalable mode but it should not change drasticaly.

And a path_prefix is correctly generated in the common section too:
```
    common:
      compactor_address: 'http://loki-backend:3100'
      path_prefix: /var/loki
      replication_factor: 3
      storage:
        azure:
            ...........
```
