### ISSUE TITLE
Panic on startup

### ISSUE THREAD

**Issue by abacef** [grafana/loki#16698]
**Describe the bug**
Starting loki with config

```
auth_enabled: false


server:
  http_listen_port: 3100

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
```

gives the unhelpful error
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/grafana/loki/v3/pkg/loki.validateSchemaRequirements(0xc000c74000)
        /src/loki/pkg/loki/validation.go:33 +0x712
github.com/grafana/loki/v3/pkg/loki.(*Config).Validate(0xc000c74000)
        /src/loki/pkg/loki/loki.go:318 +0x1815
main.main()
        /src/loki/cmd/loki/main.go:69 +0x637
```

**To Reproduce**
1. Started Loki 3.4.2 with the following config (on linux amd64)

**Expected behavior**
give a useful error message

**Environment:**
started binary

**Screenshots, Promtail config, or terminal output**
N/A

**Comment by hbobenicio** [comment]
I'm facing the same issue here.

My config is different, but the point is the same: the unhelpful message so we don't know what is the problem specifically with the config.

I see above that some work (PR) has been made about it. Looking forward for that PR to be merged...

**Comment by pcgeek86** [comment]
Same problem here. Just tried to add Loki to my Docker Compose stack on one of my Linux servers. I followed the documentation to configure the Docker Compose file, and made some minor tweaks to it.

Here is the Docker Compose snippet:

```yml
services:
  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    ports:
    - 3100:3100
    pull_policy: always
    volumes:
    - ./loki/data:/loki
    - ./loki/local-config.yaml:/etc/loki/local-config.yaml
    command:
    - -config.file=/etc/loki/local-config.yaml
```

And here's my extremely basic / minimal Loki YAML configuration snippet:

```
server:
  http_listen_port: 3100
```

I'm just getting this error over and over again. I have no idea what's wrong from the vague error message.

```
goroutine 1 [running]:
github.com/grafana/loki/v3/pkg/loki.validateSchemaRequirements(0xc000cd2000)
        /src/loki/pkg/loki/validation.go:33 +0x712
github.com/grafana/loki/v3/pkg/loki.(*Config).Validate(0xc000cd2000)
        /src/loki/pkg/loki/loki.go:348 +0x1e8c
main.main()
        /src/loki/cmd/loki/main.go:69 +0x625
```

Where do we go from here? 🤷🏻‍♂️
