### ISSUE TITLE
Out of order inserts throw 500 errors

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#168]
Currently attempting to insert Out of Order throws 500 errors. We also don't support inserting two lines with the same timestamp.

**Comment by afiskon** [comment]
I'm afraid the support of out of order logs is mandatory for the release of Loki. Here is why.

I wrote a simple client library https://github.com/afiskon/promtail-client It's README includes a client example.

If you run it in a single process everything works just fine:
```
$ ./loki-example proto
2019/01/17 16:16:40 Error: The time is 2019-01-17 16:16:40.509173 +0300 MSK m=+0.019247359, i = 1
2019/01/17 16:16:41 Error: The time is 2019-01-17 16:16:41.512412 +0300 MSK m=+1.022477432, i = 2
2019/01/17 16:16:42 Error: The time is 2019-01-17 16:16:42.517708 +0300 MSK m=+2.027764858, i = 3
2019/01/17 16:16:43 Error: The time is 2019-01-17 16:16:43.519887 +0300 MSK m=+3.029934055, i = 4
```
However when I start multiple processes in different terminals logs get rejected with out-of-order errors:

```
2019/01/17 16:17:23 promtail.ClientProto: Unexpected HTTP status code: 500, message: rpc error: code = Unknown desc = Entry out of order
```

In other words currently Loki can be used only with a single process or mkicroservice. If your system has 2+ microservices, currently you just can't use Loki.

**Comment by olafure** [comment]
@woodsaj I notice this dates back since 19/12 and hasn't been labelled as a bug (as per the comment [above](https://github.com/grafana/loki/issues/168#issuecomment-455169837)).  Perhaps stick the label on so it gets some TLC :)

**Comment by woodsaj** [comment]
support for log entries with the same timestamp is being addressed in #288

**Comment by afiskon** [comment]
Hello,

I decided to test the patch using docker-compose and recent images from DockerHub. I still get:

```
2019/02/08 14:34:05 promtail.ClientProto: Unexpected HTTP status code: 400, message: Entry out of order
```

... in the second terminal window. Images versions:

```
$ docker-compose images
   Container         Repository       Tag       Image Id      Size
--------------------------------------------------------------------
temp_grafana_1    grafana/grafana    master   8905a7bc010e   232 MB
temp_loki_1       grafana/loki       master   66862f6b38aa   32.2 MB
temp_promtail_1   grafana/promtail   master   42300bf69b30   50.2 MB
```

Docker hub says that these images were updated ~20 minutes ago, thus I believe they should include recent changes. It seem that the patch didn't work. Or maybe I did something wrong?

**Comment by UzairM** [comment]
i am getting the same issue as afiskon

**Comment by afiskon** [comment]
Here are exact steps to reproduce:

1) Make sure no images are running:

```
$ docker-compose ps
Name   Command   State   Ports
------------------------------
```

2) Create a new empty directory:

```
mkdir loki-test
cd loki-test
```

3) Create docker-compose.yaml:

```
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:master
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:master
    volumes:
      - /var/log:/var/log
    command:
      -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    environment:
      GF_EXPLORE_ENABLED: "true"
    networks:
      - loki
```
4) Run `docker-compose pull`, then `docker-compose up`
5) Open http://localhost:3000/, login/password are admin/admin
6) Open http://localhost:3000/login, add a new Loki datasource with URL: `http://loki:3100` (`loki` is a local Docker network)
7) Build `loki-example` using the source code in README.md in this repository https://github.com/afiskon/promtail-client

```
$ pwd
/Users/eax/go/src/go-sandbox/loki-example
$ ls
main.go
$ go build
```

8) Execute `./loki-example proto` in one terminal window and simultaneously `./loki-example proto` in the second window.

Expected behavior: Both programs terminate normally. 

Actual behavior: There is a `Unexpected HTTP status code: 400, message: Entry out of order` error in the second terminal window.
