### ISSUE TITLE
Enhancement Request: Index on Cassandra, Chunks on S3?

### ISSUE THREAD

**Issue by sdwire** [grafana/loki#1681]
Our on-prem datacenter has an S3-compatible object store for cheap long-term storage, but - being an on-prem environment - we don't have AWS's DynamoDB available for indexes.

We'd like to use Cassandra for the indexes and S3(-compatible) Object Storage for chunks. This combination would make Loki the perfect solution for our logs, but the current documentation suggests this isn't currently an option. Am I misreading?

**Comment by owen-d** [comment]
Hey, this is definitely do-able. You'll want to set up both storage configs (`aws` and `cassandra`). Then in your [schema](https://github.com/grafana/loki/blob/master/docs/configuration/README.md#schema_config) you just set `store: cassandra` and `object_store: s3`. 

If you have any trouble let us know (and/or submit a docs PR if it wasn't clear and you get everything working)

**Comment by vijay-jindal** [comment]
Hi,
I am trying to store indexes on cassandra, but I keep getting this error :

**level=error ts=2020-02-24T18:54:52.789922236Z caller=main.go:66 msg="error initialising loki" err="error initialising module: table-manager: gocql: unable to create session: unable to discover protocol version: dial tcp 192.168.0.100:9042: i/o timeout"** 

My configuration for Cassandra is as follows :
```
  schema_config:
    configs:
    - from: 2018-04-15
      store: cassandra
      object_store: filesystem
      schema: v9
      index:
        prefix: cassandra_table
        period: 168h
  server:
    http_listen_port: 3100
  storage_config:
    cassandra:
      username: cassandra
      password: cassandra
      timeout: 10s
      connect_timeout: 10s
      addresses: 192.168.0.100:9042
      auth: true
      keyspace: lokiindex
    filesystem:
      directory: /data/loki/chunks

```
I tried it with Kubernetes cluster on GCP as well as with minikube and still got the same issue.
I have implemented Loki and promtail using Loki-stack (here : https://github.com/grafana/loki/tree/master/production/helm/loki-stack)

I only made changes to the values.yaml in loki chart by adding the above configuration.

Let me know if any of you faced this issue and got a solution.

Thanks.
