### ISSUE TITLE
Unable to migrate to thanos object storage configuration due to storage prefix contains invalid characters

### ISSUE THREAD

**Issue by matthewhudsonedb** [grafana/loki#16931]
**Describe the bug**
We are unable to migrate to the new thanos object storage configuration due to storage prefix contains invalid characters. Our existing loki configration allowed for the dash special character -
being set in `object_prefix`. The new thanos object storage `storage_prefix` config does not accept this special character.

We receive this error when attempting to run the same prefix with the new configuration:
```
CONFIG ERROR: invalid storage_config config: invalid object store config: storage prefix contains invalid characters, it may only contain digits and English alphabet letters
```

Old config:
```    
storage_config:
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index_cache
        cache_ttl: 24h
      object_prefix: test-logs
```
New Config:
```
storage_config:
   use_thanos_objstore: true
   object_store:
      storage_prefix: "test-logs"
```

**To Reproduce**
1. Setup loki with old config as above
2. Attempt to migrate to New Config using the use_thanos_objstore client

**Expected behavior**
I would expect the storage_prefix values to accept the same charset that was available in the old config.
We have thanos configered with the dash as a prefix setting, so don't understand why it is not available with loki's implementation of the prefix.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
N/A
