### ISSUE TITLE
Deprecated fields in loki-local-config causing unmarshal error

### ISSUE THREAD

**Issue by sunwupark** [grafana/loki#16990]
**Describe the bug**
Certain configuration fields in the Loki config are no longer valid in the current version, but still appear in some loki-local-config file

The fields include:
- metric_aggregation_enabled under limits_config
- metric_aggregation under pattern_ingester
- enable_multi_variant_queries under querier.engine

**To Reproduce**
1. Started Loki with the following config:
```
limits_config:
  metric_aggregation_enabled: true

pattern_ingester:
  enabled: true
  metric_aggregation:
    loki_address: loki:3100

querier:
  engine:
    enable_multi_variant_queries: true
```
2. Run docker run grafana/loki:latest -config.file=/etc/loki/local-config.yaml
3. Error occurs:

**Expected behavior**
Ignore deprecated fields with a warning
OR explicitly remove them from all documentation and example config files

**Environment:**
 - Infrastructure: laptop, macos
 - Deployment tool: docker compose

**Screenshots, Promtail config, or terminal output**
```
failed parsing config: /etc/loki/local-config.yaml: yaml: unmarshal errors:
  line 29: field metric_aggregation_enabled not found in type validation.plain
  line 43: field metric_aggregation not found in type pattern.Config
  line 54: field enable_multi_variant_queries not found in type logql.EngineOpts.
```
