### ISSUE TITLE
More directory permissions required for glob pattern in Promtail v3.4.0

### ISSUE THREAD

**Issue by t-gebauer** [grafana/loki#17001]
**Describe the bug**
Since Promtail 3.4.0 our glob pattern does no longer match any files, because our promtail user does not have the read permission to one of the directories in the path. (This used to be fine in Promtail 3.3.2 and earlier.)

We tracked this problem to the update of the doublestar library in [release 3.4.0](https://github.com/grafana/loki/releases/tag/v3.4.0):

> deps: update module github.com/bmatcuk/doublestar to v4 (https://github.com/grafana/loki/issues/14977) ([a2b66d3](https://github.com/grafana/loki/commit/a2b66d35bdc29c54e44e1d5f5eb56536be98a41a))

I could reproduce the problem in the doublestar library: https://github.com/bmatcuk/doublestar/issues/103

**To Reproduce**
1. Create the following directory structure and log file:
    ```sh
    mkdir -p promtail-test/foo01/static/foo01/log
    echo foo >> promtail-test/foo01/static/foo01/log/2025-02-02.log
    ```
2. Remove read permission from one of the "not globbed" directories:
   ```sh
    chmod -r promtail-test/foo01
   ```
2. Start Promtail 3.4.0 with config file below
    ```sh
    promtail -config.file promtail-dummy-config.yml -log.level=debug
    ```

**Expected behavior**
Promtail starts tailing the file ("tailing new file") and tries to contact Loki. (works in 3.3.2)

**Actual behavior**
Instead, Promtail 3.4.0 outputs: "no files matched requested path, nothing will be tailed". And does nothing.

**Environment:**
 - Infrastructure: laptop, Linux
 - Deployment tool: none

**Screenshots, Promtail config, or terminal output**

promtail-dummy-config.yml
```yaml
server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: positions.yaml

# client connection is required, but does not matter, we won't get this far
clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: dummy
    static_configs:
      - targets:
          - localhost
        labels:
          service_name: dummy
          __path__: promtail-test/*/static/*/log/*.log
```
