### ISSUE TITLE
[docker-driver] Allow passing pipeline config inline

### ISSUE THREAD

**Issue by brunowowk** [grafana/loki#1711]
**Is your feature request related to a problem? Please describe.**

I'm using the docker logging driver on a swarm setup. I make remote deploys using `docker stack deploy`, so the images are fetched from my docker registry.

The problem is the plugin only allows specifying the pipeline using a file, and the file should be available on the host running the container. In my setup the pipeline file is not deployed to the server, and on a swarm setup that wouldn't be viable, as I would have to change my deploy process to push files to every swarm node instead of just a single manager node.

**Describe the solution you'd like**

If you add the `loki-pipeline` option to the driver, accepting an inlined version of the pipeline file, those configs would be pushed to the swarm and used on any of the nodes.

**Describe alternatives you've considered**

I've considered copying the pipeline files to my servers, but that would make deploys much slower and harder to maintain.

**Additional context**

Sample docker-compose.yml file with that option:
```yaml
version: "3.7"
services:
  sample-service:
    image: sample/service:latest
    logging:
      driver: loki
      options:
        loki-url: 'https://<user_id>:<password>@logs-us-west1.grafana.net/loki/api/v1/push'
        loki-pipeline:
          pipeline_stages:
            - regex:
                expression: '(level|lvl|severity)=(?P<level>\w+)'
            - labels:
                level:
```
