### ISSUE TITLE
Timeout error while trying to store Indexes in Cassandra

### ISSUE THREAD

**Issue by vijay-jindal** [grafana/loki#1734]
**Bug Description**
Hi,
I am trying to store indexes on cassandra, but I keep getting this error :

**level=error ts=2020-02-24T18:54:52.789922236Z caller=main.go:66 msg="error initialising loki" err="error initialising module: table-manager: gocql: unable to create session: unable to discover protocol version: dial tcp x.x.x.x:9042: i/o timeout"** 

My configuration for Cassandra is as follows :
```
  schema_config:
    configs:
    - from: 2018-04-15
      store: cassandra
      object_store: filesystem
      schema: v9
      index:
        prefix: cassandra_table
        period: 168h
  server:
    http_listen_port: 3100
  storage_config:
    cassandra:
      username: cassandra
      password: cassandra
      timeout: 10s
      connect_timeout: 10s
      addresses: 192.168.0.100:9042
      auth: true
      keyspace: lokiindex
    filesystem:
      directory: /data/loki/chunks

```
I tried it with Kubernetes cluster on GCP as well as with minikube and still got the same issue.
I have implemented Loki and promtail using Loki-stack (here : https://github.com/grafana/loki/tree/master/production/helm/loki-stack)

I only made changes to the values.yaml in loki chart by adding the above configuration.

Let me know if any of you faced this issue and got a solution.

**To Reproduce**
1. Add loki-stack to your helm repo
2. Setup a cassandra cluster
3. Add the above configuration in values.yaml of Loki chart without making any other changes to the loki-stack chart.

**Expected behavior**
It is suppose to connect to cassandra, create a keyspace named lokiindex and then store the indexes in cassandra.

**Environment:**
 - Infrastructure: Kubernetes,Minikube
 - Deployment tool:  helm

**Screenshots, Promtail config, or terminal output**
<img width="1271" alt="Screenshot 2020-02-25 at 12 41 14 AM" src="https://user-images.githubusercontent.com/25745453/75183163-ee54bc00-5767-11ea-8892-ffac41d9abe6.png">
