### ISSUE TITLE
Cannot use approx_topk in either Grafana or directly on the API

### ISSUE THREAD

**Issue by someStrangerFromTheAbyss** [grafana/loki#17425]
**Describe the bug**
When trying to use the **approx_topk** feature for approximate top results of queries, loki returns the following error:
`parse error at line 1, col 1: syntax error: unexpected IDENTIFIER`

Seems loki does not recognize the approx_topk even though it should.

**To Reproduce**
Loki version: 3.4.3
Grafana version: Grafana v11.4.3

Have a config similar to this one:

```

common:
  compactor_address: 'http://loki-backend:3100'
  path_prefix: /var/loki
  replication_factor: 1
  storage:
...
limits_config:
  metric_aggregation_enabled: false
  allow_structured_metadata: true
  shard_aggregations:
  - approx_topk
  discover_service_name: []
  ingestion_burst_size_mb: 30
  ingestion_rate_mb: 30
  ingestion_rate_strategy: local
  max_cache_freshness_per_query: 10m
  max_chunks_per_query: 100
  max_concurrent_tail_requests: 100
  max_entries_limit_per_query: 1000
  max_global_streams_per_user: 50000
  max_label_names_per_series: 17
  max_line_size_truncate: false
  max_query_length: 14d1h
  max_query_lookback: 14d1h
  max_query_parallelism: 128
  max_query_range: 6d
  max_query_series: 50
  max_streams_matchers_per_query: 100
  otlp_config:
    resource_attributes:
      attributes_config:
      - action: index_label
        regex: rome.project.id
      - action: index_label
        regex: resources."service.name"
      - action: index_label
        regex: service.name
      ignore_defaults: true
  per_stream_rate_limit: 20Mb
  per_stream_rate_limit_burst: 30Mb
  query_timeout: 300s
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 2d
  shard_streams:
    desired_rate: 3000000
    enabled: true
  split_queries_by_interval: 1h
  tsdb_max_bytes_per_shard: 2GB
  tsdb_max_query_parallelism: 2048
  volume_enabled: true
memberlist:
  join_members:
  - loki-memberlist
pattern_ingester:
  enabled: false
query_range:
  align_queries_with_step: true
...
```

**Expected behavior**
I expect the following query to work:
`approx_topk(1,rate({ubi_project_id="83ebddba-0f99-4965-9148-29e6d077f95e"}[1m]))`

Since the equivalent works with topk:
`topk(1,rate({ubi_project_id="83ebddba-0f99-4965-9148-29e6d077f95e"}[1m]))`

**Environment:**
 - Kubernetes in simple scalable mode

**Screenshots, Promtail config, or terminal output**
In grafana:

![Image](https://github.com/user-attachments/assets/cacf9455-963a-4280-8f83-bad49b83a8fd)

in POSTMAN directly:

![Image](https://github.com/user-attachments/assets/f97b831e-67fe-4edc-8d14-e1081524fa21)
