### ISSUE TITLE
All recordingRules `sum` across pods causing inflated series

### ISSUE THREAD

**Issue by TheRealNoob** [grafana/loki#17439]
**Describe the bug**

The problem I'm seeing is that all of the recording rules perform a `sum()` aggregation across all pods of each component, which is incorrect when coupled with the way the alerting rules and dashboards are written.  Spoken less broadly because I know it's difficult to follow through all the jargon, I will use an example - the one that turned me onto this issue.

[link](https://github.com/grafana/loki/blob/main/production/helm/loki/src/rules.yaml.tpl) to rules.yaml.tpl ([permalink](https://github.com/grafana/loki/blob/3f1fb469a80755b9811dda544546d7b35771b664/production/helm/loki/src/rules.yaml.tpl))

The `namespace_job_route:loki_request_duration_seconds:99quantile` recording rule metric is defined by:
```
    - expr: histogram_quantile(0.99, sum(rate(loki_request_duration_seconds_bucket[1m]))
        by (le, namespace, job, route))
      labels:
        cluster: mgmt1
      record: namespace_job_route:loki_request_duration_seconds:99quantile
```

It is used in the alerting rule:
```
      - alert: LokiRequestLatency
        annotations:
          message: |
            {{ $labels.job }} {{ $labels.route }} is experiencing {{ printf "%.2f" $value }}s 99th percentile latency.
        expr: |
          namespace_job_route:loki_request_duration_seconds:99quantile{route!~"(?i).*tail.*"} > 1
        for: 15m
        labels:
          severity: critical
```

Now, the `loki_request_duration_seconds_bucket` is a counter, so it is correct to perform a `rate(...[1m])` against it.  The next step is to `sum()` all resulting series.  So let's say you're application is taking 1 second to return each request and you're running 4 pods, the result will be 4 second latency.  Next step you'll take the p99 of that.  I'm overly simplifying but you should be able to follow.

Moving onto the alerting rule, it's intended to trigger if latency is greater than 1 second.  Each pod /endpoint in question is not above 1 second, but because they were `sum`ed together, the alert triggers.

I haven't dug into every single recording rule, but at a glance it seems all rules are affected as they're all using `sum()` inappropriately.

**To Reproduce**
N/A

**Expected behavior**
Very broadly there's two routes forward.  Either
1. continue to graph/alert on an aggregated metric.  For example change all `sum` operations become `avg`.  This approach assumes that all load balancing operations are working nominally.
2. change to graphing/alerting on a per-pod basis.  This approach has the potential to be a lot noisier because it bypasses assumptions about load balancing operations.

The first option is simpler to implement since it doesn't require changing any dashboards/alerts, only recording rules.  I don't want to get too deep into potential solutions here now as that should be discussed in comments.  Just wanted to high level overview it to set the stage.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**
N/A
