### ISSUE TITLE
LokiStack: CRD: storage: add support from valueFrom

### ISSUE THREAD

**Issue by Frankkkkk** [grafana/loki#17436]
**Is your feature request related to a problem? Please describe.**
The LokiStack storage secret needs an existing well-formated secret.

When using ceph, for example, an "s3" secret is generated by it, but it doesn't conform to Loki's structure. Thus an operator must create a new secret by taking the values from the existing one. For example:

Generated secret by ceph:
```yaml
Data
====
AWS_SECRET_ACCESS_KEY:  40 bytes
AWS_ACCESS_KEY_ID:      20 bytes
```

```yaml
storage:
  accessKey:
    valueFrom:
      type: secret
      name: foobar
      key: AWS_SECRET_ACCESS_KEY
   ...
```

This way, the operator never knows or touches the secrets

```

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
-

**Additional context**
Thanks!
