### ISSUE TITLE
We should document how to do alerting with Loki/Promtail

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1753]
**Is your feature request related to a problem? Please describe.**

We plan to do ruling and alerting like Prom with Alertmanager, but in the meantime we have multiple ways to already alerts on logs and I think we should document it.

This include alerting with Promtail/Alertmanager using stages or alerting with Grafana using Loki as Prometheus datasource.

We should also explain that you can use filter in the match selector stage:

```
pipeline_stages:
      - match:
          selector: '{app="promtail"} |= "panic"'
      - metrics:
          panic_total:
            type: Counter
            description: "total number of panic"
            config:
              match_all: true
              action: inc
```
