### ISSUE TITLE
Promtail: allow single job with multiple service discovery elements

### ISSUE THREAD

**Issue by rfratto** [grafana/loki#1754]
Users can't configure a single job with two different service discovery entries:

```yaml
- job_name: job
  static_configs:
    - targets:
        - localhost
      labels:
        name: a
        job: job
        __path__: /data/file.a.log
    - targets:
        - localhost
      labels:
        name: b
        job: job
        __path__: /data/file.b.log
```

When using this config, Promtail will only use the latest element in the array. I believe 
[these lines](https://github.com/grafana/loki/blob/8df56cea6e3830a505d7f455894cd72c474f4c50/pkg/promtail/targets/filetargetmanager.go#L111-L122) are the cause.
