### ISSUE TITLE
Enabling UI in Helm values does not work

### ISSUE THREAD

**Issue by rogly** [grafana/loki#17561]
**Describe the bug**
Enabling the UI using the helm chart does not properly update the Loki configuration file to enable the UI and therefore the UI service is not running on any pods.

**To Reproduce**
1. Enable UI using values.yaml:
```yaml
loki:
 image:
  tag: 3.5.0
 ui:
  enabled: true
   gateway:
    enabled: true
```
2. Deploy Loki with Helm: `helm upgrade --install grafana/loki --values values.yaml`
3. Open web browser to `http://{loki}.{domain}.{tld}/ui/`
4. Receive `HTTP 404` error

**Expected behavior**
Expected to be presented with the Loki UI

**Environment:**
 - Infrastructure: Kubernetes v1.31.7
 - Deployment tool: Helm
 - Deployment mode: Distributed (Gateway + Ingress)

**Screenshots, Promtail config, or terminal output**
The `enable` flag is never set in the ConfigMap:
```yaml
ui:
 discovery:
  join_peers:
  - loki-query-frontend.observability.svc.cluster.local
```

updating the config file template [lines](https://github.com/grafana/loki/blob/e89fd41a6aac3ed52f818cd92630855718c1cea4/production/helm/loki/values.yaml#L284C1-L290C15): 
```yaml
    {{- if .Values.loki.ui.enabled }}
    ui:
      discovery:
        join_peers:
          - '{{ include "loki.queryFrontendFullname" . }}.{{ $.Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}'
    {{- end }}
```
to:
```yaml
    {{- if .Values.loki.ui.enabled }}
    ui:
      enabled: {{ .Values.loki.ui.enabled }}
      discovery:
        join_peers:
          - '{{ include "loki.queryFrontendFullname" . }}.{{ $.Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}'
    {{- end }}
```
seems to resolve this issue pretty easily
