### ISSUE TITLE
Please add `lokiCanary.affinity` in the Helm chart

### ISSUE THREAD

**Issue by m3nthal** [grafana/loki#17580]
**Is your feature request related to a problem? Please describe.**
It would be great to have `affinity` configuration for `lokiCanary` in Loki Helm chart.

**Describe the solution you'd like**
Would be great to have `affinity` to be able to exlude some nodes. Good example would be to exclude AWS Fargate nodes, which could only be accomplished with `affinity.nodeAffinity`:
```
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: eks.amazonaws.com/compute-type
                      operator: NotIn
                      values: ["fargate"]
```

**Describe alternatives you've considered**
Kubernetes doesn't support negative nodeSelectors.

**Additional context**
Most of Helm charts I've seen support affinity for DaemonSets. Thank you!
