### ISSUE TITLE
The log can only be saved for a maximum of one day

### ISSUE THREAD

**Issue by zsksy123** [grafana/loki#17596]
Version Information
```
helm list
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/zld/kubeconfigs/xs.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/zld/kubeconfigs/xs.yaml
NAME               	NAMESPACE      	REVISION	UPDATED                             	STATUS  	CHART                          	APP VERSION
loki               	kube-prometheus	6       	2025-04-29 15:35:26.246468 +0800 CST	deployed	loki-6.29.0                    	3.4.2
```
configuration

```
global:
  # -- configures cluster domain ("cluster.local" by default)
  clusterDomain: "c1.xiaosuan.com"
deploymentMode: Distributed
loki:
  image:
    # -- The Docker registry
    registry: docker.io
    # -- Docker image repository
    repository: grafana/loki
    # -- Overrides the image tag whose default is the chart's appVersion
    tag: 3.4.2
    # -- Overrides the image tag with an image digest
    digest: null
    # -- Docker image pull policy
    pullPolicy: IfNotPresent
  # Should authentication be enabled
  auth_enabled: false
  server:
    http_listen_port: 3100
    grpc_listen_port: 9095
    http_server_read_timeout: 600s
    http_server_write_timeout: 600s
  # -- Limits config
  limits_config:
    retention_period: 189h
    max_concurrent_tail_requests: 20
    max_entries_limit_per_query: 50000
    otlp_config:
      resource_attributes:
        attributes_config:
          - action: index_label
            attributes:
            - service.group
    allow_structured_metadata: true
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_cache_freshness_per_query: 10m
    split_queries_by_interval: 15m
    query_timeout: 300s
    volume_enabled: true

  commonConfig:
    path_prefix: /var/loki
    replication_factor: 3
    compactor_address: '{{ include "loki.compactorAddress" . }}'

  storage:
    # Loki requires a bucket for chunks and the ruler. GEL requires a third bucket for the admin API.
    # Please provide these values if you are using object storage.
    bucketNames:
      chunks: ceph-bkt-ebe29555-972e-4b5a-98d0-97d8dea62788
      ruler: ceph-bkt-ebe29555-972e-4b5a-98d0-97d8dea62788
      admin: ceph-bkt-ebe29555-972e-4b5a-98d0-97d8dea62788
    type: s3
    s3:
      s3: http://rook-ceph-rgw-my-store.rook-ceph.svc.c1.xiaosuan.com:80/ceph-bkt-ebe29555-972e-4b5a-98d0-97d8dea62788
      endpoint: http://rook-ceph-rgw-my-store.rook-ceph.svc.c1.xiaosuan.com:80
      region: bj-xs
      secretAccessKey: 6RhGSydhqL3tAQJJTKuB20AEbZyqU9XV2gXSMQbY
      accessKeyId: YK9RFGZ2PBMSJ3X8PQJQ
      signatureVersion: null
      s3ForcePathStyle: true
      insecure: false
      http_config: {}
      # -- Check https://grafana.com/docs/loki/latest/configure/#s3_storage_config for more info on how to provide a backoff_config
      backoff_config: {}
      disable_dualstack: false
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  querier:
    max_concurrent: 4
  ingester:
    chunk_encoding: snappy

ruler:
  enabled: true
  replicas: 3
  maxUnavailable: 1

ingester:
  replicas: 3
  maxUnavailable: 1

distributor:
  replicas: 3
  maxUnavailable: 2

querier:
  replicas: 3
  maxUnavailable: 2

queryFrontend:
  replicas: 2
  maxUnavailable: 1

queryScheduler:
  replicas: 2
  maxUnavailable: 1

indexGateway:
  replicas: 2
  maxUnavailable: 1

compactor:
  replicas: 1
  working_directory: /data/retention
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: gcs

resultsCache:
  enabled: true
  persistence:
    # -- Enable creating PVCs for the results-cache
    enabled: enbaled
    # -- Size of persistent disk, must be in G or Gi
    storageSize: 100G
    # -- Storage class to be used.
    # If defined, storageClassName: <storageClass>.
    # If set to "-", storageClassName: "", which disables dynamic provisioning.
    # If empty or set to null, no storageClassName spec is
    # set, choosing the default provisioner (gp2 on AWS, standard on GKE, AWS, and OpenStack).
    storageClass: rook-ceph-block
    # -- Volume mount path
    mountPath: /data

minio:
  enabled: false

bloomPlanner:
  replicas: 0

bloomBuilder:
  replicas: 0

bloomGateway:
  replicas: 0

backend:
   replicas: 0

read:
   replicas: 0

write:
   replicas: 0

singleBinary:
   replicas: 0

test:
  enabled: false

lokiCanary:
  enabled: false

```
problem description

When I am browsing logs in Grafana, I can only view logs within one day at most.

<img width="1176" alt="Image" src="https://github.com/user-attachments/assets/feec3898-0a1f-4d6f-bdcb-3775c904b89c" />

**Comment by zsksy123** [comment]
Let me add some more details about my configuration. I read the documentation and made the necessary changes based on it. However, I'm still only able to query the logs for the past 3 hours within the Grafana interface.
```
ingester:
  replicas: 3
  maxUnavailable: 1
  query_ingesters_within: 0s
```
