### ISSUE TITLE
can't set object_store.s3.bucket_lookup_type via helm

### ISSUE THREAD

**Issue by okhowang** [grafana/loki#17595]
**Describe the bug**
can't set object_store.s3.bucket_lookup_type via helm
chart setting only follow values for object_store.s3
```
{{- if eq .type "s3" }}
s3:
  {{- with .s3 }}
  bucket_name: {{ $bucketName }}
  endpoint: {{ .endpoint }}
  access_key_id: {{ .access_key_id }}
  secret_access_key: {{ .secret_access_key }}
  region: {{ .region }}
  insecure: {{ .insecure }}
  http:
    {{ toYaml .http | nindent 4 }}
  sse:
    {{ toYaml .sse | nindent 4 }}
  {{- end }}
```

**To Reproduce**
helm install loki with values.yaml
```yaml
    storage:
      bucketNames:
        chunks: loki
      use_thanos_objstore: true
      object_store:
        storage_prefix: loki
        type: s3
        s3:
          endpoint: minio:9000
          access_key_id: xxx
          secret_access_key: xxx
          insecure: true
          bucket_lookup_type: path # not work here
```

**Expected behavior**
all s3 settings can be setting in helm chart

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
