### ISSUE TITLE
Loki ingesters startup and immediately enter state=LEAVING

### ISSUE THREAD

**Issue by seanankenbruck** [grafana/loki#17612]
**Describe the bug**
When ingester pods restart, they will sometimes enter a state where the `/ring` page shows them as active, but the logs indicate that they are stuck in a `LEAVING` state. We believe it has something to do with the `unregister-on-shutdown` flag. This flag is false by default, and therefore if an ingester pod gets shutdown unexpectedly (i.e. AKS node drain, configuration rollout, etc.) it does not properly drain or run through the steps for a safe shutdown and therefore there is a mismatch between its state and the recorded state in the ring. 

**To Reproduce**
1. Deploy the Loki helm chart (v6.27.0 or latest 6.29.0) 
2. Configure ingester using the example settings below
3. Once ingester pods are healthy, restart a single replica or rollout a change so the entire zone is restarted
4. Watch the logs at startup to see if ingester rejoins the ring or enters LEAVING state

**Expected behavior**
Ingester pods should be able to rejoin the ring and not get stuck in this state after unexpected restarts. Are there suggestions on additional settings or configuration values to use to ensure this does not happen?

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm with version 6.29.0
 - Configuration:

```yaml
loki:
  loki:
   ingester:
      autoforget_unhealthy: true
      chunk_idle_period: 2h
      concurrent_flushes: 128
      lifecycler:
        ring:
          heartbeat_timeout: 10m
          replication_factor: 3
deploymentMode: Distributed
ingester:
    zoneAwareReplication:
      enabled: true
    updateStrategy:
      type: OnDelete
    persistence:
      enabled: true
      claims:
        - name: data
          size: 1Gi
    replicas: 3
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 15
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 70
      behavior:
        enabled: true
        scaleUp:
          stabilizationWindowSeconds: 120
          policies:
          - type: Pods
            value: 1
            periodSeconds: 60
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
          - type: Pods
            value: 1
            periodSeconds: 180
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: http
        scheme: HTTP
      # Default initialDelaySeconds is 300. We put it to 600 to give the ingester more time to start.
      initialDelaySeconds: 600
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    maxUnavailable: 2
rollout_operator:
    enabled: true
    fullnameOverride: loki-rollout-operator
```

**Screenshots, Promtail config, or terminal output**
```text
level=info ts=2025-05-08T15:49:27.855960903Z caller=module_service.go:82 msg=starting module=ingester                                                                                       level=info ts=2025-05-08T15:49:27.856147769Z caller=ingester.go:766 component=ingester msg="sleeping for initial delay before starting periodic flushing" delay=22.267188435s
level=info ts=2025-05-08T15:49:27.856343563Z caller=lifecycler.go:728 component=ingester msg="existing instance found in ring" state=LEAVING tokens=128 ring=ingester readOnly=false readOnlyStateUpdate=0001-01-01T00:00:00Z                                                                                                                                                         level=info ts=2025-05-08T15:49:27.856559372Z caller=ingester.go:461 component=ingester msg="autoforget is enabled and will remove unhealthy instances from the ring after 10m0s with no heartbeat"                                                                                                                                                                                     level=info ts=2025-05-08T15:49:27.856581314Z caller=loki.go:545 msg="Loki started" startup_time=5.074808063s
level=info ts=2025-05-08T15:49:27.904450534Z caller=memberlist_client.go:588 phase=startup msg="joining memberlist cluster succeeded" reached_nodes=15 elapsed_time=48.80182ms
level=info ts=2025-05-08T15:49:57.85757161Z caller=recalculate_owned_streams.go:49 msg="starting recalculate owned streams job" 
level=info ts=2025-05-08T15:49:57.857610012Z caller=recalculate_owned_streams.go:63 msg="detected ring changes, re-evaluating streams ownership"
level=info ts=2025-05-08T15:49:57.857623561Z caller=recalculate_owned_streams.go:52 msg="completed recalculate owned streams job" 
```

I noticed that by default the value `ingester.unregister-on-shutdown` is set to false on all ingester zones

```yaml
containers:
        - args:
            - -config.file=/etc/loki/config/config.yaml
            - -ingester.availability-zone=zone-a
            - -ingester.unregister-on-shutdown=false
            - -ingester.tokens-file-path=/var/loki/ring-tokens
            - -target=ingester
            - -config.expand-env=true
```

Is it advisable to set enable this value to prevent ingesters from getting stuck in odd states after unexpected shutdowns? In a test, I did notice that the ingester logs no longer showed this entry after modifying the `unregister-on-shutdown` flag.

```text
 level=info ts=2025-05-08T16:27:02.427768923Z caller=loki.go:545 msg="Loki started" startup_time=5.068593892s                                                                                evel=info ts=2025-05-08T16:27:02.428008199Z caller=lifecycler.go:691 component=ingester msg="adding tokens from file" num_tokens=128
level=info ts=2025-05-08T16:27:02.479358602Z caller=memberlist_client.go:588 phase=startup msg="joining memberlist cluster succeeded" reached_nodes=15 elapsed_time=52.665879ms  
level=info ts=2025-05-08T16:27:32.428670288Z caller=recalculate_owned_streams.go:49 msg="starting recalculate owned streams job"  
level=info ts=2025-05-08T16:27:32.42870649Z caller=recalculate_owned_streams.go:63 msg="detected ring changes, re-evaluating streams ownership"  
level=info ts=2025-05-08T16:27:32.428719785Z caller=recalculate_owned_streams.go:52 msg="completed recalculate owned streams job"
```
