### ISSUE TITLE
Template stage does not work with partially filled json log messages 

### ISSUE THREAD

**Issue by nike61** [grafana/loki#1764]
**Describe the bug**
Template stage does not work if log message does not contains all json expressions that json stage contains.

**To Reproduce**
1. Stage yaml file:
```
pipeline_stages:
- match:
    selector: '{container_name="test-app"}'
    stages:
    - json:
        expressions:
          level: Level
          message: RenderedMessage
          username: Username
          http_method: HttpMethod
          http_response_status: HttpResponseStatus
          custom_field_string: CustomFieldString
          custom_field_json: CustomFieldJson
    - template:
        source: level
        template: '{{ Replace .Value "Information" "INFO" 1 }}'
    - labels:
        level:
        message:
    - output:
        source: message
```
2. Send log from inside the container (this message is partially filled because it doesn't contain Username, HttpMethod, HttpResponseStatus, CustomFieldString and CustomFieldJson
```
{
   "Level":"Information",
   "RenderedMessage": "My message"
}
```
3. The Level appears with "Information" value in Loki instead of "INFO"

**Expected behavior**
The level appears with "INFO" value in Loki

**Environment:**
 - I'm using loki docker driver with following daemon.json:
```
{
  "log-driver": "loki",
  "log-opts": {
    "loki-url": "http://192.168.44.203:3100/loki/api/v1/push",
    "loki-pipeline-stage-file": "loki-pipeline-stage.yaml"
  }
}
```

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/841778/75684780-83950a80-5caa-11ea-89ae-380203977305.png)
