### ISSUE TITLE
Broken configuration file when installing via apt on Ubuntu 22.04

### ISSUE THREAD

**Issue by thiagomarafeli** [grafana/loki#17736]
I'm trying to use Loki with Grafana Alloy, but when installing Loki via apt-get, it fails because of a broken configuration file embedded in the installation.

By default, Ubuntu 22.04 ships a 2.4.7.4 version of Loki. I followed the steps for [installing Alloy in Linux](https://grafana.com/docs/alloy/latest/set-up/install/linux/) and then I tried installing Loki following [this tutorial](https://grafana.com/docs/loki/latest/setup/install/local/). After that, I installed the 3.5.0 version, but it automatically fails to start, showing the following error:
```
failed parsing config: /etc/loki/config.yml: yaml: unmarshal errors:
  line 54: field enable_multi_variant_queries not found in type logql.EngineOpts. Use `-config.expand-env=true` flag if you want to expand environment variables in your config file
```

**Describe the bug**
When installing Loki via apt-get, it fails to start because of a broken default config file

**To Reproduce**
1. Add the Grafana GPG keys
```sh
sudo mkdir -p /etc/apt/keyrings/
wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null
echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" | sudo tee /etc/apt/sources.list.d/grafana.list
```
2. Install Loki via apt-get
```sh
sudo apt-get install loki
```

**Expected behavior**
Loki starts successfully

**Environment:**
 - Infrastructure: Ubuntu 22.04, Loki 3.5.0
 - Deployment tool: apt-get, systemd

**Screenshots, Promtail config, or terminal output**
`journalctl -eu loki` output:
![image (2).png](https://github.com/user-attachments/assets/2a14fc9e-7e60-42f3-8adb-cc3d1fd8fa0e)

**Comment by Frank-Krick** [comment]
arch packages extra/loki and aur/loki-bin are broken because of the same error

**Comment by Frank-Krick** [comment]
in case someone finds this later, #16990 describes the solution. But basically move
`enable_multi_variant_queries: true` under the `limits_config` node so that it looks like this
```yaml
limits_config:                                                                                                                
  metric_aggregation_enabled: true                                                                                            
  enable_multi_variant_queries: true    
```
And delete the node the attribute was under before

**Comment by Tervicke** [comment]
Does anyone have a fix , I tried to do as frank suggested but i am still being thrown this error 
```
line 30: field enable_multi_variant_queries not found in type validation.plain. Use `-config.expand-env=true` flag if you want to expand environment variables in your config file
```
I think the config file here [here](https://raw.githubusercontent.com/grafana/loki/main/cmd/loki/loki-local-config.yaml) needs to be updated! , its also refered in the installations docs [here](https://grafana.com/docs/loki/latest/setup/install/local/)

**Comment by hpst3r** [comment]
GrafanaLabs DNF repo package 3.5.1 has the same issue (host is Alma 9) - service does not run after install w/ the default config file. @Frank-Krick's recommendation from #16990 worked fine for me.

```txt
Jun 16 16:03:16 pgl loki[107352]: failed parsing config: /etc/loki/config.yml: yaml: unmarshal errors:
Jun 16 16:03:16 pgl loki[107352]:   line 54: field enable_multi_variant_queries not found in type logql.EngineOpts. Use `-config.expand-env=true` fla>
Jun 16 16:03:16 pgl systemd[1]: loki.service: Main process exited, code=exited, status=1/FAILURE
```

Version:

```txt
loki, version 3.5.1 (branch: release-3.5.x, revision: d4e637ce)
  build user:       root@ceaea196ea87
  build date:       2025-05-19T17:06:03Z
  go version:       go1.24.1
  platform:         linux/amd64
  tags:             netgo
```

Updated limits_config:

```yaml
limits_config:
  metric_aggregation_enabled: true
  enable_multi_variant_queries: true
```
