### ISSUE TITLE
[Helm] Global extraEnvFrom not templating correctly

### ISSUE THREAD

**Issue by npapapietro** [grafana/loki#17748]
**Describe the bug**
There's an issue when populating the `globals.extraEnvFrom` that only the `memcache`, `resultscache` and `write` are correctly templated with the values.

**To Reproduce**
Example values yaml
```yaml
deploymentMode: SimpleScalable
global:
  extraEnvFrom:
    - secretRef:
        name: loki-s3-creds
backend:
  extraEnvFrom:
    - secretRef:
        name: loki-s3-creds
loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2024-04-01"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v13
        store: tsdb
  storage:
    bucketNames:
      admin: bucket
      chunks: bucket
      ruler: bucket
    s3:
      region: us-east-1
    type: s3
```
Running `helm template loki grafana/loki -f values.yaml > loki.yaml` and inspecting the resulting output shows that 
```yaml
envFrom:
  - secretRef:
      name: loki-s3-creds
```
is missing from all sts except `loki-write`, `loki-results-cache`, `loki-chunks-cache`

**Expected behavior**
Expected every statefulset to respect the global values object

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm
