### ISSUE TITLE
Configmap rules don't work when using thanos-objstore with S3

### ISSUE THREAD

**Issue by svenjochems-nsx** [grafana/loki#17812]
**Describe the bug**
It seems not possible to use thanos-objstore as storage_config while using configmap rules (loaded with sidecar) in the ruler.

**To Reproduce**
Helm values:
```yaml
deploymentMode: SimpleScalable

loki:
  storage:
    bucketNames:
      chunks: "${S3_BUCKET_CHUNKS}"
      ruler: "${S3_BUCKET_RULER}"
    use_thanos_objstore: true
    object_store:
      type: "s3"
      s3:
        ...
  storage_config:
    use_thanos_objstore: true
   rulerConfig:
      wal:
        dir: /var/loki/ruler-wal
      storage:
        # Set this to local, configMap rules do not seem to work with S3 storage https://github.com/grafana/loki/issues/12967#issuecomment-2614050185
        type: local
        local:
          directory: /rules
      enable_api: true
      enable_alertmanager_v2: true
      alertmanager_url: ...
      rule_path: /rules
      ring:
        kvstore:
          store: memberlist
  sidecar:
    rules:
      enabled: true
      label: loki_rule
      labelValue: "true"
      folder: /rules/fake
```

This results in the following generated config:
```yaml
    ruler:
      alertmanager_url: ...
      enable_alertmanager_v2: true
      enable_api: true
      ring:
        kvstore:
          store: memberlist
      rule_path: /rules
      storage:
        local:
          directory: /rules
        type: local
      wal:
        dir: /var/loki/ruler-wal
    ruler_storage:
      backend: s3
      s3:
        access_key_id: ${S3_ACCESS_KEY_ID}
        bucket_name: ${S3_BUCKET_RULER}
        endpoint: ${S3_ENDPOINT}
        http: {}
        insecure: false
        region: ${S3_REGION}
        secret_access_key: ${S3_SECRET_ACCESS_KEY}
        sse: {}
      storage_prefix: null
```

`ruler.storage` is correctly set to local, what I need for configMap rules. `ruler_storage` is set to S3. The ruler does not pick up any rules placed in the configMap.

Related issues:
[Local storage is required for configMap rules](https://github.com/grafana/loki/issues/12967#issuecomment-2614050185)
https://github.com/grafana/loki/issues/16543

**Expected behavior**
* Should there be a way to configure logs to S3 with thanos-objstore but rules with configMaps?
* Why are both `ruler.storage` and `ruler_storage` generated in the config. `ruler.storage` seems to be deprecated.

**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: [helm]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by cheeseball212** [comment]
Running into the same issue.

**Comment by dragoangel** [comment]
same issue, also to note: when user defined local storage `Error: execution error at (loki/charts/loki/templates/write/statefulset-write.yaml:50:28): Please define loki.storage.bucketNames.ruler` should not fire: it can be safely `null`

**Comment by dragoangel** [comment]
Temp workaround:
```yaml
loki:
  structuredConfig:
    ruler:
      storage:
        type: local
        local:
          directory: /var/loki/rules
      rule_path: /var/loki/rules-temp
    ruler_storage:
      backend: local
      local:
        directory: /var/loki/rules
      s3: null
      gcs: null
      azure: null
```
