### ISSUE TITLE
Parsing Logs to create metric for prometheus

### ISSUE THREAD

**Issue by NajemAyadi** [grafana/loki#1782]
i installed prometheus-operator and promtail using the helm chart. I'm trying to parse my logs in order to create metrics for prometheus, so i can create alerts in Grafana with Prometheus as Datasource. For that i created this configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: netcoreapp
  namespace: monitoring
  labels:
    app: netcoreapp    
data:
  promtail.yaml: |    
    scrape_configs:       
    - job_name: netcoreapp-logs            
      pipeline_stages:
      - match:      
          selector: '{job="monitoring/netcoreapp"}'
          stages:
          - regex:
              expression: ".*(?P<test>test.*)"
          - labels:
              test:              
          - metrics:
              error_total:
                type: Counter
                description: "total count of errors"
                source: error_message
                config:
                  action: inc
```
My custom app i logging always:
```
_logger.LogError("Test Error Log");
```
I'm actually expecting that promtail recognize the term "Test Error Log" in the logs and increase the counter metric "total count of error", but i can't see this metrics in Prometheus.
Did i missed something, it would be greate if someone could give me some hints.
Thanks.
