### ISSUE TITLE
Helm: gateway /config doesn't work with zone aware ingesters

### ISSUE THREAD

**Issue by JohanLindvall** [grafana/loki#17969]
**Describe the bug**
If you deploy Loki using Helm and zone-aware ingesters, the /config endpoint in the gateway doesn't work, as it points to a non-existing service (loki-ingester)

**To Reproduce**
1. Install Loki using Helm, deploymentMode: SimpleScalable, zone aware replication enabled
2. curl -v http://loki-gateway/config
3. A 502 is returned

**Expected behavior**
The config endpoint should work

**Environment:**
AKS 1.31.8
Deployed with the loki helm chart, version 6.30.0

A workaround is to create the missing service yourself
```
apiVersion: v1
kind: Service
metadata:
  name: loki-ingester
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: ingester
    app.kubernetes.io/name: loki
```

The issue are these lines here:
https://github.com/grafana/loki/blob/620696c4a85e0c56a3dd561ff96b0ca1b9aa7220/production/helm/loki/templates/_helpers.tpl#L971

I suppose the file should be parameterized for zone aware ingestions?
