### ISSUE TITLE
Promtail doesn't create metric

### ISSUE THREAD

**Issue by aronneagu** [grafana/loki#1805]
**Describe the bug**
Configured promtail to generate metrics, but metrics doesn't appear on /metrics endpoint of 
promtail. Configuration was taken from the promtail example:  https://github.com/grafana/loki/blob/master/docs/clients/promtail/stages/metrics.md 

**To Reproduce**
1. Installed promtail helm chart `helm install promtail loki/promtail --values values.yam` with the following values.yaml, using chart version promtail-0.19.2
```
loki:
  serviceName: loki

pipelineStages:
- metrics:
    log_lines_total:
      type: Counter
      description: "total number of log lines"
      prefix: my_promtail_custom_
      source: time
      config:
        action: inc
```
2. Checked port forwarded promtail pod to localhost and checked http://promtail:3101/metrics

**Expected behavior**
Expected to see a metric named `my_promtail_custom_log_lines_total`

**Environment:**
 - Infrastructure: Kubernetes v 1.16 on Azure AKS
- Deployment: Helm v3

**Screenshots, Promtail config, or terminal output**
/etc/promtail/promtail.yaml (inside the pod)
```
- job_name: kubernetes-pods-static
  pipeline_stages:
    - metrics:
        log_lines_total:
          config:
            action: inc
          description: total number of log lines
          prefix: my_promtail_custom_
          source: time
          type: Counter
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: drop
    regex: ''
```

Promtail logs do not show any errors nor info regarding that particular metric

**Comment by adityacs** [comment]
@aronneagu Could you please try replacing `source: time` to `source: timestamp` ?

**Comment by aronneagu** [comment]
I have checked with timestamp, but it didn't work. From your comment, I understand that the source comes if the log format is from docker. However my log is unstructured, is there a way to count all log lines without extracting any field from it?

**Comment by cyriltovena** [comment]
@slim-bean don't we have that metric already ?

**Comment by adityacs** [comment]
@cyriltovena We have it. I guess it's `promtail_sent_entries_total`
@aronneagu You can check for this in `/metrics`

**Comment by aronneagu** [comment]
I have checked that metric and id does give the total entries sent, though I was looking for a something that allows me to be more granular, maybe matching with labels from loki.
I will keep tweaking with promtail to generate a metric from the log lines, and post back

**Comment by cyriltovena** [comment]
@aronneagu 

We use this stage internally.

```
- metrics:
            line_count_total:
                config:
                    action: inc
                    match_all: true
                description: A running counter of all lines with their corresponding
                    labels
                type: Counter
```

I think that should work for you, but you might need to use master. I don't think it's part of 1.3.
