### ISSUE TITLE
Loki ingester stays in LEAVING state after node reboot

### ISSUE THREAD

**Issue by gorilych** [grafana/loki#1806]
**Describe the bug**

After/during node reboot (preemptible node in GKE, reboot time is limited to ~30 seconds), ingester pod goes into LEAVING state forever, until the pod is deleted manually.

![image](https://user-images.githubusercontent.com/7404372/76695143-068b6d00-667c-11ea-84df-a36e87425352.png)

**To Reproduce**

Deploy with helm on preempt nodes. Every time node is preempted, one of the ingesters goes to LEAVING and keeps running in this state (/ready return Ready, so pod is marked as healthy and ready).

**Expected behavior**

Ingester should either heal itself or exit after unclean restart and finding previous state LEAVING

**Environment:**
 - Infrastructure: GKE, preempt nodes n1-standard-2
 - Deployment tool: helm

Deployment is done from [loki helm chart](https://github.com/grafana/loki/tree/master/production/helm/loki) 0.25.1

Loki version string: version=v1.3.0, branch=HEAD, revision=5e527a03

Helm values file:

```
loki:
  extraArgs:
    log.level: debug
  serviceMonitor:
    enabled: true
    interval: 10s
    scrapeTimeout: 5s
  config:
    schema_config:
      configs:
      - from: "2019-07-01"
        store: cassandra
        object_store: cassandra
        schema: v10
        index:
          prefix: index
          period: 360h
        chunks:
          prefix: chunk
          period: 360h
    storage_config:
      cassandra:
        username: cassandra
        password: cassandra
        addresses: cassandra
        auth: true
        keyspace: loki
    ingester:
      lifecycler:
        ring:
          replication_factor: 2
          kvstore:
            store: etcd
            etcd:
              endpoints:
              - etcd:2379
  nameOverride: loki
  fullnameOverride: loki
  replicas: 5
  resources:
    limits:
      cpu: 500m
      #memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  persistence:
    enabled: true
    size: 10Gi
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: cloud.google.com/gke-preemptible
            operator: Exists
        weight: 100
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: loki
        topologyKey: "kubernetes.io/hostname"
```

Promtail(daemonset)/cassandra(sts)/etcd(sts) are deployed separately to the same preempt nodes and experience no issues, except promtail not able to push logs to Loki after 3/5 of them go to LEAVING. 

**Screenshots, Promtail config, or terminal output**

Discussion in slack: https://grafana.slack.com/archives/CEPJRLQNL/p1584242451454400

Logs for starting Loki instance after node reboot:

```
level=info ts=2020-03-15T02:20:21.386901677Z caller=loki.go:149 msg=initialising module=server
level=info ts=2020-03-15T02:20:21.387793334Z caller=server.go:121 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2020-03-15T02:20:21.388305543Z caller=loki.go:149 msg=initialising module=overrides
level=info ts=2020-03-15T02:20:21.388499931Z caller=override.go:53 msg="per-tenant overrides disabled"
level=info ts=2020-03-15T02:20:21.388729433Z caller=loki.go:149 msg=initialising module=table-manager
level=info ts=2020-03-15T02:20:21.636389303Z caller=loki.go:149 msg=initialising module=store
level=info ts=2020-03-15T02:20:21.639229202Z caller=table_manager.go:220 msg="synching tables" expected_tables=36
...
level=info ts=2020-03-15T02:20:22.067044325Z caller=loki.go:149 msg=initialising module=ring
level=info ts=2020-03-15T02:20:22.067743921Z caller=loki.go:149 msg=initialising module=querier
level=debug ts=2020-03-15T02:20:22.067846777Z caller=modules.go:166 msg="initializing querier worker" config="{Address: Parallelism:10 DNSLookupDuration:10s GRPCClientConfig:{MaxRecvMsgSize:104857600 MaxSendMsgSize:16777216 UseGzipCompression:false RateLimit:0 RateLimitBurst:0 BackoffOnRatelimits:false BackoffConfig:{MinBackoff:100ms MaxBackoff:10s MaxRetries:10}}}"
level=info ts=2020-03-15T02:20:22.067909526Z caller=worker.go:72 msg="no address specified, not starting worker"
level=info ts=2020-03-15T02:20:22.086818825Z caller=loki.go:149 msg=initialising module=ingester
level=info ts=2020-03-15T02:20:22.087478269Z caller=loki.go:149 msg=initialising module=distributor
level=info ts=2020-03-15T02:20:22.087612976Z caller=loki.go:149 msg=initialising module=all
level=info ts=2020-03-15T02:20:22.087631552Z caller=main.go:70 msg="Starting Loki" version="(version=v1.3.0, branch=HEAD, revision=5e527a03)"
level=info ts=2020-03-15T02:20:22.089785918Z caller=lifecycler.go:471 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2020-03-15T02:20:22.100261899Z caller=lifecycler.go:505 msg="existing entry found in ring" state=LEAVING tokens=128 ring=ingester
level=debug ts=2020-03-15T02:20:22.100369162Z caller=lifecycler.go:359 msg="JoinAfter expired" ring=ingester
level=debug ts=2020-03-15T02:20:26.168712738Z caller=logging.go:44 traceID=17132fd9b604a73b msg="GET /metrics (200) 27.310659ms"
level=debug ts=2020-03-15T02:20:32.345468852Z caller=logging.go:44 traceID=74f88119023ce136 msg="GET /metrics (200) 9.792214ms"
```

Problem might come from cortex not having a path out from LEAVING state on startup: https://github.com/cortexproject/cortex/blob/3374e33bde0e805f9955fc8ba4caf0a4b96e04ca/pkg/ring/lifecycler.go#L363
