### ISSUE TITLE
Promtail should run as non-root in docker

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#1813]
companion of https://github.com/grafana/loki/pull/1706

**Comment by slim-bean** [comment]
Adding a note: It's possible to do this with SecurityContext and and a non-root container. 

Closing this as it's maybe something we will tackle someday but there are a lot of hurdles.

**Comment by ramran-r** [comment]
Hi ,  Have installed Promtail by keeping non-root user in SecurityContext however it is failing to send the logs . Getting permission denied to access /var/log/pods of all containers. Are there any config changes required to run promtail with non-root? 
Promtail version is  2.0.0

securityContext:
  readOnlyRootFilesystem: true
  runAsGroup: 10001
  runAsUser: 10001
 


level=error ts=2020-11-20T05:26:19.240235373Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/csf-logs_loki-0_e29e5c9b-2f18-456d-a60a-c18035aac63a/loki/0.log: permission denied" filename=/var/log/pods/csf-logs_loki-0_e29e5c9b-2f18-456d-a60a-c18035aac63a/loki/0.log

level=error ts=2020-11-20T07:10:19.267861388Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/csf-logs_promtail-79kc8_4f2bb4fb-3928-49e4-ae8c-6e50ec577193/istio-proxy/0.log: permission denied" filename=/var/log/pods/csf-logs_promtail-79kc8_4f2bb4fb-3928-49e4-ae8c-6e50ec577193/istio-proxy/0.log
level=error ts=2020-11-20T07:10:19.275335851Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/csf-logs_grafana-0_743d071f-b0f5-4f76-a937-c5ab0fac8322/istio-init/0.log: permission denied" filename=/var/log/pods/csf-logs_grafana-0_743d071f-b0f5-4f76-a937-c5ab0fac8322/istio-init/0.log
level=error ts=2020-11-20T07:10:19.275354059Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/csf-monitoring_prometheus-prometheus-prometheus-0_5c7e5dfa-1893-4a86-b33f-279e1d79783d/prometheus/0.log: permission denied" filename=/var/log/pods/csf-monitoring_prometheus-prometheus-prometheus-0_5c7e5dfa-1893-4a86-b33f-279e1d79783d/prometheus/0.log
level=error ts=2020-11-20T07:10:19.275400892Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/csf-monitoring_prometheus-prometheus-prometheus-0_5c7e5dfa-1893-4a86-b33f-279e1d79783d/prometheus/1.log: permission denied" filename=/var/log/pods/csf-monitoring_prometheus-prometheus-prometheus-0_5c7e5dfa-1893-4a86-b33f-279e1d79783d/prometheus/1.log
level=error ts=2020-11-20T07:10:19.283893529Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/csf-monitoring_prometheus-prometheus-prometheus-0_5c7e5dfa-1893-4a86-b33f-279e1d79783d/config-reloader/0.log: permission denied" filename=/var/log/pods/csf-monitoring_prometheus-prometheus-prometheus-0_5c7e5dfa-1893-4a86-b33f-279e1d79783d/config-reloader/0.log
level=error ts=2020-11-20T07:10:19.285443379Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/csf-monitoring_alertmanager-prometheus-alertmanager-0_1000ee05-18da-4b51-9704-6bc5d1095964/alertmanager/0.log: permission denied" filename=/var/log/pods/csf-monitoring_alertmanager-prometheus-alertmanager-0_1000ee05-18da-4b51-9704-6bc5d1095964/alertmanager/0.log
level=error ts=2020-11-20T07:10:19.285725688Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/csf-monitoring_alertmanager-prometheus-alertmanager-0_1000ee05-18da-4b51-9704-6bc5d1095964/config-reloader/0.log: permission denied" filename=/var/log/pods/csf-monitoring_alertmanager-prometheus-alertmanager-0_1000ee05-18da-4b51-9704-6bc5d1095964/config-reloader/0.log
level=error ts=2020-11-20T07:10:19.288221819Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/csf-logs_grafana-0_743d071f-b0f5-4f76-a937-c5ab0fac8322/istio-proxy/0.log: permission denied" filename=/var/log/pods/csf-logs_grafana-0_743d071f-b0f5-4f76-a937-c5ab0fac8322/istio-proxy/0.log
level=error ts=2020-11-20T07:10:19.288491709Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/kube-system_local-path-provisioner-7ff9579c6-s2hc2_7c78b2e0-38af-49bd-9723-ef2a0e1bea66/local-path-provisioner/0.log: permission denied" filename=/var/log/pods/kube-system_local-path-provisioner-7ff9579c6-s2hc2_7c78b2e0-38af-49bd-9723-ef2a0e1bea66/local-path-provisioner/0.log
level=error ts=2020-11-20T07:10:19.288722122Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/csf-logs_grafana-0_743d071f-b0f5-4f76-a937-c5ab0fac8322/grafana/0.log: permission denied" filename=/var/log/pods/csf-logs_grafana-0_743d071f-b0f5-4f76-a937-c5ab0fac8322/grafana/0.log
level=error ts=2020-11-20T07:10:19.288961164Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/kube-system_metrics-server-7b4f8b595-8cd2g_e2759e88-1df2-4b76-a1dd-a40605a54b06/metrics-server/0.log: permission denied" filename=/var/log/pods/kube-system_metrics-server-7b4f8b595-8cd2g_e2759e88-1df2-4b76-a1dd-a40605a54b06/metrics-server/0.log
level=error ts=2020-11-20T07:10:19.290365062Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/kube-system_coredns-66c464876b-9tq9n_46665b31-aa57-4f87-959a-76822f560175/coredns/0.log: permission denied" filename=/var/log/pods/kube-system_coredns-66c464876b-9tq9n_46665b31-aa57-4f87-959a-76822f560175/coredns/0.log
level=error ts=2020-11-20T07:10:19.292883439Z caller=filetarget.go:305 msg="failed to start tailer" error="open /var/log/pods/csf-monitoring_prometheus-kube-state-metrics-58889c5887-wbvtn_cdc98dbd-c230-4f8d-a6a6-48bb9a2b945c/kube-state-metrics/0.log: permission denied" filename=/var/log/pods/csf-monitoring_prometheus-kube-state-metrics-58889c5887-wbvtn_cdc98dbd-c230-4f8d-a6a6-48bb9a2b945c/kube-state-metrics/0.log

**Comment by Jeroen0494** [comment]
Little bit of a necro post, but for those searching the web and finding themselved here the following works:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: 2.7.3
    helm.sh/chart: promtail-6.8.3
  name: promtail
  namespace: monitoring
spec:

  selector:
    matchLabels:
      app.kubernetes.io/instance: promtail
      app.kubernetes.io/name: promtail
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: promtail
        app.kubernetes.io/name: promtail
    spec:
      containers:
      - args:
        - -config.file=/etc/promtail/promtail.yaml
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: docker.io/grafana/promtail:2.7.3
        [...]
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 0
          runAsNonRoot: true
          runAsUser: 10000
       [...]
      securityContext:
        runAsGroup: 0
        runAsUser: 10000
```

Al long as the group is 0, it can read all of the pod logs.

**Comment by motizukilucas** [comment]
I see that we can run it on kubernetes

The issue was closed considering other priorities, but I can't tell if this has been already

Right now, I can run it in a non privileged way, by setting the user as non-root and grabbing container logs with read-only permissions on docker log folder

But some features, such as associating container ID with respective name, appears to only be possible with access over docker.sock

**Comment by Jeroen0494** [comment]
> Running it as @Jeroen0494 mentioned allows to read logs, but the mounted file system are unhappy about the positions file:
> 
> ```
> level=error ts=2023-06-05T14:22:18.319745338Z caller=positions.go:179 msg="error writing positions file" error="open /run/promtail/.positions.yaml1075722675773395379: permission denied"
> level=error ts=2023-06-05T14:22:28.320167635Z caller=positions.go:179 msg="error writing positions file" error="open /run/promtail/.positions.yaml4936121625251010712: permission denied"
> level=error ts=2023-06-05T14:22:38.323569417Z caller=positions.go:179 msg="error writing positions file" error="open /run/promtail/.positions.yaml5760747310671543038: permission denied"
> ```
> 
> That is because `/run/promtail/` is still `root:root` disappointed

I see, I'm guessing the permission on the created files don't allow group writes. You could try mounting with the fsGroup option set in the pod securityContext:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#podsecuritycontext-v1-core

You will need to manually change the owner and permissions on disk when files already exist.

**Comment by Demonsthere** [comment]
The secContext i was trying to run that with is:
```yaml
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 0
    runAsNonRoot: true
    runAsUser: 1001
    seccompProfile:
      type: RuntimeDefault
  # image:
  #   repository: bitnami/promtail
  podSecurityContext:
    runAsGroup: 0
    runAsUser: 1001
```
As the `/run` path is a volume i doubt that `readOnlyRootFilesystem` is the issue here, as you mentioned looks like the guid is used for read but not for write here?

**Comment by Jeroen0494** [comment]
The files seem to be created by other pods without write permissions for the group, not much you can do about this from promtail I'm afraid.

**Comment by yanehi** [comment]
I have set the permissions on PodLevel as follows, but I always get the same error message as in [Jeroen0494](https://github.com/grafana/loki/issues/1813#issuecomment-1576958672) as soon as I set the runAsUser value to 0:

```
podSecurityContext:
  runAsUser: 0
  runAsGroup: 1000
  fsGroup: 1000
```

The permissions cannot be adjusted retroactively either:

```

chown: changing ownership of 'promtail/positions.yaml': Operation not permitted
chown: changing ownership of 'promtail': Operation not permitted 
```
