### ISSUE TITLE
how to configure storage options when deploying using helm

### ISSUE THREAD

**Issue by nbari** [grafana/loki#1818]
How could I deploy `loki` into a Kubernetes cluster using `helm` but defining a custom storage from https://github.com/grafana/loki/tree/master/docs/configuration#storage_config, for example for testing purposes I would like to use `gcs`

thanks in advance.

**Comment by SamGallagher95** [comment]
I would like to know how to do this as well, I am struggling to find a solution for this.

Loki pod is loading the `loki-stack` secret which contains the configuration data, but I don't know how to set that in the configuration values for this chart.

**Comment by bilal922** [comment]
Correct

**Comment by cyriltovena** [comment]
Hello @nbari and @SamGallagher95,

To provide a storage option (https://github.com/grafana/loki/tree/master/docs/configuration#storage_config) you can use a value file with helm.

For example here is a `values.yaml` for `gcs/bigtable` example:

```yaml
config:
  schema_config:
    configs:
    - from: 2018-04-15
      store: bigtable
      object_store: gcs
      schema: v9
      index:
        prefix: index_
        period: 168h
  storage_config:
    bigtable:
        instance: <instance_name>
        project: <project_name>
    gcs:
        bucket_name: <bucket_name>
  table_manager:
    retention_deletes_enabled: false
    retention_period: 672h
```

Then you can install using `helm install -f values.yaml loki/loki`.
