### ISSUE TITLE
Can't add loki datasource using docker (Loki: Bad Gateway. 502)

### ISSUE THREAD

**Issue by max-block** [grafana/loki#1826]
I'm trying to start loki with docker like it described here: https://github.com/grafana/loki/tree/master/production#run-locally-using-docker

Grafana successfully starts on http://localhost:3000/

But after adding the Loki datasource (using http://loki:3100 for the URL field), there is such an error in UI:
Loki: Bad Gateway. 502

There is an error log in docker-compose logs:
```
grafana_1   | t=2020-03-19T16:39:14+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/loki/api/v1/label remote_addr=172.27.0.1 referer=http://localhost:3000/datasources/edit/1/?gettingstarted error="http: proxy error: dial tcp 172.27.0.4:3100: connect: connection refused"
```

My envs:
os: macOS 10.15.3
docker: 19.03.8
docker-compose: 1.25.4

**Comment by aaronkjones** [comment]
@max-block 
Try using `grafana/loki:master-89263b0` (from 8 days ago). There appears to be a problem with the latest build.

**Comment by max-block** [comment]
Yes, now it works with `grafana/loki:master-89263b0`

**Comment by shanisma** [comment]
Same issue, worked for me , docker + macos

**Comment by cyriltovena** [comment]
Yes we changed the port for couple of days without updating docker-compose. Now everything is back to normal.

Thanks for reporting.

**Comment by shkmaaz11** [comment]
I am facing this issue.

**Comment by shkmaaz11** [comment]
> Yes we changed the port for couple of days without updating docker-compose. Now everything is back to normal.
> 
> Thanks for reporting.

This issue is still reproducible for me.

**Comment by cyriltovena** [comment]
You need to give more details, if you using latest you're most likely having docker network issues or you haven't pull the latest images ?

**Comment by Bingmang** [comment]
Facing this issue too...

docker-compose:
```
  loki:
    container_name: loki
    image: grafana/loki:2.5.0
    ports:
      - 3101:3100
    networks:
      - vm
    volumes:
      - loki_data:/loki

  grafana:
    container_name: grafana
    image: grafana/grafana:8.5.2
    ports:
      - 3000:3000
    networks:
      - vm
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-}
```

Adding the Loki datasource (using http://loki:3100/ for the URL field), there is such an error in UI:
Loki: Bad Gateway. 502

But when I use `http://192.168.xxx.xxx:3100` instead of the `http://loki:3100`, it works.
