### ISSUE TITLE
Loki can not find logs before the moment when Pod Updated.

### ISSUE THREAD

**Issue by kidrocknroll** [grafana/loki#1827]
**Describe the bug**
Loki can not find logs before the moment when loki-stack-0 pod recreated and index dir is removed by os.Remove().

**To Reproduce**
1. Start Loki StatefulSet using Kubernetes, mount /data dir and loki.yaml config file to the container. 
2. Change「table_manager.Kubernetes/retention_deletes_enabled」or 「schema_config.config.index」configuration of loki.yaml and update the pod to apply with the new configMap.
3. Query the log before the moment when loki-stack-0 pod created.

**Expected behavior**
I expect that I can still find the old logs before, but nothing showed for the API.

I assume that is because of TearDown function defined within github.com/cortexproject/cortex/pkg/chunk/local/fixtures.go, It has removed all indexes before in the index dir so that I can not find any logs before on grafana. 

I am not sure whether there is any misunderstanding of the config option max_look_back_period by myself. And I assume that there is a way to find old logs since the data chunks are actually not been deleted or maybe rebuild the index?

Sorry, I am not familiar with Boltdb, But this is the only infrastructure I got to store the indexes.

**Environment:**
 - Kubernetes v1.12.4
 - Loki v1.3.0
 - Deployment tool: Kubectl
 - Boltdb is the storage for indexes. And s3 API compatible cos is the storage of chunks. 

**Screenshots, Promtail config, or terminal output**

loki.yaml configuration
```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 2160h
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 15m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 720h
  max_streams_matchers_per_query: 2000
schema_config:
  configs:
  - from: "2018-04-15"
    index:
      period: 24h
      prefix: index_
    object_store: s3
    schema: v9
    store: boltdb
server:
  http_listen_port: 3100
storage_config:
  boltdb:
    directory: /data/loki/index
  aws:
    s3: s3://XXXXXXXXX
    s3forcepathstyle: true
table_manager:
  retention_deletes_enabled: true
  retention_period: 2160h
```

![image](https://user-images.githubusercontent.com/22533109/77143295-d3067380-6abd-11ea-88d1-08af66e33911.png)

![image](https://user-images.githubusercontent.com/22533109/77143582-9a1ace80-6abe-11ea-9e42-37b566287e11.png)

**Comment by cyriltovena** [comment]
In helm by default the persistence is off.

```
## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
## If you set enabled as "True", you need :
## - create a pv which above 10Gi and has same namespace with loki
## - keep storageClassName same with below setting
persistence:
  enabled: false
  accessModes:
  - ReadWriteOnce
  size: 10Gi
  annotations: {}
  # subPath: ""
  # existingClaim:
```

Did you activated it ? If you don't then the whole filesystem for the pod is recreated.
