### ISSUE TITLE
Loki returns empty result set on querying

### ISSUE THREAD

**Issue by stvnwrgs** [grafana/loki#1828]
**Describe the bug**
Loki gives back flaky data when querying. When I start Loki on our Kubernetes cluster and want to retrieve the data, sometimes I get an empty result back. It seems to get worse over time. The first minutes with a fresh cluster, I get data, after a few minutes, the chance to retrieve data becomes smaller and smaller.

**To Reproduce**
1. Started Loki 1.3.0
2. Started Promtail 1.3.0
3. Query via Grafana: `count_over_time({stream="stdout"}[5m])` or `{app="loki"}` or get labels query
4. A few moments after I start, I get data. After querying multiple times, I get an empty result set for data and labels.
5. This happens for querries on Loki directly (3100) as well as my sidecar (3101).  

**Expected behavior**
I would expect to get a non-empty result set.

**Environment:**
 - Infrastructure: kubernetes inside kvm
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
I started with a multi tenant setup and thought this would be the problem, but even after disabling auth, I still, see the same issue.

Loki values:

```
image:
  tag: v1.3.0

replicas: 3

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - loki
        topologyKey: "kubernetes.io/hostname"

podDisruptionBudget:
  minAvailable: 2

serviceMonitor:
  enabled: true

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 300m
    memory: 256Mi

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 50Gi

rbac:
  create: false
  pspEnabled: false

roles:
  roles:
    - name: psp-logging-store-v1
      type: ClusterRole

serviceAccount:
  create: false
  name: logging-store-roles

config:
  auth_enabled: false
  ingester:
    chunk_idle_period: 3m
    chunk_block_size: 262144
    chunk_retain_period: 1m
    max_transfer_retries: 0
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 720h
  schema_config:
    configs:
      - from: 2018-04-15
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
  server:
    http_listen_port: 3100
  storage_config:
    boltdb:
      directory: /data/loki/index
    filesystem:
      directory: /data/loki/chunks
  chunk_store_config:
    max_look_back_period: 1h
  table_manager:
    retention_deletes_enabled: false
    retention_period: 0

extraArgs:
  log.level: debug

extraContainers:
  ## Additional containers to be added to the loki pod.
  - name: loki-multi-tenant-proxy
    image: angelbarrera92/loki-multi-tenant-proxy:dev
    args:
      - "run"
      - "--port=3101"
      - "--loki-server=http://localhost:3100"
      - "--auth-config=/etc/loki-multi-tenant-proxy/authn.yaml"
    ports:
      - name: http
        containerPort: 3101
        protocol: TCP
    volumeMounts:
      - name: loki-multi-tenant-proxy-auth-config
        mountPath: /etc/loki-multi-tenant-proxy

extraVolumes:
  # Additional volumes to the loki pod.
  - name: loki-multi-tenant-proxy-auth-config
    secret:
      secretName: loki-multi-tenant-proxy-auth-config

extraPorts:
  # Additional ports to the loki services. Useful to expose extra container ports.
  - port: 3101
    protocol: TCP
    name: http
    targetPort: http
```

Promtail Config:
```

image:
  tag: v1.3.0

livenessProbe: {}

loki:
  serviceName: "logging-store-loki" # Defaults to "${RELEASE}-loki" if not set
  servicePort: 3100
  serviceScheme: http
  # user: user
  # password: pass

pipelineStages:
  - docker: {}
  # default tenant for all unmatched logs
  # - tenant:
  #     value: unmatched

  # # add all metrics from kube-system to the kube-system tenant
  # - match:
  #     selector: '{namespace="kube-system"}'
  #     stages:
  #       - tenant:
  #           value: "kube-system"
  # # int metrics to int tenant
  # - match:
  #     selector: '{__meta_kubernetes_pod_label_env="int"}'
  #     stages:
  #       - tenant:
  #           value: "int"
  # - match:
  #     selector: '{env="int"}'
  #     stages:
  #       - tenant:
  #           value: "int"
  # # dev metrics to dev tenant
  # - match:
  #     selector: '{__meta_kubernetes_pod_label_env="dev"}'
  #     stages:
  #       - tenant:
  #           value: "dev"
  # - match:
  #     selector: '{env="dev"}'
  #     stages:
  #       - tenant:
  #           value: "dev"
  # #access logs to access-logs tenant
  # - match:
  #     selector: '{container_name=~"ngninx|kong"} |~"(POST|GET|DELETE|OPTIONS|CONNECT|PATCH) (.*) (.*) ([0-9]+)"'
  #     stages:
  #       - tenant:
  #           value: "access-logs"
  # drop all log messages for /metrics /healthz and /readyz
  - match:
      selector: '{stream="stdout"} |~"(/metrics|/healthz|/readyz|/health|/ready)"'
      action: drop
  - output:
      source: message
scrapeConfigs: []

# Custom scrape_configs together with the default ones in the configmap
extraScrapeConfigs: []

podLabels: {}

rbac:
  create: false
  pspEnabled: false

roles:
  roles:
    - name: psp-logging-forwarder-v1
      type: ClusterRole

serviceAccount:
  create: false
  name: logging-forwarder-roles

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceMonitor:
  enabled: true
```

Loki log output:
https://gist.github.com/stvnwrgs/30e5b5ceaaed4f09210328bda5da7a26
