### ISSUE TITLE
Bug retention 24 hours

### ISSUE THREAD

**Issue by Hugo-janasik** [grafana/loki#18283]
I am currently running into an issue.
I would like to setup the 24 hours retention for loki.

Here is my current configuration:

```
auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  retention_enabled: true
  compaction_interval: 10m
  delete_request_store: filesystem
  shared_store: filesystem
  retention_delete_delay: 30m
  retention_delete_worker_count: 150

limits_config:
  retention_period: 24h
  allow_structured_metadata: false
  reject_old_samples: false
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 24h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
```

When I setup it into my grafana, I can still see the logs past 24 hours, seems like the retention does not work.

Do you have any idea how I can patch it ?
