### ISSUE TITLE
Can't add Syslog Receiver

### ISSUE THREAD

**Issue by tanora** [grafana/loki#1847]
I get the following error when trying to add  the Syslog Receiver.

`level=warn ts=2020-03-25T09:49:37.652388846Z caller=syslogtarget.go:164 msg="error initializing syslog stream" err="invalid or unsupported framing. first byte: 'G'"`

Helm chart config  
```yaml
extraScrapeConfigs:
- job_name: syslog
  syslog:
    listen_address: 0.0.0.0:1514
    labels:
      job: "syslog"
  relabel_configs:
  - source_labels: ['__syslog_message_hostname']
    target_label: 'host'
```
```yaml
syslogService:
  enabled: true
  type: ClusterIP
  port: 1514
```

I have tried running Netcat to create a syslog message with the following command, however no logs are sent to Loki. 

`echo '<14>sourcehost message text'| nc -v -u -w 1 promtail-syslog.default 1514`
Any help would be greatly appreciated.
