### ISSUE TITLE
Index/chunks retention for old schemas config

### ISSUE THREAD

**Issue by ncauchois** [grafana/loki#1859]
**Describe the issue**

When we add a new schema config, the retention of the tables associated with this new config scheme is correct. On the other hand it's not applied for the old schemas config. Tables associated with old schemas config are not deleted.

We can even see that when we increase the retention, the number of tables increases for the new schema config, but also for the old ones.

**Loki config**
```
   - from: "2020-03-06"
      index:
        period: 24h
        prefix: loki_index_from_20200306
      object_store: aws
      schema: v9
      store: cassandra
    - from: "2020-03-07"
      index:
        period: 24h
        prefix: loki_index_from_20200307
      object_store: aws
      schema: v9
      store: cassandra
    - from: "2020-03-24"
      index:
        period: 24h
        prefix: loki_index_from_20200324
      object_store: aws
      schema: v11
      store: cassandra

  retention_period:48h
```

**Environment:**
kubernetes : 1.13
loki : 1.3.0
