### ISSUE TITLE
grafana loki explore An unexpected error happened on filter expressions

### ISSUE THREAD

**Issue by moeinrahimi** [grafana/loki#1874]
go to grafana explore
datasource : loki
start typing {module:server} |= "hi"

**Environment:**
 - Deployment tool: ubuntu docker 

![image](https://user-images.githubusercontent.com/13715024/78042084-cd930e00-7386-11ea-969b-b756b188b46e.png)
my docker-compose
```
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - E:\docker-shared-stuff\log\promtailLog:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - loki
```
