### ISSUE TITLE
Loki clustered deployment configuration

### ISSUE THREAD

**Issue by yang3808282** [grafana/loki#1876]
I have three computer:such as 
**10.157.10.100,
10.157.10.101, 
10.157.10.102,**
Now,I have completed the clustered deployment of consul，The configuration information is as follows:
10.157.10.100(server with web ui)
```
{
    "datacenter":"dc1",
    "primary_datacenter":"dc1",
    "bootstrap_expect":3,
    "start_join":[
        "10.157.10.101",
        "10.157.10.102"
    ],
    "retry_join":[
        "10.157.10.101",
        "10.157.10.102"
    ],
    "advertise_addr": "10.157.10.100",
    "bind_addr": "10.157.10.100",
    "server":true,
    "connect":{
        "enabled":true
    },
    "node_name":"consul-server1",
    "data_dir":"/home/work/consul/data/",
    "enable_script_checks":false,
    "disable_update_check":true,
    "enable_local_script_checks":true,
    "log_file":"/home/work/consul/log/",
    "log_level":"info",
    "ui":true,
    "client_addr":"0.0.0.0",
    "log_rotate_bytes":100000000,
    "log_rotate_duration":"24h",
    "encrypt":"krCysDJnrQ8dtA7AbJav8g==",
    "acl":{
        "enabled":true,
        "default_policy":"deny",
        "enable_token_persistence":true,
        "tokens":{
            "master":"cd76a0f7-5535-40cc-8696-073462acc6c7",
            "agent":"46002ca8-ec4f-6cb7-7090-9e574ce5bd99"
           }
    }
}
```
10.157.10.101(server follow node)
```
{
    "datacenter":"dc1",
    "primary_datacenter":"dc1",
    "advertise_addr":"10.157.10.101",
    "bind_addr":"10.157.10.101",
    "client_addr":"0.0.0.0",
    "server":true,
    "connect":{
        "enabled":true
    },
    "node_name":"consul-server2",
    "data_dir":"/home/work/consul/data/",
    "enable_script_checks":false,
    "enable_local_script_checks":true,
    "disable_update_check":true,
    "log_file":"/home/work/consul/log/",
    "log_level":"info",
    "log_rotate_bytes":100000000,
    "log_rotate_duration":"24h",
    "encrypt":"krCysDJnrQ8dtA7AbJav8g==",
    "acl":{
        "enabled":true,
        "default_policy":"deny",
        "enable_token_persistence":true,
        "tokens":{
            "master":"cd76a0f7-5535-40cc-8696-073462acc6c7",
            "agent":"46002ca8-ec4f-6cb7-7090-9e574ce5bd99"
        }
    }
}
```
10.157.10.102(server leader node)
```
{
    "datacenter":"dc1",
    "primary_datacenter":"dc1",
    "advertise_addr":"10.157.10.102",
    "bind_addr":"10.157.10.102",
    "client_addr":"0.0.0.0",
    "server":true,
    "connect":{
        "enabled":true
    },
    "node_name":"consul-server3",
    "data_dir":"/home/work/consul/data/",
    "enable_script_checks":false,
    "enable_local_script_checks":true,
    "disable_update_check":true,
    "log_file":"/home/work/consul/log/",
    "log_level":"info",
    "log_rotate_bytes":100000000,
    "log_rotate_duration":"24h",
    "encrypt":"krCysDJnrQ8dtA7AbJav8g==",
    "acl":{
        "enabled":true,
        "default_policy":"deny",
        "enable_token_persistence":true,
        "tokens":{
            "master":"cd76a0f7-5535-40cc-8696-073462acc6c7",
            "agent":"46002ca8-ec4f-6cb7-7090-9e574ce5bd99"
           }
    }
}
```
**Now i want to configure 10.157.10.100 as distributor,10.157.10.101 as ingester,10.157.10.102 as querier,and my log data store in my computer filesystem.
My question is how do I configure loki.yaml，another question do I have to start a table-manager module?What is the role of the table-manager module？**
can you help me config the loki.yaml? @sh0rez

**Comment by yang3808282** [comment]
**

I configured a general loki.yaml file according to configure in the doc. The distributor, querier, and ingester modules all share this loki.yaml configuration file. Is this appropriate? Or how do I configure it?

**
```
auth_enabled: false
server:
  http_listen_address: localhost
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      store: consul
      consul:
        host: localhost:8500
        acltoken: 46002ca8-ec4f-6cb7-7090-9e574ce5bd99

querier:
  query_timeout: 1m
  tail_max_duration: 1h

ingester:
  lifecycler:
    address: localhost
    ring:
      kvstore:
        store: consul
        consul:
          host: localhost:8500
          acltoken: 46002ca8-ec4f-6cb7-7090-9e574ce5bd99
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

schema_config:
  configs:
  - from: 2020-03-03
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: loki_index_
      period: 168h

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: false
  retention_period: 0
```

**However,I run it with ./loki --config.file=loki.yaml -targer=distributor/ingester/querier，it not work。。。please help me,I just want to run loki with different module on different computer.** 

@sh0rez
