### ISSUE TITLE
rpc error: code = Unimplemented desc = unknown service logproto.Querier

### ISSUE THREAD

**Issue by vishnubraj** [grafana/loki#1896]
**Describe the bug**
Not able to add loki as a datasource in grafana.

i am getting below error in loki

```
 level=warn ts=2020-04-05T16:36:01.117973464Z caller=logging.go:49 traceID=5c3740f98292528a msg="GET /loki/api/v1/label?start=1586103960920000000 (500) 537.894µs Response: \"rpc error: code = Unimplemented desc = unknown service logproto.Querier\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate; Accept-Language: en-GB,en-US;q=0.9,en;q=0.8; User-Agent: Grafana/6.7.2; X-Forwarded-For: x.x.x.x, x.x.x.x; X-Grafana-Nocache: true; X-Grafana-Org-Id: 1; "
```

Loki reports 
```
Loki: Internal Server Error. 500. Internal Server Error 
```

Below mentioned in my loki config.. both loki and grafana is not in the same server..

```
auth_enabled: false

server:
  http_listen_port: 3100
  http_listen_address: 10.3.1.144

ingester:
  lifecycler:
    address: 10.3.1.144
    ring:
      kvstore:
        store: etcd
        etcd:
          endpoints: ["10.3.0.206:2380"]
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2020-03-20
    store: cassandra
    object_store: cassandra
    schema: v11
    index:
      prefix: logs_
      period: 168h

storage_config:
  cassandra:
    addresses: 10.3.1.48
    auth: false
    keyspace: lokiindex


limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: false
  retention_period: 0
```
