### ISSUE TITLE
entry out of order' for stream

### ISSUE THREAD

**Issue by vishnubraj** [grafana/loki#1897]
i am forwarding logs from fluentd to loki..
i am getting below mentioned error in loki. both the servers are having NTP configured and it is sync. 

```
level=warn ts=2020-04-05T16:39:22.772490867Z caller=grpc_logging.go:38 method=/logproto.Pusher/Push duration=6.996248ms err="rpc error: code = Code(400) desc = entry with timestamp 2020-04-05 16:39:11 +0000 UTC ignored, reason: 'entry out of order' for stream: {env=\"dev\"},\nentry with timestamp 2020-04-05 16:39:12 +0000 UTC ignored, reason: 'entry out of order' for stream: {env=\"dev\"},\nentry with timestamp 2020-04-05 16:39:12 +0000 UTC ignored, reason: 'entry out of order' for stream: {env=\"dev\"},\nentry with timestamp 2020-04-05 16:39:12 +0000 UTC ignored, reason: 'entry out of order' for stream: {env=\"dev\"},\nentry with timestamp 2020-04-05 16:39:12 +0000 UTC ignored, reason: 'entry out of order' for stream: {env=\"dev\"},\nentry with timestamp 2020-04-05 16:39:12 +0000 UTC ignored, reason: 'entry out of order' for stream: {env=\"dev\"},\nentry with timestamp 2020-04-05 16:39:12.771213579 +0000 UTC ignored, reason: 'entry out of order' for stream: {env=\"dev\"},\nentry with timestamp 2020-04-05 16:39:13 +0000 UTC ignored, reason: 'entry out of order' for stream: {env=\"dev\"},\nentry with timestamp 2020-04-05 16:39:13 +0000 UTC ignored, reason: 'entry out of order' for stream: {env=\"dev\"},\nentry with timestamp 2020-04-05 16:39:13 +0000 UTC ignored, reason: 'entry out of order' for stream: {env=\"dev\"},\ntotal ignored: 26 out of 1524" msg="gRPC\n
```

below mentioned in my loki config..

```
auth_enabled: false

server:
  http_listen_port: 3100
  http_listen_address: 10.3.1.144

ingester:
  lifecycler:
    address: 10.3.1.144
    ring:
      kvstore:
        store: etcd
        etcd:
          endpoints: ["10.3.0.206:2380"]
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2020-03-20
    store: cassandra
    object_store: cassandra
    schema: v11
    index:
      prefix: logs_
      period: 168h

storage_config:
  cassandra:
    addresses: 10.3.1.48
    auth: false
    keyspace: lokiindex


limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: false
  retention_period: 0
```
