### ISSUE TITLE
helm json pipeline not working when using expression shortcut.

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#1899]
**Describe the bug**

When using helm with json pipeline stage like this (values file below):

```yaml
    pipelineStages:
    - docker: {}
    - match:
        selector: '{foo="bar"}'
        stages:
        - json:
            expressions:
              level: 
              foo: bar
```

The actual config file will looks like this:

```yaml
- job_name: kubernetes-pods-static
  pipeline_stages:
    - docker: {}
    - match:
        selector:  '{foo="bar"}'
        stages:
        - json:
            expressions:
              foo: bar
```

As you can see the `level:` is removed by helm. 🤷‍♂ 

**Expected behavior**

The final config should contains the `level:` property.

**Environment:**
 - Deployment tool: helm 2.13

/cc @slim-bean @christopher-grech

**Comment by cyriltovena** [comment]
In 2.16.1 it seems to output different value.

```
- job_name: kubernetes-pods-static
  pipeline_stages:
    - docker: {}
    - match:
        selector: '{foo="bar"}'
        stages:
        - json:
            expressions:
              foo: bar
              level: null
```
