### ISSUE TITLE
promtail only scrapes one container per pod

### ISSUE THREAD

**Issue by dennybritz** [grafana/loki#190]
Using the helm chart with the following scrape config: https://github.com/grafana/loki/blob/ea712f38b82e6747892475272ff2422b46b0ed15/production/helm/templates/promtail/configmap.yaml

My pods have multiple containers, but it seems like promtrail only scrapes one of them. The promtail log files show that only one target is added per pod.

**Comment by dennybritz** [comment]
After digging a bit I believe this happens because the labels sets are not unique across containers. Appending the container name to the job label fixes this:

```yaml
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_label_name
          - __meta_kubernetes_pod_container_name
          target_label: job
```

Related but separate from https://github.com/grafana/loki/pull/154 - should probably be fixed together.
