### ISSUE TITLE
How to get full log from a pod if it exceed the line limit?

### ISSUE THREAD

**Issue by aaronsuns** [grafana/loki#1917]
There is a pod writing 4000+ lines of logs:
```
kubectl logs pod/steprunner-160-d6bgb | wc -l
4107
```
I want to see the full log in grafana loki, but the line limit does not seem to work, it only give me 500 lines maximum no matter I configured it as 5000 or not.

![Screenshot from 2020-04-08 11-09-23](https://user-images.githubusercontent.com/2472284/78769281-6e885700-798d-11ea-96bf-f97e3fa7a6e8.png)

Is there a way I could get full log from loki?  Thanks!

**Comment by owen-d** [comment]
Hey, I just tried this out and had similar results (although mine was capped at 1000). I checked the network tab and noticed that Grafana was overriding the limit on outgoing requests, so this appears to be a client side issue.  In the loki limits config, we support configuration via:
```
# Maximum number of log entries that will be returned for a query. 0 to disable.
[max_entries_limit: <int> | default = 5000 ]
```

**Comment by owen-d** [comment]
It looks like there is a maximum configured in the grafana datasource:
![image](https://user-images.githubusercontent.com/8173478/79155151-b567b980-7d9e-11ea-98b2-8cb3707e9eca.png)

**Comment by uselessjargon** [comment]
The max_entries_limit seems to not be in the latest loki version

```
./loki-linux-amd64 --version
loki, version 1.4.1 (branch: HEAD, revision: 2445ccd2)
  build user:       root@bb5e00b6b7f4
  build date:       2020-04-06T20:29:26Z
  go version:       go1.13.4
```
```
./loki-linux-amd64 -config.file loki-config.yml
failed parsing config: loki-config.yml: yaml: unmarshal errors:
  line 39: field max_entries_limit not found in type validation.plain
```
```
cat loki-config.yml
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_entries_limit: 500000

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: false
  retention_period: 0
```

**Comment by pgacek** [comment]
Hi,
I got a similar issue - I want to able search back for archive logs - my retention period is 360h.
as @uselessjargon said - we're not able to change `max_entries_limit` entry.
Loki 1.5.0

```
auth_enabled: false

    server:
      http_listen_port: 3100
      register_instrumentation: true
      graceful_shutdown_timeout: 10s

    distributor:
      ring:
        kvstore:
          store: "consul"
          consul:
            host: "consul-loki-server:8500"
            consistent_reads: true

    ingester:
      query_store_max_look_back_period: -1
      lifecycler:
        ring:
          kvstore:
            store: "consul"
            consul:
              host: "consul-loki-server:8500"
              http_client_timeout: 30s
          replication_factor: 2
        num_tokens: 512
        heartbeat_period: 15s
        join_after: 30s

    querier:
      query_timeout: 2m
      tail_max_duration: 12h
      engine:
        timeout: 30m
        max_look_back_period: 360h

    table_manager:
      retention_deletes_enabled: true
      retention_period: 360h
      poll_interval: 2m

    ingester_client:
      pool_config:
        health_check_ingesters: true
        client_cleanup_period: 30s
      remote_timeout: 120s

    storage_config:
      index_cache_validity: 30m
      max_chunk_batch_size: 10
      cassandra:
        addresses: xxxxxxx
        auth: false
        keyspace: index_logs_s
        port: 9042
        SSL: false
      azure:
        container_name: xxxx
        account_name: xxxx
        account_key: xxxxx

    schema_config:
      configs:
        - from: "2020-05-24"
          index:
            period: 120h
            prefix: index_
          chunks:
            period: 120h
            prefix: chunk_
          store: cassandra
          object_store: azure
          schema: v11

    chunk_store_config:
      max_look_back_period: 360h

    limits_config:
      ingestion_rate_strategy: global
      ingestion_rate_mb: 16
      ingestion_burst_size_mb: 32
      max_label_value_length: 4096
      max_query_length: 0
      max_chunks_per_query: 200000
      cardinality_limit: 200000
      max_streams_matchers_per_query: 2000
      max_entries_limit: 500000
```

```
failed parsing config: /etc/loki/loki.yaml: yaml: unmarshal errors:
  line 87: field max_entries_limit not found in type validation.plain
```

Is it possible to search for logs in history? I mean, logs from last 5 day for example?
