### ISSUE TITLE
Memory leak then odd errors

### ISSUE THREAD

**Issue by stackrainbow** [grafana/loki#1924]
**Describe the bug**
I'm using a single instance of loki to collect nginx logs via promtail from four webservers that are under a decent amount of load.
The collection of this data seems to occur without issue, however quering the data seems to result in eventual memory leaks and errors. Queries over time seem to add more memory (about 2GB of memory) each time. Then start to error. 

**To Reproduce**
1. Started Loki (SHA or version) Loki 1.4.1 Docker
2. Started Promtail (SHA or version) latest Docker  to tail /usr/local/openresty/nginx/logs/*.log.' 
3. Query: `{job="nginx"}`

**Expected behavior**
Query runs without memory usage substantially increasing (or with the memory eventually being deallocated) and without corruption that seems to eventually occur.

**Environment:**
 - Infrastructure: bare metal (4 vms running promtail) - 1 bare metal server running loki inside a docker container (16GB RAM, 8 Core Xeon E5)
 - Deployment tool: docker

**Screenshots, Promtail config, or terminal output**
Errors that start occuring eventually (without restarts/crashes, and with deleting the data before starting):

```
level=warn ts=2020-04-09T15:21:58.067177709Z caller=logging.go:49 traceID=72b82c394e1bcb0b msg="GET /api/prom/query?direction=BACKWARD&limit=50&regexp=&query=%7Bjob%3D%22nginx%22%7D&start=1586445657642000000&end=1586445717642000000&refId=A (500) 233.931301ms Response: \"invalid chunk time range value: 6f73746e616d65222c226874747056657273696f6e222c226970222c226a6f62222c226d6574686f64222c2270617468222c2272656665726572222c22726571756573\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,de;q=0.7,it;q=0.6; Connection: close; Sec-Fetch-Dest: empty; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Agent: Grafana/6.5.3; X-Forwarded-For: 90.255.157.85, 172.18.0.5, 172.18.0.5, 23.101.61.93; X-Forwarded-Port: 443; X-Forwarded-Proto: https; X-Forwarded-Ssl: on; X-Grafana-Org-Id: 1; X-Real-Ip: [removed];
```

```
level=warn ts=2020-04-09T15:21:47.903447591Z caller=logging.go:49 traceID=3fcfcc949a852964 msg="GET /api/prom/query?direction=BACKWARD&limit=50&regexp=&query=%7Bjob%3D%22nginx%22%7D&start=1586445647622000000&end=1586445707622000000&refId=A (500) 240.088487ms Response: \"invalid chunk ID \\\"O/h4XVPZPKp94qL4Jx+V4p8bnNNjMCJItAaFvh9Ysck\\\"\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,de;q=0.7,it;q=0.6; Connection: close; Sec-Fetch-Dest: empty; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Agent: Grafana/6.5.3; X-Forwarded-For: 90.255.157.85, 172.18.0.5, 172.18.0.5, 23.101.61.93; X-Forwarded-Port: 443; X-Forwarded-Proto: https; X-Forwarded-Ssl: on; X-Grafana-Org-Id: 1; X-Real-Ip: 23.101.61.93; "
ts=2020-04-09T15:21:52.904589876Z caller=spanlogger.go:53 org_id=fake trace_id=61336c4fb8b6b38d method=SeriesStore.GetChunkRefs level=error op=convertChunkIDsToChunks err="invalid chunk ID \"dy0tA68bvmjXqln54AS7fnGT5WSwvI02CEbE7anygkg\""
level=info ts=2020-04-09T15:21:52.904738432Z caller=metrics.go:83 org_id=fake trace_id=61336c4fb8b6b38d latency=fast query="{job=\"nginx\"}" query_type=limited range_type=range length=1m0s step=1s duration=236.754272ms status=500 throughput_mb=0 total_bytes_mb=0
```

Loki configuration:
```
auth_enabled: false

server:
  http_listen_port: 80

ingester:
  lifecycler:
    address: 0.0.0.0
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 3m
  chunk_retain_period: 1m

schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  max_chunk_batch_size: 500
  boltdb:
    directory: /mnt/loki/index

  filesystem:
    directory: /mnt/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 150
  max_streams_per_user: 0
```

Promtail config:

```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://removed/loki/api/v1/push
  basic_auth:
    username: removed
    password: removed

scrape_configs:
- job_name: nginx
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      __path__: /usr/local/openresty/nginx/logs/*.log
  pipeline_stages:
    - match:
        selector: '{filename="/usr/local/openresty/nginx/logs/access.log"}'
        stages:
          - regex:
              expression: '(?P<ip>[0-9.]+) - - \[(?P<timestamp>[^\]]+)\] "(?P<host>[^"]+)" "(?P<method>[^ ]+) (?P<path>[^ ]*) (?P<httpVersion>[^"]+)" (?P<responseCode>[0-9]+) (?P<responseSize>[0-9]+) "(?P<referer>[^"]+)" "(?P<userAgent>[^"]*)" (?P<requestTime>[0-9.]+)$'
          - labels:
              ip:
              host:
              method:
              path:
              httpVersion:
              responseCode:
              responseSize:
              referer:
              userAgent:
              requestTime:
          - timestamp:
              source: timestamp
              format: "02/Jan/2006:15:04:05 -0700"
```

**Comment by cyriltovena** [comment]
FYI there is no leak, when you run a big queries, go won't release the memory so it's normal to see the memory increase and never decrease. It should decrease very slowly over time.

Can you share more about your configuration and the query itself (the range) ?

From what I can see you also have too many labels with high cardinality.

```
 ip:
              host:
              method:
              path:
              httpVersion:
              responseCode:
              responseSize:
              referer:
              userAgent:
              requestTime:
```

I suggest you keep only method. If your intention was to build metrics you should look into metrics pipeline instead and scrape that with Prometheus. see https://github.com/grafana/loki/blob/master/docs/clients/promtail/stages/metrics.md

If you want to find specific request to trace some issue then you should use LogQL filter. see https://github.com/grafana/loki/blob/master/docs/logql.md#filter-expression
