### ISSUE TITLE
`targets` should not be required for promtail scrape config

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#1929]
```
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

```

The `targets` definition is required because of the use of Prometheus code however has no real use or application in Promtail.

Not sure how easy or possible it is to remove this but it would be a nice simplification on the config.

Relevant code here:

https://github.com/grafana/loki/blob/5e752bf343e221b274319074d358cd4dceca0bb8/pkg/promtail/targets/filetargetmanager.go#L208
