### ISSUE TITLE
Some logs are duplicated

### ISSUE THREAD

**Issue by Sh4d1** [grafana/loki#1948]
**Describe the bug**
Some lines appears to be duplicated. One parse, the other one still in Docker's json format.

**To Reproduce**
1. Started Loki (SHA or version)
1.4.1
2. Started Promtail (SHA or version) to tail '...'
1.4.0

**Expected behavior**
Only to have one line not duplicated 

**Environment:**
 - Infrastructure: Promtail in k8s, loki outside
 - Deployment tool: promtail with helm, loki with docker

**Screenshots, Promtail config, or terminal output**
Promtail config:
```
- match:
    selector: '{app=~"myapp.*"}'
    stages:
    - docker: {}
    - regex:
        expression: ^(?P<level>I|W|E)(?P<date>\d+)\s+(?P<time>\d+:\d+:\d+.\d+)\s+\d(?s)(?P<file>.*\.go:\d+)]\s+(?P<component>.*?):(?P<msg>.*)
    - template:
        source: level
        template: '{{ if eq .Value "I" }}{{ Replace .Value "I" "INFO" -1 }}{{ else if eq .Value "W" }}{{ Replace .Value "W" "WARNING" -1 }}{{ else if eq .Value "E" }}{{ Replace .Value "E" "ERROR" -1 }}{{ else }}{{ .Value }}{{ end }}'
    - labels:
        level:
        file:
        component:
```

Without this config, I have no problem, with this config, I see some duplicated logs ex:
```
I0416 06:48:04.914129       1 shoot.go:165] Async: Async: received node updates
```
Which have the correct label `level`, `file` and `component`
And 
```	
{"log":"I0416 06:48:04.914129       1 shoot.go:165] Async: Async: received node updates\n","stream":"stderr","time":"2020-04-16T06:48:04.914317011Z"}
```
which does not have the label.

Any ideas? I tried with debug enabled on promtail but didn't found something worth exploiting.
