### ISSUE TITLE
Incorrect ksonnet configuration for AWS dynamodb

### ISSUE THREAD

**Issue by yeya24** [grafana/loki#1954]
**Describe the bug**
I am using the ksonnet file to deploy loki on AWS, using dynamodb and S3. But the default config seems doesn't work for table manager.

The config is 

```
    table_manager:
        chunk_tables_provisioning:
            inactive_read_throughput: 0
            inactive_write_throughput: 0
            provisioned_read_throughput: 0
            provisioned_write_throughput: 0
        index_tables_provisioning:
            inactive_read_throughput: 0
            inactive_write_throughput: 0
            provisioned_read_throughput: 0
            provisioned_write_throughput: 0
        retention_deletes_enabled: false
        retention_period: 0
```

The error log in table-manager:

```
InvalidParameter: 2 validation error(s) found.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.ReadCapacityUnits.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.WriteCapacityUnits.\n; InvalidParameter: 2 validation error(s) found.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.ReadCapacityUnits.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.WriteCapacityUnits.\n; InvalidParameter: 2 validation error(s) found.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.ReadCapacityUnits.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.WriteCapacityUnits.\n; InvalidParameter: 2 validation error(s) found.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.ReadCapacityUnits.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.WriteCapacityUnits.\n; InvalidParameter: 2 validation error(s) found.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.ReadCapacityUnits.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.WriteCapacityUnits.\n; InvalidParameter: 2 validation error(s) found.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.ReadCapacityUnits.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.WriteCapacityUnits.\n; InvalidParameter: 2 validation error(s) found.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.ReadCapacityUnits.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.WriteCapacityUnits.\n; InvalidParameter: 2 validation error(s) found.\n- minimum field value of 1, CreateTableInput.ProvisionedThroughput.ReadCapacityUnits.\n- minimum field value of 1,
```

Is there a correct configuration? I didn't find any configuration related to `ProvisionedThrought.ReadCapacityUnits` or  `ProvisionedThroughput.WriteCapacityUnits` in this document https://github.com/grafana/loki/blob/master/docs/configuration/README.md#table_manager_config

Any help would be appreciated!
