### ISSUE TITLE
Loglines disappear after 5m (when ingester flushes to DB)

### ISSUE THREAD

**Issue by holmbaeck** [grafana/loki#1955]
**Describe the bug**
I have issue with both 1.4.0 and 1.4.1. For me it seems like an issue with either too long logline, or to large parsed fields.

I can see the lines for 5 minutes. I guess this is when the data is in the ingester before flush to DB. But after 5m the line disappear. There are no errors in the Loki pod logs.

Is this a problem because the "large" json field gets stored in a parsed field, and if so, can we remedy it somehow?

**To Reproduce**
1. Deployed loki stack
2. Deployed a pod
3. Create a logline with a large jsonfield
4. Query loki immediately - look at the nide results
5. Wait 5m 
6. Query again - wail in despair

**Expected behavior**
Get all log lines
```
{
    "status": "success",
    "data": {
        "resultType": "streams",
        "result": ["three lines with lots of data"],
        "stats": {
            "summary": {
                "bytesProcessedPerSeconds": 33994148,
                "linesProcessedPerSeconds": 2737,
                "totalBytesProcessed": 37248,
                "totalLinesProcessed": 3,
                "execTime": 0.001095718
            },
            "store": {
                "totalChunksRef": 0,
                "totalChunksDownloaded": 0,
                "chunksDownloadTime": 0,
                "headChunkBytes": 0,
                "headChunkLines": 0,
                "decompressedBytes": 0,
                "decompressedLines": 0,
                "compressedBytes": 0,
                "totalDuplicates": 0
            },
            "ingester": {
                "totalReached": 1,
                "totalChunksMatched": 3,
                "totalBatches": 1,
                "totalLinesSent": 3,
                "headChunkBytes": 37248,
                "headChunkLines": 3,
                "decompressedBytes": 0,
                "decompressedLines": 0,
                "compressedBytes": 0,
                "totalDuplicates": 0
            }
        }
    }
}
```
call again after 5 minutes
still get all loglines
-- but we get this
```
{
    "status": "success",
    "data": {
        "resultType": "streams",
        "result": [],
        "stats": {
            "summary": {
                "bytesProcessedPerSeconds": 0,
                "linesProcessedPerSeconds": 0,
                "totalBytesProcessed": 0,
                "totalLinesProcessed": 0,
                "execTime": 0.001571336
            },
            "store": {
                "totalChunksRef": 3,
                "totalChunksDownloaded": 3,
                "chunksDownloadTime": 0.000347704,
                "headChunkBytes": 0,
                "headChunkLines": 0,
                "decompressedBytes": 0,
                "decompressedLines": 0,
                "compressedBytes": 2865,
                "totalDuplicates": 0
            },
            "ingester": {
                "totalReached": 1,
                "totalChunksMatched": 0,
                "totalBatches": 0,
                "totalLinesSent": 0,
                "headChunkBytes": 0,
                "headChunkLines": 0,
                "decompressedBytes": 0,
                "decompressedLines": 0,
                "compressedBytes": 0,
                "totalDuplicates": 0
            }
        }
    }
}
```

**Environment:**
 - Infrastructure: Kubernetes 1.16.7
 - Deployment tool: helm (loki chart 0.26.0 from loki-stack)
 - using BoltDB default persistence=true, 10Gi

**Screenshots, Promtail config, or terminal output**
Loki-stack values
```
loki-stack:
  loki:
    enabled: true
    persistence:
      enabled: true
    config:
      ingester:
        max_transfer_retries: 3
      table_manager:
        retention_deletes_enabled: true
        retention_period: 168h

  grafana:
    enabled: true
    admin:
      existingSecret: "grafana"

  prometheus:
    enabled: true
    server:
      statefulSet:
        enabled: true
      persistentVolume:
        enabled: true
    alertmanager:
      persistentVolume:
        enabled: true
    nodeExporter:
      enabled: false
    pushgateway:
      enabled: false
    kubeStateMetrics:
      enabled: false    

  fluent-bit:
    enabled: false

  promtail:
    enabled: true
    ## Remove ability to deploy on master
    tolerations: []
    pipelineStages:
    - docker: {}
    - json:
        expressions:
          app:
          message:
          level:
          logger_name:
          response_code:
          request_body:
          request_path:
          response_body:
          response_time:
          request_method:
          application_name:
          trace_id:
          span_id:
    - template:
        source: jaeger_link
        template: 'https://jaeger.{DOMAIN_TOKEN}/trace/{{ .trace_id }}'
    - labels:
          app:
          level:
          logger_name:
          response_code:
          request_path:
          response_time:
          request_method:
          application_name:     
          trace_id:
          span_id:
          jaeger_link:
    - match:
        selector: '{namespace!="{NAMESPACE_TOKEN}"}'
        action: drop
```

logs are picked up immediately
![image](https://user-images.githubusercontent.com/1744680/79541355-f6efb180-8089-11ea-80cc-a8dc21c86dd8.png)
![image](https://user-images.githubusercontent.com/1744680/79541471-2c949a80-808a-11ea-9ef0-ad1ac20c9973.png)
The logline has a 12k json field (debug output), if I reduce data in that field the logline stays after flush
![image](https://user-images.githubusercontent.com/1744680/79541667-809f7f00-808a-11ea-86cb-37860b621ee6.png)
5 minutes gone - same request - no data
![image](https://user-images.githubusercontent.com/1744680/79541730-a6c51f00-808a-11ea-8858-fd6d6fecd3f2.png)
No data :(
![image](https://user-images.githubusercontent.com/1744680/79542249-906b9300-808b-11ea-91de-84d9f9254cec.png)

loki-log
```
level=info ts=2020-04-17T06:59:48.652157744Z caller=metrics.go:83 org_id=fake trace_id=76825d1e93cab114 latency=fast query="{app=\"address-service\"}" query_type=limited range_type=range length=30m1s step=1s duration=1.345012ms status=200 throughput_mb=2.7693433 total_bytes_mb=0.0037248
level=info ts=2020-04-17T07:00:13.056745392Z caller=table_manager.go:247 msg="synching tables" expected_tables=2
level=info ts=2020-04-17T07:02:13.056732943Z caller=table_manager.go:247 msg="synching tables" expected_tables=2
level=info ts=2020-04-17T07:04:13.056702243Z caller=table_manager.go:247 msg="synching tables" expected_tables=2
level=info ts=2020-04-17T07:04:57.82886167Z caller=metrics.go:83 org_id=fake trace_id=49fab37dbcfc3e7c latency=fast query="{app=\"address-service\"}" query_type=limited range_type=range length=30m1s step=1s duration=1.571336ms status=200 throughput_mb=0 total_bytes_mb=0
level=info ts=2020-04-17T07:06:13.056714063Z caller=table_manager.go:247 msg="synching tables" expected_tables=2
```

**Comment by brandonstark** [comment]
Did you ever figure this out?
I have the same issue in 1.5

**Comment by holmbaeck** [comment]
@brandonstark Unfortunately not, we haven't had time to really dig into it. Hopefully we can do something within the next couple of weeks. We are still a few months from production, but if it is not fixed, then fallback will be EFK stack

**Comment by cyriltovena** [comment]
Have you tried to look at what contains the volume (PVC) ? if it's getting erased somehow ?

**Comment by holmbaeck** [comment]
@cyriltovena, since the other loglines stay and only log lines with parsed fields larger tan 3-4k gets erased, I do not see how it can be a PVC issue. My guess is that it is a limitation in parsed fields, on the receiving end of the ingester's flush.

**Comment by cyriltovena** [comment]
Have you tried logcli? It may be related to grafana not handling correctly very long line.

**Comment by cyriltovena** [comment]
Ho sorry didn’t see the response in the network tab.

**Comment by holmbaeck** [comment]
@cyriltovena Same result with logcli. Logline is shown for 5m minutes while in the ingester, then disappears. If I change the ingester config to retain chunks for longer, the lines will be searchable in grafana during "chunk_idle_period" time
`
```yaml
      ingester:
        chunk_idle_period: 1h
        max_chunk_age: 1h
        chunk_block_size: 1048576
        chunk_retain_period: 30s
        max_transfer_retries: 0        
````
Above will make the lines available for 1 hour.
I have also bumped to loki v1.5.0, and it has same result

**Comment by cyriltovena** [comment]
Ok that’s good, can you activate debug log and check if you have any interesting log when flushing chunks ? Btw SIGTERM will force flush.

**Comment by cyriltovena** [comment]
Also can you keep only lvl, app and logger as labels the rest is easily searchable with logql and will force a chunk per request which we don’t want.

**Comment by holmbaeck** [comment]
@cyriltovena Unfortunately there is no interesting logs when doing debug.
[loki-debug.log](https://github.com/grafana/loki/files/4863288/loki-debug.log)

**Comment by cyriltovena** [comment]
Ok Could you send me a chunk where a line is supposed to be there and you don't see it, which line it is and I'll check if it has been flushed just to narrow down the issue.

We have an inspect chunk too in ./cmd you could use too if you want to push this further. see https://github.com/grafana/loki/tree/master/cmd/chunks-inspect

**Comment by holmbaeck** [comment]
@cyriltovena nice tool, I found the chunk, so it is getting stored, but doesn't show up in search
Chunk attached
[the-missing-chunk.zip](https://github.com/grafana/loki/files/4866555/the-missing-chunk.zip)

**Comment by holmbaeck** [comment]
For reference, these two chunks are created at the same time (during same request) by same service and are searchable.
[small-1.zip](https://github.com/grafana/loki/files/4866579/small-1.zip)
[small-2.zip](https://github.com/grafana/loki/files/4866580/small-2.zip)

**Comment by cyriltovena** [comment]
Thanks for this you how big the line is ? I'll take a look soon at this chunk and try to reproduce and hopefully get a fixed for it.

**Comment by holmbaeck** [comment]
@cyriltovena FYI, as per your suggestion I have reduced the amount of labels, and now the "missing" logline can be found

promtail config
````yaml
pipelineStages:
    - labels:
          app:
          application_name:     
          level:
          logger_name:

removed labels
          response_code:
          request_path:
          response_time:
          request_method:
          application_name:     
          trace_id:
          span_id:
          jaeger_link:
````
