### ISSUE TITLE
Promtail doesn't work in remote PowerShell session

### ISSUE THREAD

**Issue by SDedik** [grafana/loki#1968]
**Describe the bug**
On the same Windows Server 2019 machine, under the same user, if PowerShell is launched from full UI session, promtail works, but if the session is remote PSSession even to the localhost, it fails, or rather exits prematurely with 0 exit code.

**To Reproduce**
`config.yaml`:
```
positions:
  filename: C:\promtail\positions.yml

clients:
  - url: http://loki.instance:3100/loki/api/v1/push

scrape_configs:
  - job_name: my
    entry_parser: raw
    static_configs:
    - targets:
      - localhost
      labels:
        __path__: 'C:\log\my.log'
```

Launching from PowerShell shell started from full UI session works fine:
```
PS C:\Windows\system32> & cmd /c "C:\promtail\promtail.exe -config.file=C:\promtail\config.yaml 2>&1"
level=warn ts=2020-04-21T13:03:42.5239351Z caller=filetargetmanager.go:105 msg="WARNING!!! entry_parser config is deprecated, please change to pipeline_stages"
level=info ts=2020-04-21T13:03:42.5239351Z caller=server.go:147 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2020-04-21T13:03:42.5259289Z caller=main.go:67 msg="Starting Promtail" version="(version=1.4.1, branch=HEAD, revision=2445ccd2)"
level=info ts=2020-04-21T13:03:47.5268882Z caller=filetargetmanager.go:263 msg="Adding target" key={}
ts=2020-04-21T13:03:47.5278739Z caller=log.go:124 component=tailer level=info msg="Seeked C:\\log\\my.log - &{Offset:0 Whence:0}"
level=info ts=2020-04-21T13:03:47.5288742Z caller=tailer.go:80 component=tailer msg="start tailing file" path=C:\log\my.log
```

Launching from PSSession to localhost exits prematurely:
```
PS C:\Windows\system32> Enter-PSSession -ComputerName localhost
[localhost]: PS C:\Users\masked\Documents> & cmd /c "C:\promtail\promtail.exe -config.file=C:\promtail\config.yaml 2>&1"
level=info ts=2020-04-21T12:57:44.4624752Z caller=server.go:147 http=[::]:80 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2020-04-21T12:57:44.4624752Z caller=main.go:67 msg="Starting Promtail" version="(version=1.4.1, branch=HEAD, revision=2445ccd2)"
[localhost]: PS C:\Users\masked\Documents> $LASTEXITCODE
0
```

**Expected behavior**
For console utility it should make absolutely zero difference whether it is launched from UI session, PSSession, remotely over WMI call or triggered by some other program.

**Environment:**
& C:\promtail\promtail.exe -version
promtail, version 1.4.1 (branch: HEAD, revision: 2445ccd2)
  build user:       root@bb5e00b6b7f4
  build date:       2020-04-06T20:29:26Z
  go version:       go1.13.4
