### ISSUE TITLE
promtail failed to parse original timestamp from syslog rfc5424 message

### ISSUE THREAD

**Issue by erwin-nijenhuis** [grafana/loki#1984]
**Describe the bug**
When injecting a RFC5424 syslog messages into promtail the timestamp of the original message is not parsed at all. All other fields are parsed and labeled correctly. The time of reception is now used to fill the time tag. The following config is used:

```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      idle_timeout: 3600s

    pipeline_stages:    
      - timestamp:
         source: time
         format: RFC3339Nano

    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: host
      - source_labels: ['__syslog_message_severity']
        target_label: level
      - source_labels: ['__syslog_message_app_name']
        target_label: job
      - source_labels: [__syslog_message_facility]
        target_label: facility
```

**To Reproduce**

1) start promtail with the configuration shows above
2) inject a RFC5424 syslog message to promtail
```
echo '<30>1 2020-04-25T16:32:17.984776+02:00 api dhclient 433 - -  bound to 192.168.182.150 -- renewal in 884 seconds.' | nc -v  -w 1 192.168.2.8 1514
```
3) debug logs from promtail will show that timestamp is not parsed from the original message
```
level=debug ts=2020-04-25T14:36:46.709459567Z caller=pipeline.go:91 component=syslog_pipeline component=pipeline msg="processing pipeline" stage=0 name=timestamp labels="{facility=\"daemon\", host=\"api\", job=\"dhclient\", level=\"informational\"}" time=2020-04-25T14:36:46.709419227Z entry=" bound to 192.168.182.150 -- renewal in 884 seconds."
level=debug ts=2020-04-25T14:36:46.709818913Z caller=timestamp.go:159 component=syslog_pipeline msg="extracted data did not contain a timestamp"
level=debug ts=2020-04-25T14:36:46.709878351Z caller=pipeline.go:97 component=syslog_pipeline component=pipeline msg="finished processing log line" labels="{facility=\"daemon\", host=\"api\", job=\"dhclient\", level=\"informational\"}" time=2020-04-25T14:36:46.709419227Z entry=" bound to 192.168.182.150 -- renewal in 884 seconds." duration_s=0.000451065
```

**Expected behavior**
promtail should parse the original RFC3339MICRO timestamp from the syslog message and use that for the original timestamp in LOKI.

**Environment:**
 - Infrastructure: docker containers of Promtail, Loki and Grafana
 - Deployment tool: docker

**Screenshots, Promtail config, or terminal output**
See attached file for promtail and docker-compose config files

[promtail.yml.txt](https://github.com/grafana/loki/files/4533215/promtail.yml.txt)
[docker-compose.yml.txt](https://github.com/grafana/loki/files/4533217/docker-compose.yml.txt)
