### ISSUE TITLE
Verify that Loki and promtail are configured properly

### ISSUE THREAD

**Issue by rampreethethiraj** [grafana/loki#199]
curl -X POST -H 'Content-type:application/json'  loki:3100/api/prom/push -d '{"streams":[{"labels":"{foo=\"bar\"}","entries":[{"ts":"2018-12-18T08:28:06.801064-04:00","line":"baz"}]}]}'
rpc error: code = Unknown desc = Entry out of order

Seeing this error when trying to do a post request.

**Comment by woodsaj** [comment]
@rampreethethiraj you need to increment the timestamp of the stream entry.  Loki currently doesnt support log lines with the same timestamp.  see https://github.com/grafana/loki/issues/168

**Comment by rampreethethiraj** [comment]
Okay I see, my acutal issue is this. 
I have deployed grafana, loki and promtail agent on the kubernetes cluster but while adding loki as data source in the grafana dashboard, I am facing this error.
Data source connected, but no labels received. Verify that Loki and Promtail is configured properly.
Followed this - https://github.com/grafana/loki/tree/master/production/helm

**Comment by kentore82** [comment]
Could be related to #170 ?

**Comment by cocowalla** [comment]
Also getting this with the hosted Grafana demo of Loki 😞

**Comment by tadone** [comment]
The ClusterRoleBinding for loki-promtail-clusterrolebinding has namespace set to `default`. If you're deploying to different namespace (for me was monitoring) it will cause this error. When I changed that namespace in the binding to `monitoring` the error went away.

**Comment by tadone** [comment]
@mewwts Make sure that this file: https://github.com/grafana/loki/blob/master/production/helm/templates/promtail/clusterrolebinding.yaml has correct namespace, the one that you're deploying in. I prefer not to use Helm so I make my changes manually to generated template.

**Comment by niklasravnsborg** [comment]
I also have this error. My ClusterRoleBinding looks correct and I deployed the helm charts prometheus-operator and loki-stack. Can anyone point me to a fix?

**Comment by mlzxdzl** [comment]
I have the same problem. I Build and Run From Source. I add source in the grafana. Then I got the Error:
Data source connected, but no labels received. Verify that Loki and Promtail is configured properly.
Can any one help me ?

**Comment by tangkangrui** [comment]
I have the same error. I deploy loki promtail grafana in the same docker network.
Command `docker logs -f loki` shows `level=info ts=xxx caller=filetargetmanager.go.257 msg="Adding target " key="{job=\"varlogs\"}"`

I mount hostpath `/var/log` to promtail container, and there are some files named *.log.

**Comment by cyriltovena** [comment]
looks like promtail is happy what about Loki any interesting logs ?

You do send logs right ?

**Comment by rally25rs** [comment]
Anyone ever figure this out? I get this by simply following https://github.com/grafana/loki/blob/master/docs/installation/helm.md and customizing nothing other than using `fluent-bit` instead of `promtail`.

requirements.yaml
```
dependencies:
- name: "loki-stack"
  repository: "https://grafana.github.io/loki/charts"
  version: "^0.6.0"
```

values.yaml
```
fluent-bit:
  enabled: true
promtail:
  enabled: false
grafana:
  enabled: true
prometheus:
  enabled: true
  alertmanager:
    persistentVolume:
      enabled: false
  server:
    persistentVolume:
      enabled: false
    service:
      servicePort: web
```

deploy it with `helm upgrade --install ...`

then open the Grafana UI and try to add Loki as a datsource with the URL `http://{my release name}-loki:3100.
```
Data source connected, but no labels received. Verify that Loki and Promtail is configured properly.
```
