### ISSUE TITLE
docker is practically unusable when the loki endpoint is not accessible

### ISSUE THREAD

**Issue by rafipiccolo** [grafana/loki#2017]
**Describe the bug**
docker is practically unusable when the loki endpoint is not accessible.

**To Reproduce**
1. create this docker-compose
```
version: "3.3"
services:
  loki:
    image: grafana/loki:latest
    restart: always
    container_name: loki
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/local-config.yaml

  datelogger:
    image: busybox
    container_name: datelogger
    command: sh -c "while true; do $$(echo date); sleep 1; done"
    restart: always
```

2. create this file /etc/docker/daemon.json
```
{
    "debug" : true,
    "log-driver": "loki",
    "log-opts": {
        "loki-url": "http://localhost:3100/loki/api/v1/push",
        "loki-batch-size": "400"
    }
}
```

3. restart docker
4. start
docker-compose up -d datelogger

```
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

and the service is not up.

if on the contrary loki and datelogger were both up, and then loki dies. what happens to datelogger. its not even possible to kill it with docker-compose down.

i though about adding "mode": "non-blocking" into "log-opts".
but the loki's driver says it doesnt recognize it.

Do you have a solution ?

**Expected behavior**
the service should be up. with logs discarded until the connection is available.
if the loki endpoint becomes slow, it shouldn't slow the main server also.

**Environment:**
ubuntu 18.04 + docker + docker compose

**Screenshots, Promtail config, or terminal output**
