### ISSUE TITLE
Dockerized promtail: read-only file system\\\"\"": unknown

### ISSUE THREAD

**Issue by zar3bski** [grafana/loki#2025]
**Describe the bug**
I can't manage to start this container on my CentOS server (though it worked perfectly on my worskstation). Here are the relevant sections on the `docker-compose`

```yml
services:
  nginx: 
    container_name: ${SERVER_NAME}_nginx
    restart: always
    image: nginx:1.17.5-alpine
    entrypoint: /entrypoint.sh
    ports: 
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes: 
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - nginx-logs:/var/log/nginx
      - certificates:/etc/letsencrypt/

 promtail: 
    restart: always
    container_name: ${SERVER_NAME}_promtail
    image: grafana/promtail:master-b652f0a
    command: -config.file=/etc/promtail/docker-config.yaml
    volumes: 
      - nginx-logs:/var/log/nginx
      - ./promtail/docker-config.yaml:/etc/promtail/docker-config.yaml:ro
```

And here is the error (I do not fully understand)

```bash
ERROR: for asmodius_promtail  Cannot start service promtail: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/docker/volumes/asmodius_nginx-logs/_data\\\" to rootfs \\\"/var/lib/docker/overlay2/2a86717f58416d8c7539729c56814c6b104bb058689c190e832fb904fcd80791/merged\\\" at \\\"/var/lib/docker/overlay2/2a86717f58416d8c7539729c56814c6b104bb058689c190e832fb904fcd80791/merged/var/log/nginx\\\" caused \\\"mkdir /var/lib/docker/overlay2/2a86717f58416d8c7539729c56814c6b104bb058689c190e832fb904fcd80791/merged/var/log/nginx: read-only file system\\\"\"": unknown
```

**To Reproduce**
run this `docker-compose.yml`

**Expected behavior**
The container should have started the same way it started on my workstation (Debian 9). Because the volume pre-existed the integration of promtail in the stack, I tried to remove it but the same bug occurs. 

**Environment:**

* Docker version 19.03.8, build afacb8b
* docker-compose version 1.24.1, build 4667896b
* CentOS Linux release 7.8.2003 (Core)

**Screenshots, Promtail config, or terminal output**
Here is the `docker-config.yaml`

```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
- job_name: nginx
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginxlogs
      __path__: /var/log/nginx/*log
```

**Comment by cyriltovena** [comment]
Try to mount your nginx log somewhere else it seems that docker is trying to mkdir in /var/log/nginx at startup to prior mounting the folder. 

Try /var/log simply or /tmp/log

**Comment by yangirov** [comment]
I had exactly the same problem. 

My solution is to use a named folder, `/var/log/nginx` instead `nginx-logs`, example:
```
tb-nginx:
  image: nginx:1.18-alpine
  volumes:
    - /var/log/nginx:/var/log/nginx/
  ports:
    - 80:80

promtail:
  image: grafana/promtail:master
  volumes:
    - /var/log/nginx:/var/log/nginx
  command: -config.file=/etc/promtail/loki-promtail-config.yml
  links:
    - loki
  networks:
    - tb-network
```
