### ISSUE TITLE
promtail can't parse multiple "static_configs"

### ISSUE THREAD

**Issue by crazy-canux** [grafana/loki#2057]
**Describe the bug**

promtail log error:
u33xe7x38qua6nnpb4c6aynsb.1@l1eyap4jbi6wunhlex7u401zw    |  Unable to parse config: /etc/promtail/promtail-config.yaml: yaml: unmarshal errors:
u33xe7x38qua6nnpb4c6aynsb.1@l1eyap4jbi6wunhlex7u401zw    |    line 21: field lables not found in type struct { Targets []string "yaml:\"targets\""; Labels model.LabelSet "yaml:\"labels\"" }

**To Reproduce**
1. Started Loki (SHA or version)
    loki:latest
2. Started Promtail (SHA or version) to tail '...'
    promtail:latest
3. Query: `{} term`

**Expected behavior**
promtail works.

**Environment:**
docker swarm

**Screenshots, Promtail config, or terminal output**
promtail config:
 11 scrape_configs:
 12   - job_name: system
 13     static_configs:
 14       - targets:
 15           - localhost
 16         labels:
 17           job: varlogs
 18           __path__: /var/log/*log
 19       - targets:
 20           - localhost
 21         lables:
 22           job: csa
 23           __path__: /var/log/appliance/*log

**Comment by adityacs** [comment]
@crazy-canux Could you please format your `promtail config` and update your comment?

**Comment by adityacs** [comment]
If you have in the following format it should work

```
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log
  - targets:
     - localhost
    labels:
      job: varlogs
      __path__: /var/log/appliance/*.log

```
