### ISSUE TITLE
Promtail extraScrapeConfigs not being picked up

### ISSUE THREAD

**Issue by robbertvdg** [grafana/loki#2068]
**Describe the bug**
It seems that excluding logs in a pod using the configuration below does not work:
```  
extraScrapeConfigs:
 - job_name: blacklist
   kubernetes_sd_configs:
   - role: pod
   relabel_configs:
   - action: drop
     regex: test
     source_labels:
     - __meta_kubernetes_pod_label_app
```

**To Reproduce**
1. Deployed helm loki-stack (0.36.2)
2. Attach grafana to loki datasource
2. Query: `{app="test"}` in Grafana Loki
3. See logs

**Expected behavior**
Not seeing any logs

**Environment:**
 - Infrastructure: kubernetes (1.15)
 - Deployment tool: helm

Maybe i'm missing something, help would be appreciated!

**Comment by robbertvdg** [comment]
After a bit more research we came up with the following that did work: 

```
scrapeConfigs:
    - job_name: kubernetes-pods-name
      [.. default .. ]
    - job_name: kubernetes-pods-app
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: .+
        source_labels:
        - __meta_kubernetes_pod_label_name
      - action: drop
         regex: {{ namespace_name }}
         source_labels:
        - __meta_kubernetes_namespace
     [ .. default .. ]
```

Which feels very hacky and unsustainable, since we have to copy the default, modify it and then overwrite it. Is this intended behaviour?

**Comment by cyriltovena** [comment]
I guess it's because extraScrapeConfigs is at the end and not at the beginning ? It this was the problem I'm ok to receive a PR to move it to the top, because you're right if you want to drop targets this is useless.

Can you confirm that this was the problem ?

**Comment by robbertvdg** [comment]
I think that would solve the problem, will open an issue soon.

**Comment by cyriltovena** [comment]
You mean a PR ;)

**Comment by robbertvdg** [comment]
To clarify: the example on top is to exclude a namespace, we eventually wanted to exclude pod logs with: 
```
  - action: drop
    regex: application-controller
    source_labels:
    - __meta_kubernetes_pod_label_app
```
inside the existing kubernetes-pods-app scrape job. This did work. 
I tested yesterday with the extraScrapeConfigs on top, instead of at the bottom, but that did not seem to work. It feels to me like the kubernetes-pods-app job still picks it up. I am not too familiair with this, can you confirm this is the case?

**Comment by djmilosev** [comment]
@robbertvdg 

Were you able to exclude logs for a specific pod? I've tried with the following within the existing "kubernetes-pods-app" job but with no luck: 

`  - action: drop
    regex: application-controller
    source_labels:
    - __meta_kubernetes_pod_label_app`

Maybe you can share with me how your "kubernetes-pods-app" looks like? Thanks.

**Comment by djmilosev** [comment]
@robbertvdg 

Were you able to exclude logs for a specific pod? I've tried with the following within the existing "kubernetes-pods-app" job but with no luck:

`
  - action: drop
    regex: application-controller
    source_labels:
    - __meta_kubernetes_pod_label_app
`

Maybe you can share with me how your "kubernetes-pods-app" looks like? Thanks.

**Comment by robbertvdg** [comment]
Yes, it should work like this: 
```
    - job_name: kubernetes-pods-app
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: .+
        source_labels:
        - __meta_kubernetes_pod_label_name
     # custom code
      - action: drop
        regex: <pod app label>
        source_labels:
          - __meta_kubernetes_pod_label_app
     # custom code end
      - source_labels:
        - __meta_kubernetes_pod_label_app
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container_name
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
```

**Comment by djmilosev** [comment]
@robbertvdg 

Thanks, this seems to be working fine. 🥇

**Comment by cloudcafetech** [comment]
@robbertvdg

Can you please help me to create configuration to exclude multiple namespaces (kube-system,default)

**Comment by robbertvdg** [comment]
I haven't tested it, but the following code at the custom code block in my previous comment should work:

```
     - action: drop
        regex: kube-system
        source_labels:
          - __meta_kubernetes_namespace
     - action: drop
        regex: default
        source_labels:
          - __meta_kubernetes_namespace
```

**Comment by cloudcafetech** [comment]
NOT working :( 

Not sure if I missing anything, below my configuration ...

```
      - job_name: kubernetes-pods-app
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: drop
            regex: .+
            source_labels:
              - __meta_kubernetes_pod_label_name
          - action: drop
            regex: kube-system
            source_labels:
              - __meta_kubernetes_namespace
          - action: drop
            regex: logging
            source_labels:
              - __meta_kubernetes_namespace
          - action: drop
            regex: monitoring
            source_labels:
              - __meta_kubernetes_namespace
          - action: drop
            regex: tracing
            source_labels:
              - __meta_kubernetes_namespace
          - source_labels:
              - __meta_kubernetes_pod_label_app
            target_label: __service__
          - source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: __host__
          - action: drop
            regex: ""
            source_labels:
              - __service__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            replacement: $1
            separator: /
            source_labels:
              - __meta_kubernetes_namespace
              - __service__
            target_label: job
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
```

**Comment by dolisss** [comment]
@cloudcafetech Did it worked for you? I am facing the same issue.

**Comment by robbertvdg** [comment]
I think you should check for `__meta_kubernetes_pod_namespace` instead of `__meta_kubernetes_namespace`, since we are checking for pod logs in this job.

**Comment by cloudcafetech** [comment]
@dolisss 

Sorry for late reply.
No, my configuration didn't work, will try Robert latest configuration.
Meanwhile if you tried, please let me know.

Thanks in advance.

**Comment by dolisss** [comment]
@robbertvdg @cloudcafetech I tried using **__meta_kubernetes_pod_namespace** but I cannot see any changes, I am attaching my promtail.yaml file for your reference.  
[promtail.zip](https://github.com/grafana/loki/files/5535425/promtail.zip)

**Comment by cloudcafetech** [comment]
@robbertvdg 

Not working my end also.

@dolisss 

If you really wanted to exclude namespace then use fluent-bit Loki plugin instead of promtail

**Comment by norbertbodo91** [comment]
Hi there!

I found this issue since I was facing with it, was trying to drop logs from a specific namespace..
What I found out that, to use "_keep_" instead of "_drop_" (because in my case I was curious just for one namespace)
Also I had to overwrtie the default config in the helm chart values, here it is if someone wants to play with it:

Inserted code at:
```
    - job_name: kubernetes-pods-app
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: .+
        source_labels:
        - __meta_kubernetes_pod_label_name
      ###
      - action: keep
        regex: kube-system
        source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_namespace
      ###
```

Full config code:
```
scrapeConfigs:
  - job_name: kubernetes-pods-name
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels:
      - __meta_kubernetes_pod_label_name
      target_label: __service__
    - source_labels:
      - __meta_kubernetes_pod_node_name
      target_label: __host__
    - action: drop
      regex: ''
      source_labels:
      - __service__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - action: replace
      replacement: $1
      separator: /
      source_labels:
      - __meta_kubernetes_namespace
      - __service__
      target_label: job
    - action: replace
      source_labels:
      - __meta_kubernetes_namespace
      target_label: namespace
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_name
      target_label: pod
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_container_name
      target_label: container
    - replacement: /var/log/pods/*$1/*.log
      separator: /
      source_labels:
      - __meta_kubernetes_pod_uid
      - __meta_kubernetes_pod_container_name
      target_label: __path__
  - job_name: kubernetes-pods-app
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - action: drop
      regex: .+
      source_labels:
      - __meta_kubernetes_pod_label_name
    - action: keep
      regex: kube-system
      source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_namespace
    - source_labels:
      - __meta_kubernetes_pod_label_app
      target_label: __service__
    - source_labels:
      - __meta_kubernetes_pod_node_name
      target_label: __host__
    - action: drop
      regex: ''
      source_labels:
      - __service__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - action: replace
      replacement: $1
      separator: /
      source_labels:
      - __meta_kubernetes_namespace
      - __service__
      target_label: job
    - action: replace
      source_labels:
      - __meta_kubernetes_namespace
      target_label: namespace
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_name
      target_label: pod
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_container_name
      target_label: container
    - replacement: /var/log/pods/*$1/*.log
      separator: /
      source_labels:
      - __meta_kubernetes_pod_uid
      - __meta_kubernetes_pod_container_name
      target_label: __path__
  - job_name: kubernetes-pods-direct-controllers
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - action: drop
      regex: .+
      separator: ''
      source_labels:
      - __meta_kubernetes_pod_label_name
      - __meta_kubernetes_pod_label_app
    - action: drop
      regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
      source_labels:
      - __meta_kubernetes_pod_controller_name
    - source_labels:
      - __meta_kubernetes_pod_controller_name
      target_label: __service__
    - source_labels:
      - __meta_kubernetes_pod_node_name
      target_label: __host__
    - action: drop
      regex: ''
      source_labels:
      - __service__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - action: replace
      replacement: $1
      separator: /
      source_labels:
      - __meta_kubernetes_namespace
      - __service__
      target_label: job
    - action: replace
      source_labels:
      - __meta_kubernetes_namespace
      target_label: namespace
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_name
      target_label: pod
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_container_name
      target_label: container
    - replacement: /var/log/pods/*$1/*.log
      separator: /
      source_labels:
      - __meta_kubernetes_pod_uid
      - __meta_kubernetes_pod_container_name
      target_label: __path__
  - job_name: kubernetes-pods-indirect-controller
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - action: drop
      regex: .+
      separator: ''
      source_labels:
      - __meta_kubernetes_pod_label_name
      - __meta_kubernetes_pod_label_app
    - action: keep
      regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
      source_labels:
      - __meta_kubernetes_pod_controller_name
    - action: replace
      regex: '([0-9a-z-.]+)-[0-9a-f]{8,10}'
      source_labels:
      - __meta_kubernetes_pod_controller_name
      target_label: __service__
    - source_labels:
      - __meta_kubernetes_pod_node_name
      target_label: __host__
    - action: drop
      regex: ''
      source_labels:
      - __service__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - action: replace
      replacement: $1
      separator: /
      source_labels:
      - __meta_kubernetes_namespace
      - __service__
      target_label: job
    - action: replace
      source_labels:
      - __meta_kubernetes_namespace
      target_label: namespace
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_name
      target_label: pod
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_container_name
      target_label: container
    - replacement: /var/log/pods/*$1/*.log
      separator: /
      source_labels:
      - __meta_kubernetes_pod_uid
      - __meta_kubernetes_pod_container_name
      target_label: __path__
  - job_name: kubernetes-pods-static
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - action: drop
      regex: ''
      source_labels:
      - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_label_component
      target_label: __service__
    - source_labels:
      - __meta_kubernetes_pod_node_name
      target_label: __host__
    - action: drop
      regex: ''
      source_labels:
      - __service__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - action: replace
      replacement: $1
      separator: /
      source_labels:
      - __meta_kubernetes_namespace
      - __service__
      target_label: job
    - action: replace
      source_labels:
      - __meta_kubernetes_namespace
      target_label: namespace
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_name
      target_label: pod
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_container_name
      target_label: container
    - replacement: /var/log/pods/*$1/*.log
      separator: /
      source_labels:
      - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
      - __meta_kubernetes_pod_container_name
      target_label: __path__
```
Kubernetes version: v1.19.3

Hope it helps for someone,
Cheers

**Comment by cloudcafetech** [comment]
@norbertbodo91 

Though I have not tested yet, will do definitely.

From your statement ```to use "keep" instead of "drop" ``` does it means only ```kube-system``` namespace log can be appear rest namespaces logs will be drop.

**Comment by cloudcafetech** [comment]
Tested.. Not working :(

```
    scrape_configs:
      - job_name: kubernetes-pods-name
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels:
          - __meta_kubernetes_pod_label_name
          target_label: __service__
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ''
          source_labels:
          - __service__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __service__
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
      - job_name: kubernetes-pods-app
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: drop
          regex: .+
          source_labels:
          - __meta_kubernetes_pod_label_name
        - action: keep
          regex: kube-system
          source_labels:
            - __meta_kubernetes_namespace
            - __meta_kubernetes_pod_namespace
        - source_labels:
          - __meta_kubernetes_pod_label_app
          target_label: __service__
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ''
          source_labels:
          - __service__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __service__
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
      - job_name: kubernetes-pods-direct-controllers
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: drop
          regex: .+
          separator: ''
          source_labels:
          - __meta_kubernetes_pod_label_name
          - __meta_kubernetes_pod_label_app
        - action: drop
          regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
          source_labels:
          - __meta_kubernetes_pod_controller_name
        - source_labels:
          - __meta_kubernetes_pod_controller_name
          target_label: __service__
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ''
          source_labels:
          - __service__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __service__
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
      - job_name: kubernetes-pods-indirect-controller
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: drop
          regex: .+
          separator: ''
          source_labels:
          - __meta_kubernetes_pod_label_name
          - __meta_kubernetes_pod_label_app
        - action: keep
          regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
          source_labels:
          - __meta_kubernetes_pod_controller_name
        - action: replace
          regex: '([0-9a-z-.]+)-[0-9a-f]{8,10}'
          source_labels:
          - __meta_kubernetes_pod_controller_name
          target_label: __service__
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ''
          source_labels:
          - __service__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __service__
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
      - job_name: kubernetes-pods-static
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: drop
          regex: ''
          source_labels:
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_label_component
          target_label: __service__
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ''
          source_labels:
          - __service__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __service__
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container
        - replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
          - __meta_kubernetes_pod_container_name
          target_label: __path__
```

**Comment by yusufkaratoprak** [comment]
yes I have the same situation? It doesn't work . 

`config:
  lokiAddress: http://loki:3100/loki/api/v1/push
  snippets:
    common:
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - namespace
          - app
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        regex: true/(.*)
        separator: /
        source_labels:
          - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
          - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
    extraScrapeConfigs: |
      # Add an additional scrape config for ambassador
      - job_name: kubernetes-pods-name
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: drop
          regex: kube-system
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: ambassador
       `

**Comment by carlosmalucelli-mb** [comment]
@nothing5lose can you post your value here?

**Comment by nothing5lose** [comment]
> @nothing5lose can you post your value here?

I am using standart promtail Helmchart. Here is overrided values

```
config:
      lokiAddress: http://loki:3100/loki/api/v1/push
      snippets:
        scrapeConfigs: |
          # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
          - job_name: kubernetes-pods
            pipeline_stages:
              {{- toYaml .Values.config.snippets.pipelineStages | nindent 4 }}
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_namespace]
                action: drop
                regex: .+-system.*|.*loki.*
              - source_labels:
                  - __meta_kubernetes_pod_controller_name
                regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                action: replace
                target_label: __tmp_controller_name
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_name
                  - __meta_kubernetes_pod_label_app
                  - __tmp_controller_name
                  - __meta_kubernetes_pod_name
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: app
              - source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_component
                  - __meta_kubernetes_pod_label_component
                regex: ^;*([^;]+)(;.*)?$
                action: replace
                target_label: component
              {{- if .Values.config.snippets.addScrapeJobLabel }}
              - replacement: kubernetes-pods
                target_label: scrape_job
              {{- end }}
              {{- toYaml .Values.config.snippets.common | nindent 4 }}
              {{- with .Values.config.snippets.extraRelabelConfigs }}
              {{- toYaml . | nindent 4 }}
              {{- end }}
```

**Comment by zakkg3** [comment]
Summary for newcomers here:

to skip a namespace from your loki-stack helm-deployed promtail edit your values file:

```
  promtail:
    enabled: true
    config:
      snippets:
        extraRelabelConfigs:
          - source_labels: [__meta_kubernetes_namespace]
            action: drop
            regex: cilium
 ```
 
 reeplace cilium with your namespace regex.
