### ISSUE TITLE
Add an option to use on demand Dynamodb

### ISSUE THREAD

**Issue by stijndehaes** [grafana/loki#2079]
**Is your feature request related to a problem? Please describe.**
I want to be able to use loki without running prometheus for autoscaling the DynamoDB. By using on the Demand DynamoDB options I can be sure my grafana loki keeps on working without me worying about write and read capacity.
Also the application-autoscaling for DynamoDB is hard to configure and is becoming unsupported in cortex: https://github.com/grafana/loki/issues/1267#issuecomment-576038806.

**Describe the solution you'd like**
I would like the options to provision the DynamoDB tables with on Demand instead of using provisioned read/write capacity.

**Describe alternatives you've considered**
Application autoscaling

**Additional context**
None

I am ok with implementing this myself by the way. Just want to make sure that you would accept this PR.

**Comment by patrickjahns** [comment]
@stijndehaes 
This is already working - here is a config I am using with with loki 1.4.1

```
table_manager:
  creation_grace_period: 3h
  retention_deletes_enabled: false
  retention_period: 0
  chunk_tables_provisioning:
    provisioned_throughput_on_demand_mode: true
    inactive_throughput_on_demand_mode: true
    provisioned_write_throughput: 0
    provisioned_read_throughput: 0
    inactive_write_throughput: 0
    inactive_read_throughput: 0
  index_tables_provisioning:
    provisioned_throughput_on_demand_mode: true
    inactive_throughput_on_demand_mode: true
    provisioned_write_throughput: 0
    provisioned_read_throughput: 0
    inactive_write_throughput: 0
    inactive_read_throughput: 0
```

The flags here are taken from cortex 0.7 https://github.com/cortexproject/cortex/blob/v0.7.0/docs/configuration/config-file-reference.md 

With the next version of loki the config values will change, as cortex has renamed quite a few parameters in 1.0.0
