### ISSUE TITLE
Promtail to set journal target symbolic priority

### ISSUE THREAD

**Issue by gtrubach** [grafana/loki#2084]
Hi!

**Is your feature request related to a problem? Please describe.**
I want to display journal logs in grafana by using promtail and loki. Promtail extracts logs fine but journal contains priority in number format, not symbolic. So if I use the following scrape config:

```
- job_name: systemd-journal
  journal:
    max_age: 12h
    labels:
      job: systemd-journal
    path: /var/log/journal
  relabel_configs:
  - source_labels:
    - __journal__systemd_unit
    target_label: systemd_unit
  - source_labels:
    - __journal_priority
    target_label: level
```
`level` will be numeric and grafana will show unknown log level for it.

**Describe the solution you'd like**
It would be great if numeric priority will be transformed to symbolic as it's done for [syslog target](https://github.com/grafana/loki/blob/f0f6f249265c8725dd9909b190b54dbbb96faa08/pkg/promtail/targets/syslogtarget.go#L184). In this case I will be able to map it to level label which can be read by grafana and shown correctly.

**Describe alternatives you've considered**
I tried to set it up using pipelines but I wasn't successful in it.

**Additional context**
Note the level label (6 is an info):
![image](https://user-images.githubusercontent.com/10942688/82117850-c596fe00-977b-11ea-9c82-8b21ac817a10.png)

**Comment by gtrubach** [comment]
It still will be cool to have it out of the box, but I managed to do a workaround using pipeline stage:

```
pipeline_stages:
- job_name: systemd-journal
  journal:
    max_age: 12h
    labels:
      job: systemd-journal
    path: /var/log/journal
  relabel_configs:
  - source_labels:
    - __journal__systemd_unit
    target_label: systemd_unit
  - source_labels:
    - __journal_priority
    target_label: level
  pipeline_stages:
  - template:
      source: level
      template: '{{ if eq .Value "0" }}{{ Replace .Value "0" "emerg" 1 }}{{ else if eq .Value "1" }}{{ Replace .Value "1" "alert" 1 }}{{ else if eq .Value "2" }}{{ Replace .Value "2" "crit" 1 }}{{ else if eq .Value "3" }}{{ Replace .Value "3" "err" 1 }}{{ else if eq .Value "4" }}{{ Replace .Value "4" "warning" 1 }}{{ else if eq .Value "5" }}{{ Replace .Value "5" "notice" 1 }}{{ else if eq .Value "6" }}{{ Replace .Value "6" "info" 1 }}{{ else if eq .Value "7" }}{{ Replace .Value "7" "debug" 1 }}{{ end }}'
  - labels:
      level:
```
