### ISSUE TITLE
Canary 401 error when using production gateway

### ISSUE THREAD

**Issue by codewithcheese** [grafana/loki#2094]
**Describe the bug**
Canary fails connect to /api/prom/tail websocket via the nginx gateway with error `failed to connect to ws://loki-gateway.product-os.svc.cluster.local/api/prom/tail?query=%7Bstream%3D%22stdout%22%2Cname%3D%22loki-canary%22%7D with err websocket: bad handshake`    

nginx logs `[19/May/2020:15:44:51 +0000]  401 "GET /api/prom/tail?query=%7Bstream%3D%22stdout%22%2Cname%3D%22loki-canary%22%7D HTTP/1.1" 10 "-" "Go-http-client/1.1" "-"`
Don't understand how it could be a 401 Unauthorized error `auth_basic` is not being used.

**To Reproduce**
1. Loki 1.4.1 based on the ksonnet production config
2. Loki-canary 1.4.1 with -address argument point at nginx gateway

**Expected behavior**
Except canary to successful tail using websocket via nginx

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: yamls based on `tk show` with label, annotation, resource customization

**deployment-canary**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "false"
  labels:
    app.kubernetes.io/name: canary
    app.kubernetes.io/instance: canary
    app.kubernetes.io/part-of: loki
  name: canary
  namespace: product-os
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: canary
      app.kubernetes.io/instance: canary
      app.kubernetes.io/part-of: loki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: canary
        app.kubernetes.io/instance: canary
        app.kubernetes.io/part-of: loki
    spec:
      containers:
        - args:
            - -addr=loki-gateway.product-os.svc.cluster.local
          image: grafana/loki-canary:1.4.1
          imagePullPolicy: IfNotPresent
          name: loki-canary
          resources: {}
          ports:
            - containerPort: 3500
              name: prometheus
```

**gateway-configmap.yml**
```
apiVersion: v1
data:
  nginx.conf: |
    worker_processes  5;  ## Default: 1
    error_log  /dev/stderr;
    pid        /tmp/nginx.pid;
    worker_rlimit_nofile 8192;

    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      default_type application/octet-stream;
      log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log   /dev/stderr  main;
      sendfile     on;
      tcp_nopush   on;
      resolver kube-dns.kube-system.svc.cluster.local;

      server {
        listen               80;
        proxy_set_header     X-Scope-OrgID 1;

        location = /api/prom/push {
          proxy_pass       http://loki-distributor.product-os.svc.cluster.local:3100$request_uri;
        }

        location = /api/prom/tail {
          proxy_pass       http://loki-querier.product-os.svc.cluster.local:3100$request_uri;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }

        location ~ /api/prom/.* {
          proxy_pass       http://loki-query-frontend.product-os.svc.cluster.local:3100$request_uri;
        }

        location = /loki/api/v1/push {
          proxy_pass       http://loki-distributor.product-os.svc.cluster.local:3100$request_uri;
        }

        location = /loki/api/v1/tail {
          proxy_pass       http://loki-querier.product-os.svc.cluster.local:3100$request_uri;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
        }

        location ~ /loki/api/.* {
          proxy_pass       http://loki-query-frontend.product-os.svc.cluster.local:3100$request_uri;
        }
      }
    }
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: product-os
```
