### ISSUE TITLE
Promtail configuration changed in 1.5.0 but isnt covered in release notes or upgrade docs

### ISSUE THREAD

**Issue by chancez** [grafana/loki#2102]
**Describe the bug**
When upgrading promtail from 1.4.0 to 1.5.0 I saw the following errors at startup:

```
Unable to parse config: /etc/promtail/promtail.yaml: yaml: unmarshal errors:
  line 3: field maxbackoff not found in type util.BackoffConfig
  line 4: field maxretries not found in type util.BackoffConfig
  line 5: field minbackoff not found in type util.BackoffConfig
```

This seems to be related to the cortex 1.0 version upgrade. The upgrade docs and release notes mention this for Loki but it's not as obvious that this could also effect promtail.

**To Reproduce**
1. Started Promtail 1.4.0 with config from 1.3.0
2. Promtail exits on starrtup

**Expected behavior**
Simply mention that promtail's configuration also requires migrations before upgrading to 1.5.0 in the release notes and upgrade documentation.

**Comment by jmvizcainoio** [comment]
Hi, same as me.

Updating from 1.4.1 to 1.5.0 using the chart `loki-stack` 0.37.2 

in values.yaml 

```
  config:
    client:
      # Maximum wait period before sending batch
      batchwait: 1s
      # Maximum batch size to accrue before sending, unit is byte
      batchsize: 102400

      # Maximum time to wait for server to respond to a request
      timeout: 10s

      backoff_config:
        # Initial backoff time between retries
        minbackoff: 100ms
        # Maximum backoff time between retries
        maxbackoff: 5s
        # Maximum number of retires when sending batches, 0 means infinite retries
        maxretries: 5
```
