### ISSUE TITLE
Loki docker driver can not push to server. Gives 404 errors.

### ISSUE THREAD

**Issue by pgrond** [grafana/loki#2108]
I've configured the docker daemon to send all docker logs to my Loki server. I've also a promtail container running, wit the same endpoint, and those logs get pushed to loki without a problem.
The docker logs are not received though.

**To Reproduce**

1. Install Loki docker driver and check status
ID                  NAME                DESCRIPTION           ENABLED
1949660d95d7        loki:latest         Loki Logging Driver   true

2. Configure docker daemon to use Loki driver
```
{
    "debug" : true,
    "log-driver": "loki",
    "log-opts": {
        "loki-url": "https://loki.mydomain.nl:3100/loki/api/v1/push",
        "loki-batch-size": "400"
    }
}
```

3. Restart docker daemon
`systemctl restart docker`

**Expected behavior**
See the docker logs in Grafana. But no logs are collected.
I can see in the syslog messages like:

ubuntu-8gb-nbg1-1 dockerd[29464]: time="2020-05-21T16:26:21+02:00" level=info msg="level=error ts=2020-05-21T14:26:21.051575851Z caller=client.go:247 container_id=5edb13014e9a770c00bc4510883e30ff9ff108fd76de26aec271da83302c8539 component=client host=loki.mydomain.nl msg=\"final error sending batch\" status=404 error=\"server returned HTTP status 404 Not Found (404): 404 page not found\"" plugin=1949660d95d7235dccf4c319f34d8178f2d6a706b741b37abca66548cca5e7ac

Promtail works just fine with this config:
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://loki.mydomain.nl:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  pipeline_stages:
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: journal
  pipeline_stages:
  journal:
    path: /var/log/journal
    labels:
      job: systemd-journal
  relabel_configs:
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'
```

Am I missing something? As far as I can see I followed the documentation on https://github.com/grafana/loki/tree/v1.5.0/docs/clients/docker-driver

**Environment:**
All dockers run with docker compose files, no Kubernetes
