### ISSUE TITLE
How to form pipeline_stages for custom logs

### ISSUE THREAD

**Issue by Priyanka098** [grafana/loki#2110]
I have deployed promtail in kubernetes cluster using helm chart. The default scrape [config](https://github.com/grafana/loki/blob/master/production/helm/promtail/templates/configmap.yaml)
 Now i want to create labels based on logs. Following is the extraScrapeConfigs for promtail
          
2020-05-22 07:58:54.766 INFO 1 --- [mm-logging-info] c.s.x.v.LoggingApplication : topic: xzy, msg: {data: data }

Following is the config for log 

``` 
  extraScrapeConfigs:  
    - job_name: logs  
      kubernetes_sd_configs:                                                                                      
      - role: pod
      pipeline_stages:
        - match:
            selector: "{name=\"containername\"}"
            stages:
              - json:
                  expressions:
                    timestamp: timestamp
                    data: data
              - labels:
                  data:
                  timestamp:
```

The "logs" job is not working and i couldnt see the debug logs for this in promtail pod
