### ISSUE TITLE
(feat): Support for environment variables in loki.yaml config

### ISSUE THREAD

**Issue by lukasmrtvy** [grafana/loki#2128]
**Is your feature request related to a problem? Please describe.**
Would be great to support env vars in loki.yaml, its antipattern to have hardcoded credentials in loki.yaml config.

And this method https://github.com/grafana/loki/blob/master/docs/configuration/examples.md#aws 
_If you don't wish to hard-code S3 credentials, you can also configure an EC2 instance role_ 
is AWS (s3,dynamodb) specifc.

**Describe the solution you'd like**
Use special parsable format `${ENV#<env-var>}` in loki.yaml config.
For example:
```
schema_config:
  configs:
  - from: 2020-05-15
    store: aws
    object_store: s3
    schema: v11
    index:
      prefix: loki_
storage_config:
  aws:
    s3: s3://access_key:${ENV#SECRET_ACCESS_KEY_S3}@region/bucket_name
    dynamodb:
      dynamodb_url: dynamodb://access_key:${ENV#SECRET_ACCESS_KEY_DYNAMODB}@region
```

**Describe alternatives you've considered**
Templating loki.yaml config

**Additional context**
None

Thanks

**Comment by codewithcheese** [comment]
AWS config can be loaded with env var, we successfully do that.

```
env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY
              name: loki
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_KEY
              name: loki
        - name: AWS_SDK_LOAD_CONFIG
          value: "1"
```
