### ISSUE TITLE
Promtail and fluent bit both not scrapping any logs to loki

### ISSUE THREAD

**Issue by Srikanthshetty** [grafana/loki#2129]
**Describe the bug**
Installed loki stack with promtail and fluent-bit with helm , both agents are not able to push logs to loki.

**To Reproduce**
 helm upgrade --install loki --namespace=loki-stack loki/loki-stack  --set fluent-bit.enabled=true,promtail.enabled=false,loki.persistence.enabled=true,loki.persistence.size=10Gi,loki.persistence.storageClassName=thin-disk 

![image](https://user-images.githubusercontent.com/19268128/82847842-5f6a5380-9ebe-11ea-8998-df8e3ce8d96b.png)

**Expected behavior**
Expected logs to pushed to grafana loki either from promtail or fluent-bit. 

![image](https://user-images.githubusercontent.com/19268128/82847864-7dd04f00-9ebe-11ea-9ed0-de892996b8f9.png)

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]: Kubernetes :- Enterprise PKS (Pivotal K8s service) , 4 worker nodes 
 - Deployment tool: [e.g., helm, jsonnet]: helm 3

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

Promtail kubernetes description  : 

> Readiness probe failed: HTTP probe failed with statuscode: 500 

Promtail running logs : 
> level=info ts=2020-05-25T22:20:22.771097546Z caller=filetargetmanager.go:270 msg="Adding target" key="{app=\"loki\", container_name=\"loki\", controller_revision_hash=\"loki-58d64cc74c\", instance=\"loki-0\", job=\"loki-stack/loki\", name=\"loki\", namespace=\"loki-stack\", release=\"loki\", statefulset_kubernetes_io_pod_name=\"loki-0\"}"
level=error ts=2020-05-25T22:20:22.771290291Z caller=filetarget.go:283 msg="failed to tail file, stat failed" error="stat /var/log/pods/loki-stack_loki-0_f998668d-f077-4a80-9b1b-4e55b46fa9f6/loki/0.log: no such file or directory" filename=/var/log/pods/loki-stack_loki-0_f998668d-f077-4a80-9b1b-4e55b46fa9f6/loki/0.log

Service discovery and targets of promtail :

![image](https://user-images.githubusercontent.com/19268128/82847639-3eedc980-9ebd-11ea-8cc8-603d204c340c.png)

![image](https://user-images.githubusercontent.com/19268128/82847650-50cf6c80-9ebd-11ea-9c45-1a70d38a7d0f.png)

fluent-bit running logs :

> Fluent Bit v1.2.2
> Copyright (C) Treasure Data
> 
> [2020/05/25 22:11:57] [ info] [storage] initializing...
> [2020/05/25 22:11:57] [ info] [storage] in-memory
> [2020/05/25 22:11:57] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
> [2020/05/25 22:11:57] [ info] [engine] started (pid=1)
> [2020/05/25 22:11:57] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
> [2020/05/25 22:11:57] [ info] [filter_kube] local POD info OK
> [2020/05/25 22:11:57] [ info] [filter_kube] testing connectivity with API server...
> [2020/05/25 22:11:57] [ info] [filter_kube] API server connectivity OK
> [2020/05/25 22:11:57] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
> [2020/05/25 22:11:57] [ info] [sp] stream processor started

**Comment by cyriltovena** [comment]
The problem with Promtail is that the config you're using (the default one) does not fit your environment, it seems that Pivotal is storing long somewhere else.

You have to fix the `__path__` labels in the scrape config.

**Comment by Srikanthshetty** [comment]
Thanks for the suggestion , indeed PKS as different path for logs . I am able to scrape logs using following changes in Daemonset. 

promtail-ds.yaml
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
      annotations:
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: promtail
          image: "grafana/promtail:1.5.0"
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
            - "-client.url=http://loki:3100/loki/api/v1/push"
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: run
              mountPath: /run/promtail
            - mountPath: /var/lib/docker/containers
              name: docker
              readOnly: true
            - mountPath: /var/log/pods
              name: pods
              readOnly: true
            - mountPath: /var/vcap/store
              name: varvcap
              readOnly: true
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 3101
              name: http-metrics
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 0
            runAsUser: 0
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      volumes:
        - name: config
          configMap:
            name: promtail
        - name: run
          hostPath:
            path: /run/promtail
        - hostPath:
            path: /var/lib/docker/containers
          name: docker
        - hostPath:
            path: /var/log/pods
          name: pods
        - hostPath:
            path: /var/vcap/store
          name: varvcap
```

**Adding volume path /var/vcap/store fixed the issue**

Problem i see is now only few namespace pods getting pushed to loki . Dont know why it is not scraping all namespaces , i can see in logs it is identifing all pods.

<img width="384" alt="Promtail-servicediscovery" src="https://user-images.githubusercontent.com/19268128/83882877-b7038d00-a710-11ea-9eed-ad952ebd88ad.PNG">

<img width="376" alt="promtail-targets" src="https://user-images.githubusercontent.com/19268128/83882968-db5f6980-a710-11ea-8998-0bb7997c6ee4.PNG">

Please find the logs in promtail 

`
level=warn ts=2020-06-05T13:24:23.514778148Z caller=filetargetmanager.go:98 msg="WARNING!!! entry_parser config is deprecated, please change to pipeline_stages"
level=info ts=2020-06-05T13:24:23.515200967Z caller=kubernetes.go:190 component=discovery discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-06-05T13:24:23.518916666Z caller=server.go:179 http=0.0.0.0:3101 grpc=0.0.0.0:9095 msg="server listening on addresses"
level=info ts=2020-06-05T13:24:23.51915927Z caller=main.go:67 msg="Starting Promtail" version="(version=1.5.0, branch=HEAD, revision=12c7eab8b)"
level=info ts=2020-06-05T13:24:28.516983754Z caller=filetargetmanager.go:270 msg="Adding target" key="{container=\"coredns\", job=\"kube-system/\", k8s_app=\"kube-dns\", namespace=\"kube-system\", pod=\"coredns-5b6649768f-7jmp4\", pod_template_hash=\"5b6649768f\"}"
level=info ts=2020-06-05T13:24:28.517686619Z caller=tailer.go:80 component=tailer msg="start tailing file" path=/var/log/pods/kube-system_coredns-5b6649768f-7jmp4_1d44e865-0742-4ee3-98ba-25672eb0f27e/coredns/0.log
ts=2020-06-05T13:24:28.517796815Z caller=log.go:124 component=tailer level=info msg="Seeked /var/log/pods/kube-system_coredns-5b6649768f-7jmp4_1d44e865-0742-4ee3-98ba-25672eb0f27e/coredns/0.log - &{Offset:671 Whence:0}"
level=info ts=2020-06-05T13:24:28.518572201Z caller=filetargetmanager.go:270 msg="Adding target" key="{app=\"telegraf\", container=\"telegraf\", controller_revision_hash=\"7bf89cdf54\", job=\"pks-system/\", namespace=\"pks-system\", pod=\"telegraf-jxqmn\", pod_template_generation=\"1\"}"
level=info ts=2020-06-05T13:24:28.518836481Z caller=tailer.go:80 component=tailer msg="start tailing file" path=/var/log/pods/pks-system_telegraf-jxqmn_a76c05fc-32f9-4545-a2f8-9372f9c48f33/telegraf/0.log
ts=2020-06-05T13:24:28.518858682Z caller=log.go:124 component=tailer level=info msg="Seeked /var/log/pods/pks-system_telegraf-jxqmn_a76c05fc-32f9-4545-a2f8-9372f9c48f33/telegraf/0.log - &{Offset:1075 Whence:0}"
ts=2020-06-05T13:24:28.570156935Z caller=log.go:124 component=tailer level=info msg="Seeked /var/log/pods/issp_portal-deployment-54bd8fdcbf-6tb95_50d90f07-c8d7-46eb-9623-e45d45cf4a57/portal-app/0.log - &{Offset:242 Whence:0}"
level=info ts=2020-06-05T13:24:28.570208913Z caller=tailer.go:80 component=tailer msg="start tailing file" path=/var/log/pods/issp_portal-deployment-54bd8fdcbf-6tb95_50d90f07-c8d7-46eb-9623-e45d45cf4a57/portal-app/0.log
level=info ts=2020-06-05T13:24:28.52349622Z caller=filetargetmanager.go:270 msg="Adding target" key="{app=\"mysql\", container=\"portaldb\", controller_revision_hash=\"portaldb-64f4fcb859\", job=\"portal-db/\", namespace=\"portal-db\", pod=\"portaldb-2\", statefulset_kubernetes_io_pod_name=\"portaldb-2\"}"

`
As seen in logs pods like **tailing file" path=/var/log/pods/issp_portal-deployment-54bd8fdcbf-6tb95_50d90f07-c8d7-46eb-9623-e45d45cf4a57/portal-app/0.log** is not getting pushed to loki. 

Currently i am using only one scrap job

```
scrape_configs:
    - job_name: kubernetes-pods-name
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: pks-system
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
```
is there anything i am missing here?
