### ISSUE TITLE
promtail: failed to parse time

### ISSUE THREAD

**Issue by alexey-gusarov** [grafana/loki#2130]
**Describe the bug**
I have a lot of messages 
`level=debug ts=2020-05-26T04:10:14.3635433Z caller=timestamp.go:179 component=file_pipeline msg="failed to parse time" err="parsing time \"2020-05-26 04:08:14.158 \": extra text:  " format="2006-01-02 15:04:05.999" value="2020-05-26 04:08:14.158 " `

I've check in go, it's ok:
```
	t, err := time.Parse("2006-01-02 15:04:05.999", "2020-05-26 14:08:14.158")
	fmt.Println("error", err)
	fmt.Println(t)
```
result:
```
error <nil>
2020-05-26 04:08:14.158 +0000 UTC
```

**To Reproduce**
1. Started Promtail 1.5 in dry-run

**Expected behavior**
Parsing timestamps by format from config

**Environment:**
 - windows 10

**Screenshots, Promtail config, or terminal output**
```
scrape_configs:
  - job_name: my-services-logs
    pipeline_stages:
      - regex: #2020-05-24 14:08:20.738 [DBG <1> ] UnpackAndVerifyCmsMessage, cmsMessage size=3045.
          expression: '^(?P<timestamp>[\d-\s:.]{20,30})\s*\[(?P<level>[a-zA-Z]+)\s'
      - labels:
          level:
      - timestamp:
          format: "2006-01-02 15:04:05.999"
          source: timestamp
          action_on_failure: fudge
```
