### ISSUE TITLE
Unable to parse timestamp in Loki

### ISSUE THREAD

**Issue by falcon97** [grafana/loki#2145]
**Describe the bug**
I am unable to parse my custom timestamp in Loki. I have verified it in Go and I do not get any errors regarding timestamp parsing in Promtail logs.

Sample part of log:
```
May 27, 2020 11:11:17 AM, Info                  CBS    Ending TrustedInstaller initialization.
May 27, 2020 11:11:17 AM, Info                  CBS    Starting the TrustedInstaller main loop.
May 27, 2020 11:11:17 AM, Info                  CBS    TrustedInstaller service starts successfully.
```

Golang code:
```
const longForm = "Jan 02, 2006 3:04:05 PM"
t, err := time.Parse(longForm,"Apr 24, 2020 6:17:10 PM")
fmt.Println(t)
fmt.Println(err)
```
Output:
```
2020-04-24 18:17:10 +0000 UTC
<nil>
```

**To Reproduce**
1. Started Loki 1.5.0
2. Started Promtail 1.5.0
3. Queried a file configured in the Promtail's config file.

**Expected behavior**
Display the log with the timestamp available in it, instead of displaying the timestamp at which the log was scraped by Promtail.

**Environment:**
Laptop running Ubuntu.

**Screenshots, Promtail config, or terminal output**
Promtail config:
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
- job_name: serviceLogs
  pipeline_stages:
  - regex:
      expression: '^(?P<time>\w{3}\s+\d{1,2},\s+\d{4}\s\d{1,2}:\d{1,2}:\d{1,2}\s[AP]M)'
  - timestamp:
      source: time
      format: "Jan 02, 2006 3:04:05 PM"
  static_configs:
  - targets:
      - localhost
    labels:
        __path__: "/media/sf_Logs/Service Logs/**"
        job: serviceLogs
```
