### ISSUE TITLE
Retention period should now be a multiple of periodic table duration

### ISSUE THREAD

**Issue by uhthomas** [grafana/loki#2151]
**Describe the bug**
Cannot create a fresh instance of Loki when specifying retention in the helm chart.

**To Reproduce**
1. Create a new Helm release and PVC
2. Apply the manifests
3. Check the logs

**Expected behavior**
Loki should startup normally and adhere to the retention period.

**Environment:**
 - Infrastructure: Kubernetes v1.17.5
 - Deployment tool: Flux and Helm operator v1.0.2

**Screenshots, Promtail config, or terminal output**

Helm release and PVC:
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: grafana
spec:
  releaseName: loki
  chart:
    repository: https://grafana.github.io/loki/charts
    name: loki
    version: 0.29.0
  values:
    persistence:
      enabled: true
    config:
      chunk_store_config:
        max_look_back_period: 720h
      table_manager:
        retention_deletes_enabled: true
        retention_period: 720h
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki
  namespace: grafana
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
```

Logs:
```
➜  ~ kubectl -n grafana logs loki-0 loki
level=info ts=2020-05-29T21:14:39.625097812Z caller=server.go:179 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=error ts=2020-05-29T21:14:39.625400562Z caller=log.go:140 msg="error initialising loki" err="retention period should now be a multiple of periodic table duration\nerror initialising module: table-manager\ngithub.com/grafana/loki/pkg/loki.(*Loki).initModuleServices\n\t/src/loki/pkg/loki/loki.go:194\ngithub.com/grafana/loki/pkg/loki.New\n\t/src/loki/pkg/loki/loki.go:134\nmain.main\n\t/src/loki/cmd/loki/main.go:76\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"
```
