### ISSUE TITLE
Data lost while flushing to Dynamo DB

### ISSUE THREAD

**Issue by dragonsmith** [grafana/loki#2153]
**Describe the bug**
I'm running Loki on AWS EKS 1.16 cluster with DynamoDB configured for indexes and chunks. Loki produces error messages like

> level=warn ts=2020-05-30T02:10:40.786685462Z caller=dynamodb_storage_client.go:253 msg="Data lost while flushing to Dynamo" err="ValidationException: 1 validation error detected: Value '{=[WriteRequest(putRequest=PutRequest(item={h=AttributeValue(s=fake/1189bac5e87fc5de:1726355b2a7:1726355b2a8:823ae89d, n=null, b=null, sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null), r=AttributeValue(s=null, n=null, b=java.nio.HeapByteBuffer[pos=0 lim=1 cap=1], sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null), c=AttributeValue(s=null, n=null, b=java.nio.HeapByteBuffer[pos=0 lim=669 cap=669], sS=null, nS=null, bS=null, m=null, l=null, nULL=null, bOOL=null)}), deleteRequest=null)]}' at 'requestItems' failed to satisfy constraint: Map keys must satisfy constraint: [Member must have length less than or equal to 255, Member must have length greater than or equal to 3, Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+]\n\tstatus code: 400, request id: 69Q3DPHVE11JU5537A5GTOUDLFVV4KQNSO5AEMVJF66Q9ASUAAJG"

Some of my log messages are definitely missing.

**To Reproduce**

0. AWS EKS 1.16
1. Loki v1.5.0 (installed using Helm chart v0.29.0)
2. Promtail v1.4.1 (installed using Helm chart v0.22.2)
3. DynamoDB as backend for both chunks and indexes

custom helm values:
```yaml
config:
  limits_config:
    reject_old_samples_max_age: 48h
  schema_config:
    configs:
    - from: "2020-05-15"
      index:
        period: 168h
        prefix: loki_production_
      object_store: aws-dynamo
      schema: v11
      store: aws
  storage_config:
    aws:
      dynamodb:
        dynamodb_url: dynamodb://eu-west-1
  table_manager:
    chunk_tables_provisioning:
      enable_inactive_throughput_on_demand_mode: true
      enable_ondemand_throughput_mode: true
    index_tables_provisioning:
      enable_inactive_throughput_on_demand_mode: true
      enable_ondemand_throughput_mode: true
    retention_deletes_enabled: true
    retention_period: 168h
```

**Expected behavior**

Store all log messages without data loss.

**Environment:**
 - Infrastructure: EKS 1.16
 - Deployment tool: Helm chart 
 - Storage backend: DynamoDB

Thank you for your help!
