### ISSUE TITLE
field replication_factor not found in type distributor.RingConfig ??

### ISSUE THREAD

**Issue by samcaek** [grafana/loki#2173]
There seems to be an issue with setting `replication_factor` in the distributor section of the config file.

Here is the distributor section I am using:
```
distributor: 
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1
```

The resulting error is: 
`failed parsing config: /etc/loki/config.yaml: yaml: unmarshal errors: 
  line 51: field replication_factor not found in type distributor.RingConfig`

If I remove the replication_factor value, Loki starts as expected by setting the replication_factor to the default value of 3. 
```
distributor: 
  ring:
    kvstore:
      store: inmemory
```

Thoughts?

**Comment by adityacs** [comment]
@samcaek `replication_factor` should be set in `ingester`. Try this

```yaml
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
```
