### ISSUE TITLE
Promtail - Document the need to mount the EKS logs symlink architecture

### ISSUE THREAD

**Issue by ikerperezdelpalomar** [grafana/loki#2180]
**Is your feature request related to a problem? Please describe.**
I deployed the very same cluster in [kind](https://kind.sigs.k8s.io/), [minikube](https://kubernetes.io/docs/tasks/tools/install-minikube/) and [aws EKS](https://aws.amazon.com/eks/), however I only achieved to discover the targets in the cluster deployed in kind. After checking promtail logs, I discovered that for some reason the logs stored in `/var/log/pods` even it were found couldn't be read because an error message was complainging that they didn't exist. So I came to the conclusion that there was a sylinking error somewhere and after asking in grfana slack channel I discovered that The logs in `/var/log/pods` are symlinks to `/var/lib/docker/containers` on the EKS and minikube. Therefore the next code needs to be added:

```
volumeMounts:
- name: varlibdockercontainers
  mountPath: /var/lib/docker/containers
  readOnly: true
```
```
volumes:
- name: varlibdockercontainers
  hostPath:
    path: /var/lib/docker/containers
```

**Describe the solution you'd like**
I would like to include information about the changes needed to make promtail work in those two environments. I am not sure where this information should be added, my options are:
*   Add it at the end of [promtail/configuration.md](https://github.com/grafana/loki/blob/master/docs/clients/promtail/configuration.md). Create a new section called "configure promtail for EKS" or something similar.
*   Add it as a comment in [promtail/values.yaml](https://github.com/grafana/loki/blob/bedab491ac1a262570f5a56996ea97d85a7df4f6/production/helm/promtail/values.yaml#L101)
