### ISSUE TITLE
Promtail - Error - at least one client config should be provided

### ISSUE THREAD

**Issue by darox** [grafana/loki#2194]
I have just started with promtail and loki with docker. My promtail config is:

```
server:
   http_listen_port: 9080
   grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://172.19.0.107:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
```

The container fails just after starting with:

`level=error ts=2020-06-08T08:20:15.859761174Z caller=main.go:63 msg="error creating promtail" error="at least one client config should be provided"`

Promtail docker deploy command:

```
docker run -d \
-v /var/log:/var/log \
-v /storage/docker/promtail/etc/config.yml:/etc/promtail/config.yml \
--restart=always \
--name=prod-promtail \
--net prod-network --ip 172.19.0.108 \
grafana/promtail:master
```

I am missing something?
