### ISSUE TITLE
Loki random 500 with "unrecognised chunkTimeRangeKey" error

### ISSUE THREAD

**Issue by xmackex** [grafana/loki#2200]
**Describe the bug**

Loki randomly throws `500` error using BoltDB index with message
```
unrecognised chunkTimeRangeKey version
```

Issue happens few times in 24h for 30-60 seconds, than all good.

**Details**
* Unfortunately debug log haven't showed anything that could help to resolve the issue.
* No log lines/streams/chunks spike detected.
* No CPU/Mem spikes happened
* Promtail `dropped_bytes` metric if fine (nothing dropped)
* I have quite big label cardinality (which I'm trying to decrease)
* No OOM killed processes found in `syslog`
* This issue have not happened while using DynamoDB
* index key shows no values (checked with [boltdbweb](https://github.com/evnix/boltdbweb))

**To Reproduce**
1. Started Loki (1.4.1). Same with `1.5.0`
2. Started Promtail `d08ceef1`
3. Query: Any query from Grafana

**Expected behavior**

No random `500` errors

**Environment:**
 - Infrastructure: Bare-metal Loki (on AWS EC2) in docker container with mounted folder for index store
 - S3 as chunk storage

**Screenshots, Promtail config, or terminal output**

Loki schema config
```
schema_config:
  configs:
    - from: 2020-06-03
      store: boltdb
      object_store: s3
      schema: v11
      index:
        prefix: loki-index-us-west-2-
        period: 168h # 7 days
```

Loki log:
```
level=warn ts=2020-06-08T20:15:12.669224855Z caller=logging.go:49 traceID=48ea30cf6b34c2d7 msg="POST /loki/api/v1/query_range (500) 90.310535ms Response: \"unrecognised chunkTimeRangeKey version: \\\"fake/sdaksfnsdg23f436:172wer5f925:17292j5f926:bedber92\\\"\\n\" ws: false; Accept-Encoding: gzip; Connection: close; Content-Length: 275; Content-Type: application/x-www-form-urlencoded; User-Agent: Go-http-client/1.1; X-Forwarded-For: 10.254.4.12; X-Forwarded-Proto: https; X-Real-Ip: 10.254.4.12; "
```
_chunk name changed_

Chunk exists in S3 bucket
