### ISSUE TITLE
Loki deletes all indeces on index configuration change

### ISSUE THREAD

**Issue by Kristian-ZH** [grafana/loki#2201]
**Describe the bug**
When the configuration of the index is updated, Loki deletes all of the saved indeces before the update.

Example:
From:
```
        index:
          prefix: index_
          period: 24h
```
To:
```
        index:
          prefix: index_
          period: 48h
```

**To Reproduce**
1. Loki Version 1.5.0
2. Fluent-bit 0.1.1

**Expected behavior**
When the index configuration is updated I expect the new Loki Pod to load the old indeces. Otherwise we gonna lose log data on every index update.

**Environment:**
 - Infrastructure: Kubernetes
 - Deploying copy of the charts from the stable repo

**Entire configuration:**
```
  loki.yaml: |-
    auth_enabled: false
    ingester:
      chunk_idle_period: 3m
      chunk_block_size: 262144
      chunk_retain_period: 3m
      max_transfer_retries: 3
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    schema_config:
      configs:
      - from: 2018-04-15
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    server:
      http_listen_port: 3100
      log_level: "debug"
    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks
    chunk_store_config: 
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: true
      retention_period: 336h
```

With this configuration we would like to keep all of the log messages for 14 days before being deleted.

**Comment by cyriltovena** [comment]
You should add another config when you want to change your store and not modify the current one. This is usually done by setting a date for the new one in the future like this:

```
    schema_config:
      configs:
      - from: 2018-04-15
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
      - from: 2020-06-10
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_2
          period: 24h
```
