### ISSUE TITLE
With Cassandra as storage, Loki always use "QUORUM" consystency level

### ISSUE THREAD

**Issue by rbudiharso** [grafana/loki#2207]
**Describe the bug**
When using Cassandra as index and chunk storage, loki always use "QUORUM" consistency level even though in the configuration is specified to use "LOCAL_ONE". I haven't try to use any other consistency level to see whether it's just "LOCAL_ONE" or any other consistency level other than "QUORUM"

this is the config snippet:
```
schema_config:
  configs:
  - from: 2020-01-01
    store: cassandra
    object_store: cassandra
    schema: v11
    index:
      prefix: index_
      period: 360h
    chunks:
      prefix: chunk_
      period: 360h
storage_config:
  cassandra:
    auth: true
    username: cassandra
    password: password
    consistency: LOCAL_ONE
    addresses: cassandra.monitoring.svc.cluster.local
    keyspace: loki
```

**To Reproduce**
1. `helm install -f values.yaml loki loki/loki-stack` 
2. `kubectl logs -f <loki-pod>`

**Expected behavior**
Loki run and use cassandra as storage

**Environment:**
 - kubernetes

**Screenshots, Promtail config, or terminal output**
loki log:
```
level=info ts=2020-06-11T00:35:13.148533084Z caller=server.go:179 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=error ts=2020-06-11T00:35:13.228113651Z caller=log.go:140 msg="error initialising loki" err="gocql: unable to create session: unable to discover protocol version: Unable to perform authentication: Cannot achieve consistency level QUORUM\ngithub.com/cortexproject/cortex/pkg/chunk/cassandra.(*Config).session\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/cassandra/storage_client.go:110\ngithub.com/cortexproject/cortex/pkg/chunk/cassandra.NewTableClient\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/cassandra/table_client.go:20\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewTableClient\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:283\ngithub.com/grafana/loki/pkg/loki.(*Loki).initTableManager\n\t/src/loki/pkg/loki/modules.go:249\ngithub.com/grafana/loki/pkg/loki.(*Loki).initModuleServices\n\t/src/loki/pkg/loki/loki.go:192\ngithub.com/grafana/loki/pkg/loki.New\n\t/src/loki/pkg/loki/loki.go:134\nmain.main\n\t/src/loki/cmd/loki/main.go:76\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\ngithub.com/cortexproject/cortex/pkg/chunk/cassandra.NewTableClient\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/cassandra/table_client.go:22\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewTableClient\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:283\ngithub.com/grafana/loki/pkg/loki.(*Loki).initTableManager\n\t/src/loki/pkg/loki/modules.go:249\ngithub.com/grafana/loki/pkg/loki.(*Loki).initModuleServices\n\t/src/loki/pkg/loki/loki.go:192\ngithub.com/grafana/loki/pkg/loki.New\n\t/src/loki/pkg/loki/loki.go:134\nmain.main\n\t/src/loki/cmd/loki/main.go:76\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nerror initialising module: table-manager\ngithub.com/grafana/loki/pkg/loki.(*Loki).initModuleServices\n\t/src/loki/pkg/loki/loki.go:194\ngithub.com/grafana/loki/pkg/loki.New\n\t/src/loki/pkg/loki/loki.go:134\nmain.main\n\t/src/loki/cmd/loki/main.go:76\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"
```
![2020-06-11T07:34+07:00](https://user-images.githubusercontent.com/43447/84331992-f53bf900-abb5-11ea-81b2-0924acc39d8f.png)
