### ISSUE TITLE
Cannot display all log files in the explore of grafana

### ISSUE THREAD

**Issue by pokixing** [grafana/loki#221]
My promtail configuration file like this：
```yaml
server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: http://localhost:3100/api/prom/push

scrape_configs:
- job_name: system
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log
```

When I run this command：
>./promtail -config.file=./cmd/promtail/promtail-local-config.yaml

Only one log file can be seen in the Explore of grafana.
