### ISSUE TITLE
We need a beginner-friendly example for data retention

### ISSUE THREAD

**Issue by bzon** [grafana/loki#2214]
Is there a beginner-friendly example anywhere on how to configure data retention? I think this is really important for production users.

I just installed Loki using helm with this configuration.

```yaml
    config:
      table_manager:
        retention_deletes_enabled: true
        retention_period: 120h
```

And then I got this error `retention period should now be a multiple of periodic table duration`. What is the periodic table duration? Can we have an example in the documentation, please. Thanks.

**Comment by adityacs** [comment]
@bzon `period config` is part of your schema config. You can find period configuration here https://github.com/grafana/loki/tree/master/docs/configuration#period_config

**Comment by bzon** [comment]
Thanks @adityacs I will test it out

**Comment by bzon** [comment]
Hi @adityacs if I want to have a 15d data retention. All data deleted. Can you help me achieve this? I tried using the period_config and it is not very straightforward. There are two `duration` there with a default of 168h.

**Comment by sandeepsukhani** [comment]
`period` under `index` is what you are looking for. `chunk` is for storing chunks in tables and it is not a good idea to store loki chunks in tables because their size is big compared to cortex chunks.
Set retention to multiple of `index.period`.

**Comment by bzon** [comment]
thanks @sandeepsukhani my final working configuration now is:

```yaml
    config:
      table_manager:
        retention_deletes_enabled: true
        retention_period: 336h # or 14d, because the default index period is 168h
```
