### ISSUE TITLE
Promtail crashes when running in Windows Container

### ISSUE THREAD

**Issue by Gerthum** [grafana/loki#2221]
**Describe the bug**
When attempting to run the Promtail Windows Binary in a Windows Container it crashes with the following output:

```
fatal error: PowerRegisterSuspendResumeNotification failure

runtime stack:
runtime.throw(0x240ebbd, 0x2e)
        /usr/local/go/src/runtime/panic.go:774 +0x79 fp=0x3cdfdb0 sp=0x3cdfd80 pc=0x4331a9
runtime.monitorSuspendResume()
        /usr/local/go/src/runtime/os_windows.go:294 +0x1a9 fp=0x3cdfe50 sp=0x3cdfdb0 pc=0x42f309
runtime.goenvs()
        /usr/local/go/src/runtime/os_windows.go:531 +0x1ba fp=0x3cdfea8 sp=0x3cdfe50 pc=0x42fc8a
runtime.schedinit()
        /usr/local/go/src/runtime/proc.go:554 +0xa9 fp=0x3cdff00 sp=0x3cdfea8 pc=0x435ba9
runtime.rt0_go(0x3cdff30, 0x7ff81f387974, 0x3cdff30, 0x0, 0x7ff81f387974, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/asm_amd64.s:214 +0x13d fp=0x3cdff08 sp=0x3cdff00 pc=0x45f84d

```

**To Reproduce**
1. docker run --entrypoint powershell  -it mcr.microsoft.com/windows/servercore:ltsc2019 powershell
2. C:\promtail\promtail-windows-amd64.exe --config.file C:\promtail\promtail_config.yaml

**Expected behavior**
To run as normal

**Environment:**
 - Infrastructure: Laptop
 - Deployment tool: Manual

**Screenshots, Promtail config, or terminal output**

It looks to be related to the following bug in Golang [https://github.com/golang/go/issues/35447](url) which is resolved in 1.14

Any idea when the move to 1.14 will happen?

**Comment by cyriltovena** [comment]
Should be soon we were wait for a fix on boltdb blocking 1.14.

**Comment by Gerthum** [comment]
Thank you for the feedback I will test once its upgraded.

**Comment by sachinmsft** [comment]
any updates on this issue ?

**Comment by Gerthum** [comment]
We've built our own binary with go 1.14 and it's running without issue in windows containers.

**Comment by sachinmsft** [comment]
Thanks @Gerthum . were you able to run it on Kubernetes. if yes, Can you please share the promtail config ?

**Comment by Gerthum** [comment]
Yes we are running it successfully in K8s. We use the standard config apart from the following changes:

1. Dockerfile:

```
FROM mcr.microsoft.com/windows/servercore:ltsc2019 
RUN mkdir C:\Loki
WORKDIR "C:\Loki"
COPY promtail.exe C:\Loki\
ENTRYPOINT ["promtail.exe"]
```
2. Daemonset
```
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: loki-promtail-win
  namespace: logging
  labels:
    app: promtail-win
spec:
  selector:
    matchLabels:
      app: promtail-win
      release: loki
  template:
    metadata:
      labels:
        app: promtail-win
        release: loki
      annotations:
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: loki-promtail-chart
      imagePullSecrets:
      - name: 
      containers:
        - name: promtail-win
          image: "private-registry/promtail-win:1.0.0"
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
            - "-client.url=http://loki.logging.svc.cluster.local:3100/loki/api/v1/push"
            - "-log.level=debug"
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: C:\var
              readOnly: true
            - name: varlibdockercontainers
              mountPath: C:\ProgramData\Docker\containers
              readOnly: true

          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 3101
              name: http-metrics
          securityContext:
            readOnlyRootFilesystem: true
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {}
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      volumes:
        - name: config
          configMap:
            name: loki-promtail-win
        - name: varlog
          hostPath:
            path: C:\var
        - name: varlibdockercontainers
          hostPath:
            path: C:\ProgramData\Docker\containers
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
    name: loki-promtail-win
    namespace: logging
    labels:
      app: promtail-win
spec:
    privileged: false
    allowPrivilegeEscalation: false
    volumes:
    - 'secret'
    - 'configMap'
    - 'hostPath'
    hostNetwork: false
    hostIPC: false
    hostPID: false
    runAsUser:
        rule: 'RunAsAny'
    seLinux:
        rule: 'RunAsAny'
    supplementalGroups:
        rule: 'RunAsAny'
    fsGroup:
        rule: 'RunAsAny'
    readOnlyRootFilesystem: true
    requiredDropCapabilities:
    - ALL

``` 

3. Make sure the Service Account etc. names match the ones you use for the linux daemonset.
