### ISSUE TITLE
Default docker-compose config has loki exposed to outside

### ISSUE THREAD

**Issue by agordeev** [grafana/loki#2225]
The default config is:

```yaml
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:1.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:1.5.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - loki
```

which gets port 3100 exposed to the world. Why is that? How to make it exposed to the docker containers only?
