### ISSUE TITLE
Size-based retention

### ISSUE THREAD

**Issue by Kristian-ZH** [grafana/loki#2227]
Why Loki does not have size-based retention.

I have tried the following scenario:
1) Create Loki and attach disk on /data folder with 10gb size.
2) Wait few minutes for Loki to gather some logs.
3) Create dummy file which will fill the entire 10gb size in /data: Something like this
```
16.0K	./lost+found
45.9M	./loki/chunks
3.3M	./loki/index
49.2M	./loki
9.7G	./tmp.txt
```

Now Loki will start crashing with the following error:
```
level=error ts=2020-06-17T07:15:17.178022368Z caller=flush.go:198 org_id=fake msg="failed to flush user" err="open /data/loki/chunks/ZmFrZS83MzBmNTc4MDE4OTIzOGU0OjE3MmJkZWM0YWM3OjE3MmJkZWQ5NmJmOjNjZDQyODkx: no space left on device"
```

Also in this case the Loki is completely broken and Grafana can not fetch even the labels from it.

* Expected behaviour:
 What I expect in this case is Loki to clean the old indeces and chucks in /loki/index and /loki/chunks

* Loki configuration:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
data:
  loki.yaml: |-
    auth_enabled: false
    ingester:
      chunk_idle_period: 3m
      chunk_block_size: 262144
      chunk_retain_period: 3m
      max_transfer_retries: 3
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    schema_config:
      configs:
      - from: 2018-04-15
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
      - from: 2020-07-16
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_new_
          period: 24h
    server:
      http_listen_port: 3100
    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks
    chunk_store_config: 
      max_look_back_period: 336h
    table_manager:
      retention_deletes_enabled: true
      retention_period: 336h
```
