### ISSUE TITLE
What's the meaning of value "2020-05-15" in loki-local-config.yaml?

### ISSUE THREAD

**Issue by ZuoGuocai** [grafana/loki#2230]
Why use the key "from"  in  config file of loki-local-config.yaml? What's the meaning of value "2020-05-15" ?  Thanks.
```
schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb
      object_store: filesystem
```
