### ISSUE TITLE
Documentation and examples for AWS setup are very different

### ISSUE THREAD

**Issue by carlosjgp** [grafana/loki#2236]
**Describe the bug**
I'm setting up Loki to test it and I'm struggling to set up Loki to use DynamoDB and S3 for index and chunks respectively

**To Reproduce**
Trying to configure `schema_config` using the resources
- [Documentation](https://github.com/grafana/loki/blob/master/docs/configuration/README.md#period_config)
- [Examples](https://github.com/grafana/loki/blob/master/docs/configuration/examples.md#aws)

**Expected behavior**
Documentation and examples are consistent

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**
Documentation
![screenshot-github com-2020 06 18-10_19_55](https://user-images.githubusercontent.com/1277613/85002904-64cd5d80-b14d-11ea-810b-babbf3256726.png)

Example
![screenshot-github com-2020 06 18-10_20_33](https://user-images.githubusercontent.com/1277613/85002926-6b5bd500-b14d-11ea-8689-48939d9b7139.png)

**Comment by nikhils5501** [comment]
@carlosjgp I'm struggling to do the same thing.
What storage_config values do you see inside `/etc/loki/loki.yaml` inside the loki-0 pod?

Is it still pointing to boltdb or updated to aws as specified in values.yaml ?

**Comment by carlosjgp** [comment]
Sorry for the delay @nikhils5501 

this was my final setup

```
          # https://github.com/grafana/loki/blob/master/docs/configuration/README.md#period_config	
          # Docs and examples are contradictory	
          # https://github.com/grafana/loki/blob/master/docs/configuration/examples.md#aws	
          # https://github.com/grafana/loki/issues/2236	
          schema_config:	
            configs:	
            - from:   2020-01-01	
              store:  aws	
              object_store: s3	
              schema: v11	
              index:	
                prefix: loki_ci_	
                period: 216h	
          # https://github.com/grafana/loki/blob/master/docs/configuration/README.md#storage_config	
          storage_config:	
            aws:	
              s3: s3://eu-west-1/my-s3-bucket
              dynamodb:	
                dynamodb_url: dynamodb://eu-west-1	
                metrics:	
                  # Use metrics-based autoscaling via this Prometheus query URL.	
                  url: http://thanos-query.monitoring:9090
```

I'm using VPC endpoints for DynamoDB and S3 to reduce the cost of data transfer
- https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-s3.html
- https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-ddb.html
