### ISSUE TITLE
Promtail.log growing and filling up disk space 

### ISSUE THREAD

**Issue by nadgobpx01** [grafana/loki#2243]
Please ask questions you have in the mailing list: https://groups.google.com/forum/#!forum/lokiproject
Hello , 
I am using loki and promatail on ubuntu 18.04 .I am recieving lots of logs like the one bellow an filling the disk space up . 

"promtail[7409]: ts=2020-06-19T19:49:23.02907375Z caller=log.go:124 component=tailer level=info msg="Waiting for /var/log/installer/subiquity-info.log to appear.."

Not sure if it's a bug or  config issue  ,

The file config-promtail.yml look like this : 
"server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push
scrape_configs:
 - job_name: system
   entry_parser: raw
   static_configs:
   - targets:
      - localhost
     labels:
      job: varlogs
      host: thisserver
      __path__: /var/log/**/*.log
"

Or join our #loki slack channel at http://slack.raintank.io/

**Comment by nadgobpx01** [comment]
Hello , can anyone take a look at this please. Everytime i start promtail logs fill up the space, I am suspecting a bug.

**Comment by cyriltovena** [comment]
I think info is really verbose should you switch to WARN ?

**Comment by nadgobpx01** [comment]
> I think info is really verbose should you switch to WARN ?

Hi @cyriltovena  thank you  for looking into this , any ideea where i can do this setting .

**Comment by cyriltovena** [comment]
```
log_level: warn
```

**Comment by nadgobpx01** [comment]
> log_level: warn

thankyou , unfortunatly is still logging  info level :

ts=2020-06-23T08:04:10.096172395Z caller=log.go:124 component=tailer level=info msg="Waiting for /var/log/installer/subiquity-debug.log to appear..."

**Comment by cyriltovena** [comment]
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: warn

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
```

here is an example is this how you did it ?
