### ISSUE TITLE
Delay in logs arriving in Grafana Dashboard from Loki

### ISSUE THREAD

**Issue by vijay-jindal** [grafana/loki#2245]
Hi,
I have around 50 applications running on Kubernetes cluster which use Loki to store logs. When querying the logs from Grafana, one of the services show a delay of 3hr-8hr in the logs while all other services do not show any issues in the logs. This delay is causing a lot of confusion and sync issues.

I have implemented Logging in the following manner :

Promtail is implemented as a sidecar with the application pod and it reads the logs from a mounted directory.
Loki runs in an independent machine outside the Kubernetes cluster.

Is there anything that I can do to resolve this issue ?
Thank you.

In the following image, it is evident that there is a delay of almost 4hrs when it arrives to Grafana Dashboard.
<img width="1185" alt="Screenshot 2020-06-21 at 11 46 04 AM" src="https://user-images.githubusercontent.com/25745453/85218237-f3441800-b3b5-11ea-83d3-19e928ee78dc.png">

**Comment by Amit-Kumar-G** [comment]
I am facing a similar issue in production, any insights are appreciated !

**Comment by slim-bean** [comment]
I'm not really sure what to suggest here, we've never experienced anything like this.  By default promtail will wait no longer than a few seconds to send a batch.

I think to begin to troubleshoot we would need to see your promtail config as well as the log output from promtail

**Comment by vijay-jindal** [comment]
@slim-bean , thank you for the response. I figured the problem was with the service producing the logs. One single log was almost 4k lines and hence Promtail was taking longer to process the log and that added to delay to all the logs after that big log. The issue is resolved by removing the big log.

**Comment by slim-bean** [comment]
That's really useful feedback @vijay-jindal, thank you for the follow-up, I had not thought to check log length.  There is a metric for pipeline processing which would probably show this, but I'm also wondering if there is another metric we should add to make this more obvious..

**Comment by vijay-jindal** [comment]
Right @slim-bean , I think if there is another metric that can make it clear that the issue is with log length or size, it will help in debugging the issue faster. My initial steps where to see if the delay had been caused due to Loki, since Loki consumes a lot of memory and probably a restart would have helped, but it didn't and then I explored around Promtail to figure out the issue at that end.
Thank you.

**Comment by shagundave** [comment]
I am also getting delay logs from Loki to Grafana. It is strating delay from 3 min and than so on..

We have 300+ application running on Kubernetes Dev Env. Some of application produce too many logs.  

I am using Fluent-bit, Loki and Grafana in kubernetes. (P.S I am using Fluent-bit official . I am not using fluentbit output plugins of grafana).

Kindly let me know if i am missing anything in any configmap file. 


1) Fluent-bit Configmap file.

```
data:
  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Buffer_Size         0
        Merge_Log           Off
        #Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     debug
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE out_loki.conf
  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     128MB
        Skip_Long_Lines   On
        Refresh_Interval  20
        # Control the log line length
        Buffer_Chunk_Size 4MB
        Buffer_Max_Size   8MB
        # Using the docker mode to deal with multiline messages emitted by docker
        Docker_Mode       On
        Rotate_Wait       30
  out_loki.conf: |
    [Output]
        name              loki
        match             *
        host              loki.logging.svc.cluster.local
        port              3100
        tenant_id         ""
        labels            job=fluentbit
        auto_kubernetes_labels On
        line_format       json
  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

```

2) Loki Configmap file:

```
auth_enabled: false
ingester:

  chunk_idle_period: 5m
  chunk_retain_period: 30s
  chunk_block_size: 262144
  chunk_encoding: snappy
  max_transfer_retries: 0
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
limits_config:
  ingestion_rate_strategy: global
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_chunks_per_query: 200000
  max_entries_limit_per_query: 5000
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
  - from: 2020-10-24
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h
server:
  http_listen_port: 3100
  log_level: debug
storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /data/loki/chunks
chunk_store_config:
  max_look_back_period: 0s
table_manager:
  retention_deletes_enabled: true
  retention_period: 72h
compactor:
  working_directory: /data/loki/boltdb-shipper-compactor
  shared_store: filesystem
```
