### ISSUE TITLE
storage_config values not working with helm/loki deployment

### ISSUE THREAD

**Issue by nikhils5501** [grafana/loki#2253]
I'm trying to deploy `Loki` using production/helm/loki chart from this repo. I would like to use `aws s3 and dynamodb` as storage instead of a PVC. 
This is what my `loki_values.yaml` looks like:

```
enabled: true
schema_config:
   configs:
   - from: 2020-05-15
     store: aws
     object_store: s3
     schema: v11
     index:
       prefix: loki_index
       period: 0
storage_config:
  aws:
    s3: s3://us-east-2/loki-test-bucket-dev-east-2
    dynamodb:
      dynamodb_url: dynamodb://us-east-2
table_manager:
  retention_deletes_enabled: true
  retention_period: 336h
```

But the `loki.yaml` file inside the pod path `/etc/loki` after deployment still seem to use boltdb as storage.
Can someone help me with this? 
Is `aws storage_config` currently supported on this helm chart v0.30.0?

Thanks.

**Comment by ingram90** [comment]
I hit similar problem today, after trying to put related settings inside `config:`, such as:

```
config:
  …
  table_manager:
    retention_deletes_enabled: true
    retention_period: 336h
  …
```

and it works. 

Hope this help.

**Comment by nikhils5501** [comment]
@ingram90 Can you please share your values.yaml? 
I've already mentioned `table_manager` config in the file. Not missing what's missing.

**Comment by ingram90** [comment]
@nikhils5501 Here you are:

```
enabled: true
config:
  schema_config:
     configs:
     - from: 2020-05-15
       store: aws
       object_store: s3
       schema: v11
       index:
         prefix: loki_index
         period: 0
  storage_config:
    aws:
      s3: s3://us-east-2/loki-test-bucket-dev-east-2
      dynamodb:
        dynamodb_url: dynamodb://us-east-2
  table_manager:
    retention_deletes_enabled: true
    retention_period: 336h
```
