### ISSUE TITLE
Loki pod is failing to start

### ISSUE THREAD

**Issue by Priyanka098** [grafana/loki#2277]
**Describe the bug**
I have configured aws and dynamodb to save data and index in it. But the pod is failing with error
failed parsing config: /etc/loki/loki.yaml: not a valid duration string: "0"

**To Reproduce**
1. Deploy loki with helm chart version 0.30.0
2. Loki config
```
config:
  table_manager:
    retention_deletes_enabled: true
    retention_period: 0s
  schema_config:
    configs:
    - from: 2020-01-01
      store: aws
      object_store: aws
      schema: v9
      index:
        prefix: loki_index
  storage_config:
    aws:
      s3: s3://A***A/u***K@eu-west-1/xms-loki-master
      dynamodb:
        dynamodb_url: dynamodb://A***A/u***a/RIVxJsr+uK@eu-west-1
  chunk_store_config:
    max_look_back_period: 0s

limits_config:
  max_streams_per_user: 1000000
```

**Expected behavior**
Pod should be started and should start saving data in s3 and indexes in dynamo

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
