### ISSUE TITLE
Timestamp custom pattern not working as expected

### ISSUE THREAD

**Issue by ChangSurrey** [grafana/loki#2283]
**Describe the bug**
When I use a custom pattern in `timestamp` stage, it is unable to parse the timestamp correctly. 

**To Reproduce**
1. Started Loki v1.5.0
2. Started Promtail v1.5.0
3. Use the following `match` pipeline stage:
```
  - match:
      selector: '{pod=~"primary.*"}'
      stages:
        - json:
            expressions:
              output: log
              stream: stream
              time: time
        - regex:
            source: output
            expression: '^(?s)(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3})\|(?P<level>TRACE|DEBUG|INFO|WARN|ERROR)\|(?P<thread>.*)\|(?P<marker>.*)\|(?P<principal>.*)\|(?P<sessionid>.*)\|(?P<content>.*)\|(?P<class>.*)$'
        - labels:
            level:
            thread:
            marker:
            principal:
            sessionid:
            content:
            class:
        - timestamp:
            source: time
            format: "2006-01-02 15:04:05,000"
```

The stage works as I can see the custom labels above appear in Grafana Explore tab.

**Expected behavior**
The timestamp should be parsed correctly. However, it isn't. 

The "Parsed Fields" section in the Explore tab shows the following
```
Parsed Fields:
--
  | ts | 2020-07-02T10:12:08.829Z
  | tsNs | 1593684728829387636
  | log | "2020-07-02 10:12:08,741\|INFO\|... (remainder of the log entry)

```
which indicates that the timestamp is not parsed. 

**Environment:**
 - Infrastructure: K8s v1.15
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
