### ISSUE TITLE
Pipeline stage must contain only one key

### ISSUE THREAD

**Issue by AClarkie** [grafana/loki#2297]
**Describe the bug**
Can't define multiple keys in pipeline stage, the promtail pods are in `CrashLoopBackOff` with the following error message:

`error creating promtail" error="failed to make file target manager: pipeline stage must contain only one key"`

**To Reproduce**
1. Started Loki-stack 0.38.1 (app version 1.5.0)
2. Started Promtail 0.23.2
3. Set the following config in the promtail section of the helm chart:

```
  pipelineStages:
  - docker: {}
  - match:
    selector: '{foo="bar"}'
    stages:
    - json:
        expressions:
          level:
          foo: bar
```

**Expected behavior**
From the documentation [here](https://github.com/grafana/loki/blob/master/docs/clients/promtail/configuration.md#pipeline_stages) I expect the following config to work, the configmap shows the following:

```
    - job_name: kubernetes-pods-static
      pipeline_stages:
        - docker: {}
        - match: null
          selector: '{foo="bar"}'
          stages:
          - json:
              expressions:
                foo: bar
                level: null
```

It looks like the `match` entry is being parsed incorrectly

**Environment:**
 - Infrastructure: kubernetes eks
 - Deployment tool: helm 3

loki-stack version: 0.23.2

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by AClarkie** [comment]
Indenting was wrong, I'm a fool

**Comment by cyriltovena** [comment]
I work on loki I got bitten daily by this. I’m a fool too.

**Comment by fyqls** [comment]
how to resolve,  @cyriltovena

**Comment by nijave** [comment]
For anyone finding this in the future...

NOT THIS
```yaml
  pipelineStages:
  - docker: {}
  - match:
    selector: '{foo="bar"}'
    stages:
    - json:
        expressions:
          level:
          foo: bar
```

THIS
```yaml
  pipelineStages:
  - docker: {}
  - match:
      selector: '{foo="bar"}'
      stages:
      - json:
          expressions:
            level:
            foo: bar
```

(notice keys underneath `match` are all indented)

**Comment by caerulescens** [comment]
@cyriltovena @nijave and I join the list of fools

**Comment by damusix** [comment]
How does one debug with line is causing this issue?

**Comment by rpsirois** [comment]
Almost regretting saying this in public @damusix but if you convert to JSON then `match` should be an object with the properties `selector`, etc. when valid (as opposed to `null`).

**Comment by vhquang** [comment]
@rpsirois it is extremely useful. It drives me nut, about why 2-space indentation works with:
```yaml
expressions:
  level:
  foo: bar
```
But it has to be 4-spaces indentation to work with:
```yaml
- match:
    selector: '{foo="bar"}'
    stages:
```
It turns out nested dictionary is treated as a special case of indentation: https://stackoverflow.com/a/64999517/793367
[YAML 1.2 spec](https://yaml.org/spec/1.2.2/#block-collection-styles) is difficult for me to interpret. The best interpretation I have, is because `- ` (ie: 2-spaces) is part of the indentation, the next indent needs to be 2-spaces + next indent (2-spaces) = 4 spaces.
