### ISSUE TITLE
How to run a distributed, resilient cluster of Loki servers without kubernetes?

### ISSUE THREAD

**Issue by avkonst** [grafana/loki#2324]
**Is your feature request related to a problem? Please describe.**
Assuming I have got the following:

1. 3 instances of loki server are launched by `docker run` command.
2. each instance is given it's own storage and IP address.
3. instances are connected, ie. can talk to each other vie the network via the IP addresses assigned

What environment variables or command line arguments should I provide to the `docker run` commands, so multiple Loki instances form a resilient, distributed, synchronised cluster?

**Describe the solution you'd like**
I would like to see clear docs and an example how to run 3 instances of Loki, so they form a cluster for HA, including (automated storage replication and scalability)

**Describe alternatives you've considered**
Ingest via fluent-bit with multiple outputs to 3 independent Loki instances, but it is not ideal as it loads the containers and Loki instances do not sync with each other.

**Additional context**
Need the documentation without references to kubernetes and / or swarm,
The examples, should not use anything else except plain `docker` command.

**Comment by cyriltovena** [comment]
We're working on getting this use case finished, currently only possible (unless you're ok with experimental) with a cloud storage. You also need all Loki instances to be connected via consul/etcd or recently memberlist (no dependency) to form a ring for replication and such.

In the near future, you should be able to use boltdb-shipper and memberlist to achieve exactly what you want. You can run the experimental version if you want.

See :
- https://grafana.com/blog/2020/05/20/loki-v1.5.0-released-with-no-more-dependency-on-a-separate-index-store/
- https://github.com/grafana/loki/blob/master/docs/operations/storage/boltdb-shipper.md
- https://grafana.com/blog/2020/03/25/how-were-using-gossip-to-improve-cortex-and-loki-availability/
- https://github.com/grafana/loki/tree/master/docs/configuration#memberlist_config
- https://github.com/grafana/loki/blob/master/docs/configuration/examples.md#almost-zero-dependencies-setup

We've been running this internally so far so good. Feel free to give us some feedback if you try this out.

**Comment by avkonst** [comment]
Hi, Thanks. I am fine to try experimental but I run out of time for this Loki research task. I might come back later. We will try to move to production with one Loki instance and see what happens. Logs are critical of course, but we can compromise here a bit for some period of time. When distributed Loki is more ready, we will switch to it.

I have checked the articles. I roughly see where you are going. As far as I understand you will have each Loki having the same eventually consistent storage, which is synced via 3rd party central storage with S3 compatible API, right?. My concern is that it requires this additional external storage as well as CPU/RAM to maintain this S3 like storage. Loki feels light weight so far. Would not it be better to have Loki exchanging the information with its peers rather than via some other external storage?

**Comment by avkonst** [comment]
Please do not close it. This ticket is extremely important.

**Comment by avkonst** [comment]
Keep it open

**Comment by uginroot** [comment]
# My config from two instance without kubernetes and / or swarm

Instance 1: loki-write.mysite.com
Instance 2: loki-read.mysite.com

Usage:
1. docker
2. consul - instead of memberlist (it doesn't work)
4. s3
5. loki

Before exec `docker-comlose up -d` create folders:
1. `./data`
2. `./data/rules-temp/` - from read instance

# Write instance (loki-write.mysite.com)

consul+loki+nginx

## ./docker-compose.yaml
```yaml
---
version: "3"

services:
  init:
    image: grafana/loki:2.4.2
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/loki"
    volumes:
      - ./data:/loki

  consul:
    image: hashicorp/consul:1.11.0
    restart: always
    volumes:
     - ./config/consul.json:/consul/config/server.json:ro
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  write:
    image: grafana/loki:2.4.2
    command: "-config.file=/etc/loki/config.yaml -target=write"
    ports:
      - "3100:3100" # http
      - "7946:7946" # gossip
      - "9095:9095" # grpc
    volumes:
      - ./config/loki.yaml:/etc/loki/config.yaml
      - ./data:/loki/
    depends_on:
      - consul
      - init
```

## ./config/loki.yaml
```yaml
---
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

memberlist:
  gossip_interval: 1s
  bind_port: 7946
  abort_if_cluster_join_fails: false
  join_members:
    - loki-write.mysite.com:7946
    - loki-read.mysite.com:7946
  bind_addr:
    - loki-write.mysite.com

schema_config:
  configs:
    - from: 2022-02-17
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
      chunks:
        prefix: chunk_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      region: us-east-1
      bucketnames: ssw-loki-logs
      s3forcepathstyle: true
  ring:
    kvstore:
      store: consul
      consul:
        host: loki-write.mysite.com:8500
    instance_addr: loki-write.mysite.com

ruler:
  storage:
    s3:
      region: us-east-1
      bucketnames: ssw-loki-logs
      s3forcepathstyle: true

frontend:
  max_outstanding_per_tenant: 1024
  scheduler_worker_concurrency: 20

frontend_worker:
  parallelism: 2

query_range:
  split_queries_by_interval: 15m
  align_queries_with_step: true
  cache_results: true
  parallelise_shardable_queries: false
  max_retries: 5

limits_config:
  retention_period: 168h
  max_query_lookback: 168h
  max_query_parallelism: 256
  max_query_length: 168h
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 30

storage_config:
  aws:
    region: us-east-1
    bucketnames: ssw-loki-logs
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: s3

compactor:
  shared_store: s3
  working_directory: /loki/compactor
```

## ./config/consul.json
```json
{
    "node_name": "consul",
    "server": true,
    "bootstrap" : true,
    "ui_config": {
        "enabled" : true
    },
    "data_dir": "/consul/data",
    "addresses": {
        "http" : "0.0.0.0"
    }
}
```

# Read instance (loki-read.mysite.com)

## ./docker-compose.yaml

```yaml
---
version: "3"

services:
  init:
    image: grafana/loki:2.4.2
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/loki"
    volumes:
      - ./data:/loki

  read:
    image: grafana/loki:2.4.2
    command: "-config.file=/etc/loki/config.yaml -target=read"
    ports:
      - "3100:3100" # http
      - "7946:7946" # gossip
      - "9095:9095" # grpc
    volumes:
      - ./config/loki.yaml:/etc/loki/config.yaml
      - ./data:/loki/
    depends_on:
      - init
```

## ./config/loki.yaml

```yaml
---
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

memberlist:
  gossip_interval: 1s
  node_name: loki
  bind_port: 7946
  abort_if_cluster_join_fails: false
  join_members:
    - loki-write.mysite.com:7946
    - loki-read.mysite.com:7946
  bind_addr:
    - loki-read.mysite.com

schema_config:
  configs:
    - from: 2022-02-15
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
      chunks:
        prefix: chunk_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      region: us-east-1
      bucketnames: ssw-loki-logs
      s3forcepathstyle: true
  ring:
    kvstore:
      store: consul
      consul:
        host: loki-write.mysite.com:8500
    instance_addr: loki-read.mysite.com

ruler:
  storage:
    s3:
      region: us-east-1
      bucketnames: ssw-loki-logs
      s3forcepathstyle: true

frontend:
  max_outstanding_per_tenant: 1024
  scheduler_worker_concurrency: 20

frontend_worker:
  parallelism: 2

query_range:
  split_queries_by_interval: 15m
  align_queries_with_step: true
  cache_results: true
  parallelise_shardable_queries: false
  max_retries: 5

limits_config:
  retention_period: 168h
  max_query_lookback: 168h
  max_query_parallelism: 64
  max_query_length: 168h
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 30

storage_config:
  aws:
    region: us-east-1
    bucketnames: ssw-loki-logs
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: s3

compactor:
  shared_store: s3
  working_directory: /loki/compactor
```

**Comment by saibug** [comment]
@uginroot could you tell us more why with memberlist it doesn't work ?

**Comment by uginroot** [comment]
@saibug I wanted to sort this out in the source code of the project, but the project is too big and it would take a lot of time. In this regard, I do not have an answer to this question. I hope that the manufacturers know the project well, answer this question and possibly fix it in the next versions.

**Comment by saibug** [comment]
@uginroot otherwise.. your config with consul works fine. Tested on my lab 🙏.

**Comment by uginroot** [comment]
@saibug Yes that's right. But they haven’t rolled out for sale yet with two write machines

**Comment by saibug** [comment]
@uginroot i have tested this, with two write, two read , but doesn't work correctly . 
I have many errors : Bad gateway (for latge data volume/time range),
From consul ui, i can see only master node (when consul is installed) . 

anu idea ?

**Comment by uginroot** [comment]
@saibug All join_members, bind_addr and instance_addr sections must be correctly filled on all machines
```yaml
memberlist:
  #...
  join_members: # Same for all machines
    - loki-write1.mysite.com:7946
    - loki-write2.mysite.com:7946
    - loki-read1.mysite.com:7946
    - loki-read2.mysite.com:7946
  bind_addr:
    - loki-write2.mysite.com # One for each node
#....
common:
  ring:
    kvstore:
      store: consul
      consul:
        host: loki-write1.mysite.com:8500 # Does not change
    instance_addr: loki-write2.mysite.com # One for each node
```
The node on which the consul is running must be launched first.
It worked for me on my test machine, but usually you had to wait a few minutes until the nodes saw each other.
