### ISSUE TITLE
Metrics: Counter expiring too soon

### ISSUE THREAD

**Issue by divanikus** [grafana/loki#2333]
I'm using a simple stage which increments counter on specific log lines (WARN, ERROR, INFO, etc). Recently I've noticed that some counters just dissappear after a while. That could be a problem for rare lines. For example ERROR lines are kind of rare, maybe one in several hours, so If I try to look at them in Grafana, I see just a couple of points during day, not even connected in a line.

```
    pipeline_stages:
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) (?P<level>\w+) '
      - labels:
          level:
      - metrics:
          lines_total:
            type: Counter
            prefix: mc_log_
            source: level
            config:
              action: inc
      - match:
          selector: '{level="DEBUG"}'
          action: drop
```
![image](https://user-images.githubusercontent.com/3438036/87144101-e8432000-c2af-11ea-905f-a27d3af92d1b.png)

I'm scraping promtail metrics from prometheus-server. But if I curl the /metrics endpoint of the promtail itself, I also do not see those counters after a while.

Did I miss any expiry option here? I believe it shouldn't expire so fast.
