### ISSUE TITLE
Using flag -memberlist.bind-addr results in duplicates in config

### ISSUE THREAD

**Issue by timpalpant** [grafana/loki#2363]
**Describe the bug**
When specifying an IP address to bind using the flag `-memberlist.bind-addr`, the resulting config ends up with two entries of the specified IP. Then Loki fails to start because it will attempt to bind the same address twice, the second time failing with:

```
level=warn ts=2020-07-16T14:16:43.329796938Z caller=module_service.go:88 msg="module failed with error" module=memberlist-kv err="service &{0xc0002fdef0 { true 0 0 0 0 0 0 0 [] 1000000000 60000000000 10 false 0 300000000000 5000000000 {[127.0.0.1 127.0.0.1] 7948 5000000000 5000000000 false false 0xc0000a2730 } 0xc0000a2730  [{ringDesc 0x1b4f920}]} 0xc000ad8000 {{} [0 0 0]} <nil> <nil> {0 0} map[] map[ringDesc:{ringDesc 0x1b4f920}] {0 0} map[] map[] 0xc000ad4120 0xc000a91b60 0xc000a91bc0 0xc000a91c20 0xc000a91d40 0xc000a91c80 0xc000a91da0 0xc000a91ce0 0xc000ac23c0 0xc000ac2400 0xc000a91e00 0xc000a91ec0 0xc000a91e60 0xc0004b0ff8 0xc000ad85b0 0xc000ad8620 0xc000ac2440 0xc000ac2480 10} failed: failed to create transport: failed to start TCP listener on \"127.0.0.1\" port 7948: listen tcp 127.0.0.1:7948: bind: address already in use"
```

**To Reproduce**
1. Run loki (81b9decf) with the flag `-memberlist.bind-addr=127.0.0.1 -print-config-stderr`
2. Loki will fail to start and print the config:

```
memberlist:
  node_name: ""
  randomize_node_name: true
  stream_timeout: 0s
  retransmit_factor: 0
  pull_push_interval: 0s
  gossip_interval: 0s
  gossip_nodes: 0
  gossip_to_dead_nodes_time: 0s
  dead_node_reclaim_time: 0s
  join_members: []
  min_join_backoff: 1s
  max_join_backoff: 1m0s
  max_join_retries: 10
  abort_if_cluster_join_fails: false
  rejoin_interval: 0s
  left_ingesters_timeout: 5m0s
  leave_timeout: 5s
  bind_addr:
  - 127.0.0.1
  - 127.0.0.1
  bind_port: 7948
```

**Expected behavior**
Loki starts and binds 127.0.0.1:7948 (once). Since this config is a list option, perhaps flags are being parsed twice resulting in two appends to the list: https://github.com/grafana/loki/blob/master/vendor/github.com/cortexproject/cortex/pkg/ring/kv/memberlist/tcp_transport.go#L65

**Environment:**
 - Infrastructure: bare-metal Ubuntu 16.04
 - Deployment tool: n/a
