### ISSUE TITLE
Member list problem

### ISSUE THREAD

**Issue by mrmassis** [grafana/loki#2374]
Hi,
Im migrate to the memberlist. But I cant do that the ingester enter in the ring. Im using a multiservice deploy with 3 ingester (in pod) and 3 distributor (in pods).

My config:

```
...
   distributor:
        ring:
            kvstore:
                store: memberlist
    memberlist:
        gossip_nodes: 2
        abort_if_cluster_join_fails: false
    ingester:
        chunk_block_size: 262144
        chunk_idle_period: 15m
        lifecycler:
            heartbeat_period: 5s
            interface_names:
              - eth0
            join_after: 30s
            num_tokens: 512
            ring:
                heartbeat_timeout: 1m
                kvstore:
                    store: memberlist
                replication_factor: 3
...
```
How the ring is empty the distributor dont work and i cant receive logs.
@pstibrany any sugestions?

Tkz so much
