### ISSUE TITLE
Data from few hours ago, but query with Longer period consumes High Memory(as much as available) and High CPU

### ISSUE THREAD

**Issue by pcbl** [grafana/loki#2381]
Hi Folks,

I am having one situation with Loki (v1.4.1), that I would like to ask for advice as I believe I am missing something on my Loki Configuration. I must confess that i am quite new to Loki and might be doing something wrong.

The scenario is quite simple: I have some Logs on Loki(Data Folder has around 300mb) that I addded in the past 12 hours. So, there´s actually NO data older than 12 hours. What happens is:

I make a simple "{job=~".*"}" query, with a limit 1000 and the start of (1595228363000000 - Monday, July 20, 2020 6:59:23 AM).. 1 Day in the past.

The call looks like this (note loki is running on port 12345):
**http://localhost:12345/loki/api/v1/query_range?limit=1000&query={job=~".*"}&start=1595228363000000**

As soon as I make this request, in seconds Loki process gets from **25mb** to **8.6GB** RAM while consuming some resonable CPU in the process. Once it gets to **8.6 GB** it **collapses** as it rans **out of memory**. 

Here is my Loki configuration:

```
auth_enabled: false

server:
  http_listen_port: 12345
  log_level: 'warn'

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: C:\ProgramData\DemoApp\loki\index

  filesystem:
    directory: C:\ProgramData\DemoApp\loki\chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: true
  retention_period: 168h
```

Can anyone give me some advise on what i am possibly doing wrong?
