### ISSUE TITLE
how to use boltdb-shipper?

### ISSUE THREAD

**Issue by teichae** [grafana/loki#2382]
Hi, there.

I have a question.

I want to send the chunk log of Loki using boltdb-shipper and s3.

I installed Loki by using the helm chart.

Do I need to install additional helm charts to use boltdb-shipper?

I want to use it because I find it attractive to be able to index without using DynamicoDB.

Please help me.

Below is the error message that appeared during my setup.

> failed parsing config: /etc/loki/loki.yaml: yaml: unmarshal errors:
> line 2: field boltdb_shipper not found in type loki.Config

Below is the code that I used to settings.

```
 limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
  schema_config:
    configs:
    - from: 2018-04-15
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 168h
  server:
    http_listen_port: 3100
  storage_config:
    aws:
      s3: s3://my region/my bucket
  boltdb_shipper:
    active_index_directory: /loki/index
    shared_store: s3
    cache_location: /loki/boltdb-cache
```
