### ISSUE TITLE
🔥🔥 Promtail regular expression related 🔥🔥

### ISSUE THREAD

**Issue by happinesslijian** [grafana/loki#2409]
I found a new problem, let me describe it below:

Note: I use loki and promtail to monitor and collect virtual machine logs, not docker, nor k8s environment. Please know
The centos7 operating system defaults to the /var/log/ directory, there are messages and some empty directories, such as rhsm
If I use  ** , it is invalid according to the official statement, /path** will be regarded as /path* (that is, it matches all whether it is a directory or a file)
At this time, the messages will show rhsm is a directory and the log is of error level.

I now write /var/log/**.log in this way so that you can recursively query the log logs in all subdirectories under the /var/log/ directory, but ignore the logs in /var/log/messages.

Here comes the problem, since there are the file messages I want in the /var/log/ directory, and the empty directory rhsm I don't want, in this case, how should I match it in loki?

This is my existing configuration
```
scrape_configs:
- job_name: 10.20.80.207
  static_configs:
  - targets:
      - localhost
    labels:
      job: NFS-logs
      __path__: /var/log/**.log
```

Please help me thanks

**Comment by cyriltovena** [comment]
Add another static target with the full path of the file you want to tail. I think it should do the job.

**Comment by j0ju** [comment]
Try bash alike globs:
>        __path__: /var/log/{,*/}{*[._]log,{mail,news}.{err,info,warn}}
```
scrape_configs:
  - job_name: logfile
    pipeline_stages: []
    static_configs:
    - labels:
        __path__: /var/log/{,*/}{*[._]log,{mail,news}.{err,info,warn}}
        host: host
        job: logfile
      targets:
      - localhost
```

**Comment by happinesslijian** [comment]
> 添加另一个静态目标以及要尾部文件的完整路径。我认为应该做的。

Yes, you are right, but this is still not flexible
Below is my example
```
- job_name: 10.20.80.207
  static_configs:
  - targets:
      - localhost
    labels:
      job: NFS-messages-logs
      __path__: /var/log/messages
```

**Comment by happinesslijian** [comment]
> 尝试bash一样的glob：
> 
> > ```
> >    __path__: /var/log/{,*/}{*[._]log,{mail,news}.{err,info,warn}}
> > ```
> 
> 这适用于debian / ubuntu系统。
> 
> ```
> scrape_configs:
>   - job_name: logfile
>     pipeline_stages: []
>     static_configs:
>     - labels:
>         __path__: /var/log/{,*/}{*[._]log,{mail,news}.{err,info,warn}}
>         host: host
>         job: logfile
>       targets:
>       - localhost
> ```

This is effective, I want to know what it means, can you answer it? I don't understand at all
```
__path__: /var/log/{,*/}{*[._]log,{mail,news}.{err,info,warn}}
```
Even so, I can't see the log of /var/log/messages

**Comment by j0ju** [comment]
According to the promtail docs it supports in __path__ unix style globs (man 7 glob) and more or less something like the _Brace expansion_ from bash  (man bash, search for Brace Expansion).

On my workstation it expands to 
```
> ls -1 /var/log/{,*/}{*[._]log,{mail,news}.{err,info,warn}}
/var/log/alternatives.log
/var/log/apport.log
/var/log/apt/history.log
/var/log/apt/term.log
/var/log/dpkg.log
/var/log/fontconfig.log
/var/log/gpu-manager.log
/var/log/gpu-manager-switch.log
/var/log/installer/partman-early_command.log
/var/log/lightdm/lightdm.log
/var/log/lightdm/seat0-greeter.log
/var/log/lightdm/x-0.log
/var/log/nginx/access_log
/var/log/nginx/error_log
/var/log/preseed/late_command.log
/var/log/preseed/partman-early_command.log
/var/log/prime-offload.log
/var/log/prime-supported.log
/var/log/ubuntu-advantage.log
/var/log/unattended-upgrades/unattended-upgrades-shutdown.log
/var/log/vbox-setup.log
/var/log/Xorg.0.log
```

/var/log/messages is not included but it should bes easy to add.

Side note:
/var/log/messages and other stuff that is usually generated by syslog/rsyslog/syslog-ng is not included, as I strip on workstations and servers any syslog service and rely fully on systemd-journald which is collected and shipped by promtail, even docker ships to systemd-journald. systemd-journald usually provides the syslog interface via /dev/log, so we gather all syslog log events properly.
But on most systems we have services/jobs/deamons/apps, that have their own logfiles under /var/log/. The line we discuss on is instructing promtail to collecting events from those files, too.

**Comment by happinesslijian** [comment]
> 根据Promtail文档，它支持`__path__`unix样式的glob（man 7 glob），或多或少地支持bash 的_Brace扩展_（man bash，搜索_Brace Expansion_）。
> 
> 在我的工作站上，它扩展为
> 
> ```
> > ls -1 /var/log/{,*/}{*[._]log,{mail,news}.{err,info,warn}}
> /var/log/alternatives.log
> /var/log/apport.log
> /var/log/apt/history.log
> /var/log/apt/term.log
> /var/log/dpkg.log
> /var/log/fontconfig.log
> /var/log/gpu-manager.log
> /var/log/gpu-manager-switch.log
> /var/log/installer/partman-early_command.log
> /var/log/lightdm/lightdm.log
> /var/log/lightdm/seat0-greeter.log
> /var/log/lightdm/x-0.log
> /var/log/nginx/access_log
> /var/log/nginx/error_log
> /var/log/preseed/late_command.log
> /var/log/preseed/partman-early_command.log
> /var/log/prime-offload.log
> /var/log/prime-supported.log
> /var/log/ubuntu-advantage.log
> /var/log/unattended-upgrades/unattended-upgrades-shutdown.log
> /var/log/vbox-setup.log
> /var/log/Xorg.0.log
> ```
> 
> / var / log / messages不包括在内，但是应该很容易添加。
> 
> 我不使用` /var/log/{*,*/*}`（扩展到`/var/log/* `和` /var/log/*/*`），因为我们有/ var / log / lastlog和/ var / log / wtmp，有时还有其他文件。这些是二进制文件，我不想被徒劳地刮掉。
> 此模式也将匹配由日志轮换生成的文件，我也不想通过probtail收集这些文件。
> 
> 旁注：
> / var / log / messages和通常由syslog / rsyslog / syslog-ng生成的其他内容不包括在内，因为我在工作站和服务器上剥离了任何提供syslog的服务，并完全依赖于systemd-journald收集并按杂货运输。甚至docker也被运送到systemd-journald（，当不用作k8s节点时）。systemd-journald通常通过/ dev / log提供syslog接口，因此我们可以正确收集所有syslog日志事件。
> 但是在大多数系统上，我们都有services / jobs / deamons / apps，它们在/ var / log /下有自己的日志文件。我们讨论的这一行还指示Promtail也从这些文件中收集事件，以使不使用syslog / journald或docker的服务具有可观察性。

```
__path__: /var/log/{,*/}{*[._]log,{mail,news}.{err,info,warn}}
```
I basically understand the meaning of this passage, but what does mail news mean? I didn't want to understand
In addition, recursive query can be implemented in this way, but the log in the /var/log/ directory cannot be indexed. For example, /var/log/messages cannot be indexed. Therefore, you need to manually specify it. The final configuration file is as follows:
```
scrape_configs:
- job_name: varlogs
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/messages

- job_name: test
  static_configs:
  - targets:
      - localhost
    labels:
      job: test
      __path__: /var/log/{,*/}{*[._]log,{mail,news}.{err,info,warn}}
```
