### ISSUE TITLE
pipeline stage json not working

### ISSUE THREAD

**Issue by raducrisan1** [grafana/loki#2411]
I tried to apply structured logging to a product deployed in Kubernetes. The product pods were writing to stdout in JSON format and I tried to configure Promtail's pipelineStages section to create labels for some specific json attributes. It did not work.
Afterwards I reconfigured my product pods to output logfmt text instead of json, I also altered the pipelineStages to use regex and it just worked. For me it seems that this is a bug in the json stage. I did not spend time, yet, to look into the promtail source code to understand exactly what is the problem. I might also miss something.

**To Reproduce**

1) I have deployed Loki and Promtail on Kubernetes via Helm Chart and I set the following pipelineStage configuration in my custom values yaml file:

```
pipelineStages:
- json:
    expressions:
      level: level
      method: method
      module: module 
- labels:
    level: ""
    method: ""
    module: ""
```

The log line output formatted as JSON is below:

`
{"level":"info","method":"GET","module":"businessapi","msg":"Executed campaign list","time":"2020-07-24T07:53:46Z","url":"/api/monitor/campaigns"}
`

2) Observe in Grafana this log entry:

<img width="1671" alt="Screenshot 2020-07-24 at 10 55 02" src="https://user-images.githubusercontent.com/15193363/88372836-5a7f2e80-cd9f-11ea-8ae1-8d55b7a8df84.png">

3) Redeployed promtail with the following configuration for pipelineStages:

```
pipelineStages:
- regex:
    expression: (level|lvl|severity)=(?P<level>\w+)  
- regex:
    expression: (method|function)=(?P<method>\w+)  
- regex:
    expression: (module|package|layer)=(?P<module>\w+)  
- labels:
    level: ""
    method: ""
    module: ""
```
 
This time, the log line output is formatted as logfmt. The sample is below:

`
time="2020-07-24T07:57:26Z" level=info msg="Executed campaign list" method=GET module=businessapi url=/api/monitor/campaigns
`

4) Observe in Grafana this log entry:

<img width="1399" alt="Screenshot 2020-07-24 at 10 59 11" src="https://user-images.githubusercontent.com/15193363/88373283-41c34880-cda0-11ea-95b0-cc66df5c906e.png">

**Expected behavior**
Promtail with the pipelineStages configuration of JSON stage should have generated the log labels named level, method and module, in the same way as it worked using the configuration with Regex and logfmt line output

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool:  Loki and Promtail deployed in two separate releases with Helm. I have used the 1.5.0 image version for both of them.

**Comment by cyriltovena** [comment]
You should try to activate debug log and also use —stdin and —dry-run to try this out, let us know what suspicious log you found.

**Comment by cookandy** [comment]
I was noticing the same issue, but it was because I removed the `docker` stage by overwriting the default value for `pipelineStages`. Try something like this:

```
pipelineStages:
- docker: 
- json:
    expressions:
      level: level
      method: method
      module: module 
- labels:
    level: ""
    method: ""
    module: ""
```

**Comment by mikusk1104** [comment]
same issue here :-(

**promtail-config.yaml**
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug
  
positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  pipeline_stages:
  - json:
      expressions:
        hostIP: hostIP
        hostname:   hostname
        syslogtag:  syslogtag
  - labels:
        hostIP:
        hostname:
        syslogtag:
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /logs/*log
```
**Log Line**

`"time":"2020-08-30T15:33:45.034213+02:00":"hostIP":"192.168.27.1":"hostname":"dns":"syslogtag":"dns:":"msg":" done query: #16008 fcmconnection.googleapis.com 216.58.201.106"`

**Error code:**
`caller=json.go:130 component=file_pipeline component=stage type=json msg="failed to unmarshal log line" err="ReadMapCB: expect { or n, but found \", error found in #1 byte of ...|\"time\":\"202|..., bigger context ...|\"time\":\"2020-08-30T15:22:51.748296+02:00\":\"hostIP\":|..."`

No labels in Grafana :-)
