### ISSUE TITLE
Missing container compose_services / logs in Grafana explore for Loki

### ISSUE THREAD

**Issue by GGOUSSEAUD** [grafana/loki#2426]
**Describe the bug**
In a 8+ containers environment, Loki behaves randomly concerning the label & log gathering of other containers. Sometimes a compose_service is missing in the rollout menu and after the restart of this container it comes back up. 
The ones not picked up by loki randomizes at each start which made me believe it has to do with computation time. 

**To Reproduce**
1. Run docker stack
2. Go to Grafana explore Loki logs tab.
3. Realize not all service are there.
4. Restart missing docker container.
5. Service is back in loki/grafana after some time.

**Expected behavior**
Loki & Grafana should display all logged services without any tricks of boot priority or restarting(critical problem for some services).
Services that start before loki is fully initialized should be able to still send logs to loki post start.

**Environment:**
 - Infrastructure: Laptop (16Gb RAM & I7 processor), docker multi-compose environment.
 - Deployment tool: Local stack (invoke command)

**Screenshots**

**portainer before restart**
![portainer](https://user-images.githubusercontent.com/25582593/88542572-e949b080-d016-11ea-8870-8c898d787ade.png)

**grafana/loki before restart**
![graf_before](https://user-images.githubusercontent.com/25582593/88542652-09796f80-d017-11ea-8ba5-a10282199534.png)

**Restart missing redis**
![term_bef](https://user-images.githubusercontent.com/25582593/88542683-18f8b880-d017-11ea-8bf5-219481034f8a.png)

**grafana/loki after restart**
![graf_aft](https://user-images.githubusercontent.com/25582593/88542737-329a0000-d017-11ea-9b41-584b02a6d3e0.png)
See how both watcher and redis are back? (watcher restarts with redis)

**Files:**  
My multi-compose environment goes in such priority (top = highest priority):
- docker-compose.override.yml
- support.yml
- docker-compose.yml   
<details>
  <summary>docker-compose.yml (Click to expand)</summary>

```yaml
version: "3.7"

services:
  backend:
    image: mybackendimageonagitlab:latest
    env_file:
      - ./env/backend.env
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.backend.loadbalancer.server.port: "9000"
        traefik.http.services.backend.loadbalancer.sticky.cookie: "{}"
        traefik.http.routers.backend.rule: "Host(`${API_HOST}`)"
        traefik.http.routers.backend.entrypoints: "websecure"
        traefik.http.routers.backend.tls.certresolver: "letsencryptresolver"
      replicas: "${REPLICA_COUNT_BACK:-1}"
    volumes:
      - "backend_data:/var/www/backend/data"
      - "static_files:/var/www/backend/static"
      - "media_files:/var/www/backend/media"
    depends_on:
      - db
      - redis 
    networks:
      - redis
      - db
      - traefik

  celery:
    image: myceleryimage:latest
    env_file:
      - ./env/backend.env
    entrypoint: "poetry run celery -A config worker -Q celery,FAST --beat --scheduler django -l info"
    volumes:
      - "backend_data:/var/www/backend/data"
    deploy:
      labels:
        traefik.enable: "false"
      replicas: "${REPLICA_COUNT_CELERY:-1}"

    depends_on:
      - db
      - redis
      - backend
    networks:
      - redis
      - db

  xxx-watcher:  
    image: mywatcherimage:latest
    env_file:
      - ./env/backend.env
    entrypoint: "poetry run ./manage.py xxx_watcher"
    volumes:
      - "backend_data:/var/www/backend/data"
    deploy:
      labels:
        traefik.enable: "false"
      replicas: 1

    depends_on:
      - db
      - redis 
      - backend
    networks:
      - redis
      - db

  frontend:
    image: myfrontend:lastest
    env_file:
      - ./env/frontend.env
    depends_on:
      - backend
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.frontend.loadbalancer.server.port: "3000"
        traefik.http.routers.frontend.rule: "Host(`${WEB_HOST}`)"
        traefik.http.routers.frontend.entrypoints: "websecure"
        traefik.http.routers.frontend.tls.certresolver: "letsencryptresolver"
      replicas: 1
    volumes:
      - "static_files:/usr/share/nginx/html/static"
      - "media_files:/usr/share/nginx/html/media"
    networks:
      - traefik

  db:
    image: postgres:12.2-alpine
    restart: always
    env_file:
      - ./env/database.env
    deploy:
      labels:
        traefik.enable: "false"
      replicas: 1
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - db

  redis:
    image: redis:5-alpine
    command: redis-server --appendonly yes --save 60 1000 900 1 --appendfsync everysec
    deploy:
      labels:
        traefik.enable: "false"
      replicas: 1
    volumes:
      - "redis_data:/data" # Storage location for RDB & AOF files
    networks:
      - redis

  livy:
    image: mylivyimage:latest
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.livy.loadbalancer.server.port: "8998"
        traefik.http.routers.livy.rule: "Host(`${LIVY_HOST}`)"
        traefik.http.routers.livy.middlewares: "livyauth"
        traefik.http.middlewares.livyauth.basicauth.users: "${LIVY_LOGIN}"
        traefik.http.routers.livy.entrypoints: "websecure"
        traefik.http.routers.livy.tls.certresolver: "letsencryptresolver"
      replicas: 1
    volumes:
      - "./settings/xxx.ini:/opt/xxx/conf/xxx.ini"
      - "./settings/livy.conf:/opt/livy/conf/livy.conf"
      - "livy-sessions:/root/.livy-sessions/"
      - "backend_data:/opt/data/"
    networks:
      - redis
      - livy
      - default
      - traefik

  xxx:
    image: xxx:latest
    depends_on:
      - livy
    volumes:
      - "./settings/xxx.ini:/var/www/xxx/conf/xxx.ini"
      - "backend_data:/opt/data/"
      - "livy-sessions:/root/.livy-sessions/"
      - "./xxx_jars:/opt/external_dependencies/"
    deploy:
      labels:
        traefik.enable: "false"
      replicas: 1
    networks:
      - redis
      - livy
      - default

volumes:
  backend_data:
  livy-sessions:
  media_files:
  postgres_data:
  redis_data:
  server_initialized:
  static_files:
  traefik-certificates:

networks:
  db:
    internal: true
  livy:
    internal: true
  redis:
    internal: true
  traefik:
    external: true
```

</details>

<details>
  <summary>support.yml (Click to expand)</summary>

```yaml
version: "3.7"

x-logging: &loki-logging
  driver: loki
  options:
    loki-url: "https://${LOKI_HOST}/loki/api/v1/push"

services:
  backend:
    logging: *loki-logging
    depends_on:
      - loki

  celery:
    logging: *loki-logging
    depends_on:
      - loki

  xxx-watcher: 
    logging: *loki-logging
    depends_on:
      - loki

  frontend:
    logging: *loki-logging
    depends_on:
      - loki

  db:
    logging: *loki-logging
    depends_on:
      - loki

  redis:
    logging: *loki-logging
    depends_on:
      - loki

  livy:
    logging: *loki-logging
    depends_on:
      - loki

  xxx:
    logging: *loki-logging
    depends_on:
      - loki

  traefik:
    logging: *loki-logging
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./settings/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.prometheus.rule: "Host(`${PROMETHEUS_HOST}`)"
        traefik.http.services.prometheus.loadbalancer.server.port: "9090"
        traefik.http.routers.prometheus.entrypoints: "websecure"
        traefik.http.routers.prometheus.tls.certresolver: "letsencryptresolver"
      replicas: 1
    depends_on:
     - backend
    networks:
      - traefik
      - default
    logging: *loki-logging

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.grafana.rule: "Host(`${GRAFANA_HOST}`)"
        traefik.http.services.grafana.loadbalancer.server.port: "3000"
        traefik.http.routers.grafana.entrypoints: "websecure"
        traefik.http.routers.grafana.tls.certresolver: "letsencryptresolver"
      replicas: 1
    networks:
      - traefik
      - default

  loki:
    image: grafana/loki:latest
    command:
      - '--config.file=/etc/loki/local-config.yaml'
    deploy:
      labels:
        traefik.http.routers.loki.rule: "Host(`${LOKI_HOST}`)"
        traefik.http.services.loki.loadbalancer.server.port: "3100"
        traefik.http.routers.loki.entrypoints: "websecure"
        traefik.http.routers.loki.tls.certresolver: "letsencryptresolver"
      replicas: 1
    networks:
      - traefik
      - default
      - db
      - redis

volumes:
  grafana_data:
```

</details>

<details>
  <summary>docker-compose.override.yml (Click to expand)</summary>

```yaml
version: "3.7"

x-logging: &loki-logging
  driver: loki
  options:
    loki-url: "http://loki.xxx.lh/loki/api/v1/push"

services:
  backend:
    restart: on-failure
    container_name: xxxxx_backend
    env_file: .env
    labels:
      traefik.enable: "true"
      traefik.backend: "backend"
      traefik.http.routers.backend.rule: "Host(`api.xxx.lh`)"
      traefik.http.services.backend.loadbalancer.server.port: "9000"
    tty: true
    stdin_open: true
    ports:
      - "9000:9000"

  celery:
    restart: on-failure
    container_name: xxxxx_celery
    env_file: .env
    labels:
      traefik.enable: "false"

  xxx-watcher:
    restart: on-failure
    container_name: xxxxx_xxx_watcher
    env_file: .env
    labels:
      traefik.enable: "false"

  frontend:
    restart: on-failure
    container_name: xxxxx_frontend
    env_file: .env
    ports:
      - "3000:3000"
    labels:
      traefik.enable: "true"
      traefik.backend: "frontend"
      traefik.http.routers.frontend.rule: "Host(`xxx.lh`)"
      traefik.http.services.frontend.loadbalancer.server.port: "3000"
    tty: true
    stdin_open: true

  db:
    restart: on-failure
    container_name: xxxxx_db
    env_file: .env
    labels:
      traefik.enable: "false"

  redis:
    restart: on-failure
    container_name: xxxxx_redis
    env_file: .env
    labels:
      traefik.enable: "false"

  livy:
    restart: on-failure
    container_name: xxxxx_livy
    env_file: .env
    ports:
      - "8998:8998"
    labels:
      traefik.enable: "true"
      traefik.backend: "livy"
      traefik.http.routers.livy.rule: "Host(`livy.xxx.lh`)"
      traefik.http.services.livy.loadbalancer.server.port: "8998"

  xxx:
    restart: on-failure
    container_name: xxxxx_xxx
    env_file: .env
    labels:
      traefik.enable: "false"

  traefik:
    restart: on-failure
    container_name: xxxxx_traefik
    env_file: .env
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: "Host(`traefik.xxx.lh`)"
      traefik.http.routers.api.service: "api@internal"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./settings/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    labels:  
      traefik.enable: "true"
      traefik.http.routers.prometheus.rule: "Host(`prometheus.xxx.lh`)"
      traefik.http.services.prometheus.loadbalancer.server.port: "9090"
    depends_on:
     - backend

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3060:3000
    labels: 
      traefik.enable: "true"
      traefik.http.routers.grafana.rule: "Host(`grafana.xxx.lh`)"
      traefik.http.services.grafana.loadbalancer.server.port: "3000"

  loki:
    image: grafana/loki:latest
    command:
      - '--config.file=/etc/loki/local-config.yaml'
    ports:
      - 3100:3100
    labels:
      traefik.enable: "true"
      traefik.http.routers.loki.rule: "Host(`loki.xxx.lh`)"
      traefik.http.services.loki.loadbalancer.server.port: "3100"
```

</details>
