### ISSUE TITLE
Loki doesn't return all log entries matching query in Grafana explorer even when limit is very high

### ISSUE THREAD

**Issue by swisspol** [grafana/loki#2445]
**Describe the bug**
Depending on what you enter for the time range for the Loki query in Grafana explorer, some log records may not show up even if the total number of returned entries is still way below the query limit.

**To Reproduce**

From our setup:

Running query in Grafana explorer for `{filename=~".*presenter.*", instance="i-0615b5f7e24de4883"}` for last 2 days with a custom limit of 5000 produces:
```
Limit:
5000 (674 returned)
Total bytes processed:
814 kB
```

Newest entry: `2020-07-29 04:47:21`
Oldest entry: `2020-07-29 04:45:50`

674 results is way below the 5000 limit and we are clearly missing log entries (the oldest one is ~10 hours old).

![image](https://user-images.githubusercontent.com/627915/88856209-f0a0c380-d1a8-11ea-956a-e65e6a43b615.png)

---

Now if you change the timerange to `now-2d` to `now-6h`, you still get the same results. But if you change to `now-2d` to `now-12h`, you get:

```
Limit:
5000 (1767 returned)
Total bytes processed:
423 kB
```

Newest entry: `2020-07-29 02:03:08`
Oldest entry: `2020-07-28 03:15:31` <--- NOW FURTHER BACK IN TIME

This is twice as many results while still way below the limit.

![image](https://user-images.githubusercontent.com/627915/88856185-e7175b80-d1a8-11ea-91a1-28afca5abcc2.png)

**Expected behavior**
Asking Grafana / Loki to return logs matching a query return all entries matching the query within the limit, and is not silently hiding some of the entries.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: ad-hoc yaml (from helm originally)
- Grafana 7.1.1 + Loki 1.5.0

**Screenshots, Promtail config, or terminal output**

```
auth_enabled: false
server:
  http_listen_port: 3100
ingester:
  chunk_idle_period: 3m
  chunk_block_size: 262144
  chunk_retain_period: 1m
  max_transfer_retries: 0
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v9
      index:
        prefix: index_
        period: 168h # 7 days
storage_config:
  boltdb:
    directory: /storage/index
  filesystem:
    directory: /storage/chunks
chunk_store_config:
  max_look_back_period: 0s
table_manager:
  retention_deletes_enabled: true
  retention_period: 1680h # 70 days
```
