### ISSUE TITLE
chunk_target_size does not increase chunk file size as intended; unusually high inode usage

### ISSUE THREAD

**Issue by ChangSurrey** [grafana/loki#2465]
**Describe the bug**
Running loki v1.5.0 in a AWS EKS cluster.
Loki is deployed through helm chart, hence in monolith mode (1 ingester only).

The original issue was that its inode usage is very high. For example, these are the stats of loki running after 24 hours from a blank volume:

```
/data/loki $ df -i
Filesystem              Inodes      Used Available Use% Mounted on
overlay               10484720     60448  10424272   1% /
tmpfs                   993919        17    993902   0% /dev
tmpfs                   993919        16    993903   0% /sys/fs/cgroup
/dev/nvme1n1           6553600    514217   6039383   8% /data
tmpfs                   993919         5    993914   0% /etc/loki
/dev/nvme0n1p1        10484720     60448  10424272   1% /dev/termination-log
/dev/nvme0n1p1        10484720     60448  10424272   1% /etc/resolv.conf
/dev/nvme0n1p1        10484720     60448  10424272   1% /etc/hostname
/dev/nvme0n1p1        10484720     60448  10424272   1% /etc/hosts
shm                     993919         1    993918   0% /dev/shm
tmpfs                   993919         9    993910   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                   993919         1    993918   0% /proc/acpi
tmpfs                   993919        17    993902   0% /proc/kcore
tmpfs                   993919        17    993902   0% /proc/keys
tmpfs                   993919        17    993902   0% /proc/latency_stats
tmpfs                   993919        17    993902   0% /proc/timer_list
tmpfs                   993919        17    993902   0% /proc/sched_debug
tmpfs                   993919         1    993918   0% /sys/firmware
/data/loki $ ls -lh
total 58188
drwxr-sr-x    2 loki     loki       56.8M Aug  4 12:49 chunks
drwxr-sr-x    2 loki     loki        4.0K Aug  3 09:49 index
/data/loki $ find chunks/ | wc -l
514309
/data/loki $ ls -l chunks | head -n 1
total 2161416
```

Google search led me to #1502 as that was what I saw in my previous loki deployment - it ran out of inodes after running for 2 weeks. I added the following section into `loki.yaml` as recommended by #1502:
```
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 30m
  chunk_retain_period: 15m
  chunk_target_size: 1572864
```

The content of `loki.yaml` is as follows:
```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 672h
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 30m
  chunk_retain_period: 15m
  chunk_target_size: 1572864
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  ingestion_rate_mb: 100
  max_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
  - from: "2020-06-20"
    index:
      period: 168h
      prefix: index_
    object_store: filesystem
    schema: v11
    store: boltdb
server:
  http_listen_port: 3100
storage_config:
  boltdb:
    directory: /data/loki/index
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: true
```

By setting `chunk_target_size` to 1.5MiB I was expecting that each file under `chunk/` should be around 1.5MiB. However, it seems loki is still generating files under `chunk/` with size of approx. 1 - 1.8KiB each. 

Is this a bug, or did I miss / misconfigure anything here?
