### ISSUE TITLE
use loki-docker-driver, the `docker-compose logs` not work

### ISSUE THREAD

**Issue by qyvlik** [grafana/loki#2469]
loki-docker-driver save log file in `/var/lib/docker/plugins/<id>/rootfs/var/log/docker/<container_id>`, the `docker logs <container_id>` can work, **but `docker-compose logs` not work**

docker-compose.yml as follow

```yml
version: '2'
services:
  ping:
    image: alpine:latest
    entrypoint: ping host.docker.internal
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}
        loki-external-labels: container_name={{.Name}},awshost=machine1
        keep-file: "true"
        max-size: 512m
```

Run `docker-compose logs`, output as follow

```txt
ping_1  | WARNING: no logs are available with the 'loki' log driver
```

- https://github.com/grafana/loki/issues/1886
