### ISSUE TITLE
Promtail stops processing all but one journal file in systemd-journal-remote directory

### ISSUE THREAD

**Issue by rjgibson** [grafana/loki#2479]
**Describe the bug**
I'm using `systemd-journal-upload`-> `systemd-journal-remote` to send journal files from a cluster of servers to `/var/log/journal/remote` on a single log server, one journal file per server. Loki initially shows log entries for all servers, but after a few minutes I only see log entries for a single server.

**To Reproduce**
1. Started Loki (1.5.0)
2. Started Promtail (5714a9578735) to tail `/var/log/remote/journal`
3. Queried `{job="systemd-journal-remote"}` (all log entries) and observed `_HOSTNAME` field. Loki displays log entries for numerous servers as expected.
4. Waited a few minutes
5. Queried `{job="systemd-journal-remote"}` (all log entries) and observed `_HOSTNAME` field. Loki displays log entries for only one server. Confirmed that journal files are still being updated.

**Expected behavior**
Promtail continues to tail all journal files in remote journal directory, gracefully handling log rotation for each.

**Environment:**
- Infrastructure: bare-metal
- Deployment tool: Docker / docker-compose (for loki and promtail) using the following images:
  - grafana/loki:1.5.0
  - grafana/promtail:latest (5714a9578735) -- to get the fix for https://github.com/grafana/loki/issues/2104

**Promtail config:**
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: systemd-journal-remote
    journal:
      # Enable json format to get additional journal fields (e.g. _HOSTNAME)
      json: true
      max_age: 12h
      labels:
        job: systemd-journal-remote
      path: /var/log/journal/remote
    pipeline_stages:
      - match:
          selector: '{job="systemd-journal-remote"}'
          stages:
            - json:
                expressions:
                  host: _HOSTNAME
            - labels:
                # Add host as a label
                host:
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
```
