### ISSUE TITLE
Explicit Timestamps For Metrics Stage

### ISSUE THREAD

**Issue by d4c7** [grafana/loki#2509]
Promtail allows you to create metrics from the parsed log lines.  So, if you can parse log in near-realtime you can use only logging for both logging and metrics-monitoring.
It's very useful for some systems in which you cannot use a normal agent or client metrics.
Using Prometheus you cannot send a too old (<1h) timestamped metrics. However, a solution is on the roadmap and it will be able to ingest old metrics with some conditions.

The "problem" is Promtail does not allow to use explicit timestamps with metrics and this is the change proposed:

https://github.com/d4c7/loki/blob/stages_metrics_timestamp/pkg/logentry/metric/metricvec.go 

So you can use a `explicit_timestamps: true` for each metric condig you want:

```yaml

scrape_configs:
  - job_name: bla
    pipeline_stages:
      - regex:
          expression: '^(?P<ts>regex timestamp)'
      - timestamp:
          source: ts
          format: "whatever"
      - metrics:
          log_lines_total:
            type: Counter
            explicit_timestamps: true
```

The collector is the same already used but a explicit timestamp is added when the metric is collected. This explicit timestamp is the latest time of the parsed logs until then.
