### ISSUE TITLE
[Bug] after upgrade to 1.6 and boltdb-shipper unable to query the data

### ISSUE THREAD

**Issue by yacut** [grafana/loki#2515]
**Describe the bug**

After upgrade to 1.6, I can't query the data. Grafana explore tries to get labels und gets this error:

```
level=error ts=2020-08-16T23:30:52.664563723Z caller=chunk_store.go:541 org_id=xxx traceID=2e244b7211184adb msg="error querying storage" err="context canceled"
ts=2020-08-16T23:30:52.664863184Z caller=spanlogger.go:53 org_id=xxx traceID=2e244b7211184adb method=SeriesStore.LabelNamesForMetricName level=error msg=lookupLabelNamesBySeries err="context canceled"
```

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Loki config**
```yaml
auth_enabled: true

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

distributor:
  ring:
    kvstore:
      store: memberlist

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 2160h

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
    -xxx:xxx

  max_join_backoff: 1m
  max_join_retries: 10
  min_join_backoff: 1s

schema_config:
  configs:
    - from: 2020-05-10
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 2160h
    - from: 2020-08-15
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

server:
  http_listen_port: 3100
  log_level: info

storage_config:
  aws:
    s3: s3://xxx
    s3forcepathstyle: true
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/boltdb-cache
    cache_ttl: 168h
    shared_store: s3
    resync_interval: 5s

```
