### ISSUE TITLE
Promtail: docker images, stops trailing logs after logfile rotation 

### ISSUE THREAD

**Issue by kdandersen** [grafana/loki#2517]
**Describe the bug**
Running Promtail via a Docker container, trialing haproxy log file via volumen mount.
Promtail stops seeing new entries when logfile is rotatet daily via logrotate.

**To Reproduce**
1) Running haproxy, writing log-file to /var/log/haproxy.log
2) Run Promtail via Docker image with following docker run command:

```docker run -d --name promtail --restart unless-stopped \
  -p 9080:9080 \
  -v /opt/promtail/promtail.yaml:/promtail.yaml \
  -v /opt/promtail/pos/:/tmp/ \
  -v /var/log/haproxy.log:/haproxy.log \
 grafana/promtail:latest -config.file /promtail.yaml
```

Promtail.yaml file has the following format _(less relevant for this issue, as same file is used with locally installed Promtail that doesn't show this issue)_:
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://<loki-server-url>:3100/loki/api/v1/push

scrape_configs:
  - job_name: haproxy
    static_configs:
    - targets:
        - localhost
      labels:
        hostname: <server-name>
        hostip: "10.33.xx.xxx"
        job: haproxy
        env: infrastucture
        __path__: /var/log/haproxy.log
    pipeline_stages:
    - match:
        selector: '{job="haproxy"}'
        stages:
        - regex:
             expression: '^(?P<syslog_time>[^ ]* +[^ ]* +[^ ]*) (?P<syslog_host>[\w-\.]+) (?P<ps>\w+)\[(?P<pid>\d+)\]: ... <truncated>
        - labels:
            f_end:
            b_end:
            b_server:
```

3) When (re)starting Promtail container the haproxy logs are shipped to Loki (single server demo deploy) without issues for the next X hours, until approx 03:30 when logrotate on the host rotates and compresses the haproxy.log, and a new haproxy.log is being written to.

Once this happens, Promtail stops following the newly creates haproxy.log, and no new log lines are shipped to Loki.

**Expected behavior**
Container based Promtail should be able to detect log-rotation of a file on the host machine, that is made available to container based Promtail via a volume mount.

A native running Promtail (Linux binary), systemd controlled doesn't show this behavior.

I am aware though, that this may not be related directly to Promtail, but may fall back on the way volume-/file-mounts are handled by Docker, such that Promtail running in a container isn't actually seeing the new file.
I also believe this issue has similarities with #2479: Promtail stops processing all but one journal file in systemd-journal-remote directory

**Environment:**
- Centos 7.7 based VM host
- Haproxy 2.2.x "natively" running on host via systemd
- Logrotate rotates /var/log/haproxy.log daily at approx 3 o'clock
- Docker Engine: Docker-ce 19.03.12 + containerd
- Promtail running as a Docker deployment, accessing haproxy.log via a volume mount in the container.

**Screenshots, Promtail config, or terminal output**
Log influx stopping at approx 03:18
![image](https://user-images.githubusercontent.com/49781983/90479816-8f2c9e80-e12f-11ea-9ccc-6bb6801d00cc.png)

Log rotation happened at 03:18
![image](https://user-images.githubusercontent.com/49781983/90479866-a4a1c880-e12f-11ea-8043-02ac2c18352c.png)

Promtail container restarted day before at approx 15:45
![image](https://user-images.githubusercontent.com/49781983/90479974-d4e96700-e12f-11ea-9570-32cb5be8841e.png)

**Comment by slim-bean** [comment]
no error messages in the logs?

can you exec into the promtail container after the restart and see if you can see the file with new entries in it?

It might also work better to mount a directory and not the specific file, you can still leave your promtail config for the specific file but instead of `-v /var/log/haproxy.log:/haproxy.log \` do `-v /var/log:/log \` and update promtail to the correct path

**Comment by kdandersen** [comment]
Hi Ed,

Nopes. No error messages what so ever (picture 1, restart on the 18th). And understandable why. Since the haproxy.log is still visible and readable from inside the Promtail container (picture 2). But the visible file has gone stale at the time of the log rotation at approx 03:06 this time (picture 2, tail command).

At your advise I have changed the approach, and changed the mount from file to directory: -v /var/log:/var/log:ro
I will keep at eye on it, and see if this makes the difference.

Still "funny" how the container sees the file including content after it has been rotated and compresse to a new name...?

Picture 1 - last restart, no errors:
![image](https://user-images.githubusercontent.com/49781983/90857592-c0ea7300-e384-11ea-9522-d55bb6e29606.png)

Picture 2 /var/log folder from inside container incl. 'tail -n5' of log file:
![image](https://user-images.githubusercontent.com/49781983/90857689-eaa39a00-e384-11ea-9b8c-0cc7bee4c15f.png)

Regards

**Comment by alexandrsemak** [comment]
the same issue in Openshift with `kubernetes_sd_configs`:
```
    - replacement: /var/log/**/*$1*.log
      separator: /
      source_labels:
      - __meta_kubernetes_pod_name
      target_label: __path__
```
Openshift rotate all big log files to:
```
ad5a0f7f32eb6a30972731da7fe4734a1499fff641d7d071974c232344dfe24d.log  promtail
# cd promtail
# ls
0.log  0.log.20200925-041345.gz  0.log.20200925-074627
```
after that promtail stop tailing logs as kubernetes_sd_configs doesn't match it
