### ISSUE TITLE
How do I know I'm writing the right expression？

### ISSUE THREAD

**Issue by Yogurt-needs-straw** [grafana/loki#2545]
why I wrote the selector and expression didn't work? and How do I know I'm writing the right expression？

I find ! Although the label env came out but the level did not come out ?

```yaml
- job_name: syslog-up
    pipeline_stages: 
    - match:
       selector: '{job="log-total"}|=" up"'
       stages:
       - regex:
           expression: ".*(?P<up>up.*)"
       - labels:
           level: 'up'
    static_configs:
    - targets:
      - localhost
      labels:
        env: switch-up
        __path__: /var/log/device/2020-08/**/*.log
```
