### ISSUE TITLE
1.6.1: invalid schema config: the table period must be a multiple of 24h

### ISSUE THREAD

**Issue by Morriz** [grafana/loki#2553]
**Describe the bug**
After upgrading both loki and promtail from 1.5 to 1.6.1 I get an error about table period:
```
invalid schema config: the table period must be a multiple of 24h
```
so the loki pod won't start

**To Reproduce**
1. Started Loki (SHA or version): 1.6.1

using config (that was valid before):
```
auth_enabled: true
chunk_store_config:
  max_look_back_period: 48h
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 15m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 6h
schema_config:
  configs:
  - from: "2018-04-15"
    index:
      period: 6h
      prefix: index_
    object_store: filesystem
    schema: v9
    store: boltdb
server:
  http_listen_port: 3100
storage_config:
  boltdb:
    directory: /data/loki/index
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: true
  retention_period: 48h
```
