### ISSUE TITLE
Promtail: doesn't accept syslog stream from syslog-ng

### ISSUE THREAD

**Issue by secustor** [grafana/loki#2556]
**Describe the bug**
Promtail fails to interpret the syslog stream provided by `syslog-ng` 

**To Reproduce**
1. Setup promtail and syslog-ng following this guide: https://github.com/grafana/loki/blob/v1.5.0/docs/clients/promtail/scraping.md#syslog-receiver
2. Send syslog messages to syslog-ng
3. This leads to warnings in the log of promtail 

```
Aug 26 16:10:25 promtail.example.com promtail[16297]: level=warn ts=2020-08-26T14:10:25.019204216Z caller=syslogtarget.go:176 msg="error parsing syslog stream" err="found EOF after \"<13>1 2020-08-26T16:09:26+02:00 192.168.56.254 .... policytype=\"local-in-policy\" service=\", expecting a SYSLOGMSG containing 8246 octets"
```

**Expected behavior**
I expected promtail to accept the stream and forward it  to loki. 

**Environment:**
 - Infrastructure: VM
 - Deployment tool: Ansible

**Screenshots, Promtail config, or terminal output**
promtail: 
```
  - job_name: syslog
    relabel_configs:
    - source_labels:
      - __syslog_message_hostname
      target_label: fqdn
    syslog:
      idle_timeout: 60s
      label_structured_data: true
      labels:
        job: syslog
      listen_address: 0.0.0.0:1514

``` 

syslog-ng: 
``` 
@version: 3.5
@include "scl.conf"

source s_syslog {
	 tcp( ip(0.0.0.0) port(514) );
    };

destination d_loki {
        syslog("localhost" transport("tcp") port(1514));
    };

log {
	source(s_syslog);
	destination(d_loki);
};
``` 
If applicable, add any output to help explain your problem.
