### ISSUE TITLE
timestamp stage with multiple formats

### ISSUE THREAD

**Issue by aminjam** [grafana/loki#2590]
**Is your feature request related to a problem? Please describe.**
Yes, We consume data that can have multiple types of timestamp formats (RFC3339Nano, Unix, or "2006-01-02 03:04:05.000000000 +0000 UTC"). All timestamps arrive under the same json key but different formats. Currently we inspect the input beforehand, find out the format, and create a unique promtail config for a given selector.

**Describe the solution you'd like**
 It would be ideal to define [multiple formats](https://github.com/grafana/loki/blob/master/docs/sources/clients/promtail/stages/timestamp.md#schema) under `timestamp` stage. timestamp stage would then process each format and if it errors, it would try the next one on the list. An example timestamp stage would look like the following:

```yml
- json:
   expressions:
     timestamp:
- timestamp:
   source: timestamp
   format: RFC339Nano
    fallback_formats:
    - Unix
    - 2006-01-02 03:04:05.000000000 +0000 UTC
```

**Describe alternatives you've considered**
Pre-process the input and create unique promtail configs.
