### ISSUE TITLE
Query-Frontend does not start when running in pull mode

### ISSUE THREAD

**Issue by andersosthus** [grafana/loki#2608]
**Describe the bug**
When starting query-frontend in pull mode, it never goes into ready state. I've discussed this issue a bit with @owen-d as well, so feel free to add anything to this issue :)

**To Reproduce**
Running Loki 1.6.1, microservices deployment. All other components work, and QueryFrontend works when running in push mode (with `downstream_url` setting)

**Expected behavior**
Query-Frontend should start.

**Environment:**
 - Infrastructure: Kubernetes (1.14)
 - Deployment tool: Manual

**Screenshots, Promtail config, or terminal output**
Loki config:
```
server:
  grpc_server_max_concurrent_streams: 100000
  grpc_server_max_connection_age_grace: 5m
  grpc_server_max_connection_age: 2m
  grpc_server_max_connection_idle: 1m
  grpc_server_max_recv_msg_size: 104857600
  http_listen_port: 3100
  http_server_write_timeout: 1m
  log_level: info
auth_enabled: false
distributor:
  ring:
    heartbeat_timeout: 10m
    kvstore:
      store: consul
      prefix: "collectors/"
      consul:
        host: consul.kube-loki.svc.cluster.local:8500
storage_config:
  aws:
    s3: s3://BUCKET/CLUSTER
    dynamodb:
      dynamodb_url: dynamodb://REGION
      metrics:
        url: http://monitoring-prometheus-oper-prometheus.monitoring.svc.cluster.local:9090/prometheus/
        queue_length_query: "sum(avg_over_time(cortex_ingester_flush_queue_length{namespace=\"kube-loki\", job=\"ingester\"}[2m]))"
  index_cache_validity: 14m
  index_queries_cache_config:
    memcached_client:
      host: memcached-index-queries.kube-loki.svc.cluster.local
      service: memcached-client
      timeout: 500ms
chunk_store_config:
  cache_lookups_older_than: 36h
  max_look_back_period: 17472h
  chunk_cache_config:
    memcached_client:
      host: memcached-chunks.kube-loki.svc.cluster.local
      service: memcached-client
      timeout: 500ms
  write_dedupe_cache_config:
    memcached_client:
      host: memcached-index-writes.kube-loki.svc.cluster.local
      service: memcached-client
      timeout: 500ms
ingester:
  chunk_block_size: 262144
  chunk_retain_period: 15m
  chunk_target_size: 1536000
  max_transfer_retries: 60
  lifecycler:
    heartbeat_period: 5s
    join_after: 30s
    num_tokens: 512
    tokens_file_path: /data/tokens
    ring:
      kvstore:
        prefix: "collectors/"
        store: consul
        consul:
          host: consul.kube-loki.svc.cluster.local:8500
frontend_worker:
  frontend_address: query-frontend.kube-loki.svc.cluster.local:9095
  parallelism: 4
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
querier:
  query_ingesters_within: 168h
query_range:
  cache_results: true
  max_retries: 5
  align_queries_with_step: true
  split_queries_by_interval: 15m
  results_cache:
    max_freshness: 10m
    cache:
      memcached_client:
        host: memcached-frontend.kube-loki.svc.cluster.local
        service: memcached-client
        timeout: 500ms
table_manager:
  creation_grace_period: 3h
  poll_interval: 5m
  retention_deletes_enabled: true
  retention_period: 17472h
  index_tables_provisioning:
    enable_ondemand_throughput_mode: false
    provisioned_write_throughput: 500
    provisioned_read_throughput: 500
    enable_inactive_throughput_on_demand_mode: true
    write_scale:
      enabled: true
      min_capacity: 50
      max_capacity: 2000
      out_cooldown: 600
      in_cooldown: 600
    read_scale:
      enabled: true
      min_capacity: 10
      max_capacity: 2000
      out_cooldown: 600
      in_cooldown: 600
limits_config:
  cardinality_limit: 1000000
  enforce_metric_name: false
  ingestion_burst_size_mb: 128
  ingestion_rate_strategy: global
  ingestion_rate_mb: 64
  max_entries_limit_per_query: 100000
  reject_old_samples_max_age: 168h
  reject_old_samples: true
runtime_config:
  file: /etc/loki/overrides.yaml
schema_config:
  configs:
  - from: 2020-01-01
    object_store: s3
    schema: v9
    store: aws
    index:
      period: 168h
      prefix: CLUSTER
  - from: 2020-09-09
    object_store: s3
    schema: v11
    store: aws
    index:
      period: 168h
      prefix: CLUSTER
```

Query-Frontend logs:
```
level=info ts=2020-09-08T21:09:07.496893679Z caller=main.go:124 msg="Starting Loki" version="(version=1.6.1, branch=HEAD, revision=623858df0)"
level=info ts=2020-09-08T21:09:07.497275604Z caller=server.go:194 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=debug ts=2020-09-08T21:09:07.497566925Z caller=modules.go:285 msg="initializing query frontend" config="{Config:{MaxOutstandingPerTenant:100 CompressResponses:true DownstreamURL: LogQueriesLongerThan:5s} TailProxyUrl:}"
level=debug ts=2020-09-08T21:09:07.49771951Z caller=modules.go:290 msg="initializing query range tripperware" config="{Config:{SplitQueriesByInterval:15m0s SplitQueriesByDay:false AlignQueriesWithStep:true ResultsCacheConfig:{CacheConfig:{EnableFifoCache:false DefaultValidity:0s Background:{WriteBackGoroutines:10 WriteBackBuffer:10000} Memcache:{Expiration:0s BatchSize:1024 Parallelism:100} MemcacheClient:{Host:memcached-frontend.kube-loki.svc.cluster.local Service:memcached-client Addresses: Timeout:500ms MaxIdleConns:16 UpdateInterval:1m0s ConsistentHash:true} Redis:{Endpoint: Timeout:100ms Expiration:0s MaxIdleConns:80 MaxActiveConns:0 Password: EnableTLS:false IdleTimeout:0s WaitOnPoolExhaustion:false MaxConnLifetime:0s} Fifocache:{MaxSizeBytes: MaxSizeItems:0 Validity:0s DeprecatedSize:0} Prefix:frontend. Cache:<nil>} LegacyMaxCacheFreshness:10m0s} CacheResults:true MaxRetries:5 ShardedQueries:false}}" limits="{IngestionRateStrategy:global IngestionRateMB:64 IngestionBurstSizeMB:128 MaxLabelNameLength:1024 MaxLabelValueLength:2048 MaxLabelNamesPerSeries:30 RejectOldSamples:true RejectOldSamplesMaxAge:168h0m0s CreationGracePeriod:10m0s EnforceMetricName:false MaxLineSize:0B MaxLocalStreamsPerUser:10000 MaxGlobalStreamsPerUser:0 MaxChunksPerQuery:2000000 MaxQueryLength:0s MaxQueryParallelism:14 CardinalityLimit:1000000 MaxStreamsMatchersPerQuery:1000 MaxConcurrentTailRequests:10 MaxEntriesLimitPerQuery:100000 MaxCacheFreshness:1m0s QuerySplitDuration:0s PerTenantOverrideConfig: PerTenantOverridePeriod:10s}"
level=info ts=2020-09-08T21:09:07.501329385Z caller=module_service.go:58 msg=initialising module=runtime-config
level=info ts=2020-09-08T21:09:07.501638752Z caller=module_service.go:58 msg=initialising module=server
level=debug ts=2020-09-08T21:09:07.501661904Z caller=module_service.go:48 msg="module waiting for initialization" module=query-frontend waiting_for=server
level=info ts=2020-09-08T21:09:07.501685259Z caller=module_service.go:58 msg=initialising module=query-frontend
level=info ts=2020-09-08T21:09:07.501719151Z caller=loki.go:210 msg="Loki started"
level=debug ts=2020-09-08T21:09:15.276688939Z caller=logging.go:57 traceID=128616d978f9a005 msg="GET /metrics (200) 4.801387ms"
level=debug ts=2020-09-08T21:09:23.826811049Z caller=logging.go:57 traceID=3270858ddfaaad16 msg="GET /ready (499) 999.741086ms"
```

Querier logs:
```
level=info ts=2020-09-08T21:14:16.007323068Z caller=main.go:124 msg="Starting Loki" version="(version=1.6.1, branch=HEAD, revision=623858df0)"
level=info ts=2020-09-08T21:14:16.00763018Z caller=server.go:194 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=debug ts=2020-09-08T21:14:16.02013058Z caller=modules.go:146 msg="initializing querier worker" config="{Address:query-frontend.kube-loki.svc.cluster.local:9095 Parallelism:4 MatchMaxConcurrency:false DNSLookupDuration:10s GRPCClientConfig:{GRPC:{MaxRecvMsgSize:104857600 MaxSendMsgSize:16777216 UseGzipCompression:false GRPCCompression: RateLimit:0 RateLimitBurst:0 BackoffOnRatelimits:false BackoffConfig:{MinBackoff:100ms MaxBackoff:10s MaxRetries:10}} TLS:{CertPath: KeyPath: CAPath:}}}"
level=info ts=2020-09-08T21:14:16.021369939Z caller=module_service.go:58 msg=initialising module=store
level=info ts=2020-09-08T21:14:16.023206632Z caller=module_service.go:58 msg=initialising module=server
level=info ts=2020-09-08T21:14:16.023273593Z caller=module_service.go:58 msg=initialising module=runtime-config
level=info ts=2020-09-08T21:14:16.023430573Z caller=module_service.go:58 msg=initialising module=memberlist-kv
level=debug ts=2020-09-08T21:14:16.023489519Z caller=module_service.go:48 msg="module waiting for initialization" module=ring waiting_for=runtime-config
level=debug ts=2020-09-08T21:14:16.023514883Z caller=module_service.go:48 msg="module waiting for initialization" module=querier waiting_for=store
level=debug ts=2020-09-08T21:14:16.023527805Z caller=module_service.go:48 msg="module waiting for initialization" module=querier waiting_for=ring
level=debug ts=2020-09-08T21:14:16.023516191Z caller=module_service.go:48 msg="module waiting for initialization" module=ring waiting_for=server
level=debug ts=2020-09-08T21:14:16.023544564Z caller=module_service.go:48 msg="module waiting for initialization" module=ring waiting_for=memberlist-kv
level=info ts=2020-09-08T21:14:16.023561372Z caller=module_service.go:58 msg=initialising module=ring
level=debug ts=2020-09-08T21:14:16.023758361Z caller=module_service.go:48 msg="module waiting for initialization" module=querier waiting_for=server
level=info ts=2020-09-08T21:14:16.023836932Z caller=module_service.go:58 msg=initialising module=querier
level=info ts=2020-09-08T21:14:16.024247476Z caller=loki.go:210 msg="Loki started"
level=debug ts=2020-09-08T21:14:16.037463482Z caller=worker.go:120 msg="adding connection" addr=10.200.191.28:9095
level=debug ts=2020-09-08T21:14:26.077322516Z caller=logging.go:57 traceID=690f77988ef2dc75 msg="GET /metrics (200) 5.590797ms"
level=debug ts=2020-09-08T21:14:36.600143753Z caller=logging.go:57 traceID=7eceaad79abafa96 msg="GET /ready (200) 67.525µs"
level=debug ts=2020-09-08T21:14:39.693812072Z caller=logging.go:57 traceID=4f3f2c80f7d365fb msg="GET /ready (200) 45.324µs"
```

The IP address the `querier` lists in it's log (`adding connection addr=10.200.191.28:9095`) is the IP of one of the QueryFrontends.
