### ISSUE TITLE
Querier fails on 'failed to initialize table' after upgrade to 1.6.1

### ISSUE THREAD

**Issue by nerbysw** [grafana/loki#2624]
**Describe the bug**
After using upgrading to loki 1.6.1 from 1.5.0 queries to the querier fail with the error "failed to initialize table loki_index_18519, cleaning it up"
I am using a boltdb shipper setup with Azure storage, ingesting data seems to now show any issues, and the download succeeds when reverting back to 1.5.0/

**To Reproduce**
1. Upgraded all deployments/statefulsets to 1.6.1 from 1.5.0 using the config below
2. perform a query to a pod running with target = querier, i.e.: `curl <podip>:8080/loki/api/v1/labels -H "X-Scope-Orgid: <scopeid>"`
3. observe a a 499 status return with the following error message (debug output):

> ts=2020-09-14T13:23:09.110117629Z caller=spanlogger.go:53 org_id=AC2 traceID=1753a4acf7a8f008 method=SeriesStore.LabelNamesForMetricName level=debug metric=logs
ts=2020-09-14T13:23:09.110263228Z caller=spanlogger.go:53 org_id=AC2 traceID=1753a4acf7a8f008 method=SeriesStore.lookupSeriesByMetricNameMatchers level=debug metricName=logs matchers=0
ts=2020-09-14T13:23:09.110300027Z caller=spanlogger.go:53 org_id=AC2 traceID=1753a4acf7a8f008 method=Store.lookupIdsByMetricNameMatcher level=debug metricName=logs matcher=nil
ts=2020-09-14T13:23:09.110338427Z caller=spanlogger.go:53 org_id=AC2 traceID=1753a4acf7a8f008 method=Store.lookupIdsByMetricNameMatcher level=debug matcher=nil queries=16
ts=2020-09-14T13:23:09.110358027Z caller=spanlogger.go:53 org_id=AC2 traceID=1753a4acf7a8f008 method=Store.lookupIdsByMetricNameMatcher level=debug matcher=nil filteredQueries=16
ts=2020-09-14T13:23:09.110425426Z caller=spanlogger.go:53 org_id=AC2 traceID=1753a4acf7a8f008 method=cachingIndexClient.cacheFetch level=debug hits=0 misses=16
ts=2020-09-14T13:23:09.110538725Z caller=spanlogger.go:53 org_id=AC2 traceID=1753a4acf7a8f008 method=Shipper.Downloads.Query level=debug table-name=loki_index_18519
level=info ts=2020-09-14T13:23:09.110558925Z caller=table_manager.go:135 msg="downloading all files for table loki_index_18519"
ts=2020-09-14T13:23:09.111055422Z caller=spanlogger.go:53 org_id=AC2 traceID=1753a4acf7a8f008 method=Shipper.Downloads.Query level=debug table-name=loki_index_18519
-- duplicate lines removed --
ts=2020-09-14T13:23:09.111185321Z caller=spanlogger.go:53 org_id=AC2 traceID=1753a4acf7a8f008 
ts=2020-09-14T13:23:09.112216313Z caller=spanlogger.go:53 org_id=AC2 traceID=1753a4acf7a8f008 method=Shipper.Downloads.Query level=debug table-name=loki_index_18519
ts=2020-09-14T13:23:09.112466411Z caller=spanlogger.go:53 org_id=AC2 traceID=1753a4acf7a8f008 method=Shipper.Downloads.Query level=debug table-name=loki_index_18519
level=debug ts=2020-09-14T13:23:09.232045299Z caller=table.go:126 msg="list of files to download for period loki_index_18519: [{loki_index_18519/loki-ingester-0-1599761453661472641-1600043400 2020-09-14 00:40:54 +0000 GMT} {loki_index_18519/loki-ingester-0-1599761453661472641-1600044300 2020-09-14 01:25:54 +0000 GMT}
-- duplicate lines removed --
{loki_index_18519/loki-ingester-1-1600087016917212841-1600089300 2020-09-14 13:21:57 +0000 GMT}]"
level=info ts=2020-09-14T13:23:09.23718876Z caller=table.go:399 msg="downloaded file loki_index_18519/loki-ingester-0-1599761453661472641-1600073100"
level=info ts=2020-09-14T13:23:09.27786575Z caller=table.go:399 msg="downloaded file loki_index_18519/loki-ingester-0-1599761453661472641-1600079400"
level=info ts=2020-09-14T13:23:09.278055048Z caller=table.go:399 msg="downloaded file loki_index_18519/loki-ingester-1-1599761524034553070-1600047000"
level=info ts=2020-09-14T13:23:09.279331839Z caller=table.go:399 msg="downloaded file loki_index_18519/loki-ingester-0-1599761453661472641-1600069500"
level=info ts=2020-09-14T13:23:09.294481423Z caller=table.go:399 msg="downloaded file loki_index_18519/loki-ingester-0-1599761453661472641-1600052400"
level=error ts=2020-09-14T13:23:09.312476686Z caller=table.go:106 msg="failed to initialize table loki_index_18519, cleaning it up" err="context canceled"
level=error ts=2020-09-14T13:23:09.312542586Z caller=table.go:90 msg="failed to download table" name=loki_index_18519
level=error ts=2020-09-14T13:23:09.312586385Z caller=table_manager.go:113 msg="table loki_index_18519 has some problem, cleaning it up" err="context canceled"
level=error ts=2020-09-14T13:23:09.312612985Z caller=table_manager.go:113 msg="table loki_index_18519 has some problem, cleaning it up" err="context canceled"
-- duplicate lines removed --
level=error ts=2020-09-14T13:23:09.313106681Z caller=table_manager.go:113 msg="table loki_index_18519 has some problem, cleaning it up" err="context canceled"
level=error ts=2020-09-14T13:23:09.313124581Z caller=table_manager.go:113 msg="table loki_index_18519 has some problem, cleaning it up" err="context canceled"
level=error ts=2020-09-14T13:23:09.313178181Z caller=chunk_store.go:541 org_id=AC2 traceID=1753a4acf7a8f008 msg="error querying storage" err="context canceled"
level=debug ts=2020-09-14T13:23:09.313791276Z caller=logging.go:57 traceID=1753a4acf7a8f008 msg="GET /loki/api/v1/labels (499) 209.774201ms"

**Setup/config:**
 - Infrastructure: kubernetes (bare metal/1.19.0) 
 - Deployment tool: manual deployment:

config file (ignore the indent, its a copy/paste from a configmap):
```
   server:
      http_listen_port: 8080

    query_range:
      align_queries_with_step: true
      split_queries_by_interval: 15m
      cache_results: true

    distributor:
      ring:
        kvstore:
          prefix: "loki-collectors/"
          store: etcd
          etcd:
            endpoints:
              - http://etcd-1.etcd:2379
              - http://etcd-2.etcd:2379
              - http://etcd-3.etcd:2379

    ingester:
      lifecycler:
        ring:
          kvstore:
            prefix: "loki-collectors/"
            store: etcd
            etcd:
              endpoints:
                - http://etcd-1.etcd:2379
                - http://etcd-2.etcd:2379
                - http://etcd-3.etcd:2379
          replication_factor: 1
        final_sleep: 10s
      chunk_idle_period: 5m
      chunk_retain_period: 30s


    table_manager:
      retention_period: 840h
      retention_deletes_enabled: true


    frontend:
      log_queries_longer_than: 5s
      downstream_url: http://loki-querier.default.svc.kubernetes.loc:8080
      compress_responses: true

    schema_config:
      configs:
        - from: 2020-09-01 # Update this to the date at which you will start sending data
          store: boltdb-shipper
          object_store: azure
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:

      boltdb_shipper:
        active_index_directory: /var/lib/loki/ingesterdata/index
        shared_store: azure
        cache_location: /tmp/ingesterquerycache

      azure:
        container_name: mycontainer
        account_name: myaccount
        account_key: mykey

    limits_config:
      ingestion_rate_mb: 32
      ingestion_burst_size_mb: 64

```
I can see the downloaded files present on the querier, and on the ingesters. The issue does not seem to occur on the 1.5.0 release.
Any idea what i could be doing wrong?
