### ISSUE TITLE
json.log not preserved with keep-file

### ISSUE THREAD

**Issue by jonkristian** [grafana/loki#2626]
**Describe the bug**
With the loki logging driver the `json.log` is not preserved even though the `keep-file` flag is set to `true`.

**To Reproduce**
1. Start docker container, `docker inspect container_id` reveals `LogPath` and the `json.log` file exists.
2. Re-start the docker container with the following configuration and the `LogPath` is empty and the file `json.log` does not exist:
```
    logging:
      driver: loki
      options:
        loki-url: http://uri-to-loki:3100/loki/api/v1/push
        keep-file: "true"
        loki-retries: "5"
        loki-batch-size: "400"
```

**Expected behavior**
I expected to be able to get a `LogPath` and read the log file on disk.

**Environment:**
 - Ubuntu 18.04.4 LTS (VM)
- Docker version 19.03.6, build 369ce74a3c
- Loki Logging Driver (17.09.0-ce)

Tagging @cyriltovena based on our dialog in slack.
