### ISSUE TITLE
How to filter logs from two kubernetes cluster

### ISSUE THREAD

**Issue by ysaakpr** [grafana/loki#2628]
I had a setup of Loki using tanka as specified in the docs. I installed from tail using the helm chart in two k8s clusters. Which has the same app labels and is there a way to filter the logs from one specific cluster. 

Does promtail/loki adds any cluster identifier to the streams, by any chance ?

**Comment by cyriltovena** [comment]
It does not do that automatically but you can use client external labels in promtail. You just need to configure promtail with a different label in each cluster see: 

https://grafana.com/docs/loki/latest/clients/promtail/configuration/#client_config 

Look for external labels.

**Comment by hhstu** [comment]
# Source: loki-stack/charts/promtail/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-promtail
  namespace: loki
  labels:
    app: promtail
data:
  promtail.yaml: |
    clients:
      - url: http://loki:3100/loki/api/v1/push
    client:
      # look at here 
      external_labels: {cluster: liuchang}
------

**Comment by MazenElzanaty** [comment]
Hi guys,

I did apply this on the configmap, but I don't get any labels in loki. what could be missing?

**Comment by hhstu** [comment]
Have you ever restart every promtail after apply the configmap ? @MazenElzanaty

**Comment by MazenElzanaty** [comment]
Had to modify the helm chart values as below:

```
config:
  lokiAddress: https://lokiURL.com/loki/api/v1/push
  snippets:
    extraClientConfigs: |
      basic_auth:
        username: loki
        password: 026501da64d415ace3
      tenant_id: 1
extraArgs:
  - -client.external-labels=cluster=prod
```

I have an ingress with basic auth, I though I would include that here in case someone needed the same config.
