### ISSUE TITLE
extracted data did not contain a timestamp

### ISSUE THREAD

**Issue by XuCcc** [grafana/loki#2667]
**Describe the bug**

Custom timestamp always fail，can't parse time correct

**To Reproduce**

Loki

```yml
loki, version 1.6.1 (branch: HEAD, revision: 623858df)
  build user:       root@dd6ba3f86fac
  build date:       2020-08-24T19:10:42Z
  go version:       go1.14.2

# Config File

auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 15

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
```

---

Protmail

```yml
promtail, version 1.6.1 (branch: HEAD, revision: 623858df)
  build user:       root@dd6ba3f86fac
  build date:       2020-08-24T19:10:42Z
  go version:       go1.14.2

# Config
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://7.223.137.199:3100/loki/api/v1/push

scrape_configs:
  - job_name: plugin
    pipeline_stages:
      - regex:
          expression: ^(?P<time>\d{4}.{15}).{5}(?P<level>\w+).+$
      - labels:
          level:
      - timestamp:
          source: time
          format: "2006-01-02 15:04:05"
    static_configs:
      - labels:
          job: plugin
          component: engine
          # __path__: /data/secscan_docker_log/2020-08-18/*/workers/*/log/info/*.log
          __path__: a
```

I try it with a demo log like

```
2020-08-18 11:46:24.486 INFO [WorkerProcessMsgTask][MessageHandle.java:208] - Load component jar start
2020-08-18 11:46:25.682 INFO [WorkerProcessMsgTask][MessageHandle.java:243] - file:////home/secScan/components/engin
es/webCrawler.jar
2020-08-18 11:46:25.683 INFO [WorkerProcessMsgTask][MessageHandle.java:273] - Start load class: com.huawei.webcrawle
r.work.WorkRunner
```

**Expected behavior**

Always parse timestamp fail, i'm sure that i write the regex and custom timestamp correct,i also use go to verify this

```go
package main

import (
	"encoding/json"
	"fmt"
	"regexp"
	"time"
)

func main() {

	p := fmt.Println
	t1, _ := time.Parse("2006-01-02 15:04:05", "2020-05-13 14:49:11")
	p(t1)

	re := regexp.MustCompile("^(?P<time>\\d{4}.{15}).{5}(?P<level>\\w+).+$")
	match := re.FindStringSubmatch("2020-05-13 14:49:11.473 INFO [main][Environment.java:109] - Client environment:java.io.tmpdir=/tmp")
	groups :=re.SubexpNames()
	fmt.Printf("%v %v",match,groups)
	result := make(map[string]string)
	for i, name := range groups {
		if i != 0 && name != "" 
			result[name] = match[i]
		}
	}

	prettyResult, _ := json.MarshalIndent(result, "", "  ")

	fmt.Printf("%s\n", prettyResult)
}
```

And it give me the correct output!

**Environment:**

**Screenshots, Promtail config, or terminal output**

Promtail Log

And I find the log

```
level=debug ts=2020-09-24T12:08:15.598806487Z caller=manager.go:226 component=discovery msg="Starting provider" provider=string/0 subs=[plugin]
level=debug ts=2020-09-24T12:08:15.598995884Z caller=manager.go:244 component=discovery msg="Discoverer channel closed" provider=string/0
level=info ts=2020-09-24T12:08:15.599147132Z caller=server.go:194 http=[::]:9080 grpc=[::]:45839 msg="server listening on addresses"
level=info ts=2020-09-24T12:08:15.599404495Z caller=main.go:108 msg="Starting Promtail" version="(version=1.6.1, branch=HEAD, revision=623858df)"
level=debug ts=2020-09-24T12:08:20.599117136Z caller=filetargetmanager.go:231 msg="new target" labels="{__address__=\"localhost\"}"
level=info ts=2020-09-24T12:08:20.599348352Z caller=filetargetmanager.go:285 msg="Adding target" key="{component=\"engine\", job=\"plugin\"}"
level=debug ts=2020-09-24T12:08:20.599591268Z caller=filetarget.go:266 msg="watching new directory" directory=/root/XuPlus
level=debug ts=2020-09-24T12:08:20.59963667Z caller=filetarget.go:300 msg="tailing new file" filename=/root/XuPlus/a
ts=2020-09-24T12:08:20.599953177Z caller=log.go:124 component=tailer level=info msg="Seeked /root/XuPlus/a - &{Offset:0 Whence:0}"
level=info ts=2020-09-24T12:08:20.599879523Z caller=tailer.go:83 component=tailer msg="start tailing file" path=/root/XuPlus/a
level=debug ts=2020-09-24T12:08:20.600164867Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=0 name=regex labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-09-24T20:08:20.600049898+08:00 entry="2020-08-18 11:46:24.486 INFO [WorkerProcessMsgTask][MessageHandle.java:208] - Load component jar start"
level=debug ts=2020-09-24T12:08:20.600725615Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=1 name=timestamp labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-09-24T20:08:20.600049898+08:00 entry="2020-08-18 11:46:24.486 INFO [WorkerProcessMsgTask][MessageHandle.java:208] - Load component jar start"
level=debug ts=2020-09-24T12:08:20.600835663Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=2 name=labels labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-08-18T11:46:24Z entry="2020-08-18 11:46:24.486 INFO [WorkerProcessMsgTask][MessageHandle.java:208] - Load component jar start"
level=debug ts=2020-09-24T12:08:20.600900181Z caller=pipeline.go:113 component=file_pipeline component=pipeline msg="finished processing log line" labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\", level=\"INFO\"}" time=2020-08-18T11:46:24Z entry="2020-08-18 11:46:24.486 INFO [WorkerProcessMsgTask][MessageHandle.java:208] - Load component jar start" duration_s=0.00074439
level=debug ts=2020-09-24T12:08:20.6010412Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=0 name=regex labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-09-24T20:08:20.600213214+08:00 entry="2020-08-18 11:46:25.682 INFO [WorkerProcessMsgTask][MessageHandle.java:243] - file:////home/secScan/components/engin"
level=debug ts=2020-09-24T12:08:20.601100621Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=1 name=timestamp labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-09-24T20:08:20.600213214+08:00 entry="2020-08-18 11:46:25.682 INFO [WorkerProcessMsgTask][MessageHandle.java:243] - file:////home/secScan/components/engin"
level=debug ts=2020-09-24T12:08:20.601159451Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=2 name=labels labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-08-18T11:46:25Z entry="2020-08-18 11:46:25.682 INFO [WorkerProcessMsgTask][MessageHandle.java:243] - file:////home/secScan/components/engin"
level=debug ts=2020-09-24T12:08:20.601204964Z caller=pipeline.go:113 component=file_pipeline component=pipeline msg="finished processing log line" labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\", level=\"INFO\"}" time=2020-08-18T11:46:25Z entry="2020-08-18 11:46:25.682 INFO [WorkerProcessMsgTask][MessageHandle.java:243] - file:////home/secScan/components/engin" duration_s=0.000166162
level=debug ts=2020-09-24T12:08:20.601276363Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=0 name=regex labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-09-24T20:08:20.601086607+08:00 entry=es/webCrawler.jar
level=debug ts=2020-09-24T12:08:20.601323645Z caller=regex.go:120 component=file_pipeline component=stage type=regex msg="regex did not match" input=es/webCrawler.jar regex=^(?P<time>\d{4}.{15}).{5}(?P<level>\w+).+$
level=debug ts=2020-09-24T12:08:20.601366831Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=1 name=timestamp labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-09-24T20:08:20.601086607+08:00 entry=es/webCrawler.jar
level=debug ts=2020-09-24T12:08:20.601410427Z caller=timestamp.go:159 component=file_pipeline msg="extracted data did not contain a timestamp"
level=debug ts=2020-09-24T12:08:20.601450262Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=2 name=labels labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-08-18T11:46:25.000000001Z entry=es/webCrawler.jar
level=debug ts=2020-09-24T12:08:20.601491829Z caller=pipeline.go:113 component=file_pipeline component=pipeline msg="finished processing log line" labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-08-18T11:46:25.000000001Z entry=es/webCrawler.jar duration_s=0.000216628
level=debug ts=2020-09-24T12:08:20.601561467Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=0 name=regex labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-09-24T20:08:20.601365781+08:00 entry="2020-08-18 11:46:25.683 INFO [WorkerProcessMsgTask][MessageHandle.java:273] - Start load class: com.huawei.webcrawle"
level=debug ts=2020-09-24T12:08:20.601618049Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=1 name=timestamp labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-09-24T20:08:20.601365781+08:00 entry="2020-08-18 11:46:25.683 INFO [WorkerProcessMsgTask][MessageHandle.java:273] - Start load class: com.huawei.webcrawle"
level=debug ts=2020-09-24T12:08:20.601674644Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=2 name=labels labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-08-18T11:46:25Z entry="2020-08-18 11:46:25.683 INFO [WorkerProcessMsgTask][MessageHandle.java:273] - Start load class: com.huawei.webcrawle"
level=debug ts=2020-09-24T12:08:20.601768699Z caller=pipeline.go:113 component=file_pipeline component=pipeline msg="finished processing log line" labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\", level=\"INFO\"}" time=2020-08-18T11:46:25Z entry="2020-08-18 11:46:25.683 INFO [WorkerProcessMsgTask][MessageHandle.java:273] - Start load class: com.huawei.webcrawle" duration_s=0.000208869
level=debug ts=2020-09-24T12:08:20.601841651Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=0 name=regex labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-09-24T20:08:20.601642948+08:00 entry=r.work.WorkRunner
level=debug ts=2020-09-24T12:08:20.601886243Z caller=regex.go:120 component=file_pipeline component=stage type=regex msg="regex did not match" input=r.work.WorkRunner regex=^(?P<time>\d{4}.{15}).{5}(?P<level>\w+).+$
level=debug ts=2020-09-24T12:08:20.601913519Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=1 name=timestamp labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-09-24T20:08:20.601642948+08:00 entry=r.work.WorkRunner
level=debug ts=2020-09-24T12:08:20.601973434Z caller=timestamp.go:159 component=file_pipeline msg="extracted data did not contain a timestamp"
level=debug ts=2020-09-24T12:08:20.602020783Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=2 name=labels labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-08-18T11:46:25.000000001Z entry=r.work.WorkRunner
level=debug ts=2020-09-24T12:08:20.602065541Z caller=pipeline.go:113 component=file_pipeline component=pipeline msg="finished processing log line" labels="{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}" time=2020-08-18T11:46:25.000000001Z entry=r.work.WorkRunner duration_s=0.000224948
level=error ts=2020-09-24T12:08:21.700993171Z caller=client.go:250 component=client host=7.223.137.199:3100 msg="final error sending batch" status=400 error="server returned HTTP status 400 Bad Request (400): entry for stream '{component=\"engine\", filename=\"/root/XuPlus/a\", job=\"plugin\"}' has timestamp too old: 2020-08-18 11:46:25.000000001 +0000 UTC"
^Clevel=info ts=2020-09-24T12:09:52.435333324Z caller=signals.go:55 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=info ts=2020-09-24T12:09:52.435620429Z caller=filetargetmanager.go:346 msg="Removing target" key="{component=\"engine\", job=\"plugin\"}"
level=info ts=2020-09-24T12:09:52.435814024Z caller=tailer.go:163 component=tailer msg="stopped tailing file" path=/root/XuPlus/a
level=debug ts=2020-09-24T12:09:52.435843812Z caller=filetarget.go:167 msg="watcher closed, tailer stopped, positions saved"
level=debug ts=2020-09-24T12:09:52.436032782Z caller=positions.go:147 msg="positions saved"
```
