### ISSUE TITLE
The Capability to Use External Labels in Promtail Relabling

### ISSUE THREAD

**Issue by midnightconman** [grafana/loki#2683]
**Describe the solution you'd like**
I would like the ability to use the static external labels I have set in promtail in my relabling stages. My main use case is for constructing a tenant id that will be specific to an individual kubernetes cluster in my fleet of k8s clusters.

**Describe alternatives you've considered**
An alternative I thought about would be the capability to use a static value in addition to the `source` field in the `tenant` stage.

**Comment by midnightconman** [comment]
At the moment to achieve this I am creating a new label called `tenant`, where I add my kubernetes cluster id as a static value via the `replacement` field in the replace action. Something like this:

```
- action: replace
  replacement: "$1/<cluster-hash>"
  source_labels:
  - __meta_kubernetes_namespace
```

I want both the namespace and the cluster, so I can quota production clusters with different values than other clusters.

If I had the above mentioned capability, I wouldn't have to manage the static replacement... I could do something like this:

```
client:
  external_labels:
    cluster: <cluster-hash>
...
- action: replace
  replacement: "$1"
  separator: "/"
  source_labels:
  - __meta_kubernetes_namespace
  - __external_labels_cluster
```
