### ISSUE TITLE
EC2 Service Discovery Not Working with Systemd Journal

### ISSUE THREAD

**Issue by brianpham** [grafana/loki#2707]
**Describe the bug**
EC2 Service Discovery does not work with systemd-journal in promtail configuration. 

This block of code will not work, but doesn't return any errors. Journal never get sent to Loki. If I remove the ec2_sd_config block it will work properly. 

Adding the `ec2_sd_configs` block does not work. 
```
scrape_configs:
  - job_name: systemd-journal
    ec2_sd_configs:
      - refresh_interval: 30s
    journal:
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__meta_ec2_instance_id']
        target_label: instance
        action: replace
```

**To Reproduce**
1. Create a simple scrape config for systemd-journal. Promtail is running 1.6.1.
2. Add ec2_sd_config and try to add __meta_ec2_instance_id relabel
3. Promtail will start properly, but never indicate error in logs.
4. Targets on the UI will never show up as healthy

**Expected behavior**
Systemd journal should be sent to Loki along with the instance label. Or if it fails, we should see an error why the journal is not being sent to Loki. 

**Screenshots, Promtail config, or terminal output**
Promtail Config
```
server:
  grpc_listen_port: 0
  http_listen_port: 9080
  log_level: info
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://promtail-push.demisto.tools:3500/loki/api/v1/push
scrape_configs:
  - job_name:server-logs
    ec2_sd_configs:
      - refresh_interval: 30s
    relabel_configs:
      - source_labels: ['__meta_ec2_tag_Name']
        target_label: name
        action: replace
      - source_labels: ['__meta_ec2_instance_id']
        target_label: instance
        action: replace
      - source_labels: ['__meta_ec2_availability_zone']
        target_label: zone
        action: replace
      - action: replace
        replacement: /var/log/**.log
        target_label: __path__
      - source_labels: ['__meta_ec2_private_dns_name']
        regex: "(.*)"
        target_label: __host__
  - job_name: systemd-journal
    ec2_sd_configs:
      - refresh_interval: 30s
    journal:
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__meta_ec2_instance_id']
        target_label: instance
        action: replace
```

systemd-journal targets is not healthy when adding ec2_sd_config block
<img width="826" alt="Screen Shot 2020-10-01 at 11 59 10 AM" src="https://user-images.githubusercontent.com/5695495/94859935-30bf3500-03ea-11eb-859d-d237ee32945c.png">

**Comment by brianpham** [comment]
I am able to see systemd-journal using this block, but I want to be able to add an instance_id label to it so that I can filter off of it using something like {instance: id-01, unit:kafka.service}. 

```
  - job_name: systemd-journal
    journal:
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
```
