### ISSUE TITLE
Loki's query timeout is not working as expected

### ISSUE THREAD

**Issue by Hiro1976** [grafana/loki#2715]
I am using a helm and using loki-stack-0.32.0 (Grafana 6.5.2 , Loki 1.3.0).

I have been querying Loki from Grafana.  
Sometimes users make long-duration or data-intensive queries, which can consume a lot of Loki's resources.  
To prevent this from happening, I'm thinking of setting a timeout for queries with long response times.  

However, the timeout I have set for Loki is not working as expected.  

The loki-stack.yaml is set up as follows  
```
loki:
  enabled: true

- snip - 

  config:
    querier:
      query_timeout: 5s
      engine:
        timeout: 10s

```

Check the POD settings and make sure they are set up correctly.

```
[admin@change-rhel781 ~]$ kubectl -n loki-stack exec hoge-loki-0 -- cat /etc/loki/loki.yaml
- snip -

querier:
  engine:
    timeout: 10s
  query_timeout: 5s

- snip -
```

The following logs are from grafana.  
I accessed a query with a long response time from grafana.  
To measure the elapsed time, we switched to another screen after about 15 seconds.  

`t=2020-10-02T06:42:42+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/2/api/v1/query_range status=502 remote_addr=192.168.19.1 time_ms=15516 size=0 referer="https://hoge.hoge.com/d/1ms07fFGk/test1?orgId=1&from=now-30d&to=now"`

If the Loki configuration is working as expected, we expect to be disconnected from Loki in 5 or 10 seconds.  

Isn't this a bug?
