### ISSUE TITLE
Promtail ignores static label in match stage

### ISSUE THREAD

**Issue by krewi1** [grafana/loki#2721]
**Describe the bug**
When i define match stage and which has nested labels stage promtail ignores static labels

**To Reproduce**
1. Started Loki (grafana/loki:1.6.1)
2. Started Promtail (grafana/promtail:1.6.1) to tail '...'
3. Define match stage 
```
- match: 
          selector: '{app="test"} |= "TEXTTOMATCH"'
          stages:
          - labels:
              job_log: 1
```
4. Label job_log is not added to targeted log

**Expected behavior**
Label job_log is added to logline

**Environment:**
 - kubernetes

**Workaround**
```
- match: 
          selector: '{app="test"} |= "TEXTTOMATCH'
          stages:
          - regex:
              expression: "^(?P<job_log>TEXTTOMATCH)"
          - template:
              source: job_log 
              template: '{{ if .Value }}{{ "1" }}{{ else }}{{ "" }}{{ end }}'
          - labels:
              job_log:
```

**Comment by slim-bean** [comment]
The label stage cannot create a label with arbitrary content, it can only create a label with a value from data in the pipelines extracted data map.

Typical behavior is to extract the value with regex or json and then use the extract value in a label.

The workaround you suggested using the template stage is the only way to insert arbitrary content into the label.

I don't think you need the `regex` stage however, you should only need the match stage with selector and then the template stage can probably be simplified

```
- match: 
          selector: '{app="test"} |= "TEXTTOMATCH'
          stages:
          - template:
              source: job_log 
              template: '1'
          - labels:
              job_log:
```

Something like this ^^ i think should work.
