### ISSUE TITLE
promtail locking unexpected files

### ISSUE THREAD

**Issue by betorvs** [grafana/loki#2743]
**Describe the bug**
I deployed promtail in some freebsd machines and create a static-config to scrape only one file:

```
scrape_configs:
 - job_name: system
   pipeline_stages:
   static_configs:
   - targets:
      - localhost
     labels:
      job: elasticlogs
      host: server02
      __path__: /usr/jails/shared/kibana/elasticsearch_collector.log
```

but when I tried to free some space in that machine, it blocks auditd.log too and others files there. 

```
# procstat -f  85481 | grep kibana
85481 promtail            10 v d r----n--  2       0 -   /usr/jails/shared/kibana
85481 promtail            11 v r r----n--  2       0 -   /usr/jails/shared/kibana/all.log
85481 promtail            12 v r r----n--  2       0 -   /usr/jails/shared/kibana/auditd.log
85481 promtail            13 v r r----n--  2       0 -   /usr/jails/shared/kibana/elasticsearch_collector.log
85481 promtail            15 v r r-------  1 43910869089 -   /usr/jails/shared/kibana/elasticsearch_collector.log
```

is this expected? 

**To Reproduce**
1. Started Promtail (SHA or version) to tail '...' version: Using `static_configs` and looking for only one file.
Promtail version for reference:
```
# /usr/local/promtail/promtail --version
promtail, version 1.6.1 (branch: HEAD, revision: 623858df)
  build user:       root@dd6ba3f86fac
  build date:       2020-08-24T19:10:42Z
  go version:       go1.14.2
```

2. Try to delete one file not related to `__path__:` and check if it releases disk space.

**Expected behavior**
It blocks only files describe in `__path__:` and it should only read and lock one specific file.

**Environment:**
 - Infrastructure:  bare-metal but can be a virtual machine with freebsd
 - Deployment tool:  just run promtail and check lock files using `procstat -f $PID` with promtail pid.
