### ISSUE TITLE
Promtail: `output` stage supports multiple sources

### ISSUE THREAD

**Issue by kazukousen** [grafana/loki#2744]
currently, the output stage can only take just one of data from extracted map.

```yaml
- json:
    expressions:
      user: user
      message: message
      request_id: request_id
- labels:
    user:
- output:
    source: message # just one
```

I would like to new log line which composed the json format from multiple fields.
(in the above example, `{"message": .., "request_id": ..}`)
i think that it can be achieved by adding a richer interface like `output.json`.

```yaml
- output:
    json:
      message: message
      request_id: request_id
```

If you can tolerate this, I can work on the patch.

Thanks.
