### ISSUE TITLE
Log lines for multi-line logs (Exceptions) are split into multiple log messages

### ISSUE THREAD

**Issue by calbot** [grafana/loki#2747]
**Describe the bug**
Log lines for multi-line logs (Exceptions) are split into multiple log messages

**To Reproduce**
Using the docker loki logging driver

**Expected behavior**
Log messages with multi-line logs come out as a single message

**Environment:**
Docker

I've used other loki connections where the multi-line logs are preserved and it works better that way since the order of stacktraces are preserved in the viewer as well as the context of each stack trace line being more apparent.

**Comment by colben** [comment]
Did you use promtail to prospect logs ? 
Can you paste the config of promtail here ?

**Comment by calbot** [comment]
Not using promtail.
Using the docker plugin "loki logging driver"

Setup like this...
```
x-logging:
  &loki-logging
  driver: loki
  options:
    loki-url: "http://<my-url>:3100/loki/api/v1/push"

services:
  api:
...
    logging: *loki-logging
```
