### ISSUE TITLE
Log data vanishing 

### ISSUE THREAD

**Issue by colmtroy** [grafana/loki#2749]
I setup Loki yesterday - everything went fine. Today I'm noticing that for some of my higher volume logs, data has vanished. In some cases I only have 1 hour of data. 

Is it to do with my schema config? (data currently stored in filesystem in /tmp/loki as per default sample config.
Or have I done something wrong with my promtail config?

**To Reproduce**
1. Started Loki / Promtail with configs below
2. Display output from logs in Grafana
3. Check same output 12 hours later - data now gone (and only showing last hour of data in some cases - some show more)

**Expected behavior**
I expect all log data to be retained

**Environment:**
Infrastructure: Loki server - Ubuntu 18.04 VM (local binary install)
loki, version 1.6.1 (branch: HEAD, revision: 623858df)
  build user:       root@dd6ba3f86fac
  build date:       2020-08-24T19:10:42Z
  go version:       go1.14.2

Promtail client machine - Ubuntu 16.04 VM (local binary install)
promtail, version 1.6.1 (branch: HEAD, revision: 623858df)
  build user:       root@dd6ba3f86fac
  build date:       2020-08-24T19:10:42Z
  go version:       go1.14.2

**Screenshots, Promtail config, or terminal output**

Promtail config:
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://<<snip>>/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: nginx
  entry_parser: raw
  static_configs:
    - targets:
        - localhost
      labels:
        job: nginx
        host: vult1-mic
        __path__: /var/log/nginx/*log
  pipeline_stages:
  - match:
      selector: '{job="nginx"}'
      stages:
      - regex:
          expression: '^(?P<remote_addr>[\w\.]+) - (?P<remote_user>[^ ]*) \[(?P<time_local>.*)\] "(?P<method>[^ ]*) (?P<request>[^ ]*) (?P<protocol>[^ ]*)" (?P<status>[\d]+) (?P<body_bytes_sent>[\d]+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"?'
      - labels:
          #remote_addr:
          #remote_user:
          #time_local:
          method:
          #request:
          #protocol:
          status:
          #body_bytes_sent:
          #http_referer:
          #http_user_agent:
- job_name: phpworkers
  entry_parser: raw
  static_configs:
    - targets:
        - localhost
      labels:
        job: phpworkers
        host: vult1-mic
        __path__: /var/log/php7.*-fpm.log
  pipeline_stages:
  - match:
      selector: '{job="phpworkers"}'
      stages:
      - regex:
          expression: '^(?P<time>\[[^\]]+?\]) (?P<error_type>\w*:) (?P<pool>\[[^\]]+?\])'
      - labels:
          error_type:
          pool:

```

Loki config:

```
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

```
