### ISSUE TITLE
Documentation: config for ingester/distributor memberlist is invalid

### ISSUE THREAD

**Issue by zswanson** [grafana/loki#2754]
**Describe the bug**
https://grafana.com/docs/loki/latest/configuration/#ingester_config
https://grafana.com/docs/loki/latest/configuration/#distributor_config

Current documentation for the ingester and distributor config describes the ring config as:
```
lifecycler:
  ring:
    kvstore:
      # Backend storage to use for the ring. Supported values are: consul, etcd,
      # inmemory, memberlist
      # CLI flag: -ring.store
      [store: <string> | default = "consul"]

      # The prefix for the keys in the store. Should end with a /.
      # CLI flag: -ring.prefix
      [prefix: <string> | default = "collectors/"]

      # The consul_config configures the consul client.
      # CLI flag: <no prefix>
      [consul: <consul_config>]

      # The etcd_config configures the etcd client.
      # CLI flag: <no prefix>
      [etcd: <etcd_config>]

      # Configuration for Gossip memberlist. Only applies if store is "memberlist"
      # CLI flag: <no prefix>
      [memberlist: <memberlist_config>]
```

The `memberlist` element in that heirarchy is incorrect, and will cause loki to err at startup with an invalid config. `memberlist` is actually a root level element and is defined once and then referenced with `store: memberlist` in the distributor and ingester configurations. While I have not tested it, I imagine the same holds true for consul and etcd configs.

**Expected behavior**
Documentation should be adjusted to add memberlist as a root element, and remove the definition from the distributor_config and ingester_config sections.

**Comment by kirooshu** [comment]
We had the same problem, the documentation is wrong and seems like it would be great to fix.

**Comment by james-callahan** [comment]
I ran into this today.

I'm curious which components will have the memberlist port bound and should be listed in `join_members`. Currently I have:
```yaml
memberlist:
    join_members:
      - distributor
      - ingester
```
However I have the suspicion that e.g. `querier` could be added to that list.
