### ISSUE TITLE
Horizontal scaling of the filesystem store

### ISSUE THREAD

**Issue by gtorre** [grafana/loki#2757]
### Introduction
Hello, we are currently running Loki in Kubernetes, ingesting 1.5TB of data per day. We currently double write logs to both Loki and our ELK stack (so we are able to compare log volume/log data between clusters.) We have implemented the experimental boltdb-shipper feature to horizontally scale Loki using the filesystem for storage. We have NVMe disks for this purpose. The issue we were observing was missing/inconsistent data in queries. We started out using the boltdd-shipper but gradually changed/added various components of the Loki stack in hopes of narrowing down the problem. First we switched over to Minio for chunk storage, but continued to see the problem. We then moved to Cassandra for index storage, and have not seen the issue yet.

We've run ELK for a little over four years but we are very interested in Loki because we believe it has a lot of potential.

Although Minio/Cassandra seems to be working, our optimal solution would be to have everything on the filesystem, so boltdb-shipper would be our path forward to production.

We are **very** interested and motivated in making this work, and our team is ready to help anytime to provide debugging information you may need.

### Configuration and how to reproduce the issue
1. Started Loki 1.6.1 (6 loki pods with replication factor of 3, up from 3 pods initially)
2. Fluentd ships logs from our baremetal servers
3. Query: `sum(count_over_time({collins_pool="INTERNAL_POOL"}[1m])) by (host)`

Our configuration:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: logging
  name: loki-runtime-config
  labels:
    app: loki
data:
  loki-runtime.yaml: |
    overrides:
      docker:
        max_chunks_per_query: 100000
      syslog:
        max_chunks_per_query: 100000
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: logging
  name: loki-config
  labels:
    app: loki
data:
  loki.yaml: |
    auth_enabled: true

    chunk_store_config:
      max_look_back_period: 0s # No limit how far we can look back in the store
      chunk_cache_config:
        memcached_client:
          host: memcached
          timeout: 1s
          consistent_hash: true
        memcached:
          expiration: 90s
          batch_size: 100
          parallelism: 100
      write_dedupe_cache_config:
        memcached_client:
          host: memcached-index-writes
          timeout: 1s
          consistent_hash: true
        memcached:
          batch_size: 100
          parallelism: 100

    ingester:
      max_transfer_retries: 0 # Disable blocks transfers on ingesters shutdown or rollout.
      chunk_encoding: lz4
      chunk_target_size: 1572864
      chunk_block_size: 262144
      chunk_idle_period: 2h # Let chunks sit idle for at least 2h before flushing, this helps to reduce total chunks in store
      max_chunk_age: 2h  # Let chunks get at least 2h old before flushing due to age, this helps to reduce total chunks in store
      query_store_max_look_back_period: -1  # This will allow the ingesters to query the store for all data
      chunk_retain_period: 30s
      lifecycler:
        heartbeat_period: 5s
        join_after: 30s
        num_tokens: 512
        ring:
          heartbeat_timeout: 1m
          kvstore:
            store: memberlist
          replication_factor: 3 # The number of ingesters to write to and read from.

    memberlist:
      abort_if_cluster_join_fails: false
      # Expose this port on all distributor, ingester
      # and querier replicas.
      bind_port: 7946
      # You can use a headless k8s service for all distributor,
      # ingester and querier components.
      join_members:
      - loki-gossip-ring.logging.svc:7946
      max_join_backoff: 1m
      max_join_retries: 10
      min_join_backoff: 1s

    frontend_worker:
      frontend_address: "loki-query-frontend.logging.svc:9095"

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 24h
      ingestion_rate_mb: 100 # Per-user ingestion rate limit in sample size per second. Units in MB.
      ingestion_burst_size_mb: 12 # Per-user allowed ingestion burst size (in sample size). Units in MB.
      max_streams_per_user: 0
      max_global_streams_per_user: 0

    schema_config:
      configs:
      - from: "2018-04-15"
        index:
          period: 24h
          prefix: index_
        store: boltdb-shipper
        object_store: filesystem
        schema: v11 # The schema version to use, current recommended schema is v11.

    server:
      http_listen_port: 3100
      grpc_server_max_recv_msg_size: 8388608
      grpc_server_max_send_msg_size: 8388608

    storage_config:
      boltdb_shipper:
        shared_store: filesystem
        active_index_directory: /data/loki/index
        cache_location: /data/loki/boltdb-cache
      filesystem:
        directory: /data/loki/chunks
      index_queries_cache_config:
        memcached_client:
          host: memcached-index-queries
          timeout: 1s
          consistent_hash: true
        memcached:
          expiration: 90s
          batch_size: 100
          parallelism: 100

    table_manager:
      retention_deletes_enabled: true
      retention_period: 48h
```

### Expected behavior
Present and consistent query results.

### Environment
 - Infrastructure: Kubernetes
 - Deployment tool: Kubernetes manifests deployed via a Jenkins pipeline.

### Screenshots
The screenshot below shows two identical servers. Our expectation is that the log volume be identical. However, you can see that in this particular screenshot one server is reporting zero logs during several time frames. On subsequent refreshes, the values change dramatically. The data is inconsistent and unreliable.
<img width="1842" alt="Screen Shot 2020-10-05 at 10 40 41 AM" src="https://user-images.githubusercontent.com/5504515/95931057-290e7180-0d96-11eb-8a78-98fe528b8011.png">
