### ISSUE TITLE
promtail entry out of order when sending to loki

### ISSUE THREAD

**Issue by SunSparc** [grafana/loki#2798]
**Describe the bug**
When `promtail` sends log lines to `loki` it reports the following:
```
level=error
ts=2020-10-23T22:07
caller=client.go:250
component=client
host=loki.server:3100
msg="final error sending batch"
status=400
error="server returned HTTP status 400 Bad Request (400):
    entry with timestamp 2020-10-23 22:07:01 ignored, reason: 'entry out of order' for stream:
    {datacenter=\"east\", env=\"live\", filename=\"/var/log/haproxy.log\", job=\"haproxy\", status=\"200\"},"
```

**To Reproduce**
1. Started Loki on a standalone server:
```
loki, version 1.6.1 (branch: HEAD, revision: 623858df)
  build user:       root@dd6ba3f86fac
  build date:       2020-08-24T19:10:42Z
  go version:       go1.14.2
```
2. Started `promtail` as a sidecar to an `haproxy` multi-tenant kubernetes deployment (3 instances running at the same time).
`"Starting Promtail" version="(version=1.6.1, branch=HEAD, revision=623858df0)"`
3. Started sending `http` traffic to `haproxy`.

**Expected behavior**
Expected `loki` to be able to ingress the traffic from multiple `promtail` instances. The `tenant_id` field was set specifically on each instance and the values were unique.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: `kubectl`

**Promtail config**

haproxy/promtail server 1:
```
# head /promtail.yaml
    clients:
      - url: http://loki.server:3100/loki/api/v1/push
        tenant_id: haproxy-deploy-5544cbccdc-w4pqf
    positions:
      filename: /tmp/positions.yaml
    server:
      disable: false
      http_listen_port: 9080
      grpc_listen_port: 0
```

haproxy/promtail server 2:
```
# head /promtail.yaml
    clients:
      - url: http://loki.server:3100/loki/api/v1/push
        tenant_id: haproxy-deploy-5544cbccdc-hl2gv
    positions:
      filename: /tmp/positions.yaml
    server:
      disable: false
      http_listen_port: 9080
      grpc_listen_port: 0
```

haproxy/promtail server 3:
```
# head /promtail.yaml
    clients:
      - url: http://loki.server:3100/loki/api/v1/push
        tenant_id: haproxy-deploy-5544cbccdc-7rns7
    positions:
      filename: /tmp/positions.yaml
    server:
      disable: false
      http_listen_port: 9080
      grpc_listen_port: 0
```

**Comment by slim-bean** [comment]
Hey @SunSparc! What's your loki config look like?

**Comment by SunSparc** [comment]
Mostly just the default. Still working through what the needs are for my systems.

```
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
```

**Comment by slim-bean** [comment]
thanks!

I see you are setting the `tenant_id` field in promtail

So I have a few questions, is your intention that each of your promtail sends to a different tenant in Loki?

If yes then you need to change this:

```
auth_enabled: false
```

to

```
auth_enabled: true
```

If you aren't looking to use multiple tenants, then you need to make sure each promtail has some unique identifier as a label so that they don't all send the exact same stream to Loki, if you paste your entire promtail config we can give some pointers but this is usually done with `external-labels` or `labels` in the scrape-config section.

**Comment by SunSparc** [comment]
@slim-bean, that is good to know. I am wanting multiple tenants because the machines being tailed are haproxy load-balancers all serving traffic for the same pool of backend services. Reading through the documentation and other reports lead me to believe that `tenant_id` was the way to go for this scenario. I did not realize that `auth_enable` also needed to be changed to `true`. I had misunderstood what `auth_enable` was for.

Currently my `promail.yaml` is very basic.

```
clients:
  - url: http://10.5.4.3:3100/loki/api/v1/push
    tenant_id: <unique-hostname>
positions:
  filename: /tmp/positions.yaml
server:
  disable: false
  http_listen_port: 9080
  grpc_listen_port: 0

target_config:
  sync_period: 10s

scrape_configs:
- job_name: haproxy
  static_configs:
    - targets:
        - localhost
      labels:
        job: haproxy
        __path__: /var/log/haproxy.log

  pipeline_stages:
  - regex:
      expression: ^.* (?P<status>\d{3}) "(?P<request>.*?)" .*$
  - labels:
      status:
  - match:
      selector: '{status="200"} |~"GET .federate.match"'
      action: drop
      drop_counter_reason: "federate"
```
