### ISSUE TITLE
Loki to have external label as clustername

### ISSUE THREAD

**Issue by chahalamit009** [grafana/loki#2821]
I'm not able to make loki pickup the clustername as the tag for the alerts .

`---
config:
  client:
    external_labels:
      clusterName:  {$CLUSTER_NAME}`

This doesnt use the clustername instead picks it as a string

**Comment by cyriltovena** [comment]
The config file doesn't expand environment variable. The command line args in docker does though.

```
-client.external-labels=clusterName=$(CLUSTER_NAME)
```

**Comment by chahalamit009** [comment]
Can you give me an example for this

**Comment by maohsiang** [comment]
> Can you give me an example for this

In promtail we can use the following setting to attach extra label to each log message.
```
      - promtail:
          config:
            client:
              external_labels:
                cluster: {{ .Values.cluster }}
```
so I wonder do we have the same config for alerting_groups ?
it should be like
```
- loki:
    alerting_groups:
       external_labels:
           cluster: {{ .Values.cluster }}
```
