### ISSUE TITLE
max entries limit per query exceeded

### ISSUE THREAD

**Issue by darox** [grafana/loki#2854]
**Describe the bug**
Although I have increased the value of parameter max_entries_limit_per_query to 50000000000. It seems I'm hitting some limitations and encounter error:
![image](https://user-images.githubusercontent.com/9934402/97679935-36b23f80-1a96-11eb-9bc6-6c78f7b8583d.png)

**To Reproduce**
Configure and setup the environment according to: https://grafana.com/grafana/dashboards/12559

**Expected behavior**

**Environment:**
 - Infrastructure: Docker on Ubuntu 18.04
- Loki docker image: sha256:72e624086a81c6e6ba7608979e3248335aa89438f61c35cea1e5ef4e79e0a36c
- Grafana docker image: sha256:a09efac722769326f99ea33f6d961592ff048f23a1be23cd4bbfe6bcaa557bd6
- Nginx docker image: sha256:026db43f52eb7e67906585b615d37cd3b4f9dea3485289dbc1a9c626bce56278

**Screenshots, Promtail config, or terminal output**
```
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2020-05-15
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  max_entries_limit_per_query: 50000000000
```
