### ISSUE TITLE
Access denied from table_manager.go when trying to sync tables to S3

### ISSUE THREAD

**Issue by ckacbot** [grafana/loki#2868]
**Describe the bug**
Access denied from table_manager.go when trying to sync tables even though we have granted full permissions to the specified S3 bucket
We have tried to configure loki to ship logs via boltdb-shipper to S3. We run Loki on Fargate and tried to piece together a working config for this purpose. We have not found a complete example and the documention does not seem to be updated, no mention of 'storage_config->boltdb_shipper' exist on: https://grafana.com/docs/loki/latest/configuration/. (The boltdb_shipper config block is mentioned in other places, but not with an S3 example)
We have successfully used Loki together with DynamoDB so the task role has worked previously.

**To Reproduce**
1. Start Loki (2.0.0) with boltdb-shipper config, monitor logs

**Expected behavior**
Ship logs to s3
**Environment:**
 - Infrastructure: ECS Fargate
 - Deployment tool: Terraform

**Screenshots, Promtail config, or terminal output**

Log:
```
1604413944819,"level=info ts=2020-11-03T14:32:24.819211191Z caller=loki.go:227 msg=""Loki started"""
1604413944819,"level=info ts=2020-11-03T14:32:24.819943846Z caller=table_manager.go:324 msg=""synching tables"" expected_tables=126"
1604413944904,"level=error ts=2020-11-03T14:32:24.904558751Z caller=table_manager.go:218 msg=""error syncing tables"" err=""AccessDenied: Access Denied
\tstatus code: 403, request id: 13650B3B4BBE6387, host id: 82wYupHP/XAKe66FDSAlEwlfTju5D8mRobyDx2G0BccSkK22q5pXbyWF2Qwtn8OAgj+i5OH7br8="""
1604414004815,"level=info ts=2020-11-03T14:33:24.815548044Z caller=table_manager.go:171 msg=""uploading tables"""
1604414064815,"level=info ts=2020-11-03T14:34:24.815474955Z caller=table_manager.go:171 msg=""uploading tables"""
1604414064819,"level=info ts=2020-11-03T14:34:24.819799077Z caller=table_manager.go:324 msg=""synching tables"" expected_tables=126"
1604414064843,"level=error ts=2020-11-03T14:34:24.84365353Z caller=table_manager.go:234 msg=""error syncing tables"" err=""AccessDenied: Access Denied
\tstatus code: 403, request id: 1A75A0A8998C4C6D, host id: 1bl8ZyfIP16fVPDF63k0LMlpHwP1MquWigNuKM6d2HaF10L42X3p1iAV6T24q2R+mD6KVwq9jNk="""
```
Config:
```
auth_enabled: false
server:
  http_listen_port: 3100
ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0
schema_config:
  configs:
    - from: 2020-07-01
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_
        period: 24h
storage_config:
  aws:
    s3: s3://eu-west-1/loki-logs-core-prod
  boltdb_shipper:
    active_index_directory: /loki/active_index
    cache_location: /loki/index_cache
    shared_store: s3
compactor:
  working_directory: /loki/data/boltdb_shipper_compactor
  shared_store: filesystem
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
chunk_store_config:
  max_look_back_period: 0s
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
```
Fargate Task Policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "logs:PutLogEvents",
                "logs:DescribeLogStreams",
                "logs:CreateLogStream",
                "logs:CreateLogGroup",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetAuthorizationToken",
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability"
            ],
            "Resource": "*"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::loki-logs-core-prod/*",
                "arn:aws:s3:::loki-logs-core-prod/",
                "arn:aws:s3:::loki-config-core-prod/*",
                "arn:aws:s3:::loki-config-core-prod/"
            ]
        }
    ]
}
```

**Comment by fabianmet** [comment]
We are running into the same issue.

**Comment by fabianmet** [comment]
Was able to fix it by specifying iam user credentials in the config file. It seems somewhere the role credentials are not properly used.

**Comment by emilmark-wowgroup** [comment]
@fabianmet can you share your config? (we already tried specifying the s3 credentials but it did not work for us)

**Comment by fabianmet** [comment]
Sure! @emilmark-wowgroup. We are running inside an EKS cluster with a role that has complete access to that specific bucket.
I tried with the role assume via KIAM which goes fine for all other projects we use so i have trust in the KIAM solution. But the role failed. The only difference was adding the key and secret directly which suddenly made it start working.

The iam user i created had the exact same profile as the role.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  namespace: monitoring
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    compactor:
      working_directory: /data/loki/boltdb-shipper-compactor
      shared_store: s3

    schema_config:
      configs:
        - from: 2018-04-15
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:

      boltdb_shipper:
        active_index_directory: /data/loki/index
        shared_store: s3
        cache_location: /data/loki/boltdb-cache

      aws:
        bucketnames: loki-with-some-random-hash
        endpoint: s3.eu-central-1.amazonaws.com
        region: eu-central-1
        access_key_id: KEYHERE
        secret_access_key: SECRETHERE
        sse_encryption: true
```
