### ISSUE TITLE
Streaming logs from loki will crash

### ISSUE THREAD

**Issue by John-Lin** [grafana/loki#2881]
**Describe the bug**

Using Live button from grafana explore. loki will crash.

here is my Loki config

```yaml
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 15
schema_config:
  configs:
  - from: "2020-10-01"
    index:
      period: 24h
      prefix: index_
    object_store: s3
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
storage_config:
  aws:
    endpoint: xxx.com
    bucketnames: mybucketname
    access_key_id: xxxxxx
    secret_access_key: xxxxxxxxxxxx
    insecure: false
    sse_encryption: false
    http_config:
      idle_conn_timeout: 90s
      response_header_timeout: 0s
      insecure_skip_verify: false
    s3forcepathstyle: true
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    shared_store: s3
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 24h
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
compactor:
  working_directory: /data/loki/boltdb-shipper-compactor
  shared_store: filesystem
```

and promtail config (if needed)

```yaml
client:
  backoff_config:
    max_period: 5s
    max_retries: 20
    min_period: 100ms
  batchsize: 102400
  batchwait: 1s
  external_labels: {}
  timeout: 10s
positions:
  filename: /run/promtail/positions.yaml
server:
  http_listen_port: 3101
target_config:
  sync_period: 10s

scrape_configs:
  - job_name: kubernetes-pods-name
    pipeline_stages:
      - docker: {}

    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels:
          - __meta_kubernetes_pod_label_name
        target_label: __service__
      - source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
          - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - __meta_kubernetes_namespace
          - __service__
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
  - job_name: kubernetes-pods-app
    pipeline_stages:
      - docker: {}

    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: drop
        regex: .+
        source_labels:
          - __meta_kubernetes_pod_label_name
      - source_labels:
          - __meta_kubernetes_pod_label_app
        target_label: __service__
      - source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
          - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - __meta_kubernetes_namespace
          - __service__
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
  - job_name: kubernetes-pods-direct-controllers
    pipeline_stages:
      - docker: {}

    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: drop
        regex: .+
        separator: ''
        source_labels:
          - __meta_kubernetes_pod_label_name
          - __meta_kubernetes_pod_label_app
      - action: drop
        regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
        source_labels:
          - __meta_kubernetes_pod_controller_name
      - source_labels:
          - __meta_kubernetes_pod_controller_name
        target_label: __service__
      - source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
          - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - __meta_kubernetes_namespace
          - __service__
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
  - job_name: kubernetes-pods-indirect-controller
    pipeline_stages:
      - docker: {}

    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: drop
        regex: .+
        separator: ''
        source_labels:
          - __meta_kubernetes_pod_label_name
          - __meta_kubernetes_pod_label_app
      - action: keep
        regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
        source_labels:
          - __meta_kubernetes_pod_controller_name
      - action: replace
        regex: '([0-9a-z-.]+)-[0-9a-f]{8,10}'
        source_labels:
          - __meta_kubernetes_pod_controller_name
        target_label: __service__
      - source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
          - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - __meta_kubernetes_namespace
          - __service__
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
  - job_name: kubernetes-pods-static
    pipeline_stages:
      - docker: {}

    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: drop
        regex: ''
        source_labels:
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_label_component
        target_label: __service__
      - source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
          - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - __meta_kubernetes_namespace
          - __service__
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
          - __meta_kubernetes_pod_container_name
        target_label: __path__
```

**To Reproduce**
1. Started Loki 2.0 in monolithic mode
2. Started Promtail2.0 to tail all kubernetes pod logs and send to loki
3. Query: `{namespace="traefik"} | json | OriginStatus >= 500`

**Expected behavior**

Loki backend should work well

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: YAMLs

**Screenshots, Promtail config, or terminal output**

![Screen Shot 2020-11-05 at 6 58 21 PM](https://user-images.githubusercontent.com/4214069/98232655-e0af3180-1f98-11eb-9ea7-358a87c7205f.png)

Debug messages
```
level=debug ts=2020-11-05T11:03:57.891985331Z caller=logging.go:66 traceID=5eb33c90a61b389c msg="POST /loki/api/v1/push (204) 4.754378ms"
level=debug ts=2020-11-05T11:03:57.928565426Z caller=grpc_logging.go:58 method=/logproto.Querier/Query duration=1.569229835s msg="gRPC (success)"
ts=2020-11-05T11:03:57.929318661Z caller=spanlogger.go:53 org_id=fake traceID=2cc6ddb63a8cc835 method=query.Exec level=debug Ingester.TotalReached=1 Ingester.TotalChunksMatched=2 Ingester.TotalBatches=0 Ingester.TotalLinesSent=0 Ingester.HeadChunkBytes="215 kB" Ingester.HeadChunkLines=269 Ingester.DecompressedBytes="41 MB" Ingester.DecompressedLines=48175 Ingester.CompressedBytes="3.5 MB" Ingester.TotalDuplicates=0 Store.TotalChunksRef=0 Store.TotalChunksDownloaded=0 Store.ChunksDownloadTime=0s Store.HeadChunkBytes="0 B" Store.HeadChunkLines=0 Store.DecompressedBytes="0 B" Store.DecompressedLines=0 Store.CompressedBytes="0 B" Store.TotalDuplicates=0
ts=2020-11-05T11:03:57.929403044Z caller=spanlogger.go:53 org_id=fake traceID=2cc6ddb63a8cc835 method=query.Exec level=debug Summary.BytesProcessedPerSecond="26 MB" Summary.LinesProcessedPerSecond=30845 Summary.TotalBytesProcessed="41 MB" Summary.TotalLinesProcessed=48444 Summary.ExecTime=1.570536108s
level=info ts=2020-11-05T11:03:57.92948645Z caller=metrics.go:81 org_id=fake traceID=2cc6ddb63a8cc835 latency=fast query="{namespace=\"traefik\"} | json | OriginStatus >= 500 " query_type=filter range_type=instant length=0s step=0s duration=1.570536108s status=200 throughput_mb=26.300227 total_bytes_mb=41.305457
level=debug ts=2020-11-05T11:03:57.93807444Z caller=logging.go:66 traceID=2cc6ddb63a8cc835 msg="GET /loki/api/v1/query?query=%7Bnamespace%3D%22traefik%22%7D%20%7C%20json%20%7C%20OriginStatus%20%3E%3D%20500%20&time=1604574237000000000&limit=1000 (200) 1.579511128s"
level=debug ts=2020-11-05T11:03:58.073232164Z caller=grpc_logging.go:41 method=/logproto.Pusher/Push duration=5.2372ms msg="gRPC (success)"
level=debug ts=2020-11-05T11:03:58.073645458Z caller=logging.go:66 traceID=31b700a51a566bea msg="POST /loki/api/v1/push (204) 9.196204ms"
level=debug ts=2020-11-05T11:03:58.105625258Z caller=grpc_logging.go:58 method=/logproto.Querier/Query duration=1.60345631s msg="gRPC (success)"
level=debug ts=2020-11-05T11:03:58.242910487Z caller=grpc_logging.go:41 method=/logproto.Pusher/Push duration=359.542µs msg="gRPC (success)"
level=debug ts=2020-11-05T11:03:58.243246818Z caller=logging.go:66 traceID=26548e9dfa534c7e msg="POST /loki/api/v1/push (204) 1.755387ms"
level=debug ts=2020-11-05T11:03:58.258684664Z caller=grpc_logging.go:41 method=/logproto.Pusher/Push duration=666.569µs msg="gRPC (success)"
level=debug ts=2020-11-05T11:03:58.259026522Z caller=logging.go:66 traceID=6784527637bd5542 msg="POST /loki/api/v1/push (204) 4.127386ms"
level=debug ts=2020-11-05T11:03:58.406027751Z caller=grpc_logging.go:41 duration=5.218736ms method=/logproto.Pusher/Push msg="gRPC (success)"
level=debug ts=2020-11-05T11:03:58.406313176Z caller=logging.go:66 traceID=4a313695919a34c4 msg="POST /loki/api/v1/push (204) 13.232304ms"
level=debug ts=2020-11-05T11:03:58.490761434Z caller=grpc_logging.go:41 method=/logproto.Pusher/Push duration=248.06µs msg="gRPC (success)"
level=debug ts=2020-11-05T11:03:58.490993001Z caller=logging.go:66 traceID=4338355b9c2547f9 msg="POST /loki/api/v1/push (204) 1.335261ms"
level=debug ts=2020-11-05T11:03:58.568224098Z caller=grpc_logging.go:41 method=/logproto.Pusher/Push duration=148.893µs msg="gRPC (success)"
level=debug ts=2020-11-05T11:03:58.568491642Z caller=logging.go:66 traceID=764baada5f4a2f62 msg="POST /loki/api/v1/push (204) 1.042015ms"
level=debug ts=2020-11-05T11:03:58.572560023Z caller=grpc_logging.go:41 duration=489.38µs method=/logproto.Pusher/Push msg="gRPC (success)"
level=debug ts=2020-11-05T11:03:58.572841868Z caller=logging.go:66 traceID=9577b43f9d072a9 msg="POST /loki/api/v1/push (204) 1.69793ms"
level=debug ts=2020-11-05T11:03:58.576258901Z caller=grpc_logging.go:41 method=/logproto.Pusher/Push duration=654.233µs msg="gRPC (success)"
level=debug ts=2020-11-05T11:03:58.57653859Z caller=logging.go:66 traceID=5f076cc64a575504 msg="POST /loki/api/v1/push (204) 4.451906ms"
level=debug ts=2020-11-05T11:03:58.67812851Z caller=grpc_logging.go:41 method=/logproto.Pusher/Push duration=201.757µs msg="gRPC (success)"
level=debug ts=2020-11-05T11:03:58.678447791Z caller=logging.go:66 traceID=7bd9e821e4cc4a5d msg="POST /loki/api/v1/push (204) 1.232383ms"
level=debug ts=2020-11-05T11:03:58.733651566Z caller=grpc_logging.go:41 method=/logproto.Pusher/Push duration=265.574µs msg="gRPC (success)"
panic: runtime error: index out of range [30] with length 0

goroutine 2725 [running]:
github.com/grafana/loki/pkg/logql/log.(*LabelsBuilder).Set(0xc001f883c0, 0xc0009e50f0, 0xa, 0xc0009e50b8, 0x4, 0xc0024b1100)
        /src/loki/pkg/logql/log/labels.go:92 +0x215
github.com/grafana/loki/pkg/logql/log.addLabel.func1(0xc0009e50f0, 0xa, 0xc0009e50b8, 0x4)
        /src/loki/pkg/logql/log/parser.go:35 +0xc6
github.com/grafana/loki/pkg/logql/log.parseMap(0x0, 0x0, 0xc0024b1170, 0xc002d92fe0)
        /src/loki/pkg/logql/log/parser.go:79 +0x3e7
github.com/grafana/loki/pkg/logql/log.(*JSONParser).Process(0x3963bc0, 0xc0012ddc00, 0x312, 0x380, 0xc001f883c0, 0xc0012ddc00, 0xc0027c6a80, 0x312, 0x380)
        /src/loki/pkg/logql/log/parser.go:69 +0x144
github.com/grafana/loki/pkg/logql/log.(*pipeline).Process(0xc0033649a0, 0xc0012ddc00, 0x312, 0x380, 0xc0025897c0, 0xa, 0xa, 0x3963bc0, 0xc000686a80, 0xc0010f5f60, ...)
        /src/loki/pkg/logql/log/pipeline.go:61 +0x10d
github.com/grafana/loki/pkg/ingester.(*tailer).processStream(0xc0003a8540, 0xc000174280, 0x131, 0xc0006215e0, 0x4, 0x4, 0x7ff53e99b7d0, 0xc00098f4f0, 0xc000903f90, 0xc00157de70, ...)
        /src/loki/pkg/ingester/tailer.go:149 +0x21d
github.com/grafana/loki/pkg/ingester.(*tailer).send(0xc0003a8540, 0xc000174280, 0x131, 0xc0006215e0, 0x4, 0x4, 0x1ab8356, 0xc0000bb400)
        /src/loki/pkg/ingester/tailer.go:121 +0x187
github.com/grafana/loki/pkg/ingester.(*stream).Push.func1(0xc0011b0be0, 0xc0006215e0, 0x4, 0x4, 0x273d9c0, 0xc0007e97d0)
        /src/loki/pkg/ingester/stream.go:187 +0x23e
created by github.com/grafana/loki/pkg/ingester.(*stream).Push
        /src/loki/pkg/ingester/stream.go:176 +0x12ac
```
