### ISSUE TITLE
Add Azure blob storage config examples to the docs

### ISSUE THREAD

**Issue by wardbekker** [grafana/loki#2907]
**Is your feature request related to a problem? Please describe.**
Loki supports Azure Blob Storage, but this is not yet reflected in the docs. This issue is a reminder to add this.

**Comment by wardbekker** [comment]
See cortex version of this config https://github.com/cortexproject/cortex/blob/1797adfed2979f6096c3305b0dc9162c1ec0c046/docs/configuration/config-file-reference.md

**Comment by Crayeth** [comment]
Is there support for an azure service for index too (blob, cosmosdb)? or just chunks.

**Comment by Crayeth** [comment]
Seems like I was able to turn it on with:
```
loki:
  enabled: true
  config:
    schema_config:
      configs:
        - from: 2020-12-22
          store: boltdb-shipper
          object_store: azure
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        shared_store: azure
        cache_location: /data/loki/boltdb-cache
      azure:
        container_name: .. # add container name here
        account_name: .. # add account name here
        account_key: .. # add access key here <-- probably want to use sealed secrets or something for this one
```
