### ISSUE TITLE
SIGSEGV when using custom S3 endpoint with bolt-shipper

### ISSUE THREAD

**Issue by netdata-be** [grafana/loki#2912]
**Crash when using custom S3 endpoint with bolt-shipper**

I'm using ChubaoFS as our S3-endpoints.
When configured to run bolt-shipper to use the S3 I get this crash:

```
level=info ts=2020-11-10T14:03:31.006861719Z caller=table_manager.go:333 msg="synching tables" expected_tables=180
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12ca0f9]

goroutine 418 [running]:
github.com/cortexproject/cortex/pkg/chunk/aws.(*S3ObjectClient).List.func1(0x26df4e0, 0xc0008e4840, 0x7, 0xbfe2c54cc04a67e7)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/aws/s3_storage_client.go:320 +0x489
github.com/weaveworks/common/instrument.CollectedRequest(0x26df420, 0xc0005a1dc0, 0x2157dd1, 0x7, 0x26cca20, 0xc00011e1c0, 0x22b1d48, 0xc000c0d990, 0x0, 0x0)
	/src/loki/vendor/github.com/weaveworks/common/instrument/instrument.go:152 +0x269
github.com/cortexproject/cortex/pkg/chunk/aws.(*S3ObjectClient).List(0xc0008aaff0, 0x26df420, 0xc0005a1dc0, 0x21568ff, 0x6, 0x2151a66, 0x1, 0x0, 0x0, 0xc000c13ad0, ...)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/aws/s3_storage_client.go:296 +0x1a6
github.com/grafana/loki/pkg/storage/stores/util.PrefixedObjectClient.List(0x26e5f20, 0xc0008aaff0, 0x21568ff, 0x6, 0x26df420, 0xc0005a1dc0, 0x0, 0x0, 0x2151a66, 0x1, ...)
	/src/loki/pkg/storage/stores/util/object_client.go:25 +0xe2
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).Run(0xc00033ff40, 0x26df420, 0xc0005a1dc0, 0x0, 0x0)
	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:102 +0x120
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).loop.func1()
	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:70 +0x4e
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).loop(0xc00033ff40, 0x26df420, 0xc0005a1dc0, 0x0, 0x0)
	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:76 +0x93
github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main(0xc0003730e0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:167 +0x3f7
created by github.com/cortexproject/cortex/pkg/util/services.(*BasicService).StartAsync.func1
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:96 +0xa8
```

**To Reproduce**
1. Started Loki (2.0.0 and also tried master ) with the supplied config
3. container ( loki itself) crashes

**Expected behavior**
To just work or in the event it does not work give a clear error description.

**Environment:**
 - Infrastructure:  nomad
 - Deployment tool: terraform

Config
```
auth_enabled: false
server:
  http_listen_port: 3100
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
  - from: 2020-11-01
    store: boltdb-shipper
    object_store: s3
    schema: v11
    index:
      prefix: index
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    resync_interval: 5s
    shared_store: s3
  aws:
    s3: s3://xxxx:yyyy@s3.service.consul/loki
    insecure: true
    s3forcepathstyle: true 

limits_config:
  enforce_metric_name: false
  reject_old_samples: true  
  reject_old_samples_max_age: 168h

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: aws
```

When I tcpdump I see there is 1 call fired to the S3 endpoint:

```
GET /loki?delimiter=%2F&list-type=2&prefix=index%2F HTTP/1.1
Host: s3.service.consul
User-Agent: aws-sdk-go/1.35.5 (go1.14.2; linux; amd64)
Authorization: xxxx
X-Amz-Content-Sha256: xxx
X-Amz-Date: 20201110T133224Z
Accept-Encoding: gzip

HTTP/1.1 200 OK
Content-Length: 794
Content-Type: application/xml
Date: Tue, 10 Nov 2020 13:32:53 GMT
Server: ChubaoFS
X-Amz-Request-Id: xxxxxx

<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult><Name>loki</Name><Prefix>index/</Prefix><KeyCount>3</KeyCount><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><Contents><Key>index/</Key><LastModified>2020-11-10T13:31:54.000Z</LastModified><ETag>&#34;d41d8cd98f00b204e9800998ecf8427e&#34;</ETag><Size>0</Size><StorageClass>Standard</StorageClass></Contents><Contents><Key>index/testfile1</Key><LastModified>2020-11-10T13:31:54.000Z</LastModified><ETag>&#34;ba1f2511fc30423bdbb183fe33f3dd0f&#34;</ETag><Size>4</Size><StorageClass>Standard</StorageClass></Contents><Contents><Key>index/testfile2</Key><LastModified>2020-11-10T13:32:10.000Z</LastModified><ETag>&#34;ba1f2511fc30423bdbb183fe33f3dd0f&#34;</ETag><Size>4</Size><StorageClass>Standard</StorageClass></Contents></ListBucketResult>
```
