### ISSUE TITLE
Docker splits long log lines and Promtail considers them multiple logs, let's fix that

### ISSUE THREAD

**Issue by dcepelik** [grafana/loki#2920]
**Is your feature request related to a problem? Please describe.**

Currently when Docker's json-file log-driver is used, long logs are split into multiple entries in the file. For example, when I log 100k 'a's from a container, I will get the following entries in the JSON log file that Docker maintains for me:

    {"log":"aaa...aaa","stream":"stderr","time":"2020-11-11T12:45:18.240393806Z"}
    {"log":"aaa...aaa","stream":"stderr","time":"2020-11-11T12:45:18.240393806Z"}
    (many lines omitted)
    {"log":"aaa...aaa","stream":"stderr","time":"2020-11-11T12:45:18.240393806Z"}

This is unfortunate for several reasons:

- The limit cannot be configured in Docker, we're stuck with 32 kB per log line.
- At the very beginning of the Loki stack, the two lines will be considered two log entries. Since you typically log JSON, you will get JSON broken into multiple pieces, which isn't valid JSON anymore. This means that you may not find strings which were in fact logged if you're unfortunate enough and the break occurs in the middle of the string.

I don't really have an issue with there being an upper bound on the size of an individual log message, but this "silent corruption" (which isn't really Docker's fault neither Loki's fault) is not great. We've spent couple hours finding the culprit today.

(We noticed that kubectl gives us the correct, unsplit log lines, which led us to believe that the issue is in Loki.)

Kubectl will combine the logs together (there's enough information in the JSON documents to do it) and you will see a single logical log even if the original log is split into multiple lines in the JSON log file.

In fact, the reassembly is easy: it appears that the order of the log lines is correct (that would need to be verified, but it only makes sense) and therefore it's enough to concatenate the `.log` strings from the individual JSON logs, keeping a separate buffer per `.stream`. Once the buffer ends in `\n` (the original end-of-line is present in the logs), you have a full log.

**Describe the solution you'd like**

We think this can be solved in the following way, improving upon the Docker pipeline in Promtail:

  - Create a new pipeline stage to recombine the logs. The pipeline will keep a growing string buffer per `.stream` property of the JSON log entry.
  - Upon Process, the stage will:
    - Append the current `.log` string to the buffer of the appropriate stream.
    - If the stream ends in `\n`, return an entry with the contents of the buffer as the log message; then reset the buffer.
    - If the stream does not end in `\n`, drop the current entry with a descriptive message explaining it will be combined with the next entry.

**Describe alternatives you've considered**

There do not seem to be better solutions to this problem.

**Issues**

This approach is not without issues, we see the following potential problems/things to be addressed:

- We still should have a (configurable) upper limit on the buffer size. Should this buffer size be exceeded, we should truncate (not drop) the entry, mark the entry redacted (multiple options here: modifying the log entry itself, wrapping the log entry in a JSON with `"truncated": true`, adding a gRPC field into the protocol, etc.). We should not drop the entry, as that makes it really hard to find out which logs are being lost.
- You can lose the last long message if Docker crashes before you've seen the `\n` or the container dies before it flushes the entire log, etc. Not sure how to deal with this one. (There could perhaps be a configurable time-out to reassemble the full log line and again mark it as truncated.)
- Chances are increased that now you will actually hit the message size limit (I think it's implemented on the gRPC level) on the ingester. In that case, the log will be dropped (which again makes it difficult to find out which log was dropped), but at least there's at least a metric for this.

**Additional context**

Kudos to @graywolf-at-work who debugged this issue with me. We are happy to provide implementation for this, assuming our proposal will be accepted or some better solution found. Thanks.

**Comment by cyriltovena** [comment]
I'd be curious to see how that look like.

**Comment by patrickhuy** [comment]
Seems to be related/the same as #2281

**Comment by graywolf-at-work** [comment]
Still an issue.

**Comment by dcepelik** [comment]
I have a patch ready which adds a new Docker stage which joins the "physical" logs (JSON log chunks) into "logical" logs (log lines). I still have to figure out a few issues and test everything.

**Comment by dcepelik** [comment]
I will eventually finish my patch, so let's keep this open please.

**Comment by owen-d** [comment]
Looking forward to it, @dcepelik

**Comment by dcepelik** [comment]
Short update: I found a couple hours last week, set up a locally running promtail and started testing. I'm currently fixing one more issue. I cannot currently given an ETA, but will try to prioritize this :).

**Comment by amrynsky** [comment]
> Short update: I found a couple hours last week, set up a locally running promtail and started testing. I'm currently fixing one more issue. I cannot currently given an ETA, but will try to prioritize this :).

@dcepelik  let me know if you need help with the fix or probably testing. 

In our case, call stacks could be pretty long and we are missing important log entries because of this. Trying to find workaround by limiting log size on the application level but generic support in promtail would be preferred option.

**Comment by dcepelik** [comment]
> In our case, call stacks could be pretty long

Did you say, Java?

> Trying to find workaround by limiting log size on the application level but generic support in promtail would be preferred option.

I will share my patch over the weekend and will also try to finish testing.

**Comment by dcepelik** [comment]
Hello,

I have (finally, though later than promised - sorry!) opened a merge request with my current PoC fix. Please bear in mind that it's still only a PoC and there's a bunch of things to solve (see #3721).

If anybody wants to test this, here are the steps to reproduce my local setup:

- Build the patched promtail image (`make promtail-image`)
- `docker-compose.yml` (don't forget to fix path to `docker-config.yml` and the image tag), mostly a plug of [this](https://gist.github.com/ruanbekker/c6fa9bc6882e6f324b4319c5e3622460):

```yaml
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:1.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:fix_2920_rebased-d9380ea-WIP
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /home/d/loki-testing/docker-config.yml:/etc/promtail/docker-config.yml
    command: -config.file=/etc/promtail/docker-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - loki
```

- `docker-config.yml`, mostly a plug of [this](https://gist.github.com/ruanbekker/c6fa9bc6882e6f324b4319c5e3622460):

```yaml
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:
  - json:
      expressions:
        attrs:
  - json:
      expressions:
        tag:
      source: attrs
  - docker: {}
  - labels:
      tag:
      stream:
  - output:
      source: output
```

- `docker-compose up -d`
- Start any extra container you're comfortable with where you will produce the logs, I used a plain Alpine Linux container; use the json-log driver:

```
docker run --rm -itd --name alpine --log-driver json-file --log-opt tag="{{.Name}}" alpine sh
```

- Navigate to Grafana at `localhost:3000` and configure a Loki datasource (I used the docker-compose internal IP of the Loki pod: `docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' loki-testing_loki_1`)
- Start producing logs in the (Alpine) container (`echo foobar` is enough)
- You should be able to see the logs in Grafana and also in `/var/lib/docker/containers/<conainter-id>/<container-id>-json.log`

With this setup, I did the following to validate the PoC:

- Produce a short message (<= 16KiB inclusive of \r\n; yes, Docker adds \r even on Linux) and inspect the `*-json.log` file to make sure it wasn't broken into multiple logs. This is mostly a sanity check. You should also be able to find it in the web UI. I was producing the logs with `{ yes | paste -s -d 'y' | head -c 256000 | tr y a && echo; }` and I would change the replace character in `tr` with each run to make sure I didn't mix the logs up.
- Produce a longer message, say 20KiB, and inspect the `*-json.log` file. You should see there more than one JSON log entry. I made sure that the logs actually added up to the expected 20KiB + \r\n.
- In Grafana, without the patch, I saw two log entries as expected (or more for longer messages). I only saw one log entry with my patch applied. I checked that the length of the message in the UI was 20KiB (or more) as expected.
- I did some more ad-hoc manual testing by producing various garbage from the Alpine container. I also tried much larger messages, up to 256KiB, where I got bored. I assume there's a gRPC message size limit somewhere (I saw it earlier in the code base), but did not get to testing what happens if I exceed it.
