### ISSUE TITLE
 entry out of order' for stream

### ISSUE THREAD

**Issue by MrYueQ** [grafana/loki#2924]
**Describe the bug**
- **Failed to send batch**
```yaml
[2020-11-12T16:25:49,637][WARN ][logstash.outputs.loki    ][main] Failed to send batch attempt: 1/10 {:error_inspect=>"#<StandardError: #<Net::HTTPTooManyRequests:0x27747fbc>>", :error=>#<StandardError: #<Net::HTTPTooManyRequests:0x27747fbc>>}
[2020-11-12T16:25:50,987][WARN ][logstash.outputs.loki    ][main] Failed to send batch attempt: 2/10 {:error_inspect=>"#<StandardError: #<Net::HTTPTooManyRequests:0x76fadd80>>", :error=>#<StandardError: #<Net::HTTPTooManyRequests:0x76fadd80>>}
```

-  entry out of order for 
```yaml
Nov 12 20:00:05 hostname loki[16217]: {"caller":"grpc_logging.go:38","duration":"1.861638ms","err":"rpc error: code = Code(400) desc = entry with timestamp 2020-11-12 12:00:04.908999936 +0000 UTC ignored, reason: 'entry out of order' for stream: {application=\"AA\", hostname=\"BB\", logLevel=\"INFO\", logTime=\"2020-11-12 17:56:15.652\"},\nentry with timestamp 2020-11-12 12:00:04.908999936 +0000 UTC ignored, reason: 'entry out of order' for stream: {application=\"AA\", hostname=\"BB\", logLevel=\"INFO\", logTime=\"2020-11-12 17:56:15.652\"},\ntotal ignored: 2 out of 2","level":"warn","method":"/logproto.Pusher/Push","msg":"gRPC\n","ts":"2020-11-12T12:00:05.752830937Z"}
```
**To Reproduce**
- **loki version**
```yaml
loki, version 2.0.0 (branch: HEAD, revision: 6978ee5d)
  build user:       root@2645337e4e98
  build date:       2020-10-26T15:54:56Z
  go version:       go1.14.2
  platform:         linux/amd64
```

- **Loki Configuartion**

```yaml
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /data/loki/chunks

compactor:
  working_directory: /data/loki/boltdb-shipper-compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: false
  max_streams_per_user: 0
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

ruler:
  storage:
    type: local
    local:
      directory: /data/loki/rules
  rule_path: /data/loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
```

- **Logstash Configuartion**

```yaml
input {
   kafka {
           bootstrap_servers => "borker_lists"
           group_id => "AA"
           topics => ["BB"]
           id => "CCC"
           client_id => "idAAA"
           auto_offset_reset => "earliest"
           consumer_threads => 20
        }
}

filter {
    json {
        source => "message"
    }
    grok {
        match => {
           "message" => [   "(?m)(?<logTime>^\d+-\d+-\d+\s\d+:\d+:\d+.\d+)\s+%{LOGLEVEL:logLevel}",
                            "(?m)(?<logTime>^\d+-\d+-\d+\s\d+:\d+:\d+)\s+\d+\s+\[%{LOGLEVEL:logLevel}",
                            "(?m)(?<logTime>^\d+-\d+-\d+\s\d+:\d+:\d+.\d+)\s+(?<info_1>[^\s]+)\s+%{LOGLEVEL:logLevel}",
                            "(?m)(?<logTime>^\d+-\d+-\d+\s\d+:\d+:\d+.\d+):%{LOGLEVEL:logLevel}"
                ]
           }
        }
    grok {
        match => {
           "source" => [   "/data/logs/(?<application>[^/]+)"
                ]
           }
        } 
    mutate {
        remove_field => [ "source","info_1" ] 
     }
}

output {
  loki {
    url => "http://loki_server_domain/loki/api/v1/push"
    min_delay => 1
    max_delay => 2
  }
}
```

## Env info 

```yaml
logstash: logstash-7.10.0
plugin: logstash-output-loki
centos: Linux AA 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
