### ISSUE TITLE
Metric is not being created by the promtail pipeline

### ISSUE THREAD

**Issue by jimmy0012** [grafana/loki#2952]
**Describe the bug**
I am trying to create a counter metric based on regex, but it doesn't seem to be working

**To Reproduce**
Promtail 2.0.0
Scraping promtail metric endpoint directly to see if the metric is there

log line:
`time="2020-11-15T22:05:26.228264758Z" level=error msg="Testing promtail metric. ID: i-******"`

scrape config: 
```
  - match:
      selector: '{pod=~"testpod-.+"}'
      stages:
      - regex:
          expression: ^.*(?P<test>Testing promtail metric).*$
      - metrics:
          test_metric:
            config:
              action: inc
            description: log lines with the message Testing promtail metric
            prefix: test_
            source: test
            type: Counter
```
I've verified that the `pod` label is being created during the relabel process

Pod name is `testpod-3842` or similar

**Expected behavior**
A new metric called test_test_metric to be seen when scraping promtail

**Environment:**
 - Kubernetes EKS
