### ISSUE TITLE
Fluent-bit plugin for Loki not handling kubernetes labels correctly

### ISSUE THREAD

**Issue by iptizer** [grafana/loki#2977]
**Describe the bug**
The fluent-bit *labelmap* does not handle kubernetes labels correctly. Not all labels allowed by Kubernetes are picked up by Loki.

Working label keys:
* *my_label*
* *mydomain_com_my_label*

label keys that are allowed by Kubernetes, but don't get picked up correctly within Loki:
* *mydomain.com/my-label*
* *mydomain.com/my_label*
* *mydomain.com_my_label*
* *my-label*

![labelmap_tags](https://user-images.githubusercontent.com/24313052/99960099-7f56d300-2d8c-11eb-9c2b-90996013d9aa.png)

This means that the following characters do not work in the labelmap: [ "-" , "." , "/" ]

**To Reproduce**

Kubectl apply the following crontab to get frequently logs:
```yml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: logproducer
  labels:
    app: label-cronjob
    sp-spec-id: myid123
spec:
  schedule: "0/1 * * * *"
  jobTemplate:
    metadata:
      name: logproducer
      labels:
        app: label-job
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: label-pod
            mydomain.com/my-label: myid123
            mydomain.com/my_label: myid123
            mydomain.com_my_label: myid123
            mydomain_com_my_label: myid123
            my_label: myid123
            my-label: myid123
          name: logproducer
        spec:
          containers:
          - args:
            - ls
            - -l
            - /
            image: iptizer/swiss
            name: logproducer
            resources: {}
          dnsPolicy: ClusterFirst
          restartPolicy: Never
```

Apply the following *labelmap.json*:

```yml
  labelmap.json: |-
    {
      "kubernetes": {
        "container_name": "container",
        "host": "node",
        "labels": {
          "app": "app",
          "dag_id": "dag_id",
          "my-label": "my-label",
          "my_label": "my_label",
          "mydomain.com/my-label": "mydomain.com/my-label",
          "mydomain.com/my_label": "mydomain.com/my_label",
          "mydomain.com_my_label": "mydomain.com_my_label",
          "mydomain_com_my_label": "mydomain_com_my_label",
          "release": "release",
          "task_id": "task_id"
        },
        "namespace_name": "namespace",
        "pod_name": "pod"
      },
      "stream": "stream"
    }
```

Query for logs of the pods. Only the above mentioned tags are shown in Loki.

**Expected behavior**

All above used labels are allowed by Kubernetes and should therefore be available in Loki. In many situations it is not possible to change the keys of the tags.
To be honest, I find it a little bit strange that no one reported this before.

**Environment:**
 - Infrastructure: Kubernetes/ EKS
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**

I could add everything you need, please respond.
