### ISSUE TITLE
query_range error: "object not found in storage" when providing an aggregated query

### ISSUE THREAD

**Issue by pcbl** [grafana/loki#2978]
I am using GRAFANA to build a dashboard with some Loki Information.
For the sake of simplicity, let`s imagine it being similar to the Explorer view offered by Grafana (A bar chart on the top, followed by the log entries).
The issue occurs when I try to run the following Loki Request (query ='{job="services"}'):

```
GET loki/api/v1/query_range?direction=BACKWARD&limit=1000&query={job="services"}&start=1596232800000000000&end=1598911200000000000&step=1800
```
- Params
   - direction: **BACKWARD**
   - limit: **1000**
   - query: **{job="services"}** 
   - start: **1596232800000000000** (Friday, July 31, 2020 10:00:00 PM)
   - end: **1598911200000000000** (Monday, August 31, 2020 10:00:00 PM)
   - step: **1800** (Calulated by Grafana)

This requests works perfectly, and I get the log entries I expect for.

But If I run the following request (query='sum(count_over_time({job="services"}[30m])) by(Level)'), which will be bound to a chart on grafana:
```
GET loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=sum(count_over_time({job="services"}[30m])) by(Level)&start=1596232800000000000&end=1598911200000000000&step=1800
```
- Params
   - direction: **BACKWARD**
   - limit: **1000**
   - query: **sum(count_over_time({job="services"}[30m])) by(Level)** (the 30m was calulated by Grafana)... **_That is the Only different betwen both queries!_**
   - start: **1596232800000000000** (Friday, July 31, 2020 10:00:00 PM)
   - end: **1598911200000000000** (Monday, August 31, 2020 10:00:00 PM)
   - step: **1800** (Calulated by Grafana)

ERROR:
**object not found in storage**

The only difference on this matter is the **query** parameter. The first provided call will be bound to a Logs Panel and does not need to be aggregated. The Second one will be linked to a chart, grouping by level over time...

From what i could see, the **object not found in storage** is actually coming from Cortex when a chunk key is not located. What for me ist not clear would be why the "chunk.ExternalKey()" returns an invalid key:
https://github.com/cortexproject/cortex/blob/b3c87d71b8ac45a87308657309ce666ee1ee4028/pkg/chunk/inmemory_storage_client.go#L361

I would expect that both queries runs nicely, but it is currently not.

Here is my Loki Config (nothing fancy):
```
auth_enabled: false

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: C:\ProgramData\POC\loki\index

  filesystem:
    directory: C:\ProgramData\POC\loki\chunks

limits_config:
  enforce_metric_name: false

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
```

Am I missing something?

**Comment by pcbl** [comment]
Just as a heads-up:
When I changed my setup to use the v2.0 Production-ready "boltdb-shipper" store, it is working as expected! So I believe this is a possible bug from the "boltdb" store.

As additional info, case someone faces the same issue:
```
auth_enabled: false

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: C:\ProgramData\POC\loki\index
    cache_location: C:\ProgramData\POC\loki\index\cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: C:\ProgramData\POC\loki\chunks
    
compactor:
  working_directory: C:\ProgramData\POC\loki\compactor
  shared_store: filesystem    

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: true
  retention_period: 168h
```

I am letting this issue open as it seems to be an issue on the "boldb" store.
