### ISSUE TITLE
Promtail stops tailing still-growing file after sending only a only a few entries in k8s

### ISSUE THREAD

**Issue by airhorns** [grafana/loki#2979]
**Describe the bug**

Hi folks, trying to debug a strange problem where my promtail instance is reliably stopping tailing a Kubernetes pod’s logs file beyond a certain point early in that pod's lifecycle.

I have most logs flowing into a loki from promtail, having installed both with helm charts using the default config values. Logs from kube-system pods and from other long running pods in my cluster seem to be working fine and all are tailed into loki and I’m able to query them via Grafana, but, for some pods, promtail stops tailing after some entries, and never starts again. I can confirm other pods’ logs continue flowing and that promtail nor loki is restarting or erroring. When I look in the promtail logs, I see it stopping logging for the file in question:

```
level=info ts=2020-11-21T19:00:21.142362789Z caller=tailer.go:204 component=tailer msg="stopped tailing file" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-78370217-2sxcl_136bd69d-9356-4371-a85f-a07ee92c62c1/js-sandbox/0.log
```

That pod is still running and still writing log entries to that file. If I run kubectl logs, I get a lot more than what promtail found.

Here’s all the log entries concerning the file in question:

```
2020-11-21 13:51:06	
level=info ts=2020-11-21T18:51:06.244785469Z caller=tailer.go:122 component=tailer msg="tail routine: started" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-78370217-2sxcl_136bd69d-9356-4371-a85f-a07ee92c62c1/js-sandbox/0.log
Show context
2020-11-21 13:51:06	
ts=2020-11-21T18:51:06.245186214Z caller=log.go:124 component=tailer level=info msg="Seeked /var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-78370217-2sxcl_136bd69d-9356-4371-a85f-a07ee92c62c1/js-sandbox/0.log - &{Offset:252 Whence:0}"
2020-11-21 14:00:21	
level=info ts=2020-11-21T19:00:21.142041929Z caller=tailer.go:95 component=tailer msg="position timer: exited" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-78370217-2sxcl_136bd69d-9356-4371-a85f-a07ee92c62c1/js-sandbox/0.log
2020-11-21 14:00:21	
level=info ts=2020-11-21T19:00:21.142123717Z caller=tailer.go:138 component=tailer msg="tail routine: tail channel closed, stopping tailer" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-78370217-2sxcl_136bd69d-9356-4371-a85f-a07ee92c62c1/js-sandbox/0.log
2020-11-21 14:00:21	
level=info ts=2020-11-21T19:00:21.142326841Z caller=tailer.go:131 component=tailer msg="tail routine: exited" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-78370217-2sxcl_136bd69d-9356-4371-a85f-a07ee92c62c1/js-sandbox/0.log
2020-11-21 14:00:21	
level=info ts=2020-11-21T19:00:21.142362789Z caller=tailer.go:204 component=tailer msg="stopped tailing file" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-78370217-2sxcl_136bd69d-9356-4371-a85f-a07ee92c62c1/js-sandbox/0.log
```

It seems like that timer component is maybe expecting something to come around and start tailing the same file again, and that never happens? I am not sure.

Notably, the pods in question are short lived (no less than 2 minutes but usually around 5), and inside the pod there are child processes opening and re-opening stdout and stderr, which is maybe what’s causing this. kubectl logs picks up logs fine from the child processes and so the logs are definitely on disk, it’s just promtail not picking them up.

I also experienced this with the Grafana Cloud agent running promtail as well as a promtail all on its own.

**To Reproduce**

Not exactly sure yet! Any pointers for things to test would be great.

**Expected behavior**

**Environment:**
 - Infrastructure: GKE Kubernetes
 - Deployment tool: helm
 - Versions: grafana/promtail:2.0.0 , grafana/loki:2.0.0

**Comment by cyriltovena** [comment]
it seems to be coming from the hpcloud/tail library we are using, it suddenly closes the channel of lines.

What I don't know is why.

This is going to be hard to pin down would you be open to try custom image that I can build and add more logging ?

**Comment by cyriltovena** [comment]
Pushed grafana/promtail:tailing-err-204f235 if you want to try again and let me know what it says now. specifically when it stopped.

**Comment by airhorns** [comment]
Sure thing! I confirmed my promtail was running the new container, and here's the logs from an example where some logs were dropped:

```

2020-12-01 14:33:52 | level=info ts=2020-12-01T19:33:52.005494131Z caller=filetargetmanager.go:261 msg="Adding target" key="{app_logs_service=\"sandbox\", container=\"js-sandbox\", environmentName=\"js-sandbox\", environmentNamespace=\"gadget-app-sandbox-production\", environmentUid=\"22e65558-66ea-4c8c-87c0-a766822cd152\", executorType=\"poolmgr\", job=\"gadget-app-sandbox-production/poolmgr-js-sandbox-gadget-app-sandbox-production-83513024\", managed=\"true\", namespace=\"gadget-app-sandbox-production\", origin=\"krane\", pod=\"poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj\", pod_template_hash=\"d4fc7b97f\"}"
-- | --
  |   | 2020-12-01 14:33:52 | ts=2020-12-01T19:33:52.006393208Z caller=log.go:124 component=tailer level=info msg="Seeked /var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj_fddb1896-4192-4a35-8e75-1a84bde4c9b3/js-sandbox/0.log - &{Offset:7661 Whence:0}"
  |   | 2020-12-01 14:33:52 | level=info ts=2020-12-01T19:33:52.006803208Z caller=filetargetmanager.go:261 msg="Adding target" key="{app_logs_service=\"sandbox\", container=\"fetcher\", environmentName=\"js-sandbox\", environmentNamespace=\"gadget-app-sandbox-production\", environmentUid=\"22e65558-66ea-4c8c-87c0-a766822cd152\", executorType=\"poolmgr\", job=\"gadget-app-sandbox-production/poolmgr-js-sandbox-gadget-app-sandbox-production-83513024\", managed=\"true\", namespace=\"gadget-app-sandbox-production\", origin=\"krane\", pod=\"poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj\", pod_template_hash=\"d4fc7b97f\"}"
  |   | 2020-12-01 14:33:52 | level=info ts=2020-12-01T19:33:52.006865485Z caller=tailer.go:122 component=tailer msg="tail routine: started" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj_fddb1896-4192-4a35-8e75-1a84bde4c9b3/js-sandbox/0.log Show context
  |   | 2020-12-01 14:33:52 | level=info ts=2020-12-01T19:33:52.012562315Z caller=tailer.go:122 component=tailer msg="tail routine: started" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj_fddb1896-4192-4a35-8e75-1a84bde4c9b3/fetcher/0.log
  |   | 2020-12-01 14:33:52 | ts=2020-12-01T19:33:52.013101129Z caller=log.go:124 component=tailer level=info msg="Seeked /var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj_fddb1896-4192-4a35-8e75-1a84bde4c9b3/fetcher/0.log - &{Offset:206 Whence:0}"
  |   | 2020-12-01 14:36:31 | level=info ts=2020-12-01T19:36:31.976339407Z caller=filetargetmanager.go:277 msg="Removing target" key="{app_logs_service=\"sandbox\", container=\"js-sandbox\", environmentName=\"js-sandbox\", environmentNamespace=\"gadget-app-sandbox-production\", environmentUid=\"22e65558-66ea-4c8c-87c0-a766822cd152\", executorType=\"poolmgr\", job=\"gadget-app-sandbox-production/poolmgr-js-sandbox-gadget-app-sandbox-production-83513024\", managed=\"true\", namespace=\"gadget-app-sandbox-production\", origin=\"krane\", pod=\"poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj\", pod_template_hash=\"d4fc7b97f\"}"
  |   | 2020-12-01 14:36:31 | level=info ts=2020-12-01T19:36:31.976559386Z caller=tailer.go:95 component=tailer msg="position timer: exited" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj_fddb1896-4192-4a35-8e75-1a84bde4c9b3/js-sandbox/0.log
  |   | 2020-12-01 14:36:31 | level=info ts=2020-12-01T19:36:31.97709689Z caller=tailer.go:138 component=tailer msg="tail routine: tail channel closed, stopping tailer" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj_fddb1896-4192-4a35-8e75-1a84bde4c9b3/js-sandbox/0.log reason=null
  |   | 2020-12-01 14:36:31 | level=info ts=2020-12-01T19:36:31.977131208Z caller=tailer.go:131 component=tailer msg="tail routine: exited" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj_fddb1896-4192-4a35-8e75-1a84bde4c9b3/js-sandbox/0.log
  |   | 2020-12-01 14:36:31 | level=info ts=2020-12-01T19:36:31.977145527Z caller=tailer.go:204 component=tailer msg="stopped tailing file" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj_fddb1896-4192-4a35-8e75-1a84bde4c9b3/js-sandbox/0.log
  |   | 2020-12-01 14:36:31 | level=info ts=2020-12-01T19:36:31.97719075Z caller=filetargetmanager.go:277 msg="Removing target" key="{app_logs_service=\"sandbox\", container=\"fetcher\", environmentName=\"js-sandbox\", environmentNamespace=\"gadget-app-sandbox-production\", environmentUid=\"22e65558-66ea-4c8c-87c0-a766822cd152\", executorType=\"poolmgr\", job=\"gadget-app-sandbox-production/poolmgr-js-sandbox-gadget-app-sandbox-production-83513024\", managed=\"true\", namespace=\"gadget-app-sandbox-production\", origin=\"krane\", pod=\"poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj\", pod_template_hash=\"d4fc7b97f\"}"
  |   | 2020-12-01 14:36:31 | level=info ts=2020-12-01T19:36:31.977775988Z caller=tailer.go:95 component=tailer msg="position timer: exited" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj_fddb1896-4192-4a35-8e75-1a84bde4c9b3/fetcher/0.log
  |   | 2020-12-01 14:36:31 | level=info ts=2020-12-01T19:36:31.97861159Z caller=tailer.go:138 component=tailer msg="tail routine: tail channel closed, stopping tailer" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj_fddb1896-4192-4a35-8e75-1a84bde4c9b3/fetcher/0.log reason=null
  |   | 2020-12-01 14:36:31 | level=info ts=2020-12-01T19:36:31.978878106Z caller=tailer.go:131 component=tailer msg="tail routine: exited" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj_fddb1896-4192-4a35-8e75-1a84bde4c9b3/fetcher/0.log
  |   | 2020-12-01 14:36:31 | level=info ts=2020-12-01T19:36:31.97903634Z caller=tailer.go:204 component=tailer msg="stopped tailing file" path=/var/log/pods/gadget-app-sandbox-production_poolmgr-js-sandbox-gadget-app-sandbox-production-83513024-59rwj_fddb1896-4192-4a35-8e75-1a84bde4c9b3/fetcher/0.log
```

or a screenshot of Grafana so you can see them formatted a bit nicer: 

<img width="1605" alt="Screen Shot 2020-12-01 at 2 40 20 PM" src="https://user-images.githubusercontent.com/158950/100788524-31247e00-33e3-11eb-9b8f-d6802e4f8468.png">

**Comment by airhorns** [comment]
Looks like `reason=null`, darn. Also, the `Removed target` message seemed to happen right around the same time that my pod actually finished doing some requests. The last log message that promtail picked up was a `request completed` message from the application inside the pod. 

I should also mention I am actually running *two* promtail daemonsets in my cluster: one for internal use by myself and my team, and one that exposes some of our app's logs to our customers. I know this is a bit weird, but maybe they are sharing some resource and that's actually my issue as opposed to something being dropped by the one. 

We've deployed the two different ones as two different Helm chart installations with two different `positions` file configs. When I `ssh` into one of the kubernetes nodes and look at `/run/promtail` I see the two different positions files being maintained by the two different instances, so I am pretty sure I have configured them to store and tail using their own internal state, but if there's something else they are sharing, that might make sense.

I also just checked and the plot thickens: my `internal` promtail which is using the scrape configs that come with the helm chart and not overriding anything is the one dropping logs, but my `app-logs` promtail which is using totally custom scrape configs *does* get the subsequent log entries, and doesn't seem to be dropping any. Is there any other mechanism that the second promtail might be influencing the first, maybe via a service discovery mechanism or something?

Sorry I didn't mention the second one earlier -- didn't realize it might be relevant!

**Comment by cyriltovena** [comment]
I don't think it service discovery related. I'm more thinking about filesystem notification.

**Comment by cyriltovena** [comment]
The log is showing two different file though

**Comment by cyriltovena** [comment]
I don't see anything could you share both config. Also could you try removing the custom config and check if the default one works alone ?

**Comment by airhorns** [comment]
@cyriltovena yeah, there's two docker containers running in that pod, so there's two log files. Both the `fetcher` and the `js-sandbox` containers continue to run after their targets are removed. 

The working promtail (we'll call it `promtail-app`) is for my customers to access some of the logs for their systems that we're running for them, so it filters down a bunch of stuff and writes to a different loki. Here's the config for it:

```
client:
  backoff_config:
    max_period: 5m
    max_retries: 10
    min_period: 500ms
  batchsize: 1048576
  batchwait: 1s
  external_labels: {}
  timeout: 10s
positions:
  filename: /run/promtail/app-positions.yaml
server:
  http_listen_port: 3101
target_config:
  sync_period: 5s
scrape_configs:
- job_name: kubernetes-app-pods
  kubernetes_sd_configs:
  - role: pod
  pipeline_stages:
  - docker: {}
  - json:
      expressions:
        application_id: applicationId
        environment_id: environmentId
        user_visible: userVisible
  - labels:
      application_id: null
      environment_id: null
      user_visible: null
  - match:
      action: drop
      drop_counter_reason: no_application_id
      selector: '{application_id=""}'
  - match:
      action: drop
      drop_counter_reason: not_user_visible
      selector: '{user_visible!="true"}'
  - tenant:
      source: application_id
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_pod_node_name
    target_label: __host__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: drop
    regex: ""
    source_labels:
    - app_logs_service
  - action: replace
    replacement: $1
    separator: /
    source_labels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_pod_name
    - __meta_kubernetes_pod_container_name
    target_label: job
  - action: replace
    replacement: /var/log/pods/*$1/*.log
    separator: /
    source_labels:
    - __meta_kubernetes_pod_uid
    - __meta_kubernetes_pod_container_name
    target_label: __path__
  - action: labelkeep
    regex: (__path__|app_logs_service|job|stream)
```

The second promtail which we called `promtail-internal` is the one that is prematurely stopping tailing. It's deployed using helm with no custom config at all. Here's it's generated config:

```
client:
  backoff_config:
    max_period: 5m
    max_retries: 10
    min_period: 500ms
  batchsize: 1048576
  batchwait: 1s
  external_labels: {}
  timeout: 10s
positions:
  filename: /run/promtail/internal-positions.yaml
server:
  http_listen_port: 3101
target_config:
  sync_period: 5s
scrape_configs:
- job_name: kubernetes-pods-name
  pipeline_stages:
    - docker: {}
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_pod_label_name
    target_label: __service__
  - source_labels:
    - __meta_kubernetes_pod_node_name
    target_label: __host__
  - action: drop
    regex: ''
    source_labels:
    - __service__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: replace
    replacement: $1
    separator: /
    source_labels:
    - __meta_kubernetes_namespace
    - __service__
    target_label: job
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - replacement: /var/log/pods/*$1/*.log
    separator: /
    source_labels:
    - __meta_kubernetes_pod_uid
    - __meta_kubernetes_pod_container_name
    target_label: __path__
- job_name: kubernetes-pods-app
  pipeline_stages:
    - docker: {}
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: drop
    regex: .+
    source_labels:
    - __meta_kubernetes_pod_label_name
  - source_labels:
    - __meta_kubernetes_pod_label_app
    target_label: __service__
  - source_labels:
    - __meta_kubernetes_pod_node_name
    target_label: __host__
  - action: drop
    regex: ''
    source_labels:
    - __service__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: replace
    replacement: $1
    separator: /
    source_labels:
    - __meta_kubernetes_namespace
    - __service__
    target_label: job
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - replacement: /var/log/pods/*$1/*.log
    separator: /
    source_labels:
    - __meta_kubernetes_pod_uid
    - __meta_kubernetes_pod_container_name
    target_label: __path__
- job_name: kubernetes-pods-direct-controllers
  pipeline_stages:
    - docker: {}
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: drop
    regex: .+
    separator: ''
    source_labels:
    - __meta_kubernetes_pod_label_name
    - __meta_kubernetes_pod_label_app
  - action: drop
    regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
    source_labels:
    - __meta_kubernetes_pod_controller_name
  - source_labels:
    - __meta_kubernetes_pod_controller_name
    target_label: __service__
  - source_labels:
    - __meta_kubernetes_pod_node_name
    target_label: __host__
  - action: drop
    regex: ''
    source_labels:
    - __service__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: replace
    replacement: $1
    separator: /
    source_labels:
    - __meta_kubernetes_namespace
    - __service__
    target_label: job
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - replacement: /var/log/pods/*$1/*.log
    separator: /
    source_labels:
    - __meta_kubernetes_pod_uid
    - __meta_kubernetes_pod_container_name
    target_label: __path__
- job_name: kubernetes-pods-indirect-controller
  pipeline_stages:
    - docker: {}
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: drop
    regex: .+
    separator: ''
    source_labels:
    - __meta_kubernetes_pod_label_name
    - __meta_kubernetes_pod_label_app
  - action: keep
    regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
    source_labels:
    - __meta_kubernetes_pod_controller_name
  - action: replace
    regex: '([0-9a-z-.]+)-[0-9a-f]{8,10}'
    source_labels:
    - __meta_kubernetes_pod_controller_name
    target_label: __service__
  - source_labels:
    - __meta_kubernetes_pod_node_name
    target_label: __host__
  - action: drop
    regex: ''
    source_labels:
    - __service__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: replace
    replacement: $1
    separator: /
    source_labels:
    - __meta_kubernetes_namespace
    - __service__
    target_label: job
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - replacement: /var/log/pods/*$1/*.log
    separator: /
    source_labels:
    - __meta_kubernetes_pod_uid
    - __meta_kubernetes_pod_container_name
    target_label: __path__
- job_name: kubernetes-pods-static
  pipeline_stages:
    - docker: {}
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: drop
    regex: ''
    source_labels:
    - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_label_component
    target_label: __service__
  - source_labels:
    - __meta_kubernetes_pod_node_name
    target_label: __host__
  - action: drop
    regex: ''
    source_labels:
    - __service__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: replace
    replacement: $1
    separator: /
    source_labels:
    - __meta_kubernetes_namespace
    - __service__
    target_label: job
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - replacement: /var/log/pods/*$1/*.log
    separator: /
    source_labels:
    - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
    - __meta_kubernetes_pod_container_name
    target_label: __path__
```

So again just to be explicit, it's the default config generated by helm that is causing issues for us. I can try spinning up a third promtail with the default config to test if it too has this issue as well?

**Comment by valmack** [comment]
I am having what seems like the same issue running in docker-compose locally. When promtail starts it parses existing logs but it isn't tailing. So adding new logs never get ingested.

**Comment by valmack** [comment]
My config is very simple
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

scrape_configs:
- job_name: cas
  static_configs:
  - targets:
      - localhost
    labels:
      job: cas/access
      __path__: /usr/local/var/log/cas/access.log
  pipeline_stages:
  - regex:
      expression: \[(?P<timestamp>.*)\]
  - timestamp:
      source: timestamp
      format: RFC1123
```

**Comment by valmack** [comment]
Interestingly enough, adding the working sample above seems to have fixed something. So changed my config to this

```
# updated this part v

client:
  backoff_config:
    max_period: 5m
    max_retries: 10
    min_period: 500ms
  batchsize: 1048576
  batchwait: 1s
  external_labels: {}
  timeout: 10s
target_config:
  sync_period: 5s
server:
  http_listen_port: 9080

# updated this part ^

positions:
  filename: /tmp/positions.yaml

scrape_configs:
- job_name: cas
  static_configs:
  - targets:
      - localhost
    labels:
      job: cas/access
      __path__: /usr/local/var/log/cas/access.log
  pipeline_stages:
  - regex:
      expression: \[(?P<timestamp>.*)\]
  - timestamp:
      source: timestamp
      format: RFC1123
```

And now not seeing the issue. However this section of the config is the same between your examples above
