### ISSUE TITLE
Promtail uses all available RAM

### ISSUE THREAD

**Issue by pasmon** [grafana/loki#2985]
Starting Promtail in baremetal RHEL 7.6 server with static config eats all server RAM, so that OOM killer kills even SSH daemon.

**To Reproduce**
1. Started Loki 1.6.1 in Docker in server1
2. Started Promtail binary 2.0 with service file in server2 to tail /var/log/*log using static config as in "Problematic Promtail config" shown below
3. Observe RAM usage go through the roof and struggle to kill Promtail and/or stop the service which starts it

**Expected behavior**
I expected Promtail to use minimal resources to gather and send logs to our Loki server.

**Environment:**
 - Infrastructure: Loki in Docker container in private cloud RHEL 7.6 instance (server1), Promtail in baremetal RHEL 7.6 (server2)
 - Deployment tool: Promtail installed with Ansible

Problematic Promtail config:
```
server:
  disable: true

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://server1:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - labels:
      job: varlogs
      host: {{ inventory_hostname }}
      __path__: /var/log/*log

```
Working Promtail config:
```
server:
  disable: true

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://server1:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
```
