### ISSUE TITLE
i/o timeout using syslog

### ISSUE THREAD

**Issue by loganmc10** [grafana/loki#3001]
**Describe the bug**
```level=warn ts=2020-11-28T15:04:00.019788651Z caller=syslogtarget.go:172 component=loki msg="error initializing syslog stream" err="read tcp 172.30.0.6:7514->172.30.0.5:44791: i/o timeout"```

**To Reproduce**
Here is my syslog-ng.conf:
```
source s_net {
  default-network-drivers();
};

destination d_loki {
  syslog("grafana_agent" transport("tcp") port(7514));
};

log {
  source(s_net);
  destination(d_loki);
};
```

I am using the Grafana Cloud Agent v0.8.0 for loki, here is the config:
```
loki:
  scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: grafana_agent:7514
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'hostname'
      - source_labels: ['__syslog_message_severity']
        target_label: 'severity'
      - source_labels: ['__syslog_message_facility']
        target_label: 'facility'
      - source_labels: ['__syslog_message_app_name']
        target_label: 'appname'
```

These are side-by-side docker containers.

**Expected behavior**
I can see logs coming into syslog-ng, but they aren't making it into Loki because of this error. The error appears every time a new log shows up

**Environment:**
Docker, using docker-compose

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
