### ISSUE TITLE
Table manager config not being used by cortex. 

### ISSUE THREAD

**Issue by colinrgodsey** [grafana/loki#3016]
**Describe the bug**
Configurations in the table_manager block do not seem to propagate to cortex. 

**To Reproduce**
1. Configure Loki (currently using master@854930e) to use AWS DynamoDB and S3.
2. Configure table_manager block with the following:
```yaml
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
  index_tables_provisioning:
    enable_ondemand_throughput_mode: true
    enable_inactive_throughput_on_demand_mode: true
    provisioned_write_throughput: 0
    provisioned_read_throughput: 0
    inactive_write_throughput: 0
    inactive_read_throughput: 0
  chunk_tables_provisioning:
    enable_ondemand_throughput_mode: true
    enable_inactive_throughput_on_demand_mode: true
    provisioned_write_throughput: 0
    provisioned_read_throughput: 0
    inactive_write_throughput: 0
    inactive_read_throughput: 0
```
3. Delete any existing DynamoDB tables so Loki will recreate them. 
4. Start Loki.
5. Confirm absence of yaml marshaling errors. 
6. Observe capacity values on newly provisioned tables are set at default (300 read, 1000 write iirc). 

**Expected behavior**
Cortex (via Loki?) should parse and honor the config. There's no config errors in the output on startup. I've tried using some fake keys in the block and parsing fails, so something is parsing them, but it doesn't seem to get used. Configuration in other blocks seem fine. I understand this could easily be a cortex issue, but I'm not sure how the config flows from Loki to Cortex, so thought I'd start here. 

**Environment:**
 - Infrastructure: Docker (grafana/loki:latest)
 - Deployment tool: Docker
