### ISSUE TITLE
Default promtail configuration in helm chart does not ingest logs of pods that do not have labels

### ISSUE THREAD

**Issue by patrickhuy** [grafana/loki#3037]
**Describe the bug**
When a pod is created in Kubernetes without any labels it's logs are not tailed by promtail.
When labels (for example `name`) are present everything works as intended.

**To Reproduce**
1. Install latest loki-stack via helm chart in Kubernetes: https://github.com/grafana/loki/tree/876be8838133a837fb685dfc566aa5e05498e4a1/production/helm/loki-stack
2. Start a plain pod without labels
```
apiVersion: v1
kind: Pod
metadata:
  name: testpod
#  labels:
#    name: testpod
spec:
  containers:
   - name: busybox
     image: busybox
     command: ["sh",  "-c", 'while true; do echo "X"; sleep 2; done']
```
3. Check promtail webinterface and observe that the pod is not being discovered

**Expected behavior**
The pod should be discovered and it's logs should be processed. The pod name/namespace label should be applied.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
