### ISSUE TITLE
Upgrade using helm from v1.6 to v2.0 - Back-off restarting failed container - mkdir /data/loki/boltdb-shipper-compactor: no space left on device

### ISSUE THREAD

**Issue by waterdrop01** [grafana/loki#3041]
**Describe the bug**
I first ran:
```
helm repo update
helm upgrade loki loki/loki --values helm-loki-values.yml
```
Then realized that for loki v2.0 to work, I needed to specify the Schema config. So I edited my `loki-values.yml`:
```
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}
  storageClassName:

updateStrategy:
  type: RollingUpdate

config: <-- added this key
  schema_config:
    configs:
      - from: 2018-04-15
        store: boltdb
        object_store: filesystem
        schema: v9
        index:
          prefix: index_
          period: 168h
      - from: 2020-12-05
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
```
Then ran again `helm upgrade loki loki/loki --values helm-loki-values.yml`, and now the error is `mkdir /tmp/loki: read-only file system`:
```
level=info ts=2020-12-04T21:49:18.173467126Z caller=main.go:128 msg="Starting Loki" version="(version=2.0.0, branch=HEAD, revision=6978ee5d7)"
level=info ts=2020-12-04T21:49:18.174171775Z caller=server.go:225 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2020-12-04T21:49:18.174488994Z caller=modules.go:420 msg="RulerStorage is not configured in single binary mode and will not be started."
level=error ts=2020-12-04T21:49:18.174725921Z caller=log.go:149 msg="error running loki" err="mkdir /tmp/loki: read-only file system\nerror initialising module: table-manager\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:204\nmain.main\n\t/src/loki/cmd/loki/main.go:130\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"
```
I then edited again `loki-values.yml` and added this to the config key (copied from [this file](https://github.com/grafana/loki/blob/master/production/helm/loki/values.yaml). remark: isn't this supposed to be the default?):
```
  compactor:
    working_directory: /data/loki/boltdb-shipper-compactor
    shared_store: filesystem
  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
      shared_store: filesystem
    filesystem:
      directory: /data/loki/chunks
```
And now the new error is `mkdir /data/loki/boltdb-shipper-compactor: no space left on device`:
```
level=info ts=2020-12-04T22:15:03.369739547Z caller=main.go:128 msg="Starting Loki" version="(version=2.0.0, branch=HEAD, revision=6978ee5d7)"
level=info ts=2020-12-04T22:15:03.370661406Z caller=server.go:225 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2020-12-04T22:15:03.371012399Z caller=modules.go:420 msg="RulerStorage is not configured in single binary mode and will not be started."
level=error ts=2020-12-04T22:15:03.371425347Z caller=log.go:149 msg="error running loki" err="mkdir /data/loki/boltdb-shipper-compactor: no space left on device\nerror initialising module: compactor\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:204\nmain.main\n\t/src/loki/cmd/loki/main.go:130\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373"
```
I then tried resizing the PVC from 10Gi to 20Gi, **but still same error...**

Any help would be much appreciated! Many thanks
