### ISSUE TITLE
Add option to define existing secret for Loki configuration

### ISSUE THREAD

**Issue by alex1989hu** [grafana/loki#3042]
**Is your feature request related to a problem? Please describe.**
If the administrator handles application on cluster in GitOps way, then it is not good practise to commit unencrypted password into version control but the current version of the chart does not support to reference pre-existing secret.

Given:  Administrator has Object Storage, Amazon S3 compatible. 
Then: Administrator creates `values.yaml` (snippet).
```yaml
loki:
  config:
    storage_config:
      aws:
        s3: https://minio_admin:mypassword@minio.foo.bar./loki
```
Then: Administrator commits into version control.
Then: Minio logon is credential leaked via Helm Chart parameters.

**Describe the solution you'd like**
Given:  Administrator has Object Storage, Amazon S3 compatible. 
Then: Administrator creates secret called `my-loki-secret`.
Then: Administrator creates `values.yaml` (snippet).

```yaml
loki:
  config:
    existingSecret: my-loki-secret
```
Then: Minio logon credential is not leaked via Helm Chart parameters.

**Describe alternatives you've considered**
This proposal add alternative solution to the current one.

**Additional context**
A lots of popular chart provide option to define pre-existing secret to set it as reference for application.
