### ISSUE TITLE
Promtail configuration failed parsing with unmarshal errors.

### ISSUE THREAD

**Issue by viktorisacenko** [grafana/loki#3052]
**Describe the bug**
Get unmarshall errors when i try to start promtail with config file.

**To Reproduce**
1. `cd /usr/local/bin`
2. `sudo curl -fSL -o promtail.gz "https://github.com/grafana/loki/releases/download/v2.0.0/promtail-linux-amd64.zip"`
3. `sudo gunzip promtail.gz`
4. `sudo chmod a+x promtail`
5. `sudo nano config-promtail.yml`

->
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
```

6. `sudo ./promtail -config.file ./config-promtail.yml`

->
```
failed parsing config: ./config-promtail.yml: yaml: unmarshal errors:
  line 5: field positions not found in type main.Config
  line 8: field clients not found in type main.Config
  line 11: field scrape_configs not found in type main.Config
```

**Environment:**
 - Ubuntu 18.04.5 LTS
