### ISSUE TITLE
 boltdb-shipper + retention_deletes: "object not found in storage" when the query goes over the retention-border

### ISSUE THREAD

**Issue by pcbl** [grafana/loki#3058]
**Describe the bug**
I am using Loki 2.0 and have a Loki Configuration that uses Boltdb-shipper, fileSystem and retention for a Week(168h). Here is the vomplete configuration:
```
auth_enabled: false

server:
  log_level: 'warn'

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: C:\ProgramData\POC\loki\index
    cache_location: C:\ProgramData\POC\loki\index\cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: C:\ProgramData\POC\loki\chunks
    
compactor:
  working_directory: C:\ProgramData\POC\loki\compactor
  shared_store: filesystem    

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: true
  retention_period: 168h
```
I am facing a situation that after one week passed, the retention period is due and the table manager starts removing old data as expected. But it seems that for some reason the process of removing old data is leaving Loki on an inconsistent state and as soon as I perform some searches one day after the "retention-border", I am getting an **object not found in storage** error. Scenarios:

- Search within the past 7 days(**now-7d**) (within retendion-border): **OK!**
- Search on an old period that happened before the retention-border, let`s say From 11th to 10th past day (outside retention-border): **OK!**
- Search on the day directly outside the retention border(8th day):  **object not found in storage**
- Search on a period that goes from within the retention border to something outside, From 1st day to 11th past day directly after the retention border(8th day):  **object not found in storage**

Would that be connected with this issue here?
https://github.com/grafana/loki/issues/2816

I am wondering if there`s a place where pre-release versions of loki are somewhere available so I could try the a build which contain this PR merged: https://github.com/grafana/loki/pull/2855
