### ISSUE TITLE
memcache config in loki 2.0

### ISSUE THREAD

**Issue by mrmassis** [grafana/loki#3070]
Hi everyone,
I have a problem with memcached. When i configure it, some loki comeponets report warns. 

```
level=warn ts=2020-12-11T19:13:19.590489326Z caller=memcached_client.go:209 msg="error updating memcache servers" err="lookup _memcached-client._tcp.memcached-index-queries.loki.svc.cluster.local:11211: no such host"
```
Why it happen?

my configs:
```
storage_config:
      aws:
         s3: XXXX
         s3forcepathstyle: true
      boltdb_shipper:
         active_index_directory: /data/loki/index
         shared_store: aws
         cache_location: /data/loki/boltdb-cache
      index_queries_cache_config:
         memcached:
             batch_size: 100
             parallelism: 100
         memcached_client:
             #consistent_hash: true
             host: memcached-index-queries.loki.svc.cluster.local
             service: memcached-client
  chunk_store_config:
      chunk_cache_config:
          memcached:
             batch_size: 100
             parallelism: 100
          memcached_client:
             #consistent_hash: true
             host: memcached.loki.svc.cluster.local
             service: memcached-client
      max_look_back_period: 0s
      write_dedupe_cache_config:
          memcached:
              batch_size: 100
              parallelism: 100
          memcached_client:
             #consistent_hash: true
             host: memcached-index-writes.loki.svc.cluster.local
             service: memcached-client
```
Pods:
```
oki-loki-cdefa-logaas-compactor-98bfdc5f9-w56gz          1/1     Running   0          4m52s
loki-loki-cdefa-logaas-distributor-7dfdc6cd47-jpkcl      1/1     Running   0          4m3s
loki-loki-cdefa-logaas-distributor-7dfdc6cd47-khvxp      1/1     Running   0          3m14s
loki-loki-cdefa-logaas-distributor-7dfdc6cd47-mztfq      1/1     Running   0          4m52s
loki-loki-cdefa-logaas-ingester-0                        0/1     Running   0          33s
loki-loki-cdefa-logaas-ingester-1                        1/1     Running   0          2m24s
loki-loki-cdefa-logaas-ingester-2                        1/1     Running   0          4m18s
loki-loki-cdefa-logaas-querier-db565fb99-q6467           1/1     Running   0          4m52s
loki-loki-cdefa-logaas-query-frontend-5c49b96879-75nvr   1/1     Running   0          4m52s
loki-loki-cdefa-logaas-ruler-0

memcached-0                                              1/1     Running       0          42m
memcached-1                                              1/1     Running       0          41m
memcached-index-frontend-0                               1/1     Running       0          40m
memcached-index-frontend-1                               1/1     Running       0          39m
memcached-index-queries-0                                1/1     Running       0          40m
memcached-index-queries-1                                1/1     Running       0          40m
memcached-index-write-0                                  1/1     Running       0          40m
memcached-index-write-1                                  1/1     Running       0          40m
```
