### ISSUE TITLE
Retention period documentation not explained well enough to avoid errors

### ISSUE THREAD

**Issue by asciifaceman** [grafana/loki#3071]
I followed the docs on retention (https://grafana.com/docs/loki/latest/operations/storage/retention/) and modified for a target 7 day retention (my teams goal).

However loki does not like this, producing the error

```
Dec 11 21:22:34 ip-10-90-167-90 loki[20343]: level=error ts=2020-12-11T21:22:34.312429706Z caller=main.go:85 msg="validating config" err="invalid schema config: boltdb-shipper works best with 24h periodic index config. Either add a new config with future date set to 24h to retain the existing index or change the existing config to use 24h period"
```

**To Reproduce**

```
schema_config:
    configs:
    - from: 2020-10-24
      ...
      index:
        ...
        period: 168h
...
chunk_store_config:
    max_look_back_period: 168h
table_manager:
    retention_deletes_enabled: true
    retention_period: 168h
```

**Expected behavior**
Working 7 day retention (instead of the documentations 28 day)

**Environment:**
bare metal install

```
$ loki --version
loki, version 2.0.0 (branch: HEAD, revision: 6978ee5d)
  build user:       root@2645337e4e98
  build date:       2020-10-26T15:54:56Z
  go version:       go1.14.2
  platform:         linux/amd64
```

```
Linux ip-10-90-167-90 4.15.0-1045-aws #47-Ubuntu SMP Fri Aug 2 13:50:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Screenshots, Promtail config, or terminal output**
```
Dec 11 21:22:34 ip-10-90-167-90 loki[20343]: level=error ts=2020-12-11T21:22:34.312429706Z caller=main.go:85 msg="validating config" err="invalid schema config: boltdb-shipper works best with 24h periodic index config. Either add a new config with future date set to 24h to retain the existing index or change the existing config to use 24h period"
Dec 11 21:22:34 ip-10-90-167-90 systemd[1]: loki.service: Main process exited, code=exited, status=1/FAILURE
Dec 11 21:22:34 ip-10-90-167-90 systemd[1]: loki.service: Failed with result 'exit-code'.
```

**Comment by asciifaceman** [comment]
I'll note that making this change "fixes" the issue, but the documentation implies it should be set to match your retention period

```
schema_config:
    configs:
    - from: 2020-10-24
      ...
      index:
        ...
        period: 24h
```
