### ISSUE TITLE
Issue with regex square bracket not working

### ISSUE THREAD

**Issue by avanichy25** [grafana/loki#3093]
I have a error pattern within square bracket and creating metrics with the pipeline mentioned below is not working:

Error: 
```
2020-12-19T02:56:18.317+0000 error: Something went wrong with the MongoDB connection
(node:1) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongo-0.mongo.svc.cluster.local:27017] on first connect [MongoError: Authentication failed.]
    at Pool.<anonymous> (/mongodb/lib/core/topologies/server.js:438:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at createConnection (/mongodb/lib/core/connection/pool.js:562:14)
    at connect (mongodb/lib/core/connection/pool.js:995:11)
    at callback (mongodb/lib/core/connection/connect.js:75:5)
    at authProvider.auth.err (mongodb/lib/core/connection/connect.js:147:27)
    at connection.command (mongodb/lib/core/auth/scram.js:185:14)
```

pipeline stages:
```
- match:
    selector: '{app="app-name"}'
    stages:
    - regex:
        expression: "^.*(?P<mongoerror>MongoError: Authentication failed).*$"
    - metrics:
        mongoerror_authentication_failed_count:
          type: Counter
          description: "Total error of mongodb authentication"
          source: mongoerror
          config:
            action: inc
```
