### ISSUE TITLE
Promtail logs a lot of "reason: 'entry out of order' for stream" errors

### ISSUE THREAD

**Issue by dguendisch** [grafana/loki#3097]
**Describe the bug**
While trying to upgrade from loki&promtail 1.30 -> 2.0.0 I noticed a lot of "entry out of order" errors in promtail logs.
Example error:
```
level=error ts=2020-12-22T14:19:35.437070698Z caller=client.go:294 component=client host=tm-loki:3100 msg="final error sending batch" status=400 error="server returned HTTP status 400 Bad Request (400): entry with timestamp 2020-12-22 14:19:34.717929748 +0000 UTC ignored, reason: 'entry out of order' for stream: {container=\"prometheus-kube-state-metrics\", filename=\"/var/log/pods/monitoring_tm-prometheus-kube-state-metrics-778fdd99b-2nzbm_566dfa4d-7489-4ea0-87d1-f4b204ea554b/prometheus-kube-state-metrics/0.log\", instance=\"tm-prometheus-kube-state-metrics-778fdd99b-2nzbm\", namespace=\"monitoring\", node=\"shoot--core--tm-os-st-tm-components-z1-55f65-mkpkm\", stream=\"stderr\"},"
```

What I don't get is the error msg itself, it complains about probably some non-uniqueness, but the stream labels should be pretty unique, i.e. there is only one such pod `tm-prometheus-kube-state-metrics-778fdd99b-2nzbm` running in my cluster and promtail being a daemonset results in having only one promtail process per node.

I have promtail deployed as a daemonset with this config:
```
  promtail.yaml: |
    clients:
      - url: http://tm-loki:3100/loki/api/v1/push
    positions:
      filename: /run/promtail/positions.yaml
    server:
      http_listen_port: 3101
    target_config:
      sync_period: 10s

    scrape_configs:
    - pipeline_stages:
      - docker: {}
      job_name: pods
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_label_workflows_argoproj_io_workflow
        target_label: argo_workflow
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_annotation_workflows_argoproj_io_node_name
        target_label: argo_node
```

**Expected behavior**
No such errors to occurr.

**Environment:**
 - Infrastructure: k8s
