### ISSUE TITLE
Issue with Winston.js and Promtail running in Docker

### ISSUE THREAD

**Issue by mmcxii** [grafana/loki#3118]
**Describe the bug**
I'm pretty sure this isn't actually an issue with Loki/ Promtail but I'm hoping someone here can help me out.

I'm trying to collect logs generated by the Winston.js Logger, which is generating a log file.

I have Promtail, Loki, and Grafana running in Docker containers and the logs mounted into the Promtail container using a volume. The containers spin up as expected and all existing logs are present on Grafana. However, when new logs are generated the volume does not update unless I go to the log file and save it using `CMD + s`, after which the volume updates and the new logs are discovered by Loki.

Here is my docker-compose.yml file:
```yml
version: "3.3"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:7.3.6
    ports:
      - 3000:3000
    env_file: ./.env.grafana
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - loki

  loki:
    container_name: loki
    image: grafana/loki:2.1.0
    ports:
      - 3100:3100


  promtail:
    container_name: promtail
    image: grafana/promtail:2.1.0
    ports:
      - 9080:9080
    command:
      - "--config.file=/etc/promtail/promtail.yml"
    volumes:
      - ./promtail.yml:/etc/promtail/promtail.yml
      - ../../logs:/var/log/app
```

My promtail config:
```yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: combined
    static_configs:
      - targets:
          - localhost
        labels:
          job: combined
          __path__: /var/log/app/*/*combined.log

  - job_name: error
    static_configs:
      - targets:
          - localhost
        labels:
          job: error
          __path__: /var/log/app/*/*error.log
```

The Winston config:
```ts
const logger = Winston.createLogger({
  transports: [
    new Winston.transports.DailyRotateFile({
      filename: "logs/%DATE%/%DATE%-error.log",
      datePattern: "YYYY-MM-DD",
      level: "error",
    }),
    new Winston.transports.DailyRotateFile({
      filename: "logs/%DATE%/%DATE%-combined.log",
      datePattern: "YYYY-MM-DD",
      level: "info",
    }),
  ],
)};
```
Note: I have also tried this with the regular `Winston.transports.File` and it does not work.

**To Reproduce**
1. Start Loki, Promtail, and Grafana in Docker containers
2. Output logs to a file using Winston.js
3. Logs should be present in Loki via Promtail, but are not.

**Expected behavior**
Logs should be updated in a Docker Container but are not.

**Environment:**
 - Infrastructure: Macbook 2019
 - Deployment tool: Docker-Compose

**Screenshots, Promtail config, or terminal output**
```
level=info ts=2021-01-04T22:09:04.167968183Z caller=server.go:225 http=[::]:9080 grpc=[::]:46531 msg="server listening on addresses"
level=info ts=2021-01-04T22:09:04.168167904Z caller=main.go:110 msg="Starting Promtail" version="(version=2.1.0, branch=HEAD, revision=1b79df375)"
level=info ts=2021-01-04T22:09:09.167953932Z caller=filetargetmanager.go:261 msg="Adding target" key="{job=\"combined\"}"
level=info ts=2021-01-04T22:09:09.172877035Z caller=tailer.go:122 component=tailer msg="tail routine: started" path=/var/log/app/2021-01-04/2021-01-04-combined.log
level=info ts=2021-01-04T22:09:09.172918442Z caller=filetargetmanager.go:261 msg="Adding target" key="{job=\"error\"}"
ts=2021-01-04T22:09:09.172965798Z caller=log.go:124 component=tailer level=info msg="Seeked /var/log/app/2021-01-04/2021-01-04-combined.log - &{Offset:0 Whence:0}"
level=info ts=2021-01-04T22:09:09.175448344Z caller=tailer.go:122 component=tailer msg="tail routine: started" path=/var/log/app/2021-01-04/2021-01-04-error.log
ts=2021-01-04T22:09:09.175480895Z caller=log.go:124 component=tailer level=info msg="Seeked /var/log/app/2021-01-04/2021-01-04-error.log - &{Offset:0 Whence:0}"
```
