### ISSUE TITLE
Examples for Relabel Configs and LogQL Queries

### ISSUE THREAD

**Issue by base698** [grafana/loki#312]
Can we get an example of:
* Relabel Config.  I only found that was a thing digging through the source.  I have no experience with prometheus so it's not something I really understand.  I'm trying to pull a value out of a logline and use that as a label.  Source label doesn't make sense, but target label does.  
This is best I can come up with, but doesn't seem to work:
```
  relabel_configs:
    - source_labels: [logfield]
      regex: '.*level=([a-zA-Z]+).*'
      replacement: '${1}'
      target_label: 'level'
      action: replace
 ```
* Working `logcli query` example.  I'm unable to figure out how to read the logs that have been ingested beyond `logcli labels`

_Originally posted by @base698 in https://github.com/grafana/loki/issues/72#issuecomment-461988739_
