### ISSUE TITLE
logstash-to-loki entry out of order

### ISSUE THREAD

**Issue by ZPerling** [grafana/loki#3127]
**Describe the bug**
loki lose log caused by entry out of order. I can confirm my log is increased.

**Expected behavior**
container log pipeline: filebeat --> kafka --> logstash --> loki

**Environment:**
loki run used statefulset, loki.yaml
```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
compactor:
  shared_store: filesystem
  working_directory: /data/loki/boltdb-shipper-compactor
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
memberlist:
  join_members:
  - loki-headless.loki.svc.cluster.local
schema_config:
  configs:
  - from: "2020-12-05"
    index:
      period: 24h
      prefix: loki_index_test
    object_store: s3
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
storage_config:
  aws:
    access_key_id: xxx
    bucketnames: loki-bucket
    endpoint: xxx
    insecure: true
    region: ap-beijing
    s3forcepathstyle: true
    secret_access_key: xxx
  boltdb_shipper:
    active_index_directory: /data/boltdb-shipper-active
    cache_location: /data/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: s3
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
```

logstash.config
```
input {
    kafka {
        bootstrap_servers => "kafka-broker1.:9092"
        topics_pattern => "^k8s_app-backend.*(stag|dev)$"
        consumer_threads => 3
        codec => json {
            charset => "UTF-8"
        }
        auto_offset_reset => "latest"
        group_id => "logstash-to-loki"
    }
}

filter {
    if [datetime] {
        date {
            match => ["datetime", "yyyy-MM-dd HH:mm:ss", "yyyy-MM-dd HH:mm:ss:SSS","ISO8601"]
            target => "@timestamp"
            timezone => "Asia/Shanghai"
            locale => "cn"
            add_field => {
                "dt" => "%{@timestamp}"
            }
        }
    }

    if [kubernetes] {
        mutate {
            replace => {
                "service" => "%{[kubernetes][labels][service]}"
                "cluster" => "%{[kubernetes][labels][cluster]}"
                "pod" => "%{[kubernetes][pod_name]}"
            }
        }
    }

    mutate {
        split => ["log_path", "/"]
        add_field => { "logFile" => "%{[log_path][-1]}"}
        remove_field => ["[kafkaTopic]", "[kubernetes]", "[log_path]", "[@version]", "[serviceGroup]", "[serviceName]", "[indexes]"]
    }

    ruby {
        code => "
            hash = event.to_hash
            event.set('[loki_message]', {})
            hash.each { |key,value|
                if not Array['cluster', 'pod', 'logFile', '@timestamp'].include?(key)
                    event.set('[loki_message][%s]' % [key], value)
                    event.remove(key)
                end
            }
            event.remove('[message]')
            event.set('[loki_message]', event.get('[loki_message]').to_json)
        "
    }
}

output {
  loki {
    url => "http://loki:3100/loki/api/v1/push"
    batch_size => 204800
    retries => 5
    min_delay => 3
    max_delay => 500
    message_field => "loki_message"
    insecure_skip_verify => true
  }
  stdout {}
}
```
my log label {"pod":"xxx", "logFile":"balabal"}，this is unique，but log to loki is lost, so I think some problem is logstash multi thread, how log label can join the logstash thread id?
