### ISSUE TITLE
fluent-bit  labelmap doesn't discover namespace_labels

### ISSUE THREAD

**Issue by CloudXiaobai** [grafana/loki#3130]
**Describe the bug**
Starting with version 2.2.0, the grafana/fluent-bit helm chart.  `namespace_lables` are included in **values.config.labelMap**

```
config：
  labelMap:
    kubernetes:
      namespace_name: k8s_namespace_name
      namespace_labels:
        app_kubernetes_io/project_name: k8s_project_name
        app_kubernetes_io/zone: k8s_env_name
      labels:
        app: k8s_app_name
        app_kubernetes_io/name: k8s_app_name
        app_image_version: k8s_image_version
      host: k8s_node
      container_name: k8s_container_name
      pod_name: k8s_pod_name
    stream: stream
```

After fluent-bit actived, i can't found any namespace labels in loki.

```
curl http://loki:3100/api/prom/label
{"values":["__name__","k8s_app_name","k8s_cloud_cluster","k8s_container_name","k8s_namespace_name","k8s_node","k8s_pod_name","stream"]}
```

**To Reproduce**
1. Started Loki (6978ee5d7)
2. Started fluent-bit images: grafana/fluent-bit-plugin-loki: 2.1.0-amd64

**Expected behavior**
kubernetes namespace labels included in log stream

**Environment:**
 - Infrastructure:kubernets
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
configmap/fluent-bit

```
  fluent-bit.conf: |-
    [SERVICE]
        HTTP_Server    On
        HTTP_Listen    0.0.0.0
        HTTP_PORT      2020
        Flush          1
        Daemon         Off
        Log_Level      warn
        Parsers_File   parsers.conf
    [INPUT]
        Name           tail
        Tag            kube.*
        Path           /var/log/containers/*.log
        Parser         cri
        DB             /run/fluent-bit/flb_kube.db
        Mem_Buf_Limit  256MB
        Skip_Long_Lines On
    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_URL       https://kubernetes.default.svc:443
        Merge_Log On
        K8S-Logging.Exclude Off
        K8S-Logging.Parser Off
    [Output]
        Name grafana-loki
        Match kube.*
        Url http://stable-loki:3100/api/prom/push
        TenantID ""
        BatchWait 1
        BatchSize 1048576
        Labels {k8s_cloud_cluster="cloud-poc-0"}
        RemoveKeys kubernetes,stream
        AutoKubernetesLabels false
        LabelMapPath /fluent-bit/etc/labelmap.json
        LineFormat json
        LogLevel warn
  labelmap.json: |-
    {
      "kubernetes": {
        "container_name": "k8s_container_name",
        "host": "k8s_node",
        "labels": {
          "app": "k8s_app_name",
          "app_image_version": "k8s_image_version",
          "app_kubernetes_io/name": "k8s_app_name"
        },
        "namespace_labels": {
          "app_kubernetes_io/project_name": "k8s_project_name",
          "app_kubernetes_io/zone": "k8s_env_name"
        },
        "namespace_name": "k8s_namespace_name",
        "pod_name": "k8s_pod_name"
      },
      "stream": "stream"
    }
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
    [PARSER]
        Format regex
        Name cri
        Regex ^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Key time
```
