### ISSUE TITLE
Not uploaded index file in k8s preStop with boltdb-shipper/Monolithic mode 

### ISSUE THREAD

**Issue by nh03** [grafana/loki#3142]
**Describe the bug**
I try to use loki with boltdb-shipper/Monolithic mode/k8s on the condition that a persistent storage for storing index files is not used.
In this case, I'm sure the index file is lost and I can't search the logs by rolling update of the pod.
So I added a 15 minute sleep to the k8s prestop and tried to wait for the index file to be uploaded.
The index file upload was recorded in the loki's log while loki pod was terminating, but the index file was not actually uploaded.(chunk upload is success.)
I don't know why index file didn't uploade. 
Is it a bad idea to add 15 minutes of sleep to k8s prestop and wait for the index to upload?

**To Reproduce**
1. Start Loki-2.1.0(boltdb-shipper/Monolithic mode/not used persistent storage for storing index/add 15 minutes of sleep to k8s prestop), Promtail-2.1.0 on k8s
2. Start streaming logs
3. Rollout restart loki's pod

**Expected behavior**
Index file is uploaded even during rolling update of pod.

**Environment:**
 - Kubernetes
 - Loki-2.1.0
 - Promtail-2.1.0

**Screenshots, Promtail config, or terminal output**
Log of loki pod being terminating in rolling update
```
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:54:36.866043515Z caller=table_manager.go:208 msg="syncing tables"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:54:41.866128997Z caller=table_manager.go:208 msg="syncing tables"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:54:46.866092311Z caller=table_manager.go:208 msg="syncing tables"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:54:51.866077325Z caller=table_manager.go:208 msg="syncing tables"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:54:56.86601657Z caller=table_manager.go:208 msg="syncing tables"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:54:56.866036395Z caller=table_manager.go:171 msg="uploading tables"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:54:56.866106373Z caller=table.go:340 msg="uploading table loki_index_18634"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:54:56.866146824Z caller=table.go:367 msg="finished uploading table loki_index_18634"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:54:56.866166987Z caller=table.go:425 msg="cleaning up unwanted dbs from table loki_index_18634"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:54:56.866217202Z caller=table.go:340 msg="uploading table loki_index_18635"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:54:56.866232403Z caller=table.go:367 msg="finished uploading table loki_index_18635"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:54:56.866243246Z caller=table.go:425 msg="cleaning up unwanted dbs from table loki_index_18635"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:55:01.866085562Z caller=table_manager.go:208 msg="syncing tables"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:55:06.866112493Z caller=table_manager.go:208 msg="syncing tables"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:55:11.86604267Z caller=table_manager.go:208 msg="syncing tables"
loki-dev1-6fdfd7b664-sc886 loki level=info ts=2021-01-08T04:55:16.86608447Z caller=table_manager.go:208 msg="syncing tables"
```
loki.config
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki-config: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 5m
      max_chunk_age: 5m

    schema_config:
      configs:
      - from: 2018-04-15
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: loki_index_
          period: 24h
        chunks:
          prefix: loki_chunk_
          period: 24h

    storage_config:
      aws:
        s3: s3://****
        region: dev
        s3forcepathstyle: true

      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
        resync_interval: 5s
        shared_store: s3

    compactor:
      working_directory: /loki/compactor
      shared_store: s3

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    table_manager:
      retention_deletes_enabled: true
      retention_period: 8760h
```
