### ISSUE TITLE
AWS S3 and DynamoDB storage configuration not working with Loki

### ISSUE THREAD

**Issue by rward27** [grafana/loki#3196]
Hi
I am digging into the issue since past 3 days but could not resolve what could be the issue.
Below is my configuration for Loki

```
storage_config:
  aws:
    s3: s3://AKIA4L*****SBIF:f***********YXwahL3CaIwkFELXmy5jo@us-east-1
    bucketnames: test1203
    dynamodb:
      dynamodb_url: dynamodb://AKIA4L*****SBIF:f***********YXwahL3CaIwkFELXmy5jo@us-east-1
schema_config:
  configs:
    - from: 2021-01-20
      store: dynamodb
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
table_manager:
  retention_deletes_enabled: true
  retention_period: 336h
```

I am not getting any errors also in the logs in grafana dashboard. I get almost all the logs in my grafana dashboard having Loki as datasource. Not sure what is wrong with this config. I have also tried all the possible configurations that are provided in grafana documentation and references. But no luck so far.

Can anyone please help me in resolving the issue and making this work with AWS S3/Dynamodb storage?
