### ISSUE TITLE
Windows Promtail Regex requires double escape's

### ISSUE THREAD

**Issue by jengstro2** [grafana/loki#3197]
Following log line format to recognize level out of it. 
WARN | 2021-01-16 02:20:27.7759 | 00:27:51.532 | DuplicateVectorLogger.MoveNext | Tried to insert a duplicate vector ..."

Regex would be this (including white space and pipe):
`(?P<level>(DEBUG\s\||INFO\s\||WARN\s\||ERROR\s\||FATAL\s\|))(.*)`

Windows promtail (2.1.0) won't accept this. It will cry out on yaml illegal escape character found.
I found out, that you need to use double escapes like this (which to my understanding is not valid regex syntax):

```
  pipeline_stages:
  - match:
      selector: '{job="MyJob"}'
      stages:
      - regex:
          expression: "(?P<level>(DEBUG\\s\\||INFO\\s\\||WARN\\s\\||ERROR\\s\\||FATAL\\s\\|))(.*)"
      - labels:
          level:
```
Took a while to figure this out...
