### ISSUE TITLE
Custom metrics are not displayed on /metrics

### ISSUE THREAD

**Issue by ellcrysx** [grafana/loki#3198]
**Describe the bug**
Metrics with the histogram type did not appear at the endpoint of promtail

**To Reproduce**
1. Started Promtail 
image:
  repository: grafana/promtail
  tag: 2.1.0
2. Check all metrics on promtail:port/metrics

**Expected behavior**
I expected to get metrics with the promtail_custom prefix

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
```
 name: promtail
version: 2.2.0
appVersion: v2.1.0
kubeVersion: "^1.10.0-0"
```

**Screenshots, Promtail config, or terminal output**
```
  - job_name: kubernetes-pods-app
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - action: drop
      regex: .+
      source_labels:
      - __meta_kubernetes_pod_label_name
    - source_labels:
      - __meta_kubernetes_pod_label_app
      target_label: __service__
    - source_labels:
      - __meta_kubernetes_pod_node_name
      target_label: __host__
    - action: drop
      regex: ''
      source_labels:
      - __service__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - action: replace
      replacement: $1
      separator: /
      source_labels:
      - __meta_kubernetes_namespace
      - __service__
      target_label: job
    - action: replace
      source_labels:
      - __meta_kubernetes_namespace
      target_label: namespace
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_name
      target_label: pod
    - action: replace
      source_labels:
      - __meta_kubernetes_pod_container_name
      target_label: container
    - replacement: /var/log/pods/*$1/*.log
      separator: /
      source_labels:
      - __meta_kubernetes_pod_uid
      - __meta_kubernetes_pod_container_name
      target_label: __path__
    pipeline_stages:
      - match:
          selector: '{job="ingress-nginx/nginx-ingress"}'
          stages:
            - regex:
                expression: '(?P<remote_addr>[\w\.]+) - (?P<remote_user>[^ ]*) \[(?P<time_local>.*)\] \\"(?P<method>[^ ]*) (?P<request>[^ ]*) (?P<protocol>[^ ]*)\\" (?P<status>[\d]+) (?P<body_bytes_sent>[\d]+) \\"(?P<http_referer>[^ ]*)\\" \\"(?P<http_user_agent>[^"]*)\\" (?P<request_length>[\d]+) (?P<request_time>[\d\.]+) \[(?P<proxy_upstream_name>[^ ]*)\] \[(?P<proxy_alt_upstream_name>[^ ]*)\] (?P<upstream_addr>[\d\.\:]+) (?P<upstream_response_length>[\d]+) (?P<upstream_response_time>[\d\.]+) (?P<upstream_status>[\d]+)?'
            - regex:
                source: http_referer
                expression: .*\/\/(?P<url>[^\/:]+).*
            - metrics:
                http_nginx_request_time:
                  type: Histogram
                  description: "request time ms"
                  source: request_time
                  config:
                    buckets: [0.010,0.050,0.100,0.200,0.500,1.0]
            - labels:
                method:
                protocol:
                status:
                url:
                upstream_addr:
                namespace:
                pod:
      - match:
          selector: '{url=""}'
          stages:
            - regex:
                source: proxy_upstream_name
                expression: '(?P<url>[^ ].*)'
            - labels:
                url:
```

> 
> level=debug ts=2021-01-20T09:38:58.661523409Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=1 name=regex labels="{app=\"nginx-ingress\", app_kubernetes_io_component=\"controller\", component=\"controller\", container=\"nginx-ingress-controller\", filename=\"/var/log/pods/ingress-nginx_ingress-nginx-nginx-ingress-controller-64786954cc-7ncb4_08a25105-f70f-4de1-87dc-889b649fa31e/nginx-ingress-controller/0.log\", job=\"ingress-nginx/nginx-ingress\", namespace=\"ingress-nginx\", pod=\"ingress-nginx-nginx-ingress-controller-64786954cc-7ncb4\", pod_template_hash=\"64786954cc\", release=\"ingress-nginx\"}" time=2021-01-20T09:38:58.660841654Z entry="{\"log\":\"2021/01/20 09:38:17 [warn] 32622#32622: *112132202 a client request body is buffered to a temporary file /tmp/client-body/0014058147, client: 10.233.106.0, server: loki.company.ru, request: \\\"POST /loki/api/v1/push HTTP/2.0\\\", host: \\\"loki.company.ru\\\"\\n\",\"stream\":\"stderr\",\"time\":\"2021-01-20T09:38:17.05323393Z\"}"
> level=debug ts=2021-01-20T09:38:58.6613961Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=1 name=labels labels="{app=\"promtail\", container=\"promtail\", controller_revision_hash=\"5456fdfc5d\", filename=\"/var/log/pods/monitoring_loki-promtail-6b7t5_ccda60fc-125d-4e49-baa6-4fbc2c8107a3/promtail/0.log\", job=\"monitoring/promtail\", namespace=\"monitoring\", pod=\"loki-promtail-6b7t5\", pod_template_generation=\"9\", release=\"loki\"}" time=2021-01-20T09:38:58.660889872Z entry="{\"log\":\"level=debug ts=2021-01-20T09:38:23.194153084Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg=\\\"processing pipeline\\\" stage=0 name=match labels=\\\"{app="promtail", container="promtail", controller_revision_hash="5456fdfc5d", filename="/var/log/pods/monitoring_loki-promtail-6b7t5_ccda60fc-125d-4e49-baa6-4fbc2c8107a3/promtail/0.log", job="monitoring/promtail", namespace="monitoring", pod="loki-promtail-6b7t5", pod_template_generation="9", release="loki"}\\\" time=2021-01-20T09:38:23.19392794Z entry=\\\"{"log":"level=debug ts=2021-01-20T09:38:22.849295595Z caller=regex.go:120 component=file_pipeline component=stage type=regex msg="regex did not match" input="{"log":"2021/01/20 09:38:11 [warn] 32622#32622: *112123724 a client request body is buffered to a temporary file /tmp/client-body/0014057830, client: 10.233.106.0, server: loki.company.ru, request: \"POST /loki/api/v1/push HTTP/2.0\", host: \"loki.company.ru\"\n","stream":"stderr","time":"2021-01-20T09:38:11.377518184Z"}" regex="(?P\u003cremote_addr\u003e[\w\.]+) - (?P\u003cremote_user\u003e[^ ]*) \[(?P\u003ctime_local\u003e.*)\] \\"(?P\u003cmethod\u003e[^ ]*) (?P\u003crequest\u003e[^ ]*) (?P\u003cprotocol\u003e[^ ]*)\\" (?P\u003cstatus\u003e[\d]+) (?P\u003cbody_bytes_sent\u003e[\d]+) \\"(?P\u003chttp_referer\u003e[^ ]*)\\" \\"(?P\u003chttp_user_agent\u003e[^"]*)\\" (?P\u003crequest_length\u003e[\d]+) (?P\u003crequest_time\u003e[\d\.]+) \[(?P\u003cproxy_upstream_name\u003e[^ ]*)\] \[(?P\u003cproxy_alt_upstream_name\u003e[^ ]*)\] (?P\u003cupstream_addr\u003e[\d\.\:]+) (?P\u003cupstream_response_length\u003e[\d]+) (?P\u003cupstream_response_time\u003e[\d\.]+) (?P\u003cupstream_status\u003e[\d]+)?"\n","stream":"stderr","time":"2021-01-20T09:38:22.849354541Z"}\\\"\\n\",\"stream\":\"stderr\",\"time\":\"2021-01-20T09:38:23.194361949Z\"}"
> level=debug ts=2021-01-20T09:38:58.66155941Z caller=regex.go:94 component=file_pipeline component=stage type=regex msg="source does not exist in the set of extracted values" source=http_referer
> level=debug ts=2021-01-20T09:38:58.66157311Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=2 name=metrics labels="{app=\"nginx-ingress\", app_kubernetes_io_component=\"controller\", component=\"controller\", container=\"nginx-ingress-controller\", filename=\"/var/log/pods/ingress-nginx_ingress-nginx-nginx-ingress-controller-64786954cc-7ncb4_08a25105-f70f-4de1-87dc-889b649fa31e/nginx-ingress-controller/0.log\", job=\"ingress-nginx/nginx-ingress\", namespace=\"ingress-nginx\", pod=\"ingress-nginx-nginx-ingress-controller-64786954cc-7ncb4\", pod_template_hash=\"64786954cc\", release=\"ingress-nginx\"}" time=2021-01-20T09:38:58.660841654Z entry="{\"log\":\"2021/01/20 09:38:17 [warn] 32622#32622: *112132202 a client request body is buffered to a temporary file /tmp/client-body/0014058147, client: 10.233.106.0, server: loki.company.ru, request: \\\"POST /loki/api/v1/push HTTP/2.0\\\", host: \\\"loki.company.ru\\\"\\n\",\"stream\":\"stderr\",\"time\":\"2021-01-20T09:38:17.05323393Z\"}"
> level=debug ts=2021-01-20T09:38:58.661599439Z caller=metrics.go:174 component=file_pipeline msg="source does not exist" err="source: request_time, does not exist"
> level=debug ts=2021-01-20T09:38:58.661566286Z caller=pipeline.go:113 component=file_pipeline component=pipeline msg="finished processing log line" labels="{app=\"promtail\", container=\"promtail\", controller_revision_hash=\"5456fdfc5d\", filename=\"/var/log/pods/monitoring_loki-promtail-6b7t5_ccda60fc-125d-4e49-baa6-4fbc2c8107a3/promtail/0.log\", job=\"monitoring/promtail\", namespace=\"monitoring\", pod=\"loki-promtail-6b7t5\", pod_template_generation=\"9\", release=\"loki\"}" time=2021-01-20T09:38:58.660889872Z entry="{\"log\":\"level=debug ts=2021-01-20T09:38:23.194153084Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg=\\\"processing pipeline\\\" stage=0 name=match labels=\\\"{app="promtail", container="promtail", controller_revision_hash="5456fdfc5d", filename="/var/log/pods/monitoring_loki-promtail-6b7t5_ccda60fc-125d-4e49-baa6-4fbc2c8107a3/promtail/0.log", job="monitoring/promtail", namespace="monitoring", pod="loki-promtail-6b7t5", pod_template_generation="9", release="loki"}\\\" time=2021-01-20T09:38:23.19392794Z entry=\\\"{"log":"level=debug ts=2021-01-20T09:38:22.849295595Z caller=regex.go:120 component=file_pipeline component=stage type=regex msg="regex did not match" input="{"log":"2021/01/20 09:38:11 [warn] 32622#32622: *112123724 a client request body is buffered to a temporary file /tmp/client-body/0014057830, client: 10.233.106.0, server: loki.company.ru, request: \"POST /loki/api/v1/push HTTP/2.0\", host: \"loki.company.ru\"\n","stream":"stderr","time":"2021-01-20T09:38:11.377518184Z"}" regex="(?P\u003cremote_addr\u003e[\w\.]+) - (?P\u003cremote_user\u003e[^ ]*) \[(?P\u003ctime_local\u003e.*)\] \\"(?P\u003cmethod\u003e[^ ]*) (?P\u003crequest\u003e[^ ]*) (?P\u003cprotocol\u003e[^ ]*)\\" (?P\u003cstatus\u003e[\d]+) (?P\u003cbody_bytes_sent\u003e[\d]+) \\"(?P\u003chttp_referer\u003e[^ ]*)\\" \\"(?P\u003chttp_user_agent\u003e[^"]*)\\" (?P\u003crequest_length\u003e[\d]+) (?P\u003crequest_time\u003e[\d\.]+) \[(?P\u003cproxy_upstream_name\u003e[^ ]*)\] \[(?P\u003cproxy_alt_upstream_name\u003e[^ ]*)\] (?P\u003cupstream_addr\u003e[\d\.\:]+) (?P\u003cupstream_response_length\u003e[\d]+) (?P\u003cupstream_response_time\u003e[\d\.]+) (?P\u003cupstream_status\u003e[\d]+)?"\n","stream":"stderr","time":"2021-01-20T09:38:22.849354541Z"}\\\"\\n\",\"stream\":\"stderr\",\"time\":\"2021-01-20T09:38:23.194361949Z\"}" duration_s=0.000235093
> level=debug ts=2021-01-20T09:38:58.661607114Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=3 name=labels labels="{app=\"nginx-ingress\", app_kubernetes_io_component=\"controller\", component=\"controller\", container=\"nginx-ingress-controller\", filename=\"/var/log/pods/ingress-nginx_ingress-nginx-nginx-ingress-controller-64786954cc-7ncb4_08a25105-f70f-4de1-87dc-889b649fa31e/nginx-ingress-controller/0.log\", job=\"ingress-nginx/nginx-ingress\", namespace=\"ingress-nginx\", pod=\"ingress-nginx-nginx-ingress-controller-64786954cc-7ncb4\", pod_template_hash=\"64786954cc\", release=\"ingress-nginx\"}" time=2021-01-20T09:38:58.660841654Z entry="{\"log\":\"2021/01/20 09:38:17 [warn] 32622#32622: *112132202 a client request body is buffered to a temporary file /tmp/client-body/0014058147, client: 10.233.106.0, server: loki.company.ru, request: \\\"POST /loki/api/v1/push HTTP/2.0\\\", host: \\\"loki.company.ru\\\"\\n\",\"stream\":\"stderr\",\"time\":\"2021-01-20T09:38:17.05323393Z\"}"
> level=debug ts=2021-01-20T09:38:58.661612898Z caller=pipeline.go:113 component=file_pipeline component=pipeline msg="finished processing log line" labels="{app=\"promtail\", container=\"promtail\", controller_revision_hash=\"5456fdfc5d\", filename=\"/var/log/pods/monitoring_loki-promtail-6b7t5_ccda60fc-125d-4e49-baa6-4fbc2c8107a3/promtail/0.log\", job=\"monitoring/promtail\", namespace=\"monitoring\", pod=\"loki-promtail-6b7t5\", pod_template_generation=\"9\", release=\"loki\"}" time=2021-01-20T09:38:58.660889872Z entry="{\"log\":\"level=debug ts=2021-01-20T09:38:23.194153084Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg=\\\"processing pipeline\\\" stage=0 name=match labels=\\\"{app="promtail", container="promtail", controller_revision_hash="5456fdfc5d", filename="/var/log/pods/monitoring_loki-promtail-6b7t5_ccda60fc-125d-4e49-baa6-4fbc2c8107a3/promtail/0.log", job="monitoring/promtail", namespace="monitoring", pod="loki-promtail-6b7t5", pod_template_generation="9", release="loki"}\\\" time=2021-01-20T09:38:23.19392794Z entry=\\\"{"log":"level=debug ts=2021-01-20T09:38:22.849295595Z caller=regex.go:120 component=file_pipeline component=stage type=regex msg="regex did not match" input="{"log":"2021/01/20 09:38:11 [warn] 32622#32622: *112123724 a client request body is buffered to a temporary file /tmp/client-body/0014057830, client: 10.233.106.0, server: loki.company.ru, request: \"POST /loki/api/v1/push HTTP/2.0\", host: \"loki.company.ru\"\n","stream":"stderr","time":"2021-01-20T09:38:11.377518184Z"}" regex="(?P\u003cremote_addr\u003e[\w\.]+) - (?P\u003cremote_user\u003e[^ ]*) \[(?P\u003ctime_local\u003e.*)\] \\"(?P\u003cmethod\u003e[^ ]*) (?P\u003crequest\u003e[^ ]*) (?P\u003cprotocol\u003e[^ ]*)\\" (?P\u003cstatus\u003e[\d]+) (?P\u003cbody_bytes_sent\u003e[\d]+) \\"(?P\u003chttp_referer\u003e[^ ]*)\\" \\"(?P\u003chttp_user_agent\u003e[^"]*)\\" (?P\u003crequest_length\u003e[\d]+) (?P\u003crequest_time\u003e[\d\.]+) \[(?P\u003cproxy_upstream_name\u003e[^ ]*)\] \[(?P\u003cproxy_alt_upstream_name\u003e[^ ]*)\] (?P\u003cupstream_addr\u003e[\d\.\:]+) (?P\u003cupstream_response_length\u003e[\d]+) (?P\u003cupstream_response_time\u003e[\d\.]+) (?P\u003cupstream_status\u003e[\d]+)?"\n","stream":"stderr","time":"2021-01-20T09:38:22.849354541Z"}\\\"\\n\",\"stream\":\"stderr\",\"time\":\"2021-01-20T09:38:23.194361949Z\"}" duration_s=0.000445163
