### ISSUE TITLE
Configure runtime_config  There's a problem after configuration

### ISSUE THREAD

**Issue by guleng** [grafana/loki#3199]
1.Added configuration：
    runtime_config:
      file: /etc/loki/loki.yaml
      period: 20s

2.Version number
    loki:2.1.0

3.report errors
```
level=error ts=2021-01-20T10:59:58.731484227Z caller=manager.go:137 msg="failed to load config" err="yaml: unmarshal errors:
line 1: field auth_enabled not found in type loki.runtimeConfigValues
line 2: field chunk_store_config not found in type loki.runtimeConfigValues  
line 17: field compactor not found in type loki.runtimeConfigValues
line 20: field distributor not found in type loki.runtimeConfigValues  
line 28: field ingester not found in type loki.runtimeConfigValues 
line 53: field limits_config not found in type loki.runtimeConfigValues 
line 62: field querier not found in type loki.runtimeConfigValues
line 68: field ruler not found in type loki.runtimeConfigValues  
line 94: field runtime_config not found in type loki.runtimeConfigValues  
line 97: field schema_config not found in type loki.runtimeConfigValues  
line 107: field server not found in type loki.runtimeConfigValues
line 110: field storage_config not found in type loki.runtimeConfigValues  
line 125: field table_manager not found in type loki.runtimeConfigValues"
```
4. But the service is running normally, that is, an error is reported in the log

5.my config
```
auth_enabled: false
chunk_store_config:
  cache_lookups_older_than: 8h
  chunk_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_bytes: 20GB
      max_size_items: 1000000
      validity: 1h
  max_look_back_period: 720h
  write_dedupe_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_bytes: 20GB
      max_size_items: 100000
      validity: 1h
compactor:
  shared_store: filesystem
  working_directory: /data/loki/boltdb-shipper-compactor
distributor:
  ring:
    heartbeat_timeout: 1m
    kvstore:
      consul:
        host: sh-consul.aibee.cn:8500
      prefix: collectors/
      store: consul
ingester:
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_idle_period: 1h
  chunk_retain_period: 15m
  chunk_target_size: 0
  lifecycler:
    heartbeat_period: 5s
    join_after: 30s
    num_tokens: 512
    ring:
      kvstore:
        consul:
          consistent_reads: true
          host: sh-consul.aibee.cn:8500
          http_client_timeout: 20s
        prefix: collectors/
        store: consul
      replication_factor: 3
    tokens_file_path: /data/tokens
  max_chunk_age: 1h
  max_transfer_retries: 60
  query_store_max_look_back_period: 0
  sync_min_utilization: 0.8
  sync_period: 0
limits_config:
  cardinality_limit: 1000000
  enforce_metric_name: false
  ingestion_burst_size_mb: 128
  ingestion_rate_mb: 64
  ingestion_rate_strategy: local
  max_entries_limit_per_query: 5000
  reject_old_samples: true
  reject_old_samples_max_age: 168h
querier:
  engine:
    max_look_back_period: 30s
    timeout: 5m
  query_ingesters_within: 24h
  query_timeout: 2m
ruler:
  alertmanager_url: http://alertmanager-main.monitoring.svc.cluster.local:9093
  enable_alertmanager_v2: false
  enable_api: true
  enable_sharding: true
  evaluation_interval: 1m
  flush_period: 1m
  for_grace_period: 10m
  for_outage_tolerance: 1h
  notification_queue_capacity: 10000
  notification_timeout: 20s
  poll_interval: 5m
  resend_delay: 4h
  ring:
    kvstore:
      consul:
        consistent_reads: true
        host: sh-consul.aibee.cn:8500
        http_client_timeout: 20s
      prefix: rulers/
      store: consul
  search_pending_for: 5m
  storage:
    local:
      directory: /data/rules/
    type: local
runtime_config:
  file: /etc/loki/loki.yaml
  period: 20s
schema_config:
  configs:
  - from: "2021-01-17"
    index:
      period: 24h
      prefix: index_
    object_store: filesystem
    row_shards: 20
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
  register_instrumentation: true
storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /data/loki/chunks
  index_cache_validity: 50m
  index_queries_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_bytes: 20GB
      max_size_items: 1000000
      validity: 8h
table_manager:
  creation_grace_period: 30m
  poll_interval: 5m
  retention_deletes_enabled: true
  retention_period: 720
```
