### ISSUE TITLE
Missing logs in query when using boltdb-shipper on local filesystem

### ISSUE THREAD

**Issue by woodytec** [grafana/loki#3214]
I noticed that some queries did not give any output on some time ranges. After restarting Loki, the exact same query & time range give an output.

1. Loki version : version=2.0.0, branch=HEAD, revision=6978ee5d
2. Logs are shipped from vector to loki
3. Whatever the query is, before restarting loki some data are missing on some time ranges

Loki configuration:
```yaml
auth_enabled: false

server:
  http_listen_port: 30631

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1m 
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2020-11-13
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: C:\ProgramData\loki\boltdb-shipper-active
    cache_location: C:\ProgramData\loki\boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: C:\ProgramData\loki\data

compactor:
  working_directory: C:\ProgramData\loki\boltdb-shipper-compactor
  shared_store: filesystem

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
```
**Expected behavior**
The query should give an output, but it does not, as if they were no logs stored. After a restart, I finally got all the logs stored, without any gap, what means logs are effectively stored in Loki!

**Environment:**
 - Infrastructure: Loki is running in monolithic mode on Windows 10
 - Deployment: Deploying Loki through the executable

**Loki logs:**
Having a look at Loki's logs gave me some informartion, however I have no idea what it is due to nor if this is linked to the bug I'm reporting:
```
level=error ts=2021-01-20T11:09:59.6501308Z caller=table_manager.go:81 msg="error syncing local boltdb files with storage" err="rename C:\\ProgramData\\loki\\boltdb-shipper-cache/index_18647/R640-VM-HA01-1611138599617813500-1611138750.gz.temp C:\\ProgramData\\loki\\boltdb-shipper-cache/index_18647/R640-VM-HA01-1611138599617813500-1611138750.gz: The process cannot access the file because it is being used by another process."
````

I also get this type of error:

```
level=error ts=2021-01-22T08:29:59.7459788Z caller=table.go:235 msg="failed to remove file" path="C:\\ProgramData\\Woody technologies\\Woody in2it\\loki\\boltdb-shipper-compactor\\index_18649\\R640-VM-HA01-1611138599617813500-1611301500.gz" err="remove C:\\ProgramData\\Woody technologies\\Woody in2it\\loki\\boltdb-shipper-compactor\\index_18649\\R640-VM-HA01-1611138599617813500-1611301500.gz: The process cannot access the file because it is being used by another process."
```
I'm not able to find any process using these files, except from Loki which is running with admin privileges.

Any idea from where it could come?
