### ISSUE TITLE
Stream labels empty in response when sending logs via fluentd

### ISSUE THREAD

**Issue by davkal** [grafana/loki#322]
@lfdominguez commented on [Tue Feb 12 2019](https://github.com/grafana/grafana/issues/15393)

### What Grafana version are you using?
Master v6.0.0-pre3 (e38cfc1)

### What datasource are you using?
Loki

Hello I'm testing Loki with fluentd and code an addon to the fluentd loki ingestor to add support for dynamic labels (get the value from the message). I'm currently use Docker Swarm in my infra with fluentd docker log driver. All works great, but in the explorer UI are showed the labels on the menu of labels, but when i active to show labels on the logs list not show me nothing, are these labels hardcoded?

![image](https://user-images.githubusercontent.com/5604131/52636133-c155a400-2e99-11e9-9aa9-5d31c4045f02.png)

Here you can see how the label `test` exists and the query if for label `ueb`, but in the logs panel not show me any label.

---

@dprokop commented on [Tue Feb 12 2019](https://github.com/grafana/grafana/issues/15393#issuecomment-462794036)

@lfdominguez Thanks for your report.

Labels displayed in the explore's logs list are those that are unique to a given log entry in a logs stream. Can you please provide us with a response you get for a given query?

@davkal Can you also take a look at this, please?

---

@davkal commented on [Tue Feb 12 2019](https://github.com/grafana/grafana/issues/15393#issuecomment-462809169)

I'm suspecting loki as well. Would be great to get a screenshot of the query response from the browser dev tools. 
Another thing you can try is using [logcli](https://github.com/grafana/loki/blob/master/docs/logcli.md) to check if loki returns correct labels. It's my feeling that the labels will be empty.

It would be great to get verification via logcli. And if no labels are returned, then we should open an issue in the loki repo.

---

@lfdominguez commented on [Tue Feb 12 2019](https://github.com/grafana/grafana/issues/15393#issuecomment-462813539)

yeap, response from Loki without labels

![image](https://user-images.githubusercontent.com/5604131/52648185-156d8200-2eb4-11e9-927e-110942897be2.png)

**Comment by lfdominguez** [comment]
Not only fluentd... finnaly I can code a simple golang program that send snappy protobuff logs to Loki... and the labels not show.

**Comment by woodsaj** [comment]
@lfdominguez this looks like https://github.com/grafana/loki/issues/307   Are you using the latest version of Loki?

**Comment by lfdominguez** [comment]
let me exec `docker pull` again

**Comment by lfdominguez** [comment]
When Grafana try to call api (or fluentd, or my program):

![image](https://user-images.githubusercontent.com/5604131/52660449-b0bf2100-2ecd-11e9-9a42-329498736fbe.png)

executed with
```
docker run --rm --name=loki --network=test_log -v /home/luis/Work/Docker/loki/loki.yaml:/etc/loki/local-config.yaml -p 80:80 grafana/loki:master -config.file=/etc/loki/local-config.yaml
```

config file:

```
auth_enabled: false

server:
  http_listen_port: 80

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      store: inmemory
      replication_factor: 1
  chunk_idle_period: 15m

schema_config:
  configs:
  - from: 0
    store: boltdb
    object_store: filesystem
    schema: v9
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  enforce_metric_name: false
```
