### ISSUE TITLE
Promtail output stage does not change the log line for multiline blocks

### ISSUE THREAD

**Issue by rhart** [grafana/loki#3223]
**Describe the bug**
In a Promtail pipeline that first merges multiple lines, then parses using a regex, and then modifies the output, the resulting log line displayed ignores the output stage and always shows the original merged log line.

**To Reproduce**
With a pipeline of 

```
pipeline_stages:
    - multiline:
        firstline: '^\d{4}-\d{2}-\d{2}'
        max_wait_time: 3s
    - regex:
        expression: '^(?P<time>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2},\d{3})\s(?P<message>.*)$'
    - replace:
        expression: '\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}(,)\d{3}'
        replace: '.'
        source: time
    - timestamp:
        source: time
        format: '2006-01-02 15:04:05.000'
    - output:
        source: message
``` 

and log message of

```
2020-12-14 08:40:31,901 ERROR Error getting connection from data source
	at org.foo.debug(Unknown Source)
```

The resulting log line is

```
2020-12-14 08:40:31,901 ERROR Error getting connection from data source
	at org.foo.debug(Unknown Source)
```

**Expected behavior**
I would expect the resulting log line to not have the timestamp at the beginning i.e.

```
ERROR Error getting connection from data source
	at org.foo.debug(Unknown Source)
```

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: docker-compose
