### ISSUE TITLE
Promtail deploy in k8s docs are not exactly clear

### ISSUE THREAD

**Issue by withernet** [grafana/loki#3230]
**Describe the bug**
`promtail` documentation needs to be made more clear and concise on how to properly deploy `promtail` without `helm` charts.

**To Reproduce**
Apply the below:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: default
roleRef:
    kind: ClusterRole
    name: promtail
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail.yaml: |
    client:
      backoff_config:
        max_period: 5m
        max_retries: 10
        min_period: 500ms
      batchsize: 1048576
      batchwait: 1s
      external_labels: {}
      timeout: 10s
      url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /run/promtail/positions.yaml
    server:
      log_level: debug
      http_listen_port: 3101
    target_config:
      sync_period: 10s
    scrape_configs:
    - job_name: kubernetes-pods-name
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
    - job_name: kubernetes-pods-app
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: .+
        source_labels:
        - __meta_kubernetes_pod_label_name
      - source_labels:
        - __meta_kubernetes_pod_label_app
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
    - job_name: kubernetes-pods-direct-controllers
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: .+
        separator: ''
        source_labels:
        - __meta_kubernetes_pod_label_name
        - __meta_kubernetes_pod_label_app
      - action: drop
        regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
        source_labels:
        - __meta_kubernetes_pod_controller_name
      - source_labels:
        - __meta_kubernetes_pod_controller_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
    - job_name: kubernetes-pods-indirect-controller
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: .+
        separator: ''
        source_labels:
        - __meta_kubernetes_pod_label_name
        - __meta_kubernetes_pod_label_app
      - action: keep
        regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
        source_labels:
        - __meta_kubernetes_pod_controller_name
      - action: replace
        regex: '([0-9a-z-.]+)-[0-9a-f]{8,10}'
        source_labels:
        - __meta_kubernetes_pod_controller_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
    - job_name: kubernetes-pods-static
      pipeline_stages:
        - docker: {}
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: drop
        regex: ''
        source_labels:
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_label_component
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
        - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
        - __meta_kubernetes_pod_container_name
        target_label: __path__
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  labels:
    k8s-app: promtail
spec:
  selector:
    matchLabels:
      name: promtail
  template:
    metadata:
      labels:
        name: promtail
    spec:
      serviceAccountName: promtail
      volumes:
      - name: promtail-config
        configMap:
          name: promtail-config
      containers:
      - name: promtail
        image: grafana/promtail:2.1.0
        args:
        - -config.file=/etc/promtail/promtail.yaml
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail
        - name: docker
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: pods
          mountPath: /var/log/pods
          readOnly: true
        - name: run
          mountPath: /run/promtail
      volumes:
        - name: run
          hostPath:
            path: /run/promtail
        - name: docker
          hostPath:
            path: /var/lib/docker/containers
        - name: pods
          hostPath:
            path: /var/log/pods
        - name: promtail-config
          configMap:
            name: promtail-config
```

**Expected behavior**
I'm expecting log data to be sent to loki, but non is.

**Environment:**
 - Kubernetes
 - Deployment tool: `kustomize`

**Screenshots, Promtail config, or terminal output**
`promtail` logs:

```
level=info ts=2021-01-25T21:20:33.324292278Z caller=kubernetes.go:263 component=discovery discovery=kubernetes msg="Using pod service account via in-cluster config"
level=debug ts=2021-01-25T21:20:33.325592335Z caller=manager.go:195 component=discovery msg="Starting provider" provider=kubernetes/0 subs="[kubernetes-pods-name kubernetes-pods-app kubernetes-pods-direct-controllers kubernetes-pods-indirect-controller kubernetes-pods-static]"
level=info ts=2021-01-25T21:20:33.325867337Z caller=server.go:225 http=[::]:3101 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-01-25T21:20:33.326135265Z caller=main.go:110 msg="Starting Promtail" version="(version=2.1.0, branch=HEAD, revision=1b79df375)"
```

There are no labels in grafana except for `__name__`; I know this is not correct as I deployed the stack using `helm` and there are labels. So, it's almost as if `promtail` is simply not sending logs to `loki` (but loki is making chunks):

```
2021-01-25 21:13:59.119358 I | proto: duplicate proto type registered: ingester.Series
level=info ts=2021-01-25T21:13:59.122316388Z caller=main.go:130 msg="Starting Loki" version="(version=2.1.0, branch=HEAD, revision=1b79df375)"
level=info ts=2021-01-25T21:13:59.122547216Z caller=server.go:225 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-01-25T21:13:59.122684124Z caller=modules.go:431 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2021-01-25T21:13:59.123418805Z caller=shipper_index_client.go:99 msg="starting boltdb shipper in 0 mode"
level=info ts=2021-01-25T21:13:59.123458553Z caller=table_manager.go:171 msg="uploading tables"
level=info ts=2021-01-25T21:13:59.125444724Z caller=worker.go:65 msg="no address specified, not starting worker"
level=info ts=2021-01-25T21:13:59.126159081Z caller=modules.go:456 msg="RulerStorage is nil.  Not starting the ruler."
level=info ts=2021-01-25T21:13:59.127522517Z caller=module_service.go:58 msg=initialising module=memberlist-kv
level=info ts=2021-01-25T21:13:59.127651856Z caller=module_service.go:58 msg=initialising module=server
level=info ts=2021-01-25T21:13:59.128288561Z caller=module_service.go:58 msg=initialising module=store
level=info ts=2021-01-25T21:13:59.130393127Z caller=module_service.go:58 msg=initialising module=ingester
level=info ts=2021-01-25T21:13:59.130466022Z caller=lifecycler.go:518 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2021-01-25T21:13:59.130591861Z caller=lifecycler.go:547 msg="instance not found in ring, adding with no tokens" ring=ingester
level=info ts=2021-01-25T21:13:59.130713789Z caller=lifecycler.go:394 msg="auto-joining cluster after timeout" ring=ingester
level=info ts=2021-01-25T21:13:59.130882212Z caller=module_service.go:58 msg=initialising module=compactor
level=info ts=2021-01-25T21:13:59.130945644Z caller=module_service.go:58 msg=initialising module=table-manager
level=info ts=2021-01-25T21:13:59.131754054Z caller=table_manager.go:324 msg="synching tables" expected_tables=94
level=info ts=2021-01-25T21:13:59.131835903Z caller=table_manager.go:476 msg="creating table" table=index_18611
level=info ts=2021-01-25T21:13:59.131871013Z caller=table_manager.go:476 msg="creating table" table=index_18622
level=info ts=2021-01-25T21:13:59.13188144Z caller=table_manager.go:476 msg="creating table" table=index_18638
level=info ts=2021-01-25T21:13:59.131889296Z caller=table_manager.go:476 msg="creating table" table=index_18641
```

The loki setup:

```
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
  - protocol: TCP
    port: 3100
    targetPort: 3100
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki.yaml: |
    auth_enabled: false
    ingester:
      chunk_idle_period: 3m
      chunk_block_size: 262144
      chunk_retain_period: 1m
      max_transfer_retries: 0
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1

        ## Different ring configs can be used. E.g. Consul
        # ring:
        #   store: consul
        #   replication_factor: 1
        #   consul:
        #     host: "consul:8500"
        #     prefix: ""
        #     http_client_timeout: "20s"
        #     consistent_reads: true
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    schema_config:
      configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    server:
      http_listen_port: 3100
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        cache_location: /loki/boltdb-shipper-cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
    compactor:
      working_directory: /loki/boltdb-shipper-compactor
      shared_store: filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.1.0
        args:
          - "-config.file=/etc/loki/loki.yaml"
        ports:
        - name: loki
          containerPort: 3100
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
```

There is something missing here that is not allowing for promtail logs to be sent to loki, what is it?

I also have some other complaints regarding this documentaiton. For example if you start from scratch you'll incur other errors that result from missing `__path__`; basically the docs for loki are inconsistent from what is being deployed in the helm charts.
