### ISSUE TITLE
Affinity generation not working

### ISSUE THREAD

**Issue by MarcTerrasson** [grafana/loki#3238]
Hi,

The generation of affinity does not seems to work.
I tried to uncomment the given example : 
```
affinity:
 podAntiAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
   - labelSelector:
       matchExpressions:
       - key: app
         operator: In
         values:
         - loki
     topologyKey: "kubernetes.io/hostname"
```
And the affinity was not generated : 

`      affinity:
        {}
`

Here is my version
```
$ helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```
