### ISSUE TITLE
Guarantee unique timestamps, like fudge but on success

### ISSUE THREAD

**Issue by swantzter** [grafana/loki#3250]
**Is your feature request related to a problem? Please describe.**

I have a lot of old logs I'm trying to ingest which have timestamp with second-precision, multiple lines with the same timestamp can end up having the same labels (or even message) but they are in the right order.
These errors result in none of my logs being ingested

**Describe the solution you'd like**

"fudge on success", in other words keep an offset `p` per label in [`Process` of timestamp.go](https://github.com/grafana/loki/blob/2c8cf9e86f84cb3e8d78fd0c24db99aec139e63f/pkg/logentry/stages/timestamp.go#L150)
if `parsedTs == lastTimestamp` increment `p` by one and then `parsedTs.(time.Time).Add(p * time.Nanosecond)`. If `parsedTs != lastTimestamp` reset `p` to `0`

**Describe alternatives you've considered**

I have tried getting a value from a log-line counter in the metrics stage with a stage like
```yaml
- template:
  source: timestamp
  template: '{{ .date }}T{{ .time }}.{{ regexReplaceAll  ".*(\\d{6})" (print "000000000" .log_lines_total) "$1" }}'
```
but you can't access metric values as labels it seems

I've tried making the timestamps unique at least by adding the length or hash of the message as a label - but that doesn't work because messages _can_ be identical
