### ISSUE TITLE
(promtail) failed to parse log

### ISSUE THREAD

**Issue by 17billion** [grafana/loki#3260]
I extract traceid and spanid from log.

- Application log sample
: 2021-01-29 04:16:27.721 INFO [demo-board-oauth,f2468bbbba2944d9,f2468bbbba2944d9] 26525 --- [http-nio-8080-exec-5] c.g.d.controllers.PingController

- https://regex101.com/ site regex check ok
<img width="1360" alt="screenshot" src="https://user-images.githubusercontent.com/28832461/106239864-a925ed80-6246-11eb-94a0-7d792b0d3586.png">

But the parsing fails.

- My config file
```
  - job_name: application_log
    #    entry_parser: raw
    pipeline_stages:
    - match:
        selector: '{job="application_log", traceid!=""}'
        stages:
        - regex:
           expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) (?P<level>[A-Z]+) .*,(?P<traceid>[a-zA-Z0-9]+),(?P<spanid>[a-zA-Z0-9]+)] .*'
        - labels:
           traceid:
           spanid:
        - timestamp:
           source: timestamp
           format: "2006-01-02 15:04:05.000"
```

Can you tell me where is wrong?

**Comment by dannykopping** [comment]
Try adding `-log.level=debug` to your `promtail` command - that may give you more insight into what the problem is.

**Comment by xkilian** [comment]
Double escape \d: \\d

**Comment by 17billion** [comment]
@dannykopping 
There is no additional confirmation on the log.
```
level=debug ts=2021-02-01T00:15:35.983189314Z caller=pipeline.go:107 component=file_pipeline component=pipeline msg="processing pipeline" stage=0 name=match labels="{filename=\"/home/ec2-user/logs/application-error.log\", job=\"application_log\", service=\"oauth\"}" time=2021-02-01T00:15:35.983162357Z entry="2021-02-01 00:15:35.929  INFO [demo-board-oauth,e9752da71c764cbb,e9752da71c764cbb] 26525 --- [http-nio-8080-exec-6] c.g.d.controllers.PingController"

level=debug ts=2021-02-01T00:15:35.983221246Z caller=pipeline.go:113 component=file_pipeline component=pipeline msg="finished processing log line" labels="{filename=\"/home/ec2-user/logs/application-error.log\", job=\"application_log\", service=\"oauth\"}" time=2021-02-01T00:15:35.983162357Z entry="2021-02-01 00:15:35.929  INFO [demo-board-oauth,e9752da71c764cbb,e9752da71c764cbb] 26525 --- [http-nio-8080-exec-6] c.g.d.controllers.PingController" duration_s=2.6606e-05
```

@xkilian 
Thank you. However, it doesn't seem to have been parsed yet except for timestamps.

**Comment by dannykopping** [comment]
@17billion is this your full promtail config?
If not, please post the full one. I think I've found your issue but want to make sure

**Comment by 17billion** [comment]
@dannykopping 
Can you tell me the problem?
Below is the contents of my configuration file.
```
# Promtail Server Config
server:
  http_listen_port: 9080
  grpc_listen_port: 0

# Positions
positions:
  filename: /tmp/positions.yaml

# Loki Server URL
clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: access_log
    #    entry_parser: raw
    pipeline_stages:
    - match:
        selector: '{job="access_logs"}'
        stages:
        - regex:
           expression: '(?P<clientAddr>\w{1,3}.\w{1,3}.\w{1,3}.\w{1,3}) - - .(?P<timestamp>\d{2}.*\d{4}). "(?P<request>.*)" (?P<status>\d+) .*'
        - labels:
           clientAddr:
           request:
           status:
           #timestamp:
        - timestamp:
           source: timestamp
           format: "02/Jan/2006:15:04:05 -0700"
    static_configs:
    - targets:
        - localhost
      labels:
        service: oauth
        job: access_logs
        __path__: /home/ec2-user/logs/logs/*.log
  - job_name: application_log
    #    entry_parser: raw
    pipeline_stages:
    - match:
        selector: '{job="application_log", traceid!=""}'
        stages:
        - regex:
           expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}\.\d{2}.\d{2}.\d{3}) .*(?P<level>(INFO|DEBUG|ERROR)) .*,(?P<traceid>[a-zA-Z0-9]+),(?P<spanid>[a-zA-Z0-9]+)] .*'
        - labels:
           traceid:
           spanid:
           #controller:
           #timestamp:
        - timestamp:
           source: timestamp
           format: "2006-01-02 15:04:05.000"
    static_configs:
    - targets:
        - localhost
      labels:
        service: oauth
        job: application_log
        __path__: /home/ec2-user/logs/*.log
```
