### ISSUE TITLE
Unnecesary metrics

### ISSUE THREAD

**Issue by pando85** [grafana/loki#3262]
**Describe the bug**
`/metrics` entrypoint is returning metrics not related with Loki as etcd or Prometheus metrics. 

**To Reproduce**
1. Started Loki (2.1.0)
2. `curl {{ loki }}:3100/metrics`

**Expected behavior**
I expected just Loki related metrics not things like
```
# HELP etcd_server_version Which version is running. 1 for 'server_version' label with current version.
# TYPE etcd_server_version gauge
etcd_server_version{server_version="3.4.9"} 1
```
This affects for example our etcd dashboard which uses `label_values(etcd_server_has_leader, job)` to get the job name for filtering.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: helm

Thanks :)

**Comment by strangeman** [comment]
We also experience this issue. It leads to false alerts and noisy monitoring.

**Comment by strangeman** [comment]
Workaround for dropping unnecessary metrics on prometheus side. Add `metric_relabel_configs` to the target configuration in `prometheus.yaml`
```
  - job_name: 'loki-server'
    scheme: http
    scrape_interval: "15s"
    metrics_path: /metrics
    file_sd_configs:
        - files:
            - '/etc/prometheus/hosts/loki-server*.yaml'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: etcd(.+)
        action: drop
```
