### ISSUE TITLE
Promtail: timestamp action_on_failure causes 'entry out of order'

### ISSUE THREAD

**Issue by afletch** [grafana/loki#3266]
**Describe the bug**
As per the documentation:
When logs are being scraped by Promtail and timestamps parsed, if this involves parsing at only seconds precision, and promtail happens upon an unparsable timestamp, it will by default choose 'fudge', appending 1ns to the most recent timestamp.

If the next successfully parsed timestamp is the same as the previous successfully-parsed timestamp (highly likely when you're parsing at seconds-precision), this will result in this next log line being dropped with 'entry out of order' due to the 1ns added to the unparsable timestamp by the 'fudge' process. 

Changing to 'skip' does not help in this scenario as this is even more likely to be out of order.

**To Reproduce**
1. scrape log file using the config given below
2. send to loki
3. note out of order

**Expected behavior**
Use the last known timestamp for the unparsable log line, since it's permissable to have mutliple log lines with the same timestamp.
OR
Provide a third option to keep the same timestamp as the last known timestamp.

**Environment:**
Promtail 1.6.1
Loki 2.1.0

**Screenshots, Promtail config, or terminal output**
pipeline config:
```
  - regex:
      expression: ^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})
  - timestamp:
      format: '2006-01-02 15:04:05'
      location: Europe/London
      source: time
```
example log:
```
2021-01-29 14:21:37 [NOTICE] [12345] [127.0.0.1:3691:HTTP2:443] Request: /1
some-unexpected-line
2021-01-29 14:21:37 [NOTICE] [54321] [127.0.0.1:3691:HTTP2:443] Request: /2
```
