### ISSUE TITLE
Negative numbers not extracted by promtail to a Gauge metric

### ISSUE THREAD

**Issue by xkilian** [grafana/loki#3281]
**Describe the bug**
Negative numbers cannot be extracted as Gauge metrics from logs in promtail.

**To Reproduce**
promtail config:
```
     #<13>Jan 28 14:25:52 vehicule=1 longitude=-10.1234 latitude=15.1234
      - match:
          selector: '{host="whatever"}'
          stages:
            - regex:
                expression: 'vehicule=(?P<vehicule>\d+) longitude=(?P<longitude>[-]?\d+\.\d+) latitude=(?P<latitude>\d+\.\d+)'
            - labels:
                vehicule:
            - metrics:
                longitude:
                  type: Gauge
                  description: "longitude GPS vehicule"
                  config:
                    match_all: true
                    action: set
                latitude:
                  type: Gauge
                  description: "latitude GPS vehicule"
                  config:
                    match_all: true
                    action: set
```

**Expected behavior**
Numbers like -10.1234 should be extracted from log lines.

**Environment:**
 - linux Ubuntu 64bit
 - loki 2.1

**Screenshots, Promtail config, or terminal output**
logfmt in logql has not problem with negative numbers, but promtail cannot cast the extracted number as a signed float to a Gauge after regex extraction.
