### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by aabc1123** [grafana/loki#3282]
I deploy Loki service  by docker on a physical server 192.168.173.35, then deploy a promtail service on a physical server 192.168.173.86 also by docker. However, promtail reports some errors:

```text
level=warn ts=2021-02-02T11:14:39.10164997Z caller=client.go:322 component=client host=192.168.173.35:3100 msg="error sending batch, will retry" status=-1 error="Post \"http://192.168.173.35:3100/loki/api/v1/push\": context deadline exceeded"
level=warn ts=2021-02-02T11:15:41.957159708Z caller=client.go:322 component=client host=192.168.173.35:3100 msg="error sending batch, will retry" status=-1 error="Post \"http://192.168.173.35:3100/loki/api/v1/push\": context deadline exceeded"
level=warn ts=2021-02-02T11:16:48.120478063Z caller=client.go:322 component=client host=192.168.173.35:3100 msg="error sending batch, will retry" status=-1 error="Post \"http://192.168.173.35:3100/loki/api/v1/push\": context deadline exceeded"
level=warn ts=2021-02-02T11:17:57.590929065Z caller=client.go:322 component=client host=192.168.173.35:3100 msg="error sending batch, will retry" status=-1 error="Post \"http://192.168.173.35:3100/loki/api/v1/push\": context deadline exceeded"
level=warn ts=2021-02-02T11:19:19.444000857Z caller=client.go:322 component=client host=192.168.173.35:3100 msg="error sending batch, will retry" status=-1 error="Post \"http://192.168.173.35:3100/loki/api/v1/push\": context deadline exceeded"
```
here is my promtail configuration:
```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.173.35:3100/loki/api/v1/push
    tenant_id: test1

scrape_configs:
  - job_name: hshb-test
    static_configs:
      - targets:
          - localhost
        labels:
          job: hshb-test
          host: 192.168.173.86
          __path__: /var/log/test/*log
```
who can tell me which step is wrong, thank you!
