### ISSUE TITLE
errors: open /data/loki/index/loki_index_18659: is a directory

### ISSUE THREAD

**Issue by iamparamvs** [grafana/loki#3330]
**Describe the bug**
I am facing the below error:

```
level=info ts=2021-02-12T08:23:19.444667126Z caller=table_manager.go:485 msg="creating table" table=loki_index_18663
level=info ts=2021-02-12T08:23:19.444711059Z caller=table_manager.go:485 msg="creating table" table=loki_index_18665
level=info ts=2021-02-12T08:23:19.444752127Z caller=table_manager.go:485 msg="creating table" table=loki_index_18667
level=info ts=2021-02-12T08:23:19.444776721Z caller=table_manager.go:485 msg="creating table" table=loki_index_18668
level=error ts=2021-02-12T08:23:19.444852157Z caller=table_manager.go:227 msg="error syncing tables" err="10 errors: open /data/loki/index/loki_index_18659: is a directory; open /data/loki/index/loki_index_18660: is a directory; open /data/loki/index/loki_index_18664: is a directory; open /data/loki/index/loki_index_18666: is a directory; open /data/loki/index/loki_index_18661: is a directory; open /data/loki/index/loki_index_18662: is a directory; open /data/loki/index/loki_index_18663: is a directory; open /data/loki/index/loki_index_18665: is a directory; open /data/loki/index/loki_index_18667: is a directory; open /data/loki/index/loki_index_18668: is a directory"
```

**To Reproduce**
1. Running Loki as a StatefulSet in Openshift cluster on AWS environment
2. Using EBS mounted at "/data"

Configmap
```
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 0s
    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      max_transfer_retries: 0
    limits_config:
      max_entries_limit_per_query: 10000
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    schema_config:
      configs:
      - from: "2021-02-01"
        index:
          period: 24h
          prefix: loki_index_
        object_store: filesystem
        schema: v11
        store: boltdb
    server:
      http_listen_port: 3100
    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
```

**Environment:**
 - Infrastructure: Openshit 4.5
 - Deployment tool: manifests
