### ISSUE TITLE
Helm chart doesn’t scrape logs from Gitlab Runner pod (Kubernetes Exectutor) in Kubernetes

### ISSUE THREAD

**Issue by frapeshka** [grafana/loki#3343]
**Describe the bug**
Grafana Loki doesn't show logs from type of Kubernetes runner called Kubernetes exectutor: https://docs.gitlab.com/runner/executors/kubernetes.html.
Basically, in my cluster I'm able to see all pods logs except the CI-runner although CI-runner pod has labels.

**To Reproduce**
1. Install latest version of Loki Stack by Helm chart either way: https://grafana.com/docs/loki/latest/installation/helm/
2. Install latest version of Gitlab Runner inside Kubernetes (called Kubernetes Exectutor): https://docs.gitlab.com/runner/install/kubernetes.html#installing-gitlab-runner-using-the-helm-chart
3. Run CI pipeline in Gitlab
4. Confirm that logs are writing in stdout by kubectl:
```
# e.g.
kubectl logs pod/runner-h-iwkwk-project-22859791-concurrent-0h4l4s -n gitlab-apps -c svc-0 -f
# sample of logs below
ORACLE EDITION: ENTERPRISE

LSNRCTL for Linux: Version 19.0.0.0.0 - Production on 16-FEB-2021 11:22:02

Copyright (c) 1991, 2019, Oracle.  All rights reserved.

Starting /opt/oracle/product/19c/dbhome_1/bin/tnslsnr: please wait...
...
```
5. Confirm that pod has labels:
```
kubectl get pod/runner-h-iwkwk-project-22859791-concurrent-0h4l4s -n gitlab-apps -o yaml | head -30
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2021-02-16T11:23:59Z"
  generateName: runner-h-iwkwk-project-22859791-concurrent-0
  labels:
    app: broccoli
    pod: runner-h-iwkwk-project-22859791-concurrent-0
```
6. Go to Grafana -> Explore -> Loki, select the `broccoli` pod's label -> there's no such label and logs

**Expected behavior**
Go to Grafana -> Explore -> Loki, select `broccoli` pod's label -> get logs.

**Environment:**
 - Infrastructure: EKS 1.18
 - Deployment tool: Helm
