### ISSUE TITLE
Loki query returns  "object not found in storage" with "query_range" and get values return with "query"

### ISSUE THREAD

**Issue by StefanSa** [grafana/loki#3395]
**Describe the bug**
Loki query returns  "object not found in storage" with "query_range" and get values return with "query"

**To Reproduce**
1. Installed and started Loki 2.1.0
2. Query with Grafana Explorer `query_range` and `query`

We see this behavior mainly with data that is provided externally promtail,
with a promtail installed in kubernetes that only analyzes log files only rarely.

Data from the external promtail always cause the error message `object not found in storage` with `query_range`.
The same data from the external promtail can be successfully queried with `query`

Data from the internal k8 promtail that only sends local log files, returns data with `query_range` but nothing with `query`.

We don't see this problem on the same Kubernetes cluster with a single loki instance.
It must have something to do with the deployment type -> microservice.

**Expected behavior**
Data should be returned with "query_range" without an error message.

**Environment:**
 - Infrastructure: Kubernetes  - Rancher
 - Deployment tool: helm
 - Deployment: loki-distributed ( 3 ingester, 3 querier )

**Comment by slim-bean** [comment]
The likely difference between query_range and query is how far back Loki is going to look for data, you would have to post some exact queries with timeframes to prove that as a theory but I suspect this is why you see a difference.

As for "object not found" this sounds like something out side the Loki process is deleting/removing objects from your object store? perhaps a TTL or similar process?

> We don't see this problem on the same Kubernetes cluster with a single loki instance.
> It must have something to do with the deployment type -> microservice.

Another option that could possibly lead to object not found is a misconfiguration of your microservices setup, not having a shared ring for example, if you provide your config we could look for these types of problems.

**Comment by StefanSa** [comment]
Hi Ed,
thanks for your answer. i don't think there are workload problems in the K8 cluster. An ECK Elastic Stack with 15 nodes has been running in the cluster for a long time without any problems.
About " misconfiguration of your microservices setup" 
Can you tell me the best way to give you this data, or how do i get the information that you are missing.
Thanks for your time and -> loki.

**Comment by StefanSa** [comment]
@slim-bean Ed,
this is the current configuration, deviating from the standard installation, three ingesters and three inquirers with pvc storage have been added.
It would be good if we could get this going, because in future loki should replace the ECK stack.

```
auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      store: memberlist

memberlist:
  join_members:
    - loki-distributed-memberlist

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  chunk_idle_period: 30m
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_retain_period: 1m
  max_transfer_retries: 0

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m

schema_config:
  configs:
    - from: 2020-09-07
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  boltdb_shipper:
    shared_store: filesystem
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    cache_ttl: 168h
  filesystem:
    directory: /var/loki/chunks

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

query_range:
  align_queries_with_step: true
  max_retries: 5
  split_queries_by_interval: 15m
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 1024
        validity: 24h

frontend_worker:
  frontend_address: loki-distributed-query-frontend:9095

frontend:
  log_queries_longer_than: 5s
  compress_responses: true

compactor:
  shared_store: filesystem

ruler:
  storage:
    type: local
    local:
      directory: /etc/loki/rules
  ring:
    kvstore:
      store: memberlist
  rule_path: /tmp/loki/scratch
  alertmanager_url: https://alertmanager.xx
  external_url: https://alertmanager.xx

```
