### ISSUE TITLE
Loosing 30-45 min data on Loki restart when using boltdb-shipper

### ISSUE THREAD

**Issue by nawabb** [grafana/loki#3397]
**Describe the bug**
We recently switched to use of BoltDB shipper instead of Cassandra with Loki 2.0. Everything is working fine, but whenever the Loki instance is restarted, queries show a gap in data for 30-45 minutes.

In screenshot below; Loki was restarted at 13:05 and restart took couple of minutes. Logs after 13:07 are visible; but logs between 12:29 and 13:05 are logs.
![image](https://user-images.githubusercontent.com/63880997/109396228-97e00780-78fe-11eb-9b02-7821bbf05a63.png)

**To Reproduce**
* Using Loki 2.1.0 using Nomad. Running Minio for shared data store. Configuration used below.
* Active index is written to a directory /lokidisk/ which is persistent (using [volume_mount](https://www.nomadproject.io/docs/job-specification/volume_mount) with Nomad so the directory is on the underlying host)

```
auth_enabled: false
server:
  http_listen_port: 3100
  log_level: debug
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 2m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2021-02-22
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_bexp
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /lokidisk/loki/index
    cache_location: /tmp/loki/index_cache
    resync_interval: 60s
    shared_store: s3
    query_ready_num_days: 7
    cache_ttl: 168h

  aws:
    s3: http://minio.domain.address:6151
    access_key_id: KEY
    secret_access_key: SECRET
    s3forcepathstyle: true
    bucketnames: lokix

compactor:
  working_directory: /lokidisk/loki/boltdb-shipper-compactor
  shared_store: s3

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 24h

chunk_store_config:
  max_look_back_period: 1560h

table_manager:
  retention_deletes_enabled: true
  retention_period: 1560h
```

**Expected behavior**

**Environment:**
 - Infrastructure: Nomad-based. Running two clusters of Loki. Production setup is using Cassandra for index. Second experimental setup is ingesting logs from (1) some experimental process and (2) production Loki instance. The issue is observed only for the second experimental setup. In this setup, only a single Loki instance is running (all-in-one mode)

**Comment by nawabb** [comment]
I tested with Loki 2.2.0 as released today. Unfortunately the same behavior / data loss happens.

**Comment by nawabb** [comment]
I have conducted additional experiments with different parameters. The bug persists.

Amount of data lost, when Loki instance restarts, varies based on job label.
* For a job producing only 100 lines of logs I see 30-45 minutes of missing data when Loki crashes and restarts
* For another job producing approx 50,000 lines of logs per minute; I see only 5 minutes of missing data
So it seems like some bug where-in the files are not properly synced in case Loki crashes (force restarts)

**Comment by klausenbusk** [comment]
Did you try enabling the WAL? https://grafana.com/docs/loki/latest/operations/storage/wal/

**Comment by nawabb** [comment]
@klausenbusk thanks for the suggestion. I enabled WAL and now the data loss issue seems to have disappeared. I will keep monitoring. Without WAL, the issue was persistent with Loki 2.2.1 as well.

Below is the config I used if someone is interested. All parts are the same as in the original issue description; except the **ingestor** which is below. Note, I had to put max_transfer_retries as 0, and there is no recover-from-wal option (as mentioned on https://grafana.com/docs/loki/latest/operations/storage/wal/). I think some cleanup of documentation may be in order. Note, /lokidisk/ in the below is a volume mounted partition and is persistent across reboots.

```
ingester:
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /lokidisk/loki/wal
    replay_memory_ceiling: 4GB
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      heartbeat_timeout: 10s
      replication_factor: 1
    final_sleep: 0s
    min_ready_duration: 20s
  chunk_idle_period: 2m
  chunk_retain_period: 30s
```
