### ISSUE TITLE
Loki and alerts

### ISSUE THREAD

**Issue by soum1234** [grafana/loki#340]
Suppose I have to alert when there is an error log.let me know how to so it

**Comment by tomwilkie** [comment]
Hi @soum1234! We don't have a good answer for this yet, but it is something we plan on supporting.  The current idea is we're going to first add a Prometheus-style query language for Loki, then use Prometheus-style rules and alerts on top of this.

**Comment by soum1234** [comment]
Thanks a lot for the response

**Comment by soum1234** [comment]
could we expect it in the next release?also could you let me know if there are some documents on querying in boltdb pls send the link
thanks

**Comment by BushnevYuri** [comment]
Prometheus style alerting for logs sounds truly amazing. Hopefully, this feature will be added soon.

**Comment by mcamou** [comment]
Has there been any work done on this? Any idea on when we can expect to be able to generate alerts in Grafana from Loki?

**Comment by Kuqd** [comment]
I will start investigating this since LogQL has moved forward.

**Comment by JnMik** [comment]
yeah that would be nice to be able to send alerts if a specific query return results.
I would build queries looking up for "error" keywords and stuff like that.

**Comment by JnMik** [comment]
By the way, have you made any progress @cyriltovena  ?

**Comment by cyriltovena** [comment]
Not yet merged, but you can use promtail to create those alerts in the meantime. 

You can create metrics in promtail based on log retrieved from files, then scrape those promtail using a prometheus and create an alert.

(https://github.com/grafana/loki/blob/master/docs/logentry/processing-log-lines.md)

**Comment by mcamou** [comment]
How about if we're not using promtail? We're streaming logs directly into the Loki endpoint.

**Comment by cyriltovena** [comment]
We have plan to support Prometheus alert style.

**Comment by kalingals** [comment]
Hi @cyriltovena cyriltovena can you please tell me when do you plan to release Loki alerting feature?

**Comment by tomwilkie** [comment]
Loki already accepts PromQL like expressions (LogQL) on a Prometheus-compatible API, so the rough plan is to use the Cortex Ruler to evaluate Prometheus-style alert rules against logs.  The Cortex Rules already exists, is horizontally scalable & highly available, so the integration should be relatively straight forward we hope.

This plan is in its super early stages mind you; input is more than welcome!

**Comment by bukowa** [comment]
> 
> 
> Not yet merged, but you can use promtail to create those alerts in the meantime.
> 
> You can create metrics in promtail based on log retrieved from files, then scrape those promtail using a prometheus and create an alert.
> 
> (https://github.com/grafana/loki/blob/master/docs/logentry/processing-log-lines.md)

Link is dead :(

**Comment by migueleliasweb** [comment]
https://github.com/grafana/loki/tree/master/docs/clients/promtail/stages

You are looking for the stages section. With that, you can define metrics based on matches against the log lines. Then you use Prometheus & Alertmanager  as you would normally to create the alert ;)

I reckon this issue can be closed.

**Comment by bukowa** [comment]
@migueleliasweb thanks a lot, ill do that but i guess the issue should not be closed to provide built-in solution to this.

**Comment by migueleliasweb** [comment]
Hey @bukowa, I'm glad I helped :wink:  . 

Regarding the built-in solution for alerting, I would be surprised if this will ever be a feature. The integration with Prometheus/Alertmanager is already there and in every release it gets improved. Replicating the funcionality of creating and managing alerts would be highly deprioritized or even unwanted in this context. But that's just my view.

**Comment by bukowa** [comment]
@migueleliasweb My use case is loki for docker logs:
````yaml

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - loki
      - grafana

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"

  web:
    image: nginx:alpine
    ports:
      - 85:80
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "container_name={{.Name}}.{{.ID}}"
        loki-batch-size: "5000"
    depends_on:
      - grafana
      - loki
      - promtail
    labels:
      test: 1
````
![firefox_W1jDvQ1Feu](https://user-images.githubusercontent.com/38087302/71716272-6e1f7380-2e14-11ea-927f-6ec992723d9c.png)

Everything works great (great project thank you!) but now i cannot setup alerts for these logs (i really love simple solutions). So here goes my idea that this could and should be supported.
