### ISSUE TITLE
support collecting logs from files inside containers via annotations

### ISSUE THREAD

**Issue by woodsaj** [grafana/loki#342]
It is not uncommon for applications to write to log files inside a container, even though it is not recommended. It would be useful if promtail could be told about these files and collect them as well.

By convention, Prometheus uses annotations to allow users to customize how metrics are scraped and  I think we can do the same thing to allow users to list additional paths to be collected.  To support this use-case we should define a set of common annotations and the relabel_configs needed to use them.

I think the easiest approach is to only support collecting logs from files in volumes.  like paths to container logs, the volumes have predictable paths on the nodes.
`/var/lib/kubelet/pods/<podUID>/volumes/`

**Comment by VasylSamoilov** [comment]
Kubernetes logging architecture does this other way around - please see https://kubernetes.io/docs/concepts/cluster-administration/logging/
In the case you described it's best to implement sidecar container for you appliaction which will read custom logs and push them to stdout.

**Comment by chinglinwen** [comment]
Hi, I've had the same requirements to collect many log files from inside the container.

> I'm come from this issue https://github.com/grafana/loki/issues/633
> Thanks Serrvosky, helps me solve that issue.
> 
> I think this is the right place to continue the conversation about collect logs from inside conttainers.
> 

```
/logs $ ls
app
appCreditReport_EveryoneBelieves_error_2019-07-25.log
appCreditReport_WandReport_error_2019-07-25.log
nginx
php
/logs $ ls app
access_2019-07-25.log             error_2019-07-25.log
base_2019-07-25.log               livingBody_access_2019-07-25.log
/logs $ ls nginx/
error.log               openapi.haodai.com.log  www.haodais.com.log
openapi.haodai.com.err  www.haodais.com.err
/logs $ ls php/
php-fpm-error.log  php-fpm-slow.log
/logs $
```

https://github.com/grafana/loki/blob/master/docs/promtail-setup.md

This link says I can set an label, but I can't figure out how to locate the container mergeDir

I suppose I should add the scrap config below  `__path__` as follow:

```
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        target_label: __path__
        separator: /
        source_labes:
        - __meta_kubernetes_pod_label_logFileName
        replacement: /your_log_file_dir/$1.log
```

The `your_log_file_dir` should contains the path: 

"MergedDir": "/data/docker/overlay2/1da5caaa262b6e7a82725fb54bc896917c9871098c7b95e184af5ef11a928d3c/merged"

can you help?  @woodsaj  @VasylSamoilov
