### ISSUE TITLE
Add support for Azure Blob Storage

### ISSUE THREAD

**Issue by huydinhle** [grafana/loki#343]
**Is your feature request related to a problem? Please describe.**
Add support for Azure Blob Storage.

**Describe the solution you'd like**
Since we have support for GCS and S3, can we add Azure blob storage as well.

**Comment by huydinhle** [comment]
would love to contribute this feature to Loki as well because we want to adopt Loki in our production system. But all of our stuff lives in Azure land :cry:

**Comment by huydinhle** [comment]
Based on the code, it looks like this is coming from Cortex library. I guess I should open an issue over there instead?

**Comment by yubozhao** [comment]
@huydinhle Yes, I think open an issue and/or contributing to the cortex library is the best way to approach this.

**Comment by tomwilkie** [comment]
Closing in favour of https://github.com/cortexproject/cortex/issues/1234

Let me know if you need any pointers.

**Comment by EraYaN** [comment]
Since https://github.com/cortexproject/cortex/pull/1913 was merged the documentation might need an update (and example).

**Comment by abelal83** [comment]
> 
> 
> Since [cortexproject/cortex#1913](https://github.com/cortexproject/cortex/pull/1913) was merged the documentation might need an update (and example).

documentation not updated yet, would be really helpful.

**Comment by abelal83** [comment]
Any updates on this please? loki --help seems to suggest there is some support

```
 Azure:
   -azure.account-key string:
      The Microsoft Azure account key to use.
   -azure.account-name string:
      The Microsoft Azure account name to be used
   -azure.container-name cortex:
      Name of the blob container used to store chunks. Defaults to cortex. This container must be created before running cortex. (default cortex)
   -azure.download-buffer-count int:
      Number of buffers used to used to upload a chunk. (defaults to 1) (default 1)
   -azure.download-buffer-size int:
      Preallocated buffer size for downloads (default is 512KB) (default 512000)
   -azure.max-retries int:
      Number of retries for a request which times out. (default 5)
   -azure.max-retry-delay duration:
      Maximum time to wait before retrying a request. (default 500ms)
   -azure.min-retry-delay duration:
      Minimum time to wait before retrying a request. (default 10ms)
   -azure.request-timeout duration:
      Timeout for requests made against azure blob storage. Defaults to 30 seconds. (default 30s)
   -azure.upload-buffer-size int:
      Preallocated buffer size for up;oads (default is 256KB) (default 256000)
```

but clearly something is wrong when adding to config.yaml

**Comment by gibbonsjohnm** [comment]
Where does this currently stand?

**Comment by sshah90** [comment]
@abelal83 yes they have support for sending chunks to Azure blob but not for indexing which is mandatory so you need to use key-value store for that (ex. boltdb supported).
 
you can use config like this for azure ([Source](https://github.com/grafana/loki/issues/800)).
`
config:
  schema_config:
    configs:
      - from: 2020-02-01
        store: boltdb #indexing yet not support in Azure so use boltdb for azure
        object_store: azure
        schema: v9
  storage_config:
    azure:
      container_name: something
      account_name: something
      account_key: something
`

**Comment by abelal83** [comment]
Thanks @sshah90. I'm looking to run multi instances of loki and as indexing not supported on blob storage will run cassandra db cluster which I think should be fine.

**Comment by shapeofarchitect** [comment]
@sshah90 Just checked your config there , you also added comment that ` #indexing yet not support in Azure so use boltdb for azure`  ##  I am assuming that this was before `bolt-db-shipper` was not merged. Now with Loki 1.5.0 with @sandeepsukhani  change for botldb-shipper we can use single blob storage with this config ?

**Comment by danbrad** [comment]
@shapeofarchitect Did you ever manage to resolve this? I am getting the same error.

**Comment by danbrad** [comment]
Worked it out.. Directory should be `/data/loki/index`

**Comment by abelal83** [comment]
> Worked it out.. Directory should be `/data/loki/index`

Would be great if you're able to show your complete config?

**Comment by danbrad** [comment]
The issue shapeofarchitect was getting was caused by the directory configured for `active_index_directory` being `/loki/index`

Setting it to `/data/loki/index` appeared to work. ie.:

```
      boltdb_shipper:
        active_index_directory: /data/loki/index
        shared_store: azure
        cache_location: /data/loki/boltdb-cache
```

I then realised that the loki-stack helm chart has a set of sane defaults for this, so I removed the active_index_directory and cache_location out of my config. My values file now looks like this:

```
loki:
  config:
    schema_config:
      configs:
        - from: 2021-03-03
          store: boltdb-shipper
          object_store: azure
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      azure:
          container_name: something
          account_name: something
          account_key: something

      boltdb_shipper:
        shared_store: azure
```

Defaults from the helm chart (shared_store is overwritten by my value of 'azure'):

```
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
      shared_store: filesystem
```

https://github.com/grafana/helm-charts/blob/main/charts/loki/values.yaml

**Comment by sshah90** [comment]
@danbrad 's configs looks correct.

Just sharing our config for Blotdb shipper with Azure Blob (we use Loki `v2.0`).

```yaml
schema_config:
  configs:
  - from: "2020-12-11"
    index:
      period: 24h
      prefix: index_
    object_store: azure
    schema: v11
    store: boltdb-shipper
storage_config:
  azure:
    account_key: xxxxx
    account_name: xxxx
    container_name: loki
    request_timeout: 0
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: azure
  filesystem:
    directory: /data/loki/chunks
```
