### ISSUE TITLE
Write Ahead Log (WAL) config unmarshal errors

### ISSUE THREAD

**Issue by valdiss** [grafana/loki#3431]
**Describe the bug**
I want to use WAL config to have some kind of security and make sure I don't lose any log streams before it's flush to the Database.

I followed the instructions from this page : https://grafana.com/docs/loki/latest/operations/storage/wal/
And wrote my config file following the pattern of https://grafana.com/docs/loki/latest/configuration/#ingester_config documentation and ended up with something like this:

```
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_retain_period: 30s
  chunk_target_size: 1536000
  max_chunk_age: 1h
  
  wal:
    enabled: true
    dir: C:/Loki/wal
```

I then get the following unmarshall error:
`
2021-03-04 12:10:59.878172 I | proto: duplicate proto type registered: ingester.Series
failed parsing config: loki-local-config.yaml: yaml: unmarshal errors:
  line 29: field wal not found in type ingester.Config
`

**To Reproduce**
1. Start Loki v2.1.0 default example local config including any wal configuration in the ingester part.

**Environment:**
 - Infrastructure: Windows
 - Deployment tool: Binary
