### ISSUE TITLE
KMS option for DynamoDB storage.

### ISSUE THREAD

**Issue by ServerNinja** [grafana/loki#3438]
**Describe the solution you'd like**

Would be great if there was an option to configure loki to use a KMS key ARN in its dynamodb configuration to ensure that all tables created for indexes are encrypted with KMS key. This would meet enterprise security standards for logging.

Example:
```
    storage_config:
      aws:
        s3: s3://us-east-1
        bucketnames: my-example-bucket
        dynamodb:
          dynamodb_url: dynamodb://us-east-1
          kms_arn: arn:aws:kms:us-east-1:XXXXXXXXXXXXXXXX:key/XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

    schema_config:
      configs:
      - from: 2020-07-01
        store: aws
        object_store: aws
        schema: v11
        index:
          prefix: my-example-table-prefix_
          period: 24h
```
