### ISSUE TITLE
validate promtail config via a dedicated flag

### ISSUE THREAD

**Issue by landryb** [grafana/loki#3445]
as was done for loki in #2737 for #2713 it would be great if promtail had a flag to just validate the config file and exit (with the corresponding exit status). That would allow for seamless deployment/validation of promtail configs by ansible for example.

for example, i have this for loki:
```
- name: Template loki configuration
  template:
    src: config.yml.j2
    dest: /opt/loki/config.yml
    validate: "/opt/loki/loki-linux-amd64 -verify-config -config.file %s"
  notify: restart loki
```
