### ISSUE TITLE
Can we delete chunk in s3 after retention period

### ISSUE THREAD

**Issue by amitrana93** [grafana/loki#3450]
I have set up a PLG stack that stores index and chunk on s3 and sets a retention period of 1 month.

However, I have successfully seen the logs for 1 month but see some files created in S3 fake directory in the s3 bucket before 1 month.

can we have the option to delete chunks after the retention period?

Following my chunk and table manager config

```
chunk_store_config:
    max_look_back_period: 168h
  table_manager:
    retention_deletes_enabled: true
    retention_period: 168h
```

Here screenshot for s3 bucket.

![Screenshot from 2021-03-09 12-24-30](https://user-images.githubusercontent.com/74708925/110431606-04fc5580-80d4-11eb-8587-ccf044a562dc.png)
