### ISSUE TITLE
High Memory usage (up to 7GB) in Loki pod

### ISSUE THREAD

**Issue by sdil** [grafana/loki#3461]
**Describe the bug**
I am seeing high memory usage (up to 7GB) on our Loki pod after a few hours of running. Attached here is the Loki memory usage chart as shown on our [Lens](https://k8slens.dev/) UI:

![image](https://user-images.githubusercontent.com/461537/110575351-ac8f8b80-8199-11eb-9a4d-2eabee1b6916.png)

The memory usage starts growing significantly at 13:55 local time (The server UTC time is 05:55). I did not run any query on Grafana UI, the Loki pod is just ingesting the logs. At 14:55 (06:55 server time), I started killing the pod and uninstall the Helm app on the Kubernetes cluster. The logs ingested are around ~1MB per hour (I ran `ls -lh` in `/data/loki/boltdb-cache` directory in Loki pod).

Loki is configured with Wasabi S3 as cloud storage. The file is uploaded correctly to the Wasabi S3 bucket.

Here is the full Loki pod log: https://gist.github.com/sdil/b492481ef51d19de3d79fbd11af1bc92

I have set up a dummy Kubernetes cluster with the exact same Loki setup but with much less log ingestion. I did not see high memory usage in the cluster as in our production cluster.

**To Reproduce**
1. Install Loki version="(version=2.1.0, branch=HEAD, revision=1b79df375) helm and wait for a few hours.

**Expected behavior**
The memory usage should be steady and not growing to over 6GB.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

This is the Helm values file:

```
loki:
  enabled: true
  config:
    auth_enabled: false

    ingester:
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      max_transfer_retries: 0
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    compactor:
      working_directory: /data/loki/boltdb-shipper-compactor
      shared_store: aws

    schema_config:
      configs:
        - from: 2021-02-24
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    server:
      http_listen_port: 3100

    storage_config:
      aws:
        s3: s3://xxx:xxx@s3.wasabisys.com/xxx
        region: us-east-1
        s3forcepathstyle: true
      boltdb_shipper:
        active_index_directory: /data/loki/index
        shared_store: s3
        cache_location: /data/loki/boltdb-cache
        cache_ttl: 1h

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h

promtail:
  enabled: true
```

The full Loki log can be found here: https://gist.github.com/sdil/b492481ef51d19de3d79fbd11af1bc92
