### ISSUE TITLE
promtail_syslog_* metrics missing after Promtail upgrade to 2.2.0

### ISSUE THREAD

**Issue by karlism** [grafana/loki#3480]
**Describe the bug**
`promtail_syslog_*` metrics are missing after Promtail upgrade from 2.1.0 to 2.2.0.

**To Reproduce**
1. Update Promtail from 2.1.0 to 2.2.0
```
# curl -s localhost:9080/metrics | grep -e ^promtail_syslog -e ^promtail_build
promtail_build_info{branch="HEAD",goversion="go1.15.3",revision="1b79df37",version="2.1.0"} 1
promtail_syslog_empty_messages_total 0
promtail_syslog_target_entries_total 0
promtail_syslog_target_parsing_errors_total 0

# yum update promtail -y
[...]
Resolving Dependencies
--> Running transaction check
---> Package promtail.x86_64 0:2.1.0-1.el7 will be updated
---> Package promtail.x86_64 0:2.2.0-1.el7 will be an update
[...]

# systemctl restart promtail

# curl -s localhost:9080/metrics | grep -e ^promtail_syslog -e ^promtail_build
promtail_build_info{branch="HEAD",goversion="go1.15.3",revision="a27c7991",version="2.2.0"} 1
```

**Expected behavior**
I would expect these metrics to be present in Promtail 2.2.0

**Environment:**
 - Infrastructure: bare metal
 - Deployment tool: ansible

**Screenshots, Promtail config, or terminal output**
```
# cat /etc/promtail/promtail.yml
---
#
# Ansible managed
#

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: "/var/lib/promtail/positions.yaml"

clients:
  # loki
  - url: http://localhost:3100/loki/api/v1/push


scrape_configs:
  - job_name: "syslog"
    pipeline_stages:
    - regex:
        expression: '^(?P<timestamp>\w{3} \d{2} \d{2}:\d{2}:\d{2}) \S+ (?P<message>(?P<service>\w+)(\[\d+\])?:
          .*)'
    - template:
        source: service
        template: '{{ .Value | ToLower }}'
    - labels:
        service: null
    - timestamp:
        format: Jan 02 15:04:05
        source: timestamp
    - output:
        source: message
    - match:
        selector: '{service=~"alertmanager|loki|prometheus|promtail"}'
        stages:
        - regex:
            expression: .* level=(?P<level>\w+) ts=(?P<timestamp>[T\d-:.Z]*) .*
        - labels:
            level: null
        - timestamp:
            format: RFC3339Nano
            source: timestamp
        - match:
            selector: '{service="alertmanager|prometheus|promtail"}'
            stages:
            - regex:
                expression: .* component=(?P<component>\w+) .*
            - labels:
                component: null
        - match:
            action: drop
            selector: '{level="debug"}'
    - match:
        selector: '{service=~"node_exporter"}'
        stages:
        - regex:
            expression: .* time=\"(?P<timestamp>[T\d-:.Z]*)\" level=(?P<level>\w+).*
        - labels:
            level: null
        - timestamp:
            format: RFC3339
            source: timestamp
        - match:
            action: drop
            selector: '{level="debug"}'
    - match:
        selector: '{service="sshd"}'
        stages:
        - regex:
            expression: .* session opened for user (?P<user>\w+).*
        - labels:
            user: null
        - regex:
            expression: .* Accepted \w+ for (?P<user>\w+) from .*
        - labels:
            user: null
    - match:
        selector: '{service="sudo"}'
        stages:
        - regex:
            expression: '.*sudo:  (?P<user>\w+) : .* COMMAND=(?P<command>[\w\/]+)'
        - labels:
            command: null
            user: null
    - match:
        selector: '{service="useradd"}'
        stages:
        - regex:
            expression: '.* new user: name=(?P<user>\w+), .*'
        - labels:
            user: null
        - regex:
            expression: add .(?P<user>\w+). to .*
        - labels:
            user: null
    - match:
        selector: '{service="usermod"}'
        stages:
        - regex:
            expression: .* change user .(?P<user>\w+). .*
        - labels:
            user: null
    - match:
        selector: '{service="yum"}'
        stages:
        - regex:
            expression: '.*yum\[\d+\]: (?P<action>\w+): (?P<package>[\w\-\.]+)'
        - template:
            source: action
            template: '{{ .Value | ToLower }}'
        - labels:
            action: null
            package: null
    - match:
        action: drop
        selector: '{service=~"polkitd"}'
    static_configs:
    - labels:
        __path__: /var/log/{cron,messages,secure}
        cluster: ''
        environment: development
        hostname: hostname
        job: syslog
        platform: centos
        role: logging_server
        site: XXX
        tenant: YYY
      targets:
      - localhost
```
