### ISSUE TITLE
Support for log messages in alerts

### ISSUE THREAD

**Issue by LuciferInLove** [grafana/loki#3507]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to pass a message text from logs in alerts.

**Describe the solution you'd like**
It would be nice if there was some variable containing the log message that we could pass in the alert. For instance:
```
- name: errors
  rules:
  - alert: ErrorsInLogs
    expr: some_expr
    labels:
      severity: critical
    annotations:
      description: 'There is an error in {{ $labels.job }} logs'
      logMessage: '{{ $output }}'
```
