### ISSUE TITLE
Compactor is not running in the distributed single binary mode

### ISSUE THREAD

**Issue by tobernguyen** [grafana/loki#3512]
**Describe the bug**
Loki running in distributed mode with single binary deployment (1 statefulset with 3 replicas, single binary mode in each pod). I believe the compactor is not working because:
- `/data/loki/boltdb-shipper-compactor` is not created in pod
- Index files are not compacted into one file, each index directory in S3 bucket (24h index) contains around 300 files (while it should be several files if the compactor is working if I understand correctly)
- Metrics endpoint of loki doesn't contain metrics for compactor like
```
compact_tables_operation_total
compact_tables_operation_duration_seconds
``` 

**To Reproduce**

I used the [single binary helm chart](https://github.com/grafana/helm-charts/blob/main/charts/loki/README.md) and here is my `values.yaml`:

```yaml
image:
  repository: grafana/loki
  tag: 2.2.0

ingress:
  enabled: false

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - loki
          topologyKey: failure-domain.beta.kubernetes.io/zone
        weight: 100

replicas: 3

resources:
  limits:
    cpu: "1"
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi

persistence:
  enabled: true
  accessModes:
  - ReadWriteOnce
  size: 10Gi
  storageClassName: kops-ssd-1-17

extraArgs:
  config.expand-env: true # This is to support using Environment Variable in the configuration: https://grafana.com/docs/loki/latest/configuration/#configuration-file-reference

serviceMonitor:
  enabled: true

extraPorts:
# Additional ports to the loki services. Useful to expose extra container ports.
- port: 7946
  protocol: TCP
  name: member-ring
  targetPort: member-ring
```

I generate loki templates from helm with `helm template` command then override the loki-configuration (k8s secret object) with this:

```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  max_transfer_retries: 0
  chunk_idle_period: 12h
  chunk_target_size: 1536000
  max_chunk_age: 12h
  lifecycler:
    join_after: 0s
    ring:
      kvstore:
        store: memberlist

memberlist:
  # Expose this port on all distributor, ingester
  # and querier replicas.
  bind_port: 7946

  # You can use a headless k8s service for all distributor,
  # ingester and querier components.
  join_members:
  - lr-loki-headless.loki.svc.cluster.local:7946

limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_concurrent_tail_requests: 20
  max_cache_freshness_per_query: 10m

schema_config:
  configs:
    - from: "2020-09-07"
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  aws:
    s3: ${S3_BUCKET_URI}
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 168h
    shared_store: s3
    query_ready_num_days: 7

query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 5
  # parallelize queries in 15min intervals
  split_queries_by_interval: 15m
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 1024
        validity: 24h

frontend:
  log_queries_longer_than: 5s
  compress_responses: true

compactor:
  working_directory: /data/loki/boltdb-shipper-compactor
  shared_store: s3
```

**Final YAML that is deployed (After I run the helm template, and add the kustomize overlay)**
```yaml
kustomize build .
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: loki
    version: "1.0"
  name: loki
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app: loki
    chart: loki-2.5.0
    heritage: Helm
    release: lr
    version: "1.0"
  name: lr-loki
  namespace: loki
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app: loki
    chart: loki-2.5.0
    heritage: Helm
    release: lr
    version: "1.0"
  name: lr-loki
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  readOnlyRootFilesystem: true
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - persistentVolumeClaim
  - secret
  - projected
  - downwardAPI
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: loki
    chart: loki-2.5.0
    heritage: Helm
    release: lr
    version: "1.0"
  name: lr-loki
  namespace: loki
rules:
- apiGroups:
  - extensions
  resourceNames:
  - lr-loki
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: loki
    chart: loki-2.5.0
    heritage: Helm
    release: lr
    version: "1.0"
  name: lr-loki
  namespace: loki
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lr-loki
subjects:
- kind: ServiceAccount
  name: lr-loki
  namespace: loki
---
apiVersion: v1
data:
  loki.yaml: YXV0aF9lbmFibGVkOiBmYWxzZQoKc2VydmVyOgogIGh0dHBfbGlzdGVuX3BvcnQ6IDMxMDAKICBsb2dfbGV2ZWw6IGluZm8KCmRpc3RyaWJ1dG9yOgogIHJpbmc6CiAgICBrdnN0b3JlOgogICAgICBzdG9yZTogbWVtYmVybGlzdAoKaW5nZXN0ZXI6CiAgbWF4X3RyYW5zZmVyX3JldHJpZXM6IDAKICBjaHVua19pZGxlX3BlcmlvZDogMTJoCiAgY2h1bmtfdGFyZ2V0X3NpemU6IDE1MzYwMDAKICBtYXhfY2h1bmtfYWdlOiAxMmgKICBsaWZlY3ljbGVyOgogICAgam9pbl9hZnRlcjogMHMKICAgIHJpbmc6CiAgICAgIGt2c3RvcmU6CiAgICAgICAgc3RvcmU6IG1lbWJlcmxpc3QKCm1lbWJlcmxpc3Q6CiAgIyBFeHBvc2UgdGhpcyBwb3J0IG9uIGFsbCBkaXN0cmlidXRvciwgaW5nZXN0ZXIKICAjIGFuZCBxdWVyaWVyIHJlcGxpY2FzLgogIGJpbmRfcG9ydDogNzk0NgoKICAjIFlvdSBjYW4gdXNlIGEgaGVhZGxlc3MgazhzIHNlcnZpY2UgZm9yIGFsbCBkaXN0cmlidXRvciwKICAjIGluZ2VzdGVyIGFuZCBxdWVyaWVyIGNvbXBvbmVudHMuCiAgam9pbl9tZW1iZXJzOgogIC0gbHItbG9raS1oZWFkbGVzcy5sb2tpLnN2Yy5jbHVzdGVyLmxvY2FsOjc5NDYKCmxpbWl0c19jb25maWc6CiAgaW5nZXN0aW9uX3JhdGVfbWI6IDEwCiAgaW5nZXN0aW9uX2J1cnN0X3NpemVfbWI6IDIwCiAgbWF4X2NvbmN1cnJlbnRfdGFpbF9yZXF1ZXN0czogMjAKICBtYXhfY2FjaGVfZnJlc2huZXNzX3Blcl9xdWVyeTogMTBtCgpzY2hlbWFfY29uZmlnOgogIGNvbmZpZ3M6CiAgICAtIGZyb206ICIyMDIwLTA5LTA3IgogICAgICBzdG9yZTogYm9sdGRiLXNoaXBwZXIKICAgICAgb2JqZWN0X3N0b3JlOiBhd3MKICAgICAgc2NoZW1hOiB2MTEKICAgICAgaW5kZXg6CiAgICAgICAgcHJlZml4OiBsb2tpX2luZGV4XwogICAgICAgIHBlcmlvZDogMjRoCgpzdG9yYWdlX2NvbmZpZzoKICBhd3M6CiAgICBzMzogJHtTM19CVUNLRVRfVVJJfQogIGJvbHRkYl9zaGlwcGVyOgogICAgYWN0aXZlX2luZGV4X2RpcmVjdG9yeTogL2RhdGEvbG9raS9ib2x0ZGItc2hpcHBlci1hY3RpdmUKICAgIGNhY2hlX2xvY2F0aW9uOiAvZGF0YS9sb2tpL2JvbHRkYi1zaGlwcGVyLWNhY2hlCiAgICBjYWNoZV90dGw6IDE2OGgKICAgIHNoYXJlZF9zdG9yZTogczMKICAgIHF1ZXJ5X3JlYWR5X251bV9kYXlzOiA3CgpxdWVyeV9yYW5nZToKICAjIG1ha2UgcXVlcmllcyBtb3JlIGNhY2hlLWFibGUgYnkgYWxpZ25pbmcgdGhlbSB3aXRoIHRoZWlyIHN0ZXAgaW50ZXJ2YWxzCiAgYWxpZ25fcXVlcmllc193aXRoX3N0ZXA6IHRydWUKICBtYXhfcmV0cmllczogNQogICMgcGFyYWxsZWxpemUgcXVlcmllcyBpbiAxNW1pbiBpbnRlcnZhbHMKICBzcGxpdF9xdWVyaWVzX2J5X2ludGVydmFsOiAxNW0KICBjYWNoZV9yZXN1bHRzOiB0cnVlCiAgcmVzdWx0c19jYWNoZToKICAgIGNhY2hlOgogICAgICBlbmFibGVfZmlmb2NhY2hlOiB0cnVlCiAgICAgIGZpZm9jYWNoZToKICAgICAgICBtYXhfc2l6ZV9pdGVtczogMTAyNAogICAgICAgIHZhbGlkaXR5OiAyNGgKCmZyb250ZW5kOgogIGxvZ19xdWVyaWVzX2xvbmdlcl90aGFuOiA1cwogIGNvbXByZXNzX3Jlc3BvbnNlczogdHJ1ZQoKY29tcGFjdG9yOgogIHdvcmtpbmdfZGlyZWN0b3J5OiAvZGF0YS9sb2tpL2JvbHRkYi1zaGlwcGVyLWNvbXBhY3RvcgogIHNoYXJlZF9zdG9yZTogczMK
kind: Secret
metadata:
  annotations: {}
  labels:
    app: loki
    chart: loki-2.5.0
    heritage: Helm
    release: lr
    version: "1.0"
  name: lr-loki
  namespace: loki
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: loki
    chart: loki-2.5.0
    heritage: Helm
    release: lr
    version: "1.0"
  name: lr-loki
  namespace: loki
spec:
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  - name: member-ring
    port: 7946
    protocol: TCP
    targetPort: member-ring
  selector:
    app: loki
    release: lr
    version: "1.0"
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki
    chart: loki-2.5.0
    heritage: Helm
    release: lr
    variant: headless
    version: "1.0"
  name: lr-loki-headless
  namespace: loki
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
  - name: member-ring
    port: 7946
    protocol: TCP
    targetPort: member-ring
  selector:
    app: loki
    release: lr
    version: "1.0"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    app: loki
    chart: loki-2.5.0
    heritage: Helm
    release: lr
    version: "1.0"
  name: lr-loki
  namespace: loki
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  selector:
    matchLabels:
      app: loki
      release: lr
      version: "1.0"
  serviceName: lr-loki-headless
  template:
    metadata:
      annotations:
        checksum/config: 2076c43090c6c845c8ac827bb2bc38170b336cf06843c51bcf43ce33dbb55884
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
      labels:
        app: loki
        name: loki
        release: lr
        version: "1.0"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - loki
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
      containers:
      - args:
        - -config.file=/etc/loki/loki.yaml
        - -config.expand-env=true
        image: grafana/loki:2.2.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
        name: loki
        ports:
        - containerPort: 7946
          name: member-ring
          protocol: TCP
        - containerPort: 3100
          name: http-metrics
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 512Mi
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/loki
          name: config
        - mountPath: /data
          name: storage
      initContainers: []
      nodeSelector: {}
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      serviceAccountName: lr-loki
      terminationGracePeriodSeconds: 4800
      tolerations: []
      volumes:
      - name: config
        secret:
          secretName: lr-loki
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      annotations: {}
      labels:
        app: loki
        version: "1.0"
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: kops-ssd-1-17
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: loki
    chart: loki-2.5.0
    heritage: Helm
    release: lr
    version: "1.0"
  name: lr-loki
  namespace: loki
spec:
  endpoints:
  - port: http-metrics
  namespaceSelector:
    matchNames:
    - loki
  selector:
    matchLabels:
      app: loki
      release: lr
      variant: headless
```

**Expected behavior**
- Compactor should have kicked in (but I know we should have only one instance of Compactor running so I don't how loki should handle this)
- Index files should have been compacted into single file and unnecessary index files should have been removed from s3 bucket.

**Environment:**
 - Infrastructure: Kubernetes 1.19
 - Deployment tool: kustomize (I used helm just for printing out the template files)

**Screenshots, Promtail config, or terminal output**
Promtail is installed using the helm chart https://github.com/grafana/helm-charts/blob/main/charts/promtail/README.md with this configuration:
```yaml
config:
  lokiAddress: http://lr-loki.loki.svc.cluster.local:3100/loki/api/v1/push

rbac:
  create: true
  pspEnabled: true

resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Add extra Commandline args while starting up promtail.
# more info : https://github.com/grafana/loki/pull/1530

extraCommandlineArgs: []
# example:
# extraCommandlineArgs:
#   - -client.external-labels=hostname=$(HOSTNAME)

serviceMonitor:
  enabled: true
```

First few lines when Loki is starting up (I pick the second pod of the statefulset)

```
level=info ts=2021-03-18T18:29:53.820752723Z caller=main.go:130 msg="Starting Loki" version="(version=2.2.0, branch=HEAD, revision=a27c79913)"
level=info ts=2021-03-18T18:29:53.820861786Z caller=modules.go:477 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2021-03-18T18:29:53.821398851Z caller=server.go:229 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-03-18T18:29:53.82283133Z caller=table_manager.go:241 msg="loading table loki_index_18703"
level=info ts=2021-03-18T18:29:53.82394557Z caller=table_manager.go:241 msg="loading table loki_index_18704"
level=info ts=2021-03-18T18:29:53.841683033Z caller=table_manager.go:171 msg="uploading tables"
level=info ts=2021-03-18T18:29:53.841725544Z caller=table_manager.go:343 msg="loading local table loki_index_18696"
level=info ts=2021-03-18T18:29:53.841894769Z caller=table.go:336 msg="uploading table loki_index_18704"
level=info ts=2021-03-18T18:29:53.84193682Z caller=table.go:363 msg="finished uploading table loki_index_18704"
level=info ts=2021-03-18T18:29:53.841974071Z caller=table.go:421 msg="cleaning up unwanted dbs from table loki_index_18704"
level=info ts=2021-03-18T18:29:54.435408187Z caller=table_manager.go:343 msg="loading local table loki_index_18697"
level=info ts=2021-03-18T18:29:54.730199253Z caller=table_manager.go:343 msg="loading local table loki_index_18698"
level=info ts=2021-03-18T18:29:55.010861773Z caller=table_manager.go:343 msg="loading local table loki_index_18699"
level=info ts=2021-03-18T18:29:55.230914762Z caller=table_manager.go:343 msg="loading local table loki_index_18700"
level=info ts=2021-03-18T18:29:55.557294948Z caller=table_manager.go:343 msg="loading local table loki_index_18701"
level=info ts=2021-03-18T18:29:55.803007516Z caller=table_manager.go:343 msg="loading local table loki_index_18702"
level=info ts=2021-03-18T18:29:56.001542108Z caller=table_manager.go:343 msg="loading local table loki_index_18703"
level=info ts=2021-03-18T18:29:56.324312126Z caller=table_manager.go:343 msg="loading local table loki_index_18704"
level=info ts=2021-03-18T18:29:56.70049756Z caller=table.go:440 msg="downloading object from storage with key loki_index_18704/lr-loki-2-1616011527326166061-1616091300.gz"
level=info ts=2021-03-18T18:29:56.756196509Z caller=util.go:55 msg="downloaded file loki_index_18704/lr-loki-2-1616011527326166061-1616091300.gz"
level=info ts=2021-03-18T18:29:56.788988593Z caller=shipper_index_client.go:100 msg="starting boltdb shipper in 0 mode"
level=info ts=2021-03-18T18:29:56.789907068Z caller=memberlist_client.go:380 msg="Using memberlist cluster node name" name=lr-loki-2-e5e3e2d1
level=info ts=2021-03-18T18:29:56.790936526Z caller=modules.go:502 msg="RulerStorage is nil.  Not starting the ruler."
level=info ts=2021-03-18T18:29:56.791772099Z caller=module_service.go:59 msg=initialising module=store
level=info ts=2021-03-18T18:29:56.7918303Z caller=module_service.go:59 msg=initialising module=server
level=info ts=2021-03-18T18:29:56.791859761Z caller=module_service.go:59 msg=initialising module=memberlist-kv
level=info ts=2021-03-18T18:29:56.791954014Z caller=module_service.go:59 msg=initialising module=ingester
level=info ts=2021-03-18T18:29:56.792036766Z caller=module_service.go:59 msg=initialising module=ring
level=info ts=2021-03-18T18:29:56.792050936Z caller=lifecycler.go:521 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2021-03-18T18:29:56.792122718Z caller=module_service.go:59 msg=initialising module=table-manager
level=info ts=2021-03-18T18:29:56.792159679Z caller=lifecycler.go:550 msg="instance not found in ring, adding with no tokens" ring=ingester
level=info ts=2021-03-18T18:29:56.792311573Z caller=lifecycler.go:397 msg="auto-joining cluster after timeout" ring=ingester
level=info ts=2021-03-18T18:29:56.792472908Z caller=module_service.go:59 msg=initialising module=distributor
level=info ts=2021-03-18T18:29:56.792488678Z caller=module_service.go:59 msg=initialising module=ingester-querier
level=info ts=2021-03-18T18:29:56.792626702Z caller=loki.go:248 msg="Loki started"
level=info ts=2021-03-18T18:29:56.793800894Z caller=table_manager.go:324 msg="synching tables" expected_tables=193
level=info ts=2021-03-18T18:29:56.808600897Z caller=memberlist_client.go:492 msg="joined memberlist cluster" reached_nodes=2
level=info ts=2021-03-18T18:29:56.843093678Z caller=table_manager.go:476 msg="creating table" table=loki_index_18541
level=info ts=2021-03-18T18:29:56.84316806Z caller=table_manager.go:476 msg="creating table" table=loki_index_18548
level=info ts=2021-03-18T18:29:56.84318376Z caller=table_manager.go:476 msg="creating table" table=loki_index_18559
level=info ts=2021-03-18T18:29:56.84319625Z caller=table_manager.go:476 msg="creating table" table=loki_index_18631
```

**Comment by tobernguyen** [comment]
Update: we have deployed the compactor separately as a workaround and everything is working great for us now (indexes files are being compacted by the compactor and labels are loading much faster)

Compactor 
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lr-loki-compactor
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: lr
    app.kubernetes.io/component: compactor
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: lr
      app.kubernetes.io/component: compactor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/instance: lr
        app.kubernetes.io/component: compactor
    spec:
      serviceAccountName: lr-loki
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      terminationGracePeriodSeconds: 30
      containers:
        - name: loki
          image: docker.io/grafana/loki:2.2.0
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/loki/loki.yaml
            - -config.expand-env=true
            - -target=compactor
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /data
          resources:
            {}
      volumes:
        - name: config
          secret:
            secretName: lr-loki
        - name: data
          persistentVolumeClaim:
            claimName: data-lr-loki-compactor
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-lr-loki-compactor
  labels:
    app.kubernetes.io/component: compactor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: lr-loki-compactor
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: compactor
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: lr
    app.kubernetes.io/component: compactor
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lr-loki-compactor
  labels:
    app.kubernetes.io/instance: lr
    app.kubernetes.io/component: compactor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: lr
      app.kubernetes.io/component: compactor
  endpoints:
    - port: http
      scheme: http

```
