### ISSUE TITLE
Promtail: How to keep all pod labels?

### ISSUE THREAD

**Issue by dbluxo** [grafana/loki#3519]
I am wondering that in the [default scrape configuration](https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml) of Promtail only certain labels are allowed through (pod, container, namespace, node_name). **How can I keep all labels from the pods?** What would I need to configure in Promtail to do this without manually configuring each label (I don’t know all the labels up front)?

**Comment by nealf** [comment]
This seems to be a change from earlier versions that wasn't documented. I just upgraded from 2.0 to 2.2 and found that a number of my Grafana logging dashboards that were using custom labels were no longer viewing the appropriate logs because pod labels were no longer being added as log labels.

This feature apparently comes from the `labelmap` action of the [relabel_configs](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#relabel_configs) section of the config file. This was included in [previous helm chart defaults](https://github.com/grafana/loki/blob/6978ee5d73878d7406bda68296a3dd8ecda4d538/production/helm/promtail/templates/configmap.yaml#L34), but was left out somewhere along the way (intentionally or not) during the refactoring and upgrade to 2.2. 

I'm using the helm chart (v3.5.0 currently), so I was able to add this configuration back in by copying and pasting everything from the `config.snippets.common` section of the default [values.yaml](https://github.com/grafana/helm-charts/blob/e8c2dede8ce6391af6a70874c3a58d0082d54113/charts/promtail/values.yaml#L240-L279) file, and then adding the following to the bottom of that section:
```yaml
- action: labelmap
  regex: __meta_kubernetes_pod_label_(.+)
```

**Comment by dbluxo** [comment]
@nealf Awesome, thanks!

**Comment by pete911** [comment]
thanks @nealf, if anyone is using `loki-stack` chart, just add this to your values (all the actions are needed otherwise they would be removed and you would end up with only labelmap - helm templating doesn't do merge, but it does replace):
```
promtail:
  config:
    snippets:
      common:
        # this is copy and paste of existing actions, so we don't lose them
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_node_name
          target_label: node_name
        - action: replace
          source_labels:
            - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          replacement: $1
          separator: /
          source_labels:
            - namespace
            - app
          target_label: job
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_name
          target_label: pod
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_container_name
          target_label: container
        - action: replace
          replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
          target_label: __path__
        - action: replace
          regex: true/(.*)
          replacement: /var/log/pods/*$1/*.log
          separator: /
          source_labels:
            - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
            - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
            - __meta_kubernetes_pod_container_name
          target_label: __path__
        # this gets all kubernetes labels as well
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
```

**Comment by miglocatiq** [comment]
> 

How would I use one of the labels from labelmap as a selector within match for a stage?
Something like this doesn't work:
```yaml
- match:
    selector: '{labelmap.<labelkey>="labelvalue"}'
    stages:
```

**Comment by miglocatiq** [comment]
> > 
> 
> How would I use one of the labels from labelmap as a selector within match for a stage? Something like this doesn't work:
> 
> ```yaml
> - match:
>     selector: '{labelmap.<labelkey>="labelvalue"}'
>     stages:
> ```

Ah you don't even need the labelmap keyword.
You can just select on '{<labelkey>="labelvalue"}'

**Comment by zozo6015** [comment]
Some application pods have the label `environment: <name>`. Since I have multiple clusters all having the same applications  running and all log to the same loki I would really need the ability to add this label into the the ingested logs of the application. I have installed promtail via helm chart grafana/promtail 6.11.0 and I have added the following into the proper place of the values.yaml:

```
config:
  snippets:
    extraRelabelConfigs:
      # keep all kubernetes labels
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
```

it doesn't seam to have any effect.  What else can I do?
