### ISSUE TITLE
Grafana "bad gateway" / Logcli "EOF", while frontend says "status=200"

### ISSUE THREAD

**Issue by liuzhen** [grafana/loki#3524]
**Describe the bug**
when running a (same) large query of {service="scs"} |= "ppppppppppppp":
* grafana always returns "bad gateway";
* logcli returns "EOF"

while in the frontend log, it says:
```
level=info ts=2021-03-23T07:08:45.066191617Z caller=metrics.go:91 org_id=fake traceID=23fcc633a726136e latency=slow query="{service=\"scs\"} |= \"ppppppppppppp\"" query_type=filter range_type=range length=49m29s step=2s duration=36.905519209s status=200 limit=100 returned_lines=0 throughput=1.2GB total_bytes=45GB
```

**To Reproduce**
1. Started Loki 2.2.0 
3. Query: `{service="scs"} |= "ppppppppppppp"`

**Expected behavior**
grafana or logcli return correct "empty" result

**Environment:**
 - Infrastructure: minio (3 baremetal, 24 disks); loki (1 frontend, 6 other nodes, all baremetal)
 - Deployment tool: docker

**Screenshots, Promtail config, or terminal output**
frontend config:
```
auth_enabled: false

http_prefix:

server:
  http_listen_port: 3102

query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 5
  split_queries_by_interval: 5m
  parallelise_shardable_queries: true

frontend:
  compress_responses: true

# frontend won't start if no querier config is supplied
querier:
  query_ingesters_within: 2h

# frontend won't start if no schema_config is supplied
schema_config:
  configs:
    - from: 2020-07-01
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_
        period: 24h
```

others config:
```
auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      consul:
        consistent_reads: true
        host: localhost:8500
        acl_token: [snip]
      store: consul

ingester:
  lifecycler:
    ring:
      kvstore:
        store: consul
        consul:
          host: localhost:8500
          acl_token: [snip]
      replication_factor: 1 # for the simplest debug purpose
  chunk_encoding: snappy
  chunk_retain_period: 30m
  chunk_idle_period: 10m
  chunk_target_size: 15360000
  max_chunk_age: 1h

querier:
  query_timeout: 10s # we might noticed that long timeout stalls the retrying (in effect)
  query_ingesters_within: 2h # greator than max_chunk_age

frontend_worker:
    frontend_address: 10.19.9.161:9091

ruler:
  rule_path: "/mnt/config/tmprules"
  alertmanager_url: [snip]
  enable_sharding: true
  enable_api: true
  ring:
    kvstore:
      consul:
        consistent_reads: true
        host: localhost:8500
        acl_token: [snip]
      store: consul
  storage:
    type: s3
    s3:
      s3forcepathstyle: true
      endpoint: 10.19.8.40:9002
      region: us-east-1
      bucketnames: scs-loki
      access_key_id: [snip]
      secret_access_key: [snip]
      insecure: true

schema_config:
  configs:
    - from: 2020-07-01
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  aws:
    endpoint: minio.service.consul:9002
    region: us-east-1
    bucketnames: scs-loki
    access_key_id: [snip]
    secret_access_key: [snip]
    insecure: true
    s3forcepathstyle: true

  boltdb_shipper:
    active_index_directory: /loki/active_index
    cache_location: /loki/index_cache
    shared_store: s3
    resync_interval: 5s

compactor: null

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 24h
  ingestion_rate_strategy: local
  ingestion_rate_mb: 50

chunk_store_config:
  max_look_back_period: 72h

table_manager:
  retention_deletes_enabled: true
  retention_period: 72h
```

Previously I thought those queries were to large, and tweaked some configs.
Seldom times it returns, and the result stats's total_bytes does not vary from that of frontend when "bad_gateway" much.
