### ISSUE TITLE
Loki auto scaling with AWS ASG?

### ISSUE THREAD

**Issue by yongzhang** [grafana/loki#3527]
Hi,

I'm running loki (v2.2.0) in AWS EC2 managed by ASG, there's an ALB associated with the ASG to open access to `http_listen_port`, here's my config:

```
      auth_enabled: false
      server:
        http_listen_port: 80
        log_level: ${log_level}
      ingester:
        chunk_idle_period: 3m
        chunk_block_size: 262144
        chunk_retain_period: 1m
        max_transfer_retries: 0
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
          interface_names:
          - ens5
          - eth0
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      schema_config:
        configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /data/loki/boltdb-shipper-active
          cache_location: /data/loki/boltdb-shipper-cache
          cache_ttl: 24h
          shared_store: s3
        aws:
          s3: s3://${region}/${bucket_name}
          s3forcepathstyle: true
      chunk_store_config:
        max_look_back_period: 0s
      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s
      compactor:
        working_directory: /data/loki/compactor
        shared_store: s3
```

It is working fine with only one node, but not sure if I scale the asg to more than 1 instances? Thanks.
