### ISSUE TITLE
loki: ingester data missing from parser expression + aggregator

### ISSUE THREAD

**Issue by afletch** [grafana/loki#3528]
**Describe the bug**

I originally discussed this with @cyriltovena  on Slack, but the thread has since gone beyond the Slack workspace retention limit.

The outcome of the discussion was that when performing a parser expression, the ingester data does not get included if an aggregation is used. Therefore, any query on data within the max_chunk_age has an increasing amount of data missed the closer the query range is to the present time.

For me, this is easy to see by querying for the same data with and without the aggregator. (example below)

**To Reproduce**
```
non-aggregated, manual count
./logcli -q  query --step=2s --batch=5000 --since=1h --limit=100000 '{filename="/var/log/apache2/error_log"} | regexp "client (?P<addr>[0-9a-f:.]{6,})" | addr="1.2.3.4"'|wc -l
910

aggregated, with sum of results
./logcli -q query --step=2s --batch=5000 --since=1h --limit=100000 'sum by (addr) (count_over_time({filename="/var/log/apache2/error_log"} | regexp "client (?P<addr>[0-9a-f:.]{6,})" | addr="1.2.3.4"[100ms]))'|jq '[.[]."values"[][1] | tonumber] |add'
35
```

**Expected behavior**
The correct number of results should be returned (same as the non-aggregated query with manual sum)

**Environment:**
 - Infrastructure: Loki 2.2.0

**Screenshots, Promtail config, or terminal output**
loki ingester config;
```
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_target_size: 1048576
  max_chunk_age: 4h
  chunk_idle_period: 3m
  chunk_retain_period: 30s
  max_transfer_retries: 0
```
