### ISSUE TITLE
promtail does not tail logs from all the pods

### ISSUE THREAD

**Issue by huydinhle** [grafana/loki#353]
**Describe the bug**
Promtail does not tail logs from all the pods

**To Reproduce**

0. Start minikube, install helm
1. Started loki master with the helm chart
2. Started promtail master with the helm chart
3. Install grafana using the helm chart ( optional)
4. Check promtail logs, or check grafana 

**Expected behavior**
See every single pods/containers logs show up get tailed, and eventually show up in grafana

**Actual Behavior** 
Logs from apiserver, controller-manager are missing
I even spin up `k8s.gcr.io/logs-generator:v0.1.1` pod to generate logs, but logs from this pod is nowhere to be found

**Environment:**
 - Infrastructure: Minikube v0.34.1
 - Deployment tool: Helm

**Screenshots, promtail config, or terminal output**
If applicable, add any output to help explain your problem.
```yaml
  promtail.yaml: |
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ^$
          source_labels:
          - __meta_kubernetes_pod_label_name
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_label_name
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: instance
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container_name
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - replacement: /var/log/pods/$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
      - job_name: kubernetes-pods-app
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ^$
          source_labels:
          - __meta_kubernetes_pod_label_app
        - action: drop
          regex: .+
          source_labels:
          - __meta_kubernetes_pod_label_name
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_label_app
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: instance
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container_name
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - replacement: /var/log/pods/$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
```

**Comment by sboschman** [comment]
You might want to crosscheck the labels on your pods with the drop actions in the relabel config. Pods without certain labels are ignored. I have pods with `app.kubernetes.io/name` (Helm best practises for labels) and they didn't show up either in Loki.

No `app` label causes the entire pod to be dropped from Loki with the default config:
```
    - action: drop
          regex: ^$
          source_labels:
          - __meta_kubernetes_pod_label_app
```
