### ISSUE TITLE
Loki + Fluentbit entry with timestamp, entry out of order for stream

### ISSUE THREAD

**Issue by osipovdaniil** [grafana/loki#3536]
Hi! I have loki v2.1.0 and fluentbit v1.7.2

loki error logs:
```
caller=grpc_logging.go:38 method=/logproto.Pusher/Push duration=161.889µs err="rpc error: code = Code(400) desc = entry with timestamp 2021-03-25 06:35:35.23857473 +0000 UTC ignored, reason: 'entry out of order' for stream: {kafka_cluster=\"kafka-cluster1\", log_path=\"/var/log/kafka/kafka-request.log\"},\ntotal ignored: 1 out of 1" msg="gRPC\n"
```

Fluentbit config:
```
[PARSER]
    Name multiline_pattern
    Format regex
    Regex ^\[(?<time>[^\]]*)\] (?<level>[^ ]+) (?<message>[^ ].*) (?<class>[^ ]+)
[INPUT]
    Mem_Buf_Limit 100MB
    Buffer_Max_Size 2MB
    Skip_Long_Lines On
    Name tail
    Tag kafka
    Path /var/log/kafka/server.log
    Multiline on
    Parser_Firstline multiline_pattern
    Path_Key log_path
[OUTPUT]
    Name loki
    Match fluentbit
    Host 1.1.1.1
    Port 3100
    Labels my_labels
```

loki deploy to kubernetes and has config:
```
replicas: 3
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 256Mi
service:
  type: LoadBalancer
serviceMonitor:
  enabled: true
config:
  storage_config:
    boltdb_shipper:
      shared_store: s3
    aws:
      s3: s3://<path to s3 bucket>
      s3forcepathstyle: true
  ruler:
    alertmanager_url: <url>
  distributor:
    ring:
      kvstore:
        store: memberlist
  ingester:
    lifecycler:
      ring:
        kvstore:
          store: memberlist
        replication_factor: 1
      final_sleep: 0s
    chunk_idle_period: 5m
    chunk_retain_period: 30s
  memberlist:
    join_members:
    - loki-headless
    max_join_backoff: 3m
    max_join_retries: 50
    min_join_backoff: 1s
    leave_timeout: 30s
  limits_config:
    reject_old_samples: false
  schema_config:
    configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
  ruler:
    storage:
      type: local
      local:
        directory: /rules
    rule_path: /tmp/scratch
    ring:
      kvstore:
        store: inmemory
    enable_api: true
alerting_groups:
  - name: Loki-Alerts
    rules:
      <My alerst>
```

Help how to fix it
