### ISSUE TITLE
use_gzip_compression deprecated when upgrading to 2.2.0

### ISSUE THREAD

**Issue by Prendy** [grafana/loki#3537]
**Describe the bug**
Upgrading from 2.1.0 to 2.2.0, loki distributor and ingester fail to start as the use_gzip_compression setting is not found. This is still shown as an option at https://grafana.com/docs/loki/latest/configuration/#grpc_client_config.
 
**To Reproduce**
1. Started Loki 2.2.0 distributor or ingester with example config:
```
ingester_client:
  pool_config:
    health_check_ingesters: true
  grpc_client_config:
    max_send_msg_size: 16777216
    max_recv_msg_size: 104857600
    use_gzip_compression: true
  remote_timeout: 30s
```

2. Loki fails to start with error:
```
failed parsing config: /etc/loki/loki-distributor-config.yaml: yaml: unmarshal errors:
  line 39: field use_gzip_compression not found in type grpcclient.Config
  line 47: field use_gzip_compression not found in type grpcclient.Config
```

**Expected behavior**
Loki should start as normal in previous version 2.1.0

**Environment:**
 - Infrastructure: EC2
 - Deployment tool: terraform
