### ISSUE TITLE
loki does not support native AWS Dynamodb Autoscaling as stated in doc

### ISSUE THREAD

**Issue by openbob** [grafana/loki#3556]
**Describe the bug**
loki does not support native AWS Dynamodb Autoscaling as stated in doc. According to the doc (https://grafana.com/docs/loki/latest/configuration/#auto_scaling_config), it does and in fact it doesn't.

So my question is "Does loki support AWS Dynamodb Autoscaling at all?"

**To Reproduce**
I have setup the following in my loki.yaml:
```
loki:
  image:
    tag: 2.2.0
    table_manager:
      index_tables_provisioning:
        provisioned_write_throughput: 30
        write_scale:
          enabled: true
          role_arn: arn:aws:iam::xxxxxxxxxxxx:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
          min_capacity: 30
          max_capacity: 100
          out_cooldown: 10
          in_cooldown: 10
          target: 80
        provisioned_read_throughput: 30
        read_scale:
          enabled: true
          role_arn: arn:aws:iam::xxxxxxxxxxxx:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable
          min_capacity: 30
          max_capacity: 150
          out_cooldown: 10
          in_cooldown: 10
          target: 80
```
But when I try to start up loki, I am getting the error:
```
level=info ts=2021-03-30T11:00:26.459330686Z caller=main.go:130 msg="Starting Loki" version="(version=2.2.0, branch=HEAD, revision=a27c79913)"
level=info ts=2021-03-30T11:00:26.459396522Z caller=modules.go:477 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2021-03-30T11:00:26.459566199Z caller=server.go:229 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=error ts=2021-03-30T11:00:26.459671144Z caller=modules.go:261 msg="WriteScale is enabled but no Metrics URL has been provided"
```

Tracing back to the source (https://github.com/grafana/loki/blob/master/pkg/loki/modules.go#L253-L264):
```
	if (t.cfg.TableManager.ChunkTables.WriteScale.Enabled ||
		t.cfg.TableManager.IndexTables.WriteScale.Enabled ||
		t.cfg.TableManager.ChunkTables.InactiveWriteScale.Enabled ||
		t.cfg.TableManager.IndexTables.InactiveWriteScale.Enabled ||
		t.cfg.TableManager.ChunkTables.ReadScale.Enabled ||
		t.cfg.TableManager.IndexTables.ReadScale.Enabled ||
		t.cfg.TableManager.ChunkTables.InactiveReadScale.Enabled ||
		t.cfg.TableManager.IndexTables.InactiveReadScale.Enabled) &&
		t.cfg.StorageConfig.AWSStorageConfig.Metrics.URL == ""{
		level.Error(util_log.Logger).Log("msg", "WriteScale is enabled but no Metrics URL has been provided")
		os.Exit(1)
	}
```
It seems to me I MUST do it the Cortex way to setup the metric that uses Prometheus metrics for autoscaling to work, even if I just want to use the AWS Dynamodb Autoscaling that uses CloudWatch.

**Expected behavior**
loki will setup AWS Dynamodb Autoscaling configuration as per specified.

**Environment:**
My version of loki is:
```
  loki, version 2.2.0 (branch: HEAD, revision: a27c79913)
  build user:       root@c42b5f5263a5
  build date:       2021-03-11T14:03:20Z
  go version:       go1.15.3
  platform:         linux/amd64
```
