### ISSUE TITLE
LogQL filter over large timerange leads to Bad Gateway 

### ISSUE THREAD

**Issue by mrkwtz** [grafana/loki#3590]
**Describe the bug**
We have a LogQL query like that `{namespace="test", pod=~"test-.*", container="main"} |= "$filter"`. When we execute that query in Grafanas metrics explorer or any table panel we're hit with `<html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.19.6</center> </body> </html>` and there are lot of logs in the querier like this:

`
level=info ts=2021-04-08T07:27:18.202484429Z caller=metrics.go:83 org_id=fake traceID=219aab0a5a2419bb latency=fast query="{namespace=\"test\", pod=~\test-.*\", container=\"main\"} |= \"CPU\"" query_type=filter range_type=range length=15m0s step=5m0s duration=71.805515ms status=200 throughput=0B total_bytes=0B`

`level=info ts=2021-04-08T07:27:18.811430181Z caller=metrics.go:83 org_id=fake traceID=219aab0a5a2419bb latency=fast query="{namespace=\"test\", pod=~\"test-.*\", container=\"main\"} |= \"CPU\"" query_type=filter range_type=range length=15m0s step=5m0s duration=336.43019ms status=200 throughput=0B total_bytes=0B
`

literally thousands of them. After we get the 502, the logs also stop coming in but with no error in the pods whatsoever. If we remove the filter so that the query looks like this `{namespace="test", pod=~"test-.*", container="main"}` it takes 1-2 seconds, but we get a result. Its reproducible every time. 

**BUT** it only seems to happen, when we query a big time range (7d in this test). It looks like loki goes through all of the logfiles from this timerange without (pre-)filtering by the provided labels. 

**Expected behavior**
We expect to receive a result as fast as without the filter.

**Environment:**
 - Infrastructure: Kubernetes v1.17
 - Deployment tool: helm
 - Loki version: 2.1.0

Our loki setup includes 3 ingesters, 3 querier, 1 distributor, 1 gateway and 1 query frontend. Its deployed via the _loki-distributed_ Helm chart. Our config looks like this:

```
auth_enabled: false
server:
  log_level: info
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  max_transfer_retries: 0
  chunk_idle_period: 1h
  chunk_target_size: 1536000
  max_chunk_age: 1h
  lifecycler:
    join_after: 0s
    ring:
      replication_factor: 3
      kvstore:
        store: memberlist

memberlist:
  join_members:
    - {{ include "loki.fullname" . }}-memberlist

limits_config:
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_concurrent_tail_requests: 20
  max_cache_freshness_per_query: 10m

schema_config:
  configs:
    - from: 2021-01-28
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  aws:
    s3: s3://eu-central-1/loki-logs-test
  boltdb_shipper:
    active_index_directory: /var/loki/index
    shared_store: s3
    cache_location: /var/loki/cache

query_range:
  align_queries_with_step: true
  max_retries: 5
  split_queries_by_interval: 15m
  cache_results: true

  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 1024
        validity: 24h

frontend_worker:
  frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
```
