### ISSUE TITLE
Renaming log levels in promtail

### ISSUE THREAD

**Issue by Phara0h** [grafana/loki#3599]
I tried researching all day about this and cant seem to get it to work. Is there something I'm doing wrong or not understanding? 

```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
    relabel_configs:
      - source_labels: ['__syslog_message_app_name']
        target_label: 'app'
      - source_labels: ['__syslog_message_severity']
        target_label: 'level'
    pipeline_stages:
      - template:
          source: level
          template: '{{ ToLower .Value }}'
      - template:
          source: level
          template: '{{ Replace .Value "informational" "info" 1}}'
      - template:
          source: level
          template: '{{ Replace .Value "notice" "info" 1}}'
      - template:
          source: level
          template: '{{ Replace .Value "warning" "warn" 1}}'
      - template:
          source: level
          template: '{{ Replace .Value "critical" "error" 1}}'
      - template:
          source: level
          template: '{{ Replace .Value "alert" "fatal" 1}}'
      - template:
          source: level
          template: '{{ Replace .Value "emergency" "fatal" 1}}'
```

**Comment by dannykopping** [comment]
Please ask questions you have in the mailing list: https://groups.google.com/forum/#!forum/lokiproject

Or join our #loki slack channel at http://slack.raintank.io/

**Comment by Phara0h** [comment]
> Please ask questions you have in the mailing list: https://groups.google.com/forum/#!forum/lokiproject
> 
> Or join our #loki slack channel at http://slack.raintank.io/

When I post to that google group my message gets instantly deleted.

**Comment by Phara0h** [comment]
I figured it out on my own. For anyone who runs into this issue and wants their syslogs to show up with the right levels in grafana here you go.

```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://127.0.0.1:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
    relabel_configs:
      - source_labels:
          - __syslog_message_app_name
        target_label: app
      - source_labels: ['__syslog_message_severity']
        target_label: 'level'
        regex: '.*(nformational)'
        replacement: 'info'
      - source_labels: ['__syslog_message_severity']
        target_label: 'level'
        regex: '.*(otice)'
        replacement: 'info'
      - source_labels: ['__syslog_message_severity']
        target_label: 'level'
        regex: '.*(arning)'
        replacement: 'warn'
      - source_labels: ['__syslog_message_severity']
        target_label: 'level'
        regex: '.*(ritical)'
        replacement: 'error'
      - source_labels: ['__syslog_message_severity']
        target_label: 'level'
        regex: '.*(lert)'
        replacement: 'fatal'
      - source_labels: ['__syslog_message_severity']
        target_label: 'level'
        regex: '.*(mergency)'
        replacement: 'fatal'
```
