### ISSUE TITLE
too many unhealthy instances in the ring

### ISSUE THREAD

**Issue by venyowong** [grafana/loki#3611]
Hi, I get `too many unhealthy instances in the ring` response when get `http://localhost:3110/loki/api/v1/label?start=1618482549728000000`.

Loki Version:
```
$ ./loki-linux-amd64 --version
loki, version 2.2.1 (branch: HEAD, revision: babea82e)
  build user:       root@e2d295b84e26
  build date:       2021-04-06T00:52:41Z
  go version:       go1.15.3
  platform:         linux/amd64
```

I run 3 loki instances in my windows WSL.

Instance 1:
```
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3110
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9095

memberlist:
  node_name: node1
  randomize_node_name: false
  abort_if_cluster_join_fails: true
  join_members:
    - localhost:7947
    - localhost:7948
  bind_port: 7946

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist

schema_config:
  configs:
  - from: 2021-04-15
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: ./loki1/index
  boltdb_shipper:
    active_index_directory: ./loki1/boltdb-shipper-active
    cache_location: ./loki1/boltdb-shipper-cache
    shared_store: filesystem
  filesystem:
    directory: ./loki1/chunks
  index_queries_cache_config:
    enable_fifocache: true

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  chunk_cache_config:
    enable_fifocache: true
  write_dedupe_cache_config:
    enable_fifocache: true

ruler:
  external_url: http://localhost:3210/ruler
  storage:
    type: local
    local:
      directory: ./rules1
  rule_path: ./rules1
  ring:
    kvstore:
      store: memberlist
  enable_api: true
  enable_sharding: true
```

Instance2:
```
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3111
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9085

memberlist:
  node_name: node2
  randomize_node_name: false
  abort_if_cluster_join_fails: true
  join_members:
    - localhost:7946
    - localhost:7948
  bind_port: 7947

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist

schema_config:
  configs:
  - from: 2021-04-15
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: ./loki2/index
  boltdb_shipper:
    active_index_directory: ./loki2/boltdb-shipper-active
    cache_location: ./loki2/boltdb-shipper-cache
    shared_store: filesystem
  filesystem:
    directory: ./loki2/chunks
  index_queries_cache_config:
    enable_fifocache: true

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  chunk_cache_config:
    enable_fifocache: true
  write_dedupe_cache_config:
    enable_fifocache: true

ruler:
  external_url: http://localhost:3211/ruler
  storage:
    type: local
    local:
      directory: ./rules2
  rule_path: ./rules2
  ring:
    kvstore:
      store: memberlist
  enable_api: true
  enable_sharding: true
```

Instance 3:
```
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3112
  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9075

memberlist:
  node_name: node3
  randomize_node_name: false
  abort_if_cluster_join_fails: true
  join_members:
    - localhost:7946
    - localhost:7947
  bind_port: 7948

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist

schema_config:
  configs:
  - from: 2021-04-15
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: ./loki3/index
  boltdb_shipper:
    active_index_directory: ./loki3/boltdb-shipper-active
    cache_location: ./loki3/boltdb-shipper-cache
    shared_store: filesystem
  filesystem:
    directory: ./loki3/chunks
  index_queries_cache_config:
    enable_fifocache: true

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  chunk_cache_config:
    enable_fifocache: true
  write_dedupe_cache_config:
    enable_fifocache: true

ruler:
  external_url: http://localhost:3212/ruler
  storage:
    type: local
    local:
      directory: ./rules3
  rule_path: ./rules3
  ring:
    kvstore:
      store: memberlist
  enable_api: true
  enable_sharding: true
```

Thanks for your help!
