### ISSUE TITLE
Negative number of chunks in memory (loki_ingester_memory_chunks < 0)

### ISSUE THREAD

**Issue by klausenbusk** [grafana/loki#3622]
**Describe the bug**
Recently `loki_ingester_memory_chunks` dropped below zero:
![image](https://user-images.githubusercontent.com/1080056/115270967-23c32280-a13d-11eb-8ea2-a8025f436344.png)

**To Reproduce**
No idea, but around 00:00 we removed the `unit` label from Promtail's `journal` scrap config, as it created a crazy amount of chunks.

**Expected behavior**
`loki_ingester_memory_chunks` should never drop below zero.

**Environment:**
 - Infrastructure: Running on a single VM in *single process mode*
 - Deployment tool: Installed from the Arch Linux package registry: https://archlinux.org/packages/community/x86_64/loki/
 - Version: v2.2.1

**Screenshots, Promtail config, or terminal output**
loki.yaml
```yaml
# Enables authentication through the X-Scope-OrgID header, which must be present
# if true. If false, the OrgID will always be set to "fake".
auth_enabled: false

server:
  http_listen_address: 127.0.0.1
  http_listen_port: 3100
  grpc_listen_address: 127.0.0.1
  grpc_listen_port: 9095

ingester:
  wal:
    enabled: true
    dir: /var/lib/loki/wal
    replay_memory_ceiling: 200MB
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 10h          # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1536000  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
#  chunk_encoding: zstd
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /var/lib/loki/boltdb-shipper-active
    cache_location: /var/lib/loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /var/lib/loki/chunks

compactor:
  working_directory: /var/lib/loki/boltdb-shipper-compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 672h

table_manager:
  retention_deletes_enabled: true
  retention_period: 672h  # 28 days
```
promtail.yaml
```yaml
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080
  grpc_listen_address: 127.0.0.1
  grpc_listen_port: 0 # 0 means random

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: https://logging.archlinux.org/loki/api/v1/push
    basic_auth:
      username: 'arch_loki'
      password: 'ex1ose2Pe0eik4Eibaewuoch2pheiphi'

scrape_configs:
  - job_name: journal
    journal:
      json: true
      max_age: 72h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ["__journal__hostname"]
        target_label: instance
  - job_name: nginx
    static_configs:
      - targets:
        - localhost
        labels:
          job: nginx
          instance: monitoring.archlinux.org
          __path__: /var/log/nginx/*/*.json
    pipeline_stages:
    - match:
        selector: '{job="nginx"}'
        stages:
        - json:
            expressions:
              time_local: time_local
        - timestamp:
            format: 02/Jan/2006:15:04:05 -0700
            source: time_local
```
