### ISSUE TITLE
Promtail --config.expand-env=true parameter breaks Promtail configuration if references to regex capture groups exist

### ISSUE THREAD

**Issue by sergeykranga** [grafana/loki#3635]
**Describe the bug**
References to capture groups (`$1` or `${1}`) in Promtail stage configurations (for example, template with `regexReplaceAll`) are treated as environment variables when `--config.expand-env=true` Promtail parameter is used. This breaks the stage configurations, and Promtail fails to start because of invalid syntax.

**To Reproduce**
1. Given this json log file
```
{"hostname": "host-10-1-2-3.prod.example.com"}
```
2. Intention is to remove `.prod.example.com` from `hostname` value. Here is a corresponding Promtail configuration: 
```
server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

client:
  url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: test-job
    pipeline_stages:
    - json:
        expressions:
          hostname: hostname
    - template:
        source: hostname
        template: '{{ regexReplaceAll "(.*?)\\.(.*)" .Value "$1" }}'
    static_configs:
    - targets:
        - localhost
      labels:
        __path__: /tmp/json.log
```
3. Run in dry run mode
```
$ cat json.log | promtail --stdin --dry-run --config.file promtail.yaml --config.expand-env=true
Clients configured:
----------------------
url: http://localhost:3100/loki/api/v1/push
batchwait: 1s
batchsize: 1048576
backoff_config:
  min_period: 500ms
  max_period: 5m0s
  max_retries: 10
timeout: 10s
tenant_id: ""

level=error ts=2021-04-21T12:15:49.822312Z caller=main.go:106 msg="error creating promtail" error="invalid template stage config: template: pipeline_template:1: invalid syntax"
```

**Expected behavior**
The template syntax is valid in this case, and this can be confirmed by running the same command but without passing the `--config.expand-env=true`:
```
$ cat json.log | promtail --stdin --dry-run --config.file promtail.yaml
Clients configured:
----------------------
url: http://localhost:3100/loki/api/v1/push
batchwait: 1s
batchsize: 1048576
backoff_config:
  min_period: 500ms
  max_period: 5m0s
  max_retries: 10
timeout: 10s
tenant_id: ""

level=info ts=2021-04-21T12:14:43.518236Z caller=server.go:225 http=[::]:9080 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-04-21T12:14:43.518533Z caller=main.go:110 msg="Starting Promtail" version="(version=, branch=, revision=)"
2021-04-21T15:14:43	{__path__="/tmp/json.log"}	{"hostname": "host-10-1-2-3.prod.example.com"}
```

**Environment:**
 - Infrastructure: none is required to reproduce
 - Deployment tool: none is required to reproduce
