### ISSUE TITLE
promtail journal batches sends "entry out of order"

### ISSUE THREAD

**Issue by EirikAskheim** [grafana/loki#3666]
**Describe the bug**
I'm running promtail as a daemonset on OpenShift. We are logging to journald, so I'm using the journal promtail scraper. Each entry is labeled with the hostname of the OpenShift node and I only run one replica of promtail on each node. I'm assuming that promtail is sending the batches in reverse order, so Loki processes the latest event first and discards all other entries in the batch.

I can see that in some instances Loki processes two events in the batch and I think this might be when the timestamp of the two latest events in the batch are identical.

**To Reproduce**
1. Started Loki 2.2.1
2. Started Promtail 2.2.1 with journal scraper
3. Check promtail or Loki logs for "entry out of order"

**Expected behavior**
Entries in order ingested perfectly.

**Environment:**
- Single Loki instance running on bare metal.
- Promtail running as daemonset on openshift. OpenShift nodes running RHEL 7.9.

**Screenshots, Promtail config, or terminal output**

## Promtail configuration
```
client:
  backoff_config:
    max_period: 5m
    max_retries: 10
    min_period: 500ms
  batchsize: 1048576
  batchwait: 1s
  external_labels: {}
  timeout: 10s
positions:
  filename: /run/promtail/positions.yaml
server:
  http_listen_port: 3101
clients:
- url: http://loki01:3100/loki/api/v1/push
target_config:
  sync_period: 10s
scrape_configs:
- job_name: journal
  journal:
    json: false
    max_age: 12h
    path: /var/log/journal
    labels:
      job: systemd-journal
  relabel_configs:
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'
    - source_labels: ['__journal_container_name']
      regex: ^([^_]+)_([^\._]+)(\.([^_]+))?_([^_]+)_([^_]+)_[^_]+_[^_]+$
      target_label: 'namespace'
      replacement: '${6}'
    - source_labels: ['__journal_container_name']
      regex: ^([^_]+)_([^\._]+)(\.([^_]+))?_([^_]+)_([^_]+)_[^_]+_[^_]+$
      target_label: 'instance'
      replacement: '${5}'
    - source_labels: ['__journal_container_name']
      regex: ^([^_]+)_([^\._]+)(\.([^_]+))?_([^_]+)_([^_]+)_[^_]+_[^_]+$
      target_label: 'container_name'
      replacement: '${2}'
    - source_labels: ['__journal__hostname']
      target_label: 'hostname'
```

## Error message (added some line breaks for readability)
```
april 29 10:13:59 loki01 loki-linux-amd64[1275]: level=warn ts=2021-04-29T08:13:59.215376772Z caller=grpc_logging.go:38 method=/logproto.Pusher/Push duration=1.219084ms err="rpc error: code = Code(400) desc =

entry with timestamp 2021-04-29 08:06:37.426342 +0000 UTC ignored, reason: 'entry out of order' for stream: {container_name=\"promtail\", hostname=\"oso-node15\", instance=\"loki-promtail-z1t4d\", job=\"systemd-journal\", namespace=\"loki\", unit=\"docker.service\"},

entry with timestamp 2021-04-29 08:06:38.529434 +0000 UTC ignored, reason: 'entry out of order' for stream: {container_name=\"promtail\", hostname=\"oso-node15\", instance=\"loki-promtail-z1t4d\", job=\"systemd-journal\", namespace=\"loki\", unit=\"docker.service\"},

entry with timestamp 2021-04-29 08:06:39.62856 +0000 UTC ignored, reason: 'entry out of order' for stream: {container_name=\"promtail\", hostname=\"oso-node15\", instance=\"loki-promtail-z1t4d\", job=\"systemd-journal\", namespace=\"loki\", unit=\"docker.service\"},
total ignored: 3 out of 4" msg="gRPC
```

## Number of ignored events
```
# journalctl -n 0 -u loki -f | grep -oE 'total ignored[^"]+'
total ignored: 332 out of 334
total ignored: 4 out of 5
total ignored: 132 out of 134
total ignored: 3 out of 4
total ignored: 1 out of 2
total ignored: 6 out of 7
total ignored: 3 out of 4
total ignored: 387 out of 389
total ignored: 1 out of 2
total ignored: 1 out of 2
total ignored: 298 out of 300
total ignored: 214 out of 215
total ignored: 1 out of 2
total ignored: 421 out of 423
total ignored: 79 out of 80
total ignored: 1 out of 2
total ignored: 8 out of 9
total ignored: 1 out of 1
total ignored: 33 out of 35
total ignored: 19 out of 20
total ignored: 89 out of 92
total ignored: 1 out of 1
```
