### ISSUE TITLE
Promtail only binding to ipv6

### ISSUE THREAD

**Issue by regner** [grafana/loki#3684]
**Describe the bug**
It seems like this is happening with all servers binding to an address within the Promtail client.

Specifically in my case I have specified the syslog listen_address as 0.0.0.0:1514 and left the http_listen_address attribute as the default. I would expect that when using 0.0.0.0 that the syslog server would bind to all ipv4 addresses. However it is binding to the ipv6 address.

**To Reproduce**
1. `[root@loki ~]# /usr/local/bin/promtail -config.file=/etc/promtail/promtail.yml -log.level=info`

**Expected behavior**
I expect all the servers being created to listen and bind to ports on the ipv4 addresses.

**Environment:**
 - Virtual Machine
 - Not deployed with Docker, just the executable
 - CentOS 8

**Screenshots, Promtail config, or terminal output**
```bash
[root@loki ~]# /usr/local/bin/promtail -config.file=/etc/promtail/promtail.yml -log.level=info
level=info ts=2021-05-04T18:25:48.619641667Z caller=syslogtarget.go:93 msg="syslog listening on address" address=[::]:1514
level=info ts=2021-05-04T18:25:48.619827571Z caller=server.go:229 http=[::]:9080 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-05-04T18:25:48.619969975Z caller=main.go:112 msg="Starting Promtail" version="(version=2.2.1, branch=HEAD, revision=babea82e)"
```

```bash
[root@loki ~]# netstat -anlp | grep promtail
tcp        0      0 10.1.32.33:58656        10.1.32.10:443          ESTABLISHED 54242/promtail
tcp6       0      0 :::9095                 :::*                    LISTEN      54242/promtail
tcp6       0      0 :::1514                 :::*                    LISTEN      54242/promtail
tcp6       0      0 :::9080                 :::*                    LISTEN      54242/promtail
unix  2      [ ]         DGRAM                    1091767  54242/promtail       @00027
unix  3      [ ]         STREAM     CONNECTED     1088457  54242/promtail
```

```yaml
server:
  http_listen_port: 9080


positions:
  filename: /var/lib/promtail/positions.yml


clients:
  - external_labels:
      host: vm-t1-loki
    url: https://loki.owidev.net/loki/api/v1/push


scrape_configs:
  - file_sd_configs:
    - files:
      - /etc/promtail/file_sd/*.yml
      - /etc/promtail/file_sd/*.yaml
      - /etc/promtail/file_sd/*.json
    job_name: file_sd

  - job_name: journal
    journal:
      labels:
        job: systemd-journal
      max_age: 12h
      path: /var/log/journal
    relabel_configs:
    - source_labels:
      - __journal__systemd_unit
      target_label: unit

  - job_name: "syslog"
    syslog:
      listen_address: "0.0.0.0:1514"
      labels:
        job: "syslog"
    relabel_configs:
      - target_label: "host"
        source_labels:
          - "__syslog_message_hostname"
```

**Comment by regner** [comment]
Based on some quick research into the codebase it seems both the syslog and http servers are calling `net.Listen("tcp", <some_var_for_address>)`.

In the case of syslog that is here: https://github.com/grafana/loki/blob/main/clients/pkg/promtail/targets/syslog/syslogtarget.go#L89

In the case of the http server that is here: https://github.com/weaveworks/common/blob/master/server/server.go#L162

So it doesn't seem like it is an issue specifically with Promtail, but rather my understanding of what the Golang standard lib expects or how it works.

The Golang docs for net don't go into much more detail: https://golang.org/pkg/net/#Listen

**Comment by regner** [comment]
I also confirmed nothing else was listening on those ports already:

```bash
[root@loki ~]# netstat -anlp | grep 9080
tcp6       0      0 :::9080                 :::*                    LISTEN      54270/promtail
[root@loki ~]# netstat -anlp | grep 1514
tcp6       0      0 :::1514                 :::*                    LISTEN      54270/promtail
```

**Comment by 3Xpl0it3r** [comment]
In fact this is have nothing about Promtail, Promtail use weavescope/common library to build http server .I have summit  a pr for that http server can bind tcpv4,if weavescope team think is necessary.

**Comment by danoost** [comment]
Hey @regner, did you ever solve this? This issue still seems to be present in the most recent v2.4.2, and means I can't stand up a functioning syslog-ng link. I can replicate your logs and netstat results with a very similar config running within Docker:
```yaml
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
```

I also get the following log message when the syslog-ng connection times out:
```
level=warn ts=2022-02-03T03:02:40.746488768Z caller=syslogtarget.go:206 msg="error initializing syslog stream" err="read tcp 172.30.0.2:1514->172.30.0.3:45795: i/o timeout"
```
and this one on the syslog side:
```
[2022-02-03T02:59:36.694466] Syslog connection established; fd='14', server='AF_INET6([::ffff:172.30.0.2]:1514)', local='AF_INET6([::]:0)'
[2022-02-03T02:59:36.694759] EOF on control channel, closing connection;
[2022-02-03T03:00:36.696071] EOF occurred while idle; fd='14'
```
