### ISSUE TITLE
Authentication error with s3 and irsa

### ISSUE THREAD

**Issue by cebidhem** [grafana/loki#3718]
**Describe the bug**
When starting Loki with a s3 storage and permission granted via IRSA, I get the following messages in logs:
```
level=error ts=2021-05-12T14:22:26.123689666Z caller=compactor.go:83 msg="failed to run compaction" err="AccessDenied: Access Denied\n\tstatus code: 403, request id: 4668X6ZVNE5AK5TK, host id: ww3eaV1A9pkWLbCA28J0cV5ycgYyAZVdjGRzP14IfSd/WfqbckuO5x8ClS7DNBPdJKF0B7LCGvc="
level=error ts=2021-05-12T14:22:26.125136684Z caller=table_manager.go:218 msg="error syncing tables" err="AccessDenied: Access Denied\n\tstatus code: 403, request id: 4669JTFQPV2H4BTD, host id: 4w2ZoYZp8RVChUczOOh9ykinPZiKK2ozjm42aPW8dlFbkP56GO9NFwQVYFyKjZFT3m6Q5VqS37w="
```
I know the docs are not cleared, so I tried different config based on issues reported here and on stackoverflow, for instance swapping `aws` and `s3` for the `shared_store` properties, but still got the same error.

And of course, when trying to add Loki as Grafana datasource, the messages also appear.

The strange part, is that I can see some objects being written in the bucket, so the issue seem to be located with bolt / compactor:

```
aws s3 ls s3://mybucket/
                           PRE fake/
                           PRE index/
aws s3 ls s3://mybucket/index/
                           PRE index_18752/
                           PRE index_18753/
                           PRE index_18754/
                           PRE index_18755/
                           PRE index_18756/
                           PRE index_18757/
                           PRE index_18758/
                           PRE index_18759/
aws s3 ls s3://mybucket/index/index_18758/
2021-05-12 14:33:07    1106099 loki-stack-0-1620816543843800179-1620816633.gz
2021-05-12 14:33:07      58766 loki-stack-0-1620816543843800179-1620817200.gz
```

**Expected behavior**
S3 bucket with IRSA should just work.

**Environment:**
 - Infrastructure: kubernetes EKS 1.19
 - Deployment tool: helm / flux2

**Screenshots, Promtail config, or terminal output**
Loki configuration loki.yaml. `cat /etc/loki/loki.yaml`
```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
compactor:
  shared_store: aws
  working_directory: /data/loki/boltdb-shipper-compactor
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
  - from: "2020-10-24"
    index:
      period: 24h
      prefix: index_
    object_store: aws
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
storage_config:
  aws:
    s3: s3://eu-west-1/mybucket
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: s3
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s/
```

The `loki-stack` service account:
```
k get sa loki-stack -oyaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::MYACCOUNT:role/my-role-for-loki
    meta.helm.sh/release-name: loki-stack
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2021-05-12T10:48:59Z"
  labels:
    app: loki
    app.kubernetes.io/managed-by: Helm
    chart: loki-2.5.0
    helm.toolkit.fluxcd.io/name: loki-stack
    helm.toolkit.fluxcd.io/namespace: monitoring
    heritage: Helm
    release: loki-stack
  name: loki-stack
  namespace: monitoring
  resourceVersion: "1528542924"
  selfLink: /api/v1/namespaces/monitoring/serviceaccounts/loki-stack
  uid: 77fce941-7a65-4aef-87e9-cf4e6c375205
secrets:
- name: loki-stack-token-hh8mr
```

In AWS, I have the following policy attached to the role `arn:aws:iam::MYACCOUNT:role/my-role-for-loki`:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:ListAllMyBuckets",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/*",
                "arn:aws:s3:::mybucket"
            ]
        }
    ]
}
```
And the Trust Relationship is well set:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::MYACCOUNT:oidc-provider/oidc.eks.eu-west-1.amazonaws.com/id/MYHEXACLUSTER"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.eu-west-1.amazonaws.com/id/MYHEXACLUSTER:sub": "system:serviceaccount:monitoring:loki-stack"
        }
      }
    }
  ]
}
```

Anything you would see in my configuration that makes it fail ?

Thanks for the support.

Edit:

I tried to enable all the verbs on s3 with the following policy, and I don't see any error messages anymore:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::mybucket/*",
                "arn:aws:s3:::mybucket"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "*"
        }
    ]
}
```
So I'm assuming at least a permission is missing in the docs but can't yet tell which one.
