### ISSUE TITLE
grpc_client_config + documentation

### ISSUE THREAD

**Issue by strowi** [grafana/loki#3719]
**Describe the bug**
Documentation (https://grafana.com/docs/loki/latest/configuration/#grpc_client_config) show grpc_client_config beneath limits_config, but configuring the loki-distributed helm chart throws errors.

This seems to be needed since grafana/explore/loki complains about :+1: 
```
response larger than the max (18449292 vs 16777216)
```

**To Reproduce**
1. started Loki-distributed helm-chart:
```
apiVersion: v2
appVersion: 2.2.0
version: 0.28.0
```
2. set max_send_msg_size as shown in the docs:
```
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 1h
      max_entries_limit_per_query: 1000000
      grpc_client_config:
        max_send_msg_size: 32777216
```
3. see error in ingester:
```
ci-loki-loki-distributed-ingester-1
[ci-loki-loki-distributed-ingester-1] failed parsing config: /etc/loki/config/config.yaml: yaml: unmarshal errors: 
[ci-loki-loki-distributed-ingester-1]   line 40: field grpc_client_config not found in type validation.plain 
```

**Expected behavior**
config being applied.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

regards,
strowi

**Comment by while1eq1** [comment]
I am experiencing the same issue

**Comment by wondersd** [comment]
I also ran into this (looks like the same limit referenced above):

from fluentd attempting to push to loki (v1.6.0)

```
 error_class=Fluent::Plugin::LokiOutput::LogPostError error="500 Internal Server Error rpc error: code = ResourceExhausted desc = trying to send message larger than max (17310905 vs. 16777216)
 ```
 
 After some digging and trial and error, the correct placement in this case for `grpc_client_config` was:
 
 ```
 ingester_client:
   grpc_client_config:
     max_send_msg_size: 33554432
 ```
 
 The docs do not appear to match how the configs are laid out, https://grafana.com/docs/loki/v1.6.0/configuration/#ingester_config

**Comment by haim-ari** [comment]
> I also ran into this (looks like the same limit referenced above):
> 
> from fluentd attempting to push to loki (v1.6.0)
> 
> ```
>  error_class=Fluent::Plugin::LokiOutput::LogPostError error="500 Internal Server Error rpc error: code = ResourceExhausted desc = trying to send message larger than max (17310905 vs. 16777216)
> ```
> 
> After some digging and trial and error, the correct placement in this case for `grpc_client_config` was:
> 
> ```
> ingester_client:
>   grpc_client_config:
>     max_send_msg_size: 33554432
> ```
> 
> The docs do not appear to match how the configs are laid out, https://grafana.com/docs/loki/v1.6.0/configuration/#ingester_config

I tried the following and I still get the same error with same limit (which is mentioned as default value at the docs) after updating the config and restarting rollouts. 

```yaml
---
piVersion: v1
kind: Secret
metadata:
  name: loki-secret
  namespace: loki-stack
type: Opaque
stringData:
  config.yaml: |
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 0s
    compactor:
      compaction_interval: 5m
      shared_store: aws
    distributor:
      ring:
        kvstore:
          store: memberlist
    frontend:
      compress_responses: true
      log_queries_longer_than: 5s
    frontend_worker:
      frontend_address: "loki-loki-distributed-query-frontend:9095"
    ingester:
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_idle_period: 30m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
    ingester_client:
      grpc_client_config:
        max_send_msg_size: 33554432
    limits_config:
      max_entries_limit_per_query: 1000
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    memberlist:
      join_members:
        - loki-loki-distributed-memberlist
    query_range:
      align_queries_with_step: true
      cache_results: true
      max_retries: 5
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h
      split_queries_by_interval: 15m
    schema_config:
      configs:
        -
          from: 2021-04-10
          index:
            period: 24h
            prefix: loki_index_
          object_store: s3
          schema: v11
          store: boltdb-shipper
    server:
      grpc_server_max_recv_msg_size: 15728640
      grpc_server_max_send_msg_size: 15728640
      http_listen_port: 3100
    storage_config:
      aws:
        s3:
```

![image](https://user-images.githubusercontent.com/4179195/127140959-65f0b06c-6e9e-4a10-bbd5-df2c8d42ebc6.png)
