### ISSUE TITLE
Ingester memory leak

### ISSUE THREAD

**Issue by annymsMthd** [grafana/loki#3728]
Loki version 2.2.1, distributed chart

**Describe the bug**
We have a loki cluster storing the logs for 30-40 kubernetes clusters. After running for a bit the ingesters will start to build up the `cortex_ingester_flush_queue_length` and eventually go OOM. This seems to happen out of the blue after running for a few hours. It looks like something in the flush process is getting blocked

**To Reproduce**
no steps yet

**Expected behavior**
No blockages in the flush.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/325749/118373575-8953d480-b56c-11eb-98e4-24df2a1e8938.png">
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/325749/118373809-8f968080-b56d-11eb-8da6-dbf31950b497.png">

```yaml
auth_enabled: false
server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 8000000000
  grpc_server_max_send_msg_size: 8000000000
  log_level: warn
distributor:
  ring:
    kvstore:
      store: memberlist
memberlist:
  join_members:
    - loki-memberlist
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 2
  chunk_idle_period: 1h
  chunk_block_size: 512000
  chunk_encoding: snappy
  chunk_retain_period: 5s
  max_transfer_retries: 0
  max_chunk_age: 20m
  concurrent_flushes: 100
  flush_op_timeout: 1m
ingester_client:
  remote_timeout: 1m
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m
  ingestion_rate_mb: 4000000
  ingestion_burst_size_mb: 4000000
  max_entries_limit_per_query: 10000
  max_streams_per_user: 0
schema_config:
  configs:
    - from: 2020-09-07
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_
        period: 24h
storage_config:
  boltdb_shipper:
    shared_store: aws
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    cache_ttl: 168h
  aws:
    s3: s3://**
    insecure: false
    sse_encryption: true
    s3forcepathstyle: true
chunk_store_config:
  max_look_back_period: 0s
  chunk_cache_config:
    enable_fifocache: false
query_range:
  align_queries_with_step: true
  max_retries: 5
  split_queries_by_interval: 1h
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_bytes: 2GB
        validity: 24h
frontend_worker:
  frontend_address: loki-query-frontend:9095
frontend:
  log_queries_longer_than: 5s
  compress_responses: true
querier:
  query_timeout: 10m
  engine:
    timeout: 10m
compactor:
  shared_store: s3
ruler:
  storage:
    type: local
    local:
      directory: /etc/loki/rules
  ring:
    kvstore:
      store: memberlist
  rule_path: /tmp/loki/scratch
  alertmanager_url: https://alertmanager.xx
  external_url: https://alertmanager.xx
tracing:
  enabled: false
```
