### ISSUE TITLE
How to read logs from S3 stored by Loki?

### ISSUE THREAD

**Issue by MarjanJordanovski** [grafana/loki#3730]
I have following config:
```
schema_config:
      configs:
        - from: 2020-09-07
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
```

   ```
 storage_config:
      aws:
        s3: s3://<key>:<secKey>@<region>/<bucketName>
      boltdb_shipper:
        active_index_directory: /var/loki/index
        shared_store: s3
        cache_location: /var/loki/cache
```

And I see fake and index folders are created in s3. But when I try to download any of the files that appeared in those folders, they are in .file format and unreadable. (tried to rename them to .txt but no luck)
So how can I read logs stored in s3 by Loki? 
Also when I query logs from loki in grafana, am I seeing basically those logs from s3 or am I seeing locally stored logs by loki?

**Comment by sandstrom** [comment]
Fake is a confusing name, but that's actually legit data.

See https://github.com/grafana/loki/issues/3363

**Comment by rifler** [comment]
@sandstrom Could you please provide the example?

I suspect initial question from @MarjanJordanovski  was about reading "old" data from s3 storage (older than `retention_period`). For instance:
```
# download binary data from s3
aws s3 sync s3://loki-bucket ./temp

# somehow force logcli to work with just downloaded files from s3
logcli query '{service="my-service"} |= ``'
```

**Comment by rifler** [comment]
related issue doesn't seem related to initial question

**Comment by sandstrom** [comment]
OP wrote "And I see fake and index folders are created in s3", so I just mentioned that 'fake' is a confusing name for the folder, but that the data contained in it is real data.

I wasn't trying to solve OPs question, just wanted to help something I find confusing (the directory naming).

**Comment by BJWRD** [comment]
Has anyone got the answer to this please? I'm equally as confused on how to make the Loki S3 log files readable.

**Comment by alpkahvecioglu** [comment]
I am also trying to understand how we can store logs using Loki and use them for audit purposes? Also, what would happen if we want to ditch Loki in the future but still want to access old log data?

**Comment by rdurelli** [comment]
I'm also facing challenges with this. How can I effectively read logs from S3? Any assistance would be greatly appreciated! :D

**Comment by alpkahvecioglu** [comment]
Yes but what if I want to audit these logs or share them with a third-party to audit them. From what I can see there is no way for someone to do so without using Loki even if they are using the S3 backend?

**Comment by srjithsn** [comment]
I am also looking for such an option to read logs outside loki. In my scenario, I am trying to move the loki chunks in s3 standard storage to Glacier for long term storage and archival. If I need some logs to be restored is there an option available? the chunk files are not human readable.  Is there a tool which can help me read the files if I download it from Glacier?

**Comment by bboreham** [comment]
You can now use `logcli query --store-config=<file.yaml>` to query from an S3 bucket.
`<file.yaml>` denotes a Loki storage / schema configuration [like this](https://grafana.com/docs/loki/latest/configure/storage/#aws-deployment-s3-single-store).

**Comment by pmakow** [comment]
Hi @bboreham could you please share an example of working config file? The one from the link doesn't work as logcli is expecting cache settings. I tried multiple configurations but without luck.

**Comment by bboreham** [comment]
You don’t have one from an existing Loki?

This is one I used, redacted.  

```
storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
  aws:
    s3: s3://redacted
    bucketnames: redacted
    region: eu-south-2

compactor:
  working_directory: /tmp/loki

query_range:
  cache_index_stats_results: false

schema_config:
  configs:
    - from: "2024-06-07"
      index:
        period: 24h
        prefix: redacted
      object_store: s3
      schema: v13
      store: tsdb
```
