### ISSUE TITLE
Error restarting Loki

### ISSUE THREAD

**Issue by jt-helsinki** [grafana/loki#3734]
**Describe the bug**
When starting Loki for the first time it starts as expected. When bringing down the cluster and bringing it up again Loki generate the following logs:

```
level=info ts=2021-05-17T13:27:16.819787428Z caller=main.go:130 msg="Starting Loki" version="(version=2.2.1, branch=HEAD, revision=babea82ef)"

level=info ts=2021-05-17T13:27:16.820198826Z caller=server.go:229 http=[::]:3100 grpc=[::]:9096 msg="server listening on addresses"

level=info ts=2021-05-17T13:27:16.827425992Z caller=table_manager.go:241 msg="loading table index_18759"

level=error ts=2021-05-17T13:27:16.833038295Z caller=log.go:106 msg="error running loki" err="invalid argument\nerror creating index client\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewStore\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:179\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:319\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:103\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nerror initialising module: store\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"
```

**To Reproduce**
1. Install Loki using the following stateful set:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-service
  namespace: logging
  labels:
    app: loki-service
spec:
  serviceName: loki-service
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: loki-service
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loki-service
      annotations:
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"

    spec:
      serviceAccountName: loki-service-service-account
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 0
      containers:
      - name: loki-service
        image: grafana/loki:2.2.1
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - name: http
          containerPort: 3100
          protocol: TCP
        args: ["-config.file=/etc/loki/loki-config.yaml"]
        livenessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 45
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 45
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki
          readOnly: true
        - name: loki-service-volume-mount
          mountPath: /srv/loki/data
          readOnly: false
      volumes:
      - name: loki-config
        configMap:
          name: loki-service-configmap
      - name: loki-service-volume-mount
        persistentVolumeClaim:
          claimName: loki-service-pvc

```

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-service-configmap
  namespace: logging
  labels:
    app: loki-service
data:
  loki-config.yaml:  |-
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    ingester:
      wal:
        enabled: true
        dir: /srv/loki/data/wal
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
      max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
      chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
      chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
      max_transfer_retries: 0     # Chunk transfers disabled

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /srv/loki/data/loki/boltdb-shipper-active
        cache_location: /srv/loki/data/loki/boltdb-shipper-cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: filesystem
      filesystem:
        directory: /srv/loki/data/loki/chunks

    compactor:
      working_directory: /srv/loki/data/loki/boltdb-shipper-compactor
      shared_store: filesystem

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s

    ruler:
      storage:
        type: local
        local:
          directory: /srv/loki/data/loki/rules
      rule_path: /srv/loki/data/loki/rules-temp
      alertmanager_url: http://localhost:9093
      ring:
        kvstore:
          store: inmemory
      enable_api: true
```

**Expected behavior**
Clean startup with no errors

**Environment:**
 - Kubernetes 1.21
 - Helm V3
 - Minkube with VirtualBox 

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
