### ISSUE TITLE
Loki Canary failed to parse timestamp

### ISSUE THREAD

**Issue by jb-contino** [grafana/loki#3751]
**Describe the bug**
Deployed Loki Canary but unable to get it to validate the logs it retrieves from Loki. Errors show it's failing to parse timestamp from log content.

**To Reproduce**
1. Deployed Loki, Promtail and Loki-Canary (v2.2.0) from Helm charts
2. Loki & Promtail working as expected
3. Added promtail config to add `stream` label to canary logs - otherwise hit other errors
4. Canary logs show constant stream of parsing errors: e.g. 
`2021-05-20 17:20:16 | {"log":"failed to parse timestamp: {\"log\":\"1621527535345064148","stream":"stderr","time":"2021-05-20T16:20:16.357343147Z"}`

**Expected behavior**
Loki Canary would be able to parse the response it gets back w/out error

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
stderr logs from canary pods:
`{"log":"websocket missing entry: 1621527535345064148","stream":"stderr","time":"2021-05-20T16:20:16.35767003Z"}
{"log":"failed to parse timestamp: {\"log\":\"1621527535345064148","stream":"stderr","time":"2021-05-20T16:20:16.357343147Z"}`

** loki canary runtime args:**
```
Args:                                                                                                                                                                                   │
  -addr=loki-distributed-gateway:80                                                                                                                                                     │
  -labelname=pod                                                                                                                                                                        │
  -labelvalue=$(POD_NAME)
```

Initially the err msg showed the log field had a trailing `\n` - tried removing that via promtail, but had no impact - same error (although \n was removed)

**Comment by jb-contino** [comment]
Managed to figure this out so closing the issue. Running loki-canary & promtail locally (rather than within k8s with the default promtail config that ships with the loki-desitributed helm chart) made it clear that the issue was that the cri pipeline stage was serialising the data, but canary expects it in raw format. 

So in case it helps anyone else, the steps I had to take to get canary working with the default promtail config as per the helm chart (v2.2.0) were as follows:

- Add `stream` label to canary logs
- refactor output

my promtail values which worked were as follows:
```
config:
    snippets:
      pipelineStages:
        - cri: {}
        - match:
            selector: '{pod=~"loki-distributed-loki-canary-.*" }'
            action: keep
            stages:
            - json:
                expressions:
                  stream: stream
                  log: log
            - labels:
                stream:
            - template:
                source: rewrite_output
                template: '{{ .log }}'
            - output:
                source: rewrite_output
...
```
