### ISSUE TITLE
[loki distributed] slow query (high cpu usage) and time out

### ISSUE THREAD

**Issue by StefanSa** [grafana/loki#3753]
**Describe the bug**
With a time window of more than an hour, we get a timeout on the query. Small time windows for a query are also not really fast, `last 30min = 4min. query time` and `last 15min = 1min. query time`.
In addition, during the queries, especially with the larger time windows, we see a `high cpu load` between `200% - 300%` per node.

**To Reproduce**
1. Started Loki (SHA or version): 2.2.1
2. Started Promtail (SHA or version) to tail '...': 2.2.1
3. Query: 
```
sum by (host) (sum_over_time({event_action="firewall",host="fwgate-1.test.local"} | json | unwrap estination_bytes |  __error__="" [$__interval]))
```

**Expected behavior**
Acceptable reaction time, the aim should be to replace the existing ELK stack.

**Environment:**
 - Infrastructure: rke 2.5.8
 - Deployment tool: helm
 - 3 nodes, 16Core, 142Gib RAM

**Screenshots, Promtail config, or terminal output**
loki deployment:
```
compactor:
  enabled: true
ingester:
  replicas: 3
distributor:
  replicas: 3
querier:
  replicas: 3
queryFrontend:
  replicas: 3
loki:
  config: |
    auth_enabled: false

    server:
      log_level: info
      # Must be set to 3100
      http_listen_port: 3100

    distributor:
      ring:
        kvstore:
          store: memberlist

    ingester:
      # Disable chunk transfer which is not possible with statefulsets
      # and unnecessary for boltdb-shipper
      max_transfer_retries: 0
      chunk_idle_period: 1h
      chunk_target_size: 2621440
      max_chunk_age: 1h
      lifecycler:
        join_after: 0s
        ring:
          kvstore:
            store: memberlist

    memberlist:
          join_members:
        - {{ include "loki.fullname" . }}-memberlist

    limits_config:
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_concurrent_tail_requests: 20
      max_cache_freshness_per_query: 10m

    schema_config:
      configs:
        - from: 2020-09-07
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      aws:
        s3: s3://loki:+tdu88EM@minio.minio-tenant-1.svc.cluster.local/loki
        s3forcepathstyle: true
      boltdb_shipper:
        active_index_directory: /var/loki/index
        shared_store: s3
        cache_location: /var/loki/cache

    chunk_store_config:
      max_look_back_period: 672h

    table_manager:
      retention_deletes_enabled: true
      retention_period: 672h

    query_range:
      # make queries more cache-able by aligning them with their step intervals
            align_queries_with_step: true
      max_retries: 5
      # parallelize queries in 15min intervals
      split_queries_by_interval: 15m
      cache_results: true

      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h

    frontend_worker:
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
    compactor:
      shared_store: s3
``` 
json logfile:
```
{"client.port":45356,"sophos.xg.fw.source.mac":"00:00:00:00:00:00","event.code":"010101600001","observer.hostname":"xg230","event.severity":"6","sophos.xg.fw.state.traffic":"Allow","sophos.fw.xg.destination.nat.port":0,"source.nat.ip":"0.0.0.0","sophos.xg.fw.destination.interface":"Port2","source.nat.port":0,"server.bytes":289,"destination.nat.port":0,"sophos.xg.fw.connection_id":"1067493528","sophos.xg.fw.appresolved_by":"Signature","event.end":"2021-05-20T21:19:27.000Z","sophos.xg.network.ip.fingerprint":"02eca7c5f2f471a0e2f0d0ad1df07cfd462c06fe","client.packets":5,"destination.port":10050,"client.ip":"160.16.34.55","sophos.xg.fw.source.nat.port":0,"event.duration":10000000000,"server.packets":5,"destination.packets":5,"log.level":"informational","source.mac":"00:00:00:00:00:00","@timestamp":"2021-05-20T21:19:27.000Z","event.timezone":"+02:00","observer.serial_number":"xxxxxxxxxx","event.outcome":"allowed","source.address":"160.16.34.55","event.category":"firewall rule","sophos.xg.fw.fw_id":"56","source.packets":5,"sophos.xg.fw.connection_event":"Stop","sophos.xg.fw.application_is_cloud":"0","hostsn":"fwgate-1.test.local","destination.bytes":306,"sophos.xg.fw.application_risk":"0","sophos.xg.fw.destination.zone":"VPN","sophos.xg.fw.ips_policy_id":"0","sophos.xg.fw.heartbeat_health":"No Heartbeat","source.bytes":289,"related.ip":["160.16.34.55","160.17.34.65","0.0.0.0","0.0.0.0"],"client.bytes":306,"destination.nat.ip":"0.0.0.0","sophos.xg.fw.source.interface":"Port1","sophos.xg.fw.policy_type":"1","@version":"1","event.action":"firewall","source.ip":"172.16.34.55","sophos.xg.fw.source.zone":"LAN","sophos.xg.fw.appfilter_policy_id":"0","network.transport":"tcp","event.start":"2021-05-20T21:19:17.000Z","server.port":10050,"server.ip":"160.17.34.65","sophos.xg.fw.iap":"0","destination.ip":"160.17.34.65","source.port":45356}
```
ingester log:
```
2021-05-20 20:56:59.339027839 +0000 UTC ignored, reason: 'entry out of order' for stream: {event_action=\"firewall\", host=\"fwgate-1.test.local\", job=\"syslog\"},\nentry with timestamp 2021-05-20 20:56:59.339079185 +0000 UTC ignored, reason: 'entry out of order' for stream: {event_action=\"firewall\", host=\"fwgate-1.test.local\", job=\"syslog\"},\nentry with timestamp 2021-05-20 20:56:59.339274763 +0000 UTC ignored, reason: 'entry out of order' for stream: {event_action=\"firewall\", host=\"fwgate-1.test.local\", job=\"syslog\"},\nentry with timestamp 

```
query-frontend log:
```
ts=2021-05-20T20:57:01.641462317Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-querier-2-352624b9 has failed, no acks received"
level=info ts=2021-05-20T21:05:14.962962142Z caller=metrics.go:91 org_id=fake traceID=7654706a1f0bf45c latency=slow query="sum by (host) (sum_over_time({event_action=\"firewall\",host=\"fwgate-1.test.local\"} | json | unwrap destination_bytes | __error__=\"\" [1s]))" query_type=metric range_type=range length=30m1s step=1s duration=34.048102602s status=200 limit=1470 returned_lines=0 throughput=166MB total_bytes=5.7GB
level=warn ts=2021-05-20T21:05:14.963086329Z caller=logging.go:60 traceID=7654706a1f0bf45c msg="GET /loki/api/v1/query_range?direction=BACKWARD&limit=1470&query=sum%20by%20(host)%20(sum_over_time(%7Bevent_action%3D%22firewall%22%2Chost%3D%22fwgate-1.test.local%22%7D%20%7C%20json%20%7C%20unwrap%20destination_bytes%20%7C%20%20__error__%3D%22%22%20%5B1s%5D))&start=1621542882000000000&end=1621544683000000000&step=1 34.055325877s, error: write tcp 10.42.4.100:3100->10.42.3.127:42494: i/o timeout ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: br, gzip, deflate; Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7; Connection: close; Sec-Ch-Ua: \" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\"; Sec-Ch-Ua-Mobile: ?0; Sec-Fetch-Dest: empty; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Agent: Grafana/7.5.6; X-Forwarded-For: 10.83.234.7, 16016.34.55, 16016.34.55; X-Grafana-Org-Id: 1; X-Real-Ip: 10.83.234.7; X-Request-Id: 2a061106a49d47b800bf3305374df05c; X-Scheme: https; "
ts=2021-05-20T21:11:39.764233238Z caller=spanlogger.go:79 org_id=fake traceID=18da0ebda7f0ff9e Ingester.TotalReached=6 Ingester.TotalChunksMatched=170 Ingester.TotalBatches=1796 Ingester.TotalLinesSent=918443 Ingester.HeadChunkBytes="0 B" Ingester.HeadChunkLines=0 Ingester.DecompressedBytes="1.7 GB" Ingester.DecompressedLines=918482 Ingester.CompressedBytes="103 MB" Ingester.TotalDuplicates=0 Store.TotalChunksRef=84 Store.TotalChunksDownloaded=84 Store.ChunksDownloadTime=2.030285868s Store.HeadChunkBytes="0 B" Store.HeadChunkLines=0 Store.DecompressedBytes="1.8 GB" Store.DecompressedLines=924176 Store.CompressedBytes="104 MB" Store.TotalDuplicates=1375331
ts=2021-05-20T21:11:39.764323226Z caller=spanlogger.go:79 org_id=fake traceID=18da0ebda7f0ff9e Summary.BytesProcessedPerSecond="171 MB" Summary.LinesProcessedPerSecond=90340 Summary.TotalBytesProcessed="3.5 GB" Summary.TotalLinesProcessed=1842658 Summary.ExecTime=20.39682666s
level=info ts=2021-05-20T21:11:39.768226907Z caller=handler.go:151 org_id=fake traceID=18da0ebda7f0ff9e msg="slow query detected" method=GET host=loki-loki-distributed-query-frontend.loki-distributed.svc.cluster.local:3100 path=/loki/api/v1/query_range time_taken=20.398505434s param_direction=BACKWARD param_limit=1470 param_query="sum by (host) (sum_over_time({event_action=\"firewall\",host=\"fwgate-1.test.local\"} | json | unwrap destination_bytes | __error__=\"\" [1s]))" param_start=1621543220000000000 param_end=1621545021000000000 param_step=1
level=info ts=2021-05-20T21:11:39.769218147Z caller=metrics.go:91 org_id=fake traceID=18da0ebda7f0ff9e latency=slow query="sum by (host) (sum_over_time({event_action=\"firewall\",host=\"fwgate-1.test.local\"} | json | unwrap destination_bytes | __error__=\"\" [1s]))" query_type=metric range_type=range length=30m1s step=1s duration=20.39682666s status=200 limit=1470 returned_lines=0 throughput=171MB total_bytes=3.5GB

```

querier log:
```
level=error ts=2021-05-20T21:04:18.789604295Z caller=frontend_processor.go:135 msg="error processing requests" err=EOF
level=info ts=2021-05-20T21:04:45.901215804Z caller=metrics.go:91 org_id=fake traceID=7654706a1f0bf45c latency=fast query="sum by (host) (sum_over_time({event_action=\"firewall\",host=\"fwgate-1.test.local\"} | json | unwrap destination_bytes | __error__=\"\" [1s]))" query_type=metric range_type=range length=4m43s step=1s duration=4.991252019s status=200 limit=1470 returned_lines=0 throughput=119MB total_bytes=594MB
level=info ts=2021-05-20T21:05:14.691173663Z caller=metrics.go:91 org_id=fake traceID=7654706a1f0bf45c latency=slow query="sum by (host) (sum_over_time({event_action=\"firewall\",host=\"fwgate-1.test.local\"} | json | unwrap destination_bytes | __error__=\"\" [1s]))" query_type=metric range_type=range length=14m59s step=1s duration=33.781277275s status=200 limit=1470 returned_lines=0 throughput=93MB total_bytes=3.1GB
ts=2021-05-20T21:05:17.473180739Z caller=memberlist_logger.go:74 level=warn msg="Was able to connect to loki-loki-distributed-ingester-1-eae0beca but other probes failed, network may be misconfigured"
level=info ts=2021-05-20T21:05:19.55194173Z caller=metrics.go:91 org_id=fake traceID=2e8155d308918929 latency=fast query="sum by (host) (sum_over_time({event_action=\"firewall\",host=\"fwgate-1.test.local\"} | json | unwrap destination_bytes | __error__=\"\" [1s]))" query_type=metric range_type=range length=4m43s step=1s duration=4.586489978s status=200 limit=1470 returned_lines=0 throughput=125MB total_bytes=574MB
level=info ts=2021-05-20T21:05:47.018691562Z caller=metrics.go:91 org_id=fake traceID=4657641b9c48defd latency=slow query="sum by (host) (sum_over_time({event_action=\"firewall\",host=\"fwgate-1.test.local\"} | json | unwrap destination_bytes | __error__=\"\" [500ms]))" query_type=metric range_type=range length=5m38s step=500ms duration=11.055653588s status=200 limit=1470 returned_lines=0 throughput=106MB total_bytes=1.2GB
```
no chance with avg:
```
level=warn ts=2021-05-21T11:59:05.75358833Z caller=logging.go:71 traceID=301cc777eb709fa3 msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1621598166000000000&limit=1470&query=avg+by+%28host%29+%28avg_over_time%28%7Bevent_action%3D%22firewall%22%2Chost%3D%22fwgate-1.test.local%22%7D+%7C+json+%7C+unwrap+destination_bytes+%7C++__error__%3D%22%22+%5B200ms%5D%29%29&start=1621597865000000000&step=0.200000 (500) 23.0830485s Response: \"rpc error: code = Canceled desc = context canceled\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 301cc777eb709fa3:6ccf7b75afd96dfe:4f27b7edca4fa1ee:0; "
```

**Comment by StefanSa** [comment]
Any news in the matter?

**Comment by cyriltovena** [comment]
I would suggest to activate query sharding in query range and to use snappy compression in ingester.

**Comment by StefanSa** [comment]
@cyriltovena 
Thanks for your answer, in general it is not good that we do not even come close to the performance as under ELK.
But that is the prerequisite that we can replace ELK and switch to Loki. We can already see that Loki potential has to replace ELK in certain cases, but apparently in ours.
We have created a new config with the most important change to `split_queries_by_interval: 1m` (including optimized memcache), which means that we are faster in the query but 6h query still results in a timout.

```
compactor:
  enabled: true
ingester:
  replicas: 3
distributor:
  replicas: 3
querier:
  replicas: 3
queryFrontend:
  replicas: 3
memcachedExporter:
  enabled: true
memcachedChunks:
  enabled: true
  replicas: 3
  extraArgs:
    - -m 4096
    - -I 32m
    - -vv
  resources:
    requests:
      cpu: 500m
      memory: 3Gi
    limits:
      cpu: "2"
      memory: 6Gi
memcachedIndexQueries:
  enabled: true
memcachedFrontend:
  enabled: true
loki:
  config: |
    chunk_store_config:
      chunk_cache_config:
        memcached:
          batch_size: 100
          parallelism: 100
        memcached_client:
          consistent_hash: true
          host: {{ include "loki.memcachedChunksFullname" . }}
          service: http

    auth_enabled: false

    server:
      log_level: info
      # Must be set to 3100
      http_listen_port: 3100

    distributor:
      ring:
        kvstore:
          store: memberlist

    ingester:
      # Disable chunk transfer which is not possible with statefulsets
      # and unnecessary for boltdb-shipper
      max_transfer_retries: 0
      chunk_idle_period: 1h
      chunk_target_size: 2621440
      max_chunk_age: 1h
      lifecycler:
        join_after: 0s
        ring:
          kvstore:
            store: memberlist

    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist

    limits_config:
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_concurrent_tail_requests: 20
      max_cache_freshness_per_query: 10m
      max_query_parallelism: 32

    schema_config:
      configs:
        - from: 2020-09-07
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      aws:
        s3: s3://loki:+tdu88EM@minio.minio-tenant-1.svc.cluster.local/loki
        s3forcepathstyle: true
      boltdb_shipper:
        active_index_directory: /var/loki/index
        shared_store: s3
        cache_location: /var/loki/cache
      index_queries_cache_config:
        memcached:
          batch_size: 100
          parallelism: 100
        memcached_client:
          consistent_hash: true
          host: {{ include "loki.memcachedIndexQueriesFullname" . }}
          service: http

    table_manager:
      retention_deletes_enabled: true
      retention_period: 672h

    querier:
      query_ingesters_within: 3h
      query_timeout: 2m

    query_range:
      # make queries more cache-able by aligning them with their step intervals
      align_queries_with_step: true
      max_retries: 5
      # parallelize queries in 15min intervals
      split_queries_by_interval: 1m
      cache_results: true

      results_cache:
        cache:
          memcached_client:
            consistent_hash: true
            host: {{ include "loki.memcachedFrontendFullname" . }}
            max_idle_conns: 16
            service: http
            timeout: 500ms
            update_interval: 1m

    frontend_worker:
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
      grpc_client_config:
          max_send_msg_size: 1.048576e+08
      parallelism: 16

    frontend:
      log_queries_longer_than: 15s
      compress_responses: true
    compactor:
      shared_store: s3

```

**Comment by StefanSa** [comment]
@cyriltovena 
> I would suggest to activate query sharding in query range and to use snappy compression in ingester.

Can you please show an example.

**Comment by airclear** [comment]
Do I understand correctly ? 
 every query will fetch data from s3 store ?
 If  the dataset is very large,  the Network bandwidth will become a bottleneck

**Comment by StefanSa** [comment]
@airclear 
Hi, thanks for your reply.
these are firewall syslog events with approx. 180 logs / sec.
Yes everything is stored in s3. We did the test with `activate query sharding in query range`, but with no success.
You can see that the CPU load goes over several CPUs (over 1000%) but after a few seconds it is canceled here. Meanwhile we are at a loss as to what else to do here.
What alternative would there be to s3?

**Comment by StefanSa** [comment]
Does anyone else have an idea how to fix this problem, or is loki just not suitable for this job for us.
Maybe is the configuration wrong or hardware not sufficient ?

**Comment by John-Lin** [comment]
> @cyriltovena
> 
> > I would suggest to activate query sharding in query range and to use snappy compression in ingester.
> 
> Can you please show an example.

from docs:
```yaml
# The compression algorithm to use for chunks. (supported: gzip, lz4, snappy)
# You should choose your algorithm depending on your need:
# - `gzip` highest compression ratio but also slowest decompression speed. (144 kB per chunk)
# - `lz4` fastest compression speed (188 kB per chunk)
# - `snappy` fast and popular compression algorithm (272 kB per chunk)
# CLI flag: -ingester.chunk-encoding
[chunk_encoding: <string> | default = gzip]
```


```yaml
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
  chunk_idle_period: 5m
  chunk_block_size: 262144
  chunk_target_size: 2621440
  chunk_encoding: snappy
  chunk_retain_period: 10m
  max_transfer_retries: 0
```

**Comment by M3r1** [comment]
@StefanSa Did you eventually managed to get better results?

We are very disappointed with Loki's query times, presenting Grafana dashboards of metric queries is impossible with those query speeds.

I'm currently trying to figure out a way to tune this and maybe get better results somehow... Currently I think that most of the query execution time goes into downloading chunks from S3 and I was wondering if you investigating the subject as well and have some insights you can share.

**Comment by StefanSa** [comment]
@M3r1 
No, we have not found a solution here which is a pity.
Originally we wanted to replace our ELK stack with loki, but now we have to realize that this is probably not possible. 
I'm honestly a little disappointed that none of the core developers really takes this problem and at least tries to find a solution here. So we will stop all tests with loki and continue to work with ELK / opensearch.

**Comment by M3r1** [comment]
@StefanSa We got it working!!!

We ran the following query (I'm typing this since we run Loki on a private network):
sum(count_over_time({filename="/var/log/haproxy/haproxy.log,host=~"instance_name.+"} != "SSL handshake failure" | regexp "^.*]: (?P<ip_address>[^:]*).*~ (?P<backend>[^:]*)/(?P<server>[^ ]*).*\"(?P<operation>[^ ]*) /(?P<bucket>[^/?]*).*$" [15m] )) by (ip_address) for 24h hours back. As you can see this is a fairly complex query claiming (Logcli --stats) to fetch 2.1GB of uncompressed bytes without any caching involved, execution took 11 seconds which is miles better than the timeout we got before, dashboards are usable now! Now i'm guessing that further tuning values with query-frontend and caching might even shave an additional 3 seconds of execution time plus the excellent results_cache which makes everything a lot smoother. Since we got a timeout at 24 hour query i'll compare speeds after the fix with 3 hours queries, before it took 30 seconds, now it takes us around 4.5 meaning we got around 6 times improvement in speed. We are using 32 cpu cores for queriers.

Now to the problem, we deployed Loki on our own organization private cloud where we were using our own object store our own object store gave us around 50mbps of downloading 1.5 mb of chunk objects. Since we didn't have additional clients using our object store that require speeds significantly higher than that we didn't really pay much attention to this performance since we kinda took it as the norm and thought it is good enough.

So we ran a test, we brought up a strong vm behind a frontend with -target=all where the backend store was the vm's filesystem. This is what gave us the boost in speed sufficient to make Loki usable. We intend now to move back to our original Loki distributed deployment, this time with cassandra as the backing storage.

Hopefully our experience helps you and others.

**Comment by StefanSa** [comment]
@M3r1 
That sounds promising!
If you have successfully passed all tests, it would be great if you could publish the complete loki config here.
Thanks in advance.

**Comment by M3r1** [comment]
@StefanSa 
No problem! We have some bureaucracy to go through before we can connect cassandra to our Loki so I'll probably publish my configuration in a few days.

**Comment by StefanSa** [comment]
@M3r1 
super :+1:

**Comment by gmintoco** [comment]
Something that really helped query speed for us was using memcached and increasing the timeouts (along with lowering the split interval and increasing parallelisation). At the moment we can query about 2GB/s of logs in Grafana and could probably get this higher with more queriers (limited to about 4 cores at the moment)

**Comment by StefanSa** [comment]
@M3r1 
hi, any news here ?

**Comment by M3r1** [comment]
@StefanSa Hopefully will be done by Monday, sorry for the delay

**Comment by M3r1** [comment]
Hello @StefanSa I have some, let's call it confusing, news.

We were able to deploy Loki with Cassandra however we got inconsistent query result times, we sometimes got fast results and often got slow results. We did a lot of investigating and we came to the conclusion that we have a client overloading Loki, we have very few clients, actually we are our own clients and we are guessing that one vm wrote a lot of logs which affected all queries we can run. We decided to let it be for the close future so we will be 100% sure it is a client and then decide on our next action.

However when the load was regular we did get good results with Loki so I decided to publish our configuration anyway:
(2 distributors, 3 ingesters, 4 queriers-9, 1 query frontend)
```
auth_enabled: false

server:
  http_listen_port: 5000
  grpc_listen_port: 9096
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_server_idle_timeout: 120s,
  http_server_write_timeout: 1m 

chunk_store_config:
  chunk_cache_config:
    memcahced:
      batch_size: 100
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: memcached_host
      service: memcached
  write_dedupe_cache_config:
    memcahced:
      batch_size: 100
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: memcached_host
      service: memcached
  max_look_back_period: 672h

ingester_client:
  grpc_client_config:
    max_recv_msg_size: 67108864
  remote_timeout: 1s

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  chunk_encoding: snappy
  chunk_block_size: 262144
  chunk_target_size: 1536000
  chunk_idle_period: 15m
  chunk_retain_period: 30s
  max_chunk_age: 3h
  lifecycler:
    heartbeat_period: 5s
    join_after: 30s
    num_tokens: 512
    ring:
      heartbeat_timeout: 1m
      kvstore:
        store: memberlist
      replication_factor: 3
    final_sleep: 0s
  max_transfer_retries: 60

frontend:
  compress_responses: true
  max_outstanding_per_tenant: 1024

frontend_worker:
  frontend_address: frontend:9096
  grpc_client_config:
    max_send_msg_size: 104857600
  parallelism: 9 (we have 9 cores per querier)

limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: 10
  ingestion_rate_mb: 5
  ingestion_rate_strategy: local
  max_global_streams_per_user: 10000
  max_query_length: 12000h
  max_query_parallelism: 256
  max_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 168h

querier:
  query_ingesters_within: 4h

query_range:
  align_queries_with_step: true
  cache_results: true
  max_retries: 5 
  parallelise_shardable_queries: false //it's written everywhere that this should increase performance when true however we see no diffrence
  results_cache:
    cache:
      memcached_client:
        consistent_hash: true
        host: memcached_host
        max_idle_conns: 16
        service: memcached
        timeout: 500ms
        update_interval: 1m
  split_queries_by_interval: 15m

schema_config:
  configs:
    - from: 2021-07-30
      store: cassandra
      object_store: cassandra
      schema: v11
      index:
        prefix: test_
        period: 24h
      chunks:
        prefix: chunk_
        period: 24h

storage_config:
  index_queries_cache_config:
    memcached: 
      batch_size: 100
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: memcached_host
      service: memcached
 
memberlist:
   abort_if_cluster_join_fails: false
   bind_addr:
     - the_bind_ip_address
   bind_port: 7946
   join_members:
     - ip_address:7946
     - off_all_the_loki_components:7946 
```

**Comment by StefanSa** [comment]
@M3r1 
Thank you for your effort and time for the good analysis.
If the hope remains that loki will improve the data throughput for the queries metrics,
only then is it a real alternative to the ELK stack, unfortunately.

**Comment by wzuqui** [comment]
I installed it a week ago, I'm also facing a performance issue. Unfortunately ELK is the alternative. I hope you optimize this soon

**Comment by hsraju** [comment]
Issue still persists (Loki v2.3.0)

**Comment by lackhoa** [comment]
Writing just to agree with @M3r1 that fetching chunks from the remote store (S3 in our case) is a major point of failure. I don't understand why people say that caching is the end-all solution here. Sure caching the chunks does boost performance if you manage to hit it, two problems though:
1. What if you don't hit the cache?
2. What if the cache node went down and you have to refill it again?

I don't want my logging stack to be unreliable to the point that sometimes querying over 7 days takes <1s, other time even querying over 15m causes 502 timeout errors.

**Comment by LinTechSo** [comment]
Hi any Updates ?

**Comment by suikast42** [comment]
> @M3r1 No, we have not found a solution here which is a pity. Originally we wanted to replace our ELK stack with loki, but now we have to realize that this is probably not possible. I'm honestly a little disappointed that none of the core developers really takes this problem and at least tries to find a solution here. So we will stop all tests with loki and continue to work with ELK / opensearch.

I originally had the same thing in mind. ( I don't give up and find try to find a feasable setup for my need )

I am using the monolithic mode with local file storage. I think that must fit the best performance for a single node setup ( I don't need realy a clustering at the moment).

That are the setting what makes loki useable for my usecase 
```yaml
querier:
  max_concurrent: 4096
query_scheduler:
  max_outstanding_requests_per_tenant: 10000

query_range:
  cache_results: true

limits_config:
  retention_period: 24h
```

I have used the elk stack a lot and want try out a new approach. My feeling about one month testing loki and reading docs is, that it can't realy replace the elk stack for my use case.  Let me tell why:

1. The loki architecture is not easy to understand and to be honest not easy to scale or better to say plan the 'scale'.
2. You have to understand every single component in detail.   
3. Data retentions are hard to configure and uderstand. What is stored where ?  You have a cahce, boltdb a chunk a compactor that downloads uploads and deletes and so on. 
4. Capacitiy planing is more compilcated. For the compactor for example. 
5. You can't delete a single day ( somewhere middle in the month where a sensor produce a lot of waste for example) chunk out of box.

I hope for someone who will teach me better
