### ISSUE TITLE
unable to list rules" err="NoSuchKey

### ISSUE THREAD

**Issue by chaishiqi** [grafana/loki#3761]
Hi,When I deploy the loki cluster, the "schema_config" and "storage_config" I use is oss on Alicloud,the main config is below:

```
schema_config:
  configs:
  - from: 2021-05-25
    store: boltdb-shipper
    object_store: aws
    schema: v11
    index:
      prefix: loki_
      period: 24h

storage_config:
  boltdb_shipper:
    shared_store: aws
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache

  aws:
    s3: s3://access:secret@xxx.aliyuncs.com/loki-new
    s3forcepathstyle: true
    insecure: true
  filesystem:
    directory: /loki/chunks
...
ruler:
  storage:
    type: s3
    s3:
      s3: s3://access:secret@xxx.aliyuncs.com/loki-new
      s3forcepathstyle: true
      insecure: true
      http_config:
        insecure_skip_verify: true
  enable_api: true
  enable_alertmanager_v2: true
  alertmanager_url: "http://alertmanager-main.monitoring.svc:9093"
  ring:
    kvstore:
      store: inmemory
```
---
when I deploy loki-system/statefulset.yaml,some error occurs,like this:

```
level=info ts=2021-05-25T05:48:16.797166582Z caller=table_manager.go:171 msg="uploading tables" 
level=info ts=2021-05-25T05:48:16.800376897Z caller=table_manager.go:324 msg="synching tables" expected_tables=1 
level=error ts=2021-05-25T05:48:16.809528621Z caller=ruler.go:444 msg="unable to list rules" err="NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: 60AC8FA0328A2D353552172E, host id: " 
level=error ts=2021-05-25T05:48:16.846124844Z caller=table_manager.go:234 msg="error syncing tables" err="NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: 60AC8FA05FCE0B31349A642B, host id: " 
```

what's the problem?
