### ISSUE TITLE
field shared_store not found in type local.BoltDBConfig

### ISSUE THREAD

**Issue by Morriz** [grafana/loki#3777]
**Describe the bug**

Using the example for the shipper setup I see this error:
```
field shared_store not found in type local.BoltDBConfig
```

**To Reproduce**
1. Started Loki 2.2.1 with this config:
```yaml
chunk_store_config:
  max_look_back_period: 24h
compactor:
  shared_store: aws
  working_directory: /data/loki/boltdb-shipper-compactor
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 24h
schema_config:
  configs:
  - from: "2018-04-15"
    index:
      period: 24h
      prefix: index_
    object_store: filesystem
    schema: v9
    store: boltdb
  - from: "2021-05-12"
    index:
      period: 24h
      prefix: index_
    object_store: aws
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
storage_config:
  aws:
    s3: s3://some-bucket
  boltdb:
    shared_store: filesystem
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: aws
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: true
  retention_period: 24h
```

**Expected behavior**
Loki to start

**Environment:**
 - Infrastructure: k8s 1.19
 - Deployment tool: helm
