### ISSUE TITLE
minimum field size of 1, PutObjectInput.Bucket

### ISSUE THREAD

**Issue by Morriz** [grafana/loki#3778]
**Describe the bug**

Access to s3 with this config fails with the following error:
```
minimum field size of 1, PutObjectInput.Bucket
```

**To Reproduce**
1. Started Loki 2.2.1 with this config:
(note that I have the worker nodes access with eksctl via roles)
```yaml
storage_config:
  aws:
    s3: s3://eu-central-1/some-bucket
```

**Expected behavior**

Loki to write to s3

**Environment:**
 - Infrastructure: k8s 1.19
 - Deployment tool: helm
