### ISSUE TITLE
Promtail fails to read journal silently

### ISSUE THREAD

**Issue by jfolz** [grafana/loki#3779]
**Describe the bug**
I found that one machine was sending logs from `/var/logs/*.log`, but nothing was coming in from its journal.
`journalctl --since today` spits lots of messages, but promtail is silent.
Meanwhile on another machine running the same OS, the same kernel, ... it works as expected.
I'm having a hard time figuring out what could possibly be different about these machine that it wouldn't work on one of them.

**To Reproduce**
Use the official promtail 2.2.1 binary [downloaded from here](https://github.com/grafana/loki/releases/download/v2.2.1/promtail-linux-amd64.zip) and this config:
```
server:
  http_listen_port: 9081
  grpc_listen_port: 0

positions:
  filename: positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      json: false
      max_age: 24h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
```

Run promtail in dry-run mode. It starts without error but no logs are printed:
```
# ./promtail-linux-amd64 --dry-run --config.file=promtail-journal-config.yml
Clients configured:
----------------------
url: http://localhost:3100/loki/api/v1/push
batchwait: 1s
batchsize: 1048576
backoff_config:
  min_period: 500ms
  max_period: 5m0s
  max_retries: 10
timeout: 10s
tenant_id: ""

level=info ts=2021-05-30T19:16:00.188961827Z caller=server.go:229 http=[::]:9081 grpc=[::]:42151 msg="server listening on addresses"
level=info ts=2021-05-30T19:16:00.189351455Z caller=main.go:112 msg="Starting Promtail" version="(version=2.2.1, branch=HEAD, revision=babea82e)"
```

**Expected behavior**
Logs start spewing out like crazy ;)

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: just testing in an ssh session

If it's of any help the affected machine is running Ubuntu 18.04 (NVIDIA DGX-1 Version 4.7.0) and all default for `journald.conf`.
Some more details:
```
# uname -a
Linux [unhappy machine] 5.4.0-65-generic #73~18.04.1-Ubuntu SMP Tue Jan 19 09:02:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
# systemctl --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

**Comment by dannykopping** [comment]
Hey @jfolz 

Could you please try running promtail with `-log.level=debug`? There may be some useful diagnostic messages in there.
At the same time as running promtail, please run `journalctl -f` and ensure that new messages are being appended to the journal.

**Comment by jfolz** [comment]
@dannykopping thanks for the hint. Unfortunately promtail's output seems identical to me. Meanwhile messages are indeed popping up in `journalctl -f`.
```
# ./promtail-linux-amd64 --dry-run --log.level=debug --config.file=promtail-journal-config.yml
Clients configured:
----------------------
url: http://localhost:3100/loki/api/v1/push
batchwait: 1s
batchsize: 1048576
backoff_config:
  min_period: 500ms
  max_period: 5m0s
  max_retries: 10
timeout: 10s
tenant_id: ""

level=info ts=2021-05-31T07:14:40.861114122Z caller=server.go:229 http=[::]:9081 grpc=[::]:37731 msg="server listening on addresses"
level=info ts=2021-05-31T07:14:40.861385257Z caller=main.go:112 msg="Starting Promtail" version="(version=2.2.1, branch=HEAD, revision=babea82e)"
```

**Comment by dannykopping** [comment]
OK, that's a pity.

Next thing to try:
While promtail is running, please get its PID and then run:

```bash
sudo lsof -p <pid> |& grep /var/log/journal
# or sudo lsof -p <pid> 2>&1 | grep /var/log/journal if |& doesn't work in your shell
```

This will show if the promtail process has any file handles to the journal. If not, then something is not working as expected.

**Comment by jfolz** [comment]
No open files :(
Just to be sure `system.journal` does indeed exist and is being written to ;)
And I am logged in as root obviously so promtail should be allowed to read.
```
# ls -lhtr /var/log/journal/[machine id]/system*
-rw-r-----+ 1 root systemd-journal 40M May 31 09:46 /var/log/journal/[machine id]/system.journal
```

**Comment by jfolz** [comment]
Here's what the web interface says about targets:
| Key | Value |
|----|------|
| position |  |

The other machine where it's working shows this:
| Key | Value |
|----|------|
| position | s=f1314626db71485aa536fe4c994a679a;i=a16b7d;b=905c04389fee4ffe80ab4390164e7087;m=7c49e37d29d;t=5c39ca5804138;x=5419077c89f77291 |

**Comment by dannykopping** [comment]
Does your positions file exist, and can promtail write to it?

**Comment by jfolz** [comment]
As per config shown above it should put it in the current directory, but there is none. Changing to an absolute path has no effect, as does changing it to the example path `/tmp/positions.yaml`

The promtail process running as a service does write to its configured `positions.yaml`, but there are only references to `/var/log/*.log` in it.

**Comment by dannykopping** [comment]
Please provide a little more info on how you're running promtail...
Are you running it at a systemd unit?

**Comment by jfolz** [comment]
Apart from the setup given in the first post, there's another promtail running as a systemd unit, which is happily pushing everything to Loki as configured - apart from journal logs. I just stopped this service in case it somehow interfered with my manual testing, but there was no difference.

Config:
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://[loki machine]:3100/loki/api/v1/push

scrape_configs:
  - job_name: slurm
    static_configs:
      - labels:
          job: slurmlogs
          __path__: /var/log/slurm/*log
    pipeline_stages:
      - match:
          selector: '{job="slurmlogs"}'
          stages:
            - regex:
                expression: '\[(?P<timestamp>[T\d-:.Z]+)\] (?P<message>.+)'
            - timestamp:
                source: 'timestamp'
                format: '2006-01-02T15:04:05.999'
                location: 'Europe/Berlin'
            - output:
                source: 'message'
  - job_name: system
    static_configs:
    - labels:
       job: varlogs
       __path__: /var/log/*.log
    pipeline_stages:
    - match:
        selector: '{job="varlogs"}'
        stages:
        - regex:
            expression: '(?P<prefix>[^A-Za-z]*)(?P<timestamp>[A-Z][a-z]+[ ]?\d{2} \d{2}:\d{2}:\d{2}|\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.?\d{0,3}) (?P<message>.+)'
        - timestamp:
            source: 'timestamp'
            format: 'Jan 2 15:04:05'
            fallback_formats: ['Jan2 15:04:05', '2006-01-02 15:04:05.999', '2006-01-02T15:04:05.999']
            location: 'Europe/Berlin'
        - output:
            source: 'message'
  - job_name: journal
    journal:
      json: false
      max_age: 24h
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
```

Unit file:
```
[Unit]
Description=Promtail log tailing service
After=network.target

[Service]
Type=simple
StartLimitBurst=5
StartLimitInterval=0
Restart=on-failure
RestartSec=1
User=root
Group=root
PIDFile=/run/promtail/promtail.pid
ExecStart=/usr/local/bin/promtail-linux-amd64 -config.file /etc/loki/promtail-config.yml --client.external-labels="host=%H"
ExecStop=/bin/kill -s SIGTERM $MAINPID

[Install]
WantedBy=multi-user.target
```
