### ISSUE TITLE
Include Grafana URL that returns the logs that triggered an alert in annotations

### ISSUE THREAD

**Issue by dpkirchner** [grafana/loki#3789]
**Is your feature request related to a problem? Please describe.**
Alerts can only provide so much context and we probably wouldn't want to include every relevant log line anyway, especially when we're talking about alerts about high error volume as demonstrated at https://grafana.com/docs/loki/latest/alerting/ .

**Describe the solution you'd like**
I would like to be able to include a link to Grafana that shows the specific log lines that triggered the alert, including the time range. Alternatively, or additionally, a way to include a short link to make the alert text reasonably small.

**Describe alternatives you've considered**
I've considered hardcoding Grafana URLs as annotations in my alerts, however all of the required URL encoding makes this method cumbersome and error prone. In the end I don't think it's a good choice, so I haven't gone that route.

**Additional context**
I'd like to do something like this (based on an example alert in the docs):

```yaml
groups:
  - name: should_fire
    rules:
      - alert: HighPercentageError
        expr: |
          sum(rate({app="foo", env="production"} |= "error" [5m])) by (job)
            /
          sum(rate({app="foo", env="production"}[5m])) by (job)
            > 0.05
        for: 10m
        labels:
            severity: page
        annotations:
            summary: High request latency
--->        grafana_url: https://grafana.mycompany/explore?orgId=1&left=%5B"now-1h","now","Loki",%7B"exemplar":true,"expr":"sum(rate(%7B ... <---
```
