### ISSUE TITLE
Use labels as derived fields for Tempo integration

### ISSUE THREAD

**Issue by sergeyshaykhullin** [grafana/loki#3796]
**Is your feature request related to a problem? Please describe.**

I am using grafana, loki, promtail and tempo. I tried to setup loki to tempo datasource integration
Promtail has pipeline extracting traceId from logs and modifying output.
I can't reference to already present traceId label in loki derived fields, only regex from log text is possible

**Describe the solution you'd like**
```yaml
derivedFields:
- name: traceId
  label: traceId # or even omit and get from name
  datasourceUid: tempo
  url: "$${__value.raw}"
```

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/46970457/120644814-6daf6000-c480-11eb-8ebc-e9d359d283bc.png)
