### ISSUE TITLE
promtail: exclude files from static_configs __path__

### ISSUE THREAD

**Issue by rgl** [grafana/loki#3804]
**Is your feature request related to a problem? Please describe.**

my `/var/log` directory has files with different structures, which requires me to use different `pipeline_stages` for each set of different files.

**Describe the solution you'd like**

something like this would exclude all files that match the pattern `/host/var/log/contained.*.log`:

```yml
    static_configs:
      - labels:
          job: logwrite
          __path__: /host/var/log/*.log
          __path_exclude__: /host/var/log/contained.*.log
```

or maybe call it `__exclude_path__`?

or even modify `__path__` to be an array where the array items that start with `!` exclude paths?

if you agree, I can prepare a PR to modify the code (and docs) at:
 https://github.com/grafana/loki/blob/a9d85de4aa5290cf2f8b2dca5d08645bbd0dc66c/clients/pkg/promtail/targets/file/filetarget.go#L162-L171

to do a second call to `doublestar.Match` before calling `t.startTailing`.
