### ISSUE TITLE
docker-driver: not adding the container_name as documented

### ISSUE THREAD

**Issue by rgl** [grafana/loki#3811]
**Describe the bug**

the docker-driver is not adding the `container_name` [as documented](https://grafana.com/docs/loki/latest/clients/docker-driver/configuration/#labels).

**To Reproduce**

1. Start Loki 2.2.1
1. Install the docker-driver 2.2.1 docker plugin
1. Set the following docker 20.10.7 daemon configuration:
    ```yml
    {
      "debug": true,
      "log-driver": "loki",
      "log-opts": {
        "loki-url": "http://10.10.0.2:3100/loki/api/v1/push",
        "loki-external-labels": "job=docker"
      }
    }
    ```
1. Query: `logcli query --tail '{job="docker"}'`

Got:

```
2021-06-07T07:37:57+01:00 {filename="/var/log/docker/ce6574ee7e2385634b16bc6b277dd4530e0d4826e37bf6eb9402df2cffc1f664/json.log", host="linuxkit-525400226029", job="docker", source="stdout"} hello docker Mon Jun 7 06:37:57 UTC 2021
```

**Expected behavior**

I expected the `container_name` label.

**Workaround**

`"loki-external-labels": "job=docker,container_name={{.Name}}"`
