### ISSUE TITLE
docker-driver: loki-relabel-config does not remove the source label

### ISSUE THREAD

**Issue by rgl** [grafana/loki#3812]
**Describe the bug**

`loki-relabel-config` does not remove the source label

**To Reproduce**

1. Start Loki 2.2.1
1. Install the docker-driver 2.2.1 docker plugin
1. Set the following docker 20.10.7 daemon configuration:
    ```yml
    {
      "debug": true,
      "log-driver": "loki",
      "log-opts": {
        "loki-url": "http://10.10.0.2:3100/loki/api/v1/push",
        "loki-external-labels": "job=docker",
        "loki-relabel-config": "- regex: filename|source\n  action: labeldrop\n"
      }
    }
    ```
1. Query: `logcli query --tail '{job="docker"}'`

Got:

```
2021-06-07T08:09:27+01:00 {container_name="hello-docker", host="linuxkit-52540080b679", job="docker", source="stdout"} hello docker Mon Jun 7 07:09:27 UTC 2021
```

**Expected behavior**

I expected the `source` label to be removed.

Please note that the `filename` label was removed as expected.
