### ISSUE TITLE
docker-driver: loki-relabel-config does not rename container_name to the source label

### ISSUE THREAD

**Issue by rgl** [grafana/loki#3813]
**Describe the bug**

`loki-relabel-config` does not rename container_name to the source label.

**NB** I'm not sure if this is related to https://github.com/grafana/loki/issues/3812.

**To Reproduce**

1. Start Loki 2.2.1
1. Install the docker-driver 2.2.1 docker plugin
1. Set the following docker 20.10.7 daemon configuration:
    ```yml
    {
      "debug": true,
      "log-driver": "loki",
      "log-opts": {
        "labels": "worker_id",
        "loki-url": "http://10.10.0.2:3100/loki/api/v1/push",
        "loki-external-labels": "job=docker",
        "loki-relabel-config": "- regex: filename|source\n  action: labeldrop\n- regex: container_name\n  replacement: source\n  action: labelmap\n"
      }
    }
    ```
1. Query: `logcli query --tail '{job="docker"}'`

Got:

```
2021-06-07T08:31:45+01:00 {container_name="hello-docker", host="linuxkit-52540039804b", job="docker", source="stdout", worker_id="123"} hello docker Mon Jun 7 07:31:45 UTC 2021
```

**Expected behavior**

I expected the `container_name` label to be renamed to `source`.
