### ISSUE TITLE
docker-driver: loki-pipeline-stages does not replace the host label value

### ISSUE THREAD

**Issue by rgl** [grafana/loki#3817]
**Describe the bug**

`loki-pipeline-stages` does not replace the `host` label value.

1. Start Loki 2.2.1
1. Install the docker-driver 2.2.1 docker plugin
1. Set the following docker 20.10.7 daemon configuration:
    ```yml
      {
        "debug": true,
        "log-driver": "loki",
        "log-opts": {
          "labels": "worker_id",
          "loki-url": "http://10.10.0.2:3100/loki/api/v1/push",
          "loki-external-labels": "job=docker,container_name={{.Name}}",
          "loki-relabel-config": "- regex: filename\n  action: labeldrop\n",
          "loki-pipeline-stages": "- replace:\n    source: host\n    expression: '.*'\n    replace: linuxkit\n"
        }
    ```
1. Query: `logcli query --tail '{job="docker"}'`

Got:

```
2021-06-07T18:48:30+01:00 {host="linuxkit-5254002c513a", job="docker", source="hello-docker", worker_id="123"} hello docker Mon Jun 7 17:48:30 UTC 2021
```

**Expected behavior**

I expected the `host` label value to be `linuxkit`.
