### ISSUE TITLE
promtail multiline pipeline with kubernetes labels

### ISSUE THREAD

**Issue by Henry-Kim-Youngwoo** [grafana/loki#3820]
currently, I deployed prom-tail on my eks cluster with helm chart

and I use this configuration to use multiline parsing

```
    - job_name: rtp-server-log
      pipeline_stages:
      - docker: {}
      - multiline:
          firstline: ^\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d\.\d+([+-][0-2]\d:[0-5]\d|Z)
          max_lines: 1000
          max_wait_time: 2s
      - replace:
          expression: '(\n)'
          replace: ''
      static_configs:
      - labels:
          __path__: /var/log/pods/asterisk*/asterisk-rtp-server/*.log
          job: rtp-server-log
        targets:
        - localhost
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
```

but when I check the log on grafana explorer there is no label about kubernetes pod metadata 

how can i add kubernetes pod info like container name or pod name with multiline parsing?
