### ISSUE TITLE
Log indexes deleted from s3 bucket after changing ingestor config.  

### ISSUE THREAD

**Issue by abhardwaj29** [grafana/loki#3822]
**Describe the bug**
We are using loki 2.0 single tenant mode (k8s statefulset), with boltdbshipper, the storage used is s3 bucket, 
after changing the chunk_target_size from default 0 to 0.25 Mi the old log indexes from the bucket are deleted, 

these are the settings I changed after which the issue appeared,
`
      chunk_idle_period: 3m
      chunk_retain_period: 3m
      chunk_target_size: 262144
`
I made these changes as suggested as a fix for query taking up all the memory https://github.com/grafana/loki/issues/613

This is our prod configuration.

```
image:
  repository: grafana/loki
  tag: 2.1.0
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

affinity: {}
annotations: {}

tracing:
  jaegerAgentHost:

config:
  auth_enabled: false
  ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 3m
      chunk_retain_period: 3m
      chunk_target_size: 262144
      flush_op_timeout: 60s


  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
  schema_config:
    configs:
    - from: 2020-04-01
      store: aws
      object_store: aws
      schema: v9
      index:
        prefix: loki_dev_index_
        period: 24h
    - from: 2021-02-26
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_dev_boltdb_index_
        period: 24h

  server:
    http_listen_port: 3100
    grpc_server_max_recv_msg_size: 6000000
    grpc_server_max_send_msg_size: 6000000

  storage_config:
    aws:
        s3: s3://<REDACTED>:<REDACTED>@us-west-2/my_log_bucket
        dynamodb:
          dynamodb_url: dynamodb://<REDACTED>:<REDACTED>@myregion
    boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        shared_store: aws
        cache_location: /data/loki/boltdb-shipper-cache
    filesystem:
      directory: /data/loki/chunks

  compactor:
     working_directory: /data/loki/boltdb-shipper-compactor
     shared_store: aws

  chunk_store_config:
    max_look_back_period: 168h
  table_manager:
    retention_deletes_enabled: true
    retention_period: 168h
    chunk_tables_provisioning:
      provisioned_write_throughput: 0
      provisioned_read_throughput: 0
      inactive_write_throughput: 0
      inactive_read_throughput: 0
    index_tables_provisioning:
      provisioned_write_throughput: 0
      provisioned_read_throughput: 0
      inactive_write_throughput: 0
      inactive_read_throughput: 0

extraArgs: {}
livenessProbe:
  httpGet:
    path: /ready
    port: http-metrics
  initialDelaySeconds: 45

networkPolicy:
  enabled: false

client:
  max_recv_msg_size: 6000000
  max_send_msg_size: 6000000

nodeSelector: {}

persistence:
  enabled: false
  accessModes:
  - ReadWriteOnce
  size: 10Gi
  annotations: {}

podLabels: {}

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "http-metrics"

podManagementPolicy: OrderedReady


rbac:
  create: true
  pspEnabled: true

readinessProbe:
  httpGet:
    path: /ready
    port: http-metrics
  initialDelaySeconds: 45

replicas: 1

resources: {}
# limits:
#   cpu: 200m
#   memory: 256Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

securityContext:
  fsGroup: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001

service:
  type: ClusterIP
  nodePort:
  port: 3100
  annotations: {}
  labels: {}

serviceAccount:
  create: true
  name:
  annotations: {}

terminationGracePeriodSeconds: 4800

tolerations: []

podDisruptionBudget: {}
# minAvailable: 1
# maxUnavailable: 1

updateStrategy:
  type: RollingUpdate

serviceMonitor:
  enabled: false
  interval: ""
  additionalLabels: {}
  # scrapeTimeout: 10s

initContainers: []
## Init containers to be added to the loki pod.
# - name: my-init-container
#   image: busybox:latest
#   command: ['sh', '-c', 'echo hello']

extraContainers: []
## Additional containers to be added to the loki pod.
# - name: reverse-proxy
#   image: angelbarrera92/basic-auth-reverse-proxy:dev
#   args:
#     - "serve"
#     - "--upstream=http://localhost:3100"
#     - "--auth-config=/etc/reverse-proxy-conf/authn.yaml"
#   ports:
#     - name: http
#       containerPort: 11811
#       protocol: TCP
#   volumeMounts:
#     - name: reverse-proxy-auth-config
#       mountPath: /etc/reverse-proxy-conf


extraVolumes: []
## Additional volumes to the loki pod.
# - name: reverse-proxy-auth-config
#   secret:
#     secretName: reverse-proxy-auth-config

## Extra volume mounts that will be added to the loki container
extraVolumeMounts: []

extraPorts: []
## Additional ports to the loki services. Useful to expose extra container ports.
# - port: 11811
#   protocol: TCP
#   name: http
#   targetPort: http

# Extra env variables to pass to the loki container
env: []

```

**To Reproduce**
1: deploy loki 2.0 helm chart using above config:
2: change some ingestor config defaults 
`
      chunk_idle_period: 3m  // from 5m
      chunk_retain_period: 3m // from 30s 
      chunk_target_size: 262144 // from default 0
`
3: After deploying,  the log indexes prior to deployment time are deleted, and I cannot query older logs in grafana.

**Expected behavior**
After changing the configuration as suggested in https://github.com/grafana/loki/issues/613 the loki should not take high memory on each query and the old log indexes from the s3 bucket should not get deleted.

**Environment:**
Kubernetes: Worker node size 4Gi memory 4 core CPU
Loki running in a single-tenant mode (Stateful set).

**Comment by sandeepsukhani** [comment]
I don't think that setting should delete the index from the s3. The only way indexes could be deleted from s3 is by table manager based on retention config or aws itself based on the bucket retention policy. Your retention policy is set to just 7 days; is it intentional?

**Comment by abhardwaj29** [comment]
@sandeepsukhani  thanks for replying, we do not have a was bucket retention policy, 
Also after I changed the mentioned settings and deployed helm, any log indexes older than the deployment time are deleted from bucket.
We started using v11 schema recently with loki 2.0 upgrade earlier we were using the dynamo DB v9 schema.

The strange part is all the chunks in the s3 fake/ directory are there just the indexes are gone. 

About 7 days retention:
this setting is for our dev cluster, we wanted to test the change of chunk settings to improve high memory usage on every query on our prod cluster. (the prod cluster has a bigger retention period).

**Comment by sandeepsukhani** [comment]
Did you by any chance changed the schema by changing v9 to v11 without adding a new schema config with newer date? I just see v11 schema config with boltdb shipper.

**Comment by abhardwaj29** [comment]
As part of the recent helm deployment (after which the indexes got deleted), I just changed the `      chunk_idle_period: 3m from 5m
chunk_retain_period: 3m from 30s 
chunk_target_size: 262144 from default 0 `

We added the v11 schema couple of months back to upgrade to loki 2.0, earlier we were using Dynamo DB for storing chunks and indexes (v9), from 2021-02-26 we moved to boltdb-shipper with our upgrade to loki 2.0.
However with the new settings for chunks, I did not add a new schema config as there is no schema change or index prefix changes. 

do we need to add new schema in config after changing the chunk_target_size say from 2021-06-03 (the date when I deployed after these changes)?

**Comment by sandeepsukhani** [comment]
What was your previous Loki version?

**Comment by abhardwaj29** [comment]
we were using v1.5

**Comment by sandeepsukhani** [comment]
To sum it up, your last change was just following config change 
```
chunk_idle_period: 3m from 5m
chunk_retain_period: 3m from 30s
chunk_target_size: 262144 from default 0
```
There was no other config or version change.

If so, can you please share your compactor logs?

**Comment by abhardwaj29** [comment]
Yes those were the only changes I did, no change beyond that.
where can I locate the compactor logs? we are running loki single tenant mode as a statefulset, and I am pretty sure we don't have the persistence.

```
persistence:
  enabled: false
  accessModes:
  - ReadWriteOnce
  size: 10Gi
  annotations: {}
```
