### ISSUE TITLE
Promtail file_sd_configs not reading files

### ISSUE THREAD

**Issue by TBSliver** [grafana/loki#3830]
**Describe the bug**

trying to configure Promtail to use file_sd_configs, I have:

```
# ... snip connection stuff thats working ...
scrape_configs:
# ... snip ...
  - job_name: services
    file_sd_configs:
      - files:
          - /etc/promtail/conf.d/*.yml
        refresh_interval: 10s
    relabel_configs:
      - source_labels:
          - __meta_filepath
        target_label: meta_filepath
```

In my main promtail config, then a file at /etc/promtail/conf.d/something.yml with:

```
---
- labels:
    __path__: /home/user/catalyst.log
    job: some_job_name
    host: some.host.name
```

And its not detecting it, either in the refresh interval, or when restarting promtail. Have I missed something?

**To Reproduce**
* Add the file_sd_configs section to a working promtail/loki setup and restart promtail
* Add a new file with the sd_config as needed in the right place
* Nothing happens, even when restarting

**Expected behavior**
promtail to start 'tailing' the specified logfile

**Environment:**
 - VM on Ubuntu 20.04 LTS

**Screenshots, Promtail config, or terminal output**
See above
