### ISSUE TITLE
minio as S3 Chunk storage + boltdb_shipper not saving any data.

### ISSUE THREAD

**Issue by HannesDampft** [grafana/loki#3831]
**Describe the bug**
After deployment of Loki + Grafana via Helm (loki-stack) as described in the Dokumentation: https://grafana.com/docs/loki/latest/configuration/examples/#almost-zero-dependencies-setup no Data have been saved in the Minio Bucket.

**To Reproduce**
1. created namespace monitoring
2. `helm install loki-stack grafana/loki-stack -f loki-s3-boltdb.yaml -n monitoring`

```
config:
  auth_enabled: false

  server:
    http_listen_port: 3100

  distributor:
    ring:
      kvstore:
        store: memberlist

  ingester:
    lifecycler:
      ring:
        kvstore:
          store: memberlist
        replication_factor: 1
      final_sleep: 0s
    chunk_idle_period: 5m
    chunk_retain_period: 30s

  memberlist:
    abort_if_cluster_join_fails: false

    # Expose this port on all distributor, ingester
    # and querier replicas.
    bind_port: 7946

    # You can use a headless k8s service for all distributor,
    # ingester and querier components.
    join_members:
    - loki-gossip-ring.loki.svc.cluster.local:7946

    max_join_backoff: 1m
    max_join_retries: 10
    min_join_backoff: 1s

  schema_config:
    configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

  storage_config:

    boltdb_shipper:
      active_index_directory: /loki/index
      cache_location: /loki/index_cache
      shared_store: s3

    aws:
      s3: https://loki:password@minio.example.com.:9000/loki
      s3forcepathstyle: true

  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h

  compactor:
    working_directory: /data/compactor
    shared_store: s3
    compaction_interval: 5m

promtail:
  enabled: true

grafana:
  enabled: true 
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 7.5.0

```
 
**Expected behavior**
Expected Loki uses the s3 Storage Bucket as Volume for Chunk and boltdb index files. All Log-Files are in Grafana available via loki, no files are written to minio though.

**Environment:**
 - Infrastructure: 
the k8s helm deploys to a fresh installed kubernetes cluster on bare-metal.
Minio is a distributed miniocluster within the same VLan, pods from the k8s can reach minio.
![loki_grafana](https://user-images.githubusercontent.com/48141543/121369125-e0ff1900-c93b-11eb-97c9-567432c9e07b.png)

 - Deployment tool: deployment is done via Helm

**Screenshots, Promtail config, or terminal output**
i cannot find any logs indicating loki trying to contact minio, which is why i expect some error in the value file handed with helm. I used the file given in the dokumentation under https://grafana.com/docs/loki/latest/configuration/examples/#almost-zero-dependencies-setup. I tried many different alterations of the value file, switching shared_store: to aws etc. but no improvement.

As being new to k8s and Grafana i tried my best to visualize and give as much information you might need. the Problem with connecting to Minio seems common, but solvable. I am unsure, whether it is a simple type or miss structure in the value file or if i am missing something bigger. If you need any further Information, please let me know and i will gladly supply what you need.

best regards

**Comment by dannykopping** [comment]
@HannesDampft hi, is `minio.example.com.` a valid hostname in your cluster?

**Comment by HannesDampft** [comment]
Hello @dannykopping,
thank you for your reply!
no, the minio is not running within the cluster, but within the same VLan. 

in the meantime i did get everything to work. For everyone also wanting to set this up the same way, here what worked for me:

1. there is a minor error in the official loki doku concerning the paths. thanks to prateekkhera ([https://github.com/grafana/loki/issues/2347#issuecomment-657983044](url)) i noticed this for me and changed the config.
2. the layout of my value file for helm was formatted wrong. the complete working config i handed as values for the helm chart are here:

```
loki:
  enabled: true
  config:
    auth_enabled: false

    server:
      http_listen_port: 3100

    distributor:
      ring:
        kvstore:
          store: memberlist

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s

    memberlist:
      abort_if_cluster_join_fails: false

      # Expose this port on all distributor, ingester
      # and querier replicas.
      bind_port: 7946

      # You can use a headless k8s service for all distributor,
      # ingester and querier components.
      join_members:
      - loki-gossip-ring.loki.svc.cluster.local:7946

      max_join_backoff: 1m
      max_join_retries: 10
      min_join_backoff: 1s

    schema_config:
      configs:
      - from: 2021-06-09
        store: boltdb-shipper
        object_store: aws
        schema: v11
        index:
          prefix: index_
          period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/index_cache
        shared_store: s3

      aws:
        s3: https://loki:password@minio.example.com.:9000/loki
        s3forcepathstyle: true

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    compactor:
      working_directory: /data/compactor
      shared_store: s3
      compaction_interval: 5m


promtail:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 6.7.0

prometheus:
  enabled: false

filebeat:
  enabled: false
  filebeatConfig:
    filebeat.yml: |
      # logging.level: debug
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
      output.logstash:
        hosts: ["logstash-loki:5044"]
logstash:
  enabled: false
  image: grafana/logstash-output-loki
  imageTag: 1.0.1
  filters:
    main: |-
      filter {
        if [kubernetes] {
          mutate {
            add_field => {
              "container_name" => "%{[kubernetes][container][name]}"
              "namespace" => "%{[kubernetes][namespace]}"
              "pod" => "%{[kubernetes][pod][name]}"
            }
            replace => { "host" => "%{[kubernetes][node][name]}"}
          }
        }
        mutate {
          remove_field => ["tags"]
        }
      }
  outputs:
    main: |-
      output {
        loki {
          url => "http://loki:3100/loki/api/v1/push"
          #username => "test"
          #password => "test"
        }
        # stdout { codec => rubydebug }
      }
```

thank you guys, it is working flawlessly now. 

best regards!
