### ISSUE TITLE
[promtail] Cannot specify "catch all files" glob for dynamic file discovery

### ISSUE THREAD

**Issue by nfx** [grafana/loki#3844]
**Describe the bug**

Given this very simple file_sd:

```yaml
-
  targets:
  - localhost
  labels:
    job: generic
    __path__: /home/foo/test/**
```

i want to have `/home/foo/test/bar/baz/booze.log` picked up. It's either not supported or not documented. Didn't look at the sources.

**To Reproduce**
1. Started Promtail (version 2.2.1 (branch: HEAD, revision: babea82e))
2. Edited /etc/promtail/fille_sd/generic.yml
3. Saw confirmation of log that job=generic was added

**Expected behavior**
Any files under `/home/foo/test/` should get tailed.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: hands, hammer & ansible
