### ISSUE TITLE
Promtail to remote Loki - context deadline exceeded

### ISSUE THREAD

**Issue by Lithimlin** [grafana/loki#3867]
**Describe the bug**
I'm trying to set up Promtail on mutliple machines which all send the respective logs to a single central Loki instance. Sending logs from the machine hosting Loki to that Loki instance works fine. However, when I try to do the same from another machine, Promtail is unable to send the logs to Loki. Instead, I get the following error in the logs:

```
promtail[78741]: level=warn ts=2021-08-16T09:13:48.848403815Z caller=client.go:323 component=client host=<loki-hostname>:9200 msg="error sending batch, will retry" status=-1 error="Post \"http://<loki-hostname>:9200/loki/api/v1/push\": context deadline exceeded"
promtail[78741]: level=warn ts=2021-08-16T09:14:22.337181145Z caller=client.go:323 component=client host=<loki-hostname>:9200 msg="error sending batch, will retry" status=-1 error="Post \"http://<loki-hostname>:9200/loki/api/v1/push\": dial tcp [<loki-host-ipv6>]:9200: i/o timeout"
```

Since most issues here concerning this issue are about docker and the DNS setting, I've tried inserting the Loki-host's IP directly instead though with no difference in behavior. I've also tried looking into the [code at the line mentioned in the message](https://github.com/grafana/loki/blob/8788ddb8d6bcc00aada2a8c4231bd04e2d890111/clients/pkg/promtail/client/client.go#L245) but I can't really see anything there.
According to https://github.com/grafana/loki/pull/2453, this error message should also be more verbose if I understood correctly.
Nevertheless, I'm not sure if the data processing time is the issue here. Maybe someone else can judge that better.

**Environment:**
 - Infrastructure: Two machines with NixOS in the same subnet; No docker or the like

**To Reproduce**
1. Configured Loki and Promtail (both `grafana-loki-2.2.1`) with the config files found below on Loki-host
2. Built Nix system (Loki-host) (everything working so far)
2. Configured Promtail (also `grafana-loki-2.2.1`) with the config file found below on remote host
3. Built Nix system (remote host)
4. Look at logs on remote host (`journalctl -efu promtail`)

I'm not sure if there would be a big difference between doing this on a NixOS system vs any other Linux system though I don't expect it unless it's a different version of Loki.

**Expected behavior**
Promtail sends the logs to the Loki instance on the Loki-host without issues.

**Screenshots, Promtail config, or terminal output**
Loki-config on Loki-host:
```yaml
auth_enabled: false                                                             
                                                                                   
server:                                                                            
  http_listen_port: 9200                                                        
                                                                                
ingester:                                                                       
  lifecycler:                                                                   
    address: 127.0.0.1                                                          
    ring:                                                                       
      kvstore:                                                                  
        store: inmemory                                                         
      replication_factor: 1                                                     
    final_sleep: 0s                                                             
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0                
                                                                                
schema_config:                                                                  
  configs:
    - from: 2021-01-01
      store: boltdb-shipper                                                     
      object_store: filesystem                                                  
      schema: v11                                                               
      index:                                                                    
        prefix: index_                                                          
        period: 24h                                                             

compactor:                                                                      
  working_directory: /var/lib/loki/compactor                                    
  shared_store: filesystem
                                                                                
storage_config:                                                                 
  boltdb_shipper:                                                               
    active_index_directory: /var/lib/loki/boltdb-shipper-active                 
    cache_location: /var/lib/loki/boltdb-shipper-cache                          
    cache_ttl: 24h
    shared_store: filesystem                                                    
                                                                                
  filesystem:                                                                   
    directory: /var/lib/loki/chunks                                             
                                                                                
limits_config:                                                                  
  reject_old_samples: true                                                      
  reject_old_samples_max_age: 168h                                              
                                                                                
chunk_store_config:                                                             
  max_look_back_period: 0s                                                      
                                                                                
table_manager:                                                                  
  retention_deletes_enabled: false                                              
  retention_period: 0s
```
`promtail.nix` file on both Loki-host and remote host:
```nix
{pkgs, ...}:
{
  services.promtail = { 
    enable = true;
    configuration = { 
      server = { 
        http_listen_port = 9080;
        grpc_listen_port = 0;
      };  
      positions = { 
        filename = "/tmp/positions.yaml";
      };  
      clients = [ { url = "http://<loki-hostname>:9200/loki/api/v1/push"; } ];
      scrape_configs = [ { 
        job_name = "journal";
        journal = { 
          max_age = "12h";
          labels = { 
            job = "systemd-journal";
          };
        };
        relabel_configs = [ 
          {
            source_labels = ["__journal__systemd_unit"];
            target_label = "unit";
          }
          {
            source_labels = ["__journal__hostname"];
            target_label = "host";
          }
          {
            source_labels = ["__journal_syslog_identifier"];
            target_label = "syslog_identifier";
          }
        ];
      } ];
    };  
  };  
}

```

EDIT: Updated configs to reflect changes in NixOS 21.05
EDIT: Added i/o timeout error
