### ISSUE TITLE
`split_queries_by_interval` not work on monolithic mode

### ISSUE THREAD

**Issue by lemon-li** [grafana/loki#3869]
The query not run on multiple core ...
The following is the loki conf file that I've specified:
```yaml
auth_enabled: false

server:
  http_listen_address: {{ env "NOMAD_IP_http" }}
  http_listen_port: {{ env "NOMAD_PORT_http" }}

ingester:
  lifecycler:
    interface_names:
      - ens5                  # Amazon EC2
      - eth0
      - en0
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    min_ready_duration: 30s
    final_sleep: 30s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-11-11
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb:
    directory: /loki/boltdb
  filesystem:
    directory: /loki/chunks

# https://grafana.com/docs/loki/latest/configuration/#queryrange_config
query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  # parallelize queries in 30m intervals
  split_queries_by_interval: 30m

chunk_store_config:
  max_look_back_period: [[.retention_period]]

table_manager:
  retention_deletes_enabled: true
  retention_period: [[.retention_period]]
```
