### ISSUE TITLE
Promtail errors when trying to remove non-existent inotify watch

### ISSUE THREAD

**Issue by peterroelants** [grafana/loki#3874]
**Describe the bug**
I'm seeing a lot of the following errors in my promtail logs:
```
level=error ts=2021-06-22T07:40:15.119569083Z caller=filetarget.go:264 msg=" failed to remove directory from watcher" error="can't remove non-existent inotify watch for: /var/lib/docker/containers/bec616cace9feae05d03ad8bf2642c5ce26c41dd88fe4e88cabfe2c57d6dc210"
```

**To Reproduce**
I have a system that:
1. Starts Loki (`grafana/loki:2.2.1`)
2. Starts Promtail (`grafana/promtail:2.2.1`)
3. Starts and stop containers

I think the last part (3) is crucial to the error. My system runs a lot of short-running containers that finish after each task. I think promtail is monitoring these containers by placing an inotify watch. However, after the container has stopped running and is removed, Promtail tries to remove the non-existent inotify watch and errors as a result.

**Expected behavior**
No error when trying to remove a non-existent inotify watch for a removed container.

**Environment:**
 - Infrastructure: Laptop & EC2 instance
 - Deployment tool: docker-compose

**Screenshots, Promtail config, or terminal output**

More of these logs:
```
monitoring-promtail_1                | level=error ts=2021-06-22T07:40:15.119569083Z caller=filetarget.go:264 msg=" failed to remove directory from watcher" error="can't remove non-existent inotify watch for: /var/lib/docker/containers/bec616cace9feae05d03ad8bf2642c5ce26c41dd88fe4e88cabfe2c57d6dc210"
monitoring-promtail_1                | level=error ts=2021-06-22T07:39:15.119037948Z caller=filetarget.go:264 msg=" failed to remove directory from watcher" error="can't remove non-existent inotify watch for: /var/lib/docker/containers/6973a6b47f7f82bd54c98a986b56c4d61c2511e8e6158a2ec802319e4c6ecc47"
monitoring-promtail_1                | level=error ts=2021-06-22T07:38:15.118819419Z caller=filetarget.go:264 msg=" failed to remove directory from watcher" error="can't remove non-existent inotify watch for: /var/lib/docker/containers/43fc346d7803576e33bb427d28445c2955256bbdb09a0be2540b9580f4b2955b"
monitoring-promtail_1                | level=error ts=2021-06-22T07:37:15.119397358Z caller=filetarget.go:264 msg=" failed to remove directory from watcher" error="can't remove non-existent inotify watch for: /var/lib/docker/containers/cb8d0c8a2febf20a56cf2413be0d2f20d7cc10333af17adc0327905a3f4890e6"
monitoring-promtail_1                | level=error ts=2021-06-22T07:36:15.119147472Z caller=filetarget.go:264 msg=" failed to remove directory from watcher" error="can't remove non-existent inotify watch for: /var/lib/docker/containers/502e4a2f51dc5675649b228644167ba70834fc3f91680c91029539a7244704c6"
monitoring-promtail_1                | level=error ts=2021-06-22T07:35:25.11851982Z caller=filetarget.go:264 msg=" failed to remove directory from watcher" error="can't remove non-existent inotify watch for: /var/lib/docker/containers/da3f0c7237f46f0f80516bfb388105921b3a21a3568d39a8e149b25da2539ce9"
monitoring-promtail_1                | level=error ts=2021-06-22T07:35:25.118553981Z caller=filetarget.go:264 msg=" failed to remove directory from watcher" error="can't remove non-existent inotify watch for: /var/lib/docker/containers/c2d719f35237535ab8359534ff08fa4110564bc9340fdcadf1e44ab804920470"
monitoring-promtail_1                | level=error ts=2021-06-22T07:35:15.118855693Z caller=filetarget.go:264 msg=" failed to remove directory from watcher" error="can't remove non-existent inotify watch for: /var/lib/docker/containers/0b5160208498b12b29bf132bac0dc9f0651f26e89313102af2d792dd3dfe5b69"
monitoring-promtail_1                | level=error ts=2021-06-22T07:35:15.118891544Z caller=filetarget.go:264 msg=" failed to remove directory from watcher" error="can't remove non-existent inotify watch for: /var/lib/docker/containers/e86049a1d67daa9a40b4be66d7f4b1206b20950fb618615b271af1d85d548af3"
```

Promtail config:
```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://monitoring-loki:3100/loki/api/v1/push

scrape_configs:
# System logs
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log
# Docker logs
- job_name: docker
  static_configs:
  - targets:
      - localhost
    labels:
      job: dockerlogs
      __path__: /var/lib/docker/containers/*/*.log
  pipeline_stages:
    # Extract container ID from filename
    - match:
        selector: '{job="dockerlogs"}'
        stages:
          - regex:
              source: filename
              expression: "/var/lib/docker/containers/(?P<container_id>\\S+)/\\S+.log"
          - labels:
              container_id:
```
