### ISSUE TITLE
Promtail crashing on ubuntu 18.04

### ISSUE THREAD

**Issue by markylaing** [grafana/loki#3878]
**Describe the bug**
Promtail process crashes after a few minutes when running either locally or with docker/docker-compose. The logs suggest that it is running out of memory.

**To Reproduce**
Follow the steps at either https://grafana.com/docs/loki/latest/installation/docker/ or at https://grafana.com/docs/loki/latest/installation/local/.

**Expected behavior**
Promtail to run without issues.

**Environment:**
 - Infrastructure: Virtual machine
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
$ free -g
              total        used        free      shared  buff/cache   available
Mem:             62           0          61           0           0          61
Swap:             0           0           0

```
 - Deployment tool: local, docker, docker-compose

**Screenshots, Promtail config, or terminal output**
I've attached the logs of the promtail container from the attempted docker-compose installation.
[promtail-log.txt](https://github.com/grafana/loki/files/6693883/promtail-log.txt)

**Comment by dannykopping** [comment]
Hi @markylaing - this is not an issue with Promtail itself; you'll need to add more memory to allow processes to run without being reaped by the kernel's Out-of-Memory killer.

**Comment by markylaing** [comment]
Hi @dannykopping, thanks for getting back to me. As you can see from the output of `free -g` in the original issue, I already have 61Gb of free memory on my machine. Are you saying that promtail requires more than 64Gb of memory to run? That seems like a lot. If this is truly the case, perhaps some documentation on requirements might be a good idea?

**Comment by dannykopping** [comment]
Haha I missed the `-g`, apologies!

Promtail should certainly not require that amount of memory. This is probably some OS-related issue.
Do you have any memory limits in place in your docker configuration?

**Comment by markylaing** [comment]
No worries!

I haven't configured docker so it's just the default configuration (for which I believe there are no memory limits).
```
$ docker --version
Docker version 20.10.7, build f0df350
```
I've also tried running the promtail binary directly following [this example](https://grafana.com/docs/loki/latest/installation/local/) and I had the same issue.

**Comment by dannykopping** [comment]
Could you please send through your (redacted) syslog/kern.log/dockerd log around the time when Promtail gets OOM-killed?

**Comment by markylaing** [comment]
Here are the logs starting from when I ran `docker-compose up` until after promtail died:

[dockerd.log](https://github.com/grafana/loki/files/6754371/dockerd.log)
[kernel.log](https://github.com/grafana/loki/files/6754372/kernel.1.log)
[syslog.log](https://github.com/grafana/loki/files/6754373/syslog.1.log)

Below is the `docker-compose.yaml` I used:
```yaml
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
```
