### ISSUE TITLE
minimal config to use loki as log storage for more then 20 microservices

### ISSUE THREAD

**Issue by vtolstov** [grafana/loki#388]
I have more then 20 microservices (not kubernetes) and i want to use loki to write logs via api to it with the same labels as like own exporter for Prometheus.
What minimal config I can use for this? Ideally i don't have static services, so i can't use static config that contains all the stuff.
Does it look like this
```
auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          store: inmemory
          replication_factor: 1
      chunk_idle_period: 15m
    schema_config:
      configs:
        - from: 0
          store: boltdb
          object_store: filesystem
          schema: v9
          index:
            prefix: index_
            period: 168h
    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks
    limits_config:
      enforce_metric_name: false
```
