### ISSUE TITLE
Loki is deleting all streams rather than per-stream

### ISSUE THREAD

**Issue by atrinh567** [grafana/loki#3881]
**Describe the bug**
Loki is not deleting filtered stream, but all streams. I've pasted my Loki config below that is suppose to apply a retention period to all streams that include that label. Am I missing something?

**To Reproduce**
```
    auth_enabled: false

    server:
      http_listen_port: 3100

    distributor:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      ingestion_rate_mb: 8
      ingestion_burst_size_mb: 10
      max_query_parallelism: 32
      retention_period: 8760h
      retention_stream:
      - selector: '{app="sample-app"}'
        priority: 1
        period: 24h

    schema_config:
      configs:
        - from: 2021-01-01
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
            tags:
              component: loki

    storage_config:
      boltdb_shipper:
        shared_store: aws
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h

      aws:
        s3: s3://us-east-1/<some-loki-chunk-store-name>

    query_range:
      align_queries_with_step: true
      max_retries: 5
      split_queries_by_interval: 15m
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h

    frontend_worker:
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
      grpc_client_config:
          max_send_msg_size: 1.048576e+08
      parallelism: 6

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      tail_proxy_url: http://{{ include "loki.querierFullname" . }}.loki.svc.cluster.local:3100

    compactor:
      working_directory: /var/loki/compactor
      shared_store: aws
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 1m
      retention_delete_worker_count: 150

    ruler:
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      alertmanager_url: https://alertmanager.xx
      external_url: https://alertmanager.xx
```

**Expected behavior**
Only specified streams should be deleted, otherwise the global policy is applied (8760h)

**Environment:**

**Screenshots, Promtail config, or terminal output**
