### ISSUE TITLE
loki distributor does not use the configured consul host

### ISSUE THREAD

**Issue by dgsb** [grafana/loki#3885]
**Describe the bug**
loki distributor does not use the configured consul host

**To Reproduce**
1. Use this configuration file name loki-distributor-config.yaml
```yaml
target: distributor

distributor:
  ring:
    kvstore:
      store: consul
      consul:
        host: consul:8500

schema_config:
  configs:
    - from: 1976-02-28
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: aws
  aws:
    s3: minio
    bucketnames: loki
    access_key_id: minioadmin
    secret_access_key: minioadmin
```

2. start loki distributor with the following command line
```
docker run -v $(pwd)/loki-distributor-config.yaml:/etc/loki/distributor-config.yaml grafana/loki:2.2.1 -config.file /etc/loki/distributor-config.yaml
```

We have then the following traces:
```
level=info ts=2021-06-23T10:01:33.0509216Z caller=loki.go:248 msg="Loki started"
level=error ts=2021-06-23T10:01:33.0523364Z caller=client.go:234 msg="error getting path" key=collectors/ring err="Get \"http://localhost:8500/v1/kv/collectors/ring?stale=&wait=10000ms\": dial tcp 127.0.0.1:8500: connect: connection refused"
level=error ts=2021-06-23T10:01:34.2834968Z caller=client.go:234 msg="error getting path" key=collectors/ring err="Get \"http://localhost:8500/v1/kv/collectors/ring?stale=&wait=10000ms\": dial tcp 127.0.0.1:8500: connect: connection refused"
```

**Expected behavior**
The loki distributor should try to reach `http://consul:8500/` instead.

**Environment:**
 - Infrastructure: docker-compose on osx laptop
 - Deployment tool: docker-compose
