### ISSUE TITLE
Gracefully stopping containers get panic for query-frontend

### ISSUE THREAD

**Issue by lemon-li** [grafana/loki#3890]
There is no panic with versions before **v2.1.0**, and panic occurs in **v2.2.0** and **v2.2.1**
I use the master branch to build the docker image and it works fine

kill command: 
`docker kill -s SIGTERM f2164bc1b962`

error message:
```
docker logs -f f2164bc1b962
level=info ts=2021-06-24T12:13:42.850288Z caller=main.go:130 msg="Starting Loki" version="(version=2.2.1, branch=HEAD, revision=babea82ef)"
level=info ts=2021-06-24T12:13:42.8507079Z caller=server.go:229 http=127.0.0.1:3111 grpc=127.0.0.1:26625 msg="server listening on addresses"
level=debug ts=2021-06-24T12:13:42.8508181Z caller=modules.go:377 msg="initializing query frontend" config="{Handler:{LogQueriesLongerThan:5s MaxBodySize:10485760 QueryStatsEnabled:false} FrontendV1:{MaxOutstandingPerTenant:100} CompressResponses:true DownstreamURL:http://loki.service.consul:3100 TailProxyURL:}"
level=debug ts=2021-06-24T12:13:42.8508799Z caller=modules.go:394 msg="initializing query range tripperware" config="{Config:{SplitQueriesByInterval:15m0s SplitQueriesByDay:false AlignQueriesWithStep:true ResultsCacheConfig:{CacheConfig:{EnableFifoCache:false DefaultValidity:0s Background:{WriteBackGoroutines:10 WriteBackBuffer:10000} Memcache:{Expiration:0s BatchSize:1024 Parallelism:100} MemcacheClient:{Host: Service:memcached Addresses: Timeout:100ms MaxIdleConns:16 UpdateInterval:1m0s ConsistentHash:true CBFailures:10 CBTimeout:10s CBInterval:10s} Redis:{Endpoint: MasterName: Timeout:500ms Expiration:0s DB:0 PoolSize:0 Password: EnableTLS:false InsecureSkipVerify:false IdleTimeout:0s MaxConnAge:0s} Fifocache:{MaxSizeBytes: MaxSizeItems:0 Validity:0s DeprecatedSize:0} Prefix:frontend. Cache:<nil>} Compression:} CacheResults:false MaxRetries:5 ShardedQueries:false}}" limits="{IngestionRateStrategy:local IngestionRateMB:4 IngestionBurstSizeMB:6 MaxLabelNameLength:1024 MaxLabelValueLength:2048 MaxLabelNamesPerSeries:30 RejectOldSamples:false RejectOldSamplesMaxAge:336h0m0s CreationGracePeriod:10m0s EnforceMetricName:true MaxLineSize:0B MaxLocalStreamsPerUser:10000 MaxGlobalStreamsPerUser:0 MaxChunksPerQuery:2000000 MaxQuerySeries:500 MaxQueryLookback:0s MaxQueryLength:0s MaxQueryParallelism:14 CardinalityLimit:100000 MaxStreamsMatchersPerQuery:1000 MaxConcurrentTailRequests:10 MaxEntriesLimitPerQuery:5000 MaxCacheFreshness:1m0s QuerySplitDuration:0s RulerEvaluationDelay:0s RulerMaxRulesPerRuleGroup:0 RulerMaxRuleGroupsPerTenant:0 PerTenantOverrideConfig: PerTenantOverridePeriod:10s}"
level=debug ts=2021-06-24T12:13:42.8519017Z caller=module_service.go:49 msg="module waiting for initialization" module=query-frontend waiting_for=server
level=info ts=2021-06-24T12:13:42.8519381Z caller=module_service.go:59 msg=initialising module=server
level=info ts=2021-06-24T12:13:42.8519894Z caller=module_service.go:59 msg=initialising module=query-frontend
level=info ts=2021-06-24T12:13:42.8520153Z caller=loki.go:248 msg="Loki started"
level=debug ts=2021-06-24T12:13:52.7751206Z caller=logging.go:66 traceID=1ecf7bcb1db6d3e6 msg="GET /ready (200) 47.2µs"
level=info ts=2021-06-24T12:13:57.0862036Z caller=signals.go:55 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=debug ts=2021-06-24T12:13:57.0863546Z caller=module_service.go:81 msg=stopping module=query-frontend
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1db7f2f]

goroutine 324 [running]:
github.com/cortexproject/cortex/pkg/frontend/v1.(*Frontend).Close(...)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/frontend/v1/frontend.go:98
github.com/grafana/loki/pkg/loki.(*Loki).initQueryFrontend.func2(0x0, 0x0, 0x3, 0xc0000f7f78)
	/src/loki/pkg/loki/modules.go:463 +0x2f
github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main(0xc00070e2d0)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:184 +0x309
created by github.com/cortexproject/cortex/pkg/util/services.(*BasicService).StartAsync.func1
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:96 +0xad
```

The following is the loki conf file that I've specified:
```yaml
target: query-frontend
auth_enabled: false

server:
  http_listen_address: xxxxx
  http_listen_port: xxxxxx

schema_config:
  configs:
    - from: 2020-11-11
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# https://grafana.com/docs/loki/latest/configuration/#queryrange_config
query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  # parallelize queries in 15min intervals
  split_queries_by_interval: 15m

querier:
  query_ingesters_within: 2h

frontend:
  log_queries_longer_than: 5s
  downstream_url: http://loki.service.consul:3100
  compress_responses: true
```
