### ISSUE TITLE
Unable to retrieve older data (time range of available data variates - last 1h, 1h30m, 30m, etc.)

### ISSUE THREAD

**Issue by twix14** [grafana/loki#3896]
**Describe the bug**
Can't retrieve logs older than 1h, sometimes 45m, sometimes 15m. We have tested this using Grafana's Loki Datasource and through the API, the results are the same. Chunks are being written to S3 and we don't see any HTTP errors in the logs, after turning debug on. 

We thought the issue might have been related to our table_manager.retention_period being 120h, which is not a multiple of the default chunks.period 168h, but no luck when updating the retention period to 168h too.

The issue is probably related with S3 chunks retrieval and querier is only able to retrieve in memory data.

[The same issue as this comment](https://github.com/grafana/loki/issues/2148#issuecomment-822178857)

**To Reproduce**
1. Started Loki (2.2.0)
2. Config:

```yaml
auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  grpc_server_max_recv_msg_size: 8388608
  grpc_server_max_send_msg_size: 8388608

distributor:
  ring:
    kvstore:
      store: memberlist

memberlist:
  bind_port: 7946
  join_members:
    - loki-memberlist

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  chunk_idle_period: 30m
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_retain_period: 1m
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /var/loki/wal
    replay_memory_ceiling: 4GB 

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m

schema_config:
  configs:
    - from: 2021-05-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: loki_index_
        period: 24h
    - from: 2021-05-14
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  boltdb_shipper:
    shared_store: filesystem
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    cache_ttl: 168h
  aws:
    bucketnames: loki
    region: eu-west-1
    insecure: false
    sse_encryption: false
    http_config:
      idle_conn_timeout: 90s
      response_header_timeout: 0s
      insecure_skip_verify: false
    s3forcepathstyle: true
  filesystem:
    directory: /var/loki/chunks

chunk_store_config:
  max_look_back_period: 168h

table_manager:
  retention_deletes_enabled: false
  retention_period: 168h

query_range:
  align_queries_with_step: true
  max_retries: 5
  split_queries_by_interval: 15m
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 1024
        validity: 24h

frontend_worker:
  frontend_address: loki-query-frontend:9095

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  tail_proxy_url: http://loki-querier.observability.svc.cluster.local:3100

compactor:
  working_directory: /var/loki/compactor
  shared_store: filesystem
```

**Expected behavior**
We should be able to see logs for a maximum of 168h (chunk_store_config.max_look_back_period)

**Environment:**
 - Infrastructure: Kubernetes
 - Mode: microservices

**Screenshots, Promtail config, or terminal output**
Logs from the last 1h30m, but there should be more results since the query was for the last 7 days. If we run the exact same query 1h later, results might be different.

<img width="1361" alt="Screenshot 2021-06-22 at 18 29 07" src="https://user-images.githubusercontent.com/25937180/123290727-69b7b080-d509-11eb-9679-46c95935cfdd.png">

Older logs, all chunks must be stored in S3 and no data is shown.

<img width="1359" alt="Screenshot 2021-06-22 at 18 34 38" src="https://user-images.githubusercontent.com/25937180/123290866-83f18e80-d509-11eb-9482-812f0c3cbb9e.png">
