### ISSUE TITLE
Promtail drops entries when distributor/ingester goes down

### ISSUE THREAD

**Issue by kekscode** [grafana/loki#3903]
**Describe the bug**

Mgmt. summary: Promtail apparently drops some logs when ingester(s) become unavailable.

Description:

When ingester(s) go down or become unavailable via network, we get the following error with `status=-1` in promtail:

```
2021-06-23T17:51:08.472460304Z level=warn ts=2021-06-23T17:51:08.472396678Z
caller=client.go:323 component=client
host=loki-distributor.kargo-openshift-logging.svc:3100 msg="error sending batch,
will retry" status=-1 error="Post
\"http://loki-distributor.kargo-openshift-logging.svc:3100/loki/api/v1/push\":
context deadline exceeded"
```

At the same time, the metric `promtail_dropped_entries_total` increases, indicating that entries from the batch (maybe inflight) get dropped in `c.send(...)` and the retry logic in `c.sendBatch(...)` is skipped.

Some observations:

Maybe i'm wrong, but this code from the retry logic:

```go
// Only retry 429s, 500s and connection-level errors.
if status > 0 && status != 429 && status/100 != 5 {
    break
}
```

does not apply in this case, because status is `-1` according to the log and retries do not work in that case and the code path `final error sending batch` gets triggered. I see the retry logic logging `[...] error sending batch, will retry [...]` continuously AFTER the`promtail_dropped_entries_total` got increased once. After this happens, the retry logic works and no drops are shown in the metrics anymore.

When the ingesters become available again, the promtails start working again.

**To Reproduce**

We use https://github.com/grafana/helm-charts/commits/main/charts/loki-distributed as a base and start Loki as a distributed system with:

- 1 promtail per Kubernetes node
- 6 distributors
- 6 ingesters

In order to reproduce the bug, it does not seem to matter how many distributors/ingesters are available as long as they are up and running.

1. Started Loki components `v2.2.1`
2. Started Promtail daemonset `v2.2.1`

**Expected behavior**

In case of ingester unavailability, we should not loose log lines.

**Environment:**

 - RedHat OpenShift `4.7.12`
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**

 Grafana visualization of the `promtail_dropped_entries_total` metric increases:

![image](https://user-images.githubusercontent.com/803252/123414422-25cdb580-d5b4-11eb-8f39-6b25b4f55e28.png)

Promtail config:

Note: Setting `debug` or `info` log level or adding/removing `client :null` does not make a difference regarding the described behaviour.

```
server:
  log_level: debug
  http_listen_port: 3101

client: null

clients:
  - url: http://loki-distributor.kargo-openshift-logging.svc:3100/loki/api/v1/push
    backoff_config:
      min_period: 100ms
      max_period: 10s
      max_retries: 0 # 0 means: unlimited retries

positions:
  filename: /run/promtail/positions.yaml

scrape_configs:
  # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
  
  # Pods with a label 'app.kubernetes.io/name'
  - job_name: kubernetes-pods-app-kubernetes-io-name
    pipeline_stages:
      - cri: {}
      - tenant:
          source: namespace
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_name
        target_label: app
      - action: drop
        regex: ''
        source_labels:
          - app
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_component
        target_label: component
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - namespace
        - app
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        regex: true/(.*)
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: drop
        regex: "true"
        source_labels:
        - __meta_kubernetes_pod_label_observability_drop_log
  
  # Pods with a label 'app'
  - job_name: kubernetes-pods-app
    pipeline_stages:
      - cri: {}
      - tenant:
          source: namespace
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      # Drop pods with label 'app.kubernetes.io/name'. They are already considered above
      - action: drop
        regex: .+
        source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_name
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_label_app
        target_label: app
      - action: drop
        regex: ''
        source_labels:
          - app
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_label_component
        target_label: component
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - namespace
        - app
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        regex: true/(.*)
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: drop
        regex: "true"
        source_labels:
        - __meta_kubernetes_pod_label_observability_drop_log
  
  # Pods with direct controllers, such as StatefulSet
  - job_name: kubernetes-pods-direct-controllers
    pipeline_stages:
      - cri: {}
      - tenant:
          source: namespace
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      # Drop pods with label 'app.kubernetes.io/name' or 'app'. They are already considered above
      - action: drop
        regex: .+
        separator: ''
        source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_name
          - __meta_kubernetes_pod_label_app
      - action: drop
        regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
        source_labels:
          - __meta_kubernetes_pod_controller_name
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_controller_name
        target_label: app
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - namespace
        - app
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        regex: true/(.*)
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: drop
        regex: "true"
        source_labels:
        - __meta_kubernetes_pod_label_observability_drop_log
  
  # Pods with indirect controllers, such as Deployment
  - job_name: kubernetes-pods-indirect-controller
    pipeline_stages:
      - cri: {}
      - tenant:
          source: namespace
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      # Drop pods with label 'app.kubernetes.io/name' or 'app'. They are already considered above
      - action: drop
        regex: .+
        separator: ''
        source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_name
          - __meta_kubernetes_pod_label_app
      - action: keep
        regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
        source_labels:
          - __meta_kubernetes_pod_controller_name
      - action: replace
        regex: '([0-9a-z-.]+)-[0-9a-f]{8,10}'
        source_labels:
          - __meta_kubernetes_pod_controller_name
        target_label: app
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - namespace
        - app
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        regex: true/(.*)
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: drop
        regex: "true"
        source_labels:
        - __meta_kubernetes_pod_label_observability_drop_log
  # All remaining pods not yet covered
  - job_name: kubernetes-other
    pipeline_stages:
      - cri: {}
      - tenant:
          source: namespace
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      # Drop what has already been covered
      - action: drop
        regex: .+
        separator: ''
        source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_name
          - __meta_kubernetes_pod_label_app
      - action: drop
        regex: .+
        source_labels:
          - __meta_kubernetes_pod_controller_name
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: app
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_label_component
        target_label: component
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - namespace
        - app
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        regex: true/(.*)
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: drop
        regex: "true"
        source_labels:
        - __meta_kubernetes_pod_label_observability_drop_log

```

Loki configmap:

```
auth_enabled: true
chunk_store_config:
  chunk_cache_config:
    memcached:
      batch_size: 1024
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: 'loki-memcached-chunks'
      service: http
  max_look_back_period: 768h
compactor:
  shared_store: s3
distributor:
  ring:
    kvstore:
      store: memberlist
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  max_outstanding_per_tenant: 1024
  tail_proxy_url: http://loki-querier:3100
frontend_worker:
  frontend_address: 'loki-query-frontend:9095'
  parallelism: 2
ingester:
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_idle_period: 30m
  chunk_retain_period: 1m
  chunk_target_size: 1536000
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 2
  max_chunk_age: 1h
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  max_cache_freshness_per_query: 10m
  max_entries_limit_per_query: 5000
  max_global_streams_per_user: 10000
  max_query_length: 12000h
  max_query_parallelism: 16
  max_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 168h
memberlist:
  abort_if_cluster_join_fails: true
  bind_port: 7946
  join_members:
  - 'loki-memberlist.kargo-openshift-logging.svc.cluster.local:7946'
  max_join_backoff: 1m
  max_join_retries: 10
  min_join_backoff: 1s
querier:
  engine:
    max_look_back_period: 30s
    timeout: 3m
  extra_query_delay: 0s
  query_ingesters_within: 3h
  query_timeout: 10m
  tail_max_duration: 1h
query_range:
  align_queries_with_step: true
  cache_results: true
  max_retries: 5
  parallelise_shardable_queries: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_bytes: 1024MB
        validity: 24h
      memcached_client:
        consistent_hash: true
        host: 'loki-memcached-frontend'
        max_idle_conns: 16
        service: http
        timeout: 500ms
        update_interval: 1m
  split_queries_by_interval: 240h
ruler:
  alertmanager_url: http://alertmanager
  enable_alertmanager_v2: true
  ring:
    kvstore:
      store: memberlist
  rule_path: /tmp/loki/scratch
  storage:
    local:
      directory: /etc/loki/rules
    type: local
schema_config:
  configs:
  - from: "2020-09-07"
    index:
      period: 24h
      prefix: loki_index_
    object_store: aws
    schema: v11
    store: boltdb-shipper
server:
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_listen_port: 3100
  log_level: info
storage_config:
  aws:
    s3: s3://eu-central-1/<redacted>
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    shared_store: s3
  index_queries_cache_config:
    memcached:
      batch_size: 1024
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: 'loki-memcached-index-queries'
      service: http
table_manager:
  retention_deletes_enabled: true
  retention_period: 32d
tracing:
  enabled: false
```
