### ISSUE TITLE
Can't Use Cache when Running Large Metric Queries

### ISSUE THREAD

**Issue by M3r1** [grafana/loki#3912]
My team and I are struggling for a few days now to implement the results_cache feature with memcached of the query-frontend. 

I'm running the following query:
`sum(count_over_time({job="$job",host="$host"}[10m]))`

When running the query in a small time range (up to 2 days) the cache works as expected, the first query takes a while and after refreshing the search (in Grafana) the query results is extremely fast and i'm seeing results being fetched from memcached.

However, when running a large query (a week) after getting an initial result the second consecutive search (a refresh) immediately returns "merging responses requires at least one response".
In query-frontend i'm getting the log line (addresses are hidden since we are working on a private, separate network):
> Jul 1 15:27:31 lokiqf01 loki-linux-amd64: level=warn ts=2021-07-01T12:27:31.416882085Z caller=logging.go:71 traceID=2344ebe78c7e9f70 msg="GET /loki/api/v1/query_range?direction=BACKWARDS&limit=308&query=sum(count_over_time(%7Bjob%3D22$job%22%7D%5B1m%5D))&start=1624537651000000000&end=1625142452000000000&step=1800 (500) 6.677937ms Response: \"merging responses requires at least one response\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-US,en;q=0.5; Connection: close; User-Agent: Grafana/8.0.3; X-Forwarded-For: an_ip_address, the_same_ip_address; X-Forwarded-For: Grafan's_ip_address; X-Grafana-Org-Id: 1; "

The issue repeated itself when:
- We used in-memory cache for the results cache.
- We downgraded to 1 query-frontend down-streaming queries to 1 querier.

Our loki configuration yaml:

```
auth_enabled: false

server:
  graceful_shutdown_timeout: 5s
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_listen_port: 3100,
  http_server_idle_timeout: 120s,
  http_server_write_timeout: 1m 

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  chunk_encoding: snappy
  chunk_block_size: 262144
  chunk_target_size: 1536000
  chunk_idle_period: 15m
  lifecycler:
    heartbeat_period: 5s
    join_after: 30s
    num_tokens: 512
    ring:
      heartbeat_timeout: 1m
      kvstore:
        store: memberlist
      replication_factor: 3
    final_sleep: 0s
  max_transfer_retries: 60

ingester_client:
  grpc_client_config:
    max_recv_msg_size: 67108864
  remote_timeout: 1s

frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  max_outstanding_per_tenant: 1024

frontend_worker:
  frontend_address: frontend:9096
  grpc_client_config:
    max_send_msg_size: 104857600
  parallelism: 12

limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: 10
  ingestion_rate_mb: 5
  ingestion_rate_strategy: local
  max_cache_freshness_per_query: 10m
  max_global_streams_per_user: 10000
  max_query_length: 12000h
  max_query_parallelism: 256
  max_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 168h

querier:
  query_ingesters_within: 2h

query_range:
  align_queries_with_step: true
  cache_results: true
  max_retries: 5 
  parallelise_shardable_queries: true
  results_cache:
    cache:
      memcached_client:
        consistent_hash: true
        host: memcachedhost
        max_idle_conns: 16
        service: memcached
        timeout: 500ms
        update_interval: 1m
  split_queries_by_interval: 30m

schema_config:
  configs:
    - from: 2020-06-10
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: test_
        period: 24h

storage_config:
  aws:
    bucketnames: bucket_names
    endpoint: endpoint
    region: region
    access_key_id: mysecret_key_id
    secret_access_key: mysecret_access_key
    http_config:
      idle_conn_timeout: 90s
      response_header_timeout: 0s
      insecure_skip_verify: true
    s3forcepathstyle: true
  boltdb-shipper:
    active_index_directory /opt/loki/boltdb-shipper-active
    cache_location /opt/loki/boltdb-shipper-cache
    shared_store: s3
 
memberlist:
   abort_if_cluster_join_fails: false
   bind_addr:
     - the_bind_ip_address
   bind_port: 7946
   join_members:
     - ip_address:7946
     - off_all_the_loki_components:7946 
```

We are running loki 2.2.1 release.
Loki is deployed on vms.
We have: 
- 2 query-frontends
- 2 queriers
- 3 ingesters
- 2 distributers

Any help, even with debugging this would be greatly appreciated.
