### ISSUE TITLE
Docs feedback: /clients/promtail/stages/template.md

### ISSUE THREAD

**Issue by AverageMarcus** [grafana/loki#3939]
The example for `regexReplaceAll` is actually for `regexReplaceAllLiteral` and doesn't include an example of the `$1` syntax explained in the paragraph.

I _think_ the example should look something like:
```yaml
- template:
    source: output
    template: '{{ regexReplaceAll "(a*)bc" .Value "$1a" }}'
```
But I'm not sure. If someone is able to confirm I'll happily open a PR to update.
