### ISSUE TITLE
Loki docker: panic

### ISSUE THREAD

**Issue by Lithimlin** [grafana/loki#3959]
**Describe the bug**
I'm trying to get Loki to work in Docker. I'm using the default config as found in [this tutorial](https://grafana.com/docs/loki/latest/installation/docker/). I only adjusted the compose file a bit but am using the config files as they are in the tutorial.
However, according to the logs, Loki runs into a segmentation violation and panics.

**To Reproduce**
1. Follow the linked tutorial for docker-compose with the compose file below
2. Inspect the Loki logs

**Expected behavior**
Loki starts and runs without a panic and segmentation violation

**Environment:**
 - Infrastructure: docker-compose on a Raspberry Pi 4 (ARM64v8)

**docker-compose file and log output**
Compose file:
```yaml
version: '3.5'

networks:
  monitor-net:
    name: monitor-net

  loki:
    name: monitor-loki

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
     - 3000:3000
    volumes:
     - ~/volumes/grafana:/var/lib/grafana
    user: "104"
    networks:
     - loki
     - monitor-net

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    command: -config.file=/mnt/config/loki-config.yaml
    ports:
     - 3100:3100
    volumes:
     - ./volumes/loki/config:/mnt/config
    networks:
     - loki
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    command: -config.file=/mnt/config/promtail-config.yaml
    volumes:
     - /var/log:/var/log
     - ./volumes/promtail/config:/mnt/config
    networks:
     - loki
```

Log output:
```
level=info ts=2021-07-07T13:38:24.508047579Z caller=main.go:129 msg="Starting Loki" version="(version=, branch=, revision=)"
level=info ts=2021-07-07T13:38:24.509155991Z caller=server.go:239 http=[::]:3100 grpc=[::]:9096 msg="server listening on addresses"
level=info ts=2021-07-07T13:38:24.511884456Z caller=shipper_index_client.go:108 msg="starting boltdb shipper in 0 mode"
level=info ts=2021-07-07T13:38:24.510780007Z caller=table_manager.go:171 msg="uploading tables"
level=info ts=2021-07-07T13:38:24.51846476Z caller=mapper.go:46 msg="cleaning up mapped rules directory" path=/tmp/loki/rules-temp
level=error ts=2021-07-07T13:38:24.518674961Z caller=mapper.go:50 msg="unable to read rules directory" path=/tmp/loki/rules-temp err="open /tmp/loki/rules-temp: no such file or directory"
level=info ts=2021-07-07T13:38:24.522044621Z caller=module_service.go:59 msg=initialising module=server
level=info ts=2021-07-07T13:38:24.522072565Z caller=module_service.go:59 msg=initialising module=memberlist-kv
level=info ts=2021-07-07T13:38:24.522115176Z caller=module_service.go:59 msg=initialising module=store
level=info ts=2021-07-07T13:38:24.522464727Z caller=module_service.go:59 msg=initialising module=table-manager
level=info ts=2021-07-07T13:38:24.522415135Z caller=module_service.go:59 msg=initialising module=ring
level=info ts=2021-07-07T13:38:24.522821815Z caller=module_service.go:59 msg=initialising module=ingester
level=info ts=2021-07-07T13:38:24.523078386Z caller=ingester.go:246 msg="recovering from checkpoint"
level=info ts=2021-07-07T13:38:24.523370678Z caller=ring.go:271 msg="ring doesn't exist in KV store yet"
level=info ts=2021-07-07T13:38:24.523596268Z caller=client.go:247 msg="value is nil" key=collectors/ring index=1
level=info ts=2021-07-07T13:38:24.523930208Z caller=module_service.go:59 msg=initialising module=distributor
level=info ts=2021-07-07T13:38:24.524132169Z caller=module_service.go:59 msg=initialising module=ingester-querier
level=info ts=2021-07-07T13:38:24.524457331Z caller=recovery.go:73 msg="no checkpoint found, treating as no-op"
level=info ts=2021-07-07T13:38:24.52467781Z caller=module_service.go:59 msg=initialising module=ruler
level=info ts=2021-07-07T13:38:24.524856919Z caller=ingester.go:262 msg="recovered WAL checkpoint recovery finished" elapsed=1.754125ms errors=false
level=info ts=2021-07-07T13:38:24.52510336Z caller=ingester.go:268 msg="recovering from WAL"
level=info ts=2021-07-07T13:38:24.527826417Z caller=module_service.go:59 msg=initialising module=compactor
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13e3938]

goroutine 407 [running]:
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).RunCompaction.func1(0x450e690, 0x4a35f00, 0x1f7cc2d9, 0xc0318974, 0x8343ca1, 0x0, 0x2bc4190)
	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:219 +0x84
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).RunCompaction(0x450e690, 0x1e69d0c, 0x4644aa0, 0x0, 0x0)
	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:258 +0x350
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).loop.func1()
	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:153 +0x2c
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).loop.func2(0x4683270, 0x4961da0, 0x450e690, 0x1e69d0c, 0x4644aa0)
	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:162 +0x48
created by github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).loop
	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:160 +0x134
```
