### ISSUE TITLE
Helm chart has no promtail service configured

### ISSUE THREAD

**Issue by davkal** [grafana/loki#396]
**Describe the bug**
Without a service, promtail cannot be scraped by prometheus.

**To Reproduce**
1. Started promtail via helm chart
2. Added promtail to be scraped by prometheus.
3. Prom cannot scrape promtail

**Expected behavior**
Scrape works.

**Environment:**
 - Infrastructure: K8s
 - Deployment tool: helm

**Screenshots, promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by woodsaj** [comment]
> 2. Added promtail to be scraped by prometheus.
> 3. Prom cannot scrape promtail

Sounds like you have the wrong scrape_config in prometheus.  Prometheus should be scraping pods directly, it shouldnt be scraping a service.

**Comment by zarbis** [comment]
@woodsaj I've initially reported this in Slack. Prometheus collects Endpoints form Services with corresponding annotations.

I was troubleshooting Loki and added to `values.yaml`:
```yaml
loki.service.annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3100"

promtail.service.annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3100"
```

`values.yaml` having `promtail.service.port: 3100` made me believe that there is Service definition for promtail. And by adding annotations I will enable scraping.

**Comment by steven-sheehy** [comment]
I think we just need to remove the `promtail.service` options in the values.yaml to avoid the confusion.

**Comment by zarbis** [comment]
@steven-sheehy so what's supposed way to get metrics from promtail?

**Comment by steven-sheehy** [comment]
As @woodsaj said, you can just have prometheus scrape the pods. For example, if you're using annotation based approach:

```yaml
promtail:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"
```
