### ISSUE TITLE
Unable to use AWS EFS persistent volume claim with Loki

### ISSUE THREAD

**Issue by sauhrabh** [grafana/loki#3982]
**Describe the bug**
After installing Loki with the below YAML, status of pod `loki-stack-0` is "CrashLoopBackOff". This pod uses Amazon EFS persistent volume claim. On describing the pod, the error message is "failed to remove empty table folder, permission denied".

`loki-stack.yaml`:

```
loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: efs-sc
    size: 20Gi

promtail:
  enabled: true

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 7.5.0
```

Container logs:

```
level=info ts=2021-07-12T00:29:48.318569602Z caller=main.go:130 msg="Starting Loki" version="(version=2.2.0, branch=HEAD, revision=a27c79913)"
level=info ts=2021-07-12T00:29:48.319097669Z caller=server.go:229 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-07-12T00:29:48.319544986Z caller=modules.go:477 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2021-07-12T00:29:48.336319189Z caller=table_manager.go:241 msg="loading table index_18815"
level=error ts=2021-07-12T00:29:48.338220336Z caller=table_manager.go:251 msg="failed to remove empty table folder" table=index_18815 err="remove /data/loki/boltdb-shipper-active/index_18815: permission denied"
level=info ts=2021-07-12T00:29:48.338258287Z caller=table_manager.go:241 msg="loading table index_18816"
level=error ts=2021-07-12T00:29:48.340306206Z caller=table_manager.go:251 msg="failed to remove empty table folder" table=index_18816 err="remove /data/loki/boltdb-shipper-active/index_18816: permission denied"
level=info ts=2021-07-12T00:29:48.340341217Z caller=table_manager.go:241 msg="loading table index_18817"
level=error ts=2021-07-12T00:29:48.347051963Z caller=log.go:106 msg="error running loki" err="open /data/loki/boltdb-shipper-active/index_18817/1625868000: permission denied\nerror creating index client\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewStore\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:179\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:319\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:103\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nerror initialising module: store\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"
```

**To Reproduce**
1. Install AWS EFS CSI driver on EKS from the AWS documentation [here](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html)

    `efs-service-account.yaml`

    ```
    ---
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: efs-csi-controller-sa
      namespace: adhoc
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::010101010101:role/AmazonEKS_EFS_CSI_DriverRole
    ```

    `driver.yaml`

    ```
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
      name: efs-csi-external-provisioner-role
    rules:
    - apiGroups:
      - ""
      resources:
      - persistentvolumes
      verbs:
      - get
      - list
      - watch
      - create
      - delete
    - apiGroups:
      - ""
      resources:
      - persistentvolumeclaims
      verbs:
      - get
      - list
      - watch
      - update
    - apiGroups:
      - storage.k8s.io
      resources:
      - storageclasses
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - events
      verbs:
      - list
      - watch
      - create
    - apiGroups:
      - storage.k8s.io
      resources:
      - csinodes
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - nodes
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - coordination.k8s.io
      resources:
      - leases
      verbs:
      - get
      - watch
      - list
      - delete
      - update
      - create
    - apiGroups:
      - ""
      resources:
      - secrets
      verbs:
      - get
      - watch
      - list
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
      name: efs-csi-provisioner-binding
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: efs-csi-external-provisioner-role
    subjects:
    - kind: ServiceAccount
      name: efs-csi-controller-sa
      namespace: adhoc
    
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
      name: efs-csi-controller
      namespace: adhoc
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: efs-csi-controller
          app.kubernetes.io/instance: kustomize
          app.kubernetes.io/name: aws-efs-csi-driver
      template:
        metadata:
          labels:
            app: efs-csi-controller
            app.kubernetes.io/instance: kustomize
            app.kubernetes.io/name: aws-efs-csi-driver
        spec:
          containers:
          - args:
            - --endpoint=$(CSI_ENDPOINT)
            - --logtostderr
            - --v=2
            - --delete-access-point-root-dir=false
            env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/aws-efs-csi-driver:v1.3.2
            imagePullPolicy: IfNotPresent
            livenessProbe:
              failureThreshold: 5
              httpGet:
                path: /healthz
                port: healthz
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 3
            name: efs-plugin
            ports:
            - containerPort: 9909
              name: healthz
              protocol: TCP
            securityContext:
              privileged: true
            volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
          - args:
            - --csi-address=$(ADDRESS)
            - --v=2
            - --feature-gates=Topology=true
            - --leader-election
            env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
            image: public.ecr.aws/eks-distro/kubernetes-csi/external-provisioner:v2.1.1-eks-1-18-2
            name: csi-provisioner
            volumeMounts:
            - mountPath: /var/lib/csi/sockets/pluginproxy/
              name: socket-dir
          - args:
            - --csi-address=/csi/csi.sock
            - --health-port=9909
            image: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.2.0-eks-1-18-2
            name: liveness-probe
            volumeMounts:
            - mountPath: /csi
              name: socket-dir
          hostNetwork: true
          nodeSelector:
            kubernetes.io/os: linux
          priorityClassName: system-cluster-critical
          serviceAccountName: efs-csi-controller-sa
          volumes:
          - emptyDir: {}
            name: socket-dir
    
    ---
    kind: DaemonSet
    apiVersion: apps/v1
    metadata:
      name: efs-csi-node
      labels:
        app.kubernetes.io/name: aws-efs-csi-driver
    spec:
      selector:
        matchLabels:
          app: efs-csi-node
          app.kubernetes.io/name: aws-efs-csi-driver
          app.kubernetes.io/instance: kustomize
      template:
        metadata:
          labels:
            app: efs-csi-node
            app.kubernetes.io/name: aws-efs-csi-driver
            app.kubernetes.io/instance: kustomize
        spec:
          nodeSelector:
            beta.kubernetes.io/os: linux
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                    - fargate
          hostNetwork: true
          priorityClassName: system-node-critical
          tolerations:
            - operator: Exists
          containers:
            - name: efs-plugin
              securityContext:
                privileged: true
              image: "amazon/aws-efs-csi-driver:v1.3.2"
              args:
                - --endpoint=$(CSI_ENDPOINT)
                - --logtostderr
                - --v=2
              env:
                - name: CSI_ENDPOINT
                  value: unix:/csi/csi.sock
              volumeMounts:
                - name: kubelet-dir
                  mountPath: /var/lib/kubelet
                  mountPropagation: "Bidirectional"
                - name: plugin-dir
                  mountPath: /csi
                - name: efs-state-dir
                  mountPath: /var/run/efs
                - name: efs-utils-config
                  mountPath: /var/amazon/efs
                - name: efs-utils-config-legacy
                  mountPath: /etc/amazon/efs-legacy
              ports:
                - name: healthz
                  containerPort: 9809
                  protocol: TCP
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: healthz
                initialDelaySeconds: 10
                timeoutSeconds: 3
                periodSeconds: 2
                failureThreshold: 5
            - name: csi-driver-registrar
              image: public.ecr.aws/eks-distro/kubernetes-csi/node-driver-registrar:v2.1.0-eks-1-18-2
              args:
                - --csi-address=$(ADDRESS)
                - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
                - --v=2
              env:
                - name: ADDRESS
                  value: /csi/csi.sock
                - name: DRIVER_REG_SOCK_PATH
                  value: /var/lib/kubelet/plugins/efs.csi.aws.com/csi.sock
                - name: KUBE_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              volumeMounts:
                - name: plugin-dir
                  mountPath: /csi
                - name: registration-dir
                  mountPath: /registration
            - name: liveness-probe
              image: public.ecr.aws/eks-distro/kubernetes-csi/livenessprobe:v2.2.0-eks-1-18-2
              args:
                - --csi-address=/csi/csi.sock
                - --health-port=9809
                - --v=2
              volumeMounts:
                - name: plugin-dir
                  mountPath: /csi
          volumes:
            - name: kubelet-dir
              hostPath:
                path: /var/lib/kubelet
                type: Directory
            - name: plugin-dir
              hostPath:
                path: /var/lib/kubelet/plugins/efs.csi.aws.com/
                type: DirectoryOrCreate
            - name: registration-dir
              hostPath:
                path: /var/lib/kubelet/plugins_registry/
                type: Directory
            - name: efs-state-dir
              hostPath:
                path: /var/run/efs
                type: DirectoryOrCreate
            - name: efs-utils-config
              hostPath:
                path: /var/amazon/efs
                type: DirectoryOrCreate
            - name: efs-utils-config-legacy
              hostPath:
                path: /etc/amazon/efs
                type: DirectoryOrCreate
    
    ---
    apiVersion: storage.k8s.io/v1beta1
    kind: CSIDriver
    metadata:
      name: efs.csi.aws.com
      annotations:
        "helm.sh/hook": pre-install, pre-upgrade
        "helm.sh/hook-delete-policy": before-hook-creation
        "helm.sh/resource-policy": keep
    spec:
      attachRequired: false
    ```

    `storageclass.yaml`

    ```
    kind: StorageClass
    apiVersion: storage.k8s.io/v1
    metadata:
      name: efs-sc
      namespace: adhoc
    provisioner: efs.csi.aws.com
    ```

    `pv.yaml`

    ```
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: efs-pv
      namespace: adhoc
    spec:
      capacity:
        storage: 20Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteMany
      persistentVolumeReclaimPolicy: Retain
      storageClassName: efs-sc
      csi:
        driver: efs.csi.aws.com
        volumeHandle: fs-9d2e4a29
    ```

    `claim.yaml`

    ```
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: storage-loki-stack-0    # claim name used by loki
      namespace: adhoc
    spec:
      accessModes:
        - ReadWriteMany
      storageClassName: efs-sc
      resources:
        requests:
          storage: 20Gi
    ```

2. Install Loki with Helm using the statically provisioned Amazon EFS persistent volume. This is in manifest `loki-stack.yaml`

    ```
    helm repo add grafana https://grafana.github.io/helm-charts
    helm repo update
    helm show values grafana/loki-stack > loki-stack.yaml
    helm upgrade --install loki-stack grafana/loki-stack --values loki-stack.yaml -n adhoc
    ```

**Expected behavior**
Pod "`loki-stack-0`" using the persistent volume claim to have status "Running"

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by sauhrabh** [comment]
Changing `loki-stack.yaml` to the below worked:

```
loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: efs-sc
    mountPath: "/data"
    size: 20Gi
  securityContext:
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0


promtail:
  enabled: true


grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 7.5.0
```

But this is as root user.

How can I do this for non-root user ?
