### ISSUE TITLE
promtail: multiline inserts extra newlines

### ISSUE THREAD

**Issue by ecraven** [grafana/loki#3993]
Running on Google Cloud, the container logs are in json format. For java spring-boot apps, I have the following multiline config:
```
    - multiline:
        firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}'
        max_wait_time: 3s
```
This insert extra newlines between entries. I'm guessing this is because the lines *already* have newlines at the end, and `multiline.go` adds an extra newline at line 188.

Maybe the separator character could be made a parameter to the multiline configuration, so you could set it to be "\n", "", or whatever else you want?

**Comment by tgruenert** [comment]
having exactly same problem here. as anyone a solution?

**Comment by jeschkies** [comment]
@ecraven would you have an example of the log lines?

**Comment by tgruenert** [comment]
thank you @ecraven for your reply. 

my config in helm-chart looks like this:
```
promtail:
  config:
    snippets:
      pipelineStages:
        - docker: {}
        - multiline:
            firstline: '^\S+'
            max_wait_time: 1s
        - regex:
            # Flag (?s:.*) needs to be set for regex stage to capture full traceback log in the extracted map.
            expression: '(?P<message>(?s:.*))$'
```

docker logfile on file system snippet:
```
{"log":"[datasharing.TeamProQ] 13:56:33,190  INFO TpqReportingManager:180 - Added custom report definition for: immo.kontakte.youniq_interessentenbogen.studierende.en\n","stream":"stderr","time":"2022-02-15T12:56:33.190440698Z"}
{"log":"[export.TeamProQ] 15:11:44,238 ERROR CompImmoExcelObjekteImportierenPopup:225 - Invalid header signature; read 0x372E312D46445025, expected 0xE11AB1A1E011CFD0 - Your file appears not to be a valid OLE2 document\n","stream":"stderr","time":"2022-02-15T14:11:44.245608687Z"}
{"log":"org.apache.poi.poifs.filesystem.NotOLE2FileException: Invalid header signature; read 0x372E312D46445025, expected 0xE11AB1A1E011CFD0 - Your file appears not to be a valid OLE2 document\n","stream":"stderr","time":"2022-02-15T14:11:44.245758912Z"}
{"log":"\u0009at org.apache.poi.poifs.storage.HeaderBlock.\u003cinit\u003e(HeaderBlock.java:144)\n","stream":"stderr","time":"2022-02-15T14:11:44.245776812Z"}
{"log":"\u0009at org.apache.poi.poifs.storage.HeaderBlock.\u003cinit\u003e(HeaderBlock.java:113)\n","stream":"stderr","time":"2022-02-15T14:11:44.245785888Z"}
{"log":"\u0009at org.apache.poi.poifs.filesystem.NPOIFSFileSystem.\u003cinit\u003e(NPOIFSFileSystem.java:231)\n","stream":"stderr","time":"2022-02-15T14:11:44.245794073Z"}
{"log":"\u0009at org.apache.poi.poifs.filesystem.NPOIFSFileSystem.\u003cinit\u003e(NPOIFSFileSystem.java:167)\n","stream":"stderr","time":"2022-02-15T14:11:44.245801883Z"}
```

in grafana a lot of space is used
![image](https://user-images.githubusercontent.com/6465773/154079658-4f366d31-0fa6-4d8e-91ea-9acca8939b30.png)


Any idea or support on this are very welcome. Thank you!

**Comment by jeschkies** [comment]
Thanks. I'll take a look tomorrow :slightly_smiling_face:

**Comment by jeschkies** [comment]
I think the issue is that each `log` entry has a `\n` at the end. I wonder whether the Docker stage should trim each entry. In the mean time you could use [replace](https://grafana.com/docs/loki/latest/clients/promtail/stages/replace/) to strip the tailing `\n`.

**Comment by elliotdobson** [comment]
I've got the same issue.

> I think the issue is that each `log` entry has a `\n` at the end. I wonder whether the Docker stage should trim each entry. In the mean time you could use [replace](https://grafana.com/docs/loki/latest/clients/promtail/stages/replace/) to strip the tailing `\n`.

Adding replace to the pipeline stage ends up putting the multiline log all on a single line (thus not multiline anymore)
```
      - replace:
          expression: (\n)
          replace: ""
```

As mentioned in the OP it seems like the extra new line is coming from here:
https://github.com/grafana/loki/blob/e725a21b1aa566e3e4537e411642a3da57051460/clients/pkg/logentry/stages/multiline.go#L188

What do you think @jeschkies?

**Comment by JWackerbauer** [comment]
I added the replace stage before the multiline stage and that works for me. 
```yaml
        - replace:
            expression: '(\n)'
            replace: ""
        - multiline: #...
```

Ideally the multiline stage should check for preexisting newline characters at the end of each log and only add one if none exists.
