### ISSUE TITLE
Loki failing with msg="error running loki" err="timeout\nerror creating index client

### ISSUE THREAD

**Issue by ygurvanov** [grafana/loki#4002]
**Describe the bug**
Loki service works fine for few hours and suddenly stops working. After that only one of the Loki instances(pods) is coming up the rest of them entering CrashLoopBackOff state. 
In working instace I am seeing the following erros in the log :

```
level=error ts=2021-07-15T06:35:04.87785383Z caller=table.go:147 msg="failed to open existing boltdb file /loki-data/boltdb-cache/index_18822/loki-1-9th46-1626263053760133382-1626275359.gz, continuing without it to let the sync operation catch up" err=timeout
level=warn ts=2021-07-15T07:23:40.621530739Z caller=logging.go:71 traceID=1c691190536fe674 msg="POST /loki/api/v1/push (500) 356.241µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 596; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=warn ts=2021-07-15T07:23:40.644031822Z caller=logging.go:71 traceID=98f99e1b546cf5d msg="POST /loki/api/v1/push (500) 172.81µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 597; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=warn ts=2021-07-15T08:23:40.629172128Z caller=logging.go:71 traceID=53fd3e104b237390 msg="POST /loki/api/v1/push (500) 157.717µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 777; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=warn ts=2021-07-15T08:23:40.6441166Z caller=logging.go:71 traceID=1362f4d0148bb8b4 msg="POST /loki/api/v1/push (500) 164.016µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 416; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=warn ts=2021-07-15T09:23:40.527001664Z caller=logging.go:71 traceID=463796719abe465f msg="POST /loki/api/v1/push (500) 170.999µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 777; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=warn ts=2021-07-15T09:23:40.534075948Z caller=logging.go:71 traceID=227f1d4db38ffb33 msg="POST /loki/api/v1/push (500) 127.242µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 416; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=error ts=2021-07-15T10:02:01.529540617Z caller=client.go:187 msg="error CASing" key=collectors/ring err="Put \"http://consul-svc:8500/v1/kv/collectors/ring?cas=32102\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=error ts=2021-07-15T10:11:56.53094818Z caller=client.go:187 msg="error CASing" key=collectors/ring err="Put \"http://consul-svc:8500/v1/kv/collectors/ring?cas=32251\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=warn ts=2021-07-15T10:23:40.573302779Z caller=logging.go:71 traceID=1355b947deeca491 msg="POST /loki/api/v1/push (500) 230.679µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 777; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=warn ts=2021-07-15T10:23:40.582131853Z caller=logging.go:71 traceID=45d220f955f75208 msg="POST /loki/api/v1/push (500) 135.441µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 416; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=error ts=2021-07-15T10:45:51.5328382Z caller=client.go:187 msg="error CASing" key=collectors/ring err="Put \"http://consul-svc:8500/v1/kv/collectors/ring?cas=32779\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=error ts=2021-07-15T10:46:11.623923282Z caller=client.go:187 msg="error CASing" key=collectors/ring err="Put \"http://consul-svc:8500/v1/kv/collectors/ring?cas=32779\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=warn ts=2021-07-15T11:23:40.527377667Z caller=logging.go:71 traceID=7a0078dbc0d03d20 msg="POST /loki/api/v1/push (500) 197.863µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 596; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=warn ts=2021-07-15T11:23:40.537744179Z caller=logging.go:71 traceID=6b898815ac05cbd8 msg="POST /loki/api/v1/push (500) 129.725µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 597; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=warn ts=2021-07-15T12:23:40.480255917Z caller=logging.go:71 traceID=39aea54a688f6f81 msg="POST /loki/api/v1/push (500) 237.147µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 777; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=warn ts=2021-07-15T12:23:40.485484757Z caller=logging.go:71 traceID=579118d6977cbc53 msg="POST /loki/api/v1/push (500) 167.918µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 416; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=warn ts=2021-07-15T13:23:40.568978232Z caller=logging.go:71 traceID=4f475a222a7933bc msg="POST /loki/api/v1/push (500) 219.903µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 596; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=warn ts=2021-07-15T13:23:40.573429934Z caller=logging.go:71 traceID=e0bebc0633b09cc msg="POST /loki/api/v1/push (500) 127.875µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 440; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
level=warn ts=2021-07-15T13:23:40.575516118Z caller=logging.go:71 traceID=1cc1b1d450fa1b87 msg="POST /loki/api/v1/push (500) 117.864µs Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Accept-Encoding: gzip,deflate; Connection: Keep-Alive; Content-Length: 416; Content-Type: application/json; User-Agent: Apache-HttpClient/4.5.12 (Java/11.0.11); "
```
In the instnces which are down I am seeing the following in the logs:

```
It fails with following logs:
level=error ts=2021-07-15T14:04:53.785051644Z caller=table.go:147 msg="failed to open existing boltdb file /loki-data/boltdb-cache/index_18822/loki-1-9th46-1626263053760133382-1626275359.gz, continuing without it to let the sync operation catch up" err=timeout
level=error ts=2021-07-15T14:04:58.784639777Z caller=table.go:147 msg="failed to open existing boltdb file /loki-data/boltdb-cache/index_18822/loki-1-9th46-1626263053760133382-1626275368.gz, continuing without it to let the sync operation catch up" err=timeout
level=error ts=2021-07-15T14:05:03.782617446Z caller=table.go:147 msg="failed to open existing boltdb file /loki-data/boltdb-cache/index_18822/loki-1-9th46-1626263053760133382-1626275387.gz, continuing without it to let the sync operation catch up" err=timeout
level=error ts=2021-07-15T14:05:08.773037057Z caller=table.go:147 msg="failed to open existing boltdb file /loki-data/boltdb-cache/index_18822/loki-1-9th46-1626263053760133382-1626275700.gz, continuing without it to let the sync operation catch up" err=timeout
level=error ts=2021-07-15T14:05:13.825508846Z caller=table.go:147 msg="failed to open existing boltdb file /loki-data/boltdb-cache/index_18822/loki-1-9th46-1626263053760133382-1626276600.gz, continuing without it to let the sync operation catch up" err=timeout
level=error ts=2021-07-15T14:05:18.844027299Z caller=table.go:147 msg="failed to open existing boltdb file /loki-data/boltdb-cache/index_18822/loki-1-9th46-1626263053760133382-1626277500.gz, continuing without it to let the sync operation catch up" err=timeout
level=error ts=2021-07-15T14:05:23.867655377Z caller=table.go:147 msg="failed to open existing boltdb file /loki-data/boltdb-cache/index_18822/loki-1-9th46-1626263053760133382-1626325200.gz, continuing without it to let the sync operation catch up" err=timeout
level=error ts=2021-07-15T14:05:29.27335084Z caller=log.go:106 msg="error running loki" err="timeout\nerror creating index client\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewStore\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:179\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:319\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:103\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nerror initialising module: store\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).i...
```
 When we try to open /loki-data/boltdb-cache/index_18822/ folder we are seeing that this folder is empy, however new folder index_18823 exists and archives(loki-1-9th46-1626263053760133382-1626275359.gz) are in that folder. So it looks like Loki service is searching in old index folder.

**To Reproduce**
1. Started loki with following config: (defaut loki replicas = 3)  
```
 - apiVersion: v1
    kind: Route
    metadata:
      name: ${LOKI_DEPLOYMENT_NAME}-route
    spec:
      port:
        targetPort: loki-svc
      host: ${LOKI_DEPLOYMENT_NAME}.${TARGET_NAMESPACE}.${DNS_SUFFIX}
      to:
        kind: Service
        name: ${LOKI_DEPLOYMENT_NAME}-svc

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${LOKI_DEPLOYMENT_NAME}-svc
    spec:
      ports:
        - name: ${LOKI_DEPLOYMENT_NAME}-svc
          protocol: TCP
          port: 3100
          targetPort: 3100
      selector:
        app: ${LOKI_DEPLOYMENT_NAME}

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: ${LOKI_DEPLOYMENT_NAME}-data-store
    spec:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: ${LOKI_DATA_VOLUME_SIZE}

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${LOKI_DEPLOYMENT_NAME}
      name: ${LOKI_DEPLOYMENT_NAME}
    spec:
      strategy:
        type: Rolling
        rollingParams:
          timeoutSeconds: 300
          maxUnavailable: 5%
          maxSurge: 50%
      resources:
        requests:
          cpu: 100m
          memory: 100M
        limits:
          cpu: 100m
          memory: 100M
      triggers:
        - type: ConfigChange
      replicas: ${{LOKI_REPLICAS}}
      selector:
        app: ${LOKI_DEPLOYMENT_NAME}
      template:
        metadata:
          labels:
            app: ${LOKI_DEPLOYMENT_NAME}
          name: ${LOKI_DEPLOYMENT_NAME}
        spec:
          containers:
            - name: ${LOKI_DEPLOYMENT_NAME}
              args:
                - --config.file=/etc/loki/loki-config.yml
                - --log.level=${LOKI_LOG_LEVEL}
              resources:
                requests:
                  cpu: 200m
                  memory: 200M
                limits:
                  cpu: 500m
                  memory: 500M
              ports:
                - containerPort: 3100
                  protocol: TCP
              livenessProbe:
                tcpSocket:
                  port: 3100
                initialDelaySeconds: 15
                timeoutSeconds: 1
              readinessProbe:
                httpGet:
                  path: /ready
                  port: 3100
                initialDelaySeconds: 60
                timeoutSeconds: 10
                failureThreshold: 6
              env:
                - name: EXPERIAN_SAAS_METADATA_CLIENT_ID
                  value: ${CLIENT_ID}
                - name: EXPERIAN_SAAS_METADATA_CLIENT_NAME
                  value: ${CLIENT_NAME}
                - name: EXPERIAN_SAAS_METADATA_ENVIRONMENT_ID
                  value: ${ENVIRONMENT_ID}
                - name: EXPERIAN_SAAS_METADATA_REGION
                  value: ${REGION}
                - name: EXPERIAN_SAAS_METADATA_ENVIRONMENT_TYPE
                  value: ${ENVIRONMENT_TYPE}
                - name: EXPERIAN_SAAS_METADATA_ENVIRONMENT_NAME
                  value: ${ENVIRONMENT_NAME}
                - name: EXPERIAN_SAAS_METADATA_ENVIRONMENT_ROLE
                  value: ${ENVIRONMENT_ROLE}
                - name: EXPERIAN_SAAS_METADATA_ZONE
                  value: ${ZONE}
                - name: EXPERIAN_SAAS_METADATA_STACK
                  value: ${STACK}
                - name: EXPERIAN_SAAS_METADATA_SERVICE_ID
                  value: ${SERVICE_ID}
                - name: EXPERIAN_SAAS_METADATA_SERVICE_NAME
                  value: ${SERVICE_NAME}
                - name: EXPERIAN_SAAS_METADATA_TARGET_NAMESPACE
                  value: ${TARGET_NAMESPACE}
                - name: EXPERIAN_SAAS_METADATA_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: EXPERIAN_SAAS_METADATA_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: LOKI_RETENTION_ENABLED
                  value: ${LOKI_RETENTION_ENABLED}
                - name: LOKI_RETENTION_PERIOD
                  value: ${LOKI_RETENTION_PERIOD}
                - name: TABLE_MANAGER_INDEX_PERIOD
                  value: ${TABLE_MANAGER_INDEX_PERIOD}
                - name: LOKI_REPLICAS
                  value: ${LOKI_REPLICAS}
                - name: LOKI_LOG_LEVEL
                  value: ${LOKI_LOG_LEVEL}
              image: "${DOCKER_REGISTRY}/${LOKI_IMAGE_NAME}"
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /etc/loki
                  name: loki-config
                - mountPath: /loki-data
                  name: loki-data
          restartPolicy: Always
          volumes:
            - name: loki-data
              persistentVolumeClaim:
                claimName: ${LOKI_DEPLOYMENT_NAME}-data-store
            - name: loki-config
              configMap:
                name: loki-config

  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: loki-config
    data:
      loki-config.yml: |
        auth_enabled: false
        server:
          http_listen_port: 3100
          grpc_listen_port: 9096
        distributor:
          ring:
            kvstore:
              store: consul
              consul:
                consistent_reads: true
                host: consul-svc:8500
                http_client_timeout: 20s
        ingester:
          lifecycler:
            heartbeat_period: 5s
            join_after: 30s
            ring:
              kvstore:
                store: consul
                consul:
                  host: consul-svc:8500
              replication_factor: ${LOKI_REPLICAS}
            final_sleep: 0s
          chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
          max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
          chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
          chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
          max_transfer_retries: 0     # Chunk transfers disabled
        schema_config:
          configs:
            - from: 2018-04-15
              store: boltdb-shipper
              object_store: filesystem
              schema: v11
              index:
                prefix: index_
                period: ${TABLE_MANAGER_INDEX_PERIOD}
        compactor:
          working_directory: /loki-data/compactor
          shared_store: filesystem
        storage_config:
          filesystem:
            directory: /loki-data/chunks
          boltdb_shipper:
            active_index_directory: /loki-data/index
            cache_location: /loki-data/boltdb-cache
            cache_ttl: 24h
            resync_interval: 5s
            shared_store: filesystem
        table_manager:
          retention_deletes_enabled: ${LOKI_RETENTION_ENABLED}
          retention_period: ${LOKI_RETENTION_PERIOD}
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
        ruler:
          storage:
            type: local
            local:
              directory: /tmp/loki/rules
          rule_path: /tmp/loki/rules
          alertmanager_url: http://localhost:9093
          ring:
            kvstore:
              store: consul
              consul:
                host: consul-svc:8500
          enable_api: true

```
2. Consul configuration 
```
 - kind: ConfigMap
    metadata:
      name: consul-config
      namespace: ${TARGET_NAMESPACE}
    apiVersion: v1
    data:
      run: |-
        #!/bin/sh

        df -h

        export CONSUL_HTTP_ADDR=https://localhost:8501

        consul agent -advertise=$POD_IP -node=$POD_NAME \
        -retry-join=consul-0.consul.$NAMESPACE.svc.cluster.local \
        -config-file=${CONFIG_FOLDER}/config.json \
        -disable-host-node-id \
        -log-level=${CONSUL_LOG_LEVEL} \
        -encrypt=diCRPVDnfaF96s8KFEdVlY2gCFzu8ZdrSRRl9LxwYH0=

      config.json: |-

        {
            "server": true,
            "datacenter": "consul",
            "data_dir": "${DATA_FOLDER}",
            "bind_addr": "0.0.0.0",
            "client_addr": "0.0.0.0",
            "datacenter": "dc1",
            "domain":"cluster.local",
            "bootstrap_expect": 1,
            "ui": false,
            "performance": {
               "raft_multiplier": 1
             }
        }

  - apiVersion: v1
    kind: Service
    metadata:
      name: consul-svc
    spec:
      clusterIP: None
      ports:
        - port: ${{UI_PORT}}
          targetPort: ${{UI_PORT}}
          name: ui
        - port: ${{HTTP_PORT}}
          targetPort: ${{HTTP_PORT}}
          name: http
        - port: ${{ALT_PORT}}
          targetPort: ${{ALT_PORT}}
          name: rpc
        - port: ${{UDP_PORT}}
          targetPort: ${{UDP_PORT}}
          name: udp
          protocol: "UDP"
        - port: ${{SERVER_PORT}}
          targetPort: ${{SERVER_PORT}}
          name: server
      selector:
        app: consul

  - apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      namespace: ${TARGET_NAMESPACE}
      name: consul
    spec:
      serviceName: consul
      selector:
        matchLabels:
          app: consul
      replicas: ${{CONSUL_REPLICA_COUNT}}
      template:
        metadata:
          labels:
            app: consul
        spec:
          nodeSelector:
            location: external
          containers:
            - name: consul
              image: "${DOCKER_REGISTRY}/${CONSUL_IMAGE_NAME}"
              livenessProbe:
                tcpSocket:
                  port: 8500
                initialDelaySeconds: 15
                timeoutSeconds: 1
              imagePullPolicy: IfNotPresent
              env:
                - name: CONSUL_DISABLE_PERM_MGMT
                  value: ""
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: ADVERTISE_ADDR
                  value: "$(POD_IP)"
              command:
                - ${CONFIG_FOLDER}/run
              volumeMounts:
                - name: consul-config
                  mountPath: ${CONFIG_FOLDER}
                - name: consul-data
                  mountPath: ${DATA_FOLDER}
              lifecycle:
                preStop:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - consul leave
              ports:
                - containerPort: ${{UI_PORT}}
                  name: ui-port
                - containerPort: ${{ALT_PORT}}
                  name: alt-port
                - containerPort: ${{UDP_PORT}}
                  name: udp-port
                - containerPort: ${{HTTP_PORT}}
                  name: http-port
                - containerPort: ${{SERVER_PORT}}
                  name: server
          restartPolicy: Always
          volumes:
            - name: consul-config
              configMap:
                name: consul-config
                defaultMode: 0777
      updateStrategy:
        type: RollingUpdate
      volumeClaimTemplates:
        - metadata:
            name: consul-data
          spec:
            storageClassName: block-aws
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: ${CONSUL_DATA_VOLUME_SIZE}
```
3. environment variables
```
# loki service
- name: LOKI_DEPLOYMENT_NAME
  description: Loki
  value: "loki"

- name: LOKI_IMAGE_NAME
  description: Image Name

- name: LOKI_DATA_VOLUME_SIZE
  description: Size of the persistent volume

- name: LOKI_LOG_LEVEL
  description: Loki log level
  value: warn

- name: LOKI_REPLICAS
  description: Number of replicas

- name: LOKI_RETENTION_ENABLED
  description: A flag that shows if the retention option for the loki logs is turned on
  value: "true"

- name: LOKI_RETENTION_PERIOD
  description: The loki logs retention period
  value: "168h"

- name: TABLE_MANAGER_INDEX_PERIOD
  description: The table manager indexing period.
  value: "24h"

# Consul service
- name: CONSUL_IMAGE_NAME
  description: The name and version of the docker image of Consul

- name: CONSUL_REPLICA_COUNT
  description: Number of vault instances
  value: "1"

- name: DATA_FOLDER
  description: Consul data folder
  value: /consul/data

- name: CONFIG_FOLDER
  description: Consul configuration file folder
  value: /etc/config/consul

- name: UI_PORT
  description: UI port
  value: "8500"

- name: ALT_PORT
  description: Alt port
  value: "8400"

- name: HTTP_PORT
  description: Http port
  value: "8080"

- name: UDP_PORT
  description: UDP port
  value: "53"

- name: SERVER_PORT
  description: Server port
  value: "8300"

- name: CONSUL_LOG_LEVEL
  description: Consul log level
  value: err

- name: CONSUL_DATA_VOLUME_SIZE
  description: Size of the persistent volume
  value: "1Gi"
```

**Expected behavior**
Loki service to sync properly all index files and folders and be able to bring up all Loki instances after they were terminated or killed.
**Environment:**
 - Infrastructure: OpenShift 
 - Deployment tool: openshift template
