### ISSUE TITLE
loki fetchLazyChunks nil pointer dereference

### ISSUE THREAD

**Issue by vlorc** [grafana/loki#4008]
1. grpc based storage experiment project
2. Loki crashes when querying the 12 hour log（cache miss and remote load）,if it's 1hour, it's working

**StorageClient.GetChunks field appears to be missing**

os info
```
Linux server 5.12.14-arch1-1 #1 SMP PREEMPT Thu, 01 Jul 2021 07:26:06 +0000 x86_64 GNU/Linux
```

loki verion
```shell
loki, version 2.2.1 (branch: HEAD, revision: babea82e)
  build user:       root@e2d295b84e26
  build date:       2021-04-06T00:52:41Z
  go version:       go1.15.3
  platform:         linux/amd64
```

log lines
```
level=info ts=2021-07-19T00:54:38.554472183Z caller=table.go:336 msg="uploading table index_18827"
level=info ts=2021-07-19T00:54:38.55451632Z caller=table.go:363 msg="finished uploading table index_18827"
level=info ts=2021-07-19T00:54:38.554545693Z caller=table.go:421 msg="cleaning up unwanted dbs from table index_18827"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c6ddfe]

goroutine 552 [running]:
github.com/grafana/loki/pkg/storage.fetchLazyChunks.func2(0xc000903620, 0xc000a16ea0, 0xc000550f40, 0xc000903670, 0x2, 0x2)
        /src/loki/pkg/storage/batch.go:679 +0x6be
created by github.com/grafana/loki/pkg/storage.fetchLazyChunks
        /src/loki/pkg/storage/batch.go:652 +0x61b
```

loki-local-config.yaml fragment
```yaml

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: grpc-store
      schema: v11
      index:
        prefix: index_
        period: 24h
      chunks:
        prefix: chunk_
        period: 168h
storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  grpc_store:
    server_address: 127.0.0.1:8989
```

my storage log
```
2021-07-19T09:14:09.095+0800    DEBUG   service/store.go:105    getChunks       {"keys": ["fake/6b64c746ef280e7d:17ab9b3b619:17ab9b3be32:f03a75a9", "fake/6b64c746ef280e7d:17abc34c8d5:17abc35d49c:9ff11b40", "fake/6b64c746ef280e7d:17abc36ffa7:17abc36ffa8:554ec36", "fake/b2c2cc9397df115b:17ab9b3c253:17ab9b3ca33:89da132c", "fake/b2c2cc9397df115b:17ab9b3ca32:17ab9b3d53e:36ea014c", "fake/b2c2cc9397df115b:17ab9b3d53d:17ab9b3dfce:abd2bba", "fake/b2c2cc9397df115b:17ab9b3dfcd:17ab9b3e668:981a68ec", "fake/b2c2cc9397df115b:17ab9b3e667:17ab9b3f411:f4c261d0", "fake/b2c2cc9397df115b:17ab9b3f410:17ab9b3fb98:6c7c9f0c", "fake/b2c2cc9397df115b:17ab9b3fb97:17ab9b40546:5d55b825", "fake/b2c2cc9397df115b:17ab9b40545:17ab9b40fbd:a613ec36", "fake/b2c2cc9397df115b:17ab9b40fbc:17ab9b41bbf:e30a1218", "fake/b2c2cc9397df115b:17ab9b41bbe:17ab9b423ce:c8f6124e", "fake/b2c2cc9397df115b:17ab9b423cd:17ab9b43004:a4944b10", "fake/b2c2cc9397df115b:17ab9b43003:17ab9b442bd:d385362d", "fake/b2c2cc9397df115b:17ab9b442bc:17ab9b442f5:92270da9", "fake/b2c2cc9397df115b:17abc34b160:17abc359de1:735209f9", "fake/b2c2cc9397df115b:17abc35c4f8:17abc371044:eb2fb7af"]}
```
my storage code
```go
for _, c := range chunks {
	if buf, err := s.store.GetObject(ctx, c.GetKey()); nil != err {
		last = err
	} else if err = srv.Send(&types.GetChunksResponse{Chunks: []*types.Chunk{{Key: c.GetKey(), Encoded: buf}}}); nil != err {
		last = err
	}
}
```
bug location
[/pkg/storage/batch.go#L679](https://github.com/grafana/loki/blob/release-2.2.1/pkg/storage/batch.go#L679)

field missing
[/cortexproject/cortex/pkg/chunk/grpc/storage_client.go#L106](https://github.com/grafana/loki/blob/release-2.2.1/vendor/github.com/cortexproject/cortex/pkg/chunk/grpc/storage_client.go#L106)
