### ISSUE TITLE
Query from Grafana to Loki returning 502  when using 7 days range (too much data to parse?)

### ISSUE THREAD

**Issue by some-random-dude123** [grafana/loki#4015]
Hello everyone

**Describe the bug**
Loki Version: 2.2.0
Grafana Version: 7.5.6

I'm running a query from Grafana to Loki that looks like this (investigating for a neo4j timeout but whatever):
{namespace="neo4j", container_name="neo4j-v1-neo4j"} |~ "timed out"
The query works well when using the 2 days range, but if I go to 7 days range I'm hitting a 502 error

![image](https://user-images.githubusercontent.com/84046238/126343982-9c179d47-575f-4e05-943c-7607583d64e7.png)

I'm hot sure here if i'm facing resources limitation or anything else.
Considering it fails at 49s, I suspect this is not a timeout issue (with the load balancer or anything like it)
Our Loki machine is a t3.xlarge (4vcpu 16gb of ram), it does ingest a lot of logs, but CPU is pretty sleepy and memory is around 27%. 
Loki is running as a container on it (with no resource limitations).
Looking at the metrics of the underlying server, it doesn't really work hard while processing the query.

I've found this error in the container log when the query fail
```
level=info ts=2021-07-20T14:35:43.738263796Z caller=metrics.go:91 org_id=fake traceID=5cf702b9223409e latency=slow query="{namespace=\"neo4j\", container_name=\"neo4j-v1-neo4j\"} |~ \"timed out\"" query_type=filter range_type=range length=168h0m1s step=5m0s duration=49.731710927s status=200 limit=1000 returned_lines=34 throughput=348MB total_bytes=17GB
2021-07-20 14:35:43.738667 I | http: superfluous response.WriteHeader call from github.com/opentracing-contrib/go-stdlib/nethttp.(*statusCodeTracker).WriteHeader (status-code-tracker.go:17)
level=warn ts=2021-07-20T14:35:43.738720096Z caller=logging.go:60 traceID=5cf702b9223409e msg="GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bnamespace%3D%22neo4j%22%2C%20container_name%3D%22neo4j-v1-neo4j%22%7D%20%7C~%20%22timed%20out%22&start=1626186893000000000&end=1626791694000000000&step=300 49.73240024s, error: write tcp hidden:hidden->hidden:hidden: i/o timeout ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-US,en;q=0.9,fr;q=0.8; Cache-Control: no-cache; Pragma: no-cache; Sec-Ch-Ua: \" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"; Sec-Ch-Ua-Mobile: ?0; Sec-Fetch-Dest: empty; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Agent: Grafana/7.5.6; X-Amzn-Trace-Id: Root=1-60f6df0d-42c5460655f1981f39875589; X-Forwarded-For: hidden; X-Grafana-Org-Id: 1; "

```

**To Reproduce**
There is no exact steps on reproduction, have a loki with large data and run a query too big for the instance ? 

**Expected behavior**
 Query should return result properly on a larger time range and not fail.

**Environment:**
 - Infrastructure: AWS EKS
 - Deployment tool: Kubectl / terraform

Any hints that I could investigate to resolve this issue ? I may end up boosting the machine even if I have no sign of resource limitation, but I would like other opinions on the matter, maybe that's something else ? 

Thanks !

**Comment by Abuelodelanada** [comment]
I faced the same issue. I tested Loki in a distributed environment in a [Microk8s](https://microk8s.io/) cluster in GCP and deployed Loki in microservice mode.

- Loki distributor: 3 pods
- Loki ingester: 3 pods
- Loki gateway: 1 pod
- Loki queried: 3 pods
- Loki query frontend: 1 pod
- MinIO: 3 pods

4 GCP machines with these specs:

**Machine type:** e2-standard-2 (2 vCPUs, 8 GB memory) 
**Image:** ubuntu-2004-focal-v20210702
**Zone:** us-east4-c 
**Boot disk:**
  - **Size:** 20GB
  - **Type:** Balanced persistent disk

The ingestion rate was 50.000 log lines per second, with at least 10 minutes of log ingestion the Log rate dashboard shows an 502 error code when retrieving data

![image](https://user-images.githubusercontent.com/939888/126524639-506e643c-7f55-4ff4-950f-79c72a0ba290.png)


![image](https://user-images.githubusercontent.com/939888/126524738-d6c56c98-6979-4279-aa18-19273441bcf0.png)

**Comment by mrgreyves** [comment]
I have the exact same problem. At first I thought the problem was with the grafana timeouts and increased them. After that I started getting 504 error.

**Comment by deng47** [comment]
I encountered the same problem here.
I deployed a distributed version of Loki using the loki-distributed helm chart on a 8-node(64 processors,128g,mem,12T nvme each ) k3s cluster. 
Loki Version: 2.2.1
Loki distributor: 4 pods
Loki ingester: 4 pods
Loki gateway: 1 pod
Loki compactor: 1 pod
Loki querier: 8 pods
Loki query frontend: 2 pods
Loki memcached-chunks: 4 pods
Loki memcached-frontend: 2 pods
Loki memcached-index-queries:1 pod
Loki memcached-index-writes:1 pod
Loki ruler:1 pod
MinIO: 8 pods

The index rate is around 20k lines/s. Every stream has 4 to 6 labels, e.g. namespace, container, pod, hostname
When the query range >= 7 days, grafana returns a 502 error like below at exactly 60 seconds.
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>502 Proxy Error</title> </head><body> <h1>Proxy Error</h1> <p>The proxy server received an invalid response from an upstream server.<br /> The proxy server could not handle the request<p>Reason: <strong>Error reading from remote server</strong></p></p> </body></html>
```
Here are some logs from the Nginx gateway
```
2021/07/21 17:23:47 [error] 9#9: *12753467 upstream timed out (110: Operation timed out) while reading response header from upstream, client: <DELETE_IP_HERE>, server: , request: "GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bdata_type%3D%22logs-syslog%22%7D&start=1626283367000000000&end=1626888168000000000&step=600 HTTP/1.1", upstream: "http://<DELETE_IP_HERE>:3100/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bdata_type%3D%22logs-syslog%22%7D&start=1626283367000000000&end=1626888168000000000&step=600", host: "loki.<DELETE_DOMAIN_HERE>:80"

2021/07/24 18:47:44 [error] 9#9: *26329 upstream prematurely closed connection while reading response header from upstream, client: <DELETE_IP_HERE>, server: , request: "GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bdata_type%3D%22logs-containers%22%2Ccontainer%3D%22pg-persister%22%7D&start=1625942821000000000&end=1627152422000000000&step=600 HTTP/1.1", upstream: "http://<DELETE_IP_HERE>:3100/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bdata_type%3D%22logs-containers%22%2Ccontainer%3D%22pg-persister%22%7D&start=1625942821000000000&end=1627152422000000000&step=600", host: "loki.<DELETE_DOMAIN_HERE>:80"
```
Then I found logs from the loki-distributed-query-frontend pod
```
level=warn ts=2021-07-24T18:47:44.676008137Z caller=logging.go:71 traceID=42e37adcf1ef9caa msg="GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bdata_type%3D%22logs-containers%22%2Ccontainer%3D%22pg-persister%22%7D&start=1625942821000000000&end=1627152422000000000&step=600 (500) 42.72289471s Response: \"write /var/loki/boltdb-cache/loki_index_18820/compactor-1626190919.gz: no space left on device\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-US,en;q=0.5; Connection: close; Sec-Fetch-Dest: empty; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Agent: Grafana/7.5.5; X-Forwarded-For: 192.168.87.133; X-Forwarded-Host: loki-perlmutter.nersc.gov:80; X-Forwarded-Port: 80; X-Forwarded-Proto: http; X-Forwarded-Server: traefik-744fb8464c-c529l; X-Grafana-Org-Id: 6; X-Real-Ip: <DELETE_IP_HERE>; "
```
And found out the filesystem of querier-0 is full of boltdb shipper cache
```
[root@shasta-k3s-1 ~]# kubectl exec -it -n perlmutter-loki perlmutter-loki-distributed-querier-0 -- df -h |grep /var/loki
                         50.0G     46.7G      3.3G  93% /var/loki
[root@shasta-k3s-1 ~]# 
```
How can I clear boltdb shipper cache safely? And prevent this happen again?

Meanwhile, I noticed only one querier used a huge amount of cpu and mem resources when the query was being executed. I suspect the query was not distributed to multiple queriers through the query frontend.

Below are some of the config I changed in values.yaml 
```
      boltdb_shipper:
        shared_store: s3
        active_index_directory: /var/loki/index
        cache_location: /var/loki/boltdb-cache
        cache_ttl: 12h

    querier:
      query_timeout: 10m
      query_ingesters_within: 1h
      engine:
        timeout: 10m

    query_range:
      align_queries_with_step: true
      max_retries: 5
      split_queries_by_interval: 15m
      cache_results: true
      parallelise_shardable_queries: true
      results_cache:
        cache:
          memcached_client:
            consistent_hash: true
            host: {{ include "loki.memcachedFrontendFullname" . }}
            max_idle_conns: 16
            service: http
            timeout: 500ms
            update_interval: 1m


    frontend_worker:
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100
```

**Comment by DovilasK** [comment]
Guys, are you running on GCP under GLB? In 6+ months. found a solution to configure GCP backend configuration via annotations. That helped:
```
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: backend-config
spec:
  timeoutSec: 900
```
and annotation under ingress or service:
```
cloud.google.com/backend-config: '{"ports": {"80":"backend-config"}}'
```
also SVC recreation is a must. 

Hope that helps!

**Comment by Abuelodelanada** [comment]
Hello @DovilasK 

I'm using in GCP, and locally using microk8s.

**Comment by Abuelodelanada** [comment]
This issue is still present.

**Comment by artem-timchenko** [comment]
Facing the same issue in AWS-based setup (k8s on EC2, provisioned by kops. Using loki-distributed helm chart). Quite often I even face this with a small queries (1 hour time frame), when querier could get pretty much everything directly from ingestors, as soon as we are using 2h duration for chunks.

**Comment by nowyp** [comment]
We experiencing the same issue. GKE cluster `1.19.15-gke.1801` with helm chart loki-distributed (the same issue with 2.2 and latest 2.4.1 with applied changes described here https://grafana.com/docs/loki/latest/upgrading/#240).

I  assumed initially that it could be the https://github.com/k8spin/loki-multi-tenant-proxy component which we are using between our Grafana and loki but I've removed this component from our deployments and experiencing the same issue.

I've also tried to increased the `loki-querier` resources (multiple replicas with 4GB memory each to exclude memory issues) but still get that 502 and pods don't show any memory issues.

Tried also direct queries from some debug pod to loki API (as to exclude that this is something with Grafana) but the same problem. With quite long range queries (usually older than 7 days) get the 502 error.

I've review issues and a couple of people have the same problem without any clue what it could be:

https://github.com/grafana/loki/issues/4591
https://github.com/grafana/loki/issues/4582

Maybe related also (but not sure):

https://github.com/grafana/loki/issues/4754
https://github.com/grafana/loki/issues/4779
https://github.com/grafana/loki/issues/4721

@cyriltovena @slim-bean  maybe you guys when find a moment could put any hint where to look to solve this issue (or what really potential problem could be). I assume this is related with some specific misconfiguration (I experiencing this issue in some quite small clusters like 6xn1-standard-8 nodes and not a lot of traffic). If somebody could help here I will be able to provide all configuration details (currently GCS with boltdb-shipper) and try different possible solutions. Would be nice to find what this is about.

Thx for any input.

**Comment by cyriltovena** [comment]
There could be a lot of reason, if there is only few queriers that are doing work then possibly I'll be looking at increase or decreasing the worker config for querier.

https://grafana.com/docs/loki/latest/configuration/#frontend_worker_config

Try to increase parallelism, there were also a bug where this config would not set correctly in which case you need to set `match_max_concurrent` to false. see https://github.com/grafana/loki/pull/4761

The `max_query_parallelism` might also need to be increase.

**Comment by nowyp** [comment]
@cyriltovena thanks for hints. I'm making those tests on the separated cluster where there is no other queries (it it dedicated separated environment for those issue if I can say that).

The problem happens when I query looks like this: `{namespace="mynamespace"} |= "something something"` (I know of course how Loki is design and mostly the labels should be used but explain that developers who worked before years with ES for that kind of stuff 😄 ).

But the issue disappear when I have a query like this: `{namespace="mynamespace"} |= "something"` (so single words expressions) - then I can query without problems even for month and more - probably this is related to scanning.

I've made the suggested changes (Loki 2.4.1 based on loki-distributed Chart 0.39.3) and currently have a config like this (using GCS bucket as storage with boltdb):

```
      auth_enabled: true
      server:
        http_listen_port: 3100
        grpc_server_max_recv_msg_size: 20388078
        grpc_server_max_send_msg_size: 20388078
        log_level: warn
      distributor:
        ring:
          kvstore:
            store: memberlist
      memberlist:
        join_members:
          - {{ include "loki.fullname" . }}-memberlist
      ingester:
        lifecycler:
          ring:
            kvstore:
              store: memberlist
            replication_factor: 1
        chunk_idle_period: 30m
        chunk_block_size: 262144
        chunk_encoding: snappy
        chunk_retain_period: 1m
        max_transfer_retries: 0
        wal:
          dir: /var/loki/wal        
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_cache_freshness_per_query: 10m
        retention_period: {{ .Values.global.loki.retention.period }}
      schema_config:
        configs:
          - from: 2021-02-01
            store: boltdb-shipper
            object_store: gcs
            schema: v11
            index:
              prefix: index_
              period: 24h
      storage_config:
        gcs:
          bucket_name: mybucket-name
        boltdb_shipper:
          shared_store: gcs
          active_index_directory: /var/loki/index
          cache_location: /var/loki/cache
          cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
      chunk_store_config:
        max_look_back_period: 0s
      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s
      query_range:
        align_queries_with_step: true
        max_retries: 5
        split_queries_by_interval: 15m
        cache_results: true
        results_cache:
          cache:
            enable_fifocache: true
            fifocache:
              max_size_items: 1024
              validity: 24h
      querier:
        max_concurrent: 25
      frontend_worker:
        frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
        parallelism: 25
      frontend:
        log_queries_longer_than: 5s
        compress_responses: true
        tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100
      compactor:
        shared_store: gcs
        retention_enabled: {{ .Values.global.loki.retention.enabled }}
      ruler:
        storage:
          type: local
          local:
            directory: /etc/loki/rules
        ring:
          kvstore:
            store: memberlist
        rule_path: /tmp/loki/scratch
        alertmanager_url: http://alertmanager-proxy.monitoring:8080
        enable_alertmanager_v2: true
        enable_api: true
```

**Comment by cyriltovena** [comment]
What's the query stats ? The max_concurrent should reflect more cpu allocated per querier.

In query range you should activate sharding.

**Comment by demandbase-gmavadiya** [comment]
@cyriltovena where should `match_max_concurrent: false` be added in the Loki config ?

**Comment by magiejen** [comment]
@demandbase-gmavadiya 
looks like in frontend worker https://github.com/grafana/loki/blob/a0eb507fead4fab828330ab6ac54bc9f48f8a209/production/ksonnet/loki/config.libsonnet#L157

**Comment by demandbase-gmavadiya** [comment]
So I tried it with `match_max_concurrent: false` and selected range greater than 24h and see a 502 response on `query_range` call.

**Comment by nowyp** [comment]
@cyriltovena I've adjusted `max_concurrent` in this case to 4 as have 4 cpus assigned to querier component pod.

So have below for testing:
```
  querier:
    replicas: 6
    resources:
      limits:
        cpu: 4000m
        memory: 4Gi
      requests:
        cpu: 4000m
        memory: 4Gi
```

And adjusted settings:

```
      querier:
        max_concurrent: 4

      frontend_worker:
        frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
        parallelism: 24 # tried different values here like 4, 16, 24 etc. (finally set 24 for 6 replicas of queries each 4vcpu)
        match_max_concurrent: false
```
Regarding the stats (two samples):

```
caller=spanlogger.go:87 org_id=myorgid Summary.BytesProcessedPerSecond="310 MB" Summary.LinesProcessedPerSecond=1205210 Summary.TotalBytesProcessed="28 GB" Summary.TotalLinesProcessed=107451110 Summary.ExecTime=1m29.155461166s

caller=spanlogger.go:87 org_id=myorgid Ingester.TotalReached=1346 Ingester.TotalChunksMatched=20 Ingester.TotalBatches=0 Ingester.TotalLinesSent=0 Ingester.HeadChunkBytes="115 kB" Ingester.HeadChunkLines=479 Ingester.DecompressedBytes="41 MB" Ingester.DecompressedLines=158975 Ingester.CompressedBytes="5.7 MB" Ingester.TotalDuplicates=0 Store.TotalChunksRef=8151 Store.TotalChunksDownloaded=8151 Store.ChunksDownloadTime=34m27.574269346s Store.HeadChunkBytes="0 B" Store.HeadChunkLines=0 Store.DecompressedBytes="28 GB" Store.DecompressedLines=107291656 Store.CompressedBytes="3.8 GB" Store.TotalDuplicates=0

---

ts=2021-12-02T11:10:12.524935501Z caller=spanlogger.go:87 org_id=myorgid Summary.BytesProcessedPerSecond="304 MB" Summary.LinesProcessedPerSecond=1178664 Summary.TotalBytesProcessed="28 GB" Summary.TotalLinesProcessed=107325013 Summary.ExecTime=1m31.056454484s

caller=spanlogger.go:87 org_id=myorgid Ingester.TotalReached=1346 Ingester.TotalChunksMatched=25 Ingester.TotalBatches=0 Ingester.TotalLinesSent=0 Ingester.HeadChunkBytes="34 kB" Ingester.HeadChunkLines=99 Ingester.DecompressedBytes="54 MB" Ingester.DecompressedLines=161983 Ingester.CompressedBytes="7.4 MB" Ingester.TotalDuplicates=0 Store.TotalChunksRef=8124 Store.TotalChunksDownloaded=8124 Store.ChunksDownloadTime=33m30.270536145s Store.HeadChunkBytes="0 B" Store.HeadChunkLines=0 Store.DecompressedBytes="28 GB" Store.DecompressedLines=107162931 Store.CompressedBytes="3.8 GB" Store.TotalDuplicates=0
```

I just wondering whether it is a some kind of problem with `query_frontend` proxy because from the stats as I understand the querier components processed and returned the result.
