### ISSUE TITLE
Derived fields in combination with line_format

### ISSUE THREAD

**Issue by davidvidrih** [grafana/loki#4021]
Using Grafana+Loki+Tempo.
Lets say I have log lines like '... traceID=d2432...'. I can use derived field to create URL link to Tempo traces, great.
This works in Explore, but only until I'm not adding line_format that removes the "traceID=". It seems that derived fields are evaluated on the final result, in case of line_format on line_format result. Makes sense.
In other words, I cannot have nicely line_format-ted lines without traceID= and trace links at the same time?
Thank you!

**Comment by wodka** [comment]
this would be really great!

**Comment by tomaszgawlik** [comment]
I came across the same problem

**Comment by ThommyH** [comment]
this is still a problem, as it requires us to add the trace id into the output message just for the link to work

**Comment by stevendungan** [comment]
@davidvidrih @wodka @tomaszgawlik @ThommyH you can now create a derived field based on a label. This includes parsed labels and structured metadata.

https://grafana.com/docs/grafana/latest/datasources/loki/configure-loki-data-source/#derived-fields

Does this solve your problem?

<img width="713" alt="image" src="https://github.com/grafana/loki/assets/114922977/71eaedd1-2cf6-4429-b31a-e8b3431f23a9">

**Comment by KaydenMiller** [comment]
@stevendungan do you know how to configure this via the `datasources.yaml` syntax? That document mentions that you can set the type but I have been unable to find a source that talks about how to do it in the yaml rather than via the UI.

Similar to:

```yaml
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          type: Label
          datasourceUid: TEMPO_DATASOURCE
          matcherRegex: 'TraceId'
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'
```
