### ISSUE TITLE
promtail can't parse system.log as a static_config

### ISSUE THREAD

**Issue by VihanAgarwal97** [grafana/loki#4036]
**Describe the bug**
I'm trying to scrape `system.log` from my mac via a local setup of promtail for testing purposes. 

**To Reproduce**
Deploy the promtail helm chart with the following values
```
extraVolumes:
  - name: syslog
    hostPath:
      path: /var/log/system.log
extraVolumeMounts:
  - name: syslog
    mountPath: /syslog/log
    readOnly: true
config:
  logLevel: debug
  lokiAddress: http://loki-stack.logging:3100/loki/api/v1/push
  snippets:
    pipelineStages:
      - docker: {}
    extraScrapeConfigs: |
      - job_name: syslog
        static_configs:
        - targets:
            - localhost
          labels:
            job: syslog
            __path__: /syslog/log/system.log
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: replace
            source_labels: ['__meta_kubernetes_node_name']
            target_label: node_name


```

**Expected behavior**
I expect to have the following metric `{job="syslog", node_name="foo"}`. 

**Environment:**
 - Infrastructure: k3d, local setup
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
```
│ level=debug ts=2021-07-23T16:33:36.2672584Z caller=timestamp.go:176 component=file_pipeline msg="extracted data did not contain a timestamp"                              │
│ level=debug ts=2021-07-23T16:33:36.266194Z caller=json.go:130 component=file_pipeline component=stage type=json msg="failed to unmarshal log line" err="ReadMapCB: expect │
│  { or n, but found 2, error found in #1 byte of ...|2021-07-23T|..., bigger context ...|2021-07-23T16:33:17.4312828Z stderr F level=debug t|..."                          │
│ level=debug ts=2021-07-23T16:33:36.2682432Z caller=json.go:130 component=file_pipeline component=stage type=json msg="failed to unmarshal log line" err="ReadMapCB: expec │
│ t { or n, but found 2, error found in #1 byte of ...|2021-07-23T|..., bigger context ...|2021-07-23T16:33:17.4313388Z stderr F level=debug t|..."                         │
│ level=debug ts=2021-07-23T16:33:36.2677126Z caller=output.go:75 component=file_pipeline msg="extracted data did not contain output source"
```
