### ISSUE TITLE
Components require certain config sections that they don't seem to use

### ISSUE THREAD

**Issue by glynnforrest** [grafana/loki#4038]
**Describe the bug**
When running in microservices mode, I would like to run each component with the minimum config possible, i.e. no `ingester_client` config for the `ingester` target, no `schema_config` for the `query_frontend` target, etc.

With only component-specific settings in the config file, different loki targets will fail to start.

**To Reproduce**

Run `loki -target query-frontend` with the config documented in https://grafana.com/docs/loki/latest/configuration/query-frontend:

```yaml
# Disable the requirement that every request to Cortex has a
# X-Scope-OrgID header. `fake` will be substituted in instead.
auth_enabled: false

# We don't want the usual /api/prom prefix.
http_prefix:

server:
  http_listen_port: 3100

query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 5
  # parallelize queries in 15min intervals
  split_queries_by_interval: 15m
  cache_results: true

  results_cache:
    cache:
      # We're going to use the in-process "FIFO" cache
      enable_fifocache: true
      fifocache:
        size: 1024
        validity: 24h

limits_config:
  max_cache_freshness_per_query: '10m'

frontend:
  log_queries_longer_than: 5s
  downstream_url: http://querier.<namespace>.svc.cluster.local:3100
  compress_responses: true
```

```
level=error ts=2021-07-23T20:56:35.608525154Z caller=main.go:87 msg="validating config" err="invalid schema config: must specify at least one schema configuration"
```

This happens with other components and apparently unrelated config sections.

**Expected behavior**

It would be nice if:

* Each target only required config sections it uses
* The docs were updated to include examples of a minimum required config file for each target
* (Breaking change) Perhaps the targets could throw an error when passed a config file with an irrelevant section?

I notice in https://github.com/grafana/helm-charts/blob/f706ce12ced10f28fa2f73bea8fa3eb16d8cc4fd/charts/loki-distributed/values.yaml#L61 that one config file is used for all components. I wonder if separate smaller config files have been considered much?

**Environment:**

Docker and Nomad, but I don't think this is relevant.

**Screenshots, Promtail config, or terminal output**

`query-frontend` example:

![image](https://user-images.githubusercontent.com/578458/126841797-72cc58c2-c49d-4940-a8ac-62774880c91b.png)
