### ISSUE TITLE
Promtail Pipeline Stage via Annotations

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#4076]
It would be nice to have a way to declare pipeline stages to apply for a specific pods via annotations of that pods.

This will greatly helps multiple teams that are working on the same cluster with a single daemonset of promtail otherwise they all need to modify the same configuration.

I suggest we add a new configuration to the `kubernetes_sd` that allows to activate/deactivate this feature.

For example:

```yaml
kind: Deployment
metadata:
  name: website
  namespace: prod
  labels:
    app:  order
spec:
  template:
    metadata:
      labels:
        name: order
      annotations:
        grafana.com/promtail/stages: 'yml or b64 yaml'
    spec:
      containers:
      - name: foo
        image: foo.bar
```

PS: this is something that has been requested to me multiple times in meetings.
