### ISSUE TITLE
Docker Driver causes deadlock in `dockerd`

### ISSUE THREAD

**Issue by jeschkies** [grafana/loki#4082]
**Describe the bug**
The Loki Docker driver seems to block a container when the Loki endpoint is not reachable. The Docker daemon gets stuck and needs to be killed and restarted to clean up the container.

**To Reproduce**
1. Install the Docker driver `docker plugin install grafana/loki-docker-driver:latest --alias loki-compose --grant-all-permissions`.
2. Launch a services with the following Docker compose configuration
    ```
   version: '3.4'
   services:
    log-gen:
      logging:
        driver: loki-compose
        options:
          loki-url: "http://doesnotexist:8001/loki/api/v1/push"
      image: mingrammer/flog
      command: ["-f", "json", "-l"]
    ```
    Note that the Loki endpoint does not exist.
3. Kill the service with Ctrl-C.
4. Try to remove it with `docker rm -f` or `docker kill`. See that the command gets stuck.

**Expected behavior**
The commands `docker rm -f` or `docker kill` should always be able to remove the container.

**Comment by cyriltovena** [comment]
cc @kavirajk

**Comment by jeschkies** [comment]
I've inched a little close. See https://github.com/moby/moby/issues/42705. The Docker daemon is trying to flush all logs but Loki is stuck in a backoff. Even a restart of the Loki driver is not helping since the daemon is not restarting the logging.

**Comment by jeschkies** [comment]
The issues was a cofiguration in Loki. `retries=0` in the Docker driver does *not* disable retries but means infinite tries. The issues in the Docker engine is orthorgonal.

**Comment by SimmyD** [comment]
I hit this today too.  was really hard to recover from.  Disabled till i can find a stable way of doing this.  If my server reboots which has the loki container on it it will crawl to a hold on boot.  Is there a known config/process to work around this?

**Comment by IndeedNotJames** [comment]
> I hit this today too. was really hard to recover from. Disabled till i can find a stable way of doing this. If my server reboots which has the loki container on it it will crawl to a hold on boot. Is there a known config/process to work around this?

In case of Loki:
You could leave the native Docker plugin behind (for now) and use something similar to:

_Docker logs -> systemd/journald -> Promtail -> Loki_
instead of
_Docker logs -> Loki log driver plugin -> Loki_

Example `scrape_config` (Promtail):
```yaml
scrape_configs:
  - job_name: journal
    journal:
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'

      - source_labels: ['__journal__hostname']
        target_label: 'hostname'

      - source_labels: ['__journal_container_name']
        target_label: 'docker_container_name'

      - source_labels: ['__journal_container_id']
        target_label: 'docker_container_id'
```

See https://docs.docker.com/config/containers/logging/journald/ for additional `source_labels` and setup.

That's IMHO better than using Promtail to scrape all `/var/lib/docker/containers/*/*-json.log` files as a workaround (recommended in https://grafana.com/docs/loki/latest/clients/docker-driver/#know-issues [[permalink](https://github.com/grafana/loki/blob/625d19cddbd67afb2d7e6bc5f0f85f9b73e3e073/docs/sources/clients/docker-driver/_index.md#know-issues)] and mentioned in #2361)
