### ISSUE TITLE
kubernetes_sd_configs/relabel_configs don't work with scrape_configs

### ISSUE THREAD

**Issue by VihanAgarwal97** [grafana/loki#4084]
**Describe the bug**
I'm not sure what the bug is exactly but I can't get `relabel_configs` to add a kubernetes `node_name` to logs scraped via `static_configs`. I've posted on the [forum ](https://community.grafana.com/t/cant-add-dynamic-labels-to-my-static-configs-in-promtail/50941) and have had no luck there.

**To Reproduce**
1. Use the following config locally using the promtail `helm-chart` with any `system.log` file - 
```
extraVolumes:
  - name: syslog-vol
    hostPath:
      path: /vol
extraVolumeMounts:
  - name: syslog-vol
    mountPath: /vol
    readOnly: true
config:
  logLevel: debug
  lokiAddress: http://loki-stack.logging:3100/loki/api/v1/push
  snippets:
    extraScrapeConfigs: |
      - job_name: syslog
        static_configs:
        - targets:
            - localhost
          labels:
            job: syslog
            __path__: /vol/system.log
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: replace
            source_labels: ['__meta_kubernetes_node_name']
            target_label: node_name
```

**Expected behavior**
I expect to have `{job="syslog", node_name="<some-name>"}`, but all I have is `{job="syslog"}`.  I also see that the `kubernetes_sd_configs` scrape is happening but the relabel doesn't have anything in `$1`. 
 
**Environment:**
 - Infrastructure: k3d (kubernetes 1.21)
 - Deployment tool: promtail helm-chart

**Screenshots, Promtail config, or terminal output**
![promtail service discovery](https://user-images.githubusercontent.com/24706134/127700420-0852eb16-3eb8-4f60-b542-7040c1f76767.jpeg)
