### ISSUE TITLE
Loki not creating Chunk nor Index tables on Cassandra with table_manager enabled (Loki image v2.2.1)

### ISSUE THREAD

**Issue by jyengk** [grafana/loki#4121]
**Describe the bug**
Loki-distributed is not creating chunks nor index tables to Cassandra.

Loki ConfigMap:

```
Name:         loki
Namespace:    loki-distributed
Labels:       app.kubernetes.io/instance=loki
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=loki-distributed
              app.kubernetes.io/version=2.2.1
              helm.sh/chart=loki-distributed-0.35.0
Annotations:  meta.helm.sh/release-name: loki
              meta.helm.sh/release-namespace: loki-distributed

Data
====
config.yaml:
----
auth_enabled: false
server:
  http_listen_port: 3100
distributor:
  ring:
    kvstore:
      store: memberlist
memberlist:
  join_members:
    - loki-memberlist
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  chunk_idle_period: 30m
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_retain_period: 1m
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m
schema_config:
  configs:
    - from: 2021-07-30
      store: cassandra
      object_store: cassandra
      schema: v11
      index:
        prefix: lkindex_
        period: 168h
      chunks:
        prefix: lkchunk_
        period: 168h
storage_config:
  cassandra:
    addresses: cassandra.loki-distributed.svc.cluster.local
    keyspace: lokikeyspace
    auth: true
    username: cassandra
    password: password
    timeout: 300s
    connect_timeout: 30s
chunk_store_config:
  max_look_back_period: 168h
table_manager:
  retention_deletes_enabled: true
  retention_period: 168h
query_range:
  align_queries_with_step: true
  max_retries: 5
  split_queries_by_interval: 15m
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 1024
        validity: 24h
frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  tail_proxy_url: http://loki-querier:3100
compactor:
  shared_store: filesystem
ruler:
  storage:
    type: local
    local:
      directory: /etc/loki/rules
  ring:
    kvstore:
      store: memberlist
  rule_path: /tmp/loki/scratch
  alertmanager_url: https://alertmanager.xx
  external_url: https://alertmanager.xx

```

```
cassandra@cqlsh> select * from system_schema.keyspaces where keyspace_name = 'lokikeyspace';

 keyspace_name | durable_writes | replication
---------------+----------------+-------------------------------------------------------------------------------------
  lokikeyspace |           True | {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '3'}

(1 rows)

cassandra@cqlsh> select table_name from system_schema.tables where keyspace_name='lokikeyspace';

 table_name
------------

(0 rows)

cassandra@cqlsh>  SELECT index_name FROM system_schema.indexes WHERE keyspace_name = 'lokikeyspace';

 index_name
------------

(0 rows)


```

**To Reproduce**

1. Fetch Loki distributed helm chart
2. loki.config should be my above snippet
3. helm install loki-distributed

**Expected behavior**
Cassandra keyspace should have tables created for chunks and indices.

**Environment:**
 - Infrastructure: Openshift
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
ingester logs:

```
ts=2021-08-08T19:20:40.606448263Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve loki-memberlist: lookup loki-memberlist on 172.30.0.10:53: no such host"
level=info ts=2021-08-08T19:21:08.700444291Z caller=memberlist_client.go:521 msg="joined memberlist cluster" reached_nodes=2
level=error ts=2021-08-08T19:35:50.162209747Z caller=flush.go:220 org_id=fake msg="failed to flush user" err="unconfigured table lkchunk_2692"
```

querier logs:

```
level=info ts=2021-08-08T19:21:07.944676331Z caller=memberlist_client.go:521 msg="joined memberlist cluster" reached_nodes=2
level=error ts=2021-08-08T19:40:37.73349848Z caller=chunk_store.go:543 org_id=fake traceID=46fa7cef6a2c0ec7 msg="error querying storage" err="unconfigured table lkindex_2692"
level=warn ts=2021-08-08T19:40:37.738937235Z caller=logging.go:71 traceID=46fa7cef6a2c0ec7 msg="GET /loki/api/v1/labels (500) 95.401407ms Response: \"unconfigured table lkindex_2692\\n\" ws: false; Accept: */*; User-Agent: curl/7.68.0; "
```

**Comment by jyengk** [comment]
In helm charts, tableManager is set to false for loki-distributed.
Enabled tableManager in the tableManager helm section 
```
tableManager:
  # -- Specifies whether the table-manager should be enabled
  enabled: true
  image:
    # -- The Docker registry for the table-manager image. Overrides `loki.image.registry`
    registry: null
    # -- Docker image repository for the table-manager image. Overrides `loki.image.repository`
    repository: null
    # -- Docker image tag for the table-manager image. Overrides `loki.image.tag`
    tag: null
  # -- The name of the PriorityClass for table-manager pods
```
