### ISSUE TITLE
Loki fails to start all instances if the ruler remote_write configuration is "invalid"

### ISSUE THREAD

**Issue by RyanSquared** [grafana/loki#4136]
**Describe the bug**
When setting the `ruler.remote_write.enabled` field to false, the value for `ruler.remote_write.client.url` should be ignored. This happens for all instances of Loki, most of which share a config file, even if those instances have (I assume) nothing to do with the ruler instances.

**To Reproduce**
1. Started Loki v2.3.0 with a configuration similar to:

```
ruler:
  remote_write:
    enabled: ${LOKI_RULER_REMOTE_WRITE_ENABLED:-false}
    client:
      url: ${LOKI_RULER_REMOTE_WRITE_CLIENT_URL}
```

Given the above configuration, the two values transform to "false" and "" respectively.

**Expected behavior**

Loki starts like normal.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Kubernetes and Kustomize

Logs:

```
failed parsing config: /etc/loki/config/config.yaml: url for remote_write is empty
```

**Comment by dannykopping** [comment]
Hey @RyanSquared 

Thanks for reporting this. I tried to replicate this as follows:

```yaml
ruler:
  remote_write:
    enabled: false
    client:
      url: ""
```

Loki started as normal.

However when I set a blank value of `url:`, then I replicated your behaviour. I was obviously just using the empty `""` string in my development when testing how this would behave, but evidently our YAML parser treats an empty value and an empty string differently.

I'll work on a patch :+1:
