### ISSUE TITLE
Loki v2.3.0 gives "Request Timed Out" error

### ISSUE THREAD

**Issue by RyanSquared** [grafana/loki#4137]
**Describe the bug**
When running almost any query, no matter what, Loki returns an error with suggestions on decreasing the request duration or adding more labels.

**To Reproduce**
1. Started Loki v2.3.0
2. Run any query

Configuration file:

```
auth_enabled: false
chunk_store_config:
  chunk_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: memcached
      service: memcached-client
compactor:
  shared_store: aws
distributor:
  ring:
    kvstore:
      store: memberlist
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  max_outstanding_per_tenant: 1024
  tail_proxy_url: http://querier:3100/
frontend_worker:
  frontend_address: query-frontend:9095
  grpc_client_config:
    max_send_msg_size: 104857600
  parallelism: 2
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 15m
  lifecycler:
    heartbeat_period: 5s
    join_after: 30s
    num_tokens: 512
    ring:
      heartbeat_timeout: 1m
      kvstore:
        store: memberlist
      replication_factor: 3
  max_transfer_retries: 60
  autoforget_unhealthy: true
ingester_client:
  grpc_client_config:
    max_recv_msg_size: 67108864
  remote_timeout: 1s
limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: ${LOKI_LIMITS_CONFIG_INGESTION_BURST_SIZE_MB:-20}
  ingestion_rate_mb: ${LOKI_LIMITS_CONFIG_INGESTION_RATE_MB:-10}
  ingestion_rate_strategy: global
  max_cache_freshness_per_query: 10m
  max_concurrent_tail_requests: ${LOKI_LIMITS_CONFIG_MAX_CONCURRENT_TAIL_REQUESTS:-100}
  max_global_streams_per_user: 10000
  max_query_length: 12000h
  max_query_parallelism: 256
  max_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 168h
memberlist:
  join_members:
    - distributor
    - ingester
    - querier
    - ruler
querier:
  engine:
    # Must be a multiple of schema_config index.period
    # Default to 400 days retention.
    max_look_back_period: 9600h
  query_ingesters_within: 2h
  query_timeout: ${LOKI_QUERIER_QUERY_TIMEOUT:60s}
query_range:
  align_queries_with_step: true
  cache_results: true
  parallelise_shardable_queries: true
  results_cache:
    cache:
      memcached_client:
        consistent_hash: true
        host: memcached-frontend
        max_idle_conns: 16
        service: memcached-client
        timeout: 500ms
  split_queries_by_interval: 30m
ruler:
  alertmanager_url: ${LOKI_RULER_ALERTMANAGER_URL}
  external_url: ${LOKI_RULER_EXTERNAL_URL}
  enable_alertmanager_v2: true
  enable_api: true
  enable_sharding: true
  #remote_write:
  #  enabled: ${LOKI_RULER_REMOTE_WRITE_ENABLED:-false}
  #  client:
  #    url: ${LOKI_RULER_REMOTE_WRITE_CLIENT_URL}
  ring:
    kvstore:
      store: memberlist
  rule_path: /run/loki/ruler/scratch/
  storage:
    type: local
    local:
      directory: /etc/loki/rules
schema_config:
  configs:
    - from: "2020-10-24"
      index:
        period: 24h
        prefix: loki_index_
      object_store: aws
      schema: v11
      store: boltdb-shipper
server:
  graceful_shutdown_timeout: 5s
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_listen_port: 3100
  http_server_write_timeout: 1m
storage_config:
  aws:
    s3: s3:///
    bucketnames: ${LOKI_STORAGE_CONFIG_AWS_BUCKETNAMES}
    sse_encryption: true
  boltdb_shipper:
    shared_store: aws
  index_queries_cache_config:
    memcached:
      batch_size: 100
    memcached_client:
      consistent_hash: true
      host: memcached-index-queries
      service: memcached-client
```

**Expected behavior**
Logs are returned for the given time range

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Kustomize (https://gitlab.com/Beeper/kustomize-loki forked from https://github.com/BitGo/kustomize-loki)

**Screenshots, Promtail config, or terminal output**

```
level=info ts=2021-08-11T04:34:13.363190618Z caller=metrics.go:92 org_id=fake traceID=13082a1059d917f1 latency=fast query="{app=\"loki\"}" query_type=limited range_type=range length=5m1s step=200ms duration=104.983µs status=500 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
level=warn ts=2021-08-11T04:34:13.363320213Z caller=logging.go:71 traceID=13082a1059d917f1 msg="GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bapp%3D%22loki%22%7D&start=1628656152000000000&end=1628656453000000000&step=0.2 (504) 464.597µs Response: \"Request timed out, decrease the duration of the request or add more label matchers (prefer exact match over regex match) to reduce the amount of data processed.\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-US,en;q=0.5; Sec-Fetch-Dest: empty; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Agent: Grafana/7.4.3; X-Forwarded-For: 192.168.45.9, 192.168.29.83, 192.168.29.83; X-Grafana-Org-Id: 1; X-Real-Ip: 192.168.45.9; X-Request-Id: 0c96f5a03958ea16196526f71021ee17; X-Scheme: https; uber-trace-id: 13082a1059d917f1:13082a1059d917f1:0000000000000000:0; "
level=info ts=2021-08-11T04:34:22.26972342Z caller=metrics.go:92 org_id=fake traceID=4530dfaf14b8a907 latency=fast query="{app=\"grafana\"}" query_type=limited range_type=range length=5m1s step=200ms duration=156.85µs status=500 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
level=warn ts=2021-08-11T04:34:22.269899936Z caller=logging.go:71 traceID=4530dfaf14b8a907 msg="GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bapp%3D%22grafana%22%7D&start=1628656162000000000&end=1628656463000000000&step=0.2 (504) 659.339µs Response: \"Request timed out, decrease the duration of the request or add more label matchers (prefer exact match over regex match) to reduce the amount of data processed.\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate, br; Accept-Language: en-US,en;q=0.5; Sec-Fetch-Dest: empty; Sec-Fetch-Mode: cors; Sec-Fetch-Site: same-origin; User-Agent: Grafana/7.4.3; X-Forwarded-For: 192.168.45.9, 192.168.29.83, 192.168.29.83; X-Grafana-Org-Id: 1; X-Real-Ip: 192.168.45.9; X-Request-Id: a11a7b415d1ecdadaedb9f42609eeaa9; X-Scheme: https; uber-trace-id: 4530dfaf14b8a907:4530dfaf14b8a907:0000000000000000:0; "
```
