### ISSUE TITLE
Using backticks in promtail 2.3 log selector fails

### ISSUE THREAD

**Issue by xkilian** [grafana/loki#4146]
**Describe the bug**
Using backticks in a log selector expression will fail with "syntax error: unexpected IDENTIFIER, expecting STRING

**To Reproduce**
1. Started Loki 2.3
2. Started Promtail 2.3
3. Use the following expression

```
pipeline_stages:
  - match:
      selector: '{job="snmptrap", ip=~`10\..*`}'
      stages:
        ...
```
Replacing backticks with quotes and escaping using \ does work as expected. The release notes did not state that backticks would no longer be supported.

**Expected behavior**
Worked in 2.2. I would expect it to work in 2.3.

**Environment:**
 - Linux AMD64

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
