### ISSUE TITLE
copy_file_range: input/output error on CIFS backed PV

### ISSUE THREAD

**Issue by levindecaro** [grafana/loki#4167]
**Describe the bug**
When loki storage is backed by CIFS, loki will crash every few mins with upload failed exception message.

Loki are running as StatefulSet with 3 replica

PV mapping as below
- /loki-index <- per pod RWO on CIFS
- /loki            <- shared with 3 pod RWX  on CIFS

Remark: Same configuration on CephFS did not crash.

**To Reproduce**
1. Started Loki 2.2.1
2. Let it run for few mins, until it reach flush interval.

**Expected behavior**
No crashes.

**Environment:**
 - Infrastructure: OpenShift 4.6, fluent-bit, KVM, CentOS Samba 4.10
 - Deployment tool: Typical k8s deployment style.

**Screenshots, Promtail config, or terminal output**
```
level=info ts=2021-08-14T12:27:08.144318744Z caller=table.go:336 msg="uploading table index_18853"
level=error ts=2021-08-14T12:27:08.19455963Z caller=table_manager.go:185 msg="failed to upload dbs" table=index_18853 err="write /loki/chunks/index/index_18853/loki-0-1628940786375417760-1628942706.gz: copy_file_range: input/output error"
```

Configuration
```
auth_enabled: false
frontend:
  compress_responses: true

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 419430400
  grpc_server_max_send_msg_size: 419430400


distributor:
  ring:
    kvstore:
      store: memberlist
memberlist:
    gossip_nodes: 3
    abort_if_cluster_join_fails: false
    join_members:
      - loki-gossip-ring.caas.svc.cluster.local:7946
    max_join_backoff: 1m
    max_join_retries: 10
    min_join_backoff: 5s
    rejoin_interval: 5s
    dead_node_reclaim_time: 30s
    gossip_to_dead_nodes_time: 15s
    left_ingesters_timeout: 30s
    packet_write_timeout: 10s
    packet_dial_timeout: 10s
    leave_timeout: 10s

query_range:
  split_queries_by_interval: 24h
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_bytes: 4096MB
        validity: 3h
        
ingester:
  lifecycler:
    join_after: 30s
    observe_period: 5s
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
    final_sleep: 30s
  max_chunk_age: 1h
  chunk_idle_period: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 15m
  max_transfer_retries: 3

ingester_client:
  grpc_client_config:
    max_recv_msg_size: 419430400
                      

schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  index_cache_validity: 5m
  index_queries_cache_config:
    enable_fifocache: true
    default_validity: 5m
    fifocache:
      max_size_bytes: 128MB
  boltdb_shipper:
    shared_store: filesystem
    active_index_directory: /loki-index
    cache_location: /loki-index/boltdb-cache
    cache_ttl: 24h
    
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 744h
  ingestion_burst_size_mb: 128
  ingestion_rate_mb: 96

chunk_store_config:
  max_look_back_period: 744h
  cache_lookups_older_than: 24h
  chunk_cache_config:
    enable_fifocache: true
    default_validity: 15m
    fifocache:
      max_size_bytes: 128MB
  
table_manager:
  retention_deletes_enabled: true
  retention_period: 744h
  
```
