### ISSUE TITLE
v2.3.0 Log Entry Deletion API not found 404

### ISSUE THREAD

**Issue by michaelkebe** [grafana/loki#4171]
**Describe the bug**
The documentation found here: https://grafana.com/docs/loki/v2.3.0/operations/storage/logs-deletion/ says that the API endpoint to request a deletion is: POST /loki/api/admin/delete

But I get a 404.

**To Reproduce**
1. Start grafana/loki:2.3.0
2. curl -X POST 'http://localhost:3100/loki/api/admin/delete?match[]={label_name="label_value"}' returns 404

**Expected behavior**
Successfully request the deletion.

**Environment:**
 - docker

**Comment by dannykopping** [comment]
Hi @michaelkebe 

Can you please send through your configuration?
Did you enable the `retention_enabled` setting?

**Comment by michaelkebe** [comment]
docker-compose.yml:
```
version: "3"

services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    logging:
      driver: loki
      options:
        loki-url: http://XXXXXX:3100/loki/api/v1/push

  log-generator:
    image: mingrammer/flog
    command: "-d 10 -n 10000000"
    logging:
      driver: loki
      options:
        loki-url: http://XXXXXX:3100/loki/api/v1/push
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:8.1.1
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    logging:
      driver: loki
      options:
        loki-url: http://XXXXXX:3100/loki/api/v1/push
```

loki-local-config.yaml
```
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or
 max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read
 cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: false
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 100
  max_streams_per_user: 20000

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 3d

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
```

grafana-datasources.yml:
```
---
datasources:
  - name: loki
    type: loki
    orgId: 1
    url: loki:3100
```
