### ISSUE TITLE
multiple nodes for loki is a real cluster?

### ISSUE THREAD

**Issue by ningyougang** [grafana/loki#4209]
I did some test about local filesystem storage and ceph s3 both.

I deployed 3 loki pods including loki-0, loki-1, loki-2 and several promtail pods using `grafana/loki-stack helm chars`

### Local filesystem
* if the loki-0 pod stored the logs into local filesystem, but other pod(e.g. loki-1 or loki-2) recevied the query log request, can't query the logs. 
* It seems the log was not replicated between loki pods, so running Loki clustered is not possible with the local filesystem. My  test result proved the official document: https://grafana.com/docs/loki/latest/operations/storage/filesystem/
### ceph s3.
part of configuration as below
```
  schema_config:
    configs:
    - from: 2021-08-12
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
  server:
    http_listen_port: 3100
  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
      shared_store: s3
    aws:
      s3: s3://xxx:xxx@xx.xx.xx.xx:80/<bucketName>
      s3forcepathstyle: true
```
* if the loki-0 pod stored the logs into ceph s3,  and if other pod(e.g. loki-1 or loki-2) recevied the query log request,  query the logs successfully, but exist some delay time, for my test, several minutes.
* I observed that after some time(maybe interval time), the index data will sync from ceph s3 to local filesystem.  e.g.

  ```
  level=info ts=2021-08-24T01:34:19.967296302Z caller=util.go:55 msg="downloaded file index_18863/loki-0-1629764359888401816-1629767700.gz"
  ```
  Also proved the document as well: https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper/

For my tests, i have `2` questions
* Not only filesystem but also shared storage(e.g. ceph s3), the loki pods are not form as a whole cluster like elasticsearch  (Maybe on shared storage, these loki pods just look like a cluster)
* On ceph s3, in spite of query logs successfully on all loki pods, but still exist some delay time, have any mothod to improve it?
  the best if we can do it in real time, but not supported in real time, i think 1 minute is ok. i am looking for configuration to support it.
