### ISSUE TITLE
consulagent_sd_config not found in type scrapeconfig.plain

### ISSUE THREAD

**Issue by SunSparc** [grafana/loki#4214]
**Describe the bug**
I just tried to use the `consulagent_sd_config` in my `promtail.yaml` configuration.

**To Reproduce**
1. Use the configuration details as specified [in the documentation](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#consulagent_sd_config)
```
          - job_name: 'nomad-consul-sd-logs'
            consulagent_sd_config:
              - server: 'localhost:8500'
            relabel_configs:
              - source_labels: [__meta_consul_node]
                target_label: __host__
              - etc...
```
2. Start `promtail'

**Expected behavior**
I expected this specification to work similarly to `consul_sd_config`.

**Environment:**
 - Infrastructure: Nomad/Consul cluster in the cloud
 - Deployment tool: `nomad`

**Screenshots, Promtail config, or terminal output**
Contents of `alloc/logs/taskname.stdout.0`
```
Unable to parse config: /etc/promtail/promtail.yaml: yaml: unmarshal errors:
  line 41: field consulagent_sd_config not found in type scrapeconfig.plain
Unable to parse config: /etc/promtail/promtail.yaml: yaml: unmarshal errors:
  line 41: field consulagent_sd_config not found in type scrapeconfig.plain
Unable to parse config: /etc/promtail/promtail.yaml: yaml: unmarshal errors:
  line 41: field consulagent_sd_config not found in type scrapeconfig.plain
```
