### ISSUE TITLE
Patching additional labels to pod creates duplicate log entries

### ISSUE THREAD

**Issue by mierak** [grafana/loki#4216]
**Describe the bug**
Patching additional labels onto a pod creates a new stream. However both old and new streams are pushed to Loki, resulting in duplicate entries. The issue resolves itself after a short period of time and only the new stream is sent to Loki.

**To Reproduce**
Loki and promtail version: 2.3.0
Patch additional label onto pod: 
```
kubectl patch pod <podname> --type='json' -p='[{"op":"add","path":"/metadata/labels/someLabel","value":"someValue"}]'
```
Query logs from the pod, use pod name as the only selector. 
Some logs are duplicated, one of the duplicates contains the new label.

**Expected behavior**
Only the new stream is pushed to Loki and no duplicate entries are found.

**Environment:**
 - Kubernetes
 - Deployment tool: pulumi

**Screenshots, Promtail config, or terminal output**
<details>
<summary>Promtail config</summary>

```yml
clients:
  - external_labels:
        cluster: test
    backoff_config:
        min_period: 100ms
        max_period: 10s
        max_retries: 20
    batchsize: 304800
    batchwait: 2s
    url: http://distributor.loki.svc.cluster.local:3100/loki/api/v1/push
    tenant_id: 1

scrape_configs:
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      labels:
        job: journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: nodename
  - job_name: kubernetes-pods-name
    kubernetes_sd_configs:
      - role: pod
    pipeline_stages:
      - cri: {}
      - labeldrop:
        - filename
        - app_kubernetes_io_managed_by
    relabel_configs:
      - source_labels:
          - __meta_kubernetes_pod_label_name
        target_label: __service__
      - source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ""
        source_labels:
          - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - __meta_kubernetes_namespace
          - __service__
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
  - job_name: kubernetes-pods-app
    kubernetes_sd_configs:
      - role: pod
    pipeline_stages:
      - cri: {}
      - match:
          selector: '<redacted>'
          stages:
          - regex:
              expression: "<redacted>"
          - output:
              source: output
          - template:
              source: <redacted>
              template: '<redacted>'
          - labels:
              <redacted>:
      - match:
          selector: '{app="eventrouter"}'
          stages:
          - json:
              expressions:
                event_namespace: event.metadata.namespace
          - labels:
              event_namespace:
      - labeldrop:
        - filename
    relabel_configs:
      - action: drop
        regex: .+
        source_labels:
          - __meta_kubernetes_pod_label_name
      - source_labels:
          - __meta_kubernetes_pod_label_app
        target_label: __service__
      - source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ""
        source_labels:
          - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - __meta_kubernetes_namespace
          - __service__
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
  - job_name: kubernetes-pods-direct-controllers
    kubernetes_sd_configs:
      - role: pod
    pipeline_stages:
      - cri: {}
      - labeldrop:
        - filename
    relabel_configs:
      - action: drop
        regex: .+
        separator: ""
        source_labels:
          - __meta_kubernetes_pod_label_name
          - __meta_kubernetes_pod_label_app
      - action: drop
        regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
        source_labels:
          - __meta_kubernetes_pod_controller_name
      - source_labels:
          - __meta_kubernetes_pod_controller_name
        target_label: __service__
      - source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ""
        source_labels:
          - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - __meta_kubernetes_namespace
          - __service__
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
  - job_name: kubernetes-pods-indirect-controller
    kubernetes_sd_configs:
      - role: pod
    pipeline_stages:
      - cri: {}
      - labeldrop:
        - filename
    relabel_configs:
      - action: drop
        regex: .+
        separator: ""
        source_labels:
          - __meta_kubernetes_pod_label_name
          - __meta_kubernetes_pod_label_app
      - action: keep
        regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
        source_labels:
          - __meta_kubernetes_pod_controller_name
      - action: replace
        regex: ([0-9a-z-.]+)-[0-9a-f]{8,10}
        source_labels:
          - __meta_kubernetes_pod_controller_name
        target_label: __service__
      - source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ""
        source_labels:
          - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - __meta_kubernetes_namespace
          - __service__
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
  - job_name: kubernetes-pods-static
    kubernetes_sd_configs:
      - role: pod
    pipeline_stages:
      - cri: {}
      - labeldrop:
        - filename
    relabel_configs:
      - action: drop
        regex: ""
        source_labels:
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_label_component
        target_label: __service__
      - source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ""
        source_labels:
          - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - __meta_kubernetes_namespace
          - __service__
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
          - __meta_kubernetes_pod_container_name
        target_label: __path__
```
</details>

<details>
<summary>File used to create pod to reproduce the issue</summary>

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      name: test-pod
      labels:
        app: test
    spec:
      containers:
      - name: test-container
        image: debian
        command: ["/bin/sh"]
        args: ["-c", "i=1; while [ true ]; do echo \"Loop $i\";i=$(( $i + 1 ));sleep 0.25;done;"]
```
</details>

<details>
<summary>Duplicate logs in grafana</summary>

![image](https://user-images.githubusercontent.com/47547062/130789174-234d63f5-9d90-4d6b-82a1-eed7e4ecfe6f.png)
</details>
