### ISSUE TITLE
Prommail collection log prompt permission denied

### ISSUE THREAD

**Issue by ktpktr0** [grafana/loki#4234]
loki and promtail version : 2.3.0

promtail config:
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  grpc_server_max_recv_msg_size: 15728640
  grpc_server_max_send_msg_size: 15728640

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.1.234:80/loki/api/v1/push

scrape_configs:
- job_name: dld_log
  static_configs:
  - targets:
      - 172.21.91.125
    labels:
      service: dld
      __path__: /usr/local/test/logs/*/*.log
```

I used wildcards to collect logs, but the following error occurred:
```
promtail-linux-amd64[26158]: level=error ts=2021-08-30T07:37:41.019326271Z caller=filetarget.go:286 msg="failed to start tailer" error="open /usr/local/test/log/dld_a_12_4/table_63.log: permission denied" filename=/usr/local/test/log/dld_a_12_4/table_63.log
```

In addition, how to configure multiple log directories
