### ISSUE TITLE
Log Entry Deletion doesn't work as expected

### ISSUE THREAD

**Issue by wzjjack** [grafana/loki#4239]
**Describe the bug**
Trying to delete the log by `loki/api/admin/delete`, but looks like the log still there.

**To Reproduce**
config.yaml
```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

querier:
  engine:
    max_look_back_period: 25h      

ingester:
  wal:
    enabled: true
    dir: /tmp/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 25h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 25h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 5m    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    cache_ttl: 25h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor
  shared_store: filesystem
  compaction_interval: 3m
  retention_enabled: true
  retention_delete_delay: 3m
  retention_delete_worker_count: 500
  delete_request_cancel_period: 10m

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 25h
  max_streams_per_user: 1000000
  max_entries_limit_per_query: 5000000

chunk_store_config:
  max_look_back_period: 25h

ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
```

- call delete API `curl --location -g --request POST 'http://localhost:3100/loki/api/admin/delete?match[]={abc=%22testtest%22}'`
- list delete requests and it is `processed` status `[{"request_id":"d1befe16","start_time":0,"end_time":1630385755.211,"selectors":["{abc=\"testtest\"}"],"status":"processed","created_at":1630385755.211}]`
- call query API, and the log looks like still there, `curl --location -g --request GET 'http://localhost:3100/loki/api/v1/query?query={abc=%22testtest%22}'`
  
![image](https://user-images.githubusercontent.com/52395237/131458997-b3833f22-bed3-4c49-819f-aac3d0949eb5.png)

**Expected behavior**
when the delete request processed, the log streams between `start_time:0` to `end_time:1630385755.211` should be deleted and shouldn't return when calling query API

Did I miss anything in the config file or misunderstand the delete API? And we need to delete the log as soon as possible when we call delete API, `delete_request_cancel_period` default is `24h`, can I set it to `1m` or `0`, it is `10m` on my side now.
