### ISSUE TITLE
Allow re-packing JSON

### ISSUE THREAD

**Issue by terorie** [grafana/loki#4249]
**Is your feature request related to a problem? Please describe.**

A few JSON loggers use a format like this.

```json
{
  "t": "2021-08-31T23:55:01.661616473Z",
  "msg": "Imported new chain segment",
  "blocks": 1,
  "dirty": "12.33 MiB",
  "elapsed": "64.424ms",
  "hash": "0xaa454b5dfb5ef9b02c07fd806febc321916a55722aa872b223069ae07907ccb7",
  "lvl": "info",
  "mgas": 9.662569,
  "mgasps": 149.98317251268054,
  "number": "5418861",
  "txs": 72
}
```

They use static `t` (timestamp) and `msg` fields plus arbitrary fields depending on what's being logged.

This is surprisingly frustrating to parse with Promtail / Loki / Grafana.
The ideal way to transform and display this data in LogQL would be the following layout.

```json
{
  "_msg": "Imported new chain segment",
  "_extra": {
    "blocks": 1,
    "dirty": "12.33 MiB",
    "elapsed": "64.424ms",
    "hash": "0xaa454b5dfb5ef9b02c07fd806febc321916a55722aa872b223069ae07907ccb7",
    "lvl": "info",
    "mgas": 9.662569,
    "mgasps": 149.98317251268054,
    "number": "5418861",
    "txs": 72
  }
}
```

Transformed to the following using LogQL:

```
<timestamp> <msg> <key1=value1> <key2=value2> ...
```

e.g.

```
2021-08-31T23:55:01   Imported new chain segment     blocks='1' dirty='12.33 MiB'...
```

As of now, there is no Promtail stage that is able to do this.

**Describe the solution you'd like**

Similar to how the `pack` module works with labels and a raw string, a `json_pack` stage in Promtail or similar could allow for a Promtail JSON transformation.

```yaml
- json_pack:
    keys:
      - t
      - msg
```

Input: `{"t":1,"msg":2,"foo":3}`

Output: `{"t":1,"msg":2,"_extra":{"foo":3}}`

Example transformation from JSON using this Promtail feature:

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/21371810/131593325-c48b545c-12a5-448a-b98e-dd6db88f3c6d.png">

**Describe alternatives you've considered**

Using tricks in Promtail and LogQL, it's just about possible to solve this, but very ugly and not a sustainable solution.

1. Promtail: Wrap data in a single level of JSON (required because of #4248)

```yaml
        - json:
            expressions:
              timestamp: t
              msg: msg
        - labels:
            msg:
        - timestamp:
            source: timestamp
            format: RFC3339Nano
        - pack:
            labels:
              - msg
            ingest_timestamp: false
```

2. LogQL: Range over object and skip static labels to extract extra key value pairs

```
query
  | json
  | line_format "{{ .msg }} {{ range $k, $v := (fromJson ._entry) }}{{ if not (eq $k \"t\" \"msg\") }}{{ $k }}={{ $v }} {{ end }}{{ end }}"
```

**Additional context**

Related to #3671
