### ISSUE TITLE
Remove tmp storage in example of loki-local-config.yaml for Single machine deployment

### ISSUE THREAD

**Issue by MurzNN** [grafana/loki#4254]
**Describe the bug**
The example file `loki/loki-local-config.yaml` recommends to use /tmp folder for persistent storage. Here is that part from https://github.com/grafana/loki/blob/main/cmd/loki/loki-local-config.yaml:
```yaml
storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks
```
On many systems /tmp is cleared on each reboot, so all collected data will be deleted, that will confuse people!

I found it by link in this article https://grafana.com/docs/loki/latest/storage/#single-machinelocal-development-boltdbfilesystem when trying to find any "default" config to use as base. 

This example https://grafana.com/docs/loki/latest/configuration/examples/ is used /tmp for storage too...

So most of people, that searching any "default" config for local Loki instance, will be found the same config, that recommends to use temporary storage for persistent data!

**To Reproduce**
1. Install Loki on Linux machine or via docker
2. Grab the "recommended" config for single machine deployment
3. Start Loki, collect some useful data
4. Restart the docker container or system
5. See that all collected data are disappear

**Expected behavior**
Default and example configuration files should store persistent data not in temporary folders!
