### ISSUE TITLE
How does Loki collect metadata of docker container or k8s

### ISSUE THREAD

**Issue by ktpktr0** [grafana/loki#4266]
loki: 2.3.0
promtail: 2.3.0

I use the following configuration to collect the logs of the docker container, but when querying the log details, I can't find any metadata about the docker container or k8s the metadata

```
scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: docker
        __path__: /var/lib/docker/containers/*/*.log

    - targets:
        - localhost
      labels:
        job: docker
        __path__: /var/log/pod/*/*.log
```
Query results：
![image](https://user-images.githubusercontent.com/41657218/131971671-a00412c0-a58e-4c74-84ec-17a4777fe376.png)
