### ISSUE TITLE
promtail drop does not work

### ISSUE THREAD

**Issue by yongzhang** [grafana/loki#4269]
**Describe the bug**
promtail can't drop logs.

**To Reproduce**
1. Started Loki (SHA or version): 2.3.0
2. Started Promtail (SHA or version): 2.3.0
3. Promtail config:
```
      - job_name: kubernetes-pods-direct-controllers
        pipeline_stages:
          - docker: {}
          - match:
              selector: '{k8s_container="liveness-probe"}'
              action: drop
```

I can still get logs from grafana:
![image](https://user-images.githubusercontent.com/15604715/132008478-6595aabf-4bf5-4cff-af4e-d2caed702f70.png)

The container is one of the containers in a pod. (https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/charts/aws-efs-csi-driver/templates/controller-deployment.yaml#L98)

**Comment by liguozhong** [comment]
Match action is different from drop action. You should need drop action


pipeline_stages:
- drop:
    source: k8s_container
    value: liveness-probe

**Comment by yongzhang** [comment]
> Match action is different from drop action. You should need drop action
> 
> ```
> pipeline_stages:
> - drop:
>     source: k8s_container
>     value: liveness-probe
> ```

Looks like it doesn't work as well, I can still get logs:

![image](https://user-images.githubusercontent.com/15604715/132148095-e6e103ae-57ef-4fb1-9d27-9ea06ba659d1.png)

![image](https://user-images.githubusercontent.com/15604715/132148127-69683521-26e9-4cd2-b215-4657b24e05de.png)

**Comment by yongzhang** [comment]
actually I followed example here (the fifth stage): https://grafana.com/docs/loki/latest/clients/promtail/stages/match/#example

**Comment by liguozhong** [comment]
delete  match action
![image](https://user-images.githubusercontent.com/9583245/132155295-e23b2378-bcd3-441a-bf9b-3a83afb29273.png)

**Comment by yongzhang** [comment]
> delete match action
> ![image](https://user-images.githubusercontent.com/9583245/132155295-e23b2378-bcd3-441a-bf9b-3a83afb29273.png)

oh why? the first match is used to drop another filter:
```
    scrape_configs:
      # Pods with direct controllers, such as StatefulSet
      - job_name: kubernetes-pods-direct-controllers
        pipeline_stages:
          - docker: {}
          - match:
              selector: '{k8s_app=~"traefik"}'
              stages:
              - json:
                  expressions:
                    RouterName:
              - drop:
                  source:     "RouterName"
                  expression: "ping@internal"
```

**Comment by liguozhong** [comment]
label filter 

```
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: drop
        regex: 'liveness-probe'
        source_labels:
        - k8s_container
```
