### ISSUE TITLE
Promtail closes syslog connection when it fails to parse stream

### ISSUE THREAD

**Issue by loganmc10** [grafana/loki#4270]
**Describe the bug**
For whatever reason, sometimes syslog-ng seems to send appname labels that Loki doesn't like, I get this message in the Loki logs:
```
level=warn component=loki component=loki loki_config=1234 msg="error parsing syslog stream" err="expecting an app-name (from 1 to max 48 US-ASCII characters) or a nil value [col 57]"
```
However, at the same time, I get this on the syslog-ng side:
```
Syslog connection closed; fd='17', server='AF_INET(172.16.19.247:7514)', time_reopen='60'
```
It seems that Loki/Promtail disconnects the TCP session whenever it fails to parse one of the syslogs. This causes syslog-ng to go into a 60 second timer before reconnecting. This causes us to lose some logs.

**To Reproduce**
Send Promtail a syslog message with an improper appname label in the header

**Expected behavior**
I would expect Promtail to just drop the incorrectly formatted log, but continue to maintain the TCP session and accept other logs.

**Environment:**
syslog-ng 3.31.2 (docker), Grafana Agent v0.18

**Screenshots, Promtail config, or terminal output**
```
loki:
  configs:
  - name: 1234
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: https://xxxx:{{ api_key }}@logs-prod-us-central2.grafana.net/loki/api/v1/push
    - job_name: syslog
      syslog:
        listen_address: 0.0.0.0:7514
        labels:
          job: "syslog{{ env_suffix }}"
      relabel_configs:
        - source_labels: ['__syslog_message_hostname']
          target_label: 'hostname'
        - source_labels: ['__syslog_message_severity']
          target_label: 'severity'
        - source_labels: ['__syslog_message_facility']
          target_label: 'facility'
        - source_labels: ['__syslog_message_app_name']
          target_label: 'appname'
```

**Comment by loganmc10** [comment]
I guess this is related/same issue as mentioned here: https://github.com/grafana/loki/issues/3839#issuecomment-862725131

**Comment by IgorOhrimenko** [comment]
I have the same issue.
```
promtail_1   | level=warn ts=2021-09-22T08:43:09.780406405Z caller=syslogtarget.go:171 msg="error parsing syslog stream" err="message too long to parse. was size 8931, max length 8192"
promtail_1   | level=warn ts=2021-09-22T08:45:01.439683337Z caller=syslogtarget.go:171 msg="error parsing syslog stream" err="message too long to parse. was size 9457, max length 8192"
promtail_1   | level=warn ts=2021-09-22T08:46:18.854622543Z caller=syslogtarget.go:171 msg="error parsing syslog stream" err="message too long to parse. was size 25754, max length 8192"
promtail_1   | level=warn ts=2021-09-22T08:47:25.329564964Z caller=syslogtarget.go:171 msg="error parsing syslog stream" err="message too long to parse. was size 8687, max length 8192"
```

![изображение](https://user-images.githubusercontent.com/24807060/134312767-55382984-71f2-4cf9-9ce8-52d6b09b9dc7.png)

**Comment by loganmc10** [comment]
In case anyone comes across this same issue, I got around it by writing the appname to a structured data field, like this (if you're using syslog-ng):

syslog-ng.conf:
```
rewrite r_rewrite_set_appname {
  set("${PROGRAM}", value(".SDATA.custom@99770.appname"));
};

rewrite r_rewrite_unset{
  unset(value("PROGRAM"));
};

log {
  source(s_net);
  rewrite(r_rewrite_set_appname);
  rewrite(r_rewrite_unset);
  destination(d_loki);
};
```

Promtail:
```
    - job_name: syslog
      syslog:
        listen_address: 0.0.0.0:7514
        max_message_length: 65536
        label_structured_data: true
      relabel_configs:
        - source_labels: ['__syslog_message_hostname']
          target_label: 'hostname'
        - source_labels: ['__syslog_message_severity']
          target_label: 'severity'
        - source_labels: ['__syslog_message_facility']
          target_label: 'facility'
        - source_labels: ['__syslog_message_sd_custom_99770_appname']
          target_label: 'appname'
```
