### ISSUE TITLE
retention_enabled not found in type compactor.Config

### ISSUE THREAD

**Issue by ashish0x01** [grafana/loki#4284]
I'm using EKS k8s cluster and deployed the loki-stack using the helm chart...
now i'm trying to add retention period for older logs but it's throwing `field retention_delete_worker_count not found in type compactor.Config`

kindly have a look at my loki config
loki image tag: 2.2.0
```
config:
    auth_enabled: false
    ingester:
      chunk_idle_period: 3m
      chunk_block_size: 262144
      chunk_retain_period: 1m
      max_transfer_retries: 0
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: "168h"
    schema_config:
      configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    server:
      http_listen_port: 3100
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    chunk_store_config:
      max_look_back_period: "168h"
    table_manager:
      retention_deletes_enabled: true 
      retention_period: "168h"
    compactor:
      working_directory: /data/loki/boltdb-shipper-compactor
      shared_store: filesystem
      retention_enabled: true
      retention_delete_worker_count: 150
      retention_delete_delay: "1h"
```
