### ISSUE TITLE
How to reduce s3 storage file num

### ISSUE THREAD

**Issue by UnderTreeTech** [grafana/loki#4296]
Loki version: v2.3.0

I want to use loki to store microservices logs and my arch is boltdb+s3(minio).

I mocked 50k rpc revokes and each rpc produce 6 logs during a same trace.

Finally I found there're more than 80k small files in minio bucket.

How come it produce so many files? Is there any configs I can set to compact the files, just like tempo: `max_block_bytes`.
 
The following snippet is my loki config.
```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095 
  grpc_server_max_recv_msg_size: 15728640  
  grpc_server_max_send_msg_size: 15728640  

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m #5m
  chunk_retain_period: 30s
  max_transfer_retries: 0
  max_chunk_age: 20m  #20m 
  chunk_block_size : 1048576 # The maximum size in bytes a chunk can be before it should be flushed.

schema_config:
  configs:
    - from: 2021-09-01
      store: boltdb
      object_store: aws
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: /data/loki/index
  aws:
    # The period behind the domain forces the S3 library to use it as a host name, not as an AWS region.
    s3: http://tempo:supersecret@minio.:9000/loki
    s3forcepathstyle: true
    insecure: true

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 30  
  ingestion_burst_size_mb: 30 
  max_streams_per_user: 1000000

chunk_store_config:
  max_look_back_period: 168h 

table_manager:
  retention_deletes_enabled: true
  retention_period: 840h
```

And the pic is minio bucket files, every file is about 1k.
![image](https://user-images.githubusercontent.com/5195804/132690227-6e840742-ad6c-4ac2-bf1e-e9e86054d343.png)
