### ISSUE TITLE
Promtail warning: invalid or unsupported framing. first byte: 'G'

### ISSUE THREAD

**Issue by clambin** [grafana/loki#4370]
**Describe the bug**
Have set up Promtail and syslog-ng to feed my nodes' syslogs into Loki.   Log entries are flowing into Loki, but I continuously get the following warning from Promtail: 

```
caller=syslogtarget.go:161 msg="error initializing syslog stream" err="invalid or unsupported framing. first byte: 'G'"
```

Have looked into previous bug reports, but I only found one that stated you should use syslog-ng or Rsyslog to feed syslogs into Promtail (which is what I do).

What could be causing those warnings?

**To Reproduce**
1. Started Loki 2.3.0
2. Started Promtail 2.30
3. Start Syslog-ng 3.30.1

Promtail config:
```
   config:
      lokiAddress: http://loki-loki:3100/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          # Add an additional scrape config for syslog
          - job_name: syslog
            syslog:
              listen_address: 0.0.0.0:{{ .Values.extraPorts.syslog.containerPort }}
              labels:
                job: syslog
            relabel_configs:
              - source_labels:
                - __syslog_message_hostname
                target_label: host
```

syslog-ng config:
```
    @version: 3.30
    @include "scl.conf"
    options {
      time-reap(30);
      mark-freq(10);
      keep-hostname(yes);
      chain-hostnames(no);
    };
    source s_hostsyslog {
      file("/host/var/log/syslog" follow-freq(1));
    };
    destination d_loki {
      syslog("loki-promtail-syslog" transport("tcp") port(1514));
    };
    log {
      source(s_hostsyslog); destination(d_loki);
    };
```

**Expected behavior**
Warning message should not be there.

**Environment:**
 - Infrastructure: kubernetes on raspberry pi's. one master node (running loki) and three worker nodes.  
 - Deployment tool: helm + fluxcd

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
