### ISSUE TITLE
promtail ARM64 binary not compiled with systemd journal support

### ISSUE THREAD

**Issue by clothespin** [grafana/loki#4380]
**Describe the bug**
The arm64 binary release of Promtail is not compiled with systemd journal support. As a result, configuring the scrape_configs to scrape the systemd journal fails.
**To Reproduce**
1. Created the following config YAML on an arm64 (Rock64) host:
2. Downloaded the latest release of the promtail binary for arm64.
3. Started promtail with the given config YAML
4. Promtail prints the following warning: `level=warn ts=2021-09-25T02:50:22.501062921Z caller=journaltargetmanager.go:29 msg="WARNING!!! Journal target was configured but support for reading the systemd journal is not compiled into this build of promtail!"`

**Expected behavior**
Promtail correctly forwards systemd logs to the Loki instance.

**Environment:**
Bare metal running on Debian (Armbian) Buster.

**Screenshots, Promtail config, or terminal output**

System info:

```
$ uname -a
Linux balboa 5.10.63-rockchip64 #21.08.2 SMP PREEMPT Wed Sep 8 10:57:23 UTC 2021 aarch64 GNU/Linux
$ cat /etc/issue
Armbian 21.02.3 Buster \l
$ cat /etc/debian_version
10.10
```

Config:

```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://REDACTED/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'host'
      - source_labels: ['__journal__cmdline']
        target_label: 'cmdline'
      - source_labels: ['__journal__boot_id']
        target_label: 'boot_id'
      - source_labels: ['__journal__machine_id']
        target_label: 'machine_id'
```
Output:

```
level=warn ts=2021-09-25T03:05:41.255366157Z caller=journaltargetmanager.go:29 msg="WARNING!!! Journal target was configured but support for reading the systemd journal is not compiled into this build of promtail!"
```
