### ISSUE TITLE
Attach a static value as custom text to label in pipeline_stages

### ISSUE THREAD

**Issue by MurzNN** [grafana/loki#4384]
**Is your feature request related to a problem? Please describe.**
I have a container's logs with mixed output of nginx, php-fpm, php errors and custom application logs.
And to  I need to attach a fixed value as custom text to label in pipeline_stages, based on regexp matching, something like this:
```
if "log ~= '^{app="brick-drupal",': set label="drupal"
elseif "log ~= "NOTICE: PHP message|FastCGI sent in": set label="php-fpm"
elseif "log ~= "^Error": set label="php"
else: set label=nginx 
```
But if I try to fill a custom value to label, instead of extracted variable name, this label is not added (seem because it's value is converted to empty string).

Example:
```
- match:
    selector: '{container="brick-drupal"}'
    stages:
    - regex:
        expression: '^(?P<my_extracted_val>NOTICE: PHP message)'
    - labels:
        extracted_val: "my_extracted_val"
        custom_val: "php-fpm,"                     
```
As result I see no `custom_val` label in Loki database.

**Describe the solution you'd like**
There is exists static labels (named as `external_labels`) but it works only on the clients level.
Will be good to expand it to work on scraping level too.

**Describe alternatives you've considered**
Alternative way is to match the typed string to declared variable, and if no matches are found - use the typed text in label value as static value for that label.

**Comment by MurzNN** [comment]
Here is my workaround to fill custom value to label, using several replace stages:
```
- match:
    selector: '{app="brick-drupal", container="brick-drupal"} |~ "NOTICE: PHP message|FastCGI sent in"'
    stages:
    - replace:
        expression: "^(.*)"
        replace: "[php-fpm]: {{ .Value }}"
    - regex:
        expression: '^\[(?P<type>[^\]]+)\]: '
    - labels:
        type: "type"
    - replace:
        expression: '(^\[[^\]]+\]: )'
        replace: ""
```

**Comment by sankalp-r** [comment]
@dannykopping I would like to work on this issue.
Can you guide me where should I start?

**Comment by dannykopping** [comment]
@sankalp-r sure thing, thanks for helping out :+1:

All of promtail's stages are defined here:
https://github.com/grafana/loki/tree/main/clients/pkg/logentry/stages

You can try copying one of the simpler stages like `labelallow` and have it accept a set of static labels.

**Comment by sankalp-r** [comment]
@dannykopping 
So by looking at the code of different stages, I have the  idea to create a new stage called as `lablestatic` and provide the configuration as following:

```
- match:
    selector: '{container="brick-drupal"}'
    stages:
    - regex:
        expression: '^(?P<my_extracted_val>NOTICE: PHP message)'
    - labels:
        extracted_val: "my_extracted_val"
   - lablestatic:
        custom_val: "php-fpm"                  
```
Let me know your thoughts on this?
