### ISSUE TITLE
lambda-promtail docs wrong? 

### ISSUE THREAD

**Issue by nikolaurban** [grafana/loki#4385]
Following the blogpost: 
https://grafana.com/blog/2020/09/16/how-were-making-it-easier-to-use-the-loki-logging-system-with-aws-lambda-and-other-short-lived-services/ 
and the documentation page: 
https://grafana.com/docs/loki/latest/clients/lambda-promtail/
I am getting the below error in the promtail logs:
```
Unable to parse config: /etc/promtail/promtail.yaml: yaml: unmarshal errors: 
line 22: field relabel_configs not found in type scrapeconfig.PushTargetConfig
```
my promtail config contains the suggested config from the docs/blogpost:
```
...
stringData:
  promtail.yaml: |
    server:
      log_level: info
      http_listen_port: 3101

    client:
      url: http://loki-distributor:3100/loki/api/v1/push

    positions:
      filename: /run/promtail/positions.yaml

    scrape_configs:
      - job_name: lambda-promtail
        loki_push_api:
          server:
            http_listen_port: 3500
            grpc_listen_port: 3600
          labels:
            promtail: 'lambda-promtail'
          relabel_configs:
            - source_labels: ['__aws_cloudwatch_log_group']
              target_label: 'log_group'
      - job_name: kubernetes-pods-app-kubernetes-io-name
        pipeline_stages: ....
```
if I outdent the `relabel_configs` block out of `loki_push_api` the above error is gone, but instead I am getting:
```
level=info ts=2021-09-27T13:29:42.743016055Z caller=pushtarget.go:80 msg="starting push server" job=lambda-promtail panic: descriptor Desc{fqName: "promtail_lambda-promtail_tcp_connections", help: "Current number of accepted TCP connections.", constLabels: {}, variableLabels: [protocol]} is invalid: "promtail_lambda-promtail_tcp_connections" is not a valid metric name
``` 
What could be causing this? And can the docs for lambda-promtail be updated if they are wrong?
