### ISSUE TITLE
Removing field from json in Promtail before submitting to Loki

### ISSUE THREAD

**Issue by hterik** [grafana/loki#4402]
Given a JSON log containing timestamp, i am recording it's timestamp using the **timestamp** stage, eg:

Input log line (from Grafana): 

`{"duration":"109.51947ms","logger":"migrator","lvl":"info","msg":"migrations completed","performed":330,"skipped":0,"t":"2021-09-30T13:01:14.136635479Z"}`

promtail-config:
```yaml
    pipeline_stages:
    - json:        
        expressions:          
          timestamp: t
    - timestamp:
        source: timestamp   
        format: RFC3339Nano
```

After this i want to remove the **t**-field, and only the t-field, nothing else. Since timestamp is already recorded, to avoid duplication inside Loki. This will reduce clutter in the UI when browsing logs and should also save some storage and bandwidth.

**Describe the solution you'd like**
Roughly something like:

```yaml
    pipeline_stages:
    - json:        
        expressions:          
          timestamp: t
          filtered_log: drop("t")        # <<< New imaginary function
    - timestamp:
        source: timestamp   
        format: RFC3339Nano
    - output:
       source: filtered_log             # <<< Use the log line no longer containing the t-field
```

**Describe alternatives you've considered**
This has previously been discussed in https://github.com/grafana/loki/issues/1011 which got closed after implementing LogQL filters to show only message _during query-time in the UI._ As described above i think dropping redundant fields before ingesting them would be more useful

JMESPath has an open request for addition of a delete-function: https://github.com/jmespath/jmespath.py/issues/121  

I guess one could also filter it out using regex in a **replace**-stage but for complicated fields such as datetimes this quickly becomes messy and you also risk missing quoting-differences or replacing sub-content inside the msg-field.

**Comment by ruslantagirov** [comment]
This feature would be great, agree.

**Comment by GadskyPapa** [comment]
I agree, the feature is very useful. Sometimes i need to delete half of json fields because they are useless

**Comment by hterik** [comment]
Please unstale.

**Comment by ngotchac** [comment]
So I found a way to do that with templates:
```yaml
    pipeline_stages:
      - json:
          expressions:
            level:
            ts:
      - labels:
          level:
      - template:
          source: message
          template: '{{ omit (mustFromJson .Entry) "ts" "level" | mustToJson }}'
      - output:
          source: message
```
This effectively creates a new `message` extraction, which is a JSON representation of the entry without the `ts` and `level` keys.

**Comment by alaricljs** [comment]
@ngotchac I'd love to get this working, but have been unable to get better than '[inspect: template stage]: none' and completely unmodified output from the above.  I've tried with 2.4.2 and 2.6.1 just in case something changed since you wrote.

Any pointers to other examples or documentation on what you're using in the template?  I have found nothing on omit, or must[To|From]Json.

**Comment by ngotchac** [comment]
> @ngotchac I'd love to get this working, but have been unable to get better than '[inspect: template stage]: none' and completely unmodified output from the above. I've tried with 2.4.2 and 2.6.1 just in case something changed since you wrote.
> 
> Any pointers to other examples or documentation on what you're using in the template? I have found nothing on omit, or must[To|From]Json.
> 
> [Edit] As usual moments after I break down and post, I make some reasonable progress. Had to change `.Entry` to `.Value`. That aside, any thoughts on injecting new k:v pairs into the produced json?

So the template methods are available since Loki 2.3 apparently, cf. https://grafana.com/docs/loki/latest/clients/promtail/stages/template/#supported-functions ; which links to https://masterminds.github.io/sprig/ where you'll find those methods.
Regarding the Entry vs. Value, from the docs:
- If source is available it can be referred as .Value in template
- A special key named Entry can be used to reference the current line.
So I guess it depends on the usage. 

I'm not sure I get your question about injecting new k:v pairs. This snippet is to remove some k:v pairs

**Comment by alaricljs** [comment]
> I'm not sure I get your question about injecting new k:v pairs. This snippet is to remove some k:v pairs

It's the flip side of the same coin and something I need to do in order to fix disparities in the log output I'm stuck dealing with.  It's mixed format where some very pertinent data is outside the JSON and I'd rather inject it than make labels from it.  Thought perhaps you might have experience there to share.  I'll dig through the docs that you linked (appreciated!) and see what I can find.

With a moment to spare I might even get the less useful docs [here](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#pipeline_stages) updated to reflect the same as what you shared.

**Comment by ngotchac** [comment]
> > I'm not sure I get your question about injecting new k:v pairs. This snippet is to remove some k:v pairs
> 
> It's the flip side of the same coin and something I need to do in order to fix disparities in the log output I'm stuck dealing with. It's mixed format where some very pertinent data is outside the JSON and I'd rather inject it than make labels from it. Thought perhaps you might have experience there to share. I'll dig through the docs that you linked (appreciated!) and see what I can find.
> 
> With a moment to spare I might even get the less useful docs [here](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#pipeline_stages) updated to reflect the same as what you shared.

I see! So I guess you can make it work with a mix of [`pick`](https://masterminds.github.io/sprig/dicts.html#pick) [`merge`](https://masterminds.github.io/sprig/dicts.html#merge-mustmerge) and [`set`](https://masterminds.github.io/sprig/dicts.html#set)?

**Comment by alaricljs** [comment]
> I see! So I guess you can make it work with a mix of [pick](https://masterminds.github.io/sprig/dicts.html#pick) [merge](https://masterminds.github.io/sprig/dicts.html#merge-mustmerge) and [set](https://masterminds.github.io/sprig/dicts.html#set)?

Yes indeed, thank you!  I just used set successfully and can get back to making things work.

For anyone that wants the shortcut version:
`json_str` is the section of my log that is pure JSON accessed via `.Value`
`$foo` is a throwaway variable as the template sets json_str to the resulting value of the template output
`type` gets removed from the original JSON
`direction` is a label from the original log string accessed via `.direction`
```
          - template:
              source: json_str
              template: '{{ $foo := omit (mustFromJson .Value) "type" }}{{ $foo := set $foo "direction" .direction }}{{ $foo | mustToJson }}'
          - labeldrop:
            - direction

```
