### ISSUE TITLE
how can I use "extraScrapeConfigs"  loki-stack-values-v2.4.1?

### ISSUE THREAD

**Issue by yusufkaratoprak** [grafana/loki#4408]
hi I am using loki-stack for log shipping ..

my loki yaml :

```
loki:
  enabled: true
  config:

promtail:
  enabled: true
  extraScrapeConfigs:
  - job_name: kubernetes-pods-name
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: kube-system

  - job_name: kubernetes-pods-direct-controllers
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: kube-system

  - job_name: kubernetes-pods-indirect-controller
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: kube-system

  - job_name: kubernetes-pods-static
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: kube-system


fluent-bit:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false
```

Run:

```
helm upgrade loki grafana/loki-stack --version "2.4.1" \
  --namespace=monitoring \
  --create-namespace \
  -f "loki-stack-values-v2.4.1.yaml" 
```

But I am seeing kube-system logs. What did I miss?
