### ISSUE TITLE
How to solve issue about Promtail extraScrapeConfigs not being picked up?

### ISSUE THREAD

**Issue by yusufkaratoprak** [grafana/loki#4418]
**Describe the bug**
It seems that dropping a namespace **kube-system** and saving a gateway **ambassador** by using the configuration below does not work:
**To Reproduce**
1.Writing configuration 👍  loki-stack-values-v2.4.1.yaml

```
loki:
  enabled: true
  config:

promtail:
  enabled: true
  extraScrapeConfigs:
  - job_name: kubernetes-pods-name
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: .+
      - action: keep
        regex: ambassador
        source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_namespace
  - job_name: kubernetes-pods-app
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: .+
      - action: keep
        regex: ambassador
        source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_namespace
 
  - job_name: kubernetes-pods-direct-controllers
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: .+
      - action: keep
        regex: ambassador
        source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_namespace

  - job_name: kubernetes-pods-indirect-controller
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: .+
      - action: keep
        regex: ambassador
        source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_namespace

  - job_name: kubernetes-pods-static
    pipeline_stages:
      - docker: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: drop
        regex: .+
      - action: keep
        regex: ambassador
        source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_namespace


fluent-bit:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false
```
2. Started Promtail (SHA or version) to tail '...' 👍 
```
helm upgrade loki grafana/loki-stack --version "2.4.1" \
  --namespace=monitoring \
  --create-namespace \
  -f "loki-stack-values-v2.4.1.yaml" 
```

3. Query: `{namespace="ambassador"}`

**Expected behavior**
I am waiting some logs on screen.
**Environment:**
 - Infrastructure: [ Kubernetes v1.22.2 (client) ,  kubernetes v1.21.3 (server), Digitalocean ]
 - Deployment tool: [helm]

**Screenshots, Promtail config, or terminal output**
Actually, I am using only the above configuration. 

when I check logs and description : 

Describe : 
```
kubectl describe pod loki-promtail-mjn9j -n monitoring > test2.yaml
```
```
  Type     Reason     Age                     From     Message
  ----     ------     ----                    ----     -------
  Warning  Unhealthy  4m43s (x5040 over 14h)  kubelet  Readiness probe failed: HTTP probe failed with statuscode: 500
```
Logs:

```
kubectl logs loki-promtail-mjn9j -n monitoring > test1.yaml
```

output:

```
I attached it as attacment
```
