### ISSUE TITLE
Ruler: write relabel rules are not applied correctly

### ISSUE THREAD

**Issue by dannykopping** [grafana/loki#4428]
**Describe the bug**
When no tenant override is configured for `ruler_remote_write_relabel_configs`, the zero value overwrites any relabel configs configured in the main config.

**To Reproduce**
1. Enable remote write:

```yaml
   ...
    ruler:
        remote_write:
            client:
               ...
                write_relabel_configs:
                  - action: drop
                    regex: ALERT.*
                    source_labels:
                      - __name__
```
2. Run the ruler

**Expected behavior**
The `write_relabel_configs` define in the main config should be present, since no tenant override is configured.

Instead, it is overwritten with `nil` because `mergo.Merge` is called with `mergo.WithOverrideEmptySlice`.
We want to be able to clear all configured relabel configs if the `ruler_remote_write_relabel_configs` override is an empty list, but do nothing if no override is set.
