### ISSUE TITLE
Use Consul as lifecycler ring store with Helm chart

### ISSUE THREAD

**Issue by sboschman** [grafana/loki#444]
The lifecycler ring store can be changed from the default `inmemory` one using chart values. Different stores have their own config, f.e. Consul. See the ksonnet config for details, https://github.com/grafana/loki/blob/master/production/ksonnet/loki/config.libsonnet#L45

Unfortunately it is not possible to add the Consul config to the loki config with the Helm chart. See https://github.com/grafana/loki/blob/master/production/helm/templates/loki/_helpers.tpl#L56:
```yaml
ingester:
  lifecycler:
    ring:
      store: {{ .Values.loki.config.ingester.lifecycler.ring.store }}
      replication_factor: {{ .Values.loki.config.ingester.lifecycler.ring.replication_factor }}
```

It might be easiest to just include all the ring values into the config, instead of trying to hardcode all the possible options. 
https://github.com/grafana/loki/blob/master/production/helm/templates/loki/_helpers.tpl#L56:
```
ingester:
  lifecycler:
    ring:
{{ toYaml .Values.loki.config.ingester.lifecycler.ring | indent 6 }}
```

Any thoughts?
