### ISSUE TITLE
[Docs]: Extend runtime config docs to easily find all available options

### ISSUE THREAD

**Issue by kavirajk** [grafana/loki#4451]
**Is your feature request related to a problem? Please describe.**
Currently, the runtime config section on docs just shows very tiny example and currently no easy to way to find all the fields of runtime-config in the docs.
https://grafana.com/docs/loki/latest/configuration/#runtime-configuration-file

**Describe the solution you'd like**
And section about the complete runtime config like every other config sections.

**Describe alternatives you've considered**
NA

**Comment by arch-xtof** [comment]
Hello! would be great if there were more detailed examples in the runtime config section.

**Comment by stringang** [comment]
```yaml
overrides:
  fake:   <---------------------------- single tenant limit config
    ingestion_rate_mb: 10
    max_streams_per_user: 100000
    max_chunks_per_query: 100000
configs:

multi_kv_config:
    mirror-enabled: false
    primary: consul
```

Referencing the source code:
https://github.com/grafana/loki/blob/9f809eda70babaf583bdf6bf335a28038f286618/pkg/loki/runtime_config.go#L17-L26
