### ISSUE TITLE
loki-logstash-output

### ISSUE THREAD

**Issue by adriannowaq** [grafana/loki#4463]
**Describe the bug**
Logstash is not sending logs to Grafana Loki, I have 3 outputs:  file, elastic search, and to loki. Only loki output doesn't work
for me.

Created Docker image like this:
```
FROM logstash:7.14.1

RUN bin/logstash-plugin install logstash-output-loki

CMD ["/usr/local/bin/docker-entrypoint"]

```
Tried docker image with logstash-output-loki plugin installed but it doesn't work either.

**To Reproduce**
1. **docker-compose:**
```
version: '2'
services:
##
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks: 
      - kafka
    ports:
      - "2181:2181"
 ##     
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    networks: 
      - kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://192.168.4.128:9094,SSL_INSIDE://localhost:9095,SSL_OUTSIDE://192.168.4.128:9096
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094,SSL_INSIDE://:9095,SSL_OUTSIDE://:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,SSL_INSIDE:SSL,SSL_OUTSIDE:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
##
  logstash:
    container_name: logstash
    image: logstashwithloki
    build:
      context: ./logstash-grafana
      dockerfile: "Dockerfile"
    networks: 
      - kafka
    volumes:
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
##
  elasticsearch:
    image: elasticsearch:7.14.1
    container_name: elasticsearch
    hostname: elasticsearch
    networks: 
      - kafka
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
##
  loki:
    image: grafana/loki
    container_name: loki
    networks: 
      - kafka
    ports:
      - 3100:3100
##
networks:
  kafka:
    driver: bridge
```

2. logstash.yml

`http.host: "0.0.0.0"`

3. pipelines.yml

```
- pipeline.id: main
  path.config: "/usr/share/logstash/pipeline"
```

4. logstash.conf

```

input {
    kafka {
      bootstrap_servers => "kafka:9094"
      topics => ["test-dotnetcore"]
    }
}

filter { json { source => "message" remove_field => [ "message" ] } }


output {

  loki {
    url => "http://loki:3100/loki/api/v1/push"
  }

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs"
    #user => "elastic"
    #password => "changeme"
  }

  file {
    path => "./logs/%{+YYYY-MM-dd}.log"
  }

}
```

**Expected behavior**
Logs should appear in Grafana

Loki configuration:
**local-config.yaml**:
```
server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
```

**Elastic search configuration in grafana:**
![image](https://user-images.githubusercontent.com/57181007/137085640-02898b3e-8598-4de1-92a6-b74672c6b49b.png)
**Loki configuration in grafana:**
![image](https://user-images.githubusercontent.com/57181007/137085730-2ccdf746-5755-4917-8cc6-b3d87b5f59d1.png)
**Logs from elastic search in grafana:**
![image](https://user-images.githubusercontent.com/57181007/137085794-e1d2c902-f4c8-4d01-ba17-ac56ec4e67c7.png)
**Logs in file:**
![image](https://user-images.githubusercontent.com/57181007/137085848-43dfa578-20af-495e-b3c3-e886b57e7b78.png)
**Logs from Loki in grafana - not found any:**
![image](https://user-images.githubusercontent.com/57181007/137085889-e99ce439-9fc3-4bf4-9a06-eb54976f2d5a.png)

loki logs:
```
ts=2021-10-13T07:00:07.5908919Z caller=log.go:168 level=debug msg=Get key=collectors/ring modify_index=5 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:07.5909197Z caller=log.go:168 level=debug msg=CAS key=collectors/ring modify_index=5 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:07.5909731Z caller=log.go:168 level=debug msg=Get key=collectors/ring modify_index=6 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:07.5910037Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=6
ts=2021-10-13T07:00:09.5867245Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:09.5867731Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=6
ts=2021-10-13T07:00:10.587129Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:10.5871767Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=6
ts=2021-10-13T07:00:11.5874804Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:11.5875365Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=6
ts=2021-10-13T07:00:12.5878738Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:12.5879261Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=6
ts=2021-10-13T07:00:12.5901265Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=0
ts=2021-10-13T07:00:12.5901709Z caller=log.go:168 level=debug msg=Get key=collectors/ring modify_index=6 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:12.5901974Z caller=log.go:168 level=debug msg=CAS key=collectors/ring modify_index=6 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:12.5902599Z caller=log.go:168 level=debug msg=Get key=collectors/ring modify_index=7 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:12.5902918Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=7
ts=2021-10-13T07:00:14.5884531Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:14.5885014Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=7
ts=2021-10-13T07:00:15.5888811Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:15.5889302Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=7
ts=2021-10-13T07:00:16.5892424Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:16.5892909Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=7
ts=2021-10-13T07:00:17.5900107Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=0
ts=2021-10-13T07:00:17.5900604Z caller=log.go:168 level=debug msg=Get key=collectors/ring modify_index=7 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:17.5900896Z caller=log.go:168 level=debug msg=CAS key=collectors/ring modify_index=7 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:17.5901084Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:17.5901166Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=7
ts=2021-10-13T07:00:17.5901231Z caller=log.go:168 level=debug msg=Get key=collectors/ring modify_index=8 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:17.5901347Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=8
ts=2021-10-13T07:00:18.5907345Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:18.5907846Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=8
ts=2021-10-13T07:00:19.5908806Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:19.5909286Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=8
ts=2021-10-13T07:00:20.5914108Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:20.5915094Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=8
ts=2021-10-13T07:00:21.5917044Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:21.5917571Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=8
ts=2021-10-13T07:00:22.5907138Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=0
ts=2021-10-13T07:00:22.590766Z caller=log.go:168 level=debug msg=Get key=collectors/ring modify_index=8 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:22.5908178Z caller=log.go:168 level=debug msg=CAS key=collectors/ring modify_index=8 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:22.5908507Z caller=log.go:168 level=debug msg=Get key=collectors/ring modify_index=9 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:22.5908855Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=9
ts=2021-10-13T07:00:23.5925871Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:23.5926356Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=9
ts=2021-10-13T07:00:24.5929117Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:24.5929604Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=9
ts=2021-10-13T07:00:25.5940184Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:25.5940869Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=9
ts=2021-10-13T07:00:26.5944127Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:26.5944603Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=9
ts=2021-10-13T07:00:27.5909536Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=0
ts=2021-10-13T07:00:27.5910025Z caller=log.go:168 level=debug msg=Get key=collectors/ring modify_index=9 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:27.5910278Z caller=log.go:168 level=debug msg=CAS key=collectors/ring modify_index=9 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:27.5910681Z caller=log.go:168 level=debug msg=Get key=collectors/ring modify_index=10 value="\"\\xad\\x05\\xf4\\xac\\x02\\n\\xaa\\x05\\n\\f1ea85166ac68\\x12\\x99\\x05\\n\\x0e127.0.0.1:909\""
ts=2021-10-13T07:00:27.5911143Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=10
ts=2021-10-13T07:00:28.5958153Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:28.5958631Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=10
ts=2021-10-13T07:00:29.5963394Z caller=log.go:168 level=debug msg="Get - deadline exceeded" key=collectors/ring
ts=2021-10-13T07:00:29.5964257Z caller=log.go:168 level=debug msg=Get key=collectors/ring wait_index=10
```
