### ISSUE TITLE
[Loki-Distributor] - Not showing all logs metrics, always show less logs for latest 10-15 minutes

### ISSUE THREAD

**Issue by pawankkamboj** [grafana/loki#4490]
**Describe the bug**
Not show all logs, alway show dip in logs for last 10-15 minutes. But if you checked logs for the same time again after an hour there is no dip but for latest 10-15 minutes it always show. Tried with 1 hour/3 hour,6 hour, 12 hour windows, it always show dip for latest 10-15 minutes. We are sending lots of logs data, around 1TB per days. Did not observe behaviour if not much log volume, but if logs volume are high(5000000) then it show dip.

**To Reproduce**
1. Started Loki : `docker.io/grafana/loki:main-c4562f1-amd64`
2. Started Promtail : 2.3
3. Query: `sum(count_over_time({app="meta"}[5m]))`

**Expected behavior**
Always show all matched logs
**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - compactor - 1 replicas, 1/2 Core, 4Gb RAM
 - distributor - 3 replicas, 1 Core, 2Gib RAM
 - gateway - 3 replicas (autoscale - 3 min, 5 max), 2 Core, 512Mb RAM
 - index-gateway - 2 replicas, 1 Core, 2Gib RAM
 - ingester - 5 replicas, 2 Core, 8Gib RAM
 - querier - 3 replicas (autoscale - 3 min, 7 max),  8 Core, 8Gib RAM
 - query-frontend - 2 replicas,  1/2 Core, 512Mb RAM
 - ruler - 3 replicas, 4 Core, 8Gb RAM
 - memcached-chunk - 3 replicas, 2 Core, 28Gb RAM
 - redis-frontend - 1 replicas, 1/2 Core, 2Gb RAM
 - redis-query - 1 replicas, 1/2 Core, 2Gb RAM

**Screenshots, Promtail config, or terminal output**
```
loki:
  config: |
    chunk_store_config:
      max_look_back_period: 672h
      chunk_cache_config:
        memcached:
          expiration: 2h
          batch_size: 100
          parallelism: 100
        memcached_client:
          consistent_hash: true
          host: {{ include "loki.memcachedChunksFullname" . }}
          service: http
          timeout: 500ms

      write_dedupe_cache_config:
        memcached:
          expiration: 2h
          batch_size: 100
          parallelism: 100
        memcached_client:
          consistent_hash: true
          host: {{ include "loki.memcachedChunksFullname" . }}
          service: http

    auth_enabled: true

    server:
      http_listen_port: 3100
      http_server_read_timeout: 300s
      http_server_idle_timeout: 300s
      http_server_write_timeout: 300s
      grpc_server_max_recv_msg_size: 41943040000
      grpc_server_max_send_msg_size: 41943040000
      grpc_server_max_concurrent_streams: 2000

    distributor:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      concurrent_flushes: 24
      chunk_idle_period: 5m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 50s
      max_transfer_retries: 0
      chunk_target_size: 1572864
      max_chunk_age: 1h
      autoforget_unhealthy: true
      wal:
        enabled: true
        dir: /var/loki/wal
        replay_memory_ceiling: 6GB

    ingester_client:
      pool_config:
        health_check_ingesters: true
        client_cleanup_period: 5s
      grpc_client_config:
        max_send_msg_size: 16777216000
        max_recv_msg_size: 10485760000

    limits_config:
      retention_period: 0
      enforce_metric_name: false
      reject_old_samples: false
      max_cache_freshness_per_query: 10m
      max_entries_limit_per_query: 5000
      ingestion_burst_size_mb: 148
      ingestion_rate_mb: 128
      max_streams_per_user: 0
      ingestion_rate_strategy: 'global'
      max_query_parallelism: 256
      max_query_series: 1000
      max_streams_matchers_per_query: 5000
      cardinality_limit: 500000
      unordered_writes: true
      per_stream_rate_limit: 15m
      per_stream_rate_limit_burst: 30m
    schema_config:
      configs:
        - from: 2020-09-07
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      boltdb_shipper:
        shared_store: s3
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 24h
        query_ready_num_days: 10
        index_gateway_client:
          server_address: dns:///{{ include "loki.indexGatewayFullname" . }}:9095
      aws:
         s3: s3://xxxxxxx
      index_queries_cache_config:
        redis:
          endpoint: loki-redis-query:6379
          timeout: 1s
          expiration: 12h
          db: 0
          pool_size: 0
          idle_timeout: 0s
          max_connection_age: 0s

    querier:
      query_ingesters_within: 2h
      query_timeout: 5m
      max_concurrent: 8
      engine:
        timeout: 10m
        max_look_back_period: 672h

    query_range:
      align_queries_with_step: true
      max_retries: 5
      split_queries_by_interval: 15m
      cache_results: true
      parallelise_shardable_queries: true
      results_cache:
        cache:
          redis:
            endpoint: loki-redis-frontend:6379
            timeout: 1s
            expiration: 12h
            db: 0
            pool_size: 0
            idle_timeout: 0s
            max_connection_age: 0s

    frontend_worker:
      parallelism: 8
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
      grpc_client_config:
        max_send_msg_size: 16777216000
        max_recv_msg_size: 10485760000

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      max_outstanding_per_tenant: 1000

    compactor:
      shared_store: s3
      retention_enabled: false
      retention_delete_delay: 2h
      working_directory: /var/loki/retention

    ruler:
      storage:
        type: s3
        s3:
           s3: s3://xxxxxxxxx
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      alertmanager_url: http://xxxxxx
      external_url: https://xxxxxx
      evaluation_interval: 5m
      poll_interval: 2m
      enable_alertmanager_v2: true
      enable_api: true
      enable_sharding: true
```

**Query
```sum(count_over_time({app="meta"}[5m]))```

**Frontend query logs
```
ts=2021-10-18T07:39:43.377662999Z caller=spanlogger.go:87 org_id=meta_cataina Ingester.TotalReached=720 Ingester.TotalChunksMatched=4795 Ingester.TotalBatches=7158 Ingester.TotalLinesSent=3580100 Ingester.HeadChunkBytes="206 MB" Ingester.HeadChunkLines=165533 Ingester.DecompressedBytes="7.9 GB" Ingester.DecompressedLines=3670112 Ingester.CompressedBytes="1.2 GB" Ingester.TotalDuplicates=85228 Store.TotalChunksRef=90534 Store.TotalChunksDownloaded=90534 Store.ChunksDownloadTime=6m32.716011003s Store.HeadChunkBytes="0 B" Store.HeadChunkLines=0 Store.DecompressedBytes="339 GB" Store.DecompressedLines=117984459 Store.CompressedBytes="62 GB" Store.TotalDuplicates=50019
ts=2021-10-18T07:39:43.37773882Z caller=spanlogger.go:87 org_id=meta_cataina Summary.BytesProcessedPerSecond="11 GB" Summary.LinesProcessedPerSecond=3900043 Summary.TotalBytesProcessed="348 GB" Summary.TotalLinesProcessed=121820104 Summary.ExecTime=31.235578591s
level=info ts=2021-10-18T07:39:43.379526035Z caller=handler.go:173 org_id=meta_cataina msg="slow query detected" method=GET host=loki-distributed-query-frontend.logging.svc.cluster.local:3100 path=/loki/api/v1/query_range time_taken=31.236709557s param_step=10 param_direction=BACKWARD param_limit=1318 param_query="sum(count_over_time({app=\"meta\"}[5m]))" param_start=1634531951818000000 param_end=1634542751818000000
level=info ts=2021-10-18T07:39:43.382893882Z caller=metrics.go:92 org_id=meta_cataina latency=slow query="sum(count_over_time({app=\"meta\"}[5m]))" query_type=metric range_type=range length=3h0m0s step=10s duration=31.235578591s status=200 limit=1318 returned_lines=0 throughput=11GB total_bytes=348GB
```

![image](https://user-images.githubusercontent.com/20416881/137690381-6b5219e4-f86d-4c89-8d29-6b1ca0d84119.png)
