### ISSUE TITLE
Log deletion doesn't work as expected

### ISSUE THREAD

**Issue by wzjjack** [grafana/loki#4492]
**Describe the bug**
Trying to delete the log by loki/api/admin/delete, but looks like the log still there.

**To Reproduce**
1. Started Loki 2.3.0
2. Push the log to the loki

```
Test.js

const rp = require('request-promise').defaults({ timeout: 30000 });
(async () => {
    const stream = {
        stream: {
            id: "test"
        },
        values: []
    }
    var values = []
    for (var i = 0; i < 10; i++) {
        values.push([`${new Date() * 1000000}`, `log ${i + 1}`])
    }
    stream.values = values;
    const options = {
        uri: `http://localhost:3100/loki/api/v1/push`,
        family: 4,
        method: 'POST',
        json: { streams: [stream] }
    }
    try {
        await rp(options)
    } catch (e) {
        e && console.log("send test streams to loki error", e.error, e.statusCode)
    }
    console.log("send test streams to loki done");
})()



```
3. Query the logs and result
![image](https://user-images.githubusercontent.com/52395237/137741077-309c74c1-d97b-4a43-b48e-5663af4cce26.png)

4. call log deletion API and wait the status update to "processed"
curl -G -s  "http://localhost:3100/loki/api/admin/delete"
[{"request_id":"5e83a92d","start_time":0,"end_time":1634560904.157,"selectors":["{id=\"test\"}"],"status":"processed","created_at":1634560904.157}]

5. query the logs and looks like the log still there
![image](https://user-images.githubusercontent.com/52395237/137741435-0c700075-03de-4e0d-8763-964b23adba55.png)

**Expected behavior**
when the delete request processed, the log streams between start_time to end_time should be deleted and shouldn't return when calling query API

Did I miss anything in the config file or misunderstand the delete API?

**Config:**

```
auth_enabled: false

querier:
  engine:
    max_look_back_period: 25h

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  wal:
    enabled: true
    dir: /tmp/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor
  shared_store: filesystem
  compaction_interval: 3m
  retention_enabled: true
  retention_delete_delay: 3m
  retention_delete_worker_count: 500
  delete_request_cancel_period: 3m

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
```
