### ISSUE TITLE
Loki s3 write failing with istio sidecar injection

### ISSUE THREAD

**Issue by abin-tiger** [grafana/loki#4501]
**Describe the bug**
We enabled istio sidecar injection on loki's namespace recently. Once we enabled it loki has stopped writing logs chunks to s3. We're getting the following error message "failed to flush user" err="RequestCanceled: request context canceled\ncaused by: context deadline exceeded" constantly. When istio is disabled loki works fine.

Loki is configured to use boltdb-shipper(to s3) and s3 as chunkstore.

Sample logs. Full logs are attached and mentioned at the bottom:
```
level=error ts=2021-10-19T12:33:05.811587195Z caller=flush.go:220 org_id=fake msg="failed to flush user" err="RequestCanceled: request context canceled\ncaused by: context deadline exceeded"
level=error ts=2021-10-19T12:33:05.811587974Z caller=flush.go:220 org_id=fake msg="failed to flush user" err="RequestCanceled: request context canceled\ncaused by: context deadline exceeded"
level=error ts=2021-10-19T12:33:05.811602715Z caller=flush.go:220 org_id=fake msg="failed to flush user" err="RequestCanceled: request context canceled\ncaused by: context deadline exceeded"
level=error ts=2021-10-19T12:33:05.81160655Z caller=flush.go:220 org_id=fake msg="failed to flush user" err="RequestCanceled: request context canceled\ncaused by: context deadline exceeded"
level=error ts=2021-10-19T12:33:05.811632823Z caller=flush.go:220 org_id=fake msg="failed to flush user" err="RequestCanceled: request context canceled\ncaused by: context deadline exceeded"
level=debug ts=2021-10-19T12:33:05.811642925Z caller=flush.go:216 msg="flushing stream" userid=fake fp=fee406c109add5a8 immediate=false
level=debug ts=2021-10-19T12:33:05.811661708Z caller=flush.go:216 msg="flushing stream" userid=fake fp=8335d9316ba9051f immediate=false
level=debug ts=2021-10-19T12:33:05.811632873Z caller=flush.go:216 msg="flushing stream" userid=fake fp=e052fb097c33ba0b immediate=false
level=debug ts=2021-10-19T12:33:05.811639302Z caller=flush.go:216 msg="flushing stream" userid=fake fp=28d6331ce191fca2 immediate=false
level=error ts=2021-10-19T12:33:05.811856876Z caller=flush.go:220 org_id=fake msg="failed to flush user" err="RequestCanceled: request context canceled\ncaused by: context deadline exceeded"
level=debug ts=2021-10-19T12:33:05.811875922Z caller=flush.go:216 msg="flushing stream" userid=fake fp=179262f7fa9951a6 immediate=false
level=error ts=2021-10-19T12:33:05.811974275Z caller=flush.go:220 org_id=fake msg="failed to flush user" err="RequestCanceled: request context canceled\ncaused by: context deadline exceeded"
level=error ts=2021-10-19T12:33:05.824867727Z caller=flush.go:220 org_id=fake msg="failed to flush user" err="RequestCanceled: request context canceled\ncaused by: context deadline exceeded"
level=debug ts=2021-10-19T12:33:05.824923302Z caller=flush.go:216 msg="flushing stream" userid=fake fp=58bba535911d59fd immediate=false
```

Detailed logs are attached as file.

I don't think this is an istio issue as I deployed an amazon/awscli pod in the same namespace and it works fine.

**To Reproduce**
1. Started Loki (SHA or version): 2.2.1
2. Started Promtail (SHA or version) to tail '...': 2.2.1
3. Query: `{} term`: Nothing specific. But I noticed grafana isn't able to connect to loki and get the labels.

**Expected behavior**
Loki should be able to write the logs chunks and index to S3. 

**Environment:**
 - Infrastructure: EKS Kubernetes 1.19
 - Deployment tool: helm
 - Loki Helm chart: https://github.com/grafana/helm-charts/releases/tag/loki-2.5.2
 - Promtail helm chart: https://github.com/grafana/helm-charts/releases/tag/promtail-3.6.0

**Screenshots, Promtail config, or terminal output**

Loki logs at debug level is attached here: [attachments.zip](https://github.com/grafana/loki/files/7379636/attachments.zip)

Loki configuration. Full values.yaml file is in the zip attachment.
```yaml
schema_config:
    configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index
        period: 24h
  server:
    http_listen_port: 3100
  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
      shared_store: s3
    aws:
      s3: s3://<aws region>
      bucketnames: <bucket name>
  chunk_store_config:
    max_look_back_period: 0s
  table_manager:
    retention_deletes_enabled: true
    retention_period: 720h
  compactor:
    working_directory: /data/loki/boltdb-shipper-compactor
    shared_store: s3
    compaction_interval: 5m
```

Promtail is using the default helm values.yaml configs.
