### ISSUE TITLE
"error deleting chunk" and "failed to delete key" in loki log

### ISSUE THREAD

**Issue by michaelkebe** [grafana/loki#4504]
**Describe the bug**
The log of loki is flooded with these kinds of warnings and errors:
```
level=warn ts=2021-10-20T11:05:11.498320205Z caller=marker.go:300 msg="failed to delete key" key="\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0004" value=fake/db0094787c102fb2:17b37813c7a:17b37b82b0b:b964a4f1 err="remove /var/lib/loki/chunks/ZmFrZS9kYjAwOTQ3ODdjMTAyZmIyOjE3YjM3ODEzYzdhOjE3YjM3YjgyYjBiOmI5NjRhNGYx: no such file or directory"
level=error ts=2021-10-20T11:05:11.498258121Z caller=retention.go:219 msg="error deleting chunk" chunkID=fake/db0094787c102fb2:17b37813c7a:17b37b82b0b:b964a4f1 err="remove /var/lib/loki/chunks/ZmFrZS9kYjAwOTQ3ODdjMTAyZmIyOjE3YjM3ODEzYzdhOjE3YjM3YjgyYjBiOmI5NjRhNGYx: no such file or directory"
```
These are repeated every minute for the same file.

**To Reproduce**
We are currently using Loki version v2.3.0
Upgraded from v2.2.1 to v2.3.0 and enabled retentions deletion after a few weeks.

**Expected behavior**
No errors and warnings the logs.

**Environment:**
 - Infrastructure: Ubuntu 20.04 on a VM in VMware
 - Deployment tool: self written ansible (based on https://github.com/Amygos/ansible-loki)

**Screenshots, Promtail config, or terminal output**
loki configuration:
```
auth_enabled: False

server:
  grpc_listen_port: 9096
  http_listen_port: 3100

ingester:
  chunk_idle_period: 1h
  chunk_retain_period: 30s
  chunk_target_size: 1048576
  lifecycler:
    address: 127.0.0.1
    final_sleep: 0s
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_chunk_age: 1h
  max_transfer_retries: 0
  wal:
    dir: /var/lib/loki/wal
    enabled: true

schema_config:
  configs:
  - from: 2020-10-24
    index:
      period: 24h
      prefix: index_
    object_store: filesystem
    schema: v11
    store: boltdb-shipper

storage_config:
  boltdb_shipper:
    active_index_directory: /var/lib/loki/boltdb-shipper-active
    cache_location: /var/lib/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /var/lib/loki/chunks

compactor:
  retention_enabled: true
  shared_store: filesystem
  working_directory: /var/lib/loki/boltdb-shipper-compactor

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 336h

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h

ruler:
  alertmanager_url: http://localhost:9093
  enable_api: true
  ring:
    kvstore:
      store: inmemory
  rule_path: /var/lib/loki/rules-temp
  storage:
    local:
      directory: /var/lib/loki/rules
    type: local
```
