### ISSUE TITLE
The query time range exceeds the limit

### ISSUE THREAD

**Issue by MarkSpencerTan** [grafana/loki#4509]
**Describe the bug**
Hello, we've noticed when we try to do a query in Loki in Grafana and our time range is longer than 30days, it throws an error mentioning: "the query time range exceeds the limit".

Is this expected? Could it be increased if we need to query for a data range longer than 30 days? We would really appreciate any tips. Thank you!

**To Reproduce**
1. Create a Loki Query in Grafana
2. Set the range for the query to 1month

**Expected behavior**
We expect to see the data for the query for the past month

**Environment:**
 - Grafana using Loki as a datasource.
 - Deployed in AWS in ECS Fargate

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/10620534/138188404-8c3775a8-731e-4bb7-a913-65e7df4bd7e0.png)

**Comment by daghaian** [comment]
@kavirajk If you have any insight, we'd appreciate it

**Comment by Ollie42** [comment]
With Loki 2.4.0 some default Settings in Loki Config have changed.
[https://grafana.com/docs/loki/latest/upgrading/]
The default for Parameter max_query_length was changed from 0h (no Limit) to 721h

**Comment by edwardzjl** [comment]
> With Loki 2.4.0 some default Settings in Loki Config have changed. [https://grafana.com/docs/loki/latest/upgrading/] The default for Parameter max_query_length was changed from 0h (no Limit) to 721h

Do you know how to configure this on helm-deployed loki ?
I have tried
```bash
helm upgrade --install loki grafana/loki --set "max_query_length=0h"
```
or
```bash
helm upgrade --install loki grafana/loki --set "loki.limits_config.max_query_length=0h"
```
both not working

**Comment by Ollie42** [comment]
@edwardzjl

I am sorry, I do not have any Experience in Kubernetes.
We are running Grafana Loki in Docker, so I changed the limits_config Section
in the Loki Configfile:
```
...
limits_config:
  ingestion_rate_strategy: local # Default: global
  max_global_streams_per_user: 5000
  max_query_length: 0h # Default: 721h
  max_query_parallelism: 32 # Old Default: 14
  max_streams_per_user: 0 # Old Default: 10000
...
```
This resolved the Issue after a Container Restart.
