### ISSUE TITLE
Support using standard AWS credential discovery instead of hardcoded tokens

### ISSUE THREAD

**Issue by garo** [grafana/loki#451]
When using S3 or DynamoDB storage options Loki currently requires that static hardcoded IAM credentials (access_key:secret_access_key) are entered into the configuration.

The current way has already bugs such as https://github.com/grafana/loki/issues/310

Loki should support discovering AWS credentials with the normal aws-sdk-go credential discovery chain (see https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials) which supports ENV variables, configuration files and IAM role through the EC2 metadata service.

This would remove the need to hardcode credentials providing more security and more flexible configuration for users running Loki inside AWS EC2.

**Comment by garo** [comment]
Turns out I was incorrect on this. I will make a PR to improve the documentation.

**Comment by jralph** [comment]
@garo Was this documented? I can't seem to get environment/non-hardcoded config to work.

**Comment by garo** [comment]
Good question. I have to check myself. In the mean time here's a snippet how my loki values.yaml looks which I use for the helm. Hopefully this give you enough clues:

```
config:
  ingester:
  schema_config:
    configs:
    - from: "2019-08-10"
      store: aws
      object_store: s3
      schema: v9
      index:
        prefix: "my-prefix"
        period: 168h
  storage_config:
    aws:
      s3: s3://us-east-1/my-prefix
      dynamodbconfig:
        dynamodb: dynamodb://us-east-1
```
