### ISSUE TITLE
Compactor based retention rules not working

### ISSUE THREAD

**Issue by BitProcessor** [grafana/loki#4572]
Source: https://grafana.slack.com/archives/CEPJRLQNL/p1634558032314200

Setup:

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: loki
  namespace: prod-loki
spec:
  releaseName: loki
  chart:
    repository: https://grafana.github.io/helm-charts
    name: loki-distributed
    version: 0.38.0
  values:
    loki:
      config: |
        auth_enabled: false

        server:
          http_listen_port: 3100

        distributor:
          ring:
            kvstore:
              store: memberlist

        ingester:
          lifecycler:
            ring:
              kvstore:
                store: memberlist
              replication_factor: 1
            final_sleep: 0s
          chunk_target_size: 2097152
          max_chunk_age: 8h
          chunk_idle_period: 1h

        memberlist:
          join_members:
            - {{ include "loki.fullname" . }}-memberlist

        schema_config:
          configs:
          - from: 2020-05-15
            store: boltdb-shipper
            object_store: s3
            schema: v11
            index:
              prefix: index_
              period: 24h

        storage_config:
          boltdb_shipper:
            active_index_directory: /var/loki/index
            cache_location: /var/loki/cache
            shared_store: s3
            index_gateway_client:
              server_address: loki-loki-distributed-index-gateway.prod-loki:9095

          aws:
            bucketnames: "loki-supplystack-io"
            region: eu-west-1
            access_key_id: "<hidden>"
            secret_access_key: "<hidden>"

        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          retention_period: 24h
          retention_stream:
          - selector: '{env=~"dev|qa|staging|non-prod"}'
            priority: 1
            period: 30d
          - selector: '{env="cluster"}'
            priority: 2
            period: 7d
          - selector: '{env="cluster",namespace="ingress-nginx"}'
            priority: 3
            period: 185d
          - selector: '{env="prod"}'
            priority: 4
            period: 185d            
          - selector: '{env="prod",cluster="ncc-1031"}'
            priority: 5
            period: 30d
          - selector: '{namespace=~"prod-ums|prod-old-ums"}'
            priority: 6
            period: 365d

        compactor:
          shared_store: s3
          compaction_interval: 5m
          retention_enabled: true

        frontend:
          log_queries_longer_than: 5s
          downstream_url: http://loki-loki-distributed-querier.prod-loki.svc.cluster.local:3100
          compress_responses: true

    ingester:
      replicas: 3
      persistence:
        enabled: true
      podAnnotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3100'
        supplystack.io/env: prod
      nodeSelector:
        lifecycle: Ec2Spot-graviton
      tolerations:
      - key: spotInstanceArm
        operator: Equal
        value: tolerate
        effect: NoSchedule
    distributor:
      replicas: 3
      podAnnotations:
        supplystack.io/env: prod
      nodeSelector:
        lifecycle: Ec2Spot-graviton
      tolerations:
      - key: spotInstanceArm
        operator: Equal
        value: tolerate
        effect: NoSchedule
    querier:
      replicas: 4
      podAnnotations:
        supplystack.io/env: prod
      nodeSelector:
        lifecycle: Ec2Spot-graviton
      tolerations:
      - key: spotInstanceArm
        operator: Equal
        value: tolerate
        effect: NoSchedule
    queryFrontend:
      replicas: 4
      podAnnotations:
        supplystack.io/env: prod
      nodeSelector:
        lifecycle: Ec2Spot-graviton
      tolerations:
      - key: spotInstanceArm
        operator: Equal
        value: tolerate
        effect: NoSchedule
    indexGateway:
      enabled: true
      replicas: 3
      podAnnotations:
        supplystack.io/env: prod
      persistence:
        enabled: true
      nodeSelector:
        lifecycle: Ec2Spot-graviton
      tolerations:
      - key: spotInstanceArm
        operator: Equal
        value: tolerate
        effect: NoSchedule
    gateway:
      replicas: 3
      verboseLogging: false
      podAnnotations:
        supplystack.io/env: prod
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx-internal
          cert-manager.io/cluster-issuer: letsencrypt-prod    
        hosts:
          - host: <hidden>
            paths:
              - path: /
        tls:
          - secretName: prod-loki-gateway
            hosts:
              - <hidden>
      nodeSelector:
        lifecycle: Ec2Spot-graviton
      tolerations:
      - key: spotInstanceArm
        operator: Equal
        value: tolerate
        effect: NoSchedule 
    compactor:
      enabled: true
      # image:
      #   tag: k68-c4562f1 #override with newer build to fix retention issues
      persistence:
        enabled: true
      podAnnotations:
        supplystack.io/env: prod
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3100'

```

What I expect:
Compactor applying retention config

What actually happens:
Nothing

* The `loki_boltdb_shipper_retention_marker_count_total` metric has no data
* The `loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_count` metric has no data

Logs matching:
```
          - selector: '{env="cluster"}'
            priority: 2
            period: 7d
```
Are coming in on daily basis, so I expect them to be cleaned up after 7d. This isn't happening.
Examples, I still have logs from October 15th from `{env="cluster"}` (this is 13d ago as I write this):

![Screenshot 2021-10-28 at 08 46 20](https://user-images.githubusercontent.com/50638541/139201622-5f2506a2-bd72-444e-a0ed-133fc99a4398.png)
![Screenshot 2021-10-28 at 09 10 27](https://user-images.githubusercontent.com/50638541/139205545-c00e42ca-ff20-4ec5-b66b-f964489a9a37.png)
![Screenshot 2021-10-28 at 09 11 38](https://user-images.githubusercontent.com/50638541/139205551-21a44f78-a787-4016-9d19-472c1db3b845.png)

LOGS from the compactor: (15min) [logs.txt](https://github.com/grafana/loki/files/7432140/logs.txt)

Extra info:
Initially, as a test, I had the following setup, without the stream rules:

```
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          retention_period: 168h
```

And that worked fine.
After changing the default to 24h and adding the retention_stream rules, it stopped working.
Note that it doesn't seem to throw any errors, it just stopped working. 

What have I done already:

- Tried the same without the regexp rules (more rules): not working
- Tried the same with `h` instead of `d` : not working
- Tried a newer image tag for the compactor, didn't work (`k68-c4562f1`)
