### ISSUE TITLE
loki crashed for large queries

### ISSUE THREAD

**Issue by yongzhang** [grafana/loki#4582]
**Describe the bug**
When query a large amount of data in grafana, e.g. I select the time range to "last 6 months", I see below behavior:

1) Grafana reports 502 error

![image](https://user-images.githubusercontent.com/15604715/139386899-6667c6ed-b2b6-4caf-bd31-79fc13f89dd1.png)

2) CPU/Memory/Disk usage of Loki server increases quickly

![image](https://user-images.githubusercontent.com/15604715/139387073-29831bea-fd2e-48f0-8877-9c93fd74300c.png)

![image](https://user-images.githubusercontent.com/15604715/139387109-c5f5a3b2-862f-4b4b-b136-018d3d3377b3.png)

And soon, loki crashed, I'm running single instance with 4c16GB EC2 in AWS, s3 as storage backend.

I don't know how to improve this situation, please help, thanks.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]  bare-metal, AWS EC2 4c16GB, single
 - Deployment tool: [e.g., helm, jsonnet] Systemd
 - Loki version: v2.3.0
 - Loki config:
```
      auth_enabled: false

      server:
        http_listen_port: 80
        grpc_listen_port: 9095
        grpc_server_max_concurrent_streams: 1000
        grpc_server_max_recv_msg_size: 104857600
        grpc_server_max_send_msg_size: 104857600
        http_server_idle_timeout: 120s
        http_server_write_timeout: 1m
        log_level: ${log_level}

      ingester:
        chunk_encoding: snappy
        chunk_idle_period: 3m
        chunk_block_size: 262144
        chunk_retain_period: 1m
        max_transfer_retries: 0
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1
          interface_names:
          - ens5
          - eth0

      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        retention_period: ${log_retention_period}
        max_streams_per_user: 200000
        ingestion_burst_size_mb: 64
        ingestion_rate_mb: 32

      schema_config:
        configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h
          chunks:
            prefix: chunks_
            period: 24h

      storage_config:
        boltdb_shipper:
          active_index_directory: /data/loki/boltdb-shipper-active
          cache_location: /data/loki/boltdb-shipper-cache
          cache_ttl: 24h
          shared_store: s3
        aws:
          s3: s3://${region}/${bucket_name}
          s3forcepathstyle: true

      compactor:
        working_directory: /data/loki/compactor
        shared_store: s3
        compaction_interval: 10m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
```
