### ISSUE TITLE
[Promtail] Server config in `loki_push_api ` doesn't have `health_check_target ` field

### ISSUE THREAD

**Issue by taisho6339** [grafana/loki#4602]
**Describe the bug**

We can use same `server_config` parameters in `loki_push_api` as in `server` in root according to [configuration document](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#loki_push_api).
However, Loki uses a different server_config struct in `loki_push_api` from the one in root internally.
Therefore we can't use health_check_target in server_config in loki_push_api.

**To Reproduce**

1. Try to load the following configuration
```
  promtail.yaml: |
    server:
      log_level: info
      http_listen_port: 3101

...

    scrape_configs:
     - loki_push_api:
         server:
           http_listen_port: 80
           health_check_target: true
```

2. Fail to load it

error message
```
Unable to parse config: /etc/promtail/promtail.yaml: yaml: unmarshal errors:
  line 14: field health_check_target not found in type server.Config
```

**Expected behavior**

We can use `health_check_target` field in server_config in loki_push_api otherwise, we can know the fact we can't use it in the document.

**Environment:**
 - Infrastructure: all
 - Deployment tool: all
 - Loki version: 2.3.0

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
