### ISSUE TITLE
Loki ruler continously has "wrong chunk metadata" error

### ISSUE THREAD

**Issue by bangau1** [grafana/loki#4619]
**Describe the bug**
My loki ruler pod continously has "wrong chunk metadata" error when evaluating the alerting rules.

**To Reproduce**
1. Started Loki : v2.3.0 (docker.io/grafana/loki:2.3.0)
2. Started Promtail (SHA or version): v2.3.0 (docker.io/grafana/promtail:2.3.0)
3. Setup alerting rules and applied it
4.  After 5-10 minutes or so, the error occuring everytime it evaluates the rules. I tried to query the logQL expression used by the alert rules, directly from Grafan Explore and it works fine.

**Expected behavior**
I expect that when evaluating the alert rules, there is no continous error of "wrong chunk metadata", since it fails to send the alert to the alertmanager.

**Environment:**
 - Infrastructure: EKS (kubernetes)
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
There are many warn log in the loki ruler component pod, when evaluating the rules:

```

ts=2021-11-03T05:27:08.592335918Z caller=log.go:168 user=<redacted> level=warn group=system-infra-domain msg="Evaluating rule failed" rule="alert: Backend_Runtime_Error_Detected_at_K8S\nexpr: (sum by(app,namespace,k8s_cluster)(count_over_time({namespace=\"prod\", app=~\".*\"}\n  \|= \"runtime error\"[10m])) >= 1)\nlabels:\n  alert_key: '{{ $labels.k8s_cluster }}_{{ $labels.namespace }}_{{ $labels.app }}'\n  route: backend\n  severity: warning\nannotations:\n  description: There is runtime error detected at the service `{{ $labels.app }}`.\n    Please click the `Log` button to see in detail.\n  fullLog: https://<redacted>/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bk8s_cluster%3D%5C%22{{\n    $labels.k8s_cluster }}%5C%22,%20namespace%3D%5C%22{{ $labels.namespace }}%5C%22,%20app%3D%5C%22{{\n    $labels.app }}%5C%22,%20container%3D%5C%22app%5C%22%7D%22%7D%5D\n  locErrorLog: https://<redacted>/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bk8s_cluster%3D%5C%22{{\n    $labels.k8s_cluster }}%5C%22,%20namespace%3D%5C%22{{ $labels.namespace }}%5C%22,%20app%3D%5C%22{{\n    $labels.app }}%5C%22,%20container%3D%5C%22app%5C%22%7D%20%20%7C%3D%20%5C%22%2Fsrc%2Forg%2Fhiveos%5C%22%20%7C~%20%5C%22:%5B0-9%5D%2B%5C%22%20!~%20%5C%22(transport%7Cfilters%7Csecurity%7Cprometheus_instrumentation)%5C%22%22%7D%5D\n  log: https://<redacted>/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Bk8s_cluster%3D%5C%22{{\n    $labels.k8s_cluster }}%5C%22,%20namespace%3D%5C%22{{ $labels.namespace }}%5C%22,%20app%3D%5C%22{{\n    $labels.app }}%5C%22,%20container%3D%5C%22app%5C%22%7D%20%7C%3D%20%5C%22runtime%20error%5C%22%22%7D%5D\n  owner: <!subteam^S01UUBH3EEN>\n  title: Runtime Error Detected!\n" err="wrong chunk metadata"
--

```

Here is the loki config used by my loki-distributed installation

```yaml

  # -- Config file contents for Loki
  # @default -- See values.yaml
  config: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_server_max_recv_msg_size: 41943040
      grpc_server_max_send_msg_size: 41943040
    distributor:
      ring:
        kvstore:
          store: memberlist
    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
    schema_config:
      configs:
        - from: 2021-03-23
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: loki_dist_index_
            period: 24h
    storage_config:
      aws:
        s3: s3://${aws_access_key}:${aws_secret_key}@${aws_region}/${s3_bucket_name}
      
      boltdb_shipper:
        shared_store: s3
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h
        resync_interval: 5s
      
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
    query_range:
      align_queries_with_step: true
      max_retries: 5
      split_queries_by_interval: 15m
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h
    frontend_worker:
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
    compactor:
      shared_store: s3
    ruler:
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      alertmanager_url: ${alertmanager_internal_url}
      external_url: ${alertmanager_external_url}
      evaluation_interval: "3m"
```

Here is the screenshot of alerting rule that is failed to be evaluated by loki ruler.
![image](https://user-images.githubusercontent.com/352737/140014655-c3f5f84f-a97a-420f-a0c0-8c7fc07abf24.png)

Is there any idea what triggers this error "wrong chunk metadata"?
