### ISSUE TITLE
Who wants to help test Loki 2.4???

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#4647]
Will post a docker image soon people can use to help us test out Loki!

**Comment by atlee19** [comment]
I would be glad to!

**Comment by Abuelodelanada** [comment]
I would be glad too!

**Comment by edinardo** [comment]
I will start today for sure. Sadly, we still use binaries, so I will extract them from the images if it is not available.

**Comment by slim-bean** [comment]
The docker image we are testing is `grafana/loki:k70-3f9d067`

We made a lot of changes to configuration and you can use this ridiculous command I came up with if you want to see what the generated config diff between Loki 2.3.0 and this image will be using your current config file:

```
diff <(docker run --rm -t -v "${PWD}":/config grafana/loki:2.3.0 -config.file=/config/loki-local-config.yaml -print-config-stderr 2>&1 | sed '/Starting Loki/q') <(docker run --rm -t -v "${PWD}":/config grafana/loki:k70-3f9d067 -config.file=/config/loki-local-config.yaml -print-config-stderr 2>&1 | sed '/Starting Loki/q')
```

That command assumes you are in a directory that has your current config file which is named `loki-local-config.yaml`

If you have questions about the diff put them here.  

Also check out the [upgrade guide](https://grafana.com/docs/loki/next/upgrading/) It still needs a little cleaning up but it talks about some of the changes made.

**Our goal is that existing configs should just work** with the exception that we changed some defaults around some limits which were either not set or set differently, so you may need to increase limits.

I'm working on trying to improve the documentation of all this stuff still so let me know if you can think of docs that will help others!

Sorry @edinardo don't have any binaries yet... nothing to be sad about though, I run binaries myself in some places and I'm excited for our binary users as the single binary now has a query-frontend built into it so it can scale horizontally as well as do parallel query execution in a single process!

**Comment by mr-karan** [comment]
I am happy to test with a non-prod cluster as well. Just curious, the upgrade docs do not _yet_ mention about `unordered_writes`. I believe a lot of people are eagerly looking forward to this feature in 2.4 :)

**Comment by slim-bean** [comment]
> the upgrade docs do not yet mention about unordered_writes.

Support for unoredered writes is enabled by default!

**Comment by edinardo** [comment]
Moving from the `table-manager` to use deletes via the compactor like described [here](https://grafana.com/docs/loki/next/upgrading/#240) results in the following error on existing storage (filesystem):

```
level=info ts=2021-11-05T21:45:30.981794305Z caller=compactor.go:337 msg="compactor startup delay completed"
level=info ts=2021-11-05T21:45:30.981899888Z caller=compactor.go:376 msg="compactor started"
level=info ts=2021-11-05T21:45:30.981931675Z caller=marker.go:178 msg="mark processor started" workers=150 delay=2h0m0s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1af7a9c]

goroutine 39125 [running]:
github.com/grafana/loki/pkg/validation.(*Overrides).AllByUserID(0xc0041111c0)
        /src/loki/pkg/validation/limits.go:254 +0x1c
github.com/grafana/loki/pkg/storage/stores/shipper/compactor/retention.findSmallestRetentionPeriod({0x26f7ee8, 0xc000380c48})
        /src/loki/pkg/storage/stores/shipper/compactor/retention/expiration.go:126 +0x82
github.com/grafana/loki/pkg/storage/stores/shipper/compactor/retention.(*expirationChecker).MarkPhaseStarted(0xc000cdc580)
        /src/loki/pkg/storage/stores/shipper/compactor/retention/expiration.go:60 +0x45
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*expirationChecker).MarkPhaseStarted(0xc0001a7560)
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:516 +0x29
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).RunCompaction(0xc00028f800, {0x26f7200, 0xc0007fd2c0})
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:409 +0xb6
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions.func1()
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:342 +0x29
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions.func2()
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:350 +0x9e
created by github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:348 +0x434
```

**Comment by levonet** [comment]
Hi, I try to migrate from 2.3.0 to 2.4.0 with the next configuration:

```
auth_enabled: false
server:
  http_listen_port: 3100
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  chunk_block_size: 262144
  max_transfer_retries: 0
schema_config:
  configs:
  - from: 2021-10-10
    store: bigtable
    object_store: gcs
    schema: v11
    index:
      prefix: index_
      period: 168h
storage_config:
  gcs:
    bucket_name: loki-chunks-somewhere
  bigtable:
    instance: loki-indexes-somewhere
    project: some-gcp-project
limits_config:
  enforce_metric_name: false
table_manager:
  retention_deletes_enabled: true
  retention_period: 2520h
```

But after running the docker container I get the following error:

```
level=info ts=2021-11-07T09:34:44.747939632Z caller=main.go:94 msg="Starting Loki" version="(version=2.4.0, branch=HEAD, revision=3987933cd)"
level=info ts=2021-11-07T09:34:44.748093314Z caller=modules.go:568 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2021-11-07T09:34:44.748793366Z caller=server.go:260 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=warn ts=2021-11-07T09:34:44.749812901Z caller=experimental.go:19 msg="experimental feature in use" feature="In-memory (FIFO) cache"
level=error ts=2021-11-07T09:34:44.838102269Z caller=log.go:106 msg="error running loki" err="mkdir wal: permission denied\nerror initialising module: ingester\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
```

As far as I understand, the new version should be backward compatible with this configuration.

**Comment by maciekm** [comment]
@levonet you can set `wal` dir to something writable, if you using helm:
```diff
+  extraArgs:
+    ingester.wal-dir: /data/wal
```

**Comment by 7olstoy** [comment]
Also for users with ```err="mkdir wal: permission denied``` who have local docker volume with loki data like:
```
volumes:
  - "/var/lib/loki:/loki"
```
1) Create new folder for wal with loki owner:
```
mkdir /var/lib/loki/wal
chown 10001:10001 /var/lib/loki/wal
````
2) Add to loki config:
```
ingester:
  wal:
    enabled: true
    dir: /loki/wal
```
3) Start loki
