### ISSUE TITLE
please don't parse dotfiles in loki alerts (ruler) directory

### ISSUE THREAD

**Issue by cronolio** [grafana/loki#4654]
docker image: grafana/loki:2.3.0

```text
loki        | level=error ts=2021-11-05T09:38:49.153828932Z caller=ruler.go:481 msg="unable to list rules" err="failed to list rule groups for user fake: failed to list rule group for user fake and namespace .alerts.yml.swp: error parsing /etc/loki/alerts/fake/.alerts.yml.swp: /etc/loki/alerts/fake/.alerts.yml.swp: yaml: control characters are not allowed"
```

**Comment by ebini** [comment]
same issue here, also with loki 2.4.2 (helm chart 0.42.1)

setup loki ruler config like in https://github.com/grafana/loki/issues/3922:

```
loki:
  config: |
    ruler:
      alertmanager_url: {{ .Values.ruler.alertmanagerUrl }}
      enable_alertmanager_v2: true
      enable_api: true
      external_url: {{ .Values.ruler.alertmanagerExternalUrl }}
      ring:
        kvstore:
          store: memberlist
          prefix: rulers/
      rule_path: /tmp/loki
      storage:
        type: local
        local:
          directory: /etc/loki/rules/fake
```

and ruler:
```
loki:
  ruler:
    enabled: true
    directories:
      # in single tenant mode, the tenant ID is "fake"
      # https://grafana.com/docs/loki/latest/operations/multi-tenancy/ 
      # override this section in env-specific values
      fake: 
        testRules.yaml: |
          groups:
            - name: test1
              rules:
                - alert: test1
                  expr: |
                    1 > 0
                  for: 0m
                  labels:
                    # testing, post to #catchall for now
                    slack: slack-catchall
                    severity: warning
                  annotations:
                    summary: TEST: meowburgers and cheese
```

starting up loki:
```
 level=error ts=2022-02-01T20:09:15.359059977Z caller=ruler.go:485 msg="unable to list rules" err="failed to list rule groups for user ..2022_02_01_20_05_24.216789654: failed to list rule group for user ..2022_02_01_20_05_24.216789654 and namespace testRules.yaml: error parsing /etc/loki/rules/fake/..2022_02_01_20_05_24.216789654/testRules.yaml: /etc/loki/rules/fake/..2022_02_01_20_05_24.216789654/testRules.yaml: yaml: line 11: mapping values are not allowed in this context"
```

this is a mounted configmap and if i "shell into the pod"

```
/etc/loki/rules/fake $ ls -al
total 12
drwxrwsrwx    3 root     loki          4096 Feb  1 20:05 .
drwxr-xr-x    3 root     root          4096 Feb  1 19:58 ..
drwxr-sr-x    2 root     loki          4096 Feb  1 20:05 ..2022_02_01_20_05_24.216789654
lrwxrwxrwx    1 root     loki            31 Feb  1 20:05 ..data -> ..2022_02_01_20_05_24.216789654
lrwxrwxrwx    1 root     root            21 Feb  1 19:58 testRules.yaml -> ..data/testRules.yaml
```
