### ISSUE TITLE
Promtail: Regex stage doesn't work

### ISSUE THREAD

**Issue by flightlesstux** [grafana/loki#4661]
Hi,

Previously I'm getting an error like "Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased" and I found the issue on https://github.com/grafana/loki/issues/3335

Now, I decided the remove labels and try to parse via promtail but I didn't do that.

Here is my log sample:
`0.191.12.2 - - [10/Jun/2021:09:14:29 +0000] "GET /api/plugins/versioncheck HTTP/1.1" 200 2 "-" "Go-http-client/2.0" "13.76.247.102, 34.120.177.193" "TLSv1.2" "US" ""`

This is my promtail config:

`scrape_configs:
  - job_name: test
    pipeline_stages:
    - match:
        selector: '{job="test"}'
        stages:
        - regex:
            expression: '(?P<method>\\w+) (?P<path>[\\w|/]+) \\((?P<status>\\d+?)\\) (?P<duration>.*)'
    static_configs:
    - targets:
        - localhost
      labels:
        job: test
        __path__: /var/log/test/*.log`
       
At the Loki Explorer side, I see the log without labels. Could you please tell me what I'm missing? I'm trying to print the labels automatically like below:

`"ip" => "0.191.12.2"
"method" => "GET"
"uri" => "/api/plugins/versioncheck"
"status" => "200"
"size" => "2"
"agent" => "Go-http-client/2.0"`

**Comment by sushantkumar-amagi** [comment]
I am actually trying to achieve the same output. My scrape_config is as below:

```
scrape_configs:
  - job_name: test_log_transfer
    pipeline_stages:
    - match:
        selector: '{job="test_log_transfer"}'
        stages:
        - regex:
            expression: '^(?P<log_level>[\w\.]+) (?P<timestamp>[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9].[0-9]{3}) 
(?P<environment>[\w\.]+):( )(?P<message>.*)?'
        - labels:
            log_level:
            timestamp:
            environment:
            message:
        - timestamp:
            source: timestamp
            format: "2006-01-02 15:05:04.000"
            action_on_failure: skip
    - timestamp:
        source: timestamp
        format: "2006-01-02 15:05:04.000"
    static_configs:
    - targets:
        - localhost
      labels:
        service: test
        job: test_log_transfer
        __path__: /home/ubuntu/logs/*log
```

My log sample is as follows:
```
INFO 2021-12-01 06:26:17.687 production:   Some text message is going to be here
```

But promtail does not seem to parse the logs that way
