### ISSUE TITLE
Loki 2.4 crashes every 10 minutes

### ISSUE THREAD

**Issue by dfoxg** [grafana/loki#4684]
**Describe the bug**
After upgrading loki to v2.4 it crashes every 10 minutes:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1af803c]

goroutine 9347 [running]:
github.com/grafana/loki/pkg/validation.(*Overrides).AllByUserID(0x0)
        /src/loki/pkg/validation/limits.go:254 +0x1c
github.com/grafana/loki/pkg/storage/stores/shipper/compactor/retention.findSmallestRetentionPeriod({0x26f81e8, 0xc00054bf20})
        /src/loki/pkg/storage/stores/shipper/compactor/retention/expiration.go:126 +0x82
github.com/grafana/loki/pkg/storage/stores/shipper/compactor/retention.(*expirationChecker).MarkPhaseStarted(0xc000711c50)
        /src/loki/pkg/storage/stores/shipper/compactor/retention/expiration.go:60 +0x45
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*expirationChecker).MarkPhaseStarted(0xc0000a71a0)
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:516 +0x29
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).RunCompaction(0xc000222000, {0x26f7500, 0xc0011f7840})
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:409 +0xb6
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions.func1()
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:342 +0x29
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions.func2()
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:350 +0x9e
created by github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions
        /src/loki/pkg/storage/stores/shipper/compactor/compactor.go:348 +0x434
```

**Environment:**
 - Infrastructure: docker swarm
 - Deployment tool: docker swarm

**Screenshots, Promtail config, or terminal output**
My config:
```
auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h
  - from: 2022-11-07
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index2_
      period: 24h

storage_config:
  boltdb:
    directory: /loki/index
  filesystem:
    directory: /loki/chunks

compactor:
  retention_enabled: true

limits_config:
  retention_period: 90d
```
