### ISSUE TITLE
A Docker service discovery to Promtail

### ISSUE THREAD

**Issue by jeschkies** [grafana/loki#4703]
**Is your feature request related to a problem? Please describe.**
We have use cases when it is not desirable to ship Docker container logs via the Docker driver but with Promtail. See e.g. https://github.com/grafana/loki/issues/2361.

**Describe the solution you'd like**
We could offer Docker container discovery alongside the Kubernetes service discovery. The discovery would be pointed at the Docker daemon and fetch all [containers](https://docs.docker.com/engine/api/v1.41/#operation/ContainerList) and then their [logs](https://docs.docker.com/engine/api/v1.41/#operation/ContainerLogs).

**Describe alternatives you've considered**
It is possible [to point Promtail to the Docker logs files](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#example-docker-config). However, the Promtail process would require access to the log files.

**Comment by slim-bean** [comment]
This work was fairly recently merged into Prometheus: https://github.com/prometheus/prometheus/pull/8629 which is where Promtail gets its service discovery code which I believe could fairly easily be supported in Promtail.

**Comment by jeschkies** [comment]
This is awesome! Do you think it would be feasible to scrape the logs from the API then?

**Comment by durcon** [comment]
FYI: 

At the moment I use following work-around: 

```
scrape_configs:
- job_name: docker
  static_configs:
  - targets:
      - localhost
    labels:
      job: docker
      host: my-host
      __path__: /var/lib/docker/containers/*/*-json.log
  pipeline_stages:
  - json:
      expressions:
        message:   log
        stream:    stream
        timestamp: time
        attrs:
  - json:
      expressions:
        container_name: 
      source: attrs
  - timestamp:
      source: timestamp
      format: RFC3339Nano
  - labels:
      stream:
      container_name:
  - output:
      source: message  
```

**Disadvantages**

- It is not recommended to use Docker's log files, see [JSON File logging driver](https://docs.docker.com/config/containers/logging/json-file/)
- Promtail has to run with `root` user to read Docker's log files.
- `container_name` label is not added automatically like Loki Docker Driver does, see [Labels](https://grafana.com/docs/loki/latest/clients/docker-driver/configuration/#labels)
- `host` label is not added automatically like Docker Driver does, see [Labels](https://grafana.com/docs/loki/latest/clients/docker-driver/configuration/#labels)
- JSON is not automatically extracted like Docker Driver does

I'm not sure, but probably log rotation has to be handled, too.
