### ISSUE TITLE
Improve WAL-related error message

### ISSUE THREAD

**Issue by invidian** [grafana/loki#4704]
**Is your feature request related to a problem? Please describe.**

While upgrading Loki from `2.3.0` to `2.4.0` via `loki-stack`, I got the following error message:
```
level=error ts=2021-11-08T10:10:12.680179019Z caller=log.go:106 msg="error running loki" err="mkdir wal: read-only file system\nerror initialising module: ingester\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581
```

Figuring out out of it what is wrong is definitely not trivial.

**Describe the solution you'd like**
- Perhaps formatting for the printed stack could be improved.
- Error message should be better annotated with the standard Go error wrapping to say exactly what failed.
- Path of directory which failed to be created should be absolute, as otherwise it's ambiguous based on working directory, which makes it harder to debug when you run Loki in containers or on Kubernetes.

**Additional context**

I found this issue also mentioned in https://github.com/grafana/loki/issues/4647#issuecomment-962580566.

**Comment by DylanGuedes** [comment]
Thank you for reporting this! Agreed, not too easy to understand the problem or how to fix it.

Do you mind having a look at [PR 4705](https://github.com/grafana/loki/pull/4705) to see if it address those issues? I've added in the comments an example of what the error message will be like.

**Comment by calbot** [comment]
I ran into this issue using docker compose and I ended up changing wal: enabled: false . Is there some documentation which explains how to setup docker-compose to work with the wal dir?

**Comment by DylanGuedes** [comment]
> I ran into this issue using docker compose and I ended up changing wal: enabled: false . Is there some documentation which explains how to setup docker-compose to work with the wal dir?

For future questions, consider sending them in Slack.

Anyway,
1. Pick a directory in your host machine that will have the WAL. Since my Loki docker-compose is located in `~/Workspace/lokiplayground/docker-compose.yaml`, I'll pick `~/Workspace/lokiplayground/wal` for it.
2. Inside my `docker-compose.yaml` file, I just have to mount `~/Workspace/lokiplayground` pointing to whatever directory Loki's using for the WAL. Let's suppose it is `/loki/wal` (you can override with CLI flag `-ingester.wal.dir=/loki/wal`)

```yaml
lokinode:
  image: grafana/loki:2.4.1
  volumes:
  - ./:/loki
```

**Comment by invidian** [comment]
Not stale. I guess a bit more could be done beyond #4705.

**Comment by webchi** [comment]
Solved this for docker-compose by adding wal-dir to ingester config. `/loki` is mounted persistent volume with chmod 777
```
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled
  wal:
    dir: /loki/wal
```
