### ISSUE TITLE
Compactor panic if no override are present

### ISSUE THREAD

**Issue by webfrank** [grafana/loki#4707]
<!-- Please keep the structure below, or your issue may be closed. -->

**Describe the bug**
With a simple configuration with auth enabled but no limits per tenant we got a panic from compactor.

**To Reproduce**
1. Started Loki 2.4
2. Wait for compactor to run

**Expected behavior**
The function in /src/loki/pkg/validation/limits.go:254 returns nil if no overrides are present and after in /src/loki/pkg/storage/stores/shipper/compactor/retention/expiration.go:126 panics.

**Environment:**
 - Infrastructure: bare-metal, one instance
 - Deployment tool: loki.yaml
 - Configuration:
 ```yaml
compactor:                                                                                                          
  retention_enabled: true                                                                                           
  working_directory: /opt/loki/boltdb-shipper-compactor                                                             
  shared_store: s3                                                                                                  
                                                                                                                    
limits_config:                                                                                                      
  retention_period: 30d                                                                                             
  reject_old_samples: true                                                                                          
  reject_old_samples_max_age: 168h  
```

**Screenshots, Promtail config, or terminal output**
level=info ts=2021-11-08T14:55:19.43227299Z caller=compactor.go:376 msg="compactor started"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1e796aa]

goroutine 32168 [running]:
github.com/grafana/loki/pkg/validation.(*Overrides).AllByUserID(0xc00012f440, 0xc00000b2c0)
	/src/loki/pkg/validation/limits.go:254 +0x2a
github.com/grafana/loki/pkg/storage/stores/shipper/compactor/retention.findSmallestRetentionPeriod(0x2b539a8, 0xc00012f440, 0xc001e10e98)
	/src/loki/pkg/storage/stores/shipper/compactor/retention/expiration.go:126 +0xc9
github.com/grafana/loki/pkg/storage/stores/shipper/compactor/retention.(*expirationChecker).MarkPhaseStarted(0xc000a00590)
	/src/loki/pkg/storage/stores/shipper/compactor/retention/expiration.go:60 +0x4f
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*expirationChecker).MarkPhaseStarted(0xc001072800)
	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:516 +0x33
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).RunCompaction(0xc0002fa000, 0x2b52cc0, 0xc000836dc0, 0x0, 0x0)
	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:409 +0x465
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions.func1()
	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:342 +0x45
github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions.func2(0xc0002fa000, 0xc00ce6ffe0, 0x2b52cc0, 0xc000836dc0)
	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:350 +0x82
created by github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions
	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:348 +0x494
