### ISSUE TITLE
Promtail: Unable to set log level for discovery=consul

### ISSUE THREAD

**Issue by Himura2la** [grafana/loki#4709]
**Describe the bug**

I'm trying to disable log messages like this:

```
ts=2021-11-08T15:25:38.629285827Z caller=log.go:168 component=discovery level=debug discovery=consul msg="Watching service" service=consul tags=
```

Looks like I can't.

**To Reproduce**

1. The `/etc/promtail/config.yaml` should contain `log_level: warn` and the `consul_sd_configs` job (see below).

2.

```
$ promtail -config.file /etc/promtail/config.yaml -log.level=warn

ts=2021-11-08T15:29:02.638355395Z caller=log.go:168 component=discovery level=debug msg="Starting provider" provider=consul/0 subs=[consul_sd_configs]
ts=2021-11-08T15:29:02.639104092Z caller=log.go:168 component=discovery level=debug discovery=consul msg="Watching services" tags=
ts=2021-11-08T15:29:02.642895676Z caller=log.go:168 component=discovery level=debug discovery=consul msg="Watching service" service=***** tags=
ts=2021-11-08T15:29:02.643091775Z caller=log.go:168 component=discovery level=debug discovery=consul msg="Watching service" service=***** tags=
ts=2021-11-08T15:29:02.643387574Z caller=log.go:168 component=discovery level=debug discovery=consul msg="Watching service" service=***** tags=
```

**Expected behavior**

No `level=debug` log lines.

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: ansible

**Screenshots, Promtail config, or terminal output**

```
server:
  disable: true
  log_level: warn

clients:
  - url: https://***/loki/api/v1/push

  - job_name: consul_sd_configs
    consul_sd_configs:
      - server: '***'
        token: '****'
        datacenter: '****'
```

Promtail Version = 2.3.0
