### ISSUE TITLE
[loki-distributed] error running loki" err="mkdir /var/loki: read-only file system\nerror"

### ISSUE THREAD

**Issue by ebini** [grafana/loki#4715]
**Describe the bug**
Upgrading/Deploying vom 2.3.0 to 2.4.x doesn't work on ingester.
note: found almost the same issue (error message) in bug #4466 
perhaps these are connected.

current helm chart/version 2.4.1.

**To Reproduce**
As soon as i switch back to 2.3.0 
```
ingester:
  image:
    tag: 2.3.0
```
it works again. 

config (some things removed like ressources, and components enabling)
```
loki:
  config: |
    auth_enabled: false

    server:
      log_level: info
      http_listen_port: 3100

    distributor:
      ring:
        kvstore:
          store: memberlist

    table_manager:
      retention_deletes_enabled: true
      retention_period: {{ .Values.retention_period }}

    chunk_store_config:
      chunk_cache_config:
        memcached:
          batch_size: 100
          parallelism: 100
        memcached_client:
          consistent_hash: true
          host: {{ include "loki.memcachedChunksFullname" . }}
          service: http

    ingester:
      # Disable chunk transfer which is not possible with statefulsets
      # and unnecessary for boltdb-shipper
      max_transfer_retries: 0
      chunk_idle_period: 1h
      chunk_target_size: 1536000
      max_chunk_age: 1h
      lifecycler:
        join_after: 0s
        ring:
          kvstore:
            store: memberlist

    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist

    limits_config:
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      max_concurrent_tail_requests: 20
      max_cache_freshness_per_query: 10m

    schema_config:
      configs:
        - from: 2020-09-07
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      aws:
        s3: {{ .Values.s3 }}
        bucketnames: {{ .Values.bucketnames }}
      boltdb_shipper:
        active_index_directory: /var/loki/index
        shared_store: s3
        cache_location: /var/loki/cache
        index_gateway_client:
          server_address: dns:///{{ include "loki.indexGatewayFullname" . }}:9095
      index_queries_cache_config:
        memcached:
          batch_size: 100
          parallelism: 100
        memcached_client:
          consistent_hash: true
          host: {{ include "loki.memcachedIndexQueriesFullname" . }}
          service: http

    query_range:
      # make queries more cache-able by aligning them with their step intervals
      align_queries_with_step: true
      max_retries: 5
      # parallelize queries in 15min intervals
      split_queries_by_interval: 15m
      cache_results: true

      results_cache:
        cache:
          memcached_client:
            consistent_hash: true
            host: {{ include "loki.memcachedFrontendFullname" . }}
            max_idle_conns: 16
            service: http
            timeout: 500ms
            update_interval: 1m


    frontend_worker:
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100

    compactor:
      shared_store: s3
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150

s3: s3://eu-central-1
bucketnames: REMOVED
retention_period: 336h
```
Note: we use https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html so also adding the necessary annotations
Configuration works well with 2.3.0
with (only also only ingester) 2.4.0 (and 2.4.1). The rest seems to be working with 2.4.1

**Expected behavior**
same behaviour than with 2.3.0.

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
error message:
```
level=error ts=2021-11-09T11:42:37.712125923Z caller=log.go:106 msg="error running loki" err="mkdir wal: read-only file system\nerror initialising module: ingester\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules. *Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
```

**Comment by BitProcessor** [comment]
There is no `current helm chart/version 2.4.1.`
Can you please post the actual helm chart version ?

**Comment by DylanGuedes** [comment]
Btw, [PR 4705](https://github.com/grafana/loki/pull/4705) will make easier to understand such scenario.
You have two options:
- Define a directory with write permissions to be used for the WAL:
```yaml
wal:
  write: /var/mydirwithwritepermissions
```
- Disable WAL (not recommended):
```yaml
wal:
  enabled: false
```

**Comment by BitProcessor** [comment]
With the current helm version, you probably have /var/loki as writable folder (depending on your config) - hence my question. See this:

```
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal
```

and set   https://github.com/grafana/helm-charts/blob/70f5f2446c9ead3f122ac5a70659a4c965d08e88/charts/loki-distributed/values.yaml#L279 to `true`

**Comment by ebini** [comment]
> There is no `current helm chart/version 2.4.1.` Can you please post the actual helm chart version ?
> 
> The latest version for loki-distributed helm chart is `version: 0.39.2`

sorry, i posted the loki version. it is helm chart version: 0.39.2

**Comment by ebini** [comment]
> That should work, running with that config since this morning.
> If you set the persistence to true and set the wal folder to /var/loki/wal you should be good to go.
> Can you test?

hi, 
i just set
```
loki:
  config: |
# (...) 
    ingester:
      # (...)
      wal:
        dir: /var/loki/wal
```
(without enabling persistence)
and the pod is starting without an error

in the pod (shell into it) i see
```
/var/loki/wal $ ls -al
total 88
drwxr-sr-x    2 loki     loki          4096 Nov  9 13:38 .
drwxrwsrwx    4 root     loki          4096 Nov  9 13:38 ..
-rw-r--r--    1 loki     loki         79995 Nov  9 13:40 00000000
```

just wondering: 
is this local storage necessary (and then of course i will make it persistent). 
Thought everything would be in s3

**Comment by BitProcessor** [comment]
It works because of:
```
  {{- if not .Values.ingester.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- with .Values.ingester.persistence.storageClass }}
        storageClassName: {{ if (eq "-" .) }}""{{ else }}{{ . }}{{ end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.ingester.persistence.size | quote }}
  {{- end }}
```
So if you don't set persistence to true, it just creates a writeable folder (that is lost upon container restart).

WAL without persistence is pretty useless, see https://grafana.com/docs/loki/latest/operations/storage/wal/#write-ahead-log-wal for it's use.

Note that it EVENTUALLY ships to S3, it does not constantly ship data to S3 (that would not be a good idea for numerous reasons, but that is irrelevant here)
