### ISSUE TITLE
error creating index client while using nfs pvc

### ISSUE THREAD

**Issue by AndreyRomanchev** [grafana/loki#4720]
**Describe the bug**
I have bare-metal kubernetes with NFS autoprovisioned permanent volumes (managed-nfs-storage storageclass).
Here is my loki-stack helm values
```
loki:
  enabled: true
  serviceMonitor:
    enabled: true
  config:
    schema_config:
      configs:
      - from: "2021-01-01"
        index:
          period: 24h
          prefix: loki_index_
        object_store: filesystem
        schema: v11
        store: boltdb-shipper
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    table_manager:
      retention_deletes_enabled: true
      retention_period: 336h # 14 days

  persistence:
    enabled: true
    storageClassName: "managed-nfs-storage"
    accessModes:
    - ReadWriteOnce
    size: 20Gi

  extraArgs:
    log.level: debug

promtail:
  enabled: true
  serviceMonitor:
    enabled: true
```

PV and PVC are created fine
```
persistentvolume/pvc-bd550c99-ba90-407b-8562-749ce0a058b2   20Gi       RWO            Delete           Bound    loki/storage-loki-0                                                                                                managed-nfs-storage                 214d
loki                  persistentvolumeclaim/storage-loki-0                                                                                 Bound    pvc-bd550c99-ba90-407b-8562-749ce0a058b2   20Gi       RWO            managed-nfs-storage        214
```

After upgrade kubernetes from 1.18 to 1.19 loki is no longer working. Here is error
```
level=info ts=2021-11-09T23:44:21.96061311Z caller=main.go:129 msg="Starting Loki" version="(version=, branch=, revision=)"
level=info ts=2021-11-09T23:44:21.960687688Z caller=modules.go:504 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2021-11-09T23:44:21.960898754Z caller=server.go:239 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2021-11-09T23:44:21.965600403Z caller=table_manager.go:241 msg="loading table loki_index_18936"
level=debug ts=2021-11-09T23:44:21.970589464Z caller=table.go:119 msg="snapshotting table loki_index_18936"
level=debug ts=2021-11-09T23:44:21.970615909Z caller=table.go:122 msg="checking db 1636495200 for snapshot"
level=error ts=2021-11-09T23:44:21.973795367Z caller=log.go:106 msg="error running loki" err="read /data/loki/boltdb-shipper-active/loki_index_18936/1636495200: input/output error\nerror creating index client\ngithub.com/cortexproject/cortex/pkg/chunk/storage.NewStore\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:198\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:322\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:103\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:241\nmain.main\n\t/src/loki/cmd/loki/main.go:131\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nerror initialising module: store\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:241\nmain.main\n\t/src/loki/cmd/loki/main.go:131\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"
```

I mounted this PVC to busybox container to check everything is OK with NFS and I was able to read and write files.
```
/data/loki/boltdb-shipper-active/loki_index_18936 $ ls -la 
total 385
drwxr-xr-x    2 10001    10001           64 Nov  9 23:54 .
drwxr-xr-x    2 10001    10001       131072 Nov  9 23:35 ..
-rw-r--r--    1 10001    10001        65536 Nov  9 22:06 1636495200
-rw-r--r--    1 10001    10001        16384 Nov  9 23:50 1636495200.snapshot
/data/loki/boltdb-shipper-active/loki_index_18936 $ touch file
/data/loki/boltdb-shipper-active/loki_index_18936 $ rm file
```
As you can see loki has created 1636495200 file mentioned in error.

How can I debug what's wrong?

**Environment:**
 - Infrastructure: bare-metal Kubernetes 1.19.16
 - Deployment tool: helm
 - Loki: loki-stack 2.5.0
