### ISSUE TITLE
query_range request returns a 504

### ISSUE THREAD

**Issue by demandbase-gmavadiya** [grafana/loki#4721]
**Describe the bug**
In grafana, when we pipe multiple string filters the query_range request returns a 504.

**To Reproduce**
1. In Grafana, choose Loki as datasource and open the network tab of browser dev tools.
2.  Query with multiple string filters. For example `{container="scheduler"} |= "string1" |~ "string2_"`
3. Notice that 2 calls are made `query` and `query_range`. `query_range` always fails with a 504. (See attached snapshot)

**Expected behavior**
Request should not fail with a 504

**Environment:**
 - Infrastructure: [Hosted Grafana with Loki distributed deployed on EKS. Grafana: vv7.2.0 (efe4941ee3), Loki: v2.3.0,  EKS: v1.21]
 - Deployment tool: [helm]

**Screenshots, Promtail config, or terminal output**
![Screen Shot 2021-11-09 at 5 12 29 PM](https://user-images.githubusercontent.com/89478062/141032067-96ff8614-fe16-465d-871c-7604561246a6.png)

**Comment by demandbase-gmavadiya** [comment]
query_range config:

```
    query_range:
      align_queries_with_step: true
      max_retries: 5
      split_queries_by_interval: 15m
      parallelise_shardable_queries: true
      cache_results: true
      results_cache:
        cache:
          redis:
            endpoint: redis:6379
            expiration: 168h
            db: 0
```

**Comment by demandbase-gmavadiya** [comment]
I also tried with `split_queries_by_interval: 24h`

**Comment by demandbase-gmavadiya** [comment]
This is also reproducible when querying over longer duration like 24+hours. Query inspector shows:

```
  "error": {
    "status": 502,
    "statusText": "Bad Gateway",
    "data": {
      "message": "Bad Gateway",
      "error": "Bad Gateway",
      "response": ""
    },
    "config": {
      "url": "api/datasources/proxy/2/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bcontainer%3D%22blah%22%2Cnamespace%3D%22blah%22%7D%20%7C%3D%20%22blah%22&start=1636601983631000000&end=1636688383631000000&step=30",
      "hideFromInspector": false
    },
    "message": "Bad Gateway"
  },
```

I also bumped the distributor gateway's nginx proxy timeout values but no luck.

**Comment by demandbase-gmavadiya** [comment]
query-frontend pod log shows:

`level=error ts=2021-11-12T06:12:06.280819672Z caller=retry.go:73 org_id=fake traceID=60fd247c2521de39 msg="error processing request" try=0 err="context canceled"`

distributed-querier pod shows:
```
level=error ts=2021-11-12T06:12:06.281400135Z caller=frontend_processor.go:70 msg="error processing requests" address=10.11.8.64:9095 err="rpc error: code = Unknown desc = context canceled"
level=error ts=2021-11-12T06:12:06.281619899Z caller=batch.go:690 msg="error fetching chunks" err="RequestCanceled: request context canceled\ncaused by: context canceled"
```

**Comment by Kampe** [comment]
See the same issues here

**Comment by demandbase-gmavadiya** [comment]
@Kampe were you able resolve ? I tried a bunch of stuff but still see the issue. Hopefully someone from Loki team can take a look at it.

**Comment by demandbase-gmavadiya** [comment]
After applying changes suggested in #4015 I see a 502. Comments added to #4015

**Comment by jphuc96** [comment]
I am experiencing the same problem and it is really panic 😰

**Comment by cyriltovena** [comment]
Hello there I'm happy to help but not sure exactly what the problem.

@demandbase-gmavadiya it seems that something is going on when trying to fetch chunks from backend.

Would you be able to share the full config ? Can you try without chunk cache ? What is your S3 latency ? Can you try to tweak you s3 config there's some timeout there ?

**Comment by demandbase-gmavadiya** [comment]
@cyriltovena here's the config

```
auth_enabled: false

server:
  http_listen_port: 3100
  http_server_write_timeout: 300s
  # grpc size bumped to avoid querry error "rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4732631 vs. 4194304)"
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_recv_msg_size: 104857600

distributor:
  ring:
    kvstore:
      store: memberlist

memberlist:
  join_members:
    - loki-distributed-memberlist

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
  chunk_idle_period: 30m
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_retain_period: 1m
  max_transfer_retries: 0
  chunk_target_size: 1536000
  wal:
    dir: /var/loki/wal

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 336h
  max_cache_freshness_per_query: 10m
  # https://github.com/grafana/loki/issues/1917
  max_entries_limit_per_query: 0
  ingestion_rate_mb: 32
  ingestion_burst_size_mb: 64
  max_query_parallelism: 32

schema_config:
  configs:
    - from: 2021-10-01
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  aws:
    s3: s3://<blah>
  boltdb_shipper:
    shared_store: s3
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    cache_ttl: 168h

chunk_store_config:
  chunk_cache_config:
    redis:
      # endpoint: redis:6379
      endpoint: redis-cluster:6379
      expiration: 168h
      db: 0
  max_look_back_period: 336h

table_manager:
  retention_deletes_enabled: false
  retention_period: 336h

querier:
  query_timeout: 6m
  engine:
    # Must be a multiple of schema_config index.period
    # max_look_back_period: 2400h
    timeout: 6m
  query_ingesters_within: 4h

query_range:
  align_queries_with_step: true
  max_retries: 5
  split_queries_by_interval: 30m
  parallelise_shardable_queries: true
  cache_results: true
  results_cache:
    cache:
      redis:
        # endpoint: redis:6379
        endpoint: redis-cluster:6379
        # expiration: 168h
        db: 0
        timeout: 60s

frontend_worker:
  frontend_address: loki-distributed-query-frontend:9095
  grpc_client_config:
    grpc_compression: snappy
    # max_send_msg_size: 1.048576e+08
    max_send_msg_size: 1.548576e+08
  # match_max_concurrent: false
  parallelism: 32

frontend:
  log_queries_longer_than: 30s
  compress_responses: true
  # https://github.com/grafana/loki/issues/4613
  max_outstanding_per_tenant: 2048
  tail_proxy_url: http://loki-distributed-querier:3100

compactor:
  working_directory: /var/loki/compactor
  shared_store: s3
  compaction_interval: 5m

# ruler:
#   storage:
#     type: local
#     local:
#       directory: /etc/loki/rules
#   ring:
#     kvstore:
#       store: memberlist
#   rule_path: /tmp/loki/scratch
#   alertmanager_url: https://alertmanager.xx
#   external_url: https://alertmanager.xx
```

I will give a try without chunk cache and see if that helps. Thinking of further bumping the redis cache timeout as well. I did a Jaeger trace and saw `loki-querier` fails at S3.GetObject precisely at 60s. Our S3 bucket is pretty standard one with no additional configurations except for the retention period.
