### ISSUE TITLE
Kafka initial offset

### ISSUE THREAD

**Issue by cyriltovena** [grafana/loki#4724]
We should allow to set initial offset for a consumer.

Example of configuration:

```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: kafka
  kafka:
    use_incoming_timestamp: false
    brokers:
    - host.docker.internal:50705
    group_id: some_group
    initial_offset: 123
    topics:
    - foo
    - ^promtail.*
    labels:
      job: kafka
  relabel_configs:
      - action: replace
        source_labels:
          - __meta_kafka_topic
        target_label: topic
      - action: replace
        source_labels:
          - __meta_kafka_partition
        target_label: partition
      - action: replace
        source_labels:
          - __meta_kafka_group_id
        target_label: group
```

see `initial_offset: 123`
