### ISSUE TITLE
Authentication strategy from outside k8s promtail to inside k8s loki

### ISSUE THREAD

**Issue by yaman** [grafana/loki#473]
Hi there,

Loki+grafana in k8s made my day, saved me a big time. Thanks a lot for this great project.

I have been discovering options to use promtail outside of k8s cluster. We collect logs from edge nodes of IoT solution by deploying grafana/promtail docker image to edge nodes, connecting to loki(via kubectl port-forward) deployed with helm into k8s. There is no auth now since all the documents left auth out of topic for now. I dig into promtail and loki codes and found out there is some supporting structure for protobuf auth.

My question is, what is your suggestions to secure loki endpoint if I open k8s loki endpoint to the wild? I assume kubectl port-forward might not be the best option to access loki outside of k8s...

**Comment by daixiang0** [comment]
You can use `nodePort` to do it.
Also, like `harbor`, if to the wild, you need do extra actions by iptable or firewall to only accept ensured ip/source.

**Comment by Kuqd** [comment]
Hello @yaman ,

You're right there is no much documentation about this right now this is because usually user won't need authentification as Loki would run within their internal cluster and not exposed to the outside world.

Loki does not have any authentification system, but since you're using it as single tenant it would not be hard for you to add reverse proxy authorizing via basic auth. (nginx)
You can then use the promtail client url config to configure your user and password within the url.

```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://user:pasword@myloki.com:3100/api/prom/push

scrape_configs:
- job_name: system
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

```

However you should make sure you expose Loki via https.

Thank you !
