### ISSUE TITLE
Restoring "For State" in Alerting rules does not account for rules with the same name.

### ISSUE THREAD

**Issue by owen-d** [grafana/loki#4748]
For instance, in the following definition, we'll only re-evaluate the first instance of `absent_err`, meaning any previously firing alerts from the second rule will likely need to wait the entire `for` duration before firing again. Moreover, I expect the same problem occurs for rules with the same name in _different_ groups.
```
groups:
  - name: should_fire
    interval: 10s
    rules:
      - alert: absent_err
        expr: 'absent_over_time({job="foo"}[1m])'
        for: 10m
    rules:
      - alert: absent_err
        expr: 'absent_over_time({job="bar"}[1m])'
        for: 10m
```
