### ISSUE TITLE
TLS support for loki and promtail

### ISSUE THREAD

**Issue by Sh4d1** [grafana/loki#475]
**Is your feature request related to a problem? Please describe.**
I don't see TLS support anywhere, is it currently possible?

**Describe the solution you'd like**
If not, will/could it be implemented?
**Describe alternatives you've considered**
Or shoud we (the users) setup a reverse proxy managing TLS?

**Comment by daixiang0** [comment]
Now not possible, if you need this now, can use nginx to do it.

**Comment by Sh4d1** [comment]
@daixiang0 OK thanks! Ans is it planned in the future?

However it seems I cannot configure promtail with TLS certificats as well, so I need a external middleware that will set up the certificates?

**Comment by daixiang0** [comment]
For now you have to do like you said.

**Comment by Kuqd** [comment]
@Sh4d1 we do support https for promtail. You just need to set correctly the configuration url as such:

```yaml
client:
  url: https://mydomain.com/api/prom/push
```

If you are using custom root CA, you should consider adding the CA where you are running promtail, we don't support insecure and I don't think we will.

Server side I don't think we will add this feature as there is a lot of reverse proxy offering this for you.

What we could do though is offer a reverse proxy activation with TLS secret variable via helm to ease this for you.

Feel free to open an issue for that.

**Comment by rekz1** [comment]
@Kuqd  "we do support https for promtail" is only half right :-) 

what about mTLS for Promtail <-> Loki? Can i configure Promtail to use a client certificate?

**Comment by Kuqd** [comment]
Correct, still there is a software solving that problem like consul and istio, If you're not in k8s that could be more difficult, there is a PR open especially for that let's see.

**Comment by rekz1** [comment]
Yeah not really - unfortunately. I've already tried that. Loki/Promtail along with Istio in k8s.

When i deploy them along with Istio Envoy Sidecars...

Promtail gives me:

```
level=error ts=2019-05-02T09:16:23.403938144Z caller=client.go:186 msg="final error sending batch" status=500 error="server returned HTTP status 500 Internal Server Error (500): rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>"
```

Loki gives me:

```
evel=warn ts=2019-05-02T09:17:40.236262511Z caller=logging.go:49 traceID=765972c977acb165 msg="POST /api/prom/push (500) 224.321µs Response: \"rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: <nil>\\n\" ws: false; Accept-Encoding: gzip; Content-Length: 1061; Content-Type: application/x-protobuf; User-Agent: Go-http-client/1.1; X-B3-Parentspanid: 0400748391a49ec0; X-B3-Sampled: 0; X-B3-Spanid: 6c7b2c533a4ce85f; X-B3-Traceid: 85c8078d4e6b88f50400748391a49ec0; X-Forwarded-Proto: http; X-Request-Id: d000a4ba-4996-4c14-a437-fa9891372647; "
```

I would be happy if you can tell me how to get this working! :-)

**Comment by AlessandroEmm** [comment]
I run into the same issue, and i'm wondering how promtail/loki are even affected by the surrounding mTLS.

**Comment by rekz1** [comment]
@AlessandroEmm any progress so far? :-)

**Comment by tcolgate** [comment]
I'm looking at configuring for multiple clusters, mTLS is my usual preference for this. At the moment it looks like (promtail) -> (promtail -> loki) might be the best option?

**Comment by AlbertSu123** [comment]
Is there a way to send data from promtail(https) -> loki(https)?

**Comment by mikequentel** [comment]
Hi all...figured out how to include run loki over https (TLS) via the configuration settings that go in `local-config.yaml` ...in this example, the endpoint is using 8443:

```
server:
  http_listen_port: 8443
  http_tls_config: &tls_server_config
    cert_file: /etc/loki/myserver.cert.pem
    key_file: /etc/loki/myserver.key.pem
```

this is an alternative to using a reverse proxy.
The above is based on the fact that loki uses [github.com/weaveworks/common/server/server.go](http://github.com/weaveworks/common/server/server.go) which in turn uses [github.com/prometheus/node_exporter/https/tls_config.go](http://github.com/prometheus/node_exporter/https/tls_config.go)

**Comment by andretadeu** [comment]
Hi all,

I could configure TLS in Promtail and Loki, but now the communication between them does not work.

Configurations for Loki:
```yaml
loki-distributed:
  loki:
    config: |
      auth_enabled: false
      ...
      server:
        http_listen_port: 3100
        http_tls_config: &tls_server_config
          cert_file: /etc/loki/cert.pem
          key_file: /etc/loki/key.pem
```

Configurations for Promtail:
```yaml
clients:
  uri: http://<Redacted>/loki/api/v1/push
  tls_config:
    ca_file: /etc/loki/certs/ca.crt
    cert_file: /etc/loki/certs/cert.pem
    key_file: /etc/loki/certs/key.pem

extraVolumes:
  - name: inf-secret
    secret:
      secretName: obs-secret
      optional: false

extraVolumeMounts:
  - name: inf-secret
    mountPath: "/etc/loki/certs"
```

I am using secrets to store the certificates and the services can find them. But I am getting the following errors:

Loki Distributed:
```
ts=2022-08-12T13:52:30.424816874Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve obs-loki-distributed-memberlist: lookup obs-loki-distributed-memberlist on 10.152.183.10:53: no such host"
```

Promtail:
```
level=warn ts=2022-08-12T14:00:25.150418634Z caller=client.go:369 component=client host=pt-rdl2617-vm.infinera.com:3101 msg="error sending batch, will retry" status=-1 error="Post \"http://pt-rdl2617-vm.infinera.com:3101/loki/api/v1/push\": dial tcp 10.46.100.17:3101: connect: connection refused"
level=warn ts=2022-08-12T14:01:21.774977915Z caller=client.go:369 component=client host=pt-rdl2617-vm.infinera.com:3101 msg="error sending batch, will retry" status=-1 error="Post \"http://pt-rdl2617-vm.infinera.com:3101/loki/api/v1/push\": dial tcp 10.46.100.17:3101: connect: connection refused"
```
