### ISSUE TITLE
Enormous listbucket operations when using boltdb-shipper with S3 storage

### ISSUE THREAD

**Issue by Voronenko** [grafana/loki#4750]
**Describe the bug**
Environment: single server loki server with S3 backend , version 2.3.0

**To Reproduce**
1. Started Loki 2.3.0 with following config, difference from default - longer log storage period
```
auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  grpc_server_max_recv_msg_size: 15728640
  grpc_server_max_send_msg_size: 15728640
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  chunk_target_size: 1536000
  chunk_block_size: 1048576
  max_transfer_retries: 0
  max_chunk_age: 5m
compactor:
  working_directory: /tmp/loki/retention
  shared_store: s3
  compaction_interval: 30m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
schema_config:
  configs:
    - from: 2018-04-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h
    - from: 2021-09-27
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h
storage_config:
  boltdb:
    directory: /tmp/loki/index
  filesystem:
    directory: /tmp/loki/chunks
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    shared_store: s3
    cache_location: /tmp/loki/index_cache
    resync_interval: 30m
  aws:
    #bucketnames: CENSORED_BUCKET_NAME
    #region: eu-central-1
    s3: s3://eu-central-1/CENSORED_BUCKET_NAME
    endpoint: s3.eu-central-1.amazonaws.com
    s3forcepathstyle: true
    insecure: false
    signature_version: v4
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
chunk_store_config:
  # keep in sync with table_manager->retention_period
  # Loki requires that retention (2520h below) is divisible by the duration of each index table (168h by default)
  max_look_back_period: 2520h

table_manager:
  # keep in sync with chunk_store_config->max_query_lookback
  retention_period: 2520h
  retention_deletes_enabled: true
  poll_interval: 24
```

2. Started Promtail 2.3.0
3. Point some logging payload to loki (up to 1000 lines per hour)
4. Observe S3 billing in aws cost explorer

**Expected behavior**
Relatively reasonable cost of the ownership.
Observed behavior: enormous list of daily listbucket operations, which increases costs to unacceptable level (monthly cost of the VM and more)

**Environment:**
 - Infrastructure: Standalone loki server,  payload coming from app.
 - Deployment tool: ansible, standalone setup
