### ISSUE TITLE
Json data is shown with escape characters as non-json logs

### ISSUE THREAD

**Issue by mvkrishna86** [grafana/loki#4752]
**Describe the bug**
My log contains json data in each log statement. But that is being shown in grafana as below
```
{
  "log": "{\"traceID\":\"623713de15161e1bca9a1540d63ad031\",\"bytes_received\":\"0\",\"amazonTraceId\":\"-\",\"bytes_sent\":\"393\",\"path\":\"/_cluster/health/\",\"protocol\":\"HTTP/1.1\",\"upstream_service_time\":\"2\",\"duration\":\"2\",\"upstream_transport_failure_reason\":\"-\",\"user_agent\":\"Apache-HttpAsyncClient/4.1.4 (Java/11.0.7)\",\"response_code\":\"200\",\"start_time\":\"2021-11-15T09:10:19.107Z\",\"method\":\"GET\",\"upstream_host\":\"192.168.11.23:9200\"}\n",
  "stream": "stdout",
  "time": "2021-11-15T09:10:22.663411076Z"
}
```

**To Reproduce**
1. Grafana Agent in kubernetes cluster and push the logs to Loki
2. See the logs in grafana where loki datasource is configured.

**Expected behavior**
Logs should be shown properly without escape chars and the fields log, stream and time should not be added.

**Environment:**
 - Infrastructure: Kubernetes, Loki 2.3.0 and 2.4.1, Grafana Agent 0.18.3
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/15136443/141765393-c402e195-c78e-419d-bb26-8686fdc72c0b.png)

Grafana Agent Configuration:
```
loki:
  positions_directory: /tmp/loki-positions
  configs:
    - name: agent
      clients:
        - url: https://loki.xxxxxxxx/api/prom/push
          tenant_id: xxxxxxxxx
          external_labels:
            cluster: demo
            region: ap-south-1
      scrape_configs:
        - job_name: kubernetes-pods-app
          kubernetes_sd_configs:
            - role: pod
          pipeline_stages:
            - cri: { }
          relabel_configs:
            - action: drop
              regex: .+
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_app
              target_label: app
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_component
              target_label: component
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: node
            - action: drop
              regex: ''
              source_labels:
                - __meta_kubernetes_pod_label_app
            - action: drop
              regex: ''
              source_labels:
                - __meta_kubernetes_pod_label_app
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - namespace
                - app
              target_label: job
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__

```

**Comment by dannykopping** [comment]
You should apply a `docker` pipeline stage, since your log message is actually embedded in the `log` key:
https://grafana.com/docs/loki/latest/clients/promtail/stages/docker/

**Comment by mvkrishna86** [comment]
I added the below in grafana agent config. But still the same resilt. 
```
          pipeline_stages:
            - cri: { }
            - docker: { }
   ```         
Actually, this behavior is observed for only few pods. Some logs are being read and detected properly as json objects.

**Comment by dannykopping** [comment]
Did you restart the agent after applying those changes? This is definitely the solution to the problem.
I don't think you need to add both `cri` and `docker`, unless you have a mix of both in your environment.

**Comment by tugwitt** [comment]
I'm getting a similar issue in ECS with fluent-bit and firelens (described [here](https://grafana.com/docs/loki/latest/clients/aws/ecs/)).

<img width="1220" alt="Screen Shot 2021-11-15 at 10 45 09 PM" src="https://user-images.githubusercontent.com/11688356/141892221-36b4ab80-8838-47bf-897f-ea3baa4acfc3.png">

My configuration in ECS is exactly the same as the docs describe, except its using `json` instead of `key_value` line format. It seems like there seems to be some parsing done (similar to promtail docker stage) though I can't find anything in the loki fluent bit [docs](https://grafana.com/docs/loki/latest/clients/fluentbit/). I can open a new issue if need be, this is probably fairly reproducible.

**Comment by mvkrishna86** [comment]
@dannykopping, Yes I restarted the pods after making the changes.
I tried the below changes also. Still seeing the same issue.
```
        - job_name: kubernetes-pods-istio-proxy
          kubernetes_sd_configs:
              - role: pod
          pipeline_stages:
            - json:
                expressions:
                  path: path
                  traceID: traceID
                  duration: duration
                  amazonTraceId: amazonTraceId
                  bytes_received: bytes_received
                  bytes_sent: bytes_sent
                  method: method
                  start_time: start_time
                  response_code: response_code
                  user_agent: user_agent
                  upstream_transport_failure_reason: upstream_transport_failure_reason
                  upstream_service_time: upstream_service_time
          relabel_configs:
            - action: keep
              source_labels:
                - __meta_kubernetes_pod_container_name
              regex: 'istio-proxy'
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_app
              target_label: app
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_component
              target_label: component
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: node
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - namespace
                - app
              target_label: job
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__

```
