### ISSUE TITLE
Docs feedback: /clients/promtail/configuration.md

### ISSUE THREAD

**Issue by alekseyMaksarov** [grafana/loki#4764]
In pipeline_stages when discibing Docker stage in YAML file in json stage expressions key missed.
https://grafana.com/docs/loki/latest/clients/promtail/configuration/#docker

```
- json:
    expressions:
      output: log
      stream: stream
      timestamp: time
- labels:
    stream:
- timestamp:
    source: timestamp
    format: RFC3339Nano
- output:
    source: output
```
