### ISSUE TITLE
Issues with S3 Index download timing out on first query after longer time

### ISSUE THREAD

**Issue by applike-ss** [grafana/loki#4790]
**Describe the bug**
I have setup Loki 2.4.1 in microservice mode with boltdb-shipper and s3 as index/chunk storage.
When i query loki data via grafana for let's say the last 5 minutes, the index gateway tries to download the index file to provide it to the queriers. This seems to hang when i do the very first query in grafana for the day. The index file (4kb in my case) was the successfully downloaded after ~2 minutes. When i then try a different time range after my first query failed, it will download the missing indices that weren't downloaded before just fine (and fast).

Here's some logs from the first query timeframe:
```
level=info ts=2021-11-19T09:03:36.541550535Z caller=table_manager.go:207 msg="syncing tables"
level=info ts=2021-11-19T09:04:27.833952639Z caller=table_manager.go:181 msg="downloading all files for table loki_18950"
level=warn ts=2021-11-19T09:04:57.829169133Z caller=grpc_logging.go:55 method=/indexgatewaypb.IndexGateway/QueryIndex duration=29.995521704s err="context deadline exceeded" msg="gRPC\n"
level=warn ts=2021-11-19T09:05:57.911073337Z caller=grpc_logging.go:55 duration=29.998880886s method=/indexgatewaypb.IndexGateway/QueryIndex err="context deadline exceeded" msg="gRPC\n"
level=warn ts=2021-11-19T09:05:57.911081136Z caller=grpc_logging.go:55 duration=29.999196933s method=/indexgatewaypb.IndexGateway/QueryIndex err="context deadline exceeded" msg="gRPC\n"
level=warn ts=2021-11-19T09:05:57.911133025Z caller=grpc_logging.go:55 method=/indexgatewaypb.IndexGateway/QueryIndex duration=29.99948865s err="context deadline exceeded" msg="gRPC\n"
level=warn ts=2021-11-19T09:05:57.911185109Z caller=grpc_logging.go:55 method=/indexgatewaypb.IndexGateway/QueryIndex duration=29.999291544s err="context deadline exceeded" msg="gRPC\n"
level=warn ts=2021-11-19T09:05:57.911297833Z caller=grpc_logging.go:55 method=/indexgatewaypb.IndexGateway/QueryIndex duration=29.999082583s err="context deadline exceeded" msg="gRPC\n"
level=warn ts=2021-11-19T09:05:57.911333269Z caller=grpc_logging.go:55 method=/indexgatewaypb.IndexGateway/QueryIndex duration=29.998835723s err="context deadline exceeded" msg="gRPC\n"
level=warn ts=2021-11-19T09:05:57.911769785Z caller=grpc_logging.go:55 method=/indexgatewaypb.IndexGateway/QueryIndex duration=29.997407373s err="context deadline exceeded" msg="gRPC\n"
level=warn ts=2021-11-19T09:05:57.911787677Z caller=grpc_logging.go:55 method=/indexgatewaypb.IndexGateway/QueryIndex duration=29.997397229s err="context deadline exceeded" msg="gRPC\n"
level=warn ts=2021-11-19T09:05:57.911803367Z caller=grpc_logging.go:55 duration=29.997448087s method=/indexgatewaypb.IndexGateway/QueryIndex err="context deadline exceeded" msg="gRPC\n"
level=warn ts=2021-11-19T09:05:57.91183095Z caller=grpc_logging.go:55 method=/indexgatewaypb.IndexGateway/QueryIndex duration=29.997575631s err="context deadline exceeded" msg="gRPC\n"
level=warn ts=2021-11-19T09:05:57.911859745Z caller=grpc_logging.go:55 method=/indexgatewaypb.IndexGateway/QueryIndex duration=29.997549244s err="context deadline exceeded" msg="gRPC\n"
level=warn ts=2021-11-19T09:05:57.91187106Z caller=grpc_logging.go:55 method=/indexgatewaypb.IndexGateway/QueryIndex duration=29.997483775s err="context deadline exceeded" msg="gRPC\n"
level=info ts=2021-11-19T09:06:32.003916932Z caller=util.go:109 msg="downloaded file compactor-1637312569.gz from table loki_18950"
level=info ts=2021-11-19T09:08:36.541404118Z caller=table_manager.go:207 msg="syncing tables"
```

And here some logs for the second query with a bigger timeframe (24h instead of the prior 5 minutes)
```
level=info ts=2021-11-19T09:38:36.541296926Z caller=table_manager.go:207 msg="syncing tables"
level=info ts=2021-11-19T09:42:04.706092401Z caller=table_manager.go:181 msg="downloading all files for table loki_18949"
level=info ts=2021-11-19T09:42:04.792010149Z caller=util.go:109 msg="downloaded file compactor-1637283727.gz from table loki_18949"
level=info ts=2021-11-19T09:43:36.54130546Z caller=table_manager.go:207 msg="syncing tables"
```

All of this is happening in the same pod in kubernetes and also on the same ec2 instance. I did try to download the file that loaded slow manually via the cli multiple times and it was never slow.

**To Reproduce**
1. Started Loki 2.4.1 in microservice mode
2. Ingest some logs
3. wait until log indices were flushed and compacted
4. Query: data for some event stream for the last 5 minutes

**Expected behavior**
s3 download should always be fast (and maybe a timeout should be configurable to retry faster?)

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
See the logs above.
Config used:
```
auth_enabled: true

server:
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      store: memberlist

memberlist:
  join_members:
    - loki-loki-distributed-memberlist

ingester:
  wal:
    dir: /var/loki/wal
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      heartbeat_timeout: 30s
      replication_factor: 3
  autoforget_unhealthy: true
  chunk_block_size: 262144
  chunk_target_size: 1572864
  chunk_encoding: snappy
  chunk_idle_period: 1m
  chunk_retain_period: 30s
  concurrent_flushes: 128
  flush_check_period: 10s
  max_chunk_age: 1h
  max_transfer_retries: 0

limits_config:
  unordered_writes: true
  max_global_streams_per_user: 0
  enforce_metric_name: false
  max_cache_freshness_per_query: 10m
  max_query_length: 12000h
  max_query_parallelism: 32
  reject_old_samples: false
  ingestion_rate_mb: 100
  ingestion_burst_size_mb: 300

schema_config:
  configs:
    - from: 2020-11-12
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_
        period: 24h

storage_config:
  aws:
    s3: s3://eu-central-1/loki
  boltdb_shipper:
    shared_store: s3
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    cache_ttl: 24h
    index_gateway_client:
      server_address: dns:///loki-loki-distributed-index-gateway:9095

query_range:
  align_queries_with_step: true
  parallelise_shardable_queries: true
  max_retries: 5
  split_queries_by_interval: 15m
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 1024
        validity: 24h
querier:
  query_ingesters_within: 1h
  query_timeout: 30s
  max_concurrent: 50
  engine:
    timeout: 299s

frontend_worker:
  frontend_address: loki-loki-distributed-query-frontend:9095
  parallelism: 2

frontend:
  max_outstanding_per_tenant: 2048
  log_queries_longer_than: 5s
  compress_responses: true
  tail_proxy_url: http://loki-loki-distributed-querier:3100

compactor:
  working_directory: /var/loki/compactor
  shared_store: s3
```

I am yet new to loki and appreciate any input on what i can improve in my config here - even if not "on-topic".
