### ISSUE TITLE
Fail to migrate from 2.3.x to 2.4.x 

### ISSUE THREAD

**Issue by budarin** [grafana/loki#4827]
**Describe the bug**
Have installed Loki log driver and Loki 2.3.0 in Docker swarm  - Grafana sees all Loki logs
When upgrade to Loki 2.4.1 version  - Grafana does not see any Loki's logs

**To Reproduce**

1. initialize docker swarm
2. Install the latest Loki log driver
3. Configure Loki from https://raw.githubusercontent.com/grafana/loki/v2.4.1/cmd/loki/loki-local-config.yaml
```yml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
```
4. Start Loki (SHA or version) - 2.4.1
 ```yaml
 services:
    loki:
        image: grafana/loki:2.4.1
        ports:
            - 3100:3100
        networks:
            - serviceNetwork
        volumes:
            - loki_vol:/loki
            - ./config/docker/config/loki/loki.yaml:/etc/loki/config.yaml:ro
        command: -config.file=/etc/loki/config.yaml
        ports:
            - 3100:3100
```
5. Services are configured to log as
```yml
logging:
    driver: 'loki'
    options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
        loki-retries: '5'
        loki-batch-size: '1000'
        no-file: 'false'
        keep-file: 'true'
        max-size: '5m'
        max-file: '3'
        loki-pipeline-stages: |
            - drop:
                expression: ".*/health.*"
        loki-relabel-config: |
            - action: labelmap
              regex: swarm_stack
              replacement: stack
            - action: labelmap
              regex: swarm_(service)
            - action: labeldrop
              regex: swarm_stack
            - action: labeldrop
              regex: swarm_service
            - action: labeldrop
              regex: filename
```
6. Run Grafana and go to Explore and choose Loki Source

![image](https://user-images.githubusercontent.com/8055157/143497181-3c73f3e3-dd4d-47ac-b592-e0ef533f8253.png)

**Expected behavior**
Grafana should see Loki's logs as it was in 2.3.1 Loki version

Loki's metrics

![image](https://user-images.githubusercontent.com/8055157/143528285-24962d51-f9aa-4c9f-9600-037a5d3318c4.png)

![image](https://user-images.githubusercontent.com/8055157/143528381-593cadcb-8a22-4ba8-a593-6eb3d330da16.png)

**Environment:**
 - MacOS, Docker Swarm on Docker Desktop
 - docker-compose

**Comment by budarin** [comment]
also have tried with promtail without Loki log driver (uninstall it)

```yaml
services:
    loki:
        image: grafana/loki:2.4.1
        volumes:
            - loki_vol:/loki
            - ./config/docker/config/loki/loki.yaml:/etc/loki/config.yaml:ro
        command: -config.file=/etc/loki/config.yaml
        networks:
            - serviceNetwork


    promtail:
        image: grafana/promtail:2.4.1
        volumes:
            - ./config/docker/config/promtail/config.yml:/etc/promtail/config.yml:ro
            - /var/lib/docker/:/var/lib/docker:ro
        command: -config.file=/etc/promtail/config.yml
        networks:
            - serviceNetwork
```

promtail is collecting logs

![image](https://user-images.githubusercontent.com/8055157/143507915-d5cffa53-5f35-4933-8c79-ff39def2a79a.png)

but Grafana does not see them

**Comment by budarin** [comment]
Confirm that also have the error as is described in #4754

**Comment by chaudum** [comment]
There are 2 suspicious log lines:

```
level=warn ts=2021-12-03T00:29:47.566447433Z caller=pool.go:184 msg="removing frontend failing healthcheck" addr=10.0.0.33:9096 reason="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
level=error ts=2021-12-03T00:29:47.56686117Z caller=scheduler_processor.go:199 org_id=fake msg="error notifying frontend about finished query" err="rpc error: code = Canceled desc = grpc: the client connection is closing" frontend=10.0.0.33:9096
```

Which makes me wonder whether the scheduler component communicates via the frontend component through the 10.0.0.33 address and not through the loopback address.

Could you please run Loki with debug level

```yaml
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: debug
```

and post the complete output of the startup.

And also provide the output of

```
$ docker exec -ti LOKI_CONTAINER_ID ifconfig
```

**Comment by chaudum** [comment]
Could you also post the config of your previous Loki 2.3.x setup? And try using the 2.3.x config with Loki 2.4.1

**Comment by budarin** [comment]
Loki 2.3.0 config

```yaml
auth_enabled: false

server:
    http_listen_port: 3100
    grpc_listen_port: 9096

ingester:
    wal:
        enabled: true
        dir: /tmp/wal
    lifecycler:
        address: 127.0.0.1
        ring:
            kvstore:
                store: inmemory
            replication_factor: 1
        final_sleep: 0s
    chunk_idle_period: 1h # Any chunk not receiving new logs in this time will be flushed
    max_chunk_age: 1h # All chunks will be flushed when they hit this age, default is 1h
    chunk_target_size: 1048576 # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
    chunk_retain_period: 30s # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
    max_transfer_retries: 0 # Chunk transfers disabled

schema_config:
    configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
              prefix: index_
              period: 24h

storage_config:
    boltdb_shipper:
        active_index_directory: /tmp/loki/boltdb-shipper-active
        cache_location: /tmp/loki/boltdb-shipper-cache
        cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: filesystem
    filesystem:
        directory: /tmp/loki/chunks

compactor:
    working_directory: /tmp/loki/boltdb-shipper-compactor
    shared_store: filesystem
    retention_enabled: true

limits_config:
    retention_period: [7d]

chunk_store_config:
    max_look_back_period: 0s

table_manager:
    retention_deletes_enabled: false
    retention_period: 0s

ruler:
    storage:
        type: local
        local:
            directory: /tmp/loki/rules
    rule_path: /tmp/loki/rules-temp
    alertmanager_url: http://localhost:9093
    ring:
        kvstore:
            store: inmemory
    enable_api: true
```
