### ISSUE TITLE
NoCredentialProviders

### ISSUE THREAD

**Issue by duythien** [grafana/loki#483]
**Describe the bug**

```
 level=info ts=2019-04-16T05:04:18.192618618Z caller=lifecycler.go:366 msg="entry not found in ring, adding with no tokens"
level=info ts=2019-04-16T05:04:18.192989054Z caller=lifecycler.go:296 msg="auto-joining cluster after timeout"
level=warn ts=2019-04-16T05:05:08.730531517Z caller=gokit.go:43 traceID=2b19708c70261ad0 msg="GET /ready (500) 77.027µs Response: \"\" ws: false; Accept-Encoding: gzip; Connection: close; User-Agent: kube-probe/1.13; "
level=warn ts=2019-04-16T05:05:12.93797349Z caller=gokit.go:43 traceID=43da9206c87d7439 msg="GET /ready (500) 56.489µs Response: \"\" ws: false; Accept-Encoding: gzip; Connection: close; User-Agent: kube-probe/1.13; "
level=error ts=2019-04-16T05:19:18.19652795Z caller=flush.go:118 org_id=fake msg="failed to flush user" err="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
level=error ts=2019-04-16T05:19:48.199160025Z caller=flush.go:118 org_id=fake msg="failed to flush user" err="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
level=error ts=2019-04-16T05:20:18.19967651Z caller=flush.go:118 org_id=fake msg="failed to flush user" err="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
level=error ts=2019-04-16T05:20:48.199964847Z caller=flush.go:118 org_id=fake msg="failed to flush user" err="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors" 
```

**To Reproduce**
Loki.yaml

```
auth_enabled: false

server:
  http_listen_port: 3100

limits_config:
  enforce_metric_name: false

ingester:
  lifecycler:
    ring:
      replication_factor: 1
      store: inmemory
          
  chunk_idle_period: 15m
# schema_config:
#   configs:
#   - from: 0
#     store: boltdb
#     object_store: filesystem
#     schema: v9
#     index:
#       prefix: index_
#       period: 168h
# storage_config:
#   boltdb:
#     directory: /data/loki/index
#   filesystem:
#     directory: /data/loki/chunks
schema_config:
  configs:
  - from: 0
    store: dynamo
    object_store: s3
    schema: v9
    index:
      prefix: loki_index
      period: 0
storage_config:
  aws:
    s3: s3://xxxxx:xxxxx/E5ijo4J@eu-central-1/loki-xxx.io
    dynamodbconfig:
      dynamodb: dynamodb://xxxx:xxxE5ijo4J@eu-central-1
```

**Expected behavior**

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by duythien** [comment]
Slove it now

**Comment by khauser** [comment]
@duythien Can you please tell us how?

**Comment by duythien** [comment]
@khaines You need create new secret aws without slash `/` refer to https://rtfm.co.ua/en/grafana-labs-loki-using-aws-s3-as-a-data-storage-and-aws-dynamodb-for-indexes/

**Comment by setevoy2** [comment]
@duythien Well, the issue still persists... Thanks for the link - actually, that's my blog, and I wrote the cause there, but I completely forgot about that :-D

**Comment by duythien** [comment]
> 

Lol :)

**Comment by MohammedNoureldin** [comment]
It is funny, but I se this error, though I am not using or configuring any aws at all. Does anyone know why?

**Comment by fengluodb** [comment]
I also found the error. I use oss as my object storage.

```yaml
loki:
   storage_config:
      aws:
        access_key_id: xxx
        bucketnames: test
        endpoint: https://oss-cn-zhangjiakou.aliyuncs.com
        region: cn-zhangjiakou
        s3forcepathstyle: false
        secret_access_key: xxx
```
