### ISSUE TITLE
Promtail fails to parse syslog stream from Infinera routers

### ISSUE THREAD

**Issue by mweinelt** [grafana/loki#4871]
Syslog from Infinera metro routers fails to parse and subsequently breaks rsyslogd connection. 

**Describe the bug**
When piping syslog from an Infinera CX2 into an rsyslogd that relays it into promtail we hit 

```
caller=syslogtarget.go:216 msg="error parsing syslog stream" err="expecting a structured data parameter (`key=\"value\"`, both part from 1 to max 32 US-ASCII characters; key cannot contain `=`, ` `, `]`, and `\"`, while value cannot contain `]`, backslash, and `\"` unless escaped) [col 416]"
```

which then breaks the TCP connection with rsyslogd.

```
rsyslogd[859]: action 'action-0-builtin:omfwd' resumed (module 'builtin:omfwd') [v8.2001.0 try https://www.rsyslog.com/e/2359 ]
rsyslogd[859]: omfwd: TCPSendBuf error -2027, destruct TCP Connection to 127.0.0.1:1515 [v8.2001.0 try https://www.rsyslog.com/e/2027 ]
rsyslogd[859]: action 'action-0-builtin:omfwd' suspended (module 'builtin:omfwd'), retry 0. There should be messages before this one giving the reason for suspension. [v8.2001.0 try https://www.rsyslog.com/e/2007 ]
```

**To Reproduce**
1. Started rsyslog (8.2001.0-1ubuntu1.1)
2. Started Promtail (2.4.1) with Syslog Scrape Job
3. Configured Infinera device to send syslog

See [syslog.zip](https://github.com/grafana/loki/files/7651167/syslog.zip) for resulting syslog pcap.

**Expected behavior**
Promtail shouldn't choke on syslog that it cannot parse and treat it as unstructured instead.

**Environment:**
```
promtail, version 2.4.1 (branch: HEAD, revision: f61a4d261)
  build user:       root@9cbe2f86250f
  build date:       2021-11-08T13:05:10Z
  go version:       go1.16.2
  platform:         linux/amd64
```

**Screenshots, Promtail config, or terminal output**

### rsyslog.d/promtail.conf
```
$ModLoad imudp
$UDPServerRun 514

if $fromhost-ip != "127.0.0.1" then {
        action(type="omfwd" protocol="tcp" port="1515" Target="127.0.0.1" Template="RSYSLOG_SyslogProtocol23Format" TCP_Framing="octet-counted")
        & stop
}
```

### promtail.yml
```yml
server:
  disable: true
  http_listen_port: 9080

positions:
  filename: /var/lib/promtail/positions.yml

clients:
  - url: https://loki.example.com/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    relabel_configs:
    - regex: (.*)(.example.com)?
      replacement: ${1}.example.com
      source_labels:
      - __syslog_message_hostname
      target_label: machine
    syslog:
      idle_timeout: 60s
      label_structured_data: true
      labels:
        job: syslog
      listen_address: 127.0.0.1:1515
```

(Tried to disable `label_structured_data` but that changed nothing)
