### ISSUE TITLE
Promtail is not working with relative symbolic link

### ISSUE THREAD

**Issue by RangerCD** [grafana/loki#4905]
**Describe the bug**
Promtail can not recognize the correct target path of a relative symbolic link pointing to a log file.
Actually, it's a bug in `github.com/grafana/tail`, see https://github.com/grafana/tail/issues/11, and this [PR](https://github.com/grafana/tail/pull/12) will fix it.

**To Reproduce**
1. Enter an empty directory (eg: `mkdir /tmp/test/ && cd /tmp/test`)
2. Create a log file `touch test.log.2021-12-10` inside.
3. Create a relative symbolic link `ln -s test.log.2021-12-10 test.log`
4. Edit promtail config, add a `scrape_config` with `__path__: /tmp/test/*.log`
5. Start promtail outside the directory we store those log files

**Expected behavior**
Log should be collected with label `filename="/tmp/test/test.log"`.

**Environment:**
 - Infrastructure: PC
 - Deployment tool: -

**Screenshots, Promtail config, or terminal output**

***Promtail config***
```yaml
server:
  http_listen_address: localhost
  http_listen_port: 9080
  grpc_listen_port: 0
  http_server_read_timeout: 120
  http_server_write_timeout: 120
  grpc_server_max_concurrent_streams: 0
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
positions:
  filename: ./loki_positions.yaml
clients:
  - url: http://127.0.0.1/loki/api/v1/push
    batchwait: 10s
    tenant_id: fake
scrape_configs:
  - job_name: test
    static_configs:
      - targets:
          - localhost
        labels:
          job: test
          instance: localhost
          __path__: /tmp/test/*.log
```

***Terminal output***
```
level=info ts=2021-12-10T02:45:09.514268094Z caller=server.go:260 http=127.0.0.1:9080 grpc=[::]:39305 msg="server listening on addresses"
level=info ts=2021-12-10T02:45:09.514394153Z caller=main.go:119 msg="Starting Promtail" version="(version=2.4.1, branch=HEAD, revision=f61a4d261)"
level=info ts=2021-12-10T02:45:14.514351003Z caller=filetargetmanager.go:255 msg="Adding target" key="/tmp/test/*.log:{instance=\"localhost\", job=\"test\"}"
level=error ts=2021-12-10T02:45:14.514840341Z caller=filetarget.go:287 msg="failed to start tailer" error="open test.log.2021-12-10: no such file or directory" filename=/tmp/test/test.log
level=error ts=2021-12-10T02:45:24.515538954Z caller=filetarget.go:287 msg="failed to start tailer" error="open test.log.2021-12-10: no such file or directory" filename=/tmp/test/test.log
```
