### ISSUE TITLE
Error : permission denied error intitailising module in AWS EC2 AMI .

### ISSUE THREAD

**Issue by jjkim0816** [grafana/loki#4906]
Hi, I can't find answer for under question, so why error is evaluated?
I made server using docker-compose.

ErrorMessage:
```
level=error ts=2021-12-10T10:35:23.53008258Z caller=log.go:106 msg="error running loki" err="mkdir wal: permission denied\nerror initialising module: ingester\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
```

Environment: 
Server : AWS AMI EC2 (centos)
Authorization: root
Docker-compose:
```
version: "3.2"

services:
    grafana:
      image: grafana/grafana:latest
      container_name: sound_grafana
      ports:
        - "8000:8000" # tcp
        - "3000:3000" # web
      user: root
      volumes:
        - ./lib/grafana:/var/lib/grafana
      networks:
        - monitor
      restart: always
      depends_on:
        - loki

    loki:
      image: grafana/loki:latest
      container_name: sound_loki
      ports:
        - "3100:3100"
      volumes:
        - ./etc/loki:/etc/loki
      networks:
        - monitor
      restart: always

networks:
    monitor:
        driver: bridge
 ```
