### ISSUE TITLE
Cannot create index client using Azure Storage Account

### ISSUE THREAD

**Issue by gai6948** [grafana/loki#4918]
**Describe the bug**
Cannot create index client when using Azure Storage Account

**To Reproduce**
1. Started Loki (SHA or version) 2.4.1 (using `grafana/loki` helm chart 2.8.1)
2. Config applied:
```yaml
auth_enabled: false
ingester:
  chunk_idle_period: 30m
  chunk_block_size: 262144
  chunk_retain_period: 15m
  max_transfer_retries: 0
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: azure
      schema: v11
      index:
        prefix: index_
        period: 24h
server:
  http_listen_port: 3100
storage_config:
  azure:
    account_key: ${AZURE_STORAGE_ACCOUNT_KEY}
    account_name: jarcieasaloki
    container_name: logchunks
    request_timeout: 0
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: azure
  filesystem:
    directory: /data/loki/chunks
chunk_store_config:
  max_look_back_period: 0s
ruler:
  storage:
    type: local
    local:
      directory: /data/rules
  rule_path: /data/tmp/scratch
  alertmanager_url: http:/alertmanager.svc.prometheus:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
```
3. Loki exits upon container started

**Expected behavior**
Loki can run 

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
```
level=error ts=2021-12-13T07:10:52.870124959Z caller=log.go:106 msg="error running loki" err="illegal base64 data at input byte 0\nerror creating index client\ngithub.com/grafana/loki/pkg/storage/chunk/storage.NewStore\n\t/src/loki/pkg/storage/chunk/storage/factory.go:201\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:370\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:106\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
```
