### ISSUE TITLE
Promtail: support Avro messages from Kafka

### ISSUE THREAD

**Issue by kd7lxl** [grafana/loki#4932]
**Is your feature request related to a problem? Please describe.**
We have Avro type messages in Kafka that I'd like to send to Loki.

**Describe the solution you'd like**
I'd like to implement an Avro parser for Promtail, but I don't know where best it would fit into Promtail. Please provide some design guidance on how this should be implemented. Should it be part of the Kafka scraper? Should it be a parser or transform stage?

I'd like the solution to support reading the Avro schema from a schema registry by defining the URL of the schema registry.

**Describe alternatives you've considered**
I've already implemented a standalone tool to send these messages to Loki, but it is proprietary, and would serve the community better as a Promtail feature.

cc @cyriltovena

**Comment by cyriltovena** [comment]
Hey @kd7lxl,

I think this would be a great feature to add. I'm not sure it would be useful to have it for all targets since this is more used in the kafka land. We could start by adding this to promtail and then if needed move it to pipeline stages.

This has to happen here:

https://github.com/grafana/loki/blob/main/clients/pkg/promtail/targets/kafka/target.go#L85

From my poor knowledge, I've used Avro only couple of time, I think you'll need the user to declare where the schema file can be found. Not sure if multiple schema is possible, I think the Avro header could point to which schema.

I suggest before you dig into this too much to suggest in this issue what will the configuration look like, once we agreed then it's all yours.

Obviously I'll assist you along the way, so don't hesitate to ping me again :)

Cheers

**Comment by kd7lxl** [comment]
Thanks for replying, and sorry for the delay. Expect a bit more delay on my next reply as we break for the holidays.

I looked into this a bit and it seems to fit really well as a promtail parsing stage. Configuration could look something like this:
```yaml
- avro:
    expressions:
      output: .  # not sure if this is possible, but I want all fields marshaled as JSON!
      timestamp: ts
    schemaRegistry: http://schema-registry.schema-registry.svc
    # schema: |
    #   fixed schema could be provided like this
- timestamp:
    source: timestamp
    format: UnixNs
- output:
    source: output
```
I would want the avro log line to be replaced by a json equivalent, but I'm not sure how universal that would be. Maybe some users would want to preserve the avro format, but this would require avro support throughout loki rather than just in promtail. I suppose if a parser was supported in promtail is could be supported in the querier as well.
