### ISSUE TITLE
Loki dosent respect ingestion_rate_mb value

### ISSUE THREAD

**Issue by rpuserh** [grafana/loki#4939]
Hi,

I have following config for limits 
```
    limits_config:
        enforce_metric_name: false
        ingestion_burst_size_mb: 20
        ingestion_rate_mb: 50
        ingestion_rate_strategy: global
        max_cache_freshness_per_query: 10m
        max_global_streams_per_user: 10000
        max_query_length: 12000h
        max_query_parallelism: 16
        max_streams_per_user: 0
        reject_old_samples: true
        reject_old_samples_max_age: 168h
```

However i receive this error in promtail 

```
"server returned HTTP status 429 Too Many Requests (429): Ingestion rate limit exceeded (limit: 8738133 bytes/sec) while attempting to ingest '2049' lines totaling '1048449' bytes, reduce log volume or contact your Loki administrator to see if the limit can be increased"
```
Where 8738133 is not equal to 50mb

For some reason it dosent respect  `ingestion_rate_mb: 50` value

Installation method : Tanka
loki version 
```
jb install github.com/grafana/loki/production/ksonnet/loki@v2.4.1
```

Please advice.
