### ISSUE TITLE
Loki with AWS DynamoDB and AWS S3

### ISSUE THREAD

**Issue by akshayrathod1** [grafana/loki#4957]
I created a POC of loki with S3 and AWS DynamoDB.
attaching loki and promtail configuration below.
after this configuration the DynamoDB cost me 8350$ in one month. because of all the read request. I am totally new to this and not able to figure out what went wrong, and which parameters I should tune to optimise the cost.
Please help me out or any documentation regarding configuration will help.

-------------------------------
```
Loki configuration:
auth_enabled: false

server:

  http_listen_port: 3100

ingester:

  lifecycler:

    address: 127.0.0.1

    ring:

      kvstore:

        store: inmemory

      replication_factor: 1

    final_sleep: 0s

  chunk_idle_period: 5m

  chunk_retain_period: 30s

  max_transfer_retries: 0

schema_config:

  configs:

    - from: 2020-10-24

      store: aws

      object_store: s3

      schema: v11

      index:

        prefix: index_

        period: 8760h

        tags:

          app: loki

          env: development

storage_config:

  aws:

    s3: s3://us-east-1/arathod-loki

    dynamodb:

      dynamodb_url: dynamodb://us-east-1

limits_config:

  enforce_metric_name: false

  reject_old_samples: true

  reject_old_samples_max_age: 168h



chunk_store_config:

  max_look_back_period: 8760h



table_manager:

  retention_deletes_enabled: true

  retention_period: 8760h
  ```
Promtail configuration:
```
server:

  disable: true

  http_listen_port: ${PROMTAIL_SERVER_PORT}

  grpc_listen_port: 9801



positions:

  filename: ${SERVER_HOME}/positions.yaml



clients:

  - url: http://${LOKI_ADDRESS}:${LOKI_PORT}/loki/api/v1/push

scrape_configs:

  - job_name: server-logs

    static_configs:

      - labels:

          job: server-logs

          host: awm-an01

          __path__: ${SERVER_HOME}/log/*.log*

  - job_name: var-logs

    static_configs:

      - labels:

          job: var-logs

          host: awm-an01

          __path__: /var/log/*.log*
    ```
