### ISSUE TITLE
Build and publish the grafana-loki-driver for aarch64

### ISSUE THREAD

**Issue by Shanduur** [grafana/loki#4958]
**Is your feature request related to a problem? Please describe.**
Currently when installing `loki driver` on `aarch64` host with:
`sudo docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions` we get the following response:

```text
$ sudo docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
latest: Pulling from grafana/loki-docker-driver
Digest: sha256:82270b494d8c157f035fde65bc0159076f4c4361b5bb061b4fc817e8db04234a
32dbe5a742d5: Complete
Error response from daemon: dial unix /run/docker/plugins/<HEX>/loki.sock: connect: no such file or directory
```

This is due to the fact that `docker-driver` is packaged for `x86-64` only:
```text
$ file docker-driver
docker-driver: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=DO6vNf_wsXoEWNEjOFH3/93mUMtV44Qhc2KVPon-r/y3sw_SvVl78AQ3JXTicn/IDlaLVofQRgKVjK9AaNj, stripped
```

**Describe the solution you'd like**
Add a build target to the CI/CD.

**Describe alternatives you've considered**
Cross compiling the driver on other system - my current RaspberryPi fails on compile due to insufficient memory.

**Additional context**
None.

**Comment by Shanduur** [comment]
It can be done with addition to `.circleci/config.yml` (and adding appropriate runner):
```yaml
  # Docker driver for arm64
  build/docker-driver-arm64:
    <<: *defaults
    resource_class: arm.medium
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker-driver
          command: make PLUGIN_ARCH=-arm64 docker-driver
```
