### ISSUE TITLE
Promtail unable to push logs to Loki: "context deadline exceeded" but DNS / curl inside the promtail container works fine

### ISSUE THREAD

**Issue by onedr0p** [grafana/loki#4969]
**Describe the bug**

Promtail is unable to send logs to Loki due to:

```
level=warn ts=2021-12-19T17:10:47.099790321Z caller=client.go:349 component=client host=loki.domain.tld msg="error sending batch, will retry" status=-1 error="Post \"https://loki.domain.tld/loki/api/v1/push\": context deadline exceeded"
```

**To Reproduce**
I have Loki deployed in a Kubernetes cluster and I am trying to ship logs from another system to it via Promtail deployed with docker compose.

Docker compose:

```yaml
---
version: "3.8"
services:
  promtail:
    image: docker.io/grafana/promtail:2.4.1
    container_name: promtail
    restart: unless-stopped
    command:
      - -config.file=/etc/promtail/promtail.yaml
    volumes:
      - "./apps/promtail/promtail.yaml:/etc/promtail/promtail.yaml:ro"
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
```

Promtail config:

```yaml
server:
  log_level: debug
  disable: true
client:
  url: https://loki.domain.tld/loki/api/v1/push
positions:
  filename: /tmp/positions.yaml
scrape_configs:
  - job_name: journal
    journal:
      path: /var/log/journal
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ["__journal__systemd_unit"]
        target_label: unit
      - source_labels: ["__journal__hostname"]
        target_label: hostname
```

**Expected behavior**

Promtail to ship logs to Loki

**Environment:**
 - Infrastructure: docker-compose
 - Deployment tool: docker-compose

**Screenshots, Promtail config, or terminal output**

Now the even weirder things are I can dig `loki.domain.tld` on the host of the machine AND inside the promtail container. I can also `curl -v -L https://loki.domain.tld/loki/api/v1/push` on the host machine AND inside the promtail container and have it return HTTP `405`. It seems like promtail cannot look up my domain from within the source code. Everything looks fine on the host machine and inside the promtail container.

On the host machine:
```
❯ curl -I https://loki.domain.tld/loki/api/v1/push
HTTP/2 405
date: Sun, 19 Dec 2021 17:20:56 GMT
strict-transport-security: max-age=31449600; includeSubDomains
```

Inside the promtail container after `apt install curl`:
```
root@expanse:/# curl -I https://loki.domain.tld/loki/api/v1/push
HTTP/2 405
date: Sun, 19 Dec 2021 17:21:03 GMT
strict-transport-security: max-age=31449600; includeSubDomains
```

This is the same response I get on a machine where promtail is working:
```
root@opnsense:~ # curl -I https://loki.domain.tld/loki/api/v1/push
HTTP/2 405
date: Sun, 19 Dec 2021 17:23:14 GMT
strict-transport-security: max-age=31449600; includeSubDomains
```

Why can't promtail resolve my domain but the host and container can?

**Comment by SimplyAmuthan** [comment]
I am kind of having the similar problem, for me, I am getting the following error

Here is the context, I am using the following helm charts to install loki and promtail on a k8 cluster:

1)  grafana/loki (chart version:  2.9.1 , App version: v2.4.2 )
2) grafana/promtail (chart version:  3.11.0 , App version: 2.4.2 )

These charts are coming from https://grafana.github.io/helm-charts  

And following is the final configuration for the promtail agent

```
server:
  http_listen_network: tcp
  http_listen_address: ""
  http_listen_port: 3101
  http_listen_conn_limit: 0
  grpc_listen_network: tcp
  grpc_listen_address: ""
  grpc_listen_port: 9095
  grpc_listen_conn_limit: 0
  http_tls_config:
    cert_file: ""
    key_file: ""
    client_auth_type: ""
    client_ca_file: ""
  grpc_tls_config:
    cert_file: ""
    key_file: ""
    client_auth_type: ""
    client_ca_file: ""
  register_instrumentation: true
  graceful_shutdown_timeout: 30s
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  http_server_idle_timeout: 2m0s
  grpc_server_max_recv_msg_size: 4194304
  grpc_server_max_send_msg_size: 4194304
  grpc_server_max_concurrent_streams: 100
  grpc_server_max_connection_idle: 2562047h47m16.854775807s
  grpc_server_max_connection_age: 2562047h47m16.854775807s
  grpc_server_max_connection_age_grace: 2562047h47m16.854775807s
  grpc_server_keepalive_time: 2h0m0s
  grpc_server_keepalive_timeout: 20s
  grpc_server_min_time_between_pings: 5m0s
  grpc_server_ping_without_stream_allowed: false
  log_format: logfmt
  log_level: info
  log_source_ips_enabled: false
  log_source_ips_header: ""
  log_source_ips_regex: ""
  http_path_prefix: ""
  external_url: ""
  health_check_target: null
  disable: false
client:
  url: http://loki:3100/api/v1/push
  batchwait: 1s
  batchsize: 1048576
  follow_redirects: false
  backoff_config:
    min_period: 500ms
    max_period: 5m0s
    max_retries: 10
  timeout: 10s
  tenant_id: ""
  stream_lag_labels: filename
clients:
- url: http://loki:3100/api/v1/push
  batchwait: 1s
  batchsize: 1048576
  follow_redirects: false
  backoff_config:
    min_period: 500ms
    max_period: 5m0s
    max_retries: 10
  timeout: 10s
  tenant_id: ""
  stream_lag_labels: filename
positions:
  sync_period: 10s
  filename: /run/promtail/positions.yaml
  ignore_invalid_yaml: false
scrape_configs:
- job_name: kubernetes-pods
  pipeline_stages:
  - cri: {}
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_controller_name]
    separator: ;
    regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
    target_label: __tmp_controller_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name, __meta_kubernetes_pod_label_app,
      __tmp_controller_name, __meta_kubernetes_pod_name]
    separator: ;
    regex: ^;*([^;]+)(;.*)?$
    target_label: app
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_component, __meta_kubernetes_pod_label_component]
    separator: ;
    regex: ^;*([^;]+)(;.*)?$
    target_label: component
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*)
    target_label: node_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [namespace, app]
    separator: /
    regex: (.*)
    target_label: job
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: (.*)
    target_label: container
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
    separator: /
    regex: (.*)
    target_label: __path__
    replacement: /var/log/pods/*$1/*.log
    action: replace
  - source_labels: [__meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash,
      __meta_kubernetes_pod_annotation_kubernetes_io_config_hash, __meta_kubernetes_pod_container_name]
    separator: /
    regex: true/(.*)
    target_label: __path__
    replacement: /var/log/pods/*$1/*.log
    action: replace
  static_configs: []
target_config:
  sync_period: 10s
  stdin: false
```

I verified the Loki is up and running by going to the URL http://loki:3100/ready

but the Promtail agent was not able to reach out to it and showed the following error

```
level=error ts=2022-02-10T20:01:07.141341734Z caller=client.go:360 component=client host=loki:3100 msg=“final error sending batch” status=404 error=“server returned HTTP status 404 Not Found (404): 404 page not found”
```

**Comment by JoaoLSA** [comment]
I'm having this exact error and that's insane that there's no real solution for that other than rolling back the version.

**Comment by starcraft66** [comment]
Same thing here...

**Comment by PramodMunaweera** [comment]
This is what worked for me solving "context deadline exceeded" errors in my setup.

- Disable authentication
- Increased GRPC message size
- Increased ingester client timeout
- (Kubernetes) change loki url to k8s fully qualified DNS address

Full configuration below,

```
loki:
  auth_enabled: false
  ingester_client:
    remote_timeout: 10s
  config:
    server:
      http_server_read_timeout: 600s
      http_server_write_timeout: 600s
      grpc_server_max_recv_msg_size: 8388608
      grpc_server_max_send_msg_size: 8388608
      ingestion_rate_mb: 15
      ingestion_burst_size_mb: 30
      per_stream_rate_limit: 10MB
      per_stream_rate_limit_burst: 20MB
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 744h
      max_query_length: 0h
promtail:
  config:
    clients:
      - url: http://loki.default.svc.cluster.local:3100/loki/api/v1/push
```
