### ISSUE TITLE
There is a problem with the label setting

### ISSUE THREAD

**Issue by lgy1027** [grafana/loki#4972]
Currently using docker to deploy promtail, the configuration file is as follows, the label name obtained now is "k8s_httpbin_httpbin-0_lgy_eb9c03c4-fa3d-4bdf-b010-ec5e01667c7f_1", but the effect I want is name="httpbin-0"
namespace="lgy", what should I do to get it
```
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://192.168.194.129:31212/loki/api/v1/push
scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<pod>(?:[^|]*[^|])).(?P<name>(?:[^|]*[^|]))
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          name:
      - output:
          source: output
```
