### ISSUE TITLE
relabel_configs for AutoScaling Group Host

### ISSUE THREAD

**Issue by fayas-akram** [grafana/loki#4997]
My servers deployed in  Autoscaling Group where it runs 3 servers and I have configured my Instance with a hostname.
I want to send a log from each server with InstanceID as label. Since I have set the Hostname I can not able to use 
```
    - source_labels: [__meta_ec2_private_dns_name]
        regex: "(.*)"
        target_label: __host__
```
        
 Is there Any solution to only filter the Instance with Promtail
 
 Host Name = test.com
 ASG Size = 3
 
Note: Even I have tried using the Tag Name to filter the host. Please kindly provide some inshights.
 
```
scrape_configs:
  - job_name: Neutrino_log
    ec2_sd_configs:
      - region: us-east-1
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name
        action: replace
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance
        action: replace
      - action: replace
        replacement: /root/download/test.log
        target_label: __path__
      - source_labels: [__meta_ec2_tag_Name]
        regex: "(.*)"
        target_label: "C-Test-Server"

```
Tried the below link also: https://grafana.com/blog/2020/07/13/loki-tutorial-how-to-set-up-promtail-on-aws-ec2-to-find-and-analyze-your-logs/
