### ISSUE TITLE
Promtail too slow to keep up with heavy logging in systemd journal

### ISSUE THREAD

**Issue by macman31** [grafana/loki#4998]
**Describe the bug**
I have a server with services that are logging a total of ~12k logs/second to `journald` (with bursts up to 20k log/s). I am trying to ship the server logs to Loki. 
However with my configuration Promtail can only process around ~6k logs/s.

This results in either of two things:
- If the server only bursts occasionally above 6k logs/s, then the server logs in Loki will be running behind until Promtail can catch up to `journald`.
- If the server constantly outputs >6k logs/s, then Promtail cannot keep up with `journald`. Logs will be running extremely behind in Loki, and at some point `journald` will start to rotate out logs that Promtail still hasn't read. This causes Promtail to become stuck in a loop of trying to read logs that has been deleted. When that happens, we get 10 error messages per second, and no logs are shipped anymore to Loki (Promtail doesn't even keep open the connection to the Loki server): `caller=journaltarget.go:187 msg="received error during sdjournal follow" err="failed to iterate journal: bad message"`

This server has an EPYC 7451 processor. Promtail is at ~140% CPU usage while it's running.
Loki is no factor here, as this can easily be reproduced using Promtail's `dry-run` feature (see `To Reproduce` below).

Also note that I tried to remove the `relabel_configs` section altogether from my Promtail config (see below for the Promtail config), and the maximum I could get out of Promtail without `relabel_configs` was ~9k logs/s, still less than the ~12k logs/s `journald` logs. And those labels are pretty basic in my opinion, and necessary for my use case where I have a lot of different system and user services writing to `journald`.

I read Promtail source code and profiled Promtail using `pprof`, and I think the issue is that Promtail is reading/formatting logs sequentially, and that Promtail's [journal formatter](https://github.com/grafana/loki/blob/main/clients/pkg/promtail/targets/journal/journaltarget.go#L256) takes time to process each log line (to manage labels): at >~6k logs/s the time spent to process a log line becomes greater than the time between new log lines, and we start to get limited by the formatter run time.

**To Reproduce**
Promtail is in version 2.4.1, revision f61a4d261 (downloaded from the Releases page).

Those commands were run one after the other, while there was a constant stream of logs to `journald`:
```
# timeout 11s journalctl -f | pv --line-mode --average-rate --delay-start 1 >/dev/null
[11.7k/s]
```

With the Promtail configuration below:
```
# timeout 11s /opt/promtail_2.4.1 --dry-run -config.file=/opt/promtail.yml | pv --line-mode --average-rate --delay-start 1 >/dev/null
level=info ts=2021-12-23T16:43:52.564803502Z caller=server.go:260 http=0.0.0.0:9080 grpc=0.0.0.0:34135 msg="server listening on addresses"
level=info ts=2021-12-23T16:43:52.565420875Z caller=main.go:119 msg="Starting Promtail" version="(version=2.4.1, branch=HEAD, revision=f61a4d261)"
[6.20k/s]
```

With the same Promtail configuration, but without any `relabel_configs`:
```
# timeout 11s /opt/promtail_2.4.1 --dry-run -config.file=/opt/promtail_mod.yml | pv --line-mode --average-rate --delay-start 1 >/dev/null
level=info ts=2021-12-23T16:44:39.265169152Z caller=server.go:260 http=0.0.0.0:9080 grpc=0.0.0.0:34211 msg="server listening on addresses"
level=info ts=2021-12-23T16:44:39.265534611Z caller=main.go:119 msg="Starting Promtail" version="(version=2.4.1, branch=HEAD, revision=f61a4d261)"
[8.90k/s]
```

**Expected behavior**
Promtail can keep up with `journald` under heavy logging situations, even if it has to use a lot of CPU/other resources to do so.

**Environment**
 - Infrastructure: Bare-metal dedicated server with an EPYC 7451 CPU running 1 KVM virtual machine, all the services + Promtail are on this virtual machine. For now it is the only VM running on this dedicated server. The VM is not constrained in resources (12 dedicated cores with a load average of only 2.5, 18G free RAM, NVMe drives).
 - Deployment tool: Manual deployment

**Screenshots, Promtail config, or terminal output**
My Promtail configuration is:
```
clients:
  - url: http://[LOKI SERVER IP]:3100/loki/api/v1/push

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /opt/promtail/promtail_positions.yaml

scrape_configs:
- job_name: journal
  journal:
    max_age: 12h
    path: /var/log/journal
    labels:
      job: systemd-journal
  relabel_configs:
    - source_labels: ['__journal__hostname']
      target_label: 'host'
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'
    - source_labels: ['__journal__systemd_user_unit']
      target_label: 'userunit'
```
