### ISSUE TITLE
relabel does not support for environmental variable

### ISSUE THREAD

**Issue by fayas-akram** [grafana/loki#5001]
I have configured the promtail like below and it takes the environmental variable and then returns the error

`error:  Unable to parse config: ./promtail-local-config.yaml: "env_name" is invalid 'target_label' for replace action`

```
scrape_configs:
  - job_name: Neutrino_log
    ec2_sd_configs:
      - region: us-east-1
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name
        action: replace
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance
        action: replace
      - action: replace
        replacement: /root/download/test.log
        target_label: __path__
      - source_labels: [___meta_ec2_tag_Name]
        regex: "(.*)"
        target_label: ${SERVER_NAME}
    pipeline_stages:
      - multiline:
          firstline: '\[+[a-zA-Z]+\]'
          max_wait_time: 2s
```
