### ISSUE TITLE
Non-alphanumeric characters in AWS secret key causes SignatureDoesNotMatch error

### ISSUE THREAD

**Issue by ethanhassett** [grafana/loki#5012]
**Describe the bug**
When using S3 for shared store, having a non-alphanumeric character (specifically a `+` or a `/`) in the secret key cause a SignatureDoesNotMatch error.
This happened with both non-encoded and URL-encoded keys with Loki v2.4.1

**To Reproduce**
1. Add the following storage config to your configuration YAML, where `<SECRET_ACCESS_KEY>` contains a `+` or `/`:
```yaml
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: s3
  aws:
    s3: s3://<ACCESS_KEY_ID>:<SECRET_ACCESS_KEY>@<AWS_REGION>/<BUCKET_NAME>
    s3forcepathstyle: true
    region: <AWS_REGION>

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: aws
```
2. Attempt to start Loki and add it as a data source in Grafana to be faced with a 403 error "SignatureDoesNotMatch".

**Expected behavior**
Using a secret key with non-alphanumerics doesn't cause connection issues, or at least can be URL-encoded to work properly.

**Environment:**
 - Infrastructure: Docker on Ubuntu Server
 - Deployment tool: docker-compose

**Screenshots, Promtail config, or terminal output**
Example error output:
```
error ts=2021-12-28T01:35:10.694820122Z caller=log.go:106 msg="error running loki" err="SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
  status code: 403
```
