### ISSUE TITLE
Docs: Add ring configuration details for scheduler_ring and compactor_ring

### ISSUE THREAD

**Issue by KMiller-Grafana** [grafana/loki#5035]
PR https://github.com/grafana/loki/pull/5015 was merged in and solved the issue that ring configuration for the scheduler and compactor can be within the common section. However, ring configuration details may be specified within the scheduler block or within the compactor block.  Those configuration knob descriptions are missing from the block-specific locations.

This issue exists to identify this further work that needs to be done to complete the ring-specific configuration.

**Comment by DylanGuedes** [comment]
I did some mapping of what set of configurations is not accurate and the ones that I think we should prioritize is:
* Distributor ring is lacking these relevant configurations: `heartbeat_period`, `instance_id`, `instance_interface_names`, `instance_port`, `instance_addr`

Not so important configurations:
* Ingester lifecycler ring:
  * missing zone_awareness_enabled and excluded_zones

* Ruler ring:
  * Reusing common ring configuration, looks fine (although it doesn't have a few options such as instance_availability_zone and tokens_file_path, but doesn't are not really important)

**Comment by KMiller-Grafana** [comment]
Let's document exactly what is available.  And if those knobs can be used in a different block, then let's add the documentation to those blocks.  So that readers know exactly what _is_ available within a block.  We're missing the ring knob descriptions that may be in the compactor and scheduler block.

**Comment by DylanGuedes** [comment]
Exactly list of available configurations:

# Ingester Ring
Ingester ring is actually inside the lifecycler. The lifecycler has the following knobs:
```yaml
ring:
  kvstore:
    store:
    prefix:
    consul:
    etcd:
    multi:
  heartbeat_timeout:
  replication_factor:
  zone_awareness_enabled:
  excluded_zones:
num_tokens:
heartbeat_period:
observe_period:
join_after:
min_ready_duration:
interface_names:
final_sleep:
tokens_file_path:
availability_zone:
unregister_on_shutdown:
readiness_check_ring_health:
address:
port:
id:
```

# Distributor Ring
Distributor ring has the following knobs:
```yaml
kvstore:
  store:
  prefix:
  consul:
  etcd:
  multi:
heartbeat_period:
heartbeat_timeout:
instance_id:
instance_port:
instance_addr:
```

# Compactor Ring
Compactor ring supports the following knobs:
```yaml
kvstore:
  store:
  prefix:
  consul:
  etcd:
  multi:
heartbeat_period:
heartbeat_timeout:
tokens_file_path:
zone_awareness_enabled:
instance_id:
instance_interface_names:
instance_port:
instance_addr:
instance_availability_zone:
```

# Scheduler Ring
Scheduler ring supports the following knobs. Notice it is exactly the same as the compactor and very similar to the distributor:
```yaml
kvstore:
  store:
  prefix:
  consul:
  etcd:
  multi:
heartbeat_period
heartbeat_timeout
tokens_file_path
zone_awareness_enabled
instance_id
instance_interface_names
instance_port
instance_addr
instance_availability_zone
```

# Ruler Ring
Ruler ring supports the following knobs:

```yaml
kvstore:
  store:
  prefix:
  consul:
  etcd:
  multi:
heartbeat_period:
heartbeat_timeout:
instance_id:
instance_interface_names:
instance_port:
instance_addr:
num_tokens:
```
