### ISSUE TITLE
Loki Does not Create Tables on DynamoDB

### ISSUE THREAD

**Issue by fayas-akram** [grafana/loki#5070]
**Loki Does not Create Tables on DynamoDB**
I have configured Loki to Store chunks in s3 and indexes in DynamoDB. Each Day Loki looks for a Different table name and which is not created and therefore, it fails to show logs on my dashboard.

*my index prefix is loki_index_*
*Loki looks for different index suffixes each day. Example loki_index_18997, loki_index_18998, loki_index_18999, etc*

For the record, I used roles for my instance and it was given full access with loki_index_* resources

**My Loki Configuration is as follows**
```
schema_config:
  configs:
    - from: 2020-04-15
      store: aws
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  aws:
    s3: s3://us-east-2/my-bucket
    s3forcepathstyle: true
    dynamodb:
      dynamodb_url: dynamodb://us-east-2

compactor:
  working_directory: /loki/compactor
  shared_store: s3
  compaction_interval: 5m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
```

**Error **
```
level=error ts=2022-01-07T04:52:20.345618928Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found"
level=error ts=2022-01-07T04:52:20.34734157Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="rpc error: code = Code(500) desc = QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found\n"
level=error ts=2022-01-07T04:52:20.361839228Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found"
level=error ts=2022-01-07T04:52:20.362431505Z caller=retry.go:73 org_id=fake msg="error processing request" try=1 err="rpc error: code = Code(500) desc = QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found\n"
level=error ts=2022-01-07T04:52:20.374077785Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found"
level=error ts=2022-01-07T04:52:20.374709622Z caller=retry.go:73 org_id=fake msg="error processing request" try=2 err="rpc error: code = Code(500) desc = QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found\n"
level=error ts=2022-01-07T04:52:20.385779626Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found"
```

**Comment by cyriltovena** [comment]
You need to activate table_manager, the compactor is not compatible with NoSQL index.

**Comment by fayas-akram** [comment]
@cyriltovena Still not working and I have removed the compactor part and add table manager with 24 hours retention period and it did not work

**Configuration**
```
schema_config:
  configs:
    - from: 2018-04-15
      store: aws
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  aws:
    s3: s3://us-east-1/creately-prometheus-store-test
    s3forcepathstyle: true
    dynamodb:
      dynamodb_url: dynamodb://us-east-1

table_manager:
  retention_deletes_enabled: true
  retention_period: 24h
  index_tables_provisioning:
    provisioned_write_throughput: 10
    provisioned_read_throughput: 10
```

**Same error - Index not found**
```
level=error ts=2022-01-07T09:44:35.614402403Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found"
level=error ts=2022-01-07T09:44:35.616080133Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="rpc error: code = Code(500) desc = QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found\n"
level=error ts=2022-01-07T09:44:35.62789012Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found"
level=error ts=2022-01-07T09:44:35.62842623Z caller=retry.go:73 org_id=fake msg="error processing request" try=1 err="rpc error: code = Code(500) desc = QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found\n"
level=error ts=2022-01-07T09:44:35.639516483Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found"
level=error ts=2022-01-07T09:44:35.640028302Z caller=retry.go:73 org_id=fake msg="error processing request" try=2 err="rpc error: code = Code(500) desc = QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found\n"
level=error ts=2022-01-07T09:44:35.652181158Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found"
level=error ts=2022-01-07T09:44:35.652662619Z caller=retry.go:73 org_id=fake msg="error processing request" try=3 err="rpc error: code = Code(500) desc = QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found\n"
level=error ts=2022-01-07T09:44:35.66374471Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found"
level=error ts=2022-01-07T09:44:35.664210449Z caller=retry.go:73 org_id=fake msg="error processing request" try=4 err="rpc error: code = Code(500) desc = QueryPages error: table=loki_index_18999: ResourceNotFoundException: Requested resource not found\n"
```

Also, please let me know what is the recommended DynamoDb Read/Write ratio for production and I am planning to store my logs for ```a year```
