### ISSUE TITLE
mkdir /var/loki: read-only file system\nerror creating index client

### ISSUE THREAD

**Issue by mvkrishna86** [grafana/loki#5092]
**Describe the bug**

**To Reproduce**
Run loki using helm, querier is giving error: 
```
level=info ts=2022-01-11T05:33:58.693625359Z caller=memberlist_client.go:394 msg="Using memberlist cluster node name" name=loki-querier-59f85f45d5-rplnq-24cc500a
level=error ts=2022-01-11T05:33:58.694017193Z caller=log.go:106 msg="error running loki" err="mkdir /var/loki: read-only file system\nerror creating index client\ngithub.com/grafana/loki/pkg/storage/chunk/storage.NewStore\n\t/src/loki/pkg/storage/chunk/storage/factory.go:201\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:370\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:106\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1133\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1133"

```
**Expected behavior**
Querier should work properly

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm
 - chart: loki-distributed, version: 0.39.5
 

**Screenshots, Promtail config, or terminal output**
Below is the config: 

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  interval: 1h0m0s
  releaseName: loki-distributed
  serviceAccountName: devops
  timeout: 10m
  maxHistory: 2
  upgrade:
    cleanupOnFail: true
  chart:
    spec:
      chart: loki-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    global:
      image:
        registry: public.ecr.aws
    fullnameOverride: loki
    loki:
      image:
        repository: nslhub/loki
      config: |
        auth_enabled: true
        server:
          http_listen_port: 3100
          grpc_server_max_recv_msg_size: 20971520
          grpc_server_max_send_msg_size: 20971520
        distributor:
          ring:
            kvstore:
              store: memberlist

        memberlist:
          join_members:
            - loki-memberlist
          max_join_backoff: 1m
          max_join_retries: 10
          min_join_backoff: 1s

        ingester:
          lifecycler:
            ring:
              kvstore:
                store: memberlist
              replication_factor: 1
          chunk_idle_period: 30m
          chunk_block_size: 262144
          chunk_encoding: snappy
          chunk_retain_period: 1m
          max_transfer_retries: 5
          wal:
            enabled: false

        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h

        schema_config:
          configs:
            - from: 2020-09-07
              store: boltdb-shipper
              object_store: s3
              schema: v11
              index:
                prefix: loki_index_ 
                period: 24h

        storage_config:
          boltdb_shipper:
            shared_store: s3
            active_index_directory: /var/loki/index
            cache_location: /var/loki/cache
          aws:
            bucketnames: tfnsl-services-application-logs-ap-south-1
            region: ap-south-1
            sse_encryption: true
            sse:
              type: SSE-KMS
              kms_key_id: arn:aws:kms:ap-south-1:832807087073:key/a5169c54-c5ab-4c58-aac1-78d66a221c7f

        chunk_store_config:
          max_look_back_period: 0s

        table_manager:
          retention_deletes_enabled: true
          retention_period: 48h

        query_range:
          align_queries_with_step: true
          max_retries: 5
          split_queries_by_interval: 15m
          cache_results: true
          results_cache:
            cache:
              enable_fifocache: true
              fifocache:
                max_size_items: 1024
                validity: 24h

        frontend_worker:
          frontend_address: loki-query-frontend:9095
          grpc_client_config:
            max_recv_msg_size: 20971520
            max_send_msg_size: 20971520
        frontend:
          log_queries_longer_than: 5s
          compress_responses: true

        compactor:
          # working_directory: /loki/compactor
          shared_store: s3
          compaction_interval: 15m
          retention_enabled: true

        ruler:
          storage:
            type: local
            local:
              directory: /etc/loki/rules
          #storage:
          #  type: s3
          #  s3:
          #    bucketnames: tfnsl-cortex-ruler-ap-south-1
          #    endpoint: s3.dualstack.ap-south-1.amazonaws.com
          #    region: ap-south-1
          #    sse_encryption: true
          #    sse:
          #      type: SSE-KMS
          #      kms_key_id: arn:aws:kms:ap-south-1:832807087073:key/a5169c54-c5ab-4c58-aac1-78d66a221c7f
          ring:
            kvstore:
              store: memberlist
          rule_path: /tmp/loki/scratch
          alertmanager_url: http://cortex-alertmanager.monitoring.svc.cluster.local/api/prom/alertmanager
          enable_alertmanager_v2: false
          enable_api: true
          enable_sharding: true
          remote_write:
            enabled: true
            client:
              url: http://cortex-distributor.monitoring.svc.cluster.local/api/v1/push
              headers:
                x-scope-orgid: 755502957828

    serviceAccount:
      create: false
      name: loki
    serviceMonitor:
      enabled: true
      labels:
        app: loki
        release: kube-prometheus-stack
    prometheusRule:
      enabled: true
      groups:
        - name: loki-rules
          rules:
            - record: job:loki_request_duration_seconds_bucket:sum_rate
              expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job)
            - record: job_route:loki_request_duration_seconds_bucket:sum_rate
              expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job, route)
            - record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
              expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (node, namespace, pod, container)

    compactor:
      enabled: true
      nodeSelector:
        workload: monitoring
      tolerations:
        - key: monitoring
          operator: Exists
      persistence:
        enabled: true
        size: 30Gi
        storageClass: ebs-sc
      resources:
        limits:
          cpu: 1100m
          memory: 2Gi
        requests:
          cpu: 900m
          memory: 1Gi

    distributor:
      replicas: 3
      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 5
        targetCPUUtilizationPercentage: 80
      nodeSelector:
        workload: monitoring
      tolerations:
        - key: monitoring
          operator: Exists
      resources:
        limits:
          memory: 4Gi
        requests:
          cpu: 1800m
          memory: 2Gi

    gateway:
      enabled: false

    indexGateway:
      enabled: true
      replicas: 2
      nodeSelector:
        workload: monitoring
      tolerations:
        - key: monitoring
          operator: Exists
      persistence:
        enabled: true
        size: 30Gi
        storageClass: ebs-sc
      resources:
        limits:
          memory: 6Gi
        requests:
          cpu: 900m
          memory: 2Gi

    ingester:
      replicas: 3
      nodeSelector:
        workload: monitoring
      tolerations:
        - key: monitoring
          operator: Exists
      persistence:
        enabled: true
        size: 30Gi
        storageClass: ebs-sc
      resources:
        limits:
          memory: 12Gi
        requests:
          cpu: 1000m
          memory: 12Gi

    querier:
      replicas: 1
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 80
      nodeSelector:
        workload: monitoring
      tolerations:
        - key: monitoring
          operator: Exists
    queryFrontend:
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 80
      nodeSelector:
        workload: monitoring
      tolerations:
        - key: monitoring
          operator: Exists

    ruler:
      enabled: true
      replicas: 1
      nodeSelector:
        workload: monitoring
      tolerations:
        - key: monitoring
          operator: Exists
      resources:
        limits:
          memory: 4Gi
        requests:
          cpu: 900m
          memory: 2Gi
      extraVolumeMounts:
        - mountPath: /etc/loki/rules/755502957828
          name: dev-rules
          # subPath: rules.yaml
        - mountPath: /etc/loki/rules/901688089596
          name: prod-rules
          # subPath: rules.yaml
      extraVolumes:
        - name: dev-rules
          configMap:
            name: dev-rules
            optional: true
        - name: prod-rules
          configMap:
            name: prod-rules
            optional: true
      #directories:
      #  "755502957828":
      #      rules1.yaml: |
      #        dummy-file
      #  "901688089596":
      #      rules1.yaml: |
      #        dummy-file
    tableManager:
      enabled: false
    memcachedExporter:
      enabled: false
    memcachedChunks:
      enabled: false
    memcachedFrontend:
      enabled: false
    memcachedIndexQueries:
      enabled: false
    memcachedIndexWrites:
      enabled: false
  postRenderers:
    - kustomize:
        patchesJson6902:
          - patch:
              - op: add
                path: /metadata/annotations
                value:
                  alb.ingress.kubernetes.io/healthcheck-path: "/ready"
                  alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=3600,deregistration_delay.timeout_seconds=10
            target:
              name: loki-querier
              kind: Service
          - patch:
              - op: add
                path: /metadata/annotations
                value:
                  alb.ingress.kubernetes.io/healthcheck-path: "/ready"
                  alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=10
            target:
              name: loki-distributor
              kind: Service
          - patch:
              - op: add
                path: /metadata/annotations
                value:
                  alb.ingress.kubernetes.io/healthcheck-path: "/ready"
                  alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=10
            target:
              name: loki-query-frontend
              kind: Service
```

**Comment by mzupan** [comment]
this was my fix

```
querier:
  replicas: 1
  extraVolumes:
    - name: bolt-db
      emptyDir: {}
  extraVolumeMounts:
    - name: bolt-db
      mountPath: /var/loki
```

the distributed chart is really busted
