### ISSUE TITLE
promtail cannot collect all logs generated after it was started

### ISSUE THREAD

**Issue by hookover** [grafana/loki#5097]
event:
os 
```
MacBook Pro (13-inch, M1, 2020)
macOS 12.0.1 (21A559)
```

```
➜  ~ docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:53:48 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

docker-compose.yaml
```
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.0
    ports:
      - "3100:3100"
    volumes:
      - /opt/docker/loki:/mnt/config
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - loki

  promtail:
    ports:
      - "9080:9080"
    image: grafana/promtail:2.4.0
    volumes:
      - /opt/docker/loki:/mnt/config
      - /Users/chenjiang/Documents/golang:/mnt/work
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki
      - 
```

![image](https://user-images.githubusercontent.com/9047209/148916641-30f89ccd-ba13-4c2c-9142-4b3e6d381a03.png)

The logs will not be collected until after the reboot
![image](https://user-images.githubusercontent.com/9047209/148917270-fa111924-d4a2-46c3-b799-860156e846da.png)
