### ISSUE TITLE
loki query a dynamodb table that doesnt exist

### ISSUE THREAD

**Issue by ofiry-tm** [grafana/loki#5112]
**Describe the bug**
loki query a dynamodb table that doesnt exist, and get `ResourceNotFoundException`

**Expected behavior**
I would expect loki to query only existing dynamodb tables

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Loki logs and config**
loki logs:
```
level=error ts=2022-01-12T10:16:02.401498869Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="QueryPages error: table=grafana_loki_index_2714: ResourceNotFoundException: Requested resource not found"
level=error ts=2022-01-12T10:16:02.402853706Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="rpc error: code = Code(500) desc = QueryPages error: table=grafana_loki_index_2714: ResourceNotFoundException: Requested resource not found\n"
```
`grafana_loki_index_2714` table dosent exist.

loki config:
```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 168h
compactor:
  shared_store: filesystem
  working_directory: /data/loki/boltdb-shipper-compactor
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
  wal:
    dir: /data/loki/wal
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
  - from: "2020-10-24"
    index:
      period: 168h
      prefix: grafana_loki_index_
    object_store: s3
    schema: v11
    store: aws
server:
  http_listen_port: 3100
storage_config:
  aws:
    dynamodb:
      dynamodb_url: dynamodb://<my-region>
    s3: s3://<my-region>/<my-bucket>
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: true

```
