### ISSUE TITLE
Grafana Loki Does not retrieve older logs

### ISSUE THREAD

**Issue by fayas-akram** [grafana/loki#5114]
***Grafana Loki Does not retrieve older logs***
I have configured Loki with 4h retention period and 1h Delete Delay. With that configuration, I can only retrieve or view logs for 2 hours.
Not sure why I can retrieve it for at least 3 hours logs.

Please find the attached image for the issue

![image](https://user-images.githubusercontent.com/88644766/149146618-23f6f555-8dd4-4fa5-bf30-fd102ca60df8.png)

**my configuration as follows**

```
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: s3

  aws:
    s3: s3://us-east-1/my-test-bucket
    s3forcepathstyle: true

compactor:
  working_directory: /loki/compactor
  shared_store: s3
  compaction_interval: 5m
  retention_enabled: true
  retention_delete_delay: 1h
  retention_delete_worker_count: 150

limits_config:
  retention_period: 24h
  reject_old_samples: true
  reject_old_samples_max_age: 2h
```
