### ISSUE TITLE
Ruler Remote Write: Configured password for basic auth gets ignored

### ISSUE THREAD

**Issue by kingjan1999** [grafana/loki#5140]
**Describe the bug**

When configuring `basic_auth` credentials for the remote write ruler client, the configured `password` gets ignored and always `<secret>` gets passed as password to Prometheus.

**To Reproduce**
1. Start Loki (bf9eb33385760f2395ec7f4dfef9a577b628f023, also happens on 2.4.1)
2. Start Prometheus v2.32.1 or any other HTTP server (e.g. RequestBin) where you can watch the HTTP requests
3. Configure Loki as shown below 

Using the config from below, the `Authorization` header will be set to `Basic YWRtaW46PHNlY3JldD4=`, i.e. `admin:<secret>`

**Expected behavior**

The configured password gets passed to Prometheus / Thanos / Cortex / whatever remote storage backend. In the example, the `Authorization` header should be `Basic YWRtaW46dGVzdA==` (`admin:test`).

**Environment:**
 - Infrastructure: Docker @ Ubuntu 20.04
 - Deployment tool: N/A

**Screenshots, Promtail config, or terminal output**

<details>
<summary>
Loki Config
</summary>

```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
  remote_write:
    enabled: true
    client:
      url: http://localhost:9090/api/v1/write
      basic_auth:
        username: admin
        password: test
```
</details>

<details>
<summary>
Rule config (any will do, this is taken from the example docs):
</summary>

```yaml
groups:
    - name: NginxRules
      interval: 1m
      rules:
        - record: nginx:requests:rate1m
          expr: sum(rate({container="nginx"}[1h]))
          labels:
            cluster: us-central1
```
</details>
