### ISSUE TITLE
Disassociate storage type from it's ID

### ISSUE THREAD

**Issue by splitice** [grafana/loki#5152]
**Is your feature request related to a problem? Please describe.**
Yes, updating S3 buckets to use round robin buckets or any other structure is currently not possible without a total cluster swap.

**Describe the solution you'd like**
```
    storage_config:
      backends:
       - old_s3:
            s3:
              bucketnames: old-s3
              endpoint: ${S3_ENDPOINT}
              region: ${S3_REGION}
              access_key_id: ${S3_ACCESSKEY}
              secret_access_key: ${S3_SECRETKEY}
       - new_s3:
            s3:
              bucketnames: new-s3
              endpoint: ${S3_ENDPOINT}
              region: ${S3_REGION}
              access_key_id: ${S3_ACCESSKEY}
              secret_access_key: ${S3_SECRETKEY}
         [..,]
```

old_s3 and new_s3 then can be referered to in period_config
