### ISSUE TITLE
Cloudflare logs stop streaming in

### ISSUE THREAD

**Issue by james-callahan** [grafana/loki#5157]
**Describe the bug**
We use the new promtail Cloudflare support, however after some period of time, logs stop getting processed.

The last log message before it stops collecting logs seems to be:
`level=error ts=2022-01-05T10:03:53.538560165Z caller=target.go:119 target=cloudflare msg="failed to pull logs" err="read tcp 10.28.62.117:39766->104.19.192.29:443: read: connection reset by peer" start=2022-01-05T10:00:14.410784874Z end=2022-01-05T10:01:14.410784874Z`

![image](https://user-images.githubusercontent.com/35791147/149729955-14d29da0-b195-4417-8df8-fded12717c1e.png)
![image](https://user-images.githubusercontent.com/35791147/149729969-9cf23000-9599-4410-b327-f845faef90af.png)

**To Reproduce**
1. Started Promtail `main-96ee4a2` to tail cloudflare
2. Wait... eventually logs stop streaming in. Promtail does *not* exit or get restarted.

**Expected behavior**
Cloudflare logs should keep streaming. If there is a network problem for whatever reason, it should retry.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: kustomize

**Screenshots, Promtail config, or terminal output**
promtail config:
```yaml
server:
  http_listen_port: 3101

positions:
  filename: /var/spool/promtail/positions.yaml

scrape_configs:
- job_name: cloudflare_promtail
  cloudflare:
    api_token: ${CF_API_TOKEN}
    zone_id: ${CF_ZONE_ID}
    labels:
      job: cloudflare
      cloudflare_zone_id: ${CF_ZONE_ID}
```

[slack thread](https://grafana.slack.com/archives/CEPJRLQNL/p1641521958031600)
