### ISSUE TITLE
Is this Acceptable Configuration on on-premise enviorment with cassandra?

### ISSUE THREAD

**Issue by tr2vil** [grafana/loki#5166]
You may submit questions in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**NOTE: All questions submitted as issues will be closed.**

Hi. I want to deploy loki 3 Node on-premise. 
In QA environment , I planed like this.

```
  Grafana
 Loki-Read         Loki-Write       Loki-Write
 Cassandra        Cassandra       Cassandra
  Consul              Consul             Consul
[Server 1]          [Server 2]         [Server 3]
```

In such environment, Externel Log writer (like promtail or td-agent)  write logs to the Loki-write through Load balancer  or dnsRR. Loki-write which received logs will store in the cassandra. 
Anyone who want to see the logs can see on  grafana on Server 1. 

I have problem storing logs from Loki-write to cassandra. so, I have wonder this structure is right way.
Cassandra have loki keyspace. but Any table is not generate by loki. 
loki generate log like this 
```
{"caller":"logging.go:67","level":"debug","msg":"POST /loki/api/v1/push (204) 1.348687ms","orgID":"fake","traceID":"4edd698b4830ff99","ts":"2022-01-18T00:59:01.83376993Z"}
```

My configuration in Loki-write 

```
target: write

distributor:
  ring:
    kvstore:
      store: consul
      consul:
        host: {server-1}:8500

ingester:
  lifecycler:
    address: 192.168.0.208
    ring:
      kvstore:
        store: consul
        consul:
          host: {server-1}:8500
      replication_factor: 2
    final_sleep: 0s
    interface_names:
      - "eth0"
  chunk_idle_period: 1m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2022-01-17
    store: cassandra
    object_store: cassandra
    schema: v11
    index:
      prefix: loki_index_
      period: 360h
    chunks:
      prefix: chunk
      period: 360h

storage_config:
  cassandra:
    addresses: 192.168.0.206, 192.168.0.207, 192.168.0.208
    replication_factor: 2
    auth: true
    username: cassandra
    password: cassandra
    keyspace: loki
    timeout: 10s
    connect_timeout: 10s

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h
  creation_grace_period: 10m
```

Please let me know about loki best way clustered structure not using public cloud storage like S3.
