### ISSUE TITLE
Loki Query error disk quota exceeded

### ISSUE THREAD

**Issue by hairongGao** [grafana/loki#5167]
**Describe the bug**
loki logql return error “Query error disk quota exceeded”

**To Reproduce**
1. Started Loki (SHA or version) 
  app.kubernetes.io/version=2.4.2
2. Started Promtail (SHA or version) to tail '...' 
  promtail:2.4.2
3. Query: `{} term`

**Expected behavior**
query can succesfuully return with result

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop] 
 - Kubernetes
 - Deployment tool: [e.g., helm, jsonnet]
 - helm （loki-scalable）

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
```
level=error ts=2022-01-18T02:31:50.306590057Z caller=table.go:184 msg="failed to initialize table loki_index_19010, cleaning it up" err="disk quota exceeded"
level=error ts=2022-01-18T02:31:50.3066141Z caller=table.go:94 msg="failed to download table" name=loki_index_19010
level=error ts=2022-01-18T02:31:50.30664272Z caller=table_manager.go:159 msg="table loki_index_19010 has some problem, cleaning it up" err="disk quota exceeded"
level=error ts=2022-01-18T02:31:50.306678744Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="disk quota exceeded"
level=error ts=2022-01-18T02:31:50.306715686Z caller=table_manager.go:159 msg="table loki_index_19010 has some problem, cleaning it up" err="disk quota exceeded"
level=error ts=2022-01-18T02:31:50.306744689Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="disk quota exceeded"
level=info ts=2022-01-18T02:31:50.306813244Z caller=metrics.go:92 org_id=fake latency=fast query="sum(count_over_time({namespace=\"default\", instance=~\".*\"} |~ \"level=warn\"[1s]))" query_type=metric range_type=range length=28m14s step=1s duration=91.756902ms status=500 limit=1687 returned_lines=0 throughput=0B total_bytes=0B
level=info ts=2022-01-18T02:31:50.306825891Z caller=metrics.go:92 org_id=fake latency=fast query="sum(count_over_time({namespace=\"default\", instance=~\".*\"} |~ \"level=warn\"[1s]))" query_type=metric range_type=range length=28m14s step=1s duration=91.738285ms status=500 limit=1687 returned_lines=0 throughput=0B total_bytes=0B
level=error ts=2022-01-18T02:31:50.326780703Z caller=table.go:184 msg="failed to initialize table loki_index_19010, cleaning it up" err="disk quota exceeded"
level=error ts=2022-01-18T02:31:50.326802174Z caller=table.go:94 msg="failed to download table" name=loki_index_19010
level=error ts=2022-01-18T02:31:50.32682331Z caller=table_manager.go:159 msg="table loki_index_19010 has some problem, cleaning it up" err="disk quota exceeded"
level=error ts=2022-01-18T02:31:50.326872387Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="disk quota exceeded"
level=error ts=2022-01-18T02:31:50.326909557Z caller=table_manager.go:159 msg="table loki_index_19010 has some problem, cleaning it up" err="disk quota exceeded"
level=error ts=2022-01-18T02:31:50.326934592Z caller=chunk_store.go:524 org_id=fake msg="error querying storage" err="disk quota exceeded"
level=info ts=2022-01-18T02:31:50.327023513Z caller=metrics.go:92 org_id=fake latency=fast query="sum(count_over_time({namespace=\"default\", instance=~\".*\"} |~ \"level=warn\"[1s]))" query_type=metric range_type=range length=28m14s step=1s duration=91.098805ms status=500 limit=1687 returned_lines=0 throughput=0B total_bytes=0B
level=info ts=2022-01-18T02:31:50.327025227Z caller=metrics.go:92 org_id=fake latency=fast query="sum(count_over_time({namespace=\"default\", instance=~\".*\"} |~ \"level=warn\"[1s]))" query_type=metric range_type=range length=28m14s step=1s duration=91.437603ms status=500 limit=1687 returned_lines=0 throughput=0B total_bytes=0B
level=info ts=2022-01-18T02:33:22.523341452Z caller=table_manager.go:207 msg="syncing tables"
level=info ts=2022-01-18T02:33:22.56521141Z caller=table.go:432 msg="downloading object from storage with key loki-write-0-1642080502479627558-1642421700.gz"
level=info ts=2022-01-18T02:33:22.600501874Z caller=util.go:109 msg="downloaded file loki-write-0-1642080502479627558-1642421700.gz from table loki_index_19009"
level=error ts=2022-01-18T02:33:22.620116375Z caller=table_manager.go:101 msg="error syncing local boltdb files with storage" err="disk quota exceeded"
```

loki configmap
```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 672h
common:
  path_prefix: /var/loki
  replication_factor: 1
  ring:
    kvstore:
      store: memberlist
  storage:
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: 20
  ingestion_rate_mb: 15
  max_cache_freshness_per_query: 10m
  reject_old_samples: true
  reject_old_samples_max_age: 168h
memberlist:
  join_members:
  - 'loki-memberlist'
schema_config:
  configs:
  - from: "2021-12-24"
    index:
      period: 24h
      prefix: loki_index_
    object_store: s3
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
storage_config:
  aws:
    bucketnames: xxx
    insecure: true
    s3: xxx
    s3forcepathstyle: true
table_manager:
  retention_deletes_enabled: true
  retention_period: 672h

```
