### ISSUE TITLE
Old data is missing when adding additional s3 buckets

### ISSUE THREAD

**Issue by ilovemysillybanana** [grafana/loki#5175]
**Describe the bug**
Adding multiple AWS S3 buckets after originally having one bucket, makes it so that the old data is inaccessible. 

**To Reproduce**
1.) Using loki 2.4.2 with the distributed helm chart with only one bucket:
```yaml
schema_config:
  configs:
    - from: 2017-01-01
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  index_cache_validity: 1h
  max_chunk_batch_size: 5000
  aws:
    s3: s3://us-east-1
    region: "us-east-1"
    bucketnames: <bucket_name1>
  boltdb_shipper:
    shared_store: s3
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
  index_queries_cache_config:
    default_validity: 168h
    enable_fifocache: false
    memcached:
      batch_size: 50
      parallelism: 50
      expiration: 168h
    memcached_client:
      consistent_hash: true
      host: loki-distributed-memcached-index-queries
      service: http
      timeout: 10s
```
2.) Push some data.

3.) Now restart loki with additional buckets:
```yaml
storage_config:
  index_cache_validity: 1h
  max_chunk_batch_size: 5000
  aws:
    s3: s3://us-east-1
    region: "us-east-1"
    bucketnames: <bucket_name1>,<bucket_name2>,<bucket_name3>,<bucket_name4>,<bucket_name5>,<bucket_name6>
```

4.) Now try to pull data from loki from before when you made the above change and you'll get a `502`.

```yaml
message: "Query error: 502"
```

**Expected behavior**
I would expect the old data to be in there already and new data to be distributed between all the buckets going forward. I believe what happens instead is that a new index is created that doesn't account for the previous data. 

**Environment:**
 - Infrastructure:
   - cloud provider: aws
   - kubernetes version: `1.18`
   - platform version:`eks.8`
   - loki version: `2.4.2`
 - Deployment tool: 
   - helm chart version: `0.39.3`

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
