### ISSUE TITLE
labels.job template variable is not being properly replace in Loki alerts

### ISSUE THREAD

**Issue by hugree** [grafana/loki#5176]
**Describe the bug**
The following alert configuration using template variables `{{ $labels.job }}` and `{{ .Value }}`. 

The `{{ .Value }}` works fine.

But the labels are not showing in the alert.

```
loki-rules:
    - name: xxx
      rules:
        - alert: XXX
          expr: (sum by(container)(rate({app="loki"}[1m])) > 10)
          for: 1m
          labels:
            job: loki
            severity: critical
          annotations:
            description: '{{ $labels.job }} is generating lots of logs. Value is {{ .Value }}'
            message: There are a lot of loki logs
            summary: Loki logs volume alert {{ .Value }}
```

**To Reproduce**
1. Started Loki - 2.4.2
2. Started Promtail (SHA or version) to tail '...'-  2.4.2

**Expected behavior**
The labels variable is properly replaces with a proper value

**Environment:**
 - Infrastructure: Kubernetes 
 - Deployment tool: Helm
