### ISSUE TITLE
Ring instance addresses are all the same running 3 single-binaries in docker

### ISSUE THREAD

**Issue by trevorwhitney** [grafana/loki#5206]
**Describe the bug**
When running 3 single binaries in a docker compose setup, using memberlist for the ingester ring and replication factor of 3, all 3 instances report an address of `127.0.0.1:9095`. As a result, when iterating for the replica set in the distributor, 3 requests are sent to localhost rather than being distributed across other nodes as expected.

**To Reproduce**
1. Start Loki in docker compose with the following config
```yaml
  loki:
    image: grafana/loki:2.4.2
    command:
      - -memberlist.join=loki:7946
      - -ring.store=memberlist
      - -distributor.replication-factor=3
      - -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100
      - 9095
    deploy: &replicated
      mode: replicated
      replicas: 3
    networks: &loki-dns
      default:
        aliases:
          - loki
```

2. Go to the `/ring` endpoint
3. See 3 instances all with address `127.0.0.1:9095`

**Expected behavior**
I would expect each instance in the ring to have a unique IP address that is accessible from all the other instances in the ring.

**Environment:**
 - Docker compose

**Screenshots, Promtail config, or terminal output**
![Screenshot from 2022-01-21 11-29-50](https://user-images.githubusercontent.com/469592/150581980-14281fcd-9eaa-4769-9e75-fbb6297b2004.png)
