### ISSUE TITLE
Only logs with specific labels are returned when using official Docker containers (Loki, Promtail)

### ISSUE THREAD

**Issue by monsdar** [grafana/loki#5208]
Somehow when querying Loki for logs in the past I'm not getting all the logs returned. I was able to repro this in a small repro case and I'm wondering if there's something obvious I'm missing.

The repro is as follows:

test.log:
```
[2021-12-11 06:00:00 INFORMATION] 06:00 INFORMATION INFORMATION INFORMATION INFORMATION
[2021-12-11 06:00:00 WARNING] 06:00 WARNING WARNING WARNING WARNING
[2021-12-11 07:00:00 FATAL] 07:00 FATAL FATAL FATAL FATAL
[2021-12-11 07:00:00 INFORMATION] 07:00 INFORMATION INFORMATION INFORMATION INFORMATION
[2021-12-11 08:00:00 WARNING] 08:00 WARNING WARNING WARNING WARNING
[2021-12-11 08:00:00 INFORMATION] 08:00 INFORMATION INFORMATION INFORMATION INFORMATION
[2021-12-11 09:00:00 WARN] 09:00 WARN WARN WARN WARN
[2021-12-11 09:00:00 INFO] 09:00 INFO INFO INFO INFO
[2021-12-11 10:00:00 WARNING] 10:00 WARNING WARNING WARNING WARNING
[2021-12-11 10:00:00 INFORMATION] 10:00 INFORMATION INFORMATION INFORMATION INFORMATION
```

promtail.yaml:
```
server:
  log_level: info
  http_listen_port: 3101
   
client:
  url: http://loki:3100/loki/api/v1/push
    
positions:
  filename: "/etc/promtail/positions.yaml"
    
scrape_configs:
  - job_name: TestLog
    pipeline_stages:
    - regex:
        expression: '^\[(?P<timestamp>\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d) (?P<level>.*)\] (?P<content>.*)'
    - timestamp:
        source: timestamp
        format: "2006-01-02 15:04:05"
    - output:
        source: content
    - labels:
        level:
    static_configs:
    - labels:
        job: TestLog
        __path__: /etc/promtail/test.log
```

docker-compose.yaml:
```
version: '3.4'

services:
  loki:
    container_name: loki
    image: grafana/loki:2.4.2
    restart: always
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -validation.reject-old-samples=false
      - -store.max-query-length=0
  promtail:
    container_name: promtail
    image: grafana/promtail:2.4.2
    restart: always
    depends_on:
      - loki
    command:
      - --inspect
      - -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail.yaml:/etc/promtail/config.yml
      - ./test.log:/etc/promtail/test.log
  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.4
    restart: always
    depends_on:
      - loki
    ports:
      - "3000:3000"
```

How to reproduce:
* The test has been done on 2022-01-21, with the logs happening on 2021-12-11, as seen above. Any logs older than a few hours should work though.
* Start the given docker-compose environment with `docker-compose up -d`
* Connect to Grafana, Log in with admin/admin and add http://loki:3100 as a datasource
* Wait a bit for Promtail to push the logs into Loki and get them indexed
* Within Grafana Inspect check the logs
* Set the range of Grafana to 90 days to make sure the logs are included within the results

Actual behaviour:
* Grafana only shows the log lines that have level=WARNING, all other logs are missing. Screenshot shows the result:
![image](https://user-images.githubusercontent.com/4217216/150600244-875b3f38-38ba-44a2-995b-6954eee5ebb3.png)

Expected:
* Grafana shows all log lines, not only lines with level WARNING

Further observations:
While creating this repro case I tested a number of things and found that everything is going well as long as the log lines aren't older than ~1 hour. Within this timespan all loglevels are shown. As soon as logs get older the lines are going missing. This can also be emulated when advancing the system time where Loki runs... as soon as log entries get to a certain age they get dropped from the query results. I guess that the cause of this issue has something to do with the storage configuration, but I'm basing this only on the experience I've gained over the last days. I haven't worked with Loki much before. I wasn't able to find some configuration that'll handle this in a better way.

**Comment by jeschkies** [comment]
I believe the default [retention period](https://grafana.com/docs/loki/latest/operations/storage/retention/) is thirty days. Could you try with a different config.

Also, it's good to avoid `.*` in the regular expression and use `\w+` instead.

**Comment by monsdar** [comment]
The problem exists with a time diff within the retention period as well. In fact it also happens when pushing current log lines and waiting for >1hr.

**Comment by monsdar** [comment]
I tested once again, made slight changes to the above repro:
* I tested this on 2022-01-25 20:51 GMT+1 (so right after the logs I'm feeding happened)
* Reduced the config-parameters for loki, it's only default settings now
* Regex is using `\w+` instead of `.*` now

test.log:

```
[2022-01-25 16:00:00 INFORMATION] 16:00 INFORMATION INFORMATION INFORMATION INFORMATION
[2022-01-25 16:00:00 WARNING] 16:00 WARNING WARNING WARNING WARNING
[2022-01-25 17:00:00 INFORMATION] 17:00 INFORMATION INFORMATION INFORMATION INFORMATION
[2022-01-25 17:00:00 WARNING] 17:00 WARNING WARNING WARNING WARNING
[2022-01-25 18:00:00 INFORMATION] 18:00 INFORMATION INFORMATION INFORMATION INFORMATION
[2022-01-25 18:00:00 WARNING] 18:00 WARNING WARNING WARNING WARNING
[2022-01-25 19:00:00 INFORMATION] 19:00 INFORMATION INFORMATION INFORMATION INFORMATION
[2022-01-25 19:00:00 WARNING] 19:00 WARNING WARNING WARNING WARNING
```

docker-compose.yml:

```
version: '3.4'

services:
  loki:
    container_name: loki
    image: thirdparty.central.defence-elec.de/docker-remote/grafana/loki:2.4.2
    restart: always
    command:
      - -config.file=/etc/loki/local-config.yaml
  promtail:
    container_name: promtail
    image: thirdparty.central.defence-elec.de/docker-remote/grafana/promtail:2.4.2
    restart: always
    depends_on:
      - loki
    command:
      - --inspect
      - -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail.yaml:/etc/promtail/config.yml
      - ./test.log:/etc/promtail/test.log
  grafana:
    container_name: grafana
    image: thirdparty.central.defence-elec.de/docker-remote/grafana/grafana:8.3.4
    restart: always
    depends_on:
      - loki
    ports:
      - "3000:3000"
```

promtail.yaml:

```
server:
  log_level: info
  http_listen_port: 3101
   
client:
  url: http://loki:3100/loki/api/v1/push
    
positions:
  filename: "/etc/promtail/positions.yaml"
    
scrape_configs:
  - job_name: TestLog
    pipeline_stages:
    - regex:
        expression: '^\[(?P<timestamp>\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d) (?P<level>\w+)\] (?P<content>[\w\W]+)'
    - timestamp:
        source: timestamp
        format: "2006-01-02 15:04:05"
    - output:
        source: content
    - labels:
        level:
    static_configs:
    - labels:
        job: TestLog
        __path__: /etc/promtail/test.log
```

You can simply reproduce this by putting all the above files in a directory and starting it up with `docker-compose up -d`. Then go to Grafana, set up the data source (`http://loki:3100`) and use the Inspector to query.

The result looks like the following on my end:
![image](https://user-images.githubusercontent.com/4217216/151049710-b7ec6856-6aa3-4514-bd62-ba1650d352df.png)

Observations:
* Loki is not returning all the log-lines it got fed
  * Older log lines are missing, only showing ones with INFORMATION-level
  * Entry for `18:00` looks good, only one showing the WARNING-line
  * For some reason the most recent entry is not showing as well. This is different to what I observed before, where only older log-lines were missing
* There is a mix-up within the timestamps shown. I guess this has to do with my environment being GMT+1.
* The format of the Regex does not have something to do with this issue. Logs are parsed as expected (check promtail output for more info)

I am worried a bit. This happens with Loki default settings and nobody ever noticed? I hope it's some quirk in my setup, but I'm not sure where to look anymore. Can somebody please check if it's reproducable on their end as well?
