### ISSUE TITLE
operator: Add support for ruler component

### ISSUE THREAD

**Issue by eranra** [grafana/loki#5211]
Loki stack includes a new GA'ed component called Ruler. The `Ruler` component marriage metrics with logs closing the gap for customers to achieve a real **consolidated observability** solution. The Ruler component is responsible for continually evaluating a set of configurable queries and performing actions based on the result.  There are two key types of rules that the `Ruler` component  supports  [Alerting Rules](https://grafana.com/docs/loki/latest/rules/#alerting-rules) and [Recording Rules](https://grafana.com/docs/loki/latest/rules/#recording-rules) 

Note: In addition to the direct business value, this PR also aligns Loki Operator functionality with Loki Helm functionality. Loki Helm already provides the ability to deploy the `Ruler` component [here](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed/templates/ruler)

With this new feature, customers will be able to selectively deploy Loki  `Ruler` component as part of LokiStack operator deployments and be able to define a set of rules and any additional `Ruler` configuration needed for the `Ruler` component to function as described in the `Ruler` API documentation [here](https://grafana.com/docs/loki/latest/configuration/#ruler_config).

As an alternative customers can use helm charts and not use Loki operator when the `Ruler` component is required.

Customer-facing API:

It is suggested that the Operator configuration for the `Ruler` component will be common to the configuration used by other deployments such as the Helm charts. This includes a config-map that will be created by customers. The config-map points to a yaml file holding the `Ruler` rules. This is the same approach used by the Helm chart solution [here](production/helm/loki/templates/configmap-alert.yaml)

Example for  such `ruler_rules.yaml` file::

```
groups:
  - name: PlatformRules
    interval: 1m
    rules:
    - record: logs:openshift:platform:rate1m
      expr: |
        sum(rate({namespace=~"openshift+"}[1m]))
      labels:
        metric: "rate"
        source: "logs"
```
