### ISSUE TITLE
Oidc and serviceaccount auth failed in loki

### ISSUE THREAD

**Issue by hairongGao** [grafana/loki#5214]
**Describe the bug**
Get the below errors when trying to run query in console
```
Query error
WebIdentityErr: failed to retrieve credentials caused by: RequestError: send request failed caused by: Post "http://sts.cn-northwest-1.amazonaws.com.cn/": dial tcp 52.82.208.217:80: connect: connection refused 
```
**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - kubernetes
 - Deployment tool: [e.g., helm, jsonnet]
 - helm
 - loki-distributed-0.40.0
 - promtail-3.10.0

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

loki config snippet
```
serviceAccount:
  create: true
  name: loki-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws-cn:iam::ACCOUNT_NUMBER:role/AmazonEKS_LOKI_ROLE
```
