### ISSUE TITLE
Journal Scraping received error during sdjournal follow "Timeout expired"

### ISSUE THREAD

**Issue by gmintoco** [grafana/loki#5215]
**Describe the bug**
I am running promtail within Kubernetes (on GKE) attempting to scrape the nodes journal from the promtail pod. I have mounted the /var/log/journal and /etc/machine-id from the node into the pod.

When I attempt to start Promtail the instance hangs while starting:
```
root@loki-global-test-promtail-d5rkm:/# promtail --config.file test.yaml -client.url=http://127.0.0.1:10000/loki/api/v1/push --log.level=debug
level=info ts=2022-01-24T04:36:32.910856362Z caller=server.go:260 http=[::]:3102 grpc=[::]:9096 msg="server listening on addresses"
level=info ts=2022-01-24T04:36:32.911183129Z caller=main.go:119 msg="Starting Promtail" version="(version=2.4.2, branch=HEAD, revision=525040a32)"
```

I receive the error upon force stopping the instance:

```
root@loki-global-test-promtail-d5rkm:/# promtail --config.file test.yaml -client.url=http://127.0.0.1:10000/loki/api/v1/push --log.level=debug
level=info ts=2022-01-24T04:36:32.910856362Z caller=server.go:260 http=[::]:3102 grpc=[::]:9096 msg="server listening on addresses"
level=info ts=2022-01-24T04:36:32.911183129Z caller=main.go:119 msg="Starting Promtail" version="(version=2.4.2, branch=HEAD, revision=525040a32)"
^Clevel=info ts=2022-01-24T04:39:20.736675976Z caller=signals.go:55 msg="=== received SIGINT/SIGTERM ===\n*** exiting"
level=error ts=2022-01-24T04:39:20.750683332Z caller=journaltarget.go:187 msg="received error during sdjournal follow" err="Timeout expired"
level=error ts=2022-01-24T04:39:20.750756138Z caller=journaltarget.go:190 msg="unable to follow journal" err="Timeout expired"
level=debug ts=2022-01-24T04:39:20.766132649Z caller=positions.go:147 msg="positions saved"
```

Config:
```yaml
client:
  # Maximum wait period before sending batch
  batchwait: 1s
  # Maximum batch size to accrue before sending, unit is byte
  batchsize: 1048576

  # Maximum time to wait for server to respond to a request
  timeout: 10s

  backoff_config:
    # Initial backoff time between retries
    min_period: 500ms
    # Maximum backoff time between retries
    max_period: 5m
    # Maximum number of retries when sending batches, 0 means infinite retries
    max_retries: 10

server:
  http_listen_port: 3102
  grpc_listen_port: 9096

positions:
  filename: /run/promtail/positions.yaml
target_config:
  # Period to resync directories being watched and files being tailed
  sync_period: 10s
scrape_configs:
  - job_name: node-journal
    journal:
      json: true
      path: /var/log/journal
```

**To Reproduce**
1. Loki 2.4.2
2. Started Promtail within docker container 2.4.2 mounted /var/log/journal and /etc/machine-id on Google COS+containerd K8S v1.20.11-gke.1300

**Expected behavior**
Journal logs to be successfully scraped and shipped

**Environment:**
 - Infrastructure: Kubernetes GKE v1.20.11-gke.1300 COS + Containerd
 - Terraform

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
