### ISSUE TITLE
Loki Azure File Share Issue - invalid database error creating index client

### ISSUE THREAD

**Issue by akshaya-msd** [grafana/loki#5216]
Hello,

I am using helm to install loki-stack in Azure AKS cluster with Azure File share backed Persistent Volume.

this is my config

 ```
 loki:
    config:
      chunk_store_config:
        max_look_back_period: 168h
      limits_config:
        ingestion_burst_size_mb: 20
        ingestion_rate_mb: 20
      schema_config:
        configs:
        - from: "2022-01-21"
          index:
            period: 24h
            prefix: index_
          object_store: filesystem
          schema: v11
          store: boltdb-shipper
      table_manager:
        retention_deletes_enabled: true
        retention_period: 72h
    enabled: true
    persistence:
      enabled: true
      existingClaim: loki-claim
    enabled: true
```
The Container started and ran fine for a few days and suddenly it started failing and crashloopbackoff.

I am getting the following error from loki pod

```
level=info ts=2022-01-24T04:59:32.190666199Z caller=main.go:130 msg="Starting Loki" version="(version=2.2.0, branch=HEAD, revision=a27c79913)"
level=info ts=2022-01-24T04:59:32.1907356Z caller=modules.go:477 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2022-01-24T04:59:32.191032704Z caller=server.go:229 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2022-01-24T04:59:32.292141643Z caller=table_manager.go:241 msg="loading table index_19012"
level=error ts=2022-01-24T04:59:33.245138Z caller=log.go:106 msg="error running loki" err="invalid database\nerror creating index client\ngithub.com/
cortexproject/cortex/pkg/chunk/storage.NewStore\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/chunk/storage/factory.go:179\ngithub.com/graf
ana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:319\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/
src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:103\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModu
leServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/l
oki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/
local/go/src/runtime/asm_amd64.s:1374\nerror initialising module: store\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/s
rc/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModul
eServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/lo
ki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/l
ocal/go/src/runtime/asm_amd64.s:1374"
```

Any pointers here?

**Comment by ertekki** [comment]
We are facing the same problem, using loki helm charts v2.8.1 and those custom values:

```
loki:
  persistence:
    enabled: true
    accessModes:
    - ReadWriteMany
    storageClassName: azurefile
```

So there is not much customization, but we get the same error from time to time:

> level=info ts=2022-01-28T15:38:05.983740033Z caller=main.go:94 msg="Starting Loki" version="(version=2.4.1, branch=HEAD, revision=f61a4d261)"
level=info ts=2022-01-28T15:38:05.984261466Z caller=modules.go:573 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2022-01-28T15:38:05.984657392Z caller=server.go:260 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=warn ts=2022-01-28T15:38:05.9847865Z caller=experimental.go:19 msg="experimental feature in use" feature="In-memory (FIFO) cache"
level=info ts=2022-01-28T15:38:06.08754159Z caller=table_manager.go:241 msg="loading table index_19015"
level=error ts=2022-01-28T15:38:06.315393602Z caller=log.go:106 msg="error running loki" err="invalid database\nerror creating index client\ngithub.com/grafana/loki/pkg/storage/chunk/storage.NewStore\n\t/src/loki/pkg/storage/chunk/storage/factory.go:201\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:370\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:106\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"

[metrics-loki-0.log](https://github.com/grafana/loki/files/7960075/metrics-loki-0.log)
[metrics-loki-1.log](https://github.com/grafana/loki/files/7960076/metrics-loki-1.log)

The cause might be an outage in Azure in our region, but besides that we don't know what it could be. The only thing we can do in order for it to work again is deleting the file share completely and starting it all over.

**Comment by Chivolta** [comment]
Hi, I have the same problem.

**Comment by thuannguyenn** [comment]
hi, I got the same issue. :(

**Comment by ThomasPelletier** [comment]
I have the same issue

**Comment by thuannguyenn** [comment]
@thorker could you please more details on how we can achieve it?

**Comment by thorker** [comment]
You have to create a new [storageclass](https://docs.microsoft.com/en-us/azure/aks/azure-files-csi#create-nfs-file-share-storage-class), which supports nfs and is linked to your **PREMIUM** Storage Account and then use it in your helm chart.

That's all.

**Comment by Daniel-F-G** [comment]
Another option I've found to workaround this, provided you intend to only ever a single loki instance running, is to use `boltdb` instead of `boltdb-shipper`, e.g.

```
  config:
    ingester:
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
        final_sleep: 0s
    schema_config:
      configs:
      - from: 2022-07-01
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    storage_config:
      boltdb:
        directory: /data/loki/index
  persistence:
    enabled: true
    accessModes:
    - ReadWriteMany
    size: 16Gi
    storageClassName: azurefile
    existingClaim: "azurefile-lokilogs"
```

based on the [comlplete-local-config example](https://grafana.com/docs/loki/latest/configuration/examples/#complete-local-configyaml).
