### ISSUE TITLE
Growing memory usage in loki-read

### ISSUE THREAD

**Issue by twix14** [grafana/loki#5224]
**Describe the bug**
Memory usage grows permanently with regular usage. Similar to #4119 

**To Reproduce**
1. Run simple deployment Loki 2.4.2
2. Push 3k/s logs to Loki
3. Add Loki datasource to Grafana (v8.1.1)
3. Use the explore option in Grafana, with Loki's datasource and query: {pod_name=~"vector-load-tests.*"} (filter will show 3 pod logs)
4. Add query options: last 1h , 1000 line limit, refresh 5s. The memory consumption will stabilise after a while. After some time stop querying and start querying again with the options: last 1h , 100 line limit, refresh 5s.

**Expected behavior**
Memory usage should be in-line with the read throughput or (relatively) stable if the throughput doesn't increase from previous consumption.

**Environment:**
 - Infrastructure: Kubernetes
 - Loki config: 
```yaml
auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  grpc_server_max_recv_msg_size: 52428800
  grpc_server_max_send_msg_size: 52428800

distributor:
  ring:
    kvstore:
      store: memberlist

memberlist:
  bind_port: 7946
  join_members:
    - loki-memberlist

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  chunk_idle_period: 1m
  chunk_block_size: 10485760
  chunk_encoding: snappy
  chunk_retain_period: 0s
  max_chunk_age: 2h
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /var/loki/wal
    replay_memory_ceiling: 1GB

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m
  ingestion_rate_mb: 10

schema_config:
  configs:
    - from: 2021-05-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  boltdb_shipper:
    shared_store: s3
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    cache_ttl: 10m
  aws:
    bucketnames: <bucket_name>
    endpoint: s3.eu-west-1.amazonaws.com
    region: eu-west-1
    access_key_id: <access_key_id>
    secret_access_key: <secret_access_key>
    insecure: false
    sse_encryption: false
    http_config:
      idle_conn_timeout: 90s
      response_header_timeout: 0s
      insecure_skip_verify: false
    s3forcepathstyle: true      

querier:
  engine:
    max_look_back_period: 168h

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

query_range:
  align_queries_with_step: true
  max_retries: 5
  split_queries_by_interval: 15m
  cache_results: false
  results_cache:
    cache:
      enable_fifocache: false
      fifocache:
        max_size_items: 1
        validity: 1m

compactor:
  working_directory: /var/loki/compactor
  shared_store: filesystem

ruler:
  storage:
    type: local
    local:
      directory: /var/loki/ruler
```
 - GOGC=5
 - Log volume: 3k/s (k8s logs <- Vector -> Kafka <- Vector -> Loki)

**Screenshots, Promtail config, or terminal output**
Metrics for the Loki process after running some tests: 
- k8s memory usage
![Screenshot 2022-01-24 at 15 35 08](https://user-images.githubusercontent.com/25937180/150813791-e8b46287-f1dc-43ea-a99f-59548a2cc4be.png)
- go memory usage
![Screenshot 2022-01-24 at 15 39 42](https://user-images.githubusercontent.com/25937180/150814499-d7974d47-a2ab-4107-8163-ad65e6b78c46.png)
