### ISSUE TITLE
[kubernetes] loki disk size keeps growing (retention policy not working)

### ISSUE THREAD

**Issue by waterdrop01** [grafana/loki#5242]
**Describe the bug**
My loki config sets retention policy to 7 days (168 hours), BUT older logs are never deleted and still available.

**Expected behavior**
I expect loki to remove logs older than 7 days, so that the occupied disk dize doesn't keep growing until the disk is full.

**Environment:**
 - Infrastructure: Kubernetes 1.23.0
 - Deployment tool: helm (chart version: loki-2.9.1, docker image: grafana/loki:2.4.2)

**Reproduction**
```
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
helm upgrade loki grafana/loki --namespace=monitoring --values helm-loki-values.yml
```

**Helm values.yml file**
```yml
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 30Gi
  annotations: {}
  storageClassName:

updateStrategy:
  type: RollingUpdate

extraVolumes:
  - name: temp
    emptyDir: {}
extraVolumeMounts:
  - name: temp
    mountPath: /tmp

config:
  compactor:
    working_directory: /data/loki/boltdb-shipper-compactor
    shared_store: filesystem
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 1h
    retention_delete_worker_count: 150
  limits_config:
    retention_period: 168h # 7 days
  schema_config:
    configs:
      - from: "2020-12-05"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
      shared_store: filesystem
    filesystem:
      directory: /data/loki/chunks
  table_manager:
    retention_deletes_enabled: true
    retention_period: 168h
```
My original disk size was set to 20Gb, I've since then increased it to 30Gb, and now I have to increase it to 40Gb, in order to avoid getting a FULL DISK error.

I don't see why loki isn't deleting old logs....

Any advice would be much appreciated! Thanks
