### ISSUE TITLE
Promtail windows agent stops sending log records to Loki server

### ISSUE THREAD

**Issue by matt985** [grafana/loki#5260]
**Describe the bug**

When I start promtail executable on a windows machine it successfully sends a batch of log records to the remote Loki server. After a few minutes though no more entries seem to be delivered. 
No error is reported in the windows client logs or in the Loki server logs. 
No error is reported in the ingress controller logs.

**To Reproduce**
1. Install Loki as a statefulset on a Kubernetes cluster with default Helm Chart configuration (with ingress enabled)
2. Start Promtail executable (promtail-windows-amd64) to tail windows eventlog channel Application
3. Query: `{host="computername"}`

**Expected behavior**
Promtail starts up, collects logs from windows log channels and seamlessly sends them to Loki.

**Environment:**
Loki is installed on a Kubernetes architecture with a standard Helm Chart configuration (chart version: loki-stack-2.5.0; app version: v2.1.0)
Promtail v2.4.2 is installed on a Windows server 2019

**Screenshots, Promtail config, or terminal output**

This is the Promtail configuration file:
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: "positions.yaml"

clients:
  - url: "http://loki-server.com/loki/api/v1/push"
    follow_redirects: true
    tls_config:
      insecure_skip_verify: true

scrape_configs:
- job_name: windows
  windows_events:
    use_incoming_timestamp: false
    bookmark_path: "bookmark.xml"
    eventlog_name: "Application"
    xpath_query: "*"
    labels:
      source: promtail-windows
  relabel_configs:
    - source_labels: ['computer']
      target_label: 'host'
```

This is the shell output of Promtail on the windows machine:
```
C:\Users\Administrator\Desktop\promtail-windows>promtail-windows-amd64.exe --config.file=promtail_config.yaml
level=info ts=2022-01-27T15:29:05.2007857Z caller=server.go:260 http=[::]:9080 grpc=[::]:50793 msg="server listening on addresses"
level=info ts=2022-01-27T15:29:05.355975Z caller=main.go:119 msg="Starting Promtail" version="(version=2.4.1, branch=HEAD, revision=f61a4d261)"
```

Can you give me a hint on how to solve this issue? Is there something I forgot to do to make this configuration work as expected?
Thank you!

**Comment by erickellerek1** [comment]
seems to be a general issue with promtail on windows.
cannot get any windows event and neither get any promtail information while updating the `-log.level debug`
```
C:\promtail>.\promtail-windows-amd64.exe -config.file C:\promtail\promtail-config.yaml -log.level debug
level=debug ts=2022-03-09T02:17:33.7786192Z caller=win_eventlog.go:369 msg="Subcribed with handle id" id=2
level=info ts=2022-03-09T02:17:33.7825422Z caller=server.go:260 http=[::]:9080 grpc=[::]:51717 msg="server listening on addresses"
level=info ts=2022-03-09T02:17:33.7944432Z caller=main.go:119 msg="Starting Promtail" version="(version=2.4.2, branch=HEAD, revision=525040a32)"
```

the configuration I applied is similar to the one from @matt985 yet I also have loki basic auth in place.

```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: C:/promtail/temp/positions.yaml

clients:
  - url: http://loki.example.com:3100/loki/api/v1/push
    basic_auth:
      username: loki
      password: foobarbaz

scrape_configs:
- job_name: windows
  windows_events:
    use_incoming_timestamp: false
    bookmark_path: "./bookmark.xml"
    eventlog_name: "Application"
    xpath_query: "*"
    labels:
      job: windows
      host: win-1234
  relabel_configs:
    - source_labels: ['computer']
      target_label: 'host'
```

The configuration works perfectly fine from Linux hosts.

is anyone lucky with running promtail on windows?
