### ISSUE TITLE
Loki 2.4.0 - Compactor "segmentation violation"

### ISSUE THREAD

**Issue by skilbert** [grafana/loki#5265]
**Describe the bug**

Upgrading from Loki 2.3.0 - Loki 2.4.0 is now panicking every time the compactor is starting, causing it to crash and restart. See full stack trace further down. 

```
loki              | panic: runtime error: invalid memory address or nil pointer dereference
loki              | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1af803c]
```

**To Reproduce**
1. Started Loki 2.4.0 with following config: 

```
auth_enabled: false

server:
  http_listen_port: 3100
  http_listen_address: 10.9.0.9

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    address: 10.9.0.9
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 15m    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  max_query_length: 0h
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 336h
  retention_stream:
  - selector: '{compose_service="logger"}'
    priority: 1
    period: 8766h
```

**Environment:**
This is running with docker-compose on anUbuntu 20.04.3 LTS (GNU/Linux 5.4.0-96-generic x86_64)  VPS. 

**terminal output**

Stack trace: 
```
loki              | level=info ts=2022-01-28T12:03:20.607849402Z caller=compactor.go:337 msg="compactor startup delay completed"
loki              | level=info ts=2022-01-28T12:03:20.607939095Z caller=compactor.go:376 msg="compactor started"
loki              | panic: runtime error: invalid memory address or nil pointer dereference
loki              | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1af803c]
loki              |
loki              | goroutine 3511 [running]:
loki              | github.com/grafana/loki/pkg/validation.(*Overrides).AllByUserID(0x0)
loki              | 	/src/loki/pkg/validation/limits.go:254 +0x1c
loki              | github.com/grafana/loki/pkg/storage/stores/shipper/compactor/retention.findSmallestRetentionPeriod({0x26f81e8, 0xc00000d5d8})
loki              | 	/src/loki/pkg/storage/stores/shipper/compactor/retention/expiration.go:126 +0x82
loki              | github.com/grafana/loki/pkg/storage/stores/shipper/compactor/retention.(*expirationChecker).MarkPhaseStarted(0xc000efa730)
loki              | 	/src/loki/pkg/storage/stores/shipper/compactor/retention/expiration.go:60 +0x45
loki              | github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*expirationChecker).MarkPhaseStarted(0xc000bd5dc0)
loki              | 	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:516 +0x29
loki              | github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).RunCompaction(0xc0002b2900, {0x26f7500, 0xc000225940})
loki              | 	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:409 +0xb6
loki              | github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions.func1()
loki              | 	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:342 +0x29
loki              | github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions.func2()
loki              | 	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:350 +0x9e
loki              | created by github.com/grafana/loki/pkg/storage/stores/shipper/compactor.(*Compactor).runCompactions
loki              | 	/src/loki/pkg/storage/stores/shipper/compactor/compactor.go:348 +0x434
```

Docker-compose config (if relevant):

```
  loki:
    container_name: loki
    restart: unless-stopped
    image: grafana/loki:2.4.0
    command: -config.file=/etc/loki/loki-local-config.yaml
    volumes:
      - loki_data:/loki
      - ./loki-local-config.yaml:/etc/loki/loki-local-config.yaml
    security_opt:
      - no-new-privileges:true
    networks:
      backend_bridge:
        ipv4_address: 10.9.0.9
```

I'm new to this and might have configured something wrong. Please let med know what info you need to help.
