### ISSUE TITLE
Add Option to lookup DNS names given IP

### ISSUE THREAD

**Issue by rabbipigeon** [grafana/loki#5333]
Im facing an issue where im parsing syslog messages into Loki using Promtail as syslog forwarder however i would like to be able to do the following :
```
 - job_name: syslog-server
   syslog:
     listen_address: 0.0.0.0:1514
     idle_timeout: 60s
     label_structured_data: yes
     labels:
       job: "syslog"
   relabel_configs:
...
       -action: reverse lookup
       source_labels: [ '__syslog_message_ip' ]
       target_label: 'dns_name'
```
Can this be done currently or does this make sense as a feature?

**PS**: Love your product, makes logging and log management so much more user friendly
