### ISSUE TITLE
Support receiving logs in Loki using OpenTelemetry OTLP

### ISSUE THREAD

**Issue by js8080** [grafana/loki#5346]
**Is your feature request related to a problem? Please describe.**
I am running Grafana Loki inside a Kubernetes cluster but I have some applications running _outside_ the cluster and I want to get logging data from those applications into Loki without relying on custom APIs or file-based logging.

**Describe the solution you'd like**
[OpenTelemetry describes a number of approaches](https://opentelemetry.io/docs/reference/specification/logs/overview/) including using the OpenTelemetry Collector. The OpenTelemetry Collector [supports various types of exporters](https://opentelemetry.io/docs/collector/configuration/#exporters) and the OTLP exporter supports logs, metrics, and traces. Tempo supports receiving trace data via OTLP and it would be great if Loki also had support for receiving log data via OTLP. This way, people could run the OpenTelemetry Collector next to their applications and send logs into Loki in a standard way using the [OpenTelemetry New First-Party Application Logs recommendations](https://opentelemetry.io/docs/reference/specification/logs/overview/#new-first-party-application-logs).

Currently, unless I am misunderstanding the Loki documentation, it seems the only API into Loki is custom:
- [POST /loki/api/v1/push](https://grafana.com/docs/loki/latest/api/#post-lokiapiv1push)

Details on the OTLP specification:
- OTLP/gRPC: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlpgrpc
- OTLP/HTTP: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp

**Describe alternatives you've considered**
There are a number of [Loki Clients](https://grafana.com/docs/loki/latest/clients/) that one can use to get logs into Loki but they all seem to involve using the custom Loki push API or reading from log files. Supporting the OpenTelemetry Collector would allow following the [OpenTelemetry New First-Party Application Logs recommendations](https://opentelemetry.io/docs/reference/specification/logs/overview/#new-first-party-application-logs)

**Additional context**

**Comment by liguozhong** [comment]
done .https://github.com/grafana/loki/pull/5363
demo go client code:

func TestOtlpPush(t *testing.T) {
	grpcEndpoint := "localhost:4317"
	var defaultReceivers = map[string]interface{}{
		"otlp": map[string]interface{}{
			"protocols": map[string]interface{}{
				"grpc": map[string]interface{}{
					"endpoint": grpcEndpoint,
				},
				"http": map[string]interface{}{
					"endpoint": "localhost:4318",
				},
			},
		},
	}
	//client
	addr := grpcEndpoint
	conn, err := grpc.Dial(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
	require.NoError(t, err)

	client := otlpgrpc.NewLogsClient(conn)
	request := markRequest()
	_, err = client.Export(context.Background(), request)
	require.NoError(t, err)
}

func markRequest() otlpgrpc.LogsRequest {
	request := otlpgrpc.NewLogsRequest()
	pLog := pdata.NewLogs()

	pmm := pLog.ResourceLogs().AppendEmpty()
	pmm.Resource().Attributes().InsertString("app", "testApp")

	ilm := pmm.InstrumentationLibraryLogs().AppendEmpty()
	ilm.InstrumentationLibrary().SetName("testName")

	now := time.Now()

	logReocrd := ilm.LogRecords().AppendEmpty()
	logReocrd.SetName("testName")
	logReocrd.SetFlags(31)
	logReocrd.SetSeverityNumber(1)
	logReocrd.SetSeverityText("WARN")
	logReocrd.SetSpanID(pdata.NewSpanID([8]byte{1, 2}))
	logReocrd.SetTraceID(pdata.NewTraceID([16]byte{1, 2, 3, 4}))
	logReocrd.Attributes().InsertString("level", "WARN")
	logReocrd.SetTimestamp(pdata.NewTimestampFromTime(now))

	logReocrd2 := ilm.LogRecords().AppendEmpty()
	logReocrd2.SetName("testName")
	logReocrd2.SetFlags(31)
	logReocrd2.SetSeverityNumber(1)
	logReocrd2.SetSeverityText("INFO")
	logReocrd2.SetSpanID(pdata.NewSpanID([8]byte{3, 4}))
	logReocrd2.SetTraceID(pdata.NewTraceID([16]byte{1, 2, 3, 4}))
	logReocrd2.Attributes().InsertString("level", "WARN")
	logReocrd2.SetTimestamp(pdata.NewTimestampFromTime(now))
	request.SetLogs(pLog)
	return request
}

**Comment by frzifus** [comment]
May I ask, whats the current state here? :)

**Comment by jpkrohling** [comment]
@sandeepsukhani might know a thing or two about this :-)

**Comment by sandeepsukhani** [comment]
Hey folks, we have added experimental OTLP log ingestion support to Loki. It has yet to be released, so you would have to use the latest main to try it. You can read more about it in the [docs](https://grafana.com/docs/loki/next/send-data/otel/). Please give it a try in your dev environments and share any feedback or suggestions.

**Comment by bouk** [comment]
@sandeepsukhani looks good, I'll give it a try next week.

One immediate suggestion is that I'd like to be able to configure the indexed labels so I can add/remove items from the list. Perhaps it should default to the list you have in the docs and then the user can provide their own list to override it.

**Comment by gkaskonas** [comment]
Is this supported in Loki v3? I get 404 error when calling the endpoint

**Comment by alextricity25** [comment]
Does anyone know if this is now possible? 

I have an OTEL collector running on a k8s cluster which I would like to gather logs from and send over to a remote loki stack running on another k8s cluster. I'm hoping to achieve this via OTLP HTTP, and there is [documentation](https://grafana.com/docs/loki/latest/send-data/otel/#configure-the-opentelemetry-collector-to-write-logs-into-loki) that seems to indicate that this is possible. However, after following the documentation I haven't had any success. Sending logs from the OTEL collector to a remote Loki instance should be possible through OTLP HTTP, right?

**Comment by jpkrohling** [comment]
Yes, Loki v3 includes an OTLP port to ingest OTLP Logs natively.

**Comment by alextricity25** [comment]
> Does anyone know if this is now possible?
> 
> I have an OTEL collector running on a k8s cluster which I would like to gather logs from and send over to a remote loki stack running on another k8s cluster. I'm hoping to achieve this via OTLP HTTP, and there is [documentation](https://grafana.com/docs/loki/latest/send-data/otel/#configure-the-opentelemetry-collector-to-write-logs-into-loki) that seems to indicate that this is possible. However, after following the documentation I haven't had any success. Sending logs from the OTEL collector to a remote Loki instance should be possible through OTLP HTTP, right?

A quick update on this - I was able to receive logs via OTLP HTTP successfully. Turned out to be a mistake with my config.

**Comment by leonhma** [comment]
> A quick update on this - I was able to receive logs via OTLP HTTP successfully. Turned out to be a mistake with my config.

@alextricity25 Would you mind sharing how you got this to work? I am currently stuck at a stage where the collector gives me this error:

```
2024-06-23T17:30:51.116Z	error	exporterhelper/queue_sender.go:90	Exporting failed. Dropping data.	{"kind": "exporter", "data_type": "logs", "name": "otlphttp", "error": "not retryable error: Permanent error: rpc error: code = Unimplemented desc = error exporting items, request to http://loki.telemetry.svc.cluster.local:3100/otlp/v1/logs responded with HTTP Status Code 404", "dropped_items": 10}
go.opentelemetry.io/collector/exporter/exporterhelper.newQueueSender.func1
	go.opentelemetry.io/collector/exporter@v0.103.0/exporterhelper/queue_sender.go:90
go.opentelemetry.io/collector/exporter/internal/queue.(*boundedMemoryQueue[...]).Consume
	go.opentelemetry.io/collector/exporter@v0.103.0/internal/queue/bounded_memory_queue.go:52
go.opentelemetry.io/collector/exporter/internal/queue.(*Consumers[...]).Start.func1
	go.opentelemetry.io/collector/exporter@v0.103.0/internal/queue/consumers.go:43
```

For reference, this is the config for the collector I am currently deploying using the operator:

<details>
<summary>Click to expand</summary>

```yaml
# OpenTelemetry Operator
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: telemetry
spec:
  image: otel/opentelemetry-collector-contrib:0.103.0
  serviceAccount: otel-collector
  mode: daemonset
  volumeMounts:
    # Mount the volumes to the collector container
    - name: varlogpods
      mountPath: /var/log/pods
      readOnly: true
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
  volumes:
    # Typically the collector will want access to pod logs and container logs
    - name: varlogpods
      hostPath:
        path: /var/log/pods
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      filelog:
        include_file_path: true
        include:
          - /var/log/pods/*/*/*.log
        exclude:
          - /var/log/pods/telemetry_otel-collector*/*/*.log
        operators:
          - id: container-parser
            type: container
    processors:
      batch: {}
    exporters:
      logging:
        loglevel: debug
      otlphttp:
        endpoint: http://loki.telemetry.svc.cluster.local:3100/otlp
        compression: none
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:8889"
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus]
        logs:
          receivers: [otlp,filelog]
          processors: [batch]
          exporters: [logging, otlphttp]
```

</details>

And, the loki config:

<details>
<summary>Click to expand</summary>

```yaml
auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    schema_config:
      configs:
        - from: 2024-04-01
          object_store: s3
          store: tsdb
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/tsdb-index
        cache_location: /loki/tsdb-cache
      aws:
        s3: s3://minioadmin:minioadmin@minio-service.minio.svc.cluster.local:9000/loki-data
        s3forcepathstyle: true

    limits_config:
      retention_period: 744h
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_global_streams_per_user: 5000
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      allow_structured_metadata: true

    # chunk_store_config:
    #   max_look_back_period: 744h

    table_manager:
      retention_deletes_enabled: true
      retention_period: 744h

    ruler:
      storage:
        type: local
        local:
          directory: /loki/rules
      rule_path: /loki/rules-temp
      # alertmanager_url: http://alertmanager:9093 TODO deploy alertmanager
      ring:
        kvstore:
          store: inmemory
      enable_api: true

    query_scheduler:
      max_outstanding_requests_per_tenant: 2048

    frontend:
      max_outstanding_per_tenant: 2048
      compress_responses: true
```
</details>

This looks suspiciously like the OTLP collector is still using gRPC, but this is exactly what the [docs](https://grafana.com/docs/loki/next/send-data/otel/) tell me to do so I am clueless here. Any help would be appreciated
