### ISSUE TITLE
Promtail timestamp millis with comma are not working

### ISSUE THREAD

**Issue by yarix** [grafana/loki#5348]
**Describe the bug**
Using timestamp stage for times with comma milliseconds like `2022-02-08 03:12:37,458` is not working.

**To Reproduce**
for example:
* log line : `2022-02-08 03:12:37,458 some message`
* promtail yaml:
```
- regex:
    expression: '^(?P<ts>\d{4}-\d{2}-\d{2}\s\d{2}\:\d{2}\:\d{2},\d{3})\s(?P<message>.*)$'
- labels:
    ts:
    message:
- timestamp:
    format: '2006-01-02 15:04:05,000'
    source: ts
```

* test with dry-run it, the regex works but in timestamp it say none
```[inspect: regex stage]:
{stages.Entry}.Extracted["message"]:
        +: some message
{stages.Entry}.Extracted["ts"]:
        +: 2022-02-08 18:07:13,751

[inspect: timestamp stage]: none
```

**Expected behavior**
timestamp stage should recognize comma milliseconds.

**Environment:**
``` ./promtail-linux-amd64 --version
promtail, version 2.4.2 (branch: HEAD, revision: 525040a32)
  build user:       root@5d9e7a4c92e6
  build date:       2022-01-12T16:48:53Z
  go version:       go1.16.2
  platform:         linux/amd64
````
