### ISSUE TITLE
I can't see docker logs container_name in Loki

### ISSUE THREAD

**Issue by k-szortyka** [grafana/loki#5366]
**Describe the bug**
I configured promtail container, all seems good, logs shows id containers, in promtail containers also shows but I can't see logs in Loki, with label container_name and host.
I see only as {filename="/host/containers/7a332a1a43574c1e13b0fb2fdf63340b0fb24b712ad2b0262e3aa013c7eb7bd1/7a332a1a43574c1e13b0fb2fdf63340b0fb24b712ad2b0262e3aa013c7eb7bd1-json.log"}
Promtail and Loki are on different machines.

**To Reproduce**
1. Install Promtail with config promtail and docker-compose.

**Expected behavior**
Show docker logs in Loki with label container_name and host.

**Environment:**
Loki - EC2
Promtail - linux host with docker

**Screenshots, Promtail config, or terminal output**
docker-compose.yaml:

```
version: "3"
networks:
  loki:
services:
  promtail:
    image: grafana/promtail:2.2.1
    volumes:
      - /opt/promtail/promtail-config.yaml:/mnt/config/promtail-config.yaml
      - /var/lib/docker/containers:/host/containers
    command: -config.file /mnt/config/promtail-config.yaml
    networks:
      - loki
```

promtail-config.yaml:
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://IP_LOKI:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: dockerlogs
          __path__: /host/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          tag:
          stream:
          image_name:
          container_name:
          image_id:
          container_id:
      - output:
          source: output
```

```
ts=2022-02-10T23:16:26.408607086Z caller=log.go:124 level=info msg="Seeked /host/containers/742f46967a90602565f74b8525bc15775707319dd35bec4bb56d1a8ef41173ae/742f46967a90602565f74b8525bc15775707319dd35bec4bb56d1a8ef41173ae-json.log - &{Offset:0 Whence:0}"
level=info ts=2022-02-10T23:16:26.408831087Z caller=tailer.go:125 component=tailer msg="tail routine: started" path=/host/containers/742f46967a90602565f74b8525bc15775707319dd35bec4bb56d1a8ef41173ae/742f46967a90602565f74b8525bc15775707319dd35bec4bb56d1a8ef41173ae-json.log
level=info ts=2022-02-10T23:16:26.409048406Z caller=tailer.go:125 component=tailer msg="tail routine: started" path=/host/containers/8ef152236abe202689935071cd7f6f9592fac7d9d1b565b98bfc8144bab82953/8ef152236abe202689935071cd7f6f9592fac7d9d1b565b98bfc8144bab82953-json.log
ts=2022-02-10T23:16:26.409062281Z caller=log.go:124 level=info msg="Seeked /host/containers/8ef152236abe202689935071cd7f6f9592fac7d9d1b565b98bfc8144bab82953/8ef152236abe202689935071cd7f6f9592fac7d9d1b565b98bfc8144bab82953-json.log - &{Offset:0 Whence:0}"
level=info ts=2022-02-10T23:16:26.409135318Z caller=tailer.go:125 component=tailer msg="tail routine: started" path=/host/containers/7c4caefdff6a11c67ab0b35e544e28e42767a44d6007d5e0d2c324996f2a5c41/7c4caefdff6a11c67ab0b35e544e28e42767a44d6007d5e0d2c324996f2a5c41-json.log
ts=2022-02-10T23:16:26.409750435Z caller=log.go:124 level=info msg="Seeked /host/containers/7ead353d3713160c06cde5402231d123e95592ebedf6d12c3c774e4eaba3224a/7ead353d3713160c06cde5402231d123e95592ebedf6d12c3c774e4eaba3224a-json.log - &{Offset:0 Whence:0}"
level=info ts=2022-02-10T23:16:26.409957804Z caller=tailer.go:125 component=tailer msg="tail routine: started" path=/host/containers/7ead353d3713160c06cde5402231d123e95592ebedf6d12c3c774e4eaba3224a/7ead353d3713160c06cde5402231d123e95592ebedf6d12c3c774e4eaba3224a-json.log
ts=2022-02-10T23:16:26.410160486Z caller=log.go:124 level=info msg="Seeked /host/containers/7c4caefdff6a11c67ab0b35e544e28e42767a44d6007d5e0d2c324996f2a5c41/7c4caefdff6a11c67ab0b35e544e28e42767a44d6007d5e0d2c324996f2a5c41-json.log - &{Offset:0 Whence:0}"
```

```

root@9ced13f8f3ed:/# cd /host/containers/
root@9ced13f8f3ed:/host/containers# ls
2e9150456d2b54193bf3218f96d05c0715cea1b71ef7a5c38ddfe047a9264387  8ef152236abe202689935071cd7f6f9592fac7d9d1b565b98bfc8144bab82953
742f46967a90602565f74b8525bc15775707319dd35bec4bb56d1a8ef41173ae  9ced13f8f3ed33e709cfdd87827ed91f1a66a8a5735667096df1f00ae0d49d8c
7a332a1a43574c1e13b0fb2fdf63340b0fb24b712ad2b0262e3aa013c7eb7bd1  a04efaa63b57ecd42775a132f0611953b3b9c60de5dac5713d59f9ceff2773c6
7b1d93f42e050a0ed2f10cbc67fcd2150d98a900d207f54470e5275e438ca1f0  cb83f596da84de52389a14c01c98d1dd4485738a79374b4294a25427bd07080d
7c4caefdff6a11c67ab0b35e544e28e42767a44d6007d5e0d2c324996f2a5c41  eb164ee3cc1a9c9ebfd7ee9fe98d80c723c7130ad5b38beb83679158a0d7ef59
7ead353d3713160c06cde5402231d123e95592ebedf6d12c3c774e4eaba3224a  f2b6cfd3e88ad0a1b6e77426abfb63283b87759d1deffbff455b8649a831e3c8
root@9ced13f8f3ed:/host/containers# 
```

**Comment by tcurdt** [comment]
I wasn't aware `promtail` supports that at all.
I guess that's a reason to use the docker driver instead of `promtail`?

**Comment by paragv7** [comment]
It looks like this issue is not fixed yet. I am also facing this issue

**Comment by tcurdt** [comment]
This should all be easier. We switched to the docker integration.

This here is a working loki config with the grafana agent:

```
logs:
  configs:
    - name: agent
      clients:
        - url: {{ grafana.logs.url }}
      positions:
        filename: /tmp/grafana-logs-positions.yaml
      target_config:
        sync_period: 10s
      scrape_configs:

        - job_name: integrations/docker
          pipeline_stages:
            - multiline:
                firstline: '(INFO|ERROR)'
          docker_sd_configs:
            - host: unix:///var/run/docker.sock
              refresh_interval: 5s
          relabel_configs:
            - action: replace
              replacement: integrations/docker
              source_labels:
                - __meta_docker_container_id
              target_label: job
            - source_labels:
                - __meta_docker_container_name
              regex: '/(.*)'
              target_label: container
            - source_labels:
                - __meta_docker_container_log_stream
              target_label: stream
            - source_labels:
                - __meta_docker_container_label_service
              target_label: service
```

HTH
