### ISSUE TITLE
logstash-output-loki PLUGIN  shows only labels  and not logs in Grafana Loki explorer

### ISSUE THREAD

**Issue by pkrishnanreflexion** [grafana/loki#5390]
**Describe the bug**
Logs do not show up in LOKI explorer when ingested with "logstash-output-loki" plugin

**To Reproduce**
1. Started Loki (2.4.2) locally with following config file.

```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  reject_old_samples: false
  reject_old_samples_max_age: 3000h
  max_query_length: 0h # Default: 721h

ruler:
  alertmanager_url: http://localhost:9093


```
2. Elasticsearch is running locally on 9200 which has logs with index "reflexion-logs-demo"

3. Started Logstash with "logstash-output-loki" (7.17)  installed locally with following config file. 
```
input { 
      # Read all documents from Elasticsearch matching the given query
      elasticsearch {
        hosts => "localhost"
	index => "reflexion-logs-demo"
      }
}
output {
  stdout { codec => rubydebug }
  loki {
    url => "http://localhost:3100/loki/api/v1/push"
  }
}

```

4. I want to just read logs from elastic search using "logstash-input-elasticsearch" and push it into loki using "logstash-output-loki". Verfied that data is being pushed to LOKI from "logstash-output-loki" through logs with success for push request.

5. Verfied, loki is capturing labels.
<img width="1057" alt="Screen Shot 2022-02-14 at 6 44 46 PM" src="https://user-images.githubusercontent.com/94964199/154024442-71befe8b-1388-4f51-ac37-0ef80069aaa1.png">

3. Query: `{} term`

**Expected behavior**
Loki debug logs show "success" for PUSH request, and labels also show up in loki. But on query, the result set is not visible on Grafana, it says EMPTY result sets.
Curl query returns labels
<img width="1701" alt="Screen Shot 2022-02-14 at 6 45 08 PM" src="https://user-images.githubusercontent.com/94964199/154023928-1d18cae7-d074-4674-9e49-26e8bb7cc905.png">

Curl query for data returns result set 0.

On 
**Environment:**
Local deployment on MAC
Same behaviour when tested in docker containers.
