### ISSUE TITLE
"RequestCanceled: request context canceled\ncaused by: context deadline exceeded" with 2.4.2, works with 2.3.0

### ISSUE THREAD

**Issue by gkocur** [grafana/loki#5408]
When I perform the query based on some labels I get the `failed to get s3 object: NoSuchKey` message and 500 from loki.
What is strange logs with such labels  *exists* - if I add more labels to the query it works as expected.

For example if I search for `{namespace="demo"}`:
```
{
  "state": "Error",
  "series": [],
  "request": {
    "app": "explore",
    "dashboardId": 0,
    "timezone": "browser",
    "startTime": 1644996543908,
    "interval": "500ms",
    "intervalMs": 500,
    "panelId": "Q-9d0261c1-aec0-4c41-aa68-452355afee02-0",
    "targets": [
      {
        "refId": "A",
        "expr": "{namespace=\"demo\"}",
        "key": "Q-9d0261c1-aec0-4c41-aa68-452355afee02-0",
        "datasource": {
          "type": "loki",
          "uid": "P8E80F9AEF21F6940"
        }
      }
    ],
    "range": {
      "from": "2022-02-16T07:14:03.905Z",
      "to": "2022-02-16T07:29:03.905Z",
      "raw": {
        "from": "now-15m",
        "to": "now"
      }
    },
    "requestId": "explore_left",
    "rangeRaw": {
      "from": "now-15m",
      "to": "now"
    },
    "scopedVars": {
      "__interval": {
        "text": "500ms",
        "value": "500ms"
      },
      "__interval_ms": {
        "text": 500,
        "value": 500
      }
    },
    "maxDataPoints": 2029,
    "liveStreaming": false
  },
  "timeRange": {
    "from": "2022-02-16T07:14:03.905Z",
    "to": "2022-02-16T07:29:03.905Z",
    "raw": {
      "from": "now-15m",
      "to": "now"
    }
  },
  "error": {
    "status": 500,
    "statusText": "",
    "data": {
      "message": "failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: QNRQHPTQEFK2J44P, host id: KlDkqz7jGIUx+36M+jmmN4YyaObDTC8bbkamfFk2d0GD8lkgpjxMY906xF4oMQDc/A9rnKjKvAA=\n",
      "error": "",
      "response": "failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: QNRQHPTQEFK2J44P, host id: KlDkqz7jGIUx+36M+jmmN4YyaObDTC8bbkamfFk2d0GD8lkgpjxMY906xF4oMQDc/A9rnKjKvAA=\n"
    },
    "config": {
      "headers": {
        "X-Grafana-Org-Id": 1
      },
      "url": "api/datasources/proxy/2/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bnamespace%3D%22demo%22%7D&start=1644995643905000000&end=1644996543905000000&step=0.5",
      "retry": 0,
      "hideFromInspector": false
    },
    "message": "failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: QNRQHPTQEFK2J44P, host id: KlDkqz7jGIUx+36M+jmmN4YyaObDTC8bbkamfFk2d0GD8lkgpjxMY906xF4oMQDc/A9rnKjKvAA=\n"
  },
  "annotations": [],
  "timings": {
    "dataProcessingTime": 0
  },
  "graphFrames": [],
  "tableFrames": [],
  "logsFrames": [],
  "traceFrames": [],
  "nodeGraphFrames": [],
  "graphResult": null,
  "tableResult": null,
  "logsResult": null
}
```

But if I change the search for `{namespace="demo", app="dgraph"}` i get proper answer.
I installed loki with `loki-stack` helm chart v2.6.1, loki image `grafana/loki:2.4.2`.
My config:
```
config:
    ruler:
      alertmanager_url: http://kube-prometheus-stack-alertmanager:9093
      enable_api: true
      ring:
        kvstore:
          store: inmemory
      rule_path: /tmp/scratch
      storage:
        local:
          directory: /rules
        type: local
    schema_config:
      configs:
      - from: "2020-05-15"
        index:
          prefix: loki_
        object_store: s3
        schema: v11
        store: aws
    storage_config:
      aws:
        dynamodb:
          dynamodb_url: dynamodb://us-east-1
        s3: s3://us-east-1/some-bucket (edited)
    table_manager:
      index_tables_provisioning:
        enable_inactive_throughput_on_demand_mode: true
        enable_ondemand_throughput_mode: true
        inactive_read_throughput: 0
        inactive_write_throughput: 0
        provisioned_read_throughput: 0
        provisioned_write_throughput: 0
```

What am I doing wrong? Is it a bug?

**Comment by gkocur** [comment]
It was a missconfiguration. I had the 2 loki instances on the same aws account and both were using the same dynamodb table... Sorry.
But now I changed the prefix in the schema config, and got this:
```
level=error ts=2022-02-16T14:18:22.001449781Z caller=flush.go:221 org_id=fake msg="failed to flush user" err="ResourceNotFoundException: Requested resource not found"
```
I think it's a problem with creating the dynamoDB table?
The k8s nodes have acces to the dynamobdb, I'm able to create the table manually from the pod in this cluster.
Any ideas?

**Comment by gkocur** [comment]
Made some investigation, and changed a config a bit:
```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
compactor:
  shared_store: filesystem
  working_directory: /data/loki/boltdb-shipper-compactor
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
  wal:
    dir: /data/loki/wal
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
ruler:
  alertmanager_url: http://kube-prometheus-stack-alertmanager:9093
  enable_api: true
  ring:
    kvstore:
      store: inmemory
  rule_path: /tmp/scratch
  storage:
    local:
      directory: /rules
    type: local
schema_config:
  configs:
  - from: "2020-05-15"
    index:
      period: 168h
      prefix: us1_
      tags: {}
    object_store: s3
    schema: v11
    store: aws
server:
  http_listen_port: 3100
storage_config:
  aws:
    dynamodb:
      dynamodb_url: dynamodb://us-east-1
    s3: s3://us-east-1/intouch-loki-us-1
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /data/loki/chunks
table_manager:
  index_tables_provisioning:
    enable_inactive_throughput_on_demand_mode: true
    enable_ondemand_throughput_mode: true
  retention_deletes_enabled: true
  retention_period: 672h
```

Checked this with 2.4.2 and get:
```
level=error ts=2022-02-16T17:08:28.2228838Z caller=flush.go:221 org_id=fake msg="failed to flush user" err="RequestCanceled: request context canceled\ncaused by: context deadline exceeded"
```
With 2.3.0 works fine (4 dynamodb tables are created).

Where any braking changes in the configuration on 2.4?

Will appreciate  any help.
