### ISSUE TITLE
Loki: Internal Server Error. 500. QueryPages error: table=loki_: ResourceNotFoundException: Requested resource not found 

### ISSUE THREAD

**Issue by k-szortyka** [grafana/loki#5431]
**Describe the bug**
I'm trying to store chunks in AWS S3, index in AWS DynamoDB and I get error:
Loki: Internal Server Error. 500. QueryPages error: table=loki_: ResourceNotFoundException: Requested resource not found 

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**
Create table in DynamoDB.

**Environment:**
 - loki 2.4.0
 - permissions: AmazonS3FullAccess, AmazonDynamoDBFullAccess 

**Screenshots, Promtail config, or terminal output**
loki-config.yaml
```
auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
  - from: 2020-05-15
    store: aws
    object_store: s3
    schema: v11
    index:
      prefix: loki_
storage_config:
  aws:
   s3: s3://AKIATL2SxxxVH2AEK:lw4iIFxxxxxZCKmo9@eu-west-1/grafana-loki
   s3forcepathstyle: true
   dynamodb:
      dynamodb_url: dynamodb://AKIATL2SDHD6CxxxEK:lw4iIFDbE2NOHdWxxxxxxxxxAaU55k2AxZCKmo9@eu-west-1

ruler:
  alertmanager_url: http://localhost:9093
```

docker-compose
```
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.0
    volumes:
      - /opt/loki/local-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.1
    volumes:
      - /opt/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki
```
