### ISSUE TITLE
Queries not sent to S3 store within 2h28m when using S3 even set query_store_max_look_back_period to 0 explicitly

### ISSUE THREAD

**Issue by honganan** [grafana/loki#5434]
**Describe the bug**
When test with S3 storage, I found queries not sent to store if time range value of `--since` is less than 2h27m in logcli. 

The query 
`logcli query '{job="varlog"} |= "ppppppppppp"' --since=2h28m --limit=3 --stats` 
has been sent to store, but  
`logcli query '{job="varlog"} |= "ppppppppppp"' --since=2h27m --limit=3 --stats` 
does not.

Document saids `query_store_max_look_back_period ` is default to 0 and should not be set bigger than 0 if not using file-system storage.
And I find even if I set the `query_store_max_look_back_period ` to 0 explicitly, the starting log shows it was 0 but the api `curl http://localhost:3100/config | grep 'query_store_max_look_back_period'` shows it was still 2h28m0s, I think there is a bug.

**To Reproduce**
1. Started Loki that use S3 storage (either 2.4.2 or latest)
2. Set `query_store_max_look_back_period` to 0 or just leave it be defaults, and set `querier.query_store_only` to true.
3. Query: `logcli query '{job="varlog"} |= "ppppppppppp"' --since=2h27m --limit=3 --stats` or less since value, found stats like:
```
Ingester.TotalReached 		 0
Ingester.TotalChunksMatched 	 0
Ingester.TotalBatches 		 0
Ingester.TotalLinesSent 	 0
Ingester.HeadChunkBytes 	 0 B
Ingester.HeadChunkLines 	 0
Ingester.DecompressedBytes 	 0 B
Ingester.DecompressedLines 	 0
Ingester.CompressedBytes 	 0 B
Ingester.TotalDuplicates 	 0
Store.TotalChunksRef 		 0
Store.TotalChunksDownloaded 	 0
Store.ChunksDownloadTime 	 0s
Store.HeadChunkBytes 		 0 B
Store.HeadChunkLines 		 0
Store.DecompressedBytes 	 0 B
Store.DecompressedLines 	 0
Store.CompressedBytes 		 0 B
Store.TotalDuplicates 		 0
Summary.BytesProcessedPerSecond 	 0 B
Summary.LinesProcessedPerSecond 	 0
Summary.TotalBytesProcessed 		 0 B
Summary.TotalLinesProcessed 		 0
Summary.ExecTime 			 50.836748ms
```

And if Query `logcli query '{job="varlog"} |= "ppppppppppp"' --since=2h28m --limit=3 --stats` it shows like:
```
Ingester.TotalReached 		 0
Ingester.TotalChunksMatched 	 0
Ingester.TotalBatches 		 0
Ingester.TotalLinesSent 	 0
Ingester.HeadChunkBytes 	 0 B
Ingester.HeadChunkLines 	 0
Ingester.DecompressedBytes 	 0 B
Ingester.DecompressedLines 	 0
Ingester.CompressedBytes 	 0 B
Ingester.TotalDuplicates 	 0
Store.TotalChunksRef 		 129
Store.TotalChunksDownloaded 	 129
Store.ChunksDownloadTime 	 1.811533063s
Store.HeadChunkBytes 		 0 B
Store.HeadChunkLines 		 0
Store.DecompressedBytes 	 665 MB
Store.DecompressedLines 	 145167
Store.CompressedBytes 		 145 MB
Store.TotalDuplicates 		 0
Summary.BytesProcessedPerSecond 	 896 MB
Summary.LinesProcessedPerSecond 	 195405
Summary.TotalBytesProcessed 		 665 MB
Summary.TotalLinesProcessed 		 145167
Summary.ExecTime 			 742.902556ms
```

**Expected behavior**
Any query should be sent to storage.

**Environment:**
 - Infrastructure: Virtual machine
 - Deployment tool:  Docker

**Screenshots, Promtail config, or terminal output**
My `loki-all.yaml` file content:
```
target: all
auth_enabled: false

server:
  graceful_shutdown_timeout: 5s
  grpc_server_max_concurrent_streams: 0
  grpc_server_max_recv_msg_size: 100000000
  grpc_server_max_send_msg_size: 100000000
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  lifecycler:
    address: 127.0.0.1 
    ring:
      kvstore:
        store: inmemory  
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 3h 
  chunk_retain_period: 30s 
  chunk_target_size: 5242880   # 5MB
  chunk_encoding: lz4
  query_store_max_look_back_period: 0
  wal:
    enabled: false

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: s3
  aws:
    s3: s3://xxxx...
    s3forcepathstyle: true
  max_chunk_batch_size: 400
  index_queries_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_bytes: 2GB
      max_size_items: 0
      validity: 24h0m0s
      size: 0

compactor:
      working_directory: /loki/boltdb-shipper-compactor
      shared_store: aws

chunk_store_config:

schema_config:
    configs:
    - from: 2022-02-15
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
          prefix: index_
          period: 24h

limits_config:
    enforce_metric_name: false
    per_stream_rate_limit: 100MB
    ingestion_burst_size_mb: 100
    ingestion_rate_mb: 100
    ingestion_rate_strategy: local
    max_global_streams_per_user: 10000
    max_entries_limit_per_query: 10000
    max_query_length: 168h
    max_query_parallelism: 128
    max_streams_per_user: 0
    reject_old_samples: false
    reject_old_samples_max_age: 168h
query_range:
    align_queries_with_step: true
    cache_results: true
    max_retries: 2
    results_cache:
        cache:
            # We're going to use the in-process "FIFO" cache
            enable_fifocache: true
            fifocache:
                size: 2048000000
                validity: 24h
    split_queries_by_interval: 5m
querier:
  max_concurrent: 64
  query_store_only: true
frontend_worker:
  parallelism: 64
  match_max_concurrent: true
frontend:
    max_outstanding_per_tenant: 2600
query_scheduler:
    max_outstanding_requests_per_tenant: 2600

# should be unusefull
table_manager:
  creation_grace_period: 24h
  chunk_tables_provisioning:
      inactive_read_throughput: 0
      inactive_write_throughput: 0
      provisioned_read_throughput: 0
      provisioned_write_throughput: 0
  index_tables_provisioning:
      inactive_read_throughput: 0
      inactive_write_throughput: 0
      provisioned_read_throughput: 0
      provisioned_write_throughput: 0
  retention_deletes_enabled: true  #超过retention_period时间历史数据可以删除
  retention_period: 72h
```
