### ISSUE TITLE
Wrong AWS sts endpoint ist called

### ISSUE THREAD

**Issue by Olli73773** [grafana/loki#5436]
**Describe the bug**
Running Loki an AWS EKS in Region eu-central-1 should call the AWS STS in the same region (sts.eu.central-1.amazonaws.com) and not the central AWS STS (sts.amazonaws.com) 

**To Reproduce**
1. Started Loki version="(version=2.4.2, branch=HEAD, revision=525040a32)"
2. Wait for startup to finish.
3. Call the label endpoint via curl (curl -v http://sphs-loki.sphs-dev.svc.cluster.local:3100/api/prom/label)
4. Check log 
```
level=warn ts=2022-02-21T06:54:27.457163664Z caller=logging.go:72 traceID=206e782b2255f3db orgID=fake msg="GET /api/prom/label (500) 2m30.013641749s Response: \"rpc error: code = Unknown desc = WebIdentityErr: failed to retrieve credentials\\ncaused by: RequestError: send request failed\\ncaused by: Post \\\"https://sts.amazonaws.com/\\\": dial tcp 209.54.177.164:443: i/o timeout\\n\" ws: false; Accept: */*; User-Agent: curl/7.68.0; "
```

**Expected behavior**
Loki should call the regional endpoint. For legal reason the access to AWS resources outside the EU is blocked. 

**Environment:**
 - Infrastructure: Kubernetes on AWS EKS
 - Deployment tool: hel

**Screenshots, Promtail config, or terminal output**
```
loki.yaml:
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
compactor:
  shared_store: s3
  working_directory: /data/loki/boltdb-shipper-compactor
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
  wal:
    dir: /data/loki/wal
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
  - from: "2022-01-01"
    index:
      period: 24h
      prefix: index_
    object_store: s3
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
storage_config:
  aws:
    s3: s3://eu-central-1/bucketname
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 1h
    shared_store: s3
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
```
