### ISSUE TITLE
Loki does not assume AWS IAM Role

### ISSUE THREAD

**Issue by Olli73773** [grafana/loki#5437]
**Describe the bug**
Loki deployed in AWS EKS doesn't assume AWS IAM role as soon the endpoint is configured or the s3 config has the complete s3 hostname. 
The setup of the AWS IAM Role and the K8S Service Account was validated with aws-cli and problem was doubled check with an AWS engeneer fro Amazon Europe.

**To Reproduce**
1. setup Cloudtrail to record "AssumeRoleWithWebIdentity"
1. Started Loki version="(version=2.4.2, branch=HEAD, revision=525040a32)"
2. Wait for startup to finish
3. Call label endpoint with curl -v http://sphs-loki.sphs-dev.svc.cluster.local:3100/api/prom/label
4. A 500 "Internal Sever error" is returmed
5. check cloudtrail. AssumeRoleWithWebIdentity entry is missing

**Expected behavior**
A http 200 should be returned with a empty label list

**Environment:**
 - Infrastructure: Kubernetes on AWS EKS
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Output:
```
nobody@oedelma-shell:/$ curl -v http://sphs-loki.sphs-dev.svc.cluster.local:3100/api/prom/label
*   Trying 172.20.114.208:3100...
* TCP_NODELAY set
* Connected to sphs-loki.sphs-dev.svc.cluster.local (172.20.114.208) port 3100 (#0)
> GET /api/prom/label HTTP/1.1
> Host: sphs-loki.sphs-dev.svc.cluster.local:3100
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json; charset=UTF-8
< Date: Mon, 21 Feb 2022 07:10:28 GMT
< Content-Length: 2028
<
rpc error: code = Unknown desc = WebIdentityErr: failed to retrieve credentials
caused by: SerializationError: failed to unmarshal error message
        status code: 405, request id:
caused by: UnmarshalError: failed to unmarshal error message
        00000000  3c 3f 78 6d 6c 20 76 65  72 73 69 6f 6e 3d 22 31  |<?xml version="1|
00000010  2e 30 22 20 65 6e 63 6f  64 69 6e 67 3d 22 55 54  |.0" encoding="UT|
00000020  46 2d 38 22 3f 3e 0a 3c  45 72 72 6f 72 3e 3c 43  |F-8"?>.<Error><C|
00000030  6f 64 65 3e 4d 65 74 68  6f 64 4e 6f 74 41 6c 6c  |ode>MethodNotAll|
00000040  6f 77 65 64 3c 2f 43 6f  64 65 3e 3c 4d 65 73 73  |owed</Code><Mess|
00000050  61 67 65 3e 54 68 65 20  73 70 65 63 69 66 69 65  |age>The specifie|
00000060  64 20 6d 65 74 68 6f 64  20 69 73 20 6e 6f 74 20  |d method is not |
00000070  61 6c 6c 6f 77 65 64 20  61 67 61 69 6e 73 74 20  |allowed against |
00000080  74 68 69 73 20 72 65 73  6f 75 72 63 65 2e 3c 2f  |this resource.</|
00000090  4d 65 73 73 61 67 65 3e  3c 4d 65 74 68 6f 64 3e  |Message><Method>|
000000a0  50 4f 53 54 3c 2f 4d 65  74 68 6f 64 3e 3c 52 65  |POST</Method><Re|
000000b0  73 6f 75 72 63 65 54 79  70 65 3e 53 45 52 56 49  |sourceType>SERVI|
000000c0  43 45 3c 2f 52 65 73 6f  75 72 63 65 54 79 70 65  |CE</ResourceType|
000000d0  3e 3c 52 65 71 75 65 73  74 49 64 3e 50 45 44 4e  |><RequestId>PEDN|
000000e0  35 37 56 38 45 37 53 54  36 52 4e 57 3c 2f 52 65  |57V8E7ST6RNW</Re|
000000f0  71 75 65 73 74 49 64 3e  3c 48 6f 73 74 49 64 3e  |questId><HostId>|
00000100  48 56 6d 5a 4c 5a 57 6f  63 59 58 58 5a 2b 32 69  |HVmZLZWocYXXZ+2i|
00000110  4c 36 4c 50 5a 52 4c 6a  45 6e 35 59 2b 6a 76 45  |L6LPZRLjEn5Y+jvE|
00000120  52 54 79 49 54 48 39 69  79 35 56 42 37 6c 6e 56  |RTyITH9iy5VB7lnV|
00000130  53 43 73 72 6b 72 73 48  73 56 50 42 75 6c 71 4a  |SCsrkrsHsVPBulqJ|
00000140  6c 38 6b 49 41 49 47 38  68 30 30 3d 3c 2f 48 6f  |l8kIAIG8h00=</Ho|
00000150  73 74 49 64 3e 3c 2f 45  72 72 6f 72 3e           |stId></Error>|

caused by: unknown error response tag, {{ Error} []}
```

loki.yaml
```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
compactor:
  shared_store: s3
  working_directory: /data/loki/boltdb-shipper-compactor
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
  wal:
    dir: /data/loki/wal
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
  - from: "2022-01-01"
    index:
      period: 24h
      prefix: index_
    object_store: s3
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
storage_config:
  aws:
    bucketnames: bucketname
    endpoint: s3.eu-central-1.amazonaws.com
    region: eu-central-1
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 1h
    shared_store: s3
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
 ```
