### ISSUE TITLE
Displaying Chinese characters unreadable in grafana from loki

### ISSUE THREAD

**Issue by SnowfallDan** [grafana/loki#5442]
Service is running in windows server. The log charset is gb2312. 
We use promtail to collect log file and send them to loki running in centos.
But we search the log from grafana. The Chinese characters is unreadable.

loki config:
```
auth_enabled: false

server:
  http_listen_address: 10.4.6.46
  http_listen_port: 3100
  grpc_listen_port: 9096
  grpc_server_max_recv_msg_size: 18388608
  grpc_server_max_send_msg_size: 18388608
  log_level: info

limits_config:
  ingestion_rate_mb: 50
  ingestion_burst_size_mb: 70
  per_stream_rate_limit: 30M
  per_stream_rate_limit_burst: 50M
  max_streams_per_user: 0
  max_global_streams_per_user: 0

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
``` 

promtail config:
```
server:
  disable: false
  http_listen_address: 10.4.6.189
  http_listen_port: 9080
  grpc_listen_port: 9050
  log_level: warn
  
 
positions:
  filename: ./positions.yaml
  sync_period: 10
  ignore_invalid_yaml: false
 
clients:
  - url: http://10.4.6.46:3100/loki/api/v1/push
 
scrape_configs:
  - job_name: 10.4.6.189-kernel
    static_configs:
      - targets:
          - 10.4.6.189
        labels:
          job: tkernel
          host: 10.4.6.189
          __path__: D:\tkernel\*.log
  - job_name: 10.4.6.189-gwtrade
    static_configs:
      - targets:
          - 10.4.6.189
        labels:
          job: gwtrade
          host: 10.4.6.189
          __path__: D:\gwtrade\gwtrade_70\*.log
  - job_name: 10.4.6.189-stategy
    static_configs:
      - targets:
          - 10.4.6.189
        labels:
          job: stategy
          host: 10.4.6.189
          __path__: D:\tkernel\log\*.txt     
  ```

grafana search result:
![image](https://user-images.githubusercontent.com/16498700/155073846-2d889848-6abc-4600-9f4d-7b02f52fb12c.png)
