### ISSUE TITLE
PVC for loki isn't created when specified in helm

### ISSUE THREAD

**Issue by kamilgregorczyk** [grafana/loki#5443]
When doing:
```
helm upgrade --install -f loki.yaml loki grafana/loki-stack --namespace prometheus
```
with `loki.yaml`

```
loki:
  enabled: true
  persistance:
    enabled: true
    storageClassName: longhorn
    size: 20Gi
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 512Mi

promtail:
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 248Mi
```

PVC for loki doesn't get created:

```
➜  ~ kubectl get pvc -n prometheus
NAME                                                                                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-0   Bound    pvc-730426d6-4d52-48f4-a43f-9bd8a56fdd7b   10Gi       RWO            longhorn       94d
data-tempo-tempo-distributed-ingester-0                                                                  Bound    pvc-d9e9998d-22b7-4e85-8049-c9f744553499   10Gi       RWO            longhorn       76d
prometheus-grafana                                                                                       Bound    pvc-7a79558f-7075-4682-8047-4fa1b9456fa7   5Gi        RWO            longhorn       94d
```
