### ISSUE TITLE
if target=read and ruler not configured, error about invalid configdb storage

### ISSUE THREAD

**Issue by zswanson** [grafana/loki#5460]
**Describe the bug**
Trying to run the simple-scalable target for target=write/target=read and the read container threw this error and crashed:

> level=error ts=2022-02-23T14:12:56.608070392Z caller=log.go:106 msg="error running loki" err="configdb is not supported as a Loki rules backend type\nerror initialising module: ruler-storage\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:322\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"	

We are not using the Ruler and didn't have it configured at all in the config file. It looks like the defaults are set to a 'configdb' which isn't even a valid option according to the docs.

**To Reproduce**
1. Started Loki with target=read, using a config file that does NOT specify the `ruler` section
2. read container should crash/restart with the error about configdb

**Expected behavior**
Defaults values for ruler should probably be local file storage

**Environment:**
 - Infrastructure: AWS ECS-fargate
- Deployment tool: terraform
- Loki version: 2.4.2

**Comment by DylanGuedes** [comment]
Could you please confirm you were running `v2.4.2`?

I managed to successfully run Loki in `read` mode with ref v2.4.2 with the following configuration:
```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
```

**Comment by zswanson** [comment]
Yes, 2.4.2 for sure. But if that's the config you ran with that will default to 'all' right? You'd need `target: read` for the read mode.

**Comment by DylanGuedes** [comment]
I ran with `target=read`.

**Comment by zswanson** [comment]
This is 2.4.1 in the log, but I had changed tactics and this was while trying to use the simple-scalable helm chart. Same error. Config file follows after.

> level=info ts=2022-03-04T01:30:04.239648971Z caller=main.go:94 msg="Starting Loki" version="(version=2.4.1, branch=HEAD, revision=f61a4d261)"
level=error ts=2022-03-04T01:30:04.239975591Z caller=log.go:106 msg="error running loki" err="configdb is not supported as a Loki rules backend type\nerror initialising module: ruler-storage\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:285\nmain.main\n\t/src/loki/cmd/loki/main.go:96\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"

Please note in this config file there are some env expansion vars, I run using `-config.expand-env=true`
```
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

common:
  path_prefix: /var/loki
  replication_factor: 1
  ring:
    kvstore:
      store: memberlist

memberlist:
  join_members:
    - loki-memberlist
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s

ingester:
  chunk_idle_period: 2h
  chunk_block_size: 1536000
  chunk_encoding: snappy
  chunk_retain_period: 10m
  max_chunk_age: 2h
  max_transfer_retries: 0

  lifecycler:
    join_after: 60s
    observe_period: 5s
    final_sleep: 5s

schema_config:
  configs:
    - from: 2020-08-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  # boltdb stores both index and chunks in the S3 bucket
  boltdb_shipper:
    active_index_directory: /var/loki/index
    shared_store: s3
    cache_location: /var/loki/index_cache
    cache_ttl: 120h

  aws:
    s3: s3://${BUCKET_AWS_REGION}/${BUCKET_NAME}
    sse_encryption: true
    insecure: false

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 30m
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_query_parallelism: 16

chunk_store_config:
  chunk_cache_config:
    redis:
      endpoint: loki-redis:6379
      expiration: 6h

  max_look_back_period: ${RETENTION_PERIOD}

table_manager:
  # 14 day default retention period
  retention_deletes_enabled: true
  retention_period: ${RETENTION_PERIOD}

query_range:
  align_queries_with_step: true
  split_queries_by_interval: 15m
  max_retries: 5
  parallelise_shardable_queries: true
  cache_results: true
  results_cache:
    cache:
      redis:
        endpoint: loki-redis:6379
        expiration: 6h

querier:
  query_ingesters_within: 2h

frontend:
  compress_responses: true

compactor:
  shared_store: s3
  compaction_interval: 2h
```
