### ISSUE TITLE
Docs feedback: /clients/promtail/stages/timestamp.md

### ISSUE THREAD

**Issue by jonim8or** [grafana/loki#5469]
I noticed this behaviour. Not sure if it is a bug, or a missing documentation.
If timestamp is not the last stage in my pipeline, its value gets ignored. inspect shows that the value is parsed... but in loki it ends up using the time of scraping, not the time from the logline.
**Correct timestamp in loki:**
```
  - pack:
      labels:
         - msgTimeStamp
         - experiment
         - component
  #Tell promtail to use the timestamp in the file, not when it is scraped    
  - timestamp:
      source: msgTimeStamp
      format: 2006-01-02 15:04:05.000
      location: UTC
```

**Wrong timestamp in loki:**

```
  #Tell promtail to use the timestamp in the file, not when it is scraped    
  - timestamp:
      source: msgTimeStamp
      format: 2006-01-02 15:04:05.000
      location: UTC
  - pack:
      labels:
         - msgTimeStamp
         - experiment
         - component
```
If it is required that timestamp is the last, it should be documented clearly. If that is not a requirement, its a bug
