### ISSUE TITLE
can't get field from logfmt if label is defined in static_configs

### ISSUE THREAD

**Issue by dadamssg** [grafana/loki#5486]
**Describe the bug**
I've hardcoded a label of `host` in my promtail config to describe the server. I'm using logfmt formatted log lines for an nginx access log. In those logs there is `host="foobar.example.com"`. I can't target the access log line's `host` in my queries though. 

**To Reproduce**
```yaml
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      host: foobar
      job: varlogs
      __path__: /var/log/**/*log
```

Then generate a log line with `host="notfoobar"` and attempt to query based on `host` from the log line. For example here is my query:

```
sum by (hostname) (rate({filename="/var/log/nginx/access.logfmt.log",host="myserver"} | logfmt | label_format hostname=host [5m]))
```

I thought I might be able to use `label_format` but that still uses the `static_config`'s hardcoded label.

The value I want to query show's up in grafana's detected fields: 
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/881986/155921832-51471eb1-a695-41e0-899c-2ca3fcdccd79.png">

**Expected behavior**
I should be able to group by the log line's `host` field.
