### ISSUE TITLE
Promtail: /metrics endpoint fails when multiple clients are used

### ISSUE THREAD

**Issue by rfratto** [grafana/loki#5494]
**Describe the bug**
The `/metrics` endpoint returns an error when multiple clients are used:

```
$ curl localhost:80/metrics
An error has occurred while serving metrics:

collected metric "promtail_stream_lag_seconds" { label:<name:"filename" value:"/tmp/promtail.log" > label:<name:"host" value:"localhost:3100" > gauge:<value:0.287434 > } was collected before with the same name and label values
```

This behavior is visible against the latest Promtail commit (ead9444d7892e893ead34c1c5986dd25b2470cdb).

**To Reproduce**

1. Run Promtail with: `go run ./clients/cmd/promtail -config.file /tmp/promtail.yaml 2>&1 | tee /tmp/promtail.log` and the following config file (replacing the Loki URL as needed): 

```yaml
# /tmp/promtail.yaml
positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push
    external_labels:
      client: a
  - url: http://localhost:3100/loki/api/v1/push
    external_labels:
      client: b

scrape_configs:
- job_name: self-logging
  static_configs:
  - targets: [localhost]
    labels:
      job: promtail
      __path__: /tmp/promtail.log
```

2. Curl the metrics endpoint of Promtail: `curl localhost:80/metrics`

**Expected behavior**
Metrics should be returned without error.
