### ISSUE TITLE
Integrate Alibaba Cloud oss

### ISSUE THREAD

**Issue by tscuite** [grafana/loki#5499]
Will there be any plans to integrate Alibaba Cloud's object storage oss?

**Comment by kavirajk** [comment]
@tscuite we don't have any such immediate plans. But discussions, PRs and contributions are more than welcome :)

**Comment by tscuite** [comment]
I will read the source code carefully，learn, learn

**Comment by suraciii** [comment]
Just use aws/s3 store, AliOSS supports s3 compatible api.
```yaml
storage_config:
  aws:
    bucketnames:
    endpoint:
    access_key_id:
    secret_access_key:
    insecure: true
}
```
Notice `insecure: true` is necessary because AliOSS doesn't support chunked uploads.

**Comment by tscuite** [comment]
I'll check if all APIs are compatible when I'm free      https://help.aliyun.com/document_detail/64919.html#title-cds-fai-yxp

**Comment by liguozhong** [comment]
this pr: https://github.com/grafana/loki/pull/5522
```yaml
schema_config:
  configs:
  - from: 2020-05-15
    object_store: oss
    schema: v11
    index:
      prefix: loki_index_
      period: 168h

storage_config:
  alibaba:
    bucket: loki-chunk-test
    endpoint: oss-cn-beijing.aliyuncs.com
    access_key_id: <ak>
    secret_access_key: <sk>
```
