### ISSUE TITLE
primtail not parsed for nlog timestamp yyyy-mm-dd hh.MM.dd.tttt

### ISSUE THREAD

**Issue by naveenkumarsp** [grafana/loki#5501]
Promtail is failing to parse the timestamp of format  `yyyy-mm-dd hh.MM.dd.tttt`

[nlog-date format](https://github.com/NLog/NLog/wiki/Date-layout-renderer) i.e. "2000-01-01 00:00:00.0000" 

log line `2022-01-27 06:06:07.6405|INFO|host1|16160|fabric:/app1/service1|module1|log info is here.`

```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: D:/learning/loki/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: app_log
  pipeline_stages:
    - match:
        selector: '{job="app_logs"}'
        stages:
        - multiline:
              # Identify timestamps as first line of a multiline block. Enclose the string in single quotes.
              firstline: '^\[\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}.\d{3,4}\]'
              max_wait_time: 3s
              max_lines: 192
        - regex:
           expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3,4})\|(?P<level>(INFO|DEBUG|ERROR))\|(?P<host>[a-zA-Z0-9_]+)\|(?P<pid>[0-9]+)\|fabric:\/(?P<customer>[a-zA-Z0-9_]+)\/(?P<service>[a-zA-Z,0-9]+)\|(?P<message>(?s:.*))$'
        - labels:
           level:
           host:
           pid:
           service:
        - timestamp:
           source: timestamp
           format: '2022-02-17 06:06:07.1715'

  static_configs:
  - targets:
      - localhost
    labels:
      job: app_logs
      __path__: "D:/learning/loki/*.log"
```

**DEBUG**

```
PS D:\learning\loki> .\promtail-windows-amd64.exe --config.file=./loki/promtail-config.yaml --dry-run --inspect
Clients configured:
----------------------
url: http://localhost:3100/loki/api/v1/push
batchwait: 1s
batchsize: 1048576
follow_redirects: false
backoff_config:
  min_period: 500ms
  max_period: 5m0s
  max_retries: 10
timeout: 10s
tenant_id: ""
stream_lag_labels: filename

level=info ts=2022-03-01T12:11:10.3036294Z caller=server.go:260 http=[::]:9080 grpc=[::]:53389 msg="server listening on addresses"
level=info ts=2022-03-01T12:11:10.3036294Z caller=main.go:119 msg="Starting Promtail" version="(version=2.4.2, branch=HEAD, revision=525040a32)"
level=info ts=2022-03-01T12:11:15.3032838Z caller=filetargetmanager.go:255 msg="Adding target" key="D:/learning/loki/*.log:{job=\"app_logs\"}"
level=info ts=2022-03-01T12:11:15.3042847Z caller=tailer.go:126 component=tailer msg="tail routine: started" path=D:\learning\loki\app.log
ts=2022-03-01T12:11:15.3042847Z caller=log.go:168 level=info msg="Seeked D:\\learning\\loki\\app.log - &{Offset:0 Whence:0}"
[inspect: regex stage]:
{stages.Entry}.Extracted["customer"]:
        +: app1
{stages.Entry}.Extracted["host"]:
        +: host1
{stages.Entry}.Extracted["level"]:
        +: INFO
{stages.Entry}.Extracted["message"]:
        +: module1|log info is here.
{stages.Entry}.Extracted["pid"]:
        +: 16160
{stages.Entry}.Extracted["service"]:
        +: service1
{stages.Entry}.Extracted["timestamp"]:
        +: 2022-01-27 06:06:07.6405
[inspect: labels stage]:
{stages.Entry}.Entry.Labels:
        -: {filename="D:\\learning\\loki\\app.log", job="app_logs"}
        +: {filename="D:\\learning\\loki\\app.log", host="host1", job="app_logs", level="INFO", pid="16160", service="service1"}
[inspect: timestamp stage]: none
2022-03-01T17:41:15.3052837+0530{filename="D:\\learning\\loki\\app.log", host="host1", job="app_logs", level="INFO", pid="16160", service="service1"}   2022-01-27 06:06:07.6405|INFO|host1|16160|fabric:/app1/service1|module1|log info is here.
```
