### ISSUE TITLE
cassandra dose not work

### ISSUE THREAD

**Issue by tt945** [grafana/loki#551]
It seems  `cassandra` is supported.

![2019-05-07_151148](https://user-images.githubusercontent.com/11399406/57279013-85b62900-70da-11e9-992e-8bd74f4b78ae.png)

 But when I store data, there is error (table doesn't exist),
![2019-05-07_151259](https://user-images.githubusercontent.com/11399406/57279057-a1213400-70da-11e9-8079-2f189bf7b417.png)

Now loki still doesn't support cassandra?

**Comment by daixiang0** [comment]
Which version of cassandra do you use?

**Comment by tt945** [comment]
> Which version of cassandra do you use?

cassandra 3.11.4 from official docker image

I don't think it's the problem of cassandra version. Actually  loki has a table client for table management including create, drop table, but it was not called in code.

**Comment by mizeng** [comment]
@tt945 did you resolve cassandra issue in Loki? I'm also looking for how to use cassandra in Loki. Could you also share your config of cassandra in Loki config?

**Comment by mizeng** [comment]
@tt945 could you help to share one sample Loki config using Cassandra too?

**Comment by mizeng** [comment]
Finally my config of Cassandra works. Please pull the latest Loki Image since one bug of "lower" case Cassandra config just got fixed 3-4 days ago.
Then you can use config like below to work

```
storage_config:
  cassandra:
    username: cassandra
    password: cassandra
    addresses: 127.0.0.1
    auth: true
    keyspace: lokiindex
```

**Comment by zwennesm** [comment]
@mizeng Which native protocol are you using for Cassandra?

I am running `[cqlsh 5.0.1 | Cassandra 3.11.1 | CQL spec 3.4.4 | Native protocol v4]` but I still get the following error: 

```
main.go:71 msg="error initialising loki" err="error initialising module: table-manager: gocql: unable to create session: unable to discover protocol version: dial tcp IP:9042: i/o timeout"
```

**Comment by mizeng** [comment]
mine: `[cqlsh 5.0.1 | Cassandra 3.11.4 | CQL spec 3.4.4 | Native protocol v4]`

**Comment by zwennesm** [comment]
So it seems that's not the issue. I am using the following config

```
  schema_config:
    configs:
    - from: "2019-07-01"
      store: cassandra
      object_store: filesystem
      schema: v9
      index:
        prefix: cassandra_table
        period: 168h

  storage_config:
    cassandra:
      username: cassandra
      password: cassandra
      addresses: cassandra-0.cassandra.loki.svc.cluster.local,cassandra-1.cassandra.loki.svc.cluster.local,cassandra-2.cassandra.loki.svc.cluster.local
      disable_initial_host_lookup: true
      replication_factor: 3
      auth: true
      keyspace: lokiindex
      timeout: 20000
      connect_timeout: 20000
    filesystem:
      directory: /data/loki/chunks

  table_manager:
    retention_deletes_enabled: true
    retention_period: "48h"
```

**Comment by zwennesm** [comment]
Update for whoever hits the same error: removing the `timeout` and `connect_timeout` from the configuration seemed to have solved the issue.

**Comment by mizeng** [comment]
mine is as below, I use timeout and connect_timeout which is working normal.
```
schema_config:
        configs:
        - from: 2018-04-15
          store: cassandra
          object_store: s3
          schema: v9
          index:
            prefix: index_
            period: 168h

      storage_config:
        cassandra:
          username: cassandra
          password: cassandra
          addresses: cassandra_host
          auth: true
          keyspace: lokiindex
          timeout: 10s
          connect_timeout: 10s
```
