### ISSUE TITLE
Wrong letter in documentation about client configuration in promtail

### ISSUE THREAD

**Issue by kozicpetar** [grafana/loki#5511]
**Describe the bug**
In the documentation, Promtail configuration for client is declared as `clients:`

https://grafana.com/docs/loki/latest/clients/promtail/configuration/#clients

But if I put configuration in `promtail.yaml` with `clients:` like on example below

```
clients:
 url: some_url
  backoff_config:
    max_period: 10m
    max_retries: 10
    min_period: 1s
  batchsize: 134217728
```
I got error:
```
line 15: cannot unmarshal !!map into []client.Config
``` 

when I change word `clients:` to `client:`

everything works well:

```
client:
 url: some_url
  backoff_config:
    max_period: 10m
    max_retries: 10
    min_period: 1s
  batchsize: 134217728
```

**To Reproduce**
1. Install promtail
2. Set promtail.yaml configuration with
```
clients:
 url: some_url
  backoff_config:
    max_period: 10m
    max_retries: 10
    min_period: 1s
  batchsize: 134217728
```
3. Run promtail `promtail --config.file promtail.yaml`

**Expected behavior**
Expect to works with `clients:` statements or to change documentation.

**Environment:**
 - Infrastructure: Ubuntu Server
 - Deployment tool: 

- Promtail version:  `promtail, version 2.4.2 (branch: HEAD, revision: 525040a32)`

**Screenshots, Promtail config, or terminal output**

**Comment by dannykopping** [comment]
Hi @kozicpetar 

This isn't a bug; we support `client` as we originally only allowed a single one - this approach is now deprecated, and with `clients` you need to provide a list of clients:

```yaml
clients:
- url: some_url
  backoff_config:
    max_period: 10m
    max_retries: 10
    min_period: 1s
  batchsize: 134217728
```
