### ISSUE TITLE
Ingester connects to an old redis endpoint ip address

### ISSUE THREAD

**Issue by gmavadiy** [grafana/loki#5516]
**Describe the bug**
Ingester keeps trying to connect to an old redis endpoint ip and throws chunkredis failed to get|put errors. If ingester pod is restarted it fails to come to a ready state and fails to join back the ring.

**To Reproduce**
1. Loki v2.3.0 in distributed mode with redis cluster on kubernetes.
2. Configure redis endpoints to point to individual service name. For example 
```
chunk_store_config:
      chunk_cache_config:
        redis:
          endpoint: redis-0:6379,redis-1:6379,redis-2:6379,redis-3:6379,redis-4:6379,redis-5:6379
          expiration: 168h
          db: 0
```
3. Restart a redis pod (state of cluster is still ok as ip is updated in node.conf automatically)
4. Observe that ingesters will start throwing connection refused errors
5. At this point restart ingester and it will fail to come up in ready state or join the ring
6. Distributor will show that ingester as unhealthy

**Expected behavior**
Ingester should either use the service name (specified in loki config) or flush the old ip address

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: helm
 - Grafana Loki v 2.3.0
 - Redis v6.2.6

**Screenshots, Promtail config, or terminal output**
```
level=error ts=2022-03-01T22:29:10.943373287Z caller=redis_cache.go:72 msg="failed to get from redis" name=chunksredis err="dial tcp 10.1.1.2:6379: connect: connection refused"
level=error ts=2022-03-01T22:29:11.131041847Z caller=redis_cache.go:100 msg="failed to put to redis" name=chunksredis err="dial tcp 10.1.1.2:6379: connect: connection refused"
```
10.1.1.2 is the old ip address.
