### ISSUE TITLE
can't log through promtail via syslog

### ISSUE THREAD

**Issue by PietroPasotti** [grafana/loki#5528]
**Describe the bug**
I have seen #5409 and so I have also tried building promtail from source to ensure I had the latest version. 
I deployed loki-k8s and a tester charm with promtail. Running python3, I tried from the tester container:

* stdlib's `syslog.syslog('foo')`
* `logging.handlers.SyslogHandler(address=('localhost', 1514))`
* `pysyslogclient.SyslogClientRFC5424('localhost', 1514)`

None of these seems to get any logs through promtail or raise any exceptions.
Also promtail does not display any error or warning, even with log_level: debug.

**Expected behavior**
Promtail to log these messages.

**Environment:**
 - Infrastructure: microk8s

**Screenshots, Promtail config, or terminal output**
```bash
root@loki-tester-0:/# /opt/promtail/promtail-linux-amd64 --config.file=/etc/promtail/promtai
l_config.yaml                                                                               
level=info ts=2022-03-03T13:12:43.055551177Z caller=syslogtarget.go:108 msg="syslog listenin
g on address" address=127.0.0.1:1514 tls=false                                              
level=info ts=2022-03-03T13:12:43.055871084Z caller=server.go:260 http=[::]:9080 grpc=[::]:9
095 msg="server listening on addresses"                                                     
level=info ts=2022-03-03T13:12:43.055956777Z caller=main.go:119 msg="Starting Promtail" vers
ion="(version=, branch=, revision=)"                                                        
level=info ts=2022-03-03T13:12:48.056078911Z caller=filetargetmanager.go:328 msg="Adding tar
get" key="/loki_tester_msgs.txt:{job=\"juju_cos_78956f5b-9026-45a9-8ca8-d33e0727332e_loki-te
ster_loki-tester_0_loki-tester\", juju_application=\"loki-tester\", juju_charm=\"loki-tester
\", juju_model=\"cos\", juju_model_uuid=\"78956f5b-9026-45a9-8ca8-d33e0727332e\", juju_unit=
\"loki-tester/0\"}"                                                                         
level=info ts=2022-03-03T13:13:08.057201009Z caller=filetarget.go:252 msg="watching new dire
ctory" directory=/                                                                          
```

```yaml
clients:                                                                                    
- url: http://loki-k8s-0.loki-k8s-endpoints.cos.svc.cluster.local:3100/loki/api/v1/push     
positions:                                                                                  
  filename: /opt/promtail/positions.yaml                                                    
scrape_configs:                                                                             
- job_name: system                                                                          
  static_configs:                                                                           
  - labels:                                                                                 
      __path__: /loki_tester_msgs.txt                                                       
      job: juju_cos_78956f5b-9026-45a9-8ca8-d33e0727332e_loki-tester_loki-tester_0_loki-test
er                                                                                          
      juju_application: loki-tester                                                         
      juju_charm: loki-tester                                                               
      juju_model: cos                                                                       
      juju_model_uuid: 78956f5b-9026-45a9-8ca8-d33e0727332e                                 
      juju_unit: loki-tester/0                                                              
    targets:                                                                                
    - localhost                                                                             
- job_name: syslog                                                                          
  syslog:                                                                                   
    label_structured_data: true                                                             
    labels:                                                                                 
      job: juju_cos_78956f5b-9026-45a9-8ca8-d33e0727332e_loki-tester_loki-tester_0_loki-test
er_syslog                                                                                   
      juju_application: loki-tester                                                         
      juju_charm: loki-tester                                                               
      juju_model: cos                                                                       
      juju_model_uuid: 78956f5b-9026-45a9-8ca8-d33e0727332e                                 
      juju_unit: loki-tester/0                                                              
    listen_address: 127.0.0.1:1514                                                          
server:                                                                                     
  grpc_listen_port: 9095                                                                    
  http_listen_port: 9080                                                                    
```
