### ISSUE TITLE
flush.go:221 org_id=fake msg="failed to flush user"

### ISSUE THREAD

**Issue by mzupan** [grafana/loki#5531]
**Describe the bug**

Running the loki-distrubted helm chart. It's working but not flushing logs to s3. In the ingester I'm getting the following error with debug logging enabled

```
level=info ts=2022-03-03T18:13:48.179152249Z caller=table_manager.go:171 msg="uploading tables"
level=debug ts=2022-03-03T18:13:49.283258027Z caller=flush.go:217 msg="flushing stream" userid=fake fp=e17ca5111fda737e immediate=false
level=error ts=2022-03-03T18:13:49.292709334Z caller=flush.go:221 org_id=fake msg="failed to flush user" err="open ZmFrZS9lMTdjYTUxMTFmZGE3MzdlOjE3ZjUwZjRhNWZjOjE3ZjUwZjUyMjEyOmFkOGVkZDFk: permission denied"
```

I'm not sure where it's getting this permissions denied as it seems to be a filesystem issue but I can't track it down. 

**To Reproduce**
1. Using the following helm overrides

```
loki:
  containerSecurityContext:
    readOnlyRootFilesystem: false
  
  config: |
    auth_enabled: false
    
    server:
      http_listen_port: 3100
      log_level: debug

    distributor:
      ring:
        kvstore:
          store: memberlist
    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 2m
      chunk_block_size: 2621440
      chunk_encoding: snappy
      chunk_retain_period: 1m
      max_transfer_retries: 0
      wal:
        enabled: true
        dir: /var/loki/wal
      
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
  
    schema_config:
      configs:
      - from: 2020-09-07
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: loki_index_
          period: 24h

    storage_config:
      aws:
        s3: s3://us-east-1/company-loki-storage-test
        region: us-east-1
        s3forcepathstyle: true
      boltdb_shipper:
        shared_store: s3
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 1h
        index_gateway_client:
          server_address: dns:///{{ include "loki.indexGatewayFullname" . }}:9095

    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
    query_range:
      align_queries_with_step: true
      max_retries: 5
      split_queries_by_interval: 15m
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h
    
    frontend_worker:
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
    
    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100
    
    compactor:
      working_directory: /var/loki/compactor
      shared_store: s3

    table_manager:
     retention_deletes_enabled: true
     retention_period: 672h

    ruler:
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111111111:role/loki-test

gateway:
  serverSnippet: "client_max_body_size 100M;"

indexGateway:
  enabled: true

  persistence:
    enabled: true

querier:
  replicas: 1
  extraVolumes:
    - name: bolt-db
      emptyDir: {}
  extraVolumeMounts:
    - name: bolt-db
      mountPath: /var/loki

tableManager:
  enabled: true

ingester:
  persistence:
    enabled: true
    size: 50Gi

```

**Expected behavior**

expect logs in the s3 bucket

**Environment:**
 - Infrastructure: Kubernetes(eks)
 - Deployment tool: helm

**Comment by mzupan** [comment]
this was an oversight that the schema config had filesystem so it needed to be

```
    schema_config:
      configs:
      - from: 2020-09-07
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: loki_index_
          period: 24h
```

The `object_store` needs to be s3
