### ISSUE TITLE
Promtail missing internal telemetry about systemd-journal target

### ISSUE THREAD

**Issue by m1keil** [grafana/loki#5554]
We have a promtail configured with two scrape configs: `consulagent_sd_configs` & `systemd-journal`
Inspecting the output from the metrics at `/metrics`, it seems that Promtail only exposes data relevant to file-based log tailing. 

There is no data about metrics that were collected via the `systemd-journal` target at all. 
I'm not even sure if the total metrics such as 
- `promtail_targets_active_total`, 
- `promtail_dropped_bytes_total` 
- `promtail_dropped_entries_total`
- `promtail_encoded_bytes_total`
Include data from `systemd-journal` or not.

This makes it difficult to monitor log volume and errors from promtail.

**Comment by dannykopping** [comment]
Are you sure it's configured to scrape logs correctly from the journal? If a target isn't working, it won't expose metrics.
Does Promtail log anything related to the journal?

PS: please use the standard bug issue format next time you report a bug. We need the version number, OS, etc when evaluating issues.

**Comment by m1keil** [comment]
Yes, I'm sure.

Here's my scrape config:

```
scrape_configs:
  - job_name: systemd-journal
    journal:
      labels:
        job: systemd-journal
      path: /var/log/journal
      json: false
    relabel_configs:
    - source_labels: [__journal__systemd_unit]
      regex: '(user@\d+\.service|session-\d+\.scope)'
      action: drop
    - source_labels: [__journal__systemd_unit]
      target_label: systemd_unit
    - source_labels: [__journal__systemd_hostname]
      target_label: instance

  - job_name: nomad-logs
```

And here's a proof promtail tails journald:
```
cat /alloc/promtail-positions.yaml 
positions:
  <redacted>
  /opt/nomad/alloc/2918219e-084e-5568-f864-483e0c74ef70/alloc/logs/whoami.stderr.0: "46"
  /opt/nomad/alloc/2918219e-084e-5568-f864-483e0c74ef70/alloc/logs/whoami.stdout.0: "0"
  journal-systemd-journal: s=00000000000000000000000000000000;i=e9d47c;b=e3eb64fe1acf44b08fd622d2a0add379;m=5d4bfaeb80c;t=5d99bb971fac8;x=232bc39003643f04
```

> PS: please use the standard bug issue format next time you report a bug. We need the version number, OS, etc when evaluating issues.

Sorry about that, the bug template is a bit generic (wasn't actually asking for OS or promtail version) and I sort of didn't notice.

I'm using latest promtail v2.4.2 on Linux (via docker image).
