### ISSUE TITLE
field beaker_token not found in type client.raw

### ISSUE THREAD

**Issue by tennox** [grafana/loki#5565]
**Describe the bug**
I tried to set the bearer token to authenticate loki client, but the following was printed in console:
```
Unable to parse config: /etc/promtail/config.yml: yaml: unmarshal errors:
  line 13: field beaker_token not found in type client.raw
```

**To Reproduce**
1. `config.yml`
```
client:
  url: https://loki.my.org/loki/api/v1/push
  beaker_token_file: /var/run/loki_token
  external_labels:
    promtail: rose-pi
# ...
```
2. `docker-compose.yml`
```
version: "2.3"
services:
  promtail:
    image: grafana/promtail:main # main bc. https://github.com/grafana/loki/pull/4911
    volumes:
      - ./config.yml:/etc/promtail/config.yml
      - ./loki_token:/var/run/loki_token
      - ./data:/etc/promtail
```
4. **`docker-compose up`**

**Environment:**
 - Infrastructure: docker on `Raspbian GNU/Linux 10 (buster)`
 - Deployment tool: docker-compose
