### ISSUE TITLE
Behavior similar to memory leak in Loki Distributor

### ISSUE THREAD

**Issue by putrasattvika** [grafana/loki#5569]
**Describe the bug**
After upgrading to v2.3 and then to v2.4 (from v2.1), we noticed a constant growth of memory usage on Distributor pods. Their memory usage will always increase over time, to the point where it will almost reach our resource limit and will need to be restarted. This memory usage does not seem to be related to our ingestion rate. Below are some graphs of 24hr period: (left) memory usage of Distributor pods in MiB, (right) rate of bytes received by Distributor pods over 5m period.

![image](https://user-images.githubusercontent.com/9216079/157160206-1ab29747-ef36-4d8f-b269-484ead41dadd.png)

To be fair, the memory we allocated to our Distributor pods is relatively low (~128MiB), but this was more than enough for v2.1 where the memory usage was relatively constant (see below).

We suspect (but currently have no proof) that this is caused by an LRU cache implemented in #3092 (this feature is not present in v2.1). Unfortunately, we can't really confirm this suspicion as there are no metrics that expose the current size of the cache.

Here's a heap profile of one of our Distributor pods after running for 16hr: [loki-distributor.22-03-08T10-32-46.pb.gz](https://github.com/grafana/loki/files/8202498/loki-distributor.22-03-08T10-32-46.pb.gz) (also uploaded to [flamegraph.com](https://flamegraph.com/share/255d707e-9e91-11ec-bea9-8270a7dd3a05)).

**To Reproduce**
1. Started Loki (v2.4.2)
2. Ingest our logs like usual
3. Query memory usage as exported by cadvisor (`container_memory_working_set_bytes`

**Expected behavior**
Memory usage of Distributor in v2.3++ to be relatively constant like in v2.1. Below is memory usage graph of our v2.1 Distributors (in MiB), before we upgraded it.
![image](https://user-images.githubusercontent.com/9216079/157160524-cf52b4b5-f7a6-4fe3-b1fc-84e6278811d8.png)

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: our own Kubernetes YAML files, based on jsonnet

**Comment by dannykopping** [comment]
Thanks for reporting this @putrasattvika 

Please provide the config you are using as well. This will help us investigate this apparent bug.

**Comment by putrasattvika** [comment]
This is the config we're currently using:

```
chunk_store_config:
  chunk_cache_config:
    enable_fifocache: false
    memcached:
      batch_size: 100
    memcached_client:
      host: loki.memcached.<REDACTED>

  max_look_back_period: 8904h

  write_dedupe_cache_config:
    enable_fifocache: false
    memcached:
      batch_size: 100
    memcached_client:
      host: loki.memcached.<REDACTED>

ingester:
  chunk_idle_period: 30m
  chunk_retain_period: 10m

  lifecycler:
    interface_names:
    - eth0
    join_after: 1m
    ring:
      kvstore:
        etcd:
          endpoints: <REDACTED>
        prefix: /loki/collectors/
        store: etcd
      replication_factor: 3

  max_transfer_retries: 0

  wal:
    dir: /loki/wal
    enabled: true
    replay_memory_ceiling: 512MB

ingester_client:
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
  remote_timeout: 1s

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

schema_config:
  configs:
  - chunks:
      period: 168h
      prefix: loki_prod_chunk_
    from: '2019-11-25'
    index:
      period: 168h
      prefix: loki_prod_index_
    object_store: gcs
    schema: v10
    store: aws

  - from: '2020-07-22'
    index:
      period: 168h
      prefix: loki_prod_index_
    object_store: gcs
    schema: v11
    store: aws

server:
  graceful_shutdown_timeout: 5s
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  http_server_idle_timeout: 120s

storage_config:
  aws:
    dynamodb:
      dynamodb_url: dynamodb://<REDACTED>

  gcs:
    bucket_name: <REDACTED>

  index_queries_cache_config:
    enable_fifocache: false
    memcached:
      batch_size: 100
    memcached_client:
      host: loki.memcached.<REDACTED>

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 1
    inactive_write_throughput: 1
    provisioned_read_throughput: 1
    provisioned_write_throughput: 1

  index_tables_provisioning:
    enable_inactive_throughput_on_demand_mode: true
    enable_ondemand_throughput_mode: true

  retention_deletes_enabled: true
  retention_period: 8904h
```
