### ISSUE TITLE
query caching not working

### ISSUE THREAD

**Issue by yongzhang** [grafana/loki#5583]
**Describe the bug**
I added redis as caching for query_range, looks like it doesn't work.

**To Reproduce**
1. Started Loki (SHA or version) v2.3.0
2. Started Promtail (SHA or version) to tail '...'  v2.3.0
3. Configs:
```
query_range:
  split_queries_by_interval: 24h
  results_cache:
    cache:
      redis:
        endpoint: localhost:6379
        expiration: 8h
        db: 0
  cache_results: true
```
4. Query: 
Select a time range from grafana like this and run multiple times:
![image](https://user-images.githubusercontent.com/15604715/157366215-e2cc7b80-46a0-493a-a767-4426b0706951.png)

5. Check redis, no keys found:
```
redis-cli -h localhost
localhost:6379> KEYS *
(empty list or set)
```
6. Check loki logs, no error logs found.

**Expected behavior**
Should redis cache the query?
