### ISSUE TITLE
Frontend worker uses IP addr to connect to query FE, preventing use of mTLS with hostname in SAN

### ISSUE THREAD

**Issue by atomic77** [grafana/loki#5592]
**Describe the bug**

We are trying to protect communication between the queriers and query frontend with mTLS. 

When we start up the querier with a `frontend_address` as a regular DNS A-record, we are getting an error like:
```
level=error ts=2022-03-01T21:18:00.632904483Z caller=frontend_processor.go:63 msg="error contacting frontend" address=<ip>:<port> err="rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: x509: cannot validate certificate for <ip> because it doesn't contain any IP SANs\""
```

We've used hostnames in the SAN of the server cert for other service communications without any issue, the use of the resolved IP address appears to be particular to the frontend workers. 

**To Reproduce**

Configure a `frontend_worker` to connect to a host using TLS:
```yaml
    frontend_worker:
      frontend_address: <frontend-host>:<port>
      grpc_client_config:
        tls_enabled: true  
        tls_cert_path: <cert>
        tls_key_path: <key>
        tls_ca_path: <ca>

```
Adding the `tls_insecure_skip_verify: true` option to the `grpc_client_config` block is a "workaround", but not usable for obvious reasons. We also don't have the option of adding an IP SAN to our server certs due to internal policies. 

**Expected behavior**

We would like to be able to configure a frontend with an A-record that bypasses the IP lookup and makes the gRPC connection with the DNS entry.  Support for this in the SRV case looks like it would require a change to the cortex or grafana/dskit libraries. We will provide a potential patch shortly for community feedback!

**Environment:**
 - Infrastructure: Bare-metal
 - Deployment tool: Manual 

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
