### ISSUE TITLE
error expanding template: error executing template

### ISSUE THREAD

**Issue by AllenzhLi** [grafana/loki#5614]
**Describe the bug**
loki alert rule:

```
name: yyyy
interval: 1m
rules:
  - alert: yyyy_test
    expr: count_over_time({product="cbs", event_name="Qcloud_API_hb_depot"}[1m]) > 0
    labels:
      alert_class: log
    annotations: 
      desc: |
        {{ with query "{product='cbs', event_name='Qcloud_API_hb_depot'}" }}
           {{ . | first }}
        {{ end }}
```
result:

`     "desc": "<error expanding template: error executing template __alert_yyyy_test: template: __alert_yyyy_test:1:82: executing \"__alert_yyyy_test\" at <query \"{product='cbs', event_name='Qcloud_API_hb_depot'}\">: error calling query: parse error at line 1, col 14: invalid char literal>",`
