### ISSUE TITLE
operator: Use tenant name as ids for tenant-mode openshift-logging

### ISSUE THREAD

**Issue by periklis** [grafana/loki#5623]
**Is your feature request related to a problem? Please describe.**
Using the tenant mode `openshift-logging` is a dedicated feature for fully-automated generation of the lokistack-gateway's tenants configuration on OpenShift. The generator yields three up-front known tenants (i.e. `application`, `infrastructure`, `audit`) dedicated to support multi-tenancy on OpenShift one per log type (i.e. application logs, infrastructure logs, audit logs).

However the present implementation is using UUIDs for the tenant IDs which makes collector configuration quite hard, i.e. the collector's operator needs to read the lokistack-gateway secret that holds the `tenants.yaml` to extract the ids. This is obviously creating a dependency between the loki-operator reconciling and owning the secret `tenants.yaml` with any other operator managing the collector and its configuration. This dependency is in addition an unwanted contract between both control loops on the `tenants.yaml` field. Thus this makes independent operator upgrades more difficult in future.

**Describe the solution you'd like**
Any controller/operator of the collector configuration should be able to generate the configuration w/o needing to read the `tenants.yaml`. The solution for this is to use the tenant name additionaly as an id. The generated `tenants.yaml` should look like this:
```yaml
tenants:
- name: application
  id: application
  openshift:
    ...
  opa:
   ...
- name: infrastructure
  id: infrastructure
  openshift:
   ...
  opa:
   ...
- name: audit
  id: audit
  openshift:
   ...
  opa:
  ...
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
