### ISSUE TITLE
Loki 502 when change redis-cluster config

### ISSUE THREAD

**Issue by Juntaran** [grafana/loki#5652]
![image](https://user-images.githubusercontent.com/13732099/158778932-4b87bfc3-a929-4025-b8cf-cd10f5713041.png)

we can see this monitor in pic

I have a redis-cluster

when I use one of redis-cluster ip, to 

```
index_queries_cache_config:
    redis:
        endpoint: 1.1.1.1

chunk_cache_config:
    redis:
        endpoint: 1.1.1.1

write_dedupe_cache_config:
    redis:
        endpoint: 1.1.1.1

query_range:
    results_cache:
        cache:
            redis:
                endpoint: 1.1.1.1
```

it's ok, but i change endpoint from 1.1.1.1 to  1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4
then, restart loki, 502 error
