### ISSUE TITLE
RESPONSE ERROR (ServiceCode=BlobNotFound)

### ISSUE THREAD

**Issue by ronyrv13** [grafana/loki#5668]
**Bug Description**

We were using minio-gateway to store loki chunks on azure blob storage, but as now loki is supported with azure storage services, we updated the storage config with azure (using same storage account and container.)

But loki is unable to fetch old logs which it pushed through minio-gateway to same azure storage container.
Getting below error-

github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /src/loki/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42 ===== RESPONSE ERROR (ServiceCode=BlobNotFound) ===== Description=The specified blob does not exist. RequestId:204e6414-101e-011e-33a1-3a005a000000 Time:2022-03-18T08:22:09.0083741Z, Details: Code: BlobNotFound GET https://lokidev.blob.core.windows.net/azure-rony-use2/fake/a0e1f3edcccc986d-17f9ba4b06a-17f9ba946f7-eb52e710?timeout=30 Authorization: REDACTED User-Agent: [Azure-Storage/0.13 (go1.17.2; linux)] X-Ms-Client-Request-Id: [96d7a335-b9cb-421d-5db9-2876b71612b1] X-Ms-Date: [Fri, 18 Mar 2022 08:22:09 GMT] X-Ms-Version: [2019-12-12] -------------------------------------------------------------------------------- RESPONSE Status: 404 The specified blob does not exist. Content-Length: [215] Content-Type: [application/xml] Date: [Fri, 18 Mar 2022 08:22:08 GMT] Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0] X-Ms-Client-Request-Id: [96d7a335-b9cb-421d-5db9-2876b71612b1] X-Ms-Error-Code: [BlobNotFound] X-Ms-Request-Id: [204e6414-101e-011e-33a1-3a005a000000] X-Ms-Version: [2019-12-12]

when i checked in azure storage container for the chunk mentioned in error message, i found that chunk name is in this format- 
a0e1f3edcccc986d:17f9ba4b06a:17f9ba946f7:eb52e710
and loki is searching with name a0e1f3edcccc986d-17f9ba4b06a-17f9ba946f7-eb52e710

Difference in seperators !! ..\

**Environment:**

 - Infrastructure: AKS Kubernetes
 - Loki is deployed in microservice mode
 - Following are config used so -

```
   auth_enabled: false
    chunk_store_config:
        chunk_cache_config:
            memcached:
                batch_size: 100
                parallelism: 100
            memcached_client:
                consistent_hash: true
                host: memcached.monitoring-system.svc.cluster.local
                service: memcached-client
        max_look_back_period: 0
    distributor:
        ring:
            kvstore:
                store: memberlist
    frontend:
        compress_responses: true
        log_queries_longer_than: 5s
        max_outstanding_per_tenant: 200
    frontend_worker:
        frontend_address: query-frontend.monitoring-system.svc.cluster.local:9095
        grpc_client_config:
            max_send_msg_size: 1.048576e+08
        parallelism: 2
    ingester:
        chunk_block_size: 262144
        chunk_idle_period: 15m
        chunk_encoding: snappy
        chunk_retain_period: 15m
        lifecycler:
            heartbeat_period: 5s
            interface_names:
              - eth0
            join_after: 30s
            num_tokens: 512
            ring:
                heartbeat_timeout: 1m
                kvstore:
                    store: memberlist
                replication_factor: 3
        max_transfer_retries: 0
        wal:
          dir: /var/loki/wal
    ingester_client:
        grpc_client_config:
            max_recv_msg_size: 6.7108864e+07
        remote_timeout: 1s
    limits_config:
        enforce_metric_name: false
        ingestion_burst_size_mb: 20
        ingestion_rate_mb: 10
        ingestion_rate_strategy: global
        max_cache_freshness_per_query: 10m
        max_concurrent_tail_requests: 60
        max_global_streams_per_user: 10000
        max_query_length: 12000h
        max_query_parallelism: 16
        max_streams_per_user: 0
        reject_old_samples: true
        reject_old_samples_max_age: 168h
    memberlist:
        abort_if_cluster_join_fails: false
        bind_port: 7946
        join_members:
          - gossip-ring.monitoring-system.svc.cluster.local
        max_join_backoff: 1m
        max_join_retries: 10
        min_join_backoff: 1s
    querier:
        max_concurrent: 50
        query_ingesters_within: 2h
    query_range:
        align_queries_with_step: true
        cache_results: true
        max_retries: 5
        results_cache:
            cache:
                memcached_client:
                    consistent_hash: true
                    host: memcached-frontend.monitoring-system.svc.cluster.local
                    max_idle_conns: 16
                    service: memcached-client
                    timeout: 500ms
                    update_interval: 1m
        split_queries_by_interval: 30m
    schema_config:
        configs:
          - from: "2020-10-08"
            index:
                period: 24h
                prefix: monitoring-system_index_
            object_store: azure
            schema: v11
            store: boltdb-shipper
    server:
        graceful_shutdown_timeout: 5s
        grpc_server_max_concurrent_streams: 1000
        grpc_server_max_recv_msg_size: 1.048576e+08
        grpc_server_max_send_msg_size: 1.048576e+08
        http_listen_port: 3100
        http_server_idle_timeout: 120s
        http_server_write_timeout: 1m
    storage_config:
        azure:
          container_name: ${CONTAINER_NAME}
          account_name: ${STORAGE_ACCOUNT_NAME}
          account_key: ${STORAGE_ACCOUNT_KEY}
        boltdb_shipper:
            shared_store: azure
        index_queries_cache_config:
            memcached:
                batch_size: 100
                parallelism: 100
            memcached_client:
                consistent_hash: true
                host: memcached-index-queries.monitoring-system.svc.cluster.local
                service: memcached-client
    table_manager:
        creation_grace_period: 3h
        poll_interval: 10m
        retention_deletes_enabled: true
        retention_period: 720h
    compactor:
        shared_store: azure
```
Can anyone please help me in this?
