### ISSUE TITLE
When using S3, the data is not being stored in the correct location.

### ISSUE THREAD

**Issue by guvmao** [grafana/loki#5671]
**Describe the bug**
The following configuration sets an upper directory:
>    active_index_directory: /loki/index
>    cache_location: /loki/boltdb-cache

But no subdirectories are created inside the S3 bucket.

**To Reproduce**

**Expected behavior**
index and fake are stored in `Bucketname/loki/`

For example:
`Bucketname/loki/index`
`Bucketname/loki/fake`

**Environment:**

**Config:**
```
schema_config:
  configs:
  - from: 2020-08-01
    store: boltdb-shipper
    object_store: aws
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb_shipper:
    shared_store: aws
    #shared_store: filesystem
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache

  aws:
    s3: s3://__S3_ACCESS_KEY__:__S3_SECRET_KEY__@us-east-1
    bucketnames: Bucketname
    # Enable AES256 AWS server-side encryption
    sse_encryption: true
    # Disable https on S3 connection.
    insecure: true
    # Set this to `true` to force the request to use path-style addressing.
    s3forcepathstyle: true

```

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/40655731/158999813-27cbc1be-9725-4765-a4ce-fec6b62ede10.png)
