### ISSUE TITLE
Docker Loki Driver ARM64

### ISSUE THREAD

**Issue by feniarus** [grafana/loki#5682]
**Is your feature request related to a problem? Please describe.**
I tried installing the Loki Docker Driver but it doesn't work because it is for AMD64 only at the moment. 

**Describe the solution you'd like**
Adding support for ARM64 and ARM/v7 
Can be done by cross compiling even on AMD64
As example via `GOOS=linux GOARCH=arm GOARM=7 go build ./clients/cmd/docker-driver` 
will build the docker-driver for arm/v7 on AMD64

**Describe alternatives you've considered**
A Version for ARM64/v8 of the Loki docker plugin is on Docker hub available
[miacis/loki-docker-driver](https://hub.docker.com/r/miacis/loki-docker-driver)

**Comment by cstyan** [comment]
I think this is something we'd be open to accepting a PR for, have a look at [this](https://github.com/grafana/loki/pull/5354) in progress PR that's adding arm64 support for another component as an example.

**Comment by nepeat** [comment]
Linking this for reference if anyone else stumbles upon this issue.

#1973 is tracking a similar issue but for armv6 and armv7 due to its age (Apr 22, 2020)

**Comment by mattmeye** [comment]
+1

**Comment by fede843** [comment]
same here. +1

**Comment by adiii717** [comment]
same here +1

**Comment by francescor** [comment]
we need it badly, too

**Comment by peterhirn** [comment]
I ran into some stability issues on arm using the docker driver so I switched over to journald which works very well for my setup. Pasting my config here for reference.

`/etc/docker/daemon.json`
```json
{
  "log-driver": "journald",
  "log-opts": {
    "tag": "{{.Name}}/{{.ID}}"
  }
}
```

`promtail.yaml`
```yaml
scrape_configs:
  - job_name: journald
    journal:
      max_age: 12h
      path: /var/log/journal
      labels:
        job: journald
    relabel_configs:
      - action: drop
        source_labels: [__journal__systemd_unit]
        regex: session-.*
      - source_labels: [__journal__hostname]
        target_label: hostname
      - source_labels: [__journal__boot_id]
        target_label: boot_id
      - source_labels: [__journal__systemd_unit]
        target_label: unit
      - source_labels: [__journal_priority]
        target_label: priority
      - source_labels: [__journal_container_name]
        target_label: container
      - source_labels: [__journal_container_id]
        target_label: container_id
      - source_labels: [__journal_image_name]
        target_label: image
    pipeline_stages:
      - match:
          selector: '{job="journald"} |= ".mount: Deactivated successfully."'
          action: drop
```
