### ISSUE TITLE
promtail consume kafka topic not newest

### ISSUE THREAD

**Issue by Juntaran** [grafana/loki#5683]
```
    - job_name: kafka
        kafka:
          brokers:
            - 127.0.0.1:9092
          topics:
            - test_topic
          version: "2.3.0"
          labels:
            job: kafka
        relabel_configs:
          - action: replace
            source_labels:
              - __meta_kafka_topic
            target_label: topic
          - action: replace
            source_labels:
              - __meta_kafka_partition
            target_label: partition
          - action: replace
            source_labels:
              - __meta_kafka_group_id
            target_label: group
```

my promtail config like this,
but i use logcli, i find the log not from newest, like 3 days ago

how can i config consume from newest kafka offset
