### ISSUE TITLE
Unable to add Loki as Grafana data source: Bad Gateway. 502 (Docker Swarm)

### ISSUE THREAD

**Issue by tdbits** [grafana/loki#5725]
**Describe the bug**
Grafana reports `Bad Gateway. 502` when adding Loki as data source. Inside the grafana container it is possible to ping the Loki container and access the API via wget.

**To Reproduce**
1. Deploy attached Docker Swarm Stack via `docker stack deploy -c monlog-stack.yml monlog`
2. Add Loki as data source to grafana with URL: `http://loki:3100`

**Expected behavior**
Loki is added as data source in Grafana and can be queried.

**Environment:**
 - Infrastructure: Bare Metal Docker Swarm
 - Deployment tool: docker
 - Access to Grafana UI via SSH Tunnel (ssh -L 3090:IP:3000 HOST_IP)

**Screenshots, Promtail config, or terminal output**
**Loki Log:**
```
[...]
monlog_loki.1.rj65jlg5nrrw@server    | level=warn ts=2022-03-29T16:00:51.155730874Z caller=pool.go:184 msg="removing frontend failing healthcheck" addr=10.0.0.245:9095 reason="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
monlog_loki.1.rj65jlg5nrrw@server    | level=error ts=2022-03-29T16:00:51.15614155Z caller=scheduler_processor.go:199 org_id=fake msg="error notifying frontend about finished query" err="rpc error: code = Canceled desc = grpc: the client connection is closing" frontend=10.0.0.245:9095
monlog_loki.1.rj65jlg5nrrw@server    | level=error ts=2022-03-29T16:01:19.071358046Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
[...]

**Grafana Log:**
```
monlog_grafana.1.iyhixtlkcxy0@server    | t=2022-03-29T16:09:18+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/2/loki/api/v1/label remote_addr=10.0.0.2 referer=http://localhost:3090/datasources/edit/677UJo-7z error="http: proxy error: net/http: timeout awaiting response headers"
monlog_grafana.1.iyhixtlkcxy0@server    | t=2022-03-29T16:09:18+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/2/loki/api/v1/label status=502 remote_addr=10.0.0.2 time_ms=30006 size=0 referer=http://localhost:3090/datasources/edit/677UJo-7z
```

**Swarm Stack:**
```yml
version: '3.9'

services:
  loki:
    image: grafana/loki:2.4.2
    command: -config.file=/etc/loki-config.yml
    ports:
      - "3100:3100"
    networks: 
      - monlog-net
    volumes:
      - loki-data:/loki
    configs:
      - source: loki-config
        target: /etc/loki-config.yml
    deploy:
      placement: 
        constraints: 
          - node.role == manager
  
  logstash-loki:
    image: grafana/logstash-output-loki:main
    command: -f loki-config.conf
    environment:
      - XPACK_MONITORING_ENABLED=false
    ports:
      - "5044:5044"
    networks: 
      - monlog-net
    configs:
      - source: logstash-config
        target: /home/logstash/loki-config.conf
    deploy:
      placement: 
        constraints: 
          - node.role == manager
      
  grafana:
    image: grafana/grafana:8.3.4
    ports:
      - 3000:3000
    networks: 
      - monlog-net
    volumes:
      - grafana-data:/var/lib/grafana
    deploy:
      replicas: 1
      placement: 
        constraints: 
          - node.role == manager


configs:
  loki-config:
    file: ./files/loki-local.yml
  logstash-config:
    file: ./files/loki-logstash.conf
  prometheus-conf:
    file: ./files/prometheus.yml

networks:
  monlog-net:
    external: true

volumes:
  loki-data:
    external: true
  grafana-data:
    external: true
  prometheus-data:
    external: true
```

**Loki Config:**
```yml
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2000-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
  compaction_interval: 30m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  retention_period: 168h
  reject_old_samples: true
  reject_old_samples_max_age: 160h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h
```

**Comment by dannykopping** [comment]
This doesn't appear to be a bug in Loki, but rather some configuration issue.

It appears there's a timeout:

> `http: proxy error: net/http: timeout awaiting response headers`
> `rpc error: code = DeadlineExceeded desc = context deadline exceeded`

We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by tdbits** [comment]
Followup: I could solve the problem by changing the port configuration of the Loki service in the Docker Swarm Stack:
```yml
    ports:
      - target: 3100
        published: 3100
        mode: host
```
