### ISSUE TITLE
How to disable syslog colors?

### ISSUE THREAD

**Issue by Skipper0707** [grafana/loki#5727]
I have a log management stack that takes input from `syslog` through rsyslog and if I've understood correctly from my searches, there are Unicode color codes in them which are shown in the log management output (`grafana`).

Is there any way to disable or remove/drop these Unicode color codes in either logger or rsyslog?

If not, how can I configure my log management to drop these?

Any help is appreciated, thanks in advance.

I've tried the `drop -- expressions` in `promtail` configuration file but didn't work, could be something wrong with my regex or I'm not using/configuring something properly.

```yaml
- job_name: syslog
  syslog:
    listen_address: <something>
    job: "syslog"
  drop:
    expression: "#(\\d+)"
  relabel_config:
...
```
The Unicode color codes in log messages look like this:
```bash
\033[1;31m Sample Text \033[0m
```
