### ISSUE TITLE
No alert is getting triggered if there are zero logs

### ISSUE THREAD

**Issue by rjshrjndrn** [grafana/loki#5766]
**Describe the bug**
Need to alert, if the application is not printing any logs (plausible zombie state). But  loki alerting with prometheus alert manager is not working

**To Reproduce**
1. Started Loki (grafana/loki:2.4.2)
2. Started Promtail (docker.io/grafana/promtail:2.4.2) to tail '...'
3. Query: `count_over_time({namespace="app", app="db"} |~ "Queue Statistics"[5m]) ==0`

![image](https://user-images.githubusercontent.com/2563385/161600436-fa251b10-8ad3-4352-abb6-998ea263ebc1.png)

![image](https://user-images.githubusercontent.com/2563385/161600377-4759d8be-9d5b-4052-980b-c0a8caabc54e.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/2563385/161600584-7555a02f-5da9-4f3c-a78e-8e02f9ab2370.png)

**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: helm
```
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
helm install grafana/loki==2.4.2
```

**values.yaml**
```
image:
  repository: grafana/loki
  tag: 2.4.2
  pullPolicy: IfNotPresent
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
affinity: {}
annotations: {}
tracing:
  jaegerAgentHost:
config:
  auth_enabled: false
  ingester:
    chunk_idle_period: 3m
    chunk_block_size: 262144
    chunk_retain_period: 1m
    max_transfer_retries: 0
    wal:
      dir: /data/loki/wal
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    retention_period: 240h
  schema_config:
    configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
  server:
    http_listen_port: 3100
  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
      shared_store: filesystem
    filesystem:
      directory: /data/loki/chunks
  chunk_store_config:
    max_look_back_period: 0s
  table_manager:
    retention_deletes_enabled: false
    retention_period: 0s
  compactor:
    working_directory: /data/loki/boltdb-shipper-compactor
    shared_store: filesystem
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
  ruler:
    storage:
      type: local
      local:
        directory: /rules
    rule_path: /tmp/scratch
    alertmanager_url: http://openreplay-alertmanager.monitoring.svc.cluster.local:9093
    ring:
      kvstore:
        store: inmemory
    enable_api: true
extraArgs: {}
livenessProbe:
  httpGet:
    path: /ready
    port: http-metrics
  initialDelaySeconds: 45
networkPolicy:
  enabled: false
client: {}
nodeSelector: {}
persistence:
  enabled: true
  accessModes:
  - ReadWriteOnce
  size: 100Gi
  annotations: {}
podLabels: {}
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "http-metrics"
podManagementPolicy: OrderedReady
rbac:
  create: true
  pspEnabled: true
readinessProbe:
  httpGet:
    path: /ready
    port: http-metrics
  initialDelaySeconds: 45
replicas: 1
resources: {}
securityContext:
  fsGroup: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001
service:
  type: ClusterIP
  nodePort:
  port: 3100
  annotations: {}
  labels: {}
  targetPort: http-metrics
serviceAccount:
  create: true
  name:
  annotations: {}
  automountServiceAccountToken: true
terminationGracePeriodSeconds: 4800
tolerations: []
podDisruptionBudget: {}
updateStrategy:
  type: RollingUpdate
serviceMonitor:
  enabled: false
  interval: ""
  additionalLabels: {}
  annotations: {}
initContainers: []
extraContainers: []
extraVolumes: []
extraVolumeMounts: []
extraPorts: []
env: []
alerting_groups:
  - name: dbZombie
    rules:
    - alert: dbZombie
      expr: 0 - count_over_time({namespace="app", app="db"} |~ "Queue Statistics"[5m]) >= 0
      for: 5m
      labels:
        severity: warning
```
