### ISSUE TITLE
Loki 2.4.2 compactor does not apply retention

### ISSUE THREAD

**Issue by Cosmos-D** [grafana/loki#5816]
Changed Loki config to use compactor for retention when upgrading to 2.4.2. Since then, retention has not been applied and the following warning is logged when compaction occurs:

**err open: the system cannot find the file specified**

The compactor is configured as follows:

```yaml
compactor:
  working_directory: /Program Files/Loki/compactor/
  shared_store: filesystem
  rentention_enabled: true
  retention_delete_delay: 2h
```

Loki is installed as a single instance on a Windows client.
