### ISSUE TITLE
`__meta_docker_container_log_stream` is empty

### ISSUE THREAD

**Issue by thepheer** [grafana/loki#5882]
**Describe the bug**
`__meta_docker_container_log_stream` is empty

**To Reproduce**
I updated my Loki and Promtail to 2.5.0 version (both) and tried to setup this new `docker_sd_configs` thing.
Works great but `__meta_docker_container_log_stream` seems to be empty.
I relabeled it to `container_log_stream` (see the promtail config below) but I can't see it in Grafana Explore tab.
I also checked all the other `__meta_docker_container_*` labels, they're all fine.
Not providing much details yet because I expect it to be easily reproducible, let me know if it's not the case.

**Expected behavior**
Should be set to either `stdout` or `stderr`.

**Environment:**
 - Infrastructure: a server with ubuntu 20.04, arm64
 - Deployment tool: docker compose

**Screenshots, Promtail config, or terminal output**
```yml
# Promtail config
server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_log_stream]
        target_label: container_log_stream
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
        regex: /(.*)
```
