### ISSUE TITLE
ruler: Support alert relabeling

### ISSUE THREAD

**Issue by badrabubker** [grafana/loki#5886]
Hello Loki development team,
I would like to ask for adding `alert_relabel_configs` to ruler

**Is your feature request related to a problem**? 
I have the current setup: 
Prometheus + Alertmanager + Opsgenie and recently Loki was deployed 
I use `alert_relabel_configs` in Prometheus to map severity of an alert to Opsgenie priority 
e.g. 
```
alert_relabel_configs:
  - source_labels: [severity]
    regex: emergency
    target_label: opsgenie_priority
    replacement: P1
```
to abstract Opsgenie priorities. I can't do that with ruler since it does not support alert relabeling.

**Describe the solution you'd like**
Add alert relabeling similar to Prometheus

**Describe alternatives you've considered**
I could do the mapping on alert manager side but I had to define 5 more receivers for each receiver I had 
e.g. 
```
      routes:
      - match:
          severity: emergency
        receiver: events-P1
      - match:
          severity: alert
        receiver: events-P2
.....
```

**Additional context**
