### ISSUE TITLE
How to subscribe to multiple channel on promtail for windows_events?

### ISSUE THREAD

**Issue by riupie** [grafana/loki#5905]
From default config we can collect log from channel `Application`
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0
clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: windows
  windows_events:
    use_incoming_timestamp: false
    bookmark_path: "./bookmark.xml"
    eventlog_name: "Application"
    xpath_query: '*'
    labels:
      job: windows
```

I wan to collect log from channel Application and Security, how to do that? And if possible how to filter log so it will only collect log with severity/level <=3?

**Comment by Mario-Hofstaetter** [comment]
> I wan to collect log from channel Application and Security, how to do that

@riupie I just created a second job in `scrape_configs`, in my case to get `System` . (I did not want to struggle with `xpath_query` so took the easy path). The exact config I used:

```yaml
scrape_configs:
  - job_name: windows-application
    windows_events: 
      eventlog_name: "Application"
      labels:
        logsource: windows-eventlog
      use_incoming_timestamp: true
      bookmark_path: "./tmp/bookmark-application.xml"
      exclude_event_data: true
      exclude_user_data: true
      locale: 1033

  - job_name: windows-system
    windows_events: 
      eventlog_name: "System"
      labels:
        logsource: windows-eventlog
      use_incoming_timestamp: true
      bookmark_path: "./tmp/bookmark-system.xml"
      exclude_event_data: true
      exclude_user_data: true
      locale: 1033

```

> And if possible how to filter log so it will only collect log with severity/level <=3?

I'm not sure if this can be done without using the `xpath_query`, but you could try looking into maybe the [`drop` stage](https://grafana.com/docs/loki/latest/clients/promtail/stages/drop/), if the `level` is available in the extracted data, or possibly the [match](https://grafana.com/docs/loki/latest/clients/promtail/stages/match/) stage.
You'd have to try maybe using debug-output from promtail.
