### ISSUE TITLE
ambiguity when config cos as store backend

### ISSUE THREAD

**Issue by caibirdme** [grafana/loki#5919]
**Is your feature request related to a problem? Please describe.**
I'm very confused about configuring cos, because according to official demo, the config looks like:
```yaml
    storage_config:
      aws:
        endpoint: a
        region: b
        bucketnames: c
        access_key_id: d
        secret_access_key: e
      boltdb_shipper: 
        shared_store: s3
    schema_config:
      configs:
        - from: "2022-04-10"
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            period: 24h
            prefix: loki_index_
```
What does s3 mean? Finally it means using storage_config.aws...
Why object_store and shared_store use "s3" rather than "aws" directly, or why it's called "aws" rather than "s3" in storage_config

**Describe the solution you'd like**
Unified the name of s3 and aws
