### ISSUE TITLE
timestamp stage not working as expected

### ISSUE THREAD

**Issue by antscloud** [grafana/loki#5928]
**Describe the bug**

The timestamp appear to not be parsed/send to loki correctly in the following configuration :

Log file : 
```
2022-04-13 14:29:05,402 [pid:419] DEBUG : A log message
2022-04-13 14:29:05,406 [pid:419] DEBUG : A log message
...
2022-04-13 14:29:05,409 [pid:419] DEBUG : A log message
2022-04-13 14:29:05,413 [pid:419] DEBUG : A log message
```
Configuration : 
```yaml
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9093
  log_level: debug

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: job_test
    pipeline_stages:
      - match:
          selector: '{job="job_test"}'
          stages:
            - regex:
                expression: '\s*(?P<timestamp>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3})\s*(?P<pid>\[pid:[0-9]+\])\s*(?P<level>\w*)\s+: (?P<content>.*)'
            - labels:
                timestamp:
                pid:
                level:
                content:
            - timestamp:
                source: timestamp
                format: "2006-01-02 15:04:05.000" #https://pkg.go.dev/time#Parse
    static_configs:
      - targets:
          - localhost
        labels:
          job: job_test
          __path__: /test/*.txt
```
My regex seems to be working great : 
```
promtail_1  | level=debug ts=2022-04-14T11:01:46.220176868Z caller=regex.go:132 component=file_pipeline 
component=stage type=regex msg="extracted data debug in regex stage" 
extracteddata="map[content:A log message filename:/test/logs.txt job:job_test level:DEBUG pid:[pid:419] 
timestamp:2022-04-13 14:29:05,511]"
```

I do **not** have a debug log `caller=timestamp.go` that tells me that my format is wrong. (When i force it to be wrong the log shows up)

When I try to access loki through Grafana or directly by calling : 
http://localhost:3100/loki/api/v1/query_range?query={job="job_test"}&start=2022-04-10T00:00:00-00:00&end=2022-04-20T00:00:00-00:00

I have no data. at all : 

```json
{
  "status": "success",
  "data": {
    "resultType": "streams",
    "result": [],
    "stats": {
      "summary": {
        "bytesProcessedPerSecond": 0,
        "linesProcessedPerSecond": 0,
        "totalBytesProcessed": 0,
        "totalLinesProcessed": 0,
        "execTime": 0.002594055,
        "queueTime": 0.000039616,
        "subqueries": 1
      },
...
```

But if i **remove the timestamp stage**, it seems to work fine and as expected. I have all my log lines with the timestamp of insertion in loki and all my parsed label. 

```json
{
  "status": "success",
  "data": {
    "resultType": "streams",
    "result": [
      {
        "stream": {
          "pid": "[pid:419]",
          "timestamp": "2022-04-13 14:29:05,402",
          "content": "A log message",
          "filename": "/test/logs.txt",
          "job": "job_test",
          "level": "DEBUG"
        },
...
```
I wrote this function in `go` to test the format : 

```golang
package main

import (
	"fmt"
	"os"
	"time"
)

func main() {
	const layout = "2006-01-02 15:04:05.000"
	const yourStringTime = "2022-04-13 14:29:05,402"
	t, err := time.Parse(layout, yourStringTime)
	if err != nil {
		fmt.Println("error", err)
		os.Exit(1)
	}

	fmt.Println(t)
}
```
And it works great : 
```
>>> 2022-04-13 14:29:05.402 +0000 UTC
```

Am i missing something ? 

**To Reproduce**

docker-compose.yml
```yaml
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.5.0
    volumes: 
      - ./loki:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/log:/var/log
      - ./test-logs:/test
      - ./promtail:/etc/promtail
    ports:
      - 9093:9093
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - loki
```

loki/local-config.yaml
```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
```

promtail/config.yaml
```yaml
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9093
  log_level: debug

positions:
  filename: /tmp/positions.yaml

client:
  url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: job_test
    pipeline_stages:
      - match:
          selector: '{job="job_test"}'
          stages:
            - regex:
                expression: '\s*(?P<timestamp>[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3})\s*(?P<pid>\[pid:[0-9]+\])\s*(?P<level>\w*)\s+: (?P<content>.*)'
            - labels:
                timestamp:
                pid:
                level:
                content:
            - timestamp:
                source: timestamp
                format: "2006-01-02 15:04:05.000" #https://pkg.go.dev/time#Parse
    static_configs:
      - targets:
          - localhost
        labels:
          job: job_test
          __path__: /test/*.txt
```

./test-logs/logs.txt
```
2022-04-13 14:29:05,402 [pid:419] DEBUG : A log message
2022-04-13 14:29:05,406 [pid:419] DEBUG : A log message
...
2022-04-13 14:29:05,409 [pid:419] DEBUG : A log message
2022-04-13 14:29:05,413 [pid:419] DEBUG : A log message
```

**Environment:**
 - Infrastructure: 
   - `docker-compose`
   - `loki 2.5.0`
   - `promtail 2.5.0`

The issue is encountered with `loki 2.4.2` and `promtail 2.4.2` too

**Everything i try so far**

- Change timestamp for all log lines to stick with RFC3339 of `golang` and change format in the yaml file
- Remove the comma of milisecond of log line and adjust regex
- Set the `location` to UTC 
- Set  the `location` to where the data comes from (Europe/Paris)
