### ISSUE TITLE
Unrecognized input header error with Docker containers

### ISSUE THREAD

**Issue by lukaszczerpak** [grafana/loki#5950]
**Describe the bug**
Getting `Unrecognized input header: 50` error on simple docker container. It seems to be similar to https://github.com/grafana/loki/issues/5856 

**To Reproduce**
1. Started Loki 2.5.0
2. Started Promtail 2.5.0 to tail docker container logs
3. Run a new container that echoes something to stdout:
```
$ docker run --rm \
      --log-driver local --log-opt max-size=10m \
      alpine echo hello world
```
4. Observe errors in journald/syslog.

**Expected behavior**
Receive logs from Docker and push to Loki service.

**Environment:**
 - Infrastructure: Archlinux, Docker 20.10.14
 - Deployment tool: ansible

Promtail config:
```
...
scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: [loggingtesting]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
```

Error:
```
Apr 18 20:36:24 server promtail[462732]: level=warn ts=2022-04-18T18:36:24.283252527Z caller=target.go:120 target=docker/d127e5083600a4618b773825eac65f8b260f3605ba0ed33b43cabb66a60a39ed msg="could not transfer logs" written=0 container=d127e5083600a4618b773825eac65f8b260f3605ba0ed33b43cabb66a60a39ed err="Unrecognized input header: 50"
```

I am happy to do more testing or provide with any details needed.

**Comment by sven-n** [comment]
I've got the same issue running on Windows with Docker Desktop. After an update to the current version, the issue was gone :)

**Comment by dorinand** [comment]
Hi, did you sole it somehow? I am running Loki 2.5.0 and Promtail 2.5.0. Currently I am running 3 nodes of docker swarm and register the same issue:
```
2022-06-27T23:46:23.545893275Z level=warn ts=2022-06-27T23:46:23.545745804Z caller=target.go:120 target=docker/9eea7bb6af3159872dd6c114c8d68b3d1227709c2132c48ed73f2f9aeefe7f3c msg="could not transfer logs" written=0 container=9eea7bb6af3159872dd6c114c8d68b3d1227709c2132c48ed73f2f9aeefe7f3c err="Unrecognized input header: 50"
```
From Loki,based on my query `|= "Unrecognized input header: 50"` I can see there is exactly 10 errors every minute:
![image](https://user-images.githubusercontent.com/27764640/176057052-a38ac9bf-9b88-4fa5-9061-0ca6bd6e0b88.png)
And from ad hoc statistics I can see, there is exactly 5 containers causing this issue with exact same percentage number of the error count:
![image](https://user-images.githubusercontent.com/27764640/176057568-a00ac4cd-6081-417b-89bc-938acb86dbbf.png)

**Comment by timchenko-a** [comment]
Faced the same issue, but using `Logging Driver: json-file`
As a workaround switched promtail to read logs directly:
```
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /var/lib/docker/containers/*/*-json.log
```
