### ISSUE TITLE
Timestamp handling

### ISSUE THREAD

**Issue by chenfeilee** [grafana/loki#5953]
**Describe the bug**
We are collecting logs from pods in EKS using Grafana agent and sending the logs to Loki. It seems like Loki doesn't parse the timestamp correctly for such log format.

![image](https://user-images.githubusercontent.com/90743057/163907683-f4b0aa63-e22c-412f-94f5-ef07dfe6e7ec.png)

This is a sample snippet of JSON retrieved from the inspector function in Grafana

```
{
    "logLevel": "info",
    "timeFromNow": "34 minutes ago",
    "timeEpochMs": 1650331937620,
    "timeEpochNs": "1650331937620887959",
    "timeLocal": "2022-04-19 09:32:17",
    "timeUtc": "2022-04-19 01:32:17",
    "uniqueLabels": {
        "stream": "stdout"
    },
    "hasAnsi": false,
    "hasUnescapedContent": false,
    "searchWords": [],
    "entry": "[2022-04-19 01:39:18] LEVEL=INFO STATUS=SUCCESS {{ nvbavC0M9q }}\n",
    "raw": "[2022-04-19 01:39:18] LEVEL=INFO STATUS=SUCCESS {{ nvbavC0M9q }}\n",
    "labels": {
        "namespace": "monitoring",
        "pod": "java-mock-app-686bcf8c5f-r9mzm",
        "pod_template_hash": "686bcf8c5f",
        "app": "java-mock-app",
        "container": "java-mock-app",
        "environment": "dev",
        "job": "kubernetes-pods",
        "region": "us-west-2",
        "stream": "stdout",
        "cluster": "tssdev-usw2-perf-core-blue",
        "filename": "/var/log/pods/monitoring_java-mock-app-686bcf8c5f-r9mzm_d6ff73ce-3961-4ef6-bda5-7d4609ad255a/java-mock-app/0.log",
        "node": "ip-10-150-109-182.us-west-2.compute.internal",
        "product": "monitoring-poc"
    },
    "uid": "00208c97-5373-587f-9753-00bda2d108af_A"
}
```

This is a snippet of our configuration in Grafana agent
```
logs:
      configs:
        - name: default
          clients:
            - url: ${LOKI_ENDPOINT}
              external_labels:
                cluster: ${CLUSTER_NAME}
          positions:
            filename: /tmp/positions.yaml
          scrape_configs:
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              pipeline_stages:
                - docker: {}
                - multiline:
                    firstline: '^\d{4}-\d{2}-\d{2}'
                    max_wait_time: 6s
                    max_lines: 256
              relabel_configs:
                - target_label: job
                  replacement: kubernetes-pods
                - source_labels: [__meta_kubernetes_pod_node_name]
                  target_label: __host__
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                - action: replace
                  source_labels: [__meta_kubernetes_namespace]
                  target_label: namespace
                - action: replace
                  source_labels: [__meta_kubernetes_pod_name]
                  target_label: pod
                - action: replace
                  source_labels: [__meta_kubernetes_pod_container_name]
                  target_label: container
                - source_labels: [__meta_kubernetes_pod_node_name]
                  action: replace
                  target_label: node
                - replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
                  target_label: __path__
```

**To Reproduce**
1. Collect logs from pods in EKS cluster using Grafana Agent
2. Send logs to Loki
3. Query logs via Grafana

**Expected behavior**
Timestamp in the logs to be parsed correctly
