### ISSUE TITLE
Promtail: "Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc"

### ISSUE THREAD

**Issue by jsteppe** [grafana/loki#5955]
Hello!

I'm trying to install promtail with manifests and export logs from Kubernetes cluster to Loki. While I couldn't get manifest installation described in [documentation](https://grafana.com/docs/loki/latest/clients/promtail/installation/) going I gave helm install a try.

Helm install works fine. It labels and tags the logs files and sends them to loki.

`helm upgrade --install promtail grafana/promtail  -f /tmp/promtail_values.yml`

Now I've tried to extract manifests from helm using:

`helm upgrade --install promtail grafana/promtail  -f /tmp/promtail_values.yml --dry-run`

and applied them. 

Promtail errors out with 

`msg="GET /ready (500) 35.791µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept: */*; Connection: close; User-Agent: kube-probe/1.23`

Kubernetes: v1.23.4
Helm: v3.8.0+gd141386

Manifest:

```
# Source: promtail/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: loki
  labels:
    helm.sh/chart: promtail-4.2.0
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/version: "2.5.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: promtail/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: promtail
  namespace: loki
  labels:
    helm.sh/chart: promtail-4.2.0
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/version: "2.5.0"
    app.kubernetes.io/managed-by: Helm
stringData:
  promtail.yaml: |
    server:
      log_level: info
      http_listen_port: 3101

    clients:
      - url: http://loki-loki-simple-scalable-gateway/loki/api/v1/push

    positions:
      filename: /run/promtail/positions.yaml

    scrape_configs:
      # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
      - job_name: kubernetes-pods
        pipeline_stages:
          - cri: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_controller_name
            regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
            action: replace
            target_label: __tmp_controller_name
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
              - __meta_kubernetes_pod_label_app
              - __tmp_controller_name
              - __meta_kubernetes_pod_name
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: app
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_component
              - __meta_kubernetes_pod_label_component
            regex: ^;*([^;]+)(;.*)?$
            action: replace
            target_label: component
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_node_name
            target_label: node_name
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            replacement: $1
            separator: /
            source_labels:
            - namespace
            - app
            target_label: job
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
            target_label: __path__
          - action: replace
            regex: true/(.*)
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
            - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
            - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
            - __meta_kubernetes_pod_container_name
            target_label: __path__
---
# Source: promtail/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: promtail
  labels:
    helm.sh/chart: promtail-4.2.0
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/version: "2.5.0"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs:
      - get
      - watch
      - list
---
# Source: promtail/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: promtail
  labels:
    helm.sh/chart: promtail-4.2.0
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/version: "2.5.0"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: loki
roleRef:
  kind: ClusterRole
  name: promtail
  apiGroup: rbac.authorization.k8s.io
---
# Source: promtail/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: loki
  labels:
    helm.sh/chart: promtail-4.2.0
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/version: "2.5.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
      app.kubernetes.io/instance: promtail
  updateStrategy:
    {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: promtail
        app.kubernetes.io/instance: promtail
      annotations:
        checksum/config: e94680e64beaef2d5b2debc874a8580d23b627b7e373d2a2f207d872170d15c2
    spec:
      serviceAccountName: promtail
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      containers:
        - name: promtail
          image: "docker.io/grafana/promtail:2.5.0"
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: run
              mountPath: /run/promtail
            - mountPath: /var/lib/docker/containers
              name: containers
              readOnly: true
            - mountPath: /var/log/pods
              name: pods
              readOnly: true
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http-metrics
              containerPort: 3101
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      volumes:
        - name: config
          secret:
            secretName: promtail
        - name: run
          hostPath:
            path: /run/promtail
        - hostPath:
            path: /var/lib/docker/containers
          name: containers
        - hostPath:
            path: /var/log/pods
          name: pods
```

Log:
```
level=warn ts=2022-04-19T08:42:35.660135972Z caller=logging.go:72 msg="GET /ready (500) 113.083µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept: */*; Connection: close; User-Agent: kube-probe/1.23; "
level=warn ts=2022-04-19T08:42:45.660860296Z caller=logging.go:72 msg="GET /ready (500) 32.75µs Response: \"Not ready: Unable to find any logs to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept: */*; Connection: close; User-Agent: kube-probe/1.23; "
```

**Comment by slim-bean** [comment]
I think if i read this correctly if you install it with helm it works fine? but when you try to extract the manifests from helm and install them it doesn't work?

If that's the case I'm not sure we can offer much support here, the helm charts are largely already community maintained and we are not really helm experts, and given that the helm chart seems to be working it seems like maybe the way you are extracting the manifests is the issue?

**Comment by m62534** [comment]
check if hostpath exists and the daemonset has access to those mounts.
you can go into promtail pods and try cd to /var/log/pods (or other path appropriate for your k8s node setup) - if you can't, then promtail wont be able to find the logs to tail.

**Comment by tchellomello** [comment]
I'm hitting the same issue and I can list the contents from the `/var/log/pods` directory from the container. Going to look if I can gather more information. Interesting is that I'm seeing this only in 1 node. 
```bash
$ kubectl grep pods -n observability loki -o wide 
NAMESPACE       NAME                         READY   STATUS    RESTART   AGE   IP              NODENAME
observability   loki-stack-loki-0           1/1     Running   0         15m   10.223.28.101   p53.tatu.home
observability   loki-stack-promtail-98465   1/1     Running   0         14m   10.223.40.58    p70.tatu.home
observability   loki-stack-promtail-hqdl4   0/1     Running   0         15m   10.223.28.90    p53.tatu.home
observability   loki-stack-promtail-m67nb   1/1     Running   0         15m   10.223.42.255   t470n2.tatu.home
observability   loki-stack-promtail-m6hn4   1/1     Running   0         16m   10.223.59.3     t470n1.tatu.home

$ kubectl images -n observability loki-stack-promtail 
[Summary]: 1 namespaces, 4 pods, 4 containers and 2 different images
+----------------------------+-----------+----------------------------------+
|            Pod             | Container |              Image               |
+----------------------------+-----------+----------------------------------+
| loki-stack-promtail-98465  | promtail  | docker.io/grafana/promtail:2.6.1 |
+----------------------------+           +                                  +
| loki-stack-promtail-hqdl4  |           |                                  |
+----------------------------+           +                                  +
| loki-stack-promtail-m67nb  |           |                                  |
+----------------------------+           +----------------------------------+
| loki-stack-promtail-m6hn4  |           | docker.io/grafana/promtail:2.4.2 |
+----------------------------+-----------+----------------------------------+

```

**Comment by tchellomello** [comment]
Interesting that I've start seeing this after migrating to Kubernetes `1.25.2`. Interesting that the only node that I'm get the issue is a worker node and I can see this: 

```bash
$ kubectl get pods -A -o wide -w | grep promt                                                                                  9.3m  Mon 10 Oct 2022 11:23:49 PM EDT
observability           loki-stack-promtail-29l5j                                 1/1     Running     0               8m35s   10.223.59.56     t470n1.tatu.home   <none>           <none>
observability           loki-stack-promtail-98465                                 1/1     Running     0               37m     10.223.40.58     p70.tatu.home      <none>           <none>
observability           loki-stack-promtail-m67nb                                 1/1     Running     0               38m     10.223.42.255    t470n2.tatu.home   <none>           <none>
observability           loki-stack-promtail-scw89                                 0/1     Running     0               8m35s   10.223.28.81     p53.tatu.home      <none>           <none>
```
From the logs, I can see the k8s API is returning a timeout, however, it's working from the other nodes:
```bash
loki-stack-promtail-scw89 promtail W1011 03:21:10.994690       1 reflector.go:324] github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:502: failed to list *v1.Pod: Get "https://10.96.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%3Dp53.tatu.home&limit=500&resourceVersion=0": dial tcp 10.96.0.1:443: i/o timeout
```
However, if I run `kubectl proxy` and then try that namespace it works fine: 

```json
$ kubectl proxy
$ curl 2>/dev/null  "http://127.0.0.1:8001/api/v1/pods?fieldSelector=spec.nodeName%3Dp53.tatu.home&limit=500" | jq | head
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "resourceVersion": "119135761"
  },
  "items": [
    {
      "metadata": {
        "name": "cadvisor-kx7lh",
```

I can also achieve the same if I try directly to the k8s API using the token (mounted at the pod) (which also explains why the other pods are working).  Interesting...

**Comment by tchellomello** [comment]
To investigate the issue I've enabled the `EphemeralContainers` so I could attach a `curl` to the container to test the API version timeout. Turns out that I found an issue with `calico` and the k8s `1.25.2` which was fixed on the latest calico version. 

Deployed the new `calico` version and once I rolled out the `loki` DS it worked like a charm. So it seems the error was being triggered but the API call for that given node. 

```bash
$ kubectl get pods -A -o wide -w | grep promtai
observability           loki-stack-promtail-95mmm                                1/1     Running   0               28s     10.223.40.24     p70.tatu.home      <none>           <none>
observability           loki-stack-promtail-c69vk                                1/1     Running   0               28s     10.223.59.11     t470n1.tatu.home   <none>           <none>
observability           loki-stack-promtail-cln9z                                1/1     Running   0               28s     10.223.28.143    p53.tatu.home      <none>           <none>
observability           loki-stack-promtail-qtkd6                                1/1     Running   0               28s     10.223.42.193    t470n2.tatu.home   <none>           <none>

```

**Comment by olyhao** [comment]
I also encountered the same problem. After updating the promtail configmap file and adding keep to capture specific pod logs, a node's promtail failed to start

**Comment by hopik007** [comment]
same "problem". 
I have specified specific app labels for the collection of logs only for particular pods and pods for this app not running on all nodes. So promtail is not running on node where no pods match labels. So it is probably correct but monitoring yell at me that loki "daemonset mismatch"

**Comment by Kunone** [comment]
I'm experiencing the same issue. Specifically, only the Promtail instance running on a node without any pods being monitored by the associated configuration is generating a warning. This behavior appears to be expected, since there are no logs to capture and thus the liveness/readiness checks fail.

**Comment by vojtechvelkjop** [comment]
yes, all loki daemonset pods should be up doesn't matter if there aren`t logs for tailing.  Simalar as for splunk collector, elasticsearch collectors ...

**Comment by WeAreHadock** [comment]
Hi, any update on this issue ? 
If promtail is running on a node where there isn't any log to collect, readiness probe fails. Is this behavior expected ?

**Comment by renanqts** [comment]
I'm using it to find the logs in EKS, I hope it helps you.

```
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            regex: true/(.*)
            separator: /
            source_labels:
              - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
              - __meta_kubernetes_pod_container_name
            target_label: __path__
```

**Comment by 0120208** [comment]
Have you found the reason? Now I have encountered the problem that promtail(three) all not Ready. This is my operation and the problems I encountered:

> 1.helm repo add grafana https://grafana.github.os/helm-charts

> 2.helm repo update

> 3.helm install -n loki --values values-prob.yaml test grafana/loki-stack

Follow the helm method on the official website.

**NAME**                            READY   STATUS    RESTARTS   AGE

**test-grafana-7bbb67fbd6-jbvms**   2/2     Running   0          28m
**test-loki-0**                     1/1     Running   0          28m
test-promtail-27nz4              0/1     Running   0          3m40s
test-promtail-qws8j              0/1     Running   0          3m40s
test-promtail-zm9dj             0/1     Running   0          3m40s

My values.yaml:
![image](https://github.com/grafana/loki/assets/90227020/fa8939b2-9838-47d4-b98d-a793cd58a827)

From the loki logs,I see:

>Events:
  Type     Reason     Age                    From               Message
  --
  Normal   Scheduled  10m                    default-scheduler  Successfully assigned loki/test-loki-0 to xxx.dev.local
  Normal   Pulled     10m                    kubelet            Container image "grafana/loki:2.6.1" already present on machine
  Normal   Created    10m                    kubelet            Created container loki
  Normal   Started    10m                    kubelet            Started container loki
  Warning  Unhealthy  9m41s (x2 over 9m51s)  kubelet            Liveness probe failed: HTTP probe failed with statuscode: 503
  Warning  Unhealthy  9m41s (x2 over 9m51s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 503

From the pormtail logs,I see:
>Events:
  Type     Reason     Age                   From               Message
  --
  Normal   Scheduled  13m                   default-scheduler  Successfully assigned loki/test-promtail-jv5rt to hd4.dev.local
  Normal   Pulled     13m                   kubelet            Container image "docker.io/grafana/promtail:2.8.3" already present on machine
  Normal   Created    13m                   kubelet            Created container promtail
  Normal   Started    13m                   kubelet            Started container promtail
  Warning  Unhealthy  3m44s (x68 over 13m)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 500

And

'level=info ts=2023-12-16T08:41:04.034293213Z caller=filetarget.go:285 msg="watching new directory" directory=/var/log/pods/loki_test-grafana-7bbb67fbd6-jbvms_da01c4bf-8d64-4b32-b8aa-2aa48ac50258/grafana-sc-datasources
level=error ts=2023-12-16T08:41:04.034361975Z caller=filetarget.go:314 msg="failed to tail file, stat failed" error="stat /var/log/pods/loki_test-grafana-7bbb67fbd6-jbvms_da01c4bf-8d64-4b32-b8aa-2aa48ac50258/grafana-sc-datasources/0.log: no such file or directory" filename=/var/log/pods/loki_test-grafana-7bbb67fbd6-jbvms_da01c4bf-8d64-4b32-b8aa-2aa48ac50258/grafana-sc-datasources/0.log
level=info ts=2023-12-16T08:41:04.034350738Z caller=filetarget.go:285 msg="watching new directory" directory=/var/log/pods/kafka-manager-ns_kafka-zookeeper-0_66062653-ff3f-4867-b1f8-5ca32e0e15a9/zookeeper
level=error ts=2023-12-16T08:41:04.034820938Z caller=filetarget.go:314 msg="failed to tail file, stat failed" error="stat /var/log/pods/kafka-manager-ns_kafka-zookeeper-0_66062653-ff3f-4867-b1f8-5ca32e0e15a9/zookeeper/0.log: no such file or directory" filename=/var/log/pods/kafka-manager-ns_kafka-zookeeper-0_66062653-ff3f-4867-b1f8-5ca32e0e15a9/zookeeper/0.log
level=info ts=2023-12-16T08:41:04.034860282Z caller=filetargetmanager.go:358 msg="Adding target" key="/var/log/pods/*3179ff07-949e-4d41-bda7-dcf37b08a3d3/zookeeper/*.log:{app=\"zookeeper\", component=\"zookeeper\", container=\"zookeeper\", instance=\"kafka-manager\", job=\"kafka-manager-ns/zookeeper\", namespace=\"kafka-manager-ns\", node_name=\"hd4.dev.local\", pod=\"kafka-manager-zookeeper-0\"}"
level=info ts=2023-12-16T08:41:04.034864188Z caller=filetarget.go:285 msg="watching new directory" directory=/var/log/pods/loki_test-grafana-7bbb67fbd6-jbvms_da01c4bf-8d64-4b32-b8aa-2aa48ac50258/grafana
level=error ts=2023-12-16T08:41:04.034937051Z caller=filetarget.go:314 msg="failed to tail file, stat failed" error="stat /var/log/pods/loki_test-grafana-7bbb67fbd6-jbvms_da01c4bf-8d64-4b32-b8aa-2aa48ac50258/grafana/0.log: no such file or directory" filename=/var/log/pods/loki_test-grafana-7bbb67fbd6-jbvms_da01c4bf-8d64-4b32-b8aa-2aa48ac50258/grafana/0.log'

**Comment by ep4sh** [comment]
Hi everyone, 
I'm facing the same issue when trying to select specific pods with pod selector via `kubernetes_sd_configs`.


My config is like the following:
```
      scrape_configs:
        # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
              selectors:
              - role: pod
                label: "app=myapp"
          relabel_configs:
            - source_labels: [ __meta_kubernetes_namespace ]
              regex: '[^(myapp.*)].+'
              action: drop
            - source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
                - __meta_kubernetes_pod_label_app
                - __tmp_controller_name
                - __meta_kubernetes_pod_name
              regex: ^;*([^;]+)(;.*)?$
              action: replace
              target_label: app
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
              target_label: __path__
            - action: replace
              regex: true/(.*)
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
              - __meta_kubernetes_pod_container_name
              target_label: __path__
          pipeline_stages:
            - cri: {}
            - match:
                selector: '{app="myapp"}'
                stages:
                - json:
                    expressions:
                      level: level
                      method: method
                      status_code: status_code
                      path: path
                      msg: msg
                - labels:
                    level:
                    method:
                    status_code:
                    path:
                    msg:

```


```
│ level=warn ts=2024-05-28T12:31:13.758554373Z caller=logging.go:126 traceID=63d4bda14f0ee10b msg="GET /ready (500) 41.249µs Response: \"Not ready: Unable to find any log  │
│ s to tail. Please verify permissions, volumes, scrape_config, etc.\\n\" ws: false; Accept: */*; Connection: close; User-Agent: kube-probe/1.28;
```
