### ISSUE TITLE
Context canceled error

### ISSUE THREAD

**Issue by kiemlicz** [grafana/loki#5963]
**Describe the bug**
After some time (it can be 2 days or few weeks) of running `loki-distributed` we are user-facing error: "Bad Gateway", see screenshot down below.   
Under the hood the query-frontend logs:
```
level=debug ts=2022-04-19T07:24:00.469496215Z caller=logging.go:67 traceID=69987be5e9100bb6 orgID=fake msg="GET /loki/api/v1/label/app/values?start=1650349410373000000&end=1650353010374000000 (499) 29.992131507s"
level=error ts=2022-04-19T07:24:06.143692893Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"                                                                                                    
level=debug ts=2022-04-19T07:24:06.143962149Z caller=logging.go:67 traceID=36b37e92e184fad3 orgID=fake msg="GET /loki/api/v1/series?match%5B%5D=%7Bapp%3D%22someapp%22%7D&start=1650349416045000000&end=1650353016045000000 (499) 29.991957575s"                                                                                                                                                                                                                                      
level=debug ts=2022-04-19T07:24:06.299541997Z caller=logging.go:67 traceID=237c361ed0e086f9 orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bapp%3D%22someapp%22%7D&start=1650349416191000000&end=1650353016192000000&step=2 (499) 29.99084936s"
```
Restarting query-frontend **or** querier helps but this is unacceptable.  
How do I even debug this? There are no other logs in `loki-querier` or in `loki-frontend`.  
The 'context cancelled' seems like java-NPE and is meaningless   
The error happens roughly after 30 seconds of waiting (see logs)

**To Reproduce**
1.Deploy `loki-distributed` from Helm Chart in GKE environment

**Expected behavior**
Simply working loki...

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: `loki-distributed` Chart (version 0.39.3)
 
Using 3 ingester PODs, 3 gateway PODs, 3 distributor PODs, 2 querier PODs., 1 frontend POD, 1 compactor POD  
Promtail gathers logs

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
![image](https://user-images.githubusercontent.com/7331452/164179726-01bb7c4e-7226-4031-baec-dea3df74f871.png)

**Comment by dannykopping** [comment]
Hey @kiemlicz - do you have an nginx reverse-proxy in the mix?
I think the request is taking too long to respond and the proxy is killing the connection.

**Comment by kiemlicz** [comment]
Thank you @dannykopping 
Yes we have Istio in front, however it is not causing any issues

I've pinned down the 30sec timeout, it is caused by grafana datasource timeout (30 sec), increasing it yield same error but after longer timeout

Increasing it to some higher value yields, timeout from gateway (most likely caused by some clog with querier)
![image](https://user-images.githubusercontent.com/7331452/164220644-ff4f0997-e774-4c9b-bada-2f6e310beeda.png)

logs from loki-gateway
```
127.0.0.6 - - [20/Apr/2022:11:29:46 +0000]  204 "POST /loki/api/v1/push HTTP/1.1" 0 "-" "promtail/" "-"
2022/04/20 11:29:47 [error] 8#8: *10754914 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 127.0.0.6, server: , request: "GET /loki/api/v1/label?start=1650453527036000000 HTTP/1.1", upstream: "http://192.168.10.188:3100/loki/api/v1/label?start=1650453527036000000", host: "loki-gateway.logging-loki.svc.cluster.local:80"
127.0.0.6 - - [20/Apr/2022:11:29:47 +0000]  504 "GET /loki/api/v1/label?start=1650453527036000000 HTTP/1.1" 168 "-" "Grafana/8.3.4" "10.0.0.41, 127.0.0.6, 127.0.0.6"
127.0.0.6 - - [20/Apr/2022:11:29:47 +0000]  204 "POST /loki/api/v1/push HTTP/1.1" 0 "-" "promtail/" "-"
```

So I think it is down to some invisible error (most likely in querier).  
How do I find this?

**Comment by mtb-xt** [comment]
I'm not sure if this is the same issue, but looks similar. We're getting Gateway timeouts from `loki-gateway` component - both from grafana and from logcli.

When I try with `logcli` - I connect directly to loki-gateway with kubectl port-forward.

These are the logs:

logcli:
```
❯ time logcli labels
http://localhost:3100/loki/api/v1/labels?end=1659589324026827807&start=1659585724026827807
Error response from server: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.19.10</center>
</body>
</html>
 (<nil>) attempts remaining: 0
Error doing request: Run out of attempts while querying the server

real	1m0.372s
user	0m0.015s
sys	0m0.013s
```

loki-gateway:
```
[pod/loki-gateway-7d445b6bdd-b4mzz/nginx] 2022/08/04 05:03:04 [error] 9#9: *299596 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /loki/api/v1/labels?end=1659589324026827807&start=1659585724026827807 HTTP/1.1", upstream: "http://172.20.111.208:3100/loki/api/v1/labels?end=1659589324026827807&start=1659585724026827807", host: "localhost:3100"
[pod/loki-gateway-7d445b6bdd-b4mzz/nginx] 127.0.0.1 - - [04/Aug/2022:05:03:04 +0000]  504 "GET /loki/api/v1/labels?end=1659589324026827807&start=1659585724026827807 HTTP/1.1" 168 "-" "loki-logcli/2.6.0" "-"
```

loki-read
```
[pod/loki-read-2/read] level=error ts=2022-08-04T05:03:04.223013036Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
[pod/loki-read-2/read] level=error ts=2022-08-04T05:03:04.223189924Z caller=stats.go:57 component=frontend msg="failed to record query metrics" err="expected one of the *LokiRequest, *LokiInstantRequest, *LokiSeriesRequest, *LokiLabelNamesRequest, got "
```

We're using **loki-simple-scalable** helm chart.

**Comment by dannykopping** [comment]
In both of your cases @kiemlicz and @mtb-xt, I believe the error is occurring before Loki.

```bash
$ errno -l | grep 110   
ETIMEDOUT 110 Connection timed out
```

This `110: Operation timed out` error is coming from the OS network stack. The queriers could be taking too long to process a request, which exceeds the timeout, then you should try up your timeout.

@kiemlicz I don't know Istio, but [this guide](https://istio.io/latest/docs/tasks/traffic-management/request-timeouts/) looks useful. 
This error appears to be network-related 

As for @mtb-xt, since you're using the simple-scalable helm chart which uses `nginx` for its `loki-gateway` component, you could try set these 3 settings:

```nginx
   proxy_read_timeout 300;
   proxy_connect_timeout 300;
   proxy_send_timeout 300;
```

By default, nginx times out after 60s.

We try to keep GitHub issues strictly for bug reports and feature requests.
This doesn't appear to be a bug, so I'll close this issue, but please feel free to reach out in any of the channels listed below.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

**Comment by mtb-xt** [comment]
Notes for posterity (or google?)

This was indeed fixed for me by setting these in helm chart values:
```yaml
    gateway:
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/proxy-send-timeout: "500"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "500"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "500"
          nginx.ingress.kubernetes.io/client-header-timeout: "500"
          nginx.ingress.kubernetes.io/client-body-timeout: "500"
          nginx.ingress.kubernetes.io/proxy-request-buffering: off
        enabled: true
        ingressClassName: nginx-internal
        tls: null #TLS is handled by the loadbalancer
        hosts:
        - host: gateway-loki.website.xyz
          paths:
            - path: /
              pathType: ImplementationSpecific
    write:
      extraArgs:
        - -validation.max-entries-limit=20000
        - -querier.engine.timeout=5m
        - -querier.query-timeout=5m
        - -server.http-read-timeout=5m
        - -server.http-write-timeout=5m
    read:
      extraArgs:
        - -validation.max-entries-limit=20000
        - -querier.engine.timeout=5m
        - -querier.query-timeout=5m
        - -server.http-read-timeout=5m
        - -server.http-write-timeout=5m
```
