### ISSUE TITLE
[Feature request] Provide an opportunity to use more than one storage based on tenant

### ISSUE THREAD

**Issue by loki-dv** [grafana/loki#5974]
**Is your feature request related to a problem? Please describe.**
In my company we need to collect logs from different regions (EU, US) and store logs from these regions in that regions where they was collected, e.g. US logs -> in US, EU logs -> in EU. For now I did not found any method to store logs based on something, e.g. tenant in the different storages.

**Describe the solution you'd like**
I want to have an opportunity to store logs based on tenant in the different storages instead of creating one more Loki instance.

**Describe alternatives you've considered**
For now only one way to implement collecting and storing logs in the same region is creating of the separate instances of Loki pointed to S3 (in our case) in the region that we needed.

**Additional context**
Not sure that it is easy to implement. Please, let me know if this setup already available to implement.

Current config:
```
    storage_config:
      boltdb_shipper:
        shared_store: s3
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 336h
      aws:
        s3: s3://eu-central-1/
        bucketnames: mybucket-0,mybucket-1,mybucket-2,mybucket-3
        access_key_id: ${AWS_ACCESS_KEY_ID}
        secret_access_key: ${AWS_SECRET_ACCESS_KEY}
        s3forcepathstyle: true
```
