### ISSUE TITLE
invalid memberlist_config

### ISSUE THREAD

**Issue by caibirdme** [grafana/loki#6004]
**Describe the bug**
According to [latest docs](https://grafana.com/docs/loki/latest/configuration/#memberlist_config), there's no memberlist but memberlist_config field, but when I configure that, it returns error: `field memberlist_config not found in type loki.ConfigWrapper`

**To Reproduce**
Using [loki-distributed helm chart@v0.48.3](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed) to deploy loki, and subset of the config looks like:
```yaml
common:
  replication_factor: 3
memberlist_config:
  join_members:
    - loki-distributed-memberlist
```
