### ISSUE TITLE
etcd config not works

### ISSUE THREAD

**Issue by ahfuzhang** [grafana/loki#6005]
**Describe the bug**
I think etcd config is for register the services itself to etcd, but it not works.

**To Reproduce**
1. Started Loki (SHA or version):  version=2.5.0

**Expected behavior**
If etcd addr is correct, I will see ip port of services .
If etcd addr is error, program will shut down.

**Environment:**
cmd-line, macos, amd64

**Screenshots, Promtail config, or terminal output**
my yaml is:
```yaml
target: "ingester"
auth_enabled: false
ballast_bytes: 1073741824  # 1GB heap size
server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  lifecycler:
    ring:
      kvstore:
        store: "etcd"
        prefix: "/grafana_loki/test/"
        etcd:
          endpoints: ["11.135.12.18:23790"]  # correct of wrong addr, there is no diffrent
          dial_timeout: 1s
          max_retries: 1
          tls_enabled: true
          tls_cert_path: "./cert_content.txt"
          tls_key_path: "./key_content.txt"  #github.com/grafana/dskit/crypto/tls/tls.go
          tls_ca_path: "./ca_cert_content.txt"
      #end    kvstore       
      replication_factor: 1 
  #end of lifecycler
  wal:
    enabled: false

common:
  path_prefix: ./data/
  storage:
    filesystem:
      chunks_directory: "/Users/ahfuzhang/data/chunks/"
      rules_directory: "/Users/ahfuzhang/data/rules/"

schema_config:
  configs:
    - from: 2022-04-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

```
