### ISSUE TITLE
retention not available

### ISSUE THREAD

**Issue by liushaobo05** [grafana/loki#6017]
loki: v2.4.2
  setting retention config
  ```
  table_manager:
  retention_deletes_enabled: true
  retention_period: 24h
  ```

  loki running after 28h, chunk data not clear,  can query old log data

**Comment by liguozhong** [comment]
'retention_period' should be N multiples of 'period', what is your 'period'?
```yaml
schema_config:
  configs:
    - from:   2019-01-01
      store:  dynamo
      schema: v10
      index:
        prefix: loki_
        period: 168h

table_manager:
    retention_deletes_enabled: true
    retention_period: 24h
```

**Comment by liushaobo05** [comment]
> 
```
schema_config:
  configs:
  - from: "2021-07-01"
    index:
      period: 24h
      prefix: index_
    object_store: filesystem
    schema: v11
    store: boltdb-shipper
```
period: 24h
