### ISSUE TITLE
Promtail - Failed to convert string duration to float

### ISSUE THREAD

**Issue by nhuray** [grafana/loki#6057]
**Describe the bug**

I'm using promtail to parse Google Cloud HTTP load balancer logs coming from a Pub/Sub topic.
I followed the documentation here: https://grafana.com/docs/loki/latest/clients/promtail/gcplog-cloud/

I defined the following configuration to scrape the logs and derive metrics from logs:

```
      - job_name: http_load_balancer
        gcplog:
          project_id: "my-project"
          subscription: "promtail"
          use_incoming_timestamp: true
        pipeline_stages:
          - json:
              expressions:
                httpRequest:
          - json:
              source: httpRequest
              expressions:
                method: requestMethod
                code: status
                response_time: latency
                response_bytes: responseSize
                request_bytes: requestSize
          - labels:
              method:
              code:
          - metrics:
              request_duration_seconds:
                type: Histogram
                description: "How long it took to process the request, partitioned by status code and method."
                prefix: http_load_balancer_
                max_idle_duration: 24h
                source: response_time
                config:
                  buckets: [0.1,0.3,0.6,1.2,5]
```

The log line to parse looks like that:
![StaticShot_29-04-2022_09-57-04](https://user-images.githubusercontent.com/958983/165960778-e4fd471a-7cc0-4335-a728-72cfc994cb74.png)

The `latency` field is a string (i.e `0.347560s`) who should be converted to a float as specified in the [documentation](https://grafana.com/docs/loki/latest/clients/promtail/stages/metrics/#supported-values), but unfortunately the parsing to float is failing:

![StaticShot_29-04-2022_10-10-48](https://user-images.githubusercontent.com/958983/165961476-27a2939e-5e52-4fc9-996e-5dc0e5a7268e.png)

**Expected behavior**

A string defined as duration should be converted properly to float as stated in the documentation:
 
![StaticShot_29-04-2022_10-06-51](https://user-images.githubusercontent.com/958983/165961442-78fc46fa-cde8-458b-a699-37cee31a8164.png)

**Environment:**
 - Infrastructure: Kubernetes (GKE)
 - Promtail Helm chart version: 3.5.0
 - Promtail Image:  docker.io/grafana/promtail:2.2.0
