### ISSUE TITLE
Loki-stack helm chart misconfiguring promtail

### ISSUE THREAD

**Issue by clanktron** [grafana/loki#6081]
**Issue:**
Promtail fails to scrape logs properly after helm install. Loki can only see a couple namespaces and promtail pods have the same error over and over with slight variation (seen below). 

`level=error ts=2022-05-03T02:57:21.673928525Z caller=filetarget.go:295 msg="failed to tail file, stat failed" error="stat /var/log/pods/kube-system_kube-scheduler-server_c6fe41aa31dd61848da3d5a4bbbc42b6/kube-scheduler/2.log: no such file or directory" filename=/var/log/pods/kube-system_kube-scheduler-server_c6fe41aa31dd61848da3d5a4bbbc42b6/kube-scheduler/2.log
level=error ts=2022-05-03T02:58:21.673718159Z caller=filetarget.go:295 msg="failed to tail file, stat failed" error="stat /var/log/pods/kube-system_kube-apiserver-server_32dfdad0223e572cee94439d2f0781b3/kube-apiserver/1.log: no such file or directory" filename=/var/log/pods/kube-system_kube-apiserver-server_32dfdad0223e572cee94439d2f0781b3/kube-apiserver/1.log`

**To Reproduce**
Install grafana/loki-stack helm chart with the values.yaml file seen below

```
loki:
  enabled: true
  isDefault: true
  persistence:
    enabled: true
    storageClassName:

promtail:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: true
  persistence:
    enabled: true
    storageClassName:
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 8.3.5

prometheus:
  enabled: true
  persistence:
    enabled: true
    storageClassName:
  isDefault: false
```

**Expected behavior**
After installing, promtail should be properly scraping data from the k8s cluster and pushing to loki.

**Environment:**
Infrastructure: 'Vanilla' k8s running on debian bullseye
Deployment tool: Official Helm chart (grafana/loki-stack)
