### ISSUE TITLE
Grafana + loki binary --> Grafana Bad Gateway. 502. Bad Gateway

### ISSUE THREAD

**Issue by pH-T** [grafana/loki#6106]
**Describe the bug**
Grafana cant connect to loki (running as systemd service) via caddy reverse proxy: "Loki: Bad Gateway. 502. Bad Gateway"
Im not sure if its a bug or if Im doing something wrong...

**To Reproduce**
1. Start loki (listening on localhost) on a VPS with domain: loki.example.com:
```
scp config/loki-config.yaml root@$1:loki-config.yaml
scp config/loki.service root@$1:/etc/systemd/system/loki.service


on VPS:
curl -O -L https://github.com/grafana/loki/releases/download/v2.5.0/loki-linux-amd64.zip
unzip loki-linux-amd64.zip
rm loki-linux-amd64.zip
mv loki-linux-amd64 /usr/local/bin
chmod a+x /usr/local/bin/loki-linux-amd64
mkdir /etc/loki
mv loki-config.yaml /etc/loki/loki-config.yaml
systemctl daemon-reload
systemctl start loki
systemctl status loki --> is running
ss -ltpn --> is running on 127.0.0.1:3100
curl 127.0.0.1:3100/ready --> ready
```

loki.service:
```
[Unit]
Description=Loki service
After=network.target

[Service]
Type=simple
User=root
ExecStart=/usr/local/bin/loki-linux-amd64 -config.file /etc/loki/loki-config.yaml

[Install]
WantedBy=multi-user.target
```

loki-config.yaml:
```
auth_enabled: false

server:
  http_listen_port: 3100
  http_listen_address: 127.0.0.1 # use only without docker
  grpc_listen_port: 9096
  grpc_listen_address: 127.0.0.1 # use only without docker

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /tmp/retention
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  retention_period: 24h

ruler:
  alertmanager_url: http://localhost:9093
```

2. Install Caddy:
```
sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo tee /etc/apt/trusted.gpg.d/caddy-stable.asc
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
sudo apt update
sudo apt install -y caddy
echo -e "loki.example.com {\n        basicauth * {\n                loki <caddy hash-password PW>\n        }\n        reverse_proxy localhost:3100\n}" >> /etc/caddy/Caddyfile
sudo systemctl reload caddy
```
3. Now **outside** of the VPS: `curl -u "loki:<PW>" https://loki.example.com/ready` --> ready
4. Run grafana outside of the VPS: `docker run -p 127.0.0.1:3000:3000 grafana/grafana-oss:latest`
5. Add loki datasource in grafana:
    - URL: "https://loki.example.com"
    - User: "loki"
    - PW: `<PW>`
6. ---> "Loki: Bad Gateway. 502. Bad Gateway"

**Expected behavior**
Would have expected: "Data source connected and labels found."

**If I do the same as above except starting loki via docker, grafana is able to add loki as a datasource**:
1.  use `loki-config.yaml` as above (see comments in loki-config.yaml for only difference)
2. `docker run -d --name loki -v $(pwd):/mnt/config -p 127.0.0.1:3100:3100 grafana/loki:2.4.2 -config.file=/mnt/config/loki-config.yaml` 
3. `ss -ltpn` --> is running on 127.0.0.1:3100 (via docker-proxy)
4. `curl 127.0.0.1:3100/ready` --> ready
5. Now **outside** of the VPS: `curl -u "loki:<PW>" https://loki.example.com/ready` --> ready
6. Now grafana tells me "Data source connected and labels found." with the same datasource config as above.

I am pretty clueless about the issue. ~~I dont think its caddy or grafana related as the only "moving" part between attampts it running loki as binary vs as docker image.~~ Actually it could be grafana related as well...

**Environment:**
 - VPS (loki, caddy)
 - Private host (grafana)

**Screenshots, Promtail config, or terminal output**
(can add more info if needed)

Thanks!

**Comment by pH-T** [comment]
i was able to further isolate the issue:
if i run the loki binary (without docker) with the following config it works as expected:
* `curl localhost:3100/ready` --> ready
* `curl localhost:3100/loki/api/v1/label\?start=1652213759436000000` --> `{"status":"success","data":["__name__"]}`
* grafana is able to connect to loki
```
...
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  ...
```
now if i add `http_listen_address` and `grpc_listen_address` with `127.0.0.1`  to the config:
```
...
server:
  http_listen_port: 3100
  http_listen_address: 127.0.0.1
  grpc_listen_port: 9096
  grpc_listen_address: 127.0.0.1
  ...
  ```
... the following happens:
* `curl localhost:3100/ready` --> ready (as above)
* `curl localhost:3100/loki/api/v1/label\?start=1652213759436000000` --> just **hangs** and runs into timeout
* grafana is **not** able to connect to loki

loki log shows the following:
```
level=info ts=2022-05-10T20:41:48.067532727Z caller=loki.go:372 msg="Loki started"
level=info ts=2022-05-10T20:41:51.056384437Z caller=scheduler.go:661 msg="this scheduler is in the ReplicationSet, will now accept requests."
level=info ts=2022-05-10T20:41:51.05660489Z caller=worker.go:209 msg="adding connection" addr=127.0.0.1:9096
level=info ts=2022-05-10T20:41:53.068194917Z caller=compactor.go:324 msg="this instance has been chosen to run the compactor, starting compactor"
level=info ts=2022-05-10T20:41:53.068417416Z caller=compactor.go:351 msg="waiting 10m0s for ring to stay stable and previous compactions to finish before starting compactor"
level=info ts=2022-05-10T20:41:58.056597797Z caller=frontend_scheduler_worker.go:101 msg="adding connection to scheduler" addr=127.0.0.1:9096
level=info ts=2022-05-10T20:42:47.928374591Z caller=table_manager.go:169 msg="uploading tables"
level=error ts=2022-05-10T20:43:01.609227974Z caller=scheduler_processor.go:188 org_id=fake msg="error notifying frontend about finished query" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.0.0.12:9096: connect: connection refused\"" frontend=10.0.0.12:9096
level=warn ts=2022-05-10T20:43:03.056717106Z caller=pool.go:184 msg="removing frontend failing healthcheck" addr=10.0.0.12:9096 reason="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.0.0.12:9096: connect: connection refused\""
level=error ts=2022-05-10T20:43:10.182946436Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
```
loki seems to use `10.0.0.12:9096` internally - it should(?) be `127.0.0.1`, as given in the conifg file.
if i interpret this correctly: loki does not use the the "right" IP in this case?
