### ISSUE TITLE
Ceph Storage Support

### ISSUE THREAD

**Issue by mizeng** [grafana/loki#611]
I've seen Ceph can used for Chunk storage in https://speakerdeck.com/gouthamve/devopsdaysindia-2018-loki-prometheus-but-for-logs?slide=29.

However I didn't find how to use Ceph in Loki. Could you share more?

**Comment by ningyougang** [comment]
> I believe thanks to your work @mizeng that ceph via the s3 api is working now? We recently setup a cluster using rook/ceph with the s3 api and it appears to be working. Are you ok with closing this issue?

Can you share you configuration? @slim-bean

**Comment by ausias-armesto** [comment]
Hi @ningyougang , 
I've managed to installed in there were some tricky points to consider in the installation. This is my configuration
```
loki:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "linode-issuer"
  gateway:
    enabled: false
  test:
    enabled: false
  monitoring:
    dashboards:
      enabled: false
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false
  backend:
    persistence:
      storageClass: ceph-filesystem
      enableStatefulSetAutoDeletePVC: false
      size: 10Gi
    extraArgs:
        - '-config.expand-env=true'
    extraEnv:
      - name: S3_LOKI_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: bucket-loki
            key: AWS_ACCESS_KEY_ID
      - name: S3_LOKI_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: bucket-loki
            key: AWS_SECRET_ACCESS_KEY
  write:
    replicas: 2
    persistence:
      storageClass: ceph-filesystem
      enableStatefulSetAutoDeletePVC: false
      size: 10Gi
    extraArgs:
        - '-config.expand-env=true'
    extraEnv:
      - name: S3_LOKI_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: bucket-loki
            key: AWS_ACCESS_KEY_ID
      - name: S3_LOKI_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: bucket-loki
            key: AWS_SECRET_ACCESS_KEY
  read:
    replicas: 2
    persistence:
      storageClass: ceph-filesystem
      enableStatefulSetAutoDeletePVC: false
      size: 10Gi
    extraArgs:
        - '-config.expand-env=true'
    extraEnv:
      - name: S3_LOKI_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: bucket-loki
            key: AWS_ACCESS_KEY_ID
      - name: S3_LOKI_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: bucket-loki
            key: AWS_SECRET_ACCESS_KEY
  loki:
    auth_enabled: false
    limits_config:
      retention_period: 72h
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      # for big logs tune
      per_stream_rate_limit: 512M
      per_stream_rate_limit_burst: 1024M
      cardinality_limit: 200000
      ingestion_burst_size_mb: 1000
      ingestion_rate_mb: 10000
      max_entries_limit_per_query: 1000000
      max_label_value_length: 20480
      max_label_name_length: 10240
      max_label_names_per_series: 300
    storage:
      bucketNames:
        chunks: bucket-loki
        ruler: bucket-loki
        admin: bucket-loki
      s3:
        accessKeyId: ${S3_LOKI_ACCESS_KEY_ID}
        secretAccessKey: ${S3_LOKI_SECRET_ACCESS_KEY}
        endpoint: "https://buckets.<YOUR_HOST_DOMAIN>/bucket-loki"
        insecure": true
        s3forcepathstyle: false
      type: s3
```

It's worth to mention that Ceph Object storage is using a different pattern for the API. While the S3 standard format is to have a this pattern: `https://<bucket_name>.<bucket_server>` . Ceph is using a different pattern. Ceph only creates a single Kubernetes service for all the buckets created, and for accessing to them requires you to put a context path. See this example: https://rook.io/docs/rook/latest/Storage-Configuration/Object-Storage-RGW/object-storage/?h=bucket#put-or-get-an-object

So what I did is to create an Ingress entry to allow direct access to the bucket
````
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: linode-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: 2m
  name: bucket-loki
  namespace: rook-ceph
spec:
  ingressClassName: nginx
  rules:
  - host: "bucket-loki.buckets.{{ .Values.domain }}"
    http:
      paths:
      - backend:
          service:
            name: rook-ceph-rgw-ceph-new-objectstore
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - "bucket-loki.buckets.{{ .Values.domain }}"
    secretName: "bucket-loki.buckets.{{ .Values.domain }}-tls"
```

Somehow Loki modifies this endpoint `https://buckets.<YOUR_HOST_DOMAIN>/bucket-loki` to this other resolved endpoint "https://bucket-loki.buckets.<YOUR_HOST_DOMAIN>/bucket-loki"

I hope anyone can help this
