### ISSUE TITLE
Loki schema validity not enforced when writing

### ISSUE THREAD

**Issue by jcdauchy-moodys** [grafana/loki#6114]
**Describe the bug**
While backfilling old data into Loki, we managed to ingest data older than the schema start date.

We had no error when ingesting, but it was not possible to read them back.

**To Reproduce**
1. Started Loki (SHA or version) : 2.4.1

Ingest data older than the start validity date (2022-01-01)

Important loki settings

```
limits_config:
  # We want to be able to ingest really old data : https://github.com/grafana/loki/issues/4914
  reject_old_samples: false
  # Allow to inject 5 years old entries
  reject_old_samples_max_age: 43800h


schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_
        period: 24h
```

I have attached an example script used to ingest data with CURL.

[testLokiBackfill.zip](https://github.com/grafana/loki/files/8641686/testLokiBackfill.zip)

**Expected behavior**
I would have expected loki to send an error message telling that it could not find a valid schema for the ingested data. We got no error (HTTP code 204).

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
No data could be retrieved if this schema validity. 
As soon as I set a valid schema validaty (older), I could query the data.
