### ISSUE TITLE
[2.5.0] Error: creating WAL folder

### ISSUE THREAD

**Issue by budarin** [grafana/loki#6122]
**Describe the bug**
Use loki driver for logging. It is upgraded to the latest version.
Previous version of Loki works fine. Decided to install version 2.5.0 and got the bug

compose.yml
```yaml
    image: grafana/loki:latest
        volumes:
            - loki_vol:/loki
            - ./config/loki/loki.yaml:/etc/loki/config.yaml:ro
        command: -config.file=/etc/loki/config.yaml
        ports:
            - 3100:3100
```
Log driver oprions
```yaml
    driver: 'loki'
    options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
        keep-file: 'true'
```

loki config from https://grafana.com/docs/loki/latest/configuration/examples/#complete-local-configyaml
```yaml
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2020-05-15
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
```
Loki container fails to start with error:
```log
level=info ts=2022-05-08T13:09:14.343758Z caller=main.go:106 msg="Starting Loki" version="(version=2.5.0, branch=HEAD, revision=2d9d0ee23)"
level=info ts=2022-05-08T13:09:14.3440932Z caller=modules.go:597 msg="RulerStorage is not configured in single binary mode and will not be started."
level=info ts=2022-05-08T13:09:14.3449265Z caller=server.go:260 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=warn ts=2022-05-08T13:09:14.3470989Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache"
level=error ts=2022-05-08T13:09:14.3592785Z caller=log.go:100 msg="error running loki" err="creating WAL folder at \"/wal\": 
mkdir wal: permission denied\nerror initialising module: ingester\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:339\nmain.main\n\t/src/loki/cmd/loki/main.go:108\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
```

Previous config
```yaml
target: all
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093

frontend:
  address: 127.0.0.1

```

**Environment:**
 - Windows 10
 - Docker desktop

**Comment by DylanGuedes** [comment]
Just for curiosity, what is the previous version of Loki that you've been running? My bet is that you were running a kinda old version that doesn't have WAL enabled by default. That said, you have two options:
- Provide a valid folder for WAL. The container doesn't have permission to directly create it inside `/` so you should provide another folder that is valid. Ex:
```yaml
ingester:
  wal:
    dir: "/tmp/wal"
```
- Disable WAL, which we really advocate against unless you're just trying Loki. To disable it:
```yaml
ingester:
  wal:
    enabled: false
```

**Comment by budarin** [comment]
@DylanGuedes 

I think it should be in the configuration sample in the documentation - I took this config from the documentation
By the way, solving the problem with `wal` does not solve the general problem of correct operation of loki - another error appears

```
level=info ts=2022-05-08T22:15:55.4783051Z caller=loki.go:373 msg="Loki stopped"
level=error ts=2022-05-08T22:15:55.4785382Z caller=log.go:100 msg="error running loki" err="failed services\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:419\nmain.main\n\t/src/loki/cmd/loki/main.go:108\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
```

In general, the documentation needs a working config or loki should work locally without configurations (unfortunately, loki do not work locally by default without a config)

**Comment by jinglanghe** [comment]
It seems like loki doesn't support   .   /   - strings, but supports _

**Comment by kondelik** [comment]
Same problem here. Adding
```
ingester:
  (...)
  wal:
    dir: "/tmp/wal"
```
fixed the issue.


I think this (not really working?) configuration of ingestor comes from https://grafana.com/docs/loki/latest/configuration/examples/#complete-local-configyaml
