### ISSUE TITLE
compactor_address configuration issue

### ISSUE THREAD

**Issue by irizzant** [grafana/loki#6131]
**Describe the bug**
I have Loki deployed with Tanka in microservice mode configured with [these instructions](https://grafana.com/docs/loki/latest/installation/tanka/).

The generated Loki configuration is invalid and prevents Pods from starting with the following log:
```
failed parsing config: /etc/loki/config/config.yaml: yaml: unmarshal errors:
  line 24: field compactor_address not found in type lokifrontend.Config
```
```yaml
hunk_store_config:
    chunk_cache_config:
        memcached:
            batch_size: 100
            parallelism: 100
        memcached_client:
            consistent_hash: true
            host: memcached.loki.svc.cluster.local
            service: memcached-client
compactor:
    shared_store: s3
    working_directory: /data/compactor
distributor:
    ring:
        kvstore:
            consul:
                consistent_reads: false
                host: consul.loki.svc.cluster.local:8500
                http_client_timeout: 20s
                watch_burst_size: 1
                watch_rate_limit: 1
            store: consul
frontend:
    compactor_address: http://compactor.loki.svc.cluster.local:3100
    compress_responses: true
    log_queries_longer_than: 5s
    max_outstanding_per_tenant: 256
frontend_worker:
    frontend_address: query-frontend.loki.svc.cluster.local.:9095
    grpc_client_config:
        max_send_msg_size: 1.048576e+08
    match_max_concurrent: true
ingester:
    chunk_block_size: 262144
    chunk_idle_period: 15m
    lifecycler:
        heartbeat_period: 5s
        interface_names:
            - eth0
        join_after: 30s
        num_tokens: 512
        ring:
            heartbeat_timeout: 1m
            kvstore:
                consul:
                    consistent_reads: true
                    host: consul.loki.svc.cluster.local:8500
                    http_client_timeout: 20s
                store: consul
            replication_factor: 3
    max_transfer_retries: 0
    wal:
        dir: /loki/wal
        enabled: true
        replay_memory_ceiling: 7GB
ingester_client:
    grpc_client_config:
        max_recv_msg_size: 6.7108864e+07
    remote_timeout: 1s
limits_config:
    enforce_metric_name: false
    ingestion_burst_size_mb: 20
    ingestion_rate_mb: 10
    ingestion_rate_strategy: global
    max_cache_freshness_per_query: 10m
    max_global_streams_per_user: 10000
    max_query_length: 12000h
    max_query_parallelism: 16
    max_streams_per_user: 0
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    split_queries_by_interval: 30m
querier:
    max_concurrent: 4
    query_ingesters_within: 2h
query_range:
    align_queries_with_step: true
    cache_results: true
    max_retries: 5
    results_cache:
        cache:
            memcached_client:
                consistent_hash: true
                host: memcached-frontend.loki.svc.cluster.local
                max_idle_conns: 16
                service: memcached-client
                timeout: 500ms
                update_interval: 1m
ruler: {}
schema_config:
    configs:
        - from: "2022-05-10"
          index:
            period: 24h
            prefix: loki_index_
          object_store: s3
          schema: v11
          store: boltdb-shipper
server:
    graceful_shutdown_timeout: 5s
    grpc_server_max_concurrent_streams: 1000
    grpc_server_max_recv_msg_size: 1.048576e+08
    grpc_server_max_send_msg_size: 1.048576e+08
    grpc_server_min_time_between_pings: 10s
    grpc_server_ping_without_stream_allowed: true
    http_listen_port: 3100
    http_server_idle_timeout: 120s
    http_server_write_timeout: 1m
storage_config:
    aws:
        s3: s3://admin:Lz4ELoYan6@url/loki
        s3forcepathstyle: true
    boltdb_shipper:
        active_index_directory: /data/index
        cache_location: /data/boltdb-cache
        shared_store: s3
    index_queries_cache_config:
        memcached:
            batch_size: 100
            parallelism: 100
        memcached_client:
            consistent_hash: true
            host: memcached-index-queries.loki.svc.cluster.local
            service: memcached-client
table_manager:
    creation_grace_period: 3h
    poll_interval: 10m
    retention_deletes_enabled: false
    retention_period: 0
```

**To Reproduce**
1. Deploy Loki with [these instructions](https://grafana.com/docs/loki/latest/installation/tanka/)
2. Look at the Compactor's logs

**Expected behavior**
Loki should start

**Environment:**
 - Infrastructure: Kubernetes (k3d latest version)
 - Deployment tool: Tanka

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
