### ISSUE TITLE
log label doesn't match when use promtail

### ISSUE THREAD

**Issue by zhoushuke** [grafana/loki#6140]
**Describe the bug**
some pod name doesn't match filename showed in grafana query when log use loki & promtail
I have no idel what is happend and googled for a while and not working.

**To Reproduce**
none

**Expected behavior**
pod name matches filename

**Environment:**
 - kubernetes: v1.15.5
 - loki: v2.3.0
 - promtail:2.3.0
 - grafana: v8.1.6

**Screenshots, Promtail config, or terminal output**
there is promtail config:
```yaml
---
# Source: promtail/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: promtail
  labels:
    helm.sh/chart: promtail-3.1.0
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/version: "2.1.0"
    app.kubernetes.io/managed-by: Helm
stringData:
  promtail.yaml: |
    server:
      log_level: info
      http_listen_port: 3101

    client:
      url: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push

    target_config:
      sync_period: 30s

    positions:
      filename: /run/promtail/positions.yaml
      sync_period: 30s

    scrape_configs:
      # Pods with cronjob
      - job_name: kubernetes-pod-cronjob
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            # 这里用regex只是匹配，不做替换
            regex: .+
            source_labels:
            - __meta_kubernetes_pod_label_job_name
          - action: replace
            # regex这里要注意的是带不带(),如果是replace，则需要用正则匹配到的字符串去写入target_label的value中
            # 而replacement则是指定是第几个正则匹配到的元素，也就是第几个括号
            regex: (.+)
            replacement: '${1}'
            source_labels:
            - __meta_kubernetes_pod_label_job_name
            target_label: cronjob_pod 
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_node_name
            target_label: node_name
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
            target_label: __path__
      

      # Pods with a label 'app'
      - job_name: kubernetes-pods-app
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: drop
            regex: .+
            source_labels:
            - __meta_kubernetes_pod_label_workflows_argoproj_io_workflow
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_label_app
            target_label: app
          - action: drop
            regex: ''
            source_labels:
            - app
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_label_component
            target_label: component
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_node_name
            target_label: node_name
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
            target_label: __path__

      # Pods with direct controllers, such as StatefulSet
      - job_name: kubernetes-pods-direct-controllers
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: drop
            regex: .+
            separator: ''
            source_labels:
            - __meta_kubernetes_pod_label_workflows_argoproj_io_workflow
            - __meta_kubernetes_pod_label_app
          - action: drop
            regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
            source_labels:
            - __meta_kubernetes_pod_controller_name
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_controller_name
            target_label: app
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_node_name
            target_label: node_name
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
            target_label: __path__
          # - action: replace
          #   replacement: /var/log/pods/*$1/*.log
          #   separator: /
          #   source_labels:
          #   - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
          #   - __meta_kubernetes_pod_container_name
          #   target_label: __path__

      # Pods with indirect controllers, such as Deployment
      - job_name: kubernetes-pods-indirect-controller
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: drop
            regex: .+
            separator: ''
            source_labels:
            - __meta_kubernetes_pod_label_workflows_argoproj_io_workflow
            - __meta_kubernetes_pod_label_app
          - action: keep
            regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
            source_labels:
            - __meta_kubernetes_pod_controller_name
          - action: replace
            regex: '([0-9a-z-.]+)-[0-9a-f]{8,10}'
            source_labels:
            - __meta_kubernetes_pod_controller_name
            target_label: app
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_node_name
            target_label: node_name
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
            target_label: __path__
          # - action: replace
          #   replacement: /var/log/pods/*$1/*.log
          #   separator: /
          #   source_labels:
          #   - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
          #   - __meta_kubernetes_pod_container_name
          #   target_label: __path__
      # All remaining pods not yet covered
      - job_name: kubernetes-other
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # Drop what has already been covered
          - action: drop
            regex: .+
            separator: ''
            source_labels:
            - __meta_kubernetes_pod_label_workflows_argoproj_io_workflow
            - __meta_kubernetes_pod_label_app
          - action: drop
            regex: .+
            source_labels:
            - __meta_kubernetes_pod_controller_name
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: app
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_label_component
            target_label: component
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_node_name
            target_label: node_name
          - action: replace
            source_labels:
            - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            source_labels:
            - __meta_kubernetes_pod_container_name
            target_label: container
          - action: replace
            replacement: /var/log/pods/*$1/*.log
            separator: /
            source_labels:
            - __meta_kubernetes_pod_uid
            - __meta_kubernetes_pod_container_name
            target_label: __path__
          # - action: replace
          #   replacement: /var/log/pods/*$1/*.log
          #   separator: /
          #   source_labels:
          #   - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
          #   - __meta_kubernetes_pod_container_name
          #   target_label: __path__
```
and following is the wrong log label in grafana explore
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/6121952/167766004-67478c03-4789-4a82-8af8-b2f891e3f453.png">
