### ISSUE TITLE
Promtail Cloudflare logpull stops working after a period of time

### ISSUE THREAD

**Issue by Aaron-ML** [grafana/loki#6150]
**Describe the bug**
After running for ~72 hours cloudflare logs stop working with an opaque error below:

```
level=error ts=2022-05-11T20:06:44.445751771Z caller=target.go:122 target=cloudflare msg="failed to pull logs" err="5 errors: could not read response body: http2: response body closed; could not read response body: http2: response body closed; could not read response body: http2: response body closed; could not read response body: http2: response body closed; could not read response body: http2: response body closed" start=2022-05-11T11:34:12.817280963Z end=2022-05-11T11:35:12.817280963Z
```
**To Reproduce**
1. Launch Promtail 2.5.0 via helm
2. Tail cloudflare logs using the config below

**Expected behavior**
Cloudflare logs should continue to pull over time without failing.

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
```
              extraScrapeConfigs: |
                - job_name: cloudflare_prod
                  cloudflare:
                    pull_range: 1m
                    api_token: x
                    zone_id: x
                    fields_type: default
                    labels:
                      job: cloudflare-prod
```
![image](https://user-images.githubusercontent.com/11187707/168015692-13d71d31-31c3-46d6-bd81-7248247afca5.png)
