### ISSUE TITLE
Docker driver seems not work. Grafana explorer with Loki not show labels on log browser.

### ISSUE THREAD

**Issue by nawbc** [grafana/loki#6156]
**Describe the bug**
The default labels 'swarm_stack', 'swarm_service', 'host' can't find. But according to doc, the driver will auto discover service name.

**To Reproduce**
1. loki 2.2.1
2. promtail 2.2.1
3. grafana:7.5.15
4. driver: latest

**Environment:**
 - Infrastructure: Docker Swarm
 - Deployment tool: stack
 - OS: Manjaro 

compose file
```yaml
x-logging: &loki-logging
  driver: loki:latest
  options:
    loki-url: 'http://loki:3100/loki/api/v1/push'
    max-size: '300m'

```
promtail.yaml
```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: varlogs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /ext_logs/*log

```

loki.yaml

<details>

auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576 # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0 # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
</details>

**Screenshots, Promtail config, or terminal output**

![image](https://user-images.githubusercontent.com/45007226/168089312-0a383fe7-a313-428f-89f9-db461630de37.png)

![image](https://user-images.githubusercontent.com/45007226/168046683-c6973f7c-298f-42cf-a353-1d1c0e4e0c2e.png)
