### ISSUE TITLE
Unable to fetch logs > 14d

### ISSUE THREAD

**Issue by gmavadiy** [grafana/loki#6157]
**Describe the bug**
Unable to query for logs that are older than 14d.  

**To Reproduce**
1. Loki v2.3.0
2. Query for logs > 14d

UI returns:
`invalid query, through < from (2022-04-27 06:59:00 +0000 UTC < 2022-04-28 17:37:00.857446481 +0000 UTC m=-954420.075368366)`

S3 lifecycle i set to delete objects only after 1y

**Expected behavior**
Log lines should be returned

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**

```
    table_manager:
      retention_deletes_enabled: false
      # to maintain table entries for 365d
      retention_period: 8760h
```
