### ISSUE TITLE
Using `docker_sd_config` with Nomad bridge networking

### ISSUE THREAD

**Issue by nahsi** [grafana/loki#6165]
I'm running promtail at host, scraping docker socket to get the logs of containers running in Nomad.

Some containers are running in [`bridge` mode](https://www.nomadproject.io/docs/job-specification/network#network-modes). In this mode Nomad will create a bridge interface and a separate iptables rules chain.

Containers running in Nomad bridge networking mode are not autodiscovered  by promtail. I guess the issue is somewhere in the code responsible for creation of `__meta_docker_network_.*` labels?

![image](https://user-images.githubusercontent.com/28529663/168437702-a2a9fc3e-e282-4b35-ab4d-be1c44b0e254.png)
![image](https://user-images.githubusercontent.com/28529663/168437800-8268783d-5279-4a48-b586-7e7105c3c0fd.png)

My promtail config:
```yaml
  server:
    http_listen_port: 9380
    http_listen_address: "{{ private_ip }}"
    grpc_listen_port: 0

  positions:
    filename: "{{ promtail_dir }}/positions.yml"

  clients:
    - url: "https://loki-distributor.service.consul/loki/api/v1/push"
      external_labels:
        dc: "{{ dc }}"
        instance: "{{ inventory_hostname }}"
      basic_auth:
        username: "promtail"
        password: "{{ lookup('hashi_vault', 'secret/data/promtail/loki:password') }}"

  scrape_configs:
    - job_name: "syslog"
      syslog:
        listen_address: "127.0.0.1:1514"
        idle_timeout: "3600s"
        use_incoming_timestamp: true
      relabel_configs:
        - source_labels: ["__syslog_message_hostname"]
          target_label: "instance"
        - source_labels: ["__syslog_message_app_name"]
          target_label: "app"
        - source_labels: ["__syslog_message_facility"]
          target_label: "facility"
      pipeline_stages:
        - match:
            selector: '{app=~"({{ _syslog | join("|")}})"}'
            stages:
              - static_labels:
                  filtered: "true"
                  source: "syslog"
        - match:
            selector: '{filtered!="true"}'
            action: drop
            drop_counter_reason: "syslog-filter"
        - labeldrop:
            - "filtered"

    - job_name: "opnsense"
      syslog:
        listen_address: "{{ private_ip }}:1514"
        idle_timeout: "3600s"
        use_incoming_timestamp: true
        labels:
          source: "opnsense"
      relabel_configs:
        - source_labels: ["__syslog_message_hostname"]
          target_label: "instance"
        - source_labels: ["__syslog_message_app_name"]
          target_label: "app"
        - source_labels: ["__syslog_message_facility"]
          target_label: "facility"

    - job_name: "promtail"
      static_configs:
        - labels:
            __path__: "/var/log/promtail/promtail.log"
            source: "system"
            app: "promtail"
      pipeline_stages:
        - regex:
            expression: '^level=(?P<level>\S+) ts=(?P<time>\S+) .*'
        - timestamp:
            source: time
            format: "RFC3339Nano"

    - job_name: "portage"
      static_configs:
        - labels:
            __path__: "/var/log/emerge.log"
            source: "system"
            app: "portage"
      pipeline_stages:
        - regex:
             expression: '^(?P<time>\d+):.*'
        - timestamp:
            source: "time"
            format: "Unix"

    - job_name: "vault"
      static_configs:
        - labels:
            __path__: "/var/log/vault/vault.log"
            source: "system"
            app: "vault"
      pipeline_stages:
        - multiline:
            firstline: '^\S+ [\S+]'
        - regex:
            expression: '^(?P<time>\S+) [(?P<level>\S+)] .*'
        - timestamp:
            source: "time"
            format: "RFC3339Nano"

    - job_name: "vault-agent"
      static_configs:
        - labels:
            __path__: "/var/log/vault-agent/vault-agent.log"
            source: "system"
            app: "vault-agent"
      pipeline_stages:
        - multiline:
            firstline: '^\S+ [\S+]'
        - regex:
            expression: '^(?P<time>\S+) [(?P<level>\S+)] .*'
        - timestamp:
            source: "time"
            format: "RFC3339Nano"

    - job_name: "nomad"
      static_configs:
        - labels:
            __path__: "/var/log/nomad/nomad.log"
            source: "system"
            app: "nomad"
      pipeline_stages:
        - multiline:
            firstline: '^\S+ [\S+]'
        - regex:
            expression: '^(?P<time>\S+) [(?P<level>\S+)] .*'
        - timestamp:
            source: "time"
            format: "RFC3339Nano"

    - job_name: "consul"
      static_configs:
        - labels:
            __path__: "/var/log/consul/*"
            source: "system"
            app: "consul"
      pipeline_stages:
        - multiline:
            firstline: '^\S+ [\S+]'
        - regex:
            expression: '^(?P<time>\S+) [(?P<level>\S+)] .*'
        - timestamp:
            source: "time"
            format: "RFC3339Nano"

    - job_name: "docker"
      static_configs:
        - labels:
            __path__: "/var/log/docker.log"
            source: "system"
            app: "docker"
      pipeline_stages:
        - timestamp:
            source: "time"
            format: "RFC3339"

    - job_name: "telegraf"
      static_configs:
        - labels:
            __path__: "/var/log/telegraf/telegraf.log"
            source: "system"
            app: "telegraf"
      pipeline_stages:
        - regex:
             expression: "^(?P<time>.+) (?P<level>.)! .*"
        - labels:
            level:
        - timestamp:
            source: "time"
            format: "RFC3339"

    - job_name: "docker"
      docker_sd_configs:
        - host: "unix:///var/run/docker.sock"
          refresh_interval: "5s"
      relabel_configs:
        - source_labels: ['__meta_docker_container_label_com_hashicorp_nomad_alloc_id']
          target_label: "alloc_id"
        - source_labels: ['__meta_docker_container_label_com_hashicorp_nomad_namespace']
          target_label: "namespace"
        - source_labels: ['__meta_docker_container_label_com_hashicorp_nomad_job_name']
          target_label: "job"
        - source_labels: ['__meta_docker_container_label_com_hashicorp_nomad_task_group_name']
          target_label: "group"
        - source_labels: ['__meta_docker_container_label_com_hashicorp_nomad_task_name']
          target_label: "task"
      pipeline_stages:
        - static_labels:
            source: "nomad"

        - match: # traefik
            selector: '{task="traefik"}'
            pipeline_name: "traefik"
            stages:
            - regex:
                expression: '^time="(?P<time>.*)" level=(?P<level>.*) .*'
            - timestamp:
                source: time
                format: "RFC3339"
            - static_labels:
                filtered: "true"

        - match: # grafana
            selector: '{job="grafana",group="grafana",task="grafana"}'
            pipeline_name: "grafana"
            stages:
            - regex:
                expression: '^t=(?P<time>\S+) lvl=(?P<level>\S+).*$'
            - timestamp:
                source: time
                format: "2006-01-02T15:04:05-0700"
            - static_labels:
                filtered: "true"

        - match: # loki
            selector: '{job="loki",task!~"connect-.*"}'
            pipeline_name: "loki"
            stages:
            - regex:
                expression: '^.* ts=(?P<time>\S+).*$'
            - timestamp:
                source: time
                format: "RFC3339Nano"
            - static_labels:
                filtered: "true"

        - match: # promtail
            selector: '{task="promtail"}'
            pipeline_name: "promtail"
            stages:
            - regex:
                expression: '^level=(?P<level>\S+) ts=(?P<time>\S+).*$'
            - timestamp:
                source: time
                format: "RFC3339Nano"
            - static_labels:
                filtered: "true"

        - match: # victoria-metrics
            selector: '{job="victoria-metrics",task=~"victoria-metrics|vmagent"}'
            pipeline_name: "victoria-metrics"
            stages:
            - regex:
                expression: '^(?P<time>\S+)\s+(?P<level>\S+)\s+(?P<function>\S+)\s+.*'
            - timestamp:
                source: time
                format: "RFC3339Nano"
            - static_labels:
                filtered: "true"

        - match: # postgres
            selector: '{job="postgres",task="patroni"}'
            pipeline_name: "postgres"
            stages:
            - multiline:
                firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'
            - regex:
                expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\,\d{3}).*'
            - timestamp:
                source: time
                format: "2006-01-02 15:04:05,999"
            - drop:
                expression: ".*INFO: no action.*"
                drop_counter_reason: "noise-filter"
            - static_labels:
                filtered: "true"

        - match: # postgres-exporter
            selector: '{task="postgres-exporter"}'
            pipeline_name: "postgres-exporter"
            stages:
            - regex:
                expression: '^ts=(?P<time>\S+) .*'
            - timestamp:
                source: time
                format: "RFC3339Nano"
            - static_labels:
                filtered: "true"

        - match: # mariadb
            selector: '{job="mariadb",task="mariadb"}'
            pipeline_name: "mariadb"
            stages:
            - multiline:
                firstline: '^\d{4}-\d{2}-\d{2}  \d{2}:\d{2}:\d{2}'
            - regex:
                expression: '^(?P<time>\d{4}-\d{2}-\d{2}  \d{2}:\d{2}:\d{2}).*'
            - timestamp:
                source: time
                format: "2006-01-02  15:04:05"
            - drop:
                source: "__meta_docker_container_log_stream"
                value: "stdout"
                drop_counter_reason: "noise-filter"
            - static_labels:
                filtered: "true"

        - match: # maxscale
            selector: '{job="mariadb",task="maxscale"}'
            pipeline_name: "maxscale"
            stages:
            - multiline:
                firstline: '^\d{4}-\d{2}-\d{2}  \d{2}:\d{2}:\d{2}'
            - regex:
                expression: '^(?P<time>\d{4}-\d{2}-\d{2}  \d{2}:\d{2}:\d{2}).*'
            - timestamp:
                source: time
                format: "2006-01-02 15:04:05"
            - drop:
                source: "__meta_docker_container_log_stream"
                value: "stderr"
                drop_counter_reason: "noise-filter"
            - static_labels:
                filtered: "true"

        - match: # nats
            selector: '{job="nats",task="nats"}'
            pipeline_name: "nats"
            stages:
            - regex:
                expression: '.*(?P<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}\.\d{6}) .*'
            - timestamp:
                source: time
                format: "2006/01/02 15:04:05.999999"
            - static_labels:
                filtered: "true"

        - match: # minio
            selector: '{job="minio",task="minio"}'
            pipeline_name: "minio"
            stages:
            - multiline:
                firstline: '^\\S+'
            - static_labels:
                filtered: "true"

        - match: # seaweedfs
            selector: '{job="seaweedfs"}'
            pipeline_name: "seaweedfs"
            stages:
            - static_labels:
                filtered: "true"

        - match: # seaweedfs-csi
            selector: '{job="seaweedfs-csi"}'
            pipeline_name: "seaweedfs-csi"
            stages:
            - static_labels:
                filtered: "true"

        - match: # redis
            selector: '{task="redis"}'
            pipeline_name: "redis"
            stages:
            - regex:
                expression: '^.* (?P<time>\d{2} \w{3} \d{4} \d{2}:\d{2}:\d{2}\.\d{3}).*'
            - timestamp:
                source: time
                format: "02 Jan 2006 15:04:05.999"
            - static_labels:
                filtered: "true"

        - match: # resec
            selector: '{task="resec"}'
            pipeline_name: "resec"
            stages:
            - regex:
                expression: '^time="(?P<time>.*)" level=(?P<level>.*) .*'
            - timestamp:
                source: time
                format: "RFC3339"
            - static_labels:
                filtered: "true"

        - match: # wildduck
            selector: '{job="mail",task="wildduck"}'
            pipeline_name: "mail"
            stages:
            - static_labels:
                filtered: "true"

        - match: # zone-mta
            selector: '{job="mail",task="zone-mta"}'
            pipeline_name: "mail"
            stages:
            - static_labels:
                filtered: "true"

        - match: # haraka
            selector: '{job="mail",task="haraka"}'
            pipeline_name: "mail"
            stages:
            - drop:
                source: "__meta_docker_container_log_stream"
                value: "stderr"
                drop_counter_reason: "noise-filter"
            - multiline:
                firstline: '^\S+'
            - regex:
                expression: '^(?P<time>\S+) .*'
            - timestamp:
                source: time
                format: "RFC3339Nano"
            - static_labels:
                filtered: "true"

        - match: # sftpgo
            selector: '{job="sftpgo"}'
            pipeline_name: "sftpgo"
            stages:
            - json:
                expressions:
                  time:
                  user_agent:
            - drop:
                source: "user_agent"
                value: "Consul Health Check"
                drop_counter_reason: "noise-filter"
            - timestamp:
                source: time
                format: "2006-01-02T15:04:05.999"
            - static_labels:
                filtered: "true"

        - match: # filestash
            selector: '{job="filestash"}'
            pipeline_name: "filestash"
            stages:
            - regex:
                expression: '^(?P<time>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) .*'
            - timestamp:
                source: time
                format: "2006/01/02 15:04:05"
            - static_labels:
                filtered: "true"

        - match: # transmission
            selector: '{job="transmission",task="transmission"}'
            pipeline_name: "transmission"
            stages:
            - drop:
                source: "__meta_docker_container_log_stream"
                value: "stdout"
                drop_counter_reason: "noise-filter"
            - static_labels:
                filtered: "true"

        - match: # home-assistant
            selector: '{job="home-assistant"}'
            pipeline_name: "home-assistant"
            stages:
            - drop:
                source: "__meta_docker_container_log_stream"
                value: "stdout"
                drop_counter_reason: "noise-filter"
            - regex:
                expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) .*'
            - timestamp:
                source: time
                format: "2006-01-02 15:04:05"
            - static_labels:
                filtered: "true"

        - match: # jellyfin
            selector: '{job="jellyfin"}'
            pipeline_name: "jellyfin"
            stages:
            - drop:
                source: "__meta_docker_container_log_stream"
                value: "stderr"
                drop_counter_reason: "noise-filter"
            - regex:
                expression: '^[(?P<time>\S+] .*'
            - timestamp:
                source: time
                format: "15:04:05"
            - static_labels:
                filtered: "true"

        - match: # audiobookshelf
            selector: '{job="audiobookshelf"}'
            pipeline_name: "audiobookshelf"
            stages:
            - regex:
                expression: '^[(?P<time>\S+].*'
            - timestamp:
                source: time
                format: "RFC3339Nano"
            - static_labels:
                filtered: "true"

        - match: # drop
            selector: '{filtered!="true"}'
            action: drop
            drop_counter_reason: "nomad-filter"

        - labeldrop:
            - "filtered"
```

**Comment by jeschkies** [comment]
:wave: I'm not sure if the network labels have any influence here since you don't seem to filter on them.

Did you try in a different networking mode?

**Comment by nahsi** [comment]
@jeschkies other networking mode is native docker one - it works just fine.
I hope I will have time to debug this issue a little bit more soon. So I will be back with more details.

Although I feel that Nomad needs its own discovery config.

**Comment by jeschkies** [comment]
> Although I feel that Nomad needs its own discovery config.

I tend to agree. However, as Promtail inherits Prometheus' service discovery I believe it should be [Consul SD](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#consul_sd_config).

Could you turn on the debug logs for promtail? Maybe there is some information there. You should see some of the debug logs from the Docker [target_group](https://github.com/grafana/loki/blob/main/clients/pkg/promtail/targets/docker/target_group.go#L36).

**Comment by pikeas** [comment]
I'm experiencing the same issue.

Promtail config:

```
scrape_configs:
    - job_name: docker
      docker_sd_configs:
          - host: unix:///var/run/docker.sock
```

Promtail logs with `log_level: debug`:

```
level=debug ts=<time> caller=target.go:203 target=docker/<id> msg="starting process loop" container=<id>
```
Promtail picks up 10 containers, all of which are Nomad init containers with `NetworkMode: none`. All my actual services are set to bridge mode, and Promtail doesn't see them.

Could this be related? https://grafana.com/docs/loki/latest/clients/promtail/configuration/#docker_sd_config

```
# The port to scrape metrics from, when `role` is nodes, and for discovered
# tasks and services that don't have published ports.
[ port: <int> | default = 80 ]
```
