### ISSUE TITLE
level=error caller=main.go:46 msg="error loading config" filename=/etc/loki/loki.yaml err="yaml: unmarshal errors:\n  line 8: field store not found in type ring.Config\n  line 12: field max_look_back_period not found in type querier.Config"

### ISSUE THREAD

**Issue by GuitaristForEver** [grafana/loki#619]
Hi there, 
I have Loki setup on K8S 
been using the Loki for a few days, now (suddenly) I get the above error ..

this is **some** output of _helm get Loki_ command :

```
REVISION: 1
RELEASED: Sun May 19 17:15:35 2019
CHART: loki-stack-0.9.1
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
loki:
  affinity: {}
  annotations: {}
  config:
    auth_enabled: false
    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 15m
      lifecycler:
        ring:
          replication_factor: 1
          store: inmemory
    limits_config:
      enforce_metric_name: false
    querier:
      max_look_back_period: 0   #the value is here!
    schema_config:
      configs:
      - from: "2018-04-15"
        index:
          period: 168h
```

**Comment by sh0rez** [comment]
The error message is correct, as the configuration key does not exist (anymore). It has been removed in #610

**Comment by sh0rez** [comment]
According to https://github.com/grafana/loki/commit/3d3c05717ad27dd0407c9bed3b016a144f1a0b70#diff-fdd086729867007e57c74aad7c391f90 it should be sufficient to update 
```yaml
loki:
  querier:
      max_look_back_period: 0   #the value is here!
```

to
```yaml
loki:
  chunk_store_config:
    max_look_back_period: 0
```
