### ISSUE TITLE
[promtail] -config.expand-env not working

### ISSUE THREAD

**Issue by alexanderruch** [grafana/loki#6218]
**Description**
-config.expand-env=true does not have the desired effect, system variables are not translated and are displayed blank.

**To Reproduce**
1. $ export TESTVAR=myTest
2. setup promtail with local-config.yaml
3. $ /usr/local/bin/promtail -config.expand-env=true -config.file /opt/promtail/local-config.yaml
3. 0.0.0.:9080/targets

**Expected behavior**
Labels showing test="" expected is test="myTest"

**Environment:**
- Promtail version 2.5.0 (branch: HEAD, revision: 2d9d0ee23) / binary (promtail-linux-amd64.zip)
- Ubuntu 20.04.4 LTS

**Promtail config section**
```
scrape_configs:
  - job_name: system
    pipeline_stages:
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs  # Works as expected
          test: ${TESTVAR} # does not work
          __path__: /var/log/*.log
```

**Varabiel output on terminal**
```
test@ubuntu01:~$ echo $TESTVAR
myTest
```

**Comment by heapdavid** [comment]
We saw the same thing with:

`/path/to/promtail -config.expand-env=true -config.file /etc/promtail.yml`

```
scrape_configs:
  - job_name: journal
    journal:
      labels:
        hostname: ${HOSTNAME}
```

The `hostname` label ends up blank

**Comment by mwolter805** [comment]
In case someone else runs into this issue, the systemd unit file had to be changed to the following to pass in a variable.
```
ExecStart=/bin/bash -c 'hostname=$HOSTNAME exec /usr/local/bin/promtail -config.expand-env=true -positions.file /var/lib/promtail/positions.yml -config.file /etc/loki/promtail.yaml'
```

**Comment by TheWiresharkGuy** [comment]
Any new on this?

**Comment by Pexers** [comment]
+1
In my case I'm using Docker Compose, and even when overwriting the entrypoint, the `-config.expand-env=true` flag does nothing.
```yml
promtail:
  image: grafana/promtail:2.9.2
  volumes:
    - ./config/promtail.yml:/etc/promtail/promtail.yml
  environment:
    - MY_ENV_VAR=${MY_ENV_VAR}
  entrypoint: >
    /bin/bash -c "
    MY_ENV_VAR=localhost /usr/bin/promtail -config.expand-env=true -config.file /etc/promtail/promtail.yml
    "
```
_/etc/promtail/promtail.yml_
```yml
scrape_configs:
  - job_name: logger
    static_configs:
      - targets:
        - ${MY_ENV_VAR}
```
