### ISSUE TITLE
duplicate log line in grafana 

### ISSUE THREAD

**Issue by sohel2020** [grafana/loki#6225]
I have set up Loki with 3 replicas as a monolithic architecture with a helm chart following is my configuration.

```yaml
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
compactor:
  compaction_interval: 10m
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  retention_enabled: true
  shared_store: s3
  working_directory: /data/retention
distributor:
  ring:
    kvstore:
      store: memberlist
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  max_transfer_retries: 0
  wal:
    dir: /data/loki/wal
limits_config:
  enforce_metric_name: false
  max_entries_limit_per_query: 20000
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 2160h
memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - loki-headless.logging.svc.cluster.local:7946
  max_join_backoff: 1m
  max_join_retries: 10
  min_join_backoff: 1s
ruler:
  alertmanager_url: http://prometheus-operator-alertmanager.monitoring.svc.cluster.local:9093
  enable_api: true
  ring:
    kvstore:
      store: memberlist
  rule_path: /tmp/scratch
  storage:
    local:
      directory: /rules/fake
    type: local
schema_config:
  configs:
  - from: "2020-05-15"
    index:
      period: 24h
      prefix: index_
    object_store: s3
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
storage_config:
  aws:
    s3: s3://eu-west-1/staging-bayes-loki
    s3forcepathstyle: true
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/index_cache
    cache_ttl: 24h
    shared_store: s3
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: true
```

In grafana UI a can see some duplicate log lines sometimes 2x, 3x. is there anything wrong with the configuration?
