### ISSUE TITLE
Loki queries getting failed - Bad Gateway when using Azure Storage Account Blob Object store

### ISSUE THREAD

**Issue by akshaya-msd** [grafana/loki#6246]
- Loki Mode: Loki simple scalable
- Object store: Azure blob container
- Running on Azure Kubernetes 
- Deployed using helm https://github.com/grafana/helm-charts/tree/main/charts/loki-simple-scalable

**The following are the helm values used to deploy the chart**
```
  loki:
    config: |
      auth_enabled: false
      server:
        http_listen_port: 3100
        grpc_listen_port: 9095

      memberlist:
        join_members:
          - {{ include "loki.fullname" . }}-memberlist

      ingester:
        chunk_idle_period: 10m
        chunk_block_size: 262144
        chunk_retain_period: 1m
        max_transfer_retries: 0

      querier:
        query_timeout: 30m
        engine:
          timeout: 30m
        
      chunk_store_config:
        max_look_back_period: 72h

      common:
        path_prefix: /var/loki
        replication_factor: 3
        storage:
          azure:
            account_key: <account_key>
            account_name: <account_name>
            container_name: loki-scalable
            request_timeout: 30m

      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_cache_freshness_per_query: 10m
        split_queries_by_interval: 15m
        ingestion_rate_mb: 100
        ingestion_burst_size_mb: 150

      {{- if .Values.loki.schemaConfig}}
      schema_config:
      {{- toYaml .Values.loki.schemaConfig | nindent 2}}
      {{- end}}

    schemaConfig:
      configs:
        - from: 2022-05-23
          store: boltdb-shipper
          object_store: azure
          schema: v11
          index:
            prefix: loki_index_
            period: 24h

    structuredConfig: {}

```

**Issue Faced:**
- Slow processing of the queries and timeouts when querying the data range > 12h, sometimes facing issues even for a smaller range 

**Steps carried out to solve the issue:**

- Increased Azure application gateway timeout 
- Increased Loki querier and engine timeout
```
   querier:
        query_timeout: 30m
        engine:
          timeout: 30m
```
- Increased Grafana data proxy timeout

![image](https://user-images.githubusercontent.com/89829425/170239397-3b2f0bb9-1818-4f18-9e8d-ae602933a5cf.png)

- Increased Storage account read timeout  (which doesn't work)

```
      storage:
          azure:
            request_timeout: 30m
```

**Grafana Error:**

![image](https://user-images.githubusercontent.com/89829425/170240950-4f3c1c1a-0f89-4f0f-94f2-3458743db8d0.png)

**Error message from Loki read pods**

> | 2022-05-25 15:16:53 | level=error ts=2022-05-25T09:46:53.685895447Z caller=batch.go:716 org_id=fake msg="error fetching chunks" err="Get \"https://<account_name>.blob.core.windows.net/loki-scalable/fake/66697832634bc8c-180f9fef733-180f9ffbd90-c08296e5?timeout=61\": context canceled"

**Expected behavior**
- Should be able to query max of a week data without timeouts
