### ISSUE TITLE
please update promtail/docker-config.yaml for deprecated config

### ISSUE THREAD

**Issue by rdxmb** [grafana/loki#630]
config by

```
docker run --entrypoint cat grafana/promtail /etc/promtail/docker-config.yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
- job_name: system
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
```

results in

`level=warn ts=2019-05-28T12:57:57.318450922Z caller=filetargetmanager.go:94 msg="WARNING!!! entry_parser config is deprecated, please change to pipeline_stages"`

**Comment by slim-bean** [comment]
Thanks for mentioning this one, we are waiting for #576 to make sure we have the config ironed out before we make updates to all the various configs, here is the list I can think of places we need to update:
[ ] Helm charts
[ ] Ksonnet 
[ ] docker-config.yaml
[ ] promtail-local-config.yaml
[ ] promtail_test.go
[ ] scrape-config.sh
[ ] promtail.sh
[ ] promtail-examples.md
[ ] labels.md (maybe, this is a design doc and was built around the design at the time)

**Comment by slim-bean** [comment]
Closing, all important references to entry_parser were updated with the exception of the promtail integration test and the logs from labels design doc, will address those in a separate issue

**Comment by zen** [comment]
Looks like I'm getting the same error again:
`"WARNING!!! entry_parser config is deprecated, please change to pipeline_stages`

My config
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      -localhost
    labels:
      agent: promtail
      job: varlogs
      customer: internal
      component: core
      env: production
      __path__: /var/log/*log
```

Looks like some artefact from default options?
