### ISSUE TITLE
Loki + MinIO - MissingEndpoint

### ISSUE THREAD

**Issue by kfirfer** [grafana/loki#6311]
**Getting those logs from loki instance:**
```
level=error ts=2022-06-04T09:48:23.14423074Z caller=scheduler_processor.go:188 org_id=fake msg="error notifying frontend about finished query" err="rpc error: code = Canceled desc = context canceled" frontend=172.16.206.231:9095
level=error ts=2022-06-04T09:48:23.144255626Z caller=scheduler_processor.go:143 org_id=fake msg="error notifying scheduler about finished query" err=EOF addr=172.16.206.231:9095
level=error ts=2022-06-04T09:48:23.143638745Z caller=table.go:304 table-name=index_19147 msg="failed to init user index set fake" err="MissingEndpoint: 'Endpoint' configuration is required for this service"
level=error ts=2022-06-04T09:48:23.658769643Z caller=cached_client.go:64 msg="failed to build cache" err="MissingEndpoint: 'Endpoint' configuration is required for this service"
```

**Setup:**
Loki helm chart version 2.11.1
Grafana helm chart 6.29.5
MinIO

**Config:**
```


config:
  auth_enabled: false
  ingester:
    chunk_idle_period: 3m
    chunk_block_size: 262144
    chunk_retain_period: 1m
    max_transfer_retries: 0
    wal:
      dir: /data/loki/wal
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_entries_limit_per_query: 5000
  schema_config:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h
  server:
    http_listen_port: 3100
  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      shared_store: s3
    aws:
      s3forcepathstyle: true
      s3: s3://kfir:123123123@minio:9000/loki
  chunk_store_config:
    max_look_back_period: 0s
  table_manager:
    retention_deletes_enabled: false
    retention_period: 0s
  compactor:
    working_directory: /data/loki/boltdb-shipper-compactor
    shared_store: s3
    compaction_interval: 5m
```

**Comment by kfirfer** [comment]
I made it works with this config:

```
config:
  auth_enabled: false
  ingester:
    chunk_idle_period: 3m
    chunk_block_size: 262144
    chunk_retain_period: 1m
    max_transfer_retries: 0
    wal:
      dir: /data/loki/wal
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_entries_limit_per_query: 5000
  schema_config:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h
  server:
    http_listen_port: 3100
  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      shared_store: s3
    aws:
      access_key_id: accesskey
      secret_access_key: secretkey
      insecure: true
      endpoint: minio:9000
      s3forcepathstyle: true
      s3: s3://accesskey:secretkey@minio:9000/loki
  chunk_store_config:
    max_look_back_period: 0s
  table_manager:
    retention_deletes_enabled: false
    retention_period: 0s
  compactor:
    working_directory: /data/loki/boltdb-shipper-compactor
    shared_store: s3
    compaction_interval: 5m
```
