### ISSUE TITLE
Add hostname as default labels for promtail

### ISSUE THREAD

**Issue by mizeng** [grafana/loki#634]
**Is your feature request related to a problem? Please describe.**
I was trying to use promtail to collect application logs from some hosts. I find filename is one default labels which is useful, however it's still hard to distinguish from hosts.

One solution is to add this label in promtail config as below. However it's not efficient for adding different hostname for tons of hosts. So I was thinking if we could add hostname as one default label like filename since it's really a common need. Or at least we can have one switch config to have this, which will be more efficient for this use cases (non-kubenates use case)
```
scrape_configs:
- job_name: system
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
     hostname: host1
      __path__: /var/log/*log
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
