### ISSUE TITLE
`--client.external-labels=hostname=host1` does not work

### ISSUE THREAD

**Issue by mizeng** [grafana/loki#636]
**Describe the bug**
looks like ClientConfig and ClientConfigs are mis-used for promtail Config. The Command line configs including ExternalLabels are in ClientConfig, however Promtail only used ClientConfigs.

This will cause something like `./promtail --config.file=./docker-config.yaml --client.external-labels=hostname=host1` does not work. The external-labels is missing.

**To Reproduce**
1. Started loki (SHA or version)
2. Started promtail (SHA or version) to tail `./promtail --config.file=./docker-config.yaml --client.external-labels=hostname=host1`
3. Then the label "hostname=host1" is not showing up in Loki.

**Expected behavior**
The label "hostname=host1" should show up in Loki.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by daixiang0** [comment]
The external-labels is from prometheus, refer to [doc](https://prometheus.io/docs/prometheus/latest/getting_started/#configuring-prometheus-to-monitor-itself), do not use it before, but seems you misunderstand it.
If you want to add labels, should config scrape_config, refer to [promtail doc](https://github.com/grafana/loki/blob/master/docs/promtail-examples.md)

**Comment by mizeng** [comment]
@daixiang0  someone just suggest me to use exiternal-labels in https://github.com/grafana/loki/issues/634. So what should I use for that use case?

**Comment by daixiang0** [comment]
Just give a quick ask:
```
scrape_configs:
- job_name: system
  entry_parser: raw 
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
      hostname: host1
```

Do not think a good way to show different hostname in local mode, but in k8s, you can use `__meta_kubernetes_node_name` refer to [doc](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#node), so that you can add below scrape config:
```
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: hostname
```

**Comment by mizeng** [comment]
@daixiang0 This requirements is mainly from non k8s env. Say, if I need to install promtail in lots of VMs, and I need to have their hostname as one of the labels or default labels. I checked the code, it's already in s.hostname (https://github.com/grafana/loki/blob/master/pkg/promtail/targets/filetargetmanager.go#L213). So I want to add it into labels.
However someone suggest me to use external_labels, which I found it's not working at all.

**Comment by daixiang0** [comment]
```
scrape_configs:
- job_name: system
  entry_parser: raw 
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
      hostname: host1
```
This config can work for local mode, please note that since you run at local, for each vm you need to run a promtail, so you can not use one config at all. It is a workaround,  need to dig to find the issue about external_labels.

**Comment by mizeng** [comment]
I know this can work, but not efficient for deploy for different hostname for different vms. need something like `hostname:${HOSTNAME}`

**Comment by Kuqd** [comment]
@mizeng it will work if you use the single client config.

Either by providing a `client:` in the config or via command line. If you only use the `clients:` it won't work.

**Comment by mizeng** [comment]
@Kuqd  could you share one example with both command line start up and the promtail config?

**Comment by daixiang0** [comment]
@mizeng the clients config is as below:
```
clients:
  - url: url/to/a
    foo: a
  - url: url/to/b
    foo: b
```
you can set in config, that works for me.

We can't parse common flag via command line if specify configfile at same time.

**Comment by mizeng** [comment]
@daixiang0 then how can I fulfill the requirement? paas variable to label?

**Comment by mizeng** [comment]
never mind. Finally I figure it out. 
Remove "Clients" in the promtail config, and use below comand to start promtail:

```./promtail --client.url=http://loki.loki.svc.33.tess.io:3100/api/prom/push --client.external-labels=hostname=${hostname} --config.file=./docker-config.yaml```

**Comment by minhdanh** [comment]
>`__host__` is you want, right?

@daixiang0 I need to query the logs by the hostname (with something like `{hostname="gke-pool-1-xxxx"}`, but `__host__` is an internal label that is not usable in Loki. So how can that be done? Do I need another relabel_config for that?

**Comment by daixiang0** [comment]
just need add --client.external-labels=hostname=${hostname} then do query.

**Comment by sebek72** [comment]
> @minhdanh just need add --client.external-labels=hostname=${hostname} then do query. If still question, better to open a new issue to track it.

Does not work in 1.5.0 (hostname or HOSTNAME are empty).

**Comment by GJaminon** [comment]
This worked for me with v1.5: 
`- name: "Create the PromTail DeamonSet"
  k8s:
    host: "{{ k8s_url }}"
    kubeconfig: "{{ kubeconfig_file }}"
    wait: true
    definition: 
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: promtail
        namespace: monitoring 
      spec:
        selector:
          matchLabels:
            name: promtail
        template:
          metadata:
            labels:
              name: promtail
          spec:
            serviceAccount: promtail-serviceaccount 
            serviceAccountName: promtail-serviceaccount
            volumes:
            - name: logs
              hostPath:
                path: /var/log
            - name: promtail-config
              configMap: 
                name: "{{ config_map_result.result.metadata.name }}"
            containers:
            - name: promtail-container
              image: grafana/promtail:1.5.0
              args:
                - -config.file=/etc/promtail/promtail.yaml
                - -client.url=http://loki:3100/loki/api/v1/push
                - -client.external-labels=hostname=$(NODE_NAME)
              env:
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
              volumeMounts:
              - name: logs
                mountPath: /var/log 
              - name: promtail-config
                mountPath: /etc/promtail
`

Config: 

`- set_fact:
    promtail_config: |
          server:
            http_listen_port: 9080
            grpc_listen_port: 0
          positions:
            filename: /tmp/positions.yaml
          scrape_configs:
           - job_name: system
             entry_parser: raw
             static_configs:
             - targets:
                - localhost
               labels:
                job: varlogs
                __path__: /var/log/*.log
`

**Comment by isavcic** [comment]
Note: if not running under Kubernetes, the hostname should be specified as:

```bash
./promtail --client.external-labels=hostname=$(hostname) ...
```

Notice the braces: regular, not curly.

**Comment by flenoir** [comment]
Hi, i'm also trying to use client.external-label throught Terraform but could not manage to make it work. Regarding vales.yaml, i try like below

```
resource "helm_release" "promtail" {
  depends_on = [kubernetes_secret.azure_storage, azurerm_kubernetes_cluster.eolementhe]
  name       = "promtail"
  chart      = "promtail"
  repository = "https://grafana.github.io/helm-charts"
  namespace  = "default"

  values = [<<EOF
  args: [ "-client.url=http://videomenthe.pro.dns-orange.fr:3100/loki/api/v1/push" ]
  EOF
  ]

  set {
    name  = "loki.serviceName"
    value = "loki"
  }

}
```

Not sure if it should be something like 

```
  values = [<<EOF
  extraCommandlineArgs: [ " -client.external-labels=hostname=$(videomenthe.pro.dns-orange.fr) ]
  EOF
  ]
```

What would be best option here ?

**Comment by asymmetric** [comment]
I found it much easier to take advantage of systemd's [trusted journal fields](https://systemd.network/systemd.journal-fields.html#Trusted%20Journal%20Fields), among which is `_HOSTNAME`:

```yaml
scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ["__journal__systemd_unit"]
        target_label: "unit"
      - source_labels: ["__journal__hostname"]
        target_label: "hostname"
```
