### ISSUE TITLE
failed to create memberlist

### ISSUE THREAD

**Issue by caibirdme** [grafana/loki#6370]
**Describe the bug**
cannot run on k8s in microservice-mode, due to memberlist error

**To Reproduce**
1. use helm chart: [loki-distributed(v0.48.4)]https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed
2. custom-values.yaml below:
```yaml
serviceMonitor:
  enabled: true
gateway:
  enabled: false
loki:
  config: ""
  structuredConfig:
    auth_enabled: false
    analytics:
      reporting_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      grpc_server_max_recv_msg_size: 104857600 # 100MB
      grpc_server_max_send_msg_size: 104857600 # 100MB
      grpc_server_max_concurrent_streams: 100000
      grpc_server_keepalive_time: 30s
      grpc_server_keepalive_timeout: 20s      
      http_server_read_timeout: 5m
      http_server_write_timeout: 5m
    querier:
      query_timeout: 3m
      max_concurrent: 100
      query_ingesters_within: 2h
      engine:
        timeout: 5m
    frontend_worker:
      frontend_address: loki-distributed-query-frontend:9095
      parallelism: 100
      dns_lookup_duration: 10s
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    query_range:
      align_queries_with_step: true
      parallelise_shardable_queries: true
      cache_results: true
      results_cache:
        cache:
          redis:
            endpoint: redis-headless.redis:6379
            password: loki-redis-pwd
            timeout: 2s
            expiration: 1h
            pool_size: 10
            idle_timeout: 10m
            max_connection_age: 30m
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      concurrent_flushes: 64
      chunk_block_size: 262144 # 256KB
      chunk_target_size: 1572864 # 1.5M
      chunk_encoding: lz4
      max_chunk_age: 2h
    schema_config:
      configs:
      - from: 2022-06-10
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: loki_index_
          period: 24h
        chunks:
          prefix: loki_chunk_
          period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/data/boltdb-shipper-active
        cache_location: /var/loki/data/boltdb-shipper-cache
        shared_store: s3
        index_gateway_client:
          server_address: loki-distributed-index-gateway:9095
          grpc_client_config:
            max_recv_msg_size: 104857600
            max_send_msg_size: 104857600
      index_queries_cache_config: 
        redis:
            endpoint: redis-headless.redis:6379
            password: loki-redis-pwd
            db: 1
            timeout: 3s
            expiration: 1h
            pool_size: 10
            idle_timeout: 10m
            max_connection_age: 30m        
    chunk_store_config:
      chunk_cache_config:
        redis:
            endpoint: redis-headless.redis:6379
            password: loki-redis-pwd
            db: 2
            timeout: 3s
            expiration: 1h
            pool_size: 10
            idle_timeout: 10m
            max_connection_age: 30m   
    common:
      storage:
        s3:
          s3: s3://xxx
          s3forcepathstyle: true
      ring:
        kvstore:
          store: memberlist
    memberlist:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      join_members:
      - loki-distributed-memberlist:7946
    compactor:
      working_directory: /var/loki/data/boltdb-shipper-compactor
      shared_store: s3
      shared_store_key_prefix: index/
      compaction_interval: 10m
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
    limits_config:
      ingestion_rate_strategy: local
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 400
      ingestion_burst_size_mb: 600
      max_global_streams_per_user: 0
      max_query_length: 72h
      max_query_parallelism: 64
      cardinality_limit: 200000
      split_queries_by_interval: 30m

ingester:
  replicas: 3
  reources:
    requests:
      cpu: 1
      memory: "2Gi"
  persistence:
    enabled: true
    size: "20Gi"
    storageClass: cbs
distributor:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 75
  reources:
    requests:
      cpu: 1
      memory: "2Gi"
querier:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 75
  reources:
    requests:
      cpu: 4
      memory: "3Gi"
queryFrontend:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 75
  reources:
    requests:
      cpu: 2
      memory: "2Gi"
tableManager:
  enabled: true
  resources:
    limits:
      cpu: 1
      memory: "512Mi"
compactor:
  enabled: true
  resources:
    limits:
      cpu: 2
      memory: "2Gi"
  persistence:
    enabled: true
    storageClass: cbs
indexGateway:
  enabled: true
  replicas: 2
  resources:
    requests:
      cpu: 2
      memory: "2Gi"
  persistence:
    enabled: true
    size: "20Gi"
    storageClass: cbs
```

**Expected behavior**
Run successfully!
When I change to use ETCD, everything is fine

**Environment:**
 - Infrastructure: k8s
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
error log:
```
level=info ts=2022-06-11T08:11:00.750617757Z caller=main.go:106 msg="Starting Loki" version="(version=2.5.0, branch=HEAD, revision=2d9d0ee23)"
level=info ts=2022-06-11T08:11:00.750858126Z caller=server.go:260 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2022-06-11T08:11:00.751517906Z caller=memberlist_client.go:394 msg="Using memberlist cluster node name" name=loki-distributed-distributor-77ffd77df6-fkkpk-749ae714
level=info ts=2022-06-11T08:11:00.753810743Z caller=module_service.go:64 msg=initialising module=memberlist-kv
level=info ts=2022-06-11T08:11:00.753817843Z caller=module_service.go:64 msg=initialising module=server
level=error ts=2022-06-11T08:11:00.753914179Z caller=loki.go:384 msg="module failed" module=memberlist-kv error="invalid service state: Failed, expected: Running, failure: service &{0xc0002e94a0 { true 10000000000 4 30000000000 200000000 3 30000000000 0 true 7946 [loki-distributed-m
emberlist:7946] 1000000000 60000000000 10 false 0 300000000000 5000000000 0 {[] 7946 5000000000 5000000000 false 0xc00013ea00 false { false}} 0xc00013ea00 [{ringDesc 0x1145460} {}]} 0xc0007b9ae0 0xc00013ea00 0xc000841810 {{} [0 1 0]} {0 0} map[] map[ringDesc:{ringDes
c 0x1145460} usagestats.jsonCodec:{}] {0 0} map[] map[] {0 0} [] 0 [] 0 0 0xc000114e40 0xc0002810e0 0xc0002811a0 0xc000281260 0xc0002815c0 0xc000281380 0xc000281680 0xc0002814a0 0xc000b54400 0xc000b54440 0xc000281800 0xc0002818c0 0xc000281a40 0xc000281980 0xc000135a28 0xc000841ea0 0x
c000135a18 0xc000135a20 0xc000b54480 0xc000b544c0 10} failed: failed to create memberlist: Failed to get final advertise address: no private IP address found, and explicit IP not provided"
level=error ts=2022-06-11T08:11:00.753953841Z caller=loki.go:384 msg="module failed" module=distributor error="failed to start distributor, because it depends on module memberlist-kv, which has failed: invalid service state: Failed, expected: Running, failure: invalid service state:
Failed, expected: Running, failure: service &{0xc0002e94a0 { true 10000000000 4 30000000000 200000000 3 30000000000 0 true 7946 [loki-distributed-memberlist:7946] 1000000000 60000000000 10 false 0 300000000000 5000000000 0 {[] 7946 5000000000 5000000000 false 0xc00013ea00 false {
false}} 0xc00013ea00 [{ringDesc 0x1145460} {}]} 0xc0007b9ae0 0xc00013ea00 0xc000841810 {{} [0 1 0]} {0 0} map[] map[ringDesc:{ringDesc 0x1145460} usagestats.jsonCodec:{}] {0 0} map[] map[] {0 0} [] 0 [] 0 0 0xc000114e40 0xc0002810e0 0xc0002811a0 0xc000281260 0xc0002815
c0 0xc000281380 0xc000281680 0xc0002814a0 0xc000b54400 0xc000b54440 0xc000281800 0xc0002818c0 0xc000281a40 0xc000281980 0xc000135a28 0xc000841ea0 0xc000135a18 0xc000135a20 0xc000b54480 0xc000b544c0 10} failed: failed to create memberlist: Failed to get final advertise address: no pri
vate IP address found, and explicit IP not provided"
level=error ts=2022-06-11T08:11:00.753982627Z caller=loki.go:384 msg="module failed" module=ring error="failed to start ring, because it depends on module memberlist-kv, which has failed: invalid service state: Failed, expected: Running, failure: invalid service state: Failed, expect
ed: Running, failure: service &{0xc0002e94a0 { true 10000000000 4 30000000000 200000000 3 30000000000 0 true 7946 [loki-distributed-memberlist:7946] 1000000000 60000000000 10 false 0 300000000000 5000000000 0 {[] 7946 5000000000 5000000000 false 0xc00013ea00 false { false}} 0xc0
0013ea00 [{ringDesc 0x1145460} {}]} 0xc0007b9ae0 0xc00013ea00 0xc000841810 {{} [0 1 0]} {0 0} map[] map[ringDesc:{ringDesc 0x1145460} usagestats.jsonCodec:{}] {0 0} map[] map[] {0 0} [] 0 [] 0 0 0xc000114e40 0xc0002810e0 0xc0002811a0 0xc000281260 0xc0002815c0 0xc00028138
0 0xc000281680 0xc0002814a0 0xc000b54400 0xc000b54440 0xc000281800 0xc0002818c0 0xc000281a40 0xc000281980 0xc000135a28 0xc000841ea0 0xc000135a18 0xc000135a20 0xc000b54480 0xc000b544c0 10} failed: failed to create memberlist: Failed to get final advertise address: no private IP addres
s found, and explicit IP not provided"
level=info ts=2022-06-11T08:11:00.757108607Z caller=modules.go:877 msg="server stopped"
level=info ts=2022-06-11T08:11:00.757133789Z caller=module_service.go:96 msg="module stopped" module=server
level=info ts=2022-06-11T08:11:00.757145189Z caller=loki.go:373 msg="Loki stopped"
level=error ts=2022-06-11T08:11:00.757190193Z caller=log.go:100 msg="error running loki" err="failed services\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:419\nmain.main\n\t/src/loki/cmd/loki/main.go:108\nruntime.main\n\t/usr/local/go/src/runtime/proc.g
o:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
```

**Comment by caibirdme** [comment]
> y

I updated the config, add the instance_interface_names and still cannot start the server
```yaml
loki:
  config: ""
  structuredConfig:
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
    common:
      storage:
        s3:
          s3: s3://xxx
          s3forcepathstyle: true
      ring:
        kvstore:
          store: memberlist
        instance_interface_names:
        - eth0
    memberlist:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      join_members:
      - loki-distributed-memberlist:7946
```
And here's the error:
```
level=info ts=2022-06-14T02:10:36.752547554Z caller=memberlist_client.go:394 msg="Using memberlist cluster node name" name=loki-distributed-distributor-686ccb996c-bth6t-792c10dc
ts=2022-06-14T02:10:36.752682114Z caller=memberlist_logger.go:74 level=debug msg="configured Transport is not a NodeAwareTransport and some features may not work as desired"
level=debug ts=2022-06-14T02:10:36.75372307Z caller=module_service.go:54 msg="module waiting for initialization" module=distributor waiting_for=memberlist-kv
level=info ts=2022-06-14T02:10:36.753726613Z caller=module_service.go:64 msg=initialising module=memberlist-kv
level=debug ts=2022-06-14T02:10:36.75379514Z caller=module_service.go:54 msg="module waiting for initialization" module=ring waiting_for=server
level=error ts=2022-06-14T02:10:36.753861595Z caller=loki.go:384 msg="module failed" module=memberlist-kv error="invalid service state: Failed, expected: Running, failure: service &{0xc000a03c20 { true 10000000000 4 30000000000 200000000 3 30000000000 0 true 7946 [loki-distributed-m
emberlist:7946] 1000000000 60000000000 10 false 0 300000000000 5000000000 0 {[] 7946 5000000000 5000000000 false 0xc0000b6a50 false { false}} 0xc0000b6a50 [{ringDesc 0x1145460} {}]} 0xc0006ae370 0xc0000b6a50 0xc000204fc0 {{} [0 1 0]} {0 0} map[] map[ringDesc:{ringDes
c 0x1145460} usagestats.jsonCodec:{}] {0 0} map[] map[] {0 0} [] 0 [] 0 0 0xc000265f80 0xc000795a40 0xc000795b00 0xc000795bc0 0xc000795e00 0xc000795c80 0xc000795ec0 0xc000795d40 0xc00091ea40 0xc00091ea80 0xc000a045a0 0xc000a04660 0xc000a047e0 0xc000a04720 0xc00000f7a8 0xc000208150 0x
c00000f798 0xc00000f7a0 0xc00091eac0 0xc00091eb00 10} failed: failed to create memberlist: Failed to get final advertise address: no private IP address found, and explicit IP not provided"
```

And another question is, if I configured common.ring, do I need to config ingester.lifecycler.ring, distributor.ring, compactor.compactor_ring？

**Comment by DylanGuedes** [comment]
I think the problem is that `eth0` doesn't have a valid private IP address. Do you mind checking other net interfaces available to your pods? `eth0` probably only has the `0.0.0.0` IP which shouldn't be valid since it can't be advertised to other peers/accessed by other pods.

> And another question is, if I configured common.ring, do I need to config ingester.lifecycler.ring, distributor.ring, compactor.compactor_ring？

Nope, configuring only the `common.ring` is enough (it is copied to all rings unless you explicitly configure them).

**Comment by sakirma** [comment]
At the moment I trying to make distributed to work as well. I quickly passed this error by updating the `structuredConfig` value.

```
loki:
  structuredConfig:
    ingester:
      # Disable chunk transfer which is not possible with statefulsets
      # and unnecessary for boltdb-shipper
      max_transfer_retries: 0
      chunk_idle_period: 1h
      chunk_target_size: 1536000
      max_chunk_age: 1h
    storage_config:
      boltdb_shipper:
        shared_store: azure
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h
    schema_config:
      configs:
        - from: 2020-09-07
          store: boltdb-shipper
          object_store: azure
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
```
irrelevant part: 
My current problem is that, on Grafana changing the source to `loki-dis-loki-distributed-query-frontend` won't show me the logs of my applications.

**Comment by DylanGuedes** [comment]
Sorry @sakirma, do you mind asking your questions at Slack, Forum, etc? We're limiting GH issues to reporting Loki problems only.

Anyway, for your case, you should put as the datasource the Gateway service, not the query-frontend.

**Comment by chrizel** [comment]
> "failed: failed to create memberlist: Failed to get final advertise address: no private IP address found, and explicit IP not provided"

Follow-up to this problem. We had the same error in our small Loki setup inside of our EKS cluster using the official [Loki Helm chart](https://github.com/grafana/helm-charts/tree/main/charts/loki).

`instance_interface_names` didn't fix the problem, but after some time I found a similar error in this community discussion about Grafana Tempo: https://community.grafana.com/t/gossip-ring-memberlist-no-private-ip-address-found/52209/8

I've adapted this fix to the Loki Helm chart configuration like so:

```yaml
env:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP

extraArgs:
  config.expand-env: true

config:
  memberlist:
    bind_addr:
      - ${MY_POD_IP}
```

This fixed the problem on our side.

**Comment by DylanGuedes** [comment]
Thanks for the help Christian. I'm now closing it (looks like I forgot to do it before :smile: )

**Comment by Dunge** [comment]
This bug should probably be fixed at the root and not just closed with a workaround solution..
I have the same issue installing loki on a microk8s cluster using calico as the network stack.

**Comment by DylanGuedes** [comment]
> This bug should probably be fixed at the root and not just closed with a workaround solution.. I have the same issue installing loki on a microk8s cluster using calico as the network stack.

Sorry to hear that it isn't working for you.
I closed the issue because the issue author didn't return so I assumed my suggestion worked and this looks more like an specific environment issue than a Loki bug. That said, if you believe it is a bug, please create an issue and we'll do our best to work on it.

**Comment by Dunge** [comment]
@m1ll3nn1umf4lc0n I managed to get it running by downloading the chart locally and modifying it with @chrizel suggestion above.

Of course, as I mentioned in #8634 this is not perfect because it prevents us from using the chart online and fall back on a local copy that won't get updates. I believe this is still a bug that should be fixed in the codebase to work with different networking stacks.

**Comment by seanmorton** [comment]
@Dunge see #9078 it should allow you to use this workaround without having to make your own copy of the chart.

**Comment by FedeMarchiniHotovo** [comment]
@seanmorton Thanks, that workaround solved this issue

**Comment by bensoille** [comment]
My 5cts, maybe

Seems to be missing role arn in `serviceAccount.annotations."eks.amazonaws.com/role-arn/role-arn`  section, as you are using S3 for shared object storage

**Comment by cgustav** [comment]
This is how i implemented the proposed solution by @chrizel on simple scalable mode.

```yaml
loki:
  extraMemberlistConfig:
    bind_addr:
      - ${MY_POD_IP}

backend:
  replicas: 1

  extraArgs:
    - -config.expand-env=true

  extraEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
```

Thank you guys!

**Comment by fertab** [comment]
This is the values.yaml I've used and worked for me, thanks @chrizel 

```
loki:
  enabled: true
  auth_enabled: false
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: gp2
  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP

  extraArgs:
    config.expand-env: true

  config:
    memberlist:
      bind_addr:
        - ${MY_POD_IP}

promtail:
  enabled: true

grafana:
  enabled: true
```
