### ISSUE TITLE
how to run loki over https (TLS) via the configuration settings that go in `local-config.yaml`

### ISSUE THREAD

**Issue by mikequentel** [grafana/loki#6414]
Hi all...figured out how to run loki over https (TLS) via the configuration settings that go in `local-config.yaml` ...in this example, the endpoint is using 8443:

```
server:
  http_listen_port: 8443
  http_tls_config: &tls_server_config
    cert_file: /etc/loki/myserver.cert.pem
    key_file: /etc/loki/myserver.key.pem
```

this is an alternative to using a reverse proxy.
The above is based on the fact that loki uses [github.com/weaveworks/common/server/server.go](http://github.com/weaveworks/common/server/server.go) which in turn uses [github.com/prometheus/node_exporter/https/tls_config.go](http://github.com/prometheus/node_exporter/https/tls_config.go)

_Originally posted by @mikequentel in https://github.com/grafana/loki/issues/475#issuecomment-1158443035_

**Comment by kavirajk** [comment]
Hi @mikequentel, you mean you need a doc on how to run Loki under TLS? or am I missing something?

**Comment by mikequentel** [comment]
@kavirajk this feature should be mentioned in documentation. I will open a PR

**Comment by asperw** [comment]
Any indication how to use a custom CA in this case? We are using Loki in Docker with target all and it seems the internal connections fail. We tried putting our CA in `/usr/local/share/ca-certificates` in the container but that didn't work either. There's also the client_ca option in `tls_config.go` but that throws another error.

**Comment by mikequentel** [comment]
@asperw can the certs you are using be mounted volumes? How are you running the container?

**Comment by khronosmoe** [comment]
It looks like there is no need for `&tls_server_config`. From what I get from the config section of Promtail web, it looks like it supports tls over grpc.  So I try the following:
```
server:
  http_listen_port: 8443
  http_tls_config:
    cert_file: /etc/loki/myserver.cert.pem
    key_file: /etc/loki/myserver.key.pem
  grpc_listen_port: 9443
  grpc_tls_config:
    cert_file: /etc/loki/myserver.cert.pem
    key_file: /etc/loki/myserver.key.pem
```
It works for Promtail, but not for Loki. I suspect that Promtail may not use gprc so Promtail works. Loki, on the other hand, requires grpc to run and has no support for tls, so Loki doesn't work.
Meanwhile, Loki has no support for listening to localhost which leads to security concerns.

**Comment by mikequentel** [comment]
Example of using Caddy to enable TLS and Basic Authentication for Loki: 
https://github.com/mikequentel/caddy-and-loki-deployment-example

**Comment by khronosmoe** [comment]
> Meanwhile, Loki has no support for listening to localhost which leads to security concerns.

Listening on localhost works by adding `instance_addr: 127.0.0.1` to the `common `block. You can check [solution](https://github.com/grafana/loki/issues/6756) here.
So, the only remaining issue is tls over grpc and if you add `grpc_tls_config`  there will be error message:
`caller=frontend_scheduler_worker.go:231 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection closed before server preface received" addr=127.0.0.1:9443`

For now, configuration which works is:
```
  http_listen_address: localhost
  http_listen_port: 8443
  http_tls_config:
    cert_file: /etc/loki/myserver.cert.pem
    key_file: /etc/loki/myserver.key.pem
  grpc_listen_address: localhost
  grpc_listen_port: 9443
```

**Comment by szuro** [comment]
For future reference:
Setting `grpc_tls_config` causes the gRPC server to use TLS.
However, you still need to configure gRPC clients to do the same. The configuration is decribed [here](https://grafana.com/docs/loki/latest/configuration/#grpc_client).
Take note of the `grpc_client.tls_enabled` field.

After setting this on all relevant sections, the log is no longer littered by `err="rpc error: code = Unavailable desc = connection closed before server preface received"` messages.

**Comment by CarliJoy** [comment]
Is it really true, that there is no simple "please use TLS for server and clients" settings?

To activate TLS with GRPC I ended up with (only parts relevant for TLS):

```yaml
server:
  grpc_tls_config:
    client_ca_file: "{{ loki_ca_cert }}"
    cert_file: "{{ loki_cert }}"
    key_file: "{{ loki_cert_key }}"
    client_auth_type: RequireAndVerifyClientCert

frontend:
  grpc_client_config:
    tls_enabled: true
    tls_cert_path: "{{ loki_cert }}"
    tls_key_path: "{{ loki_cert_key }}"
    tls_insecure_skip_verify: true

ingester_client:
  grpc_client_config:
    tls_enabled: true
    tls_cert_path: "{{ loki_cert }}"
    tls_key_path: "{{ loki_cert_key }}"
    tls_insecure_skip_verify: true

pattern_ingester:
    client_config:
      grpc_client_config:
        tls_enabled: true
        tls_cert_path: "{{ loki_cert }}"
        tls_key_path: "{{ loki_cert_key }}"
        tls_insecure_skip_verify: true

memberlist:
  tls_enabled: true
  tls_cert_path: "{{ loki_cert }}"
  tls_key_path: "{{ loki_cert_key }}"
  tls_insecure_skip_verify: false

query_scheduler:
  grpc_client_config:
    tls_enabled: true
    tls_cert_path: "{{ loki_cert }}"
    tls_key_path: "{{ loki_cert_key }}"
    tls_insecure_skip_verify: true

storage_config:
  tsdb_shipper:
   index_gateway_client:
      grpc_client_config:
        tls_enabled: true
        tls_cert_path: "{{ loki_cert }}"
        tls_key_path: "{{ loki_cert_key }}"
        tls_insecure_skip_verify: true

frontend_worker:
  grpc_client_config:
    tls_enabled: true
    tls_cert_path: "{{ loki_cert }}"
    tls_key_path: "{{ loki_cert_key }}"
    tls_insecure_skip_verify: true

compactor_grpc_client:
    tls_enabled: true
    tls_cert_path: "{{ loki_cert }}"
    tls_key_path: "{{ loki_cert_key }}"
    tls_insecure_skip_verify: true
```

I mean honestly, I need to configure each ****** client manually?

Btw. I needed `tls_insecure_skip_verify:  true` because my client certifcates don't contain SAN for the IP of my hosts, which seems to be required.
I think activating TLS should be basic feature that doesn't require such extensive configuration!

Could we not introduce a `common.grpc_client_config` that if set overwrite the `grpc_client_config` of each component?

**Comment by attilaolah** [comment]
There is now [a global `grpc_client` config](https://grafana.com/docs/loki/latest/configure/#grpc_client), so something like this should do:

```yaml
  grpc_client:
    tls_enabled: true
    tls_cert_path: "{{ loki_cert }}"
    tls_key_path: "{{ loki_cert_key }}"
    tls_ca_path: "{{ loki_ca_cert }}"
```
