### ISSUE TITLE
How do I switch from Table-manger to Compactor in an existing Loki deploy

### ISSUE THREAD

**Issue by edtshuma** [grafana/loki#6462]
I have an issue whereby the chunks is not being deleted as per the set **max_look_back_period** . Having  done some research I discovered [here](https://github.com/grafana/loki/blob/main/docs/sources/upgrading/_index.md#the-single-binary-no-longer-runs-a-table-manager)  that table-manager is no longer supported.

I am however unsure how to amend my current configuration which looks like this :
loki-stack-values.yml

```yaml
grafana:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi
  adminPassword: Vfgfhdjdkdisynwtey678CMX7xghuy879

prometheus:
  enabled: true
  alertmanager:
    persistentVolume:
      enabled: true
      size: 2Gi
  server:
    persistentVolume:
      enabled: true
      size: 10Gi

loki:  
  enabled: true
  persistence:
    enabled: true
    size: 70Gi
  config:
    chunk_store_config:
      max_look_back_period: 672h
    table_manager:
      retention_deletes_enabled: true
      retention_period: 672h
```

statefulset.yml

```yaml
---
# Source: loki-stack/charts/loki/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: loki
  labels:
    app: loki
    chart: loki-2.11.0
    release: loki
    heritage: Helm
  annotations:
    {}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: loki
      release: loki
  serviceName: loki-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loki
        name: loki
        release: loki
      annotations:
        checksum/config: f1685c19aa5e8157738636fd074c7cb45763c46d46f08d9f05ca31e4445cd082
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: loki
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      initContainers:
        []
      containers:
        - name: loki
          image: "grafana/loki:2.5.0"
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/loki/loki.yaml"
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: "/data"
              subPath: 
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          resources:
            {}
          securityContext:
            readOnlyRootFilesystem: true
          env:
      nodeSelector:
        {}
      affinity:
        {}
      tolerations:
        []
      terminationGracePeriodSeconds: 4800
      volumes:
        - name: tmp
          emptyDir: {}
        - name: config
          secret:
            secretName: loki
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        {}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "70Gi"
      storageClassName:
```

I would like to amend my configuration as below. Is this correct ?  Or they are additional options I will need to add also.:

```yaml
grafana:
    enabled: true
    persistence:
      enabled: true
      size: 5Gi
    adminPassword: Vfgfhdjdkdisynwtey678CMX7xghuy879
  
  prometheus:
    enabled: true
    alertmanager:
      persistentVolume:
        enabled: true
        size: 2Gi
    server:
      persistentVolume:
        enabled: true
        size: 10Gi
  
  loki:  
    enabled: true
    persistence:
      enabled: true
      size: 70Gi
    config:
      compactor:
        retention_enabled: true
        retention_delete_delay: 2h 
        retention_delete_worker_count: 150
      limits_config:
  retention_period: 672h
  ```
