### ISSUE TITLE
Promtail : Unable to extract fields from JSON messages via Kafka topic, and add them as extra labels to each log line

### ISSUE THREAD

**Issue by wengelbrecht-grafana** [grafana/loki#6470]
**Describe the bug**

Promtail provides the pipeline stage where you can parse a JSON log, and extract these fields to add as additional labels. 
This works when the log line is coming from a file, but when the log line originates via Kafka, then the labelling stage does not work. 

For example, for the following log line: 
```
{"deviceid":"garage","f":12,"m":1,"t":"18.21","p":"1005.19","h":"59.19","l":"15.00","r":"-83.00"}
```
I am trying to extract the "deviceid" field, and add that as a label on each log line in order to create some cardinality. 
When using the below configuration, and reading the above log line from a file then the labelling works as expected: 
```
    - job_name: my-app3
      pipeline_stages:
        - json:
            expressions:
              deviceid: deviceid
        - labels:
            deviceid:
      static_configs:
      - targets:
        - localhost
        labels:
          job: applogs
          __path__: /tmp/app3.log
```
![image](https://user-images.githubusercontent.com/83230950/175267317-e4dc30aa-e9e3-42ea-93dc-e06d14d5253b.png)

However, if you do the same pipeline stage when reading from a Kafka topic, then the label is not added: 
```
scrape_configs:
  - job_name: kafka
    pipeline_stages:
      - json:
          expressions:
            deviceid: deviceid
      - labels:
          deviceid:
    kafka:
      brokers:
      - 127.0.0.1:9002
      topics:
      - iotjson
      authentication:
        type: none
      labels:
        job: kafka
        customer: customer1
```
![image](https://user-images.githubusercontent.com/83230950/175267684-a09f0c40-d4a2-46b2-87ce-33f0ced1e3ff.png)

When running promtail with --inspect, it looks like it is definitely picking up the labels in the kafka scrape config, but they are never added: 
```
level=info ts=2022-06-23T09:17:58.586192602Z caller=consumer.go:97 msg="consuming topic" details="member_id=sarama-95a8e05e-6967-4545-92f5-73a7b202986c generation_id=82 topic=iotjson partition=0 initial_offset=1292"
[inspect: json stage]:
{stages.Entry}.Extracted["deviceid"]:
        +: garage
```

**To Reproduce**
Use my two scrape configs above, and example message
Same message as a file, you will get the extra log label. Message via Kafka, no extra log label

**Expected behavior**
It should be possible to parse JSON coming via Kafka topics, extract fields from the message and add them as labels

**Environment:**
Laptop with a local Kafka (single replica). 
Promtail 2.5.0, with the above two scrape configs. Grafana Cloud logs as the destination
