### ISSUE TITLE
gcs cred fail

### ISSUE THREAD

**Issue by NoviceEric** [grafana/loki#6507]
**I  deploy  Loki  with docker ，and the docker-compose.yaml as follow :**

```
version: "3.7"
services:

  loki-1:
    image: grafana/loki:latest
    container_name: loki-1
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/etc/loki/key.json"
    volumes:
      - ./config:/etc/loki/
      - ./loki:/loki
    ports:
      - "3100"
      - "7946"
      - "9095"
    network_mode: "host"
    command: "-config.file=/etc/loki/loki-memberlist-config.yaml -target=all"
    restart: on-failure
```

**The container startup error log looks like this：**

```
loki-1  | level=warn ts=2022-06-27T10:39:48.458892621Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache"
loki-1  | level=warn ts=2022-06-27T10:39:48.458916577Z caller=fifo_cache.go:105 msg="running with DEPRECATED flag fifocache.size, use fifocache.max-size-items or fifocache.max-size-bytes instead" cache=frontend.fifocache
loki-1  | level=warn ts=2022-06-27T10:39:48.458930889Z caller=fifo_cache.go:118 msg="running with DEPRECATED flag fifocache.interval, use fifocache.ttl instead" cache=frontend.fifocache
loki-1  | level=warn ts=2022-06-27T10:39:48.459047568Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache"
loki-1  | level=error ts=2022-06-27T10:39:48.459346048Z caller=log.go:100 msg="error running loki" err="google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: invalid character '<' looking for beginning of value\nerror creating index client\ngithub.com/grafana/loki/pkg/storage/chunk/storage.NewStore\n\t/src/loki/pkg/storage/chunk/storage/factory.go:219\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:394\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:106\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:339\nmain.main\n\t/src/loki/cmd/loki/main.go:108\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:78\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:339\nmain.main\n\t/src/loki/cmd/loki/main.go:108\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
loki-1 exited with code 1

```
**is this a bug?**
