### ISSUE TITLE
loki-docker-driver install failed

### ISSUE THREAD

**Issue by edsion1107** [grafana/loki#6509]
**Describe the bug**
When i run `docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions`,from [doc](https://grafana.com/docs/loki/latest/clients/docker-driver/#installing), the result is failed.

**To Reproduce**
1. open terminal by ssh
2. run `docker login` successful
3. run `docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions`

**Expected behavior**
The plugin install successful.

**Environment:**
```shell
$ docker version
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.2
  Git commit:       20.10.12-0ubuntu2~20.04.1
  Built:            Thu Feb 10 15:03:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu1~20.04.4
  GitCommit:
 runc:
  Version:          1.1.0-0ubuntu1~20.04.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Screenshots, Promtail config, or terminal output**
```shell
$ docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
Error response from daemon: error resolving plugin reference: unexpected status code [manifests latest]: 401 Unauthorized
```

**Comment by Eratz** [comment]
Same issue, i had hope when i switched to raspbian 64bit but no...
here my workaround for now :

```
scrape_configs:
  - job_name: containers
    static_configs:
    - targets:
        - localhost
      labels:
        job: containerlogs
        __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
    - json:
        expressions:
          output: log
          stream: stream
          attrs:
    - json:
        expressions:
          tag:
        source: attrs
    - regex:
        expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
        source: tag
    - timestamp:
        format: RFC3339Nano
        source: time
    - labels:
        tag:
        stream:
        image_name:
        container_name:
        image_id:
        container_id:
    - output:
        source: output
```
Problem is, you query by container ID, which is not ideal.
