### ISSUE TITLE
Promtail : unable to set pipeline_stages with syslog config 

### ISSUE THREAD

**Issue by saibug** [grafana/loki#6510]
**Describe the bug**
pipeline_stages (timestamps) don't work for syslog module in promtail
See below the error output 

`field pipeline_stages not found in type scrapeconfig.SyslogTargetConfig`

**To Reproduce**
1. add pipepline_stages
2. Started Promtail 2.4.2 version 

**Expected behavior**
when promtail is failed/stopped, it will send the logs with logs's timestamps, and not timestamps when the log were extracted 

**Environment:**
 - Loki distributed stack (swarm cluster)
 - Deployment tool: docker swarm 

**Screenshots, Promtail config, or terminal output**

Promtail config : 

```
scrape_configs:
  - job_name: soslog-ng
    syslog:
      listen_address: 0.0.0.0:1514
      idle_timeout: 60s # The idle timeout for tcp syslog connections
      label_structured_data: yes
      labels:
        job: syslog-ng
    pipeline_stages:
    - match:
        stages:
        - timestamp:
            format: RFC3339Nano
            source: timestamp
```

**Comment by saibug** [comment]
I tried to put pipeline_stages section before syslog step, and got this error : 

`failed to make syslog target manager: invalid match stage config: selector statement required for match stage`

**Comment by saibug** [comment]
keep alive

**Comment by wols** [comment]
### promtail config
```
server:
  #
positions:
  #
clients:
  #
scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 127.0.0.1:51123
      listen_protocol: tcp
      label_structured_data: false
      labels:
        job: syslog
      use_incoming_timestamp: true
    relabel_configs:
      - source_labels: [__syslog_message_hostname]
        target_label: host
    pipeline_stages:
      - match:
        selector: '{job="syslog"}'
        stages:
          - regex:
            expression: '^(?P<all>.*)$'
```
### error message
one line:
```
level=error \
ts=2023-01-27T17:37:33.830805853Z \
caller=main.go:167 \
msg="error creating promtail" \
error="failed to make syslog target manager: pipeline stage must contain only one key"
```
