### ISSUE TITLE
Querier scheduler and tail_proxy_url

### ISSUE THREAD

**Issue by timansky** [grafana/loki#6522]
**Describe the bug**
`tail_proxy_url` not working for querier frontend when distributed loki with configured querier scheduller

**Screenshots, Promtail config, or terminal output**

```
...
    query_scheduler:
      max_outstanding_requests_per_tenant: 1024
      use_scheduler_ring: true
      scheduler_ring:
        kvstore:
          store: etcd
          etcd:
            endpoints: ***

    frontend_worker:
      parallelism: 1
      # match_max_concurrent: true
      dns_lookup_duration: 5s
      scheduler_address: loki-querier-scheduler.monitoring:9095
      grpc_client_config:
        grpc_compression: snappy
        rate_limit: 70
        rate_limit_burst: 100
        backoff_on_ratelimits: true
        max_recv_msg_size: 104857600 # 1024 * 1024 * 100 #100mb
        max_send_msg_size: 16777216 # 1024 * 1024 * 16 #16mb

    frontend:
      max_outstanding_per_tenant: 10240
      # querier_forget_delay: 15s
      log_queries_longer_than: 15s
      compress_responses: true
      tail_proxy_url: http://loki-querier.monitoring:3100
      scheduler_address: loki-querier-scheduler.monitoring:9095
...

```
```
LOKI_ADDR=http://localhost:3100 logcli --org-id="default" query '{service_name="loki"}' --tail
ws://localhost:3100/loki/api/v1/tail?limit=30&query=%7Bservice_name%3D%22loki%22%7D&start=1656389774927661000
Tailing logs failed: Error response from server:  (websocket: bad handshake)
```
