### ISSUE TITLE
[Loki] Incorrect server block configuration does not result in application failure

### ISSUE THREAD

**Issue by bschurig** [grafana/loki#6528]
**Describe the bug**

Setting  `http_server_write_timeout` or `http_server_read_timeout` to a number without a duration does not result in an error. When running on kubernetes the pod will start but never becomes healthy as the readiness probes will fail. The application does not log anything indicating that there is a misconfiguration of the server when the log level is set to `info`. 
 
**To Reproduce**

Incorrect Config:
Set the value of the timeout as an int instead of a string with a duration:
```yaml
  config: |
    auth_enabled: false
    server:
      log_level: info
      http_listen_port: 3100
      http_server_read_timeout: 910 # values should have a duration
      http_server_write_timeout: 910
      http_server_idle_timeout: 180
```

Valid Config:
Set the value of the timeout with a duration:
```yaml
  config: |
    auth_enabled: false
    server:
      log_level: info
      http_listen_port: 3100
      http_server_read_timeout: 910s
      http_server_write_timeout: 910s
      http_server_idle_timeout: 180s
```

1. Started Loki (SHA or version): [v2.5.0](https://github.com/grafana/loki/releases/tag/v2.5.0) Using the distributed helm chart.

**Expected behavior**

The expected behavior when the server block is misconfigured is that the application throws an error and stops, logging the exception so that it can be addressed.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

When looking at the logs of two different replicas, it's impossible to tell which has the incorrect configuration. If you look at the extended logs of the misconfigured replica the only difference is that there are logs from failed scrapes to `/metrics`

Pod logs from a failing distributor replica:
![image](https://user-images.githubusercontent.com/8037329/176246684-ec47005f-56be-4eb6-8632-3748308b2ce6.png)

Pod logs from a distributor replica after the configuration has been corrected (the warning from the other screen shot had been addressed in this example):
![image](https://user-images.githubusercontent.com/8037329/176247923-44d114b8-d84d-4027-8bb6-9e4c07e200e9.png)
