### ISSUE TITLE
loki-docker-driver to support defaults

### ISSUE THREAD

**Issue by chrisbecke** [grafana/loki#6567]
**Is your feature request related to a problem? Please describe.**
When deploying loki-docker-driver to Docker instances, the plugin cannot be consumed by containers without extensive per-container setup.

**Describe the solution you'd like**
Docker plugins support per-alias configuration. The setting values are stored with each alias by docker, and can be accessed with `docker plugin set` - or set during plugin installation.

Potential usage would be:

```bash
docker plugin install grafana/loki-docker-driver --alias loki loki-url=http://loki:3100 max-files=2 max-size=1m keep-files=true
docker plugin install grafana/loki-docker-driver --alias loki2 
docker plugin set loki2 loki-url=http://alt-server:3100
```

Consequently it should be possible to declare the wanted loki alias and provide no driver-opts, or to selectively override certain opts using driver-opts:

```yaml
services:
  service1:
    image: someimage:
    logging:
      driver: loki

  service2:
    image: someimage
    logging:
      driver: loki2
      driver-opts:
       no-file: "true"
 ```

**Describe alternatives you've considered**
The docker-loki-driver does support reading config when installed as the default logging plugin, but this does not help if only select services should be using loki, or if multiple loki targets are required.
