### ISSUE TITLE
Distributor tries accessing s3?

### ISSUE THREAD

**Issue by rlex** [grafana/loki#6572]
**Describe the bug**
While debugging separate issue i found traces from loki-distributor with S3 error logs (access denied). Since distributor doesn't interact with object store, it shouldn't be here?

```InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.```

Distributor doesn't have s3 keys because i expose them with env per each service.

It's s3.getobject method and it seems to appear on all components of loki-distributed helm chart.

Maybe it's trying to get some specific file, like cluster seed? If i add S3 credentials (with env variables) errors go away.

**To Reproduce**
Install loki with loki-distributed helm chart and tracing enabled, with s3 object store. Version 2.5.0.
In my case S3 credentials is in external secret store, and exposed via env like this (but should work withour ref for testing):
```
          extraArgs:
            - --config.expand-env=true
          extraEnv:
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_AGENT_PORT
              value: '6831'
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: '1.0'
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: S3_ACCESS_KEY_ID
                  name: loki-s3-credentials
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: S3_SECRET_KEY
                  name: loki-s3-credentials
```

In components where i don't need s3 (queryfrontend, distributor) i omit S3_ACCESS_KEY_ID and S3_SECRET_KEY parameters, so access keys for s3 will be empty. Then distributor and queryfrontend starts to error (but everything works as expected).

Observe traces with error=true, look for s3.getObject methods.

**Expected behavior**
Distributor and queryfrontend shouldn't try to access object store?

**Environment:**
 - Infrastructure: k8s
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
None
