### ISSUE TITLE
failed to get s3 object: NoSuchKey: The specified key does not exist

### ISSUE THREAD

**Issue by panzelva** [grafana/loki#6590]
**Describe the bug**
When trying to access log with grafana, Loki returns error message `failed to get s3 object: NoSuchKey: The specified key does not exist.`.

**To Reproduce**
1. Start Loki and connect Loki to Grafana
2. When trying to access old logs (mostly 12 hours and older), Loki returns 500 with error message in description.
3. (alternatively make GET request to `/loki/api/v1/query_range?direction=BACKWARD&end=1657091640000000000&limit=1000&query=sum+by%28level%29%28count_over_time%28%7Bcluster%3D%22production%22%7D%5B1m%5D%29%29&shards=13_of_16&start=1657090800000000000&step=60.000000`)

**Expected behavior**
Loki should not fail when querying logs.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm
 - Loki version: 2.4.2, 2.5.0 (happens on both versions)

**Screenshots, Promtail config, or terminal output**

logs from Loki:
```
level=info ts=2022-07-06T13:57:44.67219369Z caller=metrics.go:92 org_id=fake latency=fast query="sum by(level)(count_over_time({cluster=\"production\"}[1m]))" query_type=metric range_type=range length=14m0s step=1m0s duration=6.205875ms status=200 limit=1000 returned_lines=0 throughput=3.9MB total_bytes=24kB
level=info ts=2022-07-06T13:57:44.674963666Z caller=metrics.go:92 org_id=fake latency=fast query="sum by(level)(count_over_time({cluster=\"production\"}[1m]))" query_type=metric range_type=range length=14m0s step=1m0s duration=5.620112ms status=200 limit=1000 returned_lines=0 throughput=45MB total_bytes=252kB
level=error ts=2022-07-06T13:57:47.917590509Z caller=batch.go:699 msg="error fetching chunks" err="failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: txf9caaa005c174832894be-0062c594db, host id: txf9caaa005c174832894be-0062c594db"
level=info ts=2022-07-06T13:57:47.918218271Z caller=metrics.go:92 org_id=fake latency=fast query="sum by(level)(count_over_time({cluster=\"production\"}[1m]))" query_type=metric range_type=range length=14m0s step=1m0s duration=3.288313336s status=500 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
level=warn ts=2022-07-06T13:57:47.918619797Z caller=logging.go:72 traceID=1c8284e13c96e7ff orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1657091640000000000&limit=1000&query=sum+by%28level%29%28count_over_time%28%7Bcluster%3D%22production%22%7D%5B1m%5D%29%29&shards=13_of_16&start=1657090800000000000&step=60.000000 (500) 3.289122008s Response: \"failed to get s3 object: NoSuchKey: The specified key does not exist.\\n\\tstatus code: 404, request id: txf9caaa005c174832894be-0062c594db, host id: txf9caaa005c174832894be-0062c594db\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 1c8284e13c96e7ff:1eddb9b3949da408:1f28dfd267b0618e:0; "
level=error ts=2022-07-06T13:57:48.026861444Z caller=batch.go:699 msg="error fetching chunks" err="failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: txa24e615b976644f8ac3aa-0062c594db, host id: txa24e615b976644f8ac3aa-0062c594db"
level=info ts=2022-07-06T13:57:48.027116485Z caller=metrics.go:92 org_id=fake latency=fast query="sum by(level)(count_over_time({cluster=\"production\"}[1m]))" query_type=metric range_type=range length=14m0s step=1m0s duration=3.380987522s status=500 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
level=warn ts=2022-07-06T13:57:48.027322101Z caller=logging.go:72 traceID=1c8284e13c96e7ff orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1657088940000000000&limit=1000&query=sum+by%28level%29%28count_over_time%28%7Bcluster%3D%22production%22%7D%5B1m%5D%29%29&shards=13_of_16&start=1657088100000000000&step=60.000000 (500) 3.38140625s Response: \"failed to get s3 object: NoSuchKey: The specified key does not exist.\\n\\tstatus code: 404, request id: txa24e615b976644f8ac3aa-0062c594db, host id: txa24e615b976644f8ac3aa-0062c594db\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 1c8284e13c96e7ff:0158181f3ebdbe64:0c39cea0eef216b9:0; "
level=error ts=2022-07-06T13:57:50.614717271Z caller=batch.go:699 msg="error fetching chunks" err="failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: tx3b71ed38d9e4428aab702-0062c594de, host id: tx3b71ed38d9e4428aab702-0062c594de"
level=info ts=2022-07-06T13:57:50.615061969Z caller=metrics.go:92 org_id=fake latency=fast query="sum by(level)(count_over_time({cluster=\"production\"}[1m]))" query_type=metric range_type=range length=14m0s step=1m0s duration=2.585105639s status=500 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
level=warn ts=2022-07-06T13:57:50.615241758Z caller=logging.go:72 traceID=1c8284e13c96e7ff orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1657088940000000000&limit=1000&query=sum+by%28level%29%28count_over_time%28%7Bcluster%3D%22production%22%7D%5B1m%5D%29%29&shards=13_of_16&start=1657088100000000000&step=60.000000 (500) 2.585679669s Response: \"failed to get s3 object: NoSuchKey: The specified key does not exist.\\n\\tstatus code: 404, request id: tx3b71ed38d9e4428aab702-0062c594de, host id: tx3b71ed38d9e4428aab702-0062c594de\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 1c8284e13c96e7ff:0158181f3ebdbe64:0c39cea0eef216b9:0; "
level=error ts=2022-07-06T13:57:50.65206401Z caller=batch.go:699 msg="error fetching chunks" err="failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: txd006b3a14671424abc033-0062c594de, host id: txd006b3a14671424abc033-0062c594de"
level=info ts=2022-07-06T13:57:50.652495823Z caller=metrics.go:92 org_id=fake latency=fast query="sum by(level)(count_over_time({cluster=\"production\"}[1m]))" query_type=metric range_type=range length=14m0s step=1m0s duration=2.730742526s status=500 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
level=warn ts=2022-07-06T13:57:50.652694608Z caller=logging.go:72 traceID=1c8284e13c96e7ff orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1657091640000000000&limit=1000&query=sum+by%28level%29%28count_over_time%28%7Bcluster%3D%22production%22%7D%5B1m%5D%29%29&shards=13_of_16&start=1657090800000000000&step=60.000000 (500) 2.731374587s Response: \"failed to get s3 object: NoSuchKey: The specified key does not exist.\\n\\tstatus code: 404, request id: txd006b3a14671424abc033-0062c594de, host id: txd006b3a14671424abc033-0062c594de\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 1c8284e13c96e7ff:1eddb9b3949da408:1f28dfd267b0618e:0; "
level=error ts=2022-07-06T13:57:53.323389682Z caller=batch.go:699 msg="error fetching chunks" err="failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: tx9445f67dfa664154a1d51-0062c594e1, host id: tx9445f67dfa664154a1d51-0062c594e1"
level=info ts=2022-07-06T13:57:53.324028644Z caller=metrics.go:92 org_id=fake latency=fast query="sum by(level)(count_over_time({cluster=\"production\"}[1m]))" query_type=metric range_type=range length=14m0s step=1m0s duration=2.706200577s status=500 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
level=warn ts=2022-07-06T13:57:53.324372242Z caller=logging.go:72 traceID=1c8284e13c96e7ff orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1657088940000000000&limit=1000&query=sum+by%28level%29%28count_over_time%28%7Bcluster%3D%22production%22%7D%5B1m%5D%29%29&shards=13_of_16&start=1657088100000000000&step=60.000000 (500) 2.707276201s Response: \"failed to get s3 object: NoSuchKey: The specified key does not exist.\\n\\tstatus code: 404, request id: tx9445f67dfa664154a1d51-0062c594e1, host id: tx9445f67dfa664154a1d51-0062c594e1\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 1c8284e13c96e7ff:0158181f3ebdbe64:0c39cea0eef216b9:0; "
level=error ts=2022-07-06T13:57:53.519513291Z caller=batch.go:699 msg="error fetching chunks" err="failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: txff246eda2c894133bca72-0062c594e1, host id: txff246eda2c894133bca72-0062c594e1"
level=info ts=2022-07-06T13:57:53.51998042Z caller=metrics.go:92 org_id=fake latency=fast query="sum by(level)(count_over_time({cluster=\"production\"}[1m]))" query_type=metric range_type=range length=14m0s step=1m0s duration=2.86474032s status=500 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
level=warn ts=2022-07-06T13:57:53.520389531Z caller=logging.go:72 traceID=1c8284e13c96e7ff orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1657091640000000000&limit=1000&query=sum+by%28level%29%28count_over_time%28%7Bcluster%3D%22production%22%7D%5B1m%5D%29%29&shards=13_of_16&start=1657090800000000000&step=60.000000 (500) 2.865550536s Response: \"failed to get s3 object: NoSuchKey: The specified key does not exist.\\n\\tstatus code: 404, request id: txff246eda2c894133bca72-0062c594e1, host id: txff246eda2c894133bca72-0062c594e1\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 1c8284e13c96e7ff:1eddb9b3949da408:1f28dfd267b0618e:0; "
level=error ts=2022-07-06T13:57:55.788356945Z caller=batch.go:699 msg="error fetching chunks" err="failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: tx8d69371b27104fcbb03a6-0062c594e3, host id: tx8d69371b27104fcbb03a6-0062c594e3"
level=info ts=2022-07-06T13:57:55.788677027Z caller=metrics.go:92 org_id=fake latency=fast query="sum by(level)(count_over_time({cluster=\"production\"}[1m]))" query_type=metric range_type=range length=14m0s step=1m0s duration=2.461769783s status=500 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
level=warn ts=2022-07-06T13:57:55.788780863Z caller=logging.go:72 traceID=1c8284e13c96e7ff orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1657088940000000000&limit=1000&query=sum+by%28level%29%28count_over_time%28%7Bcluster%3D%22production%22%7D%5B1m%5D%29%29&shards=13_of_16&start=1657088100000000000&step=60.000000 (500) 2.462310341s Response: \"failed to get s3 object: NoSuchKey: The specified key does not exist.\\n\\tstatus code: 404, request id: tx8d69371b27104fcbb03a6-0062c594e3, host id: tx8d69371b27104fcbb03a6-0062c594e3\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 1c8284e13c96e7ff:0158181f3ebdbe64:0c39cea0eef216b9:0; "
level=error ts=2022-07-06T13:57:56.314392153Z caller=batch.go:699 msg="error fetching chunks" err="failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: txef2c3e230bb744a197975-0062c594e4, host id: txef2c3e230bb744a197975-0062c594e4"
level=info ts=2022-07-06T13:57:56.314609432Z caller=metrics.go:92 org_id=fake latency=fast query="sum by(level)(count_over_time({cluster=\"production\"}[1m]))" query_type=metric range_type=range length=14m0s step=1m0s duration=2.790988196s status=500 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
level=warn ts=2022-07-06T13:57:56.314706886Z caller=logging.go:72 traceID=1c8284e13c96e7ff orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1657091640000000000&limit=1000&query=sum+by%28level%29%28count_over_time%28%7Bcluster%3D%22production%22%7D%5B1m%5D%29%29&shards=13_of_16&start=1657090800000000000&step=60.000000 (500) 2.791836413s Response: \"failed to get s3 object: NoSuchKey: The specified key does not exist.\\n\\tstatus code: 404, request id: txef2c3e230bb744a197975-0062c594e4, host id: txef2c3e230bb744a197975-0062c594e4\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 1c8284e13c96e7ff:1eddb9b3949da408:1f28dfd267b0618e:0; "
level=error ts=2022-07-06T13:57:58.385704449Z caller=batch.go:699 msg="error fetching chunks" err="failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: txdb3e2816a9cf4a9c9330b-0062c594e6, host id: txdb3e2816a9cf4a9c9330b-0062c594e6"
level=info ts=2022-07-06T13:57:58.385996278Z caller=metrics.go:92 org_id=fake latency=fast query="sum by(level)(count_over_time({cluster=\"production\"}[1m]))" query_type=metric range_type=range length=14m0s step=1m0s duration=2.59440819s status=500 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
level=warn ts=2022-07-06T13:57:58.386219138Z caller=logging.go:72 traceID=1c8284e13c96e7ff orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1657088940000000000&limit=1000&query=sum+by%28level%29%28count_over_time%28%7Bcluster%3D%22production%22%7D%5B1m%5D%29%29&shards=13_of_16&start=1657088100000000000&step=60.000000 (500) 2.594940472s Response: \"failed to get s3 object: NoSuchKey: The specified key does not exist.\\n\\tstatus code: 404, request id: txdb3e2816a9cf4a9c9330b-0062c594e6, host id: txdb3e2816a9cf4a9c9330b-0062c594e6\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 1c8284e13c96e7ff:0158181f3ebdbe64:0c39cea0eef216b9:0; "
level=error ts=2022-07-06T13:57:58.863630061Z caller=batch.go:699 msg="error fetching chunks" err="failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: tx754a9b7a96bf45ec9efdf-0062c594e6, host id: tx754a9b7a96bf45ec9efdf-0062c594e6"
level=info ts=2022-07-06T13:57:58.864031597Z caller=metrics.go:92 org_id=fake latency=fast query="sum by(level)(count_over_time({cluster=\"production\"}[1m]))" query_type=metric range_type=range length=14m0s step=1m0s duration=2.547351175s status=500 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
level=warn ts=2022-07-06T13:57:58.864314751Z caller=logging.go:72 traceID=1c8284e13c96e7ff orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1657091640000000000&limit=1000&query=sum+by%28level%29%28count_over_time%28%7Bcluster%3D%22production%22%7D%5B1m%5D%29%29&shards=13_of_16&start=1657090800000000000&step=60.000000 (500) 2.54798494s Response: \"failed to get s3 object: NoSuchKey: The specified key does not exist.\\n\\tstatus code: 404, request id: tx754a9b7a96bf45ec9efdf-0062c594e6, host id: tx754a9b7a96bf45ec9efdf-0062c594e6\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 1c8284e13c96e7ff:1eddb9b3949da408:1f28dfd267b0618e:0; "
level=error ts=2022-07-06T13:57:59.197954188Z caller=batch.go:699 msg="error fetching chunks" err="failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: txb8607c9a565e41ef8fa05-0062c594e7, host id: txb8607c9a565e41ef8fa05-0062c594e7"
level=info ts=2022-07-06T13:57:59.19853415Z caller=metrics.go:92 org_id=fake latency=fast query="sum by(level)(count_over_time({cluster=\"production\"}[1m]))" query_type=metric range_type=range length=14m0s step=1m0s duration=2.962919156s status=500 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
level=warn ts=2022-07-06T13:57:59.19886929Z caller=logging.go:72 traceID=1c8284e13c96e7ff orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&end=1657092540000000000&limit=1000&query=sum+by%28level%29%28count_over_time%28%7Bcluster%3D%22production%22%7D%5B1m%5D%29%29&shards=13_of_16&start=1657091700000000000&step=60.000000 (500) 2.963913638s Response: \"failed to get s3 object: NoSuchKey: The specified key does not exist.\\n\\tstatus code: 404, request id: txb8607c9a565e41ef8fa05-0062c594e7, host id: txb8607c9a565e41ef8fa05-0062c594e7\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 1c8284e13c96e7ff:5eb5fcde775d9a6a:729366a18db46bac:0; "
```

Loki configuration:
```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
compactor:
  shared_store: filesystem
distributor:
  ring:
    kvstore:
      store: memberlist
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  tail_proxy_url: http://loki-querier:3100
frontend_worker:
  frontend_address: loki-query-frontend:9095
ingester:
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_idle_period: 1h
  chunk_retain_period: 1m
  chunk_target_size: 1536000
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  max_chunk_age: 1h
  max_transfer_retries: 0
  wal:
    dir: /var/loki/wal
limits_config:
  enforce_metric_name: false
  max_cache_freshness_per_query: 10m
  reject_old_samples: true
  reject_old_samples_max_age: 168h
memberlist:
  join_members:
  - loki-memberlist
query_range:
  align_queries_with_step: true
  cache_results: true
  max_retries: 5
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 1024
        validity: 24h
  split_queries_by_interval: 15m
ruler:
  alertmanager_url: https://alertmanager.xx
  external_url: https://alertmanager.xx
  ring:
    kvstore:
      store: memberlist
  rule_path: /tmp/loki/scratch
  storage:
    local:
      directory: /etc/loki/rules
    type: local
schema_config:
  configs:
  - from: "2020-09-07"
    index:
      period: 24h
      prefix: loki_index_
    object_store: s3
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
storage_config:
  aws:
    region: fr-par
    s3: s3://access_key:secret_key@s3.fr-par.scw.cloud/bucket
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    cache_ttl: 168h
    shared_store: s3
  filesystem:
    directory: /var/loki/chunks
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
```

**Comment by rlex** [comment]
By quick look you have storage_config configured as "aws", but you specify shared_store: "s3" in several places. Try swapping it to aws. Compactor should use aws as well, and object_store in schema_config should be aws too.

**Comment by rlex** [comment]
NoSuchKey usually means there is misconfiguration of s3 endpoint - ie wrong API key, s3 endpoint or etc.

**Comment by panzelva** [comment]
Looks like problem is gone - thanks for help! Closing this issue.

**Comment by gnanasalten** [comment]
can someone help on this error, i am still facing this error.


My config 
//

  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
      shared_store: s3
    aws:
      bucketnames: loki-bucket-dc1-001
      endpoint: xx.xx.xx.xx
      access_key_id: xxxxxxxxxxxxxxxxxxxxx
      secret_access_key: Axxxxxxxxxxxxxxxxxxx
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 0s
        insecure_skip_verify: true
      s3forcepathstyle: true
//

**Comment by evercast-mahesh2021** [comment]
> Looks like problem is gone - thanks for help! Closing this issue.

Do you mind sharing what was the fix for this? I am having the same issue. TIA

**Comment by panzelva** [comment]
@evercast-mahesh2021 Hi, the problem was exactly what @rlex wrote here: https://github.com/grafana/loki/issues/6590#issuecomment-1177967936

I defined storage configuration as `aws`, but I used `s3` as reference to this config. Once I changed all `s3` references to `aws`, error went away.

**Comment by evercast-mahesh2021** [comment]
@panzelva thanks for the reply. Yeah i tried the same thing but somehow its not pulling the logs older than last 3-6 hours.

**Comment by earimont-ib** [comment]
@evercast-mahesh2021 Did you ever get your configuration to work as explained above?

**Comment by GNSunny** [comment]
I have the same error
> org_id=fake msg="error fetching chunks" err="failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: 

Environment:
```
Infrastructure: Kubernetes 1.23
Deployment tool: Helm
Loki version: 2.7.3
```

Configuraiton:
```
    storage:
      bucketNames:
        chunks: dev-loki
        ruler: dev-loki
        admin: dev-loki
      type: s3
      s3:
        region: eu-west-1
    schemaConfig:
      configs:
        - from: 2020-11-05
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
        - from: 2023-06-01
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            prefix: loki_index_
            period: 24h
```
I have seen many logs with 
```
org_id=fake msg="error fetching chunks" err="failed to get s3 object: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id:
```

any help would be much appreciated.

**Comment by sebastianserrano** [comment]
For anyone facing this issue, my problem was that I was trying to reference the bucket with a nested internal path, meaning `my-bucket/loki`. This is the configuration which worked for me, on AWS, on version [4.8.0](https://artifacthub.io/packages/helm/grafana/loki/4.8.0)

```
loki:
  loki:
    auth_enabled: false

    commonConfig:
      path_prefix: /var/loki
      replication_factor: 3

    compactor:
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150

    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 48h
      split_queries_by_interval: 15m
      ingestion_rate_strategy: global
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      retention_period: 24h

    storage_config:
      aws:
        bucketnames: ""
        access_key_id: ""
        secret_access_key: ""
        region: ""
        s3: s3.endpoint.com
        endpoint: ""
        s3forcepathstyle: true
        insecure: false
        sse_encryption: false

      boltdb_shipper:
        shared_store: aws
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 168h
      filesystem:
        directory: /var/loki/chunks

    schemaConfig:
      configs:
        - from: "2022-01-11"
          index:
            period: 24h
            prefix: loki_index_
          object_store: s3
          schema: v12
          store: boltdb-shipper

    server:
      grpc_listen_port: 9095
      http_listen_port: 3100

```
