### ISSUE TITLE
too many failed ingesters/error removing stale clients

### ISSUE THREAD

**Issue by mizeng** [grafana/loki#660]
**Describe the bug**
I installed 2 loki servers (behind a vip, use one same Consul server, index store and chunk store located in a NFS mount point) on kubenates pods. However, when I insert one log through push api and want to query from the Loki server, I find one of the loki server always return "level=error ts=2019-06-11T03:10:26.577581986Z caller=pool.go:170 msg="error removing stale clients" err="too many failed ingesters"", while the other one loki server works normal.

**To Reproduce**
1. Started loki
2. Insert a log through `api/prom/push`
3. Query log

**Expected behavior**
No such error occurs,

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, promtail config, or terminal output**
loki config:
```
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: consul
        consul:
          host: consul.dev.com:8500
          prefix: ''
          httpclienttimeout: 20s
          consistentreads: true
      replication_factor: 1
  chunk_idle_period: 15m

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb
    object_store: filesystem
    schema: v9
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: /import/nfs/loki/index

  filesystem:
    directory: /import/nfs/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: false
  retention_period: 0
```
