### ISSUE TITLE
rpc error: code = Unimplemented desc = unknown service logproto.Pusher

### ISSUE THREAD

**Issue by mizeng** [grafana/loki#661]
**Describe the bug**
I deployed Loki as below on kubernetes(exposed 3100 and 9095 port):
1 table-manager
3 distributors
3 ingesters
3 queriers

However, I then find error when I try to push Logs to distributor: "rpc error: code = Unimplemented desc = unknown service logproto.Pusher". Could anyone help?  How to debug this without stack trace? Is it related to grpc communication since they all use "127.0.0.1" in ingester.lifecycle.address?

** Config
They are using the same loki config as below, but have different cmd args in the startup (-target=distributor, -target=table-manager, ...).
```
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: consul
        consul:
          host: consul.dev.com:8500
          prefix: ''
          httpclienttimeout: 20s
          consistentreads: true
      replication_factor: 1
  chunk_idle_period: 15m

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb
    object_store: filesystem
    schema: v9
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: /import/nfs/loki/index

  filesystem:
    directory: /import/nfs/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  retention_deletes_enabled: false
  retention_period: 0
```

**Distributor logs**
Below is distributor logs:
```
level=info ts=2019-06-11T07:17:37.522071222Z caller=loki.go:125 msg=initialising module=server
level=info ts=2019-06-11T07:17:37.522237359Z caller=server.go:120 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2019-06-11T07:17:37.522499626Z caller=loki.go:125 msg=initialising module=overrides
level=info ts=2019-06-11T07:17:37.522517676Z caller=override.go:48 msg="per-tenant overides disabled"
level=info ts=2019-06-11T07:17:37.522527881Z caller=loki.go:125 msg=initialising module=ring
level=info ts=2019-06-11T07:17:37.522572655Z caller=loki.go:125 msg=initialising module=distributor
level=info ts=2019-06-11T07:17:37.522607882Z caller=main.go:69 msg="Starting Loki" version="(version=master-f939e42, branch=master, revision=f939e42)"
level=error ts=2019-06-11T07:17:52.522872463Z caller=pool.go:170 msg="error removing stale clients" err="too many failed ingesters"
level=error ts=2019-06-11T07:18:07.522835493Z caller=pool.go:170 msg="error removing stale clients" err="too many failed ingesters"
level=error ts=2019-06-11T07:18:22.522810842Z caller=pool.go:170 msg="error removing stale clients" err="too many failed ingesters"
level=error ts=2019-06-11T07:18:37.522808425Z caller=pool.go:170 msg="error removing stale clients" err="too many failed ingesters"
level=warn ts=2019-06-11T07:19:08.595111149Z caller=logging.go:49 traceID=5f55f3328c8b621c msg="POST /api/prom/push (500) 2.528348ms Response: \"rpc error: code = Unimplemented desc = unknown service logproto.Pusher\\n\" ws: false; Accept: */*; Accept-Encoding: gzip, deflate; Accept-Language: en,zh-CN;q=0.9,zh;q=0.8; Cache-Control: no-cache; Connection: keep-alive; Content-Length: 490; Content-Type: application/json; Origin: chrome-extension://aicmkgpgakddgnaphhhpliifpcfhicfo; Postman-Token: 09c7b2f7-af2c-ad03-65f5-87273a3e0e19; User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36; X-Postman-Interceptor-Id: a1910a59-8c3d-9c99-6be6-148ec28e133f; "
level=warn ts=2019-06-11T07:22:55.250453599Z caller=logging.go:49 traceID=1038e0d59369bfec msg="POST /api/prom/push (500) 1.891529ms Response: \"rpc error: code = Unimplemented desc = unknown service logproto.Pusher\\n\" ws: false; Accept: */*; Cache-Control: no-cache; Content-Length: 490; Content-Type: application/json; Postman-Token: c25a2aab-522f-f2b9-2a61-5d3705f31fbf; User-Agent: curl/7.54.0; "
```
