### ISSUE TITLE
Likely Memory Leak for Ingester

### ISSUE THREAD

**Issue by mizeng** [grafana/loki#662]
**Describe the bug**
I've deployed ingester only with max 20GB memory. However from the Memory Usage Dashboard, I find a periodically pattern that memory increasing and finally use up all the memory.
![Screen Shot 2019-06-12 at 8 17 31 AM](https://user-images.githubusercontent.com/8059086/59315751-aaab4680-8ced-11e9-81be-ac4bfcca1467.png)

Only find below related log in ingester pod:
```
level=warn ts=2019-06-12T00:31:40.638602072Z caller=grpc_logging.go:37 duration=1.760055ms method=/logproto.Pusher/Push err="rpc error: code = Code(400) desc = entry out of order for stream: {hostname=\"***\", namespace=\"performanceTest\", threadName=\"LokiSink1\"}" msg="gRPC\n"
```
**To Reproduce**
1. Started table-manager, distributor, ingester.

**Expected behavior**

**Environment:**
 - Store
ring: Consul
chunk store: filesystem on NFS
index store: boltdb on NFS
```
storage_config:
  boltdb:
    directory: /import/nfs/loki/index

  filesystem:
    directory: /import/nfs/loki/chunks
```
 - Infrastructure: Kubernetes
1 table-manager
1 distributor
3 ingesters
 - Deployment tool: kubectl deploy with deploy/svc yaml

**Screenshots, promtail config, or terminal output**
1. deploy yaml for ingester
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingester
spec:
  replicas: 3
  template:
    metadata:
      name: ingester
      annotations:
        ***
      labels:
        app: "ingester"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: loki
        image: grafana/loki:latest
        command: ["/bin/loki"]
        args: ["-config.file=/etc/loki/local-config.yaml", "-target=ingester"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/loki
        - name: nfs
          mountPath: /import/nfs
        ports:
        - containerPort: 3100
        - containerPort: 9095
        resources:
          requests:
            cpu: 2
            memory: 20Gi
          limits:
            cpu: 4
            memory: 20Gi
        imagePullPolicy: Always
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: config-volume
        configMap:
          name: loki-conf
          items:
          - key: temp.yaml
            path: local-config.yaml
      - name: nfs
        nfs:
          monitors:
          - ****
          - ****
          user: user
          path: /
          secretRef:
            name: nfs-secret
          readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  annotations:
   lb_provider: lbms
  labels:
    app: ingester
  name: ingester
  namespace: loki
spec:
  ports:
  - port: 3100
    name: http
  - port: 9095
    name: grpc
  selector:
    app: ingester
  sessionAffinity: None
  type: LoadBalancer
```
