### ISSUE TITLE
Loki ignores JAEGER_SERVICE_NAME env variable

### ISSUE THREAD

**Issue by rlex** [grafana/loki#6621]
**Describe the bug**
Loki ignores JAEGER_SERVICE_NAME env variable

**To Reproduce**
Enable tracing of any loki container like this, redefining service name
```
          extraEnv:
            - name: JAEGER_SERVICE_NAME
              value: 'loki-stg-ingester'
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_AGENT_PORT
              value: '6831'
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_SAMPLER_PARAM
              value: '1.0'
```

**Expected behavior**
Traces should appear as loki-stg-ingester service name, but appear as loki-ingester. Hardcoded somewhere?
