### ISSUE TITLE
Loki-simple-scale "auth_enabled: true". The log cannot be queried in the ruler component 

### ISSUE THREAD

**Issue by weiya1990** [grafana/loki#6625]
Please see Loki configuration and screenshots
```
auth_enabled: true
chunk_store_config:
  chunk_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_bytes: 100MB
common:
  path_prefix: /var/loki
  replication_factor: 1
  storage:
    s3:
      access_key_id: xxx
      bucketnames: xxxx
      endpoint: xxxx
      secret_access_key: xxxx
      s3forcepathstyle: false
memberlist:
  join_members:
  - loki-simple-scalable-memberlist
  randomize_node_name: false
schema_config:
  configs:
  - from: "2020-09-07"
    index:
      period: 24h
      prefix: loki_index_
    object_store: s3
    schema: v11
    store: boltdb-shipper
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 1h
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: memberlist
  max_chunk_age: 1h
  wal:
    dir: /var/loki/wal
compactor:
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  retention_enabled: false
  shared_store: s3
  compaction_interval: 30m
  working_directory: /var/loki/boltdb-shipper-compactor
limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: 20
  ingestion_rate_mb: 20
  ingestion_rate_strategy: global
  max_cache_freshness_per_query: 10m
  max_global_streams_per_user: 10000
  max_query_length: 12000h
  max_query_parallelism: 16
  max_streams_per_user: 100000
  per_stream_rate_limit: 20MB
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 768h
querier:
  engine:
    timeout: 3m
  extra_query_delay: 0s
  max_concurrent: 10
  query_ingesters_within: 3h
  query_timeout: 5m
  tail_max_duration: 1h
query_range:
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_bytes: 300MB
ruler:
  alertmanager_url: http://alertmanager-main.monitoring:9093
  enable_alertmanager_v2: true
  enable_api: true
  storage:
    type: local
    local:
      directory: /loki/rules
  ring:
    kvstore:
      store: memberlist
  flush_period: 1m
  enable_sharding: false

server:
  http_listen_port: 3100
```
![image](https://user-images.githubusercontent.com/38902618/177896879-0ca70cbc-d813-48bd-9320-7ddc605ba11c.png)
