### ISSUE TITLE
Querying data spanning multiple schemas will only return data from latest schema

### ISSUE THREAD

**Issue by sflandergan** [grafana/loki#6653]
**Describe the bug**

I added an additional schema entry switching from `v11` to `v12` schema according to the [documentation](https://grafana.com/docs/loki/latest/operations/storage/schema/#changing-the-schema):

```yaml
schema_config:
  configs:
    - from: "2020-10-24"
      store: boltdb-shipper
      object_store: azure
      schema: v11
      index:
        prefix: index_
        period: 24h
    - from: "2022-07-11"
      store: boltdb-shipper
      object_store: azure
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  azure:
    account_key: <omitted>
    account_name: <omitted>
    container_name: loki
    request_timeout: 0

```

When I query logs from `2022-07-11` only or a range ending at `2022-07-10` everything works fine.
When I try to query logs spanning both schemas e.g. from `2022-07-10` to `2022-07-11` loki only returns the data from `2022-07-11`.

**To Reproduce**

1. Install loki `2.6.0` with helm chart `loki-2.13.1` 
2. Write logs across two schemas
3. Query range spanning both schemas via Grafanas Explore `https://<grafana-url>/api/datasources/proxy/<datasource id>/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bapp%3D%22app%22%7D&start=1657404000000000000&end=1657576799000000000&step=120)`
4. Query range only spanning first schema : `https://<grafana-url>/api/datasources/proxy/<data source id>/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bapp%3D%22app%22%7D&start=1657404000000000000&end=1657490399000000000&step=60`

**Expected behavior**

Logs from both schemas (here `2022-07-10` and `2022-07-11`) are returned when querying both days

**Environment:**
 - Kubernetes (AKS) `v1.23.5`
 - Deployment tool: helm

**Comment by torbjornvatn** [comment]
@sflandergan
did you find any solution for this? I have the same issue after updating Loki to the latest Helm chart.
I've tried migrating the logs using the migrate tool found [here](https://github.com/grafana/loki/tree/main/cmd/migrate) but that doesn't work either

**Comment by sflandergan** [comment]
@torbjornvatn no I did'nt.
The issue was not that critical for us since we don't keep our logs for very long time

**Comment by torbjornvatn** [comment]
@sflandergan I actually got this working today while upgrading to the newest loki helm chart.

Added a schema_config with the switch from v11 to v12 in the future and `loki_index_` as the prefix for the v12 logs.

```
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      structuredConfig:
        schema_config:
          configs:
            # Keep using the previous schema until 15/03/2023
            - from: "2000-01-01"
              store: boltdb-shipper
              object_store: filesystem
              schema: v11
              index:
                prefix: index_
                period: 24h
            # Adopt new schema on 15/03/2023
            - from: "2023-03-15"
              store: boltdb-shipper
              object_store: filesystem
              schema: v12
              index:
                prefix: loki_index_
                period: 24h
```

Then I copied all the files from the "old" chunks dir under /data/loki up one level to /data/chunks before going through the helm upgrade. 

Everything just magically works 🤯
