### ISSUE TITLE
Please update grafana requirement on the helm chart

### ISSUE THREAD

**Issue by Basster** [grafana/loki#672]
Please update the grafana requirement on the helm chart.
When trying to provide dashboard via values.yaml

```yaml
grafana:
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      traefik:
        gnetId: 4475
        revision: 4
        datasource: Prometheus
      kubernetes:
        gnetId: 315
        revision: 3
        datasource: Prometheus
```
grafana chart fails because of a bug fixed with https://github.com/helm/charts/pull/14441
