### ISSUE TITLE
loki-simple-scalable helm chart with Azure Storage Account

### ISSUE THREAD

**Issue by SDedik** [grafana/loki#6732]
Hello,
Pardon me if this is wrong place for such subject, but I figured this is best place of all.

Basically I am following official guidelines published at https://grafana.com/docs/loki/latest/installation/simple-scalable-helm/ to install Loki on AKS cluster in Azure and want to configure it to use Azure Storage Account.
The helm chart version I'm using is 1.8.0
I honestly got lost in how to configure the chart to make Loki use Azure Storage Account properly. The chart itself has not been modified in any way. All customizations I am providing via custom yaml file like so:
`helm template loki ./loki-simple-scalable -n monitoring -f ./my-values.yaml`

Following examples found in the https://grafana.com/docs/loki/latest/storage/ I configured schema_config and storage_config:
**my-values.yaml**
```
loki:
  schemaConfig:
    configs:
      - from: "2020-12-11"
        index:
          period: 24h
          prefix: index_
        object_store: azure
        schema: v11
        store: boltdb-shipper
  storage_config:
    azure:
      account_name: redacted
      account_key: redacted
      container_name: loki
      request_timeout: 0    
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h
      shared_store: azure
    filesystem:
      directory: /data/loki/chunks
```
The helm chart readme at https://github.com/grafana/helm-charts/tree/main/charts/loki-simple-scalable also claims that `loki.config.common.storage` section must be overwritten, but the chart's values.yaml file doesn't have that property anymore. Had it been removed? Setting `loki.storage` property to `null` breaks the helm chart and leaving it as-is results in following configMap being generated:
**loki-simple-scalable/templates/configmap.yaml**
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  labels:
    helm.sh/chart: loki-simple-scalable-1.8.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "2.6.1"
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    auth_enabled: true
    common:
      path_prefix: /var/loki
      replication_factor: 3
      storage:
        s3:
          bucketnames: chunks
          insecure: false
          s3forcepathstyle: false
    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
    memberlist:
      join_members:
      - loki-memberlist
    query_range:
      align_queries_with_step: true
    ruler:
      storage:
        s3:
          bucketnames: ruler
    schema_config:
      configs:
      - from: "2020-12-11"
        index:
          period: 24h
          prefix: index_
        object_store: azure
        schema: v11
        store: boltdb-shipper
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
    storage_config:
      azure:
        account_key: redacted
        account_name: redacted
        container_name: loki
        request_timeout: 0
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: azure
      filesystem:
        directory: /data/loki/chunks
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
```
The config looks suspicious because of all references to s3, but I guessed that schema_config and storage_config values will take precedence over it and tried to run it on Kubernetes. However, the pods failed with following error message:
`msg="error running loki" err="mkdir /data: read-only file system\nerror creating index client`
It refers to /data dir, but all entries where /data is encountered are taken from official example above, which makes me curious if the loki-simple-scalable helm chart supports Azure Storage Accounts at all.
If it does, could you please point me to the right direction and tell what I'm missing?
Thank you!

**Comment by SDedik** [comment]
I think I've found what I missed initially. The chart's readme file actually states that 'Volumes are mounted to /var/loki. The various directories Loki needs should be configured as subdirectories (e. g. /var/loki/index, /var/loki/cache).'
Changing paths from /data/... to /var/... solved the error and pods had started successfully
However, I'm still wondering if my approach is correct or I'm missing something fundamental?

**Comment by SDedik** [comment]
For those who might come across this in the future, what I end up doing is overwriting an entire Loki config.yaml file like so:

**my-values.yaml:**
```
loki:
  config: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      path_prefix: /var/loki
      
      storage:
        azure:
          account_key: ${AZURE_ACCOUNT_KEY}
          account_name: ${AZURE_ACCOUNT_NAME}
          container_name: loki

      ring:
        kvstore:
          store: memberlist

    compactor:
      working_directory: /var/loki/retention
      shared_store: azure
      retention_enabled: true

    limits_config:
      retention_period: 168h

    memberlist:
      join_members:
        - {{ include "loki.name" . }}-memberlist

    schema_config:
      configs:
      - from: "2020-12-11"
        index:
          period: 24h
          prefix: index_
        object_store: azure
        schema: v11
        store: boltdb-shipper

    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/boltdb-shipper-active
        cache_location: /var/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: azure

      filesystem:
        directory: /var/loki/chunks
```
This is the easiest solution to understand and to transfer over to a future helm chart versions. Especially if there will be some breaking changes around how config.yaml is generated by the chart.

**Comment by thisurawijesekera** [comment]
> For those who might come across this in the future, what I end up doing is overwriting an entire Loki config.yaml file like so:
> 
> **my-values.yaml:**
> 
> ```
> loki:
>   config: |
>     auth_enabled: false
> 
>     server:
>       http_listen_port: 3100
> 
>     common:
>       path_prefix: /var/loki
>       
>       storage:
>         azure:
>           account_key: ${AZURE_ACCOUNT_KEY}
>           account_name: ${AZURE_ACCOUNT_NAME}
>           container_name: loki
> 
>       ring:
>         kvstore:
>           store: memberlist
> 
>     compactor:
>       working_directory: /var/loki/retention
>       shared_store: azure
>       retention_enabled: true
> 
>     limits_config:
>       retention_period: 168h
> 
>     memberlist:
>       join_members:
>         - {{ include "loki.name" . }}-memberlist
> 
>     schema_config:
>       configs:
>       - from: "2020-12-11"
>         index:
>           period: 24h
>           prefix: index_
>         object_store: azure
>         schema: v11
>         store: boltdb-shipper
> 
>     storage_config:
>       boltdb_shipper:
>         active_index_directory: /var/loki/boltdb-shipper-active
>         cache_location: /var/loki/boltdb-shipper-cache
>         cache_ttl: 24h
>         shared_store: azure
> 
>       filesystem:
>         directory: /var/loki/chunks
> ```
> 
> This is the easiest solution to understand and to transfer over to a future helm chart versions. Especially if there will be some breaking changes around how config.yaml is generated by the chart.

But this will not accept logs from remote promtails @SDedik

**Comment by Surya-smart619** [comment]
@SDedik  Where did you configure AZURE_ACCOUNT_KEY and  AZURE_ACCOUNT_NAME?

**Comment by SDedik** [comment]
@Surya-smart619, I created a Kubernetes `Secret` object and then mapped it to environment variables via values file. I no longer work in that company and my records might already be outdated, but for the time being it looked like so. The secret name was `loki-azurestorageaccount`:
**values.yaml:**
```
read:
  # Current version of loki-simple-scalable helm chart doesn't include '-config.expand-env=true' option by default. To allow referencing
  # sensitive values in loki config from env vars, this option has to be enabled explicitly
  extraArgs:
    - -config.expand-env=true

  # Environment variables with Azure Storage Account details. Referenced in loki config
  extraEnv:
    - name: AZURE_ACCOUNT_KEY
      valueFrom:
        secretKeyRef:
          name: loki-azurestorageaccount
          key: azurestorageaccountkey
    - name: AZURE_ACCOUNT_NAME
      valueFrom:
        secretKeyRef:
          name: loki-azurestorageaccount
          key: azurestorageaccountname
```
And the same in the `write` section of the values.yaml file.

**Comment by lpborges** [comment]
If someone still have similar problems configuring the storage for Azure, I can't find documentation about it, and have to look how the values and helper works to configure the templates. Here is a example on how I was able to configure it:

```
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1

  storage:
    type: 'azure'

    # this are the containers names
    bucketNames:
      chunks: loki
      ruler: loki
      admin: loki

    azure:
      # use camelCase, not snake_case for the variables here
      # dont need to declare container here
      accountKey: ${STORAGE_ACCESS_KEY}
      accountName: lokistorageaccount
      requestTimeout: 0
      useManagedIdentity: false

  schema_config:
    configs:
    - from: "2023-08-08"
      store: boltdb-shipper
      object_store: azure
      schema: v11
      index:
        period: 24h
        prefix: index_

  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/data/loki/boltdb-shipper-active
      cache_location: /var/loki/data/loki/boltdb-shipper-cache
      cache_ttl: 24h
      shared_store: azure

  compactor:
    working_directory: /var/loki/data/retention
    shared_store: azure
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150

  limits_config:
    retention_period: 1h
 ```
