### ISSUE TITLE
Loki return inconsistent results for 2 same queries for the last 15 minutes

### ISSUE THREAD

**Issue by stephane-pham-shift** [grafana/loki#6744]
**Describe the bug**
Run "Run query" in the explore panel in Grafana for a given Loki datasource shows inconsistent results.
It returns logs with inconsistent order, the timestamp are not increasing but we're coming back in the past.

**To Reproduce**
1. Started Loki in Kubernetes with the official helm chart (https://github.com/grafana/helm-charts/tree/main/charts/loki) with one pod
2. Go to Grafana and make a random query(on the last 15 minutes) and it works fine
3. Add one pod for a total of 2 pods (2 replicas)
4. Go to Grafana and make a random query(on the last 15 minutes), Grafana returns a log with a timestamp T+0
5. Make the same random query(on the last 15 minutes), Grafana returns a log with a timestamp T+1
6. Make the same random query(on the last 15 minutes), Grafana returns a log with a timestamp T+0 or T-1
7. Make the same random query from last minute to last 15 minutes give same inconsistent  result.
8. Make the same random query on the timerange from last 15 minutes to more, it works properly. Only the logs for the last 15 minutes are inconsistent.

**Expected behavior**
I expect Grafana to return logs with a consistent order and the same result every time for any time range.

**Environment:**
 - Infrastructure: Kubernetes, helm chart (https://github.com/grafana/helm-charts/tree/main/charts/loki)
 - Storage: S3 bucket in Azure (storage account)
 - High available setup with usage of memberlist and multiple pods

**Screenshots, Promtail config, or terminal output**
```
loki: 
  image:
    repository: grafana/loki
    tag: 2.6.0
    pullPolicy: IfNotPresent

    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName

  ingress:
    enabled: false
    # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
    # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
    # ingressClassName: nginx
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  ## Affinity for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  # podAntiAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #   - labelSelector:
  #       matchExpressions:
  #       - key: app
  #         operator: In
  #         values:
  #         - loki
  #     topologyKey: "kubernetes.io/hostname"

  ## StatefulSet annotations
  annotations: {}

  # enable tracing for debug, need install jaeger and specify right jaeger_agent_host
  tracing:
    jaegerAgentHost:

  config:
    # existingSecret:
    target: all # run all the components of Loki
    auth_enabled: false
    ingester:
      chunk_idle_period: 10m # should not be smaller than index_cache_validity which is 5 minutes by default
      chunk_block_size: 262144
      chunk_retain_period: 1m
      max_transfer_retries: 0
      wal:
        dir: /data/loki/wal
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1 # we might need to revisit it to 3

        ## Different ring configs can be used. E.g. Consul
        # ring:
        #   store: consul
        #   replication_factor: 1
        #   consul:
        #     host: "consul:8500"
        #     prefix: ""
        #     http_client_timeout: "20s"
        #     consistent_reads: true
    query_range:
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_bytes: 1GB
            ttl: 24h
    frontend:
      compress_responses: true
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_entries_limit_per_query: 500000
      retention_period: 8759h
      max_global_streams_per_user: 500000
      max_streams_matchers_per_query: 500000
      split_queries_by_interval: 30m
      max_cache_freshness_per_query: 15m
    schema_config:
      configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: azure
        schema: v12
        index:
          prefix: index_
          period: 24h
    server:
      http_listen_port: 3100
      grpc_server_max_concurrent_streams: 50000
      grpc_server_max_recv_msg_size: 10000000
      grpc_server_max_send_msg_size: 10000000
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: azure
      azure: 
        account_name: "${AZURE_STORAGE_ACCOUNT_NAME}"
        container_name: "loki"
        account_key: "${AZURE_STORAGE_ACCOUNT_CONTAINER_KEY}"
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
    compactor:
      working_directory: /data/loki/boltdb-shipper-compactor
      shared_store: azure
  # Needed for Alerting: https://grafana.com/docs/loki/latest/rules/
  # This is just a simple example, for more details: https://grafana.com/docs/loki/latest/configuration/#ruler_config
  #  ruler:
  #    storage:
  #      type: local
  #      local:
  #        directory: /rules
  #    rule_path: /tmp/scratch
  #    alertmanager_url: http://alertmanager.svc.namespace:9093
  #    ring:
  #      kvstore:
  #        store: inmemory
  #    enable_api: true

  ## Additional Loki container arguments, e.g. log level (debug, info, warn, error)
  extraArgs:
    config.expand-env: "true"
    # log.level: debug

  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45

  ## ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
  networkPolicy:
    enabled: false

  ## The app name of loki clients
  client: {}
    # name:

  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  nodeSelector: {}

  ## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
  ## If you set enabled as "True", you need :
  ## - create a pv which above 10Gi and has same namespace with loki
  ## - keep storageClassName same with below setting
  persistence:
    enabled: false
    accessModes:
    - ReadWriteOnce
    size: 10Gi
    annotations: {}
    # selector:
    #   matchLabels:
    #     app.kubernetes.io/name: loki
    # subPath: ""
    # existingClaim:

  ## Pod Labels
  podLabels: 
    testlabel: test

  ## Pod Annotations
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "http-metrics"

  podManagementPolicy: OrderedReady

  ## Assign a PriorityClassName to pods if set
  # priorityClassName:

  rbac:
    create: true
    pspEnabled: false

  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45

  replicas: 1

  resources:
    requests:
      cpu: 1500m
      memory: 3Gi
    limits:
      cpu: 2500m
      memory: 3Gi

  securityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001

  service:
    type: ClusterIP
    nodePort:
    port: 3100
    annotations: {}
    labels: {}
    targetPort: http-metrics

  serviceAccount:
    create: true
    name:
    annotations: {}
    automountServiceAccountToken: true

  terminationGracePeriodSeconds: 4800

  ## Tolerations for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # The values to set in the PodDisruptionBudget spec
  # If not set then a PodDisruptionBudget will not be created
  podDisruptionBudget: {}
  # minAvailable: 1
  # maxUnavailable: 1

  updateStrategy:
    type: RollingUpdate

  serviceMonitor:
    enabled: false
    interval: ""
    additionalLabels: {}
    annotations: {}
    # scrapeTimeout: 10s
    # path: /metrics
    prometheusRule:
      enabled: false
      additionalLabels: {}
    #  namespace:
      rules: []
      #  Some examples from https://awesome-prometheus-alerts.grep.to/rules.html#loki
      #  - alert: LokiProcessTooManyRestarts
      #    expr: changes(process_start_time_seconds{job=~"loki"}[15m]) > 2
      #    for: 0m
      #    labels:
      #      severity: warning
      #    annotations:
      #      summary: Loki process too many restarts (instance {{ $labels.instance }})
      #      description: "A loki process had too many restarts (target {{ $labels.instance }})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      #  - alert: LokiRequestErrors
      #    expr: 100 * sum(rate(loki_request_duration_seconds_count{status_code=~"5.."}[1m])) by (namespace, job, route) / sum(rate(loki_request_duration_seconds_count[1m])) by (namespace, job, route) > 10
      #    for: 15m
      #    labels:
      #      severity: critical
      #    annotations:
      #      summary: Loki request errors (instance {{ $labels.instance }})
      #      description: "The {{ $labels.job }} and {{ $labels.route }} are experiencing errors\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      #  - alert: LokiRequestPanic
      #    expr: sum(increase(loki_panic_total[10m])) by (namespace, job) > 0
      #    for: 5m
      #    labels:
      #      severity: critical
      #    annotations:
      #      summary: Loki request panic (instance {{ $labels.instance }})
      #      description: "The {{ $labels.job }} is experiencing {{ printf \"%.2f\" $value }}% increase of panics\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      #  - alert: LokiRequestLatency
      #    expr: (histogram_quantile(0.99, sum(rate(loki_request_duration_seconds_bucket{route!~"(?i).*tail.*"}[5m])) by (le)))  > 1
      #    for: 5m
      #    labels:
      #      severity: critical
      #    annotations:
      #      summary: Loki request latency (instance {{ $labels.instance }})
      #      description: "The {{ $labels.job }} {{ $labels.route }} is experiencing {{ printf \"%.2f\" $value }}s 99th percentile latency\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"


  initContainers: []
  ## Init containers to be added to the loki pod.
  # - name: my-init-container
  #   image: busybox:latest
  #   command: ['sh', '-c', 'echo hello']

  extraContainers: []
  ## Additional containers to be added to the loki pod.
  # - name: reverse-proxy
  #   image: angelbarrera92/basic-auth-reverse-proxy:dev
  #   args:
  #     - "serve"
  #     - "--upstream=http://localhost:3100"
  #     - "--auth-config=/etc/reverse-proxy-conf/authn.yaml"
  #   ports:
  #     - name: http
  #       containerPort: 11811
  #       protocol: TCP
  #   volumeMounts:
  #     - name: reverse-proxy-auth-config
  #       mountPath: /etc/reverse-proxy-conf


  extraVolumes: []
  ## Additional volumes to the loki pod.
  # - name: reverse-proxy-auth-config
  #   secret:
  #     secretName: reverse-proxy-auth-config

  ## Extra volume mounts that will be added to the loki container
  extraVolumeMounts: []

  extraPorts: []
  ## Additional ports to the loki services. Useful to expose extra container ports.
  # - port: 11811
  #   protocol: TCP
  #   name: http
  #   targetPort: http

  # Extra env variables to pass to the loki container
  env: 
  - name: AZURE_STORAGE_ACCOUNT_NAME
    valueFrom:
      secretKeyRef:
        name: monitoring-azure-storage-account-auth
        key: AZURE_STORAGE_ACCOUNT_NAME
  - name: AZURE_STORAGE_ACCOUNT_CONTAINER_KEY
    valueFrom:
      secretKeyRef:
        name: monitoring-azure-storage-account-auth
        key: AZURE_STORAGE_ACCOUNT_CONTAINER_KEY

  # Specify Loki Alerting rules based on this documentation: https://grafana.com/docs/loki/latest/rules/
  # When specified, you also need to add a ruler config section above. An example is shown in the alerting docs.
  alerting_groups: []
  #  - name: example
  #    rules:
  #    - alert: HighThroughputLogStreams
  #      expr: sum by(container) (rate({job=~"loki-dev/.*"}[1m])) > 1000
  #      for: 2m

  useExistingAlertingGroup:
    enabled: false
    configmapName: ""`
```

**Comment by oguzhancelikarslan** [comment]
having the same problem, did you find any solution for this? @stephane-pham-shift

**Comment by stephane-pham-shift** [comment]
yes, was the inmemory which was wrong, instead use the memberlist in lifecycler.ring.kvstore.store

hope it helps

**Comment by oguzhancelikarslan** [comment]
Have 3 pods. 
@stephane-pham-shift I already did but still getting the same problem. 


```
 ingester:
    chunk_idle_period: 3m
    chunk_block_size: 262144
    chunk_retain_period: 1m
    max_transfer_retries: 0

    wal:
      dir: /data/loki/wal

    lifecycler:
      ring:
        kvstore:
          store: memberlist
        replication_factor: 1

      final_sleep: 0s

```

thanks for the answer.
