### ISSUE TITLE
Promtail: syslog job over UDP is not working

### ISSUE THREAD

**Issue by xtavras** [grafana/loki#6772]
**Describe the bug**
Promtail will not deliver "Syslog UDP" logs to Loki, but "Syslog TCP" logs works fine.

**To Reproduce**
1. Enable "**udp**" as "**listen_protocol**" option for syslog config, e.g.
```
    syslog:
      idle_timeout: 60s
      listen_protocol: udp
      label_structured_data: true
      labels:
        job: syslog
      listen_address: 0.0.0.0:514

```
Try to send some logs using UDP, I've used this example or real hardware switches which only support UDP syslog
https://gist.github.com/xtavras/4a01f7d1f94237a4abcdfb02074453c1

I can see in tcpdump that logs are coming to promtail machine, but nothing in Loki. I've tried to run promtail with debug option but don't see any additional errors.
2. Enable "**tcp**" as "**listen_protocol**" (it's default), e.g.
```
    syslog:
      idle_timeout: 60s
      listen_protocol: tcp
      label_structured_data: true
      labels:
        job: syslog
      listen_address: 0.0.0.0:514
```
Send logs using tcp, I've used this example
https://gist.github.com/xtavras/be13760713e2a9ee1a8bdae2ed6d2565

Logs are visible in tcpdump and are coming and visible in Loki.

**Expected behavior**
Logs sent to UDP syslogs should be delivered to Loki same way as TCP syslogs

**Environment:**
 - Loki: 2.5.0
 - Promtail: 2.6.1

**Screenshots, Promtail config, or terminal output**
Promtail config

```
server:
  http_listen_port: 9080


positions:
  filename: /var/lib/promtail/positions.yml


clients:
  - basic_auth:
      password: xxxxxxxxxxxxxxxx
      username: loki
    tenant_id: 1
    url: https://loki.example.com/api/prom/push


scrape_configs:
  - file_sd_configs:
    - files:
      - /etc/promtail/file_sd/*.yml
      - /etc/promtail/file_sd/*.yaml
      - /etc/promtail/file_sd/*.json
    job_name: file_sd

  - job_name: syslog-logs
    relabel_configs:
    - source_labels:
      - __syslog_message_hostname
      target_label: host
    syslog:
      idle_timeout: 60s
      listen_protocol: udp
      label_structured_data: true
      labels:
        job: syslog
      listen_address: 0.0.0.0:514
```

**Comment by jsalatiel** [comment]
@xtavras How are you installing loki and promtail?
One thing I noticed is that if I install using grafana/loki-stack chart the service will be created as tcp despite the       listen_protocol: udp

**Comment by xtavras** [comment]
@jsalatiel 
I'm using this Helm chart for Loki https://github.com/grafana/helm-charts/tree/main/charts/loki-simple-scalable

**Comment by jsalatiel** [comment]
Can you check if the  kubernetes service has been created with TCP or UDP?

**Comment by xtavras** [comment]
@jsalatiel what service do you mean? Isn't Promtail communicate with Loki just with HTTP calls, so they are always TCP?

**Comment by xtavras** [comment]
Sorry if I was not clear, promtail is running on VM just as binary, so no Docker or Kubernetes, only Loki itself is running on Kubernetes. And I see that port is `udp`  locally on VM, if change it to tcp in config, it will be `tcp` in netstat output as well, so it looks good to me tbh.

**Comment by jsalatiel** [comment]
If there's nothing listening on UDP thats the reason you can not send udp messages =)

**Comment by xtavras** [comment]
But it is listening on UDP, I already posted my netstat ouput. Promtail send data to Loki always using HTTP/HTTPS so not sure why UDP is expected on Loki side, correct me if I'm wrong.

**Comment by xtavras** [comment]
@saibug yes, our switches (Huawei) only support UDP on port 514, like I've said I see it in tcpdump in cleartext on promtail machine.

**Comment by xtavras** [comment]
Here is tcpdump examle as you see protocoll is UDP, first is test script, second is real log from switch

```
netmon:~# tcpdump -i any port 514 -vvv
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes


11:17:15.427290 IP (tos 0x0, ttl 63, id 22762, offset 0, flags [DF], proto UDP (17), length 112)
    10.1.176.55.37603 > 10.1.1.68.syslog: [udp sum ok] SYSLOG, length: 84
	Facility user (1), Severity warning (4)
	Msg: 1 2022-08-05T11:17:15.423205+02:00 t14 promtail 291547 1 - \0xef\0xbb\0xbfthis is a UDP test
	0x0000:  3c31 323e 3120 3230 3232 2d30 382d 3035
	0x0010:  5431 313a 3137 3a31 352e 3432 3332 3035
	0x0020:  2b30 323a 3030 2074 3134 2070 726f 6d74
	0x0030:  6169 6c20 3239 3135 3437 2031 202d 20ef
	0x0040:  bbbf 7468 6973 2069 7320 6120 5544 5020
	0x0050:  7465 7374
11:21:02.296315 IP (tos 0x0, ttl 254, id 51272, offset 0, flags [none], proto UDP (17), length 205)
    10.1.250.168.38514 > 10.1.1.68.syslog: [udp sum ok] SYSLOG, length: 177
	Facility local7 (23), Severity info (6)
	Msg: Aug  5 2022 09:27:44 ds28-293L.example.com %%01INFO/6/SUPPRESS_LOG(l)[43605]:Last message repeated 5 times.(InfoID=1092489232, ModuleName=MSTP, InfoAlias=RECEIVE_MSTITC)
	0x0000:  3c31 3930 3e41 7567 2020 3520 3230 3232
	0x0010:  2030 393a 3237 3a34 3420 6473 3238 2d32
	0x0020:  3933 4c2e 6265 726c 696e 2e6e 692e 7465
	0x0030:  616d 2025 2530 3149 4e46 4f2f 362f 5355
	0x0040:  5050 5245 5353 5f4c 4f47 286c 295b 3433
```

**Comment by corpix** [comment]
Same thing for me. I have Unifi EdgeSwitch which supports only UDP.

Promtail configuration:

```yaml
scrape_configs:
  # ...
  - job_name: syslog
    relabel_configs:
      - source_labels:
          - __syslog_message_hostname
        target_label: host
    syslog:
      idle_timeout: 60s
      label_structured_data: true
      labels:
        cluster: lab
        job: syslog
      listen_address: 0.0.0.0:514
      listen_protocol: udp
```

Started via systemd (on NixOS) on 514/udp.
Attaching traffic dump

[514.cap.zip](https://github.com/grafana/loki/files/9286444/514.cap.zip)
