### ISSUE TITLE
msg="failed to flush user" err="store put chunk: timeout"

### ISSUE THREAD

**Issue by doc-lb** [grafana/loki#6822]
Hello! My logs in grafana looks ok, but i have many errors from loki-cluster logs:

```
loki-cluster-loki-write-3     | level=error ts=2022-08-01T15:55:30.643700569Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: timeout"
loki-cluster-loki-write-2     | level=error ts=2022-08-01T15:55:31.315836361Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: timeout"
loki-cluster-loki-write-3     | level=error ts=2022-08-01T15:55:35.604861138Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: timeout"
```

Loki version: 2.6.1

Loki config:
```
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: error

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules

memberlist:
  join_members: ["loki-read", "loki-write"]
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  bind_addr: ['0.0.0.0']
  bind_port: 7946
  gossip_interval: 2s

ingester:
  lifecycler:
    join_after: 10s
    observe_period: 5s
    ring:
      replication_factor: 3
      kvstore:
        store: memberlist
    final_sleep: 0s
  chunk_idle_period: 30m
  wal:
    enabled: true
    dir: /loki/wal
  max_chunk_age: 1h
  chunk_retain_period: 30s
  chunk_encoding: snappy
  chunk_target_size: 1.572864e+06
  chunk_block_size: 262144

schema_config:
  configs:
  - from: 2020-08-01
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

limits_config:
  max_cache_freshness_per_query: '10m'
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 30m
  ingestion_rate_mb: 40
  ingestion_burst_size_mb: 40
  split_queries_by_interval: 15m
  retention_period: 14d

query_range:
  # make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 5
  parallelise_shardable_queries: false
  cache_results: true

  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_bytes: "1GB"
        max_size_items: 1024
        validity: 24h

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  max_outstanding_per_tenant: 2048

querier:
  query_ingesters_within: 2h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
```
What i'am doing wrong?

**Comment by dannykopping** [comment]
Hey @doc-lb

Please use the issue template as this information is really important:

**To Reproduce**
Steps to reproduce the behavior:
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

---

I also want to know if you're running multiple ingesters using the same filesystem for storage?

**Comment by doc-lb** [comment]
> Hey @doc-lb
> 
> Please use the issue template as this information is really important:
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Started Loki (SHA or version)
> 2. Started Promtail (SHA or version) to tail '...'
> 3. Query: `{} term`
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Environment:**
> 
> * Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
> * Deployment tool: [e.g., helm, jsonnet]
> 
> **Screenshots, Promtail config, or terminal output** If applicable, add any output to help explain your problem.
> 
> I also want to know if you're running multiple ingesters using the same filesystem for storage?

To Reproduce 
Steps to reproduce the behavior:

1. Started Loki 2.6.1
2. Started Promtail 2.4.1
3. No query

Expected behavior
Loki cluster running without errors

Environment:

- Infrastructure: VM with docker
- Deployment tool: ansible

docker-compose.yml:
```
version: "3.8"
services:

  loki-gateway:
    image: nginx:1.19
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3180:80"
      - "3100"

  loki-frontend:
    image: grafana/loki:2.6.1
    volumes:
        - ./config:/etc/loki/
        - ./data:/loki
    ports:
        - "3100"
    command: "-config.file=/etc/loki/loki.yml -target=query-frontend -frontend.downstream-url=http://loki-read:3100"
    deploy:
      mode: replicated
      replicas: 2

  loki-read:
    image: grafana/loki:2.6.1
    volumes:
      - ./config:/etc/loki/
      - ./data:/loki
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/loki.yml -target=read"
    restart: always
    deploy:
      mode: replicated
      replicas: 3

  loki-write:
    image: grafana/loki:2.6.1
    volumes:
      - ./config:/etc/loki/
      - ./data:/loki
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/loki.yml -target=write"
    restart: always
    deploy:
      mode: replicated
      replicas: 3


```
