### ISSUE TITLE
Why not let loki show some sort of logs by default?!?

### ISSUE THREAD

**Issue by encryptblockr** [grafana/loki#6839]
Issue with loki is by default it shows nothing
This causes hours of people trying to figure out what is going on

 Videos i see have `log browser` but i am using newer grafana and i do not see `log browser`

here is what i see and i have zero idea what to do or where to go

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/35294766/182907088-46b51f15-c150-4b72-b239-6e2ecea152a4.png">

when i added loki as datasource it says `labels found`
so where are the labels found?

<img width="427" alt="image" src="https://user-images.githubusercontent.com/35294766/182907228-3a4b684c-02cc-4ba4-ae7b-3d7ef5d7f2ac.png">

grafana version: grafana/grafana:9.0.6-ubuntu
loki version: grafana/loki:2.3.0 (did not use latest because it says no labels found when adding as datasource)

**Comment by encryptblockr** [comment]
I have containers pushing logs to loki from docker-compose file like below

```
services:
  hello-world:
    image: test/hello-world
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    ...
```

so how do i have loki show logs or find any logs?
