### ISSUE TITLE
Promtail - Unable to connect to kafka broker in Confluent Cloud

### ISSUE THREAD

**Issue by bluedog13** [grafana/loki#6847]
I am running into the below error when trying to connect to a Kafka cluster/topic in Confluent Cloud using Promtail

```
level=error ts=2022-08-05T23:20:02.398245259Z caller=main.go:117 msg="error creating promtail" error="failed to make kafka target manager: error creating kafka client: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)"
```

Below is my scrape config in Promtail.
```
- job_name: kafka
  kafka:
    brokers:
    - [redacted].confluent.cloud:9092
    - https://[redacted].confluent.cloud:443
    topics:
    - [redacted]
    group_id: kafka-promtail-cg
    authentication: 
      type: sasl
      sasl_config:
        mechanism: PLAIN
        user: [redacted]
        password: [redacted]
    labels:
      job: kafka
```

Has anybody run into similar issues before or have been able to use Promtail to read data from a Kafka topic hosted in Confluent Cloud?  Is the above scrape config for Kafka correct?

Thanks.
