### ISSUE TITLE
Add syntex check flag to Promtail command line

### ISSUE THREAD

**Issue by m1keil** [grafana/loki#6862]
**Is your feature request related to a problem? Please describe.**
Promtail doesn't support config reload. Instead, it's required that each config change is followed by a service restart. 
This means that a faulty configuration will block Promtail from starting again until problem is fixed. This make config deploys a bit more risky and involved since even minor mistakes can cause issues.

**Describe the solution you'd like**
Add `-check-syntax` flag that returns 0 if config file syntax is OK, or 1 if errors detected.
This can allow pre-flight checks in systemd's services via something like `ExecCondition` or similar.

**Describe alternatives you've considered**
The closest thing is the `-dry-run` flag which does syntax validation. However, the problem with it is that it keeps running in the foreground. It will also exit with an error if another promtail is already running due to port in use error.

**Comment by DarthBenro008** [comment]
Hi @m1keil ,

Just to confirm, the syntax check pertains only to unmarshling the YAML file, right?

An example invalid file:
```yaml
server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

  client3: # the syntax error
  url: http://localhost:3100/loki/api/v1/push

scrape_configs:
    - job_name: system
      pipeline_stages:
      static_configs:
      - targets:
         - localhost
        labels:
         job: varlogs
         host: ward_workstation
         agent: promtail
         __path__: /var/log/*.log
```

Running `promtail -config.file=config.yaml -check-syntax` should yield a `1` as a result in the terminal?

If yes, i'd be happy to send add this feature and send a PR for the same! :D
