### ISSUE TITLE
Promtail fails to fetch logs from Docker container from remote Docker daemon docker_sd_config with https URL

### ISSUE THREAD

**Issue by longsleep** [grafana/loki#6894]
**Describe the bug**
Promtail `scrape_configs` contains this section:
```yaml
  - job_name: docker_https
    docker_sd_configs:
      - host: https://test2.lxd:2375
        refresh_interval: 5s
        tls_config:
          ca_file: /srv/tls/local-ca_bundle.crt
          cert_file: /srv/tls/certs/docker-client.crt
          key_file: /srv/tls/certs/docker-client.key
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
```

This seems to fetch the containers just fine, but then promtail fails to actually load the log files for the containers.

```
Aug 12 15:39:17 munich promtail[2367033]: level=error ts=2022-08-12T13:39:17.138495308Z caller=target.go:101 target=docker/3a7283bdee7c31eb890bb2cf9599378cdf4ee9cee2eb609f272c0825ad3274e7 msg="could not fetch logs for container" container=3a7283bdee7c31eb890bb2cf9599378cdf4ee9cee2eb609f272c0825ad3274e7 err="Error response from daemon: Client sent an HTTP request to an HTTPS server."
```

**To Reproduce**
1. Configure Promptail to scape using `docker_sd_configs` with a `https` host (remote Docker daemon).
2. I use the Promtail binary build
```
promtail, version 2.6.1 (branch: HEAD, revision: 6bd05c9a4)
  build user:       root@af90ed01061f
  build date:       2022-07-18T08:41:09Z
  go version:       go1.17.6
  platform:         linux/amd64
```
3. After startup, promtail directly starts logging errors like in the example above.

**Expected behavior**
Promtail should load the logs from remote https Docker daemon just fine.

**Environment:**
 - Infrastructure: bare-metal
