### ISSUE TITLE
Promtail fatal error on shutdown

### ISSUE THREAD

**Issue by chodges15** [grafana/loki#6896]
**Describe the bug**
Low level, fatal error from promtail that occurred during a shutdown (SIGTERM sent to process)

```
{"error":"failed to cleanly stop promtail-linux-amd64
signal: terminated
ORIGINAL STACK TRACE:
binutil.go:47 +0x19b4093
main.main
   go/src/loki/cmd/promtail/promtail.go:207 +0x19c45fc
   runtime.main
     /usr/local/go/src/runtime/proc.go:250 +0x4391b1
   runtime.goexit
      /usr/local/go/src/runtime/asm_amd64.s:1571 +0x466860
","level":"fatal","msg":"Encountered an error while running promtail","time":"2022-08-12T13:31:43Z"}
```

**To Reproduce**
1. Intermittent on promtail instances that are using file based service discovery

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: custom
 - Promtail: 
 ```
promtail, version main-d6f50ca (branch: main, revision: d6f50ca5e)
  build user:       root@4c4d203c7175
  build date:       2022-06-16T15:44:00Z
  go version:       go1.17.9
  platform:         linux/amd64
```

**Screenshots, Promtail config, or terminal output**
Selected portions of promtail config (x indicates redacted info)
```
server:
  http_listen_port: xxxx
  http_listen_address: 127.0.0.1
  grpc_listen_port: xxxx
  grpc_listen_address: 127.0.0.1

positions:
  filename: /tmp/promtail_positions.yaml

options:
  stream_lag_labels: service

clients:
  - url: https://distributor:xxxx/loki/api/v1/push
    tenant_id: "loki_log_overflow"

    tls_config:
      ca_file: /tmp/ca-cert.pem
      cert_file: /tmp/cert.pem
      key_file: /tmp/key.pem
      server_name: xxx
      insecure_skip_verify: false

    external_labels:
      service: "loki_log_overflow"

    backoff_config:
      max_retries: 10

scrape_configs:

  - job_name: services
    file_sd_configs:
      - files:
          - /tmp/discovered_targets.json
        refresh_interval: 1m

    pipeline_stages:
      - match:
          selector: '{service=~".+"}'
          stages:
            - tenant:
                 label: "service"
....
      - drop:
          older_than: 10m
          drop_counter_reason: too_old

      - drop:
          source: service
          value: abusive_service_name
          drop_counter_reason: "drop_label_value"

      - limit:
          rate: 7500
          burst: 15000
          drop: true
```
