### ISSUE TITLE
runtime: program exceeds 10000-thread limit | fatal error: thread exhaustion

### ISSUE THREAD

**Issue by HadarSha** [grafana/loki#6902]
**Describe the bug**
When trying to ship a large amount of logs (over 60,000) from a single instance of promtail, the process dies with the following error:

```
runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion
```

**To Reproduce**
1. Started Loki (v2.6.0)
2. Started Promtail (v2.6.0) to tail a shared mounted volume containing over 60,000 log files
3. After roughly 30 minutes of uptime, the process terminates with the aforementioned error. Some logs are shipped, some are not, I assume due to limited capacity of the single promtail instance.

**Expected behavior**
promtail should be able to throttle upon reaching this limit, or perhaps allow horizontal scaling of sorts to distribute the load upon multiple instances

**Environment:**
 - Kubernetes (promtail as a pod within a cluster containing an Apache Airflow deployment)
 - Deployment tool: helm

**Promtail config**

```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://<our_loki_instance>/loki/api/v1/push
    batchwait: 1s
    batchsize: 102400

positions:
  filename: /promtail/positions.yaml

scrape_configs:
  - job_name: airflow_task_logs
    ec2_sd_configs:
      - role_arn: <our_role_arn>
    pipeline_stages:
      - multiline:
          firstline: '^\[[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]\,[0-9]{3}\]'
      - regex:
          expression: '^(?P<timestamp>\[[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]:[0-5][0-9]\,[0-9]{3}\]) (?P<message>(?s:.*))$'
      - timestamp:
          source: timestamp
          format: '[2006-01-02 15:04:05,999]'
          action_on_failure: skip
      - regex:
          source: filename
          expression: '\/opt\/airflow\/logs\/dag_id\=(?P<airflow_dag_id>.+?)\/run_id\=(?P<airflow_run_id>.+?)\/task_id\=(?P<airflow_task_id>.+?)\/(?:map_index\=(?P<airflow_map_index>\d+)\/)?attempt\=(?P<airflow_try_number>\d+).log'
      - labels:
          airflow_dag_id:
          airflow_run_id:
          airflow_task_id:
          airflow_try_number:
    relabel_configs:
      - action: replace
        replacement: /opt/airflow/logs/dag_id*/**/*.log
        target_label: __path__
      - action: replace
        replacement: airflow_dags
        target_label: job

limits_config:
  readline_rate_enabled: true
  readline_rate: 9000
  readline_burst: 9000
  readline_rate_drop: false
```

**Screenshots, or terminal output**
![image](https://user-images.githubusercontent.com/64405961/184428369-7ff7f555-7d06-430d-9898-bcdb2e68d8ec.png)
