### ISSUE TITLE
promtail docker_sd_configs can't discovery any container(0/0 ready)

### ISSUE THREAD

**Issue by DesistDaydream** [grafana/loki#6904]
**Describe the bug**
promtail docker_sd_configs can't discovery any container(0/0 ready)

**To Reproduce**
1. Started loki:2.6.1
2. Started promtail:2.6.1 to tail Docker daemon

**Expected behavior**
promtail should discover the container correctly

**Environment:**
 - Infrastructure: docker:20.10.9

**Screenshots, Promtail config, or terminal output**
promtail config.yaml
```yaml
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: [flog]
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "/(.*)"
        target_label: "container"
```
![image](https://user-images.githubusercontent.com/39847025/184503550-7fdc9751-f7d5-47ec-b0a9-22f5ea7d4d71.png)

promtail has no error output, just can't discover any containers
