### ISSUE TITLE
Cannot use date with partial information e.g. from syslog default timestamp format

### ISSUE THREAD

**Issue by odormond** [grafana/loki#692]
**Describe the bug**
Trying to ingest lines from syslog is impossible because the default timestamp format does not include the year which leads to parsed timestamps having a year set to 0 which in-turn fails to get encoded because the date is before `0001-01-01`.

**To Reproduce**
1. Start promtail (commit b389e44), on Ubuntu 16.04 with default rsyslog config, with debug log and this config:
```yaml
client:                                      
    url: http://localhost:3100/api/prom/push
                                                           
positions:         
  filename: /tmp/positions.yaml
                                                           
scrape_configs:
  - job_name: system  
    pipeline_stages:             
      - regex:                 
          expression: "^(?s)(?P<time>.+? \\d\\d:\\d\\d:\\d\\d):? (?P<content>.*)$"                                     
      - timestamp:
          source: time  
          format: "Jan _2 15:04:05"
      - output:
          source: content
    static_configs:
      - targets:
        - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

server:
  http_listen_port: 9080
  grpc_listen_port: 0
```
2. Watch the output and you'll see things like:
```
level=debug ts=2019-06-21T06:14:01.514582778Z caller=pipeline.go:81 component=pipeline component=pipeline msg="processing pipeline" stage=0 labels="{filename=\"/var/log/auth.log\", job=\"varlogs\"}" time=2019-06-21T08:14:01.514519781+02:00
 entry="Jun 21 08:05:01 DES-CH-101-LIN CRON[11233]: pam_unix(cron:session): session closed for user root"          
level=debug ts=2019-06-21T06:14:01.514613787Z caller=pipeline.go:81 component=pipeline component=pipeline msg="processing pipeline" stage=1 labels="{filename=\"/var/log/auth.log\", job=\"varlogs\"}" time=2019-06-21T08:14:01.514519781+02:00
 entry="Jun 21 08:05:01 DES-CH-101-LIN CRON[11233]: pam_unix(cron:session): session closed for user root"            
level=debug ts=2019-06-21T06:14:01.514639978Z caller=pipeline.go:81 component=pipeline component=pipeline msg="processing pipeline" stage=2 labels="{filename=\"/var/log/auth.log\", job=\"varlogs\"}" time=0000-06-21T08:05:01Z entry="Jun 21 
08:05:01 DES-CH-101-LIN CRON[11233]: pam_unix(cron:session): session closed for user root"                       
level=debug ts=2019-06-21T06:14:01.514664562Z caller=pipeline.go:85 component=pipeline component=pipeline msg="finished processing log line" labels="{filename=\"/var/log/auth.log\", job=\"varlogs\"}" time=0000-06-21T08:05:01Z entry="DES-CH
-101-LIN CRON[11233]: pam_unix(cron:session): session closed for user root" duration_s=8.1854e-05                 
level=error ts=2019-06-21T06:14:02.517150377Z caller=client.go:156 component=client host=localhost:3100 msg="error encoding batch" error="timestamp: &types.Timestamp{Seconds: -62152379998,\nNanos: 0,\n} before 0001-01-01"
```

**Expected behavior**
No error logged and a parsed time using the current year instead of 0000

**Environment:**
 - Infrastructure: bare-metal
 - Deployment tool: manual
 - OS: Ubuntu 16.04.6 LTS
