### ISSUE TITLE
promtail: panic when fetching target Details

### ISSUE THREAD

**Issue by tpaschalis** [grafana/loki#6930]
**Describe the bug**
Calling the Details() method of a target that has a nil error results in a panic.

https://github.com/grafana/loki/blob/2911a74175444294b94496a8645acdbffdf6329a/clients/pkg/promtail/targets/docker/target.go#L252-L256

```
goroutine 2580 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x3f48720, 0x7666310})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5.1()
	/go/pkg/mod/github.com/opentracing-contrib/go-stdlib@v1.0.0/nethttp/server.go:150 +0x139
panic({0x3f48720, 0x7666310})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/grafana/loki/clients/pkg/promtail/targets/docker.(*Target).Details(0xc000c91340)
	/go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20220411060007-0315102c34cf/clients/pkg/promtail/targets/docker/target.go:238 +0xa5
github.com/grafana/agent/pkg/logs.listTargetsHandler.func1({0x52bdb88, 0xc000477c20}, 0xc000739c70?)
	/drone/src/pkg/logs/http.go:59 +0x2cf
net/http.HandlerFunc.ServeHTTP(0xc000477d10?, {0x52bdb88?, 0xc000477c20?}, 0xc?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/grafana/agent/pkg/logs.(*Logs).ListTargetsHandler(0x3bd4540?, {0x52bdb88, 0xc000477c20}, 0xc000ea9360?)
	/drone/src/pkg/logs/http.go:43 +0x154
```

**To Reproduce**
We witnessed this behavior in the Agent code, when trying to list the status of Logs targets fetched from the Docker SD mechanism, but the same seems to be true for most implementations of the Detail() method. As far as I can tell with a quick search, the Details method is only used for logging, which might be why it hasn't been reported before

Call the Details() method on a target that hasn't errored out.

**Expected behavior**
The Details() method should return an empty error or a nil value.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
For completeness' sake, here's the job definition used under Promtail's scrape_configs.
```yaml
      - job_name: integrations/docker
        docker_sd_configs:
          - host: unix:///var/run/docker.sock
            refresh_interval: 5s
        relabel_configs:
          - action: replace
            replacement: integrations/docker
            source_labels:
              - __meta_docker_container_id
            target_label: job
          - source_labels:
              - __meta_docker_container_name
            regex: '/(.*)'
            target_label: container
          - source_labels:
            - __meta_docker_container_log_stream
            target_label: stream
```
