### ISSUE TITLE
LokiOperator to support the ca_file to connect to my s3 storage

### ISSUE THREAD

**Issue by computate** [grafana/loki#6932]
**Is your feature request related to a problem? Please describe.**
I am struggling to configure the LokiOperator to support the ca_file to connect to my s3 storage, and other lokistack-config configmap options of the LokiOperator. I have setup an s3 bucket, but when Loki distributor and other pods try to reach the s3 storage, it fails because it is an https endpoint and the LokiOperator does not support configuring the ca_file, only s3, bucketnames, access_key_id, secret_access_key. See here: 

https://github.com/grafana/loki/blob/main/operator/internal/manifests/internal/config/loki-config.yaml#L21-L29

```yaml
common:
  storage:
    {{ with .ObjectStorage.S3 }}
    s3:
      s3: {{ .Endpoint }}
      bucketnames: {{ .Buckets }}
      region: {{ .Region }}
      access_key_id: {{ .AccessKeyID }}
      secret_access_key: {{ .AccessKeySecret }}
      s3forcepathstyle: true
    {{ end }}
```

**Describe the solution you'd like**

I would like the LokiOperator to allow me to setup a ca_file for connecting to an OpenShift Data Foundation S3 storage bucket like this: 

```yaml
                http_config:
                  ca_file: "/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
```

There are other parts of the lokistack-config configmap that would be nice to customize as well as part of the operator, like: 

```yaml
          ingester:
            max_chunk_age: 2h
          limits_config:
            ingestion_rate_mb: 4
            ingestion_burst_size_mb: 6
            reject_old_samples: true
            reject_old_samples_max_age: 168h
            per_stream_rate_limit: 3MB
            per_stream_rate_limit_burst: 15MB
            multi_tenant_queries_enabled: true
          server:
            log_level: info
```

**Describe alternatives you've considered**
I have been able to use the LokiOperator, but I had to set the nodeSelector of many of the deployments and statefulsets to a node that doesn't exist `nodeSelector: { name: none }` and create custom deployments and statefulsets in the same OpenShift project to replace them. Not even setting `replicas: 0` worked, I had to change the nodeSelector to a node name that doesn't exist. See below: 

```yaml
apiVersion: loki.grafana.com/v1beta1
kind: LokiStack
metadata:
  name: lokistack
  namespace: openshift-operators-redhat
spec:
  managementState: Managed
  storage:
    secret:
      name: thanos-object-storage
      type: s3
  template:
    compactor:
      replicas: 0
      nodeSelector:
        name: none
    distributor:
      replicas: 0
      nodeSelector:
        name: none
    gateway:
      replicas: 1
    indexGateway:
      replicas: 0
      nodeSelector:
        name: none
    ingester:
      replicas: 0
      nodeSelector:
        name: none
    querier:
      replicas: 0
      nodeSelector:
        name: none
    queryFrontend:
      replicas: 0
      nodeSelector:
        name: none
  tenants:
    mode: openshift-logging
  size: 1x.extra-small
  storageClassName: ocs-external-storagecluster-ceph-rbd
```

Then I configured a new "lokistack-config-custom" that setup the s3 storage pointed to the ca_file as desired. I setup separate lokistack-distributor-custom, lokistack-gateway-custom, lokistack-querier-custom, lokistack-query-frontend-custom deployments and separate lokistack-compactor-custom, lokistack-index-gateway-custom, lokistack-ingester-custom statefulsets that were mostly copies of the originals but pointed to the lokistack-config-custom configmap instead. 

**Additional context**
Is it already possible to configure the Loki Operator to support these configuration changes like ca_file, or can this be a new feature added, please?

**Comment by periklis** [comment]
@computate Following the Object storage spec in the LokiStack CRD you will notice a separate section for a TLS spec that enables configuration for the custom CA file:

https://loki-operator.dev/docs/api.md/#objectstoragespec

**Comment by computate** [comment]
Thanks @periklis , I think that helps me get around the custom CA file problem. Now that I have applied those changes, I ran into another problem. I have setup a ClusterLogForwarder that was working before, based on these docs: 

https://loki-operator.dev/docs/forwarding_logs_to_gateway.md/

But now it is failing in the collector pods to send to the gateway with this error: 

```
2022-08-23 04:56:48 +0000 [warn]: [loki_audit] failed to write post to https://lokistack-gateway-http.openshift-operators-redhat.svc.cluster.local:8080/api/logs/v1/audit/loki/api/v1/push (302 Found {"error":"failed to find token","errorType":"observatorium-api","status":"error"}
```

The ClusterLogForwarder was working last week, but today after applying the suggested changes it stopped working, even when I reverted the changes, it continues to have the same error. I have configured my ClusterLogForwarder like this: 

```yaml
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  outputs:
    - name: loki-app
      secret:
        name: lokistack-gateway-bearer-token
      type: loki
      url: >-
        https://lokistack-gateway-http.openshift-operators-redhat.svc.cluster.local:8080/api/logs/v1/application
    - name: loki-infra
      secret:
        name: lokistack-gateway-bearer-token
      type: loki
      url: >-
        https://lokistack-gateway-http.openshift-operators-redhat.svc.cluster.local:8080/api/logs/v1/infrastructure
    - name: loki-audit
      secret:
        name: lokistack-gateway-bearer-token
      type: loki
      url: >-
        https://lokistack-gateway-http.openshift-operators-redhat.svc.cluster.local:8080/api/logs/v1/audit
  pipelines:
    - inputRefs:
        - application
      name: send-app-logs
      outputRefs:
        - loki-app
    - inputRefs:
        - infrastructure
      name: send-infra-logs
      outputRefs:
        - loki-infra
    - inputRefs:
        - audit
      name: send-audit-logs
      outputRefs:
        - loki-audit
```

**Comment by computate** [comment]
Nevermind about that above @periklis , I got the logging working again. Thanks for teaching me about the tls caName option, it worked for getting my Loki connected to my storage! 

```yaml
apiVersion: loki.grafana.com/v1beta1
kind: LokiStack
metadata:
  name: lokistack
  namespace: openshift-operators-redhat
spec:
  managementState: Managed
  storage:
    secret:
      name: thanos-object-storage
      type: s3
    tls:
      caName: lokistack-ca-bundle-custom
```

I will close this issue.
