### ISSUE TITLE
Loki Docker Driver "loki-pipeline-stage-file" no such file or directory

### ISSUE THREAD

**Issue by Strum355** [grafana/loki#694]
**Describe the bug**
Loki docker driver gives "no such file or directory" for the given file to `loki-pipeline-stage-file` set in a docker-compose.override.yml section, shown below

**To Reproduce**
1. Loki version: grafana/loki:0e04ca2133fb
2. Promtail version: grafana/promtail:518791014789
3. Docker driver:
```
docker plugin ls
ID                  NAME                DESCRIPTION           ENABLED
e0eb93aa1f77        loki:latest         Loki Logging Driver   true
```

**Expected behavior**
I guess it should find the file

**Environment:**
 - Infrastructure: local PC
 - Deployment tool: using sample docker-compose file from either loki or grafana repo

**Screenshots, promtail config, or terminal output**
```yaml
    logging:
      driver: loki
      options:
       loki-url: "http://localhost:3100/api/prom/push"
       loki-pipeline-stage-file: '/home/noah/Netsoc/dev-env/nsa/logging.yml'
```

![image](https://user-images.githubusercontent.com/18282288/59979414-800b9880-95df-11e9-9edb-a589d650015e.png)

**Comment by Kuqd** [comment]
Hello @Strum355,

The file `/home/noah/Netsoc/dev-env/nsa/logging.yml` must be available inside the docker driver.

I think you can do that by installing the driver as deamon or simply rebuild the driver with your own Dockerfile that adds this file to its filesystem.

**Comment by Strum355** [comment]
Are there instructions for installing as a daemon?

**Comment by Strum355** [comment]
```ini
> sudo cat /lib/systemd/system/loki.service
[Unit]
Description=Loki Logging Driver
Before=docker.service
After=network.target loki.socket
Requires=loki.socket docker.service

[Service]
ExecStart=/home/noah/Go/bin/loki-docker-driver

[Install]
WantedBy=multi-user.target
```

```ini
> sudo cat /lib/systemd/system/loki.socket
[Unit]
Description=Loki Logging Driver

[Socket]
ListenStream=/run/docker/plugins/loki.sock

[Install]
WantedBy=sockets.target
```

```
> journalctl -u loki
-- Logs begin at Sat 2018-10-06 01:00:19 IST, end at Mon 2019-06-24 23:08:45 IST. --
Jun 24 22:41:49 noah-Banana systemd[1]: Started Loki Logging Driver.
```

No plugins are listed with `docker plugin ls`

**Comment by Strum355** [comment]
Went down the 'rebuild the driver' route and that got it sorted :)

**Comment by raneq** [comment]
Hi @Strum355 , I am stuck with the same issue. Can you help me to "rebuild the driver"?

**Comment by Kuqd** [comment]
There’s an open issue for that.

**Comment by raneq** [comment]
@Kuqd You mean #700 , right? I find references between issues very useful, I missed that you linked it here. It's taken me a while for me to find it.

**Comment by Kuqd** [comment]
Sorry you are right.

**Comment by Kuqd** [comment]
Poke me on slack if you can't wait that I take on #700.

**Comment by BouchaaraAdil** [comment]
i managed to create my own plugin locally, using `make build-plugin`: 
1- i cloned loki repository inside `$HOME/go/src/github.com/`
2-  i have created a pipeline.yml inside `cmd/docker-driver/` folder : 
```
3- i added `pipeline.yml ` in Dockerfile `COPY ./pipeline.yaml /etc/pipeline.yml`
4- finally `make build-plugin`
then 
```
  hello-world:
    image: hello-world
    container_name: hello
    logging:
      driver: "grafana/loki-docker-driver:master-cb7c8f6-WIP"
      options:
        loki-url: "http://localhost:3100/api/prom/push"
        loki-retries: "5"
        loki-external-labels: "app={{.Name}},env=dev"
        loki-pipeline-stage-file: /etc/pipeline.yml
```

**Comment by BouchaaraAdil** [comment]
i managed to create my own plugin locally, using `make build-plugin`: 
1- i cloned loki repository inside `$HOME/go/src/github.com/`
2-  i have created a pipeline.yml inside `cmd/docker-driver/` folder : 
```
cat <<EOF > cmd/docker-driver/pipeline.yml
pipeline_stages:
- regex:
     expression: '(level|lvl|severity)=(?P<level>\\w+)'
- json:
    expressions:
      level: level
- labels:
    level:
EOF
```
3- i added `pipeline.yml ` in Dockerfile `COPY ./pipeline.yaml /etc/pipeline.yml`
4- finally `make build-plugin`
then 
```
  hello-world:
    image: hello-world
    container_name: hello
    logging:
      driver: "grafana/loki-docker-driver:master-cb7c8f6-WIP"
      options:
        loki-url: "http://localhost:3100/api/prom/push"
        loki-retries: "5"
        loki-external-labels: "app={{.Name}},env=dev"
        loki-pipeline-stage-file: /etc/pipeline.yml
```
