### ISSUE TITLE
promtail: " invalid memory address or nil pointer dereference" panic on startup

### ISSUE THREAD

**Issue by atombender** [grafana/loki#695]
**Describe the bug**
Starting a `promtail` container panics:

```
promtail-xwhfd:promtail panic: runtime error: invalid memory address or nil pointer dereference
promtail-xwhfd:promtail [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x81b56b]
promtail-xwhfd:promtail
promtail-xwhfd:promtail goroutine 1 [running]:
promtail-xwhfd:promtail github.com/grafana/loki/vendor/github.com/go-kit/kit/log/level.NewFilter(0x25fe060, 0xc000153030, 0xc00052dba0, 0x1, 0x1, 0x0, 0x0)
promtail-xwhfd:promtail 	/go/src/github.com/grafana/loki/vendor/github.com/go-kit/kit/log/level/level.go:35 +0x6b
promtail-xwhfd:promtail github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util.NewPrometheusLogger(0x0, 0x0, 0x0, 0x0, 0x5, 0x205, 0x1e0c080, 0xc000232fc0)
promtail-xwhfd:promtail 	/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/log.go:66 +0xd9
promtail-xwhfd:promtail github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util.InitLogger(0xc000232fc0)
promtail-xwhfd:promtail 	/go/src/github.com/grafana/loki/vendor/github.com/cortexproject/cortex/pkg/util/log.go:42 +0x69
promtail-xwhfd:promtail main.main()
promtail-xwhfd:promtail 	/go/src/github.com/grafana/loki/cmd/promtail/main.go:41 +0x167
```

Looks like during log configuration.

**To Reproduce**

Promtail daemonset:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: promtail
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3101"
    spec:
      serviceAccountName: promtail
      containers:
      - name: promtail
        image: "grafana/promtail:{{ .Values.imageTag }}"
        imagePullPolicy: IfNotPresent
        args:
        - "-config.file=/etc/promtail/promtail.yaml"
        - "-client.url={{ .Values.settings.service.scheme }}://{{ .Values.settings.service.name }}:{{ .Values.settings.service.port }}/api/prom/push"
        volumeMounts:
        - name: config
          mountPath: /etc/promtail
        - name: run
          mountPath: /run/promtail
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: metrics
          containerPort: 3101
        readinessProbe:
          httpGet:
            path: /ready
            port: metrics
          initialDelaySeconds: 45
        livenessProbe:
          httpGet:
            path: /ready
            port: metrics
          initialDelaySeconds: 45
      tolerations:
      # Run on any node, regardless of taints
      - operator: "Exists"
      volumes:
      - name: config
        configMap:
          name: promtail
      - name: run
        hostPath:
          path: /run/promtail
```

**Expected behavior**
Expected normal startup.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm
