### ISSUE TITLE
promtail memory leak

### ISSUE THREAD

**Issue by ly123-liu** [grafana/loki#6968]
promtail version： 2.6.1
loki version: 2.6.1

we use promtail to consumer kafka logs ,  promtail memory seems grow very fast in 10 mins  to almost 30g,   we had set limit_config in promtail , why promtail can grow to so big ?  how can we analysis promtail memory usage?

promtail config:
```yaml
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
 
positions:
  filename: /promtail/positions.yaml
 
clients:
  - url: http://loki:3100/loki/api/v1/push
    batchsize: 1048576 
    batchwait: 1s  # default
    backoff_config:
      min_period: 2s  # default 500
      max_period: 1m  # default 5m
      max_retries: 100 # default 10
 
scrape_configs:
- job_name: log-kafka
  kafka:
    brokers:
    - log-kafka-d001:9092
    - log-kafka-e001.:9092
    - log-kafka-e002:9092
    topics:
    - ^log-prod.*
    group_id: log-prod-loki-consumer
    use_incoming_timestamp: true
    labels:
      job: kafka
  pipeline_stages:
    - json:
        expressions:
          timestamp: timestamp
          cluster: fields.cluster
          namespace: fields.namespace
          container: fields.container
          podname: fields.podname
          podip: fields.podip
          nodename: fields.nodename
          log_topic: fields.log_topic
          log_type: fields.log_type
    - labels:
        timestamp:
        cluster:
        namespace: 
        nodename:
        container:
        podname:
        podip:
        log_topic:
        log_type:
  relabel_configs:
  - action: replace
    source_labels:
      - __meta_kafka_topic
    target_label: topic
 
limits_config:
  readline_rate: 4000
  readline_burst: 8000
  readline_rate_enabled: true
  readline_rate_drop: false
```

curl http://localhost:9080/debug/pprof/allocs >> /tmp/allocs2   can only see cpu time, cannot see memory usage 
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/57338370/186555765-0aaa0bae-12e5-42ad-b687-2afe041724d4.png">
![WeChatWorkScreenshot_87aa0210-81b0-428b-b0a1-6418f1c32f77](https://user-images.githubusercontent.com/57338370/186555789-fc3b9039-536c-41e2-b411-fb10346b4784.png)
