### ISSUE TITLE
No log driver named 'loki' is registered

### ISSUE THREAD

**Issue by bekiralpaydin** [grafana/loki#698]
I installed Loki logging driver for Docker:

```
[root@docker]# docker plugin ls
ID                  NAME                DESCRIPTION           ENABLED
81fd7914d805        loki:latest         Loki Logging Driver   true
```

I use the driver as follows:
```
version: "3.3"

networks:
  monitor-net:
    driver: bridge

services:
  grafana:
    image: grafana/grafana:6.2.1
    container_name: grafana
    restart: unless-stopped
    expose:
      - 3000
    logging:
      driver: "loki"
      options:
        loki-url: "http://loki:3100/api/prom/push"
        loki-retries: "5"
        loki-batch-size: "400"
```

But when I run `docker-compose-up`, I got the following error message:
```
Creating grafana ... error

ERROR: for grafana  Cannot create container for service grafana: logger: no log driver named 'loki' is registered
```

Without plugin, everything works fine.

Can you help me please? Thanks!
