### ISSUE TITLE
Cassandra index and chunk store is not being considered 

### ISSUE THREAD

**Issue by xeptore** [grafana/loki#6991]
**Describe the bug**
I setup Cassandra as both the index and chunk store, as per [this document](https://grafana.com/docs/loki/latest/storage/#on-prem-deployment-cassandracassandra), for Loki. But, after running and sending logs to Loki, Cassandra chunk and index tables are still empty:

`loki.yml`:
```yml
auth_enabled: false
target: all,table-manager
server:
  log_level: info
analytics:
  reporting_enabled: false
tracing:
  enabled: false
table_manager:
  poll_interval: 15s
  creation_grace_period: 10m
common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
schema_config:
  configs:
    - from: 2022-08-26
      store: cassandra
      object_store: cassandra
      schema: v11
      index:
        prefix: index
        period: 24h
      chunks:
        prefix: chunk
        period: 24h
storage_config:
  cassandra:
    addresses: cassandra
    keyspace: loki
```

**To Reproduce**
1. Started Cassandra (`v4.0.6`)
2. Started Loki (`v2.6.1`)
3. Sent some logs to Loki
3. Ran query on Cassandra (`cqlsh`)
    ```sql
    SELECT * FROM loki.chunk123456
    ```
    Returns empty results for all `chunk*`, and `index*` tables.

    NOTE: `123456` is a number generated by Loki. Using any available number generated by Loki will do the work.

**Expected behavior**
Tables should not be empty as I can see `wal`s are being written in Loki's container `/loki/wal` instead.

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: docker

**Screenshots, Promtail config, or terminal output**
N/A.
