### ISSUE TITLE
[loki-distributed] Add cluster_label default to prevent cross-talk from other memberlists. 

### ISSUE THREAD

**Issue by Aaron-ML** [grafana/loki#7006]
**Is your feature request related to a problem? Please describe.**
Looks like #6658 got merged, which is awesome. I see no harm in defaulting this into the chart as a default safe option.

**Describe the solution you'd like**
defaulting a memberlist config like:
```
memberlist:
  cluster_label: {{ loki.fullname }}
  cluster_label_verification_disabled: false
  join_members:
  - {{ loki.fullname }}
```
**Describe alternatives you've considered**
Right now we are defaulting this with structureConfig overrides. It works but others will run into this problem if they deploy similar services without adding it leading to additional confusion and problematic installs. For instance if tempo and loki run on the same cluster.  I'll work on this as a PR from this issue if I get the time. Thanks
