### ISSUE TITLE
Promtail `drop` stage won't match a numeric json field using `value`

### ISSUE THREAD

**Issue by slim-bean** [grafana/loki#7011]
**Describe the bug**

Take the following example promtail config
```
          scrape_configs:
            - job_name: testing
              pipeline_stages:
              - json:
                expressions:
                  level:
              - drop:
                source: "level"
                value: "50"
```               

This will not match the following json even though intuitively you would expect that it would.

```
{
  "level": 50
}
```

This is because the `extracted map` in promtail only holds strings and we do an exact match to the json value:

https://github.com/grafana/loki/blob/cff8324f241cdc13318ff4b834be750a15ce05fc/clients/pkg/logentry/stages/drop.go#L162

**Expected behavior**
Intuitively you would expect this to match

**Workaround**

The regex matcher converts the json value to a string before doing the comparison, so this config will work:

```
          scrape_configs:
            - job_name: testing
              pipeline_stages:
              - json:
                expressions:
                  level:
              - drop:
                source: "level"
                expression: "50"
```               

I think a likely easy solution to this would be to convert the value to string in the exact match case like we do for regex: https://github.com/grafana/loki/blob/cff8324f241cdc13318ff4b834be750a15ce05fc/clients/pkg/logentry/stages/drop.go#L187
