### ISSUE TITLE
Promtail Hash and Sha2Hash documentation wrong

### ISSUE THREAD

**Issue by manfred-ackermann** [grafana/loki#7014]
**Describe the bug**
Documentation is wrong.

**To Reproduce**
1. Implement template stage like described in example at https://grafana.com/docs/loki/latest/clients/promtail/stages/template/#hash-and-sha2hash
```
- template:
    source: output
    template: '{{ Hash .Value "salt" }}'
```

2. Generate a salted Sha2Hashed text using golang problem with copied function (see: https://github.com/grafana/loki/blob/cff8324f241cdc13318ff4b834be750a15ce05fc/clients/pkg/logentry/stages/template.go#L43) following the function signature
```
func Sha2Hash(salt string, input string) string {
	hash := sha256.Sum256([]byte(salt + input))
	return hex.EncodeToString(hash[:])
}

func main() {
	args := os.Args[1:]
	fmt.Println("Sha2Hash:", Sha2Hash("salt, "args[0]))
}
```

**Expected behavior**
Generated salted Sha256 hashes are equal.

**Expected solution**
Correct example at https://grafana.com/docs/loki/latest/clients/promtail/stages/template/#hash-and-sha2hash to 
```
- template:
    source: output
    template: '{{ Hash "salt" .Value }}'

- template:
    source: output
    template: '{{ Sha2Hash "salt" .Value }}'

```
