### ISSUE TITLE
Grafana explore shows "context deadline exceeded"  

### ISSUE THREAD

**Issue by LinTechSo** [grafana/loki#7018]
## Describe the bug
I am using distributed Loki version 2.6.1 that deployed via helm chart. when I query `{cluster="test"}` for 24h logs, grafana shows me this error
``` 
Failed to load log volume for this query
context deadline exceeded
```
I know my logs are too much and my query is heavy but what can I do for this? there should be a configuration or something that needs to be increased if it is not a bug
this is my Loki configuration
```
    common:
      compactor_address: http://loki-distributed-compactor:3100
    compactor:
      compaction_interval: 5m
      deletion_mode: filter-and-delete
      retention_delete_delay: 1h
      retention_delete_worker_count: 1200
      retention_enabled: true
      shared_store: s3
      working_directory: /var/loki/compactor
    distributor:
      ring:
        kvstore:
          store: memberlist
    frontend:
      compress_responses: true
      log_queries_longer_than: 5s
      max_outstanding_per_tenant: 10000
      scheduler_address: loki-distributed-query-scheduler:9095
      tail_proxy_url: http://loki-distributed-querier:3100
    frontend_worker:
      grpc_client_config:
        max_recv_msg_size: 5084857600
        max_send_msg_size: 5084857600
      scheduler_address: loki-distributed-query-scheduler:9095
    ingester:
      chunk_encoding: snappy
      chunk_idle_period: 30m
      chunk_retain_period: 1m
      chunk_target_size: 1572864
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 5084857600
        max_send_msg_size: 5084857600
    limits_config:
      cardinality_limit: 500000
      enforce_metric_name: false
      ingestion_burst_size_mb: 10
      ingestion_rate_mb: 8
      max_cache_freshness_per_query: 10m
      max_query_parallelism: 96
      per_stream_rate_limit: 80MB
      per_stream_rate_limit_burst: 100MB
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 24h
      split_queries_by_interval: 15m
    memberlist:
      join_members:
      - loki-distributed-memberlist
    querier:
      engine:
        timeout: 600s
      max_concurrent: 15
      query_timeout: 600s
    query_range:
      align_queries_with_step: true
      cache_results: true
      max_retries: 5
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            ttl: 24h
    query_scheduler:
      grpc_client_config:
        max_recv_msg_size: 5084857600
        max_send_msg_size: 5084857600
      max_outstanding_requests_per_tenant: 10000
    schema_config:
      configs:
      - from: "2020-09-07"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v11
        store: boltdb-shipper
    server:
      grpc_server_max_recv_msg_size: 5084957600
      grpc_server_max_send_msg_size: 5084957600
      http_listen_port: 3100
      http_server_read_timeout: 600s
      http_server_write_timeout: 600s
    storage_config:
      aws:
        access_key_id: xxxxxx
        bucketnames: loki
        endpoint: minio:9000
        http_config:
          response_header_timeout: 600s
        insecure: true
        s3forcepathstyle: true
        secret_access_key: yyyyyy
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 24h
        index_gateway_client:
          server_address: dns:///loki-distributed-index-gateway:9095
        shared_store: s3
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s

```

I increased the `querier.max_concurrent` up to 25 and  I saw query latency decrease but the problem persists which is a pity.

any updates? or suggestions?
