### ISSUE TITLE
Pipeline stage should act on the result of the previous stage

### ISSUE THREAD

**Issue by gouthamve** [grafana/loki#703]
Right now when using the json stage (probably other stages as well), we're not acting on the `extracted` map's `output` but on the original entry.

This makes cleaning up logs in stages impossible. For example if we have a log line like:
```
blah <JSON>
```

I was expecting to remove the blah in first stage and then use the json parsing in the next but we act on the original entry but not the processed one.

**Comment by Kuqd** [comment]
I'm surprised it is not.

**Comment by sh0rez** [comment]
Are you sure it's impossible? Taken a look at the code, it seems as if the `json` stage requires valid json to be inside of `entry`. 

However, the `regex` stage sets the extracted regex into the `extracted` map. This means it is required to use the `output` stage to move the actual json from the `extracted` map to the `entry` variable:

```yaml
  - match:
      stages:
      - regex:
          expression: blah (?P<validjson>.*)
      - output:
          source: validjson
      - json:
          expressions:
            output: log
            stream: stream
            timestamp: time

```

**Comment by pracucci** [comment]
> Right now when using the json stage (probably other stages as well), we're not acting on the extracted map's output but on the original entry.

@gouthamve I've tested the following and looks working:

```
    pipeline_stages:
      - regex:
          expression: blah (?P<json>.*)
      - output:
          source: json
      - json:
          expressions:
            // ... your expressions ...
```

However, from the UX perspective it looks more an hack than a solution.

What do you @gouthamve and @Kuqd think if we add a `source` property support to `json`: when `source` is omitted, the `json` stage parses from the entry, while when `source` is valued it parses from  `extracted[source]`.

Than the pipeline would be:
```
    pipeline_stages:
      - regex:
          expression: ([a-z]+)? (?P<json>\{.*\})
      - json:
          source: json
          expressions:
            // ... your expressions ...
```
