### ISSUE TITLE
[loki] Fail to load config.yaml with helm deployment

### ISSUE THREAD

**Issue by andikemgitopsbot** [grafana/loki#7042]
**Describe the bug**
Loki service fails to launch using officeal helm chart.
Error in pod:
```
failed parsing config: /etc/loki/loki.yaml: yaml: unmarshal errors:
line 1: field loki.yaml not found in type main.Config
```

**To Reproduce**
I deployed a Grafana based cluster observability using the helm charts as follows:
1. create an observability namespace
2. set helm file:
```
namespace: jx-observability
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
releases:
- chart: jxgh/grafana-dashboard
  name: grafana-dashboard
- chart: grafana/loki
  name: loki
- chart: grafana/promtail
  name: promtail
- chart: grafana/tempo
  name: tempo
- chart: grafana/grafana
  name: grafana
- chart: prometheus-community/prometheus
  name: prometheus
```
After deployment, all services are up, with the exception of loki and promtail, which fail as follows 
Error in pod:
```
failed parsing config: /etc/loki/loki.yaml: yaml: unmarshal errors:
line 1: field loki.yaml not found in type main.Config
```
**Expected behavior**
That the pod deploys succesfully using teh official chart

**Environment:**
 - Infrastructure: K8S v 1.21 on AWS EKS. Secret manager AWS SM.
 - Deployment tool: Jenkins X using Helm

**Screenshots, Promtail config, or terminal output**

![image](https://user-images.githubusercontent.com/106773464/188277608-a6438425-ecf4-4e10-9d16-f8b7059ef746.png)
