### ISSUE TITLE
New 3.0 helm chart install fails and produces "no matches for kind"

### ISSUE THREAD

**Issue by calbot** [grafana/loki#7047]
Trying the latest helm chart I get the following:

Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "GrafanaAgent" in version "monitoring.grafana.com/v1alpha1", unable to recognize "": no matches for kind "LogsInstance" in version "monitoring.grafana.com/v1alpha1", unable to recognize "": no matches for kind "PodLogs" in version "monitoring.grafana.com/v1alpha1"]

I believe I followed the correct steps in https://github.com/grafana/loki/tree/main/production/helm/loki
for grafana/loki

I don't get the issue if I specify the old version --version 2.16.0

**Comment by calvinbui** [comment]
try:

```
monitoring.selfMonitoring.grafanaAgent.installOperator: false
```

**Comment by calbot** [comment]
That didn't work for me...

I added it to my customvalues.yaml

╰─ helm upgrade --install loki --namespace=monitoring grafana/loki -f helm/loki/customvalues.yaml --dry-run
Error: UPGRADE FAILED: [unable to recognize "": no matches for kind "GrafanaAgent" in version "monitoring.grafana.com/v1alpha1", unable to recognize "": no matches for kind "LogsInstance" in version "monitoring.grafana.com/v1alpha1", unable to recognize "": no matches for kind "PodLogs" in version "monitoring.grafana.com/v1alpha1"]

**Comment by calvinbui** [comment]
disable one of these instead: https://github.com/grafana/loki/search?q=monitoring.grafana.com%2Fv1alpha1

**Comment by sbueringer** [comment]
I disabled basically everything
```yaml
monitoring:
  dashboards:
    # -- If enabled, create configmap with dashboards for monitoring Loki
    enabled: false
  rules:
    # -- If enabled, create PrometheusRule resource with Loki recording rules
    enabled: false
  alerts:
    # -- If enabled, create PrometheusRule resource with Loki alerting rules
    enabled: false
  serviceMonitor:
    # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
```

Now it only tries to depoy one ServiceMonitor (which fails), the one in `/loki/templates/monitoring/servicemonitor.yaml` (it can't be disabled)

**Comment by erewok** [comment]
This is perhaps unhelpful, but I ran into the same issues reported here this morning and in one of dev clusters I was able to delete and reinstall loki using our previous extra-values file for the loki-simple-scalable chart. In other words, I did the following and it worked:

```sh
$ helm delete loki
release "loki" uninstalled

$ helm upgrade --install -n monitoring -f ./manifests/loki/loki.extra-values.yaml loki grafana/loki
Release "loki" does not exist. Installing it now.
NAME: loki
LAST DEPLOYED: Wed Oct  5 08:13:06 2022
NAMESPACE: monitoring
STATUS: deployed
REVISION: 1
NOTES:
***********************************************************************
 Welcome to Grafana Loki
 Chart version: 3.2.0
 Loki version: 2.6.1
***********************************************************************

Installed components:
* gateway
* read
* write
```

Not sure if I'm going to do this for production yet...

**Comment by trevorwhitney** [comment]
Does https://github.com/grafana/loki/pull/7067 combined with disabling self monitoring fix this issue?

Self monitoring will have to be disabled if you're not planning on using the included Grafana Agent and it's CRDs.

**Comment by sbueringer** [comment]
Works! Thank you very much

For reference, I had to disable a few more things (to get to a valid configuration):
```yaml
monitoring:
  dashboards:
    # -- If enabled, create configmap with dashboards for monitoring Loki
    enabled: false
  rules:
    # -- If enabled, create PrometheusRule resource with Loki recording rules
    enabled: false
  alerts:
    # -- If enabled, create PrometheusRule resource with Loki alerting rules
    enabled: false
  serviceMonitor:
    # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
    lokiCanary:
      enabled: false

test:
  enabled: false
```

+ In my case because I'm not using S3, ....

```yaml
  rulerConfig:
    storage:
      type: local
```

Without this I ended up with `storage: null` and Loki didn't come up any more
