### ISSUE TITLE
rpc error: code = Unknown desc = failed to get s3 object: NoSuchKey: The specified key does not exist. status code: 404

### ISSUE THREAD

**Issue by teloon999** [grafana/loki#7053]
**Using MinIO as storage, 
I lost some chunk and index files, 
resulting in an error querying historical data using grafana:** 
*"rpc error: code = Unknown desc = failed to get s3 object: NoSuchKey: The specified key does not exist. status code: 404, request id: 1711F0371EFA9FC2, host id:",*

![1662374270843](https://user-images.githubusercontent.com/70459940/188430113-c1c9fc78-9aaf-409d-856c-f16e34855de5.jpg)

**Below is my configuration information：**
```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  max_chunk_age: 24h
  chunk_target_size: 1572864
  chunk_idle_period: 5h
  chunk_retain_period: 30s

compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor
  shared_store: s3

storage_config:
  aws:
    bucketnames: loki
    endpoint: http://192.168.xx.xx:9000
    s3forcepathstyle: true
    access_key_id: xxxx
    secret_access_key: xxxx
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: s3

schema_config:
  configs:
    - from: 2022-08-28
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_
        period: 24h
```
**please help me, how to query the previous data normally, thank you very much!**
