### ISSUE TITLE
Matching loglines in promtail config pipeline_stage always sets the last custom (template based) label

### ISSUE THREAD

**Issue by gerardjp** [grafana/loki#7065]
**Describe the bug**
I'm matching loglines from a standard Promtail config. In the `pipeline_stages` I do an initial syslog line parse, after which I add a label called `log_level` setting a value `error` or `warning` based on whether a variant of those is found in the log `message`. Whichever `match` directive is last in the `pipeline_stages` is the prevaling value of the label.

**To Reproduce**
1. Running loki from a systemd file, version: 2.6.1
2. Running promtail from a systemd file, version 2.2.1
3. My grafana query is:  {host="$host"} |= `gerard`

**Expected behavior**
The log messages getting the right `log_level` label value of `error` or `warning`.

**Environment:**
 - Infrastructure: Local Linux servers under Virtualbox, Ubuntu 20.04
 - Deployment tool: Saltstack

**Screenshots, Promtail config, or terminal output**
Commands used to trigger the Promtail config:
```
root@srv102 ~# logger -t gerard "This is a warning"
root@srv102 ~# logger -t gerard "This is an error"
```

Their output in syslog:
```
Sep  6 09:47:49 srv102 gerard: This is a warning
Sep  6 09:47:49 srv102 gerard: This is an error
```

My grafana panel query:
```
{host="$host"} |= `gerard`
```

My Promtail config:
```
scrape_configs:
  # --------------------------
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        host: srv102
        __path__: /var/log/*log

    pipeline_stages:
    - match:
        selector: '{job="varlogs"}'
        stages:
        - regex:
            expression: '(?P<timestamp>[a-zA-Z]{3} \d{2} \d{2}:\d{2}:\d{2}) (?P<loghost>[-a-z0-9]+) (?P<program>[-a-zA-Z/]+)\[(?P<pid>[0-9]+)\]: (?P<msg>[\s\S]*)'
        - labels:
            program:

    - match:
        selector: '{job="varlogs"}'
        stages:
        - regex:
            expression: '^.*(?P<log_level>(warn|Warn|WARN|warning|Warning|WARNING)).*$'
        - template:
            source: log_level
            template: 'warning'
        - labels:
            log_level:

    - match:
        selector: '{job="varlogs"}'
        stages:
        - regex:
            expression: '^.*(?P<log_level>(error|Error|ERROR)).*$'
        - template:
            source: log_level
            template: 'error'
        - labels:
            log_level:
```

The result of the messages and their labels in Grafana panel is in attached screenshot. Switching the order of the match directives will result in both messages having `warning` as `log_level` value.

<img width="624" alt="Screen Shot 2022-09-06 at 11 49 42" src="https://user-images.githubusercontent.com/317344/188615474-721707b4-578e-4c6b-b785-a4b0ee820a5c.png">

**Comment by liguozhong** [comment]
```
    - match:
        selector: '{job="varlogs"} |~="error|Error|ERROR"'
        stages:
        - regex:
            expression: '^.*(?P<log_level>(error|Error|ERROR)).*$'
        - template:
            source: log_level
            template: 'error'
        - labels:
            log_level:
```

I took a look, the “match” in the promtail configuration is not filtered.

        selector: '{job="varlogs"}"'
-->
        selector: '{job="varlogs"} |~="error|Error|ERROR"'
