### ISSUE TITLE
[helm/loki-simple-scalable] Are PVCs really required? / Retention not working?

### ISSUE THREAD

**Issue by R-Studio** [grafana/loki#7068]
## My Goal
- Run Loki only with Object Storage from MinIO, if it is possible.
- I want to run Loki scalable and easy as possible, that's why I decided to use [loki-simple-scalable](https://github.com/grafana/helm-charts/tree/main/charts/loki-simple-scalable) resp. the new location .

## My Question
- Is it possible to run loki-simple-scalable without PVCs (only S3 from MinIO)? 
  - If yes, how does the configuration look like?
  - If no, why are PVCs required?, Which contents are saved in my PVCs?, Why are my PVCs filling up? 
- Are the retentions configured in the `compactor` and `limits_config` working with S3 or do I need to configure the retention on my MinIO Bucket? As I understand the release notes of [Loki 2.3](https://grafana.com/docs/loki/latest/release-notes/v2-3/) there is no need for external (not loki) retentions (_Loki now has the ability to apply custom retention based on stream selectors! This will allow much finer control over log retention all of which is now handled by Loki, **no longer requiring the use of object store configs for retention**._) -> If yes, how does the configuration look like?
- Just for my interest: What's the difference between configure retention in the `compactor` component and configure retention in `table manager`? In the documentation the following written: _Retention through the Table Manager is achieved by relying on the object store TTL feature, and will work for both boltdb-shipper store and chunk/index store. However retention through the Compactor is supported only with the boltdb-shipper store._ But in the section of the Table Manager it contradicts itself: _When using S3 or GCS, the bucket storing the chunks needs to have the expiry policy set correctly. For more details check S3’s documentation or GCS’s documentation._

## My current configuration
```yaml
gateway:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 80
  ingress:
    enabled: true
  resources:
    limits:
      #cpu: 50m
      memory: 30Mi
    requests:
      cpu: 5m
      memory: 15Mi

loki:
  # The value below "config" must be a string instead of a map
  config: |
    auth_enabled: false
    common:
      path_prefix: /var/loki
      storage:
        filesystem: null
        s3:
          insecure: true
          s3: http://USERNAME:PASSWORD@minio.minio.svc.cluster.local:9000/loki
          s3forcepathstyle: true
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: s3
    schema_config:
      configs:
        - from: "2020-09-07"
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            period: 24h
            prefix: index_
    limits_config:
      retention_period: 1h
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
    compactor:
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    table_manager:
      retention_deletes_enabled: true
      retention_period: 1h
    chunk_store_config:
      max_look_back_period: 1h
    query_scheduler:
      max_outstanding_requests_per_tenant: 1000
    memberlist:
      join_members:
      - loki-memberlist
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

write:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 80
  persistence:
    size: 5Gi
    storageClass: longhorn
  resources:
    limits:
      #cpu: 400m
      memory: 1200Mi # Don't decrease this limit. Loki uses enough memory to prevent dataloss (when storage backend unavailable)
    requests:
      cpu: 35m
      memory: 300Mi # Don't decrease this limit. Loki can fastly grow up in memory and this can cause OOM-Killing of other pods

read:
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 80
  persistence:
    size: 1Gi
    storageClass: longhorn
  resources:
    limits:
      #cpu: 400m
      memory: 150Mi
    requests:
      cpu: 50m
      memory: 75Mi
    
serviceMonitor:
  enabled: true


monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
```

+ Environment specific Helm values:
```yaml
gateway:
  ingress:
    hosts:
    - host: loki.apps-test-1....
      paths: 
      - path: /
        pathType: ImplementationSpecific
    tls:
    - hosts: 
      - loki.apps-test-1....
      secretName: ingress-wildcard-cert
```

_-> I already opened this issue in the previous [location](https://github.com/grafana/helm-charts/issues/1693) of the Loki-Simple-Scalable Helm Chart, but because the Helm chart moved (thanks to @zanhsieh), I opened a new issue here._

**Comment by R-Studio** [comment]
There are other users with the same issue.

**Comment by rt005744** [comment]
This problem has been bothering me

**Comment by R-Studio** [comment]
@atze234 thanks for your reply. It is little bit confusing because in the docs for compactor following is written: 
_The [Compactor](https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper#compactor) can deduplicate index entries. **It can also apply granular retention. When applying retention with the Compactor, the [Table Manager](https://grafana.com/docs/loki/latest/operations/storage/table-manager/) is unnecessary.**_  
-> It would be helpful when the docs also adds following sentence for compactor: _When using S3 or GCS, the bucket storing the chunks needs to have the expiry policy set correctly._

Anyway, do you know how to configure loki in "scalable mode" without having persistent volumes? (so that loki only uses S3)?

**Comment by davdr** [comment]
@atze234 @R-Studio The [compactor docs](https://grafana.com/docs/loki/latest/operations/storage/retention/) also say: "The chunks will be deleted by the compactor asynchronously when swept." and "Marked chunks will only be deleted after retention_delete_delay configured is expired" (plus an explanation of why that is). So I'd say no expiry policy on the object store is necessary with the current Loki version. (Purely based on reading the docs, I hope to have time soon to try it out)

**Comment by atze234** [comment]
@R-Studio 
With the current chart its not possible to configure the PVC away. You may use an ephemeral Storage Class maybe. Although i think there will be data loss in case of restarts, so i wont do that.

@davdr 
I tried with just the compactor and no chunks were deleted out of S3. I tried with 7days retention and even after 4 weeks there were old chunks in s3. Thats why i came here :)

**Comment by guoew** [comment]
[table_manager](https://grafana.com/docs/loki/latest/configuration/#table_manager) 有提到 `The retention period must be a multiple of the index / chunks`

**Comment by guoew** [comment]
@R-Studio 
The [table_manager](https://grafana.com/docs/loki/latest/configuration/#table_manager) docs say:  "The retention period must be a multiple of the index / chunks",  the [compactor](https://grafana.com/docs/loki/latest/operations/storage/retention/#compactor) docs say `The minimum retention period is 24h.`，  and the [schema_config](https://grafana.com/docs/loki/latest/configuration/#schema_config) docs mentions that the default period of index and chunks is 168h.
Can you check your configuration and try again?

**Comment by R-Studio** [comment]
@atze234 
Thanks for your reply, but why is it possible with the "Single Binary" mode?

@guoew 
If I have understood you correctly, then the following configuration should work with the retention of 4 days:
```yaml
loki:
  # The value below "config" must be a string instead of a map
  config: |
    auth_enabled: false
    common:
      path_prefix: /var/loki
      replication_factor: 3
      storage:
        filesystem: null
        s3:
          insecure: true
          s3: http://<USER:PASSWORD>@minio.minio.svc.cluster.local:9000/loki
          s3forcepathstyle: true
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: s3
    schema_config:
      configs:
        - from: "2020-09-07"
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            period: 24h
            prefix: index_
    limits_config:
      retention_period: 4d
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
    compactor:
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    table_manager:
      retention_deletes_enabled: true
      retention_period: 4d
    query_scheduler:
      max_outstanding_requests_per_tenant: 1000
    memberlist:
      join_members:
      - loki-memberlist
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
    ruler:
      alertmanager_url: http://alertmanager-operated.cattle-monitoring-system.svc.cluster.local:9093
      enable_alertmanager_v2: true
      enable_api: true
      enable_sharding: true
```
**-> Until now the retention is not working, but maybe I have to wait. (I will get back to you later)**

**Comment by R-Studio** [comment]
@guoew It looks like the retention is working now:
Before changing the retention to 4 days:
![image](https://user-images.githubusercontent.com/7498854/190976424-74dfad12-cfe9-4003-800f-46341c249f0e.png)

After changing the retention to 4 days:
![image](https://user-images.githubusercontent.com/7498854/190976476-f9217b85-80db-40aa-98f0-c2d62ad4aaec.png)

But on the S3 (MinIO) I don't see that loki has deleted anything. But maybe this takes some time for MinIO to really delete the files.
Before changing the retention to 4 days:
![image](https://user-images.githubusercontent.com/7498854/190976882-db67eeaf-61ac-4e48-abf6-e0d4951dd030.png)

After changing the retention to 4 days:
![image](https://user-images.githubusercontent.com/7498854/190976921-ea5b4f59-5270-4849-aeff-a14f7d31f065.png)

**Comment by guoew** [comment]
You can change schema_config to the following configuration and try again.
```
    schema_config
      configs:
        - from: "2020-09-07"
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            period: 24h
            prefix: index_
          chunks:
            period: 24h
```

**Comment by guoew** [comment]
@R-Studio  You can change schema_config to the following configuration and try again.
```
    schema_config
      configs:
        - from: "2020-09-07"
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            period: 24h
            prefix: index_
          chunks:
            period: 24h
```

**Comment by R-Studio** [comment]
@guoew what does this mean/change?

**Comment by R-Studio** [comment]
Now it works, thanks! 👍😊😉
![image](https://user-images.githubusercontent.com/7498854/190990973-c445dff9-e53b-422b-8541-7d33c650661f.png)

**Comment by atze234** [comment]
For me its not deleting anything out of chunks :-1:  aws-cli easily finds files older than 7 days. 
My config:
```
    auth_enabled: true
    common:
      path_prefix: /var/loki
      replication_factor: 3
      storage:
        s3:
          bucketnames: <redacted>
          endpoint: s3.eu-central-1.amazonaws.com
          insecure: false
          region: eu-central-1
          s3: <redacted>
          s3forcepathstyle: false
    compactor:
      compaction_interval: 10m
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      retention_enabled: true
      shared_store: s3
      working_directory: /var/loki/compactor
    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 7d
      split_queries_by_interval: 15m
    memberlist:
      join_members:
      - loki-memberlist
    query_range:
      align_queries_with_step: true
    query_scheduler:
      max_outstanding_requests_per_tenant: 2048
    ruler:
      storage:
        s3:
          bucketnames: <redacted>
          endpoint: s3.eu-central-1.amazonaws.com
          insecure: false
          region: eu-central-1
          s3: <redacted>
          s3forcepathstyle: false
    schema_config:
      configs:
      - chunks:
          period: 24h
        from: "2022-01-11"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v12
        store: boltdb-shipper
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
    storage_config:
      aws:
        s3: s3://eu-central-1/<redacted>
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/boltdb-cache
        resync_interval: 5s
        shared_store: s3
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
    table_manager:
      retention_deletes_enabled: true
      retention_period: 7d
```
