### ISSUE TITLE
Loki Logs deletion -- not working for deletion-mode filter-and-delete

### ISSUE THREAD

**Issue by pkrishnanreflexion** [grafana/loki#7072]
**Describe the bug**
I am using HTTP API of loki to delete logs matching a particular stream with start time and end time as documented [https://grafana.com/docs/loki/latest/api/#post-lokiapiv1delete](https://grafana.com/docs/loki/latest/api/#post-lokiapiv1delete)

**My request example:**
http://localhost:3100/loki/api/v1/delete?query={index="x11001-logs-2022-08-09"}&start=2022-08-09T06:59:52.000Z&end=2022-08-09T06:59:59.999Z

My loki-config file:

```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

ingester:
  chunk_idle_period: 3m       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 3m           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or 
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache 
  max_transfer_retries: 0     # Chunk transfers disabled

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
  retention_enabled: true
  delete_request_cancel_period: 1m #(default = 24h)
  deletion_mode: filter-and-delete

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  enforce_metric_name: false
  reject_old_samples: false
  ingestion_rate_mb: 16 # <float> | default = 4] / 8
  ingestion_burst_size_mb: 32 # <int> | default = 6]/16
  per_stream_rate_limit: 16MB # <string|int> | default = "3MB"/5
  max_global_streams_per_user: 0
  max_query_length: 0h # Default: 721h
  max_query_parallelism: 32 # Old Default: 14
  max_streams_per_user: 0 # Old Default: 10000 /0
  max_entries_limit_per_query: 7000 #default 5000 / 7000
  allow_deletes: true

ruler:
  alertmanager_url: http://localhost:9093

```

The request works fine and produced correct results when the compactor configuration is
`
deletion-mode: filter-only
`
But the request deletes few thousands of lines when the compactor configuration is
`
deletion-mode: fileter-and-delete
`
In the initial querying the results seem appropriate (because filtering is happening at the querier). But when actual deletion happens in the physical storage, few thousands of log lines are deleted.

**To Reproduce**
1. Start Loki with above configuration file
2. Create a delete request
3. Query and verify result of delete request. (after an interval of 10 minutes to allow deletion from physical storage)

**Expected behavior**
Only requested log lines should be deleted. Additional log lines (thousands) or chunks should not be deleted.

**Environment:**
 - Docker image(single binary) on LINUX VM.
