### ISSUE TITLE
[Helm] 3.0.0 ingress does not support single binary mode

### ISSUE THREAD

**Issue by calvinbui** [grafana/loki#7080]
**Describe the bug**

The ingress that comes with the Helm chart is configured for a scalable deployment only. This is because the paths in the ingress use services suffixed with `read` and `write`. A single binary deployment does not include these services, only `loki` and `loki-headless`. 

https://github.com/grafana/loki/blob/c23e541fe7d6aa4e35e720df4e191f034325d24f/production/helm/loki/values.yaml#L759-L770

https://github.com/grafana/loki/blob/c23e541fe7d6aa4e35e720df4e191f034325d24f/production/helm/loki/templates/ingress.yaml#L36-L53

I have worked around this in the meantime by using the `headless` suffix and emptying the default `write` and `read` lists:

```yaml
paths:
  write: []
  read: []
  headless:
    - /api/prom/push
    - /loki/api/v1/push
    - /api/prom/tail
    - /loki/api/v1/tail
    - /loki/api
    - /api/prom/rules
    - /loki/api/v1/rules
    - /prometheus/api/v1/rules
    - /prometheus/api/v1/alerts
```

**Expected behavior**

The Helm chart uses the `loki` service when deploying an ingress in single binary mode.
