### ISSUE TITLE
server returned HTTP status 401 Unauthorized (401): no org id

### ISSUE THREAD

**Issue by mongoliaredmountain** [grafana/loki#7081]
I used helm install Loki and Promtail,But Promtail send 'caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"'

loki.yaml
[loki的副本.md](https://github.com/grafana/loki/files/9502707/loki.md)

promtail.yaml
[promtail的副本.md](https://github.com/grafana/loki/files/9502710/promtail.md)

logs
level=error ts=2022-09-07T04:29:34.599308846Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
level=error ts=2022-09-07T04:29:35.800382126Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
level=error ts=2022-09-07T04:29:36.900329685Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
level=error ts=2022-09-07T04:29:38.09956929Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
level=error ts=2022-09-07T04:29:39.19990638Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
level=error ts=2022-09-07T04:29:40.299893729Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
level=error ts=2022-09-07T04:29:41.399964187Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
level=error ts=2022-09-07T04:29:42.600158749Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
level=error ts=2022-09-07T04:29:43.800863042Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
level=error ts=2022-09-07T04:29:44.90022787Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
level=error ts=2022-09-07T04:29:46.100090867Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
level=error ts=2022-09-07T04:29:47.299770482Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
level=error ts=2022-09-07T04:29:48.39999092Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"
level=error ts=2022-09-07T04:29:49.599192624Z caller=client.go:380 component=client host=loki-gateway msg="final error sending batch" status=401 error="server returned HTTP status 401 Unauthorized (401): no org id"

**Comment by sbueringer** [comment]
Not sure if it's a fix or just a workaround, but I had to do the following to make it work:

promtail values.yaml
```yaml
config:
  # publish data to loki
  clients:
    - url: http://loki-gateway/loki/api/v1/push
      tenant_id: 1
```

and then in the values.yaml of the grafana chart
```yaml
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki:3100
      jsonData:
        httpHeaderName1: 'X-Scope-OrgID'
      secureJsonData:
        httpHeaderValue1: '1'
```

**Comment by fabriziopandini** [comment]
+1 to get this fixed or documented, it took a while to get things working...

**Comment by liguozhong** [comment]
https://github.com/grafana/loki/tree/main/production/helm/loki
`loki.auth_enabled  : false .
`
helm's installation command Modify this configuration to false, you can cancel the auth feature to fix this error
.
![image](https://user-images.githubusercontent.com/9583245/189073179-374e5531-0afa-44cf-ba8c-126d7d90425f.png)

**Comment by mfordjody** [comment]
good！

**Comment by eweremono** [comment]
This was very helpful, it enabled auth by default, you can change the value [here](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L197) to false and apply helm again

**Comment by dellnoantechnp** [comment]
I fond this solution:

## My Environment: 
* k8s: 1.24.x 
* Loki: loki-distributed-0.69.16 chart  (appVersion 2.8.2)
* Promtail:  promtail-6.10.0  chart  (appVersion 2.7.4)
* Grafana: 10.0.2

## 1. If you want simplely enable multitenant support:
```yaml
## loki-distributed-values.yaml
loki:
  config: |
    auth_enabled: true
  ingress:
    enabled: false
  gateway: 
    enabled: true
    basicAuth:
      enabled: false    <-- not support basic auth
```

```yaml
## promtail-values.yaml
config:
  clients:
    - url: http://loki-distributed-gateway/loki/api/v1/push
      tenant_id: tenant-1
```

In Grafana Web-UI:
config datasource.
> Custom HTTP Headers
>>  Header: `X-Scope-OrgID`
>>  Value:  `tenant-1`

![image](https://github.com/grafana/loki/assets/11703403/1825b2fc-365b-44ab-a2bf-f3c2731dca98)

---
## 2. If you want to use basic_auth `username` as `tenantID`
```yaml
## loki-distributed-values.yaml
loki:
  config: |
    auth_enabled: true
  ingress:
    enabled: false
  gateway: 
    enabled: true
    basicAuth:
      enabled: true      <--  support basic auth
      username: admin
      password: admin-password
      existingSecret: null                                                       <--  only admin user      OR
      existingSecret: loki-multi-tenant-auth-secret              <-- multi tenant user as tenantID
    nginxConfig:
      file: |
          ............
                location = /loki/api/v1/push {
                  set $loki_api_v1_push_backend http://{{ include "loki.distributorFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
                  proxy_pass       $loki_api_v1_push_backend:3100$request_uri;
                  ## add X-Scope-OrgID header to backend endpoint.
                  proxy_set_header X-Scope-OrgID $remote_user;        <--- map remote_user to X-Scope-OrgID header
                  proxy_http_version 1.1;
                }
         ............
```

### generate multi auth user using tenant id.
### copy this bash script to generator .htpassword:
```bash
while read -r line; do
  USER=$(echo $line | awk '{print $1}');
  PASSWORD=$(echo $line | awk '{print $2}');
  printf "$USER:$(openssl passwd -apr1 $PASSWORD)\n" >> .htpasswd
  printf "user:\ %-20s updated" $USER
done < <(cat << EOF
user1  password1
user2  password2
tenant-3  password-3
EOF
)
```

Create `loki-multi-tenant-auth-secret` secret:
```yaml
## kustomize
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: loki-multi-tenant-auth-secret
    namespace: loki
    files:
      - .htpasswd
```


```yaml
## promtail-values.yaml
config:
  clients:
    - url: http://loki-distributed-gateway/loki/api/v1/push
      basic_auth:
        username: tenant-3
        password: password-3
```

In Grafana Web-UI:
config datasource.
> Auth:
>>   Basic auth: enable
>
> Basic Auth Details:
>>   User: tenant-3
>>   Password: password-3
>
> Custom HTTP Headers
>>  Header: `X-Scope-OrgID`
>>  Value:  `tenant-3`

**Comment by mischavandenburg** [comment]
I ran into this issue when deploying Loki to [my homelab](https://github.com/mischavandenburg/homelab).

Then I used these values with the grafana/loki chart to get it to work:

```yaml
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: "filesystem"
    singleBinary:
      replicas: 1
```

Note that this is an installation for learning and hobby purposes.
