### ISSUE TITLE
[Helm] 3.0.0 Chart does not deploy into .Release.Namespace

### ISSUE THREAD

**Issue by sbueringer** [grafana/loki#7089]
**Describe the bug**
We were deploying the previous 2.16.0 helm chart into a specific namespace by setting the namespace in helm 
(which is consumed in the Helm Chart via .Release.Namespace). When deploying the new Helm Chart in single 
binary mode (at least) the loki StatefulSet is always deployed into the default namespace

**To Reproduce**
Deploy the v3.0.0 loki Helm chart from https://grafana.github.io/helm-charts with this values.yaml
```yaml
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'

# We are disabling basically everything because we just want
# Loki and no additional monitoring.
monitoring:
  dashboards:
    # -- If enabled, create configmap with dashboards for monitoring Loki
    enabled: false
  rules:
    # -- If enabled, create PrometheusRule resource with Loki recording rules
    enabled: false
  alerts:
    # -- If enabled, create PrometheusRule resource with Loki alerting rules
    enabled: false
  serviceMonitor:
    # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
```

and  set the release namespace to e.g. `observability`.

**Expected behavior**
All objects should be deployed in the `observability` namespace (but is deployed into `default`)

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop] local kind
 - Deployment tool: [e.g., helm, jsonnet] helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
