### ISSUE TITLE
Promtail unable to handle docker logs larger than 16kb

### ISSUE THREAD

**Issue by doanbutar** [grafana/loki#7100]
What happened?
When we have exceptions larger than 16kb, promtail does not concatenate the logs that are split by Docker.

I've found this issue here: https://github.com/grafana/loki/issues/2281

They say that doing the following in a pipeline stage will work as workaround:
```
multiline:
firstline: '(^{(.*))|([^}\s]\s$)'

replace:
expression: '(\n)'
replace: ''
```
However it's not working for me.

I've also tried [this](https://github.com/grafana/loki/issues/2281#issuecomment-1105188098) suggestion but still not working.
Example of logs:
```
{"log":"2022-09-08 07:12:03.673 WARN 7 --- [ main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty web server\n","stream":"stdout","time":"2022-09-08T07:12:03.673425879Z"} pod_name:portal-internal-deployment-65964bc5cc-gpxl8

{"log":"org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Jetty web server\n","stream":"stdout","time":"2022-09-08T07:12:03.872113781Z"} pod_name:portal-internal-deployment-65964bc5cc-gpxl8

{"log":"Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionRepositoryFilterRegistration' defined in class path resource [org/springframework/boot/autoconfigure/session/SessionRepositoryFilterConfiguration.class]: Unsatisfied dependency expressed through method 'sessionRepositoryFilterRegistration' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.session.config.annotation.web.http.SpringHttpSessionConfiguration': Unsatisfied dependency expressed through method 'setHttpSessionIdResolver' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'portalConfiguration': Unsatisfied dependency expressed through method 'updateConversions' parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nameGeneratorImpl': Unsatisfied dependency expressed through field 'invoiceHelper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'invoiceHelperImpl': Unsatisfied dependency expressed through field 'webUserService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webUserServiceImpl': Unsatisfied dependency expressed through field 'webUserRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webUserRepository': Cannot create inner bean '(inner bean)#2e1b374c' of type [org.springframework.orm.jpa.SharedEntityManagerCreator] while setting bean property 'entityManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#2e1b374c': Cannot resolve reference to bean 'entityManagerFactory' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'entityManagerFactory' defined in class path resource [com/clx/one/common/database/datasource/SmscDbConfig.class]: Unsatisfied dependency expressed through method 'entityManagerFactory' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'entityManagerFactoryBuilder' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Unsatisfied dependency expressed through method 'entityManagerFactoryBuilder' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaVendorAdapter' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.orm.jpa.JpaVendorAdapter]: Factory method 'jpaVendorAdapter' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.smscDataSource' defined in class path resource [com/clx/one/common/database/datasource/SmscDbConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'smscDataSource' threw exception; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure\n","stream":"stdout","time":"2022-09-08T07:12:03.872281984Z"} pod_name:portal-internal-deployment-65964bc5cc-gpxl8

{"log":"\u0009at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[mysql-connector-java-8.0.15.jar!/:8.0.15]\n","stream":"stdout","time":"2022-09-08T07:12:03.873393317Z"} pod_name:portal-internal-deployment-65964bc5cc-gpxl8
```

Promtail config:
```
# cat promtail.yaml

server:

  log_level: info

  http_listen_port: 3101

 

clients:

  - basic_auth:

      password: <password>

      username: <tenant id>

    external_labels:

      cluster: eu1tst-eks001

      environment: staging

    url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push

 

positions:

  filename: /run/promtail/positions.yaml

 

scrape_configs:

  - job_name: kubernetes-pods

    pipeline_stages:

      - multiline:

          firstline: ^\x{200B}\{

          max_wait_time: 3s

      - replace:

          expression: ^(\x{200B})

          replace: ""

      - replace:

          expression: ([\n])

          replace: ""

      - labeldrop:

        - filename

      - replace:

          expression: (.*)

          replace: '{{ .Value }} pod_name:{{ .pod }}'

      - labeldrop:

        - pod

    kubernetes_sd_configs:

      - role: pod

    relabel_configs:

      - source_labels:

          - __meta_kubernetes_pod_controller_name

        regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?

        action: replace

        target_label: __tmp_controller_name

      - source_labels:

          - __meta_kubernetes_pod_label_app_kubernetes_io_name

          - __meta_kubernetes_pod_label_app

          - __tmp_controller_name

          - __meta_kubernetes_pod_name

        regex: ^;*([^;]+)(;.*)?$

        action: replace

        target_label: app

      - source_labels:

          - __meta_kubernetes_pod_label_app_kubernetes_io_instance

          - __meta_kubernetes_pod_label_release

        regex: ^;*([^;]+)(;.*)?$

        action: replace

        target_label: instance

      - source_labels:

          - __meta_kubernetes_pod_label_app_kubernetes_io_component

          - __meta_kubernetes_pod_label_component

        regex: ^;*([^;]+)(;.*)?$

        action: replace

        target_label: component

      - action: replace

        source_labels:

        - __meta_kubernetes_pod_node_name

        target_label: node_name

      - action: replace

        source_labels:

        - __meta_kubernetes_namespace

        target_label: namespace

      - action: replace

        replacement: $1

        separator: /

        source_labels:

        - namespace

        - app

        target_label: job

      - action: replace

        source_labels:

        - __meta_kubernetes_pod_name

        target_label: pod

      - action: replace

        source_labels:

        - __meta_kubernetes_pod_container_name

        target_label: container

      - action: replace

        replacement: /var/log/pods/*$1/*.log

        separator: /

        source_labels:

        - __meta_kubernetes_pod_uid

        - __meta_kubernetes_pod_container_name

        target_label: __path__

      - action: replace

        regex: true/(.*)

        replacement: /var/log/pods/*$1/*.log

        separator: /

        source_labels:

        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash

        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash

        - __meta_kubernetes_pod_container_name

        target_label: __path__
```
