### ISSUE TITLE
Promtail - docker_sd re-sending logs on container shutdown

### ISSUE THREAD

**Issue by heapdavid** [grafana/loki#7103]
**Describe the bug**
Hi,

We're using `docker_sd_config` to scrape docker containers using json-file logging. The symptoms we're seeing when a container shuts down are:
- Recent logs are duplicated once the container has been shut down
- Any older logs cause the following error example:
  - `final error sending batch server returned HTTP status 400 Bad Request (400): entry with timestamp 2022-09-07 08:32:22.028843795 +0000 UTC ignored, reason: 'entry too far behind' for stream: `
  - related to `max_chunk_age`/2 as far as I can tell, as per https://github.com/grafana/loki/issues/5936#issuecomment-1102921754

**To Reproduce**
1. Configure Promtail (v2.6.1) with docker_sd_config as per config below
2. Run a docker container (for longer than `max_chunk_age`/2 since the most recent log entry if you want to reproduce the 2nd symptom)
3. Check the logs don't contain duplicates, then stop or restart the container.
4. Check the logs for the container, which now show duplicates.
5. If long running container as above, check the logs for promtail itself, which shows the 400 error.

**Expected behavior**
Promtail should only send the logs once.

**Environment:**
- Loki & Promtail v2.6.1
- Docker v20.10.17 (reproduced on both Swarm clusters and stand-alone instances)

**Screenshots, Promtail config, or terminal output**
```
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - regex: '__meta_docker_container_label_com_(docker_compose_(project|service))'
        replacement: '$1'
        action: labelmap
      - source_labels: [__meta_docker_container_label_com_docker_swarm_service_name]
        target_label: swarm_service
      - source_labels: [__meta_docker_container_label_com_docker_stack_namespace]
        target_label: swarm_stack
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container
    pipeline_stages:
      - docker: {}
      - static_labels:
          job: docker
```
