### ISSUE TITLE
Data source connected, but no labels received. Verify that Loki and Promtail is configured properly.

### ISSUE THREAD

**Issue by reyyzzy** [grafana/loki#7113]
Hi,im currently learning about loki,promtail and grafana and im facing with some issue rightnow, so i want to read nginx logs from another server,but i have an issue that my promtail unable to read my jobs and labels that i configure,then the loki,im running loki as a binary services,and its running but when i try to add the data source it says Data source connected, but no labels received. Verify that Loki and Promtail is configured properly. 

This is my config-promtail.yml 

```
server:
  http_listen_port: 9080
  grpc_listen_port: 9097

positions:
  filename: /tmp/positions.yaml

clients:
  - url: 'my:server:domain/loki/api/v1/push'

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
          host: grafana
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*log
          host: grafana
```

and this is the image where the promtail is failed to read nginx logs

![image](https://user-images.githubusercontent.com/89473810/189314440-690d649e-aea9-4ba1-a240-cb121a3dea25.png)

is anyone ever facing the similar issues?please help me,thank you!
