### ISSUE TITLE
Promtail Path exclude is not working as expected

### ISSUE THREAD

**Issue by sunil-saini** [grafana/loki#7115]
**Describe the bug**

Have `__path_exclude__:/logs/*/*[0-9][0-9]*` in `promtail.yaml` to ignore all files which have at least consecutively 2 numbers in name

still `/logs/app/app_2022-09-09.log` file is being tailed and pushed to loki

**To Reproduce**

1. add `__path_exclude__:/logs/*/*[0-9][0-9]*` in `promtail.yaml`
2. create file `/logs/app/app_2022-09-09.log`
3. file is tailed by promtail

**Expected behavior**

`/logs/app/app_2022-09-09.log` is matching pattern of __path_exclude__ , this should be excluded

**Environment:**

 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
promtail.yaml have
```yml
server:
    log_level: debug
    http_listen_port: 3101
scrape_configs:
    - job_name: applogs
    static_configs: 
        - targets: 
            - localhost 
        labels: 
            pod: POD_LABEL
            namespace: NS_LABEL
            app: APP_LABEL
            __path__: /logs/*/*.log
            __path_exclude__: /logs/app/*[0-9][0-9]*
```

**Comment by AdwitiyaMishra** [comment]
Hi @sunil-saini, I would like to work on this issue. Let me know if this can be assigned to me.

**Comment by sunil-saini** [comment]
hey @dannykopping able to find something around it

**Comment by skeespin** [comment]
Hi,
I have the same problem here. I am not a golang developer or an expert promtail user, but I have check the code. 
Perhaps, the next part of the message will help you to solve the problem.

A precision, this problem appear only when the file is created. If the file is updated after, it will be correctly excluded. 
I have the problem on logrotate files when the rotation is done (by copy). 

The function 'sendFileCreateEvent' in filetargetmanager.go that receive the event of creation file don't check if the path is excluded. I did a dirty hack to solve it and it seems to work (but I don't think his the best way to do) :

```
	for path, watcher := range s.fileEventWatchers {
		matched, err := doublestar.Match(path, event.Name)
		if err != nil {
			level.Error(s.log).Log("msg", "failed to match file", "error", err, "filename", event.Name)
			continue
		}
		if !matched {
			level.Debug(s.log).Log("msg", "new file does not match glob", "filename", event.Name)
			continue
		}
		for _, target := range s.targets {
			if target.path == path {
				matchedExclude, err := doublestar.Match(target.pathExclude, event.Name)
				if err != nil {
					level.Error(s.log).Log("msg", "failed to exclude file", "error", err, "filename", event.Name)
					continue
				}
				if matchedExclude {
					level.Debug(s.log).Log("msg", "new file is ecluded glob", "filename", event.Name)
					continue
				}
				watcher <- event
			}
		}
```
I have also updated doublestar in go.mod to avoid other problems.

Hope this is useful to you.

**Comment by nutslove** [comment]
I have the same problem here.
Any progress about this issue?

**Comment by okimiko** [comment]
I have the issue, too. Is there any progress or further information needed?

As stated by @skeespin the issue should be located in https://github.com/grafana/loki/blob/161fcac64643a03fb8c01e80d6986838413ed1d3/clients/pkg/promtail/targets/file/filetargetmanager.go#L416-L434 which clearly does not respect path_exclude.

PS: In general I was shocked about the limitations of doublestar; if something with a little bit more regex capabilities was used, path_exclude may have not been necessary.

**Comment by joyartoun** [comment]
This is causing a big issue for us as well. The point is to deploy promtail to a bunch of Linux servers and this is a real pain as we do not want to have historical logfiles creating a bunch of overhead in our Loki instance. 

Is there any update on this, has someone come up with a workaround?

**Comment by xpader** [comment]
This bug happend for me, promtail 2.9.1 on linux.

My config:
```
      __path__: /home/project/storage/logs/*.log
      __path_exclude__: /home/project/storage/logs/pay.log
```

I want to log all files with .log extension but without pay.log.
But pay.log still pushed to liki.

**Comment by xpader** [comment]
I found a way to do that like exclude use match.

__path__ instead of:
```yaml
- match
    selector: '{filename!~".*pay\\.log"}'
    stages:
```

If you want use other stages for pay.log,  like else for match, use:
```yaml
- match
    selector: '{filename=~".*pay\\.log"}'
    stages:
```
