### ISSUE TITLE
Loki 2.6.0 not connecting to Azure Blob Storage container 

### ISSUE THREAD

**Issue by verejoel** [grafana/loki#7170]
**Describe the bug**
Loki is not connecting to Azure Blob Storage. No data is written to the container, and error messages in the logs indicate the connection is not successful.

**To Reproduce**
1. Configure Loki as documented for Azure storage backend (configuration file below)
2. Deploy Loki in microservices architecture on Kubernetes with Helm
3. Check logs for ingester, distributor, querier, and query-frontend services.

**Expected behavior**
Loki connects to the Azure blob storage container and can read/write data.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: loki-distributed helm chart

**Screenshots, Promtail config, or terminal output**
 - I have tried hardcoding the base64 encoded `account_key` to rule out any problems with `-config.expand-env` argument.
 - We are behind Istio - egress rules have been added for the blob endpoint. A similar setup is working in another namespace for Thanos.

Loki distributed helm chart values:
```
  loki:
    appProtocol: tcp
    structuredConfig:
      common:
        storage:
          azure:
            account_key: ${STORAGE_ACCOUNT_KEY}
            account_name: REDACTED
            container_name: loki-default-gen1
            request_timeout: 0
      ingester:
        wal:
          enabled: true
          dir: /var/loki/wal
          replay_memory_ceiling: 750MB
    schemaConfig:
      configs:
        - from: 2020-09-07
          store: boltdb-shipper
          object_store: azure
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
    storageConfig:
      boltdb_shipper:
        shared_store: azure
        active_index_directory: /var/loki/data/loki/boltdb-shipper-active
        cache_location: /var/loki/data/loki/boltdb-shipper-cache
        cache_ttl: 24h

  ingester:
    appProtocol:
      grpc: tcp
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: loki-secrets
    max_transfer_retries: 0
    chunk_idle_period: 1h
    chunk_target_size: 1536000
    max_chunk_age: 1h
    persistence:
      enabled: true
      size: 20Gi
      storageClass: azuredisk-csi-standard-ssd-delete
```

Generated (relevant) Loki config:
```yaml
common:
  path_prefix: ""
  storage:
    azure:
      environment: AzureGlobal
      account_name: REDACTED
      account_key: '********'
      container_name: loki-default-gen1
      endpoint_suffix: ""
      use_managed_identity: false
      user_assigned_id: ""
      chunk_delimiter: '-'
      download_buffer_size: 512000
      upload_buffer_size: 256000
      upload_buffer_count: 1
      request_timeout: 0s
      max_retries: 5
      min_retry_delay: 10ms
      max_retry_delay: 500ms
    filesystem:
      chunks_directory: ""
      rules_directory: ""
  persist_tokens: false
  replication_factor: 3
ingester_client:
  pool_config:
    client_cleanup_period: 15s
    health_check_ingesters: true
    remote_timeout: 1s
  remote_timeout: 5s
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    grpc_compression: ""
    rate_limit: 0
    rate_limit_burst: 0
    backoff_on_ratelimits: false
    backoff_config:
      min_period: 100ms
      max_period: 10s
      max_retries: 10
    tls_enabled: false
    tls_cert_path: ""
    tls_key_path: ""
    tls_ca_path: ""
    tls_server_name: ""
    tls_insecure_skip_verify: false
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
        prefix: collectors/
        consul:
          host: localhost:8500
          acl_token: ""
          http_client_timeout: 20s
          consistent_reads: false
          watch_rate_limit: 1
          watch_burst_size: 1
          cas_retry_delay: 1s
        etcd:
          endpoints: []
          dial_timeout: 10s
          max_retries: 10
          tls_enabled: false
          tls_cert_path: ""
          tls_key_path: ""
          tls_ca_path: ""
          tls_server_name: ""
          tls_insecure_skip_verify: false
          username: ""
          password: ""
        multi:
          primary: ""
          secondary: ""
          mirror_enabled: false
          mirror_timeout: 2s
      heartbeat_timeout: 1m0s
      replication_factor: 1
      zone_awareness_enabled: false
      excluded_zones: ""
    num_tokens: 128
    heartbeat_period: 5s
    heartbeat_timeout: 1m0s
    observe_period: 0s
    join_after: 0s
    min_ready_duration: 15s
    interface_names:
    - eth0
    - lo
    final_sleep: 0s
    tokens_file_path: ""
    availability_zone: ""
    unregister_on_shutdown: true
    readiness_check_ring_health: true
    address: ""
    port: 0
    id: loki-distributor-64f7f667-72b86
  concurrent_flushes: 32
  flush_check_period: 30s
  flush_op_timeout: 10m0s
  chunk_retain_period: 1m0s
  chunk_idle_period: 30m0s
  chunk_block_size: 262144
  chunk_target_size: 1572864
  chunk_encoding: snappy
  max_chunk_age: 2h0m0s
  autoforget_unhealthy: false
  sync_period: 0s
  sync_min_utilization: 0
  max_returned_stream_errors: 10
  query_store_max_look_back_period: 0s
  wal:
    enabled: true
    dir: /var/loki/wal
    checkpoint_duration: 5m0s
    flush_on_shutdown: false
    replay_memory_ceiling: 786432000
  index_shards: 32
  max_dropped_streams: 10
storage_config:
  azure:
    environment: AzureGlobal
    account_name: REDACTED
    account_key: '********'
    container_name: loki-default-gen1
    endpoint_suffix: ""
    use_managed_identity: false
    user_assigned_id: ""
    chunk_delimiter: '-'
    download_buffer_size: 512000
    upload_buffer_size: 256000
    upload_buffer_count: 1
    request_timeout: 0s
    max_retries: 5
    min_retry_delay: 10ms
    max_retry_delay: 500ms
  boltdb:
    directory: ""
  filesystem:
    directory: /var/loki/chunks
  disable_broad_index_queries: false
  max_parallel_get_chunk: 150
  max_chunk_batch_size: 50
  boltdb_shipper:
    active_index_directory: /var/loki/data/loki/boltdb-shipper-active
    shared_store: azure
    shared_store_key_prefix: index/
    cache_location: /var/loki/data/loki/boltdb-shipper-cache
    cache_ttl: 24h0m0s
    resync_interval: 5m0s
    query_ready_num_days: 0
    index_gateway_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
        grpc_compression: ""
        rate_limit: 0
        rate_limit_burst: 0
        backoff_on_ratelimits: false
        backoff_config:
          min_period: 100ms
          max_period: 10s
          max_retries: 10
        tls_enabled: false
        tls_cert_path: ""
        tls_key_path: ""
        tls_ca_path: ""
        tls_server_name: ""
        tls_insecure_skip_verify: false
      log_gateway_requests: false
    ingestername: ""
    mode: RW
    ingesterdbretainperiod: 0s
    build_per_tenant_index: false
  tsdb_shipper:
    active_index_directory: ""
    shared_store: ""
    shared_store_key_prefix: index/
    cache_location: ""
    cache_ttl: 24h0m0s
    resync_interval: 5m0s
    query_ready_num_days: 0
    index_gateway_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
        grpc_compression: ""
        rate_limit: 0
        rate_limit_burst: 0
        backoff_on_ratelimits: false
        backoff_config:
          min_period: 100ms
          max_period: 10s
          max_retries: 10
        tls_enabled: false
        tls_cert_path: ""
        tls_key_path: ""
        tls_ca_path: ""
        tls_server_name: ""
        tls_insecure_skip_verify: false
      log_gateway_requests: false
    ingestername: ""
    mode: RW
    ingesterdbretainperiod: 0s
chunk_store_config:
  chunk_cache_config:
    enable_fifocache: true
    default_validity: 1h0m0s
    background:
      writeback_goroutines: 10
      writeback_buffer: 10000
    memcached:
      expiration: 0s
      batch_size: 1024
      parallelism: 100
    memcached_client:
      host: ""
      service: memcached
      addresses: ""
      timeout: 100ms
      max_idle_conns: 16
      max_item_size: 0
      update_interval: 1m0s
      consistent_hash: true
      circuit_breaker_consecutive_failures: 10
      circuit_breaker_timeout: 10s
      circuit_breaker_interval: 10s
    redis:
      endpoint: ""
      master_name: ""
      timeout: 500ms
      expiration: 0s
      db: 0
      pool_size: 0
      password: ""
      tls_enabled: false
      tls_insecure_skip_verify: false
      idle_timeout: 0s
      max_connection_age: 0s
    fifocache:
      max_size_bytes: 1GB
      max_size_items: 0
      ttl: 1h0m0s
      validity: 0s
      size: 0
      purgeinterval: 0s
    prefix: store.chunks-cache.
    async_cache_write_back_concurrency: 16
    async_cache_write_back_buffer_size: 500
  write_dedupe_cache_config:
    enable_fifocache: false
    default_validity: 1h0m0s
    background:
      writeback_goroutines: 10
      writeback_buffer: 10000
    memcached:
      expiration: 0s
      batch_size: 1024
      parallelism: 100
    memcached_client:
      host: ""
      service: memcached
      addresses: ""
      timeout: 100ms
      max_idle_conns: 16
      max_item_size: 0
      update_interval: 1m0s
      consistent_hash: true
      circuit_breaker_consecutive_failures: 10
      circuit_breaker_timeout: 10s
      circuit_breaker_interval: 10s
    redis:
      endpoint: ""
      master_name: ""
      timeout: 500ms
      expiration: 0s
      db: 0
      pool_size: 0
      password: ""
      tls_enabled: false
      tls_insecure_skip_verify: false
      idle_timeout: 0s
      max_connection_age: 0s
    fifocache:
      max_size_bytes: 1GB
      max_size_items: 0
      ttl: 1h0m0s
      validity: 0s
      size: 0
      purgeinterval: 0s
    prefix: store.index-cache-write.
    async_cache_write_back_concurrency: 16
    async_cache_write_back_buffer_size: 500
  cache_lookups_older_than: 0s
  max_look_back_period: 0s
schema_config:
  configs:
  - from: "2020-09-07"
    store: boltdb-shipper
    object_store: azure
    schema: v11
    index:
      prefix: loki_index_
      period: 1d
      tags: {}
    chunks:
      prefix: ""
      period: 0s
      tags: {}
    row_shards: 16
limits_config:
  ingestion_rate_strategy: global
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  max_label_name_length: 1024
  max_label_value_length: 2048
  max_label_names_per_series: 30
  reject_old_samples: true
  reject_old_samples_max_age: 1w
  creation_grace_period: 10m
  enforce_metric_name: false
  max_line_size: 0
  max_line_size_truncate: false
  increment_duplicate_timestamp: false
  max_streams_per_user: 0
  max_global_streams_per_user: 5000
  unordered_writes: true
  per_stream_rate_limit: 3145728
  per_stream_rate_limit_burst: 15728640
  max_chunks_per_query: 2000000
  max_query_series: 500
  max_query_lookback: 0s
  max_query_length: 30d1h
  max_query_parallelism: 32
  cardinality_limit: 100000
  max_streams_matchers_per_query: 1000
  max_concurrent_tail_requests: 10
  max_entries_limit_per_query: 5000
  max_cache_freshness_per_query: 10m
  max_queriers_per_tenant: 0
  query_ready_index_num_days: 0
  split_queries_by_interval: 15m
  min_sharding_lookback: 0s
  ruler_evaluation_delay_duration: 0s
  ruler_max_rules_per_rule_group: 0
  ruler_max_rule_groups_per_tenant: 0
  ruler_remote_write_disabled: false
  ruler_remote_write_url: ""
  ruler_remote_write_timeout: 0s
  ruler_remote_write_headers: {}
  ruler_remote_write_queue_capacity: 0
  ruler_remote_write_queue_min_shards: 0
  ruler_remote_write_queue_max_shards: 0
  ruler_remote_write_queue_max_samples_per_send: 0
  ruler_remote_write_queue_batch_send_deadline: 0s
  ruler_remote_write_queue_min_backoff: 0s
  ruler_remote_write_queue_max_backoff: 0s
  ruler_remote_write_queue_retry_on_ratelimit: false
  allow_deletes: false
  retention_period: 31d
  per_tenant_override_config: ""
  per_tenant_override_period: 10s
```

Ingester logs:
```
level=info ts=2022-09-15T10:23:27.511873316Z caller=main.go:103 msg="Starting Loki" version="(version=2.6.1, branch=HEAD, revision=6bd05c9a4)"
level=info ts=2022-09-15T10:23:27.512166414Z caller=server.go:288 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=warn ts=2022-09-15T10:23:27.512741811Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache - fifocache"
level=warn ts=2022-09-15T10:23:27.51282621Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache - chunksfifocache"
level=warn ts=2022-09-15T10:23:27.51290501Z caller=experimental.go:20 msg="experimental feature in use" feature="Azure Blob Storage"
level=warn ts=2022-09-15T10:23:27.51295761Z caller=experimental.go:20 msg="experimental feature in use" feature="Azure Blob Storage"
level=info ts=2022-09-15T10:23:27.513041109Z caller=shipper.go:124 msg="starting index shipper in WO mode"
level=info ts=2022-09-15T10:23:27.513448707Z caller=table_manager.go:134 msg="uploading tables"
level=info ts=2022-09-15T10:23:27.516375689Z caller=shipper_index_client.go:79 msg="starting boltdb shipper in WO mode"
level=info ts=2022-09-15T10:23:27.516448889Z caller=table_manager.go:167 msg="handing over indexes to shipper"
level=warn ts=2022-09-15T10:23:27.516497388Z caller=experimental.go:20 msg="experimental feature in use" feature="Azure Blob Storage"
level=info ts=2022-09-15T10:23:27.521481058Z caller=module_service.go:82 msg=initialising module=server
level=info ts=2022-09-15T10:23:27.521527858Z caller=module_service.go:82 msg=initialising module=memberlist-kv
level=info ts=2022-09-15T10:23:27.521556858Z caller=module_service.go:82 msg=initialising module=ring
level=info ts=2022-09-15T10:23:27.521578458Z caller=module_service.go:82 msg=initialising module=store
level=info ts=2022-09-15T10:23:27.521633357Z caller=ring.go:263 msg="ring doesn't exist in KV store yet"
level=info ts=2022-09-15T10:23:27.521669457Z caller=module_service.go:82 msg=initialising module=usage-report
level=info ts=2022-09-15T10:23:27.521728657Z caller=module_service.go:82 msg=initialising module=ingester
level=info ts=2022-09-15T10:23:27.521760857Z caller=ingester.go:401 msg="recovering from checkpoint"
level=info ts=2022-09-15T10:23:27.532107094Z caller=memberlist_client.go:534 msg="joined memberlist cluster" reached_nodes=2
level=info ts=2022-09-15T10:23:27.709221929Z caller=ingester.go:417 msg="recovered WAL checkpoint recovery finished" elapsed=187.466872ms errors=false
level=info ts=2022-09-15T10:23:27.709262229Z caller=ingester.go:423 msg="recovering from WAL"
level=info ts=2022-09-15T10:23:27.726173327Z caller=ingester.go:439 msg="WAL segment recovery finished" elapsed=204.41927ms errors=false
level=info ts=2022-09-15T10:23:27.726205127Z caller=ingester.go:387 msg="closing recoverer"
level=info ts=2022-09-15T10:23:27.726216727Z caller=ingester.go:395 msg="WAL recovery finished" time=204.46317ms
level=info ts=2022-09-15T10:23:27.726261826Z caller=lifecycler.go:547 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2022-09-15T10:23:27.726251126Z caller=wal.go:156 msg=started component=wal
level=info ts=2022-09-15T10:23:27.726319226Z caller=lifecycler.go:576 msg="instance not found in ring, adding with no tokens" ring=ingester
level=info ts=2022-09-15T10:23:27.726375126Z caller=loki.go:374 msg="Loki started"
level=info ts=2022-09-15T10:23:27.726407226Z caller=lifecycler.go:416 msg="auto-joining cluster after timeout" ring=ingester
level=error ts=2022-09-15T10:23:58.356703274Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/537e6557e355ebe7-18331424838-183316481f0-3a45c56e?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:23:58.381583906Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/6e9bbcd308cc2062-183367fb1cd-183368e3478-78906310?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:23:58.421428536Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/11bac131bf478181-18331821127-18331effae9-f653d78f?comp=blocklist&timeout=61\": EOF"
level=info ts=2022-09-15T10:24:27.514330552Z caller=table_manager.go:134 msg="uploading tables"
level=info ts=2022-09-15T10:24:27.516502638Z caller=table_manager.go:167 msg="handing over indexes to shipper"
level=error ts=2022-09-15T10:24:28.36278639Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/11bac131bf478181-18331821127-18331effae9-f653d78f?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:24:28.396392778Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/6e9bbcd308cc2062-183367fb1cd-183368e3478-78906310?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:24:28.408298602Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/537e6557e355ebe7-18331424838-183316481f0-3a45c56e?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:24:28.725417898Z caller=reporter.go:203 msg="failed to delete corrupted cluster seed file, deleting it" err="Delete \"https://REDACTED.blob.core.windows.net/loki-default-gen1/loki_cluster_seed.json?timeout=61\": EOF"
level=error ts=2022-09-15T10:24:58.31748167Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/6e9bbcd308cc2062-183367fb1cd-183368e3478-78906310?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:24:58.333507267Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/537e6557e355ebe7-18331424838-183316481f0-3a45c56e?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:24:58.388220814Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/11bac131bf478181-18331821127-18331effae9-f653d78f?comp=blocklist&timeout=61\": EOF"
level=info ts=2022-09-15T10:25:27.513912006Z caller=table_manager.go:134 msg="uploading tables"
level=info ts=2022-09-15T10:25:27.517342086Z caller=table_manager.go:167 msg="handing over indexes to shipper"
level=error ts=2022-09-15T10:25:28.34899018Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/6e9bbcd308cc2062-183367fb1cd-183368e3478-78906310?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:25:28.385400074Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/11bac131bf478181-18331821127-18331effae9-f653d78f?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:25:28.398034503Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/537e6557e355ebe7-18331424838-183316481f0-3a45c56e?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:25:58.380274496Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/11bac131bf478181-18331821127-18331effae9-f653d78f?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:25:58.401042477Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/6e9bbcd308cc2062-183367fb1cd-183368e3478-78906310?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:25:58.401125576Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/537e6557e355ebe7-18331424838-183316481f0-3a45c56e?comp=blocklist&timeout=61\": EOF"
level=info ts=2022-09-15T10:26:27.513582982Z caller=table_manager.go:134 msg="uploading tables"
level=info ts=2022-09-15T10:26:27.516985764Z caller=table_manager.go:167 msg="handing over indexes to shipper"
level=error ts=2022-09-15T10:26:28.374389741Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/537e6557e355ebe7-18331424838-183316481f0-3a45c56e?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:26:28.410665246Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/6e9bbcd308cc2062-183367fb1cd-183368e3478-78906310?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:26:28.479362875Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/11bac131bf478181-18331821127-18331effae9-f653d78f?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:26:58.304280129Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/11bac131bf478181-18331821127-18331effae9-f653d78f?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:26:58.328668905Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/6e9bbcd308cc2062-183367fb1cd-183368e3478-78906310?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:26:58.343181431Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/537e6557e355ebe7-18331424838-183316481f0-3a45c56e?comp=blocklist&timeout=61\": EOF"
level=info ts=2022-09-15T10:27:27.514445006Z caller=table_manager.go:134 msg="uploading tables"
level=info ts=2022-09-15T10:27:27.516750595Z caller=table_manager.go:167 msg="handing over indexes to shipper"
level=error ts=2022-09-15T10:27:28.382488817Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/11bac131bf478181-18331821127-18331effae9-f653d78f?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:27:28.435534862Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/6e9bbcd308cc2062-183367fb1cd-183368e3478-78906310?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:27:28.43801705Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/537e6557e355ebe7-18331424838-183316481f0-3a45c56e?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:27:43.988596046Z caller=reporter.go:203 msg="failed to delete corrupted cluster seed file, deleting it" err="Delete \"https://REDACTED.blob.core.windows.net/loki-default-gen1/loki_cluster_seed.json?timeout=61\": EOF"
level=error ts=2022-09-15T10:27:58.06654016Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: write error: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/537e6557e355ebe7-18331424838-183316481f0-3a45c56e?blockid=D1YVTno2SJy2ZRzOOJcL4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%3D%3D&comp=block&timeout=61\": EOF"
level=error ts=2022-09-15T10:27:58.411949916Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/6e9bbcd308cc2062-183367fb1cd-183368e3478-78906310?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:27:58.430307123Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/11bac131bf478181-18331821127-18331effae9-f653d78f?comp=blocklist&timeout=61\": EOF"
level=info ts=2022-09-15T10:28:27.513820284Z caller=table_manager.go:134 msg="uploading tables"
level=info ts=2022-09-15T10:28:27.517208467Z caller=table_manager.go:167 msg="handing over indexes to shipper"
level=info ts=2022-09-15T10:28:27.727344703Z caller=checkpoint.go:615 msg="starting checkpoint"
level=info ts=2022-09-15T10:28:27.727507502Z caller=checkpoint.go:340 msg="attempting checkpoint for" dir=/var/loki/wal/checkpoint.000819
level=error ts=2022-09-15T10:28:28.327003467Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/537e6557e355ebe7-18331424838-183316481f0-3a45c56e?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:28:28.392091837Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/6e9bbcd308cc2062-183367fb1cd-183368e3478-78906310?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:28:28.398657204Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/11bac131bf478181-18331821127-18331effae9-f653d78f?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:28:58.413592831Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/537e6557e355ebe7-18331424838-183316481f0-3a45c56e?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:28:58.440088658Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/11bac131bf478181-18331821127-18331effae9-f653d78f?comp=blocklist&timeout=61\": EOF"
level=error ts=2022-09-15T10:28:58.440088658Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: Put \"https://REDACTED.blob.core.windows.net/loki-default-gen1/fake/6e9bbcd308cc2062-183367fb1cd-183368e3478-78906310?comp=blocklist&timeout=61\": EOF"
```
