### ISSUE TITLE
[promtail] support scraping from Kubernetes API

### ISSUE THREAD

**Issue by barrettj12** [grafana/loki#7205]
**Is your feature request related to a problem? Please describe.**
Promtail supports generating scrape targets using the K8s API (`kubernetes_sd_configs`). It can get node/pod/container names from the K8s API and use these to generate `__path__` for logfiles to scrape. But AFAIK, it can't get **the logs themselves** from the K8s API.

> while Promtail can utilize the Kubernetes API to discover pods as targets, it can only read log files from pods that are running on the same node as the one Promtail is running on.

The usual pattern for k8s containers is stream logs to stdout, then k8s / the container engine will save these for you. The saved logs are then accessible via `kubectl logs`. It makes sense for Promtail to get logs the same way.

**Describe the solution you'd like**
A new type of `scrape_config` which directs Promtail to scrape from the Kubernetes API. This would be analogous to e.g. scraping from the journal. This could be used effectively in combination with the existing `kubernetes_sd_configs`. Something like:

```yaml
scrape_configs:
  - job_name: k8s-logs
    kubernetes_sd_configs:
      - role: pod
    kubernetes_api:
      namespace: ...
      pod: __meta_kubernetes_pod_name
      container: __meta_kubernetes_pod_container_name
    relabel_configs:
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
```

**Describe alternatives you've considered**
The alternative recommended in the [Promtail docs](https://grafana.com/docs/loki/latest/clients/promtail/installation/#sidecar) is to use a hostPath volume mount to the logs directory on the host (`/var/log/pods` and/or `/var/log/containers`). However, from the [k8s docs](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath):
> HostPath volumes present many security risks, and it is a best practice to avoid the use of HostPaths when possible.

It would be safer to use the Kube API, considering it already has a mechanism for capturing and serving logs. It also feels kinda hacky mounting `/var/log/pods` to our Promtail container.

**Additional context**
The Kubernetes API provides a [method to read logs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#read-log-pod-v1-core). This would be the best way to scrape the logs. I assume `kubectl log` internally uses this same API endpoint.
