### ISSUE TITLE
Duplicate logs in loki

### ISSUE THREAD

**Issue by cretzel** [grafana/loki#7207]
**Describe the bug**
We see duplicate log message in grafana with loki. We are using kubernetes and promtail. We first thought this might be related to promtail config but after investigation it seems that promtail actually sends the logs only once. So we are pretty sure the issue is related to loki.

**To Reproduce**

**Expected behavior**
Log entries should only appear once.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Loki version: 2.6.1

**Screenshots, Promtail config, or terminal output**
Loki config
```
auth_enabled: false

server:
  http_listen_port: 3100

limits_config:
  retention_period: 31d

compactor:
  working_directory: /loki/retention
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

```

Loki HTTP API response
```
curl -G -s  "http://localhost:64747/loki/api/v1/query"   --data-urlencode 'query={job="xxx/xxx"} |= "XXX321"' | jq
{
  "status": "success",
  "data": {
    "resultType": "streams",
    "result": [
      {
        "stream": {
          "stream": "stdout",
          "app_kubernetes_io_instance": "xxx",
          "filename": "/var/log/pods/xxx/xxx/0.log",
          "level": "DEBUG",
          "log": "json",
          "namespace": "xxx",
          "pdb": "xxx-xxx",
          "pod_template_hash": "5784787cb9",
          "app_kubernetes_io_name": "xxx",
          "container_name": "xxx",
          "instance": "xxx-5784787cb9-vhjgt",
          "job": "xxx/xxx"
        },
        "values": [
          [
            "1663747467420000000",
            "[http-nio-8080-exec-8] DEBUG xxx (name=XXX321)"
          ],
          [
            "1663747467420000000",
            "[http-nio-8080-exec-8] DEBUG xxx (name=XXX321)"
          ]
        ]
      }
    ],
    "stats": {
      "summary": {
        "bytesProcessedPerSecond": 11530768,
        "linesProcessedPerSecond": 66014,
        "totalBytesProcessed": 12751,
        "totalLinesProcessed": 73,
        "execTime": 0.001105824,
        "queueTime": 5.7501e-05,
        "subqueries": 1,
        "totalEntriesReturned": 2
      },
      "querier": {
        "store": {
          "totalChunksRef": 0,
          "totalChunksDownloaded": 0,
          "chunksDownloadTime": 0,
          "chunk": {
            "headChunkBytes": 0,
            "headChunkLines": 0,
            "decompressedBytes": 0,
            "decompressedLines": 0,
            "compressedBytes": 0,
            "totalDuplicates": 0
          }
        }
      },
      "ingester": {
        "totalReached": 1,
        "totalChunksMatched": 4,
        "totalBatches": 1,
        "totalLinesSent": 2,
        "store": {
          "totalChunksRef": 0,
          "totalChunksDownloaded": 0,
          "chunksDownloadTime": 0,
          "chunk": {
            "headChunkBytes": 12751,
            "headChunkLines": 73,
            "decompressedBytes": 0,
            "decompressedLines": 0,
            "compressedBytes": 0,
            "totalDuplicates": 0
          }
        }
      }
    }
  }
}
```
