### ISSUE TITLE
missing logs in loki

### ISSUE THREAD

**Issue by isshwar** [grafana/loki#7219]
issue: logs missing in loki

description: I am in the process of migrating from ELK to Loki. I have set up Loki in distributed mode and container S3 as log storage.  All services are working fine but when I compare logs between Loki and already running ELK, i see a lot of logs missing in Loki. This is a show stopper from going further with Loki set up.

Thanks
Eswar

**Comment by dannykopping** [comment]
Thank you for your question / support request.
We try to keep GitHub issues strictly for bug reports and feature requests.

You may submit questions and support requests in any of the following ways:
  - On our [community forum](https://community.grafana.com/c/grafana-loki/41)
  - To our [mailing list](https://groups.google.com/forum/#!forum/lokiproject)
  - In `#loki` in [Grafana's Public Slack](https://slack.grafana.com/)

I'm closing this issue, but please feel free to reach out in any of the channels listed above.

**Comment by DylanGuedes** [comment]
@isshwar first of all, thanks for reporting the issue.
unfortunately, it is extremely hard to investigate or take any conclusions from what you described because you didn't share anything that can be used to replicate the issue.
You concluded that it is Loki missing logs but another way of seeing it is concluding that ELK is duplicating the logs.
All that said, if you really think this is a Loki bug, please do share more info so the team can have a better look at it.

**Comment by isshwar** [comment]
@DylanGuedes thanks for the reply. let me summarize with a write up on what had been noticed so far. While, I am not saying that the issue is with Loki but cannot rule out as I could not find any other reason why the logs are not showing up. 

1.  I have fluent-bit running in our kubernetes set up with the config file outputting to both Loki and Elastic. Config below.
````yaml
[SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf
    @INCLUDE output-loki.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://k3s-master00:6443
        Kube_CA_File       ca.crt
        Kube_Token_File    token
        Kube_Tag_Prefix     kube.var.log.containers.
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
    [FILTER]
        Name      parser
        Match     kube.*
        Key_Name  log
        Parser    cri_javaapplog
        Reserve_Data On
    [FILTER]
        Name      parser
        Match     kube.*
        Key_Name  message
        Parser    json
        Reserve_Data On
        Preserve_Key On
    [FILTER]
        Name      lua
        Match     kube.*
        script    set_logstash_index_name.lua
        call      set_logstash_index_name
    [FILTER]
        Name      lua
        Match     kube.*
        script    set_env.lua
        call      set_env
    [FILTER]
        Name      lua
        Match     kube.*
        script    set_app.lua
        call      set_app

  set_logstash_index_name.lua: |
    function set_logstash_index_name(tag, timestamp, record)
      prefix = "logstash-k3s-test"
      if record["kubernetes"]["labels"]["app"] ~= nil then
        record["logstash_index_name"] = prefix
          .. "-"
          .. record["kubernetes"]["labels"]["app"]
        return 1, timestamp, record
      elseif record["kubernetes"]["labels"]["name"] ~= nil then
        record["logstash_index_name"] = prefix
          .. "-"
          .. record["kubernetes"]["labels"]["name"]
        return 1, timestamp, record
      elseif record["kubernetes"]["labels"]["k8s-app"] ~= nil then
        record["logstash_index_name"] = prefix
          .. "-"
          .. record["kubernetes"]["labels"]["k8s-app"]
        return 1, timestamp, record
      end
      return 1, timestamp, record
    end

  set_env.lua: |
    function set_env(tag, timestamp, record)
      local namespace = record["kubernetes"]["namespace_name"]
      if namespace then
        env = namespace:gsub("-.*$", "")
        record ["env"] = env
      end
      return 1, timestamp, record
    end

  set_app.lua: |
    function set_app(tag, timestamp, record)
      if record["kubernetes"]["labels"]["app"] ~= nil then
        record["app"] = record["kubernetes"]["labels"]["app"]
      elseif record["kubernetes"]["labels"]["k8s-app"] ~= nil then
        record["app"] = record["kubernetes"]["labels"]["k8s-app"]
      end
      return 1, timestamp, record
    end

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Logstash_Prefix logstash-k3s-test
        Logstash_Prefix_Key logstash_index_name
        Replace_Dots    On
        Retry_Limit     False
        net.keepalive   on
        Trace_Error     On
        Buffer_Size     1MB
        Generate_ID     on
        Type            doc

  output-loki.conf: |
    [OUTPUT]
        Name            loki
        Match           *
        Host            ${LOKI_HOST}
        Port            ${LOKI_PORT}
        http_user       ${LOKI_USER}
        http_passwd     ${LOKI_PASSWORD}
        labels          instance=$kubernetes['pod_name'],env=$env,app=$app
        tls             on

  parsers.conf: |
    [PARSER]
        Name   json
        Format json

    [PARSER]
        # http://rubular.com/r/tjUt3Awgg4
        Name cri_javaapplog
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>((?<apptime>\d{4}[-\/]\d{2}[-\/]\d{2} \d{2}:\d{2}:\d{2}\.\d{3})\s*(?<loglevel>\S*)\s*\[(?<project_name>[a-zA-Z ]*),(?<requestid>[a-z0-9]{16}),(?<spanid>[a-z0-9]{16}),(?<exportflag>[a-z]*)\].*\[(?<threadname>.*)\] (?<javaclass>\S*)\s*: (?<information>.*)|.*))$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep   On
````
2. It is not Elastic is duplicating the logs because we have trace_id generated by apps and i see some logs (trace_ids) missing in Loki. we have been Elastic since ages and can conclude it is not duplicating the logs. screenshot taken from Elastic and Loki
<img width="665" alt="image" src="https://user-images.githubusercontent.com/25328386/191744026-e45de75a-d3ef-4fdb-9f19-19f2fdc1602c.png">
![image](https://user-images.githubusercontent.com/25328386/191744090-9623a5e3-5506-408a-84f8-22aed48f5dde.png)
3. I have updated the config, increased the number of replicas of ingesteer, stopped logs from prod cluster to test some network bottlenecks, no errors on Fluent-bit, Loki pods. Got stuck and could not move ahead with the issue. 
```
```yaml
    auth_enabled: false
    compactor:
      shared_store: s3
      working_directory: /data/loki/compactor
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      compactor_ring:
        kvstore:
          store: memberlist
    distributor:
      ring:
        kvstore:
          store: memberlist
    frontend:
      compress_responses: true
      log_queries_longer_than: 20s
    frontend_worker:
      frontend_address: loki-query-frontend:9095
      grpc_client_config:
        max_send_msg_size: 17179869184  # 16GiB
        max_recv_msg_size: 17179869184
    querier:
     engine:
         timeout: 5m
         max_look_back_period: 30s
     query_timeout: 30m
     query_ingesters_within: 10m
     max_concurrent: 20
    ingester:
      concurrent_flushes: 128
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_idle_period: 30m
      chunk_retain_period: 1m
      max_chunk_age: 120m
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /data/loki/wal
    limits_config:
      max_entries_limit_per_query: 0
      ingestion_rate_strategy: global
      reject_old_samples: false
      ingestion_rate_mb: 100
      ingestion_burst_size_mb: 100
      max_cache_freshness_per_query: 10m
      creation_grace_period: 1m
      enforce_metric_name: false
      reject_old_samples_max_age: 12h
      split_queries_by_interval: 120m
      max_query_parallelism: 900
      max_query_series: 1000
      increment_duplicate_timestamp: true
    memberlist:
      join_members:
        - loki-memberlist
    query_range:
      align_queries_with_step: true
      parallelise_shardable_queries: true
      cache_results: true
      max_retries: 5
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h
    ruler:
      alertmanager_url: ${ALERTMANAGER_URL}
      ring:
        kvstore:
          store: memberlist
      rule_path: /var/loki/rules-tmp
      storage:
        local:
          directory: /loki/rules
        type: local
      enable_api: true
      enable_alertmanager_v2: true
      enable_sharding: true

      alertmanager_client:
        basic_auth_username: "${ALERTMANAGER_USERNAME}"
        basic_auth_password: "$${q}{ALERTMANAGER_PASSWORD}"
    schema_config:
      configs:
        - from: 2022-06-01
          index:
            period: 24h
            prefix: loki_index_
          object_store: s3
          schema: v11
          store: boltdb-shipper
    server:
      http_listen_port: 3100
      log_level: info
      grpc_server_max_recv_msg_size: 8388608
      grpc_server_max_send_msg_size: 8388608
      http_server_write_timeout: 10m
      http_server_read_timeout: 10m
      http_server_idle_timeout: 10m
      graceful_shutdown_timeout: 2m
    tracing:
      enabled: false
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/cache
        index_gateway_client:
          server_address: dns:///loki-index-gateway:9095
        shared_store: s3
      aws:
        access_key_id: ${S3_ACCESS_KEY_ID}
        bucketnames: ${S3_BUCKET_NAME}
        endpoint: http://pure-storage.pageplace.de
        s3forcepathstyle: true
        secret_access_key: $${q}{S3_SECRET_ACCESS_KEY}
        http_config:
          response_header_timeout: 5s
          insecure_skip_verify: true
    chunk_store_config:
      max_look_back_period: 0s
```

Please, let me know if you want more information. 

Thanks
