### ISSUE TITLE
grafana/loki-simple-scalable writer replicas issue with Grafana

### ISSUE THREAD

**Issue by mrszop** [grafana/loki#7220]
**Describe the bug**
Hello. I am using [grafana/loki-simple-scalable 1.8.11](https://artifacthub.io/packages/helm/grafana/loki-simple-scalable) Helm chart for my setup and I tried to set writer replicas to 1:

```yaml
 write:
  replicas: 1
```

which seem to work fine, but throws an error when trying to add Loki as a datasource in Grafana. When I turn back writter replicas to 3, everything works find and I can add Loki as a datasource in Grafana.

**To Reproduce**
1. use [grafana/loki-simple-scalable 1.8.11](https://artifacthub.io/packages/helm/grafana/loki-simple-scalable) Helm chart
2. take my values.yaml:

```yaml
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 3
read:
  replicas: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
gateway:
  enabled: true
  replicas: 1
  verboseLogging: true
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
monitoring:
  selfMonitoring:
    enabled: false
write:
  replicas: 1
```

3. try to add Loki in your Grafana installation as new datasource

<img width="974" alt="grafana_add_loki_datasource" src="https://user-images.githubusercontent.com/28673899/191702891-8f0f48c2-6f62-4e38-9500-0694e309685d.png">

**Expected behavior**

Be able to add Loki as datasource.

**Environment:**
 - Infrastructure: k8s GKE v1.22.12-gke.300
 - Deployment tool: [grafana/loki-simple-scalable 1.8.11](https://artifacthub.io/packages/helm/grafana/loki-simple-scalable)

I have also noticed, that if I set loki.commonConfig.replication_factor to below 3, I am able to add the datasource

```yaml
loki:
  commonConfig:
    replication_factor: # 1 - 2 works, 3 doesn't
```

Cheers,
Szop
