### ISSUE TITLE
loki forces user to configure a `compactor_address` if target=querier

### ISSUE THREAD

**Issue by Frefreak** [grafana/loki#7222]
**Describe the bug**
During experimenting with loki (_main_ branch) I notice loki refuses start when run with `target=querier` unless I configure a `compactor_address` in the querier config, even if I disabled deletion mode in the `limits_config`.

Error: `level=error ts=2022-09-22T09:40:35.884893155Z caller=log.go:103 msg="error running loki" err="query filtering for deletes requires 'compactor_address' to be configured` 

I bisected and find its starting with this commit: bd3d80ad80445a20d7c0b5860b001bc9be557a47 which is #6854

From the docs it says `deletion_mode` field in compactor config is removed, so I thought I should configure it in limits_config's deletion_mode.
However it doesn't work either. 

**To Reproduce**

with this config:

```yaml
server:
  http_listen_port: 3100

storage_config:
  aws:
    s3: http://user:pass@127.0.0.1:9000/data
    s3forcepathstyle: true
    insecure: true
  boltdb_shipper:
    active_index_directory: /tmp/
    cache_location: /tmp/
    shared_store: s3

schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: index_
        period: 24h
auth_enabled: false
common:
  ring:
    kvstore:
      store: memberlist
  replication_factor: 1
limits_config:
  deletion_mode: disabled
ingester:
  wal:
    enabled: false
  chunk_encoding: snappy
```

cmdline: `cmd/loki/loki -config.file=dev.yaml -target=querier`

**Expected behavior**
Loki starts normally (or spit out some other error due to another configuration error), but not this error. I don't even have a compactor at all and loki shouldn't force me to specify one. Even if the limits_config deletion_mode works, I think the default should be **disabled** instead of **filter-and-delete**

**Environment:**
 - Infrastructure: linux desktop
 - Deployment tool: just command line

this is master (main) branch though
```
loki, version main-5e134f3 (branch: main, revision: 5e134f3b6)
```
**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/7122156/191717011-f15d5161-5568-4f45-bdbe-c81184b207c1.png)

![image](https://user-images.githubusercontent.com/7122156/191718118-4989b5e2-6064-441f-b977-bc0296c5d54d.png)
