### ISSUE TITLE
[Helm] Cannot install `loki` helm chart in ArgoCD due to hooks

### ISSUE THREAD

**Issue by fernferret** [grafana/loki#7237]
**Describe the bug**
With the following values file, I'm unable to install Loki with ArgoCD. This is because of the Helm Hook on the `loki-canary` service account:

```yaml
  annotations:
    "helm.sh/hook": post-install
```

Argo will wait for the `loki-canary` daemonset to finish deploying before it runs the post-hooks, which never happens since the daemonset will error with:

```
Error creating: pods "loki-canary-" is forbidden: error looking up service account metrics/loki-canary: serviceaccount "loki-canary" not found
```

This places the deployment of the application in a deadlock.

**To Reproduce**
1. Apply the following application yaml which will install loki with the following values file
2. The installation will stall and fail since the daemonset never deploys due to it waiting on the service account.

```yaml
fullnameOverride: loki

monitoring:

  # Self Monitoring requires the GrafanaAgent. I'm intrested in this but want to
  # get loki working again just stock for now.
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false

write:
  persistence:
    storageClass: "local-path"

read:
  persistence:
    storageClass: "local-path"
```

The ArgoCD application file is:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo
spec:
  destination:
    namespace: metrics
    server: https://kubernetes.default.svc
  project: my-project
  source:
    helm:
      skipCrds: true
      valueFiles:
      - ../../metrics/loki.yaml
    path: oss/loki
    repoURL: https://github.com/fernferret/offline_charts.git
    targetRevision: main
```

**Expected behavior**
I expect the deployment to finish and the daemonset to start

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm + ArgoCD
 - Helm Chart version: `3.1.0`

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Workaround**
I was able to "trick" Argo into installing the service account first via the `PreSync` annotation. This overrides the Helm Hooks and causes the deployment to succeed.

```yaml
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
    lokiCanary:
      annotations:
        argocd.argoproj.io/hook: PreSync
```

* I do have concerns/reservations, why was the initial helm hook placed on the service account?
* Is there a reason the daemonset should not be deployed until a post-hook?
* Should the hook be on the daemonset instead?
* Did my disabling of the `selfMonitoring` and `grafanaAgent` cause this?

I'm trying to migrate from a **very** old loki setup, so I wanted to play with things in isolation first. I'm very keen to try out `grafanaAgent` and the `selfMonitoring` setup but wanted to get loki operational first, then add in the extra bits.
