### ISSUE TITLE
error initializing stream - i/o timeout

### ISSUE THREAD

**Issue by silveraignacio** [grafana/loki#7259]
**Describe the bug**
I have promtail configured to use syslog module. Syslog module is configured to listen on port 1514 and syslog-ng pod is sending information to promtail. It has the following config:

```
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:1514
      idle_timeout: 180s
      label_structured_data: yes
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
      - source_labels: ['__syslog_connection_ip_address']
        target_label: 'remote_ip'
      - source_labels: ['__syslog_connection_hostname']
        target_label: 'conn_host'
      - source_labels: ['__syslog_message_severity']
        target_label: 'msg_sev'
      - source_labels: ['__syslog_message_facility']
        target_label: 'facility'
      - source_labels: ['__syslog_message_app_name']
        target_label: 'app'
      - source_labels: ['__syslog_message_proc_id']
        target_label: 'proc_id'
      - source_labels: ['__syslog_message_msg_id']
        target_label: 'msg_id'
```
I'm getting the following error in the logs sporadically:
```
level=warn ts=2022-09-27T09:10:39.138664007Z caller=transport.go:285 msg="error initializing syslog stream" err="read tcp 10.233.124.134:1514->10.233.124.133:36183: i/o timeout"
level=warn ts=2022-09-27T09:27:09.692325767Z caller=transport.go:285 msg="error initializing syslog stream" err="read tcp 10.233.124.134:1514->10.233.73.91:37417: i/o timeout"
level=warn ts=2022-09-27T09:34:15.781156207Z caller=transport.go:285 msg="error initializing syslog stream" err="read tcp 10.233.124.134:1514->10.233.112.231:45903: i/o timeout"
level=warn ts=2022-09-27T09:45:06.505257631Z caller=transport.go:285 msg="error initializing syslog stream" err="read tcp 10.233.124.134:1514->10.233.113.125:43885: i/o timeout"
level=warn ts=2022-09-27T09:54:13.843961214Z caller=transport.go:285 msg="error initializing syslog stream" err="read tcp 10.233.124.134:1514->10.233.123.66:37445: i/o timeout"
level=warn ts=2022-09-27T10:02:40.601312Z caller=transport.go:285 msg="error initializing syslog stream" err="read tcp 10.233.124.134:1514->10.233.124.133:34735: i/o timeout"
level=warn ts=2022-09-27T10:34:31.751182729Z caller=transport.go:285 msg="error initializing syslog stream" err="read tcp 10.233.124.134:1514->10.233.112.231:45699: i/o timeout"
level=warn ts=2022-09-27T10:35:00.137274397Z caller=transport.go:285 msg="error initializing syslog stream" err="read tcp 10.233.124.134:1514->10.233.73.91:34443: i/o timeout"
level=warn ts=2022-09-27T10:41:08.500277216Z caller=transport.go:285 msg="error initializing syslog stream" err="read tcp 10.233.124.134:1514->10.233.113.125:38549: i/o timeout"
```
I have it deployed on 8 worker nodes, and all of them are showing the same issue (of course varying the IP). The IP after the "->" corresponds to some syslog pod. I do not understand why promtail want to reach syslog pod if is syslog who should initiate the traffic

**To Reproduce**
1. Deploy syslog-ng on K8s cluster and configure to send logs to promtail
2. Configure promtail to receive syslog messages
3. Once the connection is done, wait for the error

**Expected behavior**
No timeout should be found

**Environment:**
 - Infrastructure: Kubernetes cluster on VMs and Minikube
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
