### ISSUE TITLE
Helm Loki 3.2.0 Fails to Install

### ISSUE THREAD

**Issue by jseiser** [grafana/loki#7267]
**Describe the bug**
Working Single Binary install for 3.0.0, fails to run when deployed as 3.2.0

**To Reproduce**

```yaml
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
monitoring:
  alerts:
    enabled: true
    labels:
      release: kube-prometheus-stack
  dashboards:
    enabled: true
    labels:
      release: kube-prometheus-stack
  rules:
    enabled: true
    labels:
      release: kube-prometheus-stack
  selfMonitoring:
    enabled: false
  serviceMonitor:
    enabled: true
    interval: 1m
    labels:
      release: kube-prometheus-stack
    scrapeTimeout: 10s
singleBinary:
  persistence:
    enabled: true
    size: 100Gi
    storageClass: efs-sc
```

**Expected behavior**
Deployed

**Environment:**
 - EKS
 - Flux/Helm

**Screenshots, Promtail config, or terminal output**
```
[ec2-user@ip-10-17-1-39 ~]$ kubectl logs pod/loki-0 -n monitoring
level=error ts=2022-09-27T13:32:24.608662713Z caller=main.go:51 msg="validating config" err="invalid ruler config: invalid ruler store config: invalid Azure Storage config: unsupported Azure blob storage environment: , please select one of: AzureGlobal, AzureChinaCloud, AzureGermanCloud, AzureUSGovernment "
```

**Comment by dbirks** [comment]
Was just going to open an issue for this as well. In my case, it's with a fresh install of helm chart 3.2.0, with the values:
```yaml
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  compactor:
    retention_enabled: true
  limits_config:
    retention_period: 180d
rulerConfig:
  storage:
    type: local
singleBinary:
  persistence:
    enabled: true
    size: 30Gi
    storageClass: efs
  replicas: 1
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: private
    hosts:
      - loki.example.com
```
And same error:
```
invalid ruler config: invalid ruler store config: invalid Azure Storage config: unsupported Azure blob storage environment: , please select one of: AzureGlobal, AzureChinaCloud, AzureGermanCloud, AzureUSGovernment 
```

**Comment by fyannk** [comment]
was about to open it as well.

Managed to make it work by specifying a storage for ruler :

```yaml
loki:
    storage:
      type: 'filesystem'
    rulerConfig:
      storage:
        type: local
```

imho you misplaced rulerConfig, it must be under loki.
