### ISSUE TITLE
[Helm] Read/Write instances fail to reach STS

### ISSUE THREAD

**Issue by hkupty** [grafana/loki#7269]
**Describe the bug**
After deploying with the latest helm chart (`3.2.0`) and migrating to read/write instances instead of a single binary, both instances now fail authenticate due to being unable to reach sts (logs below)

**To Reproduce**
- Configure loki to run single-binary, with storage in s3;
- update helm chart and deploy with `3.2.0`;
- break single-binary to read/write instances;

(worth noting, maybe not necessarily related to read/write, but appeared to work w/ single-binary and helm chart 3.2.0)

**Expected behavior**
Like before the migration, loki would be able to get access to S3 through the `serviceAccount` 

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**

Helm chart values:
```
global:
  dnsService: "coredns"

loki:
  rulerConfig:
    storage:
      type: local
      local:
        directory: /tmp

config:
  compactor:
    shared_store: s3
    retention_enabled: true

  schema_config:
    configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
        tags: {}

  storage_config:
    boltdb_shipper:
      shared_store: s3
    aws:
      s3: s3://xxxxxxxxxx
      region: eu-north-1
      sse_encryption: true
      s3forcepathstyle: true

  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 120d

write:
  replicas: 1
  nodeSelector:
    role: xxx

read:
  replicas: 1
  nodeSelector:
    role: xxx

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxxx:role/LokiAccess
```

Logs from loki-read:
```
level=error ts=2022-09-27T16:12:58.551881337Z caller=reporter.go:203 msg="failed to delete corrupted cluster seed file, deleting it" err="WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.dummy.amazonaws.com/\": dial tcp: lookup sts.dummy.amazonaws.com on 172.20.0.10:53: no such host" level=info ts=2022-09-27T16:13:14.848979553Z caller=memberlist_client.go:563 msg="joined memberlist cluster" reached_nodes=1
```
