### ISSUE TITLE
Allow for multiple store configurations from the same provider

### ISSUE THREAD

**Issue by dannykopping** [grafana/loki#7276]
**Is your feature request related to a problem? Please describe.**
Loki currently supports [period_configs](https://grafana.com/docs/loki/latest/configuration/#period_config) for specifying index & chunk schema changes over time. A user can select a `store` with each config, and this effectively allows users to switch providers should they need to. Queries that span multiple periods will route requests to the appropriate store.

Example:

```yaml
storage_config:
    azure:
        account_key: ${AZURE_BLOB_SECRET_ACCESS_KEY}
        account_name: lokiprod
        container_name: data

schema_config:
    configs:
        - from: "2020-07-31"
            index:
            period: 24h
            prefix: loki_prod_index_
            object_store: azure
            schema: v11
            store: boltdb-shipper
        - from: "2022-01-24"
            index:
            period: 24h
            prefix: loki_prod_index_
            object_store: azure
            schema: v12 # <-- changed from v11 to v12
            store: boltdb-shipper
```

We currently do not support multiple store configurations for the _same_ provider, however.

At Grafana Labs, we require this feature due to a misconfiguration of an Azure Blob bucket. Its replication policy was set to be [LRS](https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy#locally-redundant-storage) (locally redundant within a zone), but we actually need it to be [ZRS](https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy#zone-redundant-storage) (zonally redundant within a region). Migrating the data from one bucket to another is impractical and slow, so we would prefer to setup a new bucket, and read/write new chunks/indexes to this bucket. Data in the old bucket will be deleted according to its [retention period](https://grafana.com/docs/loki/latest/configuration/#limits_config).

**Describe the solution you'd like**
I would like to be able to define multiple store configurations from the same provider, and use these configurations within [period_configs](https://grafana.com/docs/loki/latest/configuration/#period_config) definitions.

Additionally, if we could add a path prefix to prepend to all path lookups in the bucket, that would also solve some outstanding feature-requests (listed below), and it seems like related work. _This is not required to deliver on the main value of this ticket, but it might be possible with some drive-by refactoring that needs to be done anyway._

```yaml
storage_config:
    azure:
        account_key: ${AZURE_BLOB_SECRET_ACCESS_KEY}
        account_name: lokiprod
        container_name: data
        type: azure # <--- new "type" field, derive from key name for backwards-compatibility?
    azure-new:
        account_key: ${AZURE_BLOB_SECRET_ACCESS_KEY}
        account_name: lokiprod
        container_name: data
        chunk_path: "/path/to/chunks" # <--- new prefix (optional)
        index_path: "/path/to/indexes" # <--- new prefix (optional)
        type: azure

schema_config:
    configs:
        - from: "2020-07-31"
            index:
            period: 24h
            prefix: loki_prod_index_
            object_store: azure
            schema: v11
            store: boltdb-shipper
        - from: "2022-01-24"
            index:
            period: 24h
            prefix: loki_prod_index_
            object_store: azure
            schema: v12 # <-- changed from v11 to v12
            store: boltdb-shipper
        - from: "2022-09-29"
            index:
            period: 24h
            prefix: loki_prod_index_
            object_store: azure-new # <-- changed to use new object store
            schema: v12
            store: boltdb-shipper
```

**Describe alternatives you've considered**
There is no meaningful alternative right now.

**Additional context**
Related issues: #5889, possibly even #5757

I've [hacked up a basic implementation](https://github.com/grafana/loki/compare/main...dannykopping:loki:dannykopping/multistore) which works, but it's very rough. It also adds to the `common -> storage` config, which I think might be a better place for this than `storage_config`, but I'm not sure what'll work out to be easiest or most useful.
