### ISSUE TITLE
Helm chart - S3 credentials via role-based access and k8s annotations not honored

### ISSUE THREAD

**Issue by ralbon** [grafana/loki#7279]
**Describe the bug**
Loki deployed in AWS EKS (1.23) doesn't assume AWS IAM role to manage s3 object storage configured.

**To Reproduce**
1. Deploy an AWS Role with correct policy to be assumed by Kubernetes serviceaccount
2. Use chart from `helm-loki-3.2.0` with values bellow:
```
...
  loki:
    auth_enabled: false
    storage:
      type: s3
      bucketNames:
        chunks: <mybucket>
        ruler: <mybucket>
      s3:
        endpoint: "https://s3.<region>.amazonaws.com"
        region: "<region>"
        insecure: false

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn:  "<myarn>"
...
```

**terminal output**

However, read and write pod start with errors saying it cannot access to storage.
```
rpc error: code = Unknown desc = WebIdentityErr: failed to retrieve credentials
caused by: SerializationError: failed to unmarshal error message
        status code: 405, request id:
caused by: UnmarshalError: failed to unmarshal error message
        00000000  3c 3f 78 6d 6c 20 76 65  72 73 69 6f 6e 3d 22 31  |<?xml version="1|
00000010  2e 30 22 20 65 6e 63 6f  64 69 6e 67 3d 22 55 54  |.0" encoding="UT|
00000020  46 2d 38 22 3f 3e 0a 3c  45 72 72 6f 72 3e 3c 43  |F-8"?>.<Error><C|
00000030  6f 64 65 3e 4d 65 74 68  6f 64 4e 6f 74 41 6c 6c  |ode>MethodNotAll|
00000040  6f 77 65 64 3c 2f 43 6f  64 65 3e 3c 4d 65 73 73  |owed</Code><Mess|
00000050  61 67 65 3e 54 68 65 20  73 70 65 63 69 66 69 65  |age>The specifie|
00000060  64 20 6d 65 74 68 6f 64  20 69 73 20 6e 6f 74 20  |d method is not |
00000070  61 6c 6c 6f 77 65 64 20  61 67 61 69 6e 73 74 20  |allowed against |
00000080  74 68 69 73 20 72 65 73  6f 75 72 63 65 2e 3c 2f  |this resource.</|
00000090  4d 65 73 73 61 67 65 3e  3c 4d 65 74 68 6f 64 3e  |Message><Method>|
000000a0  50 4f 53 54 3c 2f 4d 65  74 68 6f 64 3e 3c 52 65  |POST</Method><Re|
000000b0  73 6f 75 72 63 65 54 79  70 65 3e 53 45 52 56 49  |sourceType>SERVI|
000000c0  43 45 3c 2f 52 65 73 6f  75 72 63 65 54 79 70 65  |CE</ResourceType|
000000d0  3e 3c 52 65 71 75 65 73  74 49 64 3e 50 45 44 4e  |><RequestId>PEDN|
000000e0  35 37 56 38 45 37 53 54  36 52 4e 57 3c 2f 52 65  |57V8E7ST6RNW</Re|
000000f0  71 75 65 73 74 49 64 3e  3c 48 6f 73 74 49 64 3e  |questId><HostId>|
00000100  48 56 6d 5a 4c 5a 57 6f  63 59 58 58 5a 2b 32 69  |HVmZLZWocYXXZ+2i|
00000110  4c 36 4c 50 5a 52 4c 6a  45 6e 35 59 2b 6a 76 45  |L6LPZRLjEn5Y+jvE|
00000120  52 54 79 49 54 48 39 69  79 35 56 42 37 6c 6e 56  |RTyITH9iy5VB7lnV|
00000130  53 43 73 72 6b 72 73 48  73 56 50 42 75 6c 71 4a  |SCsrkrsHsVPBulqJ|
00000140  6c 38 6b 49 41 49 47 38  68 30 30 3d 3c 2f 48 6f  |l8kIAIG8h00=</Ho|
00000150  73 74 49 64 3e 3c 2f 45  72 72 6f 72 3e           |stId></Error>|

caused by: unknown error response tag, {{ Error} []}
```

**Notes**

- I tried with a full s3 access role
- It does work if I set credentials in values.yaml via `loki.storage.s3.accessKeyId` and `loki.storage.s3.secretAccessKey`
- Issue seems to be related to https://github.com/grafana/loki/issues/5437 but solution cannot be used since chart does not allow to modify those values

**Comment by Shaltz** [comment]
Exact same issue here.

**Comment by sebagarayco** [comment]
+1

Same problem

**Comment by jeschkies** [comment]
> but solution cannot be used since chart does not allow to modify those values

@ralbon thanks. This feature would be very helpful. What values should be modified so that the Helm chart installation can assume a role?

**Comment by mjpowersjr** [comment]
Ouch - I spent a long time stuck on this issue. Eventually I wrote a helm chart from scratch, and still hit the same issue. After a lot of trial and error, I finally had a breakthrough. 

From what I can tell, it's the endpoint property that triggers the issue. As soon as I completely removed the `endpoint: ...` section of my storage config, loki began writing to my s3 bucket. 

```yaml
...
storage_config:
  aws:
    bucketnames: {{ .Values.s3.bucket }}
    # endpoint: {{ .Values.s3.endpoint }} # THIS BREAKS AUTHENTICATION ! 
    region: {{ .Values.s3.region }}
    insecure: false
```


I tried this after reading a long thread from a unrelated GitLab issue regarding S3 & the aws go-sdk that was producing a similar error message.

- https://gitlab.com/gitlab-org/charts/gitlab/-/issues/3148
- https://github.com/aws/aws-sdk-go/issues/3972

**Comment by jeschkies** [comment]
@mjpowersjr thanks for your effort. I'll look into it and add it to the new documentation. How would you feel about a Terraform provider that sets up the bucket and installs Loki via the Terraform Helm provider?

**Comment by vincentvdk** [comment]
FYI: I initially tested on AWS ECS and used the following option which worked on ECS but had to remove it to make it work on EKS 
```
  storage:
    s3:
      ...
      s3: https://s3.eu-west-1.amazonaws.com
```

**Comment by GeoAlvarenga** [comment]
> @mjpowersjr thanks for your effort. I'll look into it and add it to the new documentation. How would you feel about a Terraform provider that sets up the bucket and installs Loki via the Terraform Helm provider?

This would be beyond ideal for this product.. it seems that the configs  should be well known workflow, s3 bucket, access to it.. and the proper configuration for it .. if this was deployed via helm as a terraform module - this is a great route

**Comment by GeoAlvarenga** [comment]
> FYI: I initially tested on AWS ECS and used the following option which worked on ECS but had to remove it to make it work on EKS
> 
> ```
>   storage:
>     s3:
>       ...
>       s3: https://s3.eu-west-1.amazonaws.com
> ```

@vincentvdk   the s3: URL I have seen so many entries here...    this is probably first time I saw https://s3 etc... many places reference  s3://region  which I don't know what it may mean, I've seen the use of s3://us-west-2    and I'm wondering if that is even right..

I'm confused why EKS and ECS would behave differently when using that value.. can you explain what you meant by ECS but removed for EKS?

**Comment by vincentvdk** [comment]
@GeoAlvarenga It is indeed not clear to me either. But it did work when running on ECS and don't understand why I didn't see the errors there. I basically copied the config yaml file as-is. I must admit that I didn't spend a lot of time investigating.  

I currently have this (removed the `s3: http://....` part) which works

```
  storage:
    s3:
      bucketnames: mylokibucket
      s3forcepathstyle: true
      region: eu-west-1
      insecure: false
```

**Comment by GeoAlvarenga** [comment]
> 

I am using this and it seems to work.. this is with a an EKS role for the nodes that has a policy for full access to the one bucket... note the use of endpoint and region .. too many ways to skin this s3 config cat
```
      aws:
        bucketnames: my-bucket-name
        endpoint: s3.us-west-2.amazonaws.com
        region: us-west-2
        insecure: false
        sse_encryption: false
        http_config:
          idle_conn_timeout: 90s
          response_header_timeout: 0s
          insecure_skip_verify: false
        s3forcepathstyle: true
```
