### ISSUE TITLE
Ingress is broken when using single binary mode with v3.2.0 of Helm chart

### ISSUE THREAD

**Issue by jtackaberry** [grafana/loki#7318]
The new [Ingress resource](https://github.com/grafana/loki/blob/main/production/helm/loki/templates/ingress.yaml) creates rules mapping to either `loki-read` or `loki-write` K8s Services.  The problem is that these Services are not created in single binary mode, only in scalable mode.  In single binary mode, the Service is `loki`.

The Ingress template always appends `<-svcName>`  to the backend service name, so it's not possible to explicitly configure `ingress.paths` to point to this service.  It *is* possible to (ab)use `loki-headless` however, so this works:

```yaml
ingress:
  paths:
    headless:
      - /
    read:
    write:
```

However the ingress template in the chart should automatically use the correct configuration in single binary mode.

**Comment by k-jingyang** [comment]
Didn't check for 3.2.0. For 3.2.1, seems like I had to do

```
fullnameOverride: "loki"

ingress:
  paths:
    headless:
      - /
    read:
    write:
```

This is because `templates/ingress.yaml` uses `{{ include "loki.fullname" $ }}-{{ $svcName }}` while `templates/single-binary/service-headless.yaml` uses `{{ include "loki.name" . }}-headless`
