### ISSUE TITLE
drop syntax is giving errors

### ISSUE THREAD

**Issue by sunil-saini** [grafana/loki#7327]
**Describe the bug**

trying to send journalctl logs to loki, used configuration

```yaml
- job_name: journal
    journal:
    path: /var/log/journal
    max_age: 12h
    labels:
        job: systemd-journal
    relabel_configs:
    # example label values: kubelet.service, containerd.service
    - source_labels:
        - __journal__systemd_unit
        target_label: unit
    - source_labels:
        - __journal__hostname
        target_label: node_name
    # example label values: debug, notice, info, warning, error
    - source_labels:
        - __journal_priority_keyword
        target_label: level
```

as there were too many unwanted services logs, so added keep in relabel_configs to send only for kubelet & docker services, which is working fine

```yaml
- job_name: journal
    journal:
    path: /var/log/journal
    max_age: 12h
    labels:
        job: systemd-journal
    relabel_configs:
    # example label values: kubelet.service, containerd.service
    - action: keep
        regex: '(kubelet.service|docker.service)'
        source_labels:
        - __journal__systemd_unit
    - source_labels:
        - __journal__systemd_unit
        target_label: unit
    - source_labels:
        - __journal__hostname
        target_label: node_name
    # example label values: debug, notice, info, warning, error
    - source_labels:
        - __journal_priority_keyword
        target_label: level
```

now into these logs as well wanted to skip few unwanted log lines, so added drop in pipeline_stages expecting, which is failing with error (used reference - <https://grafana.com/docs/loki/latest/clients/promtail/stages/drop/>)

```log
level=error ts=2022-10-04T07:32:41.744123639Z caller=main.go:117 msg="error creating promtail" error="failed to make journal target manager: pipeline stage must contain only one key"
```

```yaml
- job_name: journal
    journal:
    path: /var/log/journal
    max_age: 12h
    labels:
        job: systemd-journal
    pipeline_stages:
        - drop:
            expression: "(.*ignoring event.*|.*Discovered runtime cgroup name.*)"
    relabel_configs:
    # example label values: kubelet.service, containerd.service
    - action: keep
        regex: '(kubelet.service|docker.service)'
        source_labels:
        - __journal__systemd_unit
    - source_labels:
        - __journal__systemd_unit
        target_label: unit
    - source_labels:
        - __journal__hostname
        target_label: node_name
    # example label values: debug, notice, info, warning, error
    - source_labels:
        - __journal_priority_keyword
        target_label: level
```

added in another way as mentioned here <https://grafana.com/docs/loki/latest/clients/promtail/stages/match/>

```yaml
pipeline_stages:
  - match:
    selector: '{job="systemd-journal"} |~ ".*Discovered runtime cgroup name.*"'
    action: drop
```

still error is same

going by error of `pipeline stage must contain only one key` tried with below conf

```yaml
pipeline_stages:
  drop:
    expression: "(.*ignoring event.*|.*Discovered runtime cgroup name.*)"
```

now error is `cannot unmarshal !!map into []interface {}`

**Expected behavior**
drop syntax should work as expected

**Environment:**

- Infrastructure: Kubernetes (promtail:2.6.1)
- Deployment tool: helm
