### ISSUE TITLE
Loki - Retention and reading of the s3 AWS bucket doesn't work

### ISSUE THREAD

**Issue by qdupuy** [grafana/loki#7335]
**Describe the bug**
I have log holes despite a 24h index configuration, and reading on the bucket doesn't work

**To Reproduce**

- Install loki-distributed and promtail into EKS cluster with their helm charts
- Creation of an encrypted bucket via KMS
- Creation of a Loki user with its API key pair
- IAM authorization for the Loki KMS
- s3 authorization for the Loki user

**Expected behavior**

I would like my retention to work in order to get my logs over a period of time that I have defined

**Environment:**
 - Infrastructure: EKS v1.22.10
 - Deployment tool: Helm

My configuration :

Loki : 
```
        chunk_store_config:
          max_look_back_period: 672h

        table_manager:
          retention_deletes_enabled: true
          retention_period: 672h
          poll_interval: 2m
```

SchemaConfig : 

```
    schemaConfig:
        configs:
            - from: "2020-07-01"
              store: boltdb-shipper
              object_store: aws
              schema: v11
              index:
                prefix: loki_
                period: 24h
```

StorageConfig: 

```
    storageConfig:
        boltdb_shipper:
            shared_store: s3
            active_index_directory: /var/loki/index
            cache_location: /var/loki/cache
            cache_ttl: 168h
        filesystem:
            directory: /var/loki/chunks
        aws:
         s3: s3://name
         endpoint: https://s3.eu-west-3.amazonaws.com
         region: eu-west-3
         bucketnames: name
         access_key_id: ${LOKI_S3_ACCESS_KEY_ID}
         secret_access_key: ${LOKI_S3_SECRET_ACCESS_KEY}
         s3forcepathstyle: true
         insecure: false
         sse_encryption: false
```

**Comment by chaudum** [comment]
Hi @qdupuy 
Your schema and storage configs look ok.

However, when you deploy the loki-distributed Helm chart and want to configure retention with `boltdb-shipper` store, you need to enable the compactor service.
You then need to enable retention in the compactor config as well and set a retention period in the limits config.

Example:

```yaml
compactor:
  retention_enabled: true
limits_config:
  retention_period: 30d
```

**Comment by chaudum** [comment]
> I have log holes despite a 24h index configuration, and reading on the bucket doesn't work

Could you elaborate a bit more on that and provide error logs, etc so we can narrow down the problem?

**Comment by qdupuy** [comment]
> Hi @qdupuy Your schema and storage configs look ok.
> 
> However, when you deploy the loki-distributed Helm chart and want to configure retention with `boltdb-shipper` store, you need to enable the compactor service. You then need to enable retention in the compactor config as well and set a retention period in the limits config.
> 
> Example:
> 
> ```yaml
> compactor:
>   retention_enabled: true
> limits_config:
>   retention_period: 30d
> ```

Compactor :

```
        compactor:
          shared_store: s3
          retention_enabled: true
          compaction_interval: 10m
```

I  see the problems on grafana.

![grafana_loki_datasource](https://user-images.githubusercontent.com/86727342/194026237-496707d0-5a08-48b7-be1f-2fcfa81501a3.png)

In the logs, I see nothing.

On which service can I get the right information?
