### ISSUE TITLE
err="invalid database" after restarting loki pods (Azure Blob Storage)

### ISSUE THREAD

**Issue by anfallow** [grafana/loki#7336]
Hello,

I wanted to ask for help with an issue:
- I have loki installed via helm chart to kubernetes:
  - Helm rev. 0.57.0; Loki v. 2.6.1.
  - K8s version 1.23.8
  - Queriers and Ingesters have persistence layer set up, sc:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile-loki-zrs
provisioner: file.csi.azure.com
parameters:
  skuName: Premium_ZRS
reclaimPolicy: Retain
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
allowVolumeExpansion: true
volumeBindingMode: Immediate
```
Loki helm parameters (values)

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-new
spec:
  destination:
    namespace: loki-monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: loki-distributed
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.57.0
    helm:
      parameters:
        - name: ingester.replicas
          value: '3'
        - name: distributor.replicas
          value: '3'
        - name: queryFrontend.replicas
          value: '3'
        - name: querier.replicas
          value: '3'
      values: |
        fullnameOverride: loki
        loki:
          config: |
            auth_enabled: false
            server:
              http_listen_port: 3100
              http_server_read_timeout: 900s
              http_server_write_timeout: 900s
              grpc_server_max_recv_msg_size: 20388078
              grpc_server_max_send_msg_size: 20388078
              log_level: "debug"  
            distributor:
              ring:
                kvstore:
                  store: memberlist
            memberlist:
              join_members:
                - {{ include "loki.fullname" . }}-memberlist
            ingester:
              lifecycler:
                ring:
                  kvstore:
                    store: memberlist
                  replication_factor: 3
              chunk_idle_period: 30m
              chunk_block_size: 262144
              chunk_encoding: snappy
              chunk_retain_period: 1m
              max_transfer_retries: 0
              wal:
                dir: /var/loki/wal

            limits_config:
              enforce_metric_name: false
              reject_old_samples: false
              reject_old_samples_max_age: 168h
              max_cache_freshness_per_query: 10m
              split_queries_by_interval: 15m
              ingestion_rate_mb: 10
              ingestion_burst_size_mb: 20
              max_concurrent_tail_requests: 20
              max_query_parallelism: 16

            schema_config:
              configs:
                - from: 2020-09-07
                  store: boltdb-shipper
                  object_store: azure
                  schema: v11
                  index:
                    prefix: loki_index_
                    period: 24h
            storage_config:
              boltdb_shipper:
                shared_store: azure
                active_index_directory: /var/loki/index
                cache_location: /var/loki/cache
                cache_ttl: 168h
                {{- if .Values.indexGateway.enabled }}
                index_gateway_client:
                  server_address: dns:///{{ include "loki.indexGatewayFullname" . }}:9095
                {{- end }}
              azure:
                container_name: loki
                account_name: storage
                account_key: ${storage-password}
                request_timeout: 0
            chunk_store_config:
              max_look_back_period: 0s
            table_manager:
              retention_deletes_enabled: false
              retention_period: 0s
            query_range:
              align_queries_with_step: true
              max_retries: 5
              cache_results: true
              results_cache:
                cache:
                  enable_fifocache: true
                  fifocache:
                    max_size_items: 1024
                    validity: 24h
            frontend_worker:
              frontend_address: loki-query-frontend.loki-monitoring.svc.cluster.local:9095
              grpc_client_config:
                max_send_msg_size: 1.048576e+08
              parallelism: 14
            frontend:
              log_queries_longer_than: 5s
              compress_responses: true
              tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100
            ruler:
              storage:
                type: local
                local:
                  directory: /etc/loki/rules
              rule_path: /tmp/loki/scratch
              alertmanager_url: http://prometheus-alertmanager.monitoring:9093
              ring:
                kvstore:
                  store: inmemory
        ingester:
          chunk_encoding: snappy
          persistence:
            enabled: true
            size: 5Gi
            storageClass: azurefile-loki-zrs
          extraArgs:
            - -config.expand-env=true
          extraEnvFrom:
            - secretRef:
                name: azure-blob-account

        querier:
          persistence:
            enabled: true
            size: 5Gi
            storageClass: azurefile-loki-zrs
          extraArgs:
            - -config.expand-env=true
          extraEnvFrom:
            - secretRef:
                name: azure-blob-account

        serviceMonitor:
          namespace: loki-monitoring
          interval: "300s"
          enabled: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

We also tried changing the storage class to NFS enabled azure disk, but the error is still the same when querying old logs:

```
level=info ts=2022-10-05T08:18:06.271866279Z caller=index_set.go:422 table-name=loki_index_19270 file-name=loki-ingester-2-1663750358847261778-1664944200.gz msg="downloaded file" total_time=48.969181ms
25
level=info ts=2022-10-05T08:18:06.272357944Z caller=index_set.go:422 table-name=loki_index_19270 file-name=loki-ingester-2-1663750358847261778-1664949600.gz msg="downloaded file" total_time=49.147342ms
24
level=info ts=2022-10-05T08:18:06.272548499Z caller=index_set.go:422 table-name=loki_index_19270 file-name=loki-ingester-2-1663750358847261778-1664942400.gz msg="downloaded file" total_time=49.967039ms
23
level=info ts=2022-10-05T08:18:06.272693271Z caller=index_set.go:422 table-name=loki_index_19270 file-name=loki-ingester-2-1663750358847261778-1664954961.gz msg="downloaded file" total_time=49.286148ms
22
level=info ts=2022-10-05T08:18:06.273075321Z caller=index_set.go:422 table-name=loki_index_19270 file-name=loki-ingester-2-1663750358847261778-1664956800.gz msg="downloaded file" total_time=49.557297ms
21
level=error ts=2022-10-05T08:18:06.31519842Z caller=index_set.go:265 table-name=loki_index_19270 msg="sync failed, retrying it" err="invalid database"
20
level=error ts=2022-10-05T08:18:06.315229648Z caller=index_set.go:104 table-name=loki_index_19270 msg="failed to initialize table loki_index_19270, cleaning it up" err="invalid database"
19
level=error ts=2022-10-05T08:18:06.315263111Z caller=table.go:294 table-name=loki_index_19270 msg="failed to init user index set " err="invalid database"
18
level=error ts=2022-10-05T08:18:06.315290623Z caller=table.go:312 table-name=loki_index_19270 org_id=fake msg="index set  has some problem, cleaning it up" err="invalid database"
17
level=debug ts=2022-10-05T08:18:06.315290655Z caller=index_set.go:187 table-name=loki_index_19270 org_id=fake index-files-count=0
16
level=debug ts=2022-10-05T08:18:06.31550603Z caller=series_index_store.go:403 org_id=fake msg="post intersection" matchers=1 ids=0
15
level=debug ts=2022-10-05T08:18:06.315533722Z caller=series_index_store.go:108 org_id=fake series-ids=0
14
level=debug ts=2022-10-05T08:18:06.315550844Z caller=series_index_store.go:116 org_id=fake chunk-ids=0
13
level=debug ts=2022-10-05T08:18:06.31556476Z caller=series_index_store.go:125 org_id=fake chunks-post-filtering=0
12
ts=2022-10-05T08:18:06.315646113Z caller=spanlogger.go:80 user=fake method=query.Exec level=debug Ingester.TotalReached=3 Ingester.TotalChunksMatched=0 Ingester.TotalBatches=0 Ingester.TotalLinesSent=0 Ingester.TotalChunksRef=0 Ingester.TotalChunksDownloaded=0 Ingester.ChunksDownloadTime=0s Ingester.HeadChunkBytes="0 B" Ingester.HeadChunkLines=0 Ingester.DecompressedBytes="0 B" Ingester.DecompressedLines=0 Ingester.CompressedBytes="0 B" Ingester.TotalDuplicates=0 Querier.TotalChunksRef=0 Querier.TotalChunksDownloaded=0 Querier.ChunksDownloadTime=0s Querier.HeadChunkBytes="0 B" Querier.HeadChunkLines=0 Querier.DecompressedBytes="0 B" Querier.DecompressedLines=0 Querier.CompressedBytes="0 B" Querier.TotalDuplicates=0
11
ts=2022-10-05T08:18:06.315683924Z caller=spanlogger.go:80 user=fake method=query.Exec level=debug Summary.BytesProcessedPerSecond="0 B" Summary.LinesProcessedPerSecond=0 Summary.TotalBytesProcessed="0 B" Summary.TotalLinesProcessed=0 Summary.ExecTime=392.296904ms Summary.QueueTime=0s
10
level=info ts=2022-10-05T08:18:06.315746802Z caller=metrics.go:133 component=querier org_id=fake latency=fast query="{app=\"ipxo-billing-api\"}" query_type=limited range_type=range length=1h0m1s step=2s duration=392.296904ms status=200 limit=5000 returned_lines=0 throughput=0B total_bytes=0B total_entries=0 queue_time=0s subqueries=1
9
level=debug ts=2022-10-05T08:18:06.315845587Z caller=logging.go:76 traceID=4403707668657478 orgID=fake msg="GET /loki/api/v1/query_range?direction=BACKWARD&limit=5000&query=%7Bapp%3D%22ipxo-billing-api%22%7D&start=1664947085000000000&end=1664950686000000000&step=2 (200) 392.643675ms"
8
ts=2022-10-05T08:18:06.319077099Z caller=spanlogger.go:80 table-name=loki_index_19270 org_id=fake level=info msg="downloaded index set at query time" duration=395.037935ms
7
```

I can see the ingester is pushing new files in azure blob, but queriers seem to only be able to query info that is in the ingesters, and once they flush it into blob - it becomes unavailable. 

Does loki use some additional layer for indexing the data (that might have been corrupted)?

Anybody else got this issue?  

Thanks,
