### ISSUE TITLE
Duplicate log entries for short-lived container

### ISSUE THREAD

**Issue by cedsana** [grafana/loki#7382]
## **Describe the bug**
I have a container for which I would like to get the logs but it is short-lived. A host cron job wakes it up every minute with a `docker start <container>`. The container checks in a mounted folder if it has work to do.  
If it has no work to do, nothing is logged and the container goes back to sleep almost instantly.  
If it has work to do, it will do its job and log lots of thing to the standard output.  

The log entries for my short-lived container are duplicated several times. It seems like I get a duplicate for everytime the container wakes up without work to do.  All log entries have **exactly** the same `tsNs`.

The Promtail documentation mentions the following

> Please note that the discovery will not pick up finished containers. That means Promtail will not scrape the remaining logs from finished containers after a restart.

Maybe it can be related to my bug? I'm not sure.  

This issue could also be related to the following ones which all mention duplication problems:
- https://github.com/grafana/loki/issues/7103. This one could very well be my own problem.
- https://github.com/grafana/loki/issues/7207
- https://github.com/grafana/loki/issues/7141
- https://github.com/grafana/loki/issues/6929
- https://github.com/grafana/loki/issues/6790
- https://github.com/grafana/loki/issues/6225
- https://github.com/grafana/loki/issues/5252

## **To Reproduce**
Here are my Loki and Promtail services in docker-compose:
```yml
  loki:
    image: grafana/loki:2.6.0
    container_name: loki
    restart: unless-stopped
    user: 1001:1001
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./config/loki:/etc/loki
      - ./storage/loki:/tmp/loki
  promtail:
    image: grafana/promtail:2.6.0
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/promtail/config.yml:/etc/promtail/config.yml:ro
      - ./storage/promtail:/storage/promtail
    command:
      - "-config.file=/etc/promtail/config.yml"
```

## **Expected behavior**
I should not have duplicate log entries.

## **Environment:**
 - Infrastructure: Bare metal.
 - Deployment tool: Docker/docker-compose.

## **Screenshots, Promtail config, or terminal output**
The following config files:

**Promtail config:**
```
server:
  disable: true

positions:
  filename: /storage/promtail/positions.yml

clients:
  - url: https://loki.example.com/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values:
              - company.logging.enable=True
    relabel_configs:
      - target_label: env
        replacement: dev

      - source_labels:
        - __meta_docker_container_label_com_docker_compose_project_working_dir
        target_label: env
        regex: ".*(stage1).*"

      - source_labels:
        - __meta_docker_container_label_com_docker_compose_project_working_dir
        target_label: env
        regex: ".*(stage2).*"
```

**Loki Config:**
```
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  wal:
    dir: /tmp/loki/wal

schema_config:
  configs:
  - from: 2020-05-15
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 30d

chunk_store_config:
  max_look_back_period: 14d

table_manager:
  retention_deletes_enabled: true
  retention_period: 30d
```
