### ISSUE TITLE
Metrics of stream size stored by Loki

### ISSUE THREAD

**Issue by dorinand** [grafana/loki#7385]
I am harvesting logs from docker swarm, storage mounted as data volume to the Loki is getting full. I cannot determine, which stream (combination of labels) is taking most of the space. I think, it would be nice to have this information as metrics per stream. 

I implemented python script which process output of `chunk-inspector` of each chunk, but it take too much time. Of course, solution could be split calculation between multiple processes but I think it is not best solution for this issue.

**Comment by dannykopping** [comment]
Hi @dorinand 

If we were to export a metric for every stream the cardinality would be quite excessive, so we are unlikely to implement this.
You could run an instant query like `topk(10, bytes_over_time({namespace="..."}[1h]))` to see which streams are heaviest.

**Comment by dorinand** [comment]
Hi @dannykopping ,

thank you for your reply. I understand the reason with cardinality, your query works fine but it looks like the query is quiet heavy for Loki. It takes a lot of resources and if I test it on one day period, It is not able to process (timeout). It does not make sense to give Loki more resources or time just to calculate disk usage.

Is there a better way how to get this information? When the disk is getting full that means, there is more logs in Loki and get max bytes over time will take even longer. The result also does not show how much data have each stream, only the ingest rate (number of bytes per period). So it can be heavy for stream A right now, but from whole month perspective the problem could be stream B.

**Comment by dorinand** [comment]
@dannykopping thanks for your tip. It looks like solution for my issue. 

I am struggling with configuration. I testing recording rules on localhost where I am running Loki, Prometheus, Promtail and log generator (python script).

This is ruler configuration of Loki:
```
ruler:
  remote_write:
    enabled: true
    client:
      url: http://prometheus:9090/api/v1/write
```

According the documentation, this should enable remote write to prometheus.
I also create rules.yml file and store it into `/loki/rules` (later also into `/loki/rules/fake/` based on [Rules storage](https://grafana.com/docs/loki/latest/rules/#ruler-storage))
```
name: MyRules
interval: 1m
rules:
  - record: generator:requests:rate2m
    expr: |
      sum(
        rate({service="generator_generator"}[2m])
      )
    labels:
      cluster: "something"
```

Based on documentation, I am not sure if the configuration is right, in logs, there is no info about remote write (I test it even with wrong prometheus URL but no errors occurs). Can you help me to configure it properly?
