### ISSUE TITLE
[loki-operator] CRD: support podMonitor k8s CRD

### ISSUE THREAD

**Issue by liguozhong** [grafana/loki#7387]
**Is your feature request related to a problem? Please describe.**
The promtail service discovery module is implemented with reference to the service discovery of prometheus, which achieves great flexibility, 
but the configuration is relatively complex and does not conform to the design concept of the k8s environment.

The CRD in k8s is more popular with operater personnel. 

So we should implement a podMonitor CRD similar to the prometheus-operator project to simplify the service discovery feature of promtail. And make promtail easier to be integrated into the CICD process in the k8s environment.

```
server:
 ...
scrape_configs:
  - job_name: kubernetes-pods-name
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels:
          - __meta_kubernetes_pod_label_name
        target_label: __service__
      - source_labels:
          - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ''
        source_labels:
          - __service__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        replacement: $1
        separator: /
        source_labels:
          - __meta_kubernetes_namespace
          - __service__
        target_label: job
      - action: replace
        source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
        target_label: __path__
```

**Describe the solution you'd like**
CRD is simple to read 👍
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: example-app
spec:
  selector:
    matchLabels:
      app: example-app
  namespaceSelector:
    any: true
```

**Describe alternatives you've considered**
https://github.com/grafana/loki/pull/7247 introduce reload endoint / signal to promtail. This PR will be useful when the CRD applied.

logging-operator: https://banzaicloud.com/docs/one-eye/logging-operator/configuration/flow/
Logging operator for Kubernetes based on Fluentd and Fluent-bit. not promtail.
if Fluentd and Fluent-bit has some bug, I dont know how to fix it .

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-sample
  namespace: default
spec:
  filters:
    - parser:
        remove_key_name_field: true
        parse:
          type: nginx
    - tag_normaliser:
        format: ${namespace_name}.${pod_name}.${container_name}
  localOutputRefs:
    - s3-output
  match:
    - select:
        labels:
          app: nginx
```

https://github.com/banzaicloud/logging-operator
![image](https://user-images.githubusercontent.com/9583245/195041321-cc33dc3f-738c-46ff-951c-5e1f811a0425.png)

**Additional context**
podmonitor design: 
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/design.md#podmonitor
podmonitors link:
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/crds/crd-podmonitors.yaml

https://github.com/grafana/loki/issues/7387#tasklist-block-5027866a-e326-4c77-beef-b8c3e7a91ecf
