### ISSUE TITLE
[Promtail] Exclude event message from Windows Events job

### ISSUE THREAD

**Issue by MarNicGit** [grafana/loki#7395]
**Is your feature request related to a problem? Please describe.**
Right now, events scraped by the `windows_events` job always include the event message. While this can be useful for events that produce short messages and benefit from the additional info, it can be annoying for events that produce large messages. 

A good example of this is event ID [4624](https://learn.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4624), the successful login event, which easily produces over 2000 characters of text with information that is already contained in the event data. I feel like omitting this data at its source would save data and network traffic, even if the impact is minimal.

**Describe the solution you'd like**
Like `exclude_user_data` and `exclude_event_data` I would like to see an option called `exclude_event_message`.

**Describe alternatives you've considered**
I currently omit this field entirely in my Grafana panels, but I'd rather not receive the data at all - Right now it is just wasting filespace on my storage.

**Additional context**
One can easily check this by using following job:
```yaml
- job_name: winlog-logon-success
    windows_events:
      use_incoming_timestamp: false
      bookmark_path: ./bookmark.xml
      eventlog_name: 'Security'
      xpath_query: 'Event/System[(EventID=4624)]'
```
and then triggering the event by performing a successful login. Locking the desktop and then unlocking it usually does the trick.
