### ISSUE TITLE
[Loki+Helm] S3 backend error: incorrect region, the bucket is not in 'eu-west-1' region at endpoint ''

### ISSUE THREAD

**Issue by sklarsa** [grafana/loki#7403]
**Describe the bug**
I'm running Loki in EKS using IRSA to use the s3 storage backend, and I'm getting the following errors in the `loki-read` pods:

```
│ level=error ts=2022-10-12T21:06:28.774105533Z caller=cached_client.go:65 msg="failed to build cache" err="BucketRegionError: incorrect region, the bucke │
│ t is not in 'eu-west-1' region at endpoint ''\n\tstatus code: 301, request id: , host id: "                                                              │
│ level=error ts=2022-10-12T21:06:28.774123664Z caller=compactor.go:432 msg="failed to run compaction" err="BucketRegionError: incorrect region, the bucke │
│ t is not in 'eu-west-1' region at endpoint ''\n\tstatus code: 301, request id: , host id: "                                                              │
│ level=error ts=2022-10-12T21:06:44.83911778Z caller=reporter.go:203 msg="failed to delete corrupted cluster seed file, deleting it" err="BucketRegionErr │
│ or: incorrect region, the bucket is not in 'eu-west-1' region at endpoint ''\n\tstatus code: 301, request id: , host id: "                               │
│ level=error ts=2022-10-12T21:07:21.961894672Z caller=ruler.go:497 msg="unable to list rules" err="BucketRegionError: incorrect region, the bucket is not │
│  in 'eu-west-1' region at endpoint ''\n\tstatus code: 301, request id: , host id: "
```

My helm chart values.yaml config is simple:
```yaml
        serviceAccount:
          name: loki-test
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::012345678901:role/my-role
        loki:
          storage:
            type: s3
            s3:
              s3: s3://eu-west-1/my-bucket
```

I can also confirm that the service account is configured correctly in a separate pod running the aws cli.  I've also tried multiple permutations of the `s3:` storage config, but I've only gotten different errors around assuming the role, and figured that this was the closest that I got to a working solution.

I've also confirmed the bucket region:
```bash
$ aws s3api get-bucket-location --bucket my-bucket
{
    "LocationConstraint": "eu-west-1"
}
```

**To Reproduce**
Using the following helm chart & version:
```yaml
chart: loki
repoURL: https://grafana.github.io/helm-charts
targetRevision: 3.2.1
```

**Expected behavior**
Able to connect to s3 bucket

**Environment:**
 - Infrastructure: EKS
 - Deployment tool: helm & argocd

**Comment by sklarsa** [comment]
When I add more granular s3 configs:
```yaml
                  s3: s3://my-bucket
                  bucketnames: my-bucket
                  endpoint: s3.eu-west-1.amazonaws.com
                  insecure: false
                  region: eu-west-1
                  s3forcepathstyle: true
```

I get an UnmarshallError:
```
l=error ts=2022-10-12T22:16:00.023675344Z caller=ruler.go:497 msg="unable to list rules" err="WebIdentityErr: failed to retrieve credentials\ncaused │
│  by: SerializationError: failed to unmarshal error message\n\tstatus code: 405, request id: \ncaused by: UnmarshalError:
```

and the return value is an xml-formatted HTTP 405 Method Not Allowed (POST)
