### ISSUE TITLE
Incorrect default configuration for single binary helm deployment

### ISSUE THREAD

**Issue by k-jingyang** [grafana/loki#7435]
**Describe the bug**
1. replication_factor should be 1 for single binary helm deployment
2. ring's kvstore should be `inmemory`

**To Reproduce**
1. Deploy loki chart 3.2.1 with the following in `values.yaml`
```yaml
loki:
  storage:
    type: filesystem
```
3. Wait for Loki to be ready, 
```bash
$ wget localhost:3100/ready -O - -q
ready
```
4. Query labels
```bash
$ wget  localhost:3100/loki/api/v1/labels -O - -q
wget: server returned error: HTTP/1.1 500 Internal Server Error
```

**Expected behavior**
```bash
$ wget  localhost:3100/loki/api/v1/labels -O - -q
{"status":"success"}
```

**Potential fix**
Put the following in `values.yaml`
```yaml
loki:
  commonConfig:
    replication_factor: 1
    ring:
      instance_addr: 127.0.0.1
      kvstore:
      store: inmemory
```
gets me
```
wget localhost:3100/loki/api/v1/labels -O - -q
{"status":"success"}
```
**Environment:**
- Kubernetes, 
- Loki Helm chart 3.2.1
- grafana/loki:2.6.1

**Side note**
There's another issue with the default configuration noted in https://github.com/grafana/loki/issues/7318. We could fix both issues to make the default configuration for single binary helm deployment work.
