### ISSUE TITLE
[BUG] [Loki] '404 page not found' - ARM64

### ISSUE THREAD

**Issue by zs-dima** [grafana/loki#7459]
Reproduced with image: 
- grafana/loki:2.3.0
- grafana/loki:latest

Server: Oracle Cloud A1 ARM

Grafana, Prometheus, Portainer, Traefik and etc frontends working well with current Swarm stack
Loki addresses working well also:
https://loki.mydomain.com/loki/api/v1/labels
https://loki.mydomain.com/config

But `curl http://127.0.0.1:3100/` and `https://loki.mydomain.com`
displays:
`404 page not found`

Loki config:
```yaml
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  lifecycler:
    address: 0.0.0.0
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

schema_config:
  configs:
    - from: 2020-04-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: /loki/index

  filesystem:
    directory: /loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
```

Loki service:
```yaml
  loki: 
    hostname: loki
    image: grafana/loki:2.3.0
    command:
     - -config.file=/etc/loki/loki.yml
    networks:
      - public
      - monitor
    volumes:
      - loki-data:/loki
    configs:
     - source: loki.yml
       target: /etc/loki/loki.yml
    ports:
      - 3100:3100
```
