### ISSUE TITLE
loki not accept parsed timestamps cause: sample for 'logs' has timestamp too new

### ISSUE THREAD

**Issue by xelite** [grafana/loki#747]
**Describe the bug**
I've tried to parse postgres logs. Loki not accept parsed timestamps cause: sample for 'logs' has timestamp too new. It's milliseconds since epoch. Loki should it accept. Promtail logs:

```
level=error ts=2019-07-12T20:02:26.883712074Z caller=client.go:185 component=client host=xxx:3100 msg="final error sending batch" status=400 error="server returned HTTP status 400 Bad Request (400): sample for 'logs' has timestamp too new: 1562968946581
```

**To Reproduce**
grafana/loki:latest
grafana/promtail:latest

Simple log lines:
```
[2019-07-12 00:00:45.347 CEST] [unknown]@10.21.37.6(47600):[unknown] [3968] 5d27b18d.f80/1:0 LOG:  connection received: host=10.21.37.6 port=47600
```

**Expected behavior**
See logs 

**Environment:**
 - Infrastructure: docker + vm
 - Deployment tool: docker

```
 - job_name: postgres
   static_configs:
   - targets:
      - localhost
     labels:
      job: postgres
      __path__: /var/log/postgresql/*log
   pipeline_stages:
   - regex:
       expression: ^\[(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}) \w+\] (?P<user>[\w\[\]]+)?@(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(\(\d+\))?|\[local\])?:(?P<database>\w+|\[\w+\])? \[\d+\] [^:]*:\d+ (?P<level>\w+)
   - labels:
       level:
       database:
       user:
   - timestamp:
       source: time
       format: 2006-01-02 15:04:05.999
```
