### ISSUE TITLE
Promtail kubernetes host log & drop namespace

### ISSUE THREAD

**Issue by prasenforu** [grafana/loki#748]
I am running Loki with promtail in kubernetes platform.

Promtail running as a daemonset and promtail configuration as follows ..

```
    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ^$
          source_labels:
          - __meta_kubernetes_pod_label_name
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_label_name
          target_label: job
        - action: drop
          regex: default
          source_labels:
          - __meta_kubernetes_namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: instance
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container_name
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - replacement: /var/log/pods/$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
      - job_name: kubernetes-pods-app
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: .+
          source_labels:
          - __meta_kubernetes_pod_label_name
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_label_app
          target_label: job
        - action: drop
          regex: default
          source_labels:
          - __meta_kubernetes_namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: instance
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: container_name
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - replacement: /var/log/pods/$1/*.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
```

I have a two question?

### Q1# How can I capture kubernetes host log (/var/log/messages) along with hostname and what will be config file definition?

I checked with https://github.com/grafana/loki/blob/master/docs/promtail-examples.md

But looks like its for static configuration.
```
scrape_configs:
 - job_name: system
   pipeline_stages:
   - docker:
   static_configs:
   - targets:
      - localhost
     labels:
      job: varlogs
      host: yourhost
      __path__: /var/log/*.log
```

### Q2# How can I DROP all logs from particular namespace (default)
I tried with following but no luck, not sure if I missing anything ...
I added below text in job "kubernetes-pods" & "kubernetes-pods-app"

```
        - action: drop
          regex: default
          source_labels:
          - __meta_kubernetes_namespace
```

**Comment by minhdanh** [comment]
@prasenforu Could you have your questions answered? I'm wondering the same.

**Comment by zhushilu** [comment]
Take a look at this article.    https://itnext.io/grafana-logging-using-loki-45665916aec9

**Comment by prasenforu** [comment]
I followed that URL but not working.

Finally I moved to fluent-bit

**Comment by cyriltovena** [comment]
Labels after relabeling are accessible in pipeline stage, we support dropping via the match stage so that should work now.

**Comment by imranrazakhan** [comment]
@prasenforu how you able to exclude namespace in fluent-bit?

**Comment by cloudcafetech** [comment]
@imranrazakhan 

in fluent-bit conf add in INPUT section

```
    [INPUT]
        Name           tail
        Tag            kube.*
        Path           /var/log/containers/*.log
        Exclude_Path   /var/log/containers/*_monitoring_*.log,/var/log/containers/*_logging_*.log,/var/log/containers/*_kube-system_*.log,/var/log/containers/*_kube-node-lease_*.log,/var/log/containers/*_kube-public_*.log
        Parser         docker
        DB             /run/fluent-bit/flb_kube.db
        Mem_Buf_Limit  5MB
```

**Comment by dolisss** [comment]
@prasenforu did it worked? I am facing the same issue.

**Comment by cloudcafetech** [comment]
>

**Comment by cloudcafetech** [comment]
@cyriltovena 

> Q2 - Labels after relabeling are accessible in pipeline stage, we support dropping via the match stage so that should work now.

Can you please help me to get sample configuration for dorp namespace

**Comment by eranbetzalel** [comment]
**Drop all namespaces but "default" on promtail**

        - match:
            pipeline_name: "drop-all"
            selector: '{namespace!="default"}'
            action: drop

**Comment by aroldobossoni** [comment]
> **Drop all namespaces but "default" on promtail**
> 
> ```
>     - match:
>         pipeline_name: "drop-all"
>         selector: '{namespace!="default"}'
>         action: drop
> ```
> 
> This is a working example.

Simple and easy as flying.

**Comment by mhoyer** [comment]
It might be helpful to also point out that there is a probably more efficient way to filter per namespace. Thus, this only works when it's about an include list of valid namespaces.

There is the [`kubernetes_sd_config`](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#kubernetes_sd_config) section which enables you to configure `namespaces`. Promtail will then only discover and tail on log files of pods/containers for that given set of namespaces. Ergo, less work (IOps) to do for Promtail.

```yaml
scrape_configs:
- job_name: kubernetes-pods
  pipeline_stages:
    - cri: {}
  kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
          - default
          - another-namespace
```
