### ISSUE TITLE
helm chart should not install Prometheus CRDs

### ISSUE THREAD

**Issue by sathieu** [grafana/loki#7488]
**Describe the bug**

Prometheus is installed using another chart (or any other method). The prometheus CRDs are provided by this installation method. Installing also the CRD from the loki chart may produce CRD upgrade and downgrade with possible data lost.

**To Reproduce**
1. Install prometheus-stack and loki charts with ArgoCD

->  There is a diff, between the CRD version in prometheus-stack and in loki.

**Expected behavior**

No conflict

**Environment:**
 - Infrastructure: Kubernetes installed with kubespray
 - Deployment tool: helm in ArgoCD

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by dotdc** [comment]
If you use ArgoCD, you can simply skip CRD's instllation using `skipCrds: true`:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: {{ .Values.loki.version }}
    helm:
      skipCrds: true
```

**Comment by sathieu** [comment]
@dotdc Thanks for the info, but I still thinks this is a bad practice to include CRDs from other components.

I can move the CRDs to templates (with an ` if`), if requested.

**Comment by jeschkies** [comment]
As I mentioned in the pull requests the CRDs are used by the Grafana Agent Operator that is installed with this Helm Chart. We could couple the. Also, why is the Prometheus chart installing a CRD that's conflicting. E.g. our service monitor soups only target the Loki installation.

**Comment by sathieu** [comment]
The `agent-operator` chart has [ServiceMonitor](https://github.com/grafana/helm-charts/blob/377fda9f2ec155896a7c1fe822e7287fda4290bf/charts/agent-operator/crds/monitoring.coreos.com_servicemonitors.yaml) CRD too and [a few others](https://github.com/grafana/helm-charts/tree/main/charts/agent-operator/crds). Maybe move the [prometheusrules.yaml](https://github.com/grafana/loki/blob/main/production/helm/loki/crds/crd-prometheusrules.yaml) CRD there and remove ServiceMonitor from the `loki` chart? This way, all those CRDs won't be installed when the agent is disabled.

**Comment by trallnag** [comment]
Hasn't this been merged as part of https://github.com/grafana/loki/pull/7499

**Comment by pblgomez** [comment]
It would be good to have an option to disable prometheus CRD's but for now what I use is:

```yaml
ignoreDifferences:
  - group: '*'
    jsonPointers:
    - /
    kind: CustomResourceDefinition
 ```

**Comment by batazor** [comment]
Or at least update prometheus-crd to the latest versions to avoid conflicts

**Comment by batazor** [comment]
any updates?

**Comment by azkore** [comment]
> Hasn't this been merged as part of #7499

That PR removed prometheus CRDs from the loki chart itself.  However, when the monitoring feature is active, the Loki chart deploys the [grafana-agent-operator](https://github.com/grafana/loki/blob/main/production/helm/loki/Chart.yaml#L19-L23) as a dependency. This operator chart [includes Prometheus CRDs](https://github.com/grafana/helm-charts/tree/main/charts/agent-operator/crds).
Probably this issue needs to be moved to https://github.com/grafana/helm-charts

**Comment by kuzm1ch** [comment]
+1 to this thread, 
another scenario can be to specify which group of crds we can exclude from deploying: 

```
crds:
  grafana-agent:
     enabled: true
  prometheus:
     enabled: true
```
and skip the installation of Prometheus crds with disable option. 
inspired by kube-prometheus-stack but haven't tested yet.
