### ISSUE TITLE
Problem initializing loki

### ISSUE THREAD

**Issue by biel19966** [grafana/loki#7494]
I made the connection of promtail and loki using kafka, when I connect the promtail to loki and initialize loki, it returns the following error:

```
level=debug ts=2022-10-21T17:34:51.577445545Z caller=mock.go:186 msg="Get - deadline exceeded" key=collectors/compactor
level=debug ts=2022-10-21T17:34:51.577500065Z caller=mock.go:150 msg=Get key=collectors/compactor wait_index=59
level=debug ts=2022-10-21T17:34:51.715162126Z caller=grpc_logging.go:41 method=/grpc.health.v1.Health/Check duration=46.507µs msg="gRPC (success)"
level=debug ts=2022-10-21T17:34:52.578216808Z caller=mock.go:186 msg="Get - deadline exceeded" key=collectors/compactor
level=debug ts=2022-10-21T17:34:52.578272647Z caller=mock.go:150 msg=Get key=collectors/compactor wait_index=59
level=debug ts=2022-10-21T17:34:52.578283796Z caller=mock.go:186 msg="Get - deadline exceeded" key=collectors/scheduler
level=debug ts=2022-10-21T17:34:52.578316508Z caller=mock.go:150 msg=Get key=collectors/scheduler wait_index=60
level=debug ts=2022-10-21T17:34:52.578340327Z caller=mock.go:186 msg="Get - deadline exceeded" key=collectors/ring
level=debug ts=2022-10-21T17:34:52.578350988Z caller=mock.go:150 msg=Get key=collectors/ring wait_index=62
level=debug ts=2022-10-21T17:34:52.578362365Z caller=mock.go:186 msg="Get - deadline exceeded" key=collectors/distributor
level=debug ts=2022-10-21T17:34:52.578374202Z caller=mock.go:150 msg=Get key=collectors/distributor wait_index=61
level=debug ts=2022-10-21T17:34:53.578786151Z caller=mock.go:186 msg="Get - deadline exceeded" key=collectors/distributor
level=debug ts=2022-10-21T17:34:53.578840342Z caller=mock.go:150 msg=Get key=collectors/distributor wait_index=61
level=debug ts=2022-10-21T17:34:53.578861225Z caller=mock.go:186 msg="Get - deadline exceeded" key=collectors/compactor
level=debug ts=2022-10-21T17:34:53.57886893Z caller=mock.go:150 msg=Get key=collectors/compactor wait_index=59
level=debug ts=2022-10-21T17:34:53.578875099Z caller=mock.go:186 msg="Get - deadline exceeded" key=collectors/scheduler
level=debug ts=2022-10-21T17:34:53.578882123Z caller=mock.go:150 msg=Get key=collectors/scheduler wait_index=60
level=debug ts=2022-10-21T17:34:53.578887769Z caller=mock.go:186 msg="Get - deadline exceeded" key=collectors/ring
level=debug ts=2022-10-21T17:34:53.578894222Z caller=mock.go:150 msg=Get key=collectors/ring wait_index=62
```

**To Reproduce**
1. Startet Loki and Promtail and Grafana docker-compose up

Config:

```
version: '3'

services:
  mon_grafana:
    image: grafana/grafana:main
    container_name: mon_grafana
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana:/var/lib/grafana
    ports:
      - 127.0.0.1:3000:3000
    user: "1000"
    networks:
      - monitoring

  mon_loki:
    image: grafana/loki:2.5.0
    container_name: mon_loki
    ports:
      - 127.0.0.1:3100:3100
    command: 
      - -config.file=/etc/loki/local-config.yaml
      - -log.level=debug
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml
      - loki:/data/loki
    networks:
      - monitoring

  mon_promtail:
    image: grafana/promtail:main
    container_name: mon_promtail
    ports:
      - 127.0.0.1:9080:9080
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail/promtail.yaml:/etc/promtail/promtail.yaml
    command: 
      - -config.file=/etc/promtail/promtail.yaml
      - --dry-run
      - -log.level=debug
    networks:
      - monitoring    

  #logstash:
  #  image: grafana/logstash-output-loki:main
  #  container_name: logstash
  #  ports:
  #    - "9200:9200"
  #  command: logstash -f /etc/logstash/conf.d/logstash.conf
  #  volumes:
  #    - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf:ro
  #  environment:
  #    - xpack.monitoring.enabled=false
  #  networks:
  #      - monitoring
  #  depends_on:
  #    - loki

networks:
  monitoring:

volumes:
  grafana:
  loki:
  prometheus:
```

Config Loki:

```
auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
  - from: 2022-10-21
    store: boltdb
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: /tmp/loki/index

  filesystem:
    directory: /tmp/loki/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
```

**Environment:**
 - Infrastructure: Docker compose
 - 

![Captura de tela de 2022-10-21 18-41-02](https://user-images.githubusercontent.com/29265620/197256698-a5422894-609c-4cab-8e65-f1cb042b6733.png)
![Captura de tela de 2022-10-21 18-42-05](https://user-images.githubusercontent.com/29265620/197256866-fd9b735e-19b2-4905-a3de-e5b557a01b16.png)
![Captura de tela de 2022-10-21 18-41-52](https://user-images.githubusercontent.com/29265620/197256870-67fb9173-712c-4f54-9ec7-bebff3428a41.png)
