### ISSUE TITLE
support s3 storage-class

### ISSUE THREAD

**Issue by yanglaoshi666** [grafana/loki#7501]
I looked through the document and didn't see a configuration sample of the storage class of S3, but found that github.com/thanos-io/objstore was used. This is a storage class that supports custom s3. I hope this can be added.

**Comment by chaudum** [comment]
Not entirely sure what you mean, but you can configure S3 (or any S3 compatible backend) in the schema and storage config:

Example:

```yaml
schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: aws
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: aws
  aws:
    bucketnames: my-bucket-name
    region: xxx
    access_key_id: xxx
    secret_access_key: xxx
```

---

If you have questions regarding schema and storage config, please ask on our [community forum](https://community.grafana.com/c/grafana-loki/41) or in the `#loki` channel in [Grafana's Public Slack](https://slack.grafana.com/).

Closing this issue, because it's a question more than an issue.
