### ISSUE TITLE
[Helm] Tokengen Job imagePullSecrets templating issue

### ISSUE THREAD

**Issue by rgarcia6520** [grafana/loki#7523]
**Describe the bug**
Tokengen job pulls it's imagePullSecrets from the top level key with that matching name from the chart, but it iterates through a range unlike the rest of the containers/pods in the chart. When an imagePullSecret is specified, it does not get templated in to the tokengen jobSpec correctly.

**To Reproduce**
1. Started Loki 2.6.1
2. Started Promtail 2.6.1
3. Query: `{} term`

**Expected behavior**
All Loki pods come up healthy, tokengen job executes and completes, helm installation is successful.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm (fluxv2)

**Screenshots, Promtail config, or terminal output**
Current imagePullSecret templating in main:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: enterprise-logs-tokengen
spec:
    ...
    spec:
      ....
      imagePullSecrets:
        - name: map[name:private-registry]
```
Will always lead to a 401 Unauthorized if registry requires auth.
