### ISSUE TITLE
Promtail | out of memory

### ISSUE THREAD

**Issue by r00t9** [grafana/loki#7531]
**Describe the bug**
I get out of memory, i have some servers 4G of memory for some reason i get out of memory very fast one of them. Not sure if have more logs but it should be an issue because /var/log/ is 2G

I test something like this but also not working 

```
limits_config:
  readline_rate_enabled: true
  readline_rate: 100
  readline_rate_drop: false
```
also `max_streams: 10` but then i don't read all the files.

```
du -h -d1 /var/log/
4.0K    /var/log/chrony
4.0K    /var/log/telegraf
5.2M    /var/log/apache2
2.1G    /var/log/journal
112K    /var/log/amazon
98M     /var/log/supervisor
4.0K    /var/log/private
2.3M    /var/log/sssd
88K     /var/log/unattended-upgrades
4.0K    /var/log/landscape
4.8M    /var/log/aws
108K    /var/log/apt
4.0K    /var/log/dist-upgrade
2.3G    /var/log/
```

**To Reproduce**
1. Started Loki (SHA or version)
Test with version: 2.6.1 and build from master with commit -  b4ed595461d595599a72b90b2ae2aa63b7fe6ebb

**Expected behavior**
Set up same memory limit or something so it will not crash production server.

**Environment:**
 - Infrastructure: [AWS VM]
 - Deployment tool: [binary]

**Screenshots, Promtail config, or terminal output**
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: http://test.local:3100/loki/api/v1/push

limits_config:
  readline_rate_enabled: true
  readline_rate: 10000
  readline_rate_drop: false

scrape_configs:
  - job_name: apache
    static_configs:
    - targets:
        - localhost
      labels:
        job: apache
        hostname: test1
        __path__: /var/log/apache2/*.log

  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        hostname: test1
        __path__: /var/log/**/*.log
        __path_exclude__: /var/log/apache2/*,/var/log/journal/*

  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
        hostname: test1
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
```

**Comment by liguozhong** [comment]
That's why in the 1.19 release, Go added support for setting a runtime memory limit. The memory limit may be configured either via the GOMEMLIMIT environment variable which all Go programs recognize

https://tip.golang.org/doc/gc-guide?#Memory_limit

**Comment by liguozhong** [comment]
Memory Limiter Processor
https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md

**Comment by liguozhong** [comment]
```
du -h -d1 /var/log/
4.0K    /var/log/chrony
4.0K    /var/log/telegraf
5.2M    /var/log/apache2
2.1G    /var/log/journal
112K    /var/log/amazon
98M     /var/log/supervisor
4.0K    /var/log/private
2.3M    /var/log/sssd
88K     /var/log/unattended-upgrades
4.0K    /var/log/landscape
4.8M    /var/log/aws
108K    /var/log/apt
4.0K    /var/log/dist-upgrade
2.3G    /var/log/
```

Your case seems to be caused by watch too many files,  adding a max_target: 10 to promtail?

**Comment by r00t9** [comment]
I try with max_targets but that config don't exist.

I test with max_streams but after the limit match /target change the value but don't show anything on loki.

```
Oct 31 12:15:54 uktest1 promtail[1045387]: level=error ts=2022-10-31T12:15:53.98018887Z caller=client.go:288 component=client host=loki.test.local:3100 msg="batch add err" error="streams limit exceeded, streams: 5 exceeds limit: 5, stream: '{job=\"systemd-journal\", unit=\"supervisor.service\"}'"
```

I test with Variable on linux but is not working, maybe is because is soft memory. 

`export GOMEMLIMIT=120MiB`

Not sure where to test this
```
processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 4000
    spike_limit_mib: 800
```
I will test memory limit on systemd maybe.

**Comment by liguozhong** [comment]
```
job=\"systemd-journal\"????

scrape_configs:
  - job_name: apache
        __path__: /var/log/apache2/*log

  - job_name: system
      labels:
        job: varlogs
```

systemd-journal job name?

**Comment by liguozhong** [comment]
What does the configuration file look like? It seems that the job name in the log does not match the job name in the configuration.

**Comment by r00t9** [comment]
I update the config for promtail.

**Comment by liguozhong** [comment]
thanks.
hi, have you tried to delete the journal config whether the OOM still occurs? We need to rule out whether the OOM is caused by the journal
```
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
        hostname: test1
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
```
