### ISSUE TITLE
Ingress service names are not matched in simple scalable deployment mode

### ISSUE THREAD

**Issue by czchen** [grafana/loki#7544]
**Describe the bug**

We found that Ingress service names, which is `{{ include "loki.fullname" $ }}-{{ $svcName }}` does not match service names, which are `{{ include "loki.readFullname" . }}` and `{{ include "loki.writeFullname" . }}`, for simple scalable deployment mode when helm install name is not `loki`.

The service names in Ingress, and scalable deployment mode shall use the same template to ensure these names are matched all the time.

**To Reproduce**

* Install `loki` official helm chart version `3.3.0`, with helm install name __not__ equal to `loki`. And with the following values.yaml to enable `Ingress`. 

    ```yml
    loki:
      storage:
        type: gcs # s3 or azure shall also work
    ingress:
      enabled: true
    gateway:
      enabled: false
    ```
* The Ingress will not be created due to the following error:

    ```log
    invalid ingress spec: could not find service ...
    ```

**Expected behavior**

* `Ingress` shall be created without any problem.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**
N/A
