### ISSUE TITLE
Not being able to query old data that has been just inserted.

### ISSUE THREAD

**Issue by Christian-Vasilev** [grafana/loki#7578]
I'm trying to query old data that I've just inserted. It's a month old but nothing seems to work when I try to fetch it. The label is there, queries are running but no data is returned.

**Example curl request:**

`curl -v -H "Content-Type: application/json" -XPOST -s "http://localhost:3100/loki/api/v1/push" --data-raw \
  '{"streams": [{ "stream": { "label": "test" }, "values": [ [ "1665227955524000000", "mizibuz" ] ] }]}'`
 
 
 ** Curl response:**
```
    *   Trying 127.0.0.1:3100...
    * Connected to localhost (127.0.0.1) port 3100 (#0)
    > POST /loki/api/v1/push HTTP/1.1
    > Host: localhost:3100
    > User-Agent: curl/7.79.1
    > Accept: */*
    > Content-Type: application/json
    > Content-Length: 99
    > 
    * Mark bundle as not supporting multiuse
    < HTTP/1.1 204 No Content
    < Date: Wed, 02 Nov 2022 15:27:29 GMT
    < 
    * Connection #0 to host localhost left intact
```

**Query:**

```
{label="test"} |= ``

logger-loki-1 | level=info ts=2022-11-02T15:43:47.509298439Z caller=metrics.go:133 component=frontend org_id=fake latency=fast query="{label=\"test\"} |= ``" query_type=filter range_type=range length=95h59m59s step=2m0s duration=2.406573006s status=200 limit=1000 returned_lines=0 throughput=0B total_bytes=0B total_entries=0 queue_time=1m3.17540587s subqueries=192
```

I've set it to search for 96 hours. From 2022-10-06 to 2022-10-09. The timestmap of the log is in  Saturday, 8 October 2022 11:19:15.524.

My config
```

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

limits_config:
  reject_old_samples: false
  max_query_length: 0h



storage_config:
  boltdb:
    directory: /tmp/loki/index
  filesystem:
    directory: /tmp/loki/chunks

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h


ruler:
  alertmanager_url: http://localhost:9093

# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
#
# Statistics help us better understand how Loki is used, and they show us performance
# levels for most users. This helps us prioritize features and documentation.
# For more information on what's sent, look at
# https://github.com/grafana/loki/blob/main/pkg/usagestats/stats.go
# Refer to the buildReport method to see what goes into a report.
#
# If you would like to disable reporting, uncomment the following lines:
#analytics:
#  reporting_enabled: false

```
