### ISSUE TITLE
S3 endpoint invalid using Kubernetes secret

### ISSUE THREAD

**Issue by nlamirault** [grafana/loki#7585]
**Describe the bug**
Error when S3 endpoint comes from environment variables set using a Secret.

```yaml
loki:
  # -- Limits config
  limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m

  storage:
    type: s3
    bucketNames:
      chunks: portefaix-homelab-logs-chunks
      ruler: portefaix-homelab-logs-ruler
      admin: portefaix-homelab-logs-admin
    s3:
      s3: null
      endpoint: ${AWS_S3_ENDPOINT}
      region: auto
      access_key_id: ${AWS_ACCESS_KEY_ID}
      secret_access_key: ${AWS_SECRET_ACCESS_KEY}
      s3ForcePathStyle: true
      insecure: false
      http_config: {}

write:
    replicas: 2
    extraEnvFrom:
      - secretRef:
          name: loki-cloudflare-credentials
    resources:
      limits:
        # cpu: 300m
        memory: 600Mi
      requests:
        cpu: 60m
        memory: 200Mi
    persistence:
      size: 1Gi
      storageClassName: nfs-client

  read:
    replicas: 2
    extraEnvFrom:
      - secretRef:
          name: loki-cloudflare-credentials
```
Into the pod, environment variables are correctly set.

I've got these logs:

```
level=info ts=2022-11-03T06:49:22.328033054Z caller=memberlist_client.go:563 msg="joined memberlist cluster" reached_nodes=1
level=info ts=2022-11-03T06:49:22.791907397Z caller=worker.go:209 msg="adding connection" addr=10.42.1.37:9095
level=info ts=2022-11-03T06:49:25.788624563Z caller=frontend_scheduler_worker.go:101 msg="adding connection to scheduler" addr=10.42.1.37:9095
level=info ts=2022-11-03T06:49:25.969290269Z caller=compactor.go:395 msg="this instance should no longer run the compactor, stopping compactor"
level=info ts=2022-11-03T06:49:25.969407157Z caller=compactor.go:400 msg="compactor stopped"
level=error ts=2022-11-03T06:49:28.062554958Z caller=reporter.go:203 msg="failed to delete corrupted cluster seed file, deleting it" err="InvalidEndpointURL: invalid endpoint uri\ncaused by: parse \"https://${AWS_S3_ENDPOINT}\": invalid ch
aracter \"{\" in host name"
level=error ts=2022-11-03T06:49:54.787935767Z caller=ruler.go:497 msg="unable to list rules" err="InvalidEndpointURL: invalid endpoint uri\ncaused by: parse \"https://${AWS_S3_ENDPOINT}\": invalid character \"{\" in host name"
level=error ts=2022-11-03T06:50:54.787788929Z caller=ruler.go:497 msg="unable to list rules" err="InvalidEndpointURL: invalid endpoint uri\ncaused by: parse \"https://${AWS_S3_ENDPOINT}\": invalid character \"{\" in host name"
level=error ts=2022-11-03T06:51:54.787501187Z caller=ruler.go:497 msg="unable to list rules" err="InvalidEndpointURL: invalid endpoint uri\ncaused by: parse \"https://${AWS_S3_ENDPOINT}\": invalid character \"{\" in host name"
level=error ts=2022-11-03T06:52:54.788640178Z caller=ruler.go:497 msg="unable to list rules" err="InvalidEndpointURL: invalid endpoint uri\ncaused by: parse \"https://${AWS_S3_ENDPOINT}\": invalid character \"{\" in host name"
level=error ts=2022-11-03T06:53:21.47574502Z caller=reporter.go:203 msg="failed to delete corrupted cluster seed file, deleting it" err="InvalidEndpointURL: invalid endpoint uri\ncaused by: parse \"https://${AWS_S3_ENDPOINT}\": invalid cha
racter \"{\" in host name"
```

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop] : `Kubernetes`
 - Deployment tool: [e.g., helm, jsonnet] : `Helm`
 - Chart : `Loki v3.3.1`

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
