### ISSUE TITLE
Loki Compactor Log Deletion Not Working When Using Line Filters

### ISSUE THREAD

**Issue by arch-xtof** [grafana/loki#7590]
**Describe the bug**
Loki Compactor `/loki/api/v1/delete` endpoint does not delete logs when line filters are included in the query. On the other hand, logs are deleted if only stream filters are included.
* `query={facility="archilogen"}` works
* `query={facility="archilogen"}|="archilogen-warn"` does not work

**To Reproduce**
1. Start Loki 2.6.1
2. Generate and Forward logs with custom labels and messages. Example: `{facility:archilogen} '{"message":"archilogen-warn"}'`
3. Wait for Chunk to become idle and be sent to the object store
4. Request deletion of Logs
```
curl -I -X POST -H 'X-scope-OrgID: main' -g 'http://<loki_address>/loki/api/v1/delete?query={facility="archilogen"}|="archilogen-warn"'
HTTP/1.1 204 No Content
```
5. verify that the deletion request was successfully initiated:
```
curl -H 'X-scope-OrgID: main' 'http://xxx:3020/loki/api/v1/delete' | jq '.[] | select(.status=="received")'

{
  "request_id": "7cdae6e5",
  "start_time": 0,
  "end_time": 1667381172.093,
  "query": "{facility=\"archilogen\"}|=\"archilogen-warn\"",
  "status": "received",
  "created_at": 1667381172.093
}
```
6. Wait for the deletion request to be processed.
7. check whether logs were deleted either in Grafana or via `loki/api/v1/query_range` endpoint

**Expected behavior**
All logs matching the `{facility="archilogen"} |= "archilogen-warn"` query should be deleted.

**Environment:**
 - Infrastructure: Kubernetes, S3
 - Deployment tool: Kubernetes manifests, Initially generated via Helm and then modified.
 - Loki: `2.6.1`, Distributed deployment model, including various components. See the picture below.

**Screenshots, Configs, etc**
Loki Components:
![image](https://user-images.githubusercontent.com/60723394/199680355-66612105-7f12-4ad4-91d3-81220ce398bf.png)

Relevant Loki Config:
```
common:
  compactor_address: loki-distributed-compactor.loki.svc.cluster.local:3100

compactor:
  compaction_interval: 10m
  delete_request_cancel_period: 15m
  deletion_mode: filter-and-delete
  retention_delete_delay: 2h
  retention_enabled: true
  shared_store: s3

ingester:
  chunk_idle_period: 30m
  chunk_retain_period: 1m

query_range:
  cache_results: true
  results_cache:
    cache:
       enable_fifocache: false
       memcached_client:
         addresses: dns+loki-distributed-memcached-frontend.loki.svc.cluster.local:11211

storage_config:
  boltdb_shipper:
     cache_ttl: 24h
     shared_store: s3
```
Relevant Loki Runtime Config:
```
overrides:
  main:
     allow_deletes: true
```
Relevant Loki Gateway Config:
```
location = /loki/api/v1/delete {
    set $loki_api_v1_delete_backend http://loki-distributed-compactor.loki.svc.cluster.local;
    proxy_pass       $loki_api_v1_delete_backend:3100$request_uri;
    proxy_http_version 1.1;
}
```

I also created a [topic on Grafana Community](https://community.grafana.com/t/loki-log-deletion-with-line-filtering-not-working/75275)
