### ISSUE TITLE
Why "loki-logs" pods are showing up after installing loki as single-binary using helm?

### ISSUE THREAD

**Issue by sulliwane** [grafana/loki#7610]
I upgraded my loki helm chart to v3.

Before I only had ONE loki pod. After the upgrade to the new Helm chart, I have many more pods, and no idea what is their purpose:

![Screenshot from 2022-11-07 11-40-09](https://user-images.githubusercontent.com/1733686/200296985-aa44be90-6373-4198-8b4e-ad93ac27c077.png)

Particularly, what is the purpose of the three "loki-logs" pods and how to disable them?

NOTE: I've installed prometheus from "https://prometheus-community.github.io/helm-charts" that resulted in these pods:
![Screenshot from 2022-11-07 12-16-20](https://user-images.githubusercontent.com/1733686/200297338-275741c7-7da7-418c-9dc3-4843647c8fef.png)

Are these duplicates with "loki-logs" pods?

Thanks a lot for the clarification!

Here is my loki helm values:
```
test:
  enabled: false

monitoring:
  selfMonitoring:
    grafanaAgent:
      installOperator: false
    lokiCanary:
      enabled: false

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: "filesystem"
```

**Comment by AurimasNav** [comment]
I am currently experimenting with different configuration, it seems that loki-logs are deployed when helm tests are enabled (default), try:
```yaml
test:
  enabled: false
```
I concur that any clarification on these components would be appreciated.

**Comment by jeschkies** [comment]
The `loki-logs` pods are from the Grafana Agent Operator and used to self monitor. Checkout our [brand new documentation](https://grafana.com/docs/loki/latest/installation/helm/monitor-and-alert/) on this.

```yaml
selfMonitoring:
  enabled: false
```
should do the trick.

**Comment by Gerrit-K** [comment]
@jeschkies maybe this should be part of the docs about [upgrading from `grafana/loki` 2.x](https://grafana.com/docs/loki/latest/installation/helm/upgrade-from-2.x/#upgrading-from-grafanaloki). I'm currently struggling with the upgrade as well, because there are a _lot_ of changes that are not covered by the upgrade documentation.

For example, if you previously (chart version 2.10.3) had just these values:
```yaml
persistence:
  enabled: true
  size: '20Gi'
config:
  compactor:
    retention_enabled: true
  limits_config:
    retention_period: '90d'
```

you would now need this to roughly achieve the same deployment (and there would yet be additional resources, such as the `loki-memberlist` service ...):
```yaml
singleBinary:
  persistence:
    size: 20Gi
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  compactor:
    retention_enabled: true
  limits_config:
    retention_period: 90d
rbac:
  pspEnabled: true
test:
  enabled: false
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    lokiCanary:
      enabled: false
    grafanaAgent:
      installOperator: false
```
