### ISSUE TITLE
[Helm] Load alerting and recording rules from ConfigMaps in cluster

### ISSUE THREAD

**Issue by ldunkum** [grafana/loki#7629]
**Is your feature request related to a problem? Please describe.**
Since chart version >=3.0.0 we can't inject rules like before. In the old chart we used `extraContainers` to deploy a sidecar that fetched ConfigMaps with rules and mounted them to the Loki pod.

**Describe the solution you'd like**
Since chart version >=3.0.0 we can't inject rules like before. In the old chart we used `extraContainers` to deploy a sidecar that fetched ConfigMaps with rules and mounted them to the Loki pod.

**Describe alternatives you've considered**
After a bit of reading, we think we've identified these options to collect rules:

* collect them with a sidecar and mount them to the pod (which is currently not supported in the chart)
* write them to an s3 bucket thats referenced in `loki.storage.s3` in `values.yaml`. We currently do not know, how to store the rules so they are picked up by the ruler.
* collect ConfigMaps in our CI/CD pipeline and add them with cortextool as described in the docs (see [Interacting with the Ruler](https://grafana.com/docs/loki/latest/rules/#interacting-with-the-ruler))

Is there a recommended way of collecting these rules and adding them to Loki?

**Additional context**
A similar issue with no activity for a while is #5843.

**Comment by ranjitburgute** [comment]
I was able to get Loki rules working with configmap 'loki-rules' and mounted this using below values

```
singleBinary:
  replicas: 3
  extraVolumeMounts:
    - name: rules
      mountPath: /var/loki/rules/fake
  extraVolumes:
    - name: rules
      configMap:
        name: loki-rules
```

**Comment by FreakyBytes** [comment]
I'm in a similar situation as ldunkum and would really like to dynamically define rules dynamically within k8s.

To further ldukum's suggestion to use a sidecar, it would really nice, if the loki Helm chart could include a flag similar to the [Grafana Helm chart](https://github.com/grafana/helm-charts/tree/main/charts/grafana), which basically deploys the [kiwigrid/k8s-sidecar](https://github.com/kiwigrid/k8s-sidecar) sidecar pre-configured in a useful way.

cf. https://github.com/grafana/helm-charts/blob/2d0ff4d6fd6644af721738dd072a2831223c6b06/charts/grafana/templates/_pod.tpl#L99

**Comment by ldunkum** [comment]
We found a work around for our problem by now, as we use FluxCD to deploy, we added a kustomize patch `postRenderers` section and used [kiwigrid/k8s-sidecar](https://github.com/kiwigrid/k8s-sidecar) as mentioned by @FreakyBytes.

```yaml
postRenderers:
  # Instruct helm-controller to use built-in "kustomize" post renderer.
  - kustomize:
      patchesJson6902:
      - patch:
        - op: add
          path: /spec/template/spec/containers/-
          value:
            name: loki-rules-sidecar
            image: kiwigrid/k8s-sidecar:1.19.2
            imagePullPolicy: IfNotPresent
            env:
            - name: LABEL
              value: "loki_rule"
            - name: FOLDER
              value: "/rules/"
            - name: NAMESPACE
              value: ALL
            - name: UNIQUE_FILENAMES
              value: "true"
            volumeMounts:
            - name: rules
              mountPath: /rules
            resources:
              requests:
                cpu: 50m
                memory: 50Mi
              limits:
                memory: 100Mi
        target:
          kind: StatefulSet
          name: loki-read
```

Then we just need to add the volumes for the read StatefulSet:  

```yaml
  read:
    extraVolumes:
    - name: rules
      emptyDir: {}
    extraVolumeMounts:
    - name: rules
      mountPath: /var/loki/rules
```

A native solution as described by @FreakyBytes would of course still be preferred to our (hacky) solution.

**Comment by prasoon-pxc** [comment]
@ldunkum -- does it work for S3 storage tyoe also?

**Comment by ranjitburgute** [comment]
I was able to use extraVolumeMounts and extraVolumes to load loki rules using configmap

```
loki:
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules

singleBinary:
  replicas: 1
  extraVolumeMounts:
    - name: rules
      mountPath: /var/loki/rules/fake
  extraVolumes:
    - name: rules
      configMap:
        name: loki-alerting-rules
```

**Comment by ldunkum** [comment]
@prasoon-pxc Sorry, I'm not sure, we haven't looked into that. I imagine that once you've collected all the ConfigMaps with the kiwigrid sidecar container, you can also mount an s3 bucket to it and use that, but that's just speculation.

**Comment by prasoon-pxc** [comment]
thanks @ldunkum  for your reply, and I was just wondering if this post-rendering is also possible with Argo-CD , but seems it is not possible by default and I need to add some plugins for this to work with Argo-CD, btw thanks

**Comment by ldunkum** [comment]
No problem, after a brief search I found this [blog post](https://dev.to/camptocamp-ops/use-kustomize-to-post-render-helm-charts-in-argocd-2ml6) which explains how to use post-renderers in ArgoCD (take note of the comment that explains var naming after Argo 2.4.  

However, we might be getting a bit off-topic here. Overall it would still be great, if the loki Helm chart would provide this, or similar functionality.

**Comment by prasoon-pxc** [comment]
yes, that would be great !

**Comment by Jeinhaus** [comment]
@vlad-diachenko I think the PR doesn't actually solve this issue.
The idea is to add a sidecar to the pod that is rendered from the chart. If I understand the PR correctly, this would not be the case with `extraObjects`.

**Comment by xinbinhuang** [comment]
After adding the configmaps using `extraObjects`, you can additionally mount them using `extraVolumeMounts` and `extraVolumes` as mentioned in https://github.com/grafana/loki/issues/7629#issuecomment-1343879987. Does this solve the problem? Or is there something has to be achieved by using sidecar?

**Comment by Jeinhaus** [comment]
Our use case is more geared towards multi-tenancy. We have a repository for our platform team, that manages the Loki installation and handles platform specific components. Then we also have development teams, that work in separate repositories on application specific things. 
For this use case it would be great, if the developers could define alerting and recording rules in their repository without needing to interact with the platform team. We solved this by adding the sidecar that picks up any configmaps with a specific label and mounting them to the ruler.

Do you see why the `extraObjects` doesn't work for us here @xinbinhuang @vlad-diachenko

**Comment by xinbinhuang** [comment]
That makes sense. I'll let @.vlad-diachenko to decide to see if reopen or a new issue is more appropriate.

**Comment by vlad-diachenko** [comment]
hey @Jeinhaus . I have reopened the issue to continue the discussion ) 
@Jeinhaus  What do you think we still need to add to address the issue?

**Comment by Jeinhaus** [comment]
hey @vlad-diachenko. Thank you for opening this issue again.
I think adding a way to add sidecars, volumes and volume mounts to the `loki-read` statefulset would be enough for now.

Or is there another way to achieve the usecase mentioned above: 

> Our use case is more geared towards multi-tenancy. We have a repository for our platform team, that manages the Loki installation and handles platform specific components. Then we also have development teams, that work in separate repositories on application specific things. For this use case it would be great, if the developers could define alerting and recording rules in their repository without needing to interact with the platform team. We solved this by adding the sidecar that picks up any configmaps with a specific label and mounting them to the ruler.

**Comment by vlad-diachenko** [comment]
sorry for delay @Jeinhaus . 
volumes already can be added using [.Values.read.extraVolumeMounts](https://github.com/grafana/loki/blob/4cd0aedc76679e4b46ae7d591404debce5f9585b/production/helm/loki/templates/read/statefulset-read.yaml#L114-L116) and [.Values.read.extraVolumes](https://github.com/grafana/loki/blob/4cd0aedc76679e4b46ae7d591404debce5f9585b/production/helm/loki/templates/read/statefulset-read.yaml#L154-L156)

Sidecards are not supported right now in loki helm chart. but you can easily add it to helm char https://github.com/grafana/loki/tree/main/production/helm/loki . feel free to create a PR and ping me to review it. 

However, I believe you can develop your own small k8s operator that will listen for the resources created by your external team and update some centralized configmap. This configmap can be mounted to read pods.

**Comment by Jeinhaus** [comment]
It seems @acolombier was so nice to do that in https://github.com/grafana/loki/pull/9399.

> However, I believe you can develop your own small k8s operator that will listen for the resources created by your external team and update some centralized configmap. This configmap can be mounted to read pods.

Yeah, that's probably the cleaner solution, even though the way using labeled configmaps works quite well, just like it does for Grafana dashboards. I'm not sure the operator is really worth the effort.

**Comment by miglocatiq** [comment]
> @Jeinhaus After adding the configmaps using `extraObjects`, you can additionally mount them using `extraVolumeMounts` and `extraVolumes` as mentioned in [#7629 (comment)](https://github.com/grafana/loki/issues/7629#issuecomment-1343879987). Does this solve the problem? Or is there something has to be achieved by using sidecar?

I've tried this, and I see the file is present in the read pod. But how does this work after that? I don't see these alerts in Grafana or anywhere on my k8s cluster

**Comment by ldunkum** [comment]
Hey @miglocatiq, I'm not 100% sure, but I think updating the `rulerConfig` should suffice.

We've set it up like this:

```yaml
rulerConfig:
  alertmanager_url: http://alertmanager-operated:9093
  external_url: https://alertmanager.example.com
  storage:
    type: local
    local:
      directory: /var/loki/rules
```

**Comment by miglocatiq** [comment]
> Hey @miglocatiq, I'm not 100% sure, but I think updating the `rulerConfig` should suffice.
> 
> We've set it up like this:
> 
> ```yaml
> rulerConfig:
>   alertmanager_url: http://alertmanager-operated:9093
>   external_url: https://alertmanager.example.com
>   storage:
>     type: local
>     local:
>       directory: /var/loki/rules
> ```
> 
> Edit: I missed the config in the read pods, we set up `extraVolumes` and `extraVolumeMounts`:
> 
> ```yaml
> read:
>   extraVolumes:
>   - name: rules
>     emptyDir: {}
>   extraVolumeMounts:
>   - name: rules
>     mountPath: /var/loki/rules
> ```

Thanks, that's what I have, but for some reason the ruler doesn't seem to work. I see the ruler config is correctly loaded into Loki. Is there anything else I can check?

**Comment by ldunkum** [comment]
Sorry for the late reply, we were just debugging something related to this today. 
We are using flux to deploy the Helm chart and we added a kustomize PostRenderer to our HelmRelease.  

```yaml
postRenderers:
  # Instruct helm-controller to use built-in "kustomize" post renderer.
  - kustomize:
      patchesJson6902:
      - patch:
        - op: add
          path: /spec/template/spec/containers/-
          value:
            name: loki-rules-sidecar
            image: kiwigrid/k8s-sidecar:1.19.2
            imagePullPolicy: IfNotPresent
            env:
            - name: LABEL
              value: "loki_rule"
            - name: FOLDER
              value: "/rules/fake"
            - name: NAMESPACE
              value: ALL
            - name: UNIQUE_FILENAMES
              value: "true"
            volumeMounts:
            - name: rules
              mountPath: /rules
            resources:
              requests:
                cpu: 50m
                memory: 50Mi
              limits:
                memory: 100Mi
        target:
          kind: Deployment
          name: loki-read
``` 

As long as the ConfigMaps have the label "loki_rule" it should be picked up and added by the sidecar to the volume.  
(Note: In Loki v2.8.0 loki-read was changed from a StatefulSet to a Deployment, so if you're using an earlier version maybe change the target.kind.)

**Comment by stringang** [comment]
`loki-distributed` chart ruler config:
```yaml
ruler:
  enabled: true
  directories:
   fake:   # <------  in single tenant mode, the tenant ID is "fake"
    rules1.txt: |
     groups:
      - name: should_fire
        rules:
         - alert: HighPercentageError
           expr: |
             sum(rate({app="foo", env="production"} |= "error" [5m])) by (job)
               /
             sum(rate({app="foo", env="production"}[5m])) by (job)
               > 0.05
           for: 10m
           labels:
             severity: warning
           annotations:
             summary: High error rate
```

**Comment by hauks96** [comment]
This feature should be a high priority in my opinion.

The standard way to upload custom rules for Prometheus as well as Thanos is by PrometheusRule resources picked up by sidecars. The same thing goes for Grafana dashboards and datasources. Take [kube-prometheus-stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack) helm chart for example, there you can specify a custom matchLabel that you can put on your PrometheusRule as a label so that the rules are added to the Thanos datsource:

```yaml
thanosRuler:
  thanosRulerSpec:
    ruleSelector:
      matchLabels:
      datasource: "thanos"
```

Anything other than this approach requires hard-coding all alerts and records at a single source, which is just an inconvenient solution all together when working with multiple projects that should be able to control their own alerting and recording mechanisms.

**Comment by hauks96** [comment]
There is a merge request pending review for this feature https://github.com/grafana/loki/pull/9399

**Comment by Jeinhaus** [comment]
The [loki documentation suggests using the `cortextool`](https://grafana.com/docs/loki/latest/rules/#interacting-with-the-ruler). But I haven't tried that.

**Comment by dmitry-mightydevops** [comment]
@hauks96 

- grafana 10.1.5
- loki 2.9.2

latest grafana/loki helm chart **5.36.2** support sidecar to load configmaps by labels into pod for further processing:

### configmap

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-additional-rules
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    loki_rule: 'true'
data:
  additional-loki-rules.yaml: |
    groups:
      - name: additional_loki_rules
        interval: 1m
        rules:
          - record: job:loki:kex:application:sum_rate
            expr: sum(rate({app="kubernetes-event-exporter"} | json | kind="Application" [5m])) by (name)
            labels:
              cluster: loki
      - name: should_fire
        rules:
          - alert: test_alert
            expr: |
              sum(rate({app="kubernetes-event-exporter"} | json | kind="Application" [5m])) by (name) > 0.05
            for: 0s
            labels:
                severity: page
            annotations:
                summary: test
```

### loki helm values:

```yaml
loki:
  ...
  rulerConfig:
    wal:
      dir: /loki/ruler-wal
    storage:
      type: local
      local:
        directory: /rules
    rule_path: /rules/fake
    remote_write:
      enabled: true
      client:
        url: http://prometheus-prometheus.prometheus.svc:9090/api/v1/write
    alertmanager_url: http://prometheus-alertmanager.prometheus.svc:9093
    enable_api: true
    ring:
      kvstore:
        store: inmemory
    enable_alertmanager_v2: true
sidecar:
  rules:
    label: loki_rule
    labelValue: 'true'
    folder: /rules/fake
    searchNamespace: ALL
    resource: configmap # configmap, secret, or both.
```

### you can also create such configmaps using **extraObjects**:

```yaml
# Create extra manifests via values. Would be passed through `tpl` for templating
extraObjects: []
# - apiVersion: v1
#   kind: ConfigMap
#   metadata:
#     name: loki-alerting-rules
#   data:
#     loki-alerting-rules.yaml: |-
#       groups:
#         - name: example
#           rules:
#           - alert: example
#             expr: |
#               sum(count_over_time({app="loki"} |~ "error")) > 0
#             for: 3m
#             labels:
#               severity: warning
#               category: logs
#             annotations:
#               message: "loki has encountered errors"
```

**Comment by hauks96** [comment]
Yes, I know, thank you, this was added when the issue I linked here got merged :P

**Comment by federicopires** [comment]
If I understand correctly the sidecar works for loki-backend pods where the ruler is running. Do we still need to mount the configmap in Loki Read pods?

**Comment by MartinEmrich** [comment]
I try to provision my rules as a config map as described above. I use Loki 3 and the Helm chart 6.x in "simple-scalable" mode (backend, reader, writer). Both the logs as well as the gateway config suggest that all ruler-related code runs in the backend statefulset.

I have added my rules ConfigMap as described (looks root within the container with `kubectl exec -- /binsh`), but I get this error and do not see any rules:

````
level=warn ts=2024-10-14T11:52:58.963725382Z caller=mapper.go:41 msg="unable to remove user directory" path=/lokirules/fake err="unlinkat /lokirules/fake: read-only file system"
````
Reading through the code (https://github.com/grafana/loki/blob/main/pkg/ruler/base/mapper.go#L37-L43 ff.), it looks like Loki wants to write to the rules directory `/lokirules/fake`, which is read-only if mapped from a configmap.
There's also lots of code trying to "sync" rules (with whatever) also hinting for the need to have a writeable rules directory.

My `rulerConfig:`
````
      rulerConfig:
        alertmanager_url: http://{{ prometheus_ip }}:9093/alertmanager
        enable_alertmanager_v2: true
        enable_api: true
        enable_sharding: true
        remote_write:
          enabled: true
          client:
            url: http://{{ prometheus_ip }}:9090/prometheus/api/v1/write
        rule_path: /lokirules
        storage:
          type: local
          local:
            directory: /var/loki/rules
````

Reading through the code (https://github.com/grafana/loki/blob/main/pkg/ruler/base/mapper.go#L37-L43 ff.), it looks like Loki wants to write to the rules directory `/lokirules/fake`, which is read-only if mapped from a configmap.

Is this why you need that sidecar approach (copying from the read-only configMap volume to a read-write emptyDir one?
Or am I missing something?
