### ISSUE TITLE
Feature request: Loki alert rule tests

### ISSUE THREAD

**Issue by dannystaple** [grafana/loki#7655]
**Is your feature request related to a problem? Please describe.**
When making prometheus alert or recording rules, there's a system to test them. Making Loki alert or recording rules is frustrating since there's no clear testing system.

**Describe the solution you'd like**
I'd like a system for Loki that mirrors the prometheus system described at https://prometheus.io/docs/prometheus/latest/configuration/unit_testing_rules/.

**Describe alternatives you've considered**
Keeping things in prometheus as much as possible, so promtool test can be used. Making Loki recording rules only if possible.

**Additional context**
This could potentially be a loki tool, or some kind of cortextool extension?

**Comment by kavirajk** [comment]
I love idea. Loki already have a CLI tool (logcli). Would love to see something like this integrated into LogCLI. May be LogCLI is the best place for it?

**Comment by fraserdarwent** [comment]
+1 would be great to have

**Comment by superg28-dm** [comment]
+1 was just searching if this was possible

**Comment by jsolana** [comment]
+1 , any news related?

**Comment by matthewhudsonedb** [comment]
I have this PR ready for review, I've tried to follow promtools implementation as closely as possible: https://github.com/grafana/loki/pull/20484
Readme in PR: https://github.com/matthewhudsonedb/loki/tree/lokitestrules/pkg/tool/rules

**Comment by swb1systems** [comment]
@matthewhudsonedb This is really cool! But I've tried to create a test case and use your `lokitool` version but it always SUCCEEDs (although it should not).

This is my test setup:

file name: `dovecot-logs.yaml`
```
groups:
  - name: Dovecot
    rules:
      - alert: DovecotChildKill
        expr: |
           count_over_time(
             {app_kubernetes_io_name="dovecot"}
             |~ `child \d+ killed with signal 9`
             [10m]
           ) > 0
        for: "2m"
        labels:
          severity: critical
        annotations:
          summary: A Dovecot process was killed by SIGKILL
          description: >-
            Dovecot process in Pod {{ $labels.namespace }}/{{ $labels.kubernetes_pod_name }} in cluster {{ $labels.cluster }} was killed by SIGKILL.
```

file name: `dovecot-logs_test.yaml`
```
rule_files:
  - dovecot-logs.yaml

evaluation_interval: 1m

tests:
  - name: "Alert DovecotChildKill is fired"
    interval: 1m
    input_streams:
      - labels: '{app_kubernetes_io_name="dovecot", namespace="test_namespace", cluster="test_cluster", kubernetes_pod_name="test_kubernetes_pod_name"}'
        lines:
          - 'pop3-login: Fatal: master: service(pop3-login): child 538442 killed with signal 9'
    alert_rule_test:
      - alertname: DovecotChildKill
        eval_time: 2m
        exp_alerts: []
      - alertname: DovecotChildKill
        eval_time: 2m
        exp_labels:
          severity: critical
        exp_annotations:
          summary: A Dovecot process was killed by SIGKILL
          description: >-
            Dovecot process in Pod test_namespace/test_kubernetes_pod_name in cluster test_cluster was killed by SIGKILL.
```

**Comment by swb1systems** [comment]
Turns out: The problem was me. I forgot to define an `exp_alerts` list in the second `alert_test_rule` case. If I do, the alert fires (although not in a way _I_ expected). So thank you for your fabulous tool which will allow us to lint, test and rethink our loki log alerts!

**Comment by swb1systems** [comment]
Feeback
---

After evaluating your version of `lokitool` I have found a couple of problems:

**Problem 1: Go Templating variables won't be resolved in `labels` and `annotations`:**

_File name: `dovecot-logs.yaml`_
```
groups:
  - name: Dovecot
    rules:
      - alert: DovecotChildKill
        expr: |
           count_over_time(
             {app_kubernetes_io_name="dovecot"}
             |~ `child \d+ killed with signal 9`
             [10m]
           ) > 0
        for: "2m"
        labels:
          severity: critical
          UserLogin: "{{ $labels.cluster }}-alertmanager@localhost"
        annotations:
          summary: A Dovecot process was killed by SIGKILL
          description: >-
            Dovecot process in Pod {{ $labels.namespace }}/{{ $labels.kubernetes_pod_name }} in cluster {{ $labels.cluster }} was killed by SIGKILL.
```

_File name: `dovecot-logs_test.yaml`_
```
rule_files:
  - dovecot-logs.yaml
evaluation_interval: 1m
tests:
  - name: "Alert DovecotChildKill is fired"
    interval: 1m
    input_streams:
      - labels: '{app_kubernetes_io_name="dovecot", namespace="test_namespace", cluster="test_cluster", kubernetes_pod_name="test_kubernetes_pod_name"}'
        lines:
          - 'pop3-login: Fatal: master: service(pop3-login): child 538442 killed with signal 9'
    alert_rule_test:
      - alertname: DovecotChildKill
        eval_time: 1m
        exp_alerts: []
      - alertname: DovecotChildKill
        eval_time: 3m
        exp_alerts:
          - exp_labels:
              app_kubernetes_io_name: "dovecot"
              cluster: "test_cluster"
              kubernetes_pod_name: "test_kubernetes_pod_name"
              namespace: "test_namespace"
              severity: critical
              UserLogin: "test_cluster-alertmanager@localhost"
            exp_annotations:
              summary: A Dovecot process was killed by SIGKILL
              description: >-
                Dovecot process in Pod test_namespace/test_kubernetes_pod_name in cluster test_cluster was killed by SIGKILL.
```

_Result_:
```
FAILED:
  name: Alert DovecotChildKill is fired,
  alertname: DovecotChildKill, time: 3m,
    exp:[
        0:
          Labels:{UserLogin="test_cluster-alertmanager@localhost", app_kubernetes_io_name="dovecot", cluster="test_cluster", kubernetes_pod_name="test_kubernetes_pod_name", namespace="test_namespace", severity="critical"}
          Annotations:{description="Dovecot process in Pod test_namespace/test_kubernetes_pod_name in cluster test_cluster was killed by SIGKILL.", summary="A Dovecot process was killed by SIGKILL"}
        ], 
    got:[
        0:
          Labels:{UserLogin="{{ $labels.cluster }}-alertmanager@localhost", app_kubernetes_io_name="dovecot", cluster="test_cluster", kubernetes_pod_name="test_kubernetes_pod_name", namespace="test_namespace", severity="critical"}
          Annotations:{description="Dovecot process in Pod {{ $labels.namespace }}/{{ $labels.kubernetes_pod_name }} in cluster {{ $labels.cluster }} was killed by SIGKILL.", summary="A Dovecot process was killed by SIGKILL"}
        ]

lokitool: error: unit tests failed: 1 of 2 tests failed, try --help
```
---
**Problem 2: Evaluations are not independent from each other**

When I delete one of the two evaluations the result of the other changes.

_File name: `dovecot-logs.yaml`_
```
groups:
  - name: Dovecot
    rules:
      - alert: DovecotChildKill
        expr: |
           count_over_time(
             {app_kubernetes_io_name="dovecot"}
             |~ `child \d+ killed with signal 9`
             [10m]
           ) > 0
        for: "2m"
        labels:
          severity: critical
          UserLogin: "{{ $labels.cluster }}-alertmanager@localhost"
        annotations:
          summary: A Dovecot process was killed by SIGKILL
          description: >-
            Dovecot process in Pod {{ $labels.namespace }}/{{ $labels.kubernetes_pod_name }} in cluster {{ $labels.cluster }} was killed by SIGKILL.
```

_File name: `dovecot-logs_test.yaml`_
```
rule_files:
  - dovecot-logs.yaml
evaluation_interval: 1m
tests:
  - name: "Alert DovecotChildKill is fired"
    interval: 1m
    input_streams:
      - labels: '{app_kubernetes_io_name="dovecot", namespace="test_namespace", cluster="test_cluster", kubernetes_pod_name="test_kubernetes_pod_name"}'
        lines:
          - 'pop3-login: Fatal: master: service(pop3-login): child 538442 killed with signal 9'
    alert_rule_test:
      - alertname: DovecotChildKill
        eval_time: 3m
        exp_alerts:
          - exp_labels:
              app_kubernetes_io_name: "dovecot"
              cluster: "test_cluster"
              kubernetes_pod_name: "test_kubernetes_pod_name"
              namespace: "test_namespace"
              severity: critical
              UserLogin: "test_cluster-alertmanager@localhost"
            exp_annotations:
              summary: A Dovecot process was killed by SIGKILL
              description: >-
                Dovecot process in Pod test_namespace/test_kubernetes_pod_name in cluster test_cluster was killed by SIGKILL.
```

_Result:_
```
  name: Alert DovecotChildKill is fired,
  alertname: DovecotChildKill, time: 3m,
    exp:[
        0:
          Labels:{UserLogin="test_cluster-alertmanager@localhost", app_kubernetes_io_name="dovecot", cluster="test_cluster", kubernetes_pod_name="test_kubernetes_pod_name", namespace="test_namespace", severity="critical"}
          Annotations:{description="Dovecot process in Pod test_namespace/test_kubernetes_pod_name in cluster test_cluster was killed by SIGKILL.", summary="A Dovecot process was killed by SIGKILL"}
        ], 
    got:[]

lokitool: error: unit tests failed: 1 of 1 tests failed, try --help
```
---
**Problem 3: Inconsistent results**

Now in this scenario no alert fires although it should.

_File name: `dovecot-logs.yaml`_
```
groups:
  - name: Dovecot
    rules:
      - alert: DovecotChildKill
        expr: |
           count_over_time(
             {app_kubernetes_io_name="dovecot"}
             |~ `child \d+ killed with signal 9`
             [10m]
           ) > 0
        for: "2m"
        labels:
          severity: critical
          UserLogin: "{{ $labe
          ls.cluster }}-alertmanager@localhost"
        annotations:
          summary: A Dovecot process was killed by SIGKILL
          description: >-
            Dovecot process in Pod {{ $labels.namespace }}/{{ $labels.kubernetes_pod_name }} in cluster {{ $labels.cluster }} was killed by SIGKILL.
```

_File name: `dovecot-logs_test.yaml`_
```
rule_files:
  - dovecot-logs.yaml
evaluation_interval: 1m
tests:
  - name: "Alert DovecotChildKill is fired"
    interval: 1m
    input_streams:
      - labels: '{app_kubernetes_io_name="dovecot", namespace="test_namespace", cluster="test_cluster", kubernetes_pod_name="test_kubernetes_pod_name"}'
        lines:
          - 'pop3-login: Fatal: master: service(pop3-login): child 538442 killed with signal 9'
    alert_rule_test:
      - alertname: DovecotChildKill
        eval_time: 3m
        exp_alerts: []
```

_Result:_
```
SUCCESS
```

**Comment by matthewhudsonedb** [comment]
thanks @swb1systems Seems theres some bugs to iron out here still. I'll add some additional test cases to cover the above scenarios.

**Comment by matthewhudsonedb** [comment]
@swb1systems those bugs should be ironed out now. Care to test again?

**Comment by swb1systems** [comment]
@matthewhudsonedb I have started to create unit tests for log alerts for the [openDesk](https://www.opendesk.eu/) project. My early feedback after four unit tests: no problems so far. I'll report back when I have gathered more experience by building more unit tests.

**Comment by swb1systems** [comment]
@matthewhudsonedb Right the next unit test hit a roadbloack. This is one of our expressions:

```
sum by(cluster, customer, repo, git_error) (count_over_time({namespace="argocd", pod_name=~"argocd-repo-server-.+"}[5m]
    | json 
    | line_format `{{.log}}` 
    | logfmt 
    | level = `error` 
    | line_format `{{.msg}}` 
    | msg =~ `^Failed to get git client for repo .+` 
    | pattern `Failed to get git client for repo <repo>: <git_error>`))
```
Unfortunately, the `line_format` function to select one of the fields seems to be [unsupported](https://github.com/matthewhudsonedb/loki/tree/lokitestrules/pkg/tool/rules). At least this input stream did not trigger the alert:

```
input_streams:
    - labels: '{namespace="argocd", pod_name="argocd-repo-server-test", cluster="test_cluster", customer="test_customer"}'
      lines:
        - '{"log":"level=error msg=\"Failed to get git client for repo test_repo: test_git_error\""}'
```

**Comment by swb1systems** [comment]
It would be awesome to have some kind of neat syntax to bulk generate log entries. Something like `promtool` does with its `1+2x3` syntax. So a mechanism which generates `n` log lines and accepts a loop `integer` variable (or alternatively a `character` or `string`?) which can be incremented easily.

For example, `1+2x3, "My logline with var $1"` could mean:
```
My logline with var 1
My logline with var 3
My logline with var 5
My logline with var 7
```
This would be handy in situations where you need to generate lots of log lines to trigger the alert.

**Comment by swb1systems** [comment]
So here is my feedback in form of three somewhat simplified but real world alerts and my attempts to write unit tests for them. I have an idea why the second and third example do not work but I have no clue about the first one. Forgive me my inexperience but I still have to learn the basics of Loki unit tests. ;)

`lokiunittests-alerts.yaml`
```
groups:
  - name: fluentbit
    rules:
      - alert: FluentbitChunkTooLargeToUpload
        expr: |
          sum by (cluster, customer) (rate({container_name="fluent-bit"} |~ `\[error\].+remote-write.loki.central-monitoring.example.com.+HTTP status=413` [30m])) > 0
            or
          sum by (cluster, customer) (rate({kubernetes_container_name="fluent-bit"} |~ `\[error\].+remote-write.loki.central-monitoring.example.com.+HTTP status=413` [30m])) > 0
        for: "30m"
        labels:
          severity: error
          UserLogin: "{{ $labels.cluster }}-alertmanager@localhost"
        annotations:
          summary: "FluentBit could not upload a log chunk to the central-monitoring system because the chunk is too large"
          description: >-
            A FluentBit instance of customer '{{ $labels.customer }}' running on cluster '{{ $labels.cluster }}' failed to upload a chunk of logs to remote-write.loki.central-monitoring.opendesk.b1-systems.de.
            It got HTTP Status-Code 413 in response (Request Entity Too Large)

      - alert: FluentbitLogCollectionFailure
        expr: |
          sum by (cluster, customer) (
            count_over_time(
              {cluster!="central-monitoring", pod_name=~"fluentbit-fluent-bit-.*"}
              |= "pausing tail.0"
              [10m]
            )
          ) > 50
        for: "2m"
        labels:
          severity: error
          UserLogin: "{{ $labels.cluster }}-alertmanager@localhost"
          # impact: TODO
        annotations:
          summary: "FluentBit could not collect logs"
          description: >-
            A FluentBit instance of customer '{{ $labels.customer }}' running on cluster '{{ $labels.cluster }}' failed to collect logs.

      - alert: ArgocdFailedToGit
        expr: |
          sum by(cluster, customer, repo, git_error) (count_over_time({namespace="argocd", pod_name=~"argocd-repo-server-.+"}[5m] 
              | json 
              | line_format `{{.log}}` 
              | logfmt 
              | level = `error` 
              | line_format `{{.msg}}` 
              | msg =~ `^Failed to get git client for repo .+` 
              | pattern `Failed to get git client for repo <repo>: <git_error>`))
        for: "5m"
        labels:
          severity: error
          UserLogin: "{{ $labels.cluster }}-alertmanager@localhost"
        annotations:
          summary: "ArgoCD could not fetch Configuration-As-Code ressources"
          description: >
            The ArgoCD-Repo-Server running for customer '{{ $labels.customer }}' in cluster '{{ $labels.cluster }}' could not perform a refresh of its configuration from git repository '{{ $labels.repo }}' with the following error:

            {{ $labels.git_error }}
```

`lokiunittests-alerts_test.yaml`
```
rule_files:
  - lokiunittests-alerts.yaml

evaluation_interval: 1m

tests:
  - name: "Alert FluentbitChunkTooLargeToUpload fires"
    interval: 1m
    input_streams:
      - labels: '{container_name="fluent-bit", cluster="test_cluster", customer="test_customer"}'
        lines:
          - '[error] test remote-write.loki.central-monitoring.example.com test HTTP status=413'
    alert_rule_test:
      - alertname: FluentbitChunkTooLargeToUpload
        eval_time: 29m
        exp_alerts: []
      - alertname: FluentbitChunkTooLargeToUpload
        eval_time: 30m
        exp_alerts:
          - exp_labels:
              cluster: "test_cluster"
              customer: "test_customer"
              pod_name: "fluentbit-fluent-bit-test"
              severity: error
              UserLogin: "test_cluster-alertmanager@localhost"
            exp_annotations:
              summary: "FluentBit could not upload a log chunk to the central-monitoring system because the chunk is too large"
              description: >-
                A FluentBit instance of customer 'test_customer' running on cluster 'test_cluster' failed to upload a chunk of logs to remote-write.loki.central-monitoring.example.com.
                It got HTTP Status-Code 413 in response (Request Entity Too Large)

  - name: "Alert FluentbitLogCollectionFailure fires"
    interval: 1m
    input_streams:
      - labels: '{pod_name="fluentbit-fluent-bit-test", cluster="test_cluster", customer="test_customer"}'
        lines:
          # UPSTREAM: no mechanism available to bulk generate log lines
          - "pausing tail.0"
    alert_rule_test:
      - alertname: FluentbitLogCollectionFailure
        eval_time: 1m
        exp_alerts: []
      - alertname: FluentbitLogCollectionFailure
        eval_time: 2m
        exp_alerts:
          - exp_labels:
              cluster: "test_cluster"
              customer: "test_customer"
              pod_name: "fluentbit-fluent-bit-test"
              severity: error
              UserLogin: "test_cluster-alertmanager@localhost"
            exp_annotations:
              summary: "FluentBit could not collect logs"
              description: >-
                A FluentBit instance of customer 'test_customer' running on cluster 'test_cluster' failed to collect logs.

  - name: "Alert ArgocdFailedToGit fires"
    interval: 1m
    input_streams:
      - labels: '{namespace="argocd", pod_name="argocd-repo-server-test", cluster="test_cluster", customer="test_customer"}'
        lines:
          # UPSTREAM: line_format unsupported
          # https://github.com/grafana/loki/issues/7655#issuecomment-4198982174
          - '{"log":"level=error msg=\"Failed to get git client for repo test_repo: test_git_error\""}'
    alert_rule_test:
      - alertname: ArgocdFailedToGit
        eval_time: 4m
        exp_alerts: []
      - alertname: ArgocdFailedToGit
        eval_time: 5m
        exp_alerts:
          - exp_labels:
              cluster: "test_cluster"
              customer: "test_customer"
              namespace: "argocd"
              pod_name: "argocd-repo-server-test"
              severity: error
              UserLogin: "test_cluster-alertmanager@localhost"
            exp_annotations:
              summary: "ArgoCD could not fetch Configuration-As-Code ressources"
              description: >-
                The ArgoCD-Repo-Server running for customer 'test_customer' in cluster 'test_cluster' could not perform a refresh of its configuration from git repository 'test_repo' with the following error:

                test_git_error
```
