### ISSUE TITLE
Loki declarative config.yaml can't connect to minio

### ISSUE THREAD

**Issue by rufreakde** [grafana/loki#7686]
# error log loki - connection reset by peer
```
│ level=info ts=2022-11-14T10:21:26.54920171Z caller=table_manager.go:167 msg="handing over indexes to shipper"                                                                                                                                    │
│ level=info ts=2022-11-14T10:21:26.549251138Z caller=table_manager.go:134 msg="uploading tables"                                                                                                                                                  │
│ level=error ts=2022-11-14T10:21:26.562939882Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: SerializationError: failed to unmarshal error message\n\tstatus code: 400, request id: , host id: \ncaused by: Un │
│ marshalError: failed to unmarshal error message\n\t00000000  43 6c 69 65 6e 74 20 73  65 6e 74 20 61 6e 20 48  |Client sent an H|\n00000010  54 54 50 20 72 65 71 75  65 73 74 20 74 6f 20 61  |TTP request to a|\n00000020  6e 20 48 54 54 50 5 │
│ 3 20  73 65 72 76 65 72 2e 0a  |n HTTPS server..|\n\ncaused by: read tcp 100.64.0.41:56830->100.64.1.61:9000: read: connection reset by peer"                                                                                                    │
│ level=error ts=2022-11-14T10:21:26.562997275Z caller=flush.go:146 org_id=fake msg="failed to flush user" err="store put chunk: SerializationError: failed to unmarshal error message\n\tstatus code: 400, request id: , host id: \ncaused by: Un │
│ marshalError: failed to unmarshal error message\n\t00000000  43 6c 69 65 6e 74 20 73  65 6e 74 20 61 6e 20 48  |Client sent an H|\n00000010  54 54 50 20 72 65 71 75  65 73 74 20 74 6f 20 61  |TTP request to a|\n00000020  6e 20 48 54 54 50 5 │
│ 3 20  73 65 72 76 65 72 2e 0a  |n HTTPS server..|\n\ncaused by: read tcp 100.64.0.41:56816->100.64.1.61:9000: read: connection reset by peer"
...
```

My loki config with default minio secret user for testing
```yaml
spec:
# deployed with argocd helm chart
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 3.1.0
    helm:
      releaseName: up-monitoring
      values: |
        loki:
          existingSecretForConfig: "loki-config-secret"
          commonConfig:
            path_prefix: /tmp
            replication_factor: 1

        enterprise:
          enabled: false

        monitoring:
          rules:
            enabled: true
            alerting: true
            namespace: up-monitoring
            annotations: {}
            labels:
              matchLabels:
                prometheus: k8s
                role: alert-rules
            additionalGroups:
            - name: additional-loki-rules
              rules:
                - record: job:loki_request_duration_seconds_bucket:sum_rate
                  expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job)
                - record: job_route:loki_request_duration_seconds_bucket:sum_rate
                  expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job, route)
                - record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
                  expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (node, namespace, pod, container)

          alerts:
            enabled: true
            namespace: up-monitoring
            annotations: {}
            labels: {}
          serviceMonitor:
            enabled: true
            namespace: up-monitoring
            namespaceSelector: {}
            annotations: {}
            labels: {}
            interval: null
            scrapeTimeout: null
            relabelings: []
            scheme: http
            tlsConfig: null

        read:
          replicas: 2
          persistence:
            size: 5Gi
            storageClassName: default
          autoscaling:
            enabled: true
            size: 5Gi
          extraVolumes:
            - name: bolt-db
              emptyDir: {}
          extraVolumeMounts:
            - name: bolt-db
              mountPath: /tmp

        write:
          replicas: 2
          persistence:
            size: 5Gi
            storageClassName: default
          extraVolumes:
            - name: bolt-db
              emptyDir: {}
          extraVolumeMounts:
            - name: bolt-db
              mountPath: /tmp
```
this is the config secret used by loki:
```yaml
# all just test values
apiVersion: v1
kind: Secret
metadata:
  name: loki-config-secret
  namespace: up-monitoring
type: Opaque
stringData:
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    memberlist:
      join_members: ["loki-read", "loki-write"]
      dead_node_reclaim_time: 30s
      gossip_to_dead_nodes_time: 15s
      left_ingesters_timeout: 30s
      bind_addr: ['0.0.0.0']
      bind_port: 7946
      gossip_interval: 2s

    common:
      storage:
        s3: # minio connect configuration
          endpoint: minio1-hl.up-monitoring-db.svc.cluster.local.:9000
          bucketnames: chunks
          access_key_id: minio
          secret_access_key: minio123
          s3forcepathstyle: true
          insecure: true

    limits_config:
      max_cache_freshness_per_query: '10m'
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 30m
      ingestion_rate_mb: 10
      ingestion_burst_size_mb: 20
      split_queries_by_interval: 15m
      retention_period: 48h
      retention_stream:
        - selector: '{app="*"}'
          priority: 1
          period: 720h

    chunk_store_config:
      chunk_cache_config:
        memcached:
          batch_size: 256
          parallelism: 10
        memcached_client:
          host: ""
          service: "memcached-client"

    schema_config:
      configs:
        - from: 2022-09-07
          store: boltdb-shipper
          object_store: aws
          schema: v12
          index:
            prefix: loki_index_
            period: 24h

    query_range:
      cache_results: false
      results_cache:
        cache:
          default_validity: "12h"
          memcached_client:
            host: ""
            service: "memcached-client"
            timeout: "500ms"

    storage_config:
      boltdb_shipper:
        shared_store: s3
        active_index_directory: "/tmp/index"
        cache_location: /tmp/boltdb-cache

    query_scheduler:
      max_outstanding_requests_per_tenant: 1024

    compactor:
      working_directory: /tmp/compactor
      retention_enabled: true
      shared_store: s3

    ingester:
      lifecycler:
        join_after: 10s
        observe_period: 5s
        ring:
          replication_factor: 1
          kvstore:
            store: memberlist
        final_sleep: 0s
      chunk_idle_period: 1m
      wal:
        enabled: true
        dir: /tmp/wal
      max_chunk_age: 1m
      chunk_retain_period: 30s
      chunk_encoding: snappy
      chunk_target_size: 1.572864e+06
      chunk_block_size: 262144
      flush_op_timeout: 10s

```

```yaml
# minio
secrets:
  name: minio1-env-configuration
  # MinIO root user and password
  accessKey: minio
  secretKey: minio123
```

Somehow it does not connect is the `common.storage` config wrong?

**Comment by rufreakde** [comment]
Any ideas we can spill credentials :/

**Comment by rufreakde** [comment]
Okay found the solution now.
It is a very long one...

In the end what we do now is using the helm chart but replacing the configs of `loki-read`and `loki-write` with kustomize at the end...

Here are the necessary hints for others:
```yaml
--- # argoproject
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: default
  source:
    #Custom plugin to enable helm
    plugin:
      name: kustomize-build-with-helm
    repoURL: https://OUR_REPO.git
    targetRevision: main
    path: PATH/loki
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSync=true
--- # kustomization.yaml
helmCharts:
- name: loki
  version: 3.6.0
  repo: https://grafana.github.io/helm-charts
  releaseName: monitoring
  namespace: monitoring
  valuesFile: values.yaml
  valuesMerge: merge
  includeCRDs: true

patchesStrategicMerge:
- overlay/loki-read.yaml
- overlay/loki-write.yaml
---  # example patch
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-read
spec:
  template:
    spec:
      volumes:
        - name: config
          configMap:
            $patch: delete
          secret:
            secretName: loki-custom # we rendered the template `helm template . -f ./tmpValues > result.yaml to understand how our config would look like
```
