### ISSUE TITLE
recovered from panic opening boltdb file: invalid freelist page: 0, page type is unknown<00>\nerror creating index client

### ISSUE THREAD

**Issue by darox** [grafana/loki#7694]
**Describe the bug**
Loki distributed stops working after running for some time  with the following error:
```level=error ts=2022-11-15T08:29:03.538800447Z caller=log.go:103 msg="error running loki" err="recovered from panic opening boltdb file: invalid freelist page: 0, page type is unknown<00>\nerror creating index client\ngithub.com/grafana/loki/pkg/storage.(*store).storeForPeriod\n\t/src/loki/pkg/storage/store.go:245\ngithub.com/grafana/loki/pkg/storage.(*store).init\n\t/src/loki/pkg/storage/store.go:162\ngithub.com/grafana/loki/pkg/storage.NewStore\n\t/src/loki/pkg/storage/store.go:145\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/src/loki/pkg/loki/modules.go:522\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:120\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:92\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:341\nmain.main\n\t/src/loki/cmd/loki/main.go:105\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:122\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:92\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:341\nmain.main\n\t/src/loki/cmd/loki/main.go:105\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"```

**Expected behavior**
Loki continues to run successfully

**Environment:**
 - Infrastructure: kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Helm config:
```
repositories:
  - name: "grafana"
    url: "https://grafana.github.io/helm-charts"

environments:
  default:
    values:
      - s3:
          key: ref+sops://secrets.yaml?format=yaml#/secrets/s3/key
          secret: ref+sops://secrets.yaml?format=yaml#/secrets/s3/secret
releases:
  - name: "loki"
    namespace: "monitoring"
    chart: "grafana/loki"
    wait: true
    version: 3.3.4
    set:
      - name: ingress.enabled
        value: true
      - name: ingress.annotations.cert-manager\.io/cluster-issuer
        value: letsencrypt-prod
      - name: ingress.annotations.kubernetes\.io/ingress\.class
        value: nginx
      - name: ingress.annotations.nginx\.ingress\.kubernetes\.io/auth-type
        value: basic
      - name: ingress.annotations.nginx\.ingress\.kubernetes\.io/auth-secret
        value: basic-auth-loki
      - name: ingress.annotations.nginx\.ingress\.kubernetes\.io/auth-realm
        value: Authentication Required
      - name: ingress.hosts[0]
        value: loki.local
      - name: ingress.tls[0].hosts[0]
        value: loki.local
      - name: ingress.tls[0].secretName
        value: le-loki-local
      - name: loki.auth_enabled
        value: false
      - name: loki.commonConfig.replication_factor
        value: 1
      - name: loki.storage.bucketNames.chunks
        value: loki-chunks
      - name: loki.storage.bucketNames.ruler
        value: loki-ruler
      - name: loki.storage.bucketNames.admin
        value: loki-admin
      - name: loki.storage.s3.endpoint
        value: http://minio-s3.minio.svc.cluster.local:9000
      - name: loki.storage.s3.insecure
        value: true
      - name: loki.storage.s3.s3ForcePathStyle
        value: true
      - name: loki.storage.s3.secretAccessKey
        value: {{ .Values.s3.secret | fetchSecretValue }}
      - name: loki.storage.s3.accessKeyId
        value: {{ .Values.s3.key | fetchSecretValue }}
      - name: monitoring.selfMonitoring.enabled
        value: true
      - name: monitoring.selfMonitoring.grafanaAgent.installOperator
        value: false
      - name: read.persistence.storageClass
        value: nfs-client-ssd
      - name: read.replicas
        value: 1
      - name: write.persistence.storageClass
        value: nfs-client-ssd
      - name: write.replicas 
        value: 1

```

**Comment by Kevin-Bannier** [comment]
I have the same problem with Loki in singleBinary mode (Helm chart 3.3.4)

values.yaml:

```yaml
loki:
  singleBinary:
    resources:
      requests:
        memory: "80Mi"
        cpu: "50m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    persistence:
      enabled: true
      storageClass: "nfs-client"

  loki:
    structuredConfig:
      table_manager:
        retention_deletes_enabled: true
        retention_period: 840h
    auth_enabled: false
    server:
      http_listen_port: 3100
    commonConfig:
      replication_factor: 1
    storage:
      type: "filesystem"
    rulerConfig:
      storage:
        type: local

  test:
    enabled: false

  monitoring:
    serviceMonitor:
      enabled: false
      metricsInstance:
        enabled: true
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
      lokiCanary:
        enabled: false
```
