### ISSUE TITLE
New logs being generated for caller "table.go" post-2.7.0 upgrade

### ISSUE THREAD

**Issue by cassidy3** [grafana/loki#7699]
**Describe the bug**
Immediately after updating from 2.6 tree to 2.7.0, a large number of log lines with caller "table.go" are being generated.

**To Reproduce**
1. Start Loki on version 2.7.0, running the config listed below.

**Expected behavior**
Log lines may be intentional, but do not appear to be in the upgrade guide or change log for 2.7.0. AFAIK, they should not be generated unless something has changed in the underlying module.

**Environment:**
 - Infrastructure: Docker, 4-node cluster fronted by HAProxy, Vector for ingest and MinIO for backend storage.
 - Deployment tool: Docker Swarm deploy via compose.

**Screenshots, Promtail config, or terminal output**
Example log lines:
```logfmt
level=info ts=2022-11-15T05:40:44.757056614Z caller=table.go:131 table-name=index_19305 msg="listed files" count=1
level=info ts=2022-11-15T05:40:44.757005029Z caller=table.go:131 table-name=index_19306 msg="listed files" count=1
level=info ts=2022-11-15T05:40:44.756937873Z caller=table.go:131 table-name=index_19307 msg="listed files" count=1
level=info ts=2022-11-15T05:40:44.756880485Z caller=table.go:131 table-name=index_19308 msg="listed files" count=1
level=info ts=2022-11-15T05:40:44.756811359Z caller=table.go:131 table-name=index_19309 msg="listed files" count=1
level=info ts=2022-11-15T05:40:44.645391257Z caller=table.go:131 table-name=index_19310 msg="listed files" count=4
level=info ts=2022-11-15T05:40:44.544087026Z caller=table.go:131 table-name=index_19311 msg="listed files" count=5
level=info ts=2022-11-15T05:40:32.50182823Z caller=table.go:334 msg="finished handing over table index_19311"
level=info ts=2022-11-15T05:40:32.501820148Z caller=table.go:318 msg="handing over indexes to shipper index_19311"
level=info ts=2022-11-15T05:40:32.501792113Z caller=table.go:334 msg="finished handing over table index_19310"
level=info ts=2022-11-15T05:40:32.501784293Z caller=table.go:318 msg="handing over indexes to shipper index_19310"
level=info ts=2022-11-15T05:40:32.501750618Z caller=table.go:334 msg="finished handing over table index_19309"
level=info ts=2022-11-15T05:40:32.501740074Z caller=table.go:318 msg="handing over indexes to shipper index_19309"
```

Logs started popping up immediately after update on the 13th, and increased yesterday:
![image](https://user-images.githubusercontent.com/15707989/201962833-344a2461-092e-4598-b4bf-2629723e6566.png)

Loki configuration:
```yaml
auth_enabled: false

server:
  http_listen_port: 3100

distributor:
  ring:
    kvstore:
      store: memberlist
    instance_interface_names: [eth1]

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  max_join_backoff: 1m
  max_join_retries: 10
  min_join_backoff: 1s
  join_members:
    - loki-1:7946
    - loki-2:7946
    - loki-3:7946
    - loki-4:7946

frontend:
  address: ${HOSTNAME}

frontend_worker:
  parallelism: 64

querier:
  max_concurrent: 2048

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

query_range:
  align_queries_with_step: true
  cache_results: true
  parallelise_shardable_queries: true
  results_cache:
    cache:       
      enable_fifocache: true   
      default_validity: 1h    
      fifocache:
        max_size_bytes: 10G    
        max_size_items: 1000   
        validity: 1h   

ingester:
  wal:
    enabled: false
  lifecycler:
    address: ${HOSTNAME}
    interface_names: [eth1]
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
    final_sleep: 0s
  chunk_idle_period: 2h
  max_chunk_age: 24h
  chunk_block_size: 262144
  chunk_target_size: 1572864
  chunk_retain_period: 30s
  max_transfer_retries: 0
  chunk_encoding: snappy

schema_config:
  configs:
    - from: 2022-04-29
      store: boltdb-shipper
      object_store: s3
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 720h
    shared_store: aws
  aws:
    endpoint: ingress:9000
    bucketnames: loki
    access_key_id: loki
    secret_access_key: ${S3_SECRET}
    insecure: false
    http_config:
      idle_conn_timeout: 90s
      response_header_timeout: 0s
      insecure_skip_verify: true
    s3forcepathstyle: true

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: aws
  retention_enabled: true

limits_config:
  split_queries_by_interval: 48h
  reject_old_samples: false
  ingestion_rate_strategy: local
  ingestion_rate_mb: 50
  ingestion_burst_size_mb: 500
  max_entries_limit_per_query: 100000
  max_query_series: 10000
  retention_period: 365d 
  max_query_length: 0

chunk_store_config:
  max_look_back_period: 0s
```
