### ISSUE TITLE
Add storage provider for OCI Object Storage

### ISSUE THREAD

**Issue by ericrrath** [grafana/loki#7713]
**Is your feature request related to a problem? Please describe.**
I want to use Loki, but have it store data in Oracle's OCI Object Storage.  OCI does have an S3-compatibility mode, but this doesn't support [OCI IAM instance principal authentication](https://docs.oracle.com/en-us/iaas/Content/Identity/Tasks/callingservicesfrominstances.htm) (i.e. location-based auth).

**Describe the solution you'd like**
I'd like to add the OCI SDK for go as a dependency, then modify Loki to add "native" support for OCI Object Storage (i.e. not through OCI's S3-compatibility mode).

**Describe alternatives you've considered**
Configuring Loki to use its S3 provider pointed to OCI Object Storage's S3-compatibility interface works, but requires me to provide keys to Loki.  

**Additional context**

**Comment by Nitishmane** [comment]
Is there a working PR for this?

**Comment by andytael** [comment]
@ericrrath Can you provide the storage config you are using for OCI Object Storage?

**Comment by starboi02** [comment]
@ericrrath can you share the storage config you used for it?

**Comment by dzirg44** [comment]
@andytael and @starboi02 
```yaml
  aws:
    access_key_id: d844cd76659fe0d204f1213123asdasdsd
    bucketnames: logging-bucket
    endpoint: https://dasdjkjwi.compat.objectstorage.my-region-1.oraclecloud.com
    http_config:
      insecure_skip_verify: true
    insecure: true
    region: my-region-1
    s3forcepathstyle: true
    secret_access_key: 8sacRn7Akasddasdio21233ksasaM8=
```
keep in mind that you have to create customer secret key for an user, and assign proper permissions for a group.
Good luck!

**Comment by yaniveliash** [comment]
I think the above example is not valid anymore as it didn't worked in my case
any update on native integration?

Thanks

**Comment by krishnarudraraju** [comment]
This worked for me with these steps:

```
schemaConfig:
    configs:
    - from: "2020-09-07"
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h
```
```
storageConfig:
    boltdb_shipper:
      shared_store: s3
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 24h
    aws:
      access_key_id: xxxxxx
      bucketnames: lokix402
      endpoint: https://axxxxrg.compat.objectstorage.us-sanjose-1.oraclecloud.com
      s3forcepathstyle: true
      insecure: true
      region: us-sanjose-1
      secret_access_key: "1xxxxxxI="
    filesystem:
      directory: /var/loki/chunks
```

I can see object in bucket
<img width="529" alt="image" src="https://github.com/grafana/loki/assets/160546936/e8e3b2f7-18eb-4f3a-80ac-c799e235ec37">

**Comment by PrathapDasari** [comment]
@krishnarudraraju  It seems like you followed the same steps as I did, but for some reason, it didn't work. Do you have any insights on why that might be?


`  schema_config:
    configs:
    - from: "2024-05-13"
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h
  storage_config:
    boltdb_shipper:
      shared_store: s3
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 24h
    aws:
      access_key_id: **********
      bucketnames: loki-log
      endpoint: https://f***********
      s3forcepathstyle: true
      insecure: true
      region: eu-frankfurt-1
      secret_access_key: "*********"
    filesystem:
      directory: /var/loki`

**Comment by krishnarudraraju** [comment]
here is my values file

```
loki:
  auth_enabled: false
  storage:
    bucketNames:
      chunks: log-aggregation-loki
      ruler: log-aggregation-loki
      admin: log-aggregation-loki
    type: s3
    s3:
      s3: null
      endpoint: https://<namespace>.compat.objectstorage.uk-london-1.oraclecloud.com
      region: uk-london-1
      secretAccessKey: "<lokibucket-user-secret-key>"
      accessKeyId: <lokibucket-user-access-key>
      signatureVersion: null
      s3ForcePathStyle: true
      insecure: true
      http_config: {}
lokiCanary:
  nodeSelector:
    node-type: loki
backend:
# -- Number of replicas for the backend
  replicas: 3
  nodeSelector:
    node-type: loki
write:
# -- Number of replicas for the write
  replicas: 3
  nodeSelector:
    node-type: loki
read:
# -- Number of replicas for the read
  replicas: 3
  nodeSelector:
    node-type: loki
gateway:
  nodeSelector:
    node-type: loki
  service:
    type: LoadBalancer

```

**Comment by PrathapDasari** [comment]
Thank you for you prompt response :) 
This is my values file which i am using with default configuration as of now.
```
loki:
  enabled: true
  isDefault: true
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  datasource:
    jsonData: "{}"
    uid: ""
  auth_enabled: false
  storage:
     bucketNames:
        chunks: loki-uat
        ruler: loki-uat
        admin: loki-uat
     type: s3
     s3:
       s3: null
       endpoint: https://namesapce.compat.objectstorage.eu-frankfurt-1.oraclecloud.com
       region: eu-frankfurt-1
       secretAccessKey: "x*************"
       accessKeyId: *****************
       signatureVersion: null
       s3ForcePathStyle: true
       insecure: true
       http_config: {}

``` 

But still it is failing with below error 

Error: INSTALLATION FAILED: execution error at (loki/templates/validate.yaml:40:4): You must provide a schema_config for Loki, one is not provided as this will be individual for every Loki cluster. See https://grafana.com/docs/loki/latest/operations/storage/schema/ for schema information. For quick testing (with no persistence) add `--set loki.useTestSchema=true`

**Comment by PrathapDasari** [comment]
@krishnarudraraju  thank you for you assistance 

I now managed to fix the issue .

```
loki:
  enabled: true
  isDefault: true
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  datasource:
    jsonData: "{}"
    uid: ""
  auth_enabled: false
  schemaConfig:
    configs:
    - from: "2024-05-13"
      store: boltdb-shipper
      object_store: s3
      **schema: v13**
      index:
        prefix: loki_index_
        period: 24h
  **limits_config:**
      **allow_structured_metadata: false**
  storage:
     bucketNames:
        chunks: loki
        ruler: loki
        admin: loki
     type: s3
     s3:
       s3: null
       endpoint: https://namespace.compat.objectstorage.eu-*************-1.oraclecloud.com
       region: eu-***********-1
       secretAccessKey: "*********************"
       accessKeyId: ***************************
       signatureVersion: null
       s3ForcePathStyle: true
       insecure: true
```
