### ISSUE TITLE
promtail: config reload fails

### ISSUE THREAD

**Issue by pschulten** [grafana/loki#7734]
**Describe the bug**
With [7247](https://github.com/grafana/loki/pull/7247) added in 2.7.0 (https://github.com/grafana/loki/blob/d3111bcaa7749ca53902c45f4856e28e2980c79d/CHANGELOG.md?plain=1#LL99C3-L99C52) config reload should be possible but fails.

**To Reproduce**
1. Started Loki 2.7.0
2. Started Promtail 2.7.0 with config:
```
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  reload: true

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs-reload-promtail-test
      __path__: /var/log/cloudprintupdate.log
```

**Expected behavior**
Above config is parsed correctly

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Terraform

**Screenshots, Promtail config, or terminal output**
```
Unable to parse config: /etc/promtail/promtail.yaml: yaml: unmarshal errors:
  line 4: field reload not found in type server.Config
```

Maybe related: https://github.com/grafana/loki/issues/6388

**Comment by liguozhong** [comment]
hi, reload filed is `enable_runtime_reload` 

```
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  enable_runtime_reload: true
```

**Comment by liguozhong** [comment]
https://grafana.com/docs/loki/latest/clients/promtail/configuration/

enable_runtime_reload

**Comment by pschulten** [comment]
thanks, that works. sorry :(

**Comment by liuxuzxx** [comment]
Describe the bug
1. Start promtail version=2.9.0, branch=HEAD, revision=2feb64f69   in vm
2. Started promtail version=2.9.0, branch=HEAD, revision=2feb64f69 in vm config.yaml is 
```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  enable_runtime_reload: true
clients:
  - url: http://loki.cpaas.wxchina.com:30669/loki/api/v1/push
positions:
  filename: ./positions.yaml
target_config:
  sync_period: 10s
scrape_configs:   
  - job_name: alert-log
    static_configs:
      - targets:
         - localhost
        labels:
          node: liuxu-node
          job: alert-log
          app: alert-app
          type: alert
          __path__: /media/liuxu/data/component/promtail/alert.log
```
3. and modify config.yaml and save
```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  enable_runtime_reload: true
clients:
  - url: http://loki.cpaas.wxchina.com:30669/loki/api/v1/push
positions:
  filename: ./positions.yaml
target_config:
  sync_period: 10s
scrape_configs:   
  - job_name: alert-log
    static_configs:
      - targets:
         - localhost
        labels:
          node: liuxu-node
          job: alert-log
          app: alert-app-liuxu  #modify the app label from alert-app to alert-app-liuxu
          type: alert
          __path__: /media/liuxu/data/component/promtail/alert.log
```
5. execute curl reload
```bash
curl http://localhost:9080/reload
```

6. the error information:  (I am in vm use vim modify the config.yaml and save)
```bash
panic: duplicate metrics collector registration attempted

goroutine 209 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0x37fd4eb?, {0xc000560e40?, 0x1, 0xb?})
	/drone/src/vendor/github.com/prometheus/client_golang/prometheus/registry.go:405 +0x85
github.com/grafana/loki/clients/pkg/promtail/wal.NewWatcherMetrics({0x40e50d0, 0xc0000c6a00})
	/drone/src/clients/pkg/promtail/wal/watcher_metrics.go:73 +0xaac
github.com/grafana/loki/clients/pkg/promtail/client.NewManager(0x0?, {0x40c8600, 0xc000136e10}, {0x40c3880000000000, 0x2710, 0x0, 0x1, 0x0, 0x0, 0x0}, ...)
	/drone/src/clients/pkg/promtail/client/manager.go:61 +0x8f
github.com/grafana/loki/clients/pkg/promtail.(*Promtail).reloadConfig(0xc000c1f2c0, 0xc0005f6000)
	/drone/src/clients/pkg/promtail/promtail.go:170 +0x8cb
github.com/grafana/loki/clients/pkg/promtail.(*Promtail).reload(0xc000c1f2c0)
	/drone/src/clients/pkg/promtail/promtail.go:286 +0xaf
github.com/grafana/loki/clients/pkg/promtail.(*Promtail).watchConfig(0xc000c1f2c0)
	/drone/src/clients/pkg/promtail/promtail.go:271 +0x3e9
created by github.com/grafana/loki/clients/pkg/promtail.(*Promtail).Run
	/drone/src/clients/pkg/promtail/promtail.go:214 +0xcc

```
