### ISSUE TITLE
[HEROKU] - field relabel_configs not found in type main.Config

### ISSUE THREAD

**Issue by jakobsuckow** [grafana/loki#7783]
**Describe the bug**
I have followed the tutorial over at https://grafana.com/blog/2022/09/19/how-to-easily-configure-grafana-loki-and-promtail-to-receive-logs-from-heroku/ which describes setting up promtail on a heroku instance. However, when trying to deploy, it gives the following output:

Unable to parse config: /etc/promtail/config.yml: yaml: unmarshal errors:
2022-11-26T18:16:47.481043+00:00 app[web.1]: line 19: field relabel_configs not found in type main.Config

**To Reproduce**
Each step of
https://grafana.com/blog/2022/09/19/how-to-easily-configure-grafana-loki-and-promtail-to-receive-logs-from-heroku/

**Expected behavior**
Application should load

**Environment:**
 - HEROKU
 - 

<img width="1229" alt="Bildschirmfoto 2022-11-26 um 19 15 02" src="https://user-images.githubusercontent.com/29168155/204103393-4de4180e-216a-46a7-b9e9-5b95ed2e7e39.png">

**Comment by robmarco** [comment]
Hi @jakobsuckow!

I'm not sure if this issue is still happening to you, but I've changed the `config.yml` mentioned in the post and it works (at least to me):

```yml
# file: config.yml

server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"

positions:
  filename: /tmp/positions.yaml

# This bit indicates what Loki instance to write the logs to. We’ll inject the
# details and credentials through environment variables
clients:
  - url: https://${LOKI_TENANT_ID}:${LOKI_TOKEN}@${LOKI_HOST}/loki/api/v1/push

scrape_configs:
  # Job name, that will be injected in each log line
  - job_name: ${JOB_NAME}
    # Apply relabel to keep Heroku internal labels
    relabel_configs:
    - source_labels: ["__heroku_drain_host"]
      target_label: "host"
    - source_labels: ["__heroku_drain_app"]
      target_label: "app"
    - source_labels: ["__heroku_drain_proc"]
      target_label: "proc"
      # Main heroku target configuration
    heroku_drain:
      server:
        http_listen_address: 0.0.0.0
        # $PORT is a special environment variable that Heroku fills with
        # port that’s accessible from outside the container. We indicate promtail
        # to listen for Heroku logs in it.
        http_listen_port: ${PORT}
        log_level: info
      # Tag each log entry with our job name
      labels:
        job: ${JOB_NAME}
```

**Screenshot – Working after deploy to Heroku**

![Captura de pantalla 2023-01-12 a las 11 57 18](https://user-images.githubusercontent.com/450193/212060694-6c5ec74c-5210-44c8-84cd-7ac192f54961.png)

Hope this works for you :)
