### ISSUE TITLE
Ingester uses hard-coded deprecated FIFO cache

### ISSUE THREAD

**Issue by dekelpilli** [grafana/loki#7798]
**Describe the bug**
Ingester uses hard-coded FIFO cache when certain configurations are enabled, causing it to always log the following error message on startup:
```
{"caller":"cache.go:114","level":"warn","msg":"fifocache config is deprecated. use embedded-cache instead","ts":"2022-11-28T02:30:12.272258829Z"}
```

This is happening due to the following line of code:
https://github.com/grafana/loki/blob/343e39f67baf5bf9b22f0b01936aae7864324d16/pkg/loki/modules.go#L520

**To Reproduce**
1. Started Loki (2.7.0) with the following config:

```yaml
---
auth_enabled: true
target: ${TARGET}

analytics:
  reporting_enabled: false

common:
  ring:
    kvstore:
      store: memberlist
    instance_interface_names: []
    instance_addr: ${HOST_IP}
  compactor_address: ...

server:
  log_level: warn
  log_format: json
  http_listen_address: ${IP_http}
  http_listen_port: ${PORT_http}
  grpc_listen_address: ${IP_grpc}
  grpc_listen_port: ${PORT_grpc}
  graceful_shutdown_timeout: 5s
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_recv_msg_size: 1.048576e+08
  grpc_server_max_send_msg_size: 1.048576e+08
  http_server_idle_timeout: 120s
  http_server_write_timeout: 1m

schema_config:
  configs:
    - from: '2020-08-01'
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

ingester:
  autoforget_unhealthy: true
  max_chunk_age: 2h            # All chunks will be flushed when they hit this age, default is 2h
  chunk_idle_period: 1h        # Any chunk not receiving new logs in this time will be flushed
  chunk_block_size: 524288
  chunk_target_size: 3145728   # Loki will attempt to build chunks up to 3MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s     # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  chunk_encoding: lz4
  max_transfer_retries: 0
  flush_check_period: 5s
  wal:
    dir: /loki/wal
    flush_on_shutdown: true
    replay_memory_ceiling: 1GB
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 2
    final_sleep: 0s

chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: false
    memcached:
      expiration: 30m
    memcached_client:
      host: ...
      service: ...
  write_dedupe_cache_config:
    embedded_cache:
      enabled: false
    memcached:
      expiration: 30m
    memcached_client:
      host: ...
      service: ...

compactor:
  working_directory: /loki/compactor
  shared_store: s3
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  compactor_ring:
    instance_addr: ${HOST_IP}
    kvstore:
      store: inmemory

limits_config:
  retention_period: 744h
  ingestion_rate_mb: 10000
  ingestion_burst_size_mb: 100000
  per_stream_rate_limit: 1GB
  per_stream_rate_limit_burst: 10GB
  enforce_metric_name: false
  reject_old_samples: false
  reject_old_samples_max_age: 336h
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 5m

memberlist:
  randomize_node_name: true
  bind_addr: [${IP_gossip}]
  bind_port: ${PORT_gossip}
  min_join_backoff: 1s
  max_join_backoff: 1m
  max_join_retries: 10
  dead_node_reclaim_time: 30s
  gossip_to_dead_nodes_time: 15s
  left_ingesters_timeout: 30s
  join_members:
    - ...

storage_config:
  index_cache_validity: 5m
  index_queries_cache_config:
    embedded_cache:
      enabled: false
    memcached:
      expiration: 30m
    memcached_client:
      host: ...
      service: ...
  aws: &s3
    s3: ...
    insecure: true
    s3forcepathstyle: true

  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: s3
    index_gateway_client:
      server_address: ...

querier:
  query_ingesters_within: 2h1m
  engine:
    timeout: 30m
    max_look_back_period: 2160h

query_range:
  align_queries_with_step: true
  parallelise_shardable_queries: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: false
      memcached:
        expiration: 30m
      memcached_client:
        host: ...
        service: ...

frontend:
  #log_queries_longer_than: 1s
  compress_responses: true
  instance_interface_names: []
  address: ${IP_grpc}

frontend_worker:
  frontend_address: ${FRONTEND_ADDR}
  parallelism: 16
  grpc_client_config:
    max_send_msg_size: 104857600
    grpc_compression: snappy

ruler:
  enable_api: true
  external_url: ...
  alertmanager_url: ...
  enable_alertmanager_discovery: true
  enable_alertmanager_v2: true
  rule_path: /loki/loki-ruler
  storage:
    type: s3
    s3: *s3

runtime_config:
  file: /local/runtime.yml
```

**Expected behavior**
One of the following:
- Use embedded cache config instead of the deprecated fifo cache to avoid this log message
- Add configuration to allow other cache types for this purpose

**Environment:**
 - Infrastructure: Docker
 - Deployment tool: Terraform

**Screenshots, Promtail config, or terminal output**
```
{"caller":"cache.go:114","level":"warn","msg":"fifocache config is deprecated. use embedded-cache instead","ts":"2022-11-28T02:30:12.272258829Z"}
```
