### ISSUE TITLE
[Helm] loki pod does expect `rules-temp` file

### ISSUE THREAD

**Issue by H777K** [grafana/loki#7806]
**Describe the bug**

If i deploy the loki helm chart with the `rules_directory` set to `/var/loki/rules` the pod will output in the log that the file `/var/loki/rules-temp` can not be found:

```sh
level=info caller=mapper.go:46 msg="cleaning up mapped rules directory" path=/var/loki/rules-temp
level=error caller=mapper.go:50 msg="unable to read rules directory" path=/var/loki/rules-temp err="open /var/loki/rules-temp: no such file or directory" 
```

**To Reproduce**

1. create values file for override:

```yaml
# values.yaml
loki:
  commonConfig:
    path_prefix: /var/loki
  limits_config:
    retention_period: 744h
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1
  rulerConfig:
    storage:
      type: local
  auth_enabled: false
monitoring:
  serviceMonitor:
    enabled: true

grafana-agent-operator:
  podSecurityContext:
    runAsUser: 10001
```

2. add helm repository:

```sh
helm repo add grafana https://grafana.github.io/helm-charts
```

3. install helm release:

```sh
helm install loki grafana/loki -f values.yaml
```

4. check the logs of the `loki-0` pod:

```sh
kubectl logs loki-0
```

**Expected behavior**

I would expect that the log file should show the `/var/loki/rules` file instead `/var/loki/rules-temp` because the first one is set as `rules_repository`.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
