### ISSUE TITLE
Grafana Agent crashes with exception

### ISSUE THREAD

**Issue by pfzim** [grafana/loki#7825]
Hello!

Grafana Agent crashes with exception at startup

```
>"C:\Program Files\Grafana Agent\agent-windows-amd64.exe" -config.file="C:\Program Files\Grafana Agent\agent-config.yaml"

Exception 0xc0000005 0x1 0x0 0x7ffaa94ee254
PC=0x7ffaa94ee254
signal arrived during external code execution

runtime.cgocall(0x552e60, 0xc000420ac0)
        /usr/local/go/src/runtime/cgocall.go:158 +0x4a fp=0xc00148b780 sp=0xc00148b748 pc=0x4e4e6a
syscall.SyscallN(0x17f?, {0xc00148b818?, 0x4ee94d?, 0x22df17abd98?})
        /usr/local/go/src/runtime/syscall_windows.go:557 +0x109 fp=0xc00148b7f8 sp=0xc00148b780 pc=0x54de09
syscall.Syscall9(0x22df17abd98?, 0x0?, 0x22de9970a28?, 0x10?, 0xc000420800?, 0xc000ced7f0?, 0x0?, 0xc00140c0a0?, 0xc00148b8f8?, 0x0, ...)
        /usr/local/go/src/runtime/syscall_windows.go:507 +0x78 fp=0xc00148b870 sp=0xc00148b7f8 pc=0x54db18
github.com/grafana/loki/clients/pkg/promtail/targets/windows/win_eventlog._EvtFormatMessage(0xc0014041c0?, 0xc0014041c0?, 0x0, 0x0, 0x67146a0?, 0x3, 0x0, 0x2a47a3d?, 0xc001402060?)
        /go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221031191413-16761723f4f2/clients/pkg/promtail/targets/windows/win_eventlog/zsyscall_windows.go:153 +0xe5 fp=0xc00148b908 sp=0xc00148b870 pc=0x2a48425
github.com/grafana/loki/clients/pkg/promtail/targets/windows/win_eventlog.formatEventString(0x3, 0xc001402060?, 0x800?)
        /go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221031191413-16761723f4f2/clients/pkg/promtail/targets/windows/win_eventlog/win_eventlog.go:521 +0x4a fp=0xc00148b978 sp=0xc00148b908 pc=0x2a4784a
github.com/grafana/loki/clients/pkg/promtail/targets/windows/win_eventlog.(*EventFetcher).renderEvent(_, _, _)
        /go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221031191413-16761723f4f2/clients/pkg/promtail/targets/windows/win_eventlog/win_eventlog.go:504 +0x26c fp=0xc00148ba08 sp=0xc00148b978 pc=0x2a474ac
github.com/grafana/loki/clients/pkg/promtail/targets/windows/win_eventlog.(*EventFetcher).FetchEvents(0xc000a11f68, 0xc0012ebeb0?, 0x0?)
        /go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221031191413-16761723f4f2/clients/pkg/promtail/targets/windows/win_eventlog/win_eventlog.go:444 +0x16a fp=0xc00148be38 sp=0xc00148ba08 pc=0x2a46f8a
github.com/grafana/loki/clients/pkg/promtail/targets/windows.(*Target).loop(0xc0006cac60)
        /go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221031191413-16761723f4f2/clients/pkg/promtail/targets/windows/target.go:114 +0x305 fp=0xc00148bfc8 sp=0xc00148be38 pc=0x2a4a225
github.com/grafana/loki/clients/pkg/promtail/targets/windows.New.func2()
        /go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221031191413-16761723f4f2/clients/pkg/promtail/targets/windows/target.go:94 +0x26 fp=0xc00148bfe0 sp=0xc00148bfc8 pc=0x2a49e86
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00148bfe8 sp=0xc00148bfe0 pc=0x551561
created by github.com/grafana/loki/clients/pkg/promtail/targets/windows.New
        /go/pkg/mod/github.com/grafana/loki@v1.6.2-0.20221031191413-16761723f4f2/clients/pkg/promtail/targets/windows/target.go:94 +0x4b8
```

**agent-config.yaml**
```
server:
  log_level: warn

logs:
  positions_directory: "C:\\ProgramData\\grafana-agent"

  configs:
    - name: windows
      clients:
        - url: http://s-loki-01.contoso.com:3100/loki/api/v1/push
  
      scrape_configs:
  
      - job_name: windows_application
        pipeline_stages:
          - json:
              expressions:
                event_id: "event_id"
                source: "source"
          - labels:
              event_id:
              source:
        windows_events:
          use_incoming_timestamp: false
          bookmark_path: "C:\\ProgramData\\grafana-agent\\bookmark_application.xml"
          eventlog_name: "Application"
          xpath_query: '*'
          labels:
            job: windows
        relabel_configs:
          - source_labels: ['computer']
            target_label: 'host'
  
      - job_name: windows_system
        pipeline_stages:
          - json:
              expressions:
                event_id: "event_id"
                source: "source"
          - labels:
              event_id:
              source:
        windows_events:
          use_incoming_timestamp: false
          bookmark_path: "C:\\ProgramData\\grafana-agent\\bookmark_system.xml"
          eventlog_name: "System"
          xpath_query: '*'
          labels:
            job: windows
        relabel_configs:
          - source_labels: ['computer']
            target_label: 'host'
  
      - job_name: windows_forwarded
        pipeline_stages:
          - json:
              expressions:
                event_id: "event_id"
                source: "source"
          - labels:
              event_id:
              source:
        windows_events:
          use_incoming_timestamp: false
          bookmark_path: "C:\\ProgramData\\grafana-agent\\bookmark_forwarded.xml"
          eventlog_name: "ForwardedEvents"
          xpath_query: '*'
          labels:
            job: windows
        relabel_configs:
          - source_labels: ['computer']
            target_label: 'host'
```
