### ISSUE TITLE
Promtail journal scraper fails silently for permissions issues

### ISSUE THREAD

**Issue by timw6n** [grafana/loki#7836]
When configuring promtail to scrape journal logs, it appears to fail silently if filesystem permissions prevent reading the configured journal directory. E.g. because the promtail user had not been added to the systemd-journal group.

It would be helpful in troubleshooting if an error message were logged in this case.

```
      scrape_configs:
        - job_name: journal
          journal:
            json: false
            max_age: 12h
            path: /var/log/journal
            labels:
              job: systemd-journal
          relabel_configs:
            # etc
```

```
$ promtail --version
promtail, version HEAD-1b627d8 (branch: HEAD, revision: 1b627d880)
  build user:       root@079d888186e6
  build date:       2022-11-10T23:52:44Z
  go version:       go1.19.2
  platform:         linux/amd64
```

(This is the using latest package in the official repository, on Ubuntu 20.04.)
