### ISSUE TITLE
Unable to make loki works with a loadbalancer ip?

### ISSUE THREAD

**Issue by moonmanious** [grafana/loki#7844]
We installed grafana, loki and promtail in kubernetes and we need to expose both grafana and loki with two different metallb loadbalancers (one for grafana and one for loki).

We have been successful to configure ingress for grafana but we also need a different loadbalancer ip for loki since an external promtail needs to send data to loki.

We installed loki as follows:
`helm install loki-stack grafana/loki-stack --values ./loki-stack-values.yaml -n loki --create-namespace`

loki-stack-values.yaml:
```
test_pod:
  image: bats/bats:v1.1.0
  pullPolicy: IfNotPresent

loki:
  enabled: true
  isDefault: true

promtail:
  enabled: true
  config:
    logLevel: info
    serverPort: 3101
    clients:
      - url: http://{{ .Release.Name }}:3100/loki/api/v1/push

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
      maxLines: 1000
  image:
    tag: 8.3.5
```

We have successfully configured grafana to use an ingress using nginx. We exposed the port and configured resource ingress yaml. We want to access loki from our host OS using a loadbalancer with a different ip that we used for grafana. We can see the service as follows:

```
kubectl get svc -A -n loki
loki   loki-stack   ClusterIP   192.168.5.11   <none>   3100/TCP               
loki   loki-stack-grafana   ClusterIP   192.168.239.141   <none>   80/TCP   
```

```
kubectl expose deployment loki-stack --type=LoadBalancer --name=loki-service

deployments.apps "loki-stack" not found
```

```
kubectl get deployments -A -n loki  we get:
loki               loki-stack-grafana 
```
i.e. there is no loki-stack
