### ISSUE TITLE
Promtail pods in CrashLoopBackOff status if i use default docker tag --> v0.1.0

### ISSUE THREAD

**Issue by C123R** [grafana/loki#786]
**Describe the bug**
I am trying to install Loki-stack using helm chart with default values, just disabling RBAC and enabling PVC.

```sh
$ helm upgrade --install loki loki/loki-stack --set loki.rbac.create=false --set loki.persistence.enabled=true --namespace monitoring
```
I have noticed Loki is getting installed correctly but having issues with Promtail Daemon set.

```sh
$ kubectl get pods -n monitoring -l release=loki
NAME                  READY   STATUS             RESTARTS   AGE
loki-0                0/1     Running            0          92s
loki-promtail-6sn9w   0/1     CrashLoopBackOff   3          92s
loki-promtail-frcwp   0/1     CrashLoopBackOff   3          92s
loki-promtail-m2p6p   0/1     CrashLoopBackOff   3          92s
loki-promtail-sl7jm   0/1     CrashLoopBackOff   3          92s
```

```sh
$ kubectl logs loki-promtail-6sn9w -n monitoring
level=error ts=2019-07-19T14:15:12.413377984Z caller=main.go:45 msg="error creating promtail" error="yaml: unmarshal errors:\n ..........
```
I saw recent [commit](https://github.com/grafana/loki/pull/697) on promtail, and just tried using the latest docker image grafana/promtail:latest which helped:

```sh
$ kubectl -n monitoring set image ds/loki-promtail promtail=grafana/promtail:latest

$ kubectl get pods -n monitoring -l release=loki
NAME                  READY   STATUS    RESTARTS   AGE
loki-0                1/1     Running   0          12m
loki-promtail-dg6j6   0/1     Running   0          11s
loki-promtail-jbsc8   0/1     Running   0          11s
loki-promtail-ks65t   0/1     Running   0          11s
loki-promtail-x95ph   0/1     Running   0          11s
```

**To Reproduce**
1. `helm upgrade --install loki loki/loki-stack` or `helm upgrade --install promtail loki/promtail`

**Expected behavior**
Promtail pod should be in running state.

**Environment:**
 - Infrastructure: AKS
 - Deployment tool: HELM

**Screenshots, promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by slim-bean** [comment]
can you paste the full output of the promtail log so we can see what the unmarshal errors are?

**Comment by C123R** [comment]
> can you paste the full output of the promtail log so we can see what the unmarshal errors are?

Here you go:

`level=error ts=2019-07-19T14:15:12.413377984Z caller=main.go:45 msg="error creating promtail" error="yaml: unmarshal errors:\n  line 2: cannot unmarshal !!str `0` into int64\n  line 3: cannot unmarshal !!str `0` into int64\n  line 4: cannot unmarshal !!str `0` into int64\n  line 5: cannot unmarshal !!str `13270` into int64\n  line 6: cannot unmarshal !!str `94` into int64\n  line 7: cannot unmarshal !!str `10749` into int64\n  line 8: cannot unmarshal !!str `93` into int64\n  line 9: cannot unmarshal !!str `0` into int64\n  line 10: cannot unmarshal !!str `9066295` into int64\n  line 11: cannot unmarshal !!str `334` into int64\n  line 12: cannot unmarshal !!str `433` into int64\n  line 13: cannot unmarshal !!str `799` into int64\n  line 14: cannot unmarshal !!str `94` into int64\n  line 15: cannot unmarshal !!str `21029` into int64\n  line 16: cannot unmarshal !!str `93` into int64\n  line 17: cannot unmarshal !!str `14271121` into int64\n  line 18: cannot unmarshal !!str `1995233` into int64\n  line 19: cannot unmarshal !!str `787` into int64\n  line 20: cannot unmarshal !!str `94` into int64\n  line 21: cannot unmarshal !!str `5980` into int64\n  line 22: cannot unmarshal !!str `37085471` into int64\n  line 23: cannot unmarshal !!str `8608` into int64\n  line 24: cannot unmarshal !!str `94` into int64\n  line 25: cannot unmarshal !!str `32889` into int64\n  line 26: cannot unmarshal !!str `3052` into int64\n  line 27: cannot unmarshal !!str `44596` into int64\n  line 28: cannot unmarshal !!str `1354` into int64\n  line 29: cannot unmarshal !!str `0` into int64\n  line 30: cannot unmarshal !!str `94` into int64\n  line 31: cannot unmarshal !!str `3646` into int64\n  line 32: cannot unmarshal !!str `94` into int64\n  line 33: cannot unmarshal !!str `29097535` into int64\n  line 34: cannot unmarshal !!str `93` into int64\n  line 35: cannot unmarshal !!str `93` into int64\n  line 36: cannot unmarshal !!str `1357` into int64\n  line 37: cannot unmarshal !!str `802` into int64\n  line 38: cannot unmarshal !!str `94` into int64\n  line 39: cannot unmarshal !!str `2482` into int64\n  line 40: cannot unmarshal !!str `94` into int64"`

**Comment by Kuqd** [comment]
Hello, I think there is an issue with your config file. Have you tried to look at it ?

**Comment by C123R** [comment]
@Kuqd I am not passing any config file for promtail, it uses default one.

**Comment by Kuqd** [comment]
There is still a config file involve when using helm, I'm wondering if this isn't just a mismatch between helm version and docker tag version.

**Comment by slim-bean** [comment]
yeah those are some bizarre errors, something seems awry with your config.  Can you look at the promtail configmap and post it?

```
kubectl describe configmaps promtail 
```

**Comment by C123R** [comment]
> yeah those are some bizarre errors, something seems awry with your config. Can you look at the promtail configmap and post it?
> 
> ```
> kubectl describe configmaps promtail 
> ```

@slim-bean Thanks for your reply. Below is the describe output of promtail CM.

Moreover, I would like to highlight: If I try running promtail with `grafana/promtail:latest` or `grafana/promtail:master` with same configmap it works.

```sh
$ kubectl describe configmaps loki-promtail -n monitoring
```
```yaml
Name:         loki-promtail
Namespace:    monitoring
Labels:       app=promtail
              chart=promtail-0.8.1
              heritage=Tiller
              release=loki
Annotations:  <none>

Data
====
promtail.yaml:
----
client:
  backoff_config:
    maxbackoff: 5s
    maxretries: 5
    minbackoff: 100ms
  batchsize: 102400
  batchwait: 1s
  external_labels: {}
  timeout: 10s
positions:
  filename: /run/promtail/positions.yaml
server:
  http_listen_port: 3101
target_config:
  sync_period: 10s

scrape_configs:
- job_name: kubernetes-pods-name
  pipeline_stages:
    - docker: {}
    
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels:
    - __meta_kubernetes_pod_label_name
    target_label: __service__
  - source_labels:
    - __meta_kubernetes_pod_node_name
    target_label: __host__
  - action: drop
    regex: ^$
    source_labels:
    - __service__
  - action: replace
    replacement: $1
    separator: /
    source_labels:
    - __meta_kubernetes_namespace
    - __service__
    target_label: job
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: instance
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container_name
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - replacement: /var/log/pods/*$1/*.log
    separator: /
    source_labels:
    - __meta_kubernetes_pod_uid
    - __meta_kubernetes_pod_container_name
    target_label: __path__
- job_name: kubernetes-pods-app
  pipeline_stages:
    - docker: {}
    
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: drop
    regex: .+
    source_labels:
    - __meta_kubernetes_pod_label_name
  - source_labels:
    - __meta_kubernetes_pod_label_app
    target_label: __service__
  - source_labels:
    - __meta_kubernetes_pod_node_name
    target_label: __host__
  - action: drop
    regex: ^$
    source_labels:
    - __service__
  - action: replace
    replacement: $1
    separator: /
    source_labels:
    - __meta_kubernetes_namespace
    - __service__
    target_label: job
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: instance
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container_name
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - replacement: /var/log/pods/*$1/*.log
    separator: /
    source_labels:
    - __meta_kubernetes_pod_uid
    - __meta_kubernetes_pod_container_name
    target_label: __path__
- job_name: kubernetes-pods-direct-controllers
  pipeline_stages:
    - docker: {}
    
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: drop
    regex: .+
    separator: ''
    source_labels:
    - __meta_kubernetes_pod_label_name
    - __meta_kubernetes_pod_label_app
  - action: drop
    regex: ^([0-9a-z-.]+)(-[0-9a-f]{8,10})$
    source_labels:
    - __meta_kubernetes_pod_controller_name
  - source_labels:
    - __meta_kubernetes_pod_controller_name
    target_label: __service__
  - source_labels:
    - __meta_kubernetes_pod_node_name
    target_label: __host__
  - action: drop
    regex: ^$
    source_labels:
    - __service__
  - action: replace
    replacement: $1
    separator: /
    source_labels:
    - __meta_kubernetes_namespace
    - __service__
    target_label: job
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: instance
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container_name
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - replacement: /var/log/pods/*$1/*.log
    separator: /
    source_labels:
    - __meta_kubernetes_pod_uid
    - __meta_kubernetes_pod_container_name
    target_label: __path__
- job_name: kubernetes-pods-indirect-controller
  pipeline_stages:
    - docker: {}
    
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: drop
    regex: .+
    separator: ''
    source_labels:
    - __meta_kubernetes_pod_label_name
    - __meta_kubernetes_pod_label_app
  - action: keep
    regex: ^([0-9a-z-.]+)(-[0-9a-f]{8,10})$
    source_labels:
    - __meta_kubernetes_pod_controller_name
  - action: replace
    regex: ^([0-9a-z-.]+)(-[0-9a-f]{8,10})$
    source_labels:
    - __meta_kubernetes_pod_controller_name
    target_label: __service__
  - source_labels:
    - __meta_kubernetes_pod_node_name
    target_label: __host__
  - action: drop
    regex: ^$
    source_labels:
    - __service__
  - action: replace
    replacement: $1
    separator: /
    source_labels:
    - __meta_kubernetes_namespace
    - __service__
    target_label: job
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: instance
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container_name
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - replacement: /var/log/pods/*$1/*.log
    separator: /
    source_labels:
    - __meta_kubernetes_pod_uid
    - __meta_kubernetes_pod_container_name
    target_label: __path__
- job_name: kubernetes-pods-static
  pipeline_stages:
    - docker: {}
    
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: drop
    regex: ^$
    source_labels:
    - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_label_component
    target_label: __service__
  - source_labels:
    - __meta_kubernetes_pod_node_name
    target_label: __host__
  - action: drop
    regex: ^$
    source_labels:
    - __service__
  - action: replace
    replacement: $1
    separator: /
    source_labels:
    - __meta_kubernetes_namespace
    - __service__
    target_label: job
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: instance
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container_name
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - replacement: /var/log/pods/*$1/*.log
    separator: /
    source_labels:
    - __meta_kubernetes_pod_annotation_kubernetes_io_config_mirror
    - __meta_kubernetes_pod_container_name
    target_label: __path__

Events:  <none>

```
