### ISSUE TITLE
Does loki supports ceph rbd as its backend storage?

### ISSUE THREAD

**Issue by ningyougang** [grafana/loki#7863]
Currently, i know, loki supports `ceph s3` as its backend storage, e.g. below is my test, works well using `ceph s3`
```
  schema_config:
    configs:
    - from: 2022-08-12
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
  server:
    http_listen_port: 3100
  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h 
      shared_store: s3
    aws:
      s3: s3://xxx:xxx@10.106.250.27:80/bucketName
      s3forcepathstyle: true
```
refer to: https://grafana.com/docs/loki/latest/configuration/examples/#aws-basic-config-no-credsyaml

But i didn't find any doc that `use ceph rbd as loki's backend storage`, someone knows?
