### ISSUE TITLE
Query don't return results since update

### ISSUE THREAD

**Issue by Christoph-AK** [grafana/loki#7865]
Hey there, since the main update today my queries don't return results anymore. I looked through the commits and couldn't find any changed config that would impact me. What could be the problem? I have rolled back from :main to the :latest version, but the queries are still empty. (Probably broken since 433d883fcd7b837b927637e09893008cd2eec356 )

Neither old nor new log lines show up. No new objects are written to s3.

What is happening here? I hope the logs are not lost. (Using s3 as backend.)

Config 
```yaml
auth_enabled: false

server:
  http_listen_port: 4100
  http_server_read_timeout: 3m
  http_server_write_timeout: 3m

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 10s
  chunk_idle_period: 5m
  wal:
    dir: "/loki/wal"
    flush_on_shutdown: true
    replay_memory_ceiling: "512MB"

schema_config:
  configs:
    # - store: boltdb
    #   object_store: filesystem
    #   schema: v11
    #   index:
    #     prefix: index_
    #     period: 24h
    - store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: aws_index_
        period: 24h

compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: aws

storage_config:
  # boltdb:
  #   directory: /loki/index

  # filesystem:
  #   directory: /loki/chunks

  aws:
    bucketnames: <bucket>
    region: eu-central-1
    access_key_id: <key>
    secret_access_key: <key>
    sse_encryption: true
    endpoint: s3.eu-central-1.amazonaws.com

  boltdb_shipper:
    active_index_directory: /loki/index
    shared_store: s3
    cache_location: /loki/boltdb-cache

limits_config:
  enforce_metric_name: false
  split_queries_by_interval: 24h

frontend:
  compress_responses: true
  max_outstanding_per_tenant: 4096

querier:
  max_concurrent: 1024
```

**Environment:**
 - Infrastructure: Docker on AWS EC2
