### ISSUE TITLE
Report error log: error loading cache generation numbers

### ISSUE THREAD

**Issue by ningyougang** [grafana/loki#7885]
I did benchmark against loki, found some errors

### Loki configuration
```
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 0s
    compactor:
      shared_store: filesystem
      working_directory: /data/loki/boltdb-shipper-compactor
      retention_enabled: false
    distributor:
      ring:
        kvstore:
          store: memberlist
    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
      query_store_max_look_back_period: -1
      wal:
        enabled: true
        dir: /data/wal
    limits_config:
      ingestion_rate_mb: 8
      ingestion_burst_size_mb: 16
      per_stream_rate_limit: 5MB
      per_stream_rate_limit_burst: 15MB
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    memberlist:
      join_members:
        - loki-headless
    schema_config:
      configs:
      - from: "2022-11-20"
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          period: 24h
          prefix: index_
        chunks:
          period: 24h
          prefix: chunks_
    server:
      http_listen_port: 3100
    storage_config:
      boltdb:
        directory: /data/loki/index
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
```
### Reported below error logs often.
```
2022-12-09T15:58:28.2369245+09:00 stderr F level=error ts=2022-12-09T06:58:28.196953929Z caller=gennumber_loader.go:129 msg=\"error loading cache generation numbers\" err=\"unexpected status code: 404
...
...
2022-12-09T15:58:28.236956964+09:00 stderr F level=error ts=2022-12-09T06:58:28.197187929Z caller=delete_requests_client.go:211 msg=\"error getting delete requests from the store\" err=\"unexpected status code: 404
```
