### ISSUE TITLE
Loki readers and writes are not becoming ready with "failed services" as a response

### ISSUE THREAD

**Issue by kastriotdobratiqi** [grafana/loki#7914]
**Describe the bug**
Deployed Loki using the grafana/loki helm chart `version: 3.6.0, appVersion: 2.7.0` based on readers/writers structure (also known as simple-scalable on the deprecated version) and the pods are failing, showing:
```
failed services
github.com/grafana/loki/pkg/loki.(*Loki).Run
        /src/loki/pkg/loki/loki.go:446
main.main
        /src/loki/cmd/loki/main.go:105
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1594
```

**To Reproduce**
1. Deploy loki by overriding the following from helm values:
```
serviceAccount:
  name: loki
  annotations:
    eks.amazonaws.com/role-arn: "<loki-iam-role-arn>"

loki:
  auth_enabled: false
  storage:
    bucketNames:
      chunks: <loki-bucket>
    s3:
      s3: s3://us-east-1/<loki-bucket>
      s3ForcePathStyle: true
      region: us-east-1
  compactor:
    working_directory: /var/loki/compactor
    shared_store: s3
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/index_cache
      shared_store: s3

monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    lokiCanary:
      enabled: false
    grafanaAgent:
      installOperator: false

test:
  enabled: false

gateway:
  ingress:
    enabled: true
    hosts:
      - host: <loki-host>
        paths:
          - path: /
            pathType: Prefix
    tls: {}
  autoscaling:
    enabled: true

singleBinary:
  enabled: false

read:
  autoscaling:
    enabled: true
```

I tested reaching out the s3 bucket using the sa from a different pod and it worked fine. I do not really get much info from the error output. I came up with the config based on the docs and the helm chart format. Is something wrong with my config?

**Expected behavior**
Loki readers and writers come up and work as intended.

**Environment:**
 - Infrastructure: EKS v1.23
 - Deployment tool: Helm chart
