### ISSUE TITLE
ec2_sd_configs official tutorial missing port declaration in ec2_sd_configs

### ISSUE THREAD

**Issue by life5ign** [grafana/loki#7958]
**Describe the bug**
The instructions do not say to set the `host:` key in `ec2_sd_configs` to the `server: -> http_listen_port` value, and thus port 80 is used to scrape, which is never/rarely used.

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by life5ign** [comment]
I don't have time to fill out all that, but want to help the project; I think this is clear, but if you have any questions, please ask me, thank you

**Comment by life5ign** [comment]
This is the official customer facing tutorial and there's *no* reply?

**Comment by vishwa-trulioo** [comment]
Is there any update on this? I'm also a paying customer. Would it be possible to provide and answer. I suppose the fix should be easy.

**Comment by rgroothuijsen** [comment]
> I've been working on this for several hours and am totally stuck. One problem is that I can't get debugging on what capture group I'm effectively grabbing, even with log.level=trace, and am using this config for promtail:

It did appear to be almost correct. I tested your config by temporarily replacing the `__host__` target with something like `fake_host` so that it would show up in the logs in any case, which gave me the IP part without the rest of the hostname. To get the full hostname, place the final `.*` within your capture group instead of after it: `regex: '^(ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+.*)'`

**Comment by life5ign** [comment]
@rgroothuijsen good idea re. using a dummy label.  I did the same, and found that my regex was working as intended.  `echo $HOSTNAME` on the instance showed the same thing.  For some reason, the problem was explicitly stating `replacement`; I removed that line, and it worked.  Below is the config that works:

```yaml
- source_labels: [__meta_ec2_private_dns_name]
  regex: '^(ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+).*'
  # the first capture group      
  # adding this explicitly prevented the relabeling from working
  #replacement: "${1}"
  target_label: __host__
```

Using `(.*)` wouldn't work, because it would capture something like `ip-xxx-xxx-xxx-xxx.<region>.compute.internal` , which wouldn't match `$HOSTNAME` on the instance, which only has the hostname part of that (private) domain name.

I don't have time to explore why this is happening, but I'm guessing that non-capturing groups need to be used in sub expressions in the regex, or there is a bug with promtail.

Thanks for your inspiration.  Glad it's working now!

**Comment by malcolm061990** [comment]
Hi.
What is the full final config? It still doesn't work for me.

**Comment by Ayatallah** [comment]
@life5ign how you could validate its working from grafana?

**Comment by dm-canteen** [comment]
Just ran into this issue, very disappointing as I remember `ec2_sd_configs` being easy to setup and get working last time I played around with it. I still couldn't get the labels working even with the snippet above.

I note that `$HOSTNAME` on my instances (Amazon Linux 2) is set to the entire `ip-xxx-xxx-xxx-xxx.<region>.compute.internal` value. Commenting out the `regex:` line doesn't help with this.

My relevant YAML:
```YAML
ec2_sd_configs:
  # This allows promtail to connect to EC2 and gather the following source labels
  - region: ${AWS_DEFAULT_REGION}
    access_key: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_ACCESS_KEY}
    port: 9080

relabel_configs:
  # Use the ec2 labels as target loki labels
  - source_labels: [__meta_ec2_tag_Name]
    target_label: name
    action: replace
  - source_labels: [__meta_ec2_tag_AppName]
    target_label: app_name
    action: replace
  - source_labels: [__meta_ec2_instance_id]
    target_label: instance
    action: replace
  - source_labels: [__meta_ec2_private_dns_name]
    # ip-xxx-xxx-xxx-xxx.<region>.compute.internal
    # regex: '^(ip-[0-9]+-[0-9]+-[0-9]+-[0-9]+).*'
    target_label: __host__
  - target_label: source
    replacement: grafana-agent
    action: replace
```
