### ISSUE TITLE
DNS resolution fails in docker container despite nslookup giving the expected result

### ISSUE THREAD

**Issue by mspiess** [grafana/loki#7971]
**Describe the bug**
In a docker swarm setup loki containers fail to join the memberlist because the container name cannot be resolved.

**To Reproduce**
1. Create a file named `docker-compose.yml` with the following content:
  ```yaml
  version: "3.9"
  
  configs:
    loki-config:
      file: loki-config.yaml
  
  services:
    cassandra:
      image: cassandra:4.0.7
      deploy:
        endpoint_mode: dnsrr
  
    loki:
      image: grafana/loki:2.7.1
      configs:
        - source: loki-config
          target: /etc/loki/config.yaml
      command: -config.file=/etc/loki/config.yaml
      deploy:
        replicas: 2
        endpoint_mode: dnsrr
      healthcheck:
        test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
        interval: 10s
        timeout: 5s
        retries: 5

  ```
2. Create a file named `loki-config.yaml` with the following content:
  ```yaml
  target: "all,table-manager"
  
  auth_enabled: false
  
  server:
    http_listen_port: 3100
    grpc_listen_port: 9096
  
  common:
    replication_factor: 2
    ring:
      kvstore:
        store: memberlist
  
  ingester:
    wal:
      enabled: true
      dir: /loki/wal # fix for "mkdir wal: permission denied
  
  memberlist:
    abort_if_cluster_join_fails: false
    gossip_nodes: 0
  
    bind_port: 7946
  
    join_members:
      - dns+loki:7946
  
    max_join_backoff: 1m
    max_join_retries: 10
    min_join_backoff: 1s
  
  
  storage_config:
    cassandra:
      addresses: cassandra
      keyspace: loki
      replication_factor: 1
  
  schema_config:
    configs:
      - from: 2022-12-18
        store: cassandra
        schema: v11
        index:
          prefix: index_
          period: 168h
        chunks:
          prefix: chunk_
          period: 168h
  
  ruler:
    alertmanager_url: http://localhost:9093
  
  analytics:
    reporting_enabled: false
  ```
3. Run `docker stack deploy -c docker-compose.yml loki`
4. Follow the logs with `docker service logs -f loki_loki`

**Expected behavior**
Both loki containers start and form a ring.

**Environment:**
 - Infrastructure: Docker swarm
 - Deployment tool: docker cli

**Screenshots, Promtail config, or terminal output**
Relevant loki logs:
```
loki_loki.1.nrm0iuv17j1k    | level=error ts=2022-12-19T14:43:04.074141149Z caller=resolver.go:86 msg="failed to lookup IP addresses" host=loki err="lookup loki on 127.0.0.11:53: no such host"
loki_loki.1.nrm0iuv17j1k    | level=warn ts=2022-12-19T14:43:04.074177659Z caller=resolver.go:133 msg="IP address lookup yielded no results. No host found or no addresses found" host=loki
loki_loki.1.nrm0iuv17j1k    | level=warn ts=2022-12-19T14:43:04.074210612Z caller=memberlist_client.go:601 msg="joining memberlist cluster: found no nodes to join" retries=2
loki_loki.2.bwkeeg06e806    | level=error ts=2022-12-19T14:43:06.099598875Z caller=resolver.go:86 msg="failed to lookup IP addresses" host=loki err="lookup loki on 127.0.0.11:53: no such host"
loki_loki.2.bwkeeg06e806    | level=warn ts=2022-12-19T14:43:06.099671503Z caller=resolver.go:133 msg="IP address lookup yielded no results. No host found or no addresses found" host=loki
loki_loki.2.bwkeeg06e806    | level=warn ts=2022-12-19T14:43:06.099716173Z caller=memberlist_client.go:601 msg="joining memberlist cluster: found no nodes to join" retries=2
```

Output of `docker exec loki_loki.1.nrm0iuv17j1kx4ono0g2ooy03 nslookup loki`:
```
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:

Non-authoritative answer:
Name:   loki
Address: 10.0.62.18
Name:   loki
Address: 10.0.62.19
```

Setting `GODEBUG=netdns=cgo` for the loki containers has no effect:
```
go package net: built with netgo build tag; using Go's DNS resolver
```
