### ISSUE TITLE
GCS storage : private key structure error

### ISSUE THREAD

**Issue by GrimDev** [grafana/loki#7977]
**Describe the bug**
Hi there, I'm unable to store my loki chunks on GCS due to the following error :
`private key should be a PEM or plain PKCS1 or PKCS8; parse error: asn1: structure error: tags don't match (16 vs {class:0 tag:13 length:45 isCompound:true}`

I'm using the `service_account` params that seem's pretty new; I put in it my JSON service account key in one line string format, downloaded from GC Service Account Key Management.

**To Reproduce**
1. Configure loki GCS storage (bucket_name & service_account)
2. Started Loki version HEAD-e0af1cc (branch: HEAD, revision: e0af1cc8a)
3. Send a test log via any solution (for me using winton loki)

When configuring with local filesystem storage, it works well, but with the following configuration, I got the previous error.

```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /tmp/loki
  storage:
    filesystem: null
    gcs:
      bucket_name: my-loki-bucket-name
      service_account: '{"type":"service_account","project_id":"XXX","private_key_id":"XXX","private_key":"-----BEGIN PRIVATE KEY-----\\nmyPrivateKey\\n-----END PRIVATE KEY-----\\n","client_email":"XXX","client_id":"XXX","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_x509_cert_url":"XXX"}'
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
```

To produce the service account param, I created GCloud service account with full access permission to the bucket, exported the JSON file, ran "JSON.stringify(MY_JSON)" and copy/pasted it into the loki config.

**Expected behavior**
Logs into GCS

**Environment:**
 - Infrastructure: Bare ubuntu 22.0.4
 - Deployment tool: Binary

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by GrimDev** [comment]
[EDIT]

Updated the following param, issue still present 

```yaml
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: gcs
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/index
    shared_store: gcs
    cache_location: /data/loki/index_cache
    resync_interval: 5s
```
