### ISSUE TITLE
Logstash plugin doesn't send logs to Loki

### ISSUE THREAD

**Issue by ichasco-heytrade** [grafana/loki#7986]
**Describe the bug**
I have added in logstatsh the output plugin of loki and it seems like it doesn't send any logs to loki. Logstash is working because it sends also logs to opensearch and it works pefect.

**To Reproduce**
Install loki output plugin in logstash
Configure the output to send the logs to loki
Generate logs

**Expected behavior**
I need to send logs from logstash to loki

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Versions**
Loki: `2.7.0`
Logstash: `8.4.0` | Docker Image: `opensearchproject/logstash-oss-with-opensearch-output-plugin`

**Configs**

Loki:
```
auth_enabled: false
    common:
      path_prefix: /var/loki
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
      storage:
        filesystem:
          chunks_directory: /var/loki/chunks
          rules_directory: /var/loki/rules
    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
    memberlist:
      join_members:
      - loki-memberlist
    query_range:
      align_queries_with_step: true
    schema_config:
      configs:
      - from: "2022-01-11"
        index:
          period: 24h
          prefix: loki_index_
        object_store: filesystem
        schema: v12
        store: boltdb-shipper
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
    storage_config:
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
```
Logstash:
```
    input {
        http {
          port      => 9601
          add_field => { "[@metadata][input-http]" => "" }
        }
      }
      filter {
        if [@metadata][input-http] == "" {
          date {
            match         => [ "date", "UNIX" ]
            remove_field  => [ "date" ]
          }
          mutate {
            remove_field => ["headers","host","_p"]
          }
        }
      }
      output {
      if [cluster] == "development" {
          loki {
            url => "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
            insecure_skip_verify => true
          }
          opensearch {
            hosts => ["${ELASTIC_HOST}"]
            auth_type => {
              type      => 'basic'
              user      => "${ELASTIC_USERNAME}"
              password  => "${ELASTIC_PASSWORD}"
            }
            index  => "logstash-dev-%{+YYYY.MM.dd}"
            action => "create"
          }
        }
     }
```

If I send a log with curl to loki, it works. So I guess that is loki out plugin error beacause logstash also sends the logs as expected to opensearch.

Thanks
