### ISSUE TITLE
Loki and Azure Blob Storage - AWS NoCredentialProviders error

### ISSUE THREAD

**Issue by raxtorDD** [grafana/loki#8003]
I am using Loki with an external azure blob storage. As of now I am not able to connect successfully to this container.
Guessing from the error I am getting, Loki tries to connect to aws instead to azure (or logging is just not implemented right).
I tried to connect via service principal and with account key. Both result in the same error.

1. Started Loki v2.7.0 (Chart v3.8.0)
2. Started Promtail v2.7.0 (Chart v6.7.4)
3. Query: `{app=loki} term`

**Expected behavior**
No error messages regarding connection to the azure blob storage.
Available logs in azure blob storage.

**Environment:**
 - Azure Kubernetes 1.22.6 with Kong Gateway deployed
 - Deployment tool: helm

**Error Message in Loki:**

`level=error ts=2022-12-23T18:04:36.525152314Z caller=flush.go:144 org_id=fake msg="failed to flush" err="failed to flush chunks: store put chunk: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors, num_chunks: 1, labels: {app=\"test-service\", container=\"curl\", filename=\"/var/log/pods/app-dev_test-service-27863605--1-trx8l_aa90b90c-e426-471b-811f-f6bd454160ba/curl/0.log\", job=\"app-dev/app-service\", namespace=\"app-dev\", node_name=\"aks-nodepool1-10332009-vmss000022\", pod=\"app-service-27863605--1-trx8l\", stream=\"stderr\"}" `

```
# values.yaml loki (with service principal)

loki:
  auth_enabled: false
  server:
    http_listen_port: 3100
  commonConfig:
    replication_factor: 1

write:
  replicas: 1
read:
  replicas: 1

schema_config:
  configs:
  - from: "2020-12-11"
    index:
      period: 24h
      prefix: loki_index_
    schema: v11
    store: boltdb-shipper
    object_store: azure
storage_config:
  azure:
    use_service_principal: true
    tenant_id : <tenant_id>
    client_id: <client_id>
    client_secret: <client_secret>
    container_name: loki-dev
    request_timeout: 0
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/cache
    cache_ttl: 24h
    shared_store: azure
```

```
# values.yaml loki (with account key)

loki:
  auth_enabled: false
  server:
    http_listen_port: 3100
  commonConfig:
    replication_factor: 1

write:
  replicas: 1
read:
  replicas: 1

schema_config:
  configs:
  - from: "2020-12-11"
    index:
      period: 24h
      prefix: loki_index_
    schema: v11
    store: boltdb-shipper
    object_store: azure
storage_config:
  azure:
    account_name: loggingstorage
    account_key: <account_key>
    use_managed_identity: false
    container_name: loki-dev
    request_timeout: 0
  boltdb_shipper:
    active_index_directory: /data/loki/index
    cache_location: /data/loki/cache
    cache_ttl: 24h
    shared_store: azure
```

**Comment by raxtorDD** [comment]
Whelp, this was an error on my side. I had troubles to figure out the correct format of the values.yaml.
What really made me think long and hard was the resulting loki configuration.
Here the default storage aws s3 was listed. As far as I could notice, this is just been ignored by loki if the "storage_config" is set correctly.

Here is the working version:

```
# loki values.yaml

write:
  replicas: 1
read:
  replicas: 1

loki:
  auth_enabled: false
  server:
    http_listen_port: 3100
  commonConfig:
    replication_factor: 1

  schemaConfig:
    configs:
    - from: "2022-12-01"
      index:
        period: 24h
        prefix: loki_index_
      schema: v11
      store: boltdb-shipper
      object_store: azure

  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      cache_ttl: 24h
      shared_store: azure
    azure:
      account_name: loggingstorage
      account_key: ***
      container_name: loki-dev
      request_timeout: 0

  compactor:
    working_directory: /var/loki/boltdb-shipper-compactor
    shared_store: azure
```
