### ISSUE TITLE
grafana-loki via Helm Chart, logs older than 2 hours disappear

### ISSUE THREAD

**Issue by TsengSR** [grafana/loki#8023]
**Describe the bug**
I have installed grafana-loki from the bitnami helm chart repository and it works so far. My only issue is, logs older than 2 hours disappear. Been looking for the past 3 days and I can't find the issue. The settings are pretty much default, 

The values are pretty much default, I only disabled promtail since it was getting logs from all pods and I was only interested in containers sending logs via Serilog Sink to the loki instance. 

**To Reproduce**
Install grafana loki from bitnami via 

```bash
helm install grafana-loki bitnami/grafana-loki -n monitoring --values grafana-loki.yaml
`` 
and add it as data source to grafana.

**Expected behavior**
Logs to retain for 7 days (default settings)

**Environment:**
 - Infrastructure: Self-Hosted Kubernetes Cluster (no could)
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
values.yaml
```
promtail:
  enable: false
```

**Comment by TsengSR** [comment]
The Ingester seems to write properly, but the Querier's PV is empty. Feel there's something not working

**Comment by mateuszdrab** [comment]
I have a very similar issue in my not-so-typical test setup where I tried to run the ingester, querier and compactor in the same pod so that I can the `filesystem` store, whilst keeping the microservices chart. 
Logs get ingested fine, the index is seen moving to the 'store' and when that happens, the logs seem to disappear.

I was able to use the `boltdb` store instead of `boltdb-shipper` which allowed the logs to be queried and didn't observe any disappearing.

There are configuration parameters which can force the querier to query only the ingester or the store, I tried also setting `query_store_max_look_back_period` to `-1` which made no change.

The logs do seem to exist on the disk, as the space usage is continuously growing for `/var/loki/chunks`, which makes the inability to query them a bit bizzare.

Which chart and deployment model/backend store are you using?

**Comment by TsengSR** [comment]
I tried everything possible. At first, the bitnami helm charts with both filesystem and minio storages, then the official helm charts with both filesystem and minio and also the latest 3.x chart with single binary mode and distributed with s3 (against minio).

It's a on-premises k8s cluster. On both filesystem and minio chunks seem to be written, but the read replicas never seem to be able to retrieve them.
In case of the official v3 helm chart in distributed mode (s3 against minio), the files are uploaded correctly but the read replicas show errors on reading, but logs only go back for the 2-3 hours span.

After 2-3 days readers crashloop while trying to read the files and will keep so until the chunks from minio are deleted

**Comment by mateuszdrab** [comment]
> I tried everything possible. At first, the bitnami helm charts with both filesystem and minio storages, then the official helm charts with both filesystem and minio and also the latest 3.x chart with single binary mode and distributed with s3 (against minio).
> 
> 
> 
> It's a on-premises k8s cluster. On both filesystem and minio chunks seem to be written, but the read replicas never seem to be able to retrieve them.
> 
> In case of the official v3 helm chart in distributed mode (s3 against minio), the files are uploaded correctly but the read replicas show errors on reading, but logs only go back for the 2-3 hours span.
> 
> 
> 
> After 2-3 days readers crashloop while trying to read the files and will keep so until the chunks from minio are deleted

This is really strange, I've not experienced that.

Perhaps post your redacted values for the deloyment?

**Comment by TsengSR** [comment]
Tried it today again, with Chart 4.5. Installed as singleBinary mode, but with 3 replicas and MinIO als S3 Storage.

Logs were there for about 3 hours and then it happened again, all older than 30 mins gone. I see that there are 62 MB written on each replica on the file system.  45 MB of it is inside chunks folder, 15 the write-ahead-log (wal). 

Still, the total uploaded chunks on MinIO storage is 290 KB

![image](https://user-images.githubusercontent.com/10427430/217280101-a060e809-8969-4925-bbfc-52ad52d831f6.png)

**Comment by samcm** [comment]
@TsengSR Did you ever figure this one out?

**Comment by TsengSR** [comment]
> @TsengSR Did you ever figure this one out?

I think I did, as I wrote in [this comment](https://github.com/grafana/loki/issues/3248#issuecomment-1424496597). My assumption is, that there is a race condition when saving the files, which triggers the described bug when using NFS. 

My quick research shows that the .nfs0000xxx files comes, when a client tries to delete a file, but the file is still being accessed by another process. Since the file doesn't seem to be released, it remains and loki tries to read in these files and throws errors.

But it seems no one is having a closer look there and so far i fear there's no way to run it properly on NFS until this is fixed. I haven't seen any other issues with NFS except for these. And my skills in go are non-existent to look into these. 

I assume there's a file handle thats not being released properly.

**Comment by phyzical** [comment]
https://github.com/grafana/loki/issues/9131#issuecomment-1689389189

Just thought id add my config in case it saves someone a few hours in the future

**Comment by XXA964** [comment]
Bonjour, 
j'ai aussi le même problème au bout de trois heure je perd mes logs dans grafana j'ai tenté de modifier le code de ma charte les retentions ...etc 

voici ma config: 
 configuration: |
    auth_enabled: false

    server:
      http_listen_port: {{ .Values.loki.containerPorts.http }}

    common:
      compactor_address: http://{{ include "grafana-loki.compactor.fullname" . }}:{{ .Values.compactor.service.ports.http }}

    distributor:
      ring:
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - {{ include "grafana-loki.gossip-ring.fullname" . }}

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: none
      chunk_retain_period: 720h
      max_transfer_retries: 0
      wal:
        dir: {{ .Values.loki.dataDir }}/wal

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 720h
      reject_old_samples_max_age: 720h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      retention_period: 720h


    schema_config:
      configs:
      - from: 2023-10-07
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h      

    storage_config:
      boltdb_shipper:
        shared_store: filesystem
        active_index_directory: {{ .Values.loki.dataDir }}/loki/index
        cache_location: {{ .Values.loki.dataDir }}/loki/cache
        cache_ttl: 24h
        {{- if .Values.indexGateway.enabled }}
        index_gateway_client:
          server_address: {{ (printf "dns:///%s:9095" (include "grafana-loki.index-gateway.fullname" .)) }}
        {{- end }}
      filesystem:
        directory: {{ .Values.loki.dataDir }}/chunks
      index_queries_cache_config:
        {{- if .Values.memcachedindexqueries.enabled }}
        memcached:
          batch_size: 100
          parallelism: 100
        memcached_client:
          consistent_hash: true
          addresses: dns+{{ include "grafana-loki.memcached-index-queries.host" . }}
          service: http
        {{- end }}

    chunk_store_config:
      max_look_back_period: 720h
      {{- if .Values.memcachedchunks.enabled }}
      chunk_cache_config:
        memcached:
          batch_size: 100
          parallelism: 100
        memcached_client:
          consistent_hash: true
          addresses: dns+{{ include "grafana-loki.memcached-chunks.host" . }}
      {{- end }}
      {{- if .Values.memcachedindexwrites.enabled }}
      write_dedupe_cache_config:
        memcached:
          batch_size: 100
          parallelism: 100
        memcached_client:
          consistent_hash: true
          addresses: dns+{{ include "grafana-loki.memcached-index-writes.host" . }}
      {{- end }}

    table_manager:
      retention_deletes_enabled: true
      retention_period: 613200h

    query_range:
      align_queries_with_step: true
      max_retries: 5
      cache_results: true
      results_cache:
        cache:
          {{- if .Values.memcachedfrontend.enabled }}
          memcached_client:
            consistent_hash: true
            addresses: dns+{{ include "grafana-loki.memcached-frontend.host" . }}
            max_idle_conns: 16
            timeout: 500ms
            update_interval: 1m
          {{- else }}
          embedded-cache:
            enabled: true
            max_size_items: 1024
            validity: 720h
          {{- end }}
    {{- if not .Values.queryScheduler.enabled }}
    frontend_worker:
      frontend_address: {{ include "grafana-loki.query-frontend.fullname" . }}:{{ .Values.queryFrontend.service.ports.grpc }}
    {{- end }}

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      tail_proxy_url: http://{{ include "grafana-loki.querier.fullname" . }}:{{ .Values.querier.service.ports.http }}

    compactor:
      shared_store: filesystem
      retention_enabled: true 
      retention_delete_delay: 600h
      retention_delete_worker_count: 90000


    ruler:
      storage:
        type: local
        local:
          directory: {{ .Values.loki.dataDir }}/conf/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      alertmanager_url: https://alertmanager.xx
      external_url: https://alertmanager.xx

avez vous une idée ?

**Comment by nesa-david** [comment]
> I tried everything possible. At first, the bitnami helm charts with both filesystem and minio storages, then the official helm charts with both filesystem and minio and also the latest 3.x chart with single binary mode and distributed with s3 (against minio).
> 
> It's a on-premises k8s cluster. On both filesystem and minio chunks seem to be written, but the read replicas never seem to be able to retrieve them. In case of the official v3 helm chart in distributed mode (s3 against minio), the files are uploaded correctly but the read replicas show errors on reading, but logs only go back for the 2-3 hours span.
> 
> After 2-3 days readers crashloop while trying to read the files and will keep so until the chunks from minio are deleted

Can you share how you were able to install the bitnami grafana-loki helm chart with minio storage please? There is no official documentation on how to do this...

**Comment by TsengSR** [comment]
> > I tried everything possible. At first, the bitnami helm charts with both filesystem and minio storages, then the official helm charts with both filesystem and minio and also the latest 3.x chart with single binary mode and distributed with s3 (against minio).
> > It's a on-premises k8s cluster. On both filesystem and minio chunks seem to be written, but the read replicas never seem to be able to retrieve them. In case of the official v3 helm chart in distributed mode (s3 against minio), the files are uploaded correctly but the read replicas show errors on reading, but logs only go back for the 2-3 hours span.
> > After 2-3 days readers crashloop while trying to read the files and will keep so until the chunks from minio are deleted
> 
> Can you share how you were able to install the bitnami grafana-loki helm chart with minio storage please? There is no official documentation on how to do this...

Technically it is or was. The AWS S3 setup works with min.io, you just create an bucket and a user for it, then use that in the s3 string instead, so just install minio from its own helm chart, log in, create a bucket and then an user, allow that user to access the bucket and use the connection string + client credentials in the s3 connection string in the loki part of the helm chart and use s3 as storage. 

Thing is it doesn't works (or didn't work last year) when the minio (and/or loki) was running on an NFS PV provisioner rather than minio being mapped to an local pv/physical storage device

**Comment by nesa-david** [comment]
> > Can you share how you were able to install the bitnami grafana-loki helm chart with minio storage please? There is no official documentation on how to do this...
> 
> Technically it is or was. The AWS S3 setup works with min.io, you just create an bucket and a user for it, then use that in the s3 string instead, so just install minio from its own helm chart, log in, create a bucket and then an user, allow that user to access the bucket and use the connection string + client credentials in the s3 connection string in the loki part of the helm chart and use s3 as storage.
> 
> Thing is it doesn't works (or didn't work last year) when the minio (and/or loki) was running on an NFS PV provisioner rather than minio being mapped to an local pv/physical storage device

Hmm I've got a minio cluster set up properly with all the buckets configured. I also disabled authentication to make it simple. Unfortunately my difficulty is in pointing loki to the minio cluster for object storage. I can't see where to specify the "s3 connection string" in the [bitnami-grafana-loki values.yaml](https://github.com/bitnami/charts/blob/main/bitnami/grafana-loki/values.yaml) file.

Just for context: I started up a bitnami-grafana-loki cluster in kubernetes with minimal configuration and it started up successfully. However the logs seemed to disappear after about an hour. I was told that perhaps this is due to loki being configured with filesystem storage. In fact, in the [bitnami-grafana-loki readme.md](https://github.com/bitnami/charts/blob/main/bitnami/grafana-loki/README.md#limitation) file it says "**This chart does not function fully when using local filesystem as a persistence store. When using a local filesystem as a persistence store, querying will not be possible (or limited to the ingesters' in-memory caches). For a fully functional deployment of this helm chart, an object storage backend is required.**" Presumably this would be enough of a show-stopper that the bitnami people should have included some documentation on how to run loki with a proper object store. However none exists, and moreover the bitnami-grafana-loki values.yaml doesn't match the [non-bitnami grafana-loki values.yaml](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml).

I would like to use the proper grafana helm repo, but unfortunately I only have access to the bitnami repo. :(

If you could share some sample yaml that I can adapt and put into my values.yaml file, I'd be forever in your debt...

**Comment by phyzical** [comment]
@nesa-david  this is ours, fargate, s3, single binary

so i guess change the s3 stuff with your min.io stuff?

good luck
```
loki:
  storage:
    type: s3
    bucketNames:
      chunks: ${bucket}
      ruler: ${bucket}
    s3:
      region: ${region}
      bucketnames: ${bucket}
  commonConfig:
    # gotta set to tmp dir
    path_prefix: /tmp/loki
    replication_factor: 1
  auth_enabled: false
  limits_config:
    ingestion_rate_mb: 20
    ingestion_burst_size_mb: 30
  compactor:
    apply_retention_interval: 1h
    compaction_interval: 5m
    retention_delete_worker_count: 500
    retention_enabled: true
    shared_store: s3
  schemaConfig:
    configs:
      - from: 2021-05-12
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    boltdb_shipper:
      shared_store: s3
      cache_ttl: 168h
    aws:
      region: ${region}
      bucketnames: ${bucket}
  server:
    http_listen_port: 3100
    grpc_server_max_recv_msg_size: 104857600 # 100 Mb
    grpc_server_max_send_msg_size: 104857600 # 100 Mb
    http_server_write_timeout: 310s
    http_server_read_timeout: 310s
  ingester_client:
    grpc_client_config:
      max_recv_msg_size: 104857600 # 100 Mb
      max_send_msg_size: 104857600 # 100 Mb
  service:
    port: 80
    targetPort: 3100
  url: http://${domain}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
## makes it monolith matching the old stack way
singleBinary:
  replicas: 1
  resources:
    limits:
      cpu: 0.30
      memory: 1.25Gi
    requests:
      cpu: 0.25
      memory: 1.25Gi
  persistence:
    enabled: false
monitoring:
  selfMonitoring:
    enabled: true
  lokiCanary:
    enabled: false
gateway:
  enabled: false
test:
  enabled: false
```
