### ISSUE TITLE
loki-query-frontend report `query filtering for deletes requires 'compactor_address' to be configured`

### ISSUE THREAD

**Issue by Caelebs** [grafana/loki#8030]
Pod startup failed after helm installs `loki-distributed`, The error is `CrashLoopBackOff`, 
The installation command is
```
helm install loki -n logging -f ./minio-values.yaml ./loki-distributed
```

Contents of the minio-values.yaml file

```
loki:
  structuredConfig:
    ingester:
      max_transfer_retries: 0
      chunk_idle_period: 1h
      chunk_target_size: 1536000
      max_chunk_age: 1h
    storage_config:
      aws:
        endpoint: minio.logging.svc.cluster.local:9000
        insecure: true
        bucketnames: loki-data
        access_key_id: HoOM4ZgfwJHJ7ra6
        secret_access_key: i3LwEW7c997YulvpJbh0rWNLNkXgaX9A
        s3forcepathstyle: true
      boltdb_shipper:
        shared_store: s3
    schema_config:
      configs:
        - from: 2022-06-21
          store: boltdb-shipper
          object_store: s3
          schema: v12
          index:
            prefix: loki_index_
            period: 24h
distributor:
  replicas: 1
ingester:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: local
querier:
  replicas: 2
  maxUnavailable: 3
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: local
queryFrontend:
  replicas: 2
  maxUnavailable: 3
gateway:
  nginxConfig:
    httpSnippet: |-
      client_max_body_size 100M;
    serverSnippet: |-
      client_max_body_size 100M;
```

```
kubectl get pods -n logging

NAME                                    READY   STATUS             RESTARTS        AGE
grafana-59956b85f9-g7pwh                1/1     Running            0               5d2h
loki-compactor-786658bc6d-rdlpz         1/1     Running            0               24m
loki-distributor-6b56f76c94-8ntrr       1/1     Running            0               24m
loki-gateway-5bdb7987bd-4f79c           1/1     Running            0               24m
loki-ingester-0                         1/1     Running            0               24m
loki-querier-0                          0/1     CrashLoopBackOff   9 (3m41s ago)   24m
loki-querier-1                          0/1     CrashLoopBackOff   9 (3m28s ago)   24m
loki-query-frontend-5bf4d454fb-7vgdr    0/1     CrashLoopBackOff   9 (3m26s ago)   24m
loki-query-frontend-5bf4d454fb-tm9qs    0/1     CrashLoopBackOff   9 (3m37s ago)   24m
loki-query-scheduler-799698c7b7-4bllv   1/1     Running            0               24m
loki-query-scheduler-799698c7b7-mrk9x   1/1     Running            0               24m
minio-0                                 1/1     Running            0               5d21h
minio-1                                 1/1     Running            0               5d21h
```

The pod query-frontend logs report errors
```
kubectl logs loki-query-frontend-5bf4d454fb-7vgdr -n logging

query filtering for deletes requires 'compactor_address' to be configured
error initialising module: cache-generation-loader
github.com/grafana/dskit/modules.(*Manager).initModule
	/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:122
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
	/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:92
github.com/grafana/loki/pkg/loki.(*Loki).Run
	/src/loki/pkg/loki/loki.go:360
main.main
	/src/loki/cmd/loki/main.go:105
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594
```
How do I need to configure compactor_address? This parameter does not appear to be in the official documentation.

**Comment by Hukha** [comment]
I'm having this same issue where querier and query-frontend are in perma CrashLoopBackOff and with those logs.

Did you fixed it @Caelebs ?

**Comment by kamikaze** [comment]
same here

**Comment by osmirbresciani** [comment]
same here

**Comment by karr1gan** [comment]
same here. any updates?

**Comment by rafawhs** [comment]
Hi! Installing or upgrading to **0.69.0** you have to explicitly set `compactor_address`, as mentioned [here](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed#from-068x-to-0690).

```
loki:
  config: |
    common:
      compactor_address: {{ include "loki.compactorFullname" . }}:3100
```
