### ISSUE TITLE
[helm chart] Ingress points to the wrong service name

### ISSUE THREAD

**Issue by blezoray** [grafana/loki#8032]
Hello,

I use the helm chart 3.8.0 with the following values.yaml
```yaml
ingress:
  enabled: true
  hosts:
    - loki-shared-monitoring.apps.tech.com
```

It generates this ingress:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-loki
  labels:
    helm.sh/chart: loki-3.8.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/version: "2.7.0"
    app.kubernetes.io/managed-by: Helm
    domain: ops
    productname: loki
    accounting: orange-loki
spec:
  rules:
    - host: "loki-shared-monitoring.apps.fr01.paas.tech.orange"
      http:
        paths:
          - path: /api/prom/push
            pathType: Prefix
            backend:
              service:
                name: monitoring-loki
                port:
                  number: 3100
          - path: /loki/api/v1/push
            pathType: Prefix
            backend:
              service:
                name: monitoring-loki
                port:
                  number: 3100
...
```
But the service name is `loki`and not `monitoring-loki`

Could you verify this issue in the ingress or service ?

Rgds.

**Comment by blezoray** [comment]
I think the issue is in the _helpers.tpl file, [here](https://github.com/grafana/loki/blob/main/production/helm/loki/templates/_helpers.tpl#L422).
It should be `loki.name` instead of `loki.fullname`.

```yaml
{{/*
Ingress service name helper function
Params:
  ctx = . context
  svcName = service name without the "loki.fullname" part (ie. read, write)
*/}}
{{- define "loki.ingress.serviceName" -}}
{{- if (eq .svcName "singleBinary") }}
{{- printf "%s" (include "loki.name" .ctx) }}
{{- else }}
{{- printf "%s-%s" (include "loki.name" .ctx) .svcName }}
{{- end -}}
{{- end -}}
```

**Comment by mickutz** [comment]
:sob: 
still an issue!

**Comment by r4j4h** [comment]
still an issue :(

**Comment by r4j4h** [comment]
However, with Flux a postRenderer can be used to get around it:

```

  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              kind: Ingress
              name: dev-loki
            patch:
              - op: replace
                path: /spec/rules/0/http/paths/0/backend/service/name
                value: loki-read
              - op: replace
                path: /spec/rules/0/http/paths/1/backend/service/name
                value: loki-read
              - op: replace
                path: /spec/rules/0/http/paths/2/backend/service/name
                value: loki-read
              - op: replace
                path: /spec/rules/0/http/paths/3/backend/service/name
                value: loki-read
              - op: replace
                path: /spec/rules/0/http/paths/4/backend/service/name
                value: loki-read
              - op: replace
                path: /spec/rules/0/http/paths/5/backend/service/name
                value: loki-read
              - op: replace
                path: /spec/rules/0/http/paths/6/backend/service/name
                value: loki-read
              - op: replace
                path: /spec/rules/0/http/paths/7/backend/service/name
                value: loki-write
              - op: replace
                path: /spec/rules/0/http/paths/8/backend/service/name
                value: loki-write
```
