### ISSUE TITLE
[helm-chart] loki-canary pods cannot connect to loki due to invalid URL

### ISSUE THREAD

**Issue by rychuhardy** [grafana/loki#8046]
**Describe the bug**
Loki-canary pods have incorrect Loki Url configured in the DaemonSet. 
The addr argument is set to `loki-helm.testing.svc.cluster.local.:3100` even though the loki Service name is "loki", which means the addr argument should be set to `loki.testing.svc.cluster.local.:3100`

**To Reproduce**
1. Create the following values.yml
```
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
gateway:
  enabled: false
ingress:
  enabled: false
```
3. Generate kubernetes manifests from the loki helm chart
```
helm template --namespace "testing" --version "3.8.1" --release-name "loki-helm" --repo "https://grafana.github.io/helm-charts" --values "values.yml"  "loki"
```
4. Search for Service "loki". The name is just "loki"
```
# Source: loki/templates/single-binary/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    helm.sh/chart: loki-3.8.1
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki-helm
    app.kubernetes.io/version: "2.7.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
...
```
5. Search for DaemonSet "loki-canary". The "addr" argument is incorrect here since the service name above is loki and not loki-helm.
```
# Source: loki/templates/loki-canary/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: loki-canary
  labels:
    helm.sh/chart: loki-3.8.1
...
      containers:
        - name: loki-canary
          image: docker.io/grafana/loki-canary:2.7.0
          imagePullPolicy: IfNotPresent
          args:
            - -addr=loki-helm.testing.svc.cluster.local.:3100
            - -labelname=pod
            - -labelvalue=$(POD_NAME)
            - -user=self-monitoring
            - -tenant-id=self-monitoring
...
```

**Expected behavior**
loki-canary should have `- -addr=loki.testing.svc.cluster.local.:3100` argument instead of `- -addr=loki-helm.testing.svc.cluster.local.:3100`

The same issue is in the loki-helm LogsInstance 
```
# Source: loki/templates/monitoring/logs-instance.yaml
apiVersion: monitoring.grafana.com/v1alpha1
kind: LogsInstance
...
  clients:
    - url: http://loki-helm.testing.svc.cluster.local:3100/loki/api/v1/push
      externalLabels:
```
The URL should be `loki.testing.svc.cluster.local.:3100`

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: helm
