### ISSUE TITLE
Promtail: possible memory leak

### ISSUE THREAD

**Issue by MiGrandjean** [grafana/loki#8054]
**Describe the bug**
We are seeing a slow but steady increase in memory usage for our Promtail pods. IMHO this looks very typical for a memory leak. Sooner or later we experience OOM kills for Promtail. 

**To Reproduce**
1. Running Loki (2.6.1), deployed on EKS via Helm Chart
2. Running Promtail (2.7.0), deployed on EKS via Helm Chart
3. Running some Pods (Ingress, Prometheus, Grafana, Thanos ... ) on the Node

**Expected behavior**
I would expect memory consumption to be somewhat linear under regular operation. Or, if there are spikes, that the memory is freed after increased demand.

**Environment:**
 - Infrastructure: Kubernetes 1.22 (EKS)
 - Deployment tool: Helm ([official Promtail chart](https://github.com/grafana/helm-charts/tree/main/charts/promtail))

**Screenshots, Promtail config, or terminal output**

![Auswahl_274](https://user-images.githubusercontent.com/8418423/210974404-6da7f499-b6b1-4951-bf72-0717acaab438.png)

We are using the default values of the Helm Chart (with exception of the Loki URL and some podAnnotations and tolerations).

I'm also happy to investigate more on this and e.g. track down what is actually driving the memory consumption, if someone can point me in the right direction how to do this.

**Comment by DylanGuedes** [comment]
Could you share a memory dump? You can do it by:
1. Run promtail with `-server.profiling_enabled`
2. Access `http://localhost:9080/debug/pprof/heap?duration=15s`

**Comment by grandich** [comment]
Also seeing a "leaky" pattern and oom kills across our promtail daemonsets

![image](https://github.com/grafana/loki/assets/1310215/b60a0869-3640-458d-af37-822b1ea5bc8c)

sum by (node) (container_memory_working_set_bytes{job="cadvisor/cadvisor", pod=~"promtail.+",container!=""})

**Comment by grandich** [comment]
We could correlate the leak with extremely long lines or absolutely no line breaks in certain pods logs. We experimented adding line breaks and the leak disappeared. 

Using max_line_size = 0

**Comment by Gakhramanzode** [comment]
> We could correlate the leak with extremely long lines or absolutely no line breaks in certain pods logs. We experimented adding line breaks and the leak disappeared.
> 
> Using max_line_size = 0

hi @grandich . you mean adding this lines ?
```
config:
  snippets:
    extraLimitsConfig: |
      max_line_size: 0
      max_line_size_truncate: true
```

**Comment by Gakhramanzode** [comment]
or can you send example what you mean ? :)

**Comment by grandich** [comment]
> or can you send example what you mean ? :)

I meant we are using v2.5 defaults (no override/config): https://grafana.com/docs/loki/v2.5.x/configuration/#limits_config

max_line_size: 0
max_line_szie_truncate: false

**Comment by grandich** [comment]
This are our promtail pods as today (one week)

sum by (node) (container_memory_working_set_bytes{job="cadvisor/cadvisor", pod=~"promtail.+",container!=""})

![image](https://github.com/grafana/loki/assets/1310215/5898b8af-97be-4e3b-a306-92dff157d48a)

**Comment by Gakhramanzode** [comment]
@grandich thank you! I try again tomorrow fix memory leak))

**Comment by Gakhramanzode** [comment]
@grandich thank you for sharing your insights on the memory consumption issue with promtail. we have implemented your suggestion but decided to set max_line_size to 16384 instead of 0, to ensure better control over the log line size. all changes have been applied, and we will observe the system over the next few days to monitor the memory usage. I appreciate your help!

**Comment by sajithnedunmullage** [comment]
@grandich do you know why setting max_line_size: 0 helped to remove the leak? According to the doc, by setting this we essentially say there's no limit on the log line length. For me it's counter-intuitive.

**Comment by Gakhramanzode** [comment]
@sajithnedunmullage so, I don't understand 😀 I set max_line_size to 16384. It's wrong?))

**Comment by sajithnedunmullage** [comment]
@Gakhramanzode I'm also confused. Seeking for insights and advice :) 

My Promtail pods have been slowly, but steadily increasing their memory consumption for the last 30 days. Trying to find a proper fix for this.

![image](https://github.com/grafana/loki/assets/136712585/3e495c62-39d5-47e3-b4af-a1464e2391a1)

**Comment by Gakhramanzode** [comment]
@sajithnedunmullage I understand you bro 😄 ![image](https://github.com/grafana/loki/assets/62985982/a8687a3e-6b47-45cb-91f1-d5822d1e860a)

**Comment by grandich** [comment]
> @grandich do you know why setting max_line_size: 0 helped to remove the leak? According to the doc, by setting this we essentially say there's no limit on the log line length. For me it's counter-intuitive.

Hi @sajithnedunmullage I didn't said that. In https://github.com/grafana/loki/issues/8054#issuecomment-1888178237 I mentioned that the leak is correlated to the length of the lines. We had lines in the order of ~500KB / ~1MB which produced huge leaks. We introduced line breaks and in certain cases we eliminated such lines, and the leaks improved.

I only mentioned max_line_size as a reference.

In theory, if we set max_line_size to something != 0, the leak should improve, but we didn't test it.

**Comment by Gakhramanzode** [comment]
hello everyone guys 👋
@grandich I think your revision helped us
![Снимок экрана_30-5-2024_83210_grafana citydrive tech](https://github.com/grafana/loki/assets/62985982/105a2b27-1f36-4873-a378-7a258bc7f110)
```yaml
...
# -- Section for crafting Promtails config file. The only directly relevant value is `config.file`
# which is a templated string that references the other values and snippets below this key.
# @default -- See `values.yaml`
config:
...
  # -- A section of reusable snippets that can be reference in `config.file`.
  # Custom snippets may be added in order to reduce redundancy.
  # This is especially helpful when multiple `kubernetes_sd_configs` are use which usually have large parts in common.
  # @default -- See `values.yaml`
  snippets:
...
    # -- You can put here any keys that will be directly added to the config file's 'limits_config' block.
    # @default -- empty
    extraLimitsConfig: |
      max_line_size: 0
      max_line_size_truncate: false
...
```

**Comment by Rohlik** [comment]
This issue should be renamed to "Promtail: memory leak" as it was confirmed that this is really a memory leak.
Also, a fix would be nice 🙏🏼.

**Comment by Gakhramanzode** [comment]
[it's](https://github.com/grafana/loki/issues/8054#issuecomment-2138723721) work 🤔
![image](https://github.com/grafana/loki/assets/62985982/e0b44335-6179-40f3-87da-f0c2fa2a1c02)

**Comment by naveen2112** [comment]
Hi , facing memory leak issue in the promtail.
My Promtail pods have been slowly, but steadily increasing their memory consumption for the last 30 days
kindly provide any solution for that 
![Uploading Screenshot 2024-07-25 at 10.39.13 AM.png…]()

**Comment by naveen2112** [comment]
Hi , facing memory leak issue in the promtail.
My Promtail pods have been slowly, but steadily increasing their memory consumption for the last 30 days
kindly provide any solution for that
<img width="1449" alt="Screenshot 2024-07-25 at 10 39 13 AM" src="https://github.com/user-attachments/assets/594600df-5f02-499b-808d-1bf36f84897b">

**Comment by AniketTendulkar2510** [comment]
Any solution for this issue?
Still facing this for v3.0.0

**Comment by VtG242** [comment]
This is happening even promtail is used only for ingesting logs from journal.![Image](https://github.com/user-attachments/assets/12d80fdb-0e90-432a-95e7-f82050615450)

**Comment by defanator** [comment]
> This is happening even promtail is used only for ingesting logs from journal

We have a few installations of promtail scraping logs from regular files and systemd journal. Historically, these are running separately, each instance with its own config. We noticed that only the ones with journal scraping are consistently leaking, while others (those scraping regular files) doing just fine, e.g.:

![Image](https://github.com/user-attachments/assets/1066397a-6c52-4dbe-b187-4b5351465717)

![Image](https://github.com/user-attachments/assets/bb4ca965-94c2-4b33-84e1-458a616cee4b)

So far we confirmed the leak on v2.8.2 and v3.0.1.

We also tried to migrate from promtail to alloy (for this particular log scrapping task), but alloy was consuming almost 2x more RSS doing exactly the same thing as promtail, so we had to postpone the migration for now.

For this particular workloads we do not use any k8s or containers; promtails are running on regular VMs.

I'd be happy to provide more context if it helps to finally resolve the issue.

**Comment by M4teo** [comment]
Hello
on my side, I had the same mem leak problem but just on few promtail of the daemonset. (helm chart : 6.16.4 with promtail : `3.0.0`)
I've tried some settings under `extraLimitsConfig` without evolution.
Finally, the best thing I've found is to reduce the number of files being tracked. In our context, there is no need to keep every container discovered by kubernetes_sd_configs under watch in Loki. 
As an example, some exclusions (_slightly modified for the post_): 
```
    extraRelabelConfigs:
      - action: drop
        source_labels:
          - namespace
        regex: '(kube-system|kubernetes-dashboard|postgres|observability)'
      - action: drop
        source_labels:
          - pod
        regex: '(loki|promtail|.*botkube|kafka-lag-exporter)-.*'
      - action: drop
        source_labels:
          - container
        regex: "(vault-agent|jaeger-agent|envoy-sidecar)"
```
This workaround fixes our recurring OOM of promtail in various envs. 
![Image](https://github.com/user-attachments/assets/4ada7f47-b091-4c7f-83de-3c2f49db2837)

**Comment by Stogas** [comment]
We observe the same memory leak with the `promtail` Helm Chart `6.16.6` with the following values:
```
    daemonset:
      enabled: true
    deployment:
      enabled: false
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        memory: 128Mi
    serviceMonitor:
      enabled: true
      interval: null
      scrapeTimeout: null
    config:
      logLevel: info
      serverPort: 3101
      clients:
        - url: http://loki-scalable-gateway.loki.svc.cluster.local/loki/api/v1/push
      enableTracing: false
    sidecar:
      configReloader:
        enabled: false
```

30 Days graph:

![Image](https://github.com/user-attachments/assets/9f74ada2-1387-4c6a-83b8-83df9fa3bd1e)
