### ISSUE TITLE
How to create time related labels such as “sec,min,hr,month,year” in the extraScrapeConfigs of promtail configuration deployed in kubernetes eks as demonset

### ISSUE THREAD

**Issue by dkumarkaran** [grafana/loki#8118]
Hi,
I am finding difficult to create the scrape config that can create labels **“sec,min,hr,month,year”**.I am using the helm chart grafana/promtail and trying to add some code in the **extraScrapeConfigs**.
Below is the Code which i implemented on instance, I am not sure how to implement on **kubernetes** to create the following labels “sec,min,hr,month,year” . 

```
scrape_configs:
- job_name: logs
  pipeline_stages:
  #- timestamp:
  #    source: time
  #    format: RFC3339
  - regex:
      expression: ^(?P<timestamp>\[[^\]]*])
  - regex:
      expression: (?P<year>\d{4})-(?P<month>\d{2})-(?P<date>\d{2})\ (?P<hour>\d{2})
      source: “timestamp”
  - labels:
      year:
      month:
      date:
      hour:

```
Please suggest any modifications we may do in the above code to create “sec,min,hr,month,year” labels.
Thanks in Advance.
