### ISSUE TITLE
loki 3.8.1 helm chart : <.Values.ruler.enabled>: nil pointer evaluating interface

### ISSUE THREAD

**Issue by jehutyy** [grafana/loki#8121]
Install grafana/loki chart triggers the following error : 
```
Error: template: loki/templates/networkpolicy.yaml:111:14: executing "loki/templates/networkpolicy.yaml" at <.Values.ruler.enabled>: nil pointer evaluating interface {}.enabled
```

**Command used to install** : 
`helm upgrade --install -n test-logs --create-namespace  -f loki/debug-values.yaml loki-1673534804 grafana/loki --version 3.8.1`

**helm version** : 
`version.BuildInfo{Version:"v3.9.3", GitCommit:"414ff28d4029ae8c8b05d62aa06c7fe3dee2bc58", GitTreeState:"clean", GoVersion:"go1.17.13"}`

**chart version** : 
3.8.1

`values.yaml` :
```
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'

networkPolicy:
  enabled: true
```
