### ISSUE TITLE
promtail: journald/systemd 251>252 seems to break log-scraping 

### ISSUE THREAD

**Issue by DennisGlindhart** [grafana/loki#8163]
**Describe the bug**
After system updated to systemd 252 from 251 (OpenSuSE MicroOS/Tumbleweed in my case) promtail will no longer read journald logs.

```
level=info ts=2023-01-16T09:14:47.958685214Z caller=main.go:171 msg="Starting Promtail" version="(version=2.7.1, branch=HEAD, revision=e0af1cc8a)"
level=warn ts=2023-01-16T09:14:47.958805407Z caller=promtail.go:217 msg="disable watchConfig" reason="promtailServer cast fail"
```

**To Reproduce**
1. System with journald/systemd version 252 or higher
2. Start promtail with following -config.file=promtail.yaml

promtail.yaml config
```
server:
  disable: true

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: https://<lokiserver>/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
     max_age: 12h
     labels:
       job: systemd-journal
      path: /var/log/journal
   relabel_configs:
     - source_labels: ['__journal__systemd_unit']
       target_label: 'unit'
   pipeline_stages:
```

**Expected behavior**
Promtail being able to read jounrnald log and send to Loki

**Environment:**
 - Using promtail image from Dockerhub via podman --privileged -v /var/log/journal:/var/log/journal:ro
- OpenSuSE MicroOS/Tumbleweed

**Screenshots, Promtail config, or terminal output**
I've tried appending -log.level=debug to command, but no extra output is printed.
