### ISSUE TITLE
Config reload with /reload endpoint causes metrics scraping error

### ISSUE THREAD

**Issue by buildsville** [grafana/loki#8174]
**Describe the bug**
If multiple `scrape_config` set and `metrics` is set in `pipeline_stages`, reloading the config with the /reload endpoint will cause an error when scraping /metrics endpoint.

**To Reproduce**
1. Started Promtail 2.7.1 with below

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      containers:
        - name: promtail
          image: grafana/promtail:2.7.1
          args:
            - -config.file=/etc/promtail/promtail.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: tmp
              mountPath: /tmp
        - name: log
          image: busybox
          command:
            - sh
            - -c
            - while true; do echo hello; sleep 1; done >/tmp/hello.log
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: promtail
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
data:
  promtail.yaml: |
    server:
      enable_runtime_reload: true
      http_listen_port: 3101

    client:
      url: http://localhost:3101/

    positions:
      filename: /tmp/positions.yaml

    scrape_configs:
      - job_name: local1
        static_configs:
          - targets: [localhost]
            labels:
              job: local1
              __path__: /tmp/hello.log
        pipeline_stages:
          - metrics:
              debug_metrics:
                type: Counter
                source: job
                config:
                  action: inc

      - job_name: local2
        static_configs:
          - targets: [localhost]
            labels:
              job: local2
              __path__: /tmp/hello.log
        pipeline_stages:
          - metrics:
              debug_metrics:
                type: Counter
                source: job
                config:
                  action: inc
```

2. Modify ConfigMap as below. (Add a label to one of the job)

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
data:
  promtail.yaml: |
    server:
      enable_runtime_reload: true
      http_listen_port: 3101

    client:
      url: http://localhost:3101/

    positions:
      filename: /tmp/positions.yaml

    scrape_configs:
      - job_name: local1
        static_configs:
          - targets: [localhost]
            labels:
              job: local1
              __path__: /tmp/hello.log
        pipeline_stages:
          - metrics:
              debug_metrics:
                type: Counter
                source: job
                config:
                  action: inc

      - job_name: local2
        static_configs:
          - targets: [localhost]
            labels:
              add: add                          #!!! <- add this line !!!# 
              job: local2
              __path__: /tmp/hello.log
        pipeline_stages:
          - metrics:
              debug_metrics:
                type: Counter
                source: job
                config:
                  action: inc
```

3. Access `http://localhost:3101/reload` to reload config.
4. Access `http://localhost:3101/metrics` and get following error.

```
An error has occurred while serving metrics:

collected metric "promtail_custom_debug_metrics" { label:<name:"filename" value:"/tmp/hello.log" > label:<name:"job" value:"local1" > counter:<value:8 > } was collected before with the same name and label values
```

**Expected behavior**
No errors and metrics can be scraped.

**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: [any]
