### ISSUE TITLE
Pb using pipeline_stages

### ISSUE THREAD

**Issue by sbenzakountradelab** [grafana/loki#818]
I am trying to use promtail to label some logs but i have the same error and i don't understand how to handle it.

here is the config.yaml file:

```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/api/prom/push
scrape_configs:
- job_name:  myapp
  static_configs:
  - targets:
      - localhost
    labels:
      app: myapp
      host: myhost
      __path__: /home/user/myapp/logs/*.log
  pipeline_stages:
  - match:
    selector: '{app="myapp"}'
    stages:
    - regex:
        expression: "(?P<level>(INFO|WARNING|ERROR))(.*)"
    - labels:
        level:
```

Then i obtain the following error:

level=error ts=2019-07-30T14:10:54.775552347Z caller=main.go:45 msg="error creating promtail" error="failed to make file target manager: pipeline stage must contain only one key"

When i remove the element pipeline_stages (and its children) it work correctly.

Any suggestion to use pipeline stages to add label (such as level) and parse the log line to have the correct timestamp.

Thank you for your help.

**Comment by slim-bean** [comment]
can you put your config inside a code block (using three backticks)?

That error is generally representative of an indentation problem, yaml is whitespace sensitive.

**Comment by sbenzakountradelab** [comment]
Hi, I just updated the yaml config file, i am not very familiar with yaml.

Thank you for helping me.

**Comment by slim-bean** [comment]
Ok, I can see one issue, the indentation looks wrong to me after `-match`, should be like this:

```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:3100/api/prom/push
scrape_configs:
- job_name:  myapp
  static_configs:
  - targets:
      - localhost
    labels:
      app: myapp
      host: myhost
      __path__: /home/user/myapp/logs/*.log
  pipeline_stages:
  - match:
      selector: '{app="myapp"}'
      stages:
      - regex:
          expression: "(?P<level>(INFO|WARNING|ERROR))(.*)"
      - labels:
          level:
```

See if that works better for you
