### ISSUE TITLE
loki helm-chart 3.10.0 - allow the use of existing volume claim in persistence configuration

### ISSUE THREAD

**Issue by mstavrev** [grafana/loki#8180]
**Is your feature request related to a problem? Please describe.**
On some custom deployment scenarios, it is helpful to reuse an already existing persistent volume claim. One example is a case, where one would like the storage space to outlive the deployment itself if the later needs to be shutdown and recreated later.

**Describe the solution you'd like**
Lots of helm charts allow the use of a named persistent volume claim, usually via a value parameter `existingClaim` under the relevant `persistence` section. If it is defined, it should take precedence over the automatic provisioning.

**Describe alternatives you've considered**
I am not aware of a way to overcome the lack of such feature with the most recent loki helm charts. It used to be possible in older helm chart versions (for example 2.16.0).

**Comment by JWebDev** [comment]
Hi, I also expected a product like Loki to have this. It would be cool, to have this feature in helm chart.
But I found a workaround. At least in the case with a single node.
@mstavrev 
Just create a PVC with name `storage-loki-0`.
When starting, Loki will automatically connect to this stigma.
At least Ceph wit static provisioning worked for me.

**Comment by jaumebalust** [comment]
Did it work? should the issue be closed?

**Comment by mstavrev** [comment]
There is a work-around described on the first comment. I would prefer if it gets an official fix as we are relying on hard coding the name of the pvc, which may change at any moment as the helm devlopment progresses.

**Comment by anand-pradeep** [comment]
Thank you @JWebDev but this work-around didn't worked for me, Keep this thread updated if anyone finds out a way to use existing persistent volume claim (hostpath) in Loki Stack .

**Comment by danilo-lopes** [comment]
Guys, we need persistence settings on Loki helm chart, specially if I want to deploy it on bare metal, using storage class 😐

**Comment by lrdshaper** [comment]
This is what worked for me using local filesystem
using PV and PVC:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/vol/loki"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: monitoring
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce 
  volumeName: loki-pv
  resources: 
    requests:
      storage: 50Gi
```
values.yaml:
```
singleBinary:
  replicas: 1
  persistence:
    enabled: false
  extraVolumeMounts:
    - name: persistent-storage
      mountPath: /var/loki
  extraVolumes:
    - name: persistent-storage
      persistentVolumeClaim:
         claimName: loki-pvc
```
If you want to use hostPath without PV and PVC:
values.yaml
```
singleBinary:
  replicas: 1
  persistence:
    enabled: false
  extraVolumeMounts:
    - name: persistent-hostpath
      mountPath: /var/loki
  extraVolumes:
    - name: persistent-hostpath
      hostPath:
        path: /vol/loki

```
If you set `singleBinary.persistence.enabled` to `true` the charts will create a PVC named storage (which results in `storage-loki-0`) or an emptyDir (if `storageClass` is not defined) and mount it to `/var/loki` which you do not want. So make sure to set it to false.
