### ISSUE TITLE
Helm: provide a way to override metrics cluster label

### ISSUE THREAD

**Issue by nervo** [grafana/loki#8214]
Right now, when using `serviceMonitor`, a cluster label is added https://github.com/grafana/loki/blob/fd3d362e0c4097e9554413faac106b72f671cb57/production/helm/loki/templates/monitoring/servicemonitor.yaml#L43

This is good, as it's a requirement for embedded grafana dashboards.

But the cluster label value is templated as `{{ include "loki.fullname" $ }}` which is often just "loki".

In a multi-cluster environment, we have to distinguish each cluster by a unique name (especially in graphana dashboards), thats why we should be able to set this cluster label value in helm values

Please note that we can temporary use relabeling to achieve the same result:
```yaml
monitoring:
  serviceMonitor:
    relabelings:
      - replacement: my-beautiful-cluster-name
        targetLabel: cluster
```
