### ISSUE TITLE
Config File: field s3forcepathstyle not found in type aws.StorageConfig

### ISSUE THREAD

**Issue by Serrvosky** [grafana/loki#823]
Hello guys,

I'm facing a problem with custom S3 implementation. I'm trying to send logs chunks to Scaleway Object Storage, but whem I start Loki, it sends to stout the following error:
`level=error ts=2019-07-31T13:21:58.6874542Z caller=main.go:46 msg="error loading config" filename=/etc/loki/loki.yaml err="yaml: unmarshal errors:\n  line 40: field s3forcepathstyle not found in type aws.StorageConfig"`

This is my config file:
```
...
schema_config:
  configs:
  - from: 2019-07-15
    index:
      period: 1h
      prefix: index_
    object_store: s3
    schema: v9
    store: boltdb
server:
  http_listen_port: 3100
storage_config:
  boltdb:
    directory: /data/loki/index
  #filesystem:
  #  directory: /data/loki/chunks
  aws:
    s3: s3://API_KEY:SECRET_KEY@http://s3.fr-par.scw.cloud/BUCKET_NAME
    s3forcepathstyle: true
...
```

**Environment:**
 - Infrastructure: [Kubernetes]
 - Deployment tool: [helm]
