### ISSUE TITLE
vector() function produces wrong timestamp on remote write

### ISSUE THREAD

**Issue by mprokopov** [grafana/loki#8240]
**Describe the bug**
If `vector()` function is used to produce a default value for extracted metrics from logs, it's being sent to prometheus using `remote write` with **bad** timestamp. Related to https://github.com/grafana/loki/issues/6946

The major issue it brings, is that Prometheus fully stops accepting any new metrics after this event. The only way to resume Prometheus operations is to stop and completely clear TSDB.

**To Reproduce**
1. Started Loki 2.7.1 with the following config snippet for `ruler`
```
ruler:
  storage:
    type: local
    local:
      directory: /rules
  wal:
    dir: /loki/rules-wal
  rule_path: /tmp/rules
  enable_api: true
  remote_write:
    enabled: true
    client:
      url: http://prometheus.my.internal/api/v1/write

```
2. Started Promtail 2.7.1
3. Started Prometheus with remote write option enabled.
4. Rule: 
    ```logql
    groups: 
    - name: Traefik
      interval: 1m
     rules:
     - record: traefic_count
       expr: |
         sum(count_over_time({namespace="traefik"}[5m]))
         or
         vector(0)
    ```
**Expected behavior**
Exported metrics to prometheus endpoint using `remote write` should use correct timestamp.

**Environment:**
 - Infrastructure: bare-metal with docker
 - Deployment tool: ansible

**Screenshots, Promtail config, or terminal output**
<img width="1617" alt="Screenshot 2023-01-23 at 12 37 08" src="https://user-images.githubusercontent.com/549392/214030382-7abd3ebe-bbfc-4dbd-a22a-0689b24f9a0d.png">
