### ISSUE TITLE
Loki reporting too much errors about querier and scheduler, "context canceled"

### ISSUE THREAD

**Issue by davidrd-es** [grafana/loki#8321]
**Describe the bug**
Loki shows hundreds of errors, reporting connectivity issues on  Querier and Scheduler:

``` bash
2023-01-28 20:14:45 | level=error ts=2023-01-28T19:14:44.943214073Z caller=scheduler_processor.go:137 org_id=fake msg="error notifying scheduler about finished query" err=EOF addr=127.0.0.1:9096

2023-01-28 20:14:45 | level=error ts=2023-01-28T19:14:44.943190233Z caller=scheduler_processor.go:182 org_id=fake msg="error notifying frontend about finished query" err="rpc error: code = Canceled desc = context canceled" frontend=172.18.0.15:9096

level=error ts=2023-01-28T19:36:23.572333721Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"
```

I have tried several configurations from Loki side, but whatever I set as config for Loki, I have these errors are reported, which are creating hundreds of errors per minute. 

I did minimal tests and I can see port 9096 is up and accepting connections:

```
devuser@4302e28a2288:~$ telnet loki 9096
Trying 172.18.0.15...
Connected to loki.
Escape character is '^]'.
```

From Grafana, I can see logs from Loki + Grafana, but I don´t know if any log is missing, or not shown because these errors. 

**To Reproduce**
1. Started Loki (SHA or version): [grafana/loki:2.7.2] deployed as Monolithic mode
2. Grafana [v9.3.2 (21c1d14e91)]
3. Docker Version:  20.10.3

I tried several configuration and checked previous issues, whatever configuration I use, I always find this errors reported by Lokl

Loki config from this issue (https://github.com/grafana/loki/issues/4613#issuecomment-1018367471): + s3 minio config 

``` yaml
target: all
auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3100
  http_server_read_timeout: 60s # allow longer time span queries
  http_server_write_timeout: 60s # allow longer time span queries

  grpc_listen_address: 0.0.0.0
  grpc_listen_port: 9096
  grpc_server_max_recv_msg_size: 33554432 # 32MiB (int bytes), default 4MB
  grpc_server_max_send_msg_size: 33554432 # 32MiB (int bytes), default 4MB
  log_level: info

common:
  path_prefix: /tmp/data/loki
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      region: es-patata-1
      bucketnames: test-logs
      access_key_id: root
      secret_access_key: SuperPassword1
      s3forcepathstyle: true
  # storage:
  #   filesystem:
  #     chunks_directory: /tmp/data/loki/chunks
  #     rules_directory: /tmp/data/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-11-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    shared_store: s3
    active_index_directory: /tmp/data/loki/index
    cache_location: /tmp/data/loki/boltdb-cache
    cache_ttl: 72h   

ingester:
  wal:
    enabled: true
    dir: /tmp/data/loki/wal
  lifecycler:
    final_sleep: 0s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

ingester_client:
  grpc_client_config:
    max_send_msg_size: 33554432 # 32mb, default = 16777216]
    max_recv_msg_size: 33554432

frontend:
  max_outstanding_per_tenant: 2048 # default = 100]
  compress_responses: true # default = false]
  log_queries_longer_than: 20s

frontend_worker:
  grpc_client_config:
    max_send_msg_size: 33554432 # 32MiB, default = 16777216]
    max_recv_msg_size: 33554432

querier:
  max_concurrent: 20

query_scheduler:
  max_outstanding_requests_per_tenant: 2048
  grpc_client_config:
    max_send_msg_size: 33554432 # 32mb, default = 16777216]
    max_recv_msg_size: 33554432

query_range:
  split_queries_by_interval: 0 # 720h # 30d

compactor:
  working_directory: /tmp/data/loki/boltdb-shipper-compactor
  shared_store: s3
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

limits_config:
  retention_period: 91d
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 8 # <float> | default = 4]
  ingestion_burst_size_mb: 16 # <int> | default = 6]
  per_stream_rate_limit: 5MB # <string|int> | default = "3MB"
  per_stream_rate_limit_burst: 15MB # <string|int> | default = "15MB"
  max_query_length: 2165h # <duration> | default = 721h
  max_query_lookback: 90d

ruler:
  storage:
    type: local
    local:
      directory: /tmp/data/loki/rules # volume, directory to scan for rules
  rule_path: /tmp/data/loki/rules-temp # volume, store temporary rule files
  alertmanager_url: http://alertmanager:9093
  enable_alertmanager_v2: true
  #alertmanager_client:
  #  basic_auth_username: "{{ loki_alertmanager_username }}"
  #  basic_auth_password: "{{ loki_alertmanager_password }}"

analytics:
  reporting_enabled: false
```

Also I followed indications from the documentation, but also this config throws these errors:
https://github.com/grafana/loki/issues/7649
https://raw.githubusercontent.com/grafana/loki/v2.7.0/production/docker-compose.yaml

**Expected behavior**

I expect a configuration which doesn´t throw this massive amount of logs, as all these errors indicate Loki is not working properly.

**Environment:**
 - Infrastructure: docker
 - Deployment tool: docker-compose

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

```
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572333721Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
-- | -- | -- | -- | --
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572310831Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572268611Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572244731Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572228431Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572227461Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572211611Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572209881Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572194541Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572191951Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572174761Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572175601Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572157611Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572156511Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572138501Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.572138841Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57212015Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57212016Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57209931Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57210204Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.5720801Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.5720826Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57207587Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57206376Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57205934Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57205271Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57204479Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57204007Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57201794Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57200454Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57199991Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57198614Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57198084Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57197007Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57196704Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57196314Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57196226Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57194973Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57194703Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57194161Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57194288Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57193037Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57192737Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57192479Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled" |  
  |   | 2023-01-28 20:36:23 | level=error ts=2023-01-28T19:36:23.57192525Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="context canceled"

``

**Comment by patsevanton** [comment]
Same issue. Log:
```
loki-loki-distributed-querier-8bd745798-s425n querier level=error ts=2023-01-31T07:04:03.431136546Z caller=scheduler_processor.go:85 msg="error contacting scheduler" err="rpc error: code = Canceled desc = context canceled" addr=10.236.167.152:9095
loki-loki-distributed-querier-8bd745798-b2nk8 querier level=error ts=2023-01-31T07:04:03.62108248Z caller=scheduler_processor.go:85 msg="error contacting scheduler" err="rpc error: code = Canceled desc = context canceled" addr=10.236.167.50:9095
loki-loki-distributed-querier-8bd745798-6v5kf querier level=error ts=2023-01-31T07:04:03.427881386Z caller=scheduler_processor.go:85 msg="error contacting scheduler" err="rpc error: code = Canceled desc = context canceled" addr=10.236.167.152:9095
loki-loki-distributed-querier-8bd745798-jdtjq querier level=error ts=2023-01-31T07:04:03.738155854Z caller=scheduler_processor.go:85 msg="error contacting scheduler" err="rpc error: code = Canceled desc = context canceled" addr=10.236.167.152:9095
loki-loki-distributed-querier-8bd745798-lg6qq querier level=error ts=2023-01-31T07:04:03.918315138Z caller=scheduler_processor.go:85 msg="error contacting scheduler" err="rpc error: code = Canceled desc = context canceled" addr=10.236.167.50:9095
loki-loki-distributed-querier-8bd745798-lg6qq querier level=error ts=2023-01-31T07:04:03.918311136Z caller=scheduler_processor.go:85 msg="error contacting scheduler" err="rpc error: code = Canceled desc = context canceled" addr=10.236.167.50:9095
loki-loki-distributed-querier-8bd745798-x6h78 querier level=error ts=2023-01-31T07:04:03.831029896Z caller=scheduler_processor.go:85 msg="error contacting scheduler" err="rpc error: code = Canceled desc = context canceled" addr=10.236.167.152:9095
```

Config:
```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 336h
common:
  compactor_address: http://loki-loki-distributed-compactor:3100
compactor:
  compaction_interval: 10m
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  retention_enabled: true
  shared_store: s3
distributor:
  ring:
    kvstore:
      store: memberlist
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  scheduler_address: loki-loki-distributed-query-scheduler:9095
  tail_proxy_url: http://loki-loki-distributed-querier:3100
frontend_worker:
  scheduler_address: loki-loki-distributed-query-scheduler:9095
ingester:
  autoforget_unhealthy: true
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_idle_period: 1h
  chunk_retain_period: 20m
  chunk_target_size: 1536000
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
  max_chunk_age: 1h
  max_transfer_retries: 0
  wal:
    dir: /var/loki/wal
limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: 1000
  ingestion_rate_mb: 10000
  max_cache_freshness_per_query: 10m
  max_global_streams_per_user: 10000
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 336h
  split_queries_by_interval: 24h
memberlist:
  join_members:
  - loki-loki-distributed-memberlist
querier:
  engine:
    timeout: 600s
  query_timeout: 600s
query_range:
  align_queries_with_step: true
  cache_results: true
  max_retries: 5
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        ttl: 24h
ruler:
  alertmanager_url: https://alertmanager.xx
  external_url: https://alertmanager.xx
  ring:
    kvstore:
      store: memberlist
  rule_path: /tmp/loki/scratch
  storage:
    local:
      directory: /etc/loki/rules
    type: local
runtime_config:
  file: /var/loki-distributed-runtime/runtime.yaml
schema_config:
  configs:
  - from: "2020-09-07"
    index:
      period: 24h
      prefix: loki_index_
    object_store: s3
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
  http_server_read_timeout: 610s
  http_server_write_timeout: 610s
storage_config:
  aws:
    bucketnames: magnit-core-dev-loki
    s3: https://xxxxx:xxxxxx@storage.cloud.net/
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    cache_ttl: 168h
    index_gateway_client:
      server_address: dns:///loki-loki-distributed-index-gateway:9095
    shared_store: s3
  filesystem:
    directory: /var/loki/chunks
  index_queries_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: loki-loki-distributed-memcached-index-queries
      service: memcached-client
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
```

**Comment by robertscherbarth** [comment]
I have the same issue.

**Comment by lycheese** [comment]
Not sure if it is exactly the same problem but I stumbled on a similar error today and moving `instance_addr` from `common.ring` to `common` (#6106) fixed it for me. I see that you also have it under `common.ring` in your config so maybe that is worth a try? @davidrd-es

**Comment by robertscherbarth** [comment]
We tried this out you approach @lycheese but that didn't work for us. 

**Versions:**
- Started Loki (SHA or version): [grafana/loki:2.7.2] deployed as Simple Scalable Mode
- Grafana [v9.3.6 (21c1d14e91)]

**Config** 
```
common:
  ring:
    kvstore:
      store: memberlist
  instance_addr: ""
chunk_store_config:
  max_look_back_period: "0s"
compactor:
  shared_store: "filesystem"
  working_directory: "/var/lib/loki/boltdb-shipper-compactor"
distributor:
  ring:
    kvstore:
      store: memberlist
frontend:
  log_queries_longer_than: 5s
  downstream_url: ""
  compress_responses: true
  max_outstanding_per_tenant: 10000
frontend_worker:
  frontend_address: ""
  scheduler_address: ""
query_scheduler:
  max_outstanding_requests_per_tenant: 10000
```
