### ISSUE TITLE
use kubernetes_sd_config with role node cannot work

### ISSUE THREAD

**Issue by TOTom** [grafana/loki#8322]
**Describe the bug**
i use kubernetes_sd_config   to discover node , and then collect kubelet log to loki, but it doesnot work. the configure is refered from https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus-kubernetes.yml.  but promtail cannot start with the field tls_config.

here is the scrape_config of promtail:
```
scrape_configs:
  # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
  - job_name: kubernetes-pods
    pipeline_stages:
      - cri: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels:
          - __meta_kubernetes_pod_controller_name
        regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
        action: replace
        target_label: __tmp_controller_name
    .
    .
    .
  # Scrape config for nodes (kubelet).
  - job_name: "kubernetes-nodes"
    kubernetes_sd_configs:
      - role: node

    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true

    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
```

next is the error log of promtail:
Unable to parse config: /etc/promtail/promtail.yaml: yaml: unmarshal errors:
  line 90: field tls_config not found in type scrapeconfig.plain

**Environment:**
 - Infrastructure:  Kubernetes:1.20.6
 - Deployment tool: helm 
 - promtail:2.7.0
 - loki:2.6.1
