### ISSUE TITLE
Loki labels are not loading intermittently

### ISSUE THREAD

**Issue by chavan-suraj** [grafana/loki#8330]
I have deployed Loki 2.7.1 with loki-distributed helm chart. We are using 3 ingesters, 5 queriers, 1 query-frontend, 3 distributor, 1 compactor, 3 memcached, 3 distributor. Below is the config,

```
auth_enabled: false
chunk_store_config:
  chunk_cache_config:
    embedded_cache:
      enabled: false
    memcached:
      batch_size: 100
      expiration: 30m
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: loki-integration-loki-distributed-memcached-chunks
      service: memcached-client
  max_look_back_period: 0s
  write_dedupe_cache_config:
    memcached:
      batch_size: 100
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: loki-integration-loki-distributed-mcd-indx-wr
      service: memcached-client
common:
  compactor_address: http://loki-integration-loki-distributed-compactor:3100
compactor:
  compaction_interval: 10m
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  retention_enabled: true
  shared_store: s3
  working_directory: /var/loki/compactor
distributor:
  ring:
    kvstore:
      store: memberlist
frontend:
  compress_responses: true
  log_queries_longer_than: 5s
  tail_proxy_url: http://loki-integration-loki-distributed-querier:3100
frontend_worker:
  frontend_address: loki-integration-loki-distributed-query-frontend:9095
  grpc_client_config:
    max_recv_msg_size: 128000000
    max_send_msg_size: 128000000
  parallelism: 12
ingester:
  autoforget_unhealthy: true
  chunk_block_size: 262144
  chunk_encoding: snappy
  chunk_idle_period: 2m
  chunk_retain_period: 1m
  chunk_target_size: 2572864
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 2
  max_chunk_age: 2m
  max_transfer_retries: 0
  wal:
    dir: /var/loki/wal
    enabled: false
ingester_client:
  grpc_client_config:
    max_recv_msg_size: 128000000
    max_send_msg_size: 128000000
limits_config:
  enforce_metric_name: false
  ingestion_burst_size_mb: 24
  ingestion_rate_mb: 15
  ingestion_rate_strategy: local
  max_cache_freshness_per_query: 10m
  max_global_streams_per_user: 1000000
  max_query_length: 12000h
  max_query_parallelism: 256
  max_streams_per_user: 1000000
  query_timeout: 15m
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 744h
  split_queries_by_interval: 15m
memberlist:
  join_members:
  - loki-integration-loki-distributed-memberlist
querier:
  engine:
    timeout: 10m
  max_concurrent: 12
query_range:
  align_queries_with_step: true
  cache_results: true
  max_retries: 5
  results_cache:
    cache:
      memcached_client:
        consistent_hash: true
        host: loki-integration-loki-distributed-memcached-frontend
        max_idle_conns: 16
        service: memcached-client
        timeout: 500ms
        update_interval: 1m
ruler:
  alertmanager_url: https://alertmanager.xx
  external_url: https://alertmanager.xx
  ring:
    kvstore:
      store: memberlist
  rule_path: /tmp/loki/scratch
  storage:
    local:
      directory: /etc/loki/rules
    type: local
runtime_config:
  file: /var/loki-distributed-runtime/runtime.yaml
schema_config:
  configs:
  - from: "2020-09-07"
    index:
      period: 24h
      prefix: loki_index_
    object_store: aws
    schema: v11
    store: boltdb-shipper
  - from: "2023-01-12"
    index:
      period: 24h
      prefix: loki_index_
    object_store: s3
    schema: v12
    store: boltdb-shipper
server:
  grpc_server_max_recv_msg_size: 128000000
  grpc_server_max_send_msg_size: 128000000
  http_listen_port: 3100
  http_server_idle_timeout: 300s
  http_server_read_timeout: 10m
  http_server_write_timeout: 10m
storage_config:
  aws:
    bucketnames: mt-grafana-loki-integration
    http_config:
      response_header_timeout: 5s
    s3: s3://ap-south-1
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/cache
    cache_ttl: 24h
    index_gateway_client:
      server_address: dns:///loki-integration-loki-distributed-index-gateway:9095
    shared_store: s3
  index_queries_cache_config:
    memcached:
      batch_size: 100
      expiration: 15m
      parallelism: 100
    memcached_client:
      consistent_hash: true
      host: loki-integration-loki-distributed-mcd-indx-qrs
      service: memcached-client
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s
```

Grafana version - 9.3.0. Loki fails to load labels most of the times even with timeout value of 250.

<img width="1759" alt="Screenshot 2023-01-30 at 3 50 05 PM" src="https://user-images.githubusercontent.com/81158660/215452227-3504fa8d-ca45-4921-ada8-492e6dbc26f2.png">

Getting below error in querier logs -
`level=warn ts=2023-01-31T06:22:35.637634621Z caller=logging.go:86 traceID=529678ac2245659c orgID=fake msg="GET /loki/api/v1/labels?end=1675146125339000000&start=1675145525339000000 (500) 29.99586118s Response: \"rpc error: code = Canceled desc = context canceled\\n\" ws: false; X-Scope-Orgid: fake; uber-trace-id: 529678ac2245659c:157dd8f813f3dd51:1aa811744b3c8454:0; "
level=error ts=2023-01-31T06:22:35.637729436Z caller=frontend_processor.go:145 msg="error processing requests" err=EOF`

It works when tried with logcli as well, however it takes too much of time(~3mins)  -> `logcli labels --since=1h --stats  0.04s user 0.04s system 0% cpu 2:46.51 total`

Need help to improve the performance of loading labels.
