### ISSUE TITLE
Promtail: replace stage can`t replace GUID

### ISSUE THREAD

**Issue by MiroslavMikus** [grafana/loki#8344]
**Describe the bug**

Promtail pipeline stage `replace`, can`t replace guid.

**To Reproduce**
1. Started Loki (SHA or version): 2.6.1
2. Started Promtail (SHA or version) to tail '...': 2.7.1
3. Capture log with Promtail:
``` json
{"ClientHost":"10.0.0.239","DownstreamContentSize":10,"DownstreamStatus":404,"Duration":641237,"OriginStatus":404,"RequestAddr":"httpbin.development.systems","RequestMethod":"GET","RequestPath":"/here/2479a99a-ad75-4475-bb36-63d02eabd608","RequestProtocol":"HTTP/1.1","RequestScheme":"https","RouterName":"test-httpbin-ingress-httpbin-development@kubernetes","ServiceName":"test-httpbin-80@kubernetes","StartUTC":"2023-01-31T06:17:49.006784813Z","TLSVersion":"1.3","level":"info","msg":"","time":"2023-01-31T06:17:49Z"}
```

**Expected behavior**
I have pipeline stage: 
``` yml
- regex: # this will cut off the query (from `/here?we=are` to `/here`)
      expression: (?P<Path>(/[A-Za-z0-9]+)+)
      source: RequestPath
- replace:
      expression: ([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12})
      replace: xxxx
      source: Path
```
I expect, that if the key `RequestPath` contains any guid, it will be transformed in to `xxxx`
Example data:
Input: `/here/2479a99a-ad75-4475-bb36-63d02eabd608`
Expected: `/here/xxxx`

I get this instead:
![image](https://user-images.githubusercontent.com/29312172/215684864-a9b3c0c5-b858-4b67-9bfb-26f78efe810d.png)

In my own words: 
- the regex can the guid
- replace block does not apply
- it looks like the first `-` char will be found, and the result will just cut off from this place

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]: Kubernetes on Azure
 - Deployment tool: [e.g., helm, jsonnet]: Helm
``` yml
dependencies:
- name: loki
  repository: https://grafana.github.io/helm-charts
  version: 2.16.0
- name: promtail
  repository: https://grafana.github.io/helm-charts
  version: 6.8.1
- name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.48.2
- name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 15.5.4
```
**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
I have for you the promtail config in `yml`
``` yml
promtail:
    config:
        snippets:
            pipelineStages:
                - cri: {}
                - json:
                      expressions:
                          DownstreamStatus: DownstreamStatus
                          RequestAddr: RequestAddr
                          RequestMethod: RequestMethod
                          RequestPath: RequestPath
                - regex:
                      expression: (?P<Path>(/[A-Za-z0-9]+)+)
                      source: RequestPath
                - replace:
                      expression: ([a-fA-F0-9]{8}-[a-fA-F0-9]{4}-4[a-fA-F0-9]{3}-[8|9|aA|bB][a-fA-F0-9]{3}-[a-fA-F0-9]{12})
                      replace: xxxx
                      source: Path
                - labels:
                      Path: null
                      DownstreamStatus: null
                      RequestAddr: null
                      RequestMethod: null
```

Did I miss something? 

Thanks upfront!
