### ISSUE TITLE
verify-config does not work as expected

### ISSUE THREAD

**Issue by bodsch** [grafana/loki#8346]
**Describe the bug**
I create a minimal configuration via Ansible and validate it before starting the service.
The call `loki -log.level debug -verify-config -config.file /etc/loki/loki.yml` ends with an exit code 1.
There is no indication what is wrong with the configuration.

**To Reproduce**
```
# cat /etc/loki/loki.yml

target: all

auth_enabled: false
server:
  graceful_shutdown_timeout: 2m
  grpc_server_max_recv_msg_size: 8388608
  grpc_server_max_send_msg_size: 8388608
  http_listen_address: 127.0.0.1
  http_listen_port: 3100
  http_server_idle_timeout: 10m
  http_server_read_timeout: 10m
  http_server_write_timeout: 10m
  log_level: debug

# loki -log.level debug   -verify-config -config.file /etc/loki/loki.yml ; echo $?
1
```

**Expected behavior**
What is expected is a hint about missing or wrong configuration entries.

**Environment:**
- Infrastructure: base metal
- Deployment tool: ansible
- loki version: 2.7.2
