### ISSUE TITLE
Logs retention doesn't work

### ISSUE THREAD

**Issue by fpaparoni** [grafana/loki#8357]
**Describe the bug**
Using a custom configuration I think the logs should be deleted after 1h, but they are always available

**To Reproduce**
I used the following configuration values for loki helm chart

```
loki:
  config:
    limits_config:
      retention_period: 1h
    compactor:
      retention_enabled: true
      retention_delete_delay: 1h
    table_manager:
      retention_deletes_enabled: true
      retention_period: 1h
```
launched the creation using the following command

`helm install loki grafana/loki-stack --values loki-stack-values.yaml -n loki --create-namespace`

and if I enter into the loki pod I can see the following configuration from /etc/loki/loki.yaml

```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0s
compactor:
  retention_delete_delay: 1h
  retention_enabled: true
  shared_store: filesystem
  working_directory: /data/loki/boltdb-shipper-compactor
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      replication_factor: 1
  max_transfer_retries: 0
  wal:
    dir: /data/loki/wal
limits_config:
  enforce_metric_name: false
  max_entries_limit_per_query: 5000
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 1h
memberlist:
  join_members:
  - 'loki-memberlist'
schema_config:
  configs:
  - from: "2020-10-24"
    index:
      period: 24h
      prefix: index_
    object_store: filesystem
    schema: v11
    store: boltdb-shipper
server:
  grpc_listen_port: 9095
  http_listen_port: 3100
storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: true
  retention_period: 1h
```

**Expected behavior**
After one hour logs should be deleted, but the retention doesn't work (of course there is something in the configuration that is wrong)

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
