### ISSUE TITLE
Unavailable desc = name resolver error: produced zero addresses

### ISSUE THREAD

**Issue by patsevanton** [grafana/loki#8361]
**Describe the bug**
```
loki-loki-distributed-querier-668f5f9954-vq8vh querier level=warn ts=2023-02-01T00:39:22.03008595Z caller=logging.go:86 traceID=5612ff99f8d6cf85 orgID=fake msg="GET /loki/api/v1/labels?end=1675211962001000000&start=1675211362001000000 (500) 381.309µs Response: \"rpc error: code = Unavailable desc = name resolver error: produced zero addresses\\n\" ws: false; X-Query-Queue-Time: 92.883µs; X-Scope-Orgid: fake; uber-trace-id: 5612ff99f8d6cf85:1a2ea48e787d98d6:0654888a630c93e8:0; "

loki-loki-distributed-query-frontend-64944df784-7vtsh query-frontend level=error ts=2023-02-01T00:39:22.025418368Z caller=retry.go:73 org_id=fake msg="error processing request" try=0 err="rpc error: code = Code(500) desc = rpc error: code = Unavailable desc = name resolver error: produced zero addresses\n"
```

**To Reproduce**
1. Started Loki: 2.7.1
3. Query: `{} term` ??

**Expected behavior**
Connect and work loki datasource in grafana

**Environment:**
 - Infrastructure: Kubernetes - Deployment tool: helm

**Loki config**

```
compactor:
  enabled: true
  persistence:
    enabled: true
    storageClass: yc-network-ssd
  resources:
    limits:
      cpu: 200m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 256Mi
distributor:
  autoscaling:
    enabled: true
    maxReplicas: 4
    minReplicas: 2
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 80
  maxUnavailable: 1
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
gateway:
  enabled: false
global:
  image:
    registry: harbor.corp/dockerhub
indexGateway:
  enabled: true
  maxUnavailable: 1
  persistence:
    enabled: true
    storageClass: yc-network-ssd
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
ingester:
  affinity: {}
  autoscaling:
    enabled: true
    maxReplicas: 12
    minReplicas: 5
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 80
  maxUnavailable: 1
  persistence:
    enabled: true
    storageClass: yc-network-ssd
  resources:
    limits:
      cpu: 600m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 1512Mi
ingress:
  annotations:
    nginx.ingress.kubernetes.io/client-body-timeout: "610"
    nginx.ingress.kubernetes.io/client-header-timeout: "610"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "610"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "610"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "610"
  enabled: true
  hosts:
  - loki-k8s.corp
  ingressClassName: nginx
  paths:
    distributor:
    - /api/prom/push
    - /loki/api/v1/push
    querier:
    - /api/prom/tail
    - /loki/api/v1/tail
    query-frontend:
    - /loki/api
    ruler:
    - /api/prom/rules
    - /loki/api/v1/rules
    - /prometheus/api/v1/rules
    - /prometheus/api/v1/alerts
loki:
  config: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      http_server_read_timeout: 610s
      http_server_write_timeout: 610s
    common:
      compactor_address: http://{{ include "loki.compactorFullname" . }}:3100
    distributor:
      ring:
        kvstore:
          store: memberlist
    memberlist:
      join_members:
        - {{ include "loki.fullname" . }}-memberlist
    ingester:
      autoforget_unhealthy: true
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_retain_period: 20m
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal
    limits_config:
      ingestion_rate_mb: 10000
      ingestion_burst_size_mb: 1000
      max_global_streams_per_user: 10000
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 24h
      retention_period: 240h
    {{- if .Values.loki.schemaConfig}}
    schema_config:
    {{- toYaml .Values.loki.schemaConfig | nindent 2}}
    {{- end}}
    {{- if .Values.loki.storageConfig}}
    storage_config:
    {{- if .Values.indexGateway.enabled}}
    {{- $indexGatewayClient := dict "server_address" (printf "dns:///%s:9095" (include "loki.indexGatewayFullname" .)) }}
    {{- $_ := set .Values.loki.storageConfig.boltdb_shipper "index_gateway_client" $indexGatewayClient }}
    {{- end}}
    {{- toYaml .Values.loki.storageConfig | nindent 2}}
    {{- if .Values.memcachedIndexQueries.enabled }}
      index_queries_cache_config:
        memcached:
          batch_size: 100
          parallelism: 100
        memcached_client:
          consistent_hash: true
          host: {{ include "loki.memcachedIndexQueriesFullname" . }}
          service: memcached-client
    {{- end}}
    {{- end}}

    runtime_config:
      file: /var/{{ include "loki.name" . }}-runtime/runtime.yaml
    chunk_store_config:
      max_look_back_period: 240h
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
    querier:
      query_timeout: 600s
      engine:
        timeout: 600s
    query_range:
      align_queries_with_step: true
      max_retries: 5
      cache_results: true
      results_cache:
        cache:
          {{- if .Values.memcachedFrontend.enabled }}
          memcached_client:
            consistent_hash: true
            host: {{ include "loki.memcachedFrontendFullname" . }}
            max_idle_conns: 16
            service: memcached-client
            timeout: 500ms
            update_interval: 1m
          {{- else }}
          embedded_cache:
            enabled: true
            ttl: 24h
          {{- end }}
    frontend_worker:
      {{- if .Values.queryScheduler.enabled }}
      scheduler_address: {{ include "loki.querySchedulerFullname" . }}:9095
      {{- else }}
      frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
      {{- end }}
    frontend:
      log_queries_longer_than: 5s
      compress_responses: true
      {{- if .Values.queryScheduler.enabled }}
      scheduler_address: {{ include "loki.querySchedulerFullname" . }}:9095
      {{- end }}
      tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100
    compactor:
      shared_store: s3
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    ruler:
      storage:
        type: local
        local:
          directory: /etc/loki/rules
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      alertmanager_url: https://alertmanager.xx
      external_url: https://alertmanager.xx
  structuredConfig:
    ingester:
      chunk_idle_period: 1h
      chunk_target_size: 1536000
      max_chunk_age: 2h
      max_transfer_retries: 0
    schema_config:
      configs:
      - from: "2020-09-07"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v11
        store: boltdb-shipper
      - from: "2023-02-01"
        index:
          period: 24h
          prefix: tsdb_index_
        object_store: s3
        schema: v12
        store: tsdb
    storage_config:
      aws:
        bucketnames: core-dev-loki
        s3: https://xxxxxxxxx@storage.cloud.net/
      boltdb_shipper:
        cache_ttl: 168h
        shared_store: s3
      tsdb_shipper:
        active_index_directory: /var/loki/tsdb-index
        cache_location: /var/loki/tsdb-cache
        index_gateway_client:
          server_address: dns:///index-gateway:9095
        query_ready_num_days: 7
        shared_store: s3
memcached:
  image:
    repository: library/memcached
memcachedIndexQueries:
  enabled: true
  maxUnavailable: 1
  replicas: 3
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
querier:
  autoscaling:
    enabled: true
    maxReplicas: 20
    minReplicas: 6
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 80
  maxUnavailable: 1
  resources:
    limits:
      cpu: 2000m
      memory: 3096Mi
    requests:
      cpu: 200m
      memory: 3096Mi
queryFrontend:
  affinity: {}
  autoscaling:
    enabled: true
    maxReplicas: 6
    minReplicas: 3
    targetCPUUtilizationPercentage: 60
    targetMemoryUtilizationPercentage: 80
  extraArgs:
  - -log.level=debug
  maxUnavailable: 1
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 256Mi
queryScheduler:
  enabled: true
serviceMonitor:
  annotations:
    prometheus.io/port: "3100"
    prometheus.io/scrape: "true"
  enabled: true
  labels:
    release: prometheus-operator
```
