### ISSUE TITLE
Helm: Missing `enterprise-logs-provisioned-self-monitoring` secret breaks self-monitoring 

### ISSUE THREAD

**Issue by basvdl** [grafana/loki#8365]
**Describe the bug**
In my scenario I configured Grafana cloud as my logsInstance client.

If you checked the loginstance deployed, you can see 2 clients:

```
spec:
  clients:
  - basicAuth:
      password:
        key: password
        name: enterprise-logs-provisioned-self-monitoring
      username:
        key: username
        name: enterprise-logs-provisioned-self-monitoring
    externalLabels:
      cluster: gel-lab-enterprise-logs
    url: http://enterprise-logs-gateway.loki.svc.cluster.local/loki/api/v1/push
  - basicAuth:
      password:
        key: password
        name: primary-credentials-logs
      username:
        key: username
        name: primary-credentials-logs
    url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
```

But if you do not deploy a secret called `enterprise-logs-provisioned-self-monitoring`, the agents for collecting logs will not be started. Basically the daemonset will not be created because of the missing secret.

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy GEL using the Helm chart 4.4.1
2. Setup meta-monitoring like this:
```
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
    alerting: false
  serviceMonitor:
    enabled: true
    metricsInstance:
      enabled: true
      remoteWrite:
      - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
        basicAuth:
          username:
            name: primary-credentials-metrics
            key: username
          password:
            name: primary-credentials-metrics
            key: password
  selfMonitoring:
    enabled: true
    grafanaAgent:
      installOperator: true
    logsInstance:
      clients:
      - url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
        basicAuth:
          username:
            name: primary-credentials-logs
            key: username
          password:
            name: primary-credentials-logs
            key: password
```
3. Do not create the secret `enterprise-logs-provisioned-self-monitoring`
4. Create the secret `primary-credentials-logs`
```
apiVersion: v1
kind: Secret
metadata:
  name: primary-credentials-logs
  namespace: loki
stringData:
  username: "***"
  password: "***"
```
5. Deploy and check for the missing daemonset or the loginstance including 2 clients
6. Create a secret `enterprise-logs-provisioned-self-monitoring`
```
apiVersion: v1
kind: Secret
metadata:
  name: enterprise-logs-provisioned-self-monitoring
  namespace: loki
stringData:
  username: "***"
  password: "***"
```
7. Check that the daemonset is created, pod are running and log is flowing into the local and cloud Loki cluster.

**Expected behaviour**
If you do not configure sending data to your local cluster, the client should not be added to the loginstance.

**Environment:**
 - Kubernetes
 - Helm
