### ISSUE TITLE
A Docker service discovery to Promtail

### ISSUE THREAD

**Issue by Bamboer** [grafana/loki#8388]
Hi there,
I got the problem when using docker_sd_configs model .
**Promtail configuration**
```
scrape_configs:
- job_name: docker
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
      filters:
        - name: expose
          values: ["9080/TCP"]
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
  pipeline_stages:
  - docker: {}

```
**The Promtail dashboard**
![image](https://user-images.githubusercontent.com/57797847/216337196-01003dfc-7b9f-41ca-8bed-6a49dd614f9d.png)

I will get all containers info if drop the filters option. but I coudn't got the container log file path in the Promtail dashboard ,even if   configure the  __path__  label  in the  relabel_configs model. 
```
    - source_labels: ['__meta_docker_container_id']
      replacement: /var/lib/docker/containers/$1/*.log
      target_label: __path__
```
The other problem is seems that  the relabel_configs is not work with docker_sd_configs. I have tried
 the latest version:  grafana/promtail:main-8fd956e  grafana/promtail:2.6.1

**The Promtail stdout**
![image](https://user-images.githubusercontent.com/57797847/216343377-d55a2b81-e703-4953-bb47-d5dc9588fd74.png)

**Promtail deploy file**
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: promtail
    app.kubernetes.io/version: "1.0"
    helm.sh/chart: base-0.2.0
  name: promtail
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: promtail
      app.kubernetes.io/name: promtail
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: promtail
        app.kubernetes.io/name: promtail
    spec:
      containers:
      - args:
        - -config.file=/etc/promtail/promtail.yml
        - -print-config-stderr
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: grafana/promtail:main-8fd956e 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
          hostPort: 9080
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/promtail/promtail.yml
          name: promtail-config
          readOnly: true
        - mountPath: /var/lib/docker
          name: log
          readOnly: true
        - mountPath: /tmp
          name: tmpdir
        - mountPath: /var/run/docker.sock
          name: sock
          readOnly: true
      hostNetwork: true
      serviceAccount: promtail-monitoring
      serviceAccountName: promtail-monitoring
      volumes:
      - hostPath:
          path: /etc/promtail/promtail.yml
        name: promtail-config
      - hostPath:
          path: /var/lib/docker
        name: log
      - hostPath:
          path: /var/run/docker.sock
        name: sock
      - hostPath:
          path: /tmp
        name: tmpdir

```

**Comment by jeschkies** [comment]
Does it work if you don't relabel anything?

**Comment by Bamboer** [comment]
> Does it work if you don't relabel anything?

No. I can't found Promtail sent log data to Loki about container log in the Promtail log.

**Comment by Bamboer** [comment]
> Does it work if you don't relabel anything?

Hi jeschkies, Could you  please confirm whether this problem exists？

**Comment by jeschkies** [comment]
@Bamboer unfortunately it's not a known problem for me. Could you enable debug logs and check them for errors? Also, I wonder if promtail can connect to the Docker socket.

**Comment by Bamboer** [comment]
> @Bamboer unfortunately it's not a known problem for me. Could you enable debug logs and check them for errors? Also, I wonder if promtail can connect to the Docker socket.

hi jeschkies, I get the specific container data when move the  dockerSDconfigs field to  ServiceDiscoveryConfig .
![image](https://user-images.githubusercontent.com/57797847/218290937-a5c39189-0143-48f6-ab06-e81e28407028.png)
![image](https://user-images.githubusercontent.com/57797847/218290986-39d34480-4a7b-4739-bf26-582931d271f6.png)

**Comment by jeschkies** [comment]
What does our Promtail config look like?

**Comment by Bamboer** [comment]
> What does our Promtail config look like?

```
scrape_configs:
- job_name: node-exporter
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 30s
  pipeline_stages:
  - docker: {}
  relabel_configs:
  - source_labels: [__meta_docker_container_id]
    target_label: container
  - source_labels: [__meta_docker_container_id, __meta_docker_container_id]
    separator: /
    target_label: __path__
    replacement: /var/lib/docker/containers/$1-json.log
    action: replace
  - source_labels: [__meta_docker_container_label_io_kubernetes_pod_name]
    regex: node-exporter.*
    action: keep
```
