### ISSUE TITLE
Loki starting issue with legacy-read-mode parameter

### ISSUE THREAD

**Issue by gdubroeucq** [grafana/loki#8407]
**Describe the bug**
The _legacy-read-mode_ parameter affects the startup of some Loki components when starting in scaling mode (with helm)
When I run loki on Kubernetes, I encounter this error:

```
flag provided but not defined: -legacy-read-mode
Run with -help to get list of available parameters
```

I can reproduce the issue in local if I add the _legacy-read-mode_ parameter as well.

This is annoying because the loki helm chart adds the legacy-read-mode parameter in multiple loki components.

Affected components:
> - loki-read
> - loki-backend

I am astonished that I am the first to see this issue, the bug look like added by the following commit since December 2022:
https://github.com/grafana/loki/commit/f5fbfabd8445b5f027d0da896bfa44c66829d705

**To Reproduce**
helm charts 4.4.2
loki 2.7.3

**Expected behavior**
Each loki components (reader, writer, backend, ...) run.

**Environment:**
 - Infrastructure: kubernetes and laptop
 - Deployment tool: helm (kubernetes), docker (laptop)

**Screenshots, Promtail config, or terminal output**

One component affected by the parameter:

```
---
# Source: loki/templates/read/deployment-read.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-read
  labels:
    app.kubernetes.io/part-of: memberlist
    helm.sh/chart: loki-4.4.2
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.7.3"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: read
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: read
  template:
    metadata:
      annotations:
        checksum/config: 5ecab9deb640e3c15ade0804cd26e3dc9be741c57663762c25991aab09b9344e
      labels:
        app.kubernetes.io/part-of: memberlist
        app.kubernetes.io/name: loki
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/component: read
    spec:
      serviceAccountName: loki
      automountServiceAccountToken: true
      imagePullSecrets:
        - name: nexus-registry-proxies

      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      terminationGracePeriodSeconds: 30
      containers:
        - name: loki
          image: dockerhub.io/grafana/loki:2.7.3
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/loki/config/config.yaml
            - -target=read
            - -legacy-read-mode=false
            - -common.compactor-grpc-address=loki-backend.loki.svc.cluster.local:9095
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-memberlist
              containerPort: 7946
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 30
            timeoutSeconds: 1
          volumeMounts:
            - name: config
              mountPath: /etc/loki/config
            - name: runtime-config
              mountPath: /etc/loki/runtime-config
            - name: tmp
              mountPath: /tmp
            - name: data
              mountPath: /var/loki
          resources:
            {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: loki
                  app.kubernetes.io/instance: release-name
                  app.kubernetes.io/component: read
              topologyKey: kubernetes.io/hostname

      volumes:
        - name: tmp
          emptyDir: {}
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: loki
        - name: runtime-config
          configMap:
            name: loki-runtime
```

**Comment by DylanGuedes** [comment]
hey I didn't faced this when deploying a 4.5 helm chart from scratch earlier today. Do you mind trying it with the 4.5 version?

**Comment by DylanGuedes** [comment]
Ok, here's the fix:
```yaml
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
singleBinary:
  replicas: 1
``` 
you need the `singleBinary` replicas to be higher than zero.
This is already fixed in the future docs [see here](https://grafana.com/docs/loki/next/installation/helm/install-monolithic/), you're seeing the docs that were released with Loki 2.7. Closing the issue, as the problem is already fixed in main.

**Comment by gdubroeucq** [comment]
> hey I didn't face this when deploying a 4.5 helm chart from scratch earlier today. Do you mind trying it with the 4.5 version?

Hello, I tried the 4.5 chart version but I got the same issue.

Then I was sure that the issue was with my Loki version, so in my chart value I deleted this:

```
loki:
  image:
    registry: nexus-registry.****
    repository: grafana/loki
    pullSecrets:
      - nexus-****
#    tag: 2.7.3        <-- I commented this part to see what version the chart will give me instead
```

And now the chart is working (yeah).
The Loki's helm chart version used is loki:main-5e53303 (why this version format??, look like weird instead of 2.7.x)

Can't we use simple digit version so it easier to know what loki version we use instead?
