### ISSUE TITLE
Loki Helm 4.5.0 singleBinary single Replica reports live replica requirements not met

### ISSUE THREAD

**Issue by krohrsb** [grafana/loki#8432]
**Describe the bug**
When using `singleBinary` (which now enforces 1 replica) the stack reports errors internally expecting more than 1 member.

This is reported via the `loki-0` StatefulSet.

**To Reproduce**
1. Running loki helm chart `4.5.0` leveraging the following values:

```
        test:
          enabled: false
        monitoring:
          lokiCanary:
            enabled: false
        singleBinary:
          replicas: 1
          persistence:
            storageClass: my-custom-storageclass
            size: 10Gi
        loki:
          query_scheduler:
            max_outstanding_requests_per_tenant: 2048
          query_range:
            parallelise_shardable_queries: false
            split_queries_by_interval: 0
          storage:
            type: filesystem
          auth_enabled: false
          podSecurityContext:
            fsGroupChangePolicy: "OnRootMismatch"
```

**Expected behavior**
I would expect the new singleBinary requirement to be supported by the system internally.

**Environment:**
 - Infrastructure: Kubernetes (hosted on bare metal)
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**

```
level=warn ts=2023-02-06T21:46:23.692396054Z caller=logging.go:86 traceID=487835be9906c399 orgID=fake msg="POST /loki/api/v1/push (500) 1.077475ms Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Content-Length: 3434; Content-Type: application/x-protobuf; User-Agent: GrafanaAgent/; "
```

**Comment by krohrsb** [comment]
Note, this still occurs in Loki Helm Chart 4.6.1

**Comment by wrdls** [comment]
Can you try setting? It [defaults to 3](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L227)

```yaml
loki:
  commonConfig:
    replication_factor: 1
```
