### ISSUE TITLE
Loki crashes for simple query for loglevels

### ISSUE THREAD

**Issue by suikast42** [grafana/loki#8473]
I have a simple time seriers query for counting log leveles over time. But if I grov the time range then loki is unsreponsible and grafana shows an error 

![image](https://user-images.githubusercontent.com/5046525/217665423-fa6bf791-3270-4825-bef4-ba09670ff99e.png)

Loki config

```yaml
auth_enabled: false

server:
  #default 3100
  http_listen_port: 3100
  #default 9005
  #grpc_listen_port: 9005
  # Max gRPC message size that can be received
  # CLI flag: -server.grpc-max-recv-msg-size-bytes
  #default 4194304 -> 4MB
  grpc_server_max_recv_msg_size: 419430400

  # Max gRPC message size that can be sent
  # CLI flag: -server.grpc-max-send-msg-size-bytes
  #default 4194304 -> 4MB
  grpc_server_max_send_msg_size:  419430400

  # Limit on the number of concurrent streams for gRPC calls (0 = unlimited)
  # CLI flag: -server.grpc-max-concurrent-streams
  grpc_server_max_concurrent_streams:  100

  # Log only messages with the given severity or above. Supported values [debug,
  # info, warn, error]
  # CLI flag: -log.level
  log_level: "warn"
ingester:
  wal:
    enabled: true
    dir: /data/loki/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

compactor:
  working_directory: /data/loki/retention
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: /data/loki/index

  filesystem:
    directory: /data/loki/chunks

## Delete retention_ with table manager
#chunk_store_config:
#  max_look_back_period: 168h
#table_manager:
#  retention_deletes_enabled: true
#  retention_period: 168h

querier:
  multi_tenant_queries_enabled: false

limits_config:
  query_timeout: 5m
  retention_period: 168h # 1 week log storage
## Enable this for define stream based retention
#  retention_stream:
#  - selector: '{namespace="dev"}'
#    priority: 1
#    period: 24h

  ingestion_rate_mb: 64
  ingestion_burst_size_mb: 8
  max_label_name_length: 4096
  max_label_value_length: 8092
  enforce_metric_name: false
  reject_old_samples: false
  # 5 years
  reject_old_samples_max_age: 438000h
  # The limit to length of chunk store queries. 0 to disable.
  max_query_length: 0
  max_entries_limit_per_query: 20000
  max_query_series: 100000
  max_query_parallelism: 2
  # Alter the log line timestamp during ingestion when the timestamp is the same as the
  # previous entry for the same stream. When enabled, if a log line in a push request has
  # the same timestamp as the previous line for the same stream, one nanosecond is added
  # to the log line. This will preserve the received order of log lines with the exact
  # same timestamp when they are queried, by slightly altering their stored timestamp.
  # NOTE: This is imperfect, because Loki accepts out of order writes, and another push
  # request for the same stream could contain duplicate timestamps to existing
  # entries and they will not be incremented.
  # CLI flag: -validation.increment-duplicate-timestamps
  increment_duplicate_timestamp: true
#  reject_old_samples: true
#  reject_old_samples_max_age: 168h
```

To be  honest I have a lot of log data. But I am "only" make a query to the index for statistical data. I asume that loki should have playing ping pong with that. Even the working range ( max 8d) takes more then two minutes to response. 

I use a lot elasticsearch with that amount of data without any issues. Is there a peformance setting that I miss? 

![image](https://user-images.githubusercontent.com/5046525/217670535-6c50c4ce-ba3d-4ae1-b7d6-d3ec923179b4.png)

**Comment by suikast42** [comment]
After little deep dive in loki's archrictecture I understand the query mechinism of loki.

The bottleneck in my config was the default split_queries_by_interval=30m 

This is my "performant working example"  for peapole that run in the same issue.

```yaml
auth_enabled: false

server:
  #default 3100
  http_listen_port: 3100
  #default 9005
  #grpc_listen_port: 9005
  # Max gRPC message size that can be received
  # CLI flag: -server.grpc-max-recv-msg-size-bytes
  #default 4194304 -> 4MB
  grpc_server_max_recv_msg_size: 419430400

  # Max gRPC message size that can be sent
  # CLI flag: -server.grpc-max-send-msg-size-bytes
  #default 4194304 -> 4MB
  grpc_server_max_send_msg_size:  419430400

  # Limit on the number of concurrent streams for gRPC calls (0 = unlimited)
  # CLI flag: -server.grpc-max-concurrent-streams
  grpc_server_max_concurrent_streams:  100

  # Log only messages with the given severity or above. Supported values [debug,
  # info, warn, error]
  # CLI flag: -log.level
  log_level: "warn"
ingester:
  wal:
    enabled: true
    dir: /data/loki/wal
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

storage_config:
  boltdb:
    directory: /data/loki/index

  filesystem:
    directory: /data/loki/chunks

querier:
  multi_tenant_queries_enabled: false
  max_concurrent: 4096
  query_store_only: false

query_scheduler:
  max_outstanding_requests_per_tenant: 4096

query_range:
  cache_results: true

limits_config:
  ingestion_rate_mb: 64
  ingestion_burst_size_mb: 8
  max_label_name_length: 4096
  max_label_value_length: 8092
  enforce_metric_name: false
  reject_old_samples: false
  # 5 years
  reject_old_samples_max_age: 438000h
  # The limit to length of chunk store queries. 0 to disable.
  max_query_length: 0
  # Maximum number of log entries that will be returned for a query.
  max_entries_limit_per_query: 20000
  # Limit the maximum of unique series that is returned by a metric query.
  max_query_series: 100000
  # Maximum number of queries that will be scheduled in parallel by the frontend.
  max_query_parallelism: 64
  split_queries_by_interval: 24h
  # Alter the log line timestamp during ingestion when the timestamp is the same as the
  # previous entry for the same stream. When enabled, if a log line in a push request has
  # the same timestamp as the previous line for the same stream, one nanosecond is added
  # to the log line. This will preserve the received order of log lines with the exact
  # same timestamp when they are queried, by slightly altering their stored timestamp.
  # NOTE: This is imperfect, because Loki accepts out of order writes, and another push
  # request for the same stream could contain duplicate timestamps to existing
  # entries and they will not be incremented.
  # CLI flag: -validation.increment-duplicate-timestamps
  increment_duplicate_timestamp: true
#  reject_old_samples: true
#  reject_old_samples_max_age: 168h
```
