### ISSUE TITLE
The efect of reject_old_samples and enforce_metric_name? 

### ISSUE THREAD

**Issue by suikast42** [grafana/loki#8478]
It is not clear in docuentation what this settings does. 

```yaml
limits_config:
  enforce_metric_name: false  # Does this rename metrics?
  reject_old_samples: true  # What  old samples mean ? 
  reject_old_samples_max_age: 168h
```
