### ISSUE TITLE
Issues with connecting to Minio from Helm-installation of a single-binary version of Loki.

### ISSUE THREAD

**Issue by NanineO** [grafana/loki#8485]
I have been installing a single-binary, single tenant version of Loki with Minio, with version 4.4.0 of the helm-chart for Loki on an own-managed Kubernetes-cluster.
I stumbled upon the following issues:

1) 
The endpoint name for Minio is constructed with an ending of "svc", and so doesn't work and Minio cannot be found by Loki.
It won't work to give the right endpoint name for Minio in the values file under **loki.storage.s3.endpoint**, because this name is overwritten by the constructed name ending on "svc". 

This is caused by the code in the values-file for **loki.config.common.storage**, which is set by parameter **loki.commonStorageConfig**

The value of this parameter is set in  _helpers.tpl by the following code :
```
{{- define "loki.commonStorageConfig" -}}
{{- if .Values.minio.enabled -}}
s3:
  endpoint: {{ include "loki.minio" $ }}
  bucketnames: {{ $.Values.loki.storage.bucketNames.chunks }}
  secret_access_key: {{ $.Values.minio.rootPassword }}
  access_key_id: {{ $.Values.minio.rootUser }}
  s3forcepathstyle: true
  insecure: true
```

The value of **loki.minio** is set in that same _helpers.tpl by the following code: 
```
{{- define "loki.minio" -}}
{{- if .Values.minio.enabled -}}
{{- printf "%s-%s.%s.svc:%s"  ........
```

so, ignoring any value set by the user and adding "svc".
N.B.: More parameters under **loki.storage.s3.endpoint** in the values-file are ignored the same way, as you can see at the definition for **loki.commonStorageConfig** above.

I solved this by including in my values-file the following:

```
loki:
  structuredConfig:
    common:
      storage:
        s3:
          s3: http://pod-name.namespace-name:9000
          endpoint: http://pod-name.namespace-name:9000
          bucketnames: chunks
          access_key_id: .....
          secret_access_key: .....
          s3forcepathstyle: true
          insecure: true   
```

2)
Somehow some of the parameters needed to be repeated to the storage-section of the config, despite what was configured in the common-section. So I added the following to my values-file:

```
loki:
  storage_config:
    aws:
      s3: http://pod-name.namespace-name:9000
      bucketnames: chunks
      endpoint: http://pod-name.namespace-name:9000
      s3forcepathstyle: true
      region: null
      access_key_id: ....
      secret_access_key: ......
      insecure: true
      sse_encryption: false
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 0s
        insecure_skip_verify: false  
```

3)
To enable a single-binary installation, I had to put parameter **loki.storage.type** to "filesystem". But this parameter is also used by constructing the **object_store** parameter in the schema config. So, I had to include `object_store: s3` in the **schemaConfig** in the values-file, else Minio can't be found. 

Because of the if-else construction at constructing the **loki.config.schema_config** parameter in the values-file I had to add the rest of
 the **schemaConfig** parameters to my values-file too: 

```
loki:
  schemaConfig:
    configs:
    - from: 2022-01-11
      store: boltdb-shipper
      object_store: s3
      schema: v12
      index:
        prefix: loki_index_
        period: 24h  
```

I would plead to not misuse parameter **loki.storage.type** for setting the installation to single-binary.

**Comment by SmartGuyy** [comment]
Same problem

**Comment by alexbarcelo** [comment]
I missed some details, so let me ask:
- Are you using an external Minio?
- Did you set `minio.enabled` to `true`

If I understood correctly, that's what you did and that is semantically wrong: you enable Minio IF AND ONLY IF you want a minio deployment within the loki helm chart. That's why the templates are overriding your configuration, because if minio is deployed by the template, the URL will be set by the template.

If you want to use an external Minio, you NEED TO NOT ENABLE MINIO. And then, nobody will overwrite your storage configuration for loki.

At least, that's my understanding. Feel free to correct if I misunderstood your problem or if I misunderstood how the chart works.

**Comment by mwasplund** [comment]
Using the suggested configs from the docs and getting the same error

**Comment by mwasplund** [comment]
It does look like a year ago a default address field was added to the helpers which worked for me as an easy workaround: https://github.com/grafana/loki/pull/12675

```yaml
minio:
      enabled: true
      address: http://loki-minio.grafana.svc.cluster.local:9000 # http://[service].[namespace].svc.[cluster-domain]:9000
```
