### ISSUE TITLE
Loki fails to create container in Azure Storage Account

### ISSUE THREAD

**Issue by brandongallagher1999** [grafana/loki#8501]
**Describe the bug**
After creating Loki in my cluster via the helm chart and a values file of

```
schema_config:
  configs:
  - from: "2020-12-11"
    index:
      period: 24h
      prefix: index_
    object_store: azure
    schema: v11
    store: boltdb-shipper
storage_config:
  azure:
    account_name: redacted
    account_key: redacted
    container_name: loki
    use_managed_identity: true
    request_timeout: 0
  boltdb_shipper:
    active_index_directory: /data/loki/boltdb-shipper-active
    cache_location: /data/loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: azure
  filesystem:
    directory: /data/loki/chunks
```

As well as trying this config file following the helm chart values page (https://grafana.com/docs/loki/latest/installation/helm/reference/)

```
loki:
  auth_enabled: false

  schemaConfig:
    configs:
    - from: "2020-12-11"
      index:
        period: 24h
        prefix: index_
      object_store: azure
      schema: v11
      store: boltdb-shipper

  storage_config:
    azure:
      account_name: redacted
      account_key: redacted
      container_name: loki
      use_managed_identity: true
      request_timeout: 0

    boltdb_shipper:
      active_index_directory: /data/loki/boltdb-shipper-active
      cache_location: /data/loki/boltdb-shipper-cache
      cache_ttl: 24h
      shared_store: azure
    filesystem:
      directory: /data/loki/chunks
```

Both are failing to create a loki container in Azure Storage.

**To Reproduce**
1. Create values.yaml file for Loki Helm Chart
2. Install Loki Helm Chart

**Expected behavior**
A loki container to be created in Azure Storage Account. However, it's not there and I can only see the 2 previous containers that are in the storage account (for other reasons).

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/36753063/218130138-08f74212-8708-4ed0-835d-daa410f3dae4.png">

**Environment:**
 - Infrastructure: AKS, Azure Storage Account
 - Deployment tool: Helm (grafana/loki)
