### ISSUE TITLE
Loki Helm 4.6.0: mkdir /var/loki/compactor and /var/loki/boltdb-shipper-cache: permission denied

### ISSUE THREAD

**Issue by johnswarbrick-napier** [grafana/loki#8511]
**Describe the bug**
Installing Loki into Minikube with Helm chart version 4.6.0 in single binary mode with 3 replicas results in only one 1 replica starting.

1 of the failing replicas reports `mkdir /var/loki/compactor: permission denied`

1 of the failing replicas reports `mkdir /var/loki/boltdb-shipper-cache: permission denied`

Loki cannot form quorum and fails to write logs.

**To Reproduce**

1. `minikube start --disable-metrics --nodes=3`
2. Download Loki Helm chart 4.6.0 from https://grafana.github.io/helm-charts
3. Create values.yaml:

```
  loki:
    # Disable multi-tenancy mode
    auth_enabled: false

    commonConfig:
      # Set minimum replication factor
      replication_factor: 2


  # Enable single binary mode
  singleBinary:
    # -- Number of replicas for the single binary
    replicas: 3

  # Disable distributed write pod(s)
  write:
    # -- Number of replicas for the write
    replicas: 0

  # Disable gateway component
  gateway:
    # -- Specifies whether the gateway should be enabled
    enabled: false

  test:
    enabled: false

  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false
```

4. `helm install --values ./values.yaml loki . --namespace monitoring --create-namespace`
5. `minikube kubectl -- get pods -A`
6. Observe two of the three pods are failing to start:

```
monitoring    loki-0                                    0/1     CrashLoopBackOff    1 (9s ago)      61s
monitoring    loki-1                                    0/1     CrashLoopBackOff    1 (9s ago)      61s
monitoring    loki-2                                    0/1     Running             0               61s
```

**Expected behavior**
I am expecting all three pods to start.

**Environment:**
 - Infrastructure: Minikube v1.29.0
 - Deployment tool: Helm v3.10.1

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

```
mkdir /var/loki/compactor: permission denied
error initialising module: compactor
github.com/grafana/dskit/modules.(*Manager).initModule
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:122
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:92
github.com/grafana/loki/pkg/loki.(*Loki).Run
        /src/loki/pkg/loki/loki.go:422
main.main
        /src/loki/cmd/loki/main.go:105
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1594
```

```
mkdir /var/loki/boltdb-shipper-cache: permission denied
error creating index client
github.com/grafana/loki/pkg/storage.(*store).storeForPeriod
        /src/loki/pkg/storage/store.go:270
github.com/grafana/loki/pkg/storage.(*store).init
        /src/loki/pkg/storage/store.go:164
github.com/grafana/loki/pkg/storage.NewStore
        /src/loki/pkg/storage/store.go:147
github.com/grafana/loki/pkg/loki.(*Loki).initStore
        /src/loki/pkg/loki/modules.go:632
github.com/grafana/dskit/modules.(*Manager).initModule
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:120
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:92
github.com/grafana/loki/pkg/loki.(*Loki).Run
        /src/loki/pkg/loki/loki.go:422
main.main
        /src/loki/cmd/loki/main.go:105
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1594
error initialising module: store
github.com/grafana/dskit/modules.(*Manager).initModule
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:122
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:92
github.com/grafana/loki/pkg/loki.(*Loki).Run
        /src/loki/pkg/loki/loki.go:422
main.main
        /src/loki/cmd/loki/main.go:105
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1594
```

**Comment by johnswarbrick-napier** [comment]
Resolved - managed to address by running in singleBinary mode with 1 replica and local storage using the following options:

```
##
## Loki-specific configuration for sub-chart
##
loki:

  loki:

    # -- Disable multi-tenancy mode
    auth_enabled: false

    commonConfig:
      # -- Set minimum replication factor
      replication_factor: 1

    storage:
      # -- Enable PVC storage (change to object storage in Production)
      type: filesystem

    rulerConfig:
      storage:
        type: local

  # Enable single binary mode
  singleBinary:

    # -- Number of replicas for single binary mode
    replicas: 1

    # -- Enable PVC storage for single binary (change to object storage in Production)
    persistence:
      enabled: true
      size: 10Gi

  test:
    enabled: false

  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false
```

**Comment by pen-pal** [comment]
hi

this is my values.yaml
```
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  ingester:
    chunk_encoding: snappy
  limits_config:
    max_cache_freshness_per_query: 10m
    max_entries_limit_per_query: 5000
    query_timeout: 300s
    reject_old_samples: true
    reject_old_samples_max_age: 31d
    split_queries_by_interval: 15m
    volume_enabled: true
  querier:
    max_concurrent: 2
  schemaConfig:
    configs:
    - from: "2024-04-01"
      index:
        period: 24h
        prefix: loki_index_
      object_store: s3
      schema: v13
      store: tsdb
  storage:
    bucketNames:
      admin: loki
      chunks: loki
      ruler: loki
    type: s3
    s3:
      s3: loki
      region: eu-west-2
      secretAccessKey: secret
      accessKeyId: access
      s3ForcePathStyle: true
      insecure: false
  storage_config:
    aws:
      bucketnames: loki
      #s3: s3://eu-west-2
      s3: s3://access:secret@eu-west-2
    tsdb_shipper:
      active_index_directory: /loki/index
      cache_location: /loki/index_cache
  tracing:
    enabled: true

deploymentMode: SingleBinary

singleBinary:
  extraEnv:
  - name: GOMEMLIMIT
    value: 3750MiB
  replicas: 1
  resources: {}
  persistence:
    enabled: false
    storageClass: "gp2"
#serviceAccount:
#  create: false
#  name: loki-sa

chunksCache:
  # -- Specifies whether memcached based chunks-cache should be enabled
  enabled: false #true
  resources: {}
  writebackSizeLimit: 10MB

lokiCanary:
  enabled: false

resultsCache:
  enabled: false

test:
  enabled: false

backend:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
compactor:
  replicas: 0
distributor:
  replicas: 0
indexGateway:
  replicas: 0
ingester:
  replicas: 0
minio:
  enabled: false
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
```

if i disable persistance, i keep getting following errors
```
init compactor: mkdir /var/loki: read-only file system                                                                                                                                                                                                                     
error initialising module: compactor                                                                                                                                                                                                                                       
github.com/grafana/dskit/modules.(*Manager).initModule                                                                                                                                                                                                                     
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138                                                                                                                                                                                                       
github.com/grafana/dskit/modules.(*Manager).InitModuleServices                                                                                                                                                                                                             
    /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108                                                                                                                                                                                                       
github.com/grafana/loki/v3/pkg/loki.(*Loki).Run                                                                                                                                                                                                                            
    /src/loki/pkg/loki/loki.go:458                                                                                                                                                                                                                                         
main.main                                                                                                                                                                                                                                                                  
    /src/loki/cmd/loki/main.go:129                                                                                                                                                                                                                                         
runtime.main                                                                                                                                                                                                                                                               
    /usr/local/go/src/runtime/proc.go:271                                                                                                                                                                                                                                  
runtime.goexit                                                                                                                                                                                                                                                             
    /usr/local/go/src/runtime/asm_amd64.s:1695                                                                                                                                                                                                                             
level=info ts=2024-09-04T17:58:41.669415031Z caller=main.go:126 msg="Starting Loki" version="(version=release-3.1.x-89fe788, branch=release-3.1.x, revision=89fe788d)"                                                                                                     
level=info ts=2024-09-04T17:58:41.669444085Z caller=main.go:127 msg="Loading configuration file" filename=/etc/loki/config/config.yaml                                                                                                                                     
level=info ts=2024-09-04T17:58:41.670815916Z caller=server.go:352 msg="server listening on addresses" http=:3100 grpc=:9095                                                                                                                                                
level=info ts=2024-09-04T17:58:41.672152478Z caller=memberlist_client.go:435 msg="Using memberlist cluster label and node name" cluster_label= node=loki-0-0d0ff337                                                                                                        
level=info ts=2024-09-04T17:58:41.672894546Z caller=memberlist_client.go:541 msg="memberlist fast-join starting" nodes_found=1 to_join=4                                                                                                                                   
level=error ts=2024-09-04T17:58:41.672948394Z caller=log.go:216 msg="error running loki" err="init compactor: mkdir /var/loki: read-only file system\nerror initialising module: compactor\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/gith
ub.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:458\nmain.ma
in\n\t/src/loki/cmd/loki/main.go:129\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1695"
```
