### ISSUE TITLE
Loki ingests logs from Promtail with multiple backslashes, breaking Grafana queries

### ISSUE THREAD

**Issue by johnswarbrick-napier** [grafana/loki#8512]
**Describe the bug**
Loki appears to be ingesting logs from Promtail with multiple backslashes, resulting in Grafana queries failing to render data:

<img width="960" alt="Loki-01" src="https://user-images.githubusercontent.com/105818625/218331165-e4184338-213f-4025-91a3-9d91d4ed931e.PNG">

<img width="959" alt="Loki-02" src="https://user-images.githubusercontent.com/105818625/218331184-27e1285b-9fae-49b9-b926-51a4ee3f2da6.PNG">

<img width="960" alt="Loki-03" src="https://user-images.githubusercontent.com/105818625/218331236-167facbb-b9f3-4c29-b1f3-cc7c7068ed7a.PNG">

```
Loki and Promtail both installed from Helm, versions:

  - name: loki
    version: "4.6.0"
    repository: https://grafana.github.io/helm-charts

  - name: "promtail"
    version: "6.8.2"
    repository: "https://grafana.github.io/helm-charts"

  - name: kube-prometheus-stack
    version: "45.0.*"
    repository: https://prometheus-community.github.io/helm-charts
```

Current configuration:

```
##
## Prometheus-specific configuration for sub-chart
##
kube-prometheus-stack:

  # Grafana-specific configuration
  grafana:

    # -- Add Loki to Grafana as additional data source
    additionalDataSources:
    - access: proxy
      isDefault: false
      name: loki
      type: loki
      url: http://loki-gateway
      version: 1


##
## Loki-specific configuration for sub-chart
##
loki:

  loki:

    # -- Disable multi-tenancy mode
    auth_enabled: false

    commonConfig:
      # -- Set minimum replication factor
      replication_factor: 1

    storage:
      # -- Enable PVC storage (change to object storage in Production)
      type: filesystem

    rulerConfig:
      storage:
        type: local

  # Enable single binary mode
  singleBinary:

    # -- Number of replicas for single binary mode
    replicas: 1

    # -- Enable PVC storage for single binary (change to object storage in Production)
    persistence:
      enabled: true
      size: 10Gi

  test:
    enabled: false

  monitoring:
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false
    lokiCanary:
      enabled: false
```

Running on Minikube v1.29.0 and installed with Helm v3.10.1

**To Reproduce**

1. Install Loki, Promtail and Grafan using versions given above
2. Apply values.yaml as given above
3. Run raw query {namespace="monitoring"} |= and observe the backslashes

**Expected behavior**
Expecting logs to be ingested without backslashes so it can be queried

**Environment:**
See versions above

**Screenshots, Promtail config, or terminal output**
See screenshots above
