### ISSUE TITLE
error initialising module: cache-generation-loader

### ISSUE THREAD

**Issue by h0ns0l0** [grafana/loki#8523]
**Describe the bug**

Error for query-frontend with minio storage:

```
Started Loki.
query filtering for deletes requires 'compactor_address' to be configured
error initialising module: cache-generation-loader
github.com/grafana/dskit/modules.(*Manager).initModule
         /drone/src/vendor/github.com/grafana/dskit/modules/modules.go:122
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
         /drone/src/vendor/github.com/grafana/dskit/modules/modules.go:92
github.com/grafana/loki/pkg/loki.(*Loki).Run
         /drone/src/pkg/loki/loki.go:360
 main.main
         /drone/src/cmd/loki/main.go:105
 runtime.main
         /usr/local/go/src/runtime/proc.go:250
 runtime.goexit
         /usr/local/go/src/runtime/asm_amd64.s:1594
Stopped Loki.
```

**To Reproduce**

1. Started Loki = 2.7.0
2. MinIO = 1.19.3
3. Fluent-bit = 1.9.9

**Expected behavior**

Read-only access as dedicated to the query-frontend.

**Environment:**

 - virtual machine
 - ELF 64-bit
 - systemd

**LOKI CONFIG**

```yaml
auth_enabled: false

server:
  http_listen_port: 3100

query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true

  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        size: 1024
        validity: 24h

memberlist:
 join_members:
  - loki-1:3100
  - loki-2:3100

limits_config:
  max_cache_freshness_per_query: '2m'
  split_queries_by_interval: '5m'

frontend:
  log_queries_longer_than: 5s
  downstream_url: http://loki-1:3100
  compress_responses: true

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
     schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /opt/loki/var/index
    cache_location: /opt/loki/var/index_cache
    shared_store: s3
  aws:
    bucketnames: $NAME
    endpoint: http://$MINIO:9000
    region: $REG
    access_key_id: $USER
    secret_access_key: $PASS
    s3forcepathstyle: true
    insecure: true

common:
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
```
