### ISSUE TITLE
[Feature request] Write reason oomkilled in logs application before shutdown

### ISSUE THREAD

**Issue by patsevanton** [grafana/loki#8538]
**Is your feature request related to a problem? Please describe.**
I view promql query
```
sum(changes(kube_pod_container_status_last_terminated_reason{reason="OOMKilled",namespace="loki"}[10m]) > 0) by (container, pod)
```
and i sea restart pod by OOMKilled.
Memory limit have 56.63% at this moment.
I have resources:
```
      resources:
        requests:
          memory: "3072Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
          cpu: "2000m"
```

**Describe the solution you'd like**
I will see reason oomkilled in logs application before shutdown

**Describe alternatives you've considered**
Write memory used in logs application before shutdown

**Additional context**
