### ISSUE TITLE
[Promtail] Support for `health_check_target` attribute in server config for `loki_push_api`

### ISSUE THREAD

**Issue by Yasmine92** [grafana/loki#8544]
**Is your feature request related to a problem? Please describe.**

according to the [documentation](https://github.com/grafana/loki/blob/main/docs/sources/clients/promtail/configuration.md#loki_push_api) we sould be able to use the same `servers_config` parameters for `loki_push_api` as described [here](https://github.com/grafana/loki/blob/main/docs/sources/clients/promtail/configuration.md#server).
However we can't use `health_check_target`  as this results with the following error:
 
```
Unable to parse config: /etc/promtail/promtail.yaml: yaml: unmarshal errors:
  line 20: field health_check_target not found in type server.Config

```
example of a configuration producing this:

```
            scrapeConfigs: |
              - job_name: lokipush
                loki_push_api:
                  server:
                    http_listen_port: 3500
                    grpc_listen_port: 3600
                    log_level: debug
                    health_check_target: true
```

**Describe the solution you'd like**

add support for `health_check_target` attribure  to the  server of type `loki_push_api` as this is important for readinessProbe purposes.
