### ISSUE TITLE
[loki] "failed parsing config: bad substitution" when using -config.expand-env=true

### ISSUE THREAD

**Issue by johnswarbrick-napier** [grafana/loki#8558]
**Describe the bug**
Loki fails to start reporting error "failed parsing config: bad substitution" when I try to use environment variables in the configuration with "-config.expand-env=true".

I'm trying to specify Azure Blob Storage account key and name through a Kubernetes Secret instead of specifying via the values.yaml file. Setting the values explicitly works fine, trying to use environment variable substitution is failing:

```
# minikube kubectl -- logs -n monitoring monitoring-loki-0
failed parsing config: bad substitution
```

Documentation: https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration

I'm probably doing something obviously wrong but I've been struggling with it for days and not made any progress!

**To Reproduce**
Here is my configuration:

```
loki:
  loki:
    storage:
        # -- Set preferred object storage provider
        type: azure

        # -- Options for Azure Blob Storage
        azure:
          accountName: ${azure-account-name}
          accountKey: ${azure-account-key}

  # -- Enable Loki single binary (monolithic) mode
  singleBinary:
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
            # -- Kubernetes Secret with object storage details
            name: azure-storage

  compactor:
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
            # -- Kubernetes Secret with object storage details
            name: azure-storage

  read:
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
            # -- Kubernetes Secret with object storage details
            name: azure-storage

  write:
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
            # -- Kubernetes Secret with object storage details
            name: azure-storage

  ingestor:
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
            # -- Kubernetes Secret with object storage details
            name: azure-storage

  querier:
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
            # -- Kubernetes Secret with object storage details
            name: azure-storage
```

The Kubernetes Secret is being created with command:

```
kubectl create secret generic -n monitoring azure-storage --from-literal=azure-account-key=[KEY_VALUE] --from-literal=azure-account-name=[ACCOUNT_VALUE]
```

**Expected behavior**
Successfully read in secret values

**Environment:**
 - Kubernetes, Loki Helm Chary 4.6.1
