### ISSUE TITLE
How to configure aws s3 credentials securely for accessing aws storage object in loki-configuration

### ISSUE THREAD

**Issue by vermaprateek695** [grafana/loki#8572]
Hi All ,

In our approach we are defining the entire aws s3 configuration in a secret and creating environment variables in the loki config to access the secret containing AWS s3 details , but when trying to deploy and access the aws secret using env section defined in loki configuration

extraArgs:
  config.expand-env: true

env:
    - name: S3_ACCESS_KEY_id
      valueFrom:
        secretKeyRef:
          name: s3-credentials
          key: access_key_id
    - name: S3_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: s3-credentials
          key: secret_access_key

    aws:
      s3: <URL>
      bucketnames: mybucketnames 
      access_key_id: ${S3_ACCESS_KEY_id}
      secret_access_key: ${S3_SECRET_ACCESS_KEY}

But we are getting below error 

level=error ts=2023-02-21T06:31:04.487300046Z caller=flush.go:146 org_id=acc msg="failed to flush user" err="store put chunk: InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.\n\tstatus code: 403,

Validated the access_key_id and secret_access_key , values looks good but still unable to access it.

Any leads will be appreciated for fixing this issue or maybe another workaround.

Thanks !

**Comment by jeschkies** [comment]
How are you deploying? Depending on your environment you could use an IAM role.

**Comment by jonas-tm** [comment]
I am also interested in how to configure this properly (unrelated to the cloud provider).
Seems like a lot of people are having the same problem [here](https://github.com/grafana/helm-charts/issues/158).
To my knowledge it is bad practice to put secrets into helm values instead of a secret reference.

**Comment by vermaprateek695** [comment]
> How are you deploying? Depending on your environment you could use an IAM role.

Hi @jeschkies 

We are deploying using helm chart and its a dev environment where we are using it.. can you let me know how we can implement AWS IAM role for the same ?

Any ideas and suggestions are welcomed .



Regards,
Prateek

**Comment by Pela647** [comment]
@vermaprateek695 , please use IRSA and follow everything here: https://github.com/grafana/loki/issues/8152

**Comment by mrwormhole** [comment]
current problem seems to be confusion around where to put `extraArgs:
config.expand-env: true` and helm charts not supporting secretKeyRef

**Comment by PaoloC68** [comment]
Please clarify where `extraArgs: config.expand-env: true` belongs!
Do I have to set   also `extraEnv:` or `extraEnvFrom:`  or it is enough one of them?

**Comment by davidusken** [comment]
@PaoloC68 just managed to set this up, you will need both for each pod. I am using a Helm chart to deploy but this is how I set it up:
```
...
  write:
    replicas: 1

    # Disable podAntiAffinity because of running on single-node
    affinity: {}
    extraArgs:
      - '-config.expand-env=true'
    extraEnv:
      - name: S3_LOKI_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: loki-bucket-secret
            key: S3_LOKI_ACCESS_KEY_ID
      - name: S3_LOKI_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: loki-bucket-secret
            key: S3_LOKI_SECRET_ACCESS_KEY

  read:
    replicas: 1
    persistence:
      enableStatefulSetAutoDeletePVC: false
      
    # Disable podAntiAffinity because of running on single-node
    affinity: {}
    extraArgs:
      - '-config.expand-env=true'
    extraEnv:
      - name: S3_LOKI_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: loki-bucket-secret
            key: S3_LOKI_ACCESS_KEY_ID
      - name: S3_LOKI_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: loki-bucket-secret
            key: S3_LOKI_SECRET_ACCESS_KEY
...
```

**Comment by esmaeilzadehayub** [comment]
I am using a Helm chart to deploy Loki, and it is working fine 
`backend:
     extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: S3_LOKI_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: loki-bucket-secret
              key: S3_LOKI_ACCESS_KEY_ID
        - name: S3_LOKI_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: loki-bucket-secret
              key: S3_LOKI_SECRET_ACCESS_KEY
    write:
            extraArgs:
        - '-config.expand-env=true'
      extraEnv:
        - name: S3_LOKI_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: loki-bucket-secret
              key: S3_LOKI_ACCESS_KEY_ID
        - name: S3_LOKI_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: loki-bucket-secret
              key: S3_LOKI_SECRET_ACCESS_KEY
  
          read:
               extraArgs:
        - '-config.expand-env=true'
    extraEnv:
      - name: S3_LOKI_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: loki-bucket-secret
            key: S3_LOKI_ACCESS_KEY_ID
      - name: S3_LOKI_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: loki-bucket-secret
            key: S3_LOKI_SECRET_ACCESS_KEY

**Comment by jeschkies** [comment]
Maybe we should make it simple. Please note, if you are running in AWS you don't d to pass the credentials at all.

**Comment by esmaeilzadehayub** [comment]
Close this issue

**Comment by tomaaron** [comment]
> Maybe we should make it simple. Please note, if you are running in AWS you don't d to pass the credentials at all.

I agree. This should be simpler. As far as I read the docs from the [values](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L80C93-L80C112) there should be an option to set `global.extraEnvFrom` but found nowhere a helper or reference to this.

**Comment by david-nano** [comment]
> Close this issue, it is a solution [#8572 (comment)](https://github.com/grafana/loki/issues/8572#issuecomment-1582831358)

Sorry for this update, but even this practice didn't worked on "backend" deployment, log:
```
level=warn ts=2023-07-24T10:42:16.360157037Z caller=loki.go:286 msg="per-tenant timeout not configured, using default engine timeout (\"5m0s\"). This behavior will change in the next major to always use the default per-tenant timeout (\"5m\")."
level=info ts=2023-07-24T10:42:16.367888601Z caller=main.go:108 msg="Starting Loki" version="(version=2.8.2, branch=HEAD, revision=9f809eda7)"
level=info ts=2023-07-24T10:42:16.370839487Z caller=server.go:323 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2023-07-24T10:42:16.377107158Z caller=memberlist_client.go:437 msg="Using memberlist cluster label and node name" cluster_label= node=loki-backend-1-0b9a51ca
level=warn ts=2023-07-24T10:42:16.37885915Z caller=cache.go:114 msg="fifocache config is deprecated. use embedded-cache instead"
level=warn ts=2023-07-24T10:42:16.378908049Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache - chunksembedded-cache"
level=info ts=2023-07-24T10:42:16.379652446Z caller=memberlist_client.go:543 msg="memberlist fast-join starting" nodes_found=1 to_join=4
level=info ts=2023-07-24T10:42:16.383488628Z caller=table_manager.go:404 msg="loading local table loki_index_19562"
ts=2023-07-24T10:42:16.389344301Z caller=spanlogger.go:85 level=info msg="building index list cache"
ts=2023-07-24T10:42:16.392472186Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve loki-memberlist: lookup loki-memberlist on 10.43.0.10:53: server misbehaving"
level=warn ts=2023-07-24T10:42:16.392516186Z caller=memberlist_client.go:563 msg="memberlist fast-join finished" joined_nodes=0 elapsed_time=12.90534ms
level=info ts=2023-07-24T10:42:16.392544286Z caller=memberlist_client.go:576 msg="joining memberlist cluster" join_members=loki-memberlist
ts=2023-07-24T10:42:16.405380926Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve loki-memberlist: lookup loki-memberlist on 10.43.0.10:53: server misbehaving"
```

**Comment by WoodyWoodsta** [comment]
More confusion here. The dots that are not being joined are that you need to add tokens in the config which `'-config.expand-env=true'` will expand, as per: https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration

So you need:

```yaml
loki:
  s3:
    # ... s3 config
    accessKeyId: ${S3_LOKI_ACCESS_KEY_ID}
    secretAccessKey: ${S3_LOKI_SECRET_ACCESS_KEY}
```

As well as what has been mentioned already, where the values for the above tokens will come from:

```yaml
backend:
  extraArgs:
    - '-config.expand-env=true'
  extraEnv:
    - name: S3_LOKI_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: loki-bucket-secret
          key: S3_LOKI_ACCESS_KEY_ID
    - name: S3_LOKI_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: loki-bucket-secret
          key: S3_LOKI_SECRET_ACCESS_KEY

# Repeated for `write` and `read`
```

**Comment by david-nano** [comment]
@WoodyWoodsta  it's answer we saw already by @davidusken 
https://github.com/grafana/loki/issues/8572#issuecomment-1543652661

**Comment by WoodyWoodsta** [comment]
> @WoodyWoodsta  it's answer we saw already by @davidusken 
> 
> https://github.com/grafana/loki/issues/8572#issuecomment-1543652661

No it's not. They only mention the second part. It was unclear whether the component reads in the environment variables directly or uses them to expand the config further. I was just trying to string the two together in one comment.

**Comment by matschaffer-roblox** [comment]
Thanks @WoodyWoodsta - I got confused by that exact point and seeing your complete example helped clear up if `S3_LOKI_ACCESS_KEY_ID` was some sort of "special" env var or not (answer: it's not).

**Comment by jhr1972** [comment]
For those in need to debug the env-expansion, it might be useful to add the print-config statement as it dumps you all the variables finally processed.
```
  extraArgs:
    - --config.expand-env=true
    - --log.level=debug
    - --print-config-stderr
```

**Comment by Angel0r** [comment]
I had similar problem [#12218](https://github.com/grafana/loki/issues/12218).
Since I use Kubernetes Secrets I solved it by using `extraEnvFrom` instead of `extraEnv`.
```yaml
loki:
  storage:
    type: s3
    s3:
      s3: "s3://test-loki"
      endpoint: "test.se-grid.com/"
      region: eu-north-1
      secretAccessKey: "${secretAccessKey}"
      accessKeyId: "${accessKeyId}"
      signatureVersion: null
      s3ForcePathStyle: true
      insecure: false
      http_config: {}

# Configuration for the backend pod(s)
backend:
  # -- Number of replicas for the backend
  replicas: 3
  extraArgs: ["-config.expand-env=true"]
  extraEnv:extraEnvFrom: ["loki-test-credentials"]
```
