### ISSUE TITLE
Loki exits 1 with no logs after upgrade 2.1.0 -> 2.7.4 despite following upgrade guide

### ISSUE THREAD

**Issue by avarsava** [grafana/loki#8625]
**Describe the bug**
loki-linux-amd64 exits 1 with no error message after upgrade from 2.1.0 -> 2.7.4 despite following the upgrade guide.

**To Reproduce**
1. Had working Loki 2.1.0 install 
2. Upgraded to 2.7.4
3. Followed upgrade guide, only section that seemed to apply to me was changing the retention rules in table_manager block as per 2.4.0 guide
4. The upgrade guide says to put the retention period inside `[]`, this causes "cannot unmarshall !!seq to str" (this is probably its own bug)
5. removed brackets, now loki just exits 1 with no error at all even with debug level logging

**Expected behavior**
At least an error detailing what's wrong with the config.

**Environment:**
 - Infrastructure: bare-metal

**Screenshots, Promtail config, or terminal output**
Here's the config file, you can see I followed the 2.4.0 upgrade instructions:

<details>
<summary>loki-config.yml</summary>

```
auth_enabled: false

server:
  http_listen_port: 3100
  log_level: debug

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 1

schema_config:
  configs:
  - from: 2018-04-15
    store: boltdb
    object_store: filesystem
    schema: v9
    index:
      prefix: index_
      period: 168h

storage_config:
  boltdb:
    directory: /data/index

  filesystem:
    directory: /data/chunks

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_label_value_length: 10000
  max_streams_per_user: 0
  retention_period: 2520h

chunk_store_config:
  max_look_back_period: 0

table_manager:
  chunk_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
  index_tables_provisioning:
    inactive_read_throughput: 0
    inactive_write_throughput: 0
    provisioned_read_throughput: 0
    provisioned_write_throughput: 0
    #retention_deletes_enabled: true
    #retention_period: 2520h # This is required to be a multiple of the index period. 168h = 7 days, 168 * 5 (weeks) * 3 (months) = 2520h

compactor:
  retention_enabled: true
```

</details
