### ISSUE TITLE
Error changing Table period

### ISSUE THREAD

**Issue by HakimMiao** [grafana/loki#8639]
I want to change the Table period, but there is an error. I use the docker.

Successful loki configuration:

``` yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/grafana/loki
  storage:
    filesystem:
      chunks_directory: /tmp/grafana/loki/chunks
      rules_directory: /tmp/grafana/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

limits_config:
  per_stream_rate_limit: 15MB
  per_stream_rate_limit_burst: 75MB

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
```

When I change 24h to 48h and 72h, loki will directly exit 1. I also tried 2880m, but still failed:

``` yaml
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 48h
```
![image](https://user-images.githubusercontent.com/126433295/221459443-c64e93b8-2507-48bf-a56e-cd51df3f2a60.png)
