### ISSUE TITLE
table_manager - Dynamo DB - Impossible to change provisioning capacity 

### ISSUE THREAD

**Issue by quadrinho** [grafana/loki#8676]
**Describe the bug**
Hello,
i am trying to deploy the loki-grafana chart using S3 and DynamoDB. I see that the "Read Capacity Mode" is set to 300 and the "Write Capacity Mode" is set to 1000.

I see from the documentation that it is possible to configure the DynamoDB Provisioning:

https://grafana.com/docs/loki/latest/operations/storage/table-manager/

But in the values.yaml of the chart the section "table_manager" (inside config) is not customizable and it is fixed:

```
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0
```

**To Reproduce**
1. Started Loki (SHA or version) --> Chart Version: 4.8.0, Application Version: 2.7.3

**Expected behavior**
It should be possible customize the table_manager section as described in the documentation above:
```

table_manager:
  index_tables_provisioning:
    provisioned_write_throughput: 10
    provisioned_read_throughput: 10
  chunk_tables_provisioning:
    provisioned_write_throughput: 10
    provisioned_read_throughput: 10
```

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]: Kubernetes EKS
 - Deployment tool: [e.g., helm, jsonnet]: helm
