### ISSUE TITLE
Likely Memory Leak for Distributor

### ISSUE THREAD

**Issue by mizeng** [grafana/loki#868]
**Describe the bug**
I've deployed 1 Distributor with 4U 20GB RAM, 2 Ingesters only with 4U 20GB RAM. Ingester works well, however from the Memory Usage Dashboard, I find a periodically pattern that memory increasing and finally use up all the memory in Distributor.
![Screen Shot 2019-08-08 at 10 02 44 AM](https://user-images.githubusercontent.com/8059086/62669832-b0f33180-b9c3-11e9-8943-6af2baee6562.png)

**To Reproduce**
1. Started table-manager, distributor, ingester.
2.Use API `/api/prom/push` with payload like below to ingest log
```
{
	"streams": [{
		"labels": "{job=\"varlogs\",node=\"node\",filename=\"/var/log/teste.log\"}",
		"entries": [{
			"ts": "2019-07-22T01:16:23.647Z",
			"line": "2019-07-22 01:16:23.647 test1"
		},
              ... //another 3999 entries
             ]
	}]
}
```

**Expected behavior**
Distributor should works well without memory issue

**Environment:**
 - Store
ring: Consul
chunk store: Ceph Object Store
index store: Cassandra
```
storage_config:
  cassandra:
    username: cassandra
    password: cassandra
    addresses: cassandra_host
    auth: true
    keyspace: lokiindex
    timeout: 10s
    connect_timeout: 10s

  aws:
    s3: s3://xx:xx@cephhost/lokitest
    s3forcepathstyle: true
```
 - Infrastructure: Kubernetes
1 table-manager
1 distributor
2 ingesters
 - Deployment tool: kubectl deploy with deploy/svc yaml

**Screenshots, promtail config, or terminal output**
1. deploy yaml for distributor
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: distributor
spec:
  replicas: 1
  template:
    metadata:
      name: distributor
      annotations:
        xxx
      labels:
        app: "distributor"
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: loki
        image: grafana/loki:latest
        command: ["/bin/loki"]
        args: ["-config.file=/etc/loki/local-config.yaml", "-target=distributor", "-log.level=debug"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/loki
        ports:
        - containerPort: 3100
        - containerPort: 9095
        resources:
          requests:
            cpu: 4
            memory: 20Gi
          limits:
            cpu: 4
            memory: 20Gi
        imagePullPolicy: Always
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: loki-conf
          items:
          - key: temp.yaml
            path: local-config.yaml

---
apiVersion: v1
kind: Service
metadata:
  annotations:
   xxx
  labels:
    app: distributor
  name: distributor
  namespace: lokitest
spec:
  ports:
  - port: 3100
    name: http
  - port: 9095
    name: grpc
  selector:
    app: distributor
  sessionAffinity: None
  type: LoadBalancer
```

Update:
1. Thanks to Ed, we narrow down it to poor JSON decode performance. Better way is to try serialize to ProtoBuf before sending to Distributor for high volume ingestion.
