### ISSUE TITLE
Promtail 2.7.4 uses more memory than 2.7.3

### ISSUE THREAD

**Issue by Joibel** [grafana/loki#8690]
**Describe the bug**
Promtail 2.7.4 uses more memory than 2.7.3

**To Reproduce**
Install promtail 2.7.3 from the helm chart with memory limits set low but adequate on an a cluster actively producing logs, feeding them to loki.
See that it works without OOM behaviour.
Upgrade to 2.7.4.
Observe pods going OOM.

**Expected behavior**
Promtail to continue to use similar amounts of memory to before.

**Environment:**
 - EKS kubernetes cluster v1.24.8-eks-ffeb93d
 - Helm chart. Bumped from 6.9.1 to 6.9.2

**Screenshots, Promtail config, or terminal output**
Helm pod resource configuration.
```
   resources:
     limits:                                                              
       cpu: 200m      
       memory: 200Mi                                                      
     requests:                                                            
       cpu: 100m
       memory: 200Mi
```

I imagine the golang bump from 1.19.5->1.20.1 is to blame.
