### ISSUE TITLE
journalctl scrape is not working

### ISSUE THREAD

**Issue by piontec** [grafana/loki#872]
I'm trying to use this example: https://github.com/grafana/loki/blob/master/docs/promtail-examples.md#simple-systemd-journal-config

to get logs from journald, but it doesn't seem to work. Tested on ubuntu 18.04.

My `/var/log` layout:
```bash
$ docker exec -it promtail ls -la /var/log/journal
total 20
drwxr-sr-x    3 root     112           4096 May 17  2018 .
drwxrwxr-x   14 root     104           4096 Aug  8 04:25 ..
drwxr-sr-x    2 root     112          12288 Jul 26 07:14 a2b1671204f1279ccbf727e753c8dd7a
```

The promtail config file:
```yaml
$ docker exec -it promtail cat /etc/loki/promtail-docker.yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: journal
    journal:
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
```

`static_config` works ok, `journal` just logs this on startup:
```
$ docker logs promtail
level=warn ts=2019-08-08T11:14:41.826323734Z caller=filetargetmanager.go:98 msg="WARNING!!! entry_parser config is deprecated, please change to pipeline_stages"
level=warn ts=2019-08-08T11:14:41.82785528Z caller=journaltargetmanager.go:24 msg="WARNING!!! Journal target manager initialized on platform without Journal support!"
level=info ts=2019-08-08T11:14:41.828351727Z caller=server.go:120 http=[::]:9080 grpc=[::]:45809 msg="server listening on addresses"
```

promtail version:
```
$ docker image inspect grafana/promtail
[
    {
        "Id": "sha256:5e5610ecaf1750b82a3cad9cdd246bb817694bfd810fc13f36c78b60918e7814",
        "RepoTags": [
            "grafana/promtail:latest"
        ],
        "RepoDigests": [
            "grafana/promtail@sha256:2d6d4b7b09fd93422bd45247c18698f9844418d0a7c7429513f404eea471c93f"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2019-08-08T06:50:59.79037259Z",
```
