### ISSUE TITLE
[Bug] Loki read readiness probe fails in non default namespace

### ISSUE THREAD

**Issue by Sharathmk99** [grafana/loki#8723]
When installing loki in non default namespace, `loki-read` pod readiness fails. With same configuration it works in `default` namespace.

I'm installing loki from official helm chart with below custom `values.yaml`

```
loki:
  image:
    repository: grafana/loki
    tag: 2.7.4
  auth_enabled: false
  storage:
    type: "s3"
    s3:
      s3: http://minio:xxxxx@minio-service.default.svc.cluster.local:9000
      s3ForcePathStyle: true
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
  podSecurityContext:
    fsGroup: 122
    runAsGroup: 122
    runAsNonRoot: true
    runAsUser: 1223
  compactor:
    shared_store: s3
    compaction_interval: 10m
    retention_enabled: true
    retention_delete_delay: 1m
    retention_delete_worker_count: 50
    working_directory: /var/loki/retention
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_cache_freshness_per_query: 10m
    split_queries_by_interval: 15m
    retention_period: 168h
  storage_config:
    hedging:
      at: "250ms"
      max_per_second: 20
      up_to: 3
    boltdb_shipper:
      shared_store: s3
    aws:
      s3: http://minio:xxxx@minio-service.kubeflow.svc.cluster.local:9000/loki-admin
      s3forcepathstyle: true
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
gateway:
  enabled: true
  podSecurityContext:
    fsGroup: 122
    runAsGroup: 122
    runAsNonRoot: true
    runAsUser: 1234
  image:
    repository: nginxinc/nginx-unprivileged
    tag: 1.19-alpine
test:
  enabled: false
read:
  replicas: 3
  persistence:
    storageClass: storage-delete
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
write:
  replicas: 3
  persistence:
    storageClass: storage-delete
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
memberlist:
  service:
    publishNotReadyAddresses: false
```

Kubectl status

```
NAME                           READY   STATUS    RESTARTS   AGE
loki-gateway-6b488f99d-jq9p2   1/1     Running   0          65s
loki-read-0                    0/1     Running   0          64s
loki-read-1                    0/1     Running   0          64s
loki-read-2                    0/1     Running   0          64s
loki-write-0                   1/1     Running   0          65s
loki-write-1                   1/1     Running   0          64s
loki-write-2                   1/1     Running   0          64s
```

`loki-read-0` logs

```
level=warn ts=2023-03-06T21:54:19.210866952Z caller=loki.go:251 msg="per-tenant timeout not configured, using default engine timeout (\"5m0s\"). This behavior will change in the next major to always use the default per-tenant timeout (\"5m\")."
level=info ts=2023-03-06T21:54:19.212276733Z caller=main.go:103 msg="Starting Loki" version="(version=2.7.4, branch=HEAD, revision=98421b0c0)"
level=info ts=2023-03-06T21:54:19.213739074Z caller=server.go:323 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2023-03-06T21:54:19.215083615Z caller=memberlist_client.go:436 msg="Using memberlist cluster label and node name" cluster_label= node=loki-read-0-7df3ecfc
ts=2023-03-06T21:54:19.215121549Z caller=memberlist_logger.go:74 level=debug msg="configured Transport is not a NodeAwareTransport and some features may not work as desired"
level=debug ts=2023-03-06T21:54:19.308203015Z caller=tcp_transport.go:393 component="memberlist TCPTransport" msg=FinalAdvertiseAddr advertiseAddr=10.244.26.129 advertisePort=7946
level=debug ts=2023-03-06T21:54:19.308614184Z caller=tcp_transport.go:393 component="memberlist TCPTransport" msg=FinalAdvertiseAddr advertiseAddr=10.244.26.129 advertisePort=7946
level=info ts=2023-03-06T21:54:19.30881313Z caller=memberlist_client.go:543 msg="memberlist fast-join starting" nodes_found=1 to_join=4
level=warn ts=2023-03-06T21:54:19.309299807Z caller=cache.go:114 msg="fifocache config is deprecated. use embedded-cache instead"
level=warn ts=2023-03-06T21:54:19.309345108Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache - chunksembedded-cache"
level=info ts=2023-03-06T21:54:19.311697167Z caller=table_manager.go:262 msg="query readiness setup completed" duration=4.975µs distinct_users_len=0
level=info ts=2023-03-06T21:54:19.311751696Z caller=shipper.go:127 msg="starting index shipper in RO mode"
level=info ts=2023-03-06T21:54:19.311767232Z caller=shipper_index_client.go:78 msg="starting boltdb shipper in RO mode"
level=debug ts=2023-03-06T21:54:19.312371517Z caller=worker_service.go:146 msg="determining if querier is running as standalone target" runningStandalone=false queryFrontendEnabled=false queryScheduleEnabled=false readEnabled=true allEnabled=false
level=info ts=2023-03-06T21:54:19.312426652Z caller=worker.go:112 msg="Starting querier worker using query-scheduler and scheduler ring for addresses"
ts=2023-03-06T21:54:19.407514003Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
level=debug ts=2023-03-06T21:54:19.407574394Z caller=memberlist_client.go:549 msg="fast-joining node failed" node=loki-memberlist.mlops-monitoring.svc.cluster.local:7946 err="1 error occurred:\n\t* Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host\n\n"
level=warn ts=2023-03-06T21:54:19.40759394Z caller=memberlist_client.go:563 msg="memberlist fast-join finished" joined_nodes=0 elapsed_time=98.793005ms
level=info ts=2023-03-06T21:54:19.407616013Z caller=memberlist_client.go:576 msg="joining memberlist cluster" join_members=loki-memberlist.mlops-monitoring.svc.cluster.local:7946
ts=2023-03-06T21:54:19.413727781Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
level=warn ts=2023-03-06T21:54:19.413748477Z caller=memberlist_client.go:598 msg="joining memberlist cluster: failed to reach any nodes" retries=0 err="1 error occurred:\n\t* Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host\n\n"
ts=2023-03-06T21:54:21.213214027Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
level=warn ts=2023-03-06T21:54:21.213261866Z caller=memberlist_client.go:598 msg="joining memberlist cluster: failed to reach any nodes" retries=1 err="1 error occurred:\n\t* Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host\n\n"
ts=2023-03-06T21:54:24.282256359Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
level=warn ts=2023-03-06T21:54:24.282303225Z caller=memberlist_client.go:598 msg="joining memberlist cluster: failed to reach any nodes" retries=2 err="1 error occurred:\n\t* Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host\n\n"
ts=2023-03-06T21:54:31.816687175Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
level=warn ts=2023-03-06T21:54:31.816732314Z caller=memberlist_client.go:598 msg="joining memberlist cluster: failed to reach any nodes" retries=3 err="1 error occurred:\n\t* Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host\n\n"
ts=2023-03-06T21:54:43.696067525Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
level=warn ts=2023-03-06T21:54:43.696111687Z caller=memberlist_client.go:598 msg="joining memberlist cluster: failed to reach any nodes" retries=4 err="1 error occurred:\n\t* Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host\n\n"
ts=2023-03-06T21:55:13.43294643Z caller=memberlist_logger.go:74 level=warn msg="Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host"
level=warn ts=2023-03-06T21:55:13.432982566Z caller=memberlist_client.go:598 msg="joining memberlist cluster: failed to reach any nodes" retries=5 err="1 error occurred:\n\t* Failed to resolve loki-memberlist.mlops-monitoring.svc.cluster.local:7946: lookup loki-memberlist.mlops-monitoring.svc.cluster.local on 10.96.0.10:53: no such host\n\n"
ts=2023-03-06T21:56:00.43957937Z caller=memberlist_logger.go:74 level=debug msg="Initiating push/pull sync with:  10.244.19.6:7946"
ts=2023-03-06T21:56:00.441349415Z caller=memberlist_logger.go:74 level=debug msg="Initiating push/pull sync with:  10.244.29.207:7946"
ts=2023-03-06T21:56:00.442463915Z caller=memberlist_logger.go:74 level=debug msg="Initiating push/pull sync with:  10.244.26.130:7946"
level=info ts=2023-03-06T21:56:00.443111964Z caller=memberlist_client.go:595 msg="joining memberlist cluster succeeded" reached_nodes=3 elapsed_time=1m41.035495561s
ts=2023-03-06T21:56:16.313752588Z caller=memberlist_logger.go:74 level=debug msg="Initiating push/pull sync with: loki-write-2-d8f135d6 10.244.29.207:7946"
ts=2023-03-06T21:56:24.357785503Z caller=memberlist_logger.go:74 level=debug msg="Stream connection from=10.244.19.6:48954"
ts=2023-03-06T21:56:25.540185733Z caller=memberlist_logger.go:74 level=debug msg="Stream connection from=10.244.27.229:35654"
```

Below is my loki configmap,

```
apiVersion: v1
data:
  config.yaml: |
    auth_enabled: false
    common:
      compactor_address: 'loki-read'
      path_prefix: /var/loki
      replication_factor: 1
      storage:
        s3:
          bucketnames: loki-chunks
          insecure: false
          s3: http://minio:xxxx@minio-service.default.svc.cluster.local:9000
          s3forcepathstyle: true
    compactor:
      compaction_interval: 10m
      retention_delete_delay: 1m
      retention_delete_worker_count: 50
      retention_enabled: true
      shared_store: s3
      working_directory: /var/loki/retention
    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 168h
      split_queries_by_interval: 15m
    memberlist:
      join_members:
      - loki-memberlist.mlops-monitoring.svc.cluster.local:7946
    query_range:
      align_queries_with_step: true
    ruler:
      storage:
        s3:
          bucketnames: loki-ruler
          insecure: false
          s3: http://minio:xxxx@minio-service.default.svc.cluster.local:9000
          s3forcepathstyle: true
        type: s3
    runtime_config:
      file: /etc/loki/runtime-config/runtime-config.yaml
    schema_config:
      configs:
      - from: "2022-01-11"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v12
        store: boltdb-shipper
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
    storage_config:
      aws:
        s3: http://minio:xxx@minio-service.default.svc.cluster.local:9000/loki-admin
        s3forcepathstyle: true
      boltdb_shipper:
        shared_store: s3
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0
kind: ConfigMap
```
```[tasklist]

```
