### ISSUE TITLE
promtail kafka consumer support set offset

### ISSUE THREAD

**Issue by xxm404** [grafana/loki#8729]
**Is your feature request related to a problem? Please describe.**
I use promtail to read logs from kafka and write them to loki. When I modify the groupid of promtail, I can only re-consume historical logs once
OffsetNewest
OffsetOldest

**Describe the solution you'd like**
maybe promtail should support setting offset for users to skip history log
```
scrape_configs:
- job_name: nginxLog
  kafka:
    brokers:
    - brokers-1:4092
    - brokers-2:4092
    topics:
    - nginxLog
    start_from_newest: true
    group_id: promtail
```

**Describe alternatives you've considered**
Of course i can modify the offset of consumer group through the tools provided by kafka

**Additional context**
