### ISSUE TITLE
Loki cannot query logs from before the upgrade from 2.3 -> 2.7

### ISSUE THREAD

**Issue by mohit94ag** [grafana/loki#8738]
**Describe the bug**
We recently upgraded loki from version 2.3 -> 2.7. The upgrade was successful and we are able to query logs created after the upgrade but anything before that is not returned and there's no error in the logs/dashboard either making it harder for us to debug what might be the issue.

**Expected behavior**
Able to query logs from time before the upgrade

**Environment:**
 - Infrastructure: eks v1.24
 - Deployment tool: helm

Loki config 
```
# This tells loki to require the X-Scope-OrgID header when receiving log events.
    # promtail sets this to neeva-loki, with the net effect that this names the S3 directory
    # that holds all the logs.
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 0s
    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    limits_config:
      enforce_metric_name: false
    schema_config:
      configs:
      - from: 2021-11-05
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: loki_index_
          period: 24h
    storage_config:
      aws:
        s3: s3://us-west-2/neeva-shared-us-west-2
      boltdb_shipper:
        active_index_directory: /data/index
        shared_store: s3
        shared_store_key_prefix: neeva-loki/index/
        cache_location: /data/boltdb-cache
    compactor:
      working_directory: /data/compactor
      shared_store: s3
    server:
      http_listen_port: 3100
```
```[tasklist]

```
