### ISSUE TITLE
Ruler Remote Write Tenant overrides seg fault

### ISSUE THREAD

**Issue by owenhaynes** [grafana/loki#8751]
**Describe the bug**
When overriding remote write config for a tenant the reader will segfault after a few mins. Metrics do make it to the remote instance until the crash

```
level=info ts=2023-03-08T18:23:56.853312313Z caller=engine.go:199 component=ruler org_id=foomsg="executing query" type=instant query="sum by (namespace,app)(rate({namespace=~\".+\"} | json | __error__=\"\" |= \"\" | level=\"error\"[1m]))"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1a631b5]

goroutine 105683 [running]:
github.com/prometheus/prometheus/scrape.(*Manager).TargetsActive(0x0)
        /src/loki/vendor/github.com/prometheus/prometheus/scrape/manager.go:315 +0x55
github.com/prometheus/prometheus/storage/remote.(*MetadataWatcher).collect(0xc006b9c6e0)
        /src/loki/vendor/github.com/prometheus/prometheus/storage/remote/metadata_watcher.go:137 +0xad
github.com/prometheus/prometheus/storage/remote.(*MetadataWatcher).loop(0xc006b9c6e0)
        /src/loki/vendor/github.com/prometheus/prometheus/storage/remote/metadata_watcher.go:123 +0xba
created by github.com/prometheus/prometheus/storage/remote.(*MetadataWatcher).Start
````

**To Reproduce**
1.  Started Loki in two component mode (reader, writer) version 2.4.7 GCS Storage
2.  Have a recording rule setup for the tenant 
3.  Have global ruler write config something like 
```
      remote_write:
        enabled: true
        clients:
          prometheus-prometheus-stack-kube-prom-prometheus-0:
            name: prom-0
            url: http://prometheus-prometheus-stack-kube-prom-prometheus-0.prometheus-operated.monitoring:9090/prometheus/api/v1/write
          prometheus-prometheus-stack-kube-prom-prometheus-1:
            name: prom-1
            url: http://prometheus-prometheus-stack-kube-prom-prometheus-1.prometheus-operated.monitoring:9090/prometheus/api/v1/write
```
4. Add a tenant runtime override such as 
```
    overrides:
      "foo":
        deletion_mode: filter-and-delete
        retention_period: 2160h
        ruler_remote_write_disabled: false
        ruler_remote_write_config:
             prometheus-prometheus-stack-kube-prom-prometheus-0:
               name: prom-0
               url: hhttp://prometheus-prometheus-stack-kube-prom-prometheus-0.prometheus-operated.monitoring-foo:9090/prometheus/api/v1/write
            prometheus-prometheus-stack-kube-prom-prometheus-1:
              name: prom-1
              url: http://prometheus-prometheus-stack-kube-prom-prometheus-1.prometheus-operated.monitoring-foo:9090/prometheus/api/v1/write
```
5. wait a few mins and seg fault will happen

**Expected behavior**
Loki keeps running without crashing

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
