### ISSUE TITLE
Reduce S3 cost for PUT, COPY, POST, or LIST requests

### ISSUE THREAD

**Issue by marekvesely-direct** [grafana/loki#8756]
Hello,

i want to reduce S3 cost, because there are a lot of PUT, COPY, POST, or LIST requests. Is there some configuration to send less and bigger request. So not to send every log line, but i want to wait and send for example every 1 hour logs to S3 bucket. This will extremely reduce cost of S3 bucket for Loki storage. My configuration of Loki
```
# Ansible managed
# Config Wiki: https://grafana.com/docs/loki/latest/configuration/#server
---
auth_enabled: false

target: all

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  grpc_server_max_recv_msg_size: 131072000
  grpc_server_max_send_msg_size: 131072000

distributor:
  ring:
    kvstore:
      store: memberlist

querier:
  engine:
    timeout: 3m
  max_concurrent: 12

ingester_client:
  grpc_client_config:
    grpc_compression: snappy
    max_recv_msg_size: 1048576000
    max_send_msg_size: 1048576000

query_range:
  parallelise_shardable_queries: true # false increase RAM usage!!
# make queries more cache-able by aligning them with their step intervals
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
      # We're going to use the in-process "FIFO" cache
      enable_fifocache: true
      fifocache:
        size: 1024
        validity: 24h

storage_config:
  aws:
    s3: s3://***:***@eu-west-1
    bucketnames: cn-grafana
    s3forcepathstyle: true
    http_config:
      response_header_timeout: 15s
  boltdb_shipper:
    active_index_directory: /loki/active
    cache_location: /loki/cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: s3

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor
  shared_store: s3
  retention_enabled: true
  retention_delete_delay: 1h
  delete_request_cancel_period: 30m

ingester:
  chunk_idle_period: 1h
  chunk_block_size: 262144
  chunk_target_size: 8388608
  max_chunk_age: 1h
  chunk_retain_period: 30s
  max_transfer_retries: 0
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
    final_sleep: 0s
  wal:
    dir: /loki/wal

limits_config:
  retention_period: 168h
  deletion_mode: filter-and-delete
  max_entries_limit_per_query: 10000000
  max_queriers_per_tenant: 40
  max_global_streams_per_user: 5000000
  max_cache_freshness_per_query: 10m
  split_queries_by_interval: 15m
  max_query_parallelism: 5000
  max_query_series: 100000000
  ingestion_rate_strategy: global
  ingestion_rate_mb: 60
  ingestion_burst_size_mb: 100
  per_stream_rate_limit: 100MB
  per_stream_rate_limit_burst: 500MB
  reject_old_samples: true
  reject_old_samples_max_age: 12h
  query_timeout: 2m
  cardinality_limit: 10000000

query_scheduler:
  max_outstanding_requests_per_tenant: 10000

frontend_worker:
  grpc_client_config:
    grpc_compression: snappy
    max_recv_msg_size: 1048576000
    max_send_msg_size: 1048576000
  parallelism: 12

frontend:
  log_queries_longer_than: 5s
  compress_responses: true
  max_outstanding_per_tenant: 10000
  grpc_client_config:
    grpc_compression: snappy
    max_recv_msg_size: 1048576000
    max_send_msg_size: 1048576000

chunk_store_config:
  max_look_back_period: 0s

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
    - cn-grafana-1.triglav.local:7946
    - cn-loki-1.triglav.local:7946
    - cn-loki-2.triglav.local:7946
  max_join_backoff: 1m
  max_join_retries: 10
  min_join_backoff: 1s
```
Promtail config
```
---
server:
  http_listen_port: 9080
  grpc_listen_port: 9081

positions:
  filename: /srv/promtail/positions.yaml

clients:
  - url: http://cn-grafana.triglav.local:3100/loki/api/v1/push

scrape_configs:
  - job_name: bpm-processor
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
      - labels:
          level:
      - timestamp:
          format: "2006.01.02 15:04:05.999"
          source: timestamp
          location: "Europe/Prague"
    static_configs:
      - labels:
          company: insurance
          env: dev
          app_name: bpm-processor
          log_app: backend
          __path__: /var/log/app/bpm-processor-*/logs/actual/bpm-processor-*.log
        targets:
          - localhost
  - job_name: core-backend
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
      - labels:
          level:
      - timestamp:
          format: "2006.01.02 15:04:05.999"
          source: timestamp
          location: "Europe/Prague"
    static_configs:
      - labels:
          company: insurance
          env: dev
          app_name: core-backend
          log_app: backend
          __path__: /var/log/app/core-backend-*/logs/actual/core-backend-*.log
        targets:
          - localhost

---
server:
  http_listen_port: 9080
  grpc_listen_port: 9081

positions:
  filename: /srv/promtail/positions.yaml

clients:
  - url: http://cn-grafana.triglav.local:3100/loki/api/v1/push

scrape_configs:
  - job_name: postgres
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3}\s.{3})\s(?P<message>.*)$'
      - output:
          source: message
      - timestamp:
          format: "2006-01-02 15:04:05.999 MST"
          source: timestamp
          location: "Europe/Prague"
    static_configs:
      - labels:
          company: insurance
          env: dev
          log_app: database
          app_name: postgres
          __path__: /var/lib/pgsql/11/data/pg_log/postgresql-*.log
        targets:
          - localhost
```
Now i see in billing there are 24 millions of PUT, COPY, POST or LIST request, which is really expensive. If it PUT only once per hour, it is 720 request per month, so price will be minimal. Can you help me with this?
![obrazek](https://user-images.githubusercontent.com/56677711/223993794-b09554f4-0550-420f-8f84-b95cb31decce.png)
