### ISSUE TITLE
Support `query_range ` in Helm chart

### ISSUE THREAD

**Issue by FalconerTC** [grafana/loki#8772]
The Loki helm chart does not allow you to configure `cache_config`  (https://grafana.com/docs/loki/latest/configuration/#cache_config).  This would be very useful, particularly since the default config is deprecated
```
loki-read-1 loki level=warn ts=2023-03-10T14:30:47.687211579Z caller=cache.go:114 msg="fifocache config is deprecated. use embedded-cache instead"
loki-read-1 loki level=warn ts=2023-03-10T14:30:47.687240786Z caller=experimental.go:20 msg="experimental feature in use" feature="In-memory (FIFO) cache - chunksembedded-cache"
```

**Comment by FalconerTC** [comment]
I realize I misunderstood how the configuration works and that `cache_config` is a child config of `query_range`

**Comment by n-asenov** [comment]
You should be able to customize the `query_range` config under the `loki.structuredConfig` key
```yaml
loki:
  structuredConfig:
    query_range:
      align_queries_with_step: false
```

**Comment by julian-waibel** [comment]
@n-asenov: Thank you, it worked. Here is the full code in case someone is interested.

```yaml
loki:
  # As of Loki Helm chart v5.35.0, the following settings can only be set via this `structuredConfig` block
  structuredConfig:
    query_range:
      cache_results: true
      results_cache:
        cache:
          # `fifocache` has been renamed to `embedded-cache` in Loki v2.7 and is deprecated since
          enable_fifocache: false
          embedded_cache:
            enabled: true
            max_size_mb: 1024
            ttl: 24h
    chunk_store_config:
      chunk_cache_config:
        # `fifocache` has been renamed to `embedded-cache` in Loki v2.7 and is deprecated since
        enable_fifocache: false
        embedded_cache:
          enabled: true
          max_size_mb: 512
          ttl: 24h
```
