### ISSUE TITLE
Timestamp of loki's own log is UTC but local time

### ISSUE THREAD

**Issue by duj4** [grafana/loki#8780]
**Describe the bug**
Timestamp of loki's own log is UTC.

**To Reproduce**
1. Started Loki and check the output

**Expected behavior**
It should be set with the local time.

**Environment:**
 - RHEL 8

**Screenshots, Promtail config, or terminal output**

**Comment by duj4** [comment]
![Snipaste_2023-03-13_10-37-02](https://user-images.githubusercontent.com/19278537/224595935-441b8b57-4427-4165-959e-758eb3003443.png)

**Comment by niluan304** [comment]
try to declare timezone in config,
for example:
```yaml
    - timestamp:
        source: time
        format: '2006-01-02 15:04:05.000'
        location: "Asia/Shanghai"

```
