### ISSUE TITLE
Promtail crashes in compress/gzip.(*Reader)

### ISSUE THREAD

**Issue by juissi-t** [grafana/loki#8784]
**Describe the bug**

We are running promtail version 2.7.4 and the pods sometimes crash with this error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x280 pc=0x61570e]

goroutine 3822006 [running]:
compress/gzip.(*Reader).Read(0x2c?, {0xc001d8f000?, 0x4?, 0x1?})
        /usr/local/go/src/compress/gzip/gunzip.go:247 +0x2e
bufio.(*Scanner).Scan(0xc0033d9f28)
        /usr/local/go/src/bufio/scan.go:214 +0x876
github.com/grafana/loki/clients/pkg/promtail/targets/file.(*decompressor).readLines(0xc000868e60)
        /src/loki/clients/pkg/promtail/targets/file/decompresser.go:198 +0x838
created by github.com/grafana/loki/clients/pkg/promtail/targets/file.newDecompressor
        /src/loki/clients/pkg/promtail/targets/file/decompresser.go:96 +0x58a
```

These two log lines seem to happen before the crash, with always different files mentioned:

```
ts=2023-03-10T00:44:37.924440049Z caller=log.go:168 level=info msg="Re-opening moved/deleted file /var/log/pods/monitoring_datadog-jz55r_15df45c3-a7ef-41db-a6a9-eaf7f2d4ead8/agent/0.log ..."
ts=2023-03-10T00:44:37.92448151Z caller=log.go:168 level=info msg="Successfully reopened /var/log/pods/monitoring_datadog-jz55r_15df45c3-a7ef-41db-a6a9-eaf7f2d4ead8/agent/0.log"
```

**To Reproduce**
1. Run promtail version 2.7.4 on Kubernetes
2. Ship logs to a Loki instance running in another cluster
3. Wait a few days, some promtails crash every now and then

**Expected behavior**
No crashes.

**Environment:**
 - Infrastructure: Kubernetes, EKS 1.22 with Bottlerocket instances
 - Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**
Promtail config:

```yaml
server:
  log_level: info
  http_listen_port: 3101
  
clients:
  - external_labels:
      cluster: abc-dev
    url: https://loki-gateway.internal.abc.xyz/loki/api/v1/push

positions:
  filename: /run/promtail/positions.yaml

scrape_configs:
  # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
  - job_name: kubernetes-pods
    pipeline_stages:
      - cri: {}
      - docker: {}
      - match:
          selector: '{app="eventrouter"}'
          stages:
          - json:
              expressions:
                namespace: event.metadata.namespace
          - labels:
              namespace: null
      - match:
          selector: '{job=~"ingress-nginx/(external|internal)"}'
          stages:
          - regex:
              expression: ^(?P<remote_addr>[\w\.]+) - (?P<remote_user>[^ ]*) \[(?P<time_local>.*)\]
                \"(?P<method>[^ ]*) (?P<request>[^ ]*) (?P<protocol>[^ ]*)\" (?P<status>[\d]+)
                (?P<body_bytes_sent>[\d]+) \"(?P<http_referer>[^\"]*)\" \"(?P<http_user_agent>[^\"]*)\"?
                (?P<request_length>[^ ]*) (?P<request_time>[^ ]*) \[(?P<service>[^ ]*)\].*
          - labels:
              service: null
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels:
          - __meta_kubernetes_pod_controller_name
        regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
        action: replace
        target_label: __tmp_controller_name
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_name
          - __meta_kubernetes_pod_label_app
          - __tmp_controller_name
          - __meta_kubernetes_pod_name
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: app
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_instance
          - __meta_kubernetes_pod_label_release
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: instance
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_component
          - __meta_kubernetes_pod_label_component
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: component
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - namespace
        - app
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        regex: true/(.*)
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
        - __meta_kubernetes_pod_container_name
        target_label: __path__
  
  - job_name: journal
    journal:
      path: /var/log/journal
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/{*.log,messages,secure,dmesg/*,aws-routed-eni/*,support/*}
  
limits_config:
```
