### ISSUE TITLE
promtail docker image doesn't support journald

### ISSUE THREAD

**Issue by vukor** [grafana/loki#882]
**Describe the bug**
promtail docker image doesn't support journald.

**To Reproduce**
1. Started promtail ("grafana/promtail:v0.2.0") with config:
```
# cat /etc/promtail/promtail.yaml
client:
  backoff_config:
    maxbackoff: 5s
    maxretries: 5
    minbackoff: 100ms
  batchsize: 102400
  batchwait: 1s
  external_labels:
    cluster: elasticsearch
  timeout: 10s
positions:
  filename: /run/promtail/positions.yaml
server:
  http_listen_port: 3101
target_config:
  sync_period: 10s

scrape_configs:
- job_name: journal
  journal:
    labels:
      system_job: systemd-journal
    path: /var/log/journal
  relabel_configs:
  - source_labels:
    - __journal__systemd_unit
    target_label: system_unit
  - source_labels:
    - __journal_priority
    target_label: system_priority
  - source_labels:
    - __journal__hostname
    target_label: system_hostname
  - source_labels:
    - __journal__transport
    target_label: system_transport
  - action: drop
    regex: .+
    source_labels:
    - __journal__audit_id
```

**Expected behavior**
Promtail send journald logs to loki.

**Environment:**
 - Infrastructure: Kubernete 1.13.9
 - Deployment tool: helm

**Terminal output**
Promtail log:
```
level=info ts=2019-08-12T04:48:57.35004952Z caller=kubernetes.go:192 component=discovery discovery=k8s msg="Using pod service account via in-cluster config"
8/12/2019 11:48:57 AM level=warn ts=2019-08-12T04:48:57.350921203Z caller=journaltargetmanager.go:24 msg="WARNING!!! Journal target manager initialized on platform without Journal support!"
8/12/2019 11:48:57 AM level=info ts=2019-08-12T04:48:57.353399761Z caller=server.go:120 http=[::]:3101 grpc=[::]:9095 msg="server listening on addresses"
8/12/2019 11:48:57 AM level=info ts=2019-08-12T04:48:57.353629724Z caller=main.go:55 msg="Starting Promtail" version="(version=v0.2.0, branch=HEAD, revision=321b928c)"
```

**My workaround**
As temporary solution I build image and use custom image from next dockerfile:
```
FROM grafana/loki-build-image:latest as builder
WORKDIR /go/src/github.com/grafana
RUN git clone https://github.com/grafana/loki.git
WORKDIR /go/src/github.com/grafana/loki
RUN GOOS=linux go build -o promtail ./cmd/promtail

FROM debian:stable-slim
RUN apt-get update && \
    apt-get install ca-certificates tzdata -y && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /go/src/github.com/grafana/loki/promtail /usr/bin/promtail
ENTRYPOINT ["/usr/bin/promtail"]
```

It would be wonderful if upstream docker image will support journald. Thanks you guys for your work.
