### ISSUE TITLE
Fail to connect to loki as grafana datasource, if instance was started with `target: read`

### ISSUE THREAD

**Issue by smoos** [grafana/loki#8827]
**Describe the bug**
When trying to configure a loki `target:read` instance as datasource for grafana, I get the following error messages
```
logger=context userId=1 orgId=1 uname=admin t=2023-03-17T14:39:48.469587535Z level=error msg="Failed to call resource" error="rpc error: code = Unimplemented desc = unknown service logproto.Querier\n" traceID=
```

**To Reproduce**
1. Deploy Loki (2.7.4) into k8s Cluster using [single scalable deployment](https://grafana.com/docs/loki/latest/fundamentals/architecture/deployment-modes/) setup.
2. Configure grafana datasource pointing to `loki_read_service`
3. Query: `{} term`

**Expected behavior**
Showing the logs, which were shipped to loki

**Environment:**
 - Infrastructure: Kubernetes (1.25.6), Grafana (9.4.3)
 - Deployment tool: kustomize and kubectl apply -f

**Screenshots, Promtail config, or terminal output**
Grafana GUI:

![logproto-querier-2023-03-17_15-38](https://user-images.githubusercontent.com/4271570/225937519-db1925dc-5b7b-4603-ab28-03fbaf5e9a66.png)

We deployed the following setup (I shortend out the uninteressting bits) as stateful set in a kubernetes cluster:

```yaml
[...]
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: read
          image: grafana/loki:2.7.4
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/loki/config/loki.yaml
            - -target=read
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-memberlist
              containerPort: 7946
              protocol: TCP
[...]
---
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: write
          image: grafana/loki:2.7.4
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/loki/config/loki.yaml
            - -target=write
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: http-memberlist
              containerPort: 7946
              protocol: TCP

```
These are the services pointing at those two replicasets:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: loki_read_service
  labels:
    app.kubernetes.io/version: 2.7.4
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki_instance_handle
    app.kubernetes.io/component: read

spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 3100
      targetPort: http-metrics
      protocol: TCP
    - name: grpc
      port: 9095
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki_instance_handle
    app.kubernetes.io/component: read
---
apiVersion: v1
kind: Service
metadata:
  name: loki-memberlist
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki_instance_handle
    app.kubernetes.io/component: read
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp
      port: 7946
      targetPort: http-memberlist
      protocol: TCP
  selector:
    app.kubernetes.io/instance: loki_instance_handle
```

Grafana is part of the kubernetes cluster, hence no ingress is needed here.

If I user `target:all` instead of `target:read` (i.e. having three instances `target:all` plus 3 instances `target:write`). Everything works fine.

@DylanGuedes allready offered some help and insight and suspects a wrongly configured service, but I didn't change any service routing, only the target.

I'm willing to debug further into this issue, but I need some help to do so.

Thanks in advance,
sebastian
