### ISSUE TITLE
Promtail: can't replcae `level=DEBU` to `level=debug`

### ISSUE THREAD

**Issue by niluan304** [grafana/loki#8868]
**Describe the bug**
Here are some logs:

```log
2023-03-21 09:34:53.998 [INFO] swagger ui is serving at address: http://127.0.0.1:8180/swagger/
2023-03-21 09:34:54.001 [DEBU] {f42c68674a4b4e178559bb682711750b} [ 11 ms] [default] [exam_dev_pi] [rows:1  ] SELECT * FROM 
```

I try to add a stage for  replacing `level=DEBU` to `level=debug` , but it didn't work:

```yaml
    pipeline_stages:
    - regex:
        expression: '(?P<time>^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) \[(?P<level>[A-Z]+)\](?:\s+{(?P<trace>\w*)})? (?P<msg>(.|\n)*$)'

    - replace:
        expression: "(DEBU)"
        source: level
        replace: "debug"
```

**Related Issues**
#7944, #8344

**To Reproduce**
1. Started Loki (docker  image: grafana/loki:2.7.3)
2. Started Promtail 
   1. docker version
      -  image: grafana/promtail:2.7.3 (amd64)
      - command:  `-config.file=/etc/promtail/config.yml`
   2. window10 version
      - version: 2.7.3
      - powershell command: `./promtail.exe '-config.file=./config.yml'`
3. Add Log

   set log file’ path and run `main.go`

 ```go
package main

import (
	"context"
	"github.com/gogf/gf/v2/os/glog"
	"time"
)

func main() {
	var logger = glog.New()
	logger.SetPath("/var/log") // log file's path

	for {
		Log(context.TODO(), logger)
		time.Sleep(time.Minute * 1)
	}
}

func Log(ctx context.Context, logger *glog.Logger) {
	defer func() { _ = recover() }()

	logger.Debug(ctx, "Debug Level")
	logger.Info(ctx, "Info Level")
	logger.Error(ctx, "Error Level")
	logger.Critical(ctx, "Critical Level")
	logger.Panic(ctx, "Panic Level")
}
 ```

**Expected behavior**

See  `level=debug`, `level=error` in grafana instead of `unknown`

![image-20230320133045059](https://user-images.githubusercontent.com/51920864/226263685-12664701-f89f-4c5d-a71f-428d657e7164.png)

**Environment:**

- Infrastructure: Docker
- Deployment tool: compose

**Screenshots, Promtail config, or terminal output**

https://github.com/grafana/loki/blob/183fe85f1cc27ad59e8c092f50b3fc531b97271f/clients/pkg/logentry/stages/replace.go#L142-L154

print the  value of `r.cfg` and `result` , get this:

- label `level`

```log
r.cfg : {"Expression":"(DEBU)","Source":"level","Replace":"debug"}
source: DEBU
result: debug
```

- label `tarce`

```log
r.cfg : {"Expression":"([a-z]{4})","Source":"trace","Replace":"TEST"}
source: 88bcbd7177b34e17ae5c5445c5a4a5ec
result: 88TEST7177b34e17ae5c5445c5a4a5ec
```

- label `msg`

```log
r.cfg : {"Expression":"(http://127.0.0.1)","Source":"msg","Replace":"http://192.168.32.132"}
source: swagger ui is serving at address: http://127.0.0.1:8180/swagger/
result: swagger ui is serving at address: http://192.168.32.132:8180/swagger/
```

In grafana, I successfully modify label `msg`, but fail in label `level`,  `tarce`.

- Promtail config:

```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0
 
positions:
  filename: /var/promtail/positions.yml
 
clients:
  - url: http://192.168.32.71:3100/loki/api/v1/push

scrape_configs:
  - job_name: 132-exam
    static_configs:
    - labels:
        job: 132-exam
        dir: app
        __path__: /var/log/*.log
        
    pipeline_stages:
    - multiline:
        firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}'
        max_wait_time: 3s

    - regex:
        expression: '(?P<time>^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) \[(?P<level>[A-Z]+)\](?:\s+{(?P<trace>\w*)})? (?P<msg>(.|\n)*$)'

    - labels:
        time:
        level:
        trace:

    - timestamp:
        source: time
        format: '2006-01-02 15:04:05.000'
        location: "Asia/Shanghai"
    
    - replace:
        expression: "(DEBU)"
        source: level
        replace: "debug"

    - replace:
        expression: "(ERRO)"
        source: level
        replace: "error"

    - replace:
        expression: '([a-z]{4})'
        source: trace
        replace: "TEST"

    - replace:
        expression: '(http://127.0.0.1)'
        source: msg
        replace: "http://192.168.32.132"

    - output:
        source: msg
```

**Comment by niluan304** [comment]
My answer: using `replace` stage  before `regex` stage

```yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0
 
positions:
  filename: /var/promtail/positions.yml
 
clients:
  - url: http://192.168.32.71:3100/loki/api/v1/push

scrape_configs:
  - job_name: 132-exam
    static_configs:
    - labels:
        job: 132-exam
        dir: app
        __path__: /var/log/*.log
        
    pipeline_stages:
    - multiline:
        firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}'
        max_wait_time: 3s
    
    - replace:
        expression: '(\[DEBU\])'
        replace: "[DEBUG]"

    - replace:
        expression: '(\[ERRO\])'
        replace: "[ERROR]"

    - regex:
        expression: '(?P<time>^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}) \[(?P<level>[A-Z]+)\](?:\s+{(?P<trace>\w*)})? (?P<msg>(.|\n)*$)'

    - labels:
        time:
        level:
        trace:

    - timestamp:
        source: time
        format: '2006-01-02 15:04:05.000'
        location: "Asia/Shanghai"

    - replace:
        expression: '(http://127.0.0.1)'
        source: msg
        replace: "http://192.168.32.132"

    - output:
        source: msg
```
