### ISSUE TITLE
Metrics recorded by Ruler are different from the original results (with no delay)

### ISSUE THREAD

**Issue by 17billion** [grafana/loki#8892]
**Describe the bug**

Metrics recorded by Ruler are similar to the original results but not identical, with some unexplained points.
![스크린샷 2023-03-24 오전 10 25 51](https://user-images.githubusercontent.com/28832461/227405585-4344ba1e-0736-43d1-9356-0bfb8fd2bcbf.png)
**Note that there is almost no delay in the pipeline.**

1. In the figure, the results from **Prometheus-infra-(Notify for alerts failed)(Yellow of the below grafana)** should be recorded every five minutes, but when using Ruler(Green of the top grafana), the results are irregular as shown in the figure.

2. It seems that the timing of Ruler calling the query results in slightly different results. How can I make the results appear every minute on the dot, for example, taking the results from the last minute of 13:03:00 ~ 13:03:59 when Ruler executed the query at 13:04:23? Currently, when Ruler executes the query at 13:04:23, it seems to take the results from 13:03:23 ~ 13:04:22 and record them as metrics. 

Lastly, is there any further feedback on this issue at https://github.com/grafana/loki/issues/4909? I have found that in some cases, different delays need to be set.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Loki version : 2.6.1
 - Grafana version : 9.2.5
 - Prometheus version : 2.40.1

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
```
...
limits_config:
  ruler_evaluation_delay_duration: 1m
...
ruler:
  enable_api: true
  enable_sharding: true
  storage:
    type: s3
    s3:
      s3: s3:/xxx
      bucketnames: xxx
  rule_path: /tmp/loki/scratch
  wal:
    dir: /var/loki/ruler-wal
  ring:
    kvstore:
      store: memberlist
  remote_write:
    enabled: true
    client:
      url: http://xxx/api/v1/write
```

recording rule (in grafana)
![recording rule](https://user-images.githubusercontent.com/28832461/227407092-5a5fa3cd-ce59-487a-83bf-17819d6fea5f.png)
![recording rule 2](https://user-images.githubusercontent.com/28832461/227407100-19cadec6-90c5-49be-9dfe-de59bebb337a.png)

normal query
![normal query](https://user-images.githubusercontent.com/28832461/227407122-42321fe8-c116-4c8d-9f69-390e5577612e.png)
