### ISSUE TITLE
server returned HTTP status 500 Internal Server Error (500): at least 2 live replicas required,  could only find 1

### ISSUE THREAD

**Issue by mhellsten** [grafana/loki#8899]
**Describe the bug**
Helm deployment results in grafana-agent not being able to write logs

**To Reproduce**
values.yaml:
```
loki:
  auth_enabled: false
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules

monitoring:
  rules:
    enabled: false
    alerting: false
  serviceMonitor:
    enabled: false
  lokiCanary:
    enabled: false

singleBinary:
  replicas: 1
```

**Expected behavior**
Should record logs without errors. I've tried bumping single-binary replicas to 2, but that didn't make a difference... and it's unclear why that'd be required anyway.

**Environment:**
 - Infrastructure: Kubernetes 1.23.16, kubeadm, bare metal
 - Deployment tool: helm
 - Chart version: 4.8.0

**Screenshots, Promtail config, or terminal output**
single-binary log:
```
level=warn ts=2023-03-26T05:33:13.934459395Z caller=logging.go:86 traceID=0b676f56f12de8d0 orgID=fake msg="POST /loki/api/v1/push (500) 1.99939ms Response: \"at least 2 live replicas required, could only find 1\\n\" ws: false; Content-Length: 32883; Content-Type: application/x-protobuf; User-Agent: GrafanaAgent/; "
```
grafana-agent log:
```
ts=2023-03-26T05:34:09.506259225Z caller=client.go:366 level=warn component=logs logs_config=loki/loki component=client host=loki.loki.svc.cluster.local:3100 msg="error sending batch, will retry" status=500 error="server returned HTTP status 500 Internal Server Error (500): at least 2 live replicas required, could only find 1"
```
Any ideas? Thanks!

**Comment by vlad-diachenko** [comment]
You need to set 'replication_factor' to 1

**Comment by vlad-diachenko** [comment]
> @vlad-diachenko Why `replication_factor` needs to be set to 1. Is more than 1 not supported?

supported. and it's recommended to set it to 3. but it means that you have to run 3 instances at least. and at least 2 replicas must be active in the ring.

**Comment by xi2656-akhanna** [comment]
> > @vlad-diachenko Why `replication_factor` needs to be set to 1. Is more than 1 not supported?
> 
> supported. and it's recommended to set it to 3. but it means that you have to run 3 instances at least. and at least 2 replicas must be active in the ring.

What is this `replication_factor`?

**Comment by abhijaypatne** [comment]
> > > @vlad-diachenko Why `replication_factor` needs to be set to 1. Is more than 1 not supported?
> > 
> > 
> > supported. and it's recommended to set it to 3. but it means that you have to run 3 instances at least. and at least 2 replicas must be active in the ring.
> 
> What is this `replication_factor`?

It's a setting in the `values.yaml`

```
loki:
  # set if you have only 1 replica
  commonConfig:
    replication_factor: 1

```
