### ISSUE TITLE
Multiline block isn't populated as expected

### ISSUE THREAD

**Issue by TimJongerius** [grafana/loki#8906]
**Describe the bug**
I'm trying to add the stacktrace of a log message to the multiline block. WIthout the multiline stage I see each line seperated as expected. When I add the multiline stage as shown below I can only see the firstline but the stacktrace doesn't seem to be logged at all.

**To Reproduce**

Run promtail chart version 6.9.3 on Azure AKS Kubernetes Version 1.23.8
Ship logs to a Loki instance
Query logs with grafana

**Expected behavior**
Have the stacktrace in multiline block

**Environment:**

    Infrastructure: Kubernetes, AKS with linux nodes
    Deployment tool: Helm

**Screenshots, Promtail config, or terminal output**

Original log file output from kubernetes node:

> 2023-03-27T09:47:13.584782998Z stdout F [09:47:13 ERR] Response status code does not indicate success: 500 (Internal Server Error).
2023-03-27T09:47:13.584811698Z stdout F Refit.ApiException: Response status code does not indicate success: 500 (Internal Server Error).
2023-03-27T09:47:13.584817198Z stdout F    at Refit.RequestBuilderImplementation.<>c__DisplayClass14_0`2.<<BuildCancellableTaskFuncForMethod>b__0>d.MoveNext() in /_/Refit/RequestBuilderImplementation.cs:line 313
2023-03-27T09:47:13.584822499Z stdout F --- End of stack trace from previous location ---
2023-03-27T09:47:13.584827599Z stdout F    at Company.Product.Provider.FunctionProvider.GetFunctionByMaterial(List`1 materialList, DateTime from, DateTime to) in /src/Company.Product/Provider/FunctionProvider.cs:line 105
2023-03-27T09:47:13.584832299Z stdout F    at Company.Product.Provider.FunctionProvider.GetFunctionPerMonth(DateTime from, DateTime to, List`1 materialList, List`1 merkmalList) in /src/Company.Product/Provider/FunctionProvider.cs:line 75
2023-03-27T09:47:13.584837599Z stdout F    at Company.Product.Provider.FunctionProvider.FetchFunction(List`1 materialList, List`1 merkmalList, Int32 maxYearCount) in /src/Company.Product/Provider/FunctionProvider.cs:line 62
2023-03-27T09:47:13.584845599Z stdout F    at Company.Product.Provider.FunctionProvider.GetOctoApiFunction() in /src/Company.Product/Provider/FunctionProvider.cs:line 34
2023-03-27T09:47:13.584863299Z stdout F    at Company.Product.WorkerBackgroundService.FunctionUpdateBackgroundService.DoWorkAsync(CancellationToken cancellationToken) in /src/Company.Product/WorkerBackgroundService/FunctionUpdateBackgroundService.cs:line 40

Promtail configuration:
```yaml
    pipelineStages:
      - cri: {}
      - match:
          selector: '{namespace="applications"}'
          stages:
          - multiline:
              firstline: "^\\[\\d{1,2}:\\d{2}:\\d{2} \\S+?\\]"
          - regex:
              expression: "^(?s)\\[(?P<ts>\\d{1,2}:\\d{2}:\\d{2}) (?P<level>\\S+?)\\] (?P<clearcontent>.*)$"
              source: content
          - labels:
              apptime: ts
              level:
          - output:
              source: clearcontent
```

Log on grafana dashboard:

On the grafana dashboard I only see the first line. I can also see that the cri, regex, labels and output stages are working as expected.

![grafik](https://user-images.githubusercontent.com/106235768/227925365-55c1b439-8299-4b9a-b1e9-22678b6b24eb.png)
