### ISSUE TITLE
Grafana cannot query loki logs

### ISSUE THREAD

**Issue by fsckzy** [grafana/loki#8915]
my env：
```
docker version : 19.03.0
loki/promtail: 2.74
grafana : 9.4.3
```

The loki configuration file is as follows
```yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /data/loki
  storage:
    filesystem:
      chunks_directory: /data/loki/chunks
      rules_directory: /data/loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093
```

The promtail configuration file is as follows:
```yaml
# Promtail Server Config
server:
  http_listen_port: 9080
  grpc_listen_port: 0

# Positions
positions:
  filename: /tmp/positions.yaml

# Loki服务器的地址
clients:
  - url: http://192.168.201.171:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          host: localhost
          __path__: /var/lib/docker/containers/*/*.log
```
You can see that the data directory of loki already has 1.9 G
```shell
[root@k8sn2 loki]# du -sh *
124K	boltdb-shipper-active
0	boltdb-shipper-cache
1.9G	chunks
0	compactor
0	index
0	rules
4.6M	wal
```
I'm sure the loki data source is ok。
![image](https://user-images.githubusercontent.com/34021474/228148808-1128f66a-a432-4021-9290-d3090aa01f0c.png)

But when I query in grafana, it prompts me: 
![image](https://user-images.githubusercontent.com/34021474/228148682-f4f60aa4-79a7-4d97-a6bc-fe0c666e1699.png)

> Label browser

No labels found.

why?
