### ISSUE TITLE
positions.yaml is create with 700 mode

### ISSUE THREAD

**Issue by Poil** [grafana/loki#892]
Hi,

On fresh installation, the positions.yaml file is create with 700 mode. Not needed to be an executable file.

Config
```
clients:
- url: http://tlslog-p01.engsec:3100/api/prom/push
positions:
  filename: /var/lib/promtail/positions.yaml
scrape_configs:
- job_name: journal
  journal:
    labels:
      job: systemd-journal
    path: /run/log/journal
  relabel_configs:
  - source_labels:
    - __journal__systemd_unit
    target_label: unit
server:
  grpc_listen_port: 0
  http_listen_port: 9080
```

SystemD unit-file
```
[Unit]
Description = Promtail Server
After = network-online.target

[Service]
User = promtail
Restart = on-failure
ExecStart = /opt/promtail/promtail -config.file /opt/promtail/promtail.yml

[Install]
WantedBy = multi-user.target
```

Best regards
