### ISSUE TITLE
Can't configure tls_min_version

### ISSUE THREAD

**Issue by AleksandrAksenov** [grafana/loki#8933]
**Describe the bug**
I try to configure TLS version for http_tls_config. When I do it I get the error:
```
failed parsing config: /etc/loki/config.yaml: yaml: unmarshal errors:
line 18: field tls_min_version not found in type server.TLSConfig
```

I use next configuration for the server section
```
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: warn
  http_tls_config:
    cert_file: /cert.crt
    key_file: /key.key
    tls_min_version: VersionTLS12
```

**To Reproduce**
1. Make configuration for server as below
2. Start Loki: loki, version 2.7.4 (branch: HEAD, revision: 98421b0c0)

**Expected behavior**
The server should use TLS version 1.2

**Environment:**
 - Infrastructure: EC2 instance
 - Deployment tool: on bare metal with systemd unit
 ```
[Unit]
Description=Loki service
After=network.target

[Service]
Type=simple
User=loki
Group=loki
ExecStart=/usr/local/bin/loki -config.file /etc/loki/config.yaml

[Install]
WantedBy=multi-user.target
```
