### ISSUE TITLE
Unpack parsing bug: "could not write JSON response"

### ISSUE THREAD

**Issue by the-voidl** [grafana/loki#8936]
**Describe the bug**
Queries fail when a certain log line is within the query and the unpack parser is used.

We couldn't find out exactly which format the log line has to have for Loki to fail - first we thought it might depend on our logs scheme but it also occurs with  third party tools as probot.

**To Reproduce**
The error occurs when
1. unpack is used
2. a specific log line is within the query result

This can be archived through filtering out that much of the stream that the corrupt line slips into the query range or by increasing the time range until the query fails.

![image](https://user-images.githubusercontent.com/63976048/228274644-e32e9daa-65e1-4e25-a97e-7e5f8d99dde3.png)

Using the grafana builtin "Prettify JSON" after using `| json`  detects the questionable fields as intended and does not throw an error as `unpack` does.

We tried to reproduce the error and found that UnpackParser can't handle some json keys while JsonParser can do so by replacing some chars with an underline. E.g. if the key contains one of `:.-`
There might also be problems with memory handling in `nextKeyPrefix`, respecting the error messages we got.

```bash
{namespace="npay-backend"}
    | line_format `{"foo-buzz":"bar","_entry":"{\"a\":\"1\"}" }` #does not work
    | line_format `{"foo.buzz":"bar","_entry":"{\"a\":\"1\"}" }` #does not work
    | line_format `{"foo:buzz":"bar","_entry":"1" }`             #does not work
    | line_format `{"foo_buzz":"bar","_entry":"{\"a\":\"1\"}" }` #works
    | line_format `{"foo_buzz":"bar","_entry":"1" }`             #works
    | unpack
```

Replacing `unpack` by `json` in above query fixes the issue in these cases.

**Most observed error messages:**
```
could not write JSON response: 1:125: parse error: unexpected "," in label set, expected "="
could not write JSON response: 1:2: parse error: unexpected string "\":\"" in label set, expected identifier or "}"
could not write JSON response: 1:62: parse error: unexpected string "\"MessageTe"... in label set, expected identifier or "}"
could not write JSON response: 1:2: parse error: unexpected character inside braces: '8'
could not write JSON response: 1:155: parse error: unexpected character inside braces: '\\'
could not write JSON response: 1:2: parse error: unknown escape sequence U+003D '='
error decoding response: Value looks like object, but can't find closing '}' symbol (bearbeitet) 
```

**Expected behavior**
We expect unpack to work as intended and parse the nested _entry field as json.

-----

**Environment:**
Grafana Cloud Loki
Selfhosted Grafana 9.4.7
Promtail 2.7.5 (also tried 2.7.4)
Clusters mostly in Google Kubernetes Engine
First observed: 28.03.2023

**Promtail config**
<details>

```yaml
[...]
          - match:
              selector: '{namespace="gke-deploy",container="gke-deploy"}'
              stages:
              - json:
                  expressions:
                    module: "name"
                    Message: msg
                    level:
                  source: jsonPayload
              - replace:
                  expression: '(30)'
                  replace: INFO
                  source: level
              - replace:
                  expression: '(50)'
                  replace: ERROR
                  source: level
          - pack:
              labels:
                - container
                - pod
                - k8s_module
                - k8s_app
                - jsonPayload
                - Message
                - MessageTemplate
```

</details>

**Logs from the screenshot** (Beautified)
<details><summary>First logline</summary>

```json
{
  "insertId": "aqbqaxqs44f7yn5r",
  "jsonPayload": {
    "hostname": "gke-deploy-deployment-0",
    "level": 50,
    "msg": "Deployment log:  Warning: Autopilot increased resource requests for StatefulSet monitoring/kube-state-metrics to meet requirements. See http://g.co/gke/autopilot-resources\n",
    "name": "probot",
    "pid": 25,
    "v": 0
  },
  "labels": {
    "compute.googleapis.com/resource_name": "gk3-xxxxxxxxxxx",
    "k8s-pod/app": "gke-deploy",
    "k8s-pod/controller-revision-hash": "gke-deploy-deployment-854d749989",
    "k8s-pod/statefulset_kubernetes_io/pod-name": "gke-deploy-deployment-0"
  },
  "logName": "projects/xxxxxx/logs/stdout",
  "receiveTimestamp": "2023-03-28T13:15:53.982474097Z",
  "resource": {
    "labels": {
      "cluster_name": "xxxxxxxxxx",
      "container_name": "gke-deploy",
      "location": "europe-west3",
      "namespace_name": "gke-deploy",
      "pod_name": "gke-deploy-deployment-0",
      "project_id": "xxxxxxx"
    },
    "type": "k8s_container"
  },
  "timestamp": "2023-03-28T13:15:52.458Z"
}
```

</details>
