### ISSUE TITLE
[loki-distributed] It seems that Query Frontend cannot recognize querier component

### ISSUE THREAD

**Issue by kworkbee** [grafana/loki#8937]
Hi, I'm getting trouble with components related to querier / query frontend.

I set loki up using `loki-distributed` chart, after it deployed, it seems that query frontend cannot recognize querier component. The log of query frontend shows like below:
```
level=info ts=2023-03-29T09:26:12.128448634Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
34
level=info ts=2023-03-29T09:26:22.127687877Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
33
level=info ts=2023-03-29T09:26:32.12811141Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
32
level=info ts=2023-03-29T09:26:42.128383354Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
31
level=info ts=2023-03-29T09:26:49.334831155Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
30
level=info ts=2023-03-29T09:26:52.128180318Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
29
level=info ts=2023-03-29T09:27:02.127360467Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
28
level=info ts=2023-03-29T09:27:12.128124334Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
27
level=info ts=2023-03-29T09:27:22.127456996Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
26
level=info ts=2023-03-29T09:27:32.127609597Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
25
level=info ts=2023-03-29T09:27:42.128299241Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
24
level=info ts=2023-03-29T09:27:52.127494557Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
23
level=info ts=2023-03-29T09:28:02.127835811Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
22
level=info ts=2023-03-29T09:28:09.334952283Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
21
level=info ts=2023-03-29T09:28:12.127634221Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
20
level=info ts=2023-03-29T09:28:22.127728359Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
19
level=info ts=2023-03-29T09:28:32.127648752Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
18
level=info ts=2023-03-29T09:28:42.128405108Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
17
level=info ts=2023-03-29T09:28:52.127450051Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
16
level=info ts=2023-03-29T09:29:02.127618396Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
15
level=info ts=2023-03-29T09:29:12.12752973Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
14
level=info ts=2023-03-29T09:29:22.127940252Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
13
level=info ts=2023-03-29T09:29:26.3344329Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
12
level=info ts=2023-03-29T09:29:32.128012292Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
11
level=info ts=2023-03-29T09:29:42.127572899Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
10
level=info ts=2023-03-29T09:29:52.128019447Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
9
level=info ts=2023-03-29T09:30:02.128197137Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
8
level=info ts=2023-03-29T09:30:12.127444843Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
7
level=info ts=2023-03-29T09:30:22.127835861Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
6
level=info ts=2023-03-29T09:30:32.128448992Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
5
level=info ts=2023-03-29T09:30:42.127532702Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
4
level=info ts=2023-03-29T09:30:42.127532775Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
3
level=info ts=2023-03-29T09:30:42.334452784Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
2
level=info ts=2023-03-29T09:30:52.12744149Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"
1
level=info ts=2023-03-29T09:30:52.127441434Z caller=frontend.go:342 msg="not ready: number of queriers connected to query-frontend is 0"

...
```

Despite of executing querier components, logs repeatedly show `not ready` messages.

Any considerations do I need?

For more details, see https://github.com/grafana/helm-charts/issues/2295.

Here is what I set values up:
```yaml
loki-distributed:
  # prometheus expose for metric
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack

  loki:
    structuredConfig:
      analytics:
        reporting_enabled: false

      ingester:
        wal:
          enabled: true
          checkpoint_duration: 5m
          replay_memory_ceiling: 2GB
          flush_on_shutdown: true

        # Disable chunk transfer which is not possible with statefulsets
        # and unnecessary for boltdb-shipper
        max_transfer_retries: 0
        chunk_idle_period: 1h
        chunk_target_size: 1536000
        max_chunk_age: 1h

      storage_config:
        aws:
          bucketnames: ***
          endpoint: ***
          region: ***
          access_key_id: ***
          secret_access_key: ***
        boltdb_shipper:
          shared_store: s3
      schema_config:
        configs:
          - from: 2022-05-10
            store: boltdb-shipper
            object_store: aws
            schema: v11
            index:
              prefix: loki_index_
              period: 24h

  ingester:
    extraArgs:
      - "-config.expand-env=true"
    extraEnvFrom:
      - secretRef:
          name: ***
    replicas: 3
    maxUnavailable: 1

    persistence:
      enabled: true
      size: "80Gi"
      storageClass: "efs"
    resources:
      requests:
        cpu: 4000m
        memory: 8Gi
        ephemeral-storage: 8Gi
      limits:
        cpu: 4000m
        memory: 8Gi
        ephemeral-storage: 8Gi

  distributor:
    extraArgs:
      - "-config.expand-env=true"

    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 6
      targetCPUUtilizationPercentage: 60

    resources:
      requests:
        cpu: 1000m
        memory: 4Gi
      limits:
        cpu: 2000m
        memory: 8Gi

  querier:
    replicas: 4
    maxUnavailable: 2

    extraArgs:
      - "-config.expand-env=true"

    extraEnvFrom:
      - secretRef:
          name: ***

    autoscaling:
      enabled: true
      minReplicas: 4
      maxReplicas: 6
      targetCPUUtilizationPercentage: 60

    resources:
      requests:
        cpu: 1000m
        memory: 4Gi
      limits:
        cpu: 2000m
        memory: 8Gi

  queryFrontend:
    replicas: 2
    maxUnavailable: 1

    extraArgs:
      - "-config.expand-env=true"

    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 3
      targetCPUUtilizationPercentage: 60

    resources:
      requests:
        cpu: 1000m
        memory: 4Gi
      limits:
        cpu: 2000m
        memory: 8Gi

  gateway:
    nginxConfig:
      file: |
        worker_processes  5;  ## Default: 1
        error_log  /dev/stderr;
        pid        /tmp/nginx.pid;
        worker_rlimit_nofile 8192;

        events {
          worker_connections  4096;  ## Default: 1024
        }

        http {
          client_max_body_size  50M;
          client_body_temp_path /tmp/client_temp;
          proxy_temp_path       /tmp/proxy_temp_path;
          fastcgi_temp_path     /tmp/fastcgi_temp;
          uwsgi_temp_path       /tmp/uwsgi_temp;
          scgi_temp_path        /tmp/scgi_temp;

          proxy_http_version    1.1;
          default_type application/octet-stream;
          log_format   {{ .Values.gateway.nginxConfig.logFormat }}
          
          {{- if .Values.gateway.verboseLogging }}
          access_log   /dev/stderr  main;
          {{- else }}
          map $status $loggable {
            ~^[23]  0;
            default 1;
          }
          
          access_log   /dev/stderr  main  if=$loggable;
          {{- end }}
          
          sendfile     on;
          tcp_nopush   on;
          
          {{- if .Values.gateway.nginxConfig.resolver }}
          resolver {{ .Values.gateway.nginxConfig.resolver }};
          {{- else }}
          resolver {{ .Values.global.dnsService }}.{{ .Values.global.dnsNamespace }}.svc.{{ .Values.global.clusterDomain }};
          {{- end }}
          
          {{- with .Values.gateway.nginxConfig.httpSnippet }}
          {{ . | nindent 2 }}
          {{- end }}
          
          server {
            listen             8080;
          
            {{- if .Values.gateway.basicAuth.enabled }}
            auth_basic           "Loki";
            auth_basic_user_file /etc/nginx/secrets/.htpasswd;
            {{- end }}
          
            location = / {
              return 200 'OK';
              auth_basic off;
              access_log off;
            }
          
            location = /api/prom/push {
              set $api_prom_push_backend http://{{ include "loki.distributorFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass       $api_prom_push_backend:3100$request_uri;
              proxy_http_version 1.1;
            }
          
            location = /api/prom/tail {
              set $api_prom_tail_backend http://{{ include "loki.querierFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass       $api_prom_tail_backend:3100$request_uri;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
              proxy_http_version 1.1;
            }
          
            # Ruler
            location ~ /prometheus/api/v1/alerts.* {
              proxy_pass       http://{{ include "loki.rulerFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
            }
          
            location ~ /prometheus/api/v1/rules.* {
              proxy_pass       http://{{ include "loki.rulerFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
            }
          
            location ~ /api/prom/rules.* {
              proxy_pass       http://{{ include "loki.rulerFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
            }
          
            location ~ /api/prom/alerts.* {
              proxy_pass       http://{{ include "loki.rulerFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
            }
          
            location ~ /api/prom/.* {
              set $api_prom_backend http://{{ include "loki.queryFrontendFullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass       $api_prom_backend:3100$request_uri;
              proxy_http_version 1.1;
            }
          
            location = /loki/api/v1/push {
              set $loki_api_v1_push_backend http://{{ include "loki.distributorFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass       $loki_api_v1_push_backend:3100$request_uri;
              proxy_http_version 1.1;
            }
          
            location = /loki/api/v1/tail {
              set $loki_api_v1_tail_backend http://{{ include "loki.querierFullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass       $loki_api_v1_tail_backend:3100$request_uri;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
              proxy_http_version 1.1;
            }
          
            location ~ /loki/api/.* {
              set $loki_api_backend http://{{ include "loki.queryFrontendFullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }};
              proxy_pass       $loki_api_backend:3100$request_uri;
              proxy_http_version 1.1;
            }
          
            {{- with .Values.gateway.nginxConfig.serverSnippet }}
            {{ . | nindent 4 }}
            {{- end }}
          }
        }

```
