### ISSUE TITLE
Loki 2.4.1 empty ring Code(500) error for "GET /loki/api/v1/labels" API on AWS ECS

### ISSUE THREAD

**Issue by akshayjadhav92** [grafana/loki#8986]
#### Bug Description
- Loki 2.4.1 runs fine in "**Simple scalable deployment mode**" on local docker using docker-compose. 
- Same Loki configuration when ported to ECS, responds correctly only to `/ready` and `/config` APIs but throws `empty ring Code(500)` error while trying to add Loki as a datasource in Grafana. i.e issue with `GET /loki/api/v1/labels` API
- Is something being conceptually missed in loki-config, ECS config or networking on ECS  ?

##### Networking

` bridge mode and dynamic port allocation in ECS task definition`
` cluster in public vpc`

##### Specs
```
$ lscpu
Architecture:        aarch64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           ARM
```

##### Platform

```
Amazon Linux (Inferred)
```

##### AMI Name

```
amzn2-ami-ecs-hvm-2.0.20230314-arm64-ebs
```

##### Docker version

```
$ docker version
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        100c701
 Built:             Sat Dec  3 04:13:49 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true
```

##### docker-compose.yaml (Converted to task-definition.json on ECS cluster)

```
---
version: "3"

networks:
  loki:

services:
  read:
    ...
    ports:
      - 3100
      - 7946
      - 9095
    ...
    networks: &loki-dns
      loki:
        aliases:
          - loki

  write:
    ...
    ports:
      - 3100
      - 7946
      - 9095
    ...
    networks:
      <<: *loki-dns

  gateway:
    ...
    ports:
      - "3100:3100"
    networks:
      - loki
```

#####  loki-config.yaml

```
auth_enabled: true

server:
  http_listen_port: 3100
  http_server_read_timeout: 10m
  http_server_write_timeout: 10m
  http_server_idle_timeout: 10m

memberlist:
  bind_port: 7946

frontend:
  instance_interface_names:
    - ${instance_interface_names1}
    - ${instance_interface_names2}
    - ${instance_interface_names3}

common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      s3: ${s3_url}
      insecure: false
      bucketnames: ${s3_bucket_name}
      access_key_id: ${s3_access_key_id}
      secret_access_key: ${s3_secret_access_key}
      s3forcepathstyle: true
  ring:
    instance_interface_names: 
      - ${instance_interface_names1}
      - ${instance_interface_names2}
      - ${instance_interface_names3}
    instance_addr: ${instance_addr}
    kvstore:
      store: memberlist

limits_config:
  retention_period: 744h
  per_stream_rate_limit: 10MB
  unordered_writes: true
  split_queries_by_interval: 10m
  max_entries_limit_per_query: 5000
  reject_old_samples: false
  max_query_series: 100000
  max_global_streams_per_user: 100000

query_range:
  align_queries_with_step: true
  split_queries_by_interval: 10m
  cache_results: true
  
schema_config:
  configs:
    - from: 2022-11-21
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

querier:
  query_timeout: 5m0s

compactor:
  retention_enabled: true
  working_directory: /loki/compactor
  shared_store: s3
  compaction_interval: 5m

ingester:
  chunk_idle_period: 2h
  max_chunk_age: 2h  

ruler:
  ring:
    instance_interface_names: 
      - ${instance_interface_names1}
      - ${instance_interface_names2}
      - ${instance_interface_names3}
    instance_addr: ${instance_addr}
    kvstore:
      store: memberlist
  storage:
    s3:
      s3: ${s3_url}
      insecure: false
      bucketnames: ${s3_bucket_name}
      access_key_id: ${s3_access_key_id}
      secret_access_key: ${s3_secret_access_key}
      s3forcepathstyle: true
```

#####  nginx.conf

```conf
user  nginx;
worker_processes  16;  ## Default: 1

events {
  worker_connections   1000;
}

http {

  resolver 172.16.0.23; # for ECS environment

  upstream read {
      server read:3100;
  }

  upstream write {
      server write:3100;
  }

  server {
    listen             3100;

    location = / {
      return 200 'OK';
      auth_basic off;
    }

    location ~ /ready {
      proxy_pass       http://read$request_uri;
    }

    location ~ /config {
      proxy_pass       http://read$request_uri;
    }

    ...

    location = /loki/api/v1/push {
      proxy_pass       http://write$request_uri;
    }

    location ~ /loki/api/.* {
      proxy_pass       http://read$request_uri;
    }
  }
}

```

##### ECS task definition

- It has three containers as in docker-compose.yaml viz. 
  * read
  * write
  * gateway (nginx)

#### Loki initialisation command in ECS task definition for respective read and write container
* Read container
```json
"command": [
    "-config.file=/etc/loki/config.yaml",
    "-target=read",
    "-memberlist.join=dns+127.0.0.1:7946",
    "-config.expand-env=true",
    "-log.level=debug"
],
```

* Write container
```json
"command": [
    "-config.file=/etc/loki/config.yaml",
    "-target=write",
    "-memberlist.join=dns+127.0.0.1:7946",
    "-config.expand-env=true",
    "-log.level=debug"
],
``` 

#### Environment variables in ECS task definition for loki-config.yaml

* Did try `instance_interface_names1` with `docker0` and `eth0` as well.
* Did try `instance_addr` with `172.16.0.23` as well.
```json
"environment": [
    {
        "name": "instance_addr",
        "value": "127.0.0.1"
    },
    {
        "name": "instance_interface_names1",
        "value": "lo"
    },
    {
        "name": "instance_interface_names2",
        "value": ""
    },
    {
        "name": "instance_interface_names3",
        "value": ""
    }
],
```

#####  Terminal output  

> level=error ts=2023-04-01T06:45:56.093462695Z caller=retry.go:73 org_id=loki_docker msg="error processing request" try=0 err="rpc error: code = Code(500) desc = empty ring\n"
>
> level=warn ts=2023-04-01T06:55:28.134558822Z caller=logging.go:72 traceID=75403ff64a7f19f9 orgID=loki_docker msg="GET /loki/api/v1/labels?start=1680331527903000000&end=1680332127903000000 (500) 2.956091ms Response: \"empty ring\\n\" ws: false; Accept-Encoding: gzip, deflate, br; Connection: close; User-Agent: Grafana/9.3.2; X-Scope-Orgid: loki_docker; "
