### ISSUE TITLE
How to add more location for scrape ?

### ISSUE THREAD

**Issue by petarkozic** [grafana/loki#90]
Hi,
I run this in docker on clean ubuntu 18.04

syslog works well. I installed nginx and try to add nginx in scrape_config but I can't

```
scrape_configs:
- job_name: system
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log
      job: nginx
     __path__:/var/log/nginx
```

I tried to add new label job with path, and after restart promtail container, container exited.
If I try to open interactive docker exec -it promtail I saw under /var/log my nginx folder regulary.

How to add new log file to scrape ?

**Comment by woodsaj** [comment]
You need to define a scrap_config for each one.  eg.
```
scrape_configs:
- job_name: system
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log
- job_name: nginx
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      __path__: /var/log/nginx
```

**Comment by djdubd** [comment]
Just so that you know, I just struggled with this for about 20 minutes after following the accepted answer here. It doesn't seem to be correct anymore. I ended up finally getting it running by using the config formatting that the original poster had.

**Comment by crazy-canux** [comment]
@woodsaj   not work for me.

j8lf4gltdppf5vapw5z616aoj.1@l1eyap4jbi6wunhlex7u401zw    |  Unable to parse config: /etc/promtail/promtail-config.yaml: yaml: unmarshal errors:
j8lf4gltdppf5vapw5z616aoj.1@l1eyap4jbi6wunhlex7u401zw    |    line 25: field lables not found in type struct { Targets []string "yaml:\"targets\""; Labels model.LabelSet "yaml:\"labels\"" }

**Comment by eschulma** [comment]
I also had problems with the accepted answer. This worked:

```
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: webapp
      __path__: /opt/tomcat9/logs/webapp.log
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log

```
