### ISSUE TITLE
Loki 2.7.5 compactor panic every 10 minutes

### ISSUE THREAD

**Issue by gabriellemadden** [grafana/loki#9059]
**Describe the bug**
We recently switched our Loki storage to boltdb-shipper with gcs, so according to the [Single Store](https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper/#compactor) documentation, I wanted to enable compactor to save some space. However, the compactor component crashes every 10 minutes with `invalid memory address or nil pointer dereference` when enabled. I have noticed it sometimes lasts longer than 10 minutes before dying, so it's not consistent. Despite the crashes, the compactor is still sometimes able to compress our gcs tables successfully.

**To Reproduce**
1. Configure Loki version 2.7.5 in microservices mode with Promtail, distributor, gateway, query frontend, table manager, ingester, memcached chunks, memcached frontend, memcached index queries, and querier with service monitors enabled.
2. Enable compactor (start up separate compactor deployment)
3. Wait for it to start and complete its compaction interval (10 minutes for our case)
4. See crash
   
**Expected behavior**
Compactor does not crash

**Environment:**
 - Infrastructure: Kubernetes v1.25.6
 - Deployment tool: helm charts with ArgoCD
 - Chart version: loki-distributed version ^0.69.9 from https://grafana.github.io/helm-charts

**Screenshots, Promtail config, or terminal output**
Here are the initial compactor run logs:
```
level=warn ts=2023-04-05T23:06:05.849935699Z caller=loki.go:251 msg="per-tenant timeout not configured, using default engine timeout (\"5m0s\"). This behavior will change in the next major to always use the default per-tenant timeout (\"5m\")."
level=info ts=2023-04-05T23:06:05.928868282Z caller=main.go:108 msg="Starting Loki" version="(version=2.7.5, branch=HEAD, revision=fd33f6a18)"
level=info ts=2023-04-05T23:06:06.023797604Z caller=server.go:323 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2023-04-05T23:06:06.138014113Z caller=module_service.go:82 msg=initialising module=runtime-config
level=info ts=2023-04-05T23:06:06.138905068Z caller=memberlist_client.go:436 msg="Using memberlist cluster label and node name" cluster_label= node=loki-loki-distributed-compactor-6499875f8f-s6gdb-5b7e36e4
level=info ts=2023-04-05T23:06:06.225583129Z caller=module_service.go:82 msg=initialising module=server
level=info ts=2023-04-05T23:06:06.22587866Z caller=module_service.go:82 msg=initialising module=memberlist-kv
level=info ts=2023-04-05T23:06:06.225903437Z caller=module_service.go:82 msg=initialising module=usage-report
level=info ts=2023-04-05T23:06:06.333968Z caller=module_service.go:82 msg=initialising module=compactor
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe59a24]
goroutine 262 [running]:
github.com/hashicorp/memberlist.(*TransmitLimitedQueue).queueBroadcast(0x0, {0x2802600, 0xc0005f5b00}, 0x0)
	/src/loki/vendor/github.com/hashicorp/memberlist/queue.go:183 +0x64
github.com/hashicorp/memberlist.(*TransmitLimitedQueue).QueueBroadcast(...)
	/src/loki/vendor/github.com/hashicorp/memberlist/queue.go:165
github.com/grafana/dskit/kv/memberlist.(*KV).queueBroadcast(0xc0006bf800, {0xc0013d4b70?, 0xc0013d4b70?}, {0xc0002269e0?, 0xc00089e700?, 0x2c1?}, 0x353?, {0xc0002bdb00, 0x2df, 0x2df})
	/src/loki/vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go:1098 +0x168
github.com/grafana/dskit/kv/memberlist.(*KV).broadcastNewValue(0xc0006bf800, {0xc0013d4b70, 0xf}, {0x2804618?, 0xc000219ca0}, 0x1, {0x28025d0, 0xc0007df2f0})
	/src/loki/vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go:982 +0x813
github.com/grafana/dskit/kv/memberlist.(*KV).processValueUpdate(0xc0006bf800, 0xc0005f5920, {0xc0013d4b70, 0xf})
	/src/loki/vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go:1073 +0x3ab
created by github.com/grafana/dskit/kv/memberlist.(*KV).getKeyWorkerChannel
	/src/loki/vendor/github.com/grafana/dskit/kv/memberlist/memberlist_client.go:1036 +0x16a
```
And when it restarts, traffic from other components can't reach the old compactor:
```
level=warn ts=2023-04-06T14:26:30.999698648Z caller=loki.go:251 msg="per-tenant timeout not configured, using default engine timeout (\"5m0s\"). This behavior will change in the next major to always use the default per-tenant timeout (\"5m\")."
level=info ts=2023-04-06T14:26:31.103838774Z caller=main.go:108 msg="Starting Loki" version="(version=2.7.5, branch=HEAD, revision=fd33f6a18)"
level=info ts=2023-04-06T14:26:31.104766876Z caller=server.go:323 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2023-04-06T14:26:31.204118906Z caller=memberlist_client.go:436 msg="Using memberlist cluster label and node name" cluster_label= node=loki-loki-distributed-compactor-78c78fbf86-hz7pj-44a4e6d8
level=info ts=2023-04-06T14:26:31.302188476Z caller=module_service.go:82 msg=initialising module=server
level=info ts=2023-04-06T14:26:31.399629629Z caller=module_service.go:82 msg=initialising module=usage-report
level=info ts=2023-04-06T14:26:31.399989986Z caller=module_service.go:82 msg=initialising module=runtime-config
level=info ts=2023-04-06T14:26:31.401228914Z caller=module_service.go:82 msg=initialising module=memberlist-kv
level=info ts=2023-04-06T14:26:31.401552476Z caller=module_service.go:82 msg=initialising module=compactor
level=info ts=2023-04-06T14:26:31.500737137Z caller=memberlist_client.go:543 msg="memberlist fast-join starting" nodes_found=1 to_join=4
level=info ts=2023-04-06T14:26:32.201816702Z caller=memberlist_client.go:563 msg="memberlist fast-join finished" joined_nodes=9 elapsed_time=701.10901ms
level=info ts=2023-04-06T14:26:32.201902021Z caller=memberlist_client.go:576 msg="joining memberlist cluster" join_members=loki-loki-distributed-memberlist
level=info ts=2023-04-06T14:26:32.202223763Z caller=basic_lifecycler.go:259 msg="instance found in the ring" instance=loki-loki-distributed-compactor-78c78fbf86-hz7pj ring=compactor state=ACTIVE tokens=1 registered_at="2023-04-05 23:51:00 +0000 UTC"
level=info ts=2023-04-06T14:26:32.202250368Z caller=basic_lifecycler_delegates.go:63 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2023-04-06T14:26:32.202688114Z caller=compactor.go:328 msg="waiting until compactor is JOINING in the ring"
level=info ts=2023-04-06T14:26:32.202737631Z caller=compactor.go:332 msg="compactor is JOINING in the ring"
level=info ts=2023-04-06T14:26:33.299596398Z caller=compactor.go:342 msg="waiting until compactor is ACTIVE in the ring"
level=info ts=2023-04-06T14:26:33.400362934Z caller=memberlist_client.go:595 msg="joining memberlist cluster succeeded" reached_nodes=9 elapsed_time=1.198461015s
level=info ts=2023-04-06T14:26:33.499484233Z caller=compactor.go:346 msg="compactor is ACTIVE in the ring"
level=info ts=2023-04-06T14:26:33.499606162Z caller=loki.go:461 msg="Loki started"
ts=2023-04-06T14:26:33.600227296Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.2.240:7946"
ts=2023-04-06T14:26:34.199921497Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.1.168:7946"
ts=2023-04-06T14:26:34.200514648Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.0.95:7946"
ts=2023-04-06T14:26:35.55785863Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.1.168:7946"
ts=2023-04-06T14:26:35.558315751Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.0.93:7946"
ts=2023-04-06T14:26:35.559013046Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.1.167:7946"
ts=2023-04-06T14:26:36.14445788Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.6.83:7946"
ts=2023-04-06T14:26:36.144651678Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.6.84:7946"
ts=2023-04-06T14:26:36.144724676Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.0.92:7946"
ts=2023-04-06T14:26:36.178150506Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.6.83:7946"
ts=2023-04-06T14:26:36.179271708Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.0.92:7946"
ts=2023-04-06T14:26:36.17936442Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.1.167:7946"
level=info ts=2023-04-06T14:26:38.500333929Z caller=compactor.go:407 msg="this instance has been chosen to run the compactor, starting compactor"
level=info ts=2023-04-06T14:26:38.500442021Z caller=compactor.go:436 msg="waiting 10m0s for ring to stay stable and previous compactions to finish before starting compactor"
ts=2023-04-06T14:26:42.441104859Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.0.93:7946"
ts=2023-04-06T14:26:44.443428325Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.6.85:7946"
ts=2023-04-06T14:26:44.444436584Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.1.167:7946"
ts=2023-04-06T14:26:44.444592429Z caller=memberlist_logger.go:74 level=warn msg="Got ping for unexpected node 'loki-loki-distributed-compactor-78c78fbf86-hz7pj-fb5a3c92' from=10.52.1.168:7946"
```

Distributor logs trying to communicate with compactor:
```
Page 1 (Lines 1 to 64)
level=warn ts=2023-04-05T23:51:27.058134843Z caller=loki.go:251 msg="per-tenant timeout not configured, using default engine timeout (\"5m0s\"). This behavior will change in the next major to always use the default per-tenant timeout (\"5m\")."
level=info ts=2023-04-05T23:51:27.063680294Z caller=main.go:108 msg="Starting Loki" version="(version=2.7.5, branch=HEAD, revision=fd33f6a18)"
level=info ts=2023-04-05T23:51:27.065711134Z caller=server.go:323 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2023-04-05T23:51:27.067324434Z caller=memberlist_client.go:436 msg="Using memberlist cluster label and node name" cluster_label= node=loki-loki-distributed-distributor-6f9f655496-5hv5r-72e09344
level=info ts=2023-04-05T23:51:27.069485457Z caller=memberlist_client.go:543 msg="memberlist fast-join starting" nodes_found=1 to_join=4
level=info ts=2023-04-05T23:51:27.070487636Z caller=module_service.go:82 msg=initialising module=server
level=info ts=2023-04-05T23:51:27.070632311Z caller=module_service.go:82 msg=initialising module=usage-report
level=info ts=2023-04-05T23:51:27.070637319Z caller=module_service.go:82 msg=initialising module=runtime-config
level=info ts=2023-04-05T23:51:27.071113828Z caller=module_service.go:82 msg=initialising module=memberlist-kv
level=info ts=2023-04-05T23:51:27.071138509Z caller=module_service.go:82 msg=initialising module=ring
level=info ts=2023-04-05T23:51:27.162368452Z caller=memberlist_client.go:563 msg="memberlist fast-join finished" joined_nodes=6 elapsed_time=92.889432ms
level=info ts=2023-04-05T23:51:27.162421093Z caller=memberlist_client.go:576 msg="joining memberlist cluster" join_members=loki-loki-distributed-memberlist
level=info ts=2023-04-05T23:51:27.162842373Z caller=module_service.go:82 msg=initialising module=distributor
level=info ts=2023-04-05T23:51:27.162874342Z caller=lifecycler.go:547 msg="not loading tokens from file, tokens file path is empty"
level=info ts=2023-04-05T23:51:27.162950762Z caller=lifecycler.go:576 msg="instance not found in ring, adding with no tokens" ring=distributor
level=info ts=2023-04-05T23:51:27.163005971Z caller=loki.go:461 msg="Loki started"
level=info ts=2023-04-05T23:51:27.163093082Z caller=lifecycler.go:416 msg="auto-joining cluster after timeout" ring=distributor
level=info ts=2023-04-05T23:51:27.179601333Z caller=memberlist_client.go:595 msg="joining memberlist cluster succeeded" reached_nodes=6 elapsed_time=17.180886ms
ts=2023-04-06T00:01:53.389131876Z caller=memberlist_logger.go:74 level=info msg="Marking loki-loki-distributed-compactor-78c78fbf86-hz7pj-2cb8828b as failed, suspect timeout reached (2 peer confirmations)"
ts=2023-04-06T00:12:24.342247581Z caller=memberlist_logger.go:74 level=info msg="Marking loki-loki-distributed-compactor-78c78fbf86-hz7pj-9db6d343 as failed, suspect timeout reached (2 peer confirmations)"
ts=2023-04-06T00:23:12.070676711Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-0e26e817 has failed, no acks received"
ts=2023-04-06T00:23:27.569974862Z caller=memberlist_logger.go:74 level=info msg="Marking loki-loki-distributed-compactor-78c78fbf86-hz7pj-0e26e817 as failed, suspect timeout reached (2 peer confirmations)"
ts=2023-04-06T00:33:47.070272353Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-1947d9e7 has failed, no acks received"
ts=2023-04-06T00:34:07.070517808Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-1947d9e7 has failed, no acks received"
ts=2023-04-06T00:34:07.890916074Z caller=memberlist_logger.go:74 level=info msg="Marking loki-loki-distributed-compactor-78c78fbf86-hz7pj-1947d9e7 as failed, suspect timeout reached (2 peer confirmations)"
ts=2023-04-06T00:44:44.341463063Z caller=memberlist_logger.go:74 level=info msg="Marking loki-loki-distributed-compactor-78c78fbf86-hz7pj-fba3e96a as failed, suspect timeout reached (2 peer confirmations)"
ts=2023-04-06T00:54:59.001655319Z caller=memberlist_logger.go:74 level=error msg="Push/Pull with loki-loki-distributed-compactor-78c78fbf86-hz7pj-9601572e failed: read tcp 10.52.6.83:46274->10.52.2.241:7946: read: connection reset by peer"
ts=2023-04-06T01:06:02.070914855Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-bbc42e0e has failed, no acks received"
ts=2023-04-06T01:06:09.315608069Z caller=memberlist_logger.go:74 level=info msg="Marking loki-loki-distributed-compactor-78c78fbf86-hz7pj-bbc42e0e as failed, suspect timeout reached (2 peer confirmations)"
ts=2023-04-06T01:28:07.071087034Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-5608cc36 has failed, no acks received"
ts=2023-04-06T01:49:17.070887381Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-17469dcf has failed, no acks received"
ts=2023-04-06T01:49:32.642561494Z caller=memberlist_logger.go:74 level=info msg="Marking loki-loki-distributed-compactor-78c78fbf86-hz7pj-17469dcf as failed, suspect timeout reached (2 peer confirmations)"
ts=2023-04-06T02:22:17.071089506Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-2c0adc64 has failed, no acks received"
ts=2023-04-06T02:22:22.516257171Z caller=memberlist_logger.go:74 level=info msg="Marking loki-loki-distributed-compactor-78c78fbf86-hz7pj-2c0adc64 as failed, suspect timeout reached (2 peer confirmations)"
ts=2023-04-06T02:44:07.070556704Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-deeea649 has failed, no acks received"
ts=2023-04-06T02:44:07.515365372Z caller=memberlist_logger.go:74 level=info msg="Marking loki-loki-distributed-compactor-78c78fbf86-hz7pj-deeea649 as failed, suspect timeout reached (2 peer confirmations)"
ts=2023-04-06T03:04:52.070517671Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-49aaf2e5 has failed, no acks received"
ts=2023-04-06T03:05:07.542352604Z caller=memberlist_logger.go:74 level=info msg="Marking loki-loki-distributed-compactor-78c78fbf86-hz7pj-49aaf2e5 as failed, suspect timeout reached (2 peer confirmations)"
ts=2023-04-06T04:06:09.169582632Z caller=memberlist_logger.go:74 level=info msg="Marking loki-loki-distributed-compactor-78c78fbf86-hz7pj-bff66dc4 as failed, suspect timeout reached (2 peer confirmations)"
ts=2023-04-06T04:06:12.070078907Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-bff66dc4 has failed, no acks received"
ts=2023-04-06T04:37:02.070530362Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-9d1e9f59 has failed, no acks received"
ts=2023-04-06T04:37:22.070810787Z caller=memberlist_logger.go:74 level=info msg="Marking loki-loki-distributed-compactor-78c78fbf86-hz7pj-9d1e9f59 as failed, suspect timeout reached (2 peer confirmations)"
ts=2023-04-06T05:08:07.071371337Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-71d7ba2c has failed, no acks received"
ts=2023-04-06T06:20:42.070437396Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-b7978a2f has failed, no acks received"
ts=2023-04-06T06:20:47.516561606Z caller=memberlist_logger.go:74 level=info msg="Marking loki-loki-distributed-compactor-78c78fbf86-hz7pj-b7978a2f as failed, suspect timeout reached (2 peer confirmations)"
ts=2023-04-06T06:51:42.071309226Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-e0a78687 has failed, no acks received"
ts=2023-04-06T06:51:52.070839759Z caller=memberlist_logger.go:74 level=info msg="Suspect loki-loki-distributed-compactor-78c78fbf86-hz7pj-e0a78687 has failed, no acks received"
...etc
```

This is the loki config mounted to all of our loki microservices (mostly defaulting from the [distributed helm chart config](https://github.com/grafana/helm-charts/blob/2ea64f7/charts/loki-distributed/values.yaml#L79) value):
 ```
    auth_enabled: false
    chunk_store_config:
      chunk_cache_config:
        embedded_cache:
          enabled: false
        memcached_client:
          addresses: dnssrv+_memcached-client._tcp.loki-loki-distributed-memcached-chunks.metrics.svc.cluster.local
          consistent_hash: true
      max_look_back_period: 0s
    common:
      compactor_address: http://loki-loki-distributed-compactor:3100
    compactor:
      compactor_ring:
        kvstore:
          store: memberlist
      shared_store: gcs
      working_directory: /var/loki/compactor
    distributor:
      ring:
        kvstore:
          store: memberlist
    frontend:
      compress_responses: true
      log_queries_longer_than: 5s
      tail_proxy_url: http://loki-loki-distributed-querier:3100
    frontend_worker:
      frontend_address: loki-loki-distributed-query-frontend-headless:9095
    ingester:
      chunk_block_size: 262144
      chunk_encoding: snappy
      chunk_idle_period: 30m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /var/loki/wal
    limits_config:
      enforce_metric_name: false
      max_cache_freshness_per_query: 10m
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      split_queries_by_interval: 15m
    memberlist:
      join_members:
      - loki-loki-distributed-memberlist
    query_range:
      align_queries_with_step: true
      cache_results: true
      max_retries: 5
      results_cache:
        cache:
          memcached_client:
            consistent_hash: true
            host: loki-loki-distributed-memcached-frontend
            service: memcached-client
    ruler:
      alertmanager_url: https://alertmanager.xx
      external_url: https://alertmanager.xx
      ring:
        kvstore:
          store: memberlist
      rule_path: /tmp/loki/scratch
      storage:
        local:
          directory: /etc/loki/rules
        type: local
    runtime_config:
      file: /var/loki-distributed-runtime/runtime.yaml
    schema_config:
      configs:
      - from: "2020-07-01"
        index:
          period: 24h
          prefix: index_
        object_store: gcs
        schema: v11
        store: boltdb-shipper
    server:
      http_listen_port: 3100
      log_level: info
    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/boltdb-shipper-active
        cache_location: /var/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: gcs
      filesystem:
        directory: /var/loki/chunks
      gcs:
        bucket_name: polished-enigma-247013-loki-chunks
      index_queries_cache_config:
        memcached:
          batch_size: 100
          parallelism: 100
        memcached_client:
          addresses: dnssrv+_memcached-client._tcp.loki-loki-distributed-memcached-index-queries.metrics.svc.cluster.local
          consistent_hash: true
    table_manager:
      retention_deletes_enabled: true
      retention_period: 168h
```

Here's the [loki-distributed](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed) helm chart values we are using with the following replica counts:
```

    distributor:
      replicas: 3
      maxUnavailable: 2

    gateway:
      replicas: 3
      maxUnavailable: 2

    ingester:
      replicas: 3
      maxUnavailable: 2

    queryFrontend:
      replicas: 3
      maxUnavailable: 2

    querier:
      replicas: 3
      maxUnavailable: 2

    memcachedFrontend:
      enabled: true
      replicas: 3
      maxUnavailable: 2

    memcachedIndexQueries:
      enabled: true
      replicas: 3
      maxUnavailable: 2

    memcachedChunks:
      enabled: true
      replicas: 3
      maxUnavailable: 2

    memcachedIndexWrites:
      enabled: false

    tableManager:
      enabled: true

    compactor:
      enabled: true
```
