### ISSUE TITLE
Loki helm chart - extra-containers

### ISSUE THREAD

**Issue by angelbarrera92** [grafana/loki#908]
Hi. 

I was looking for a solution to deploy loki in a multi-tenant way. Documentation exposes that an `auth_enabled` flag has to be set up to `true`. But, it needs a reverse proxy to inject some headers along with the authentication layer.

I made a POC modifying a rendered loki helm chart template and i think that making available the possibility to add extra-containers, extra-volumes and extra service ports could make it easy to deploy loki in a multi-tenant way. Something similar to nginx ingress controller chart from bitnami -> https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values-production.yaml#L223

I think it may be a non-intrusive solution and may be helpful to implement multi-tenant solutions.

I'll paste part of the modification i tested:

*partial statefulset.yaml*
```yaml
        
    spec:
      serviceAccountName: loki
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        
      containers:
        - name: reverse-proxy
          image: angelbarrera92/basic-auth-reverse-proxy:dev
          args:
            - "serve"
            - "--upstream=http://localhost:3100"
            - "--auth-config=/etc/reverse-proxy-conf/authn.yaml"
          ports:
            - name: http
              containerPort: 11811
              protocol: TCP
          volumeMounts:
            - name: reverse-proxy-auth-config
              mountPath: /etc/reverse-proxy-conf
        - name: loki
          image: "grafana/loki:v0.2.0"
          imagePullPolicy: Always
          args:
            - "-config.file=/etc/loki/loki.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/loki
```
Added a sidecar container with a basic golang reverse proxy *(we can discuss it later if you want)*.

*partial service.yaml*
```yaml
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: 11811
      protocol: TCP
      name: http
      targetPort: http
  selector:
    app: loki
    release: loki
```
*partial service-headless.yaml*
```yaml
spec:
  clusterIP: None
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
    - port: 11811
      protocol: TCP
      name: http
      targetPort: http
  selector:
    app: loki
    release: loki
```

Both services add the sidecar port.

I can make a PR for this ;)

Thanks!
