### ISSUE TITLE
Unimplemented desc = unknown service logproto.Querier

### ISSUE THREAD

**Issue by drayanqi** [grafana/loki#9102]
**Describe the bug**
I am trying to replace my monolithic loki by the scalable version.
I want : 
- 1 loki read instance
- 1 loki write instance
I want to connect it to Grafana as a datasource, but whenever I try to connect, I get this error :

![image](https://user-images.githubusercontent.com/24436472/231167883-aa0d49bb-edbb-44cd-911c-c62b842ca8da.png)

And in the `loki-read` container logs : 

```sh
msg="GET /loki/api/v1/labels?start=1681216469981000000&end=1681217069981000000 (500) 7.7491ms Response: \"rpc error: code = Unimplemented desc = unknown service logproto.Querier\
```

To me, the doc is really poor concerning loki scalable version and could be improved.
I read through all of the similar issues on this repo and none of them really helped me to figure this out.

**To Reproduce**

- docker-compose : 
```
---
version: "3.7"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    user: "${UID:-1001}:${GID:-1001}"
    volumes:
      - ./monitor/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    networks:
      - loki
    ports:
      - 3000:3000
    depends_on:
      - grafana_mysql

  grafana_mysql:
    container_name: grafana_mysql
    restart: unless-stopped
    image: mysql:8.0
    user: "${UID:-1001}:${GID:-1001}"
    volumes:
      - grafana_mysql:/var/lib/mysql
    networks:
      - loki

  read:
    image: grafana/loki:2.8.0
    container_name: loki-read
    restart: unless-stopped
    volumes:
      - ./monitor/loki/loki.yml:/etc/loki/loki.yml
      - loki_data:/loki
    command: "-config.file=/etc/loki/loki.yml -target=all -log.level=debug"
    networks:
      - loki
    ports:
      - 3101:3100
      - 7946
      - 9095

  write:
    image: grafana/loki:2.8.0
    container_name: loki-write
    command: "-config.file=/etc/loki/loki.yml -target=write -log.level=debug"
    ports:
      - 3102:3100
      - 7946
      - 9095
    volumes:
      - ./monitor/loki/loki.yml:/etc/loki/loki.yml
      - loki_data:/loki
    networks:
      - loki

  loki-gateway:
    container_name: loki-gateway
    image: nginx:1.19
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "3100"
    networks:
      - loki

networks:
  loki:

volumes:
  grafana_mysql:
  loki_data:
  grafana_data:
```

- nginx.conf :

```
error_log  /dev/stderr;
pid        /tmp/nginx.pid;
worker_rlimit_nofile 8192;

events {
    worker_connections  4096;  ## Default: 1024
}

http {
  default_type application/octet-stream;
  log_format   main '$remote_addr - $remote_user [$time_local]  $status '
    '"$request" $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';
  access_log   /dev/stderr  main;
  sendfile     on;
  tcp_nopush   on;

  upstream read {
    server loki-read:3100;
  }

  upstream write {
    server loki-write:3100;
  }

  upstream cluster {
    server loki-read:3100;
    server loki-write:3100;
  }

  server {
    listen 80;
    listen 3100;

    location = /ring {
        proxy_pass       http://cluster$request_uri;
    }

    location = /memberlist {
        proxy_pass       http://cluster$request_uri;
    }

    location = /config {
        proxy_pass       http://cluster$request_uri;
    }

    location = /metrics {
        proxy_pass       http://cluster$request_uri;
    }

    location = /ready {
        proxy_pass       http://cluster$request_uri;
    }

    location = /loki/api/v1/push {
        proxy_pass       http://write$request_uri;
    }

    location = /loki/api/v1/tail {
        proxy_pass       http://read$request_uri;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location ~ /loki/api/.* {
        proxy_pass       http://read$request_uri;
    }
  }
}
```

- loki.yml : 
```
auth_enabled: false

http_prefix:

server:
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: debug

frontend:
  log_queries_longer_than: 5s
  max_outstanding_per_tenant: 2048
  compress_responses: true

memberlist:
  join_members:
    - loki-write
    - loki-read
  bind_port: 7946

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: memberlist
  compactor_address: http://loki-write:3100

ingester:
  wal:
    enabled: false
  lifecycler:
    unregister_on_shutdown: false
    join_after: 60s
    observe_period: 5s
    final_sleep: 0s
    ring:
      kvstore:
        store: memberlist

schema_config:
  configs:
    - from: 2022-01-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  storage:
    type: local
    local:
      directory: /loki/rules

query_scheduler:
  max_outstanding_requests_per_tenant: 1024

querier:
  query_ingesters_within: 2h

query_range:
  cache_results: true

storage_config:
  boltdb_shipper:
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
```

**Expected behavior**
Grafana correctly connects to loki.

**Environment:**
 - docker 
 - nginx gateway
