### ISSUE TITLE
Helm chart issues with new backend target

### ISSUE THREAD

**Issue by clarkperkins** [grafana/loki#9109]
**Describe the bug**
I've been testing out version 5.0.0 of the helm chart with the 3 scalable targets and found a few issues:

1. The `read` pods still seem to be downloading indexes instead of letting the `backend` pods handle the downloads. I was able to resolve this by setting the `index_gateway_client` bits in the storage_config - see workaround below. (There's a chance I'm misunderstanding and this is working as desired, but the release notes stating that the new backend target "makes the read target stateless" led me to believe the read target pods should not be downloading indexes)
2. The `read` target has autoscaling configs in values.yaml, but doesn't use them to create an HPA (no HPA resource [here](https://github.com/grafana/loki/tree/main/production/helm/loki/templates/read))
3. The ruler endpoints in the ingress paths are being sent to the read pods instead of the backend pods (see [here](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L962-L973))

**To Reproduce**
1. Install Loki with the official helm chart, using three scalable targets as described [here](https://grafana.com/docs/loki/latest/installation/helm/migrate-to-three-scalable-targets/)

**Expected behavior**
The three scalable targets should be configured properly when following the documentation

**Workarounds**
For issue 1, set the proper configs via helm value overrides:

```yaml
loki:
  storage_config:
    boltdb_shipper:
      # other configs
      index_gateway_client:
        server_address: dns:///loki-backend:9095
    tsdb_shipper:
      # other configs
      index_gateway_client:
        server_address: dns:///loki-backend:9095
```

For issue 2, add an HPA under extraObjects:

```yaml
extraObjects:
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: '{{ include "loki.readFullname" . }}'
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: '{{ include "loki.readFullname" . }}'
      minReplicas: <min>
      maxReplicas: <max>
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: <utilization>
```

For issue 3, use the gateway instead of the ingress. The gateway appears to have the ruler endpoints routed correctly to the backend pods.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
