### ISSUE TITLE
[Loki 2.8] Ruler extra_labels configuration

### ISSUE THREAD

**Issue by Demonsthere** [grafana/loki#9129]
**Describe the bug**
I am unable to set the `extra_labels` for rules using loki 2.8. 

expected format in [2.7](https://grafana.com/docs/loki/v2.7.x/configuration/#ruler):
```yaml
# Labels to add to all alerts
external_labels:
  [<labelname>: <labelvalue> ...]
```

New format in [2.8](https://grafana.com/docs/loki/latest/configuration/#ruler)
```yaml
# Labels to add to all alerts.
[external_labels: <list of Labels>]
```

I have tried the following options but neither works

```yaml
#  gracefully ignored by the application, rules are created without adding the labels
external_labels:
  foo: bar

# failed to parse array into map[string]string
external_labels:
  - foo: bar
 
# failed to parse array into map[string]string
external_labels: "foo:bar"

# failed to parse array into map[string]string
external_labels: {"foo":"bar"}
```

**To Reproduce**
1. Started Loki (2.8.0)
2. Provide config to the app with the ruler config
3. App crashes or labels are not added

**Expected behavior**
The documentation is updated with working examples/snippets of expected config

**Comment by yurissouza** [comment]
Hello!!!
Have you found a solution to add the external labels to your alerts via Ruler?

**Comment by mhulscher** [comment]
This is still broken in loki 2.9.0 .

**Comment by yurissouza** [comment]
Hi guys! We've managed to make that work. We're using Loki-distributed helm-chart v0.69.16 (Loki v2.8.2).
In our case was just a matter of adding that configuration into the Ruler section of the values.yaml of the chart.

```yaml
    ruler:
      rule_path: /tmp/loki/scratch
      alertmanager_url: <ALERT-MANAGER URL>
      enable_api: true
      enable_alertmanager_v2: true
      external_labels:
        cluster_name: "{{ .Values.cluster_name }}"
        cloud_provider: "{{ .Values.cloud_provider}}"
      ring:
        kvstore:
          store: inmemory
```

After adding that configuration into our Loki-distibuted Ruler chart (values.yaml) we could see  in the Alert-manager UI that those `external_labels`  have been automatically added into the alert along side with the other that have been configured in the Grafana UI (when creating the alert).

Hope that could help in some way.
