### ISSUE TITLE
explain storage endpoint configuration

### ISSUE THREAD

**Issue by Morriz** [grafana/loki#913]
The `storage_config` configuration is inconsistent for aws, and as such it makes me wonder what I need to know to work with it. Consider the following example from your documentation to work:
```yaml
schema_config:
  configs:
  - from: 2018-04-15
    store: cassandra
    object_store: filesystem
    schema: v9
    index:
      prefix: cassandra_table
      period: 168h

storage_config:
  cassandra:
    username: cassandra
    password: cassandra
    addresses: 127.0.0.1
    auth: true
    keyspace: lokiindex

  filesystem:
    directory: /tmp/loki/chunks
```
Now, here the chunks config is plucked directly from `storage_config.filesystem`, and same analogy goes for the default boltdb setup. It implies that each section in `storage_config` can be a separate config to be used by the index and/or the chunk apps, each knowing how to consume it.

Now, for AWS there is made an exception, and the chunks config is referenced from  `storage_config.aws.s3`, implying something is goin on behind the scenes here:
```yaml
schema_config:
  configs:
    - from: 2018-04-15
      store: aws
      object_store: s3
      schema: v9
      index:
        prefix: dynamodb_table_name
        period: 0
storage_config:
  aws:
    s3: s3://access_key:secret_access_key@region/bucket_name
    dynamodbconfig:
      dynamodb: dynamodb://access_key:secret_access_key@region
```
It looks as if suddenly the object store knows the indexer is in 'aws mode' and will now also get it's `s3` config from `storage_config.aws`. I think this is not clear and should be fixed to conform to the other examples. So it should be like this imo:
```yaml
schema_config:
  configs:
    - from: 2018-04-15
      store: dynamodbconfig
      object_store: s3
      schema: v9
      index:
        prefix: dynamodb_table_name
        period: 0
storage_config:
  s3:
    s3: s3://access_key:secret_access_key@region/bucket_name
  dynamodbconfig:
    dynamodb: dynamodb://access_key:secret_access_key@region
```

Maybe there is meaning attached to the keys under `storage_config` so I might have named them incorrectly, but it seems as if the key names may be arbitrarily chosen.

I hope this makes sense and is in focus already, as your docs are very limited and adoption should not be hindered by inconsistent configuration schemes...
