### ISSUE TITLE
grafana/loki helm chart installation pending on pvc storage even though S3 is configured?

### ISSUE THREAD

**Issue by Robsta86** [grafana/loki#9131]
Hi,

I am trying to deploy the grafana loki helmchart (version 5.0.0) on our EKS cluster, and I noticed the read and write pods are stuck in the "pending" state.

After doing some research I figured out that the pods are stuck in the pending state because they are reliant on persistent storage. Since we have no persistent storage configured in our EKS cluster (And we are not intending to do so) the pvc's for these mentioned pods are also stuck in the pending state:

```
NAME                STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-loki-read-0    Pending                                      gp2            10s
data-loki-read-1    Pending                                      gp2            10s
data-loki-read-2    Pending                                      gp2            10s
data-loki-write-0   Pending                                      gp2            10s
data-loki-write-1   Pending                                      gp2            10s
data-loki-write-2   Pending                                      gp2            10s
```

This is the values.yaml I used to deploy the chart:

```
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: **MASKED**
 
loki:
  storage:
    bucketNames:
      chunks: **MASKED**/chunks
      ruler: **MASKED**/ruler
      admin: **MASKED**/admin
    type: s3
    s3:
      endpoint: https://s3.eu-central-1.amazonaws.com/
      region: eu-central-1
 
  schema_config:
    configs:
      - from: 2023-04-13
        store: boltdb-shipper
        object_store: aws
        schema: v12
        index:
          prefix: index_
          period: 24h
```

I was under the impression that when S3 is configured as a storage backend there is no need to use persistent storage within the cluster. Did I misconfigure something? Is there a bug in the helm chart? Or.... is this expected behavior?

If the latter is the case it is actually a bit confusing since the loki-distributed helm chart (which is no longer recommended according to a Grafana Loki Configuration webinar I just watched) has no need for persistent storage within kubernetes. And the same goes for the lok-stack helm chart.

**Comment by jkern888** [comment]
Weird timing because I just ran into this same issue today too and would very much like to hear an answer. Is the only solution for EKS getting the EBS CSI driver setup?

**Comment by rubenvw-ngdata** [comment]
Not sure if this is going to resolve the complete problem, but in the schema config the object store should be s3 instead of aws I think.

**Comment by Robsta86** [comment]
> Not sure if this is going to resolve the complete problem, but in the schema config the object store should be s3 instead of aws I think.

Unfortunately this wont resolve the problem and still everything is pending, waiting for a persistent volume that we cannot provision :)

**Comment by slim-bean** [comment]
Loki's primary storage is object storage, however it does use a disk for a few things:

* the write ahead log
* creating and caching of index files

For the highest guarantees around not losing any data, you would need to have a persistent volume for these at a minimum on the ingesters (or write) components.

For other components like compactor, index-gateway. This could be ephemeral disk.

If you use ephemeral disk for the components on the write path, your only durability would be provided by the replication factor. So with a rep factor of 3, losing more than 1 disk would result in some data loss of recent data.

**Comment by kundan89** [comment]
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  4m46s (x105 over 17h)  default-scheduler  running PreBind plugin "VolumeBinding": binding volumes: timed out waiting for the condition     any solution for this

**Comment by imanAzi** [comment]
We are in the same situation as described here above. Is persistent storage needed for running Loki or can you have a fully working setup of Loki in simple scalable mode only using S3?

**Comment by phyzical** [comment]
you can, it took be way to long to get it going.

Granted i have not full stress tested it. but confirmed after a day a reboot is able to see the last days logs and the s3 bucket is populated so good enough for my POC for now

hopefully it helps i think the important chucks are 

```
loki:
  ## handles the s3 magic
  storage:
    type: s3
    bucketNames:
      chunks: ${bucket}
      ruler: ${bucket}
    s3:
      region: ${region}
      bucketnames: ${bucket}
  commonConfig:
    # gotta set to tmp dir as no PV
    path_prefix: /tmp/loki
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2021-05-12
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: loki_index_
          period: 24h
    storage_config:
      boltdb_shipper:
        shared_store: s3
        cache_ttl: 168h
      aws:
        region: ${region}
        bucketnames: ${bucket}        
singleBinary:
  replicas: 1
  persistence:
    enabled: false
```

Below is my full helm values 

```
serviceAccount:
  create: false
  name: ${service_account_name}
memberlist:
  service:
    publishNotReadyAddresses: true
loki:
  storage:
    type: s3
    bucketNames:
      chunks: ${bucket}
      ruler: ${bucket}
    s3:
      region: ${region}
      bucketnames: ${bucket}
  commonConfig:
    # gotta set to tmp dir
    path_prefix: /tmp/loki
    replication_factor: 1
  auth_enabled: false
  limits_config:
    ingestion_rate_mb: 20
    ingestion_burst_size_mb: 30
  compactor:
    apply_retention_interval: 1h
    compaction_interval: 5m
    retention_delete_worker_count: 500
    retention_enabled: true
    shared_store: s3
  schemaConfig:
    configs:
      - from: 2021-05-12
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    boltdb_shipper:
      shared_store: s3
      cache_ttl: 168h
    aws:
      region: ${region}
      bucketnames: ${bucket}
  server:
    http_listen_port: 3100
    grpc_server_max_recv_msg_size: 104857600 # 100 Mb
    grpc_server_max_send_msg_size: 104857600 # 100 Mb
    http_server_write_timeout: 310s
    http_server_read_timeout: 310s
  ingester_client:
    grpc_client_config:
      max_recv_msg_size: 104857600 # 100 Mb
      max_send_msg_size: 104857600 # 100 Mb
  service:
    port: 80
    targetPort: 3100
  url: http://${domain}:{{ .Values.loki.service.port }}
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45
## makes it monolith matching the old stack way
singleBinary:
  replicas: 1
  persistence:
    enabled: false
monitoring:
  selfMonitoring:
    enabled: true
  lokiCanary:
    enabled: false
gateway:
  enabled: false
test:
  enabled: false
ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internal
    # Use this annotation (which must match a service name) to route traffic to HTTP2 backends.
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    external-dns.alpha.kubernetes.io/hostname: ${domain}
    alb.ingress.kubernetes.io/shield-advanced-protection: "true"
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    kubernetes.io/ingress.class: alb
  hosts:
    - ${domain}
```
