### ISSUE TITLE
Configure account_key as secret for Loki with Azure storage

### ISSUE THREAD

**Issue by lucasoares** [grafana/loki#9143]
To use Loki with Azure I need to set an `account_key` attribute when using [Helm](https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml#L240).

```
storage_config:
  azure:
    account_name: ???
    account_key: ???
    container_name: loki
    request_timeout: 0
```

Shouldn't we be able to to set this setting from an environment variable or a secret? Currently I need to keep my `accountKey` inside my `values.yaml` file and this is not secure.

There is any workaround?

**Comment by slyt** [comment]
The same issue exists for [s3 storage configuration](https://github.com/grafana/loki/blob/98b5e35f94ab70a05e92a95343f83b2ed1984e84/production/helm/loki/values.yaml#L234-L235) as well. `secretAccessKey` and `accessKeyId` should be able to reference Kubernetes Secrets instead of being provided in plaintext in values.yaml.

**Comment by slyt** [comment]
I got this working for s3 storage by setting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` in a secret then use `extraEnvFrom:` to inject them into environment variables for each pod. This works because Loki uses the AWS SDK client which [prioritizes environment variables for credentials](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials). Example config below inspired by [this comment](https://github.com/grafana/loki/issues/2128#issuecomment-633693775).

The same approach might work for Azure (I'm unable to test with Azure). Based on the [Azure Go SDK docs](https://learn.microsoft.com/en-us/samples/azure-samples/azure-sdk-for-go-samples/azure-sdk-for-go-samples/), you can set `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET` via environment variables.

helm values:

```yaml
write: 
  extraEnvFrom:
    - secretRef:
        name: loki-s3-credentials # contains AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
read:
  extraEnvFrom:
    - secretRef:
        name: loki-s3-credentials
backend:
  extraEnvFrom:
    - secretRef:
        name: loki-s3-credentials
```

Secret config:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: loki-s3-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YOUR_ACCESS_KEY_ID_HERE
  AWS_SECRET_ACCESS_KEY: YOUR_AWS_SECRET_ACCESS_KEY_HERE
  ```
  
Alternatively, you could try using [environment variable expansion](https://grafana.com/docs/loki/latest/configuration/#use-environment-variables-in-the-configuration) in the configuration by passing in `-config.expand-env=true` via `extraArgs` and use the `${VAR}` syntax in the config. I was unable to get this working with s3, it wasn't expand the variables. I am unable to test with Azure.

helm values (untested):
```yaml
loki:
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    type: azure
    azure:
      accountName: ${AZURE_ACCOUNT_NAME}
      accountKey: ${AZURE_ACCOUNT_KEY}
      useManagedIdentity: false
      useFederatedToken: false
      userAssignedId: null
      requestTimeout: null
read:
  extraArgs:
    - "-config.expand-env=true"
write:
  extraArgs:
    - "-config.expand-env=true"
backend:
  extraArgs:
    - "-config.expand-env=true"
```

Secret config:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: loki-azure-credentials
type: Opaque
data:
  AZURE_ACCOUNT_NAME: YOUR_AZURE_ACCOUNT_NAME_HERE
  AZURE_ACCOUNT_KEY: YOUR_AZURE_ACCOUNT_KEY_HERE
```

**Comment by sinacek** [comment]
> ```yaml
> apiVersion: v1
> kind: Secret
> metadata:
>   name: loki-azure-credentials
> type: Opaque
> data:
>   AZURE_ACCOUNT_NAME: YOUR_AZURE_ACCOUNT_NAME_HERE
>   AZURE_ACCOUNT_KEY: YOUR_AZURE_ACCOUNT_KEY_HERE
> ```
@slyt please change example to use `stringData:` instead of `data:`. I'm use to use helm and missed that there is missing base64. Thanks for all

**Comment by lausserl** [comment]
Hi, I tried to configure the secrets for an azure blob storage the last few days and ran into issues with the configuration as described.
I have tried this configuration 

> helm values (untested):
> 
> ```
> loki:
>   storage:
>     bucketNames:
>       chunks: chunks
>       ruler: ruler
>       admin: admin
>     type: azure
>     azure:
>       accountName: ${AZURE_ACCOUNT_NAME}
>       accountKey: ${AZURE_ACCOUNT_KEY}
>       useManagedIdentity: false
>       useFederatedToken: false
>       userAssignedId: null
>       requestTimeout: null
> read:
>   extraArgs:
>     - "-config.expand-env=true"
> write:
>   extraArgs:
>     - "-config.expand-env=true"
> backend:
>   extraArgs:
>     - "-config.expand-env=true"
> 
> ```
> Secret config: 
> 
> ```
> apiVersion: v1
> kind: Secret
> metadata:
>   name: loki-azure-credentials
> type: Opaque
> stringData:
>   AZURE_ACCOUNT_NAME: YOUR_AZURE_ACCOUNT_NAME_HERE
>   AZURE_ACCOUNT_KEY: YOUR_AZURE_ACCOUNT_KEY_HERE
> ``` 

I tried with `config.expand-env=true` and with the `secretRef`, but I always get `illegal base64 data at input byte 0`. 

I have tried it with putting the AZURE_ACCOUNT_KEY directly into the helm chart, this works well, but as soon as I use a secret, I get a base64 error.

Do you have any suggesetions on why this could still be?

**Comment by Aangbaeck** [comment]
@lausserl Hi, did you solve it? I have the exact same issue. I have put many hours into trying to solve this but could not.

**Comment by Sargastico** [comment]
@slyt @lausserl @Aangbaeck I am facing the same problem using the loki-stack chart. Do you have any idea how to configure the `values.yaml` file to save the logs on Azure Storage? I can't keep any secrets on my `values.yaml`.

**Comment by faustodavid** [comment]
Hi, for me the explanation of @slyt works with Azure Storage.

This is how I did it using `AzureKeyVaultSecret`.

### Step 1: Store Secrets in Azure Key Vault
Ensure your Azure storage **account name** and **key** are securely stored in an Azure Key Vault.

### Step 2: Define AzureKeyVaultSecret in Helm Template
Go to the Helm Templates directory and create a file that defines the `AzureKeyVaultSecret`. This configuration creates Kubernetes secrets from the Azure Key Vault and outputs two environment variables, `AZURE_ACCOUNT_NAME` and `AZURE_ACCOUNT_KEY`.

Here's the Helm template for the Azure Key Vault secret:
```yaml
# Template for the storage account key
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: loki-az-storage-account-key
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  vault:
    name: {{ .Values.kvAzName }}
    object:
      name: {{ .Values.kvAzStorageAccountKey }}
      type: secret
  output:
    secret:
      name: loki-az-storage-account-key
      dataKey: AZURE_ACCOUNT_KEY

---

# Template for the storage account name
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: loki-az-storage-account-name
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  vault:
    name: {{ .Values.kvAzName }}
    object:
      name: {{ .Values.kvAzStorageAccountName }}
      type: secret
  output:
    secret:
      name: loki-az-storage-account-name
      dataKey: AZURE_ACCOUNT_NAME
```

### Step 3: Configure values.yaml for Each Environment
For each environment, such as staging or production, update the values-{env}.yaml file with the following parameters:
```yaml
kvAzName: "YOUR_KEYVAULT_NAME"
kvAzStorageAccountKey: "THE_SECRET_NAME_FOR_ACCOUNT_KEY"
kvAzStorageAccountName: "THE_SECRET_NAME_FOR_ACCOUNT_NAME"
```

### Step 4: Update Loki's values.yaml
Update the `values.yaml` file used by Loki's Helm chart with the secrets that will be injected:
```yaml
loki:
  storage:
    azure:
      accountName: ${AZURE_ACCOUNT_NAME}
      accountKey: ${AZURE_ACCOUNT_KEY}
```

And in each Loki component add:
```yaml
extraArgs:
   - "-config.expand-env=true"
extraEnvFrom:
  - secretRef:
      name: loki-az-storage-account-name
  - secretRef:
      name: loki-az-storage-account-key
```

I hope this help! 🙏🏼

**Comment by Sargastico** [comment]
For anyone looking for a solution using loki-stack chart, the problem is that apparently declaring the argument this way:

```
extraArgs:
   - "-config.expand-env=true"
```

Doesn't work and ends up resulting in a manifest with corrupted flags, like this:

```
spec:
  affinity: {}
  containers:
    - args:
        - '-config.file=/etc/loki/loki.yaml'
        - '-0=-config.expand-env=true'
```

Somehow, `-0=` is added to the arg, which is causing the container to crash.

What solved it for me was defining the yaml values like this:

```
  extraArgs:
    "-config.expand-env": "true"
  extraEnvFrom:
    - secretRef:
        name: loki-storage-secrets
    - secretRef:
        name: loki-storage-secrets
```

- https://github.com/grafana/helm-charts/issues/2705

**Comment by Sargastico** [comment]
still unable to make this work due to the `illegal base64 data at input byte 0` error reported by @lausserl

**Comment by Sargastico** [comment]
problem solved! Now I'm using the basic loki helm chart, this is my setup:

kustomization.yaml
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: loki
    repo: "https://grafana.github.io/helm-charts"
    version: "5.36.2"
    releaseName: loki
    namespace: monitoring
    valuesFile: values.yaml
```

values.yaml
```
loki:
  auth_enabled: false
  schema_config:
    configs:
    - from: "2020-12-11"
      index:
        period: 24h
        prefix: index_
      object_store: azure
      schema: v11
      store: boltdb-shipper
  storage:
    bucketNames:
      chunks: loki
    type: azure
    azure:
      accountName: ${AZURE_ACCOUNT_NAME}
      accountKey: ${AZURE_ACCOUNT_KEY}
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-storage-secrets
write:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-storage-secrets
read:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-storage-secrets
backend:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-storage-secrets
test:
  enabled: false
monitoring:
  dashboards:
    enabled: false
  selfMonitoring:
    enabled: true
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
```

**Comment by npuichigo** [comment]
The document of Loki should be enhanced like Tempo (https://grafana.com/docs/tempo/latest/configuration/hosted-storage/azure/#sample-configuration-for-tempo-distributed-mode) and mention the need to specify `extraArgs` and `extraEnv` configuration for all the services.

**Comment by mentlak0** [comment]
Today I have been using this document as a guide to help with a migration from minio to azure blob storage. 

This guide was a good foundation at first, but is out of date.

I use a connection string over ACCOUNT_NAME and ACCOUNT_KEY. But expecting it to work the same.

If anyone comes across this and is struggling, you need to add this to your values.yaml:

```
global:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-azure
```

Full values for reference:

```
global:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-azure
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'azure'
    bucketNames:
      chunks: loki-chunks
      ruler: loki-rules
    azure:
      accountName: lokichunksoss
      containerName: lokichunks
      connectionString: ${ACCOUNT_KEY}
  limits_config:
    max_global_streams_per_user: 10000
    max_concurrent_tail_requests: 200
    retention_period: 240h
  compactor:
    working_directory: /var/loki
    retention_enabled: true
    delete_request_store: azure
  filesystem:
    directory: /var/loki/chunks

  schemaConfig:
    configs:
    - from: "2022-01-11"
      store: tsdb
      object_store: azure
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
```

**Comment by eldinphp** [comment]
Here is what worked for me

values.yaml:
```

---
deploymentMode: SimpleScalable
fullnameOverride: loki

loki:
  enabled: true
  auth_enabled: false

  memcached:
    chunk_cache:
      enabled: false
    results_cache:
      enabled: false

  storage:
    type: azure
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    azure:
      accountName: ${AZURE_ACCOUNT_NAME}
      accountKey: ${AZURE_ACCOUNT_KEY}
      useManagedIdentity: false
      useFederatedToken: false
      userAssignedId: null
      requestTimeout: null
      endpointSuffix: null
      chunkDelimiter: null

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: azure
        schema: v13
        index:
          prefix: index_
          period: 24h

  compactor:
    working_directory: /var/loki/compactor

global:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: azure-storage-secret
---
```


secret azure-storage-secret.yaml
```

---
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: loki
type: Opaque
stringData:
  AZURE_ACCOUNT_NAME: something
  AZURE_ACCOUNT_KEY: something
---

```

**Comment by ynoamdev** [comment]
Thanks @eldinphp , its **work** for me

**Comment by jkroepke** [comment]
@JStickler i guess this can be closed.

**Comment by JStickler** [comment]
@jkroepke let me check to see if the docs are up to date before I close this.

**Comment by 3rk1n** [comment]
hi,

**Helm Repo:** grafana - https://grafana.github.io/helm-charts
**Hem Chart:** loki-6.46.0
**App Version:** 3.5.7

This method is not work for me.

**values.yaml**

```
deploymentMode: SingleBinary
singleBinary:
  replicas: 1

  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

  extraEnv:
    - name: AZURE_STORAGE_ACCOUNT_NAME
      valueFrom:
        secretKeyRef:
          name: loki-azure-secret
          key: AZURE_STORAGE_ACCOUNT_NAME
    - name: AZURE_STORAGE_ACCOUNT_KEY
      valueFrom:
        secretKeyRef:
          name: loki-azure-secret
          key: AZURE_STORAGE_ACCOUNT_KEY

global:
  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
      name: loki-azure-secret

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: azure
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage:
    type: azure
    azure:
      accountName: ${AZURE_STORAGE_ACCOUNT_NAME}
      accountKey: ${AZURE_STORAGE_ACCOUNT_KEY}
      useManagedIdentity: false
      useFederatedToken: false
      endpointSuffix: blob.core.windows.net
    bucketNames:
      chunks: loki

  extraArgs:
    - "-config.expand-env=true"
  extraEnvFrom:
    - secretRef:
        name: loki-azure-secret
    - secretRef:
        name: loki-azure-secret

  limits_config:
    allow_structured_metadata: true
    volume_enabled: true

  serviceAccount:
    create: true

  useTestSchema: false

test:
  enabled: false

selfMonitoring:
  enabled: false

lokiCanary:
  enabled: false
  replicas: 0
  daemonset:
    enabled: false
    replicas: 0

ruler:
  enabled: false
  enable_api: false
chunksCache:
  enabled: false
resultsCache:
  enabled: false

gateway:
  enabled: false
minio:
  enabled: false

backend:
  enabled: false
  replicas: 0
read:
  enabled: false
  replicas: 0
write:
  enabled: false
  replicas: 0

distributor:
  enabled: false
  replicas: 0
ingester:
  enabled: false
  replicas: 0
querier:
  enabled: false
  replicas: 0
queryFrontend:
  enabled: false
  replicas: 0
queryScheduler:
  enabled: false
  replicas: 0
compactor:
  enabled: false
  replicas: 0

indexGateway:
  enabled: false
  replicas: 0
bloomCompactor:
  enabled: false
  replicas: 0
bloomGateway:
  enabled: false
  replicas: 0
```

**secret yaml**

```
apiVersion: v1
kind: Secret
metadata:
  name: loki-azure-secret
  namespace: loki
type: Opaque
stringData:
  AZURE_STORAGE_ACCOUNT_NAME: <something-here>
  AZURE_STORAGE_ACCOUNT_KEY: <something-here>
```

**error log**

```
illegal base64 data at input byte 0
error initialising module: ruler-storage
github.com/grafana/dskit/modules.(*Manager).initModule
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
        /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108
github.com/grafana/loki/v3/pkg/loki.(*Loki).Run
        /src/loki/pkg/loki/loki.go:531
main.main
        /src/loki/cmd/loki/main.go:129
runtime.main
        /usr/local/go/src/runtime/proc.go:283
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1700
level=info ts=2025-11-20T08:16:00.948029057Z caller=main.go:126 msg="Starting Loki" version="(version=3.5.7, branch=release-3.5.x, revision=d5b382b9)"
level=info ts=2025-11-20T08:16:00.948072408Z caller=main.go:127 msg="Loading configuration file" filename=/etc/loki/config/config.yaml
level=error ts=2025-11-20T08:16:00.948472692Z caller=log.go:223 msg="error running loki" err="illegal base64 data at input byte 0\nerror initialising module: ruler-storage\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/loki/v3/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:531\nmain.main\n\t/src/loki/cmd/loki/main.go:129\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:283\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1700"
```
