### ISSUE TITLE
Only the data of the current object store is returned when multiple schema configs on different object stores 

### ISSUE THREAD

**Issue by rubenvw-ngdata** [grafana/loki#9148]
**Describe the bug**
When you have a multiple schema configurations on the same object store (but for example with a different schema version), the data is combined when querying it.
But when the schema configurations use a different object store, the data is not combined. In that case the data that is returned is based on the active schema config.

**To Reproduce**
I have this schema configuration
```
  schemaConfig:
    configs:
      - from: "2023-03-25"
        index:
          period: 24h
          prefix: loki_index_
        object_store: filesystem
        schema: v12
        store: boltdb-shipper
      - from: "2023-04-15"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v12
        store: boltdb-shipper
```
Up until yesterday evening, I retrieved the data in the filesystem store, but when I query today I only get the data from the s3 store, even when querying specifically on a timestamp where the filesystem store was used.

**Expected behavior**
The data from both stores is combined in the result

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Do not hesitate to shout out if you need more information.
