### ISSUE TITLE
promtail skip logs on Loki unavailable for a short time

### ISSUE THREAD

**Issue by pracucci** [grafana/loki#915]
**Describe the bug**
When Loki is unavailable (down, network partitioning, ...) `promtail` keeps sending a batch of tailed logs until the `backoff_config` `maxretries` is reached. Once reached, the batch is discarded and promtail tries to push the next batch of lines read from a file.

The backoff implementation is [inherited from Cortex](https://github.com/cortexproject/cortex/blob/master/pkg/util/backoff.go#L72), which implements a "Full jitter" backoff algorithm (the `minbackoff` is not a guaranteed minimum, just the base for the initial upper range for the random sleep time). I've sketched an [example in a google spreadsheet](https://docs.google.com/spreadsheets/d/11csf8vknb1mvm37UtiRZp1Q2lCq_zctXjdf6U4pb1DA/edit?usp=sharing).

The [`production/helm/promtail/values.yaml`](https://github.com/grafana/loki/blob/master/production/helm/promtail/values.yaml) is configured with:

```
    backoff_config:
      # Initial backoff time between retries
      minbackoff: 100ms
      # Maximum backoff time between retries
      maxbackoff: 5s
      # Maximum number of retries when sending batches, 0 means infinite retries
      maxretries: 5
```

This means that - on an average case - it's enough to have Loki unavailable for 1.55 seconds before start loosing logs.

Is there any reason for such a low number of `maxretries`? Shouldn't we try to reduce the likelihood of data loss, increasing it significantly?
