### ISSUE TITLE
no such file or directory errors moving to v2.8.0

### ISSUE THREAD

**Issue by pseymournutanix** [grafana/loki#9173]
**Describe the bug**
Queries are failing occasionally even going back a small period with errors in the query-frontend pods like:-
```
err="rpc error: code = Code(500) desc = open /var/loki/chunks/fake/81d2fe7eec97c0b8/MTg3OTMyYmIzMGY6MTg3OTM2MzEwODI6N2YxNzdjYjI=: no such file or directory\n"
```

I recently updated to v2.8.0 and moved to try the `tsdb` from the previous `boltdb_shipper` and I put this in the configuration:-
```
    schema_config:
      configs:
      - from: "2021-05-12"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v11
        store: boltdb-shipper
      # New TSDB schema below
      - from: "2023-04-13"
        store: tsdb
        object_store: filesystem
        schema: v12
        index:
          period: 24h
          prefix: loki_index_
```
At the time `2023-04-13` was a day in the future, and afaik from the metrics this is now in use.

In terms of the `storage_config` details I have:-
```
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
        cache_ttl: 168h
        resync_interval: 5s
        shared_store: s3
      filesystem:
        directory: /var/loki/chunks
      index_queries_cache_config:
        memcached_client:
          addresses: dnssrv+_memcached-client._tcp.loki-memcached-index-queries.grafana.svc.cluster.local
          consistent_hash: true
      tsdb_shipper:
        active_index_directory: /loki/tsdb_index
        cache_location: /loki/tsdb_index_cache
        cache_ttl: 168h
        resync_interval: 5s
        shared_store: s3
```

Is there any way to correct any of my mistakes, or rectify this situation ?
