### ISSUE TITLE
How do I reserve loki logs for 7 days

### ISSUE THREAD

**Issue by kubecto** [grafana/loki#9190]
I want to keep the logs of loki within 7 days. As I hope to pass the test and know how to modify, I set the log within 2 minutes, and the logs before 2 minutes will be cleared and deleted, but my requirement has not been realized. Who can help me check

This is my loki configuration file
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: logging
  labels:
    helm.sh/chart: promtail-3.11.0
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "2.4.2"
    app.kubernetes.io/managed-by: Helm
data:
  loki.yaml: |
    auth_enabled: false
    chunk_store_config:
      max_look_back_period: 0s
    compactor:
      shared_store: filesystem
      working_directory: /data/loki/boltdb-shipper-compactor
    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 3m
      chunk_retain_period: 2m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      max_transfer_retries: 0
      wal:
        dir: /data/loki/wal
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    schema_config:
      configs:
      - from: "2020-10-24"
        index:
          period: 24h
          prefix: index_
        object_store: filesystem
        schema: v11
        store: boltdb-shipper
    server:
      http_listen_port: 3100
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    table_manager:
      retention_deletes_enabled: true
      retention_period: 2m
```
I looked at grafana, but the log is still not deleted, there are still logs from 2 minutes ago, how should I adjust and keep loki's log, I want to delete the old log

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/94602819/233037921-c2bc502c-1135-4381-9889-91c3656fa10b.png">
