### ISSUE TITLE
Query frontend unable to connect to scheduler

### ISSUE THREAD

**Issue by mac133k** [grafana/loki#9193]
**Describe the bug**
I want to upgrade the read path in my Loki cluster and have a scalable query frontend with schedulers. I deployed one frontend, one scheduler and 16 queriers. According to the config documentation:

```
# Set to true to have the query schedulers create and place themselves in a
# ring. If no frontend_address or scheduler_address are present anywhere else in
# the configuration, Loki will toggle this value to true.
# CLI flag: -query-scheduler.use-scheduler-ring
[use_scheduler_ring: <boolean> | default = false]
```

Setting this to true and adding Etcd config to kvstore section did not have any effect - queriers and frontend did not connect to the scheuduler. When I added scheduler address to frontend and frontend worker config queriers could connect to the scheduler, but frontend could not showing the following error:

`level=error ts=2023-04-18T16:31:26.763259123Z caller=frontend_scheduler_worker.go:237 msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"error reading server preface: EOF\""`

When I pointed queriers to the frontend instead of the scheduler there were able to connect and query frontend was responding to queries, so basically queriers can connect to scheduler or frontend, but frontend cannot connect to scheduler. This is strange and suggest there is a problem (bug?) in the frontend.

All nodes in my cluster use the same gRPC and TLS configuration, here are some snippets from my config:

```
frontend:
  compress_responses: true
  log_queries_longer_than: 24h
  scheduler_address: qsch1-loki-XXX:9095
  scheduler_worker_concurrency: 8
  tail_tls_config:
    tls_ca_path: /etc/loki/ca.crt
    tls_cert_path: /etc/loki/client.crt
    tls_key_path: /etc/loki/client.key
frontend_worker:
  grpc_client_config:
    tls_ca_path: /etc/loki/ca.crt
    tls_cert_path: /etc/loki/client.crt
    tls_enabled: true
    tls_key_path: /etc/loki/client.key
  parallelism: 12
  scheduler_address: qsch1-loki-XXX:9095
querier:
  max_concurrent: 12
  multi_tenant_queries_enabled: true
  query_ingesters_within: 2h
  query_timeout: 10m
query_range:
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 2048
        ttl: 12h
query_scheduler:
  grpc_client_config:
    tls_ca_path: /etc/loki/ca.crt
    tls_cert_path: /etc/loki/client.crt
    tls_enabled: true
    tls_key_path: /etc/loki/client.key
server:
  grpc_listen_port: 9095
  grpc_server_max_concurrent_streams: 0
  grpc_server_max_recv_msg_size: 67108864
  grpc_server_max_send_msg_size: 67108864
  grpc_tls_config:
    cert_file: /etc/loki/client.crt
    client_auth_type: RequireAndVerifyClientCert
    client_ca_file: /etc/loki/ca.crt
    key_file: /etc/loki/client.key
  http_listen_port: 3100
  http_tls_config:
    cert_file: /etc/loki/client.crt
    client_auth_type: RequireAndVerifyClientCert
    client_ca_file: /etc/loki/ca.crt
    key_file: /etc/loki/client.key
  log_level: debug
```

**To Reproduce**
1.Deploy Loki query frontend, scheduler and queriers with the above configuration.

**Expected behavior**
Queriers and frontend connect to scheduler, fronted reponds to log queires.

**Environment:**
 - VMs with Rocky Linux 8
 - Loki version first 2.7.0, then 2.8.0 (upgrade did not solve the problem)
