### ISSUE TITLE
Complex labels option for docker configuration

### ISSUE THREAD

**Issue by wapmorgan** [grafana/loki#922]
**Describe the bug**
I tried to use complex label expanding with function `index` it in docker-compose plugin like this: 

```yml
loki-external-labels: container_name={{.Name}},cluster=${COMPOSE_PROJECT_NAME},service={{ index .Config.Labels 'com.docker.compose.service' }}
```

But this throws an error.

**To Reproduce**
1. Install loki docker plugin
2. Create docker-compose with configuration:
```yml
driver: loki
  options:
    loki-url: ${LOKI_PUSH_URL}
    loki-external-labels: container_name={{.Name}},cluster=${COMPOSE_PROJECT_NAME},service={{ index .Config.Labels 'com.docker.compose.service' }}
```
3. Try to run stack: `docker-compose up`
4. Got error.

**Expected behavior**
Expanding of template.

**Screenshots, promtail config, or terminal output**
```
ERROR: for ___  Cannot start service ___: failed to initialize logging driver: error creating logger: error creating loki logger: loki: could not expand label value: {{ index .Config.Labels "com.docker.compose.service" }} err : template: label_value:1:3: executing "label_value" at <index .Config.Labels...>: error calling index: index of untyped nil
```

Is there any opportunity to use `index` function or another hack to attach service name label to logs?

**Comment by mindfl** [comment]
## Some additional checks

Same error with your example:

``` shell
# docker ps --format='{{index .Config.Labels "com.docker.compose.project"}}'
template: :1:2: executing "" at <index .Config.Labels...>: error calling index: index of untyped nil
````

But if I understood correctly, then we have to use docker-cli "understandable" format. Like this:

``` shell
docker ps --format='{{.Label "com.docker.compose.project"}}'
docker ps --format='{{.Label "com.docker.compose.service"}}'
```

Attempt to use it:

``` yaml
    logging:
      driver: loki
      options:
        loki-url: "https://****/api/prom/push"
        loki-external-labels: 'container_name={{.Name}},compose_project={{.Label "com.docker.compose.project"}},compose_service={{.Label "com.docker.compose.service"}}'
```

No success:

```
ERROR: for loki  Cannot start service loki: failed to initialize logging driver: error creating logger: error creating loki logger: loki: could not expand label value: {{.Label "com.docker.compose.project"}} err : template: label_value:1:2: executing "label_value" at <.Label>: can't evaluate field Label in type *logger.Info

ERROR: for loki  Cannot start service loki: failed to initialize logging driver: error creating logger: error creating loki logger: loki: could not expand label value: {{.Label "com.docker.compose.project"}} err : template: label_value:1:2: executing "label_value" at <.Label>: can't evaluate field Label in type *logger.Info
ERROR: Encountered errors while bringing up the project.
```

So, I think, we can use fields from [docker documentaion](https://docs.docker.com/config/containers/logging/log_tags/) only. And It can be issue for docker.

## Loki docker driver possible "fix"

I haven't Go programming skills yet. But Loki gets information about swarm service from labels too:

``` go
...
	swarmServiceLabelKey = "com.docker.swarm.service.name"
	swarmStackLabelKey   = "com.docker.stack.namespace"

	swarmServiceLabelName = "swarm_service"
	swarmStackLabelName   = "swarm_stack"
...
	// parse docker swarms labels and adds them automatically to attrs
	swarmService := logCtx.ContainerLabels[swarmServiceLabelKey]
	if swarmService != "" {
		attrs[swarmServiceLabelName] = swarmService
	}
	swarmStack := logCtx.ContainerLabels[swarmStackLabelKey]
	if swarmStack != "" {
		attrs[swarmStackLabelName] = swarmStack
	}
...
```

So I think, it's should be easy to add compose labels support like this:

``` go
	composeServiceLabelKey = "com.docker.compose.service"
	composeProjectLabelKey   = "com.docker.compose.project"

	composeServiceLabelName = "compose_service"
	composeProjectLabelName   = "compose_project"
...
	// parse docker compose labels and adds them automatically to attrs
	composeService := logCtx.ContainerLabels[composeServiceLabelKey]
	if composeService != "" {
		attrs[composeServiceLabelName] = composeService
	}
	composeProject := logCtx.ContainerLabels[composeProjectLabelKey]
	if composeProject != "" {
		attrs[composeProjectLabelName] = composeProject
	}
```
And then It's not a bug. It's feature request, I think.
