### ISSUE TITLE
Credential access key has length 25, should be 32

### ISSUE THREAD

**Issue by Lusitaniae** [grafana/loki#9224]
Loki should be more flexible with key lengths to allow for the use of S3 compatible storage systems.

Currently I'm trying to setup Cloudflare R2 as an alternative to another S3 compatible storage but blocked by the api length checks.

```
Apr 21 11:20:09 mon-loki1 loki[435927]: level=error ts=2023-04-21T11:20:09.662386715Z caller=flush.go:222 org_id=fake msg="failed to flush user" err="InvalidArgument: Invalid Argument: Credential access key has length 25, should be 32\n\tstatus code: 400, request id: , host id: "
```

```
sudo /usr/local/bin/loki --version
loki, version 2.5.0 (branch: HEAD, revision: 2d9d0ee23)
  build user:       root@4779f4b48f3a
  build date:       2022-04-07T21:50:00Z
  go version:       go1.17.6
  platform:         linux/amd64

```

Config similar to
```
aws:
  bucketnames: "my-bucket-name"
  endpoint: "<long-unique-string>.r2.cloudflarestorage.com"
  region: "us-east-1"
  access_key_id: "<25-char-key-id>"
  secret_access_key: "<31-char-key>"
  insecure: false
  sse_encryption: false
  http_config:
    idle_conn_timeout: 90s
    response_header_timeout: 0s
    insecure_skip_verify: false
  s3forcepathstyle: true
```
