### ISSUE TITLE
Ring cfg error if set in service block

### ISSUE THREAD

**Issue by timansky** [grafana/loki#9242]
Hi
i've faced ring config issue.
According to documentation I can specify ring config per service config block.
My case is if ring is specified in service block, instead of `common` block there will be erros about additional parameters

For example for intester:
```
ingester:
    ring:
      kvstore:
        store: etcd
        etcd:
          endpoints:
            - host1:2379
            - host2:2379
            - host3:2379
      heartbeat_timeout: 1m
      heartbeat_period: 15s
    replication_factor: 2
```
 Will be fired an error: 
```
line n: field heartbeat_period not found in type ring.Config.
line n: field replication_factor not found in type ring.LifecyclerConfig.
```

PS
Which service is responsible for replication_factor: distributor or ingester?
According to documentation replication factor must be set in ingester block, but according to cli flags it must be set in distributor (`-distributor.replication-factor`).

PSS
I'm using hybrid(stateful is VM, stateless is container) microservice variant, and there is a lot of questions which parameter belongs(applies) to which service. This information absent in documentation.

PSSS
loki version: 2.8.0
