### ISSUE TITLE
Broken Grafana dashboards for Loki

### ISSUE THREAD

**Issue by dragoangel** [grafana/loki#9273]
**Describe the bug**
Build-in in Loki helm chart dashboards have many panels that has query with cluster label on metrics which metrics doesn't have and will never have, leading to broken dashboards. If edit panels and dashboard variables to remove cluster from places that missing this label, f.e.: loki logs itself, kube metrics, etc.

**To Reproduce**
1. Deployed kube-prometheus-stack with Grafana and dashboard-sc
3. Deployed loki via loki Helm chart with monitoring enabled
4. Checked new dashboards, half of panels on them doesn't work

**Expected behavior**
All panels on shipped with helm chart dashboards works.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.

**Comment by dragoangel** [comment]
@JStickler thanks to adding bug label, honestly I found documentation that explains some "prerequirements" that I missed. I think many people who deploy Loki via Helm chart will scratch their head and also miss them: [Loki - Configure monitoring and alerting - Prometheus Operator Prequisites](https://grafana.com/docs/loki/latest/installation/helm/monitor-and-alert/with-local-monitoring/#:~:text=Prometheus%20Operator%20Prequisites).

I think if `values.yaml` file would mention the link to this document at https://github.com/grafana/loki/blob/0bba510d192c50cca6ea84939eb97d063ff1b43e/production/helm/loki/values.yaml#L473 - it would help people a lot. Thank you :)

**Comment by dragoangel** [comment]
@JStickler btw `Loki / Logs` dashboard also missing `~` regex for log level, it allow take multiply log levels, but as not use `~` will fail to display anything.

**Comment by lmo-wt** [comment]
@dragoangel Could you explain exactly how you added `cluster` to Prometheus metrics? I followed the requirements from https://grafana.com/docs/loki/latest/setup/install/helm/monitor-and-alert/with-local-monitoring/#:~:text=Prometheus%20Operator%20Prequisites but I still have issues on the Grafana dashboards. Especially, the `loki_build_info` metric seems empty on the Prometheus data source.

**Comment by dragoangel** [comment]
> @dragoangel Could you explain exactly how you added `cluster` to Prometheus metrics? I followed the requirements from https://grafana.com/docs/loki/latest/setup/install/helm/monitor-and-alert/with-local-monitoring/#:~:text=Prometheus%20Operator%20Prequisites but I still have issues on the Grafana dashboards. Especially, the `loki_build_info` metric seems empty on the Prometheus data source.

just enable serviceMonitor if we speak about k8s, it should be not a problem:
```yaml
  # Monitoring section determines which monitoring features to enable
  monitoring:
    # Dashboards for monitoring Loki
    dashboards:
      # -- If enabled, create configmap with dashboards for monitoring Loki
      enabled: true
      # -- Annotations for the dashboards ConfigMap
      annotations:
        k8s-sidecar-target-directory: "Loki"
      # -- Labels for the dashboards ConfigMap
      labels:
        grafana_dashboard: "1"
    # Recording rules for monitoring Loki, required for some dashboards
    rules:
      # -- If enabled, create PrometheusRule resource with Loki recording rules
      enabled: true
      # -- Include alerting rules
      alerting: true
      # -- Additional groups to add to the rules file
      additionalGroups:
      - name: additional-loki-rules
        rules:
          - record: job:loki_request_duration_seconds_bucket:sum_rate
            expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job)
          - record: job_route:loki_request_duration_seconds_bucket:sum_rate
            expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job, route)
          - record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
            expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (node, namespace, pod, container)
    # ServiceMonitor configuration
    serviceMonitor:
      # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
      enabled: true
      # -- ServiceMonitor scrape interval
      # Default is 15s because included recording rules use a 1m rate, and scrape interval needs to be at
      # least 1/4 rate interval.
      interval: 15s
      # -- ServiceMonitor relabel configs to apply to samples before scraping
      # https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#relabelconfig
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: instance
      # -- If defined, will create a MetricsInstance for the Grafana Agent Operator.
      metricsInstance:
        # -- If enabled, MetricsInstance resources for Grafana Agent Operator are created
        enabled: true
    # Self monitoring determines whether Loki should scrape its own logs.
    # This feature currently relies on the Grafana Agent Operator being installed,
    # which is installed by default using the grafana-agent-operator sub-chart.
    # It will create custom resources for GrafanaAgent, LogsInstance, and PodLogs to configure
    # scrape configs to scrape its own logs with the labels expected by the included dashboards.
    selfMonitoring:
      enabled: true
    # The Loki canary pushes logs to and queries from this loki installation to test
    # that it's working correctly
    lokiCanary:
      enabled: true
      extraArgs:
        - -wait=2m0s
      tolerations:
        - effect: "NoSchedule"
          operator: "Exists"
        - effect: "NoExecute"
          operator: "Exists"
      resources: {}
```
