### ISSUE TITLE
store and object_store does not supported alibabacloud 

### ISSUE THREAD

**Issue by 13193310336** [grafana/loki#9280]
**Describe the bug**
store and object_store does not supported alibabacloud 

**To Reproduce**

1. storage_config configure alibabacloud
2. schema_config configure alibabacloud
3. start receiving: Unrecognized storage client alibabacloud, choose one of: aws, cassandra, inmemory, gcp, bigtable...

**Expected behavior**
normal operation

**Environment**

- Infrastructure: Docker
- Deployment tool: docker-compose
- Docker image: grafana/loki:2.8.1

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
<img width="837" alt="image" src="https://user-images.githubusercontent.com/19640682/234236850-38844da4-f4f8-41f1-ad97-69cebdf67321.png">
<img width="1885" alt="image" src="https://user-images.githubusercontent.com/19640682/234237065-b30a65bf-5bad-4a34-b749-f1f95ce78e3d.png">

**Comment by liguozhong** [comment]
hi @13193310336 ,Thanks for using loki and alibabacloud oss.
`object_store` is object storage config, which is responsible for storing the original log, and` alibabcloud oss` is just an object storage. So just implement `object_store`.

`store` is an configuration used to store index. Currently the most recommended by the loki community is to use `tsdb`, you can refer to the configuration below. 

```yaml
schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: alibabacloud
      schema: v11
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  alibabacloud:
    bucket: <bucket>
    endpoint: <endpoint>
    access_key_id: <access_key_id>
    secret_access_key: <secret_access_key>
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
    shared_store: alibabacloud
```

https://grafana.com/docs/loki/latest/operations/storage/tsdb/
More detailed documentation you can learn. In `tsdb` through `tsdb_shipper.shared_store`: `alibabacloud` indirectly uses `alibabacloud oss `as the index storage.
