### ISSUE TITLE
Example Loki Retention index and chunks ( S3 Storage)

### ISSUE THREAD

**Issue by csdnkrue1** [grafana/loki#9285]
I installed a loki stack and attached it to an S3 storage. The index files and chunks are created.
Unfortunately there is no automatic deletion. The compactor does not seem to delete them. I read in the documentation that I still need settings on the S3 storage side. 

I ran some tests this morning.
The marker files are written. Unfortunately the Compactor can not delete the logs.

```
/var/loki/compactor/retention/markers $ ls
1682487489654919561  1682488674124105964  1682489874314862064
```

Error in the compactor log
``` 
level=info ts=2023-04-26T07:40:42.544495905Z caller=marker.go:203 msg="no marks file found" 
```

Configuration:

```
schema_config:
        configs:
        - from: 2020-09-07
          store: boltdb-shipper
          object_store: aws
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
          chunks:
            prefix: loki_chunk
            period: 24h

      storage_config:
        boltdb_shipper:
           shared_store: s3
           active_index_directory: /var/loki/index
           cache_location: /var/loki/cache
           cache_ttl: 168h
           resync_interval: 5s
         aws:
            s3: https://<user>:<passwd>@<servername>/loki
            s3forcepathstyle: true
       
       limits_config:
        retention_period: 24h


       compactor:
        working_directory: /var/loki/retention
        shared_store: aws
        compaction_interval: 10m
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
   
```

This is the configuration that resolve my problem. The Loki Retention works well
