### ISSUE TITLE
loki-gateway routes /loki/api/v1/delete to loki-read

### ISSUE THREAD

**Issue by quarckster** [grafana/loki#9325]
**Describe the bug**
When Loki is deployd to Kubernetes in "scalable" mode `loki-gateway` routes `/loki/api/v1/delete` endpoint to `loki-read`. I believe this endpoint should be routed to `loki-backend` that has `compactor` module.

**To Reproduce**
1. Deploy Loki in "Scalable mode" on Kubernetes
2. `curl https://<HOSTNAME>/loki/api/v1/delete`

**Actual result**
```
404 page not found
```
nginx.conf that was generated by the helm chart:

```
worker_processes  5;  ## Default: 1
error_log  /dev/stderr;
pid        /tmp/nginx.pid;
worker_rlimit_nofile 8192;

events {
  worker_connections  4096;  ## Default: 1024
}

http {
  client_body_temp_path /tmp/client_temp;
  proxy_temp_path       /tmp/proxy_temp_path;
  fastcgi_temp_path     /tmp/fastcgi_temp;
  uwsgi_temp_path       /tmp/uwsgi_temp;
  scgi_temp_path        /tmp/scgi_temp;

  client_max_body_size 4M;

  proxy_read_timeout    600; ## 6 minutes
  proxy_send_timeout    600;
  proxy_connect_timeout 600;

  proxy_http_version    1.1;

  default_type application/octet-stream;
  log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
  access_log   /dev/stderr  main;

  sendfile     on;
  tcp_nopush   on;
  resolver kube-dns.kube-system.svc.somehost.local.;
  

  server {
    listen             8080;

    location = / {
      return 200 'OK';
      auth_basic off;
    }

    location = /api/prom/push {
      proxy_pass       http://loki-write.some_namespace.svc.somehost.local:3100$request_uri;
    }

    location = /api/prom/tail {
      proxy_pass       http://loki-read.some_namespace.svc.somehost.local:3100$request_uri;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location ~ /api/prom/.* {
      proxy_pass       http://loki-read.some_namespace.svc.somehost.local:3100$request_uri;
    }

    location ~ /prometheus/api/v1/alerts.* {
      proxy_pass       http://loki-backend.some_namespace.svc.somehost.local:3100$request_uri;
    }
    location ~ /prometheus/api/v1/rules.* {
      proxy_pass       http://loki-backend.some_namespace.svc.somehost.local:3100$request_uri;
    }
    location ~ /ruler/.* {
      proxy_pass       http://loki-backend.some_namespace.svc.somehost.local:3100$request_uri;
    }

    location = /loki/api/v1/push {
      proxy_pass       http://loki-write.some_namespace.svc.somehost.local:3100$request_uri;
    }

    location = /loki/api/v1/tail {
      proxy_pass       http://loki-read.some_namespace.svc.somehost.local:3100$request_uri;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location ~ /compactor/.* {
      proxy_pass       http://loki-backend.some_namespace.svc.somehost.local:3100$request_uri;
    }

    location ~ /distributor/.* {
      proxy_pass       http://loki-write.some_namespace.svc.somehost.local:3100$request_uri;
    }

    location ~ /ring {
      proxy_pass       http://loki-write.some_namespace.svc.somehost.local:3100$request_uri;
    }

    location ~ /ingester/.* {
      proxy_pass       http://loki-write.some_namespace.svc.somehost.local:3100$request_uri;
    }

    location ~ /store-gateway/.* {
      proxy_pass       http://loki-backend.some_namespace.svc.somehost.local:3100$request_uri;
    }

    location ~ /query-scheduler/.* {
      proxy_pass       http://loki-backend.some_namespace.svc.somehost.local:3100$request_uri;
    }
    location ~ /scheduler/.* {
      proxy_pass       http://loki-backend.some_namespace.svc.somehost.local:3100$request_uri;
    }

    location ~ /loki/api/.* {
      proxy_pass       http://loki-read.some_namespace.svc.somehost.local:3100$request_uri;
    }

    location ~ /admin/api/.* {
      proxy_pass       http://loki-write.some_namespace.svc.somehost.local:3100$request_uri;
    }
  }
}
```

As you can see `loki/api/v1/delete` falls into 

```
location ~ /loki/api/.* {
      proxy_pass       http://loki-read.some_namespace.svc.somehost.local:3100$request_uri;
    }
```

**Expected behavior**
The endpoint should return a list of the existing delete requests.

`loki/api/v1/delete` endpoint should be routed to `loki-backend`, it has `compactor` module that serves this endpoint.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Scalable mode
 - Chart version 5.0.0
 - Loki version 2.8.0

**Screenshots, Promtail config, or terminal output**
values.yaml content:

```yaml
global:
  clusterDomain: "some_hostname"
loki:
  existingSecretForConfig: "loki"
  runtimeConfig:
    overrides:
      tenant-1:
        retention_period: "336h"
      tenant-2:
        retention_period: "336h"
read:
  legacyReadTarget: false
test:
  enabled: false
gateway:
  ingress:
    enabled: true
    ingressClassName: "haproxy"
    annotations:
      external-dns.alpha.kubernetes.io/target: "ingress-controller.some_hostname"
    hosts:
      - host: "loki.some_hostname"
        paths:
          - path: "/"
            pathType: "ImplementationSpecific"
    tls:
      - hosts:
          - "loki.some_hostname"
```

"loki" secret content:

```yaml
auth_enabled: true
common:
  compactor_address: 'loki-backend'
  path_prefix: /var/loki
  replication_factor: 3
  storage:
    s3:
      access_key_id: <TRUNCATED>
      bucketnames: chunks
      endpoint: <TRUNCATED>
      secret_access_key: <TRUNCATED>
compactor:
  compaction_interval: 10m
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  retention_enabled: true
  shared_store: s3
  working_directory: /var/loki/retention
limits_config:
  enforce_metric_name: false
  max_cache_freshness_per_query: 10m
  reject_old_samples: true
  reject_old_samples_max_age: 336h
  retention_period: 336h
  split_queries_by_interval: 15m
memberlist:
  join_members:
  - loki-memberlist
query_range:
  align_queries_with_step: true
ruler:
  storage:
    s3:
      access_key_id: <TRUNCATED>
      bucketnames: ruler
      endpoint: <TRUNCATED>
      secret_access_key: <TRUNCATED>
    type: s3
runtime_config:
  file: /etc/loki/runtime-config/runtime-config.yaml
schema_config:
  configs:
  - from: "2022-01-11"
    index:
      period: 24h
      prefix: loki_index_
    object_store: s3
    schema: v12
    store: boltdb-shipper
server:
  grpc_listen_port: 9095
  http_listen_port: 3100
storage_config:
  hedging:
    at: 250ms
    max_per_second: 20
    up_to: 3
table_manager:
  retention_deletes_enabled: false
  retention_period: 0
```
