### ISSUE TITLE
Old chunks not getting deleted after retention period

### ISSUE THREAD

**Issue by shaikatz** [grafana/loki#936]
**Describe the bug**
I've configured 72h retention for my logs, but I can see chunks 5 years old filling my disk.

**To Reproduce**
This is my config:
```
auth_enabled: false
chunk_store_config:
  max_look_back_period: 0
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 15m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
  - from: "2018-04-15"
    index:
      period: 36h
      prefix: index_
    object_store: filesystem
    schema: v9
    store: boltdb
server:
  http_listen_port: 3100
storage_config:
  boltdb:
    directory: /data/loki/index
  filesystem:
    directory: /data/loki/chunks
table_manager:
  retention_deletes_enabled: true
  retention_period: 72h
```

**Expected behavior**
Chunks older than 72h should be deleted.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

**Screenshots, promtail config, or terminal output**
The index files being rotated:
```
-rw-r--r--    1 10001    10001     206.3M Aug 23 15:29 index_12086
-rw-r--r--    1 10001    10001      56.2M Aug 24 00:09 index_12087
-rw-r--r--    1 10001    10001      64.0K Aug 24 00:08 index_12088
```

The cunks file not being rotated, this is my chunks folder oldest and newest files:
```
/data/loki/chunks $ ls -lt | tail -1
-rw-r--r--    1 10001    10001       181645 Aug 20 10:38 ZmFrZS9jYTczYjY1YTMxNzE5YWJjOjE2Y2FlOTg1ZTc4OjE2Y2FlOWFkZTEzOjQ2MzE3NjYw
/data/loki/chunks $ ls -ltr | tail -1
-rw-r--r--    1 10001    10001       151552 Aug 24 00:09 ZmFrZS82Y2U1ODc3ZmU2YjM3OWQ1OjE2Y2MwZDMxMDhmOjE2Y2MwZWIwZjRlOjI4YzVlN2I5
```

We can see 5 days of logs although I've configured 72h.
