### ISSUE TITLE
Ruler can not access AWS Prometheus throughout sigv4_auth configuration

### ISSUE THREAD

**Issue by antonio-tolentino** [grafana/loki#9438]
**Describe the bug**
I have configured Loki Ruler to send metrics to AWS Prometheus api using sigv4_auth and web identity token integration with EKS but I have got "HTTP status 403 Forbidden".  I am not sure if I am missing something in terms of configuration but it seems to be correct because I have applied the same approach to Grafana to access AWS Prometheus api and it has worked perfectly.

**To Reproduce**
Steps to reproduce the behaviour:
1. Started Loki 2.8.2

**Expected behaviour**
It is expected that Loki ruler could access AWS Prometheus API exactly the same way Grafana does when  sigv4_auth is configured.

**Environment:**
 - Infrastructure: Kubernetes (EKS)
 - Deployment tool: helm

**Screenshots, Promtail config, or terminal output**
Loki error log:
```
ts=2023-05-09T13:11:11.91954568Z caller=dedupe.go:112 storage=registry manager=tenant-wal instance=recording component=remote level=info remote_name=recording-rw-default url=https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-11111111-2222-3333-4444-55555555555/api/v1/remote_write msg="Done replaying WAL" duration=4m36.806586268s
ts=2023-05-09T13:11:15.198583234Z caller=dedupe.go:112 storage=registry manager=tenant-wal instance=recording component=remote level=error remote_name=recording-rw-default url=https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-11111111-2222-3333-4444-55555555555/api/v1/remote_write msg="non-recoverable error" count=1 exemplarCount=0 err="server returned HTTP status 403 Forbidden: {\"message\":\"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.\\n\\nThe Canonical String for this request should have been\\n'POST\\n/workspaces/ws-11111111-2222-3333-4444-55555555555/api/v1/remote_write\\n\\ncontent-encoding:snappy\\ncontent-type:application/x-protobuf\\nhost:aps-workspaces.eu-central-1.amazonaws.com\\nx-amz-date:20230509T131115Z\\nx-amz-security-token:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```

**Details of configuration**
Environment variables injected by EKS due to service account annotated with role "**arn:aws:iam::123456789123:role/loki"** : 
```
AWS_STS_REGIONAL_ENDPOINTS=regional
AWS_DEFAULT_REGION=eu-central-1
AWS_REGION=eu-central-1
AWS_ROLE_ARN=arn:aws:iam::123456789123:role/loki
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

Role **"arn:aws:iam::123456789123:role/loki"** permissions to access AWS Prometheus api:
```
    {
      "Version": "2012-10-17",
      "Statement": [
          {
            "Action": [
                "aps:*"
            ],
            "Resource": "*",
            "Effect": "Allow"
          }
      ]
    }
```

**Loki complete configuration:**

```
auth_enabled: false
common:
  compactor_address: 'loki'
  path_prefix: /var/loki
  replication_factor: 1
  storage:
    s3:
      bucketnames: loki-s3-bucket
      insecure: false
      region: eu-central-1
      s3: s3://eu-central-1/loki-s3-bucket
      s3forcepathstyle: true
compactor:
  compaction_interval: 10m
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  retention_enabled: true
  shared_store: s3
  working_directory: /var/loki/compactor
index_gateway:
  mode: ring
limits_config:
  enforce_metric_name: false
  max_cache_freshness_per_query: 10m
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 168h
  split_queries_by_interval: 15m
memberlist:
  join_members:
  - loki-memberlist
query_range:
  align_queries_with_step: true
ruler:
  enable_api: true
  remote_write:
    client:
      sigv4:
        region: eu-central-1
      url: https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-11111111-2222-3333-4444-55555555555/api/v1/remote_write
    config_refresh_period: 10s
    enabled: true
  ring:
    kvstore:
      store: inmemory
  rule_path: /tmp/loki/rules-tmp
  storage:
    local:
      directory: /etc/loki/rules
    type: local
  wal:
    dir: /var/loki/ruler-wal
runtime_config:
  file: /etc/loki/runtime-config/runtime-config.yaml
schema_config:
  configs:
  - from: "2023-04-01"
    index:
      period: 24h
      prefix: loki_index_
    object_store: s3
    schema: v12
    store: tsdb
server:
  grpc_listen_port: 9095
  http_listen_port: 3100
storage_config:
  aws:
    s3: s3://eu-central-1/loki-s3-bucket
    s3forcepathstyle: true
  hedging:
    at: 250ms
    max_per_second: 20
    up_to: 3
  tsdb_shipper:
    active_index_directory: /var/loki/tsdb-index
    cache_location: /var/loki/tsdb-cache
    cache_ttl: 24h
    shared_store: s3
table_manager:
  retention_deletes_enabled: false
  retention_period: 0
```
