### ISSUE TITLE
How to configure local filesystem

### ISSUE THREAD

**Issue by JPFrancoia** [grafana/loki#9478]
Hi,

I'm running Grafana and Prometheus successfully and my microk8s cluster. They work flawlessly. I'm now trying to setup Loki. I have some success, however I'm still unable to configure the local filesystem.

Here is what I did:

```
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update
helm upgrade --install loki grafana/loki-stack -f loki-values.yaml
```

And here is the content of `loki-values.yaml`:

```yaml
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /home/djipey/loki/chunks
      rules_directory: /home/djipey/loki/rules
  rulerConfig:
    storage:
      type: local
singleBinary:
  replicas: 1
```

The dir `/home/djipey/loki` exists on the machine and I chmoded it 777 so I don't expect any permission issues.

The setup above works, and I can create a Loki data source in Grafana, and it contains the data I expect. However, the `loki` folder statys empty. A describe on the loki pod hints that the storage config is ignored:

```
Volumes:
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  loki
    Optional:    false
  storage:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-w5tz2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
```

I have read several threads (e.g: https://github.com/grafana/loki/issues/7267) but I still can't figure it out. Would you be able to help please?

**Comment by dels78** [comment]
@JPFrancoia FWIW, since there doesn't seem to be any support here, I was able to fix my StatefulSet by applying this patch with kustomize:
```yml

patch-sts.yaml:
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki

spec:
  template:
    spec:
      securityContext:
        # this is to make sure i have the allowed pid/gid for the nfs mount, you may not need this if you just want to change the directory
        runAsUser: 1000
        fsGroup: 1000
      volumes:
        - name: storage
          emptyDir: null
          nfs:
            path: /volume1/loki
            server: <ip of nfs server>
```

kustomization.yaml:
```yml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: robusta

patches:
  - path: patch-sts.yaml
    target:
      kind: StatefulSet

```

**Comment by JPFrancoia** [comment]
Hey :wave: I ultimately managed to get the filesystem storage working (well, kinda....). Data is written to the right dir, but the rotation of the log doesn't work (it consumes disk space indefinitely).

loki-values.yaml

```yaml
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  commonStorageConfig:
    type: filesystem
  rulerConfig:
    storage:
      type: local
singleBinary:
  replicas: 1
  persistence:
    storageClass: local-loki
    enabled: true
    size: 5Gi

table_manager:
  retention_deletes_enabled: true
  retention_period: 24h
```

pv-loki.yaml

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-db
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /home/djipey/loki
    type: DirectoryOrCreate
  storageClassName: local-loki
```

**Comment by omidraha** [comment]
I tried it but I got this error:

```
waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrato
```

```
fluent-bit   29m         Normal    Created                  pod/loki-gateway-7b667dfd4f-jfwkq                            Created container nginx
fluent-bit   29m         Normal    Started                  pod/loki-gateway-7b667dfd4f-jfwkq                            Started container nginx
fluent-bit   20m         Normal    Killing                  pod/loki-gateway-7b667dfd4f-jfwkq                            Stopping container nginx
fluent-bit   20m         Warning   Unhealthy                pod/loki-gateway-7b667dfd4f-jfwkq                            Readiness probe failed: Get "http://11.0.65.4:8080/": dial tcp 11.0.65.4:8080: connect: connection refused
fluent-bit   29m         Normal    SuccessfulCreate         replicaset/loki-gateway-7b667dfd4f                           Created pod: loki-gateway-7b667dfd4f-jfwkq
fluent-bit   4m46s       Normal    Scheduled                pod/loki-gateway-8556c965c5-b25gz                            Successfully assigned fluent-bit/loki-gateway-8556c965c5-b25gz to ip-11-0-154-236.us-west-2.compute.internal
fluent-bit   4m45s       Normal    Pulling                  pod/loki-gateway-8556c965c5-b25gz                            Pulling image "docker.io/nginxinc/nginx-unprivileged:1.23-alpine"
fluent-bit   4m42s       Normal    Pulled                   pod/loki-gateway-8556c965c5-b25gz                            Successfully pulled image "docker.io/nginxinc/nginx-unprivileged:1.23-alpine" in 2.899765379s (2.89977626s including waiting)
fluent-bit   4m42s       Normal    Created                  pod/loki-gateway-8556c965c5-b25gz                            Created container nginx
fluent-bit   4m42s       Normal    Started                  pod/loki-gateway-8556c965c5-b25gz                            Started container nginx
fluent-bit   4m46s       Normal    SuccessfulCreate         replicaset/loki-gateway-8556c965c5                           Created pod: loki-gateway-8556c965c5-b25gz
fluent-bit   29m         Normal    ScalingReplicaSet        deployment/loki-gateway                                      Scaled up replica set loki-gateway-7b667dfd4f to 1
fluent-bit   4m46s       Normal    ScalingReplicaSet        deployment/loki-gateway                                      Scaled up replica set loki-gateway-8556c965c5 to 1
fluent-bit   29m         Normal    WaitForFirstConsumer     persistentvolumeclaim/storage-loki-01b06ea7-0                waiting for first consumer to be created before binding
fluent-bit   29m         Normal    WaitForPodScheduled      persistentvolumeclaim/storage-loki-01b06ea7-0                waiting for pod loki-01b06ea7-0 to be scheduled
fluent-bit   24m         Normal    ExternalProvisioning     persistentvolumeclaim/storage-loki-01b06ea7-0                waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator
fluent-bit   54m         Normal    ExternalProvisioning     persistentvolumeclaim/storage-loki-255f1be4-0                waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrato
```

Code:

```python
import pulumi
import pulumi_kubernetes as kubernetes


def create_loki(namespace):
    """
    :param namespace:
    :return:
    @see: https://grafana.com/docs/loki/latest/installation/helm/install-monolithic/
    @see: https://grafana.com/docs/loki/next/setup/install/helm/reference/
    """
    fb = kubernetes.helm.v3.Release(
        "loki",
        kubernetes.helm.v3.ReleaseArgs(
            chart="loki",
            version="5.15.0",
            repository_opts=kubernetes.helm.v3.RepositoryOptsArgs(
                repo="https://grafana.github.io/helm-charts"
            ),
            namespace=namespace.metadata.name,
            values={
                "singleBinary": {
                    "replicas": 1,
                    "persistence": {
                        "storageClass": "loki-data",
                        "enabled": True,
                        "size": "5Gi",
                    }
                },
                "loki": {
                    "storage": {
                        "type": "filesystem"
                    },
                    "commonConfig": {
                        "replication_factor": 1
                    },
                    "commonStorageConfig": {
                        "type": "filesystem"
                    },
                    "rulerConfig": {
                        "storage": {
                            "type": "filesystem",
                        },
                    }

                }

            },
        ),
    )
    return fb


def create_loki_pv(namespace):
    kubernetes.core.v1.PersistentVolume(
        'loki-pv',
        metadata={
            'namespace': namespace.metadata.name,
        },
        spec={
            'access_modes': ["ReadWriteOnce"],
            'capacity': {
                "storage": "10Gi"
            },
            'host_path': {
                'path': "/home/ws/loki",
                'type': "DirectoryOrCreate"
            },
            'storage_class_name': "loki-data"
        },

    )
```

**Comment by Vetrixs** [comment]
I had a simlar setup but with a nfs storage system, what worked for me was switching from tablemanager to the compactor.

**Comment by JPFrancoia** [comment]
I'm regularly trying to solve this problem:

```
helm upgrade --install loki grafana/loki --values loki-values.yaml
```

loki-values.yaml:

```yaml
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
singleBinary:
  replicas: 1

#table_manager:
  #retention_deletes_enabled: true
  #retention_period: 72h

compactor:
  compaction_interval: 10m
  retention_enabled: true
  retention_period: 72h
```

Nothing really works. Lots of files keep getting created...

**Comment by Vetrixs** [comment]
I had overwritten the auto config and wrote my own, here is a snippet of my own configuration.

loki-values.yaml:
```yaml
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'

  config: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /var/loki/loki/boltdb-shipper-active
        cache_location: /var/loki/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /var/loki/loki/chunks

    compactor:
      shared_store: filesystem
      working_directory: /var/loki/loki/boltdb-shipper-compactor
      compaction_interval: 10m
      retention_enabled: true
      deletion_mode: 'filter-and-delete'
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
    
    limits_config:
      retention_period: 7d
      allow_deletes: true
```

**Comment by JPFrancoia** [comment]
I just tried that but I ran into permission errors:

```
msg="error running loki" err="creating WAL folder at \"/wal\": mkdir wal: read-only file system\nerror
```

I tried pointing to my loki directory in my /home, but I'm getting kinda the same error: "/home/djipey is read-only"

**Comment by viertel97** [comment]
Any news regarding this? I am also thinking about using Loki in my microk8s cluster.

**Comment by ralfzen** [comment]
Did you check the monolithic installation: https://grafana.com/docs/enterprise-logs/latest/setup/install/helm/install-monolithic/

**Comment by mztnnrt** [comment]
> Did you check the monolithic installation for smaller devices?
> https://grafana.com/docs/enterprise-logs/latest/setup/install/helm/install-monolithic/
>  https://github.com/grafana/loki/issues/9478#issuecomment-2451608032

This setting is maybe S3 (default). We have try to hostpath, but I think I'll change my mind, use the cloud storage honestly.

**Comment by rgauthey** [comment]
Any news on using loki with a local filesystem ? I'd like to use it on my k3s cluster

**Comment by ralfzen** [comment]
I've installed Loki with the following values but I haven't tested it. Feel free to try it out; feedback is appreciated. For the dynamic local pv provisioner I've used openebs: https://github.com/openebs/openebs/tree/51ca25f89ef00996e1847e306f675f1d461d20bb/charts#install-openebs-helm-chart-with-default-values
`
deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: filesystem # we're storing on filesystem so there's no real persistence here.
      schema: v13
singleBinary:
  replicas: 1
  persistence:
    # -- Enable StatefulSetAutoDeletePVC feature
    enableStatefulSetAutoDeletePVC: true
    # -- Enable persistent disk
    enabled: true
    # -- Size of persistent disk
    size: 10Gi
    # -- Storage class to be used.
    # If defined, storageClassName: <storageClass>.
    # If set to "-", storageClassName: "", which disables dynamic provisioning.
    # If empty or set to null, no storageClassName spec is
    # set, choosing the default provisioner (gp2 on AWS, standard on GKE, AWS, and OpenStack).
    storageClass: openebs-hostpath
    # # -- Selector for persistent disk
    # selector: null
    # # -- Annotations for volume claim
    # annotations: {}
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0

gateway:
  enabled: false

ingress:
  enabled: true
  ingressClassName: "traefik"
  hosts:
    - my-loki.local
`

**Comment by iby-dev** [comment]
I am having similar issues using the following config, using the same chart i believe:

- chart.yaml
```
apiVersion: v2
name: detect
description: A generated Helm Chart for detect

version: 0.0.1
appVersion: 0.0.1
keywords:
  - detect

dependencies:
  - name: opentelemetry-collector
    version: 0.119.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: loki
    version: 6.6.2 # Use the latest stable version or the version you prefer
    repository: https://grafana.github.io/helm-charts
```

- values-loki.yaml

```
deploymentMode: SingleBinary

loki:
  enabled: true
  isDefault: true
  auth_enabled: false

  server:
    http_listen_port: 3100

  commonConfig:
    replication_factor: 1
    path_prefix: /loki

  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage_config:
    filesystem:
      directory: /loki/chunks

  limits_config:
    retention_period: 744h # 31 days
    max_query_length: 721h
    max_query_parallelism: 32
    max_streams_per_user: 10000
    creation_grace_period: 168h # 7 days
    split_queries_by_interval: 24h
    allow_structured_metadata: true
    volume_enabled: true
    discover_log_levels: true

  pattern_ingester:
    enabled: false

  tracing:
    enabled: false

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    storageClass: default
    existingClaim: loki-pvc

service:
  type: ClusterIP
  port: 3100

podLabels:
  app.kubernetes.io/name: otel-loki
```

I have tried with the `bucketNames` property and regardless i get the same error:

```
storage:
  type: filesystem
  bucketNames:
    chunks: chunks
    ruler: ruler
    admin: admin
```

- error output

`error calling include: template: detect/charts/loki/templates/_helpers.tpl:228:19: executing "loki.commonStorageConfig" at <$.Values.loki.storage.bucketNames.chunks>: nil pointer evaluating interface {}.chunks`

Any help is greatly appreciate, I am not a k8s expert.

**Comment by ralfzen** [comment]
> I am having similar issues using the ...
> ```
> storage:
>   type: filesystem
>   bucketNames:
>     chunks: chunks
>     ruler: ruler
>     admin: admin
> ```
> 
> - error output
> 
> `error calling include: template: detect/charts/loki/templates/_helpers.tpl:228:19: executing "loki.commonStorageConfig" at <$.Values.loki.storage.bucketNames.chunks>: nil pointer evaluating interface {}.chunks`

Is your "storage" definition within Values.loki?

**Comment by iby-dev** [comment]
> r "storage" definition within Valu

I could do with an example, there is larger storage definition on the parent values file
but there is no "chunks" storage definition if that is what the error is enforcing.

I just want to use filesystem as my storage type. I don't need buckets.

> Loki requires a bucket for chunks and the ruler. GEL requires a third bucket for the admin API.
    # Please provide these values if you are using object storage.

_I have been using chart versions v6.1.* +_

The current config i am working with and failing:


```
# root key for Loki Configuration
chunks_cache:
  enabled: false

loki:
  enabled: true
  name: "otel-loki"
  image:
    registry: docker.io
    repository: grafana/loki
    pullPolicy: IfNotPresent

  podLabels:
    app.kubernetes.io/name: otel-loki

  fullnameOverride: "otel-loki"

  # Loki configuration
  auth_enabled: false
  server:
    http_listen_port: 3100
    grpc_listen_port: 9095
    log_level: info
  pattern_ingester:
    enabled: false
  ingester: {}
  limits_config:
    retention_period: 744h # 31 days
    max_query_length: 721h
    max_query_parallelism: 32
    max_streams_per_user: 10000
    creation_grace_period: 168h # 7 days
    split_queries_by_interval: 24h
    allow_structured_metadata: true
    metric_aggregation_enabled: true
    volume_enabled: true # This is for volume-based retention, ensure it aligns with your retention strategy.
    discover_log_levels: true
  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: 'filesystem'
        schema: v13
        index:
          prefix: index_
          period: 24h
  storage_config:
    tsdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
      shared_store: 'filesystem'
  tracing:
    enabled: false
  storage:
    type: 'filesystem'
  commonConfig:
    replication_factor: 1
  common:
    path_prefix: /var/loki
    storage:
      type: 'filesystem'
    replication_factor: 1
    ring:
      kvstore:
        store: inmemory

  service:
    type: ClusterIP
    port: 3100
    targetPort: 3100
    labels:
      app: loki

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    storageClass: "default"
  config:

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
```

**Comment by iby-dev** [comment]
I tried pivoting back to an older release (`6.0.0`) of the chart to "try" and workaround the issue but this has been a terrible waste of a work day. The older chart refuses to acknowledge the presence of the schema config block. 🙃. This has been my first experience trying to configure an OSS helm chart. 😞 

![Image](https://github.com/user-attachments/assets/902fea68-7198-44ff-a8ed-46e3e7983a24)

**Comment by Starttoaster** [comment]
These helm values worked for me until sometime between helm chart version 6.42.0 and 6.45.1
```
loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
      enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true
  storage:
    type: 'filesystem'
  auth_enabled: false

deploymentMode: SingleBinary
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 60Gi
    storageClass: ceph-rbd
```
But it seems like the chart maintainers broke filesystem storage type setups once again. It seems like they like to do this every year or so.

**Comment by adivis12** [comment]
@Starttoaster did you get this figured out?

**Comment by Starttoaster** [comment]
@advis12 with the latest helm chart errors these values give? It was something where you just specify a fake bucket name that doesn't even get used, because the chart maintainers don't give two deuces about making sure their changes haven't broken local storage configurations again.

**Comment by adivis12** [comment]
@Starttoaster, sorry for the confusion. Your comment above made me think that the recent chart updates broke your storage configuration. I'm doing a first-time setup and have been struggling getting the ruler and reader talking to each other with rule.yaml files on local storage. I thought it might be because of a broken chart you mentioned.

I have been trying to figure out how to set up "local" storage for the ruler and reader for days and am so close to getting this to work but can't seem to find the right combination of values.

Do you have an example of working local storage configuration?

**Comment by adivis12** [comment]
@Starttoaster also I'm aware of the fake "tenant" requirement but a fake bucket name is news to me. That might be relevant to me.

**Comment by Starttoaster** [comment]
@advis12 I don't have helm values that do what you need them to do. I'm running Loki in single binary mode with one replica. I only use local filesystem storage at home, in non-production, because I don't want to pay for S3. I have examples for that, as well as examples of working configuration in Simple Scalable mode with an S3 backend.

**Comment by adivis12** [comment]
@Starttoaster can you share the local filesystem config? It might not be a copy/paste of what I need but maybe it would still be helpful. I'm essentially trying to figure out how to properly populate this:
```
loki:
  rulerConfig:
    storage:
      type: local
      local:
        directory: /var/loki/rulestorage
    rule_path: "/var/loki/rules-temp/fake"
    ring:
      kvstore:
        store: inmemory
```

And whatever corresponding configuration might be relevant in the "read" block.

**Comment by Starttoaster** [comment]
This is the entirety of my local filesystem values yaml on the most current Helm chart release:
```yaml
loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  pattern_ingester:
      enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
  ruler:
    enable_api: true
  storage:
    type: 'filesystem'
    bucketNames:
      chunks: "thisisafakebucket" # Helm chart is now mad when this isn't set
      ruler: "thisisafakebucket"
      admin: "thisisafakebucket"
  auth_enabled: false

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 60Gi
    storageClass: ceph-rbd

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
gateway:
  enabled: false
chunksCache:
  enabled: false
resultsCache:
  enabled: false
lokiCanary:
  enabled: false
test:
  enabled: false
```
I don't use Loki's ruler directly, which is probably why this has been a simpler deployment for me. In some places, I do use it indirectly through Grafana, which I believe uses the ruler API.

**Comment by jkroepke** [comment]
```
    bucketNames:
      chunks: "thisisafakebucket" # Helm chart is now mad when this isn't set
      ruler: "thisisafakebucket"
      admin: "thisisafakebucket"
```

That should be fixed on next release.
