### ISSUE TITLE
Example for Promtail json pipeline deployed with loki-stack

### ISSUE THREAD

**Issue by JPFrancoia** [grafana/loki#9480]
Hi,
I have been at it for hours, but I haven't been able to figure this out. I have an app deployed on my k8s cluster that sends structured logs. I have Grafana + Loki + Promtail setup with loki-stack. I can see the logs in Grafana. But for now I only get the basic labels, like namespace, pod, etc. I would like to access the tags in the rest of the log entries.

I understand that I need to write a json pipeline. SO far I have a `loki-values.yaml` file:

```yaml
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /home/djipey/loki/chunks
      rules_directory: /home/djipey/loki/rules
  rulerConfig:
    storage:
      type: local
singleBinary:
  replicas: 1
promtail:
  enabled: true
  config:
    snippets:
      pipelineStages:
      - json:
          expressions:
            level: level
            path: path
      - labels:
          level: null
          path: null
```

And I use it like this:

```
helm upgrade --install loki grafana/loki-stack -f loki-values.yaml
```

However the above doesn't do anything. I've looked everywhere for a recent example of Promtail config setup with loki-stack, without success.

Would you have any example please?

**Comment by JPFrancoia** [comment]
Ok I managed to get it to work:

```
promtail:
  config:
    snippets:
      pipelineStages:
      - docker: {}
      - cri: {}
      - json:
          expressions:
            level: level
            path: path
            ts: ts
            time: time
            status: status
            method: method
            latency: latency
      - labels:
          level: ''
          path: ''
          status: ''
          method: ''
      - timestamp:
          source: ts
          format: RFC3339Nano
  enabled: true
```
