### ISSUE TITLE
container_name in azure_storage_config is not used

### ISSUE THREAD

**Issue by ivanmagdic** [grafana/loki#9483]
**Describe the bug**
When defining 'container_name' in 'azure_storage_config' a provided name is not used, and instead a 'chunks' name is used for the container name. It seems to be inherited from 'loki.storage.bucketNames.chunks' because if you change that value, for example, if we set it to 'logs', that container name ('logs') is used in config.yaml.

**To Reproduce**
1. Deploy and start Loki with Helm

**Expected behavior**
A 'container_name' that is defined in 'azure_storage_config ' property should be used instead of 'loki.storage.bucketNames.chunks' to define container name.

**Environment:**
 - Infrastructure: Kubernetes (AKS v1.26.3)
 - Deployment tool: HELM
 - Helm chart: https://grafana.github.io/helm-charts **loki** (chart version: 5.5.1, loki version: 2.8.2)

**Screenshots, Promtail config, or terminal output**
When using following Helm'values.yaml':
```
loki:
  auth_enabled: false
  server:
    http_listen_port: 3100
  commonConfig:
    replication_factor: 1
  storage:
    type: azure
    azure:
      accountName: REDACTED
      accountKey: REDACTED
      container_name: logs
```

loki 'config.yaml' is following:
```
auth_enabled: false
common:
  compactor_address: 'loki-backend'
  path_prefix: /var/loki
  replication_factor: 1
  storage:
    azure:
      account_key: REDACTED
      account_name: REDACTED
      container_name: chunks
      use_federated_token: false
      use_managed_identity: false
...
```

If we change the Helm 'values.yaml':
```
loki:
  auth_enabled: false
  server:
    http_listen_port: 3100
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: logs <--- This values is used
    type: azure
    azure:
      accountName: REDACTED
      accountKey: REDACTED
      container_name: loki
```

the 'config.yaml' will be like following:
```
auth_enabled: false
common:
  compactor_address: 'loki-backend'
  path_prefix: /var/loki
  replication_factor: 1
  storage:
    azure:
      account_key: REDACTED
      account_name: REDACTED
      container_name: logs
      use_federated_token: false
      use_managed_identity: false
...
```
