### ISSUE TITLE
Error "maximum of series (500) reached for a single query"

### ISSUE THREAD

**Issue by Bruno-Macedo** [grafana/loki#9487]
Hello,

Im using Promtail, Loki and Grafana as part of my bachelor thesis to implement a SIEM-simular solution. For the first test Im trying to detect SSH-based attacks using the rules and material provided by [Voidquark - Parsin SSH Logs with Grafana Loki](https://voidquark.com/parsing-ssh-logs-with-grafana-loki/).

With small files (40kb) I get no problem, but by using log files with (4mb) the problem starts:
_Error "maximum of series (500) reached for a single query"_

Im using the following query:
```
sum by (username) (count_over_time({job="sshlogs"} |="sshd[" |=": Failed" !~"invalid user" | pattern "<_> for <username> from <_> port" | __error__="" [$__interval]))
```

Grafana, Loki and Promtail are running in container in the following versions:
Grafana: v9.5.2
Loki:        2.8.2
Promtail: 2.8.2

I tried to adjust the loki config file severel times according to several posts in github, stack overflow  or grafana community. But I still run with this problem. My config file is the following:

```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  wal:
    enabled: true
    dir: /tmp/wal
  config:
    max_block_size: 67108864
    max_uncompressed_block_size: 67108864
    chunk_size: 1048576
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h       # Any chunk not receiving new logs in this time will be flushed
  max_chunk_age: 1h           # All chunks will be flushed when they hit this age, default is 1h
  chunk_target_size: 1048576  # Loki will attempt to build chunks up to 1.5MB, flushing first if chunk_idle_period or max_chunk_age is reached first
  chunk_retain_period: 30s    # Must be greater than index read cache TTL if using an index cache (Default index read cache TTL is 5m)
  max_transfer_retries: 0     # Chunk transfers disabled

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/boltdb-shipper-active
    cache_location: /tmp/loki/boltdb-shipper-cache
    cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /tmp/loki/boltdb-shipper-compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 1024
  ingestion_burst_size_mb: 1024
  ingestion_rate_strategy: global
  per_stream_rate_limit: 12MB
  max_query_series: 100000
  max_query_parallelism: 32
  split_queries_by_interval: 24h

query_scheduler:
  max_outstanding_requests_per_tenant: 10000
frontend:
  max_outstanding_per_tenant: 4096
  compress_responses: true
query_range:
  parallelise_shardable_queries: false

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 360s

ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
```
