### ISSUE TITLE
Grafana-Loki Datasource pompt "Data source connected, but no labels received"

### ISSUE THREAD

**Issue by JunejaTung** [grafana/loki#9492]
**Describe the bug**
The data source of loki in grafana prompt "
Data source connected, but no labels received. Verify that Loki and Promtail is configured properly.".
![image](https://github.com/grafana/loki/assets/13295415/e74d27f6-2680-4559-9dd9-6580318d88a8)

**To Reproduce**
 1. Started Loki (SHA or version)
docker run --name loki -d -v $(pwd):/mnt/config -v /etc/localtime:/etc/localtime -p 3100:3100 grafana/loki:2.8.0 -config.file=/mnt/config/loki-local-config.yaml -log.level=debug
```
auth_enabled: false
server:
  http_listen_port: 3100
common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 30  #修改每用户摄入速率限制，即每秒样本量，默认值为4M
  ingestion_burst_size_mb: 15  #修改每用户摄入速率限制，即每秒样本量，默认值为6M
analytics:
  reporting_enabled: false
```
2. Started Promtail (SHA or version) to tail '...'
docker run --name promtail -d -v $(pwd):/mnt/config -v /h3coasis/local_volumes/h3c_logs:/h3coasis/local_volumes/h3c_logs -v /var/log:/var/log -v /etc/localtime:/etc/localtime --link loki grafana/promtail:2.8.0 -config.file=/mnt/config/promtail-local-config_p2.yaml -log.level=debug
```
server:
  http_listen_port: 9080
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://172.30.254.1:3100/loki/api/v1/push
scrape_configs:
- job_name: service
  static_configs:
  - targets:
      - 172.30.254.1
    labels:
      job: servicelogs
      __path__: /home/azureuser/logs/*.log
target_config:
  sync_period: "60s"
```
3. Query: `{} term`
/loki/api/v1/labels ---> {"status":"success","data":["filename","job"]}

**Expected behavior**
Can query labels in grafana

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]
1. the lo address of the machine is 172.30.254.1
2. the container of loki and promtail  running , and there no error or exception in the out logs.
```
[root@iotvm132 loki]# docker ps | grep loki
fe96c59df253        grafana/loki:2.8.0                            "/usr/bin/loki -conf…"   45 hours ago        Up 45 hours         0.0.0.0:3100->3100/tcp   loki
[root@iotvm132 loki]# docker exec -ti fe96c59df253 /bin/ash
/ $ cd /tmp/loki/
/tmp/loki $ ls
boltdb-shipper-active  boltdb-shipper-cache   chunks                 compactor              rules                  wal
/tmp/loki $
```
```
[root@iotvm132 loki]# docker exec -ti 34c641d8b159 /bin/bash
root@34c641d8b159:/# more /tmp/positions.yaml
positions:
  /h3coasis/local_volumes/h3c_logs/services/172.17.0.5-iotsmartlockas-20230520.0.log: "39404"
  /h3coasis/local_volumes/h3c_logs/services/172.17.0.11-iotsmartlocakcfg-20230520.0.log: "19952"
  /h3coasis/local_volumes/h3c_logs/services/172.17.0.11-iotsmartlocakcfg-20230521.0.log: "6956"
  /h3coasis/local_volumes/h3c_logs/services/172.17.0.12-iotsmartlockns-20230520.0.log: "19870"
  /h3coasis/local_volumes/h3c_logs/services/172.17.0.13-iotsmartlocakcfg-20230520.0.log: "13010"
  /h3coasis/local_volumes/h3c_logs/services/172.17.0.16-iotsmartlockas-20230520.0.log: "3138"
  /h3coasis/local_volumes/h3c_logs/services/172.17.0.22-iotsmartlockas-20230520.0.log: "1543"
  /h3coasis/local_volumes/h3c_logs/services/172.17.0.23-iotsmartlocakcfg-20230520.0.log: "784"
  /h3coasis/local_volumes/h3c_logs/services/172.17.0.24-iotsmartlockns-20230520.0.log: "886"
  /h3coasis/local_volumes/h3c_logs/services/172.17.0.33-iotsmartlockns-20230520.0.log: "5061"
  /h3coasis/local_volumes/h3c_logs/services/172.17.0.33-iotsmartlockns-20230521.0.log: "8856"
  /h3coasis/local_volumes/h3c_logs/services/172.17.0.33-iotsmartlockns-20230522.0.log: "5535"
  /h3coasis/local_volumes/h3c_logs/services/iot230mgr.log: "10407"
  /h3coasis/local_volumes/h3c_logs/services/iotgateway.2023-05-20.0.log: "831"
  /h3coasis/local_volumes/h3c_logs/services/iotlora.2023-05-20-00.log: "2308"
  /h3coasis/local_volumes/h3c_logs/services/iotzigbeeserver.log: "206285"
  /h3coasis/local_volumes/h3c_logs/services/licsmgr2.2023-05-20.0.log: "102810"
  /h3coasis/local_volumes/h3c_logs/services/licsmgr2.2023-05-21.0.log: "93152"
  /h3coasis/local_volumes/h3c_logs/services/licsmgr2.log: "64029"
root@34c641d8b159:/#
```

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
1. I'm Sure the promtail has read logs from scrape_configed;
2. Sure the Communication  within promtail and loki is normal;
3. Not sure the promtail had send logs/labels to loki，how to fix this ? I had try an wron push api in promtail config，there has error logs ，but no any logs about push when with right push api’
4. Not sure the labels query is normal ,how to define it?
/loki/api/v1/labels ---> {"status":"success","data":["filename","job"]}
5. the version of loki and promtail  are the same 2.8.0, run in docker,  
6. the version of grafan is 6.4.4 , run with default namespace in kubernetes
```
[root@iotvm132 loki]# docker images | grep grafana
grafana/promtail                                       2.8.0               b062beaf992b        6 weeks ago         197MB
grafana/loki                                           2.8.0               6723a4d27412        6 weeks ago         65.5MB
hub.h3c.com:5000/iotprivate/grafana                    6.4.4               be90e387821a        3 years ago         274MB
hub.h3c.com:5000/iotprivate/grafana-tiny-tools         v1                  8c5f0fb345a6        5 years ago         26.1MB
[root@iotvm132 loki]# kubectl  get pods -A | grep grafana
default       grafana-core-57455c6b94-l4k2p              1/1     Running     1          47h
default       grafana-import-dashboards-5z6cj            0/1     Completed   0          47h
You have mail in /var/spool/mail/root
[root@iotvm132 loki]# docker ps | grep -E 'loki|promtail'
34c641d8b159        grafana/promtail:2.8.0                        "/usr/bin/promtail -…"   4 hours ago         Up 4 hours                                   promtail
fe96c59df253        grafana/loki:2.8.0                            "/usr/bin/loki -conf…"   45 hours ago        Up 45 hours         0.0.0.0:3100->3100/tcp   loki
[root@iotvm132 loki]#
```

**Comment by JunejaTung** [comment]
@JStickler Hi，any progress?

**Comment by JStickler** [comment]
@JunejaTung I'm a technical writer, I won't be working on this bug as I write documentation, not code.

**Comment by chaeyan** [comment]
Same issue

**Comment by Koraxtu** [comment]
same issue

**Comment by limacharlie2me** [comment]
same issue

**Comment by Pexers** [comment]
+1
Getting this error when trying to use `auth_enabled: true` together with `X-Scope-OrgID` and basic-auth. 

Using the below configuration in Grafana:
```
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100/
    jsonData:
      maxLines: 1000
      httpHeaderName1: X-Scope-OrgID
    basicAuth: true
    basicAuthUser: ${LOKI_USERNAME}
    secureJsonData:
      basicAuthPassword: ${LOKI_PASSWORD}
      httpHeaderValue1: foo
```
