### ISSUE TITLE
Long query time after bulk load

### ISSUE THREAD

**Issue by mfredenhagen** [grafana/loki#9530]
**Describe the bug**
We use loki-stack deployed on a single node cluster to analyze customer log files. Because we don't have access to the customer loki instance, we export all customer logs for a specific time range (last five days) via `/loki/api/v1/query_range` into a file that we transfer and then ingest into our loki instance via `/loki/api/v1/push`. This works so far, but we recognized that there is a long waiting period (~270 seconds) if the ingested file only contains a few entries (~2000) compared to less than 30 seconds for a bigger file with more than 2000000 entries, for example, before we can start analyzing (using Grafana Dashboard or logcli).
The times vary, but the magnitude is the same between invocations.

**To Reproduce**
1. Started Loki (docker.io/grafana/loki@sha256:1ee60f980950b00e505bd564b40f720132a0653b110e993043bb5940673d060a)
via helm installation of loki-stack 2.9.10 with these values:
```
    loki:
      config:
        server:
          log_level: warn
        limits_config:
          reject_old_samples: false
          max_query_length: 0
          ingestion_burst_size_mb: 512
          ingestion_rate_mb: 128
      readinessProbe:
        httpGet:
          path: /ready
          port: http-metrics
        initialDelaySeconds: 10
      livenessProbe:
        httpGet:
          path: /ready
          port: http-metrics
```
3. Started Promtail (SHA or version) to tail '...' - not relevant in this scenario
4. Query: `{bundle="<customer specific filename>"}` - bundle label is append during import to distinguish logs from different customers and support cases, push API is called in batches of 256 log lines at most

**Expected behavior**
The expectation is that a query doesn't take longer for a small data set than a more extensive set of log entries.

**Environment:**
 - Infrastructure: K3D, laptop Apple M1 Max, 64 GB memory; 8 CPU's and 24 GB for docker
 - Deployment tool: helm via K3S autodeploy

**Screenshots, Promtail config, or terminal output**
see attached log files
[loki-faster-query.log.zip](https://github.com/grafana/loki/files/11572939/loki-faster-query.log.zip)
[loki-slow-query.log.zip](https://github.com/grafana/loki/files/11572940/loki-slow-query.log.zip)
