### ISSUE TITLE
Loki Querier Pods throw errors connecting to Compactor over TLS

### ISSUE THREAD

**Issue by diranged** [grafana/loki#9539]
**Describe the bug**
When running Loki in TLS mode (on HTTP), the `loki-querier` pods cannot reach the `loki-compactor` pod via `https://loki-compactor:3100`. They throw an error:

```
level=error ts=2023-05-26T16:23:28.090871721Z caller=http.go:97 msg="error getting delete requests from the store" err="Get \"https://loki-compactor:3100/loki/api/v1/delete\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
```

**To Reproduce**
1. Started Loki: 2.8.2
2. Loki Config

```yaml
# config.yaml
  config.yaml: |
    analytics:
      reporting_enabled: false
    auth_enabled: false
    common:
      compactor_address: https://loki-compactor:3100
      replication_factor: 3
    compactor:
      retention_enabled: true
      shared_store: s3
    distributor:
      ring:
        heartbeat_timeout: 15s
        kvstore:
          store: memberlist
    frontend:
      compress_responses: true
      grpc_client_config:
        tls_ca_path: /tls/ca.crt
        tls_cert_path: /tls/tls.crt
        tls_enabled: true
        tls_key_path: /tls/tls.key
        tls_server_name: 'loki-query-frontend'
      log_queries_longer_than: 15s
      tail_tls_config:
        tls_ca_path: /tls/ca.crt
        tls_cert_path: /tls/tls.crt
        tls_key_path: /tls/tls.key
    frontend_worker:
      frontend_address: 'loki-query-frontend:9095'
      grpc_client_config:
        grpc_compression: gzip
        max_send_msg_size: 134217728
        tls_ca_path: /tls/ca.crt
        tls_cert_path: /tls/tls.crt
        tls_enabled: true
        tls_key_path: /tls/tls.key
        tls_server_name: 'loki-query-frontend'
    ingester:
      autoforget_unhealthy: true
      chunk_idle_period: 2h
      chunk_target_size: 1536000
      flush_op_timeout: 600s
      lifecycler:
        join_after: 5s
        ring:
          heartbeat_timeout: 15s
          kvstore:
            store: memberlist
      max_chunk_age: 1h
      max_transfer_retries: 0
      query_store_max_look_back_period: 0
      wal:
        enabled: false
    ingester_client:
      grpc_client_config:
        tls_ca_path: /tls/ca.crt
        tls_cert_path: /tls/tls.crt
        tls_enabled: true
        tls_key_path: /tls/tls.key
        tls_server_name: 'loki-ingester'
    limits_config:
      ingestion_burst_size_mb: 80
      ingestion_rate_mb: 50
      ingestion_rate_strategy: local
      max_cache_freshness_per_query: 10m
      max_concurrent_tail_requests: 50
      max_entries_limit_per_query: 10000
      max_global_streams_per_user: 0
      max_label_name_length: 128
      max_label_value_length: 1024
      max_line_size: 256kb
      max_line_size_truncate: true
      max_streams_per_user: 0
      per_stream_rate_limit: 20M
      per_stream_rate_limit_burst: 40M
      query_timeout: 30m
      reject_old_samples: true
      reject_old_samples_max_age: 1h
      retention_period: 720h
      split_queries_by_interval: 15m
    memberlist:
      join_members:
      - dnssrv+_tcp._tcp.loki-memberlist.observability.svc.cluster.local.
      left_ingesters_timeout: 30s
    querier:
      engine:
        timeout: 5m
      multi_tenant_queries_enabled: true
      query_ingesters_within: 45m
    query_range:
      align_queries_with_step: true
      cache_results: false
      max_retries: 5
      parallelise_shardable_queries: true
    runtime_config:
      file: /var/loki-runtime/runtime.yaml
    schema_config:
      configs:
      - from: "2021-01-20"
        index:
          period: 24h
          prefix: index_
        object_store: s3
        schema: v11
        store: boltdb-shipper
    server:
      grpc_server_max_recv_msg_size: 134217728
      grpc_tls_config:
        cert_file: /tls/tls.crt
        client_auth_type: RequireAndVerifyClientCert
        client_ca_file: /tls/ca.crt
        key_file: /tls/tls.key
      http_listen_port: 3100
      http_server_idle_timeout: 1800s
      http_server_read_timeout: 1800s
      http_server_write_timeout: 1800s
      http_tls_config:
        cert_file: /tls/tls.crt
        client_auth_type: VerifyClientCertIfGiven
        client_ca_file: /tls/ca.crt
        key_file: /tls/tls.key
      log_level: debug
    storage_config:
      aws:
        s3: s3://us-west-2/XXX
        s3forcepathstyle: true
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/boltdb-cache
        cache_ttl: 24h
        index_gateway_client:
          grpc_client_config:
            tls_ca_path: /tls/ca.crt
            tls_cert_path: /tls/tls.crt
            tls_enabled: true
            tls_key_path: /tls/tls.key
            tls_server_name: 'loki-index-gateway'
          server_address: dns:///loki-index-gateway:9095
        resync_interval: 5m
        shared_store: s3
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
```

**Expected behavior**
It seems to me that what we're really missing here is a "client tls" configuration block for the loki components that helps it understand how to make TLS queries to the other pods on the `3100` port. Alternatively, the `loki-distributed` helm chart should expose the GRPC endpoint for the compactor like the rest of the services.
