### ISSUE TITLE
logs missing in index

### ISSUE THREAD

**Issue by Morriz** [grafana/loki#954]
**Describe the bug**
Grafana querying loki shows no logs found for most parts of the day. Sometimes a block of some hours shows up from the last day.
We have been running for 7 days, but no logs show up for the first 6 days for a lot of label combinations. Some do however. But most apps seem to have their logs disappeared since a couple of hours ago. It's hard to infer any logic behind this behaviour.

I created another issue which might be related: #953  

**To Reproduce**
1. Started loki (SHA or version)
0.3.0
2. Started promtail (SHA or version) to tail '...' 
0.8.1
3. Query: `{} term`
any

**Expected behavior**
I expect all the logs to be indexed and queryable

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm

We run a 2 node statefulset. Our PVCs are hardly used.
We use the following helm values:
```
config:
  auth_enabled: false
  ingester:
    chunk_idle_period: 15m
    chunk_block_size: 262144
    lifecycler:
      ring:
        kvstore:
          store: inmemory
        replication_factor: 1

  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
  schema_config:
    configs:
    - from: "2018-04-15"
      store: boltdb
      object_store: aws
      schema: v9
      index:
        prefix: index_
        period: 168h
  storage_config:
    boltdb:
      directory: /data/loki/index
    filesystem:
      directory: /data/loki/chunks
    aws: 
      s3: s3://eu-central-1/logs.***
  chunk_store_config:
    max_look_back_period: 0
  table_manager:
    retention_deletes_enabled: true
    retention_period: 2160h
```
One error is found during last day output from loki:
```
2019-08-30 14:37:11	
level=error ts=2019-08-30T12:37:11.840780429Z caller=tail.go:208 Errorreceivingresponsefromgprctailclient="rpc error: code = Canceled desc = context canceled"
2019-08-30 14:37:11	
level=error ts=2019-08-30T12:37:11.84065633Z caller=http.go:270 Errorwritingclosemessagetowebsocket="write tcp 100.96.6.201:3100->100.96.6.230:49112: write: broken pipe"
2019-08-30 14:37:11	
level=error ts=2019-08-30T12:37:11.840592211Z caller=http.go:268 Errorwritingpingmessagetowebsocket="write tcp 100.96.6.201:3100->100.96.6.230:49112: write: broken pipe"
```
the rest of the logs is just of level info like this:
```
level=info ts=2019-08-30T02:33:58.91425169Z caller=table_manager.go:349 msg="creating table" table=index_2581
level=info ts=2019-08-30T02:33:58.914263413Z caller=table_manager.go:349 msg="creating table" table=index_2582
level=info ts=2019-08-30T02:33:58.914270669Z caller=table_manager.go:349 msg="creating table" table=index_2584
level=info ts=2019-08-30T02:33:58.914277841Z caller=table_manager.go:349 msg="creating table" table=index_2587
level=info ts=2019-08-30T02:35:58.914065825Z caller=table_manager.go:206 msg="synching tables" num_expected_tables=13 expected_tables=13
```
