### ISSUE TITLE
no template "loki/templates/configmap.yaml" associated with template "gotpl"

### ISSUE THREAD

**Issue by tijmenvandenbrink** [grafana/loki#9545]
Hi,

I'm getting the following error when trying to deploy the latest helm chart (5.5.10):

```
  Warning  error  78s (x2 over 10h)  helm-controller  Helm install failed: template: loki/templates/single-binary/statefulset.yaml:42:28: executing "loki/templates/single-binary/statefulset.yaml" at <include (print .Template.BasePath "/configmap.yaml") .>: error calling include: template: no template "loki/templates/configmap.yaml" associated with template "gotpl"
```
Could it be that the following reference is wrong and should be pointing to `/config.yaml`?:

https://github.com/grafana/loki/blob/d1fd6b78832e2c4dff1e0adf7bcf1b884ca7c251/production/helm/loki/templates/single-binary/statefulset.yaml#LL42C65-L42C74

These are the relevant settings I set in my config:

```yaml
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
    singleBinary:
      replicas: 1
```

**Comment by tijmenvandenbrink** [comment]
These are the relevant settings I set:

```yaml
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
    singleBinary:
      replicas: 1
```
