### ISSUE TITLE
[logcli] logcli should use Read-Only mode when it works with TSDB index

### ISSUE THREAD

**Issue by vlad-diachenko** [grafana/loki#9555]
**Describe the bug**
When we run the query against the bucket with loki data(indexes and chunks), logcli tries to use index-gateway and initialize table-manager. However, when it works with boltdb-shipper, it works with indexes in Read-Only mode. 

**To Reproduce**
1. enable debug logs in logcli, adding 
    ```go
    var logLevel logging.Level
    _ = logLevel.Set("debug")
    util_log.InitLogger(&server.Config{LogLevel: logLevel}, prometheus.DefaultRegisterer, true, false)
    ```
1. create storage config that will be used to access the bucket: 
Example for AWS S3:
   ```yaml
    storage_config:
      tsdb_shipper:
        shared_store: aws
        cache_location: /tmp/logs-cache/
      boltdb_shipper:
        shared_store: aws
        cache_location: /tmp/logs-cache/
      aws:
        access_key_id: {{REPLACE WITH AWS ACCESS KEY ID}}
        secret_access_key: {{REPLACE WITH AWS SECRET ACCESS KEY}}
        bucketnames: {{REPLACE WITH YOUR BUCKET NAME}}
        region: {{REPLACE WITH YOUR AWS REGION}}

    limits_config:
      query_timeout: 2h
    ``` 
1. run logcli with params 
```shell
logcli query \
--remote-schema \
--store-config=./logcli-aws-config.yaml \
--from="2023-05-08T18:00:00Z" \
--to="2023-05-08T19:14:00Z" \
'{environment=~".+"}' \
--org-id=YOUR_TENANT_ID \
--timezone=UTC
```

**Actual behavior**
You can find the log lines like: `msg="syncing files for table loki_tsdb_index_19482"` and `index-store=tsdb-2023-01-11 msg="starting index shipper in RW mode"` . 

**Expected behavior**
Logcli should operate in Read-Only mode when it works with TSDB index files and Index-gateway client must be disabled. It should work as with boltd-shipper indexes. 
https://github.com/grafana/loki/blob/d1fd6b78832e2c4dff1e0adf7bcf1b884ca7c251/pkg/logcli/query/query.go#L461-L462 

**Environment:**
 - Infrastructure: laptop
