### ISSUE TITLE
How to make Pipeline configuration effective?

### ISSUE THREAD

**Issue by lipaysamart** [grafana/loki#9572]
**I have the following log that needs to be processed:**
```test
May 30 23:17:59 ZH5-office %%01SNMPMAC/4/LOG(l)[81672]: #015#012 Fail to synchronise the ARP table from the target host through SNMP. The IP address of the target host is [192.168.147.2]
```
**This is my Pipeline configuration:**
```yaml
- job_name: syslog
  pipeline_stages:
  - match:
      selector: '{job="usglogs"}'
      stages:
      - regex:
          expression: '^(?P<TimeStamp>\S+\s\d{2}\s\d{2}:\d{2}:\d{2})\s(?P<Hostname>\S+)\s(?P<Flags>\S+)\/(?P<Level>\d+)\/(?P<Brief>\S+)\s(?P<Description>.*)'
      - labels:
          Hostname:
  static_configs:
  - targets:
      - localhost
    labels:
      job: usglogs
      __path__: /var/syslog/*log
```
**On the Grafana page, the log is not being processed:**
```test
May 30 23:17:59 ZH5-office %%01SNMPMAC/4/LOG(l)[81672]: #015#012 Fail to synchronise the ARP table from the target host through SNMP. The IP address of the target host is [192.168.147.2]
```
**The expected processing result should be like this.**
![image](https://github.com/grafana/loki/assets/96456128/8ce3aeab-782c-4e52-8c7f-c16050c17b9d)

**Version information:**

* promtail 2.8
* Loki 2.8
* Grafana latest

**How can I modify the Pipeline stages to make it effective and process this log?**
