### ISSUE TITLE
Server section of promtail documentation is incomplete

### ISSUE THREAD

**Issue by a-a-abramov** [grafana/loki#9583]
**Describe the bug**
Some fields are absent from `server` section of Promtail's configuration. For instance `http_tls_config` – it's possible to run Promtail's `loki_push_api` behind TLS, but this part of documentation is missing. 

We're pretty sure it's documentation issue only, because (1.) both [Loki](https://github.com/grafana/loki/blob/main/pkg/server/internal_server.go#L7) and [Promtail](https://github.com/grafana/loki/blob/main/clients/pkg/promtail/server/server.go#L24) use the same [web server](https://github.com/weaveworks/common/tree/master/server) package from Weaveworks and (2.) this Promtail config actually works as expected – :3100 is accessible via https only:

```
server:
  http_listen_port: 3200

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
- url: https://example.com:3100/loki/api/v1/push
  tenant_id: tenant1
  external_labels:
    dc: dc1
    host: example.dc1.com

scrape_configs:
- job_name: loki_push_api
  loki_push_api:
    server:
      http_listen_port: 3100
      http_tls_config:
        cert_file: /etc/ssl/certs/some.crt
        key_file: /etc/ssl/private/some.key
    use_incoming_timestamp: true
  pipeline_stages:
    ...
```

**To Reproduce**
Nothing besides documentation is broken.

**Expected behavior**
Documentation [page](https://grafana.com/docs/loki/latest/clients/promtail/configuration/#server) clearly states that it's possible to run `loki_push_api` behind TLS.

**Environment:**
-

**Screenshots, Promtail config, or terminal output**
-
