### ISSUE TITLE
newbie s3 question

### ISSUE THREAD

**Issue by spedro** [grafana/loki#9587]
Dear all I am trying to configure a minimal loki stack in "Microservices mode". 

My only requirement to get started is that all persistent data are saved to an s3 bucket.

So I'm trying with this values.yaml:

```
ingester:
  max_transfer_retries: 0 
  chunk_idle_period: 1h
  chunk_target_size: 1536000
  max_chunk_age: 1h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 5m
    shared_store: s3
  aws:
    s3: s3://x:y@eu-central-1
    bucketnames: bucket-test

schema_config:
  configs:
    - from: 2020-07-01
      store: boltdb-shipper
      object_store: aws
      schema: v11
      index:
        prefix: index_
        period: 5m
```

And I install it in this way:

```
helm upgrade --install loki grafana/loki-stack -n loki -f values.yaml --set grafana.enabled=true
```

I can see all the logs I need in grafana, but after 1 hour I still do not see any data  saved to my s3 bucket.

Please can someone help me understand what is missing or what is wrong in my configuration ?

Thx a lot

P.
