### ISSUE TITLE
Missing config validation for runtime_config can cause high CPU load  in container when wrong Go duration is set

### ISSUE THREAD

**Issue by Xuxe** [grafana/loki#9619]
**Describe the bug**
After enabling the runtime_config with a "invalid"  period setting i discovered high CPU load on Loki running in a Docker container provisioned by Nomad. 
Due to doing a upgrade to 2.8.2 at the same time i have not related it with a invalid configuration because there was no validation error. 

**To Reproduce**
Setup a Loki instance, in Docker/Nomad.
Configure the runtime_config similar to this:
````
runtime_config:
  file: "/etc/loki.d/runtime.yaml"
  period: 60

````
You should discover high CPU load because Loki is trying to poll the runtime config every 60 ns. 
The correct setting would be a Go duration like "60s". Setting it to 60 does not cause the config validation to fail. 
it is probably related to a combination of Docker/Nomad and EPOLL_CTL.
The container is running with User ID / Group 2001, so not as root.  I can't reproduce it on my local machine with Debian 12/Podman sadly...

**Expected behavior**
Either Loki switches back to the default if it discovers a "invalid" config or should error out. 

**Environment:**
 - Infrastructure:  Docker + Nomad
 - Deployment tool: Nomad (v 1.5.2)
 - Docker Info:
```
root@monitoring:~# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 37
  Running: 22
  Paused: 0
  Stopped: 15
 Images: 23
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 78f51771157abb6c9ed224c22013cdf09962315d
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-20-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.839GiB
 Name: monitoring
 ID: EB7Y:R3YN:ZBJJ:NEHU:PRXC:D5HW:4WLY:7PH3:YCQY:GQPC:33I7:CEP3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Screenshots, Promtail config, or terminal output**
Strace should reveal a lot of lines like this:
`epoll_ctl(4, EPOLL_CTL_ADD, 13, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=[1643402280](tel:1643402280), u64=139772764116008}}) = -1 EPERM (Operation not permitted)`

CPU Usage of the Loki VM after deploying the valid config:
![image](https://github.com/grafana/loki/assets/6413398/b6a5d382-71b6-4f88-9be2-867efd1c560c)

```
auth_enabled: false

runtime_config:
  file: "/etc/loki.d/runtime.yaml"
  period: 60

limits_config:
  ingestion_rate_mb: 8
  ingestion_burst_size_mb: 16
  retention_period: 168h # Default retention of 7d
  retention_stream:
    - selector: '{environment="production"}'
      priority: 1
      period: 336h # 14d
    - selector: '{environment="dev|test"}'
      priority: 1
      period: 168h # 7d

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  grpc_server_max_recv_msg_size: 8388608
  log_level: ${LOG_LEVEL:-info}

common:
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  path_prefix: /var/lib/loki
  storage:
    filesystem:
      chunks_directory: /var/lib/loki/chunks
      rules_directory: /var/lib/loki/ruler/rules

storage_config:
  boltdb_shipper:
    active_index_directory: /var/lib/loki/index
    shared_store: filesystem
    cache_location: /var/lib/loki/boltdb-cache
    cache_ttl: 24h

compactor:
  working_directory: /var/lib/loki/compactor
  shared_store: filesystem
  retention_enabled: true
  retention_delete_delay: 1h
  retention_delete_worker_count: 150
  delete_request_cancel_period: "5m"

ruler:
  poll_interval: 1m
  storage:
     type: local
     local:
       directory: /etc/loki.d/rules
  alertmanager_url: "http://127.0.0.1:9093"
  rule_path: "/var/lib/loki/ruler/rules"

ingester:
  chunk_idle_period: 1h
  chunk_target_size: 8388608
  wal:
    enabled: true
    dir: /var/lib/loki/wal
    flush_on_shutdown: true

schema_config:
  configs:
    - from: 2022-02-07
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
```
