### ISSUE TITLE
[logcli] unknown index file version 3

### ISSUE THREAD

**Issue by vlad-diachenko** [grafana/loki#9640]
**Describe the bug**
Logcli supports running the queries against the bucket with Loki data (index and chunk files).
However, Logcli can not open TSDB index files v3, it reports an error `Query failed: unknown index file version 3`

**To Reproduce**
1. update `logcli-aws-config.yaml`(attached bellow) with your AWS information 
1. adjust and run the command `logcli query --remote-schema --store-config=./logcli-aws-config.yaml --from=2023-05-23T10:00:00Z --to=2023-05-23T15:05:00Z '{YOUR_STREAM_SELECTOR}' --org-id={{YOUR_ORG_ID}} --timezone=UTC --stats`
    1. update `from` and `to` parameters to run the query against TSDB index file V3
    2. replace `{YOUR_STREAM_SELECTOR}` with your stream selector
    3. replace {{YOUR_ORG_ID}} with your OrgID
1. after some time `logcli` returns an error: `Query failed: unknown index file version 3` 

**Expected behavior**
The execution should complete without errors

**Environment:**
 - Infrastructure: laptop
 
 ```shell
❯ logcli --version
logcli, version 2.8.2 (branch: HEAD, revision: 9f809eda7)
  build user:       root@b7e9ca0bf6e0
  build date:       2023-05-03T11:13:57Z
  go version:       go1.20.4
  platform:         darwin/amd64
 ```

**Screenshots, Promtail config, or terminal output**

logcli-aws-config.yaml:
```yaml

storage_config:
  tsdb_shipper:
    shared_store: aws
    cache_location: /tmp/logs-logcli/
  boltdb_shipper:
    shared_store: aws
    cache_location: /tmp/logs-logcli/
  aws:
    access_key_id: {{YOUR_ACCESS_KEY_ID}}
    secret_access_key:  {{YOUR_ACCESS_KEY_ID}}
    bucketnames: {{YOUR_S3_BUCKET_NAME}}
    region:  {{YOUR_AWS_REGION}}

limits_config:
  query_timeout: 2h
```
