### ISSUE TITLE
Loki does not send traces

### ISSUE THREAD

**Issue by EugeneAikashev** [grafana/loki#9652]
**Describe the bug**
Loki does not send a traces.

I use helm chart  [loki-distributed](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed)  version `0.69.16` to run a Loki. And I want Loki to send traces to otel-collector.
Loki version `docker.io/grafana/loki:2.8.2`

Here are my custom `values.yaml` config:
```
distributor:
  enabled: true
  extraEnv:
   - name: JAEGER_AGENT_HOST
      value: otel-collector
    - name: JAEGER_AGENT_PORT
      value: "6831"
    - name: JAEGER_SAMPLER_TYPE
      value: const
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
ingester:
  enabled: true
  extraEnv:
   - name: JAEGER_AGENT_HOST
      value: otel-collector
    - name: JAEGER_AGENT_PORT
      value: "6831"
    - name: JAEGER_SAMPLER_TYPE
      value: const
    - name: JAEGER_SAMPLER_PARAM
      value: "1"compactor:
  enabled: true
  extraEnv:
   - name: JAEGER_AGENT_HOST
      value: otel-collector
    - name: JAEGER_AGENT_PORT
      value: "6831"
    - name: JAEGER_SAMPLER_TYPE
      value: const
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
querier:
  enabled: true
  extraEnv:
   - name: JAEGER_AGENT_HOST
      value: otel-collector
    - name: JAEGER_AGENT_PORT
      value: "6831"
    - name: JAEGER_SAMPLER_TYPE
      value: const
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
indexGateway:
  enabled: true
  extraEnv:
   - name: JAEGER_AGENT_HOST
      value: otel-collector
    - name: JAEGER_AGENT_PORT
      value: "6831"
    - name: JAEGER_SAMPLER_TYPE
      value: const
    - name: JAEGER_SAMPLER_PARAM
      value: "1" 
queryFrontend:
  enabled: true
  extraEnv:
   - name: JAEGER_AGENT_HOST
      value: otel-collector
    - name: JAEGER_AGENT_PORT
      value: "6831"
    - name: JAEGER_SAMPLER_TYPE
      value: const
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
```
The same config works perfectly with `grafana/tempo`, I see all `tempo` traces.

**To Reproduce**
1. Started distributed Loki (version 2.8.2)
2. Add env variabels - `JAEGER_AGENT_HOST, JAEGER_AGENT_PORT, JAEGER_SAMPLER_TYPE, JAEGER_SAMPLER_PARAM`

**Expected behavior**
Loki sends traces

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool:  helm chart  [loki-distributed](https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed)  version `0.69.16`

**Screenshots, Promtail config, or terminal output**
I see no relevant pod logs that tracing is enabled or something is wrong in my config.
