### ISSUE TITLE
Store logs in single s3 bucket

### ISSUE THREAD

**Issue by paramjeet01** [grafana/loki#9709]
**Describe the bug**

Loki is able to write on Powerscale s3 , but throw error as shown below

`caller=flush.go:144 org_id=fake msg="failed to flush" err="failed to flush chunks: store put chunk: AccessDenied: Bucket owner does not have a write permission for the bucket path.\n\tstatus code: 403, request id: 618632610

**To Reproduce**
1. Started Loki : version 2.8.2 
2. Started Promtail : version 2.5.0

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool:  helm

**Comment by chaudum** [comment]
The bucket names must follow the [S3 bucket naming requirements](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-s3-bucket-naming-requirements.html). They must not be paths. I'm pretty sure this causes the error.

**Comment by paramjeet01** [comment]
I have created separate buckets and it works. Looks like Loki doesn't accept "/" in the path and can't use a single bucket for all the environments. Other issue that I receive when grafana tries to fetch labels. Find my attached error and config

Error : 
`
ts=2023-06-21T05:32:08.197106833Z caller=spanlogger.go:85 user=fake level=info org_id=fake latency=fast query_type=labels length=1h0m0s duration=506.881µs status=500 label= query= splits=0 throughput=0B total_bytes=0B total_entries=0
level=error ts=2023-06-21T05:32:08.197602225Z caller=retry.go:73 org_id=fake msg="error processing request" try=2 query= err="rpc error: code = Code(500) desc = empty ring\n"
`
Config: 
```
auth_enabled: false
common:
  compactor_address: 'loki-backend'
  path_prefix: /var/loki
  replication_factor: 1
  ring:
    kvstore:
      store: memberlist
  storage:
    s3:
      access_key_id: myaccess_key_id
      bucketnames: loki-dev
      endpoint: https://powerscale.s3:9021
      http_config:
        insecure_skip_verify: true
      insecure: true
      s3forcepathstyle: true
      secret_access_key: mysecret_access_key
compactor:
  compaction_interval: 5m
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  retention_enabled: true
  shared_store: s3
  working_directory: /var/loki/compactor
frontend:
  scheduler_address: query-scheduler-discovery.shared-services.svc.cluster.local.:9095
frontend_worker:
  scheduler_address: query-scheduler-discovery.shared-services.svc.cluster.local.:9095
index_gateway:
  mode: ring
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
limits_config:
  enforce_metric_name: false
  max_cache_freshness_per_query: 10m
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  retention_period: 168h
  split_queries_by_interval: 15m
memberlist:
  join_members:
  - loki-memberlist
query_range:
  align_queries_with_step: true
ruler:
  storage:
    s3:
      access_key_id: myaccess_key_id
      bucketnames: loki-dev
      endpoint: https://powerscale.s3:9021
      insecure: true
      s3forcepathstyle: true
      secret_access_key: mysecret_access_key
    type: s3
runtime_config:
  file: /etc/loki/runtime-config/runtime-config.yaml
schema_config:
  configs:
  - from: "2023-06-18"
    index:
      period: 24h
      prefix: loki_index_
    object_store: s3
    schema: v12
    store: boltdb-shipper
server:
  grpc_listen_port: 9095
  http_listen_port: 3100
storage_config:
  boltdb_shipper:
    active_index_directory: /var/loki/index
    cache_location: /var/loki/index_cache
    resync_interval: 5s
    shared_store: s3
  hedging:
    at: 250ms
    max_per_second: 20
    up_to: 3
table_manager:
  retention_deletes_enabled: false
  retention_period: 0
```

**Comment by percy78** [comment]
@paramjeet01 Did you get any clarity with this coz we're encountering the same issue. However, not sure if ours is somewhat different but I cannot pinpoint where the issue is.

First of all my ingesters aren't working. They are not running:
```
loki-ingester-kjj-0                         0/1     Running   264 (2m15s ago)   24h
loki-ingester-sr3-0                         0/1     Running   264 (2m14s ago)   24h
loki-ingester-sr6-0                         0/1     Running   264 (2m25s ago)   24h
```

Checking the logs I see the same issue as you highlighted. 

`caller=flush.go:144 org_id=fake msg="failed to flush" err="failed to flush chunks: store put chunk: AccessDenied: Access Denied.\n\tstatus code: 403, request id`

When I then check in minio, I see this from traces and logs.

This is from one of the Logs:

**API: PutObject
Time: Invalid Date
DeploymentID: d0db3fa5-dd2c-4874-991f-227711cafd72
RequestID: 17955EC24C36D938
RemoteHost: 172.16.16.28
UserAgent: MinIO (linux; amd64) minio-go/v7.0.47
Error: At least one of the pre-conditions you specified did not hold (cmd.PreConditionFailed)**

**Backtrace: 
0: internal/logger/logger.go:258:logger.LogIf()
1: cmd/api-errors.go:2235:cmd.toAPIErrorCode()
2: cmd/api-errors.go:2260:cmd.toAPIError()
3: cmd/object-handlers.go:1870:cmd.objectAPIHandlers.PutObjectHandler()
4: net/http/server.go:2109:http.HandlerFunc.ServeHTTP()**

And the traces say: 


![image](https://github.com/grafana/loki/assets/28777690/25e02d80-f7a9-4bff-9832-bdcdc203d9bd)


On of the things I can see already is the Time: Invalid Date issue, however all our worker nodes are running chrony and synced to world watch so not sure about this one.

**Comment by paramjeet01** [comment]
@percy78 , There was an issue in the bucket configuration , s3forcepathstyle to false - worked for me I guess. Or the endpoint and bucket naming convention should be followed. Sorry , I really have bad memory.

**Comment by percy78** [comment]
> @percy78 , There was an issue in the bucket configuration , s3forcepathstyle to false - worked for me I guess. Or the endpoint and bucket naming convention should be followed. Sorry , I really have bad memory.

Ah so are you saying that you changed s3forcepathstyle to false from true and the issue seem to have disappeared? Appreciate if you don't remember all of it but this is a good test to start with. Will change that tomorrow for our DEV env first and check. Thanks for helping.

**Comment by Ibtihaj-Abdullah** [comment]
Any update on using custom prefixes??? I diabled forcepathstyle and it didnt work

**Comment by axtox** [comment]
I had the same issue, and actually the issue was that I was using paths in bucket names like: `bucket-id/folder/anotherfolder`

I was using TimeWeb Cloud S3 storage, and there is NO permission settings that you can configure, so that's why I started to search for another solution. I wasn't thinking that the issue is in the bucket name that consists of the folders, because Loki has successfully created some files and folder in my S3 in the provided bucket path! It is so confusing: only the file `loki_cluster_seed.json` and `index/delete_requests/delete_requests.gz` was *successfully* created but the indexes itself and logs were missing.

I've just deleted the folder path from my S3 configuration and it works just fine. So basically question it: why it is partly working when using bucket name with folder path and is there a way to specify a specific folder in the S3 bucket where the logs should be located?

Here's my S3 config section for Loki version 3.3.2 (I am using environment variables so had to also use -config.expand-env=true CLI flag):
```yaml
schema_config:
  configs:
  - from: 2024-04-23 
    store: tsdb
    object_store: s3
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
 tsdb_shipper:
   active_index_directory: /etc/loki/index
   cache_location: /etc/loki/cache
   cache_ttl: 24h
 aws:
   endpoint: ${LOKI_S3_ENDPOINT}
   bucketnames: ${LOKI_S3_BUCKET_NAME} #do not use paths here!! only the bucket name!
   access_key_id: ${LOKI_S3_ACCESS_KEY}
   secret_access_key: ${LOKI_S3_SECRET_ACCESS_KEY}
   region: ${LOKI_S3_REGION}
   s3forcepathstyle: true 
   insecure: false

compactor:
  working_directory: /etc/loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: aws
```
