### ISSUE TITLE
Starting from Docker: msg="error running loki" err="mkdir /loki/rules: permission denied

### ISSUE THREAD

**Issue by bvn13** [grafana/loki#9753]
Hi.

I have a problem which is not solvable to me. Please give me a hint.

```
Starting monitoring-loki ... done
Attaching to monitoring-loki
monitoring-loki | mkdir /loki/rules: permission denied
monitoring-loki | error initialising module: ruler-storage
monitoring-loki | github.com/grafana/dskit/modules.(*Manager).initModule
monitoring-loki |       /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:122
monitoring-loki | github.com/grafana/dskit/modules.(*Manager).InitModuleServices
monitoring-loki |       /src/loki/vendor/github.com/grafana/dskit/modules/modules.go:92
monitoring-loki | github.com/grafana/loki/pkg/loki.(*Loki).Run
monitoring-loki |       /src/loki/pkg/loki/loki.go:457
monitoring-loki | main.main
monitoring-loki |       /src/loki/cmd/loki/main.go:110
monitoring-loki | runtime.main
monitoring-loki |       /usr/local/go/src/runtime/proc.go:250
monitoring-loki | runtime.goexit
monitoring-loki |       /usr/local/go/src/runtime/asm_amd64.s:1598
monitoring-loki | level=warn ts=2023-06-20T20:28:22.162592247Z caller=loki.go:286 msg="per-tenant timeout not configured, using default engine timeout (\"5m0s\"). This behavior will change in the next major to always use the default per-tenant timeout (\"5m\")."
monitoring-loki | level=info ts=2023-06-20T20:28:22.164901456Z caller=main.go:108 msg="Starting Loki" version="(version=2.8.2, branch=HEAD, revision=9f809eda7)"
monitoring-loki | level=error ts=2023-06-20T20:28:22.166219404Z caller=log.go:171 msg="error running loki" err="mkdir /loki/rules: permission denied\nerror initialising module: ruler-storage\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:122\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/grafana/dskit/modules/modules.go:92\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:457\nmain.main\n\t/src/loki/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"
```

I have such exception on start of loki from Docker with this configuration:

```


loki:
--
  loki:
    image: grafana/loki:2.8.2
    container_name: monitoring-loki
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    networks:
      - logging
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - /usr/lib/monitoring/loki:/loki
```

I cannot figure it out...
