### ISSUE TITLE
Unable to fetch labels from Loki (no org id ), please check the server logs for more details

### ISSUE THREAD

**Issue by Surya-smart619** [grafana/loki#9756]
While testing Loki data source in grafana getting this error `Unable to fetch labels from Loki (no org id ), please check the server logs for more details`

I'm using helm to install both loki and grana. Here is the values file used to install.

**loki-values.yaml**
```
loki:
  storage:
    type: azure
    bucketNames:
      chunks: ${LOKI_CONTAINER_NAME}
      ruler: ${LOKI_CONTAINER_NAME}
      admin: ${LOKI_CONTAINER_NAME}
    azure:
      accountName: ${AZURE_STORAGE_ACCOUNT_NAME}
      accountKey: ${AZURE_STORAGE_ACCOUNT_KEY}
read:
  replicas: 2
  extraArgs:
    - "-config.expand-env=true"
  extraEnv:
    - name: AZURE_STORAGE_ACCOUNT_KEY
      valueFrom:
        secretKeyRef:
          name: loki-azure-storage-account
          key: storage-account-key
    - name: AZURE_STORAGE_ACCOUNT_NAME
      valueFrom:
        secretKeyRef:
          name: loki-azure-storage-account
          key: storage-account-name
    - name: LOKI_CONTAINER_NAME
      valueFrom:
        secretKeyRef:
          name: loki-azure-storage-account
          key: loki-container-name
write:
  replicas: 2
  extraArgs:
    - "-config.expand-env=true"
  extraEnv:
    - name: AZURE_STORAGE_ACCOUNT_KEY
      valueFrom:
        secretKeyRef:
          name: loki-azure-storage-account
          key: storage-account-key
    - name: AZURE_STORAGE_ACCOUNT_NAME
      valueFrom:
        secretKeyRef:
          name: loki-azure-storage-account
          key: storage-account-name
    - name: LOKI_CONTAINER_NAME
      valueFrom:
        secretKeyRef:
          name: loki-azure-storage-account
          key: loki-container-name
backend:
  replicas: 2
  extraArgs:
    - "-config.expand-env=true"
  extraEnv:
    - name: AZURE_STORAGE_ACCOUNT_KEY
      valueFrom:
        secretKeyRef:
          name: loki-azure-storage-account
          key: storage-account-key
    - name: AZURE_STORAGE_ACCOUNT_NAME
      valueFrom:
        secretKeyRef:
          name: loki-azure-storage-account
          key: storage-account-name
    - name: LOKI_CONTAINER_NAME
      valueFrom:
        secretKeyRef:
          name: loki-azure-storage-account
          key: loki-container-name
```

***grafana-value.yaml**
```
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
      - name: Thanos
        type: prometheus
        uid: thanos
        url: http://thanos-query.monitoring:9090
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki-gateway.loki
        jsonData:
          maxLine: 1000
          httpHeaderName1: "X-Scope-OrgID"
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: "traceID=(\\w+)"
              name: TraceID
              url: "$${__value.raw}"
          secureJsonData:
            httpHeaderValue1: "self-monitoring"
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo-query-frontend.monitoring:3100
        jsonData:
          httpMethod: GET
          tracesToLogs:
            datasourceUid: loki
            mapTagNamesEnabled: false
            spanStartTimeShift: '1h'
            spanEndTimeShift: '1h'
            filterByTraceID: false
            filterBySpanID: false
          lokiSearch:
            datasourceUid: loki
          serviceMap:
            datasourceUid: prometheus
          search:
            hide: false
          nodeGraph:
            enabled: true
```
I provide datasource value for grafana. I hope this information is enough to reproduce.
Am I missing something in the configuration?

**Comment by Surya-smart619** [comment]
Any Update on this?

**Comment by willzhang** [comment]
same here
loki v2.8.2
```
helm upgrade -i loki grafana/loki -n loki --create-namespace \
  --set write.replicas=1 --set read.replicas=1 --set backend.replicas=1
```
grafana v9.5.5
```
helm install loki-grafana grafana/grafana -n loki
```

add datasource in grafana

![image](https://github.com/grafana/loki/assets/33590311/df6e3f88-49f1-44a9-b3a4-9d2440da1d20)

![image](https://github.com/grafana/loki/assets/33590311/4e218feb-1803-4e31-80a0-db86b8fbf94f)

**Comment by abalage** [comment]
Checking Grafana logs showed explicit HTTP 401, thus the request was unauthorized.
The helm chart enables authentication by default, however that needs additional setup, see https://grafana.com/docs/loki/latest/operations/authentication/

Disabling authentication support in values.yaml (with the acknowledged consequences) makes it work.
```yaml
loki:
  # Auth requires a revers proxy providing basic auth
  # https://grafana.com/docs/loki/latest/operations/authentication/
  auth_enabled: false
```
