### ISSUE TITLE
series-API returns no info even though query-range-API returns log-lines

### ISSUE THREAD

**Issue by gabor** [grafana/loki#9771]
**Describe the bug**
the `/api/v1/series` API returns no info for a given time-range, but a `/api/v1/query_range` returns log-lines for the same time range.

**To Reproduce**
it's hard to reproduce. in my case i'm running loki:2.8.2 docker image, with the following config-file:
```yaml
auth_enabled: false

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h


analytics:
  reporting_enabled: false
```

i am sending some fake data to it, with a script similar to https://github.com/grafana/grafana/blob/main/devenv/docker/blocks/loki/data/data.js
it has been running for roughly two hours, and now:

a range query returns log-rows:
```
curl 'http://localhost:3100/loki/api/v1/query_range'\
  --data-urlencode 'start=1687436113898000000'\
  --data-urlencode 'end=1687436838855000000'\
   --data-urlencode 'limit=3' --data-urlencode 'query={place="luna"}'
```
(i get 3 log lines from this one, the log lines have more labels than "place").

the series query does not return anything:
```
curl 'http://localhost:3100/loki/api/v1/series'\
  --data-urlencode 'start=1687436113898000000'\
  --data-urlencode 'end=1687436838855000000'\
  --data-urlencode 'match[]={place="luna"}'
```

returns:
```
"status":"success","data":[]}
```

(if i run the series-query closer to "NOW", it does return the correct data)

**Expected behavior**

series-API should return data when query-range-api returns data.

**Environment:**
running docker image on arm mac computer.
