### ISSUE TITLE
loki does not create any index on k8ssadnra database while table manager is enabled

### ISSUE THREAD

**Issue by ehsanrocket** [grafana/loki#9785]
I have setup k8ssadnra cluster with k8ssandra/k8ssandra-operator
and loki with helm chart grafana/loki
I have also enabled the table manager 
this is my schema and storage Config
```
  schemaConfig:
    configs:
    - from: 2022-04-01
      store: cassandra 
      object_store: cassandra
      schema: v12
      index:
        prefix: loki_index
        period: 720h
      chunks:
        prefix: loki_chunk
        period: 720h
        
  storageConfig:
    cassandra:
      username: aaaa
      password: bbbb
      addresses: k8ssandra-dc1-service.k8ssandra-operator.svc.cluster.local
      auth: true
      keyspace: loki
      timeout: 10s
      connect_timeout: 10s
    filesystem:
      directory: /var/loki/chunks

```
it creates 4 tables 
```
SELECT table_name FROM system_schema.tables WHERE keyspace_name = 'loki';

 table_name
---------------
loki_chunk650
loki_chunk651
loki_index650
loki_index651
```
but there is no index_name in system_schema.indexes
```
SELECT index_name FROM system_schema.indexes WHERE keyspace_name = 'loki';

 index_name
------------

(0 rows)

```
**K8ssandra version : 4.0.9
loki version: 2.8.2**
