### ISSUE TITLE
Error: "at least one bucket name must be specified"

### ISSUE THREAD

**Issue by mac133k** [grafana/loki#9824]
**Describe the bug**
After adding named_store_configs block to the storage config Loki failed to start with the following error message:
```
level=error ts=2023-06-28T13:51:12.95861224Z caller=log.go:171 msg="error running loki" err="at least one bucket name must be specified\ngithub.com/grafana/loki/pkg/storage/chunk/client/aws.buckets\n\t/drone/src/pkg/storage/chunk/client/aws/s3_storage_client.go:332\ngithub.com/grafana/loki/pkg/storage/chunk/client/aws.NewS3ObjectClient\n\t/drone/src/pkg/storage/chunk/client/aws/s3_storage_client.go:152\ngithub.com/grafana/loki/pkg/storage.NewObjectClient\n\t/drone/src/pkg/storage/factory.go:483\ngithub.com/grafana/loki/pkg/storage.NewIndexClient\n\t/drone/src/pkg/storage/factory.go:294\ngithub.com/grafana/loki/pkg/storage.(*store).storeForPeriod\n\t/drone/src/pkg/storage/store.go:268\ngithub.com/grafana/loki/pkg/storage.(*store).init\n\t/drone/src/pkg/storage/store.go:164\ngithub.com/grafana/loki/pkg/storage.NewStore\n\t/drone/src/pkg/storage/store.go:147\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/drone/src/pkg/loki/modules.go:655\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/drone/src/vendor/github.com/grafana/dskit/modules/modules.go:120\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/drone/src/vendor/github.com/grafana/dskit/modules/modules.go:92\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/drone/src/pkg/loki/loki.go:457\nmain.main\n\t/drone/src/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\nerror creating index client\ngithub.com/grafana/loki/pkg/storage.(*store).storeForPeriod\n\t/drone/src/pkg/storage/store.go:270\ngithub.com/grafana/loki/pkg/storage.(*store).init\n\t/drone/src/pkg/storage/store.go:164\ngithub.com/grafana/loki/pkg/storage.NewStore\n\t/drone/src/pkg/storage/store.go:147\ngithub.com/grafana/loki/pkg/loki.(*Loki).initStore\n\t/drone/src/pkg/loki/modules.go:655\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/drone/src/vendor/github.com/grafana/dskit/modules/modules.go:120\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/drone/src/vendor/github.com/grafana/dskit/modules/modules.go:92\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/drone/src/pkg/loki/loki.go:457\nmain.main\n\t/drone/src/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\nerror initialising module: store\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/drone/src/vendor/github.com/grafana/dskit/modules/modules.go:122\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/drone/src/vendor/github.com/grafana/dskit/modules/modules.go:92\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/drone/src/pkg/loki/loki.go:457\nmain.main\n\t/drone/src/cmd/loki/main.go:110\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"
```
This error was gone and Loki was able to start after ```shared_store: s3``` was commented out from BoltDB-Shipper and TSDB-Shipper config blocks.

**To Reproduce**
1. Add named_store block to the config.
2. Restart Loki to see it failing.
3. Comment out the shared_store line from storage congs.
4. Restart Loki without a problem

**Expected behavior**
I am not sure why commenting out  ```shared_store: s3``` helped, but from Loki code it seems like the ```bucketnames: ``` line was ignored for some reason after introducing named stores. I am also not sure whether removing shared store line from TSDB and BoltDB-Shipper configs has any side effects, but the cluster seems to be working as usual for 2 days since the config change.

**Environment:**
 - Infrastructure: Microservice mode running Linux VMs with Ceph as S3 storage.

**Configuration**
Storage config before the change:
```
common:
  storage: 
    s3:
      access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
      bucketnames: loki-logs
      endpoint: ceph.devmain.net:9000
      http_config:
        idle_conn_timeout: 10m
      s3forcepathstyle: true
      secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
storage_config:
  boltdb_shipper:
    active_index_directory: /data1/loki/boltdb
    cache_location: /data1/loki/boltdb-cache
    cache_ttl: 24h
    index_gateway_client:
      grpc_client_config:
        tls_ca_path: /etc/loki/ca.crt
        tls_cert_path: /etc/loki/client.crt
        tls_enabled: true
        tls_key_path: /etc/loki/client.key
      log_gateway_requests: true
      server_address: igw1-loki.devdomain.net:9095
    query_ready_num_days: 1
    shared_store: s3
  tsdb_shipper:
    active_index_directory: /data1/loki/tsdb-index
    cache_location: /data1/loki/tsdb-cache
    cache_ttl: 24h
    index_gateway_client:
      grpc_client_config:
        tls_ca_path: /etc/loki/ca.crt
        tls_cert_path: /etc/loki/client.crt
        tls_enabled: true
        tls_key_path: /etc/loki/client.key
      log_gateway_requests: true
      server_address: igw2-loki.devdomain.net:9095
    query_ready_num_days: 1
    shared_store: s3
````
Storage config after the change:
```
storage_config:
  boltdb_shipper:
    active_index_directory: /data1/loki/boltdb
    cache_location: /data1/loki/boltdb-cache
    cache_ttl: 24h
    index_gateway_client:
      grpc_client_config:
        tls_ca_path: /etc/loki/ca.crt
        tls_cert_path: /etc/loki/client.crt
        tls_enabled: true
        tls_key_path: /etc/loki/client.key
      log_gateway_requests: true
      server_address: igw3-loki.devdomain.net:9095
    query_ready_num_days: 1
  tsdb_shipper:
    active_index_directory: /data1/loki/tsdb-index
    cache_location: /data1/loki/tsdb-cache
    cache_ttl: 24h
    index_gateway_client:
      grpc_client_config:
        tls_ca_path: /etc/loki/ca.crt
        tls_cert_path: /etc/loki/client.crt
        tls_enabled: true
        tls_key_path: /etc/loki/client.key
      log_gateway_requests: true
      server_address: igw2-loki.devdomain.net:9095
    query_ready_num_days: 1
  named_stores:
    aws:
      cceph-20220101:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs-atdev1
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
      cceph-20230511:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs-atdev1
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
      cceph-20230608:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs-atdev1
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
schema_config:
  configs:
  - chunks:
      prefix: chunk_
    from: '2022-01-01'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20220101
    schema: v11
    store: boltdb-shipper
  - chunks:
      prefix: chunk_
    from: '2023-05-11'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20230511
    row_shards: 64
    schema: v12
    store: boltdb-shipper
  - chunks:
      prefix: chunk_
    from: '2023-06-08'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20230608
    schema: v12
    store: tsdb
```
