### ISSUE TITLE
Loki write pods not scaling down

### ISSUE THREAD

**Issue by imanAzi** [grafana/loki#9825]
**Describe the bug**
Loki write pods not scaling down after scale up action succeeded. 
**To Reproduce**
1. Configured Loki in simple scalable mode and S3 as backend storage. Minimum 4 write pods and this can be scaled up to 6 write pods.
2. Start write load test with K6
3. Verify loki write autoscaling to 6
4. Cancel load test
5. After 2 days loki still hasn't scaled down and couple of pods still have very high memory consumption
==> kubectl top pods ==> 113% is the as is memory consumption
```
NAME         REFERENCE                TARGETS            MINPODS   MAXPODS   REPLICAS   AGE
loki-write   StatefulSet/loki-write   113%/60%, 2%/70%   4         6         6          4h21m
```
6. Logs of pod are throwing error:
```
level=info ts=2023-06-29T13:34:35.420523969Z caller=flush.go:168 msg="flushing stream" user=fake fp=63d40b2f203c4143 immediate=false num_chunks=1 labels="{app=\"Oliveprince\", format=\"rfc3164\", instance=\"vu6.BEG2N52LV45C\", namespace=\"out-of-the-box\", os=\"windows\"}"
level=error ts=2023-06-29T13:34:35.538513089Z caller=flush.go:144 org_id=fake msg="failed to flush" err="failed to flush chunks: store put chunk: write /var/loki/boltdb-shipper-active/loki_index_19537/1688045400: no space left on device, num_chunks: 1, labels: {app=\"Oliveprince\", format=\"rfc3164\", instance=\"vu6.BEG2N52LV45C\", namespace=\"out-of-the-box\", os=\"windows\"}"
```
7. When checking on those pods with high memory issue with kubectl exec -it loki-write-0 -- df -h , I see the that the local disk is full.
```
Filesystem                Size      Used Available Use% Mounted on
/dev/nvme2n1              9.7G      9.7G         0 100% /var/loki
```

**Expected behavior**
I would expect that loki will use the local storage as some sort of caching but it should flush all the chunks to S3.

**Environment:**
 - Infrastructure: EKS 1.27 with 4x m6g.XL worker nodes (can autoscale to 10 worker nodes)
 - Deployment tool: helm loki chart v 5.8.1

**Screenshots, Promtail config, or terminal output**
values.yaml for loki:
```
read:
    replicas: 3
    resources:
        requests:
            cpu: 1
            memory: 1Gi
    persistence:
        enableStatefulSetAutoDeletePVC: false

write:
    replicas: 4
    resources:
        requests:
            cpu: 1
            memory: 1Gi

    autoscaling:
        enabled: true
        minReplicas: 4
        maxReplicas: 6
        targetCPUUtilizationPercentage: 70
        targetMemoryUtilizationPercentage: 60
        behavior:
            # -- see https://github.com/grafana/loki/blob/main/docs/sources/operations/storage/wal.md#how-to-scale-updown for scaledown details
            scaleUp:
                policies:
                    - type: Pods
                      value: 1
                      periodSeconds: 180
            scaleDown:
                policies:
                    - type: Pods
                      value: 1
                      periodSeconds: 600
                stabilizationWindowSeconds: 600
    persistence:
        enableStatefulSetAutoDeletePVC: true

backend:
    replicas: 3
    persistence:
        enableStatefulSetAutoDeletePVC: false

loki:
    storage:
        type: s3
        s3:
            s3: s3://eu-west-1/${loki_bucket}
        bucketNames:
            admin: ${loki_bucket}
            chunks: ${loki_bucket}
            ruler: ${loki_bucket}

    auth_enabled: false

    limits_config:
        max_global_streams_per_user: 10000
        max_streams_per_user: 10000
        split_queries_by_interval: 24h
        reject_old_samples: false
        ingestion_rate_mb: 80
        ingestion_burst_size_mb: 100
        per_stream_rate_limit: 3MB
        per_stream_rate_limit_burst: 10MB
        max_query_parallelism: 90
        retention_period: 90d
    server:
        grpc_server_max_recv_msg_size: 8388608
        grpc_server_max_send_msg_size: 8388608
    compactor:
        retention_enabled: true

serviceAccount:
    create: true
    name: loki-sa
    annotations:
        eks.amazonaws.com/role-arn: ${loki_sa_role}

test:
    enabled: false

ingress:
    enabled: true
    ingressClassName: haproxy
    hosts:
        - my-loki-url.test.com

gateway:
    enabled: false

monitoring:
    dashboards:
        enabled: false
    rules:
        enabled: false
    serviceMonitor:
        enabled: false
    selfMonitoring:
        grafanaAgent:
            installOperator: false
    lokiCanary:
        enabled: false
```
kubectl top pods:
```
NAME                         CPU(cores)   MEMORY(bytes)   
grafana-57dcd57f98-c5cfd     1m           50Mi            
grafana-57dcd57f98-ck8rv     1m           49Mi            
loki-backend-0               7m           41Mi            
loki-backend-1               8m           45Mi            
loki-backend-2               9m           43Mi            
loki-read-749c56669d-2kd9x   7m           61Mi            
loki-read-749c56669d-gbqnj   8m           62Mi            
loki-read-749c56669d-xg4zn   7m           63Mi            
loki-write-0                 91m          1688Mi          
loki-write-1                 150m         1635Mi          
loki-write-2                 195m         1640Mi          
loki-write-3                 196m         1648Mi          
loki-write-4                 8m           238Mi           
loki-write-5                 10m          146Mi           
promtail-4rf4r               9m           42Mi            
promtail-4xqkl               3m           24Mi            
promtail-56ln9               5m           43Mi            
promtail-jv6s2               3m           22Mi            
promtail-kks4j               7m           47Mi            
promtail-vz65z               4m           44Mi 
```
==> loki-write-1 , 2 and 3 /var/loki on local disk has 0% free space and these are the pods throwing the error
```
Filesystem                Size      Used Available Use% Mounted on
/dev/nvme2n1              9.7G      9.7G         0 100% /var/loki
```
S3 bucket:
![loki-s3-bucket](https://github.com/grafana/loki/assets/25829454/26b7f6b8-c345-482e-9cb2-04f9fe365d23)

**Comment by MasslessParticle** [comment]
Loki writes index tables locally when it flushes chunks. When you run out of disk space, Loki can't write indexes anymore which also means it can't flush chunks anymore and the whole thing tips over.

What's the load test rate you're using? I'd only expect Loki to fall into this trap when there are way too few write nodes for the incoming traffic volume.

You'll probably also see better performance if you increase your write node resource requests. It's not uncommon for write nodes to use 10s of GiB of memory and several CPUS to do their work with non-trivial workloads.

Something else you can do is move to the TSDB index. It won't solve this but it's much smaller so the window where this can happen is smaller.

**Comment by imanAzi** [comment]
I was using K6 to load test, here a screenshot of the load test I performed that caused this issue:
![image](https://github.com/grafana/loki/assets/25829454/b04811ab-51be-4593-9943-098d752907b0)

I have 4 loki replicas set as minimum and it can scale to 6 and each pod getting 1CPU and 1Gi of memory. 

If I would increase the CPU and Memory requests, would the load on the local disk be lower? Is it going to do more in memory?

If I would increase my pods disk space to lets say 100 to 200 GB, the indexes that loki writes locally, will these also be written away to S3 and the drive will become empty again or do I need to increase the drive over time because the index will get larger and larger locally?

**Comment by imanAzi** [comment]
So basically, as suggested here, I changed the following configuration to make it work: 

- I made the autoscaling more aggressive (kick in at 50% memory load)
- I provided more request resources to the wright pods 
- Changed the schema to TSDB

The below configuration works for me, using EKS v1.27 with 4 m6g.XL worker nodes (can autoscale to 10) and Loki helm chart v5.8.7 in simple scalable mode + S3 backend
```
read:
    replicas: 3
    resources:
        requests:
            cpu: 1
            memory: 1Gi
    persistence:
        #This parameter is specific to Kubernetes StatefulSets, which are used in Loki for the write and backend components.
        #When set to true, it enables automatic deletion of the associated PersistentVolumeClaim (PVC) when the StatefulSet is deleted.
        enableStatefulSetAutoDeletePVC: true

write:
    resources:
        requests:
            cpu: 1
            memory: 4Gi

    autoscaling:
        enabled: true
        minReplicas: 4
        maxReplicas: 10
        targetCPUUtilizationPercentage: 70
        targetMemoryUtilizationPercentage: 45
        behavior:
            # -- see https://github.com/grafana/loki/blob/main/docs/sources/operations/storage/wal.md#how-to-scale-updown for scaledown details
            scaleUp:
                policies:
                    - type: Pods
                      value: 2
                      periodSeconds: 30
            scaleDown:
                policies:
                    - type: Pods
                      value: 1
                      periodSeconds: 300
                #This parameter defines a duration in seconds that specifies how long the system should wait after a scaling event before considering further scaling actions.
                #During this stabilization window, the system observes the impact of the scaling action and gives the cluster time to stabilize.
                stabilizationWindowSeconds: 300
    persistence:
        #This parameter is specific to Kubernetes StatefulSets, which are used in Loki for the write and backend components.
        #When set to true, it enables automatic deletion of the associated PersistentVolumeClaim (PVC) when the StatefulSet is deleted.
        enableStatefulSetAutoDeletePVC: true

backend:
    replicas: 3
    persistence:
        #This parameter is specific to Kubernetes StatefulSets, which are used in Loki for the write and backend components.
        #When set to true, it enables automatic deletion of the associated PersistentVolumeClaim (PVC) when the StatefulSet is deleted.
        enableStatefulSetAutoDeletePVC: true

loki:
    commonConfig:
        #In this configuration, any log streams sent to Loki will have the prefix /var/loki added to their names.
        #For instance, a log stream named app1 would become /var/loki/app1, app2 would become /var/loki/app2, and so on.
        path_prefix: /var/loki
        #the desired replication factor for log data. It determines the number of replicas that should be maintained for each log entry in order to achieve data redundancy and fault tolerance.
        replication_factor: 2

    #Wheter you want to enable authentication on Loki
    auth_enabled: false

    storage:
        bucketNames:
            #This configuration setting refers to the S3 bucket used for storing log chunks in Loki.
            #Log chunks contain the actual log data that is ingested and stored in Loki.
            chunks: ${loki_bucket}
            #This configuration setting refers to the S3 bucket used for storing administrative data related to Loki.
            #Administrative data can include indexes, metadata, or other internal data used by Loki for managing and organizing log entries.
            admin: ${loki_bucket}
            #This configuration setting refers to the S3 bucket used for storing data related to the Loki ruler component.
            #Loki ruler is a component that enables alerting and querying of log data in Loki.
            ruler: ${loki_bucket}
        type: s3

    #Cofngiraution of the indexing system based on Time Series Data Base (tsdb)
    schema_config:
        configs:
            - from: "2022-01-12"
              index:
                  period: 24h
                  prefix: loki_index_
              store: tsdb
              object_store: s3
              schema: v12

    storage_config:
        aws:
            s3: s3://eu-west-1/${loki_bucket}
            #This parameter controls whether to use a secure (HTTPS) connection when communicating with the S3 service if set true.
            insecure: false
            #This parameter controls whether to use path-style URLs when accessing S3 objects.
            #When set to false: Virtual hosted-style URLs include the bucket name as part of the hostname, like https://bucket-name.s3.amazonaws.com/object-key.
            #This style is the default and is generally recommended for new S3 deployments.
            s3forcepathstyle: false
        tsdb_shipper:
            #specifies the directory path where the active index files for the TSDB shipper are stored.
            active_index_directory: /var/loki/index
            #The TSDB shipper will utilize S3 as the shared storage to store the log data.
            shared_store: s3

    limits_config:
        #How many MB/s of data the ingestor will consume, the higher the number the higher the memory consumption
        ingestion_rate_mb: 40
        #How many MB/s of data the ingestor can burst to
        ingestion_burst_size_mb: 80
        #How many MB/s of data the ingestor will consume per stream, the higher the number the higher the memory consumption
        per_stream_rate_limit: 3MB
        #How many MB/s of data the ingestor will burst per stream, the higher the number the higher the memory consumption
        per_stream_rate_limit_burst: 10MB
        #Determines the maximum number of concurrent queries that Loki can execute in parallel
        #By adjusting the value of max_query_parallelism, you can optimize the trade-off between query throughput and resource consumption.
        #A higher value allows for more concurrent queries to be processed simultaneously, which can increase query throughput but may also consume more system resources, such as CPU and memory.
        max_query_parallelism: 90
        #The retention period of chunks in the backend storage (s3)
        retention_period: 90d

    server:
        #This sets the maximum size (in bytes) for incoming gRPC messages that Loki's server can receive.
        #If an incoming message exceeds the specified maximum size, the Loki server will reject or terminate the connection.
        #Increasing the value of grpc_server_max_recv_msg_size allows larger messages to be received by the server, accommodating scenarios where large log payloads or other data need to be transmitted.
        grpc_server_max_recv_msg_size: 8388608
        #This parameter sets the maximum size (in bytes) for outgoing gRPC messages that Loki's server can send.
        grpc_server_max_send_msg_size: 8388608

    compactor:
        #By enabling retention during compaction, Loki ensures that log data that exceeds the configured retention period is appropriately handled and removed from the backend storage.
        #This helps to maintain compliance with the desired data retention policies and prevents unnecessary storage usage
        retention_enabled: true

serviceAccount:
    create: true
    name: loki-sa
    annotations:
        eks.amazonaws.com/role-arn: ${loki_sa_role}

test:
    enabled: false

ingress:
    enabled: true
    ingressClassName: haproxy
    hosts:
        - loki.prod.cloud
        - loki.nonprod..cloud

gateway:
    enabled: false

monitoring:
    dashboards:
        enabled: false
    rules:
        enabled: false
    serviceMonitor:
        enabled: false
    selfMonitoring:
        grafanaAgent:
            installOperator: false
    lokiCanary:
        enabled: false
```
