### ISSUE TITLE
Period config activated ahead of its from date

### ISSUE THREAD

**Issue by mac133k** [grafana/loki#9837]
**Describe the bug**
I was testing the storage config where a number of periods were specified to use a new S3 bucket after every 2 days:

```
schema_config:
  configs:
  - chunks:
      prefix: chunk_
    from: '2022-01-01'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20220101
    schema: v11
    store: boltdb-shipper
  - chunks:
      prefix: chunk_
    from: '2023-05-11'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20230511
    row_shards: 64
    schema: v12
    store: boltdb-shipper
  - chunks:
      prefix: chunk_
    from: '2023-06-08'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20230608
    schema: v12
    store: tsdb
  - chunks:
      prefix: chunk_
    from: '2023-07-01'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20230701
    schema: v12
    store: tsdb
  - chunks:
      prefix: chunk_
    from: '2023-07-03'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20230703
    schema: v12
    store: tsdb
  - chunks:
      prefix: chunk_
    from: '2023-07-05'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20230705
    schema: v12
    store: tsdb
  - chunks:
      prefix: chunk_
    from: '2023-07-07'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20230707
    schema: v12
    store: tsdb
  - chunks:
      prefix: chunk_
    from: '2023-07-09'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20230709
    schema: v12
    store: tsdb
  - chunks:
      prefix: chunk_
    from: '2023-07-11'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20230711
    schema: v12
    store: tsdb
  - chunks:
      prefix: chunk_
    from: '2023-07-13'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20230713
    schema: v12
    store: tsdb
  - chunks:
      prefix: chunk_
    from: '2023-07-15'
    index:
      period: 24h
      prefix: index_
    object_store: cceph-20230715
    schema: v12
    store: tsdb
storage_config:
  boltdb_shipper:
    active_index_directory: /data1/loki/boltdb
    cache_location: /data1/loki/boltdb-cache
    cache_ttl: 24h
    index_gateway_client:
      grpc_client_config:
        tls_ca_path: /etc/loki/ca.crt
        tls_cert_path: /etc/loki/client.crt
        tls_enabled: true
        tls_key_path: /etc/loki/client.key
      log_gateway_requests: true
      server_address: igw2-loki.devdomain.net:9095
    query_ready_num_days: 1
  named_stores:
    aws:
      cceph-20220101:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
      cceph-20230511:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
      cceph-20230608:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
      cceph-20230701:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs-1
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
      cceph-20230703:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs-2
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
      cceph-20230705:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs-3
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
      cceph-20230707:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs-4
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
      cceph-20230709:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs-5
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
      cceph-20230711:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs-6
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
      cceph-20230713:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs-7
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
      cceph-20230715:
        access_key_id: kkv5JZnR88LwPdRKNlNt80JmDpakDNHNKDaBSvz7
        bucketnames: loki-logs-8
        endpoint: ceph.devdomain.net:9000
        http_config:
          idle_conn_timeout: 10m
        s3forcepathstyle: true
        secret_access_key: qK3JTwuh5Upy3AXQXc2v4yRVnOEnIid01gZfrum8
        signature_version: v4
        storage_class: STANDARD
  tsdb_shipper:
    active_index_directory: /data1/loki/tsdb-index
    cache_location: /data1/loki/tsdb-cache
    cache_ttl: 24h
    index_gateway_client:
      grpc_client_config:
        tls_ca_path: /etc/loki/ca.crt
        tls_cert_path: /etc/loki/client.crt
        tls_enabled: true
        tls_key_path: /etc/loki/client.key
      log_gateway_requests: true
      server_address: igw3-loki.devdomain.net:9095
    query_ready_num_days: 1
```

As you can see I used named store configs to specify the configuration for every period. There were 3 pre-existing period configs all using the same bucket called loki-logs. The buckets loki-logs-[1:8] were supposed to be used starting from July 1, 2023, but after the new config was rolled out and every host in cluster restarted on June 29, 2023, the bucket called loki-logs-8 was started being used alongside with the existing loki-logs even though it was the last one on the schedule and not supposed to be used until July 15, 2023. This bucket has index folder with a few index_* sub-folders that contain *.tsdb.gz files from all active ingesters.

**To Reproduce**
1. Update Loki storage config.
2. Restart Loki on all hosts.

**Expected behavior**
The expected behaviour is to have each period config active starting from its assigned date.

**Environment:**
 - Infrastructure: Microservice mode deployed to Linux VMs.

**Screenshots, Promtail config, or terminal output**
Not sure where to look for clues, please ask for specific debug info and I will provide.
