### ISSUE TITLE
Loki read returning always empty ring

### ISSUE THREAD

**Issue by yuriolisa** [grafana/loki#9839]
**Describe the bug**

After deploying Loki Chart, the loki-read pod is returning `empty ring` to the following curl: 
````bash
curl 'http://localhost:3100/loki/api/v1/label/host/values'
````

**To Reproduce**
1. Deploy the helm chart loki version : 5.8.8, with the following values.yaml: 
````yaml
loki:
  fullnameOverride: loki
  monitoring:
    lokiCanary:
      enabled: false
    selfMonitoring:
      grafanaAgent:
        installOperator: false
  querySchedulerAddress: query-scheduler-discovery.<namespace>.svc.cluster.local:9095
  test:
    enabled: false
  memberlist:
    service:
      publishNotReadyAddresses: true
  read:
    replicas: 1
  write:
    replicas: 1
  backend:
    replicas: 1
  loki:
    auth_enabled: false
    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    memberlistConfig:
      bind_addr: ['0.0.0.0']
      bind_port: 7946
      dead_node_reclaim_time: 30s
      gossip_interval: 2s
      gossip_to_dead_nodes_time: 15s
      left_ingesters_timeout: 30s
      join_members:
        - loki-memberlist.<namespace>.svc.cluster.local:7946
    storage:
      type: s3
      s3:
        endpoint: <endpoint>
        region: <region>
        secretAccessKey: <secretAccessKey>
        accessKeyId: <accessKeyId>
        s3ForcePathStyle: true
    storage_config:
      boltdb_shipper:
        shared_store: s3
      aws:
        s3: <s3-endpoint>
        s3forcepathstyle: true
    compactor:
       shared_store: s3
       compaction_interval: 5m
  minio:
    enabled: false
````
3. Open a port-forward against the loki-read service.

4. Run the curl command: 

````bash
curl 'http://localhost:3100/loki/api/v1/label/host/values'
````

**Expected behavior**
See the labels values.

**Environment:**
 - Infrastructure: [Kubernetes 1.26]
 - Deployment tool: [helm]

**Screenshots, Promtail config, or terminal output**
