### ISSUE TITLE
allow to configure GCS subpath (bucket prefix configuration) 

### ISSUE THREAD

**Issue by suranga-nisiwasala** [grafana/loki#9840]
Is your feature request related to a problem? Please describe.

Currently a full GCS (Google Cloud Storage) bucket is required for Loki - however, in some situations a bucket may need to be shared with other use cases.

Describe the solution you'd like

Ability to specify a folder where all Loki data will be stored in a bucket

Thank you.

**Comment by suryastef** [comment]
I know this is old discussion, but this can be achieved using:

```yaml
storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
  gcs:
    bucket_name: your-bucket-name
  object_prefix: your/custom/dir/
```

according to original [docs](https://grafana.com/docs/loki/latest/configure/#storage_config)
