### ISSUE TITLE
Helm chart: LokiCanary can not be disabled, validation fails

### ISSUE THREAD

**Issue by epleterte** [grafana/loki#9849]
**Describe the bug**
When installing Loki with the Helm chart, setting

_monitoring.lokiCanary.enabled_ to _false_

results in an error when I try to render the template (with _helm template_):

`Error: execution error at (loki/templates/validate.yaml:10:4): Helm test requires the Loki Canary to be enabled
helm.go:84: [debug] execution error at (loki/templates/validate.yaml:10:4): Helm test requires the Loki Canary to be enabled`

**To Reproduce**
1. Run `helm template --debug --namespace loki --set monitoring.lokiCanary.enabled=false loki grafana/loki`

**Expected behavior**
Rendered template w/o warnings and errors, validation should exclude the Loki Canary test when Loki Canary is disabled

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**

**Comment by PhilippWitzmann** [comment]
In your values.yaml, set test.enabled to false

**Comment by JStickler** [comment]
@epleterte Were you able to implement PhilippWitzmann's suggestion?

**Comment by Raclaw-jl** [comment]
I tried disabling it (chart version 5.41.4) by setting `test.enabled` to `false` but it's still deploying for me. My values look like this so far:
```
        test:
          enabled: false

        ################################################################################
        ## Monitoring
        ################################################################################
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
            lokiCanary:
              enabled: false
```

**Comment by leonharetd** [comment]
test:
          enabled: false
        lokiCanary:
          enabled: false

work great！！

**Comment by iby-dev** [comment]
This appears to still be broken on loki v`3.5.0`.


My example test config in my `values.yaml` file looks like so:

```yaml
# other values file config here ....

loki:
  deploymentMode: SimpleScalable

  # Disable monitoring to avoid GrafanaAgent CRD issues
  monitoring:
    lokiCanary:
      enabled: false
    enabled: false
    dashboards:
      enabled: false
    rules:
      enabled: false
    serviceMonitor:
      enabled: false
    selfMonitoring:
      enabled: false
      grafanaAgent:
        installOperator: false

  test:
    enabled: false
  lokiCanary:
    enabled: false

  # Core Loki configuration
  loki:
    auth_enabled: false
    server:
      http_listen_port: 3100

  # other loki specific config continues here ....
```

It would also be useful to confirm if the above `double` nesting of `loki` config properties and values is legal too.
