### ISSUE TITLE
Promtail doesn't set default value on `follow_redirects` and `enable_http2` correctly

### ISSUE THREAD

**Issue by thampiotr** [grafana/loki#9856]
**Describe the bug**
Promtails clients configuration of `follow_redirects` and `enable_http2` are not set to their default values as documented in https://grafana.com/docs/loki/latest/clients/promtail/configuration/#clients.

**To Reproduce**
1. Use a promtail config file, e.g.
```
clients:
  - external_labels:
      cluster: backyard-pine-treehouse-1
    url: http://localhost/loki/api/v1/push

```
2. Start promtail with e.g. `promtail -print-config-stderr -config.file ./<the file from above>`
3. See that the default values for `follow_redirects` and `enable_http2` were not set in the output:
```
clients:
- url: http://localhost/loki/api/v1/push
  batchwait: 1s
  batchsize: 1048576
  follow_redirects: false
  enable_http2: false
  backoff_config:
    min_period: 500ms
    max_period: 5m0s
    max_retries: 10
  external_labels: |
    cluster: backyard-pine-treehouse-1
  timeout: 10s
  tenant_id: ""
  drop_rate_limited_batches: false
  stream_lag_labels: ""
```
**Expected behavior**
The `follow_redirects` and `enable_http2` should both be `true` as described in docs https://grafana.com/docs/loki/latest/clients/promtail/configuration/#clients

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: none

**Screenshots, Promtail config, or terminal output**
Provided above
