### ISSUE TITLE
entry too far behind, oldest acceptable timestamp is....

### ISSUE THREAD

**Issue by adeturner** [grafana/loki#9869]
**Describe the bug**

It is a challenge being unable to disable/ignore this error:

ts=2023-07-05T15:03:41.962613339Z component=loki.write.local level=error component=client host=loki msg="final error sending batch" status=400 error="server returned HTTP status 400 Bad Request (400): entry with timestamp 2023-07-02 05:47:13.434495881 +0000 UTC ignored, reason: 'entry too far behind, oldest acceptable timestamp is: 2023-07-05T14:03:33Z' for stream: {....}"

This is occurring with several app server syslogs. The issue is compounded by Grafana Agent is writing the error to the syslog and then failing to send its own messages!  The machine is slow and it doesn't catch up. Its also consuming 2GB per day of storage space in this cycle.

**To Reproduce**

Loki downtime (due to firewall in this case I suspect)

**Expected behavior**

It seems to me that per #5936 and #9355 it would be useful if Loki respected limits_config, or something like it.

Specifically there does not appear to be an override that allows users to discard old log entries >max_chunk_time/2

**Screenshots, Promtail config, or terminal output**

n/a

**Comment by adeturner** [comment]
I can confirm that #9877 is the same issue. I can I see get this on other VMs with promtail/syslog for no reason.  My promtail config below

```
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${loki_url}
    external_labels:
        ops_env: ${domain}
        ops_name: ${hostname}
        ops_type: vm
        ops_remotewriter: promtail
        ops_scope: os_linux

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
```
