### ISSUE TITLE
Promtail never scrapes `journal` logs (using README suggestions in official helm chart)

### ISSUE THREAD

**Issue by fzyzcjy** [grafana/loki#9922]
**Describe the bug**
Hi thanks for Loki, but I fail to use it to get journald logs.

**To Reproduce**
1. Started Loki (SHA or version): 2.8.2
2. Started Promtail (SHA or version): 2.8.2
3. it does not handle journal logs at all

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop] k8s
 - Deployment tool: [e.g., helm, jsonnet] helm

**Screenshots, Promtail config, or terminal output**

I use the official promtail helm chart, and deliberately disabled the original section and only remain the journalctl section that I added, in order to show it more clearly.

helm values:

```yaml
config:
  snippets:
    # #10154, https://github.com/grafana/helm-charts/blob/main/charts/promtail/README.md#journald-support
    extraScrapeConfigs: |
      # Add an additional scrape config for syslog
      - job_name: journal
        journal:
          path: /var/log/journal
          max_age: 12h
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels:
              - __journal__hostname
            target_label: hostname

          # example label values: kubelet.service, containerd.service
          - source_labels:
              - __journal__systemd_unit
            target_label: unit

          # example label values: debug, notice, info, warning, error
          - source_labels:
              - __journal_priority_keyword
            target_label: level

# Mount journal directory and machine-id file into promtail pods
extraVolumes:
  # #10154, https://github.com/grafana/helm-charts/blob/main/charts/promtail/README.md#journald-support
  - name: journal
    hostPath:
      path: /var/log/journal
  - name: machine-id
    hostPath:
      path: /etc/machine-id

extraVolumeMounts:
  # #10154, https://github.com/grafana/helm-charts/blob/main/charts/promtail/README.md#journald-support
  - name: journal
    mountPath: /var/log/journal
    readOnly: true
  - name: machine-id
    mountPath: /etc/machine-id
    readOnly: true
```

config when `cat` inside the container (DaemonSet pod):

```yaml
root@promtail-7mtbh:/# cat /etc/promtail/promtail.yaml
server:
  log_level: info
  http_listen_port: 3101
  

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /run/promtail/positions.yaml

scrape_configs:
  
  # Add an additional scrape config for syslog
  - job_name: journal
    journal:
      path: /var/log/journal
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels:
          - __journal__hostname
        target_label: hostname
  
      # example label values: kubelet.service, containerd.service
      - source_labels:
          - __journal__systemd_unit
        target_label: unit
  
      # example label values: debug, notice, info, warning, error
      - source_labels:
          - __journal_priority_keyword
        target_label: level
  

limits_config:
  

tracing:
  enabled: false
root@promtail-7mtbh:/# 
```

promtail logs, when level=debug

```
level=debug ts=2023-07-12T14:05:32.163270151Z caller=promtail.go:125 msg="Reloading configuration file"
level=info ts=2023-07-12T14:05:32.164971302Z caller=promtail.go:133 msg="Reloading configuration file" md5sum=979bfe7c7e37b5cb2aaee0a6ada862ed
level=info ts=2023-07-12T14:05:32.172243698Z caller=server.go:323 http=[::]:3101 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2023-07-12T14:05:32.172409725Z caller=main.go:174 msg="Starting Promtail" version="(version=2.8.2, branch=HEAD, revision=9f809eda7)"
level=warn ts=2023-07-12T14:05:32.172441948Z caller=promtail.go:265 msg="enable watchConfig"
level=debug ts=2023-07-12T14:05:41.417964184Z caller=logging.go:76 msg="GET /ready (200) 52.01µs"
level=debug ts=2023-07-12T14:05:41.418061331Z caller=logging.go:76 msg="GET /ready (200) 142.741µs"
level=debug ts=2023-07-12T14:05:42.385697851Z caller=logging.go:76 msg="GET /metrics (200) 1.833019ms"
```

systemctl version

```
systemctl --version
systemd 249 (249.11-0ubuntu3.6)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
```

**Comment by jseiser** [comment]
We are having the same exact issue.  Promtail Helm Chart, running as a Daemonset in AWS EKS.

here is a config mounted from a pod
```
root@promtail-6kg64:~# cat /etc/promtail/promtail.yaml 
server:
  log_level: info
  log_format: json
  http_listen_port: 3101
  

clients:
  - url: http://loki-gateway.loki/loki/api/v1/push

positions:
  filename: /run/promtail/positions.yaml

scrape_configs:
  # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
  - job_name: kubernetes-pods
    pipeline_stages:
      - cri: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels:
          - __meta_kubernetes_pod_controller_name
        regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
        action: replace
        target_label: __tmp_controller_name
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_name
          - __meta_kubernetes_pod_label_app
          - __tmp_controller_name
          - __meta_kubernetes_pod_name
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: app
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_instance
          - __meta_kubernetes_pod_label_instance
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: instance
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_component
          - __meta_kubernetes_pod_label_component
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: component
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - namespace
        - app
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        regex: true/(.*)
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
        - __meta_kubernetes_pod_container_name
        target_label: __path__
  
  - job_name: journal
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      matches: _SYSTEMD_UNIT=kubelet.service _SYSTEMD_UNIT=containerd.service
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'
      - source_labels: ['__journal_priority_keyword']
        target_label: level
  

limits_config:
  

tracing:
  enabled: false
```

The journal is mounted

```
root@promtail-6kg64:~# ls -lah /var/log/journal/
total 16K
drwxr-sr-x. 3 root  983 4.0K Aug 24 20:58 .
drwxr-xr-x. 1 root root 4.0K Aug 29 14:59 ..
drwxr-sr-x. 2 root  983 4.0K Aug 29 05:39 ec2e7fb9a81f32c7fc85d7f6a6d54e1d
```

The Machine ID is mounted

```
root@promtail-6kg64:~# cat /etc/machine-id 
ec2e7fb9a81f32c7fc85d7f6a6d54e1d
```

There is not a single log relating to journal.

```
❯ kubectl logs pod/promtail-6kg64 -n promtail -c promtail | jq ".msg" | rg journal

```

**Comment by jseiser** [comment]
Not that its entirely relevant, but on the same nodes, we have to run fluentbit to ship logs to cloudwatch for a regulatory compliance issue, and we are able to get journal logs from there.

```
{
    "hostname": "i-0b718733d59f3540f.us-gov-west-1.compute.internal",
    "systemd_unit": "kubelet.service",
    "message": "I0829 15:00:22.032021    1306 operation_generator.go:878] UnmountVolume.TearDown succeeded for volume \"kubernetes.io/secret/8991a7ad-08dc-4c6d-91e2-e96374a43699-config\" (OuterVolumeSpecName: \"config\") pod \"8991a7ad-08dc-4c6d-91e2-e96374a43699\" (UID: \"8991a7ad-08dc-4c6d-91e2-e96374a43699\"). InnerVolumeSpecName \"config\". PluginName \"kubernetes.io/secret\", VolumeGidValue \"\""
}
```

So the nodes themselves obviously have a working journal, and fluent-bit behaves pretty similar, where you mount journal and machine-id, and configure an input

```
    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Systemd_Filter _SYSTEMD_UNIT=docker.service
        Systemd_Filter _SYSTEMD_UNIT=containerd.service
        Read_From_Tail On
```

**Comment by jseiser** [comment]
```
config:
  clients:
    - url: http://loki-gateway.loki/loki/api/v1/push
  logFormat: json
  snippets:
    extraScrapeConfigs: |
      - job_name: journal
        journal:
          json: false
          max_age: 12h
          path: /var/log/journal
          matches: _SYSTEMD_UNIT=kubelet.service _SYSTEMD_UNIT=containerd.service
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'
          - source_labels: ['__journal__hostname']
            target_label: 'hostname'
          - source_labels: ['__journal_priority_keyword']
            target_label: level

extraVolumes:
  - name: journal
    hostPath:
      path: /var/log/journal
  - name: machine-id
    hostPath:
      path: /etc/machine-id

extraVolumeMounts:
  - name: journal
    mountPath: /var/log/journal
    readOnly: true
  - name: machine-id
    mountPath: /etc/machine-id
    readOnly: true
```

**Comment by n9** [comment]
Same issue here:
> systemd 252 (252.17-1~deb12u1)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

Promtail logs with debug level:
```
level=debug ts=2023-10-11T10:58:01.879042803Z caller=promtail.go:125 msg="Reloading configuration file"
level=info ts=2023-10-11T10:58:01.879925531Z caller=promtail.go:133 msg="Reloading configuration file" md5sum=2084a20bac6ea0eced0eb867fd583d64
level=info ts=2023-10-11T10:58:01.909401697Z caller=server.go:323 http=[::]:3101 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2023-10-11T10:58:01.909671648Z caller=main.go:174 msg="Starting Promtail" version="(version=2.8.4, branch=HEAD, revision=89d282c43)"
level=warn ts=2023-10-11T10:58:01.909693615Z caller=promtail.go:265 msg="enable watchConfig"
level=debug ts=2023-10-11T10:58:02.388970497Z caller=logging.go:76 traceID=18d428143023c727 msg="GET /ready (200) 74.177µs"
```

**Comment by n9** [comment]
@fzyzcjy Have you found a solution?

**Comment by fzyzcjy** [comment]
No, I finally gave up loki...

**Comment by weixiaolv** [comment]
grafana-agent does not have access to systemd-journal . try to use the system-unit user run journalctl.

```sh
sudo -u promtail journalctl -f
```

**Comment by klzsysy** [comment]
I successfully collected it after adding the path. It seems that the default value does not work.

image: promtail:2.9.6

```yaml
   - job_name: journal
      journal:
          path: /var/log/journal
```
