### ISSUE TITLE
Fix docs: promtail configuration: mention the correct use of <labelname>

### ISSUE THREAD

**Issue by dapeleg-dn** [grafana/loki#9928]
**Describe the bug**

In Promtail configuration, when using labels, it's not clearly mentioned that the label name must be a valid regular expression `[a-zA-Z_][a-zA-Z0-9_]*`. And that any special character needs to be converted to an underscore.

See a probably related bug: https://github.com/grafana/loki/issues/9113
See this bug + fix in the Prometheus project: https://github.com/prometheus/docs/issues/735

**To Reproduce**
Try using the following scrape config:

```
scrape_configs:

- job_name: docker

  docker_sd_configs:
    - host: unix:///var/run/docker.sock
  
  # See: https://grafana.com/docs/loki/latest/clients/promtail/configuration/
  relabel_configs:
    - source_labels: ['__meta_docker_container_id']
      regex: '(.*)'
      target_label: 'container_id'
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container_name'
    - source_labels: ['__meta_docker_container_log_stream']
      regex: '(.*)'
      target_label: 'container_log_stream'
    - source_labels: ['__meta_docker_network_ip']
      regex: '(.*)'
      target_label: 'container_ip'
    - source_labels: ['__meta_docker_container_label_com.docker.swarm.service.name']
      regex: '/(.*)'
      target_label: 'app'
```

**Expected behavior**
The docker label should be taken and injected into Loki.
But you get a runtime error when trying to start Promtail, telling you that the configuration is invalid. 

The solution is to convert any special character (dashes, dot, slashes) to underscores, and specifically here to: `__meta_docker_container_label_com_docker_swarm_service_name`

**Environment:**
Docker Swarm, but the same is probably true for Kubernetes, and every other place that "\<labelname\>" is being used.

**Screenshots, Promtail config, or terminal output**
See above.
