### ISSUE TITLE
Distributer Ring Status does not show Availability Zone

### ISSUE THREAD

**Issue by sky-philipalmeida** [grafana/loki#9970]
**Describe the bug**
Distributer Ring Status does not show Availability Zone.
This happens even if the below configuration is present:
```
    common:
      ring:
        instance_availability_zone: hhe
        zone_awareness_enabled: true
```
This can be view in http://localhost:3100/distributor/ring

**To Reproduce**
1. Started Loki (SHA or version)
2. Configure Availability zone_awareness_enabled to true and set instance_availability_zone

**Expected behavior**
The ui, http://localhost:3100/distributor/ring will not show the distributer availability zone.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
